### ISSUE TITLE
Cybernetic Augmentations (Advanced limbs) 

### ISSUE THREAD

**Issue by Lorkhatosh** [d3athrow/vgstation13#10022]
When Nexis first announced Deus Ex update I was hype as fuck, and lungs/advanced eyes upgrade was neat but I heard that there would be more and hoped that it would eventually happen...it did not.

My main issue with no actual augmentations is the fact that genetics with a lot less effort and resources gets actual super powers, while science has little to offer in terms of bodily augmentations in a world where they should exist.

I suggest Goon like "modular borg" system to create augmentations. Obviously to balance stuff out they would be really high research/high material cost items. 

So RD does a lot of research and Roboticist gets "Augmentations" tab. In there he gets different parts to assemble augmentations. For example how I imagine limbs would work:

> Modular Limb Chassis  
> Modular Limb Hull
> Modular Limb thingy that gives it it's augmentation advantages 

There would be multiple parts in each of these, like:

> Limb Chassis: Left hand, right hand, left leg, right leg
> Limb Hull: electricity resistant so you can't get shocked, emp protection laced so that said limb would get affected by EMP damage less, ROBUST hull that generally has more damage resistance 
> Thing that gives powers: Modular tool-hand (A hand that would have UI button similar to borg UI over said hands icon, so you click that button and something like an inventory comes out, when you click one of the tools in the inventory the hand turns into that tool), ROBUST module (Just makes you really strong, not Hulk strong but it should do damage comparable to a toolbox or something), SANIC module (gotta go fast), Magnetic feet module (no need for magboots with these) etc.

Roboticist would do something like this:

> Roboticist prints out Modular left hand Chassis
> Roboticist prints out Modular electricity resistant Hull
> Roboticist prints out Modular tool-hand (A hand that would have UI button similar to borg UI over said hands icon, so you click that button and something like an inventory comes out, when you click one of the tools in the inventory the hand turns into that tool)
> He assembles these parts and he gets electricity resistant hand that has all of the tools inside of it, perfect augmentation for engies. 

It would also be possible to revamp eyes and lungs in the same way. I can't think of anything for lungs but still it would allow for future features.

> Eye Chasis
> Eye Module (Sechud, medhud etc.) 

And of course there should be illegal research like Chainsaw hands and Lubespray feet(Legs that leave a trail of lube behind you once loaded with lube )

I just think that cybernetic augmentations would add a lot to "to do" list of scientists, give everyone some new toys to play around with and generally add to the feeling of FUTURE. I am actually surprised that this is not a more requested thing.
Most importantly the modular design of the limbs would allow to easily tweak each of the different parts and easily add new limb parts.

**Comment by Lorkhatosh** [comment]
This is basically a pure "idea" tier shit right now but if anything thinks that it's worth doing tell me because if someone will attempt to do this thing I am willing to do what Cluster suggested and put this issue up on Bountysource, as in you will get paid once the feature is finished.

**Comment by Lorkhatosh** [comment]
I will try to set up bounty source for this request.

**Comment by Shadowmech88** [comment]
I'd like more in-depth prosthetics as well, but prosthetic functions would require messing with mob code, and mob code is messy.

**Comment by ghost** [comment]
Was kinda hoping for this as well

> 3-4 tiers of upgrade, ranging from the default with no module slots, to military-grade that you'd only find from vaults/away missions and on deathsquad
> Upgrades for organs, internal and external (Strength upgrades on external limbs increases the damage dealt by them, up to punching and kicking through walls)
> More specific upgrades like an augment for the heart that attempts a defibrillation after a certain time, or maybe deploy mednanobots or combatnanobots if the host is in a pickle

Maybe even have passive and active upgrades, with active upgrades requiring power from an internal cell (Perhaps located in the heart to be cliche)

#7627

**Comment by Lorkhatosh** [comment]
Yep, though I think at first limb augments have to come and that will eventually cause more organ augmentations.

**Comment by Lorkhatosh** [comment]
Also that one guy in the issue you made does have a point, limbs getting really damaged and fucked/blowing off should be easier for there to be actual demand on robotic limbs.

**Comment by ghost** [comment]
Here's the thing, would you need a new surgery type to apply upgrades to a limb (Akin to cavity surgery, but with more cables and screwdrivers as you connect it all up) or would you have to take the limb off, apply the upgrades, then put it back on the patient?

How about both, with an additional upgrade-bed that'll apply the upgrades to a person that climbs inside for some self service/

**Comment by Lorkhatosh** [comment]
Nah, I think it's a lot easier for it to be just a limb replacement surgery.
You create a new augmented limb, remove old/damaged limb, attach new one.

**Comment by icantthinkofanameritenow** [comment]
Another thing: with stuff that strong, shouldn't they have equally big drawbacks? Right now cyborg limbs aren't OP enough for everyone to go and get, but offering something upgradeable that can minimize the main weaknesses of robotic limbs while simultaneously emulating the effect of various useful items would make it so there would be absolutely no reason not to get them. 

To use your example with genetics, you have to deal with disabilities if you want to get superpowers. Why should this be different? Material costs alone are an absolute joke in most cases, and research requirements are completely irrelevant within the first 10 minutes of any given round. They need equally big disadvantages (e.g. for the tool hand, you can no longer pick up regular items with that hand).

**Comment by Imagebard** [comment]
>shouldn't they have equally big drawbacks?

-You're totaled if you're hit by a EMP
-They occasionally drop items if they've been damaged.
-Also, they explode when damaged

**Comment by icantthinkofanameritenow** [comment]
@Imagebard

Did you miss the part where one of the modifications proposed was EMP-proofing?

**Comment by Imagebard** [comment]
That removes 1 drawback, and you can add a different downside to go with it.

**Comment by icantthinkofanameritenow** [comment]
@Imagebard
Like what? The other things you listed apply to all robotic limbs, and by definition some of the upgrades would make said limbs very difficult to damage to the point those downsides would be a complete nonissue. It has to be something major enough to make someone really consider whether or not one of these augmentations would be a good idea.

**Comment by Lorkhatosh** [comment]
What disabilities are you talking about? You get disabilities for a second, then you reset your SE and it's done.
You said "Disabilities" as if it's a necessary part of using powers when it's clearly not.
When geneticist finishes his work he has clean cut superpowers with no drawbacks.

**Comment by Imagebard** [comment]
>Like what?

Really, just use your imagination to balance it. You talk as if this is already coded.

>Bio-tech arm
+Immune to EMPs
-Damage to the arm connects to the rest of your body like usual, instead of being contained to the robot arm.

**Comment by Lorkhatosh** [comment]
There are no downsides to genetic powers, nill, zero, nothing.
Plus EMP shielding does not remove EMP damage, it reduces it, and if you have EMP shielding you used up a slot that could be used for some other hull upgrade.
Plus what I listed is not something concrete, they are suggestions. I am literally suggesting stronger researchable modular limbs.

**Comment by icantthinkofanameritenow** [comment]
@Lorkhatosh 
Aren't you forgetting the massive amount of randomness that even getting a power entails (which can take a geneticist hours to fully finish), and that even when you've modified the right gene it can take dozens of injectors to make the damn thing work if you're unlucky? Not to mention the existence of disabilities that can be triggered by the very same gene as a power can. It's rare, but it happens enough to notice. 

Stronger limbs, I understand. But you're going to the wrong extreme, judging by your examples. With those, there would be no reason at all not to upgrade them, and we really don't need to give people more reasons to powergame than we already do.

Consider stuff like this: for the speedy foot module, make all slips act as if you were slipped by space lube. Or the increased damage resistance module having less "health" than a regular arm, so whatever damage it doesn't resist will be that much more important to deal with. Every one of these  modules has to have an equal and opposite downside, so that there costs that can act as a counterpoint to their benefits.

**Comment by Lorkhatosh** [comment]
What hours are you talking about? Geneticist can get all the fucking powers in an hour with extremely bad luck.
Also what you are describing is the process of getting said item, you can still have the powers with zero fucking drawbacks what so ever. 
Regardless of "research" being a joke or not maxing research still takes time, especially research that needs fucking high-end materials. 
Also sure, these counterpoints make sense but as long as they are reasonable. I mean the limbs still have to fucking benefit you at least somehow.
I still don't understand your problem with some of the limbs like the one that has tools though, there is shit like surgeons switchtool already, why would an aug like this have a downside?

**Comment by Lorkhatosh** [comment]
Plus imagine this.
Research has to get to the level of the limb first, then they have to produce the parts to make the limbs AND then people should be willing to chop of their current limbs and get new limbs that are extremely affected by EMP even if shielding upgrade is installed.
Even with highest tier materials readily available you never EVER see more than two Durands, and Durands are way more benefitial and robust than any limb aug that I've described. 

You are imagining it all wrong if you think that suddenly everyone will get the augmentations one minute into the round. If augs like that are implemented they will still be a shift end thing and most likely will be handed out to one or two guys, and that's just one fucking limb. Unless science is miraculously really efficient and Mining are not shitters, but when a department is really efficient you get shit like "All power injectors" and "Pill that makes you immortal" anyway.

**Comment by icantthinkofanameritenow** [comment]
@Lorkhatosh 
The same reason that cyborgs can't pick up and drop items, 

 I'm not denying they have to benefit you, I just would prefer that the benefit comes with strings attached so every asshole tries to get them ASAP. It's a recipe for powergaming of the worst kind, and your enthusiasm doesn't take into account how quickly people are to seize on any advantage they can possibly get. 

> What hours are you talking about? Geneticist can get all the fucking powers in an hour with extremely bad luck.

Are you talking about the same genetics system where I can use 50 DNA injectors on myself and still fail to manifest a power? I've rarely if ever seen Genetics act as miraculously effective as you describe it being, and even more rarely distribute those powers to anybody besides themselves. 

> Even with highest tier materials readily available you never EVER see more than two Durands, and Durands are way more benefitial and robust than any limb aug that I've described.

I'd buy that- if I wasn't personally involved in shifts where we had no fewer than 6 Phazons active at once and constantly making more, and that was with only one miner present. (Engiborg material synths, they make all materials instantly as long as the borg has charge for it.) Unless you want to make those prices massively high, materials simply will not be an issue. And as I said, RnD is literally following a flowchart, so everyone in the department has to be braindead not to max it within 10 minutes (and it's usually even less).

**Comment by Imagebard** [comment]
I really don't know why but it seems that ICTOANRN just dislikes this Feature Request instead of having any legitimate criticism towards it.

>Genetics cause side-effects

If you have access to gene changing, you can usually fix that without an itch.

>It takes time to discover genes and actually insert them

You need to do surgery to get modified robotic limbs. Injecting everyone is simple and quick, putting the entire station in surgery is boring and long.

>I've rarely if ever seen Genetics act as miraculously effective as you describe it being, and even more rarely distribute those powers to anybody besides themselves. 

And I've rarely seen 6 Phazon rounds, but they happen regardless. And taking in account the above argument, it will be even more boring to give everyone upgraded robotic limbs, to the point powergamers might just, y'know, ignore it completely?
Why is this feature request even being balanced around genetics? What is the point of referencing genetics?

**Comment by icantthinkofanameritenow** [comment]
@Imagebard 

I simply find it difficult to like things which come off as being too easily exploited and abused, when the costs are too greatly outweighed by the benefits. I look at this, and I see everyone lining up to get brand-new super-limbs that do everything the regular ones do and more. The chance of powergamers ignoring something that can theoretically (among other things) act as built-in insulated gloves/magboots or give them the equivalent of unstrippable armor is near zero, and I'm sure if genetics wasn't built around randomness I would have the exact same complaints for it.  

I only referenced genetics because the request maker was complaining about how genetics had so much more to offer the station than robotic limbs, again ignoring the fact that stuff like Hulk has only a 1 in 20 chance of actually triggering with every injection, no matter how much gene changing you do or how skilled the geneticist is. Do limb replacement surgeries only have a 1 in 20 chance of actually working that can't be changed in any way? 

Because even I wouldn't go that far to suggest doing a similar thing here.

**Comment by Lorkhatosh** [comment]
How about we forget specific downsides and do it so that Limbs need to be recharged for their benefits to be active?
So there is this pod which looks something like a sleeper but with wires and tech attached to it, call it augmentation recharge station.
The charge of the augs run out and the guy has to recharge them every now and then, this doubled with EMP damage is enough of a downside for anyone. 
Anyone with these limbs would need to constantly run back and forth to robotics to recharge AND he would have to look out for wizards, guys with EMP guns and generally anyone who can do any sort of EMP damage.

**Comment by Imagebard** [comment]
>1 in 20 chance

So basically, gene buffs are restricted to people that actually need the genes because its time consuming to apply them?
_Just like surgery?_

**Comment by icantthinkofanameritenow** [comment]
@Lorkhatosh 
Better. If they're going to have advantages like borgs do, they'll have to have the disadvantages of borgs as well. I'd prefer that the better augs require more recharging though. 

@Imagebard 
How many people "need" Hulk, might  I ask? Besides greytiders and shitters, I mean.

Even those people who might need something like shock resistance aren't guaranteed to get it because it just won't manifest. Probability doesn't care who you are, if the RNG gods decide you aren't manifesting that power then you are FUCKED. 

And when did surgeries require multiple attempts just to have their effects happen even when you do all the steps perfectly?

**Comment by Lorkhatosh** [comment]
Surgeries are harder to do now and have chance of slipping etc. if proper tools and gloves and all that is not used but that is besides the point.

As for recharge times, obviously the speed of energy consumption will depend on the aug and how logical it is, so strong augs would need large recharge times.

**Comment by Imagebard** [comment]
>How many people "need" Hulk, might I ask?

Here's the problem, nobody does, making your "1-in-20" chance argument ridiculous in first place

>And when did surgeries require multiple attempts just to have their effects happen even when you do all the steps perfectly? 

And here's your problem. For some reason, you can't seem to understand that a RNG timelock(genetics) is the same as a hard timelock(robotic limbs)
if a power doesn't manifest you just need to keep injecting. Its the same thing as waiting to do a surgery. How can you not understand this? Is there something unique about RNG I don't understand? Is it the 0.1% chance that a gene might not manifest after 30 injections, unlike in surgery?

Its the same thing. _They do the same thing_. the only thing will be that, randomly, a genetics team might be slower or faster to apply than robotic limb upgrades than a equally crewed and efficient R&D/Robotics team, depending on what RNGod is feeling like today.

**Comment by icantthinkofanameritenow** [comment]
@Imagebard 
I find RNG timelocks to be consistently longer than hard timelocks by virtue of their randomness. Hard timelocks are consistent, and in many cases (e.g. by upgrading parts) can be minimized or even bypassed outright. And unless there's a way to manipulate the RNG so it always yields powers when and how you want them to, even a 50% chance of manifesting may translate into you not getting that power even after a whole fucking hour. The number of times you inject it won't change a thing- it was 50% the first time, 50% the second time, and it'll remain that way no matter what. You say it's only a 0.1% chance, but I would say that happens practically every time Genetics tries to get any power that isn't borderline useless. 

Surgeries do take time, and they do have an RNG element- but _only if you're using the ghetto tools for said _surgery__.  You still don't need to do it over and over again to get the desired result. Also, all you need to make any random table into a surgical one is a single scanning module, so the wait for an empty table is itself a nonissue.

**Comment by gbasood** [comment]
when
you
code
it

I just made the code he left us work, the rest is up to some other nerds

**Comment by Lorkhatosh** [comment]
While that is true, I am attempting to set up BountySource as Clusterfack suggested in a thread so that the coders will actually get paid if they do add some form of advanced limbs. 
Paypall doesn't accept my country though so I am trying to do it through bitcoins and shit like that.
But hopefully once I set up BountySource money will be a good enough motivation for some actually good coders on our serb so that I don't have to code it.

**Comment by Shadowmech88** [comment]
How much are you offering?

**Comment by ghost** [comment]
Started poking at coding it now, turns out the welding_prot variable did absolutely nothing, probably something forgotten.

**Comment by Lorkhatosh** [comment]
I am offering 30$ and I think I've figured out how to set up bounty source from here.
I will post once I actually do it.

**Comment by ghost** [comment]
Currently thinking on the upgrading system being similar to how borgs are upgraded, with 'boards' being applied to the cybernetic organs, or would that be going down the wrong path?

**Comment by Lorkhatosh** [comment]
That might be the way to go, not sure though.
One thing I dislike about board upgrades is that generally it would be neat if making limbs took a bit more than just taking a robotic hand and sewing it onto a human, like if it actually had components.
What do you think?

**Comment by ghost** [comment]
I think I'm not that good of a coder. I've managed to narrow down the variables I'd need to use and create, but changing that much regarding limbs and how they function would mean a whole lotta work that I wouldn't know where to start on, hence I'm not wanting to do it for money because I may deliver a sub-standard product.

I've dissected the surgery code to see what applying a robotic external limb currently does, and it just sets a define that's rarely even used now, instead there's like 3 different variables and procs to check if an organ is robotic or not, and changes the icon folder.

But, I'm seeing where you're coming from now, maybe have it so that applying the upgrade isn't akin to how borg upgrades are done (Where the board is deleted and some variables are changed on the borg, hence you can't get those upgrade boards back.) But could make it so that it shifts the upgrade into the limb, and it runs through each upgrade in process to see if any can be used as such in that present time. That way, when you come to upgrading the limb, you simply take a module out and swap it for a different one.

So, I think I can make a win-win situation by borrowing some aspects from genetics and mecha by having passive and active upgrades. Passive upgrades being simple variable changes, whereas active upgrades are toggleable as they run off an internal cell in the heart perhaps? Problem is I'd have to take some time to research into how it can check if a module is actually in the limb without seriously messing with the game.

**Comment by Lorkhatosh** [comment]
Awesome, this all sounds great.
Honestly from start I knew that a coder would find a better way to do it, the main thing that I want is for limbs not to be useless and for them to be modifiable and fun. Not to mention gateway for future coders to add more powers and whatnot to limbs if they feel like it.

**Comment by Lorkhatosh** [comment]
Okay do you think this is possible?

> robotic limb
> add some component which turns it into an augmented limb, so now it has slots for the boards 
> make two slots, one for outer coating/armor, second slot for upgrade like toolhand 
> If upgrades are not applied limb just can be attached and it will be same as current limbs 
> I just sort of dislike the very idea of robotic limbs just being slapped on the person and it just working.

**Comment by ghost** [comment]
Ah, I see where you're coming from, like a conversion process to make a limb that was previously for robotic construction into something compatible with carbon lifeforms, like a nerve to electrode interpreter setup? That I can definitely do, and that would actually make making upgrades for external limbs a whole lot easier as well, it'd just mean changing how limb replacement to a robotic equivalent would work (As currently it just mocks it up as a new leg and changes variables and icons, as was mentioned), which should be as easy as making a new object, and deleting the references to the current robotic limb in surgery.

Having 2 different types of slots for external and internal could certainly be done.

(I really shouldn't be coding this before we've got all the brainstorming done first.)

**Comment by ghost** [comment]
Crap, but that would also mean anyone who's rolling with robotic limbs at roundstart, their character saves would corrupt to hell and back. That I ain't too sure how to handle.

**Comment by Lorkhatosh** [comment]
Yeah, brainstorming is important aspect of it. Really you can just let go of coding for now before I settle bountysource shit if you want.
But yeah, the new item thing would be easier, wouldn't it?

> Crap, but that would also mean anyone who's rolling with robotic limbs at roundstart, their character saves would corrupt to hell and back.

Yeah, but would it be possible to substitute new limbs for the ones at roundstart? Like default empty limbs with no upgrades installed?

**Comment by ghost** [comment]
I have no experience with fiddling with how saves work, so I wouldn't know without asking somebody else

**Comment by Lorkhatosh** [comment]
Could you ask around? I will ask some guys too.

**Comment by ghost** [comment]
Found out how it's handled. There's a define I mentioned earlier (the one that changes the icon and all that of a limb) that handles it all when it comes to sorting out mechanical limbs being loaded from saves.

I'd simply have to change how mechanize() works on a limb and that should mean nothing goes wrong with saves at all.

**Comment by Lorkhatosh** [comment]
Grand. 
Any other issues you can think of so far?
Also what do you think about the modules themselves?
What is possible, what is not etc.

**Comment by Lorkhatosh** [comment]
Also what do you think about the modules themselves?

**Comment by ghost** [comment]
The modules are, again, something a bit odd to tackle. Could approach it the way that mecha modules are handled (Contents are a list) then have 2 additional lists that reference the contents, 1 of active modules 1 of passive modules. The active modules could be ran through by adding them to the process handler, as it runs through each one it would declare that a certain variable assigned to that limb (EMP resistance, damage resistance, damage regeneration) is that value, then to make sure no modules are overwriting each other you simply have it so that you can't have two of the same module at a time (So, you'd have a specific module for EMP resistance, another for damage resistance, etc.)

Active modules, in theory, should be a whole lot easier as they'd run more on the aforementioned internal cell and player interaction.

**Comment by ghost** [comment]
Am I cool to start attempting coding?

**Comment by Lorkhatosh** [comment]
Of course, but I think it would be better for you to wait till I set up bountysource, again sorry this shit is taking so long it's both paypal and bitcoin have problems with my country apparently.
But if you are okay with starting anyway, sure, go ahead.

**Comment by Lorkhatosh** [comment]
Also do you know how welder/coil healing the hands work?
Welder fixing the dents is okay I guess but coil magically healing burns on arms sort of makes no sense, maybe nanopaste should do it or something?

**Comment by ghost** [comment]
Nanopaste is general fixing, wires is I assume rewiring the electronics on an arm (considering you take burn from EMP sources)

**Comment by ghost** [comment]
And to tell you the truth, I just wanna code this regardless of if there's a reward or not.

Was looking forward to the Deus Ex Update, watching N3x's streams whenever I could, and was hoping it'd breath new life into robotics, until he dropped it short after the whole forced map rotation fiasco.

After that, started researching life code, reading N3x's code to make head and tail of it, and was almost about to start working on it myself when he dropped it, then sood took it up, patched it, and put it in as a new pair of lungs and a new pair of eyes.

**Comment by Lorkhatosh** [comment]
Well start coding it obviously and thanks a lot.
I will find a way set up bountysource though and you will get your 30$ which is not much but still. I generally believe that it's not a bad way to motivate coders to do new features.

**Comment by Lorkhatosh** [comment]
By the way, I heard that advanced Eyes are bugged or something?
I have never actually tried them, only tried advanced lungs, but aren't they supposed to give night vision and protect from welding damage? Could you possibly also improve advanced eyes while you are at it, if they are shit that is.

**Comment by ghost** [comment]
I've already got a PR up that fixes them not being welder-proof, but the night-vision thing is beyond my understanding entirely.

**Comment by Lorkhatosh** [comment]
Why? Is night vision somehow borked or complicated?
Maybe if not permanent, do you think it's possible to make it like a spell icon or one of those icons at the top left and when you click it a spell gets turned on which gives you night vision for some time?

**Comment by Lorkhatosh** [comment]
Also have you thought about full limb replacement vs just hand or foot replacement? Because during character creation you can do stuff like that, but in round replacement does not allow it.
In which case I say why not remove just feet/hand replacement and make it full limb only?

**Comment by Lorkhatosh** [comment]
So in total, how many tiers do you think there should be?
Base augmented arm.
Advanced augmented arm that has some slots.
One level above.
(Another level above for super high research?)
Rare/Vault/Syndie/Deathsquid tier.
Right?

**Comment by ghost** [comment]
Yup, 5 total, 1 for initial 'oh, my arm got cut off so I slapped a bit of borg onto it', 3 researchable, 1 ultra-high tier for superloot

**Comment by Lorkhatosh** [comment]
http://i.imgur.com/wYx3bXX.png
Mockup of all the prosthetics.

**Comment by Lorkhatosh** [comment]
http://i.imgur.com/gQ9slVZ.png
Mockup of items that can be used during upgrade/construction of higher tier augs/can be applied to aug to upgrade. Whichever one will be the way to upgrade or create better augs.

NIT, Neural Information Translator. (Turn robotic hand into usual prosth hand.)
Augmentation Upgrades Mainboard. (Tier 1)
Adaptive Hull. (Tier 2)
Flux Energy Core. (Tier 3)

I assume that there will be no parts or items that can ugprade/create augs of the highest tier and that they will be spawn only or found complete in some rare vaults or something.
