### ISSUE TITLE
Human heads are sometimes welded on if burn husked.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10101]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 3ddc5b88ad0e786c072d5c142186b5d789279246 
> 
> General description of the issue
> Can't remove a burn husk's head via sharp attacks to head.
> 
> What you expected to happen
> Burn husk head to come off when attacked with circlesaw.
> 
> What actually happened
> 50 attacks to the head, still attached to body.
> 
> Steps to reproduce if possible
> Burn husk a body, try to circlesaw the head off.

**Comment by Killette2** [comment]
I think this is intentional, it's been around for so long.

**Comment by Shadowmech88** [comment]
Did you try aiming for the mouth instead?

**Comment by Allspice** [comment]
Can't speak for this time, but I've sawed at the mouth before and it didn't come off.

That said, help saw on mouth while tabled always works, it's just harm saw/sharp that's fucked.

**Comment by TheFriggenSawbones** [comment]
yeah this happened to me recently.

I killed a traitor Vox with the captains laser and I couldn't cut off his head using a fire axe or an esword. Every other limb came off. I was targeting the head.

**Comment by ComicIronic** [comment]
Probably a null error behind the scenes.

**Comment by PJB3005** [comment]
My theory is that the total combined brute + burn is capped so the burn cancels out the brute enough to not be able to reach decapitation amounts.

Although that's probably not what's happening.

**Comment by Sprok0** [comment]
This came up again, a vampire was lasered into being a husk, cheated death to resurrect, then could not be decapitated to kill it.

**Comment by Gringonius** [comment]
@Sprok0 Was about to comment that, this could lead to some degree powergaming with lings and vamps to make themselves unbeheadable.

**Comment by 9600bauds** [comment]
I can confirm that this is related to the damage of the corpse before attempting to behead it rather than with the husking itself. You can laser a dude 4ish times and then try to behead him and it won't work despite him not being husked.
This doesn't happen with toxin damage. My theory is that that's because the limbs themselves don't take toxin damage.
For some reason when you try attacking the dude in the head it starts attacking other bodyparts instead. I can't figure out why, or why this only happens with pre-damaged corpses.

edit seems to be around line 135 in organ_external i'm going to sleep

**Comment by Killette2** [comment]
@9600bauds 

What about genetic damage? Limbs technically take that, but it doesn't show up on the simple scanners.

**Comment by 9600bauds** [comment]
Will fix tomorrow
