### ISSUE TITLE
Weird ass captain jumpsuit bug

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#10121]
1. Join as captain
2. Try to take off jumpsuit, it doesn't work
3. Hotswitch it with another jumpsuit, I'm able to take the other jumpsuit off
4. Put back on captains jumpsuit, I'm unable to take it off again

**Comment by 9600bauds** [comment]
This is because of the medal of captaincy that the jumpsuit has attached. You can rightclick the jumpsuit and click remove accessory to remove the medal, then you can remove it freely. For some reason the medal disappears when you do this.
I guess the fact that you can hotswitch it is a bug? Then again this is a pretty lousy feature

**Comment by Shadowmech88** [comment]
The medal of captaincy should be changed to be a proper attachable thing like the shoulder holster is instead of whatever snowflake item I'm sure it is right now.

**Comment by Exxion** [comment]
It actually is a proper accessory and has no custom accessory interaction code, so I'm not sure what's going on

**Comment by Exxion** [comment]
Oh would you look at that it's added to the suit on job initialization manually rather than by calling the proper proc
That might be the problem

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/15390021/8e7f17e4-1d87-11e6-9d03-ab10901a4a7f.png)

Those arguments should be in the opposite order
I'd fix it myself but I really should be studying
It's in `jobs\job\captain.dm`

**Comment by clusterfack** [comment]
The metal of captaincy did nothing wrong
