### ISSUE TITLE
Should we change the name of Left 4 Zed to something that better describes it?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10174]
I know it's had the same name for years so its pretty rooted.  But what exactly does Left 4 Zed confer?

From the wiki

> Left-4-Zed: Makes your plant more susceptible to mutagenic chemicals, so that you need to use less of them for the same effect. How big of an effect Left-4-Zed will have on your plant is rather unpredictable, so be prepared for potentially dangerous mutations.

I think a new name for it at this point is alright.  Its been changed over the years so the original name is ambiguous.

**Comment by clusterfack** [comment]
Alright, we'll make left 4 zed 2

**Comment by Kurfursten** [comment]
> Clonexadone can de-age your plants

Feeding Clonex to Diona to turn them back into Nymphs when?

**Comment by ghost** [comment]
Look at https://github.com/d3athrow/vgstation13/pull/6901/files .

 From my terrible understanding left4zed, plantbgone and radium up the mutation_mod  which caps(Clamp(mutation_mod, 0, 3)???) at 3. Chems that raise mutation level, radium(0.6) & mutagen (1), are multiplied by the mod and some other factor that doesn't make much sense. This caps at 25 and resets every time mutate is called if I get this right.

i'm not sure exactly how but it should help you do more with less cause everything is all spread out and I'm having trouble with all the notation since I think in a bunch of spots it's like he's talking about mutation level but just says mutagen instead. I guess the higher "mutation level" from your mutation mod you got from the left4zed plants you higher on the brackets in hydroponics_mutations.dm. So if it's not getting stopped by, mutate(min(mutation_level, 25)) //Lazy 25u cap to prevent cheesing the whole thing, then it'd be integral for getting up to the 200 (?)potency hard cap after robust harvest peters out at 130-150.

Edit: I guess it'd also be useful in an apocalypse scenario where there's no way to get chem dispensers so you're having to use kudzu antitox and glowshroom radium to do mutations but whatever. So far out there in the realm of never relevant.

`code/modules/hydroponics/hydroponics_mutations.dm
-   var/mutation_mod = 1       // Modifier to mutation_level increase.
  -  var/mutation_level = 0     // Increases as mutagenic compounds are added, determines potency of resulting mutation when it's called.

+/datum/reagent/radium/on_plant_life(var/obj/machinery/portable_atmospherics/hydroponics/T)
-  ..()
-  T.mutation_level += 0.6_T.mutation_mod_custom_plant_metabolism
-  T.toxins += 4
-  if(T.seed && !T.dead)
-      T.health -= 1.5
-      if(prob(20))T.mutation_mod += 0.1 //ha ha

+/datum/reagent/fertilizer/left4zed/on_plant_life(var/obj/machinery/portable_atmospherics/hydroponics/T)
-  ..()
-  T.adjust_nutrient(1)
-  if(T.seed && !T.dead)
-      T.health -= 0.5
-      if(prob(30)) T.mutation_mod += 0.2`

Could go with mutagenic amplifier or something?
