### ISSUE TITLE
Antibodies do not prevent infection by disease

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#10188]
Antibodies SHOULD make you completely immune to affected diseases. However, if you're in proximity to someone when they're infected (such as injecting a monkey or person with infected blood), there seems to be a chance for you to quickly suffer the symptoms of the disease, then return to being immune.

Some examples during a recent round were sprouting a clown mask and hallucinating, sprouting a horse mask, going blind, and beginning to cough, each on different occasions when I injected a monkey or crewmember with infectious blood. Each time, the symptoms appeared, then the disease was instantly cured. Checking my blood in virology yielded nothing but antibodies; no pathogens were present.

**Comment by Probe1** [comment]
They had no viruses in their system when they ahelped after the fact.  I checked with VV and it was blank.

**Comment by Kurfursten** [comment]
This may have something to do with old diseases. Sometimes we'll go to deff and someone finds a beaker of an old disease, or one will proc off the random event, and they can be buggy.

**Comment by invoid9** [comment]
I once cured myself of a virus that had resting syndrome. I swear I still found myself collapsing shortly afterwards (could be unrelated and due to having eaten radium, I'm not very experienced). I was collapsing (experiencing symptoms of the virus I cured in myself) when around other people I hadn't cured yet. Dunno if my issue is related, or if it had some other cause, just thought I point it out just in case.

**Comment by Imagebard** [comment]
This also blatantly shows up if you're using a MedHUD.

**Comment by Hoshi-chan** [comment]
It has nothing to do with old diseases. Of the 12 diseases that I spread that round, it showed symptoms of at least three of them, distinctly, at the appropriate stages. It ONLY occurred when someone else became infected right next to me, too, so I think that might be what's causing it.

Perhaps the code is checking for people nearby to infect when someone else contracts a disease, and is acting on them before the antibodies prevent it, so you get the symptoms, then you're instantly cured.

EDIT: I've also contracted that disease that makes you FOREVER HUNGRY before, cured it, and then remained hungry forever despite the virus no longer being present.

**Comment by PJB3005** [comment]
My guess as to why this happens is that the getting infected code doesn't check whether you have the antibodies, then it gives you the initial effect and then gets removed because some other life code realises.

**Comment by Hoshi-chan** [comment]
Happened again last round to an IAA that had become a slimeperson, despite ALL antibodies present in his system. It's possible that it happened WHEN he became a slimeperson, so that might be something to test as well.

**Comment by Killette2** [comment]
Let me explain this SHITUATION.

With diseases, the syndromes will occur quickly before the disease is cured due to your antibodies. This is why if you get a virus with longetivity cured, you will constantly get spammed "You feel old" because you will get infected again, but cured within about 1 tick, while still suffering from the virus.

So pretty much what PJB said.

**Comment by MercuryDoll** [comment]
That _kinda_ makes sense because antibodies need a moment to kill the virus once it entered the system. I'm wondering if symptoms should show up the moment the patient is infected though.

**Comment by Shadowmech88** [comment]
I think the best option would be to give all viruses a short asymptomatic incubation period.
Also It'd be nice to be able to change the incubation period somehiw, for traitor antics.

**Comment by MercuryDoll** [comment]
Yeah, that's probably the best solution.

**Comment by DeityLink** [comment]
They do in Nuviro.
