### ISSUE TITLE
Dr. Acula the blood donation medibot

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#10181]
Thought it might be useful to have a modified medibot in the medical lobby that accepts blood donations, and dispenses small rewards to donors. 
![dr acula](https://cloud.githubusercontent.com/assets/15067109/15490997/582f8b3e-2164-11e6-8b20-41d3caf09f34.png)
Maybe have it dispense any full bloodpacks when smacked with a medical ID and blood could be automagically converted into O- for ease of use. 

Ideas for rewards: tea and biscuits, blood donor badge (jumpsuit accessory), medbay branded trolley token (works as a vending machine coin).

Maybe also have a limit on blood taken, that would be removed when emagged, and possibly have it seek out 'donors', rather than being voluntary.

**Comment by ComicIronic** [comment]
> convert blood into O-

What kind of handholding codebase do you think we run here?

**Comment by SysadminJeroen** [comment]
![Dr. Acula](https://vignette2.wikia.nocookie.net/scrubs/images/c/c4/5x23dracula.jpg/revision/latest?cb=20090703171011)

**Comment by Hoshi-chan** [comment]
Here in the US you get juice and a cookie for donating blood.

Providing food for blood donations would be fantastic though, regardless of what kind, since food is something that people are always after, unlike silly trinkets which people might go for every day for a week, then never bother with again.

**Comment by SysadminJeroen** [comment]
@Hoshi-chan You just gave me an idea for a food item to make, it is an [IJzerkoekje](https://en.wikipedia.org/wiki/IJzerkoekje). Doesn't actually contain iron but I could get the cookie ingame to give both nutriments and iron.

**Comment by Hoshi-chan** [comment]
@Jeroen52 Wowee, those look delicious.

**Comment by SysadminJeroen** [comment]
@Hoshi-chan They sure are delicious, never pass on a chance to purchase them.
The real recipe contains no iron, but for the ingame recipe I'll make it out of flour and iron, possibly even a third or fourth ingredient.

**Comment by SysadminJeroen** [comment]
@Hoshi-chan Here is my attempt at spriting the IJzerkoekje: 
![ijzerkoekje](https://cloud.githubusercontent.com/assets/2915526/15499320/e9b3d166-21a3-11e6-9e18-4209d39ea9d4.png)

**Comment by nuklearcellphoneg** [comment]
+1 to dispensing the food, since you'll need it for your missing blood.

However instead of being a little medibot, maybe make it into a stationary pod/shower thing near the front desk of medbay. Few reasons for this:

1) I like that emagging it makes them drain blood more, but then if you make ten of them they're like a cloud of death bots.

2) Really, I just want this to be a sort of blood donation booth, akin to a suicide booth from Futurama. And I want it to be slightly dark inside of the booth. Because I want vampires to hide in the booth with their invisibility. 

AAA idea so far though, really.

**Comment by SysadminJeroen** [comment]
@nuklearcellphoneg, it could be programmed that every tick it checks if a player's blood level is above a dangerous amount. This check will not be executed once the bot is emagged.
And the amount of IJzerkoekjes is depending on how much blood you donate.

# 

I was thinking of 30u flour and 30u iron to make 6 IJzerkoekjes, and each IJzerkoekje has 5 nutriment and 5 iron. Does that sound good?

**Comment by SysadminJeroen** [comment]
Coded the IJzerkoekje and committed it to my fork.

Can't test it right here (because my Laptop is special), so I'll have to wait until I can go home to compile and test the commits.

I know it compiles without errors, but still gotta check if it works.

https://github.com/Jeroen52/vgstation13/tree/IJzerkoekje

**Comment by FudgePucker** [comment]
I support converting the blood gotten into O-.
So you are telling me that we have a medicine that is able to put O2 into every cell instantly treating oxygen deprivation and a cloning machine, but removing the markers off of blood is too out there?

Remember, people can (and do) treat blood loss with a tool box and the cloner.

**Comment by SysadminJeroen** [comment]
The converting to O- should come at a cost, maybe 50% of the converted blood should be lost.

**Comment by Hoshi-chan** [comment]
@nuklearcellphoneg Suicide booths when?

@Jeroen52 It's cute!

**Comment by Killette2** [comment]
@Hoshi-chan beat me to it

The food should be cookie and OJ, as bizarre of a flavor combo that is in all honesty. If you want to be a cheapo, make it the sugar cookie instead of admin prayer cookie.

Also cookie/sugar cookie is fine, we don't need a new food, because cookies contain both sugar and nutriment, which both restore your hunger for your blood, or you could just throw in sugar to it too.

**Comment by Imagebard** [comment]
But I really like the Iron Cookies.
Besides nutriment does heal blood but its roundabout about it, something with Iron is a better idea.

**Comment by Blithering** [comment]
Iron cookies are a really good idea, would help offset the blood loss much faster than regular food.
![emagged](https://cloud.githubusercontent.com/assets/15067109/15527979/7c8d35f2-2237-11e6-8fe8-08cd42c36894.png)
Emagged icon!

**Comment by nuklearcellphoneg** [comment]
Well, both iron and nutriment are going to help you refill your blood, but at 5u/5u they're going to metabolize very quickly- 7.5u/7.5u might be slightly better than 5u/5u without being too much. 

Some in game testing would probably be best, to find a proper amount which replaces most of the blood lost without replacing all of it- it should also take a considerable amount of time to get the blood, at least equal to the IV time.

**Comment by MercuryDoll** [comment]
Holy shit that's adorable. And these wafflecookies look delicious.
I'm for making the bloodpacks O-, but we should adjust the loss/transmutation-rate comparative to the average amount of donators. Doesn't make much sense if we never get a full bloodpack per shift.

**Comment by SysadminJeroen** [comment]
Looks like #10189 has been merged.

**Comment by Kurfursten** [comment]
Another thing worth thinking about is that bloodpacks are 3 plastic sheets a piece, and this machine will be freely generating those too

Unless you want to make doctors insert a bloodbag like an IV drip and retrieve it when it pings or something

**Comment by SysadminJeroen** [comment]
@Kurfursten Could make the bot spawn with 12 plastic, and internally use 3 plastic to lathe a bloodbag when it is needed to fill it with blood.
The bot would require plastic to be inserted when it is out of plastic.

**Comment by SonixApache** [comment]
absolutely adorable

**Comment by chatsonf** [comment]
Bump because this looks amazing and I love it

**Comment by MercuryDoll** [comment]
Doesn't medbay start out with empty bloodbags? If not, simply add a handful, if yes just add one or two anyway. Since he's gonna have to be build first it probably isn't too far fetched just loading the little bloodsucking toaster up with empty bloodbags before sending it on a lifeforce stealing rampage.

**Comment by Kurfursten** [comment]
@MercuryDoll I actually like this idea because unless you're solo in medbay, it's kind of boring at the start of shift. You are either the guy working chemistry to get pills/cryo ready, the guy pre-loading the cloner, or... nothing. You go to idle at the front desk and watch the suit sensor computer.

So it might be fun to give doctor's the job to drag out the bloodbot to the front and load it up as part of their shift ritual.

**Comment by kol1th** [comment]
Did someone say code something that's already sprited?

**Comment by Blithering** [comment]
@kol1th It would be great if you picked this up for coding, also reminded me I never gave a link for the sprites: http://s000.tinyupload.com/index.php?file_id=00254431253340170293

**Comment by Blithering** [comment]
He lives!
