### ISSUE TITLE
Revert Celt's buggy shitcode hypothermia

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#10196]
Too many bugs, too many issues, none of it's getting fixed, Celt took the money he got for coding it and ran (all $0.02)

For example, if you try to ventcrawl in a room temperature vent, you will freeze to death.

Raise the temperature to above room temperature and average pressure (101.3kpa) in the vents? Freeze to death still

Unwrench a pipe with high pressure? You bet your ass it's gonna freeze you to death

Hypothermia has an issue of working properly, and I've even gotten hypothermia sleeped with no warning messages, while in above average temperature in vents. This issue has been reported by dionas for ages but never touched. Remove shitcode!

**Comment by Shadowmech88** [comment]
All these issues stem from the intentionally-coded property of heat loss to the environment being affected by the number of moles of gas in the air. If there's more moles of gas in the local atmos, then you get hit by molecules of said gas more often, causing heat to be conducted away from you faster.

It's shitty from a gameplay standpoint, but it's not really a bug. Maybe an oversight if anything.

**Comment by 9600bauds** [comment]
I'm pretty sure Celt said it shouldn't affect you in vents

**Comment by Shadowmech88** [comment]
Well tell him to get off his ass and fix it then.

**Comment by 9600bauds** [comment]
He tried.
https://github.com/d3athrow/vgstation13/pull/9116

**Comment by Killette2** [comment]
If it's been such an unfixable problem for so long, just remove it and try when it's better tested and tweaked.

Even with the right pressure and temperature (therefore the correct mols), you still get ice barraged in vents.

**Comment by Shadowmech88** [comment]
> If it's been such an unfixable problem for so long

It's not unfixable.
It's just that no one cares enough to fix it.

**Comment by ghost** [comment]
It can be fixed, the values need tweaking

**Comment by AutismSpider** [comment]
@Shadowmech88 sums up all the bugs.

this makes antag atmos item useless no matter what they do they freeze to death in the pipes

Vent in as a slime die form the cold same as diona and a monkey

**Comment by TheFriggenSawbones** [comment]
REVERT

**Comment by icantthinkofanameritenow** [comment]
@Dylanstrategie
If it's that easy to fix, why hasn't Celt or else done it? It's his baby, he should be taking care of it instead of jerking off over #6789 without showing been a hint that the whole reason he ever coded this will ever make it into the game. 

Also, the mancrowave. Still ugly as sin and bulky to boot, still made irrelevant by the cryo cells having built in thermoregulation, and if you ask me cryo shouldn't  be ejecting people asleep in the first place.

**Comment by ihadtoregisterforthis** [comment]
![unfixable](https://cloud.githubusercontent.com/assets/13305885/15551044/7efd87bc-228a-11e6-9c78-d0f63a6f31c4.png)

**Comment by AutismSpider** [comment]
revert it or fix it.

THIS shit was put in for a map he has done nothing with.

**Comment by ghost** [comment]
Hello.
First of all, it was not put in for a map; it was added to make heat simulation in bodies more realistic. Which facilitates the map, yes, but does not necessitate it.
The fact there is only one bug mentioned here in this hyperbolic report is actually very positive, I'm glad to see it's working well.
My attempt to fix it was rejected and I was given no reason so *shrug. I'll get a new fix for that when I am back. I'll return next month.

But to be honest if you're going to ask for a revert of the entirety of hypothermia over one bug, (the revert would definitely cause wayyyy more bugs than it would fix by the way.) you should be doing the same for the 1,500 other bugs/requests etc in the repo.

**Comment by icantthinkofanameritenow** [comment]
@DrCelt

> It was added to make heat simulation in bodies more realistic

And who asked for that, exactly? I don't remember the initial reaction bring much of anything more positive than indifference, and the old method got the job done with no issues inherent to it. 

The fact that you yourself originally admitted in the hypothermia PR that its main purpose was to facilitate the snow map does not help your case very well, nor does the fact that this supposedly easy-to-fix bug hasn't been fixed already.

**Comment by ghost** [comment]
> supposedly easy-to-fix bug hasn't been fixed already. 

I'm not back yet, nerd. I did a rudimentary fix but it was rejected, and I received no reason for it being closed so *shrug

> the old method got the job done with no issues inherent to it.

I could apply that quote to literally any PR ever. It's literally a nothingness, it means absolutely nothing other than to impede change or progress.

**Comment by Killette2** [comment]
Cmon Celt, your heat retaining system was no code from the heavens. It caused other things such as husking treadmills, spicy foods to be a death sentence unless you had a glass of milk, that have been fixed but show how flawed the system was on release and how flawed it still is. Sure one current bug exist (pressure related and vent issues), but to say every bug should be removed because your system has a few bugs that break more major things, is a big much of a demand.

Stop sugarcoating the issue, the bug is major as it completely makes the ventcrawling atmos traitor suit useless, kills slimes in vents 4noraisins, diona nymphs and changelings suffer. Thank god xenos are immune to this shit, but haven't we suffered long enough from death to buggy vent code?

**Comment by ghost** [comment]
@Killette2 And all of those issues bar very few have been fixed, you nerd. If every buggy piece of code was removed as soon as a bug arrived, we wouldn't have even left r4407. Also, the removal of hypothermia would cause more bugs than it would fix.

**Comment by ghost** [comment]
But yes, my code isn't fucken perfect, and if I've ever claimed that go ahead and shoot me. It was a buggy mess, sure. In fact, every piece of code is. I will endeavor to learn from this but I hardly think you're going about it the right way.

**Comment by Killette2** [comment]
That's the other thing. I already mentioned over half of hypothermia being fixed, but it's been months after months I don't even know how long and it's still a mess. I just have to ask since you keep repeating it, what will break more if we remove hypothermia? Is it just a balance thing? Because I prefer bug free over balance with critical bugs. If you'd state the problems that would arise if hypothermia would be removed, maybe we'd agree with you a bit more instead of you just saying there are without providing proof.

**Comment by ghost** [comment]
@Killette2 To summarise; if you throw a cup of water into the ocean, it's impossible to get that same cup of water out. Similarly, if you add an addition to the game, and time is granted, it becomes tangled in. Conflicts, other shite, not including the features in hypothermia you wouldn't want to remove. A lot of files were changed overall over the course of a few PRs, it'd be a clusterfuck to fix and you'd in effect have to test all the changes in reverse. Not to mention of course the balance issues which you brought up. Overall, just wait a month or less dude, I'll fix them.

If you really want to be productive, link here all the bugs that have not yet been fixed so that when I can, I will fix them, and then if you want to push forward your point the bugs that were fixed and see the ratio between them.

Anyway, I'm going to bed because I'm exhausted and probably coming across the wrong way.

**Comment by AutismSpider** [comment]
Joking right???

bugs you should of fix sec they pop up but no all you did was sit on ur ass

**Comment by Killette2** [comment]
Honestly what really else was tied into hypothermia besides hypothermia and a few bits of heat retaining? Cryo would probably still be fine, mancrowave would also be fine and obsolete. We just want it, and anything that came with it, temporarily gone then you can bring back a golden bar of code instead of a turd spray painted gold and covered in duct tape.

**Comment by AutismSpider** [comment]
he fuck with how temp gun work and fire fighting foam.

Cyro does what the mancrowave does now so does the sleeper so zero need or use for that thing.

**Comment by icantthinkofanameritenow** [comment]
@Killette2 
 I can't name even one right now apart from the ones that were made specifically to address the hypothermia itself in the first place. Cryo would be the same, mancrowave would be little more than dead weight (as it already is most of the time), and extreme cold would just kill people instead of putting them to sleep and then killing them.  If these conflicts and features that are so tangled up actually exist, then he should at least be able to name one right here and now. 

I'm no saint in bug testing either, but if I was in Celt's place and I released something that big with that many flaws, I'd have taken it all down immediately and set off to do **_no less than_** a couple months' worth of testing, both directly and with mass playtests from volunteers trying to push the system to its absolute breaking points. 

> Overall, just wait a month or less dude, I'll fix them.

That would be more convincing if you didn't say the same thing months ago. Do it quickly or not at all.

**Comment by ghost** [comment]
@killette2 see the suggestions I made earlier to prove your case
@autismspider

> he fuck with how temp gun work and fire fighting foam.

Temperature gun has ALWAYS BEEN shit. The only reason anyone found out how shit it was is that people were trying to abuse hypothermia and realised hold on this gun is bollocks, as it was before. If you want to buff it, go ahead. I retained its functionality, but scaled it down to fit with the new system.
As for the firefighting foam, it works fine and was not actually actively changed in the hypothermia update.
@icantthinkofanameritenow
Interesting because I did hold bug testing and I do remember the people that attended including: not you.

**Comment by ghost** [comment]
But hey it's all well and good saying stuff like "wow if I coded this it'd be perfect for sure and I'd do everything right ever." I know there were flaws and I have learned from that but again, this is a drastic overreaction and it is perhaps telling that no coder has demanded it be reverted, only those that do not code or >code.

**Comment by 9600bauds** [comment]
> If you really want to be productive, link here all the bugs that have not yet been fixed

You can start by this one
We've already waited a month

**Comment by icantthinkofanameritenow** [comment]
@DrCelt 
Yes, I know. That was because I had no confidence in it then, and while it's improved marginally since then anyone can see that it should have been tested longer before being merged- and it's equally damning that you can't name a single conflict or bug that might be caused by the feature's removal, only insist on it on the assumption everyone will take your word for it. But that's irrelevant, the point is this:

Why delay fixing those bugs any longer than you already have? It's giving a lot of people the impression you simply do not want to take responsibility for the feature you programmed. I'm not saying I'd have done it perfect, but I sure would have pushed for an immediate revert and put the thing on hold if it was buggy.

**Comment by ghost** [comment]
Currently in the middle of a move to a different country fam, computer is shipped off. Sometimes real life takes precedence over spessmens.

**Comment by 9600bauds** [comment]
Were you moving two months and a half ago? #8767

**Comment by TheFriggenSawbones** [comment]
drcelt can you move to america so we can hang out

**Comment by icantthinkofanameritenow** [comment]
@DrCelt

Bauds said it better than I can. You've been making excuses instead of fixes for long enough.

**Comment by Boxe** [comment]
:eggplant:

**Comment by Intigracy** [comment]
Still need to punch yourself to stand up from the mancrowave?

**Comment by 9600bauds** [comment]
The microwave has nothing to do with that bug

**Comment by MercuryDoll** [comment]
> That was because I had no confidence in it then,

If you are opposed to a feature, that's just as much incentive to join the free, voluntary bugtesting as wanting it, if not more. You want to shoot it down and prevent it from going live, your negative bias is your gun but you need ammo. This makes your goal to find as many bugs and exploits as you can. You're prone to point out the flaws directly and uncensored instead "well, this is a bit wonky but whatever it's _fun_!" asslicking.
You had a role in it, you could have stopped it, why didn't you try? Kinda late for a revert now that we're several commits in.

**Comment by Killette2** [comment]
We did, it barely got tested, we complained about a lot of things early but it got put in way too fast.

**Comment by AutismSpider** [comment]
@MercuryDoll Are you retarded??? people bitch and complained about how bad it was with very little testing that was done on it and it got in any way after meme vote.

**Comment by AutismSpider** [comment]
Like to point out this going happen with that so called borer rework got ton of yes votes some how.

When that thing needs way more work.

**Comment by Boxe** [comment]
:eggplant:

**Comment by Killette2** [comment]
We don't need to test borers, it's gonna be cool!

Hmmm this seems familiar somehow...

**Comment by ihadtoregisterforthis** [comment]
It's called field testing, Alfred

**Comment by Killette2** [comment]
I think you mean 6ish months of suffering.

**Comment by AlphaBuffalo** [comment]
I don't really have to many problems with hypothermia, except that cryo should have a mancrowave built in, but the husking treadmill and chilly pepper death fits the nature of spess station. Atmos vent crawling suit was always shit because if you go into a pipe that's pressurized you die anyways, not to mention you are limited on what to bring in, it's better just to emag a mommi and let them do the vent crawling for you. Though monkey and slimes should be fixed for vent crawling.

**Comment by Killette2** [comment]
> He thinks you can't bring anything decent with you with the contortionist jumpsuit

Loving
Every
Laugh

**Comment by AutismSpider** [comment]
@AlphaBuffalo Sounds like some one never used the suit.

Can take bombs IED's etc with you with the suit on. 

like any thing a mommi can do you can do with the contortionist suit go in grab shit and get the fuck out

**Comment by Intigracy** [comment]
9 days later

**Comment by Shadowmech88** [comment]
He did say he won't be back until sometime this month.

**Comment by AutismSpider** [comment]
no he had shit ton of time fix the bugs now he just bitching out
