### ISSUE TITLE
60 burn damage causes perma pain stun

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#10215]
What title says is the issue, also this might happen with some lower amount of burn damage as well. Also I think everyone had some paracetamol in them by default before and now they don't and without paracetamol you really can't recover from pain stuns. Since you don't passively regenerate burn damage you can get stuck in a pain stun limbo. 

 Make people passively generate a little amount of paracetamol in them by default or fix the pain code I don't know I am a dummy lol haha what is game code :100:

**Comment by 9600bauds** [comment]
Kind of, there's a few issues with pain
The first is that pain basically never fucking matters except for burn damage which is really painful, and brute/toxin usually kill you before pain even comes into play
The second is that once you go past the pain threshold you build up shock (starts at 0), which just keeps building up forever and then permastuns you.
The third is that painkillers are SHIT and never used because just healing the damage you have will treat the pain just as good, so kelotane is actually better against pain than an actual painkiller.

**Comment by Killette2** [comment]
If I've learned anything from this server, it's that permas and pain come hand in hand

**Comment by 9600bauds** [comment]
Also, fun fact: The original code for painkillers was just analgesics that completely blocked pain but made you unable to see your health or hazard warnings.
![asd](https://cloud.githubusercontent.com/assets/6526157/15590035/f0da6c10-236b-11e6-9010-ed316fb8b896.png)
![sadd](https://cloud.githubusercontent.com/assets/6526157/15590042/fb39fa0e-236b-11e6-8c40-214706799ab8.png)

**Comment by Imagebard** [comment]
@9600bauds 
Any chance we can re-add that as a souped-up version of painkillers?

**Comment by Kurfursten** [comment]
> Make people passively produce painkiller

more like make the human Hear() produce painkiller when they hear positive words

only you can help save people in a xeno attack by chanting positive words over radio to raise troop morale

**Comment by Killette2** [comment]
Addictive painkillers when?

**Comment by Probe1** [comment]
I put painkillers in cryo and if I feel really autismal I put them in other medicine.

Its not useful at all on its own.  It's an additive chem.  You wouldn't just give someone tricord, you'd mix tricord in with bicard or keloderma.
