### ISSUE TITLE
Flashbacks of murders hallucination effect

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10210]
This is such a cool idea that I have to write it down.  It's in all likelihood never gonna be coded but this is worth an issue

When someone dies violently the server takes a screenshot of their vision when they die.  It then adds one or several color filters (noir, etc).  Other players can trigger hallucinations either through mindbreaker or new chemicals that gives them a flashback/hallucination of the scene for a few seconds.  The images would be from many different rounds so it's not a meta concern.

Wouldn't that be the tightest shit ever?  
Fat chance its getting coded.

**Comment by ComicIronic** [comment]
Detective doing Salvia to get in touch with the spirit world when

We could probably base it off photo code + client images + transparency.

**Comment by ghost** [comment]
It's possible and amazing.

**Comment by Probe1** [comment]
> Detective doing Salvia

Its a pipe dream metaphorically and literally.

**Comment by ghost** [comment]
I could code it I reckon and include it in that big client colour update I want to do one day.

**Comment by 9600bauds** [comment]
The only problem here is that even 5x5 photos were too fucking laggy (thanks BYOND)

**Comment by Shadowmech88** [comment]
The _creation_ of the photos is laggy because getFlatIcon() is.

I don't think it'd be too terrible if it happens only when someone dies.
And since the server would be storing these, we could make it only a 1/20 chance or so for each death to be captured. I doubt the lag would be noticeable overall, and we'd still get plenty of death scenes to use since deaths happen _a lot_.
