### ISSUE TITLE
Replace the SME on Deff with a TEG?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10263]
I was thinking about ways to marry the two inconsolable differences with the SME on Deff.  It's an advanced engine.  And it's set to be the primary engine on Deff.

But it doesn't have to be.  

There's another engine and that engine is the TEG.  It will provide useful atmospheric experience, its got a vintage appeal to it which meets Deffs narrative, and its a lot easier/reliable/safer than the SME so new engineers won't be quite so slammed and delaminated by power setup on Deff.

It'd also be easier to link to the R-UST that way.  With a pre-built TEG the R-UST would really be about setting it up and getting it going, not building the TEG and all that jazz.

Whatcha think?

**Comment by Konater** [comment]
I think the supermatter sucks and making it the primary engine with a shoddy setup was a mistake

**Comment by Kurfursten** [comment]
I think the deff supermatter is fine. It's pretty bad that there are engineers who can't work an SME.

Just give the babby engineers back their AME. Adding a RUST at its expense was a mistake, since the RUST doesn't even come with all the parts.

**Comment by Probe1** [comment]
I gave them an improved AME in the same PR.  

And all the boards to build a functioning R-UST but people still order it from cargo for some strange reason.

**Comment by FudgePucker** [comment]
Holy shit do you really think that the TEG is easier than the SME?

**Comment by ComicIronic** [comment]
A station-powering TEG is much much simpler than a similarly-terrible SME.

It's harder to make better, but we should think in terms of less experienced engineers when choosing station engines.

**Comment by FudgePucker** [comment]
Just make deffs SME less shitty. 
It should be easier to set up than boxes or metas because for them singulo is the main engine.

**Comment by PJB3005** [comment]
Why do people insist the deff SME is shit.

IT'S NOT.

**Comment by FudgePucker** [comment]
I know its not bad, it just needs to be better because its the only engine.

**Comment by Konater** [comment]
@PJB3005 
Nexis's implementation of the supermatter engine was poor (dude can't map I'm sorry) but that was okay because it wasn't the primary engine. Duny had a supermatter boner at the time he ported over defficiency which was fine but he made the mistake of copying over Nexis's design instead of bays assuming that the server would git gud.

Our server is unique in that our default supermatter setup doesn't work and exists to be a noob trap that you can't fix or set up unless you are a silicon or have a good understanding of how the game works.

The setup is unintuitive and no new player should be expected to be able to set it up which sucks because unlike atmospherics which is already set up generating power is necessary for the round. Ask around and I promise you people will say atmospherics will be one of the last things they learnt how to do.

The reason I think the supermatter is shit is because it generates both heat and radiation and is really hard to make balanced to set up in a reasonable amount of time. It should either stay as a toy for the mommis to play with and have another engine that is easy to set up as the primary or we port the bay (or hippie lmao) design.

**Comment by ghost** [comment]
I'd say keep going like you have been with tacking the rust w/ teg bay up near atmos. It's close to atmos to run fuelmix, canister fillups, and plasma pressurizing pipes. Shouldn't be too much work to socket the O2 and plasma outlets into a fuel mixer into the cyan. Layer manifold hashed H/E pipes, a scrubber stack to passive vents, then manifolded thermals into a 3x3/5x5, weld down a signaller-igniter, glass it off, go place the pumps for the hot outlet, cold inlet, and it's good to go. Probably about 20,25 min. Less if you cut back on the excess.  Another benefit from you having the TEG on the map finally is that Eng borgs can setup good power as well.

If they wanted to get power up but transfer into the rust it's not hard to add a double ended chute through the glass to get shit in/out.

You can do a <15 min sme on box. Reconfigure the chamber scrubbers. Dump the 4 TEG oxygen cans into the freezer and get that going. Replace the vent siphon with a scrubber if you don't want to have to micromanage the console. Layer manifold 5 vol pumps into 5 thermal plates in space and put a plasma can in it. Go get a portapump. Swap cans. Go empty plasma tanks. Pump the chilled plasma into the pump. Fill a tank for ~0.5-1 mw per collector. Then go emitter the shard open. Turn it off. 

It runs a little bumpy but generally just upping the pressure lets you cool it back off. Later in the round you can add some of the N2 cans to slow its energized level creep to keep it calm.

Can't see any reason why it wont work with the deff map but I haven't done it there so whatever.

Fudge, TEG isn't hard. It's mostly learning to not clog your outlets by having sufficient volume and pumps clearing it or to dump to space and go the overpressure route. Once you spend a couple rounds with a setup to tweak it just right it's nearly sing tier easy.

**Comment by PJB3005** [comment]
Output clogging is a lot less bad now that the TEG is correctly synchronized again. But yeah enough pumps is definitely a big boost to output.

**Comment by AutismSpider** [comment]
Are you crazy  Probe1?

people have hard time with the shard they shit the bed with the TEG

**Comment by Probe1** [comment]
TEGs are easier to design for beginners than engines that violently explode.  Ultimately we're either going to have a completely casual SME setup that requires no work so experienced players are dissatisfied and new players don't learn much, or an engine that's too complicated for new players and unless you're like you or me, a challenge to get set up before power starts dying in the halls.

I'm not married to this idea though.  It was just a thought on how to improve deffs engineering which still needs work.

**Comment by ihadtoregisterforthis** [comment]
A ~~rock~~ mineral that screams when it's uneasy is more explicit than a silent pipe with numbers, that hardly anyone can ride successfully.
"Do well or we are all doomed" works wonders for the shard and the singulo. Changing canisters in the dark and sometimes nailing it is terrible by comparison.
Make a better setup if needed, don't swap it.

**Comment by Kurfursten** [comment]
@ihadtoregisterforthis I actually believe the main reason new engineers are afraid to use the SME is because it announces issues over general radio. They're afraid of looking like an idiot when they start it up and the whole station is told: INSTABILITY 5%... 6%... 7%...

Maybe it should only announce over engineering radio. Singuloose doesn't announce at all.

**Comment by FudgePucker** [comment]
Late comment, I know that hand holding in most cases is bad, but I believe the best solution is to just make the the SME set up as easy and idiot proof as the singularity on deff. Add a sheet of instructions that an idiot can follow.

The cons are: hand holding, also it would be faster and safer than the singularity, any idiot can run in and provide power for the station. The pros are: no early shuttle calls due to no power, no rookies blowing up engineering, and it would help new players learn how SMEs work by providing an example they can look at in detail, rather than images and text. Also it would be good for advance engine techs, the SME isn't that hard of a challenge in the first place, especially when there's a R-UST halfway set up for you. Being able to quickly set up power gives you MUCH needed time to work on the most time consuming autism project. Every second counts when trying to set up the R-UST, when the time it takes to set it up is past the point that admins start mashing buttons to get the shuttle called.

**Comment by Probe1** [comment]
I will keep that in mind but I've tried to make the SME as easy as possible without offending the experienced players.

**Comment by FudgePucker** [comment]
As an experienced player I don't know how you could be offended by a nice simple set up on only one map, especially if you are having an autistic fit there's the R-UST to set up to get HIGH NUMBERS to masterbait about.
