### ISSUE TITLE
Remove Bus Station from high pop map rotation

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#10337]
Everyone hates it, it's worse than taxi and yet it's available for shitters to vote before leaving the server on high pop.
There are no votes happening to ask the server to have it removed for now from rotation and I beg of you to open a poll during high pop to check what people want.

**Comment by 9600bauds** [comment]
Seems to be inspired by a post that happened a couple minutes before this issue report
![firefox_2016-06-01_12-50-14](https://cloud.githubusercontent.com/assets/6526157/15716106/6516a0dc-27f7-11e6-9662-b1b7ff2ac433.png)

**Comment by Gringonius** [comment]
I made this before the post showed up on my end, it's common practice to vote for the perceived worst maps before leaving the server just to see the tears in OOC.

**Comment by Kurfursten** [comment]
It should be restricted to lowpop like Taxi was anyway. It wasn't made to be played during high pop.

I don't think it's worse than Taxi though - I think that shows a poor memory of what Taxi was. That's just emotions running high because launch week of course.

**Comment by Gringonius** [comment]
The only thing I can picture Taxi doing worse was splitting research between two stations. Medbay in particular got severely improved there and suddenly the map was discontinued.

**Comment by Kurfursten** [comment]
If Medbay is a concern, please check out the discussion. There's a new build that will probably get pushed today which has received a lot of player input.

I'm sure you have some worthwhile input too, so go have a look at the newest screenshot.

**Comment by Probe1** [comment]
I will make a poll to further the discussion.  I haven't seen a majority say they dislike it.  I think like most things, the people who dislike it are very vocal about disliking it.  Which is good.

**Comment by Kurfursten** [comment]
If you do a poll, make one of the options to "restrict to lowpop like Taxi was"

I do want to point out though that this week has been wonderful for feedback. Even on the test server I was just getting people who were saying "good job". They had very little real criticism on github or on the test serb except to help me find missing wires or lights.

It took real-world testing to get some honest criticism about medbay. Not one complaint about it until it went live, and it was on github for 5 months. I'm not saying medbay was good - I'm saying we will never get it in good condition without some critical examination that just doesn't happen on test serb.

**Comment by Megamaw** [comment]
Common practice? You mean, what you do, so you think everyone else does it?

Nice.

**Comment by icantthinkofanameritenow** [comment]
I'll be blunt- in my current experience, the only difference between this and Taxi is that this has bigger shuttles. That's it. 

The whole premise behind this and Taxi was a mistake.

**Comment by Gringonius** [comment]
> Common practice? You mean, what you do, so you think everyone else does it?
> Nice.

I thought that people discussed about the server on Github and the forums exactly to avoid shitposting.
![1464836281545](https://cloud.githubusercontent.com/assets/6732634/15732622/3c2ba63c-2855-11e6-9a3e-395e25892df9.jpg)

**Comment by Kurfursten** [comment]
Look - I think this whole argument is a distraction, but the fact that only one person did it proves that it's not a "common practice", it's one person abusing the system. Just ban the guy.

_Obviously I'm being facetious for effect, but it was pretty dumb repost this comment in the thread without context_

**Comment by Gringonius** [comment]
Banning the guy for what? He did not break any rules.

**Comment by Kurfursten** [comment]
Why post it in this topic? It demonstrably proves you wrong - only one person is apparently voting for Bus. If it's only appearing 3% of the time, I'd say it's doing more to help with feedback than it is hurting the server.

If you want to talk about the merits of a weighted vote system rather than the map - that belongs in a different Issue, don't you think? Post about it here:
#9642
#9640

**Comment by Gringonius** [comment]
This is not about the voting system, this is about the map. Weighted voting system is fine, Bus as we have it now is not. People vote for the map exactly because it's Bus, even Deff is now a mostly functional map.
And how exactly is one single poll proof that bus gets 3% of votes every time? It's often getting 20-30% of votes because of the current perception of it and people leaving for the next round, the same type of behavior demonstrated by that guy. Have you actually been playing on the server lately or are you simply pretending otherwise?

Regarding another subject because you mentioned feedback, what happened to Taxi? It was a better map, we saw lots of improvements on it and now it's gone, replaced by this much rougher map instead. What happened to that feedback? Thrown into the trashbin along with Taxi?

But anyway, I'm straying from my main suggestion that is enabling it to be voted only on "low pop" similarly to Taxi. The amount of players to be considered that would obviously be open for suggestion.

As it is I just feel that when admins do bus rounds to end the round early because it's Bus Station for the third time in a row is enough evidence that the map is not ready to be this easily available for weighted voting.

**Comment by PJB3005** [comment]
Sadly we can't control low-pop only, gonna have to bug pomf.

**Comment by MercuryDoll** [comment]
> even Deff is now a mostly functional map.

After how many months of people bitching it's "unplayable"? "maint op", "it's too big", "map is shit!", all complaints made simply because it wasn't box. After a month or two of people actually having to play it now and then, there were finally issues opened on github to fix and improve the station map and suddenly people were like "well, it's still not box but it's okay i guess".
And my believe was that Bus was made in response to the Taxi feedback, sort of like a rework or "taxi 2.0".
Honestly, your complaints seem more targeted at the weighted voting system instead of the map itself. Request an upgrade to the voting system, let them add logging to see who voted for what, add vote banning, make it limit how many times in a row a map can be played or eliminate map choices below a percentual vote threshold. But don't blame the maps if people abuse the vote system.

**Comment by ComicIronic** [comment]
Yeah, we can't obligate players to play on maps they vote for.

**Comment by SysadminJeroen** [comment]
I like Bus, because I see potential in it and it can be improved massivelyb
Op 2 jun. 2016 17:59 schreef "ComicIronic" notifications@github.com:

**Comment by icantthinkofanameritenow** [comment]
I personally can't see exactly what the draw is to begin with. If you don't make each of the sub-stations self-sufficient, then you're inevitably going to run into trouble. At the very least, each one ought to have its own engineering area even if it's just a PACMAN attached to a SMES.

**Comment by ComicIronic** [comment]
Wait, how are the other stations powered?
They should be using the portable SMESs if they're anything like Taxi.

**Comment by Gringonius** [comment]
Changed the topic name since I guess it was a bit misleading.

**Comment by Kurfursten** [comment]
If you're just trying to remove it from highpop, I support that. It was _never_ intended for 40 players. Cozy turns to cramped quickly.

@ComicIronic @icantthinkofanameritenow The individual stations can be powered by your choice of portable SMES or solars. Engineering also spawns with 2 PACMANs and there are 2 more in maint somewhere. If you like, you can also connect the stations to one grid with an RCL, as they are much closer together than on Taxi.

**Comment by SysadminJeroen** [comment]
They are using portable SMESs.

2016-06-02 20:49 GMT+02:00 ComicIronic notifications@github.com:

**Comment by icantthinkofanameritenow** [comment]
> portable SMES

The ones that are so easily spaced or hidden in the ass end of nowhere? No, each station should have its own as well as a way to charge it.

And honestly, the stations should connected in the first place, buses or taxis (or whatever you feel like calling them) do nothing but waste people's time. Even those transport tubes that barely work would be better, for fuck's sake.

**Comment by SysadminJeroen** [comment]
@icantthinkofanameritenow There are about 6+ portable SMESs on the station Z-Level.
Box SMESs and pretty much all of the engines in the game are way more vulnerable.
Three Portable SMESs disappearing is not really a problem.

**Comment by icantthinkofanameritenow** [comment]
@Jeroen52

And yet with fewer places where they can be charged plus a very easily disrupted powernet equals even a single cut with making an entire sub-station go dark for much longer than it ought to. Any advantages they could provide are effectively made irrelevant due to the lack of redundancy inherent to the map, to say nothing of how simple it is for a breach to leave one permanently screwed over due to atmos fuckery being so much harder to fix.

**Comment by SysadminJeroen** [comment]
@icantthinkofanameritenow It is more difficult to fix, but it is also more difficult to cause problems in all stations.

At Box I know a single cable that causes a power outage in 90% of the station, pretty much anything but Engineering will be drained of power. If no Engineer knows how to fix it, the station will stay unpowered. I don't hear you about that.

The stations must have some weaker spots, that makes it fun.

**Comment by icantthinkofanameritenow** [comment]
@Jeroen52

But most of those weak spots aren't in spots where a single stray meteor has a high chance of hitting it. And unlike your example, one station going down means that they'll all be crippled for a long time afterwards because of how dependent they are on one another. 

MiniStation would be an exponentially better station for lowpop in every possible manner.

**Comment by Kurfursten** [comment]
I'm kind of confused by this discussion because it's actually the reverse of what I think is true. Bus is actually easier to repair but easier to bomb. Think about this:

> It requires more wire cuts to completely disable Bus power than Box
> Unlike Box, Bus has 3x as many gas miners, dedicated to smaller rooms, meaning atmos stabilizes much faster
> Flooding gas on one station does not endanger the other stations at all
> Repairing a breach requires less material because all rooms are smaller

The fact that Bus is easier to bomb is the reason that there are only 2 TTVs and the singulo was removed.

**Comment by SysadminJeroen** [comment]
@icantthinkofanameritenow If you want to, I can add some grilles to spess to make sure that a meteor can't hit the engine as easily.

**Comment by icantthinkofanameritenow** [comment]
@Jeroen52

Remember that some meteors go straight through grilles now, because Dylan. You'll want a.couple layers of rwalls at the very least. 

And you don't need to fuck up all the stations to make it unplayable. Fucking up the engineering or medical stations alone will bring everything else screeching to a halt - that's what I mean by it being so easily disrupted. Unless each station gets its own medbay (or a clone pod at minimum) and generator, it only takes one bomb to end the round.

**Comment by Kurfursten** [comment]
Wait, are you saying that if you bomb medbay on Box with a maxcap bomb, the round won't be over and players will rebuild?

Amazing. I've never seen the /vg/ players you're talking about, but I want to play with them.

**Comment by icantthinkofanameritenow** [comment]
@Kurfursten 
Just because you haven't seen it doesn't mean it doesn't happen. 

But by the very nature of Bus being bad for high-pop, the few people willing to do that will shy away from even playing that map in the first place. Again, all that would be necessary to fix bus is to make the three stations stop being so dependent on one another- make it so that if one of them were to suddenly disappear for any reason at all, the other two would be completely unaffected by its absence. Only then will it actually be a good map as opposed to three station-pieces that fall apart when even one ceases to function.

**Comment by Kurfursten** [comment]
I'm not saying it should be played in high pop.

More directly, I am not sure if you actually mean what you're saying. Completely unaffected? That means you want three medbays? Three cargos? Three R&D desks? Every department would be a ghost town if you have to spread out 1 doctor for each medbay. I don't actually believe you can have more than one cargo with our current code. But the only station that has an extra medbay in case the first one gets bombed is deff.

The concept seems so silly that I think I must be misunderstanding you. Do you mean you want a brig medbay like on Box? I might be able to find some space for a sleeper and scanner.

**Comment by icantthinkofanameritenow** [comment]
@Kurfursten 
Something like that. Essentially, a way that each station has some kind of way to take care of its medical and power needs without outside help should that be needed. 

If they're going to be split up as they are, it's only fair.

**Comment by Kurfursten** [comment]
They all have solars to take care of power, or you can use the provided portable SMES, or the provided PACMAN. That's three ways, as many as three ones.

**Comment by icantthinkofanameritenow** [comment]
@Kurfursten 
Acceptable, for power at least. But that doesn't matter much if the cloner is gone and there's no other way of getting people back into the round.

**Comment by Kurfursten** [comment]
R&D (pAI), Xenobio (Golems, Borers) are on SecSci
Botany (Diona), Mechanics (rebuild cloner) are on CivEng

We're pretty well spread out in that eventuality. But you know, maybe it would be nice to have a sleeper in each of the three EVAs. They're for emergencies after all.

**Comment by icantthinkofanameritenow** [comment]
> implying mechanics ever rebuild anything

**Comment by AutismSpider** [comment]
>mechanics

>build/fxi or set up power.

no fuck off mechanics is a meme job we should not have a job/should be part of sci only and not engi

**Comment by ComicIronic** [comment]
That cloner criticism is just as true of Box or any other map.
Please stay focused on issues specific to Bus, or make a new issue.

**Comment by icantthinkofanameritenow** [comment]
But Box isn't split into three pieces like Bus is. They should have another way of connecting them other than the buses. Like some kind of bridge or the transport tubes.

**Comment by ComicIronic** [comment]
but why

The whole gimmick is that you move by Bus. You can spacejump if you have the equipment,  but adding another way of moving isn't compatible with the map idea.

**Comment by icantthinkofanameritenow** [comment]
Because IMO, the gimmick itself is the root cause of many of these issues. The idea simply does not work as well as you think it does.

**Comment by Kurfursten** [comment]
There are a few ways to get between the bus stations
- Use the taxis
- Space sorter (somewhat dangerous but totally viable, you can rest and heal at the sort sat)
- EVA (pod or suit - there are 11 public suits and 5 public pods at shift start)

I don't really get what this has to do with having an extra cloner though. Transport tubes definitely would not help with transporting bodies for cloning. As far as I know, you still can't remove bodies from them.

I thought you were kidding with me though, because you were making a reversal on what I said (I said: 'engineers never rebuild after medbay is bombed', then you said 'mechanics never rebuild machines')

**Comment by icantthinkofanameritenow** [comment]
Part of it is that on Box or Meta, at least you can get the corpse to cloning fast enough to ensure that the person who it belonged to hasn't given up on it being cloned. You can't just wait indefinitely for the buses and dead people can't use EVA or sorters to get there. 

Plus, taxis still take too long to move between stations. If it's going to be used on anything but deadpop, they should move from one to another instantly. Hence my request for other, more efficient methods of travel (e.g. bridges; you don't need to wait for them, and unlike space pods or suits nobody can just take one and fuck off into space never to be seen again- to say nothing of the fact rhe generic space suit won't even allow you to hold a full sized oxygen tank in its storage, making it useless for anything beyond a last resort). 

And I wasn't making a reversal so much as pointing out a fact. I have yet to see mechanics actually rebuilding any machines at all, even in the best of circumstances. In practice, they're just assistants with more access and a potentially useful gimmick they never use to its full potential.

**Comment by Kurfursten** [comment]
Paramedics have access to telescience to alleviate your concerns. It's pretty prominent in new medbay.

I'm just not seeing it. It's not a long walk, you actually physically can't be more than 100 tiles away from a Taxi on any station (this is the same distance from the cargo desk to the medbay entrance on Box). So it's actually twice as fast to recover a corpse from any room on Taxi than it is to move one from Box arrivals to Box medbay.

If the discussion is about lowering the cooldown/travel time on Taxis though, maybe that deserves a separate discussion. I'm not opposed to it.

**Comment by AutismSpider** [comment]
people really didn't like taxi.

Some one Makes taxi 2.6.7b people hate that too.

If it was a snow map/not fucking space it be less shit you could just suit up and walk to other parts etc

**Comment by Kurfursten** [comment]
We're getting pretty far off from the topic here. I'm not even sure what this issue is supposed to be about anymore. Remove it entirely, or just from highpop? If this is the topic, why aren't people discussing the number it should be limited to? I'd say 15 or 20, around Taxi levels. But instead we're getting:
- Weighted voting is abusive!
- Bus doesn't have enough cloners
- Why don't mechanics rebuild medbay?
- Why don't the taxis travel instantly instead of after a 1-second delay? Why is there a cooldown on taxis?
- Why isn't Bus a snow map?

These don't have anything to do with the ostensible topic of this issue. And some of them are even valid things to talk about - maybe we SHOULD talk about adjusting the travel time on Taxis, for instance. But those deserve to have their own issue where people can talk about them. Arguing aimlessly in this thread isn't getting us anywhere, so I'm not going to. You have my opinion on what the player limit should be.

**Comment by icantthinkofanameritenow** [comment]
And my opinion is that there should be a hardcap of 25-30 people on the map at roundstart at most.

**Comment by Gringonius** [comment]
Between the range of 20-30 sounds good since I guess that Bus is meant to be slightly bigger than Taxi after all.
And talking about deviating from the topic and complaining about the map, I can't find a defibrillator recharger at medbay. I used to think that I'd find something of a single open issue for people to post about issues in a new map instead of having to create a new one for every single problem you find.

**Comment by SysadminJeroen** [comment]
@Gringonius It makes managing issues way easier if you make a new issue per mapping problem.
There is a [Mapping (Bus)] tag that can be added to an issue, you can sort issues per tag if you use tags.

**Comment by Gringonius** [comment]
I just hope it's not frowned upon to ignore all those issue creating guidelines other than checking if there's not a current existing one for such a simple issue.

**Comment by Gringonius** [comment]
Nobody told me this happened. I thought bus was being temporarily removed to be added back later.
