### ISSUE TITLE
Port scheduler improvements.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10339]
The scheduler has gotten some improvements on paradise and on goon (510), we should port them.

**Comment by Probe1** [comment]
@mrstonedone is also doing a MC improvement if you wanna look at that

**Comment by PJB3005** [comment]
Yeah but that's stonedMC

**Comment by clusterfack** [comment]
mfw people name a system after themself

**Comment by ComicIronic** [comment]
Reminder to vote for Comicstation

**Comment by PJB3005** [comment]
No PJStation will be best when I finish that map.

**Comment by MrsTonedOne** [comment]
Mine is in theory better because it allows the subsystems to control how they are prioritized, and how the tick is split up between things that want to run, but you guys could only see that being useful for lighting. I mainly use it so mob gets more runtime then objects/machinery if they all want to hog the tick because resolving stuns is more important than singulo processing or power ticking. (and so atmos gets only idle cpu)

(Unless this limitation was removed in GoonPS)

Edit, GoonPS lets you set a max runtime in tick percentage, whereas StonedMC uses a tick budget system so that it can take all running processes into account, rather than a flat run for static_number_here% of a tick.

But don't worry, I fully expect GoonPS to absorb some of StonedMC.

**Comment by DamianX** [comment]
#13270 brought stonedmc
