### ISSUE TITLE
flashlights not working if they're in your belt or in your pockets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10404]
(WEB REPORT BY: cumoverme REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> ee861b2231d95dbe3c1e56a4dd8343a905afbedc
> 
> General description of the issue
> Flashlights, flares, PDAs and others lighting only work if the item is on your hands.

**Comment by ihadtoregisterforthis** [comment]
Note that this happens since before pillow lighting.

**Comment by Blithering** [comment]
I noticed that when this happens, switching the light off and on fixes it. Might be something to that.

**Comment by ghost** [comment]
So hold on, this has been happening for how long ?

**Comment by SysadminJeroen** [comment]
As far as I know since Goon lighting.
Op 7 jun. 2016 07:53 schreef "dylanstrategie" notifications@github.com:

**Comment by dylanstrategie** [comment]
@PJB3005

**Comment by PJB3005** [comment]
Just did some testing and it turns out to be @unid15's fault. #10045 is causing more calls like `dropped()` and such, but most importantly on `equipped()`: **the `loc` of the item is the turf when it is called**.

Before hand refactor: https://dl.dropboxusercontent.com/u/107028026/ShareX/2016/06/2016-06-08_13-52-21.webm

After hand refactor: https://dl.dropboxusercontent.com/u/107028026/ShareX/2016/06/2016-06-08_13-38-57.webm
