### ISSUE TITLE
Changeling cannot regen in lockers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10414]
(WEB REPORT BY: chainsauce REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> e8432f9aadc20196a267dcf3c0058da3c50cdd0e 
> 
> General description of the issue
> Ling cannot regen unless they are on a turf, and as such I was unable to regen while in a locker
> 
> What you expected to happen
> To be able to regen while in a locker
> 
> What actually happened
> When I pressed the regen button I go the message
> ((Due to a BYOND bug, it is not possible to come out of regenerative statis if you are not on a turf (walls, floors...)))
> 
> Steps to reproduce if possible
> Be in a locker and try to regen

**Comment by clusterfack** [comment]
>((Due to a BYOND bug, it is not possible to come out of regenerative statis if you are not on a turf (walls, floors...)))

Wow I WONDER WHY IT FUCKING HAPPENED THEN

**Comment by clusterfack** [comment]
Like seriously how dense can you be

**Comment by clusterfack** [comment]
Who does he think put that message there?

**Comment by clusterfack** [comment]
What does he think its there for?

**Comment by clusterfack** [comment]
Does he think we were withholding a fix for shits and giggles that we will now put out?

**Comment by ComicIronic** [comment]
Can an admin go on the server and permaban this guy so he can appeal to prove he's literate

**Comment by chainsauce** [comment]
Eh, I reported it because an admin told me to
[15:59:41] PM to - Admins: Just tried to regen while in this locker and it gives me "((Due to a BYOND bug, it is not possible to come out of regenerative statis if you are not on a turf (walls, floors...)))" what the heck
[15:59:59] PM to - Admins: Did this locker just defeat me forever?
[16:08:01] Junkmin PM from-Kammerjunk: That sounds DUMB and I thought the update that made you able to use bags in lockers would also fix this. Should probably bugreport it
[16:08:11]  PM to-Kammerjunk: Will do

**Comment by clusterfack** [comment]
Not even REMOTELY related

**Comment by ComicIronic** [comment]
Can someone perma that admin
