### ISSUE TITLE
Prevent MoMMIs from emagging other MoMMIs

### ISSUE THREAD

**Issue by MercuryDoll** [d3athrow/vgstation13#10469]
So we don't have this discussion every other thread.

**Comment by ihadtoregisterforthis** [comment]
> coding away the thread

**Comment by ghost** [comment]
:+1:

**Comment by Intigracy** [comment]
Prevent un-emagged MoMMis*

**Comment by Exxion** [comment]
Or, rather than physical restrictions like that, we could just add a law to Keeper that says something along the lines of "Do not allow your laws to be changed."
Could justify it with keeping the station's repair squad functional or something

**Comment by 9600bauds** [comment]
Being emagged impairs your ability to improve or repair the station, so that's already a violation of law 3

**Comment by AutismSpider** [comment]
law three covers that Exxion.

need way stop non emag mommis form emaging other mommis

**Comment by Exxion** [comment]
GOD FUCK SHIT FUCK DAMN I'VE EXPLAINED THIS THREE GOD DAMN TIMES ALREADY
Law 3 does not say you must prevent the station from not being repaired, it only says you must repair the station
It has no clause against inaction, like Asimov does
If you allow yourself to get emagged, you are not breaking your laws, because they only apply while you have them

I definitely explained this better last time we talked about this
