### ISSUE TITLE
Randomize plasma properties each round.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10474]
Right now, plasma has nothing unique about it. SS13 is about researching plasma goddamnit!

So I suggest plasma gets modified stats each round, yes it'll still burn but factors like the following would be different (within reason):
- Optimal burn mix ratio
- Burn CO<sub>2</sub> output
- Heat output
- Rad collector output
- Heat capacity
- Mass density (does this even matter in SS13?)
- etc...

**Comment by ghost** [comment]
oh dear oh dear oh dear oh dear this sounds bad

**Comment by Shadowmech88** [comment]
I can't foresee the players hating this _at all_.

**Comment by ComicIronic** [comment]
You just invented a reason to implement a way to get more TTVs.

**Comment by PJB3005** [comment]
@ComicIronic, no, I did not.

TRUE SCIENTISTS would learn how to determine the properties and then work with them, a derp making bombs to ~~grief~~ be a traitor now needs effort.

**Comment by FudgePucker** [comment]
No.
WHY WOULD YOU SCREW OVER ENGINEERING LIKE THIS?

> shuttle has been called: plasma sucks here and the engineers are on strike

**Comment by ghost** [comment]
does give me a pretty neat idea though - what if science can research different types of plasma which have different properties like described in the OP?

**Comment by PJB3005** [comment]
@FudgePucker the difference in properties wouldn't be bad enough to make engineers go "fuck this shit".

**Comment by ihadtoregisterforthis** [comment]
[muh emulsions]

**Comment by Killette2** [comment]
Even I wouldn't suggest this!

**Comment by kol1th** [comment]
> get a shitty roll with plasma rad collector output
> 200kw from cold plasma with the SME

this can't go wrong

**Comment by Killette2** [comment]
Non plasma related engines when? AME and solars don't count because they're boring. Pacman don't count because it's a generator and not an engine.

**Comment by Megamaw** [comment]
I'd say I've heard worse ideas, but I'd be hard pressed to think of anything dumber than this.

@Killette2 
I once pitched 'the Heredth Engine' but no one liked it.

**Comment by ghost** [comment]
Inputting RNG to a game is a good way of adding 'unreliability' to a strategy, but it can also tick the users off if they have to forcefully adapt to whatever the RNG has chosen for them.

It's why any attempts to redo R&D are generally disapproved of and genetics is fairly avoided.

You could have elements of 'Biased' RNG that do work well with players, such as how mining resources are distributed (Some are higher yields and less danger, but less common (unless the map is Meta))

My 2 cents is keep it as it is, and simply have different ways for the player to treat plasma for it to do certain things (We already have plasma in solid, liquid and gaseous states, so that pretty much covers that, but having some way to treat each state to convert it into another state could be interesting)

If we were to make a way to make plasma gas solidifiable or condensive, we would have to do away with the roundstart plasma miner however, so atmos doesn't equal infinite money.

**Comment by Probe1** [comment]
lol yea cause our RNG jobs are SO popular :laughing: 

A little rng helps stretch the game.  This level of rng makes jobs tedious as fuck.

**Comment by PJB3005** [comment]
> This level of rng makes jobs tedious as fuck.
> 
> (within reason)

Are you guys not reading half my fucking post Jesus Christ.

**Comment by Killette2** [comment]
Honestly, not really.

**Comment by Killette2** [comment]
Memes aside, what is the point of this suggestion? This seems not only like a lot of nerfs, but a lot of field testing to see how SHIT your plasma is this round. Where is the good? Slightly hotter fires? Who cares!

If there was a gas you could mix with plasma to make a modified plasma however, that has these unique properties, then maybe that would be worth studying instead of fucking over our reliable gas. Also this neo-mixed plasma should have at least one positive property over normal plasma, to make it useful after being discovered.

**Comment by Shadowmech88** [comment]
I believe the good is supposed to _be_ the field testing.

**Comment by Killette2** [comment]
Do you think I test large artifacts first or drag them in the bar for quickest results?

**Comment by Probe1** [comment]
@Killette2 has the right idea about how it should go.

**Comment by Killette2** [comment]
All my ideas are good, friend :)
