### ISSUE TITLE
The Great Lockbox Issue

### ISSUE THREAD

**Issue by icantthinkofanameritenow** [d3athrow/vgstation13#10487]
So we all know how laughably easy lockboxes are to open, and how Sci can flood the station with guns at will if they're so inclined. 

Thus I'm thinking that perhaps the lockboxes could either be made indestructible or send an alarm to Security if opened in any way other than with an ID with access or emag. Thoughts?

**Comment by 9600bauds** [comment]
Making them indestructible is probably not good due to station emergencies like newcops or blob or such.
Speaking of, during emergencies, you often come to the situation where Sec gets a few lockboxes, but they require armory access. There's often no Warden/HoS, so the lockboxes get blown anyways.

I definitely think we should try the "make them broadcast your purpletidery in Sec channel" approach before something more drastic, see how that works out.

**Comment by Exxion** [comment]
Lockboxes should definitely be _harder_ to open without access, but not impossible
But I can't think of any good way to implement that

**Comment by icantthinkofanameritenow** [comment]
@9600bauds 
And what's Security going to do about it? Most of the time they just end up looking the other way in exchange for getting a gun or two themselves.

If people need the access badly enough, they can bug the captain or HOP, or nick the spare. Plus, there's a whole bunch of constructable weapons that are plenty powerful, and they need no access at all.

**Comment by Exxion** [comment]
Maybe breaking open the lockbox could damage the gun and make it less powerful or have a chance to jam or something so that there's an incentive to opening them the right way, but they can still be broken into

**Comment by 9600bauds** [comment]
You'd need to interact with Sec. You can't be sure of how they will react. This is already a huge deterrent for some spergos.
Even if they can probably get away with it, just the actual _possibility_ of consequences stops some types

I say we definitely should try it first.

**Comment by Zth--** [comment]
I said it before, and I say it again. Make it so printing guns is only doable on red code. This solves pretty much everything. Borgs use this system, why guns not? It also adds another reason to start using the god damn red button

**Comment by Imagebard** [comment]
Idea
Lockboxes give a warning signal to security SPSes when forcibly opened.

**Comment by Imagebard** [comment]
I like what @Zth-- said more but I wanted to put that out too

**Comment by icantthinkofanameritenow** [comment]
@Imagebard
Security looks the other way half the time. 
Especially because the regular officers are bribed with new guns. 

An SPS alarm won't mean shit.

**Comment by icantthinkofanameritenow** [comment]
@Zth-
I don't even know if the code for something like that exists. You'd have to make it yourself from scratch.

**Comment by Shadowmech88** [comment]
> Make it so printing guns is only doable on red code

So if there's a threat and the heads are missing, the crew's just shit out of luck?
Bear in mind you need two heads to trigger code red.

**Comment by icantthinkofanameritenow** [comment]
@Shadowmech88

What, the blunderbusses and railguns you yourself coded not good enough anymore?

**Comment by Shadowmech88** [comment]
Railguns are meant to be a reward for Engineering autism, they're not feasible as a standard go-to weapon in case of emergencies since they need so much power to deal decent damage.

The blunderbusses are a fair point, though they're really only effective if you've got a small group of people that each have one and focus fire on a single target.

**Comment by Killette2** [comment]
What if the blue wires of the protolathe actually did something?

**Comment by clusterfack** [comment]
Whoa there buddy, let's not get crazy

**Comment by ghost** [comment]
You've a bit of an obsession with nerfing science and buffing security, man.

**Comment by Imagebard** [comment]
Maybe because they deserve it?

**Comment by ghost** [comment]
icantthinkofanameritenow, stop making 57 duplicate issues about the same shit cause science touched your nono place until only the people who hate it show up.

**Comment by icantthinkofanameritenow** [comment]
Only when they stop being purpletiding shitheads. You've been their biggest apologist for ages, and I get the feeling you're just opposed to anything that might make them learn their place.

**Comment by ghost** [comment]
Yeah, cause you don't care if you burn the forest down to get at a chipmunk. It's not a code issue and the issues being fragmented all over keeps sidestepping it. Code blue when you're supposed to. Random search if you get itchy and brig them for their big backpack of crime. If they go full retard then they'll get banned for being scitiding pieces of shit.

**Comment by icantthinkofanameritenow** [comment]
@SarahJohnson489 
All of that would be true...IF we could consistently get more than a skeleton crew of Security staff on most shifts. Even then, most Security players (e.g. Trinity) seem to be hopelessly inept at their jobs to the point where they may be worse than no Security at all. 

If it's not a code issue, how are we supposed to fix it- by bribing people to play as Security more often when it's the most hated role on the server, or have their shittery be overlooked more often when they do act up? Face it, we need _some_ kind of coding thing to act as a stopgap at least if only because it's so much simpler to implement than trying to change how people play. I'm not so stupid as to assume changing lockboxes alone will fix that, but it'll be a passable start if nothing else.

**Comment by ghost** [comment]
Lowpop gonna lowpop. It's gotten better with more thorough admin scrutiny on dindu ahelps and weaker protection on greytiding.

There's nothing to face cause it's fine. You're the one that needs to face it. Oh wow, gee, how about this. There's no security and now you're trying to code your way around people being able to defend themselves cause gunsci touched your nono place and you don't want to actually have to enforce space law. Making it that much worse in the larger "team' modes like blob/xenos/rev/cult/wiz/nuke where either side needs to arm up better to shoot at each other and all the shit you'll say about just ask sec/command dey sum nice bois who aways there and rdy 2 open is crap and you know it. You don't even see that cause you're hellbent on on a problem that's minimal at worst. They can already confiscate and be in the right to do so. They can keep confiscating until it's a permabrig and if the tider ever escalates they're fucked when the admins are brought in. That doesn't change if you're one man or one of seven. And if there's none then so the fuck what. All you're doing is fucking shit up when people actually need the stuff for nothing.

Making the god knows how many duplicate issue of muhgunsci/muhlockbox issues isn't helping.

**Comment by icantthinkofanameritenow** [comment]
It's not that so much as nobody actually being able to enforce law sufficiently enough to bring gunsci under control if they do go full retard. I don't know about you, but I don't play Security constantly and I don't expect to have to do their job when I spawn in as RD or Station Engineer or whatever. 

> when people actually need the stuff

There's plenty of ways to kill people without guns as well as with them, and more than once I've seen newcops foiled by nothing more than a simple banana peel. Besides, how could making lockboxes sound an SPS alert to security somehow limit people's access to guns when they really need them? 

Honestly, I'd prefer you keep the childish personal attacks to yourself. All I want is a harder safeguard that doesn't strictly rely on admin tard-wrangling or a security force which isn't always there. I do enforce space law when I have the ability- but just as often, I do not, and neither do many other players. At the end of the day, it's silly to just keep pretending the issues will go away if you just keep shouting that they aren't as bad as they look, and there's surely some way that the odds can be pushed just a little more in Security's favor, as opposed to assuming that they'll be able to babysit Science exclusively.

**Comment by ghost** [comment]
We went over it in one of the god know how many duplicates of this and it bottomed out at you just wanted to code your way around shit that was fine cause you didn't want to have to enforce space law as security and you don't care how much damage you do to everything else to get it. What you campaign for is just victimizing the most vulnerable people in the worst staffed rounds while doing fuckall on the rest. You don't even accomplish what you want. Security already has plenty of favor until they get eviscerated by the almighty lube chloral prick killstrip while ignoring the buddy system which has nothing to do with gunsci.

The sps is a great idea now that we have that functionality. As useless as ied/explosion explosion in ghetto bar/art/lockers has been but whatever gives you a cookie before it's time for a glass of milk until everything is gone.

**Comment by Probe1** [comment]
fwiw the last time we did this I discussed how pants on head retarded it was that security can't open stun revolver lockboxes but scientists can with very simple methods.

**Comment by icantthinkofanameritenow** [comment]
@SarahJohnson489

How long are you going to just make baseless accusations about my ability simply because you disagree with me? You're only making it seem like you think the current system is absolutely perfect when it does need improvement - even if that improvement is not what I would prefer it to be either. 

Sure, an IED alone won't get Security's attention but if it's reported that it was to open.a laser cannon lockbox you'd bet they'd do something. If they're as competent as you say they are (or ought to be), that would be their cue to run in and confiscate it on the spot. 

If your issue is that people won't get access to guns when they need them, perhaps it would be better to make some lockboxes require only Security access instead of Armory access. That should be an acceptable enough compromise to make it so the people who do need guns can get them more easily. Surely you would be amenable to that?

**Comment by ghost** [comment]
Because it wasn't baseless? That's how it went out in those duplicate issues and ooc. It's not perfect but it's still where when shit breaks down it can still be handled by whoever you can drum up instead of go crawl in a locker.

4/5 it's somebody blowing something open cause they do fuckall otherwise. And when it isn't it's x threw it at y and it's case closed. The point anyway was it was already in the wind and it could be anybody cause there's only a couple of us who bother to lock the console. Majority of people didn't care before and they wont after cause the majority blowing them don't give a shit and are just tired of being naked husks in space for 2 hours and the problem chilluns you dig through when they're suspicious enough anyway.

Yeah, stun revolvers and most of the fab guns definitely should have been sec from the start.It was always silly to have to ied or shoot open a stack of AEG's so the officer could go shoot up xenos or whoever ran off with the armory this time. I just don't like the shit that makes it hell for people to get at guns while it's nosec, lowsec that doesn't care, nobody can rustle up a cargo id, anyone who can is off being rambo and shit like that. I went through when it was an id or bust and no. Never again.

**Comment by Gringonius** [comment]
SHALL
NOT
BE
INFRINGED

**Comment by icantthinkofanameritenow** [comment]
Understandable; perhaps the biggest issue is the server's general  hostility to security warding off people from playing it in the first place. I admit that I am not the greatest Security player ever and don't expect to be,but I can say at least that I understand and am ready to enforce Space Law. But on rounds where there's one or two officers at most Space Law becomes little more than a bad joke.

What happens when there's nobody else to drum up? In the situations you describe, you can't always count on there being a way to get others to switch jobs so they can help you.

There has to be a way to get more people to join the redsuits short of making X number of.officers mandatory for certain round types to start, right?

**Comment by jknpj** [comment]
Alert silicons about lockboxes being destroyed. I'm sure they'll enjoy their asimov valids.

**Comment by icantthinkofanameritenow** [comment]
But MUH POTENT HAM

Seriously, that might not be a half-dead idea.

**Comment by ghost** [comment]
The increased scrutiny and occasional ban for dindu ahelps has helped. The lower protection on greytiders who got killed or perma'd for their heap of repeat crimes has helped. Some of the baww admins are mean are from people trying to be the punisher instead of sticking pretty close to space law. The hugh's eventually run off the rails hard enough to either get or take a vacation.

Self-preservation is generally alright. If nothing else you just gotta rambo till you go down or come out the other side.

Not really and that's kind of down to what space is. Some just aren't up for the experience. Some feel they aren't ready. Some just can't let the dindu squawking slide right off. Some just want to do other things like a walking mushroom fight club. Some just don't like having the target on their back. Some just don't like the down time when they could be doing something more engaging to them. Especially in the lowpop nothing happening/oh god everything is terrible or and now it's pseudo-extended until crew transfer experience. It's a pretty tight focus and the people coming to space have a wide variety of stuff they come for. Always nice to see a full team in higher medpop and highpop though even if there's a lot of harping about the buddy system, using hudglasses, retag the sec gps and shit.

**Comment by Intigracy** [comment]
Lockboxes are fine as-is t b h

**Comment by 9600bauds** [comment]
That's not very constructive
Would help the discussion if you said why they're OK to you

**Comment by Intigracy** [comment]
You already have to have enough materials to make the item in the protolathe, as well as science access to use it.

You have to have already done research to get to the point where you can even print one out.

You have to cause an explosion to even get it to open without an ID with access / an emag. Making emags the only counter to ID access is not good game design.

Increasing the metal/glass cost of assault rifles (which is what spawned this entire issue in the first place) to the levels of the hookshot would be a great start, the hookshot honestly shouldn't be so expensive anyway.

The only reasonable alternative I've seen in this entire discussion is having a chance to break the gun if you explode it open instead of opening with an ID/emag.

Also sec should be given access to gun lockboxes, especially the stun revolver.

**Comment by Imagebard** [comment]
>Increasing the metal/glass cost of assault rifles (which is what spawned this entire issue in the first place) to the levels of the hookshot would be a great start

**Comment by icantthinkofanameritenow** [comment]
How would this breakage chance be calculated? As Sarah put it, it might backfire to make guns harder to get by people who need them in emergencies and waste materials as well.

**Comment by 9600bauds** [comment]
> as well as science access to use it.

The protolathe doesn't require science access :tada: 

> You have to have already done research to get to the point where you can even print one out.

https://www.youtube.com/watch?v=Z4tcb2XwijU

> The only reasonable alternative I've seen in this entire discussion is having a chance to break the gun if you explode it open instead of opening with an ID/emag.

What's wrong with alerting Sec?

**Comment by Hoshi-chan** [comment]
Remember that there's a station-shaking explosion when a lockbox is forcibly opened with an IED or potassium+water. It **already** notifies security, and the entire station for that matter, it's just that nobody ever gives a shit and just lines up for their free guns instead of doing something about it.

That should tell you everything you need to know.

**Comment by 9600bauds** [comment]
You can blow up the lockbox on the research station to prevent the explosion sound
IEDs do not shake the screen station-wide 
One explosion sound is far from a perfect tell of exactly what happened, it could be fucking anything, it could be Cargo too

**Comment by SangriaMonkey** [comment]
How about we stop legislating from the bench and start giving notes and bans to shitty scientists.

**Comment by Intigracy** [comment]
Nah the whining came from a nuke op round where a scientist printed/opened guns after the ops were revealed.

**Comment by ComicIronic** [comment]
> How about we stop legislating from the bench and start giving notes and bans to shitty scientists.

Because maybe the fundamental issue isn't player behaviour but that this is possible in the first place.

**Comment by SangriaMonkey** [comment]
It does boil down to player behavior though. You shouldn't childproof the game because a couple of dipshits can't control themselves. We have admins for a reason.

**Comment by ComicIronic** [comment]
Yes, this would also be solved if players just didn't print guns, but that's a moronic approach. We shouldn't leave something in with a serious impact on the game and just tell players never to use it - that's an unnecessary burden on the admins and it's a lazy design philosophy.

**Comment by SangriaMonkey** [comment]
Marginalizing a department further isn't the solution. I don't completely disagree with making weapon production a little more difficult, but it shouldn't be outright impossible for an experienced scientist to arm themselves or the crew if they put the effort in.

**Comment by 9600bauds** [comment]
I think we've already established that making lockboxes unopenable without an ID is a bad idea, but I feel like nearly all the reactions here still haven't moved past it and overlook the other alternatives. Even after this being the somehing like third time this exact discussion is opened.

**Comment by Intigracy** [comment]
I don't even see scientists be shitty with guns on the levels that guncargo causes/has caused in the past.

What even is the problem that's bringing this up again?

**Comment by 9600bauds** [comment]
I do see scientists being a shit with assault rifles
I've seen non-antag scientists opening fire into medbay's windoors to break in, with people running past the other side of the windoors (complete miracle nobody got shot)
But sure, let's say those scientists are just shitters. There's also balance concerns, with cults being knee deep in assault rifles very often
Why use runez when you got gunz

**Comment by SangriaMonkey** [comment]
Because runez are scarily robust and hard to deal with in the right hands.

**Comment by icantthinkofanameritenow** [comment]
"In the right hands" is the key word. Most of them struggle to use anything more complex than stun talismans, and even there they fuck up a lot. 

You have a point about player behavior being an issue, but the admins aren't always there and you can bet your ass that a real crackdown would generate a massive uproar.

**Comment by icantthinkofanameritenow** [comment]
@9600bauds 
So what's wrong with the "alerting SPSes" idea then? Worst case, it doesn't harm anyone. Best case, it specifically alerts Sec to the type of weapon that was opened.

**Comment by Blithering** [comment]
How about having an option on the keycard authentication console to choose whether or not printed guns spawn with lockboxes? That way in a real emergency guns can be accessed asap, while still leaving room to make lockboxes harder to breach.

**Comment by icantthinkofanameritenow** [comment]
Best idea I've heard yet. Though that does assume that there's two heads alive to use it...

**Comment by 9600bauds** [comment]
Basically like red code but even more obscure

**Comment by icantthinkofanameritenow** [comment]
And what does that mean?

**Comment by Killette2** [comment]
Remember what it was like when any ID could open lockboxes, and before that, when no lockboxes even existed?

**Comment by ComicIronic** [comment]
Actually it went
- Lockboxes
- No lockboxes
- ID lockboxes
- No lockboxes
- Lockboxes

I believe

**Comment by DeityLink** [comment]
This discussion is outdated. It should be closed and a new one be made if this is still an issue.
