### ISSUE TITLE
bus station nuke ops shuttle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10520]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue

the medical crates are empty

> What you expected to happen

have stuff

> What actually happened
> they are empty
> 
> Steps to reproduce if possible
> be nuke op on bus

**Comment by Kurfursten** [comment]
I looked into this because the syndie ship is just an exact copy from Taxi

It turns out it has a lot less of everything - no crew monitor, security cameras, no syndie bomb, barely any medical supplies.

Most of this I don't see a reason to not just port Box's stuff, although the fact that the nook shuttle spawns without a syndie bomb is probably for the best since Bus is so small. Maybe they could get some other bonus like a box of EMP grenades, or some superglue (so their guns can't be disarmed away or for shenanigans) instead.

As for the medical stuff, we could discuss it, but I just see no reason to not give it to the ops.

**Comment by kol1th** [comment]
Is bus station's pop requirement even high enough for nuke ops?

**Comment by Kurfursten** [comment]
Apparently Pomf never limited it like Taxi
