### ISSUE TITLE
Hi hello we need to talk about stock BYOND Bump() and how to fix it

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#10530]
If you fail to enter a tile because something on the tile returns 0 on its `Cross()`, you `Bump()` the first dense object in that tile's `contents`. This is not necessarily, and in fact often is not, the thing that actually prevented you from entering the tile.
We handled this before by manually calling `Bump()` and making BYOND discard automated calls to it. This was hacky, but worked.
Another way to deal with this is to make objects move themselves to the beginning of their `loc`'s `contents` when they return 0 on `Cross()`. I have confirmed that this works, but you need to manually add the object to the beginning of `contents` because procs like `Swap()` don't work on `contents`. I haven't profiled this fix, but it's possible that it could have a performance impact.

So which solution is the best?
1. Go back to making automated `Bump()` calls do nothing
2. Make objects move themselves in `contents` so that the correct object is `Bump()`ed, which is (marginally) less hacky but also probably a bit slower
3. Something else, if someone can think of another solution

**Comment by Shadowmech88** [comment]
What advantage was gained by moving to Byond's automated `Bump()` system?

**Comment by PJB3005** [comment]
Makes a transition to pixel movement like, actually feasible.

**Comment by Shadowmech88** [comment]
Alright, so then it looks like 2 is the best option if we want to ever move to pixel movement?
_Do_ we ever intend to move to pixel movement?

**Comment by 9600bauds** [comment]
> pixel movement

Okay

Why?

**Comment by ComicIronic** [comment]
It would make the game somewhat sleeker.

**Comment by Exxion** [comment]
Pixel movement is still a _long_ way away, even if we do want it
I was working on it for a while, but it's  on hold for now
But anyway, automated calls to `Bump()` happen whether we want them to or not, we just made them not _do_ anything before

**Comment by PJB3005** [comment]
I guess we could band aid it by making a ..() sanity in Bump(), then manually calculating whether we should pass the bump or not.

**Comment by clusterfack** [comment]
I have spent a long time considering this because I have felt the same way as you @Exxion. And it seems we have had many of the same ideas. 

Any fix we choose ends up being a hack anyway until this byond bug is fixed, and it's being ignored
http://www.byond.com/forum/?post=2079322
![](http://unvailed.com/wp-content/uploads/2014/02/00000065-001.png)

The problem with the old system is that while it DID work, it also didn't really work at all. Because many things ended up relying on broken assumptions like double bump occurring, see: particle accelerator particles, several different projectiles, and a few other objects. The absolute one thing we should not do is go back to the old system which relied on several hacks and other cases relied on this purely broken behavior to function correctly.

I believe this suggestion
>Another way to deal with this is to make objects move themselves to the beginning of their loc's contents when they return 0 on Cross(). I have confirmed that this works, but you need to manually add the object to the beginning of contents because procs like Swap() don't work on contents. I haven't profiled this fix, but it's possible that it could have a performance impact.
Is the correct one at the moment. A simple modification to the forcemove of border objects, and to their New() will allow us to do this. It will have no performance impact, but it will be injecting oldcode that we will have to fix at some point in the future.

Alternatively, we remove all Bump() calls altogether with very simple regex to a proc we have defined ourselves until this is fixed. But I haven't fully thought through how this idea could break so I don't really feel like it is the best.

**Comment by Exxion** [comment]
Border objects are not the only problem. Tables also block lasers if there is a dense object on them, even if that object is the person you're aiming at.
The dense object that has been on the tile the longest is always the one that gets hit.

**Comment by clusterfack** [comment]
Yeah that's why you see my RAGE FACE at the byond bug not having been fixed yet. Otherwise I would have easily fixed this myself some time ago.

**Comment by Exxion** [comment]
This was fixed an eternity ago
