### ISSUE TITLE
Add Gunkata

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#10589]
#### Description of suggestion

Make it so that **only** when on disarm or grab intent, and  only standing next to and while **facing** the source of a pixel projectile that you have disarmed or grabbed at in the last second (IE someone with a gun), projectiles will fly past you behind or slightly askew randomly +-30 degrees instead of hitting you.

**Comment by Shadowmech88** [comment]
> only standing next to

It is very easy to yakety sax away from an opponent such that they remain non-adjacent to you. Once they are no longer next to you, the gunkata would be useless to them, and you could fire at them at will while maintaining distance.

I'm not saying the idea as a whole doesn't have merit, but requiring the player to be adjacent to his opponent would cause it to be very rarely used with success.

**Comment by Midaychi** [comment]
How would you do it differently then? I'd rather have something that is difficult to do, but great when you can perfect it, than something that is easy to do and just next in line for the nerf or removal chopping board.

**Comment by Shadowmech88** [comment]
Difficult, sure, but I defy you to try staying consistently in melee range against a gun-wielder that is running away.

Given that you need to have grabbed or disarmed them in the last second (in and of itself difficult when fighting a ranged opponent that is maintaining distance) AND you need to be facing them when they fire, I don't think you should also need to be adjacent to them.
Or maybe have it check for whether you're in a two to three-tile range of them instead of right next to them.

**Comment by Midaychi** [comment]
@The point of gunkata is that you are in melee range. https://www.youtube.com/watch?v=A2KJHysK6k8
Maybe it'd be better to make it a martial art though?

**Comment by Shadowmech88** [comment]
I know how gunkata is intended to work.
But using a defensive melee technique against ranged fighters isn't feasible in SS13 due to how quickly players are able to move and change direction. Offensive melee techniques are possible only because it's possible to spam click and get close enough to a fleeing player that you can land a hit on him when your paths cross. But expecting a player to maintain melee distance constantly in order to defend against incoming projectiles just isn't reasonable.

In a video game, you sometimes have to make concessions due to being bound by existing game mechanics.

**Comment by Midaychi** [comment]
Martial art that works through forms, and requires you start unarmed and surrounded, start with disarms and grabs that end up with the disarmed weapons in your hands rather than on the ground, and perpetuate the dodging and form progression by landing successful hits?
Automatically does *flip animations when necessary?
