### ISSUE TITLE
Trader Quality of Life

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#10605]
Feature request - make Vox Trader a latejoin job like everything else other than silicon. There's not even a reason they necessarily couldn't arrive on the arrivals shuttle and barter passage to the outpost from cargo or science -- or just jump into space and hope.

In my experience the ID you are given after shift start doesn't match your alternate Vox title if you have one selected in preferences. Someone should look into that.

It seems there should be some mild incentive to starting with no ID so that it's not a purely RP-based choice. Maybe an extra credit chip roll?

Please add Vox shuttle access to the Vox outposts other than Bus. All of the other three also have oxygenated lobbies meaning that a miner can carelessly walk through the no-access doors and poison the air.

**Comment by ScrambledSteak** [comment]
better idea: remove vox trader

**Comment by 9600bauds** [comment]
There is a very strong incentive to getting an ID and that is not being deported out the mass driver.

Even if there was no incentive I'm not sure why there should be, an RP choice that you don't have to cripple yourself for is good

**Comment by Kurfursten** [comment]
Yeah, I'm saying the opposite. There is a very strong incentive to getting and ID (you can move the ship / not get arrested) and no incentive to cripple yourself by choosing no ID. By the way, if you idle at round start and don't choose within 30 seconds you're forced into no ID.

What I'm getting at is that I don't know why we even have the option to cripple yourself with no upside. It's kind of like if there was an option to start any job with no ID.

**Comment by ComicIronic** [comment]
> make Vox Trader a latejoin job

I do not support this. The only latejoin jobs should be on-station ones, because it incentivises people to ready up if they want their snowflake jobs and forces players to join as station-useful jobs later on when other players might be dead or braindead.

**Comment by Kurfursten** [comment]
Remove Assistant and Virologist as latejoin jobs then? They're not station-useful enough and full of snowflakes. What's snowflakier than the Virologist who sits in his private office all shift?

Xenoarch should probably get axed too. You can't really even argue that's an "on station" job, they never leave the roid.

**Comment by ComicIronic** [comment]
Abusing semantics is an argument that convinces exactly nobody.

Virologist and assistant aren't snowflakes because they're both human jobs with the regular interaction of the round. All silicons are non-human, and vox trader plays completely differently to station jobs.

Assistants are also totally capable of being useful to the station.

> You can't really even argue that's an "on station" job

Sure you can, xenoarchs still start on the human station. Their jobs are station-relevant, instead of being a job that could operate totally on its own without the station there.

**Comment by Kurfursten** [comment]
Traders are equally, actually more capable of being useful to the station than assistants - they have access to more tools and supplies. Played the same way, a benevolent trader can benefit the station more than a benevolent assistant.

"Snowflake" here is a meaningless word that convinces exactly no one. The reason silicons can't latejoin is because that would half- obsolete the roboticist. You can make more silicons, not more traders. The only snowflake here is that every other job can be joined after a round starts except this.

**Comment by ComicIronic** [comment]
Assistants are meant to get access to help do other jobs, which Traders, played properly, cannot do. It doesn't make sense to talk about a "benevolent" trader, unless you mean in wanting to make trades, because traders giving things away would be rather against the point.

> The reason silicons can't latejoin is because that would half- obsolete the roboticist.

There's more reasons than that.

How does a Trader even get on the NT arrivals shuttle? And it would have to be Arrivals, because you can't have them spawn in the Vox crash site or wherever it is they start out because that doesn't make any sense either.

**Comment by Kurfursten** [comment]
Spawn them in the airlock-to-space room instead. It makes as much sense as a stationary shuttle being where people appear. Or the arrivals shuttle if you care to, it doesn't make that much difference. /vg/ doesn't have "lore" so make up your own reason they hired the space taxi.

Anyway, your views on assistants are out of touch and worthwhile of dismissal. Why can Traders only be played a certain way but Assistants can be played any way and are therefore assumed paragons of virtue? Here's a true story of one deadpop game I played trader: the HOP hired me to set up the engines and granted my Vox ID engine access. Guess I broke your made-up rules. Oops!

The Vox-hate meme is a funny and interesting component of gameplay in-game, but it doesn't really have a place here on Github. Stop roleplaying.
