### ISSUE TITLE
I never wanted to restrict nonhuman races from playing as head roles.

### ISSUE THREAD

**Issue by Intigracy** [d3athrow/vgstation13#10616]
Discuss / emoticons.

**Comment by 9600bauds** [comment]
Emoticons

**Comment by ScrambledSteak** [comment]
Remove vox
Remove plasmaman
Remove all aliens except for grays and diona

**Comment by SacredAtom** [comment]
I agree racewar now

**Comment by ihadtoregisterforthis** [comment]
No fun allowed

**Comment by kol1th** [comment]
Wanted this for a while, but I never made an issue for it :ok_hand:

**Comment by Intigracy** [comment]
fyi I actually play as vox pretty regularly, this isn't no fun allowed it just makes sense to me that centcomm would have human heads of staff on a station with an AI that favors humans

**Comment by Shadowmech88** [comment]
For what reason other than RP?
And if the sole reason is RP, I would ask why are we heavily changing gameplay on a light RP server, for the sole purpose of RP?

**Comment by ScrambledSteak** [comment]
because people who play vox are usually shit at their jobs. This is especially true with vox HoS and vox Captains

**Comment by cowboybuttsdrivemenuts** [comment]
Eh, prevent vox for being captain and head of security and it'd be pretty good. There's one or two okay vox CEs and CMOs. Although Shadow has a point.

**Comment by TheFriggenSawbones** [comment]
I don't really see a point in it??

plus sometimes i like being CMO

**Comment by mikecari** [comment]
Do it, fuck nonhuman scum.

**Comment by Blithering** [comment]
Makes sense to me, although I would miss being a plasmaman captain.

**Comment by ghost** [comment]
With an exemption:
Allow greys to play RD & CMO.

**Comment by icantthinkofanameritenow** [comment]
Nanotrasen is a human-run company. Logically, they would only select humans for heads of staff. 

I see no reason why this was not implemented earlier. Plus, avoids someone going "AI LAW 2 KILL THE CAPTAIN" at roundstart.

**Comment by kol1th** [comment]
Skrell and humans are best friends lore-wise, so let's add skrell and have them be heads of staff. :ok_hand:

**Comment by ScrambledSteak** [comment]
allow greys to play all jobs
allow vox to stay on their fucking trade stations
allow plasmamen to blow their brains out
allow diona to do whatever the fuck they want ooga booga
allow all other aliens to fuck right off the edge of my dick

**Comment by Blithering** [comment]
Only fault in the logic I can think of is what would happen to humans who had high rank and then became plasmamen. I would like to see alternate roles on the lines of trader to make up for the lost jobs though.

**Comment by cowboybuttsdrivemenuts** [comment]
Can we get an actual reason for this besides muh RP and muh feelings?

**Comment by Intigracy** [comment]
> fyi I actually play as vox pretty regularly, this isn't no fun allowed it just makes sense to me that centcomm would have human heads of staff on a station with an AI that favors humans
1. AI, kill the captain he's been harming people
2. Nanotrasen clearly has a human bias shown with the AI laws, it would make sense to have actual humans as heads of staff
3. Muh RP (but not muh feelings idc if this were to get shot down)

I'm partial to leaving CMO and RD available.

**Comment by 9600bauds** [comment]
Where are we getting this seemingly arbitrary "CMO, RD" list from
Why is the RD kosher and the CE not

**Comment by TheFriggenSawbones** [comment]
the only problem is that I see a lot of rounds where these head roles aren't played so race restricting them is kinda furthering this issue?

although I only play late so maybe its not as bad during the day.

**Comment by Kurfursten** [comment]
I actually think Captain should be restricted to Human.

The rest, I agree with @TheFriggenSawbones - we rarely have people play heads as it is, so further restricting it seems like a questionable decision.

**Comment by Probe1** [comment]
I've jokingly said this many times before.  And I like it.  But the reality is what sawbones and kurfurst said.

**Comment by Probe1** [comment]
Also fuck non human captains with a rake

**Comment by Kammerjunk** [comment]
I seriously don't care either way but I don't think there's an emoticon for shrugging so this is the closest I could find :fried_shrimp: it has "shr" in the name
That said, I think the "RD and CMO is fine" thing came from the fact that the CMO is currently just a doctor with a fancy coat and autoinjector and the RD is just the local tard wrangler

What people have said makes sense, though. Nuke ops/rev with no captain and/or only 1-2 heads NO MORE

**Comment by Probe1** [comment]
shrugging emoji NOW

**Comment by ihadtoregisterforthis** [comment]
Soon actually
![](http://emojipedia-us.s3.amazonaws.com/cache/6c/0b/6c0bf583f98fbf936329259548b9f677.png)

**Comment by Intigracy** [comment]
![vote1](https://cloud.githubusercontent.com/assets/4043940/16168630/793d6e3c-34c3-11e6-9f46-0b40b88f8dc1.png)

**Comment by Durgen** [comment]
I think we should restrict plasmamen from medical intern

**Comment by Blithering** [comment]
vOv Closest I can get to a shrug.

**Comment by TheFriggenSawbones** [comment]
@Durgen
THATS EVIL

**Comment by Kammerjunk** [comment]
vOv That's Coffee. It is tiny.

**Comment by 9600bauds** [comment]
Server votes a shit tbh, especially for these type of topics

**Comment by cowboybuttsdrivemenuts** [comment]
Gee, if I'd known there was a server vote I would've gotten on and voted. If only it was up for a decent amount of time.

**Comment by Intigracy** [comment]
I'm not basing everything on one thing.

Eventually there should be a poll.

**Comment by icantthinkofanameritenow** [comment]
@Kurfursten 
The people who don't play heads won't be persuaded to change their minds about it just by making head roles species exclusive. It's purely a safeguard to ensure they don't get done in by ASIMOV asap.

**Comment by TheFriggenSawbones** [comment]
how often does that happen
I've had that used against me as captain once

**Comment by icantthinkofanameritenow** [comment]
More than you think. 

The only reason you haven't seen it used against you more is because most people would rather robust you themselves.

**Comment by Intigracy** [comment]
> Where are we getting this seemingly arbitrary "CMO, RD" list from
> Why is the RD kosher and the CE not

Oh I forgot about the CE entirely,

**Comment by Kurfursten** [comment]
So did the playerbase [complex shrugging emoji using Japanese characters for the face]

**Comment by TheFriggenSawbones** [comment]
¯\_(ツ)_/¯

there you go

**Comment by Durgen** [comment]
any changes to races will be too contentious to reach a consensus. Maybe this one should be sent upstairs.

**Comment by Kammerjunk** [comment]
> Backslash removed by GitHub

Nice

**Comment by Kurfursten** [comment]
What about "all job with a loyalty implant must be human"? So that's Cap, HOP, IAA, + all sec.

That "feels" right to me. Maybe that's why we instinctively leaned away from saying bar them from RD CMO and CE at first.

**Comment by TheFriggenSawbones** [comment]
Lawyers being restricted sounds lame as hell

**Comment by Kurfursten** [comment]
I wouldn't want someone to be my lawyer if their lawyer suit was concealed under a pressure suit.

Being a lawyer on /vg/ is 90% wearing a suit, 8% raiding botany and medbay, 2% actual work

**Comment by icantthinkofanameritenow** [comment]
I thought that was just because we had some people in those roles who were nonhumans and not terrible at it. Still, I don't see why it wouldn't be better off all-or-nothing.

**Comment by AutismSpider** [comment]
CE not real just 1000s of spiders in a suit.

**Comment by Gringonius** [comment]
On the topic of making the station more human centered I still find it silly how humans now speak by default some sort of universal language instead of their own native Sol Common.

**Comment by Brolaire** [comment]
I thought the station runs on ASIMOV default because it's been the default since before non-humans have been implemented?
Besides that I don't like this, the only real issue is the "kill cap law2" which could be solved by maybe adding a small pop-up window reminding non-humie caps they're not part of asimov laws, so they know what kind of horror they're jumping in

**Comment by ghost** [comment]
"all job with a loyalty implant must be human"

I like this idea a lot, it makes sense and I hardly if ever see a non-human in any jobs that'd be given round start loyalty implants anyway so it's not as if we're killing off jobs here.

**Comment by Megamaw** [comment]
Buff the most powerful race in the game even further? Wow, what a fat lot of sense that makes.

You can't make the argument about 'mmmuh lore' when most of the server plays for valids and greentext. You have to think about things from a gameplay balance perspective.

Humans already have the strongest racial trait, have absolutely no downsides, and you want to make them _**stronger?**_

**Comment by ghost** [comment]
@Megamaw actually the most powerful race in the game is plasmaman, next is diona, then skellingtons (though they were nerfed so not sure where they are right now, might be lower.), THEN human

**Comment by ihadtoregisterforthis** [comment]
Power is not only measured on damage modifiers.

**Comment by icantthinkofanameritenow** [comment]
@ihadtoregisterforthis 
Counterpoint- those modifiers are a big factor, and ASIMOV isn't as influential as it seems when you remember how easily sillycone laws can be changed. And while humans have no downsides, they have no _upsides_ either.  The advantage to playing one vanishes in the blink of an eye.

**Comment by Kurfursten** [comment]
I'm not sure about that. There's a reason humans are far-and-away the most-played race.

> Don't need to be on a constant drip of hyperzine to move at a reasonable speed so you can get to work right away instead of reporting to chemistry at the start of every shift, good at yakity sax
> Asimov for easy access to almost anywhere
> Much easier self-cleaning with showers, almost never start with a genetic defect (Greys have a much higher chance of this but no one ever mentions it)
> Station atmos caters to them
> O2 lockers cater to them
> Everyone starts with two boxes of internals specially designed for humans
> All around stats with no special instant-death weakness to either burn or brute; tanky enough to survive a shock at roundstart so you can just guess the wires without insulated gloves
> No one hates you (this is a social game, and let's be real here, no one has ever said "I refuse to help you because you're human" but it does happen to other races)

They really make the the perfect race whether you're a greytiding loner, a position of importance, or just an average joe. No weaknesses, no need to rely on others.

More specifically, in my favorite department of engineering:

> You don't have to deal with the "hardsuit problem" of other races where their hardsuit helmets do not provide welder protection so you have to give up an eye slot for welding goggles and a constant hand slot for flashlight
> Easy access to breach areas via silicone laws
> Good for collaborating with borgs on engineering projects, for getting AI access to rooms that you want to improve or repair
> Just imagine having to wait on a chemist for pills before you could set up an engine, or worse getting hit by a stray emitter beam with fire weakness - not to mention an accidental misclick with a welder means you're half dead

It's no surprise that I played human for two years straight.

**Comment by icantthinkofanameritenow** [comment]
I hate splitting hairs, but most O2 lockers have nitrogen tanks in them too. Genetic defects only happen when a gene for a power triggers a disability too, and since that hardly ever happens even to greys that's not really a plus for humans. 

 And the "master of none" caveat is still very much in effect- they have no weaknesses, but they also have no strengths. They're simply mediocre in every way. 

Sure, a Diona is vaporized by burn damage but when hit with everything else it will NEVER die. Hell, they don't even need radiation suits when working with supermatter because radiation heals them. 

As for borgs, in addition to what I said regarding NT default only the most uncooperative of borgs will refuse to listen to you on account of non-human status if you're not doing something blatantly harmful.  I acknowledge the hardsuit problem in part because I was responsible for it- the alternative being unstrippable flash protection for those races at roundstart. That said, with the addition of the plasmaman prisoner suit I suppose I could revert it for the engineer equivalents of those races.

**Comment by AutismSpider** [comment]
radiation will stun lock them so they need to suit.

**Comment by Kurfursten** [comment]
@icantthinkofanameritenow In my experience it happens about a third of all rounds you play as a grey (or detective), although maybe someone like Yahir might be able to give more long-term insight. It's probably a bug but it happens all the time - even someone like me who barely plays it gets a defect almost every round as a grey. Multiple times the issue has been brought up. Imagebard commented on it recently and I did too here #6818, but every time it gets "fixed" it doesn't actually get fixed. Some like seizures and cough actually force you to go get treated because they're shift-ruining.

If you want to split hairs, I can too. Where are the backup plasma tanks in those O2 lockers? The extended O2 tanks don't even have an equivalent, but they appear in 20% of all O2 lockers. And let's not forget that there are also twice as many O2 tanks in lockers as well. Inaprovaline and dexalin work properly on humans instead of damaging them, meaning that they can be saved more easily when bloodied and won't get wrecked by the wild ride, but ALSO meaning that O2 locker medkits are far more valuable to them.

I don't think even you believe your claims about Asimov. After all, weren't you in the other thread saying how important it is that heads be human for Asimov protection? Hey, you even know from my thoughts there that I'm with you. I have consistent beliefs that Asimov is important for a certain segment of roles, particularly those with implants. It's the same kind of inconsistency as your views on damage. Diona's and Plasmamen are apparently both "better" than humans because of strength versus brute or burn and weakness to the other. But when fighting **any** intelligent opponent, especially in a game like this based around surprise attacks, they're always going to use your weakness. If there was a Pokemon type with no resistance and no weakness, it would be the ultimate defensive type. We humans are the master race.

There's a reason 90% of our players of our players play human just like me and you.

**TL;DNR** This isn't to say I'm totally happy with the state of alien balance, but I think you're not appreciating how good humans are. It sounds like you just choose one for exclusively for roleplaying purposes, which is a pity.

**Comment by icantthinkofanameritenow** [comment]
Not exactly, I choose to play humans because unlike some people I can mention (_cough_Sawbones_cough_) I consider it to be beneath me to choose the others simply to gain a mechanical advantage. I don't deny that surprise attacks are vital, but a hard mechanical advantage can't be denied as playing a major part of that. 

 And I do believe my claims about Asimov. I simply noted that as powerful as Asimov is for humans, it's all too easily taken away by a nonhuman head or someone who just wants the silicons to shut up about human harm so they can have an execution uninterrupted. Asimov would be much better protection for humans if there was an unwritten law forcing silicons to avoid law changes at all costs, but do you really think that would be practical? (Also, as a Pokemon player I'll point out that such a type does exist in Normal-types, but they have the counterbalance that all of THEIR attacks aren't super-effective against anything and in fact are resisted by a wide variety of other types. In a game where offense is the best defense, that's one hell of a weakness.)

As for backup plasma tanks, it's obvious- you don't want some idiot just opening one up and creating a mini-plasmaflood on the spot. And hell, I could code an extended-capacity emergency nitrogen tank right now if I was so inclined. 

> Inaprovaline and dexalin work properly on humans instead of damaging them, meaning that they can be saved more easily when bloodied and won't get wrecked by the wild ride, but ALSO meaning that O2 locker medkits are far more valuable to them.

Okay, now THAT just sounds like a bug if I've ever heard of one.

**Comment by Kurfursten** [comment]
Any actual Pokemon player would realize that Fighting is an extremely popular offensive type which is super-effective versus Normal. Are you sure you've played the games?

> Bug

It's a special exception to hurt Vox because Oxygen-based. I was actually wrong about Dexalin, that was only talked about, it never got merged, but yes, Inaprovaline will poison Vox. The fact that either of us could play Medbay and not know this by heart kind of proves how rare Vox players are. Just imagine how many Vox have been killed by the wild ride because this isn't wildly known to newbie doctors.

> I could code

Yeah, and I could code plasmaman has 1x weakness to burn in about 2 minutes, but that doesn't make it true.

**Comment by Intigracy** [comment]
One of the chems converts into nitrogen for vox actually.

**Comment by Kurfursten** [comment]
I'm not sure what you mean by that, but these are all of the snowflake Vox interactions, just checked the code:

> Oxygen and Inaprovaline cause toxin damage
> Nitrogen reduces toxin and suffocation damage
> Gravy reduces toxin damage

**Comment by icantthinkofanameritenow** [comment]
I meant that normal types were the closest equivalent to the hypothetical type you spoke of. And really, I can count the number of times anyone uses inaprovaline for anything other than making tricordrazine on one hand.

**Comment by Kurfursten** [comment]
Normal types don't fit because they are cripplingly weak to a very common type though.

And your statement is really "/vg/ doctors and paramedics are bad" but that's not super compelling because it also means they're just as likely to inject Vox with poison, try to clone Vox and never put on an N2 mask - the whole gamut of reasons you rarely see aliens healed in medbay.

**Comment by icantthinkofanameritenow** [comment]
And to be fair, that's more medical incompetence than anything else. It would be nice if someone explained to me what the logic was in making inaprovaline toxic to Vox, though. It still gives me the impression  that it's some kind of bug since no other alien race is affected badly by medicines like that. 

(I realize the mistake I made with normal types, but still Smogon and the other competitive sites all echo similar sentiments about it being perfect defensively except for that fighting weakness. But that's increasingly beside the point now.)

**Comment by Blithering** [comment]
I've been playing a plasmaman captain for quite a while now, and the only times crew have taken issue with my race it tends to lead to more fun in the round in general; such as the time an atmos traitor ordered a contortionist jumpsuit and became a sort of underground racist tunnel snake, bothering nonhumans and shouting at me from the pipes, and leading to a half excavation half chase trying to track him down.

**Comment by Orangerush** [comment]
All two non human heads are gonna hate this
