### ISSUE TITLE
Pill box request

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10699]
Take a smart fridge.  Turn it into an item instead of machinery. Lower its limit to 50 or 100 items.  Make it weight class 3 so it only fits in bags of holding.  Remove the options to dispense more than 1 at a time.  Give it an ID required panel.  Let chemistry/CMO IDs toggle securing bolts so it can't be moved without I don't know a wrench and welder or something.

Now chemists can put this thing on the counter and fill it with pills for the "I just need an anti toxin" pill crowd.  

See how the smartfridge faces the lobby?  That's a good idea.  But it hinders medbay by making doctors walk around for it.  And we don't need two stinkin smartfridges.

![1466512143598](https://cloud.githubusercontent.com/assets/8550416/16229909/e725ec64-378c-11e6-8593-c668f8609bd1.png)

**Comment by ComicIronic** [comment]
So you want something that isn't a smartfridge but is worse and we don't need two smartfridges because...?

**Comment by Konater** [comment]
You just wanted to post that image didn't you

**Comment by Probe1** [comment]
I didn't really want to find what map it was on what server.  I think it's tg's box but I don't know.

@ComicIronic Trading size for portability.

**Comment by ComicIronic** [comment]
But if it's not going to be portable in the first place because it's stuck in the lobby, why include the option?  You're making something not much better than a pillbag or a smartfridge but it's really not clear why you'd use it for either.

**Comment by nuklearcellphoneg** [comment]
I think it would be nice if most of the departments had a very secure method of selling goods to others. Most importantly the ability to browse the inventory without being able to steal the inventory

I think the public having ez access to the entire medicine supply is bad.

I think that updating the Supply Request machines a bit would be a better step in the right direction, as well as giving more Departments wrapping paper/destination taggers, so the chemist can wrap up a bottle of medicine, tag it for Science, then send it over, or say in the case of a Virus, distribute the antibodies throughout the station, and have a more proper Quarantine

**Comment by Probe1** [comment]
@ComicIronic the idea was it to be an item.  An item that can be secured in place by chemists if active and medicine dispensed directly to the lobby.

Two smart fridges is silly and will cause confusion.  One smart fridge facing the lobby hurts Medbay players.  Why not have a secure box for chemists to stock, allowing crew that ate Discount Dans to walk up and grab a pill instead of hammering on the door until someone stops treating a patient and opens it?

**Comment by uazuaz** [comment]
@nuklearcellphoneg 
friendly reminder:
https://github.com/d3athrow/vgstation13/issues/8186

**Comment by ComicIronic** [comment]
> Two smart fridges is silly and will cause confusion

Not really, it's a sensible way to split up public and private chems. If the Chemist is so braindead that they can't possibly figure out how to use TWO fridges, then we may have a player problem, because at least one person playing is actually a slug on a keyboard.

> Why not have a secure box for chemists to stock

Because really that's describing a Smartfridge. I think you have a nice idea, but it's in a weird point where you want it to replace a Smartfridge by doing a similar thing and then at the same time have some extra functionality that doesn't really seem useful or necessary.

I support having a lobby-facing chem stock for users, but I don't see why this has to be anything other than what we already have, because I'm not seeing the case for the pillbox.

**Comment by clusterfack** [comment]
We should nake it so ingesting chems via pills doesnt work for all chemicals. Otherwise medvay would be almost completely invalidated by a public facing smartfridge.

**Comment by Probe1** [comment]
Medbay is completely invalidated by cloning, cryo, pills, pepto bismol exploits, borers, nanomachines, pAIs, [...]

Giving chemists an easier way to load up pills for players doesn't sound like the end of the world when borers can shit peridaxon into people.

**Comment by ghost** [comment]
Medbay is generally completely invalidated by allowing anyone to use Medbay

If you have two neurones to strike together and access to a Chemistry Dispenser, a filled Medivend and the Surgery room, you can cure any ailment that isn't outright death. If you add Cloning and Cryo to the mix, you have Medbay

Everything else at this point is just fluff. We don't have the TG system where you just slap magic healing bandaids, but we're far from Goon where health statuses matter a fuckton and can kill you if you don't rush to Medbay, instead of just making you emote, jitter or talk funny

**Comment by nuklearcellphoneg** [comment]
@dylanstrategie 

This is also part of a larger discussion we need to have about Economy and overall difficulty. Hum hum

**Comment by 9600bauds** [comment]
As for the original suggestion: I don't really see the point at all, the type of pills you want people to have free access to isn't very varied and the volume of the pills you want to give away isn't too big either. You can just clickdrag the pill collector onto the table to fill it with antitox pills if you care so much, but then an assistant will just take 5 for his internals box and then the clown will take 4 for his internals box and an engineer will eat 7 of them in one go to treat 2% radiation.

As for this whole discussion in the comments: Blood loss and broken bones and organ damage all exist and they're a bitch to deal with and pills don't instafix them and they are much much more common than you think.
