### ISSUE TITLE
Corporate lawset is retarded

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#10691]
It needs to be amended to care about profits instead of costs.
This will prevent it from being the WHO TURNED OFF THE LIGHTS meme lawset it is today.
A corporate AI should care about crew productivity, particularly from miners and scientists.

**Comment by Shadowmech88** [comment]
> couldn't even be bothered to delete the bug report template

**Comment by Durgen** [comment]
sorry hit submit too early, I will edit

**Comment by Durgen** [comment]
![corporate](https://cloud.githubusercontent.com/assets/19157295/16213563/ff18bb98-3715-11e6-8cf4-e0e58188c952.png)

**Comment by icantthinkofanameritenow** [comment]
First you'd need to create an actual source of profits for the station. Ever since the cargo rework the only way to get money for the station as a whole rather than just the miners is for payroll to be toggled on.

**Comment by Shadowmech88** [comment]
There would also need to be a metric by which profit can be measured, since monitoring the individual account status of each crewmember would be a bit tedious.

**Comment by Durgen** [comment]
> There would also need to be a metric by which profit can be measured

It could be avoided if we instead define specific crew behaviors as things that generate income

1 Maximize station profits. (Income - Expenses)
2 Crew productivity increases Income
3 [Definition of productive crew behaviors]
4 [Definition of expenses]

**Comment by Shadowmech88** [comment]
Would the (Income - Expenses) portion be a part of the actual lawset?

**Comment by Durgen** [comment]
> I feel like a joint law 1 (Maximize station profits and minimize station expenses.) would be best.

I think you are missing the point of making it about profit. Expenses are already part of the definition of profit.
Profit = Income - Expenses

**Comment by Shadowmech88** [comment]
That needs to be evident in the final law, I think. Not every player would know the correct definition of profit.

**Comment by icantthinkofanameritenow** [comment]
@Durgen 
Still, there's the underlying issue that the station has no true income. Thus, no profit.

**Comment by Durgen** [comment]
Yes, this is an Issue, but I think it can be sidestepped by creating a cleverly written lawset.

**Comment by Imagebard** [comment]
Or by actually finishing the economy system

**_:^)_**

**Comment by icantthinkofanameritenow** [comment]
For once Imagebard is right. Even Asimov doesn't need extra laws simply to function at a semi-normal level.

**Comment by Durgen** [comment]
even if the economy system was finished the lawset would still need to be modified to care about profits.
caring about expenses only does not make sense.

**Comment by Kurfursten** [comment]
I just want to point out that some of our general interpretation of Corporate is weird. Why do we turn out lights? No one is paying a bill for those. We regularly cap out max power at the SMES units. There's no expense. A more reasonable Corporate AI would simply lockdown Cargo, murder the Vox traders, and demand its Engiborg relocate all vending machines to its core. Those are things that involve expending money. If anything, this reminds me that engineers have been asking for years for a way to transmit excess power to Centcomm in exchange for some dosh.

**Comment by Shadowmech88** [comment]
If you really want to get technical, the Corporate lawset does not define anything as expensive besides the replacement of you, the station and its equipment, and the crew. As far as the lawset is concerned, the HoP could withdraw all 5000 credits from the station account and space them, and the AI wouldn't need to care because the act of spacing 5000 credits doesn't necessitate the replacement of the AI, the station and its equipment, or the crew, and as such is not known to be an expense.

**Comment by Durgen** [comment]
> If you really want to get technical, the Corporate lawset does not define anything as an expense besides the replacement of you, the station and its equipment, and the crew.

If you are super literal, shouldn't corporate AI try to prevent the station from being repaired, and the crew from being cloned when shit hits the fan?
Those are both defined as expensive things which the AI is trying to avoid.

**Comment by Shadowmech88** [comment]
That'd actually be a fun corporate gimmick to try.
I wonder if it would result in a ban.

**Comment by Kurfursten** [comment]
I've seen corporate AIs turn off the APC in genetics on more than one occasion, so no

**Comment by SysadminJeroen** [comment]
@Kurfursten I have seen it happen like 3 times as a doctor, and I do not regularly play as a doctor.

Fun fact: I seen it happen twice on Metaclub.

**Comment by SysadminJeroen** [comment]
One minimized expenses by placing grilles all over Genetics, like... that is a shitty way to minimize expenses because a round of cloning is way cheaper than placing 14 grilles.

The other one argumented that cloning IS replacing crew, I made the argument that all cloning does is replace someone's totalled body, but does not replace someone as an individual.
If they shut down cloning, they might as well shut down Chemistry, as it costs resources to produce chemicals.
Shut down botany as well.
Tke Kitchen.
Security.
Roboticist.
Bartender.
Fuck it, let's just de-power the entire station.

**Comment by Shadowmech88** [comment]
> they might as well shut down Chemistry, as it costs resources to produce

The point was that replacing crew is _explicitly defined_ as being expensive. A Corporate AI is not obligated to shut down Chemistry in order to prevent use of resources in the production of chems, as the Corporate lawset does not define the use of power, or any resource for that matter, as expensive.

**Comment by SysadminJeroen** [comment]
@Shadowmech88 It says that replacing is expensive. In my opinion cloning is not replacing as you are not replacing the crewmember itself, but merely the body of the deceased crewmember. Getting new replacements from the shuttle is however expensive in my opinion.

**Comment by Ephx1** [comment]
> but merely the body of the deceased crewmember

Hoooooold on there buddy pal. That would be implying that silicons know that each person is actually the same soul, meaning that cloning really shouldn't be called cloning but regeneration. This is a whole mess and it leans on what YOU truly believe to be a person in terms of roleplay. Meaning the lawset is pretty shit and needs reworking like the OP said.

**Comment by SysadminJeroen** [comment]
@Ephx1 One could argue that cloning is merely regeneration, however with regeneration I believe that the original body should be restored in working order, not that a person got... cloned from the original body.

**Comment by Ephx1** [comment]
Exactly. Under corporate it would make sense to just revive the old corpse, they are still the same thing. Which is why genetics is turned off usually. Again this is all player perspective, and as the server has shown any interpretation that does not fit with other's views will get screeched at.

This is why picking anything other than asimov is basically going to get someone pissy.

**Comment by SysadminJeroen** [comment]
@Ephx1 And cloning is not replacing a crewmember, but merely replacing a body.

**Comment by Ephx1** [comment]
Entirely up to what you believe, but others may disagree.

**Comment by SysadminJeroen** [comment]
@Ephx1 And that is one reason why Corporate sucks.

**Comment by Imagebard** [comment]
>Multiple interpretations means a certain lawset sucks

Oh god what the FUCK are you smoking?
