### ISSUE TITLE
Imbue rune can waste 'target' runes on already-imbued papers.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10708]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 0cde9ec9df2d0376d8f32423bf2f532a774e0a20 
> 
> General description of the issue
> Whenever you imbue a rune onto a stack of papers, imbue can affect a talisman (to no effect) instead of a fresh paper.
> 
> What you expected to happen
> Talismans to be exempt from imbuing
> 
> What actually happened
> Talismans not exempt
> 
> Steps to reproduce if possible
> Put ten fresh papers on an Imbue rune next to ten Stun runes stacked on top of each other. Activate Imbue ten times, all Stun runes will be used up but not all of the papers will be imbued.

**Comment by ComicIronic** [comment]
When this says "to no effect", does that mean you don't imbue an old talisman with a different rune when you do this?

**Comment by Allspice** [comment]
My mistake, it overwrites the talisman with the new rune (imbuing Stun onto EMP talisman makes a Stun talisman). But this behaviour is bad, since you essentially never want to change a talisman's type. Instead, an experienced cultist sometimes mass-fabricates stunners by stacking up paper and Stun runes, and this makes doing so shittier because each time you imbue you need to move the new talisman to the side.

**Comment by ComicIronic** [comment]
Is there any way to clear a talisman without using it? We could do some kind of mass-imbue functionality, but I'm thinking about people wanting to reimbue a talisman deliberately.

**Comment by Allspice** [comment]
No clearing functionality that I'm aware of. I suppose you could make it so imbuing with no adjacent rune blanks a paper.
