### ISSUE TITLE
Empty DNA scramblers still Called DNA scramblers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10722]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)

> General description of the issue
> DNA scramblers have giant letters plastered all over them saying what it is even if its used, while most syndicate tools that look like common stuff like thermals and mesons are named their similar stuff

Got arrested for DNA scrambling as a Geneticist despite it being commonf or them to do so because there was a DNA scrambler on station and i didnt match anyone on manifest. While this is proper, There technically should have been 0 evidence to prove this since geneticist use syringes all the time to scramble theirs and others DNA.

In this situation, the detective is technically right, but that evidence shouldn't exist, in theory

> What you expected to happen
> DNA scrambler to be named an empty syringe upon use. Should be before, as well.
> 
> What actually happened

still says DNA scrambler, despite looking 100% like an empty syringe

> Steps to reproduce if possible

**Comment by Intigracy** [comment]
Hell it should just delete itself and spawn an empty syringe.

**Comment by Shadowmech88** [comment]
Are DNA scramblers not just a regular DNA injector with a random UI+UE inside it?
Regular DNA injectors just disappear when they're used, I don't see why this should function any differently.

**Comment by JustSumBody** [comment]
They're both completely separate weapons
/obj/item/weapon/dnascrambler
/obj/item/weapon/dnainjector

**Comment by Gunosaguki** [comment]
Yes of course but the point is visually they're not different. and there shouldn't be anything identifying them as a dna scrambler. since its not a very stealthy tool if theres a giant label on it saying "SYNDICATE ITEM". its just a syringe once its used, so it shouldnt be identifyable as anything but. some items make sense to be identifyable like the chameleon projector and weapons/eswords. but stuff like thermals and no-slip shoes don't show up
