### ISSUE TITLE
mp3 feature request

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10736]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
make an hand held jukebox that you can put on your ears to listen to music with the same songs in the jukebox and you can chose which

**Comment by Exxion** [comment]
Quick question
Why not just listen to something with the computer you're already playing the game on?

**Comment by ghost** [comment]
Pomfs mix is better tho

**Comment by unid15** [comment]
@Exxion not as immersive

**Comment by Exxion** [comment]
Alright get this
An item that, when used in your hand, opens a Google search in your default browser for "good cool  music"

**Comment by clusterfack** [comment]
There's really no reason to waste pomfs bandwith for this

**Comment by 9600bauds** [comment]
Feature request: Newscasters have a channel to watch InfoChammel
https://www.youtube.com/watch?v=52we39IPpGs

**Comment by Shadowmech88** [comment]
Even if he DID code it, I don't think it would get merged because each additional stream from the media server uses additional bandwith.

The best we could do is probably to just make portable versions of the wall-mounted sound systems we already have, that would just play the audio that the DJ satellite streams in.
