### ISSUE TITLE
Bus map issues

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10764]
#### Description of issue

The solars on Engineering and Cargo station aren't wired 'correctly'
Now, before you go saying 'it's a feature', I mean they're not wired between the main grid and the SMES

Down behind Cargo
![ultra immoral platform 18 2016-06-25 113651](https://cloud.githubusercontent.com/assets/9110500/16356305/db01075c-3aca-11e6-8545-cac7af1e0fa2.png)

And up by atmospherics
![ultra immoral platform 18 2016-06-25 114804](https://cloud.githubusercontent.com/assets/9110500/16356311/ee184f76-3aca-11e6-98b0-cc902984d8c7.png)

This isn't the case for the other solars on the other stations, unless you include the half destroyed one out in space

The monkey pen in genetics requires general science access rather than medical or no access like other maps

![access](https://cloud.githubusercontent.com/assets/9110500/16356367/c136157c-3acc-11e6-8a45-26a66b19cda2.png)

Not sure if it belongs in this report, but admins can't access any of the doors in the vox outpost with their presumably all access ID. Might be a separate issue though

Disposals 'beneath' medbay are incomplete.

![nettle waystation five 2016-06-27 155505](https://cloud.githubusercontent.com/assets/9110500/16384169/da2ac78a-3c7f-11e6-85cc-f07d96c78ebb.png)

The mass driver here isn't linked to any button. The button inside disposals does nothing.

![nettle waystation five 2016-06-27 155814](https://cloud.githubusercontent.com/assets/9110500/16384219/043cd2a2-3c80-11e6-808d-3d90991a36eb.png)
#### Server revision

0907a707646bf4c6b0e9f7a3d14055901dc72fc5 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
Thanks for the reports - I appreciate the time you've taken to provide pictures and show your work. I'm planning on a cleanup of all engineering in the near future, so the solars stuff is especially relevant.

You are correct in guessing that the Vox outpost access not being given to admins is more of a code-end issue, it would be hacky to just add centcomm access to the doors instead of giving admins Vox access.

**Comment by kol1th** [comment]
@Kurfursten Don't forget that the solars area + part of QM's office are unsimulated

**Comment by ghost** [comment]
Another thing that's more of a personal complaint.

The area that's supposed to be for a singularity to the south of engineering, the PA room is way too short, it can't actually fit a PA in it, and if you were to build a PA inside, you wouldn't be able to navigate around it easily.

![pabusstation](https://cloud.githubusercontent.com/assets/9110500/16383925/f6d97e9a-3c7e-11e6-82ed-d09a723c2e45.png)

**Comment by Kurfursten** [comment]
Yeah, I actually mentioned that in my own Issue about bus engineering. The whole engineering department is getting rebuilt entirely.

It has a lot of issues, most of which are caused because it was the stitched together product of a bunch of Taxi rooms. That's not the basis for a good department. The new one is being built from the ground up.

**Comment by ghost** [comment]
Gonna keep adding to this as I find more things broken or otherwise not functioning as intended, hang on.

**Comment by Kurfursten** [comment]
Heh, I can tell you were really thorough based on some subtle stuff in those images. Keep up the good work.
