### ISSUE TITLE
Vox Traders should not get antag roles.

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#10796]
Vox traders already start on a different z-level, with access to a station that no one has access to.
They exist only to greytide and twice today, they've broken into and stolen the chem dispenser from the Research Outpost before 12:15 station time.
They can travel to the station at their leisure, they have access to station external airlocks and spawn with spaceworthy hardsuits.
They do not have any type of security record, you do not know their name to make one until they speak on the radio or are otherwise and therefore cannot be easily arrested via Beepsky.

On top of being hated for looting and generally shitter, that vox trader may also have access to changeling stings / vampire powers / syndicate weapons & gear.

It's somehow unfair to have them be listed as targets for traitor in the crew, BUT they themselves can be antagonists?

Who's idea was this?
Also, should've been removed with #9514

**Comment by 9600bauds** [comment]
I think they were forbidden from being tators, but nobody thought of forbidding them from vamp/ling

**Comment by AutismSpider** [comment]
forbidden form all antag  rolls.

**Comment by Intigracy** [comment]
fyi I didn't remove them from targeting for their benefit, if it was unfair to anyone it was the antagonist.

**Comment by kernikov** [comment]
![ss 2016-06-26 at 10 23 54](https://cloud.githubusercontent.com/assets/5549060/16370524/238270e2-3c06-11e6-9da3-42e388b10bb4.png)
Here's a vox trader that turned out to be a changeling.
Why does a trader need to escape to the central command of an organization that he has literally zero ties to?

**Comment by Shadowmech88** [comment]
Obviously because there will be high-level NT officials to absorb on Centcomm.
He can then use their identities to acquire _things_. Vox like having things.

**Comment by Killette2** [comment]
How do you know that changeling was originally the vox? Traders make for easy targets

**Comment by Kurfursten** [comment]
You don't think that's a buff in a way?

> We can trust him, because Traders can't be antagonists.

@9600bauds They can be traitors

@kernikov The chem dispenser should be outright removed from the research outpost and replaced with a full, large beaker with analysis fluid. There's absolutely no reason for it to be there other than easy chloral for a cult base, and most of the reason miners or traders would break in. It's the biggest problem with the outpost. What's more, you don't even need a **lot** of analysis fluid as a xenoarch, and if you somehow spill it or lose it all, you could always get more from the chem dispenser that gets built in R&D every shift, or make chemistry do their job.

**Comment by Konater** [comment]
Those are some weak as fuck reasons

**Comment by kol1th** [comment]
@Kurfursten Xenobotany?

**Comment by jknpj** [comment]
@Kurfursten Excavation suits have slowdown and scientists make hyperzine, medicine to heal themselves and thermite to test artifacts with that chem dispenser. Removing it from the outpost is a silly nerf. I would move all chem machines to the anomalist room and reinforce the walls around it.

PS:. ELETRIFY ALL FUCKING EXTERNAL WINDOWS WHILE YOU'RE AT IT

**Comment by Kurfursten** [comment]
Setting aside a moment all the reasons that research botanist as a job was a mistake, botanists don't start with a chem dispenser either @kol1th 

@jknpj Miners always got along fine without a chem dispenser. Gee, even the janitor wouldn't mind having a chem dispenser with that logic. Galoshes have slowdown, medicine to heal himself, and more spacecleaner when his bottles run out. I'd just reinforce the walls around the custodial closet and call it a day. Ps: Electrifying windows does nothing http://a.pomf.cat/rlvmlz.webm

**Comment by jknpj** [comment]
@Kurfursten we're not talking about miners. We're talking about xenoresearch, the place where every single plant and artifact may kill you faster than a goliath in heat. Mind you that unlike the janitor, they don't work in the main spation and medbay is far, far away. Miners/Janitors are not even supposed to know how chem dispensers work(MUH IMMULSIONS), but scientists? Come on.

**Comment by Kurfursten** [comment]
No one's making an immersion argument but you. Miners are actually further from Medway by tile count.

In any case, no one's saying the asteroid doesn't have dangers, but security doesn't have a roundstart chem dispenser either. The truth is that an unattended chem dispenser makes the outpost a target for anyone - miners just as much - and the dispenser serves the same purpose most shifts that the old outpost baron served before it was removed.

**Comment by jknpj** [comment]
Removing the chem dispenser from the research outpost chemistry room still seems fucking silly to me.

**Comment by Imagebard** [comment]
>Miners/Janitors are not even supposed to know how chem dispensers work(MUH IMMULSIONS)

Where are you getting this form? Is some high roleplay server running /vg/station code?

**Comment by JustSumBody** [comment]
Consider a scenario in which a trader ling/vamp has a trader buddy.
In addition to the previous advantages, you now also have what is essentially free blood/genome for just glaring/parastinging him. You don't need silence sting/hypnosis, you don't need to remove radio headsets. Hell, you could probably just shove/slip(especially considering the new Vox specific slippy plant is coming out) and cuff him and be fine. You can't possibly be caught killing them unless they happen to turn their SBR mic on round start. There's no chance of the AI, sec, random maint crawlers, or even miners finding this unless they go out of their way to the vox outpost round start and ransack the place for corpses. The Vox has the upper hand before anyone even knows they're in the round. 
There's no way to reasonably prevent it. This is an issue.

**Comment by kernikov** [comment]
As it stands, the only defense posted was "Those are some weak as fuck reasons"./
Which is, at the very least, subjective.

**Comment by Konater** [comment]
The vox outposts don't have any access requirements and while it's nice they might have an antagonist base they're not exactly antagonising the station if they're there. It's not hard to make a coordinated effort to raid the outpost. Spawning off the station z-level is not a big issue when you consider miners and xenoarcheologists immediately go to the asteroid anyway.

Saying they only exist to greytide is dumb when they clearly have a defined role that should keep them more busy than most of the station jobs, the chemistry dispenser theft is only an issue on boxstation because they spawn with little and it's so easy to get into the research station without access.

Space suits are too easy to find as it is so owning one is not considered to be that big a balance issue, this has been brought up several times the defensive stats on the suits are high but this is a code issue that anyone can change. The values don't even matter when combat is all about stuns anyway

Who cares if Beepsky can't arrest them?

There's no IC reason why a trader can't be an antagonist

I don't really play trader/much at all now but I've been traitor trader a couple of times and each time I eventually made myself known as a traitor doing stuff like spawning agent IDs for my buds back when there weren't IDs. I think I managed to convince one to steal my objective for me and pass it over. I can't really remember them that well but they were easily the most rp filled traitor rounds I've ever played in years

I want to bet that you got butthurt a trader stole the chem dispenser when you were a scientist/officer, you tried to arrest them and they used their antagonist powers to stop this from happening in a remote area because you went in by yourself

**Comment by ghost** [comment]
I think it's just better to disable antag drafts on Vox Traders due to how special their role is, with the very clear exception of antag roles that "respawn you" (Read : Wizard, Nuclear Operatives, and naturally Vox Raiders)

**Comment by unid15** [comment]
Maybe make it a server vote

**Comment by ghost** [comment]
A server poll ? Great, server poll it is then

**Comment by kernikov** [comment]
SERVER VOTE WHEN

**Comment by Probe1** [comment]
http://ss13.moe/index.php/poll/99

**Comment by despotate** [comment]
On a roleplay level this idea fails miserably. Vox Traders are an obvious syndicate recruitment target, an easy foothold for changelings, nothing stops 'em from being vampires, blob is a meme, Nar-Sie accepts fuckin' diona, why wouldn't he accept Traders. I could _somewhat_ see them not fitting the mold of being revolutionaries or revsquaddies but at the same time they _are_ a downtrodden lumpenproletariat being oppressed by the entirety of NT, and I'm sure they gain something from overthrowing the oppressors.

Then there's the whining about non-antag Traders stealing shit. I don't know what that has to do with Traders being antag. Just job ban whoever does that shit. I play a shit ton of Trader as Wun and rarely see any fellow traders go out of their way to steal shit these days, let alone from the research outpost.

Vox Traders have access to a different z-level by default but as someone else said here, they're not doing any antagonizing if they're sticking to their station. Science and supply also have outposts that no one ever checks up on, with supply being able to order nearly anything they want and crack it open on the outpost, and science being able to print nearly anything they want and EMP/emitter it open on their outpost. While the vox outpost doesn't have cameras, borgs can open any doors at will and send/lockdown their shuttle at any time, and all but two rooms in the outpost can just be broken into through the windows.

Lack of security record is a problem but merging Trader PDAs and adding the Traders to the manifest should work out in that regard. Fix the oversights, don't just throw the baby out with the bathwater.

And while I don't want to argue by calling everyone in here inexperienced, I have to wonder how many of you have actually played Trader. Because the suits are slow as shit and no longer super armor, and the only airlocks that traders have access to are the arrivals/escape ones and public ones. No maintenance or department access. It's pretty hard to do any antagonizing on station when you don't have access anywhere and everyone's breathing down your neck wondering why you're wandering the halls instead of at your shuttle and hoping to secure Trader valids. At one point a non-antag actually fired a ricochet rifle at me (and killed themselves with the ricochet) because I wouldn't leave the bar.

Regarding free snowballing as Trader when vampire or changeling, this argument applies to the miners and xenoarchs in the same ways. Most Traders rush for the mining headset roundstart anyway so it's no use trying to glare/parasting them early, but more importantly, the Trader role is exclusionary enough from the server's general population that most Traders generally abide by the idea of the antags not killing the non-antags in exchange for not being revealed by the non-antags. I believe this meta is in place because otherwise you'd just die roundstart half the time as non-antag trader.

Finally I have to object to the use of a server poll to determine whether or not we remove antag rolls from Trader. A huge amount of the server has no idea what the vox outpost even looks like let alone ever played Trader, or even Vox at all. There's bound to be a large amount of mindless server-culture "gas the vox lmao" votes in favor of removing antag roles from a race and occupation that not everyone has the greatest of intentions towards. Something like removing vox heist being a poll makes sense since it's a gamemode that everyone gets affected by and everyone can easily opt into playing as by ticking "heist" on, but Trader is much more exclusionary and bound to be voted on for stupid reasons.

In the end I can't say I'm dissatisfied with the potential change at play here because it'd be nice to always be automatically trusted by the crew no matter what, which would allow for far greater freedom for gimmicks, tradertiding, and just getting dangerous shit from other people. But I'd rather people actually thought the potential change through and at least talked to someone who's played the role at least once.

**Comment by kernikov** [comment]
![democracy](https://cloud.githubusercontent.com/assets/5549060/24573983/7e733218-1651-11e7-9b77-c83f32c2ad25.png)
Make them target-able for traitors then.
Perhaps the syndicate has infiltrated an agent to the near-by station to have the vox assassinated.
The fact that they are not targets of antagonists, while they can BE antagonists, is unacceptable and no amount of "bloo bloo I play vox they dont kno bout my feefees" tears can change that

**Comment by despotate** [comment]
Do you not think it's a massive over-reaction to entirely remove vox traders from all antag roles just because _some_ objectives of _some_ antag types don't include traders? Who the hell even gives a shit about greentext at all, let alone enough to want to remove vox traders from being any type of antag?

Also they can be double agent targets last I checked, so the only thing you're complaining about here is that they can't be ling, vamp, or traitor targets. But that's kind of balanced out by how easy it is to kill traders if you get to them, and how small a lie you'd need to do it ("they stole my x" / "they assaulted me").

**Comment by kernikov** [comment]
> how easy it is to kill traders if you get to them, and how small a lie you'd need to do it

That seems to be an IC problem.

They're either completely fair game as targets or they get nothing.

**Comment by despotate** [comment]
Traders don't get to be Protect objectives either, we should multiply their chance of being antag by 2 to compensate. Also, since scientists are the only ones with to high risk items (TTVs) as non-heads, we should remove all non-scientists from antag roles as they don't have the burden of protecting an objective. Also, engineering shouldn't have antag roles either because they're the only department that has a private escape pod to use for the escape objective. Etc.

There's a million asymmetries amongst all the different jobs, and you seem to have latched onto a single one of them as an excuse to take away a playerbase's freedom to improve the round and have fun in an antagonizing way. Greentext is buggy enough as it is in the first place, eg heads have objectives to steal their own items, and there seems to have been no thought put into the poll whatsoever, what reasoning is there to remove Traders from being blobs? Blobs don't exactly get objectives to kill people.

**Comment by Allspice** [comment]
I believe scientists are banned from having TTV objectives for what it's worth, and heads should currently be banned from having to steal their own jumpsuit and job toys (if that comes up report it).

**Comment by IAGFPRMF** [comment]
Traitor traders (heh) have so much potential to do crazy and scummy shit. I wouldn't have it any other way. Observing some of the shenanigans traders have put the station through has been a blast.

I guess I'm alone on liking traders taking up hitman contracts, selling the armory back to the station, and buying slaves but since /vg/ isn't hardcore enough for even security or head antags like the good old days (you worthless whiny casuals), the chance to being an antag trader should be reduced and have objectives tweaked instead of removed entirely.

**Comment by Allspice** [comment]
Also both sec and head can get their antag rolls, not like you play them eyy.

**Comment by AutismSpider** [comment]
antag rolls for head and sec are low as shit should be the same for the jew burds

**Comment by Durgen** [comment]
traders should be blocked from rev, but I don't see a reason for the other roles

edit: revhead

**Comment by ghost** [comment]
traders should be blocked from everything but ling
it makes more sense for a ling wanting to infiltrate a mega corporation by disguising as a trader
also about the chem dispenser in the outpost, it's needed for hyperzine and mutagen because of xenobotany and xenoarch. Xenoarch suits slow down without magboots and you're going to be moving a lot
>analysis fluid
lmao only nerds use that, xenoarchs just hand pick everything and brush larges

**Comment by Durgen** [comment]
![how2playvoxtrader](https://cloud.githubusercontent.com/assets/19157295/24594272/15e0e122-17f1-11e7-9aa9-8dc06af61fc7.png)

voice changer and agent ID

**Comment by despotate** [comment]
I'm not saying scientists have TTV objectives, I'm saying they are tasked with protecting them and are thus more likely to die if they're working in toxins because some antag has the TTVs as their objective. Like a chef and scientist have the same chance of being antagonized if all other things are equal, but if a traitor has a theft objective then the scientist is much more likely to be antagonized as a direct result of greentext, since they'll be in the way of stealing a TTV or slime core extract. This is an example of there being "antag asymmetry" between different roles, so it's not really a valid excuse to take away antag from Traders entirely.

Overall I just don't see the argument against Traders having antag roles. If you believe they're too overpowered to be antags then that says something entirely different: which is that we should be nerfing them by making their outpost more accessible, taking away their toys, etc., because if you do remove their antag rolls then they are now not only overpowered but will always be trusted by the crew which just makes them even more OP.

**Comment by Allspice** [comment]
If traders have nothing to protect by dint of being in bumfuck nowhere and have less chance of dying thereby, that seems like an argument to remove their antag roll more than an argument to keep it.

**Comment by despotate** [comment]
> Traders don't get to be Protect objectives either

Antagonists can have the objective to kill someone. They can also have the objective to keep someone alive.

Traders are excluded from both of these, which balances them out.

**Comment by Durgen** [comment]
Is having access to steal objectives the metric by which we are allowing antag rolls? Should assistants be blocked from antag as well? This is all getting very esoteric.

I don't really understand the logic here. Do people think trader antags are OP? 

This whole vote/discussion seems to be based on gasthevox memes instead of real grievances.

**Comment by despotate** [comment]
Here's how I'm making sense of it:

- Server in general: gas the vox lmao
- Kernikov: Traders shouldn't be any form of antag solely for the one reason that they aren't a valid assassinate objective for other antags.
- Most other people in this thread?: Trader antags are OP.

Note however that most of the pre-poll responses are from a year ago when the average nonantag Trader was a griefing tradertider dickbag, so opinions likely changed about that.

**Comment by Allspice** [comment]
isn't the protect jectie twinned with someone else having assassinate on that person during DA

**Comment by Durgen** [comment]
@kernikov show me on the doll where a trader memestung you

![ckey](https://cloud.githubusercontent.com/assets/19157295/24594836/8641394e-17f6-11e7-83ae-86036542ef13.png)

**Comment by Kurfursten** [comment]
Vox Traders SHOULD be possible antag targets and possible antags. Bring back targeting Traders. We let people target miners and you just have to deal with that shit if you want greentext. The best part about targeting a trader is security probably won't even care.

>Traders are "unfair" as antags / antag targets because they have an outpost

You mean like those scientist guys who have an outpost? Plus bombs, mechs, protolathes, the tsci console, slime cores, artifacts, et cetera, et cetera? Or were you talking about the miners who have an outpost, unlimited money, jetpacks, drills that make short work of any wall, tons of guns, and an army of Pokemon?

**Comment by kernikov** [comment]
If traders are not targets, they should not be antagonists.
If traders are targets, they can be antagonists.

Revert #9514 or remove antag from traitors.
As per the poll, remove is winning with less than 24 hours left.
![democracy](https://cloud.githubusercontent.com/assets/5549060/24596144/a5fc1fae-1802-11e7-886c-2a1d33a667db.png)

>Logic fallacies because ur KFC cancer is getting changed

good shit 100

**Comment by Durgen** [comment]
I think we all agree reverting #9514 is a good idea.

**Comment by despotate** [comment]
You went through a bogglingly stupid amount of effort to paint Traders as undeserving of antag status, wasted the time of everyone who replied to you, and set up a poll just to try to revert something that I'm pretty sure no one is even against reverting?

**Comment by kernikov** [comment]
>It's your fault that I wasted my life writing 2000 words about birds and guns on a atmospherics simulator code forum belonging to a community of misfit weeaboos.

**Comment by despotate** [comment]
You spent the effort to write essays at the top and took an in game screenshot to try to back up your argument, along with getting dozens of others to pile on when you could as easily have just asked to revert the previous change to fulfill your greentext autism.

Also I'm surprised no one called you out on 

>  Why does a trader need to escape to the central command of an organization that he has literally zero ties to?

Changelings aren't traders or crew, they're aliens.

**Comment by kernikov** [comment]
![democracy](https://cloud.githubusercontent.com/assets/5549060/24693368/dd5ace7c-19a2-11e7-9bc1-fa68fbf0ca0e.png)
Mr. @Probe1 -achev, throw out those birds.

**Comment by Probe1** [comment]
Go right ahead m8.  Unless you are going to start paying me money then your balance ideas are being coded by you.

**Comment by Kurfursten** [comment]
I don't think this is relevant anymore since Merchants exist and significant changes have been made (e.g.: ling doesn't exist, traders can't be revs)

If anyone still cares they should open a new topic with a modern argument
