### ISSUE TITLE
Old viruses probably bugged

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#10843]
#### Description of issue

i think that old viruses are just bugged;
last shift there was a Magnitis virus on station, cure was iron, i gave iron to a lot of people and took about 200 iron units myself, it didn't cure it.
some days ago there was flu, cure was spaceacillin, i gave spaceacillin to all the crew and took about 150 units myself (not at the same time to avoid overdose of course), nothing happened.
#### Length of time in which bug has been known to occur

i saw the flu one about a week ago, i don't know if happened before.
#### Server revision

fd564aa3ff152d1b0fade3b5cf88662d970482d9 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ComicIronic** [comment]
I thought cures just stopped symptoms?

**Comment by uazuaz** [comment]
well, "cure" should cure the virus.
by the way, the magnitis symptoms didn't disappear, so the cure did absolutely nothing.

**Comment by Gringonius** [comment]
What, again? Not long ago both borging viruses were incurable and it became apparent when MoMMI's spaghetti was added.

**Comment by clusterfack** [comment]
This issue seems extremely familiar didn't someone fix this exact issue someone dig around in the old pull request look for it

**Comment by ghost** [comment]
The 'old' viruses have been broken forever. Every time someone finds one on deff and releases it an issue crops up and people yell that nothing works to cure it, yet no one has removed them. Their cures only have a chance of halting the progress of the virus, from what I remember. You still get stuck at whatever stage you're at, which means if you hit stage 4 you can't be cured. Well, you can be murdered and cloned, but with the virus still going around strong because people will have it regardless, you'll just contract it again and by the time you manage to 'cure' yourself again, you'll probably be at a late stage again. They just need to be taken out, they ruin rounds.

**Comment by Intigracy** [comment]
I fixed the borg virus yeah.

**Comment by icantthinkofanameritenow** [comment]
And it happened again. I'm thinking at this point we should remove old viruses entirely.

**Comment by DeityLink** [comment]
Magnitis is now a virus2 symptom, and other old diseases should no longer appear outside of adminbus.
