### ISSUE TITLE
Borer thought-speech inaudible as ghost w/o GhostEars but inrange

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10911]
(WEB REPORT BY: wizardcrying REMOTE: 172.93.109.202:7777)
Revision 0d91b25673f35182d69c6e36175ad143f2e1db89

It doesn't seem that it's possible to hear borers inside of anyone without enabling GhostEars. Even if you're within earshot of the host, thought-speech is still inaudible.

**Comment by Shadowmech88** [comment]
Thought-speech is not technically "talking" in the same way that humans talk. The borer enters a message, and then that message is displayed to the host/other borers directly via to_chat() instead of say(), which is why observers can't hear it by default.
Borer code then loops through all the observers in the `player_list` and checks specifically for ones with GhostEars on, then directly shows the message to those players in the same manner.

I suppose a possible fix would be to get all observers in range of the host that don't have GhostEars on, and show them the message as well?
