### ISSUE TITLE
Differentiating Pills And Bottles

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#10977]
Currently, there is essentially no reason to use bottled medicine when you could take it in pill form instead. The pill adds it directly to your bloodstream, it's faster than using a syringe, and it can deliver more meds at once than a syringe.

Should pills be given a gameplay difference from liquid medicine? For example, ingested pills needing 30 seconds before they take effect (to be digested) whereas injected medicines take effect immediately?

**Comment by PJB3005** [comment]
Eh. Bottles have their use in storing & separating chemicals.

**Comment by kol1th** [comment]
I never use bottles.

**Comment by 9600bauds** [comment]
Bottles are for mediborgs. Are you a mediborg?

**Comment by nuklearcellphoneg** [comment]
Things I use bottles for:

Clonex Cryox

Things I use pills for:

Everything else

It would be a big change in a lot of ways

**Comment by 9600bauds** [comment]
If we want to make bottles useful we could start by making them 50u

**Comment by nuklearcellphoneg** [comment]
This is true- no reason not to, you already have a nigh infinite amount of small beakers(2 boxes in chem, at least one in storage, 21 small beakers). Large and onward sized beakers are infinitely more useful than the small beakers.

As it stands, I know of maybe one instance where it can be more effective to injections, via IV. There is blood of course(can you just ingest it as pills? Never really tried, but that bit could be powergamed if so). A pill can hold 50u, but using a blue space or large blue space beaker(200-300u) you can load it with useful reagents. 300u is a bit rare, but let's look at a 200u.

25 derma
25 kelo
25 bicard
25 tricord
25 DD
25 Antitox
25 Dplus
25 Honey

Just as an example, this IV could replace cryo(in the sense of cryo being used to treat an injured person, and not a fresh clone). Albeit this is wasteful because it's very very very rare someone has all four damage types but it's a fire-and-forget tactic I guess.

b u t   w a i t

Bottles are still silly, even if you notched them to 50u, since 50u = 1 pill. It could be useful in the sense that you could only give people the right amount of a chem(kelo/derma IV, unhook them once they're almost at full health) which could be neat but

why not just stick them in the sleeper?

It's important to consider all the methods of administering medicine I guess.
1. Drinking
2. Pills
3. Reagents in food

## 
1. IV
2. Syringe
3. Cryo
4. Sleeper
5. Hugs? Vampires, but that's a virus iirc

I use to use bottles for putting the plasma back into plasma beaker I left near the grinder. Once we added in the pill-beaker function, I stopped doing that because putting it in a bottle meant I now had a useless bottle to put in the trash or leave on the ground.

Also, don't we have different functions for reagents based on ingest/all other forms, at least with regards to polyacid?

I do think it's an interesting concept but I'm not sure it would be easy to implement.

As bicaridine and kelo/derma are both a bit silly for ingesting for results (I know I know scifi http://memory-alpha.wikia.com/wiki/Bicaridine), and I know this is a bit of a side step, but what if instead of it being used as an injection/pill, we instead directed it to be a reagent which could be added to ointment/bandages instead?

While I'm thinking about it, characters also have a pulse which iirc is/was affected by inaprovaline(flavor text calls it a stimulant iirc), which increased the someone's heart rate but that's just flavor text stuff. Metabolism also isn't affected by hunger, where if you took a painkiller IRL while starving it would hit you much hard but doing so while full would have a greatly diminished effect.
