### ISSUE TITLE
Feet and hands still pop out when a whole limb is severed.

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#11000]
I actually haven't found an issue about this.
#### Description of issue

If you cut out (or lose) an arm or leg, your correspondent hand or foot flies off like you're made of glass.
#### Difference between expected and actual behavior

For the hand/foot to still remain attached to the limb. 

This issue has been going for so long we're pretty much accustomed to it, but I still think that changing the organ system so that organic limbs don't always split in two when removed would improve reattachment surgery without having to resort to mechanical limbs because they're much faster to use.

It also would make medbay frankenstein slightly more common, if you like that sort of thing.

**Comment by Exxion** [comment]
We don't have a system in place to handle this, but it would be really cool if we did
Hell, if we did, we could even make the head of the mob the root rather than the torso and fix a bunch of bugs/remove code that would be unnecessary in that case

It would be a lot of work and nobody would actually do it but I can dream

Also nice one getting #11000
