### ISSUE TITLE
Bleb gets resources so fast, holy shit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11009]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision a82df9e4f7eb04b6edc68a8d5c55cdf59ea52568
> 
> General description of the issue
> Deity's blob changes seems to have increased blob resource gen overmuch (perhaps because it no longer decreases over time/from lag?)
> 
> What you expected to happen
> Less resource gen
> 
> What actually happened
> Blebs can shit out strong blobs right and left in the face of heavy fire with middling econ, need one resource or two max in order to make a second core, et cetera. Extremely difficult to suppress even a blob that is facing space if it has half a mind of what it is doing, especially now that AEGs are more difficult to acquire.
> 
> Steps to reproduce if possible
> Become belb

**Comment by kol1th** [comment]
> discussion
> no discussion

wew

**Comment by clusterfack** [comment]
Who was doing statistic again? Was it @gbasood, would be useful

**Comment by kol1th** [comment]
too bad he fucked off

**Comment by clusterfack** [comment]
It's pretty fucking stupid using the web reporter for this kind of thing

**Comment by ihadtoregisterforthis** [comment]
Don't attack the blob from a single angle

**Comment by Allspice** [comment]
Well, bleb is still excessively strong. Even the hardest cheese with emitters and cargo lasers from multiple angles can't do shit because by the time you can logistics all of that the overmind shat out five cerebrates due to its resource gen buffs, good luck with that.

**Comment by gbasood** [comment]
@clusterfack #9626

Blob doesn't have any cool stat collection stuff going on aside from 'Who won, bleb or not bleb?' But you can add it easy
The viewing of  those stats is the hard part
Also, depending on how SQL performance is looking, it might be better to have the server offload stats to a DB than to a text file, since that's ultimately what the stats viewer, such as it is, does.

In terms of blob balance I don't see this as a problem, blob still struggles unless the crew manages to ignore it for 15+ mins it seems to me
