### ISSUE TITLE
Newscasters show a TODO message when printing newspapers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11076]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 7767f1234b8ea9736b7edeebe4178cf28599aec4
> 
> General description of the issue
> Newscasters have a TODO message at the end of the prompt to print a newspaper.

http://puu.sh/q7H4D/50d998aeba.png
//TODO CONTINU

**Comment by kol1th** [comment]
:joy:

**Comment by Exxion** [comment]
Ah yes, someone forgot that you can't fucking put comments in document-formatted text. Or at least you need to use HTML comment syntax rather than DM.

What's most mysterious is that the comment isn't actually cut off here. That's the whole thing.
What did the author want to continu? The world may never know.
