### ISSUE TITLE
Aliens and cages

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11072]
#### Description of issue

Alien simple animal mobs, such as queens and drones, don't seem to really care that they're caged, and lay vine nodes, resin nests, and eggs everywhere while being dragged around

Same could possibly be the case for carbon xenos
#### Difference between expected and actual behavior

Expected - Captured xenos to not shit the place up

Actual - Oh god sorry it's laying eggs everywhere, why is everyone wearing facehugger masks?

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
Once i took a caged simple mob sentinel to xenobio and told the xenobiologist to NOT open the cage's cover. 10 minutes later the AI is screaming that xenobio was breached and with sacs everywhere, because the HOP came in and "accidentally" opened the **DO NOT OPEN - LIVING XENO** cage's cover. The fact that their acid INSTANTLY melt down rwalls don't help at all, i wish we could keep them inside xenobio's slime cages.

**Comment by gbasood** [comment]
`if(isturf(loc))`

also since when do aliens get to melt ANY rwalls ever

**Comment by jknpj** [comment]
Since #9549, i think?

**Comment by ghost** [comment]
Thanks deity

**Comment by gbasood** [comment]
at least its only AI ayys

**Comment by Intigracy** [comment]
It's not caused by that one I'm pretty sure, he doesn't have any changes changing rwalls.
