### ISSUE TITLE
Allow changelings to succ catatonic mobs

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11095]
A few rounds ago I was trying to do a changeling gimmick with a catbeast monster. I made a tajaran and tried to absorb it but it didn't work because it was a catatonic. I did not care about the genomes, but I wanted to absorb it so I could use the changeling ability change species for my gimmick. I ahelped and none of the admins would want to jump in the body so I could perform this action. I suggest that changelings be able to absorb all catatonics, but get no genomes from them in return.

Benefits of being able to change species include letting you change into a
-skrell
-skellington
-plasmaman
-vox (jk this is a downgrade)
-diona
-catbeast
-unathi/lizarddude
-slimehuman
-golem
-probably some others I've forgotten

When you take away your ability to do things like stinging everyone into a skrell or being able to become a catbeast you absorbed, you take away FUN.

**Comment by Exxion** [comment]
I had assumed this was how it worked
You can't even absorb them just to get the appearance? That's stupid.

**Comment by kernikov** [comment]
Changelings also cannot succ decapitated mobs because the ckey is tied to the head.

**Comment by kol1th** [comment]
> When you take away your ability to do things like stinging everyone into a skrell 

That does not and never has worked like that

**Comment by Killette2** [comment]
> Be a skrell
> Transform sting

If it doesn't work, it should.

**Comment by icantthinkofanameritenow** [comment]
No.

I changed that for a good damn reason, and it's not going to be changed back because you want to force a stupid gimmick.

**Comment by 9600bauds** [comment]
I don't think you quite read all the text and words in this issue

**Comment by icantthinkofanameritenow** [comment]
@9600bauds
As far as I can tell from the code, the only way to get the appearance is by getting the genome too. IAnd since the check for braindead is the same as.the catatonic check, it'll once again.encourage lings to do nothing but wait for someone to go braindead, only this time they'll "only" get a free false identity. I simply do not see the reason in allowing that happen just because Killette2 couldn't get an admin to indulge him. 

If he wants it that badly, I'm sure that a ghetto brain transplant and a defibrillator would give him exactly what he wants without bringing back the age of sucking off monkeymen. Either that or an emagged cloning console. in either case, you get a non-braindead but perfectly vulnerable victim whose species you can pick out in advance. And if you're really set on it, ask to have your own brain transplanted into one of those things- changelings keep their changeling status if their brains are transplanted, so you'll get your power to turn people into Skrell with no strings attached.

**Comment by Killette2** [comment]
Here's where all your logic is flawed @icantthinkofanameritenow 
-hoping it's traitorchang instead of changeling and waiting for emag to emag cloning
-allowing others to turn you into a catbeast as an antag
-thinking you will have the time to perform surgery on another to make them another species, THEN absorbing them

You also have to remember this isn't about being a species 100% of the time, it's about being able to transform back and forth.

**Comment by icantthinkofanameritenow** [comment]
@Killette2 
And I can now personally verify the latter is entirely possible and in fact actually pulled it off myself during a round on the serb. All you need is a defib and you can just transplant the guy you just succed and succ him again right there. It even gives you another genome for doing so. Shit, you don't even need to be an actual doctor; as long as you can hack into ghetto surgery you should be just fine. Just think about it- if I of all people can do it any programming crutches, I know you can too. Just use your imagination for something other than inane feature requests every now and then. 

Also, protip: that black gift on the telecomms satellite in Box has a good chance of having an emag inside of it. Use that. 

Now if you want to code a "Change species" power that lets you become a species you haven't absorbed yet or somehow decouple the appearance stealing from the absorption itself without totally wrecking the code in the process, be my guest. But don't you dare think that wrecking a hard-earned balance just for a single gimmick that can be done in ways you couldn't be bothered to figure out is anything less than frivolous and selfish.

**Comment by Killette2** [comment]
I think anyone can figure out surgery fam. Some things just aren't worth the time and by the time you're done doing it, the round's over.

**Comment by icantthinkofanameritenow** [comment]
When I pulled it off, it ended up being less than halfway through the round but that's not the point. 

The point is that you can't get the appearance without the genome, and if you let changelings absorb catatonic mobs again you go right back to the tedious, boring rounds that they almost always were before my update happened. And I'm not sure it's even possible to decouple the appearance theft from taking the genomes.

 It's unfortunate, but better to give up an easy gimmick than fuck over balance for the sake of convenience- or worse, break a mode completely by trying to do so.

**Comment by Exxion** [comment]
Or someone could just make it so that you _can_ get the appearance without the genome

**Comment by icantthinkofanameritenow** [comment]
@Exxion 
DNA extract sting already does that...but it uses the same code as.absorb to work so it too will fail automatically. 

Not to mention the balance issues that would arise from any changeling being able to disguise as anybody with a mere touch in a manner that's wholly undetectable and costs no evolution points to attain. You just gotta think these things all the way through man. It's simply _not worth it_.

**Comment by Exxion** [comment]
I meant it could be changed so that absorb can get the appearance without the genome if used on a catatonic mob

**Comment by icantthinkofanameritenow** [comment]
@Exxion
It would still give the changeling a new identity for zero effort and encourage them to do nothing but sit on their asses waiting for someone to ghost.

Does nobody want to work for their gimmicks these days?

**Comment by Killette2** [comment]
> New identity
> Of someone without a PDA, ID, or spot on the crew manifest

Not a real good identity if you ask me.

**Comment by icantthinkofanameritenow** [comment]
@Killette2

What, hasn't it occurred to you that you could give some.bullshit along the lines of "I lost my ID" or "I was brain transplanted"? Or just not be seen by people who would give enough fuck's to check the manifest?

**Comment by Killette2** [comment]
> It's a disguise that's easy to obtain!
> YOU JUST CAN'T BE SEEN BY ANYONE WITH IT!

Really moving the goalpost of what's considered an "easy to get, overpowered, disguise" huh?

**Comment by icantthinkofanameritenow** [comment]
Really twisting my words around, aren't you. Put bluntly, it's called "lying about losing your ID". You'd be surprised how many people believe that excuse.

**Comment by Killette2** [comment]
> Hey HoP I lost my ID

Sure you need an ID and PDA?

> Yes please

Let me just go into the accounting room to find your account so I can link it to your ID
_goes in room_
Funny, I don't see that man listed in here...
_goes back outside_
Were you put in a monkeyman by chance?

> Uhhh yeah

Who were you before?

> _leaves_

:s security to HoP office, we have someone here who's not on our crew

**Comment by icantthinkofanameritenow** [comment]
@Killette2
That's more of a sign of how bad you are at bluffing than anything else.  Everyone knows that you should never show signs of nervousness when lying and to stick to your story no matter what. 

But let's drop that point for now and focus on something else. Suppose this worked in a way that would allow catatonics to be absorbed **but not monkeymen**.

Assuming this was even possible given that the code can't tell the difference between a monkeyman and a player who ghosted partway through the round, it would be acceptable enough since players going catatonic is an exception rather than the rule. But on the other hand that could backfire as people being absorbed ghost during the process to deny the changeling their genomes. All in all, it would still be an awful lot of work with a bunch of potential complications just to enable a single gimmick you'll probably use once or twice before it gets boring/makes the rest of the serb hate you. It also assumes someone will become a catbeast, which is itself very rare without a geneticist who is either an antag or willing to do antag-like things. 

Another alternative would be to make an "advanced transform sting" that would turn someone into a species of your choice with.a random appearance.. That would sidestep the need to absorb anyone at all and so make this entire debate irrelevant. That being said, seeing that your goal was to (I can assume) change people into catbeasts left and right, it would need a fairly large evolution point requirement and chemical cost.

**Comment by Killette2** [comment]
That wasn't my bluffing but just an example. Point is, we USED to be able to do this, but now you're saying we shouldn't have it back because it was "too easy" despite not giving the changelings a genome, their most powerful resource.

Why should it stay gone when we used to be able to steal their species, UI, AND genomes? This also ignores the fact that this would all be void if we had all species unwhitelisted but I'd rather not have that happen.

**Comment by icantthinkofanameritenow** [comment]
> we USED to do this

Do what, bluff competently or suck off monkeymen for consequence-free bonuses? The first is something we need more of, the second has been sent to its well-deserved grave. There has never been a time when absorbing did not give evolution points, at least to my knowledge. And unless you want to switch us over to TG's changeling code, that's not going to change. 

> Why should it stay gone when we used to be able to steal their species, UI, AND genomes? This also ignores the fact that this would all be void if we had all species unwhitelisted but I'd rather not have that happen.

Let's look at what things are like now. The average changeling is a cowardly fuck who can only antagonize with all of his fellow changelings at his back, knowing they won't betray him because they too are too cowardly to do so. Before I removed the ability to suck catatonics and monkeymen, it was even worse because they would never attack anyone that could actually resist them unless they were in horror mode guaranteeing that any changeling round was identical to extended. The question is, why didn't any of them try any fun things like what you suggest when they had a chance to do so? (And why didn't you at that matter? The change has been in effect for months, so you have no excuse for your ignorance.)

But if you must, I suppose I can copypaste the vampire transform power over and give it a "species select" menu as well. It's not like the vamps ever used it anyway.

**Comment by Killette2** [comment]
I guess species change is good, because that's literally all I cared about. Genomes are not the issue, and when trying to absorb the catonic mob, I was hoping to be able to zorb it but just get no points. Instead, we lead to this issue when I wasn't able to absorb it at all. I mainly want the ability to more easily obtain other species you aren't likely to encounter (due to whitelist) ICly to absorb without surgery, and the ability to turn others into it isn't really needed and could be deemed overpowered like catbeasting. Not like it matters when you have deathsting anyways, but that's another power issue.

**Comment by icantthinkofanameritenow** [comment]
And one that I will be able to fix much more easily, no doubt.

Problem is, I don't know what kind of code would be able to create that effect, and I get the feeling that in practice it'll be all but completely ignored since nobody in their right mind would actually want to turn into a catbeast. (Plus, as you mentioned it shouldn't be able to be used with transform sting since otherwise it would lead to catbeasting everyone.)
