### ISSUE TITLE
Internal Affairs has fucked up access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11172]
(WEB REPORT BY: senaat1 REMOTE: 172.93.109.202:7777)
Revision: 868b010626d9f9738f0b203d8b64c1b16d59bf60 
In Security: 
Can open podbay maintenance just fine.
http://i.imgur.com/lecjmE8.png

But not the main door?
http://i.imgur.com/XykW1Uz.png

In Cargo:

Can't open front door (or any of the side doors really)
http://i.imgur.com/nS19WWN.png

Can open maintenance though??
http://i.imgur.com/sSCaZ0c.png
http://i.imgur.com/Q79aqNF.png

**Comment by Durgen** [comment]
i was hoping nobody would ever point this out

**Comment by Kurfursten** [comment]
It's not really fucked up access so much as a quirk of the system.

IAA has Cargo Bay so he can inspect what's being bought, but not Cargo Office because that has some other things attached to it (IIRC, MULE controls and the order console)

IAA has courtroom access but not prison access (so he can't just release prisoners himself), so in this case it's more like "we wanted to let IAAs get to the secpod". You could argue that the pod door should use generic security access anyway, though.

Another little-mentioned fact is that the IAA gets full service access and generic medical bay access. And while most people know he gets Bridge now, few know he gets announcement privileges.
