### ISSUE TITLE
Glowberries don't glow

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11188]
(WEB REPORT BY: higgsbonbon REMOTE: 172.93.109.202:7777)

> ccb55b121a3fd5338fc56a602424016009566488 
> 
> Unlike similar plants like novaflowers and glowshrooms, glowberries do not luminesce, neither the plant or product.

**Comment by Kurfursten** [comment]
Looks like glowberries use some kind of depreciated effect from before we used biolum as a standard with @9600bauds botany3

They have two snowflake vars related to light that seem unused

> Glowberries contain uranium instead of radium

Wow, neat, I never realized this. Now I can make so many bartenders so happy.

**Comment by Exxion** [comment]
But radium makes a much cooler drink than any of the ones you can make with uranium

**Comment by Killette2** [comment]
Did I hear... BOTANY?

A fun fact is, that bioluminescence isn't from botany3. In fact, it actually came from the very first, botany1! What do you mean Kill-sama? What I mean is glowshrooms! Glowshrooms and glowberries have coexisted in spacestation 13 for a very long time, many years even. The question that should be asked is why they haven't gotten it yet.

See my issue bellow regarding glowshrooms and how they work. They don't work as they should since the creation of botany2 and botany3, but they were still the first bioluminescence plant that existed in botany1 along with every other plant.

#11099

**Comment by PJB3005** [comment]
I know for a fact that when I ported baylights initially I was extremely confused when working with the growshrooms, I have no idea why anymore but it was probably because I was shit at coding back then.

It's not impossible I broke this.
