### ISSUE TITLE
MoMMi spaghetti not working properly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11248]
(WEB REPORT BY: rattletrap REMOTE: 172.93.109.202:7777)

> Revision c8d679e1bc0bdd3f99107dfa51401c224d0d0650
> 
> General description of the issue
> Eating MoMMi spaghetti only seems to work half the time, sometimes it doesn't make you start beeping booping at all, and other times it gives you the wrong virus and you become a cyborg instead of a MoMMi.
> 
> What you expected to happen
> MoMMi spaghetti turns you into a MoMMi
> 
> What actually happened
> MoMMi spaghetti didn't work after eating it once, second time it worked except it turned me into a cyborg
> 
> Steps to reproduce if possible
> Eat MoMMi spaghetti

**Comment by Kurfursten** [comment]
There's a really simple explanation for this.
1. Roburgers and MoMMI Spaghetti in general don't seem coded to work all the time. It's actually a miracle they work as often as they do, because it seems like you should only get a 10% chance per bite.
2. The code for Autism Nanites (chemsitry-reagents.dm line 2331) is really poorly thought through. It's a child of regular nanites and runs ..() so of course it tries to give normal robotic transformation before it tries to give mommi transformation. @Zth-- wasn't really thinking - there are plenty of other ways to implement this that don't involve mixing inheritance and copy/paste, but granted he does mostly basic stuff.

@Intigracy already fixed another issue from the same PR. It just goes to show we shouldn't let a small PR slip by without review/comments (although in turn, it created this problem with the inheritance).

**Comment by Killette2** [comment]
I saw that in the food code where mommi spaghetti has an incredibly tiny bitesize full of the nanites right? Why didn't we just code a new chemical?

**Comment by Kurfursten** [comment]
It is a different chemical, the chemical is coded badly

**Comment by Zth--** [comment]
@Kurfursten is right. I had a wrong idea of how "..()" worked
