### ISSUE TITLE
Give non-humans lower wages.

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11250]
Now that we have economy and pay rates every so often on the station, how come non-humans like voxes and grays get paid the same rate as humans, who are supposed to have more authority and rights than these other races?

Would we be able to lower the pay for non-human employees, and if the is a good idea how much less money should each race get? It would also be worthy to note we would see more things like vox doing odd jobs for money if they care about it, which would make for good and creatively entertaining roleplay.

**Comment by Shadowmech88** [comment]
How about 3/5ths of a human's wage?

**Comment by jknpj** [comment]
> how come non-humans like voxes and grays get paid the same rate as humans

Because they do the same job? Grays are smarter and vox are physically stronger than humans. I see o point in non-humans earning less, unless they are trying to do something the race is bad at or if they are not doing their job properly.

**Comment by SkowronX** [comment]
2/5 the wages please. And no head/management roles.

**Comment by Kurfursten** [comment]
I don't know why we even have wages for every job. Maybe for sec and doctors, but it seems to defeat the point of "economy" if you're just paying everyone a flat rate so they have money but have nothing to use it on or any motivation to use it.

> Scientist, I'll pay you 100 credits for a temperature gun
> But I'll get paid regardless by the company

**Comment by gbasood** [comment]
You can always implement per-role wages.

**Comment by Megamaw** [comment]
as a nonhuman player, this would add to the idea that humans are easy mode.

it makes sense in lore, i think? i do not oppose. i think this is interesting. we just need more ideas for what to do with money.

**Comment by gbasood** [comment]
I've said this about as many places as I can
Money will always be useless until:
- Cargo crates are completely revalued
- Mining income gets nerfed to shit

Other than that, you would need to introduce some sort of resource scarcity, either by removing items from the station (metal sheets etc) or by adding cargo-only items to get people to order stuff
I emphasize cargo so  much because that's currently the main money sink as well as the main income generator, even with wages

**Comment by Kurfursten** [comment]
Last time mining income tried to be nerfed was in #3893, and @NigglyWiggly blocked it.

Haven't seen him very active anymore though, so maybe it is finally time to ease up on that cash. I'd say something like.

> Lower ore redemption income and mining vendor prices by 90%, miners no longer receive periodic income

I firmly agree with you that the problem of making money worthwhile is solved by adding more things to do with money though.

**Comment by NigglyWiggly** [comment]
**IS SOME FUCKER TRYING TO TAKE AWAY MY MINERBUX**

**Comment by PJB3005** [comment]
Yes.

**Comment by Megamaw** [comment]
@NigglyWiggly to be fair A: you don't play anymore and B: if we want money to be useful and to give it more stuff we need to make it so every money related problem can't be solved by just mining

**Comment by gbasood** [comment]
@Kurfursten I'd say that 90% reduction is good, it's roughly along the lines of what I was thinking
Values can always be tweaked
@NigglyWiggly 

> research station
> primary income is from mining
> income from mining so vastly outweighs other jobs/tasks/labor that the miners are the most highly paid job on a **RESEARCH STATION**
> one miner can earn more money than the entire rest of the station's account balances combined in 10-15 mins

Speaking of mining outweighing research, maybe R&D could make money by increasing tech levels

**Comment by ghost** [comment]
90% reduction doesn't go far enough.

**Comment by ihadtoregisterforthis** [comment]
Killing miner income can kill mining.
Lowering vendor prices can lead to _even easier_ to obtain weapons, jetpacks, pokemon, alien killing robots and soap.

**Comment by Kurfursten** [comment]
@ihadtoregisterforthis You can just activate the throw wire for free weapons and jetpacks anyway.

**Comment by Exxion** [comment]
Even if you couldn't, you can probably buy the whole vending machine (or at the very least one of everything) after one good expedition. The most expensive thing in there is a measly 3000 credits, right?

**Comment by Kurfursten** [comment]
That's right. For reference, breaking one tile of plasma (one of the most common ores) is worth 5 (pieces) \* 40 (value of single ore) = 200.

**Comment by NigglyWiggly** [comment]
Nerfing Miningbux so drastically is stupid, IMO.
I've always enjoyed being stupidly rich as a miner, but that is silly if we're actually going to try to fix the economy here, but as it stands, everything is fucking super overpriced, and destroying all the profit of mining will make it far less rewarding.
If we are actually going to change economy shit, maybe we should start with laying out guidelines on what fucking credits are worth, because right now you can buy a bunch of full pizzas for the same price as a bag of chips.

**Comment by Killette2** [comment]
> nerfing mining is stupid
> I always enjoyed being stupidly rich as a miner

I also thought the pizzas were always insane cheap from cargo compared to selling food on a menu as a chef. Cargo always undermined you with stupid pizza.

**Comment by Kurfursten** [comment]
Pizza isn't as bad as it used to be. It's 75 now, used to be 15. That's still 2,000 nutrition for just $75, though.

@NigglyWiggly It's funny you mention that because the same PR that standardized prices for vending machines was the one that raised pizza cost by 400%. You have to take things in increments, though, or people freak out. People like NigglyWiggly. Your point is taken, though, maybe people are ready for pizzas to be split up into

> Pizza Order: $75
> Crate of 3 Pizzas: $225
> Crate of 5 Pizzas: $375

That would still make pizzas a cheaper option for nutriment than vending machines by a lot (vending machines would be about 3x more expensive for that nutriment amount) but it wouldn't be as crazy a difference as it is now.

**Comment by Killette2** [comment]
> want to buy chips while on break at my job of being a professional shitter
> know it will cost 2 hours worth of salary

Being a spessman seems tough

**Comment by Kurfursten** [comment]
> Professional shitter
> Not breaking into botany to cook your own chips

**Comment by Megamaw** [comment]
maybe we should make chips and shit cheaper, but pizza still better in general? idk, the current prices for stuff r/n are pretty bloated

**Comment by Kurfursten** [comment]
Ramen still has an extremely good nutrition / cost ratio, it's dirt cheap. Dan food, too -- extremely cheap for its nutrition value and the only downside is having the occasional pain message.

The problem with making chips cost like $5 is that there's no reason to visit the kitchen when you can get an unlimited amount of food that you know hasn't been tampered with, so there's no reason to have a chef anymore.

I'm not one of those people who insists on "economy" where people have to trade, I don't think you should have to pay the chef every time you swing by his table, but I do want the chef to have a reason to exist at all.

**Comment by gbasood** [comment]
@NigglyWiggly 
>everything is fucking super overpriced, and destroying all the profit of mining will make it far less rewarding.

Name one thing you can't buy after 5 minutes of mining
@Megamaw
**PIZZAS ARE MORE EXPENSIVE THAN GUNS**
This is the most fucking stupid thing ever and I hate it
