### ISSUE TITLE
with all my good ideas i must recommend a bad idea

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#11294]
feature request: supplementary materials for SS13 say space lube is used in lubricating machines for higher performance

quoth wiki: "Space Lube is a high performance lubricant intended for maintenance of extremely complex mechanical equipment"

what if we gave it a use OTHER than slipping people, like increasing speed of the janicart, increasing MULE's something, improving mechs, pods, maybe even borgs?

ie, give people an excuse to make space lube besides slipping folks

note: probably terrible

**Comment by AutismSpider** [comment]
We have rags and stuff can be use to rub down stuff even works on cyborgs/mommis

So rub rag of lube on mule bot cyborgs etc for speed boost

**Comment by Kurfursten** [comment]
Something like a year ago I wrote something like this for fabs and grinders, but after much meditating on it I realized that no one would use this anyway because they're all pretty fast to begin with. Lubing the turbines of the TEG for more output still seems like a good idea to me though, because it encourages interdepartment interaction.

**Comment by AutismSpider** [comment]
Lube that hard to make even as jack ass clown i can make lube by buying crap out of food vends/soda vends etc

**Comment by Killette2** [comment]
I suggested this years ago and I'm probably not even the first. I like the idea of mechs having a lube reservoir that they can tap into to boost their speeds in certain areas.

**Comment by Exxion** [comment]
Pretty sure this was implemented for the TEG
