### ISSUE TITLE
Feature Request: Anti-NPC gun

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11302]
(WEB REPORT BY: rattletrap REMOTE: 172.93.109.202:7777)
So a gun that can only harm NPC's, space carp, bears, spiders, that kinda thing. Give it to sec officers and maybe as a sec borg upgrade?

My reasoning for this would be to encourage a kind of "protector" mindset in asimov secborgs, allow them to actually save crew from wild space animals without having to waltz in with a harm baton and get to integrity 50% every time you go to fight anything.
Security officers don't get any lethals unless there's a Warden or HoS, it would be nice if they could save people from at least space carp without breaking into the armory themselves.
I know you can just research illegal module board and give a secborg a laser gun and sec officers shouldn't be without at least a warden anyway, but I want some opinions about how terrible this is regardless.

Codewise, I have no idea how hard this would be to code and I sure can't code for shit so someone enlighten me as to what kind of impossibility I'm proposing here.

**Comment by Exxion** [comment]
It would be quite easy to code, but a way to explain how it works without utterly obliterating immulsions is not immediately obvious

**Comment by Ephx1** [comment]
A mind fryer that only works on lower beings, only gives headaches to sentient things.

BAM
EDIT: Lower beings also includes vox

**Comment by ghost** [comment]
@Ephx1 I don't like it, sounds like a cop-out.

**Comment by Ephx1** [comment]
I can't really think of any other way that it would work, some of these creatures I would argue are stronger than humans so a weak firearm wouldn't work.

**Comment by Killette2** [comment]
A gun called law 1. Harms anything that's not a human and is asimov's best friend.

**Comment by Rattlederp** [comment]
Ephx's idea actually sounds better than what I was thinking, maybe except for the Vox part. Brain waves makes a lot of sense in this case since its only supposed to kill NPC's. My idea was to tie it to the animals' genetics. Since these animals are a consistent problem for space stations throughout spess, scientists collected genetic data from the dead creatures and modified a floral somatoray to scramble the DNA of these creatures rather than of plants. The rapid mutations, caused by multiple hits, kill the creatures. Although the name of the gun itself.. Atomic Valence Resonator? I still think Ephx's idea makes a lot more sense than mine. In any event, its a niche-filling gun, so I dont think it'll be high priority on any coder's list even if it was agreed on as a good idea

**Comment by NigglyWiggly** [comment]
> maybe except for the Vox part

Reminder that Vox are literally retarded, so it would make perfect sense for them to be functioning at a much lower intellect

**Comment by Ephx1** [comment]
Aside from the players, the whole "Vox are literal retards" is a thing from Bay where the on-station vox are those who fucked up and had parts of their brains ripped out.

Should totally incorporate it into our five sentence """lore""" though

**Comment by Rattlederp** [comment]
Well then I can't argue with that logic, vox should be hurt by it too the damn birds

**Comment by Exxion** [comment]
This was kind of fulfilled by the hunting rifle
