### ISSUE TITLE
suggestion about electrified grilles and glass shards

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#11359]
i know that it was talked about this before and i know that glass is not a conductor, but having glass shards that can destroy electrified grills makes electrified grills totally pointless;
every time you hit a metal grille with a piece of broken glass you should at least receive cut damage on your hand on each hit.

**Comment by 9600bauds** [comment]
I have already said too many times that I think this whole "glass shards are the only thing that safely destroy shocked grilles" thing is gold-plated stupid
Also double stupid that grilles used to have specific code to take LESS damage from glass shards and it was removed 4nr
When Bump() gets fixed I'll make it so that grilles take light damage from any thrown item and remove the glass shard snowflake. That way, you can still break a grille with a glass shard, you just gotta throw it a lot.

**Comment by FudgePucker** [comment]
BUT MUH PERMA EXCAPE
IF SECURITYS LIVES ARENT FUCKING MISERABLE THEN SATAN WINS

**Comment by AlphaBuffalo** [comment]
I think that holding a glass shard should hurt the holder unless they're wearing gloves

**Comment by AutismSpider** [comment]
dumb as fuck really

>cut a fucking shock grilled with glass is ok 

>try do it with fucking esword shocks you or boners bone sword/hammer

**Comment by 9600bauds** [comment]
Not just glass, specifically glass shards
A broken bottle still shocks you

**Comment by Rattlederp** [comment]
bauds our savior from the greytiding hordes

**Comment by AutismSpider** [comment]
force you to use gloves to hit it etc.and make so only E sword can cut it down with out getting shocked to death.

**Comment by AlphaBuffalo** [comment]
is there a way to have it check if the obj doing the hitting is made of glass?

**Comment by ComicIronic** [comment]
Shocking from the grille is based off the siemens_coeff of the item being used. Please don't bandy around the word "snowflake" for no reason - glass shards are not snowflaked to not conduct, they just have a siemens of 0, which makes them a non-conductor. If you want to make other things not conduct, set their seimens to 0. This could easily be done for eswords: better still, we could do something like:

```
/obj/item/weapon/melee/energy/sword/is_conductor(var/siemens_min)
    if(active)
        return 0
    return 1
```

That way eswords would only be conductors while not turned on.

**Comment by Kurfursten** [comment]
@ComicIronic You keep saying it in this way but it's a little deceptive, I'm not sure why you don't just tell the whole story because it would make the whole situation a lot more clear and I don't even know why you keep avoiding explaining it this way. There's nothing incriminating about this at all, it's actually BETTER implementation.

What Comic MEANS to say is:

> You're right. It was snowflake once, but a few months ago around April I personally removed the snowflake code in grille and added siemen's coefficient = 0 to glass shards.

I'm not sure why you keep avoiding saying it this way, because it would make a lot more sense to people who saw the previous code and know it was snowflaked once. Are you worried people will complain that you changed the SC on glass shards?

**Comment by ComicIronic** [comment]
The PR in April of last year? I'm not avoiding explaining it like that, I just don't see the need to add all the extra detail. The new system has been in place for 16 months, and bauds clearly knows about those changes, because he even complained that I removed the special case for glass shards that caused them to do 1/10th of their damage to grilles.

**Comment by 9600bauds** [comment]
When I say "snowflake" I mean "glass shards and specifically glass shards are the only item in the whole game that are used for this purpose", replace with whatever term suits you for it we both know exactly the whole story.

**Comment by Kurfursten** [comment]
If I understand your point, bauds, it's that many things in the game (beakers, buckets, bar drinking glasses, vials, plastic bags, plastic forks, everything made of plastic really, basically all clothing, shoes, etc) should ALL have either a 0 or very low coefficient. Yet glass shards were given primacy, someone went out of their way to specifically change their value alone, BECAUSE they come with every broken window.

**Comment by ComicIronic** [comment]
They are the only items which were edited to have a 0 value because it kept their behaviour as not shocking you when you hit a grille with them. Nothing has prevented anyone from making more items have 0 siemens, and I feel like we've had this discussion a number of times in the past, but nobody has made a PR to add 0 siemens to more items, even though it would typically be a 1 line change.

If you think more things should not conduct, for the love of Christ, make a PR to make it so. This is why these systems exist.
