### ISSUE TITLE
Weird borer gene unlocking

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11399]
(WEB REPORT BY: sjbenster REMOTE: 172.93.109.202:7777)

> Revision d991fac3b115187ac9486336123a55f7f360e668
> 
> General description of the issue
> After unlocking genes for my host, I crawled out of him, he then lost his genes. After crawling back in, I had to evolve them again to get them to unlock.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Wizardcrying** [comment]
:100:

**Comment by Shadowmech88** [comment]
Gene unlocking for borers has always been unintuitive, even before multiborers.

I believe the current, and intended, progression is that you spend chems to unlock a gene _one time_ in _one host_. If you leave the host, they lose the gene. When you re-enter them, since they don't have the gene, you have to unlock it again.

I believe this is done so that a single borer can't hop from host to host unlocking everyone's genes.

As far as jumping in and out of the same host, I don't see any way to fix it except to have a human-level list of genes that were unlocked by borers specifically as well as the name of the borer that unlocked each gene, and then check the list every time a borer enters a host to see whether _that_ particular borer had previously unlocked _that_ specific gene for the host before, and then re-unlock the gene if so.
Which sounds really convoluted to me.

**Comment by SonixApache** [comment]
Wouldn't it make a lot more sense to just have it unlock genes permanently for the host but reset the progress for the borer?

**Comment by Shadowmech88** [comment]
> unlock genes permanently for the host

Then you'd have the situation I described where a single borer can hop from host to host, permanently unlocking the genes of the whole station.

**Comment by Shadowmech88** [comment]
I think this should be re-tagged as feature request. Even before I touched them, it was explicitly intended for hosts to lose their mutations when the borers leave.
