### ISSUE TITLE
Autolathe Shock Doesn't Appear to Check Adjacency

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#11410]
@ComicIronic 

Opened autolathe menu
Someone else was hacking it
Walked away
They hit the shock wire
Killed me all the way in the brig with electrical shocks by clicking on the lathe over and over

Pls fix

**Comment by kol1th** [comment]
It's vending machines all over again.

**Comment by ghost** [comment]
Weird. Whenever I've hacked autolathes lately, the shock wire didn't take effect until after it was screwdriver closed, and then it would just shock whenever you did anything to it.

**Comment by JustSumBody** [comment]
After testing it extensively*, I was able to replicate this under the following conditions:
1)have someone start hacking the machine
2)have someone else open the wire menu while the machine's panel is still open, then walk away while keeping the wire menu open
3)shock the machine
4) The first person then begins printing stuff from the lathe/recycling stuff(also a fun fact: If you rapid fire click on the name of the item in the construction it will bypass the queue entirely and print multiple things simultaneously)
5) Second person gets shocked
I have no idea why this is happening since "shock" should only be called on the person interacting with it, unless there's something really weird happening with the way wires set user.

**Comment by Kurfursten** [comment]
Yeah, the circumstances you mention are exactly like my situation. I'll describe it just for comparison.

> Someone has built a public autolathe in the halls
> I walk up and try to use it, but when I click on it, I get the wire prompt, and I realize someone is hacking it
> Just walk away instead
> About 40 seconds later they start printing things and I die
