### ISSUE TITLE
Creeper vines fruit sprite broken

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11449]
No matter how long I waited, the fruit sprite only grew in the 3x3 area around the original plant. Bellow are pictured the bug, and the plant stats.

Fruit was still harvestable without the sprite, the sprite just never showed up.

![grass136](https://cloud.githubusercontent.com/assets/5169310/17724269/b1ef0860-640e-11e6-9fe8-9e37fb477a1f.png)

![fruitsprite](https://cloud.githubusercontent.com/assets/5169310/17724283/d34735aa-640e-11e6-8f69-285e6d27ef08.png)

**Comment by Exxion** [comment]
Was it just the sprite, or were the rest of the vines not actually growing fruit at all?

**Comment by Killette2** [comment]
Just the sprite. You could harvest them but there was never any indication that it was ready.

**Comment by Exxion** [comment]
How strange.

**Comment by Kurfursten** [comment]
I have also seen this happen but I thought I was crazy.

**Comment by Killette2** [comment]
It's existed quite a long time. It was supposively fixed forever ago but I witnessed it again.

**Comment by Killette2** [comment]
Still a bug. First officially reported in april
https://github.com/d3athrow/vgstation13/issues/9744

**Comment by Killette2** [comment]
Still a thing 🙁
How fix?

**Comment by Exxion** [comment]
Judging by the code, this is intended.
It's stupid as fuck though

**Comment by Killette2** [comment]
If I could add another 2 cents, would we be able to sprite the fruit to be a little less bulky? It takes a lot of the remaining visibility that the tile would otherwise have

**Comment by Killette2** [comment]
New information

This might only affect creeper vines, but not kudzu vines

**Comment by Exxion** [comment]
We don't really need more information
The cause is clear in the code
The sprite used for a given vine tile is based only on a single numerical var, which decreases with distance from the center
Fixing it without removing the feature would require making a bunch of new sprites, which is probably more work than the feature is worth

To be clear, the feature I'm suggesting removing is just making vines look less healthy farther from their center, and affects only their appearance.

**Comment by Eneocho** [comment]
No longer seems to be the case.
