### ISSUE TITLE
Drop Windows XP support?

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#11452]
Windows XP is basically dead, and supporting it is a major pain in the ass because we can't use anything higher than IE8 for interfaces.

**Comment by Exxion** [comment]
Why didn't we stop supporting it when Microsoft did?

**Comment by PJB3005** [comment]
Because BYOND still technically supports it.

**Comment by PJB3005** [comment]
On that note should we drop Vista while we're at it too? Then we can go all the way up to IE 11.

**Comment by AlphaBuffalo** [comment]
We should drop support for 7 and 8 and use edge :^)

**Comment by Exxion** [comment]
I would almost support that if it were actually possible

**Comment by AlphaBuffalo** [comment]
If only we didn't have to rely on IE, anything is better than IE

**Comment by gbasood** [comment]
i'm so glad that many of our players play on literal 10+ year old toasters

**Comment by NigglyWiggly** [comment]
For what purpose

**Comment by Exxion** [comment]
So that we don't have to gimp the possibilities of Goonchat in order to support a fucking stone age operating system

**Comment by ComicIronic** [comment]
XP is still estimated as 10% of the market, and unless someone got Wine Byond working at all, paying for a Windows upgrade will be the only recourse for some players.

**Comment by PJB3005** [comment]
> and unless someone got Wine Byond working at all

They did.

Although I'm not sure yet whether IE9 is supported yet in WINE, but it's being worked on.

**Comment by AlphaBuffalo** [comment]
We should do a survey to see who still uses XP tbh

**Comment by AlphaBuffalo** [comment]
http://www.strawpoll.me/11013647

**Comment by PJB3005** [comment]
![](http://i.imgur.com/ptVxvAl.png)

This isn't really decisive but still.

**Comment by AlphaBuffalo** [comment]
I posted my strawpoll on the thread to try and get more people

**Comment by Exxion** [comment]
Maybe a proper player poll is in order
But so far we'd exclude 4 people, assuming WINE doesn't yet support IE 9 (which I have no idea about)

**Comment by AlphaBuffalo** [comment]
I kind of cant feel bad for people who haven't upgraded from XP unless they're that poor.

**Comment by Exxion** [comment]
~~Seems like that would make one feel _more_ bad for them~~

Oh wait I can't read never mind

**Comment by AlphaBuffalo** [comment]
I think we can get away with removing support for XP and vista and go straight to 7

**Comment by PJB3005** [comment]
Yeah I'd love to drop Windows XP and Vista instantly, but that'd be a guaranteed dropping of Linux too.

Goddamnit I wish we had CEF already.

**Comment by AlphaBuffalo** [comment]
How do you guys play games on Linux? I know a lot of games don't support it so unless you guys only play 4 games max idk how you do it

Not trying to meme I'm genuinely curious

**Comment by Exxion** [comment]
WINE

**Comment by AlphaBuffalo** [comment]
Is WINE that robust?

**Comment by PJB3005** [comment]
Yes.

**Comment by AlphaBuffalo** [comment]
Is it worth me switching?

**Comment by Exxion** [comment]
Switching from what?

**Comment by AlphaBuffalo** [comment]
w10

**Comment by Exxion** [comment]
No

**Comment by Iamgoofball** [comment]
no, stay on 10

**Comment by Iamgoofball** [comment]
quite a lot

probably because it's easy to set up a VM for it and evade bans with

muh privacy dipshits also like it too for some reason

**Comment by clusterfack** [comment]
If you're using XP for privacy you'd be a dense cunt because there are so many unpatched exploits found in it by now every hacker has your information.

**Comment by Exxion** [comment]
Privacy means big companies can't get your info
Security means only big companies can get your info
Generally you get to choose one or the other

**Comment by ririchiyo** [comment]
You should keep support of WinXP at least up until BYOND itself no longer supports it because a lot of people will still be using it or using systems that haven't been moved from XP to other things yet. In regards to supporting it we should continue to support Vista/7 at the minimum still due to retarded design choices that Microsoft decided to make in Win 8/8.1/10 with the retarded push for WinRT.

@AlphaBuffalo You can pretty easily play games on Linux with WINE or through a VM because you can just let the VM have full access to your graphics card. If you're going this route I'd recommend a slimmed down version of Windows 7 or 8 because they performed the best in a VM when I did test them for some other games that required some HW Accel things. I'd also recommend using VMWare specifically for that because of the slow development of VirtualBox and others but you could probably use QEMU+KVM but I can't say I know how performance will fare.

In regards to swapping from Win10 to Linux it's up to what you need more you'll probably run into problems with audio/graphics drivers. But mostly any game on Linux will probably perform as well as if not better than on Windows if there's a native version for it. Hopefully with Vulkan as well it'll make DX12 less desirable for people to want to use because it's a Win10 exclusive thing at this point.

**Comment by clusterfack** [comment]
>You should keep support of WinXP at least up until BYOND itself no longer supports it

Byond will ALWAYS support it. We cant take cues from Byond.

**Comment by FudgePucker** [comment]
Why don't they just use an open source browser instead of ie?

**Comment by PJB3005** [comment]
because it would take effort to implement.

**Comment by FudgePucker** [comment]
And having multiplatform support to increase player base (and donation base) isn't worth it? Also they would be able to have more control and do more with their own edited version of an open source browser. (I guess licensing disputes due to byond being closed source could arise.)

**Comment by PJB3005** [comment]
@FudgePucker if you want to argue the thread to move to CEF is on the BYOND forums: http://www.byond.com/forum/?post=1877855

Although the cross platform thing is not just the embedded thing, they'd have to move a lot of Windows specific code from DS to be multiplatform which IS hard.

**Comment by Shadowmech88** [comment]
What kinds of benefits would players see from our ability to use a higher IE version?

**Comment by PJB3005** [comment]
Cooler HTML interfaces.

**Comment by gbasood** [comment]
Also less potential for security exploits on the user's end.
If someone managed to write a book with some hacky shit that exploits old IE things to install a malign activex control or something, for instance, because older IE versions don't have a fix for it but new IE does

This is legitimately something that has happened before, but not specific to BYOND

But yeah mostly cooler HTML things

**Comment by AlphaBuffalo** [comment]
IE is the least secure browser. If only we could just you know. NOT use IE for anything
