### ISSUE TITLE
Pneumatic Cannon is pretty overpowered

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#11621]
Seeing it one shot ANY and EVERYONE is pretty crazy, especially for Wizards/Lings/Vamps.

It doesn't seem to be hard to set up too.

**Comment by ghost** [comment]
This has been known forever and ever. It's just because ARs were so effortless to print they were rarely used. Now no one can use ARs, gotta find another thing to shit on!

**Comment by TheFriggenSawbones** [comment]
ya i've known it since RANDO NAMOYE blew me the fuck up as a full power vamp

**Comment by ghost** [comment]
Pneumatic cannon is weird. I did some testing. A regular, small oxygen tank everyone spawns with, at 1013 pressure, can't hit someone for more than 5 brute. This is firing a sheet of plasteel at someone, which has does about 9 damage when thrown on it's own.
But, put a big blue tank in, it's another story. That sheet of plasteel will now do 40 brute, leave you bleeding so bad you'll bleed out in about a minute. 
Now, put an antimatter containment jar in it. that's 60-80 brute, whatever just got his is completely shattered, you're bleeding so bad you're dead in 20 seconds. 
Really not sure what causes things to do more damage, because throwing an antimatter jar at someone regularly does 2 brute. 
Now, I tested this with a security hardsuit on my subjects. Due to the way armor works, you CANNOT be certain you'll even hurt them. A few of my shots did nothing, the next would shatter them completely and kill them.

This thing IS strong, but it requires refreshing every time you fire it, so unless you want to carry 4 large oxygen tanks around with you incase of misses, it's a glass cannon sort of thing.  It's a weird item, I'm not sure if it even requires balancing because it has a lot of downsides.

EDIT
WHAT THE HELL
Glass shards in this thing are OP.
Just the regular ones. Point blank, shot someone and it did 260 brute across multiple areas. What makes this 300% stronger than anything else?
I changed my mind, nerf this. 
http://i.imgur.com/8Hr4nR3.png

**Comment by AutismSpider** [comment]
What makes this better you can force feed people food with this to aim at the lips.

so you can load it up with ever toxin crap you want thats a food.

**Comment by ScrambledSteak** [comment]
> run around launching mommi spaghetti into everybody's mouths
> entire station is autism

**Comment by Exxion** [comment]
269.9 damage? Wow, you broke my record. How'd you do that?

**Comment by ghost** [comment]
Big blue oxy-tank from Atmospherics dispenser thingy, filled to 1013kpa at a large oxygen canister, glass shard loaded and output set to 50%. I haven't tested over-pressurizing yet and doing that, but I got sawbones to do some var-editing and got him to fire an energy axe from it in the same conditions, did 320 brute IIRC.

**Comment by Exxion** [comment]
What
But that's exactly what I did
How did you get 14.7 more damage?

**Comment by Gringonius** [comment]
> ya i've known it since RANDO NAMOYE blew me the fuck up as a full power vamp 

Considering how vampires were it was fighting broken with broken.

**Comment by kol1th** [comment]
#7046

**Comment by TheFriggenSawbones** [comment]
you'll be remembered as a legend Gringonius

**Comment by TheFriggenSawbones** [comment]
@Exxion high force low speed = high dam

**Comment by SonixApache** [comment]
load monkey cubes and aim for the mouth for maximum fun

**Comment by PJB3005** [comment]
@SonixApache whoa there satan.

**Comment by SonixApache** [comment]
@PJB3005 Make sure you fire twice, as the first monkey won't necessarily kill them -- especially if they have quick access to surgery.

**Comment by Shadowmech88** [comment]
It's not necessarily the pneumatic cannon itself.

The reason that glass shards do so much damage when fired out of a pneumatic tank, is that the pneumatic tank's damage is calculated based on the projectile's throwforce _and_ it's w_class. Glass shards have 15 throwforce, which is among the highest of all items. However, they _also_ have a w_class of 1, whereas everything else with 15 throwforce has a w_class of 3. I mentioned this in #7718.

This combination of a very high throwforce and a very low w_class means that it deals insane damage when fired out of a pneumatic cannon. It's one of the reasons that I prevented glass shards from being inserted into the blunderbuss, which uses the same kind of damage calculation.

A better solution than nerfing the pneumatic cannon as a whole, I think, would be to nerf the throwforce of glass shards.

**Comment by Exxion** [comment]
Hatchets also have the same `throwforce`/`w_class` as glass shards

**Comment by Shadowmech88** [comment]
True, but at least they take some effort to acquire instead of the station being littered with them.

**Comment by ghost** [comment]
Shadow you're confusing w_class with throw_speed. throw_speed is the variable the pneumatic cannon uses, w_class is used in what can and can't be put in the cannon itself. The shard has a throw_speed of 1, which is the same as toolboxes; energy axes and swords; antimatter containment jars as well as paper. However only the antimatter containment jars out of there can be put in the cannon to do any damage and don't do anything CLOSE to the same. The hatchet has a throw_speed of 4, meaning it won't do as much damage as the shard.

**Comment by Exxion** [comment]
Nope
Pneumatic cannon uses w_class for the speed
Read the code

**Comment by ghost** [comment]
Ah, sorry I guess, I can't understand any of it so I just went off the tests I did. Seemed like throw_speed was the thing causing the damage changes.

Decided to jump and do a bit more testing and yeah you're right. All the tiny items with even a fraction of throwforce have their damage amplified by a multiple of 20. Bike horns doing 60 brute and making you bleed out in 30 seconds is not good. Screwdrivers, skulls, null rods completely destroying people is not good either.
Maybe it just needs some sort of limiter stacked on it, ramping some items damages up so much is just ridiculous.

**Comment by ghost** [comment]
I have an idea for a fix. The blunderbuss works the same as the pneumatic cannon if i'm reading everything right and has a banned items list coded in. Couldn't we add something similar for the cannon? If anything, restrict w_class_tiny from being put in the cannon, saying something like, 'the ____ falls out of the barrel!' whenever you try and load it. There are still a tonne of w_class_small items which will fit in the cannon and do damage, but none of them will be stupid-tier damage wise.

**Comment by Exxion** [comment]
Or just lower the max speed cap from the current ridiculous 80
