### ISSUE TITLE
service borg beaker

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11789]
(WEB REPORT BY: tornader REMOTE: 172.93.109.202:7777)

> Revision 
> db680ede40c7a8fe642eb556a969f13be6240561 
> 
> General description of the issue
> I used the service borg beaker on the pill maker thing and it got stuck inside it, couldn't take it out anymore and my inventory got bugged
> 
> What you expected to happen
> work just fine
> 
> What actually happened
> didn't work
> 
> Steps to reproduce if possible
> be service borg with module upgrade, use the beaker on the pill thing in chemistry, enjoy no longer having a beaker

**Comment by Exxion** [comment]
#11701

**Comment by Shadowmech88** [comment]
@Exxion 
These two may not be related, code-wise. Service borgs have shakers by default, but they can acquire beakers with an upgrade, for use with stuff like food grinders.
This bug seems to be solely related to their beaker, not whatever code added the ability to put their shakers into dispensers.

**Comment by Exxion** [comment]
It's the same code
All they did was change the `istype()`

**Comment by ComicIronic** [comment]
It could be an issue with how the beaker is loaded into the module. Has this been tested with a beaker on the chem dispenser and the shaker on the machine?
