### ISSUE TITLE
mobility module

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11790]
(WEB REPORT BY: tornader REMOTE: 172.93.109.202:7777)

> Revision db680ede40c7a8fe642eb556a969f13be6240561
> 
> General description of the issue
> combat borg mobility module doesn't actually increase mobility

like get a combat borg and try it out it doesn't work

**Comment by Shadowmech88** [comment]
Side effect of something that happened a long time ago which essentially removed all "speed-ups" from the game, restricting everything to a maximum speed. It's the same reason the VTEC stopped working.

Can be fixed by making the mobility module modify the borg's movement_speed_modifier variable, which _can_ bring things above what is normally their maximum speed.

**Comment by clusterfack** [comment]
Are we sure @DrCelt's ugprade refactor didn't have something to do with it

**Comment by SkowronX** [comment]
also related, #11138. probably has to do with the use of the var "speed"

**Comment by Shadowmech88** [comment]
Tested, no longer exists.
