### ISSUE TITLE
The change to ling succ rules can be abused to deny a ling their succ

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#12045]
If a ling kills you (or starts to kill you), you can log out (I think), or immediately ghost and hop into a diona, borer, posibrain, derelict MoMMI, or whatever to just completely deny them their succ because of the way that it works now, since you can't succ bodies that don't have a ckey assigned to them.

This also means that beheaded corpses (such as those you behead with the changeling arm blade) cannot be given the succ, nor can most of the bodies in the morgue, even if they're player corpses, because they no longer have a ckey assigned to them once the head is removed or the body is cloned.

It was my understanding that this change was to specifically target lings giving the succ to humanized monkeys. So what the fuck?

My suggestion is that you make monkey-humans a separate race (as in, ckey-less monkeys that are humanized), and simply prevent lings from giving the succ to those.

**Comment by TheFriggenSawbones** [comment]
I'd assume this is also applicable to vampires.

**Comment by clusterfack** [comment]
Are you -sure-

**Comment by icantthinkofanameritenow** [comment]
I'm pretty sure it works as long as they had a ckey assigned to them at one point. It not working on headless corpses is because the ckey is "stored" in the head- no head means no ckey.

 Fixing that is possible in theory, but it would mean completely changing how ckeys are associated with players, and it could easily break more than it could fix.

**Comment by Shadowmech88** [comment]
Just make a var on the mob itself that gets set to 1 if it has a ckey at any point, then check the var instead of checking whether they currently have a ckey.

**Comment by icantthinkofanameritenow** [comment]
@Shadowmech88
Don't we already have that?

**Comment by Shadowmech88** [comment]
If we did, wouldn't you be able to succ a body even without its head? The "mob" is the torso, so all mob-level vars would be held there.

**Comment by icantthinkofanameritenow** [comment]
@Shadowmech88 
I don't know, I just know that for whatever reason it's the head which contains the ckey, probably because otherwise brain and head transplants wouldn't transfer ckeys correctly. If those were in the torso, those transplants would become impossible. 

Incidentally, that also enables the flip side of the exploit, where transplanting a husk's brain into a monkeyman and reviving will let you suck the monkeyman off despite it being the same ckey.

**Comment by clusterfack** [comment]
I'm fairly sure this already checks the mind datum instead of the ckey, and the mind is already irrelevant to whether someone ghosts out of the body or not. That's why I said, did you actually test this?

**Comment by gbasood** [comment]
@clusterfack 

``` dm
    if(!T.mind)
        to_chat(src, "<span class='warning'>This creature's DNA is useless to us!</span>")
        return
```

you's right
