### ISSUE TITLE
Hairdye

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#12074]
So nerds can change their hair color in round without admin intervention and without genetics

**Comment by ghost** [comment]
Hair needs a rework in general.

Hair dyes for changing colour, including mixing to get the perfect shade of iridescent pink.

A hair 'scale' where you can only get hair types that are shorter than your current, otherwise you'd have to use hairgro to go back up the scale, or have a virus that makes you into cousin it

And remove the magic haircutting mirrors

**Comment by gbasood** [comment]
> remove magic haircutting mirrors

I think there's been stations with barber jobs before
they're awful

But we could add an autobarber that you could emag to cut someone's throat :+1:

**Comment by SonixApache** [comment]
Vocal cords organ when?
