### ISSUE TITLE
idea that makes too much sense to not be in the game

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#12078]
alert levels = more sec access
green - normal sec access
blue - sec basic access to all departments
red - sec all access to all non-command departments
delta - sec all access to all departments

**Comment by Wizbing** [comment]
I agree, also unban me from the fourms.

It was a picture in celts thread.

We're one step away from the holocaust

**Comment by icantthinkofanameritenow** [comment]
Why isn't this already in?

**Comment by ghost** [comment]
@icantthinkofanameritenow it popped into my head and I thought the exact same thing

**Comment by Kurfursten** [comment]
Sec all access during delta seems almost too strong against antags on one hand

However it is well documented that I hate silicons and that would only affect malf so I approve

**Comment by charmstruck** [comment]
I agree, though there should be a short time after the alert level is lowered that access remains as it was so that officers don't get locked into a department (similar to maint radiation access)

**Comment by icantthinkofanameritenow** [comment]
That implies anyone ever lowers the alert level. I saw that happen exactly once in all the time I've played.

**Comment by Exxion** [comment]
I think it happens a bit more often than that
But only a bit

**Comment by Kurfursten** [comment]
Actually, one of the things I like about the PR is that it gives a reason to lower alert level. As a head of staff, I basically don't care if we're forever at code blue because it doesn't affect me. But if the threat is passed and sec keeps patrolling through the engine room I'd be a lot more likely to call for code green.

**Comment by rweeblington** [comment]
I agree with Kurfursten.
It would encourage people to say, "Hey, didn't security catch that guy? Can they please leave my department?" and then command would respond.
Possibly AI being able to lower alert levels without having to wait for someone to leave a logged in communications console unattended so that someone can say, "AI I don't like these secshits here, lower the alert level."

**Comment by SonixApache** [comment]
Make red alert lower everyone else's access levels to 0 as well (if there's more than 2 security officers). Might help keep them in their own department so you don't accidentally shoot 5 greyshirts and a scientist when you're trying to shoot a wizman / nuke op.

**Comment by Kurfursten** [comment]
> Red alert locks everyone in their room

That sounds like a good way to make red alert useless in blob and also result in every door on the station being hacked open

**Comment by DeityLink** [comment]
Yeah nah
