### ISSUE TITLE
How Should We Utilize Autistic Amounts of Power

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#12087]
Currently there isn't hardly anything that can make USE of all the power Engineering is capable of churning out. I believe the only things currently are electrified machinery, the engie tator lightning gloves, and the railgun.

What are some items/machines/features that could be added that'd require so much power they'd become something to strive for, rather than a given?

**Comment by sonime** [comment]
Engineers should be able to get dosh with excess power and they should be able to buy things with it. Things they can use like plasteel and more cells or something.

**Comment by AlphaBuffalo** [comment]
A bluespace power transmitter?

**Comment by CptWad** [comment]
theres been ideas over the years
portable SMES that can be sold (based on how much power stored)
there EXISTS the railgun that can create rods at superb powerlevels
we can also make it so that higher level parts increase power usage  of the machines
maybe improved shit so that engineers can power huge sheilds around the station to protect it from meteors and shit

**Comment by Shadowmech88** [comment]
> there EXISTS the railgun that can create rods at superb powerlevels

Yeah, but I don't think anyone's ever used it to great effect, mostly because it requires _such_ high levels of power. You'd probably have to have at least two engines running in tandem at great efficiency to pull a gigawatt.

I'm looking more for stuff that, for example, couldn't be powered by a standard singularity setup, but _could_ be powered by even a halfway-decent supermatter setup.

**Comment by AutismSpider** [comment]
better parts in mechines = bigger power drain.Using all this power to make stuff some how

**Comment by SonixApache** [comment]
A SHIELD GENERATOR IN THE CENTER OF THE MAP TO PROTECT THE STATION FROM MEATY WHORES AND/OR BLEBS

**Comment by ghost** [comment]
Matter synthesizer, converts power into matter cartridges.

Before you go saying 'but you'd need 1.81 Terawatts for a grain of sand', engiborgs can already convert very minor power amounts to diamonds straight from a sub-KW cell. Just say it's ran over a bluespace crystal catalyst and in fact teleports the matter from elsewhere.

**Comment by PJB3005** [comment]
> but you'd need 1.81 Terawatts for a grain of sand

Unless you mean 1 grain per second, you fucked up your unit conversions.

<sup>/s</sup>

**Comment by ghost** [comment]
I meant for a grain of sand, as in that's the amount of power to make one.

And I was being very, very rough with my estimation, but it's somewhere around that level of crazy-numbers

**Comment by Blithering** [comment]
I'd agree with the idea of chargeable batteries that can be sent on the cargo shuttle in exchange for goodies. Alternatively give touching a live wire with over a gigawatt of power in it 1/100 chance of granting max level lightning bolt spell instead of ashing. 
Having higher tier parts in a machine require more power would be a bad idea in my opinion, as it would discourage upgrading machines, rather than encouraging power hoarding.

**Comment by BobdaBiscuit** [comment]
D20 had a material synthesizer which was quite good to play about with in autism rounds.
It shat out heat which had to be cooled and you could produce whatever material you wanted with enough power, which gave us shit to sell to centcomm.

Just gives an extra autism option.

**Comment by Iamgoofball** [comment]
Bitcoin

**Comment by Exxion** [comment]
@Skullyton PJB's point was  that that's the wrong unit
Watt is a unit of power, which is energy per unit time. You need an amount of energy to make a grain of sand, not an  amount of power.
But there's no distinction in-game because someone fucked up.

**Comment by sonime** [comment]
I don't think it should go through cargo, because then getting what you need becomes as unreliable as asking miners for plasteel. Engineering should have its own shuttle if you want them to reliably buy anything.

**Comment by gbasood** [comment]
Giving engineering a matter synth or letting them make money over transmitted power is cool, but it doesn't benefit the rest of the station.
Ideally instead of converting power straight into diamonds or something, we should give players the ability to make/upgrade departmental machines, like I've already said in several places.
This means power has a more direct impact on other departments.

The only upside I can see for engineering making money off transmitted power is we might be able to move the massive fucktons of money that cargo makes off mining, literally out of thin air by the way, to engineering instead

**Comment by sonime** [comment]
What I wanna see in terms of the economy is each department being able to make money by doing their job: miners make money by mining, engineering makes money by producing power, so on.

**Comment by Blithering** [comment]
For something that benefits people aside from engineering, would it be possible to have the gateway align itself if power is maintained at a certain level for a set period?

**Comment by Exxion** [comment]
The gateway being a use for absurd amounts of power is a neat idea, but it currently requires admin intervention to activate, and doing so probably (???) hangs the server for a few seconds

**Comment by FudgePucker** [comment]
@Skullyton 
I had a similar idea as that as well, but more unique.
Pretty much a new engine/machine that uses crystallized energy to create a beam, that can be used to shoot into an SME or into a photo collector.
The engine is a three/two part machine that has to be pushed together.
It has three modes, generating, burning, and both.
When generating it creates a crystal of energy, the quality of the crystal is based on the amount of power in the loop.
Burning turns the crystal into a laser that shoots out.
And both does both at the same time, pretty much making it into a SUPER EMITTER.
This by itself is nice because it makes setting up autistic SMEs easier, because instead of having to order more emitters and dealing with aligning them, and then having to get prisms and mirrors (this is a special kind of hell.), you can set up just one of these machines and set up how strong you want the amount of power emitted to be. Pretty much letting you turn a clusterfuck filled room with emitters and prisms everywhere into one nice small machine.

Also the crystals could have other uses. Modifying a RCD/RSD/Mat synth to take crystals, letting you have super powered RCDs that you don't have to recharge every two uses if you have an super autism engine. Selling them for fat stacks of cash. Being able to buy crystals and using them with a photocollector for a temporary engine alternative to the AME or pacmans (also adds a reason to have photocollectors available.), making bombs out of them or some shit I don't know, it is a just a science fiction energy crystal.

**Comment by AlphaBuffalo** [comment]
I like it

**Comment by Hoshi-chan** [comment]
Make it so that excess power in the grid is redirected into increasing the efficiency and speed of machines onboard the station.

So lathes and fabricators would build items more quickly, chem, booze, and coffee dispensers would refill faster, and borg, cell, and weapon chargers would reach full charge in a shorter amount of time.

**Comment by Blithering** [comment]
@Hoshi-chan Faster cell charging would be awesome, but I think some of that is already tied into part tiers, so that would require a rework too.

**Comment by Hoshi-chan** [comment]
@Blithering Parts are already underwhelming considering the work required to install them. They need an overhaul.

**Comment by uazuaz** [comment]
like AutismSpider said before, better parts in machines should have bigger power drain, but only if there is enough power in the grid; this means that if a machine have tier 3 parts and there is enough power in the grid it will have tier 3 performance and tier 3 drain, but if there is not enough power in the grid it will have tier 1 or 2 performance and drain even with tier 3 parts.
this way there will be no downsides on putting high tier parts in machines, but they'll have a bonus when there is enough power.

i also like the idea of selling surplus energy to centcomm for money, so engineers could have a money source doing their job like miners do; for example, a machine attached to the grid that teleports energy directly to centcomm, you could set it to choose the amount of energy absorbed and sent, then engineer department members will receive a money bonus on each payroll based on the amount of power sent.

**Comment by ghost** [comment]
Let's look at it on a per-department basis:

Engineers could apply the extra power into making even more power, which defeats the point.

Sec might be interested in protecting the station, show would a battery of anti-meteor laser turrets sound like? I'm sure engineers would love that too.
Hell, make it so they need a central computer that requires energy too, and if that computer goes boom, you'd have to assume direct control and shoot em up yourself; could be great for meteor rounds.

Medbay won't need any of this extra power, neither do civilian jobs.

Science uses top few machines right now and should turn into a sprawling autismus lab full of power consuming machines. And let them have some mega projects too, think stuff like R-UST.
And xenoarch could get massive artifacts; one per round, easy to find and excavate, but hard to use because you'll need to collaborate with engies to power that up.

Cargo is all about buying and selling, there should definitely be a way to transmit high amounts of power around. I'm not just talking selling the power to NT, which already pretty neat, but also send that power to the asteroid so xenoarch can power that thinamajyk of theirs. Just think, a huge ass laser on station sending a powerful as fuck beam across space to a huge ass receiving pad.

Cargo is also about mining, and with mining comes industry. Wasn't plasma supposed to be the new oil? Then how comes we can mine so much solid plasma yet only use it for a few specific things?
Let's make machines that use power to refine solid plasma into solid plasma crystals or something, and use those plasma crystals at that receiving pad to capture that energy beam; hell, make it so centcomm requires cargo sending those crystals before engineering can sell power.
We could also use all that power to refine plasteel, metal and uranium into more valuable materials or something. Hell, we could even tie it up to oil refineries and get an actual source of plastic and welder fuel, getting plastic out of mushrooms shouldn't have ever been a thing.

And now that we have a network of power drains to choose from, an High Power Network System with switches and converters and accumulators could be done, so engineers have to manage how much power goes where and actually get to do something once the local autist has finished their masterwork

**Comment by gbasood** [comment]
@JellyVeggie Medbay doesn't need extra power _until someone adds machines that use extra power to do cool things_

**Comment by Exxion** [comment]
We should do that thing someone suggested where there are two separate powergrids, with one at low power for APCs and one at high power for machines that require direct connections, and make more machines require direct connections, and make them work better the more power they have
For example, chem dispensers could be made to charge more quickly with more available power, etc.

**Comment by Shadowmech88** [comment]
Two powernets would be a nightmare, so what if the whole grid runs at high power, but APCs act like step-down transformers?

**Comment by FudgePucker** [comment]
I agree with Shadowmech88 here, the power grid already is a bunch of spaghetti that is a pain in the ass to fix, imagine the hell it would be with two different grids.

**Comment by clusterfack** [comment]
We need a machine that can detect and display all the lines in a powernet

**Comment by Intigracy** [comment]
Sorta like a holomap?

**Comment by FudgePucker** [comment]
I mean, anything that makes the station harder to repair in the case of damage is a very bad thing, not because muh casuls, but because if its not fixed in five minuets the shuttle is called. If you have to fix two different power grids after a bomb goes off, the shuttle is now more likely to be called than if you had to only fix one power grid.

This is the engineering paradox. Shuttle gets called if you don't fix it, but the shuttle will be called if you can't fix it within a time frame, you do not know this time frame, do you even bother trying to fix it? Please note that you get absolutely nothing from fixing it because you have the most thankless job on the station. Oh boy I can't wait to also have to spend twice the amount of time to fix the wire grid, just for the shuttle to be called before then!

**Comment by sonime** [comment]
Too bad the collabs in general don't see it that way. In their eyes, every player is a top notch ultra-competent player who can fix a bombcap hole to like new in five minutes, hence why they see the need to make more busywork instead of letting players engage in optional autism.

**Comment by ghost** [comment]
An high power grid would be manageable as long as we keep the number of machines that need it somewhat low, no need for the HPG to reach every room in the station.

It would also only ever see any use engineering bothers generating the extra power; so by that same reasoning machines depending on it should not be critical to the round and liable to provoke a shuttle call. The number and complexity of systems to be mantained should only ever increase if players choose to put effort into them.

@gbasood I'm having a hard time figuring out a non-critical machine that'd help out in medbay, honestly.

**Comment by AlphaBuffalo** [comment]
There is another wire type I found in the code if it hasn't been removed yet, it's basically a thicker power cable that can't be removed (we would have to fix that) but if we make the width a little bigger and put it below the pipe layer it wouldn't be too hard to click it, and we can make it so when the low power grid (lpg for short) has above 2MW wires start to catch fire, and the high power grid (hpg) can only transmit power above 1MW. we should also make APC unable to interface to it because of improper connections

**Comment by AlphaBuffalo** [comment]
And we should have a hpg connection to each department that is just open so if anyone add a machine that needs they won't have to lay a bunch of wires. I also think there should be some important machines connected to the hpg just so engineering has incentive to repair it and expand on it.

Stuff that would require HPG connections would be like the teleporter in science, the SMES in tcomms and AI chamber, chem machines (but add more power storage), (maybe) cloning, (maybe) the protolathe, and anything else that can be loss mid round that won't invoke a shuttle call

**Comment by FudgePucker** [comment]
OH BOY TWO POWER GRIDS TO FIX. WHAT FUN.

**Comment by AlphaBuffalo** [comment]
Better than, SINGULO IS RUNNING TIME TO JACK OFF TILL SOMEONE BLOWS UP A FUEL TANK

**Comment by Blithering** [comment]
I'm not a fan of the HPG idea, particularly if pre-existing machines are changed to be dependant on it. Having to wait for engineering to get their megawatts up and running before cloning and research can be done doesn't improve matters, and the overload idea would mean the whole grid is one weldertank away from disaster. 
I would really prefer new machines and mechanics that make use of the possibility of huge power rather than demanding it every round for what previously ran fine.

**Comment by AlphaBuffalo** [comment]
Actually one consequence of that set up is the singularity makes like 1 MW with room temp plasma, it could work better if we make the singularity make more power and so on

**Comment by gbasood** [comment]
Why? The singulo could be more than good enough to power station without much fuss, and then engineering could tweak it or use thermo or SME to generate high power, like engineering already does practically every round anyway.

**Comment by AlphaBuffalo** [comment]
Because with my idea of 2 grids that support two different power supplies, the HPG being 2MW up, important machines wouldnt be operational unless you set up 2 or 3 engines, to reach around 3MW. The only engines able to produce 3MW easily and reliably is the SMR and Rust. I guess if we do decide on 2 grids it should be used by machines that if unpowered wont invoke a shuttle call

**Comment by Shadowmech88** [comment]
> 2 or 3 engines to reach 3MW

Doesn't even the singulo get to a couple megawatts if you put cooled plasma in the rad collectors?

**Comment by AlphaBuffalo** [comment]
It does, but I always account for people to do the least work possible in enigneering, and well, just filling the tanks with plasma gets about 1MW

**Comment by Shadowmech88** [comment]
> I always account for people to do the least work possible in enigneering

I'm pretty sure cooling plasma is less work than running two or three engines at once.

**Comment by AlphaBuffalo** [comment]
It is, but most new engineers who only know how to set up the singularity think that cooling plasma will require 120 thermal pipes running all round the station in order to achieve optimal pressure and temperature, and thats only for the people with half a brain that arent scared of atmos in the first place. 

For the new engineer, the singularity will have room temp plasma, the AME will be at 2 cores, and the SMR and TEG will be left unused because they think atmos is some next level shit

**Comment by gbasood** [comment]
Maybe if anyone put shit on the wiki

**Comment by Zth--** [comment]
Well I have a simple idea. Maybe It's been mentioned before (tl;dr). A machine that converts energy into matter. Some kind of big fucking oven that consumes a fuck ton of energy and you can create artificial diamonds or even phazon

**Comment by Shadowmech88** [comment]
I realize that we don't have to go the realism route, but if we *did*, creating a single compressed matter cartridge would consume unheard-of amounts of power.

**Comment by FudgePucker** [comment]
@AlphaBuffalo
So engineers have to have a super difficult job that allows no free time?
So what engineers can do other projects after setting up an engine. At least its better than making a clusterfuck spaghetti nightmare out of the powergrid.

Also I really think my engine idea would work well. It would give engineering a feature dump, instead of cargo and science hogging all the new fancy additions to code.

**Comment by SonixApache** [comment]
did i mention shield generators

**Comment by PJB3005** [comment]
WE'RE GONNA BUILD A SHIELD AND MAKE THE MOMMIS PAY FOR IT!
