### ISSUE TITLE
Special roles preferences won't save

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12127]
(WEB REPORT BY: rfultra REMOTE: 172.93.109.202:7777)

> 6cc88f327d8296b8c80ca3539b1a654c8106eda5
> 
> Special roles wont save at all  no matter what I do
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Kammerjunk** [comment]
Hearing the same issue from other people. I'll ask them to share.

**Comment by clusterfack** [comment]
We need to nail down under what circumstances it may or may not occur. That's the most important part of this issue

**Comment by j-mie** [comment]
So I've been looking into this: I suspect the issue is here: https://github.com/d3athrow/vgstation13/blob/82403c717536aea5fecb9341bba9cef9d8948704/code/modules/client/preferences_savefile.dm#L789-L790

I've noticed that if I set the my preference to Always then it will save, but yes will not. I suspect this is due to this: https://github.com/d3athrow/vgstation13/blob/4505af93746c5166654a46a04c6bbd68476c7b15/code/setup.dm#L841-L849

I've always dumped the hrefs when you set it to yes, and then always.

yes:

``````
preference=set_roles&alien=1&blob=1&changeling=0&cultist=1&malf+AI=1&operative=0&revolutionary=0&traitor=1&vampire=0&vox+raider=0&wizard=0&borer=0&Dionaea=0&pAI=0&posibrain=0```
``````

always:

``````
preference=set_roles&alien=0&blob=3&changeling=3&cultist=3&malf+AI=3&operative=3&revolutionary=3&traitor=3&vampire=3&vox+raider=3&wizard=3&borer=3&Dionaea=3&pAI=3&posibrain=3```
``````

**Comment by BarneyGumball** [comment]
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/client/preferences.dm#L1763

Yes and No options don't get flagged to be saved.  Mid round recruitment for everything except borer seems to be done via modifying prefs.  `datum/recruiter` should be used for mid round recruitment to avoid modifying prefs mid round.

**Comment by Kammerjunk** [comment]
Quote from upset man without valids:
"i open it, select changes, save, close, open it again and its the same thing it was before"
"it shows up that it updated, i click submit"

**Comment by clusterfack** [comment]
Yeah it seems to come from nexis mixing up rolepref persist between two different ideas.

**Comment by j-mie** [comment]
The easy fix would be to remove the "Do you want to be this role" feature and then just have a No and Yes option. The correct fix would be to fix it properly 😄. So the way I see it this is what "roles 2.0" is expecting:

Never: 2
No: 0
Yes: 1
Always: 3

No and Yes will never save because of the check. The check could just be removed, as you have to actually click save for it to be saved AFAIK. https://github.com/d3athrow/vgstation13/blob/82403c717536aea5fecb9341bba9cef9d8948704/code/modules/client/preferences_savefile.dm#L789-L790

**Comment by gbasood** [comment]
@clusterfack you changed the prefs UI so you have placed this burden upon yourself

**Comment by clusterfack** [comment]
Nothing I did changed this system, I merely moved it into another window
