### ISSUE TITLE
Buff Makeshift Weapons

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#12164]
In the midst of the recent lockbox debacle, some have said that the makeshift weapons need a buff in order to be viable.
But weapon balance is a tricky thing and I'd rather not personally make any decisions regarding it, considering quite a lot of them are my weapons.

So I'd like to hear the thoughts of others on what makeshift weapons need buffed, and in what way?

**Comment by icantthinkofanameritenow** [comment]
In most cases, it's about making them practical and a genuinely viable alternative to the regular lockbox weapons; if my own PR doesn't get merged, there needs to be a viable alternative to things like lasers and stun revolvers. I'll list out my feelings on the current makeshift weapons you added in your PR, the other ones haven't changed since then to be worth talking about. 

Swords are fine, but tomahawks are redundant since swords do everything they can do better. Venom sword is an exception, it shouldn't require the hypospray to make since the hypospray already does what the venom sword can do better. 

The railgun can be the strongest weapon of all, but only if the engineers are doing totally amazing; even then, most people don't get to make capacitors so they can never use them. 

The hivehand does far too little damage to justify using it, even given it's self-charging ability; it certainly doesn't justify losing a hand for it. 

The revialver is just plain worse than the syringe gun in every way, which is worsened by the fact that medbay (which alone has all the stuff needed to make it immediately) already starts with a syringe gun.  

The blast cannon by definition uses up valuable TTVs, which few scientists would willingly give up. 

The blunderbuss is decent but unreliable; its main issue as far as i can tell is its bad range and accuracy. Fixing that would make it a much better weapon. I've never seen anyone use the cannon, so no comments there. 

I can't say anything about the blinder, inasmuch as I have never seen anyone actually use it either. 

The subspace tunneller...barely counts as a weapon, really. It's more of a gimmick item. A fun gimmick to be sure, but too expensive to get much use out of due to the bluespace crystal requirement.

IMO, there needs to be a "ghetto taser" of a sorts. I'm picturing a two-shot taser whose bolt moves at half the speed of the normal one, to be used as an emergency ranged stun. A ranged weapon which does fixed damage instead of having its effectiveness being based on a gimmick would be good too, you don't see other guns changing their damage based on how much they're loaded or whatever.

**Comment by Shadowmech88** [comment]
The single advantage of tomahawks compared to swords is that they are pocket-sized, and the pipe tomahawk is, to my knowledge, the only damage-dealing item that can fit in the mask slot.

The venom sword _does_ have an advantage over the hypospray in that it lets you autoinject chems straight out of a stasis beaker.
Also if it was buildable with autoinjectors, wouldn't that just be giving anyone who can find a medical kit access to what is essentially a big hypospray?

> The blunderbuss is decent but unreliable; its main issue as far as i can tell is its bad range and accuracy

The range can be tweaked, but what do you mean by bad accuracy? Does the item not land on the tile you click on? Its code is the same as the pneumatic cannon's as far as launching the items.

> The revialver is just plain worse than the syringe gun in every way

The idea is that if you had any way to GET a syringe gun, you wouldn't need to make a revialver. It's supposed to serve as a plan B, not a replacement for the syringe gun.

I guess a larger question to ask in this issue is "How close should makeshift weapons get to the efficacy of proper weapons?"

**Comment by icantthinkofanameritenow** [comment]
I don't really get the deal with the stasis beakers; I've never seen them used, for the venom sword or anything else. You do have a point with the autoinjectors, but there's no reason why the only hypospray on the station should be given up dor the venom sword though- most CMOs are just going to use it to dispense chloral. 

As for the revialver, keep in mind that the only department which can reliably get all the components without theft is Cargo, which has much better options for weaponry than a ghetto syringe gun. (On that note, I'd like to point out the rapid syringe gun has no lockbox and is easily mass produced.)

The blunderbuss just seemed somewhat inaccurate, it may have been a misjudgement from my own observations. But anyway my answer to the last question is "it depends". If my PR goes through, they should be slightly better than they are now, not quite enough to rival proper weapons but enough to make them a choice worth considering. But if not, they need to be much more on par with true weapons, to fill in the gap for things the crew can be armed with to defend themselves against things like blobs, nuke ops, and horrorform changelings.

**Comment by Shadowmech88** [comment]
I personally don't feel it's a problem that only Medbay can readily make a revialver, given that Medbay is essentially the only department with easy access to the wide variety of chemicals required to make good use of it.
Although as a general issue, I believe permeability code is still shit, which means that the revialver is shit because chem transfer via splashing is shit.

As for the venom sword, what method of construction would you suggest to make it not require a hypospray, but still be sufficiently difficult to produce?

**Comment by icantthinkofanameritenow** [comment]
I am not entirely sure myself. My first instinct is to just add another hypospray to the CMO's locker just in case he really wants to make one, but I'm not entirely sure that would be justifiable. 

Point taken for the revialver, though the fact they start with a syringe gun already does weaken the argument somewhat.

**Comment by SonixApache** [comment]
**Buffs?**
- Flamethrowers are pretty ineffective. I did some testing. A full tank gets you about 10 shots, for a total of about 40 burn damage if everything hits. That's not including damage over time, of course, but it's still pretty weak.
- Venom sword is interesting, but the hypospray limits it to the point where it's almost never seen. Syringe shotgun version that can be loaded with a few syringes that break after each hit, maybe? Could use the revialver's cylinder for it.
- Hivehand isn't worth removing a hand -- maybe allow for detachment by injecting antitox or sleeptox?

**New?**
- Ghetto lasers! Using prescription glasses, maybe?
- Bigger IEDs made outta those welding fuel cans would be good.
- Throwing knives?

**And for the rest?**
- Aren't pipe guns a thing? I saw an assistant with one a while ago, but I'm not sure what it did. Might've just been a blast cannon without the bomb on it (which makes sense, since he was in the incinerator with a bunch of bomb-making materials.) If they're not, maybe make them into ghetto syringe guns?
- if #12168 gets done and soda cans net you aluminium, ghetto flashbangs wouldn't be too hard to make. Would be even better if soda cans fit into grenade casings on their own.
- Are ranged stuns really that necessary? Can't you just use cable bolas or throw a stunprod or some other heavy item for a knockout?
-  _"There needs to be a viable alternative to things like lasers and stun revolvers."_ Actual weapons should be hard to get, why would you even bother if you can make some makeshift piece of shit that's just as viable?

**Comment by icantthinkofanameritenow** [comment]
Nobody uses the real bolas, let alone the ghetto version.

**Comment by SonixApache** [comment]
I've got bolas on me at all times as officer, usually just forget to use them.
And I've been cablebola'd by some greyshirts while transporting prisoners before. Was VERY annoying.

**Comment by icantthinkofanameritenow** [comment]
Hm, well I've never seen them used.

As for my other suggestion, I figured that if the lockbox nerf did stay, the makeshift weapons would need a smaller power gap to help compensate for all the issues I have described enough in other PRs already. Besides, there's nothing that's keeping the components of those theoretical weapons tricky to find; for the ghetto taser I was picturing a high-capacity power cell as a component, but I can't think of anything fitting for the other parts yet. I just know I want it to be objectively inferior to a true taser, but still usable as a last resort. Hence the halved projectile speed and poor capacity. 

The pipe gun you describe sounds like the blast cannon. Ghetto syringe guns would be pointless since revialvers already fill that niche. The ghetto blaster does sound like a good idea though- maybe it could use a bunch of micro-lasers and focus the beam somehow?

**Comment by FudgePucker** [comment]
Main problem I feel like with ghetto weapons is that science has the means to accuire all of them easier than other departments, even though they have access to protolathe weapons as well.
Flamethrowers give a much needed boost to engineering, they have very little means of anti personnel weapons, most of their weapons destroy the station, so the flamethrower being powerful helps them, also its hard for other departments to get one because the lack of plasma tanks... Oh fuck me science can make them, nerf them into the ground.

Reviler can take stasis beakers right? So science now has a acid smoke gun, ALONG WITH THEIR FOUR SHOT SYRINGE GUN.

Also venom sword is worthless for the most part.
What would you put into a hypospray to use it as a weapon? The instant knockout chem that only requires three button presses at the chemical despenser. What would be the best thing to put into the venom sword? The instant knockout chemical. So the venom sword is a downgrade, it has a larger in hand sprite, can't fit in your pocket, visible attack log instead of only your target getting 'you feel a tiny prick', and it can miss. Sure you can use stasis beakers, but besides water potassium most of the reactions would fuck you up as well, also they aren't the instant knockout chem.

The only weapon science can't make really is the super instagib railgun, and they can actually if the engineers set up an autism engine straight to grid.

As we all know I have the stance of 'fuck interaction'. This is a good example of this. If an engineer asks for a super capuator to make a railgun, he gets rejected, after all, science needs that RGS to print guns.
The reason science is so over powered is the fact they don't have to depend on other departments to do anything, so in this anti social simulator they are the best.
The protolathe is a feature creep device. Have something cool? Don't want it available round start? Fuck it, put it in the protolathe and give it a research level, problem solved. We tried pushing for 'interaction' so now everyone has to go science to get fun toys, the thought being that now departments will have to work together. In reality the other departments rarely get fun toys, AND SCIENCE HAS ALLLLLLLLLL THE FUN TOYS. Science can do anything they want besides engines because most of the parts come from cargo.

This hurts other departments incredibly. Half of the difficulty of setting up a R-UST is getting the stars to align. You gotta get like, five crates from cargo, and five specific boards from science. Oh and don't forget plasteel for the other parts. But fuck giving engineering anything, they should have to grovel and beg for an hour before even getting a chance to start on the hardest engine in the game that takes two hours plus to set up from scratch, oh hey the round has been going on for an hour and a half? Time to mash buttons!

Science and cargo don't have to interact at all with other departments, you can get all the slime colors, max research, mine for artifacts, do xenobio, and make bombs without ever leaving your department. Need medication? Oh you got a chemical dispenser and advance trama and burn kits. Why do people keep thinking that it is a good idea to force departments to interact with departments that don't ever need to interact?

Wait what was the topic again I forgot

**Comment by Shadowmech88** [comment]
@SonixApache 

> Flamethrowers are pretty ineffective. I did some testing. A full tank gets you about 10 shots, for a total of about 40 burn damage if everything hits

Were you using pure plasma?
Since the flamethrower rework, a flamethrower's damage is based on the burn temperature of the theoretical reaction between the gases in the tank. If you want big damage, you need to make a good plasma/oxygen burn mix.

**Comment by icantthinkofanameritenow** [comment]
I think Fudge is really getting at the underlying issue for the whole lockbox thing. It's silly to expect interaction from a department that has everything it needs at its fingertips, so logically the best thing to do is to begin reversing the protolathe's feature creep. Just about any time new items are added, it's through RnD rather than any other methods of acquisition. 

While the old "weaponlathe" idea has been proposed on occasion, the main counterargument to it is that if it requires security access then only a small fraction of staff who are the first to die will be able to use it- and they are not trusted to distribute the weapons they make when needed in favor of hoarding them all. On the other hand, it is undeniably cluttered and could use some reorganization. At the very least, each department should be given a machine that makes only the items they're required to make, with weapons and armor becoming.available to Sec on a Code Blue and everyone on a Code Red. 

This would also solve any issues with weapon overproliferation, and would also make lockboxes unnecessary for weapons given that the entries to make them would be hidden most of the time. It might even get people to remember to raise the alert levels. 

I've since made an issue elaborating on this, see #12217

**Comment by SonixApache** [comment]
@Shadowmech88 I'll give it another go with a better mix. Spraying burning plasma at someone seems woefully ineffective, though.

**Comment by FudgePucker** [comment]
Also the avalibility of some common objects is piss poor.
If you are in engineering or civilian departments how do you get a beaker besides breaking and entering or asking nicely.
Good luck getting one by asking nicely, your more likely to get a gun from science than them giving you a single beaker.

**Comment by charmstruck** [comment]
@FudgePucker 
You'd be better off asking Cargo or the mechanics for one than science

**Comment by SonixApache** [comment]
Beakers are just reagent containers, you can use other reagent containers (paper cups, soda cans) for a lot of things. Not grenades, which is a bummer, but apart from that.

**Comment by Blithering** [comment]
As a plus point for the revialver, aren't there chemicals that have special interactions on splash that wouldn't work when fired out of a syringe gun?

**Comment by Exxion** [comment]
Either kind of acid. There might be others, but not many.

**Comment by Shadowmech88** [comment]
What about, as a way to make the venom sword better than just the hypospray, make it able to inject more reagents at once, and hold any kind of beaker? Like, 15u or 20u per hit instead of five?

**Comment by icantthinkofanameritenow** [comment]
That would still be a significant improvement, though it's still somewhat offset by the greater visibility and difficulty concealing the venom sword, to say nothing of the fact that there's still only one hypospray on the station and the CMO usually has more important things to do than validhunt.

**Comment by ghost** [comment]
Cable Bola's are only a 30% to work vs the bola's 60% if I read it right back when they got in, I probably didn't. While on one hand, I managed to down a warden at executions, take his AEG, and kill 3/4 of sec who were there before going down, it usually just gets you captured or killed for trying. Basically a ranged push attempt.
