### ISSUE TITLE
You are either AFK, experiencing lag or the connection has closed.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#12170]
#### Description of issue

After restart, when client reconnects to server, after "Processing Geometry..." connection is closing.
![image](https://cloud.githubusercontent.com/assets/10612280/19286381/20481ffe-9006-11e6-8d23-21983ea74dd0.png)
#### Difference between expected and actual behavior

Erm... Auto-restoring of connection or saving it?
#### Steps to reproduce
1. Download latest revision of code
2. Host local server (tested on different machines)
3. Restart round
4. _You are either AFK, experiencing lag or the connection has closed._
#### Server revision

cdf61ec
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by gbasood** [comment]
????
Does the connection restore itself after a bit?
If so that's intended, the thing that's giving you that message is javascript which is just saying that your client hasn't received a message from the server in awhile.
At roundstart this occurs because SERVER SETUP IS FUCKING HARD

If you need to manually reconnect to your local server though that's different

**Comment by ghost** [comment]
Connection doesn't restores by itself. 
It was tested by several people.

After restart, players are reconnecting automaticly. But after displaing MOTD and "Processing geometry" connection is dying.

**Comment by gbasood** [comment]
Sounds to me like the local server is shitting the bed while processing geometry hard enough to drop connections then
We could add sleeps in to make it not shit everything up? But other than that, overloaded serb dropping connection is a BYOND thing.

**Comment by clusterfack** [comment]
Is it actually closing though? Round start initializations are the very definition of lag

**Comment by gbasood** [comment]
The connection is actually closing based on how they're describing it at least

**Comment by Aurx** [comment]
My experience is that this is tied to connection speed.  
I used to almost always have to manually reconnect, aside from once in a blue moon when it'd reconnect on its own.  
Then I upgraded my connection from 10 megabit down to 80 megabit down, and I've only had to manually reconnect once.  
And that might just have been my VPN instead of SS13, it causes intermittent lagspikes.

**Comment by SonixApache** [comment]
I've got a very good connection, but I get kicked out at that point or other points all the time.

**Comment by PJB3005** [comment]
I should remove the message about AFK though, since we fixed that.
