### ISSUE TITLE
ERT members can be chosen as cult sacrifice targets

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#12233]
Wouldn't be so weird on its own, but the job title they're given in the objective description is listed as MODE
Presumably the same happens with deathsquad, but I'm talking out my ass for that.
![image](https://cloud.githubusercontent.com/assets/19365096/19416672/de21c35c-9364-11e6-8318-169c1e481adc.png)

**Comment by Kammerjunk** [comment]
In the extraordinary circumstance that there was a wizard _and_ a cult and the wizard got chosen for sacrifice, it'd also be The Great Memename, the MODE, because that's their assigned role. It looks like there's a good reason for that since it allowed you to exclude all special roles. ERTs **cannot** be chosen while they're on z-level 2, but I'm not sure they should be possible targets while on z-level 1 because of how likely they are to leave that z-level again. If it chooses the HoS and he dies in a gorey shower without a head to recover, the cult is probably the only antags with the freedom to have done that. If it chooses an ERT and they leave the world never to be seen again, welp.
Then again, it's not like ERT members often try to go back to CentComm, especially not when there are valids to be had.
