### ISSUE TITLE
you cant turn beer into flour with the electrolyzer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12249]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> cant 
> 
> What you expected to happen
> flour because flour + enzyme = beer
> 
> What actually happened
> the reaction didnt react
> 
> Steps to reproduce if possible
> put beer into electrolyzer
> zap
> no reactions

**Comment by Kurfursten** [comment]
Probably related to #11476

There is some really unusual behavior when trying to electrolyze certain alcohols. As far as I know, no one has been able to figure out why some won't electrolyze. The behavior is very strange.

**Comment by Shadowmech88** [comment]
Could it have to do with practically every alcohol being a child of deadrum?

**Comment by Kurfursten** [comment]
I don't believe so. Strangely, other alcohols which are children of deadrum seem to work fine. You can read about some of my testing in that other Issue.

Slightly offtopic, if someone DOES fix this, they should adjust the beer recipe to output a lot of beer (like 5x) so that if you want to use the beer keg for flour, it doesn't get too out of hand.
