### ISSUE TITLE
Feature Request - Removable mecha DNA Lock

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12436]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
I find it very strange there is literally no way to remove DNA locks.  Even stealing someones UI + UE wont work. At the very least the research director should be able to remove it by unlocking the mech with his ID I feel.

**Comment by PJB3005** [comment]
Fucks sake man learn how to make issue titles at the very least.

**Comment by Ephx1** [comment]
I'm pretty sure that DNA locks can be removed by the pilot themselves, but there should be some outside ability to do so as well.

**Comment by Gunosaguki** [comment]
Yes you can remove them yourself. But thats an issue when you're trying to remove a theft. Granted most of the time its their fault, but some people just dont know how to set a dna lock or forget and there definately should be a way to remove

**Comment by ComicIronic** [comment]
How would you implement it in a way that doesn't completely invalidate the DNA lock?

**Comment by Intigracy** [comment]
UI/UE sounds good.

**Comment by Gunosaguki** [comment]
I agree with Intigracy. If you can obtain the UI+UE of whoever locked it, such as if they were arrested. Then you can fairly remove the lock, since otherwise they'd just spitefully refuse.

Just That or research director ID. The exosuit Control computer would be too easy to break into to remove a lock
