### ISSUE TITLE
Feature Request: Remove vox traders free no movement penalty magboots

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#12470]
Who the fuck thought this was a good idea?

Seriously. Every fucking round they smash their way into science outpost and mining outpost to loot the place, and they DON'T EVEN HAVE TO WORRY ABOUT ZAS AT ALL.

**Comment by kilozombie** [comment]
If you see a trader do that, get a ban request. If multiple traders do that, expand the ban request.
Pain's said he wants to set an example that trader isn't a license for shittery. Make it happen, because this is a little pointless.

**Comment by Kurfursten** [comment]
Mining outpost has unsimmed doors you can walk in and out without magboots all day no woosh of air

**Comment by FudgePucker** [comment]
@kilozombie 
Even then, why do the poor gypsy birds have better magboot tech than the CE's magboots?

**Comment by Exxion** [comment]
Immulsion-wise, vox boots aren't really magboots. They're just boots that fit vox talons properly and are very sharp and hard, allowing the wearer to dig their talons into the floor. There's not really any tech involved.
That's why you can't magboot stomp with them.

**Comment by FudgePucker** [comment]
@Exxion So their claws can go though steel? And also do no damage to the plating?

**Comment by Shadowmech88** [comment]
If you want to code puncture decals for when vox walk across the floor with their magboots on, be my guest.

**Comment by Exxion** [comment]
@FudgePucker That's what it says when you activate them.
Also it's just iron 99% of the time

**Comment by FudgePucker** [comment]
So they can pearse though the floor every step they take and are not slowed down by that at all?

**Comment by Shadowmech88** [comment]
Evidently so.

**Comment by charmstruck** [comment]
I suggest that you give Trader boots normal magboot penalties and let Raiders have boots with no penalties

**Comment by kilozombie** [comment]
I don't understand why this issue exists.
If you're mad about people abusing the boots to do griff, that's not the boots' fault, that's just griffing and should get bans.
If you're mad about a job getting good equipment... I mean... why do you actually care? It's come in handy before and doesn't strike me as unreasonable. Traders already deal with ZAS on a regular basis due to their existence on a volatile outpost often invaded by Miners and, as it stands, _can't wear any other kind of magboots._

**Comment by kilozombie** [comment]
Plus, Defficency's trader ship is so immensely shitty that you WILL get ZAS'd to death if your magboots aren't on.

**Comment by FudgePucker** [comment]
Why should traders get better magboots than the CE?

**Comment by ghost** [comment]
I can understand giving them faster magboots than standard, but no movement penalty at all? nahhh

**Comment by kilozombie** [comment]
Because they're Vox boots. They're not actually magboots, they're the same ones that Raiders use. They don't actually grasp the ground with magnets, but instead use the chicken grip, whatever
If you want a legitimate suggestion, it would probably fit better as some sort of racial ability with a small movement penalty rather than special boots.
Right now, there's absolutely no reason to remove them unless there's a replacement, though. Traders can't sell them except to other Vox and the situations in which it helps them are rare and usually reserved for times where they're clumsy and open an airlock they weren't supposed to, or get their outpost depressurized by random shit.

**Comment by Shadowmech88** [comment]
There's actually a list var in species datums for special species-only verbs, so it'd be really easy to give vox specifically a "magboot" verb where they grip the floor, and do away with the boots.

**Comment by kilozombie** [comment]
Sure.
It would be an interesting tradeoff if:
1. Barefoot vox can do the magboots for a small or nonexistent speed penalty, but they have all the penalties that come with not having shoes
2. Vox boots are given exclusively to Raiders or perhaps on the Defficiency outpost, which lets them act as magboots as well as protecting feet
I still don't think it's an entirely _necessary change_, though.

**Comment by icantthinkofanameritenow** [comment]
Why not make the trader magboots have the normal speed penalty? It's not like they need it, and they already have a plant that gives them hyperzine access.

**Comment by kilozombie** [comment]
I don't think "it's not like they need it" is an argument.
It's in, it's a feature, I've heard no good reason to remove it except for the fact that people can't imagine why it exists. I've given a few reasons already as to why it helps traders not fuck up their outpost and trade shuttle. They spend a lot of time in space. Without fast magboots, they would need woodapple jam in order to not depressurize the Defficiency trade shuttle horribly. They spend a huge majority of their time in a trade shuttle which, if depressurized suddenly, will kill them with ZAS unless they can react to turn on their magboots in time.
Is it being abused? Is it being used to powergame? If so, say so.

**Comment by icantthinkofanameritenow** [comment]
Yes, it is. See the first post. 

Vox Traders right now are little more than assistants without a place on the crew manifest and a free spacesuit. The very nature of their job is currently too open to abuse, and if in-game limits aren't given to them then harsher rule enforcement must take its place. Besides, the Deff trade shuttle being shit should be another issue entirely.  

And now that I think of it, miners shouldn't be able to access the vox outpost anyway.

**Comment by kilozombie** [comment]
Vox Traders _do_ abuse the job to be shitters, and now they're being banned for it. At least, I'm pushing for that, because everyone hates it.
People abusing the job is a consequence of the job having too few rules and too much open-endedness; if the magboots were slowed, nothing would change. Shitters would still depressurize environments, except now they'd powergame even harder by making hyperzine jam first.
This is like putting a band-aid over a gun. You're not blocking the bullet and you're not patching up the wound.

**Comment by kilozombie** [comment]
MrPain has set a precedent that traders who cause dangerous environments (such as depressurizing mining or research, as said in the OP) would be bannable.

**Comment by icantthinkofanameritenow** [comment]
Then clearly more people need to be requesting bans, including Fudge.

**Comment by kilozombie** [comment]
Agreed completely. I try and ask for the circumstances whenever somebody on the thread complains about a horrible Trader, get ckey and such

**Comment by icantthinkofanameritenow** [comment]
I'm more worried that there's so many of them. It's still a bit too RP-focused on a server that actively avoids RPing when possible, I think.

**Comment by kilozombie** [comment]
I main Trader and generally don't have problems.
You'd be surprised how much people calm down and take a second to relax when they can buy things and chat with a trader. It's a comfy job because I get to meet people without having to be involved in the clusterfuck that they're often perpetuating.
Sometimes there's RP, sometimes it's just an exchange. Either way.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Close this

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
@Exxion
