### ISSUE TITLE
Pathogenic Incubator Bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12511]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
>Revision
66e2d4d61d281895120a9b9aa9f127d5be3f103d 

>General description of the issue
When upgraded, the pathogenic incubator will incubate forever if told to isolate a virus

>What you expected to happen
for it to isolate it faster than before

>What actually happened
it never isolated

>Steps to reproduce if possible
Upgrade the pathogenic incubator and try to isolate a virus from a blood sample

**Comment by ghost** [comment]
I've found what causes this

If you have 2 pico manipulators, the general_process_time goes from 40, to 6.6666 recurring

Now, during the machine process, it just takes 1 away each time until it would assume that it reaches 0. However, because there's a decimal point, it can never reach true 0, so just keeps going into the negatives.
