### ISSUE TITLE
Should Speedcloning Be Removed

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#12585]
Specifically the mechanic in which you can swipe your ID to unlock the pod and eject a clone within seconds of creating it.

I have no opinion one way or the other, but people in the thread seem to be angry at it and are obviously not going to make the issue themselves.

**Comment by kilozombie** [comment]
People in the thread are angry about it?
Oh, I see somebody who's probably a mechanic salty about upgraded cloners not being muh useful.
Medbay would be much worse without speedcloning especially on rounds where there are lots of corpses that can't be defibbed, I don't see ANY reason to remove it.

**Comment by kol1th** [comment]
no

**Comment by Kammerjunk** [comment]
Nah
People are just shitflinging about medbay. The latter half of the last thread went with it and just keeps going

**Comment by Exxion** [comment]
Cloning is too easy, but I'm not sure just removing early eject is the way to go about fixing it

**Comment by AutismSpider** [comment]
come out with way more damage when eject early or missing body parts

**Comment by Exxion** [comment]
The former is already the case, but cryo makes it irrelevant
Honestly the latter sounds good to me but the probability I'll be yelled at for saying that within the next few minutes is essentially 100%

**Comment by Kammerjunk** [comment]
Eh, there is absolutely no way at all to replace body parts without a trip to robotics for a direct downgrade or finding a "donor"

**Comment by Exxion** [comment]
>direct downgrade

That's debatable, but robotic limbs definitely need some work

Actually limbs in general need some work
Our organ system is horrific
But I digress

**Comment by Ephx1** [comment]
> People in the thread are angry about it

If we listened to the thread, the station would be one big room with a bunch of toolboxes, and it would always be on traitor.

**Comment by Exxion** [comment]
Except this isn't the first time this has been talked about here.

**Comment by Ephx1** [comment]
And?

**Comment by Exxion** [comment]
>The thread's talking about it now so it's obviously just shitposting

**Comment by kol1th** [comment]
The thread is always shitposting

Anyway, about the "come out missing limbs part", that wouldn't really work considering if you're even just missing a foot you're absolutely useless and all you get to do is lie on the floor

**Comment by Megamaw** [comment]
I always get speedcloned. Never the regular way, so I'm not certain if what I'm about to say is accurate to the way the game works.

Is this why I come out of cloning with hilarious amounts of genetic deficiencies and the doctors just kick me out right then and there?

If so, please remove this, this is dumb.

**Comment by AI-Is-Rogue** [comment]
magic healtubes

**Comment by yclatious** [comment]
Medbay is already relatively simple, it isn't in any way complex or hard, and people still get mad to the highest of heavens as to how medbay can fuck up in such ridiculous ways, like 45 units of bicardine and shit, not to mention autism over cryo mixes, surgery, pill colors, so on, touching it in general is a bad idea unless you got everything planned out already.

Folks, not everyone is a ultra competent player, especially in terms of the medical area, the last thing we need is to remove speedcloning, both so death isn't over 10 minutes for 1 person to be revived due to upgrades never reaching the medbay area due to mechanics mostly being affected by lack of supplies, and due to the idea of removing limbs and shit to just be anti player. Sometimes, medbay gets the ride, and shit gets wild, over 7 bodies sometimes, and since Science are lazy bumholes who don't do extra cloners or anything, you are absolutely not getting extra cloners unless the gods grace you and a mechanic isn't a nigger, you really want to make every single clone to take atleast 7 minutes to make at bare minimum? And you want to punish people for trying their best to get people back in the round by removing crucial things like limbs when a single missing foot makes you useless? If there is 5 people in line to cloning, the last one will get cloned in about 35 minutes, that is if they pop clones with max efficiency, that won't happen.

Id say that's bad logic honestly, cryo is meant to be good and has been perfected to the best of its theoretical ability over literal months, to nerf it is to deny all the skill it took for the players to perfect it, obviously bad, death is still meaningful as cloning still takes a while and body recovery is not exactly speedy or reliable, to claim people don't fear getting killed is bollocks, increasing the time it takes to clone just to make death "meaningful" makes no sense, it is meaningful, you what what isn't, permanently screwing people for wanting to not be half a hour out of the action, hurting docs for wanting to help people enjoy the game as living, alive players, that's bollocks, plain and simple.

If you don't like the status quo, offer a better alternative, because removing limbs and making people get emp bait is no answer.

**Comment by kilozombie** [comment]
Megamaw, I have absolutely no idea what you're saying
People who are cloned should be put in a cryotube regardless of anything. If the cryo has a decent mix with cryo/clonex/alkysine/ryet, then you can get speedcloned. If not, then you still need to be cryox'd with the base beaker mix. 
If doctors are popping you out of the magic clone tube and don't put you in the magic heal tube, then they don't know what fastcloning actually is.
If you get fastcloned into a cryox-only mix, go take some ryetalyn.
Everyone who plays SS13 should know how to fix simple problems like brain damage or ryet for when Medbay becomes a wild ride. You should stop expecting doctors to give it to you if it's not already in the cryomix.

**Comment by JustSumBody** [comment]
>you should stop expecting doctors to do their jobs
Que

**Comment by kilozombie** [comment]
>guy standing next to medbay fridge for 10 minutes
>medbay is busy and understaffed
>screaming "HELP I HAVE A COUGH"
>"HELP HELP PLEASE FIX ME"
>fridge has 80 ryetalyn pills
>some kind assistant comes to force a ryet pill down his throat
>guy runs away
>"HELP HE'S TRYING TO KILL ME"
>runs out of medbay
>"medbay is so shitty today, they didn't even fix me"
>"doctors need to do their JOB"

**Comment by kilozombie** [comment]
yes, you should stop expecting medbay to do their job. if they do it, that is good. if they don't, know how to fix yourself when possible.

**Comment by Allspice** [comment]
Even if you remove the ID swipe you can still toggle the APC to eject a clone. But fucking with speedcloning some how seems okay to me.

**Comment by Gringonius** [comment]
>The thread is always shitposting

your discord is always shitposting
OOC is always shitposting
everything is shitposting and should be disregarded

I do think that something needs to be changed. The main argument for the status quo is when medbay only has incompetent players and not a single person get cloned. I do think that the opposite is just as an issue to gameplay, if there's at least one competent player death becomes a complete non-issue unless someone's head is destroyed while medbay can clone dozens of people under 5 minutes.

If speedcloning somehow gets completely removed, the cloner speed from upgraded materials should be even faster.

**Comment by Arthurdentist** [comment]
Medbay doesn't need to be made anymore tedious then it already is. What is with this obsession with messing with Medbay? seems to come up time and time again. Wasn't the cloner already nerfed by Dylan a while back? Wasn't that enough then or what?

**Comment by yclatious** [comment]
The problem with basing nerfs on thinds like buffs to t4 parts and such lies in the following

*ALMOST NOBODY PLAYS FUCKING MECHANIC AND SCIENCE WOULD BUILD THEMSELVES LITERAL DILDOS TO SIT ON THEIR AUTISM CAVES RATHER THAN ACTUALLY HELP MEDBAY IN 99 OUT OF 100 ROUNDS*

Even if you buggered them enough, I would bet you real, live cash thy wouldn't upgrade it without the RPE, swear most of them don't bother even thinking of upgrading things unless they have it. Science is not reliable to base a nerf on.

**Comment by Arthurdentist** [comment]
lets just remove all medbay equipment until science researches and then builds it tbh.

Actually we could do this with all departments.

**Comment by yclatious** [comment]
The fact I know atleast a few people sincerely think that's a actual solution makes me :^)

**Comment by Ephx1** [comment]
@Exxion

If it was brought up before then it must've been shot down, so yes, the thread _is_ shitposting.
Or should we open up another issue about changing the AI round start laws?

**Comment by kilozombie** [comment]
Ehh, I'm reading some shitty posty in the thread and there are good points.
I don't think speedcloning should be removed, but, honestly, that's only because I use it often. Feel free to dismiss my opinion.

**Comment by Exxion** [comment]
#4307
Not really. There was discussion then it just fizzled out.

The problem is that two machines shouldn't outmode an  entire department.
Cloning should be a last resort, but right now it's one of the first.

**Comment by Megamaw** [comment]
@kilozombie 
>take ryetalin

With what syringe my man

**Comment by kilozombie** [comment]
>playing a skellyman

Get a syringe from a medical box ya meme

**Comment by Megamaw** [comment]
ok, i have a syringe

now where's a beaker

**Comment by kilozombie** [comment]
Uh oh, spaghetti-os
That actually is a conundrum, but wouldn't a soda can or cup from the water cooler work?

**Comment by Ephx1** [comment]
A glass, any food, a free bottle from chemistry etc.

**Comment by ghost** [comment]
Leave medbay alone, if you change it, even less people will play it, and then the rounds will get 200x shitter.
If you want to get rid of super speed cloning, the machine takes way too long at default to pop someone out on it's own (and it used to take even longer before the inaprov overdose was removed).
Not allowing the machine to remove people below something like 50% health could be an option, but then if the power goes out and someone is at a less percent would they be trapped? That sounds kind of unfair. You'd need to impliment someway for them to wake up and get out (I thought about resist and then breaking the cloning tube but then it would never get fixed, or more importantly how would you fix that)

Megamaw. If you're a skeleton, use an IV and a pill, then you don't need a beaker or a syringe. There are two publicly available IV drips in medbay. 
If you do need a beaker, a cryox beaker starts on the table next to cloning, dissolve a pill in it and take 5u out, ryet only needs a tiny bit to work.

**Comment by AutismSpider** [comment]
@Megamaw soda can glass cup work too you meme lord

**Comment by TheFriggenSawbones** [comment]
no

**Comment by FudgePucker** [comment]
I think that this is a bad idea.
Everybody wants medbay to be stocked with better doctors that don't just clone cyro. But ask your self this, are you playing medbay?

**Comment by AutismSpider** [comment]
@FudgePucker play med-bay if you die of an aneurysm

**Comment by SonixApache** [comment]
logically / lore-wise: yes
/vg/ high-octane action gameplay meta: no

**Comment by Probe1** [comment]
Lets just do the limb thing.  If someones not fully cloned they have a very high chance of having broken limbs.  That way we don't have too mess with printing new limbs (which is shoddy at best) and we don't have the cryo-fixes-all solution.  You can speedclone them and roll the dice on whether they need surgery.

**Comment by kilozombie** [comment]
Interesting.
I think I'd roll, personally, with speedcloning and then surgery, unless you mean 2-3 different broken bones, in which case only if surgery has an impressive toolset and a dedicated surgeon.

**Comment by Probe1** [comment]
Yeah if that's an agreeable direction then it should be limited to one thing and not "He's so fucked we should just clone again"

**Comment by kilozombie** [comment]
Could be like, the average is one bone, with 0 or 2 being outliers?

edit: If the goal is for surgery to be relevant, a chance for a damaged organ is also applicable, I guess.

**Comment by PJB3005** [comment]
Various organ damage and a 1 or 2 bones sounds fair.

Fixing multiple organs in the chest isn't hard because they're done at the same time but it makes keeping the patient alive not something that can be ignored if they've got a barely functional heart.

**Comment by kilozombie** [comment]
Although I can imagine doctors doing something ridiculous where they scan clones before cryo, and then toolbox clones to death if they have more than one bone broken or an essential organ. A really unlucky clone could undergo 3-4 clonings because hey, we've got enough biomass, why not?

**Comment by Kammerjunk** [comment]
Any penalty to speedcloning I can think of effectively removes it since it'll be way easier to just let them clone all the way through and then cryo them. Lets them sit and not die and frees you up to treat other patients. Assuming no surgery upgrades from science, it'll even take you less time.

**Comment by Probe1** [comment]
That's generally my idea and what I concluded as well.  Speedcloning should be in the game.  But it should have downsides and be reserved for "The shuttle is about to leave and we MUST hurry" instead of "do this every time no matter what".

With tier 3 upgrades cloning only takes like 15 seconds.  So the in game mechanic for fast cloning already exists, but it's overwritten by speedcloning since 1 second > 15 seconds.

**Comment by PJB3005** [comment]
In a theoretically highly coordinates medbay one could speed clone while another doctor does fixing of the clones.

Such a medbay doesn't exist however.

**Comment by kilozombie** [comment]
An unupgraded cloner is arduous on certain patients, though. For some, it can't even get to a fully cloned state because they'll be taking damage (definitely Vox and maybe Plasmamen?)

I once organized (as CMO) an actual surgeon to do his job while the rest of Medbay operated separately. I don't think it's unreasonable to try for clone-surgery cooperation! It provides a goal for CMO.

**Comment by Kammerjunk** [comment]
😢 
@Probe1 I didn't think of it like that. Reserving speedcloning for absolute emergencies, yeah.
I don't necessarily *like* it because speedcloning or not speedcloning isn't robust, it's just faster/slower, but I can work with it

**Comment by kilozombie** [comment]
Way I see it, if a mechanic is upgrading the cloner to level 3, the cloner should be used, not speedcloning.
Then, if speedcloning could break bones or organs, speedcloning becomes a complex technique for a good Medbay to use when a Mechanic can't upgrade the cloner.

**Comment by ComicIronic** [comment]
Can you not replace limbs with meat? You can at least peg them.

**Comment by kilozombie** [comment]
Peg limbs are absolutely awful though.

**Comment by AutismSpider** [comment]
can up monkey humans for new limbs and shit

**Comment by PJB3005** [comment]
Or cut off the limbs of the old corpse...

**Comment by Probe1** [comment]
do they retain their dmg vars or are they just magically fixed when they're removed from a body

**Comment by PJB3005** [comment]
That's a good question.

Logically: retain, but I know limbs are pure shitcode so ???

**Comment by Exxion** [comment]
I'm almost certain that limb damage is attached to the mob, not the limb

**Comment by Shadowmech88** [comment]
Limbs don't retain their damage when cut off.
Also counter-intuitively, I believe the host body *does* retain limb damage for missing limbs.
So if someone breaks their arm and you cut it off and attach a different one, it'll still be broken.

**Comment by Exxion** [comment]
Thanks, oldcode:tm:
