### ISSUE TITLE
Map won't change out of Metaclub

### ISSUE THREAD

**Issue by sonime** [d3athrow/vgstation13#12600]
#### Description of issue
We are playing on Metaclub even when people vote for other stuff

#### Difference between expected and actual behavior
We voted in Box but it's been Metaclub again

#### Steps to reproduce 
Vote a different map than metaclub
???
Metaclub!

#### Length of time in which bug has been known to occur

Last three rounds at least

#### Server revision

6d46abc882a8b10d93a575d12cd69a2b8e939f0f

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by JustSumBody** [comment]
On a possibly related note, the round end screen isn't popping up when the shuttle docks properly.
It takes a full 30 or so seconds until SMELELELE and it shows up. During this time the shuttle is also dark, I assume it had to do with lighting runtimes or some such but the runtime viewer silenced them because they were numerous.
The shuttle docking at the station message also doesn't play for about the same time as well. Lighting isn't an issue in this case and I'm not at all sure what I should be looking for.

**Comment by sonime** [comment]
Should I close this, we played Box a few rounds ago

**Comment by ComicIronic** [comment]
It's still an issue if it happens again.

**Comment by PJB3005** [comment]
Round end code's a mess and I'm not sure whether this is N3X15's watchdog breaking down or the code shitting itself.

**Comment by Kurfursten** [comment]
@Exxion Haven't reproduced in 2 years
