### ISSUE TITLE
Request: Build-able full glass that can block radiation.

### ISSUE THREAD

**Issue by ReindH** [d3athrow/vgstation13#12673]
Requesting a recolored version of a glass pane that can stop radiation from the super matter shard and the singularity.
Let the crew see what powers the station without the negative effects of being a filthy carbon near his majesty the shard.

**Comment by PJB3005** [comment]
As much as this would be nice, it's basically impossible with our current radiation code.

And even with proper radiation code I doubt it'd be feasible...

**Comment by ReindH** [comment]
Does that mean that the shutters on deff and the singularity ain't worth shit against the rads?

**Comment by ComicIronic** [comment]
I mean, it would be possible with an adaptation of the existing explosion code, but not easily.

**Comment by Shadowmech88** [comment]
Radiation from stuff like the supermatter shard is based on being in the shard's view, so it might be able to be blocked by a one-way-window, I think?
But last time I tried to add one-way-windows something went wrong and it caused major lag on the server that never happened in testing, and I haven't gotten around to trying again yet.

**Comment by ComicIronic** [comment]
view() is Byond internal, so sadly not.

**Comment by yclatious** [comment]
Wait, maybe Im just a retard, but wouldn't surrounding the shard with radiation blocking material make the collectors not output anything and as such, make the SME useless?

**Comment by ComicIronic** [comment]
You'd think so, but no. Radiation collectors are hardcoded into the singulo and SME code.

**Comment by PJB3005** [comment]
It's weird actually.

Because radiation is snowflaked into everything it's not standardized.

The SME's effective range to irradiate mobs is less than 3 tiles in any normal situation. You have to be INSIDE the chamber to even get hurt. Note that it does travel through walls (using `range()`?).

Rad collectors do work with `view()` though, and much larger ranges.


Anyways, why this request isn't possible:
We can't change how BYOND's `view()` works without ALSO blocking LoS from regular players. There's 2 solution to this and neither are pretty:
* Trace a line from every player in range and try to detect a blocking tile on the way, slow.
* Do recursive stepping like explosions, slow.

**Comment by Shadowmech88** [comment]
>Do recursive stepping like explosions, slow

What if radiation was sent in pulses, rather than constantly?
How much performance would it cost to do the spiral calculation that explosions do once every second or so?

**Comment by Exxion** [comment]
>Raycasting
>Slow

It's faster than checking if something is in `view()`
By a lot
Problem is that our current `can_see()` implementation sucks incredible amounts of ass and is wrong most of the time
(Well not most of the time but a significant portion of it)

A while ago I was working on making it less awful, but I still haven't gotten around to finishing it
BYOND's occlusion is... not simple.

**Comment by ComicIronic** [comment]
It would be raycasting on top of a `view()`, which would be slow.

**Comment by PJB3005** [comment]
Don't get me wrong I'd love this because it would allow me to nerf the shit out of rad collectors in an intuitive way.
