### ISSUE TITLE
ai on box can be killed by his own turrets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12771]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue 
if the turrets aim at a dude breaking from captains office the 2 turrets on the left will shoot the ai istead

>What you expected to happen
ai not dying from  his own turrets

>What actually happened

ai got damage from the turret
>Steps to reproduce if possible

break a wall from captains and be the laser turret target and look how the ai dies from lasers

**Comment by 9600bauds** [comment]
If you can get a picture of the exact spot that'd be great

**Comment by pvak** [comment]
it happened in the tile where there is only one rwall but it probably works on other places too

**Comment by Ephx1** [comment]
The bottom two turrets will shoot at the AI if there's a target on the AI directly, or if there's one directly behind the core's walls.

**Comment by Kitfox88** [comment]
silicon ban for breaking law 3

**Comment by Ephx1** [comment]
I really don't see how this could be fixed without making it harder to kill the AI.
Something should be done, but I'm not sure what.

I mean unless someone is willing to alter how core turrets work and make them function based on line of sight like how I assume regular turrets do instead of a magical sensor covering the core.

**Comment by Shadowmech88** [comment]
Core turrets could be given a special projectile that just doesn't damage the AI.

**Comment by Ephx1** [comment]
There is a slight problem with that. Wraiths (and sometimes wizards) LOVE to pop directly on top of the AI mob itself and hit it, so I'm not sure how others feel about that. 

I forget if we still allow jaunting into walls or not, if we do then I suppose that's fine, otherwise that sort of nerfs one of the few surefire ways of killing the AI.

**Comment by Probe1** [comment]
Without remapping a lot of shit I don't see how this is feasible to fix from a mapping perspective.  Maybe do what @Shadowmech88 said.

**Comment by Shadowmech88** [comment]
Better solution, I know that ranged mobs have code to prevent them from firing if doing so would hit a friendly standing between them and their target.

Maybe implement something like that for turrets, to prevent them from firing at an unauthorized mob if doing so would hit an authorized mob?

**Comment by Probe1** [comment]
That'd be a huge issue for AIs.  As long as you get to the core, you can just stand there for free and not get stunned/lasered.

**Comment by Ephx1** [comment]
Also a Wraith would kill an AI 100% of the time as there would be no way to attack it. (Which I suppose would be a problem on Metastation, but when the fuck do we even play anything other than box anyways?)

**Comment by Shadowmech88** [comment]
>As long as you get to the core, you can just stand there for free and not get stunned/lasered.

This would happen just the same as it would if the turrets *tried* to hit you and the AI blocked the projectiles.
