### ISSUE TITLE
Medical Nanobots doesn't heal toxin damage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12782]
(WEB REPORT BY: fruktlimpa REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
I asked an admin to give me 50 toxin damage and then use medical nanobots to heal me and the Medical nanobots seemingly doesn't heal Toxin damage

>What you expected to happen
I expected to be steadily healed from my toxin damage

>What actually happened
Nothing. The medical nanos were matbolizing at a rate of 0.05 per tick and healing diddly squat

>Steps to reproduce if possible
Just give yourself toxin damage and inject yourself with medical nanobots and it shouldn't heal.

Not sure if this is intentional but the description of them say they heal all kinds of damage.

**Comment by Intigracy** [comment]
It may just be a really bad case of RNG, there's only a 50% chance per mob tick to heal toxin damage, but other damage types are 90%.

**Comment by Fruktlimpa** [comment]
Does that mean that there is a 50% PER tick or a 50% when you inject yourself? Because I let it go for at least a few ticks before healing myself with anti-toxin pills and surely I cannot have had such shit luck that over them any ticks that transpired none of them triggered the medical nanos.

I also had a situation earlier in the same round where I injected a treeman with medical nanos to heal his burn damage and it didn't heal anything and just slowly metabolized.

To add to that, how many ticks per second does this game run? If you can ask like that. I can test this out tomorrow some more and see what gives.

**Comment by pvak** [comment]
nanobots dont work on dionas

**Comment by JustSumBody** [comment]
@pvak should have been changed recently by https://github.com/d3athrow/vgstation13/pull/12230

**Comment by Fruktlimpa** [comment]
Alright I did some testing on my own server and found out these interesting things about it.
If you want logs or something I'll have to redo it tomorrow, but for now you'll have to take my word for it.

The only time you get the message "X wounds heal in the blink of an eye" is when the chest is the damage location. This works for both brute and burn and it will instantly and fully heal the chest with no extra reagent consumed by it.
However,  if some other body part is damaged that isn't the chest then the medical nanos will only heal 5 damage per tick. This isn't bad of course but it is terrible compared to the instantaneous healing of the chest area, and it gets extra shit when you account for the RNG.
If you have, for example, the chest and the legs damaged, then the nanos will instantly heal the chest while ticking away at the legs.

From what I could glean from the code it seems that toxin and oxygen is coded so that it is supposed to heal less reliably and also heal less overall.
From the attached comment it seems like Brute and Burn should heal 50 per unit, this doesn't seem to be the case because if you inject someone with 5u med nanos then it should be able to heal 250 brute, however it only seems to heal about 175 at best from what I tested.
While oxygen only heal 30 per unit and has a 60% chance per tick of actually healing anything. Toxin healing 20 per unit and having a 50% of working.

All in all it seems extremely inconsistent and that only the chest is able to be instantly healed seems like a bug. It probably is a balance issue but I see no problem with it seeing as Med nanos are annoying to gather since you need several departments actually working and willing to give you the tools.
