### ISSUE TITLE
Virus effects don't have a standardized suffix

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#12912]
#### Description of issue

Half the viruses are called "x syndrome/effect" while the other half are just "x". Basically the difference between "Full Glass Syndrome"/"Biolobulin Effect" and "Watery Eyes"/"Hearing Loss". We should pick a suffix and stick to it. I personally vote for removing all suffixes like "effect" and "syndrome" because of how repetitive they are, and because of this occurring when you examine a dish:

[...]
Effect: Saliva Effect [...]
Effect: Appetiser Effect [...]
Effect: Hyper-Perspiration Effect [...]
Effect: Delightful Effect [...]

#### Difference between expected and actual behavior

Expected: virus effects have a consistent naming pattern
Actual: inconsistent naming pattern, eye cancer when examining dishes

#### Specific information for locating

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/virus2/effect.dm

**Comment by PJB3005** [comment]
Suffixes are used when the name of the virus is more a "special name" and not directly based on the effect of the syndrome. It makes sense to me, and I personally think it should be standardized to "x syndrome".

Because my previous sentence isn't directly clear, something like "Hearing Loss" is very obvious, but "Full Glass"?

**Comment by despotate** [comment]
I agree with what you say. Self-descriptive names should stay as is while all others should be suffixed with syndrome.

Some of these virus names are really uncreative. "Saliva effect"?
