### ISSUE TITLE
About engineering hardsuits on boxstation

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#12958]
on deff and meta engineering and atmos hardsuit are readily available;
on box the engineering hardsuits are inside the secure storage, so if an engineer needs them they need to ask the CE or a silicon to open it, hack inside the CE office or go to E.V.A., and i can't really understand why.
in my humble opinion they should be available like the other maps, one way could be to modify the storage, for example like this:

![sstorage2](https://cloud.githubusercontent.com/assets/6170726/21350086/cd5195b4-c6b5-11e6-833f-aa5514b4966e.jpg)

1- airlocks with normal engineering access 

2- there is a button inside the storage to open the shutters, it's been moved inside the new secure section

3- in this example the storage is now 1 tile longer, these lattices are meant to aid people spacewalking on that corner outside the station

what do you think?

**Comment by Probe1** [comment]
Yeah sure i'll bang that out later this week.  No big deal, it's a reasonable change.

**Comment by Shadowmech88** [comment]
Alternatively we could *add* shutters to the other maps' Secure Storage rooms.

The upside of shutters is that the average shitter can't just hack two doors from maintenance and have a free hardsuit.

**Comment by Probe1** [comment]
If you're stealing a hardsuit you're stealing it from EVA instead of going fuck all the way to engineering.  

That's how it works in game.

**Comment by uazuaz** [comment]
@Shadowmech88 
they can already steal the atmos hardsuits that way and do the same at E.V.A.

**Comment by PJB3005** [comment]
Another interesting fact is that box has way more hardsuits.

**Comment by Probe1** [comment]
It should be said the other way around since Box came first and then Meta/Deff, which received less hardsuits since they never had a proper "hardsuit storage area" like Box did when we updated from OLD ASS BOX with robotics where Telecomms is and engineering got a storage area.

I have never once seen a real shortage of hardsuits on Box, Meta, or Deff, so I'm personally satisfied with the amounts they have.  

Taxi though

Holy shit.

You literally had to RUSH the hardsuits on taxi or else you weren't getting one too fucking bad buddy you're a greasemonkey that fixes doors and windows now.

**Comment by uazuaz** [comment]
what about replacing the engineering suits from box's EVA with 2 generic space suits?

**Comment by SysadminJeroen** [comment]
@uazuaz What would the difference be between Meta generic EVA suits and the ones supposedly being in Box Engi EVA?

**Comment by Probe1** [comment]
Why?

**Comment by uazuaz** [comment]
you were talking about the fact that box has more hardsuits, i thought you were talking about engineering hardsuits, maybe i misunderstood.
