### ISSUE TITLE
tinsel issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#12965]
#### Description of issue

![scrnshot1](https://cloud.githubusercontent.com/assets/6170726/21365440/a57bf508-c6f5-11e6-927e-9b78d16fc520.png)

tinsel are placed on the west and north sides of a tile only; checking the file
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/icons/obj/christmas.dmi
i can see that there are sprites for all 4 directions, so i can assume it's a bug.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
It's not.  I added their directions initially but the implementation did not work out so we scrapped it.  Since they can be seen from both sides of the wall @Shadowmech88 suggested it was best if we just stuck to one orientation for N/S and E/W.  Sadly.

The issue stems from TILE_BOUND not working how we want and objects with pixel offsets being visible if you can see the tile they were placed on in the map, rather than where they appear.  If we place them on the tile next to a wall then offset them, they are not visible on both sides of the wall.  However this creates a mess when you are in a situation where you cannot see the wall but can see the tile in front of it.  

Tinsel on black no vision tiles.

**Comment by uazuaz** [comment]
ok, should i close this issue?

**Comment by Probe1** [comment]
It's up to you.  Do you think that it would look better if they were properly aligned on the walls for the hallway side, but not for the maint side?

I can and will change it.

**Comment by uazuaz** [comment]
well, i don't think that my opinion alone matters, so i'll leave it open for now just in case someone wants to give his opinion.

**Comment by Shadowmech88** [comment]
Personally I think that all E/W tinsel should keep its current orientation, but the N/S tinsel might look better if it was aligned to the hallway side.
