### ISSUE TITLE
Should you be able to build girders (and then walls) faster? Y/N?

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#13124]
Personally I think it should be at least maybe 25% faster just because building autism forts is difficult enough and we rarely ever get "WE BUILD" anymore because rebuilding takes so long. I'd like to hear some opinions first though

**Comment by Aurx** [comment]
The main issue is that you can only build girders on your own tile, whereas most other mass constructions can be at least done on all adjacent tiles at once.  This means that girder workflow is move->start girder->wait->next tile whereas for, for example wall plating, it's move thrice -> start plating N times -> wait (just once!) -> next 3x3 area.

**Comment by kol1th** [comment]
Yes.

**Comment by nuklearcellphoneg** [comment]
RCD

**Comment by nuklearcellphoneg** [comment]
I'd argue removing steal objectives would do more for build/rebuild, since cargo/science/etc wouldn't need to be so finicky about 1) building RCD and its carts preemptively 2) wouldn't be an issue to build one when someone else asks ahead of time or during a disaster 3) engineers/etc could be more freely equipped with them.

**Comment by kilozombie** [comment]
Can't RCD wooden walls, for instance if you want to build a cabin in snowmap with just an axe and spade it's pretty difficult as you need to girder each wall on each tile.
Maybe just faster for wooden walls?

**Comment by ghost** [comment]
Give us some construction time variables to work with, rather than it being magic numbers

**Comment by Probe1** [comment]
@Aurx you apply the plating to the previous girder while building the next girder.  Like so much of SS13 its about being gud.

**Comment by jakmak** [comment]
I literally reduced the price of the RCD compressed matter cartridges exactly for this. The problem is compressed matter has to be made via autolathe and compressed matter doesn't fit in boxes and the RCD only holds 3 cartridges. Good luck making a million Trips to cargo to get 6 walls worth of compressed matter per trip

**Comment by Aurx** [comment]
@Probe1 It's faster to slam down the girders then plate them all at once.  Git gud.

**Comment by Intigracy** [comment]
@jakmak Compressed matter DOES fit in boxes and pockets.
