### ISSUE TITLE
Should we return to chemists and CMOs being the only ones with access to chemistry?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13214]
2010-2014:  Chemist was an important job and we had many notable chemists.

November 2014: Badclown removes chloral and gives everyone but paramedics chemistry access

December 2014: Pomf returns and we get chloral back

2016:  Chemists are muscled out by half the station walking in to replace them.  Quality players play doctor since it has chemist built into it but without the expectation of doing a thorough job.

Is it time we go back and return Chemist to a real part of Medbay?

**Comment by Ephx1** [comment]
I think if you want to talk about this you might want to consider the extended access that other departments got.

**Comment by Blithering** [comment]
Possibly trial run no extended access for a week?

**Comment by Probe1** [comment]
It's worth pointing it out yes.  Engineers got atmos access.  Scientists got robotics access.  And vice versa.

However those didn't kill off roboticists or atmospheric techs.

**Comment by Ephx1** [comment]
I would argue that it sort of made roboticists pointless but atmospheric technicians are usually only played by someone who knows pipes while normal engis know the basics.

**Comment by ghost** [comment]
I've noticed on some servers that you can be given extended access at roundstart if there's a lack of people. Like a mechanic would get general engineering access to set up engines and such.

Perhaps, should there be no chemist at roundstart, any roundstart MDs are given chemistry access? This would mean that any non-roundstart MDs wouldn't get chemistry access, and should there be a chemist the MDs won't get their additional access.

Problem with this would be you'd be at the whim of a shit chemist if he just joins to go AFK in chemistry to fuck over MDs

**Comment by Kammerjunk** [comment]
There are too few chemists who know how to do anything and those who do and still somehow have an interest in medbay mostly play MD or scientist because it's the same except you can do more/have less responsibility (respectively). In lowpop, doctors will have to break in and in highpop, doctors will either have to break in or get mad at the chemist for having fucked off. As I understand it, this is also exactly what caused the access in general.
For engineering, this'll mean station engineers will have to work around their limited access to cool plasma (no access to the socket wrenches) and for science, this means lone robos can't do RnD (or was the deconstructive analyser's access requirement removed recently?) and lone scientists have to do RnD the long way (and can't fix up borgs). If you want to remove extended access, what @Skullyton suggests is the best way around it.

**Comment by kilozombie** [comment]
Possibly because atmos and robotics are their own jobs and can't be done very quickly unless you're just hopping in to grab some things. When MDs were given Chemistry access, all previous Chemists just became MDs because it had more benefits overall, maybe? I wasn't around for the change but had played on servers where the jobs were mutually exclusive.

@Skullyton I was going to suggest something like this, it makes enough sense but yeah it can get bad with an inactive chemist. In the end though, you really only need to break one window, and I doubt anyone's going to persecute you if you're an MD and there's no chemist.

**Comment by Probe1** [comment]
@Skullyton we have that partially implemented in the code.  We at least have restricted and extended access defines.

**Comment by Gringonius** [comment]
If anything I think that chemist should be turned into an alternative MD job title, occupying the same job slot, medbay gets overpopulated enough during high pop.

Since things here are always balanced around scenarios where players are absolutely incompetent, blocking MDs from chemistry will just bring back those rounds with 2-3 doctors having to break into chem or screaming at the chemists to do anything but mutagen and space drugs smoke.

**Comment by Kuranon** [comment]
I mean, the Head of Personnel job exists, you don't have to break into places you don't have access to

**Comment by Fruktlimpa** [comment]
We very rarely have chemists and when we do they are 9 out of 10 times horrendous for some odd reason. The extended access might have been the fault of that, but I foresee a lot of breaking into chemistry and a lot of angry MDs who get busted for trespassing.

**Comment by ghost** [comment]
Kuranon, weapon permits exist that can be granted via a HoP, doesn't stop scientists from blowing open lockboxes

**Comment by Kuranon** [comment]
The HoP shouldn't be giving out weapon permits to just anyone. Extra access to jobs within your department is reasonable to ask for and you will most likely get it, if you just asked

**Comment by PJB3005** [comment]
I think it's less that the HoP wouldn't give them out and more that it's easier to just bust the lockbox open the hard way.

**Comment by Gringonius** [comment]
>It's worth pointing it out yes. Engineers got atmos access. Scientists got robotics access. And vice versa.
>However those didn't kill off roboticists or atmospheric techs.

Scientists and roboticist are doing the same job, often scientists take care of robotics when roboticists are incompetent or non-existent. This is the exact same thing that is happening with chemistry, with the only difference of people from outside of medbay breaking in to make their own drugs.

At least the way you put all this doesn't seem to show any sort of issue regarding medbay itself but rather chemistry being easily broken into by people from outside of its department.

**Comment by Kammerjunk** [comment]
And similarly, breaking into chemistry is easier and much less time-consuming than getting the HoP's attention

**Comment by 9600bauds** [comment]
Would Chemists not have surgery access or something to balance out their access?

**Comment by ghost** [comment]
Overall I believe Chemistry access should be given only to Chemists save only if there is no Chemist. And to the people who say no because there might be a shit chemist well then tough luck, you could say that about every job on the station and make the argument that everyone should have access to everything because they might be shit. And on the same front I believe Chemists shouldn't have Surgery access unless there are no Doctors.

**Comment by Kammerjunk** [comment]
I believe they already don't, but I'm not sure since I only very rarely see any worth their salt.

**Comment by 9600bauds** [comment]
Yes they do, Chemist and MD are exactly the same job bar the PDA cartridge

**Comment by aceedex** [comment]
This will simply increase the amount of broken windows and fix little else. you could just remove the chemist job and get a better ending

**Comment by kilozombie** [comment]
I mean, at some point, that's like saying "just remove warden and let security officers have armory access" or "just remove quartermaster and let cargo techs do the job"
There are a lot of advantages to having different jobs with different access and purposes in a single department.

**Comment by Fruktlimpa** [comment]
The thing is, if the chemist is bad then the MDs get completely crippled. They literally cannot do their job if there are no chems or mix.
Science wont fall apart because there is no robo.
Engi wont fall apart because there is no atmos tech.

**Comment by despotate** [comment]
Are the MDs really "completely crippled"? Can't they order medical crates?

**Comment by Kuranon** [comment]
Medical crates, sleepers, the medkits in the backroom

**Comment by PJB3005** [comment]
@despotate has a point. Medbay can run fine without chemistry.

**Comment by ghost** [comment]
@Fruktlimpa Maybe medbay should start with more pills or a small cryo mix at round start to ease this if there is a bad player, or if there is no Chemist the HoP can give one access.

**Comment by Fruktlimpa** [comment]
Crates, medkits, and sleepers cannot AT ALL replace the need for chems. It will be extremely inefficient, time-consuming, and frustrating. 

@PJB3005 
No, they absolutely cannot. I can't believe you even said this since it is so wrong.

**Comment by kilozombie** [comment]
I was replying to Aceedex. I think it'd make sense if MDs had access to Chemistry if there were no chemists, but removing the chemist job entirely seems pretty bad.

**Comment by Gringonius** [comment]
>Are the MDs really "completely crippled"? Can't they order medical crates?

Unless you consider having to treat every eye and brain damage with slow surgery and also 30 cryox cryo tubes being the fastest way to stabilize and heal people in critical conditions not crippling, then they're not.

**Comment by Kammerjunk** [comment]
Medbay cannot run fine without chemistry, Christ what
Sleepers only work on people above crit. There are no first aid kits - or anything else from cargo - that give bicar. Even if it did, you'd have a few pills of the four _basic_ damage types done (with regular dex instead of dex+)
You can't even clone people without chemistry because even with the laughable 30u cryox beakers, that needs alkysine (and ryetalyn, but you can substitute for SEs, which also give tiny toxins, in a pinch)

**Comment by aceedex** [comment]
Medbay does not run fine without chemistry. at all.
christ sake's you wouldn't even be able to cure a virus without having to bust out the windows
it can be _manageable_ if things are slow with some things, but for example, brain damage and clone damage are absolutely 100% permanent without chemistry. Anyone who'd suggest otherwise is a silly person who doesn't play enough of it. hell, even now with extended access the term "wild ride" came into effect. imagine if you made that even worse by putting an arbitrary barrier.

@kilozombie you see, sec officers don't need the warden to set times for them. so it works out fine in that end.

**Comment by ghost** [comment]
From the comments I have seen here the basic argument against chemistry having its own access is:

"Its an important job shitters my screw it up so give the job to everyone just in case."

Does this sound right? Maybe chemistry needs some changes? I believe constantly giving extended access for the sole reason of "shitty" players screwing up isn't very good solution.

**Comment by Gringonius** [comment]
>I believe constantly giving extended access for the sole reason of "shitty" players screwing up isn't very good solution.

How so? When I played medbay often extended access saved medbay most of the time. 
Again, half of the issue I see Probe bringing up doesn't seem to be about medbay access at all but instead about chemistry being easy to break in.
>Chemists are muscled out by half the station walking in to replace them.

**Comment by ghost** [comment]
@Gringonius Well the best solution I have seen is simply making the chem dispenser chemist only so even if people break in they don't have access unless they get it from the HoP or some other means the coders might add in. People will stop breaking in when they all know it wont matter, though it is a shitty situation thats why Id like for there to be a fail safe in case there is no chemist not if there is a shitty one

**Comment by Gringonius** [comment]
I honestly fail to see how the current system is bad in any shape or form at this point.
Again I think that chemists should just be turned into an alternative MD title/starting equipment set.

And at this point I don't see why, geneticists, atmos techs and roboticists shouldn't get the same treatment either.

**Comment by kilozombie** [comment]
@Gringonius Because it's an awful idea. You need to split up responsibility somewhere, at some point, at least for most jobs. You're essentially saying every department should be only one job with a million responsibilities instead of a few different ones with different responsibilities.

**Comment by yclatious** [comment]
>make the most important tool in medbay, what governs cryo mixes and gives you the ability to get medicine for all 4 damage types, restricted to some of the most autistic players in medbay for no good reason
>Somehow, this ultimately bad change is better because you can also fix it by visiting the HoP, despite the fact that no issue ever came up from general access to the chem dispensers and indeed, said access has made medbay better, more efficient and more enjoyable

What the zog

Nothing has ever stopped you from being a chemist, why do you suddenly want for medbay to be dependant on chemists, which was never a good idea.

**Comment by PJB3005** [comment]
Ok I take that back but other than alkysine and bicard it's fucking fine.

If the round is actually so damn busy that having to actually spend a bit of time with your patients is unacceptable then just go to the fucking HoP already jesus.

**Comment by ghost** [comment]
@Gringonius Because for me personally its fun having many specialized jobs. I think everyone should focus on what their job is. I think more than anything Doctor's need a large change as they have come to heavily rely and Chemistry and Genetics. Most doctors I see now days will just shove Dermaline/Bicardine/Anti-tox down peoples throws and send them on there way or even worse will wait for critical patients to die and just clone/cryo them. I think the issue more lies with the doctors not being able have a lesser substitute for having a bad chemist or no chemist.

**Comment by Kammerjunk** [comment]
Alkysine and bicar, yeah. And clonex, ryetalyn, dex+, hyro/arith, imidazoline (as any small eye damage will have to be treated with surgery)
In the round that finally prompted this issue, the chemist, the doctors, and the medborg were all extreme autists about wanting to use the chem dispenser, to the point where I left for beakers and crates and came back a minute or two later and the chemist had straight-up quit and become an engineer. You're not going to cure autism by forcing the autists to play in different rooms.
@Secish The vast majority of medbay is chemistry and you can't fix people who only need a damage healed any faster than the reagents will metabolise. This is hardly a new thing.

**Comment by Gringonius** [comment]
>You need to split up responsibility somewhere, at some point, at least for most jobs.
>You're essentially saying every department should be only one job with a million responsibilities

This happens organically at round start in departments like medbay itself and science already or in engineering with just the engine at round start.
The issue here is that the jobs I've mentioned don't even need huge amount of time spent on it, work best coupled with the resources brought or made by the "main" jobs of their respective department and aren't even that crucial with the exception of chemist or atmos tech when there are lots of breaches.
Engineers who fix breaches are often checking if atmos pipes are working on their own instead of assuming that an atmos tech will show up to do just the pipes, scientists doing RnD often want mech syringe guns at the start and often gift themselves with mechs they easily build in robotics which is 3 seconds away from them, geneticists are never really missed and I don't think anyone misses the time doctors couldn't access cloning.

>I think more than anything Doctor's need a large change as they have come to heavily rely and Chemistry and Genetics.

How is this wrong exactly? Medicine and cloning are a huge deal with treating people and bodies.

>Most doctors I see now days will just shove Dermaline/Bicardine/Anti-tox down peoples throws and send them on there way or even worse will wait for critical patients to die and just clone/cryo them. I think the issue more lies with the doctors not being able have a lesser substitute for having a bad chemist or no chemist.

A chemist making medicine or a doctor wouldn't change a thing about this behavior. You want a complete change on the chemistry and healing system instead of access changes, advanced scan + chemicals and sending people out is just how our system works and doctors waiting for people on crit to die or killing them outright for cloning is entirely the player's own fault and not something that locking doctors from chemistry and cloning would fix at all.

**Comment by ghost** [comment]
@Kammerjunk What does "autist" mean in this example? The chemist was upset that everyone came in and tried to do his job for him before he could do it himself and was fed up.
And I know I said Doctors lack a lesser substitute, thus the need to break into Chemistry should the Chemist be slow or bad.

@Gringonius I personally think Doctors should have other ways to treat people than pills and a tube but thats just me personally. The pills and tube should be a harder to get but more effective treatment, again my opinion.

**Comment by Anton-Kr** [comment]
If anything this makes the wildride even worse. Having no chems as the only MD on is absolutely horrible.

**Comment by PJB3005** [comment]
@kammerjunk most of the things you listed aren't strictly needed and you're *fine* without them. Sure they're extremely useful but most are simply convenience and speed over the things medbay can get without chemistry.

**Comment by Kammerjunk** [comment]
@Secish "Autist" in this means that people entered chemistry because it was empty at roundstart and someone called out for people to get chemistry done over medical channel.
@PJB3005 You can't treat radiation without hyro or arith or waiting for all of it to become toxins. Regular dexalin only heals 1 per tick, which is not viable for when you actually need to heal suffocation damage. One first-aid kit contains either 3 kelotane pills, 3 anti-tox pills, or 4 dexalin pills, which you'll have to either turn into smaller pills or crush into beakers if you want to ration them beyond only lasting 3 people. It's not viable except in way lowpop

**Comment by kilozombie** [comment]
@Gringonius 
>This happens organically at round start in departments like medbay itself and science already or in engineering with just the engine at round start.

Sometimes. I don't know if it's the best way to balance the game, though. People enjoy being able to just do their own thing without having the expectation that (x) things need to be done. A roundstart engineer might hate doing atmos but feel pressured to do it if atmos techs didn't exist.

**Comment by KingofHONK** [comment]
I'll give my 2 cents because I'm a chem regular. 

Perceived problem: nobody plays chemist because you can be Med doc. And do the same job.

Actual problem: chemists job is easily completed in the first 10-15 minutes. Unless you're yred and then it's 5 minutes. There is no endgame. After that you are an orange doctor. The solution isn't to restrict content or cut content It's to create content.

**Comment by SangriaMonkey** [comment]
Before every basic boy had access to most of his department you'd see a whole lot more slamfucked windows and hacked doors if there weren't heads of staff willing to fill in. I don't think that trying to roll back this kind of thing is going to be very constructive.

The better solution would be to add a little more depth to chemistry, without completely fucking things over or making vital drugs even more of a chore to come by (a la goofchem).

**Comment by kilozombie** [comment]
Maybe someday there will be an endgame. I have an insider source that there might be something like that coming Soon (tm)

**Comment by Gringonius** [comment]
@kilozombie
>Sometimes. I don't know if it's the best way to balance the game, though. People enjoy being able to just do their own thing without having the expectation that (x) things need to be done. A roundstart engineer might hate doing atmos but feel pressured to do it if atmos techs didn't exist.

I also hated having people threaten my atmos tech for not doing the engine because he didn't feel like it was his responsibility to the point a new admin had angrily PMd me but that's life. As long as there's someone working on the important stuff I often rest easy and do my own thing.

**Comment by Fruktlimpa** [comment]
Do you not fathom how annoying it would be to work as an MD with no chems? 
Spend more time with your patients, you can do that fine with brute packs, blood bags, surgery, and other shit, we don't need more annoying things? NOBODY is going to be happy about having to do surgery to fix eye damage or brain damage or always having a clean SE injector lying around(Which would be exactly the same as Rye)

I repeat, medbay cannot function to any decent degree without chems. Nobody in game is going to be happy about a medbay that works without chems. Everyone will be frustrated about it, why do you believe this would be positive for the playing experience?

**Comment by kilozombie** [comment]
@Gringonius 
That's fair. I don't think it's the worst thing like I initially said, but I still think it's against some of what makes spess fun to me, and seems like a slippery slope to having fewer and fewer jobs with more and more access, when in reality SS13 is a machine with many interlocking cogs (jobs).

**Comment by KingofHONK** [comment]
Another note on the chemistry content in general: just as an example for an idea that would make chemistry more attractive is to add a research component similar to that of genetics and virology: add new chemical reactions that complex and unstable in nature that are RNG based, but have strong benefits to medbay as a whole. A pill that could mend broken bone and save precious time from a surgery. You could even add traitor elements and make some strong antag pills as well. 

I know that you say "when you code it" when shit like this is brought up but cutting content or as it seems to be called "balancing" is not the right answer and is frankly lazy. I stopped playing chem as much as I used to because my job ends in 15 minutes. Experimental drugs and shit would be so fucking cool to have and give me something to do after the mix is done.

**Comment by ghost** [comment]
@Fruktlimpa Maybe as I have said before Medbay should be changed to not be so reliant on Chemistry. The way you want things sounds boring. Why dont we just remove chemistry completely and put the chem dispensers in the middle of med bay and let the doctors deal with it. Or just remove miners and let the science shuttle go to the outpost and let them get their own supplies?

**Comment by Fruktlimpa** [comment]
@Secish 
What the hell do you mean boring? Do you find the current medbay system boring? Because it is how I want it to be.
Chems and medbay are deeply intertwined, you would have to redesign a lot of things if you want doctors to work well without chems. 

Out of curiosity how much do you play medbay? Because there are already a few people in this very issue that doesn't know jack about medbay but still wants to change it up like they know how it works and it is extremely frustrating.

**Comment by ghost** [comment]
@Fruktlimpa At the end of the day I just think Chemists should have a fair shot at doing their job before everyone else in medbay jumps in and does it for them. Which is hard to do with so many people hardcore powergaming wanting the tubes filled and fridge stocked within 2 minutes or they are coming in and doing it for you.

EDIT: Also I have played medbay a lot and have felt the pain of having no chemist which is why I don't like relying so fervently on chemistry or Genetics. Doctors should have something very basic to get them by if there is neither.

**Comment by luzzgawr** [comment]
if they had more of a job than 15 minutes of pressing memorized buttons then it wouldnt be an issue.

**Comment by despotate** [comment]
Can you perform all of chemistry without moving from your seat? I get the feeling the job is so routine that you could automate all of it by using an autohotkey script.

**Comment by Kammerjunk** [comment]
Assuming you have plasma near you, say 5u in a small beaker in your pocket, and not counting running out of energy in the chem dispenser, yeah, but don't do it

**Comment by despotate** [comment]
I'm not gonna implement that idea, it just illustrates what the job really is: the exact same routine of button clicking every time.

**Comment by kilozombie** [comment]
Again, insider info, chemistry may receive some new reagents sometime soon, but until then... yeah.
I used to main Chemist for many many hours and basically the only fun part was making drugs by mixing existing reagents in specific amounts. Doing the 15 minutes of autism at roundstart? I never did that, especially on servers where it wasn't the norm. It's just a slog.
On /vg/ I played CMO and basically after chemistry is done nobody wants to touch the room unless they want fun chems.

**Comment by despotate** [comment]
> chemistry may receive some new reagents sometime soon

Oh boy, more clicking!

**Comment by PJB3005** [comment]
@despotate If I wanted to I could literally make an automatic script do all of chemistry for me as fast as my connection allows me to. It's all BYOND macros and hrefs.

**Comment by kilozombie** [comment]
Actually, you'd get certain ingredients for the reagents from outside of Medbay, and others would require a lot of micromanagement with tons of different reagents meaning you need, like, pill bottles and organization and shit and can't just make it in one beaker.

**Comment by ghost** [comment]
@despotate this entire game is clicking, what are you going on about?

**Comment by despotate** [comment]
Most of the clicking in this game has variety, RNG, or involves other players, who are unpredictable and fun.

Chemistry is literally the exact same stuff every time. Adding more reagents just makes _the list_ of buttons to click longer rather than more interesting. edit: I wrote this part without having read kilozombie's reply

@kilozombie Your ideas are good.

**Comment by ghost** [comment]
@despotate how is R&D any different? How is surgery any different? its just clicking on someone or something in a specific order every time.

**Comment by kilozombie** [comment]
I don't know what to tell you @despotate 
An entire chemistry research system is a big old WYCI and I'd rather have interesting expansions to what we already have. What if Chemistry had to team up with Botany for some good meds? What if Chemistry had to grind strange items for some good meds? What if Chemistry had to go through immense effort and think-tanking in order to make the toppest tier of meds?

**Comment by despotate** [comment]
Yeah @kilozombie I just read your ideas and they're what I had in mind for breaking the monotony of chemistry. I'm just saying that adding more reagents to the chem dispenser doesn't fundamentally solve the problem, but obviously that's not what you're going for. Honestly, if I wanted to maximize fun, the first thing I'd WYCI is remove/cripple the chem dispenser and make its reagents something you have to find/get supplied elsewhere. But that's none of my business, I don't look at or play chemistry.

@Secish R&D also has the same problem as chemistry, you can macro the entire thing because there's no actual variety or fun involved in the "set up" time. Surgery is a bit less so because you're racing against time, often working with incomplete information, and most patients all come in with different injuries. A lot of departments have start-up overhead that's really boring and needs to be replaced or cut out.

**Comment by kilozombie** [comment]
My favorite times playing Scientist were when I knew almost nothing about the job on a different serb and thought I'd have to steal/"borrow" shit from everywhere in order to get the right research. That was fun, but R&D is already currently unreliable. A lot of rounds will end up with no research being done, despite it being easy, just because it _is_ monotonous.

**Comment by jakmak3** [comment]
As it stands now with our server culture and the current way chem is trying to make chemistry restricted to a total of 3 people on station (2 chemists and the cmo) would mean the wild ride would become even wilder. Our chem system is very simple and streamlined in comparrison to other codebases. Making a simple chem to heal all forms of tox damage no strings attatched (anti tox) requires 3 button presses to mix 3 chemicals from the chem dispenser into this basic healing chem. Cryo mix which is very usefull and rewarding you could argue being the most valuable of all chem mixes while being the most complex takes under 5 minutes to make enough mixes to last 2 cryo tubes for well over 2 hours. In our chem the MOST complicated and autistic chem is medical/combat nanobots which are the most powerfull chem in the game and rightfully so. It requires cooperation from robotics, chef, miners, and someone with a chem machine + grinder and a huge amount of managing several individual chems to produce a tiny amount of a ultra powerful chem capable of healing any damage quickly and effortlessly. The only other complex chem is rezadone (which isnt very good) and rezadone and that is only because it requires carpotoxin which come from hostile mobs which spawn from a random event OR has to be autismed up from one of the few odd ball sources from across the station.  To sum it up we have a simplistic chem system designed for LRP codebases. The 2 alternatives are full goonchem and goofchem which goonchem while not inherently bad has its own balancing issues and simple healing chems take upwards of 6 steps if not more to make from scratch while goofchem is a complete and total mess of a system that attempts to reach a middle ground and fails. The big problem with both being that they need a full time chemist to sit there for half a hour and press buttons in order to have a semi well stocked fridge and a adequate cryo mix. Good for codebases with a little more RP but for somewhere like us it would not fit. Locking down chem with baychem would mean someone has to manually pick a shitty job that no one likes and sit there and push buttons for 10-15 minutes to fill the chem fridge (which lasts up to 3 hours) and make a cryo mix (again lasts 2-3 hours if done not retartedly). No one would bother to be a chemist for that alone and would just be a another issues of not having access to do the proper job in medbay gimping them like paramedics are gimped now. Not to mention the playerbase is use to the concept of doing whatever job you need done yourself instead of cucking yourself to have someone sit there and do a job you can do yourself much faster than they can. Like how engineers do atmos tech jobs (optimize distro, cool plasma, fix pipes), Vice versa (atmos techs setup engines, fix breaches/cables, and general repairs), robotisists do r&d and scientists fix the borgs and all have the access to use the borg console. Its a matter of when YOU do it yourself instead of asking another to do it. This behavior extends itself to the meta of when you want a feature the common response is WYCI. The culture here says YOU do your own job instead of bothering someone else to do it for you. Trying to implement reduced access for all would just result in r&d not getting done, chem fridges being empty 24/7, cryo has the stock 30u cryox, chef out of ingredients to grow food, and a immense amount of break ins happening ( and people getting arrested/killed/banned because of it) much much more. In the end it would not at all benfit anyone if access was stripped and only result in people doing their jobs less along with a lot more break ins.

**Comment by Kurfursten** [comment]
@Skullyton @Probe1 I would be interested in seeing it be a toggle available to command staff. The captain can currently unrestrict maintenance access at any time he wants from the command console, as if it were a radstorm. It would be interesting to see the command staff have available some options such as

* Skeleton Crew - Current access
* Stable Crew - Pre-Badclown access
* Emergency - Security has increased access

etc

**Comment by Probe1** [comment]
That was an idea I wished for a long time ago and it would be nice to see it implemented in that way.

**Comment by nuklearcellphoneg** [comment]
Y e s

**Comment by nuklearcellphoneg** [comment]
Ideally though, maybe if there are no chemists/cmo, then it all should have access, if that's possible.

**Comment by nuklearcellphoneg** [comment]
Overall though, I think too many people have way too much access... why does the Clown get maint?

**Comment by Probe1** [comment]
that's actually a rather good question and one I don't have an answer to.

**Comment by ghost** [comment]
There has been a bit of access inflation/powercreep over the years. Should we tone back on it? Maybe. But I think that honestly MDs having access to chemistry is a massive improvement to the medical bay, so this, if nothing else, should stay.

**Comment by Fruktlimpa** [comment]
The reason a lot of chemists stopped maining chemist is not only because MDs started muscling them out. Like a lot of people have already said, chemistry has no end game at all and is very quickly done with and it takes a while for it to be needed again, which causes the issue with chemists fucking off or only new, inexperienced players taking on the role.
The role is fundamentally flawed yet it is vital for medbay, restricting it will cause asshurt on all sides.

If you are serious about doing this then at least implement the "No chemist, MDs get access" function because otherwise it is just going to be a pain having to ask the HoP or hack in every other round.

As long as there is a chemist I let them do their shit, they are rarely good but I don't muscle them out for that. But lo and behold, the ones that are shit end up ditching medbay ASAP so in the end I am usually the one who has to do it, only delayed.

Can't we just crack down on MDs who doesn't give the chemist a chance?

**Comment by uazuaz** [comment]
i'd like to see the chemistry job modified to be more varied; you could have some chems removed from the chem dispenser in a a way that you can obtain important medicines that are not available at round start with a chem dispenser alone, and chems not so important using other additional tools;
for example i never understood why there is not a proper tool inside chemistry to electrolyze chems, a tool that does automatically the same job of an electrolyzer + centrifuge would be nice.

also, reminder that there are never used bottles and pills of inaprovaline and antitox readily available at round start on the chemistry desk, they could be used for missing chems, something else could be added to be used with such hypothetical electrolyzer maybe.

http://greendotbd.com/wp-content/uploads/2015/11/water-electrolyzer-test.jpg

https://c2.staticflickr.com/2/1003/1107331492_c8cfc53500.jpg

www.radleys.com/sf_images/default-source/Products/parallel-reaction-stations/w9-department-product-montage/w9-parallel-reaction-stations.tmb-large700.jpg

**Comment by Aurx** [comment]
@Fruktlimpa 
>Can't we just crack down on MDs who doesn't give the chemist a chance?

That's not an administrative issue, and making it one would be a major inversion of policy.

**Comment by kol1th** [comment]
I think it's fine the way it is - If there are chemists, the doctors bugger off, and if there aren't, the doctors can do chemistry without jumping through a few extra hoops.

In the end, however, it only takes around 5 minutes (or less) to get a very serviceable fridge and cryo mix done, but I think that's a separate issue on its own. 

As a chemist, if people actually feel like the doctors muscle them out or tell them to get fucked so they can do chemistry instead, I don't think they play the job very often. I've played chemistry quite a lot, and typically the first thing that happens roundstart is people asking "Hey, you got the mix and stuff?", which is far from taking over. Hell, I've had captains and mechanics just barge in and kick me out to get their GIBSMEDATS out of chemistry. 

If a system were to be implemented, where doctors would get access if there are no chemists, that would be fine by me. As is, it wouldn't change much other than doctors barging in to not say any words and make chloral or whatever other flavor of shitter juice they want.

**Comment by Probe1** [comment]
That doesn't actually happen in game.  If there are chemists doctors make the chems they want.  If there are not chemists doctors make the chems they want.  

You can't say it happens how it was intended to happen after 2 years of empirical evidence that if you give someone access, they will use it.

**Comment by Aurx** [comment]
>If there are chemists, the doctors bugger off, and if there aren't, the doctors can do chemistry without jumping through a few extra hoops.

That's not at all how it works.  If the chemist made the exact thing the doctor in question wants, the doctor will grab it from the fridge without a single word and bugger off.  Otherwise the doctor will barge in without a single word and make his chems and/or call the chemist shit.  
This goes triple for cryomixes, especially such highly opinionated cases as "Rye in pills, not in the mix".  I've seen two doctors get in a beakerswap fight over that.

**Comment by 9600bauds** [comment]
> If the chemist made the exact thing the doctor in question wants, the doctor will grab it from the fridge without a single word and bugger off. 

On a good day. Sometimes doctors barge in and start re-making all the chems that are already well-stocked in the fridge, and they will do so in slightly different dosages or with slightly different pill names, and I don't understand it.

And yes just fucking forget about people with access asking things of you instead of barging in. Special shout-out to the all-access HoP that loves to beeline right in and get his hyperzine fresh off the dispenser, because the pills in the fridge are stale.
