### ISSUE TITLE
Job objectives, except possibly not dumb

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#13227]
## So what's wrong with the unimplemented job objectives?
 - They try to be succeed/fail objectives. They do this because they have associated money payouts.
 - Because they are succeed/fail objectives, they must be *quantifiable* by the game, meaning that they're basically just job performance objectives.

Those things are not in and of themselves bad, but I think they fail to encourage *roleplay* which is what I think makes spess fun. Obviously I mean roleplay in our light RP flavor, but muh greentext stories and muh IC justifications are what I think myself and other players have the most fun with.

## So what could a better job objective system do right?

*Unquantifiable suggestions instead of rewarded succeed/fail job objectives.* Each player would get one of these. Examples (not intended to be examples of GOOD objective suggestions):

 - **Assistant:** "You joined the station in order to be trained in X department. Try to learn as much as you can before the end of your shift." 
 - **Captain:** "When the shift ends, leave no man behind."
 - **Security officer:** "Try to make more arrests than your fellow officers." *Could be an administrative issue, but shitcurity would probably be shit with or without this suggestion.*
 - **Xenoarchaeology:** "Discover at least one beneficial large artifact before the end of your shift." *This one might actually be bad, because it's job performance and not roleplay direction, but asteroid roles and encouraging roleplay is hard man*

Technical stuff:
 - Weighted list of random suggestions picked at round start based on job/department. Unique to person.

This is a discussion issue because:
 - Feedback. Wooooo.
 - The implementation of this is actually really, really easy. The hard part is thinking of **GOOD** objectives/suggestions, and enough variety of objectives per department. So leave comments with objective ideas if you think this is neato.

That was a lot of typing.

**Comment by Probe1** [comment]
I don't see anything wrong with the idea.  It's more a matter of getting someone to do it.

**Comment by gbasood** [comment]
literally just a weighted list
easiest thing in the world to implement
hardest part is thinking up objectives
even newcoders could do this

**Comment by Ephx1** [comment]
I can already tell you that Assistant one, even being unquantifiable, will never be done because only people who want to fuck around or break shit play assistant.

Some ideas I can think of:
Stock your library with x amount of novels
Upload x amount of newsfeed updates
Clean up x messes (practically already a thing)
Build x mech
Get x research level
Get x slime
Get x amount of activated blocks
Cook x meal/cook x amount of foods
Ship x amount of crates 
Get x amount of money (Miners)
Get x amount of power
Grow x plant with y potency
Send x faxes
Create x amount of """HELPFUL""" pills
Scan x amount of machines
Create an extra x machine

I'll think of some role play oriented ones in a bit, but I'm sure you can rework the above to make some, like "Make someone's favorite food"

**Comment by gbasood** [comment]
@Ephx1 fucking hell dude did you miss EVERYTHING I TYPED where I said "unquantifiable"
I'm not looking for measurable job performance things
Measurable "I did this X times" during round is not roleplay-oriented
I'm literally aiming for the sort of thing that can't be measured via code because those things are boring, which is why traitor objectives, which are exactly that, are things people just straight ignore

**Comment by Ephx1** [comment]
I know, but you're really asking to push role play on a server who's players see each other as NPCs? It's a ridiculous thought to even conceive of it.

**Comment by gbasood** [comment]
They are entirely optional and no one has to do them.
I'm not pushing anything on anyone.

**Comment by Ephx1** [comment]
OK so, if they're optional, unquantifiable, and most people won't do them.
Riddle me this, why even have them?

**Comment by Exxion** [comment]
To ENCOURAGE people to do interesting shit

**Comment by Ephx1** [comment]
A piece of text isn't going to encourage anything. If anything having 20 ideas to do pre-made will only encourage the same thing over and over.

**Comment by Exxion** [comment]
>A piece of text isn't going to encourage anything.

So... why do we have antag objectives?

**Comment by Ephx1** [comment]
Honestly I don't think we should. But antag objectives have the bare minimum of "GREENTEXT" as a big "I WON!" to tickle someone's brain. Which, those objectives always encourage the quickest and easiest way of getting, over and over.

**Comment by gbasood** [comment]
I guess I'm not sure what your argument is then.
Should we do away with all text and just make spess an arena?

**Comment by Exxion** [comment]
Alright, at least you're consistent

You're right, the job objectives probably wouldn't have much effect, but adding them wouldn't require much effort at all and (unless they're REALLY BAD) couldn't hurt

**Comment by Ephx1** [comment]
If anything it should be a big wiki page to allow anyone to easily edit for lots of ideas.
@gbasood how the hell did you get that from anything I said?

**Comment by gbasood** [comment]
I'm a bit confused is all. I realize in review that what you want is quantifiable objectives.
And hey, we can *also* have those. But I think they do a bad job of bringing out the best qualities of /vg/ spess.
And also, whoever wanted those bad enough to outline some of them never actually implemented them.

**Comment by Ephx1** [comment]
I think having something quantifiable will at the very least push some people for that sweet dopamine hit when they see the green. Something truly entertaining regarding role play should come from what you yourself want to see, and yes I can see the idea behind wanting to encourage this behavior but I don't think many will bother. If you don't want to roleplay in the first place, chances are a cool idea won't spark anything.

**Comment by Ephx1** [comment]
I probably shouldn't have sperged as much as I did. I'm sorry, I'm just tired of role play encouragement that goes nowhere, especially in a goal oriented system. I still think it would be better in an informative instead of challenge medium. What about that "News" section in PDAs? You could easily slip in a "DIY" section.

**Comment by gbasood** [comment]
I don't know, I feel like that'd be entirely forgotten about. Basically hidden away. Same with wiki

**Comment by icantthinkofanameritenow** [comment]
@Ephx1 has a point. The way our server works, people simply will not wish to RP if they do not want to unless they have either a reward for doing so or a punishment for refusing to do it.  Greentext serves well enough as a "carrot", since it encourages antags to actually do stuff instead of hide away for half the round.  By contrast, the Vox Raider Inviolate is an example of a "stick", in that if you don't follow it you risk a jobban- but in this case that wouldn't help at all. 

In light of the above, making job objectives quantifiable for greentext purposes is your best bet. Otherwise they may as well not exist as far as players care.  By all means put job objectives in, but if there's no greentext (or better yet, a concrete reward like a cash bonus or something) it will be just as ignored as the wiki's "job objectives" are now. You said adding ones that aren't quantifiable "couldn't hurt", but I say they definitely won't help in encouraging RP. Aim higher than that. 

@gbasood 
Then have it pop up at the round start and then make it visible in the notes, like an antag's objectives. Granted, that won't stop people from not giving a shit, but at least people will notice them. But overall, the basic premise is flawed: you simply cannot "encourage" people to RP. It has to occur naturally and willingly, and people will just resent it if you try to coerce it out of them. A better way of going about it would be to interpret more RP-friendly policies (though this would itself threaten the light-RP status; can't have it both ways), or by providing benefits for good RPing either via cash rewards, greentexts, trophies, or other things that might make someone want to RP when they would normally not care about it.

**Comment by jknpj** [comment]
How about some kind of shuttle coming from centcomm from time to time with rewards  if you complete your "work objectives"?

**Comment by icantthinkofanameritenow** [comment]
@jknpj 
Reasonable enough, though that should be done in a way that doesn't require admin intervention to carry it out. Fluff it out as a work quota NT wants the crew to fill and you're good.

**Comment by gbasood** [comment]
I thought about that idea but I felt it was too reliant on mining actually doing their job, but I guess I was thinking about it in a "make shit for us" context

**Comment by ComicIronic** [comment]
I think the reason antag objectives are win/fail is because that kind of objective is much more effective in making an antag who has no ideas do something. Being told to "set up a bomber gimmick" requires a lot more familiarity and originality than "go jack this guy's thing", because you know when you've done the second one properly.

**Comment by gbasood** [comment]
Another thing I/we could do is add a suggested objective and quantify it via player vote on the match's page on the stats server.
Goonhub has a similar vote system for their ticketing system
