### ISSUE TITLE
Leaving a long AAC script running causes an ungodly amount of lag

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#13287]
Recently, an AAC script that disabled all (or most) of the pressure checks on station began seeing some use.

While you can set it to run and disable it immediately after to disable all the pressure checks in one swoop, leaving it running will I guess constantly attempt to disable all pressure checks. This causes an immense amount of stuttering for almost everyone involved that makes it an absolute pain in the ass to play with.

**Comment by jknpj** [comment]
Since the default freq of all vents is the same as the default freq of the AAC i think even the AI can do it efortlessy, too. Really exploitable and testing it locally skyrocketed my ping from 10ms to 83ms

**Comment by Kurfursten** [comment]
Instead of a simple not running / running toggle, we should have an "execute" button (which is what most people want, issue a change one time, such as for an SME or in this case, to fuck with loads of air alarms). I would say in 95% of cases, you don't need the script repeating every tick.

We could also bury a special repeat operator in the menu somewhere to give it the original function for scripts that need to run on repeat (such as ones that regularly check gauges then take an action).

**Comment by BobdaBiscuit** [comment]
You could also do what NTSL does and kill scripts that are repeating too much and causing lag.

**Comment by PJB3005** [comment]
> You could also do what NTSL does and kill scripts that are repeating too much and causing lag.

Now if only this worked in practice for NTSL.
