### ISSUE TITLE
Materials.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#13380]
We have a material datum system but it's more some counters for abstractly storing material amounts of a set list of minerals than actually having meaningful materials.

On bay and goon and such on the other hand, a lot more things have materials incorporated. You don't just have a table, you have a steel table, etc... This is really cool and it opens up a lot of flexibility and personally I think materials are a better way to handle upgrades than flat part upgrades.

On goon you can literally combine Uqill, a very blast resistant crystal, with Fibrilith, a sort of cloth-like "mineral", To make blast resistant cloth. Now make a jumpsuit out of that. You can make rainbow coloured floor tiles. And jumpsuits. And chairs. And toolboxes. You can make plasma chairs which produce plasma gas when sparked. Hide some in the bushes and run around spamming RCD sparks for !!FUN!!

The problem is our materials system isn't exactly laid out to handle this. At all.

Now the question is, how do we make a system like this here?

**Comment by Kurfursten** [comment]
Since byond can't extend more than one parent, you'd need atom level procs for material types so that anything made of, for example plasma, could do plasma behaviors (e.g.: make plasmagas.

If you wanted to make it happen, you should first create a design doc with a list of all materials and alloys you want to be available, then assign properties to each.

**Comment by N3X15** [comment]
While BYOND can't accept multiple parents, you can do something similar with component-based design.  See: Unity MonoBehaviors as an example.

Instead of hardcoding material A + material B = material C with both hardcoded properties, you can do:
```
/material/A
  /InitComponents()
    components = list(
      /mateffect/A
    )


/material/B
  /InitComponents()
    components = list(
      /mateffect/B
    )
```
When you combine them, just dump their combined components together.

This is similar to what I'm planning to do for chemframework 2, which would outwardly work the same as before, but with component-based backend for less duplicated code.

**Comment by PJB3005** [comment]
Yep components.

Honestly I'm tempted to code a legit ECS in BYOND.

**Comment by ghost** [comment]
Masterwork gold-plated bananium-encrusted silver chairs soon?

**Comment by N3X15** [comment]
Now a work in progress, assigned to Components project.

**Comment by MadmanMartian** [comment]
looks like it could be fun
