### ISSUE TITLE
Remove fake newscaster channels

### ISSUE THREAD

**Issue by Lokiamis** [d3athrow/vgstation13#13404]
They're not interesting, nobody reads them, they condition players to ignore newscaster beeps, and they make newspapers worse/less likely to be used because you need to click past them to get to player-made content.

**Comment by gbasood** [comment]
[Feature Loss Request]

**Comment by despotate** [comment]
If a feature gets removed and no one was ever aware of it, does the thread make a complaint?

**Comment by SysadminJeroen** [comment]
Just have Admins post more shit on it.

**Comment by Probe1** [comment]
We won't.

Feels good to say that but we won't.  I'm probably the most active user of it and I've used it maybe 10 times total.

**Comment by despotate** [comment]
It's kind of a shame that newscasters are so little used when they provide a good departmental alternate media outlet to the radio, where your messages get lost after 3 seconds. It's convenient for long-term news, like what viruses you're releasing as a virologist, as an example.

**Comment by SysadminJeroen** [comment]
Perhaps automatically submit stories to one of the two news channels? Could report on habbenings or it would announce a meteor storm two minutes before the random event actually triggers, or other random events.

**Comment by Ephx1** [comment]
Do they even update anymore? I can't recall them having their few pre-made stories in the last few months at all.

**Comment by SysadminJeroen** [comment]
The PDA has pre-made stories, in my opinion the news caster should randomly pick one every hour or so.

**Comment by Exxion** [comment]
The newscasters still had the pre-made stories last time I played. They're just really uncommon.

**Comment by mrpain666** [comment]
FAKE NEWS

**Comment by mrpain666** [comment]
Are these the empty channels that literally have no content in them at all and start at round start?

**Comment by Exxion** [comment]
Yes
They do, like once every five or ten rounds, get a story at random

**Comment by despotate** [comment]
Yeah, the Gibson Gazette and Tau Ceti news something. They do however add stories to themselves occasionally, usually along the lines of the spam messages that one receives on their PDA.

**Comment by despotate** [comment]
I don't like them because, as OP says, they condition people to ignore newscaster beeps when newscasters, in my unexperienced opinion, are a great way to distribute long-lasting, important, department-wide information. Right now all that's used is the radio and it tends to be flooded with spam and any messages you send through it are gone after a few seconds.

My idea for how newscasters would work is that all departments get their own department-exclusive channel set up at start so they can easily relay any long-term information to others. It's why I like setting up newscasters as a warden to tell people who got arrested, or as a virologist to tell people what viruses are gonna come out and when.

**Comment by mrpain666** [comment]
Either re work them to get more stories and be more relevant, or remove them entirely, yeah, I can understand that.

**Comment by west3436** [comment]
These should be reworked, not removed.
