### ISSUE TITLE
Security Progression During Cult

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#13445]
Cult is a very progression-based game mode that rewards not fighting security head on, instead building elaborate dens and sending waves of juggernauts and manifested ghosts at the security team. Unfortunately for the 'protagonists', even if the sec team successfully raids a hideout, they gain little but to flush survivors to another hideaway. Worse, hideouts can be on different Z-levels entirely.

One idea I had to remedy this and would like to discuss is a concept called "blood residue". Basically, every time security destroys a rune on the ground or a manifested ghost or juggernaut, varying amounts of blood residue are dropped. Talismans and _maybe_ tomes could also be destroyed at a machine for residue. This would mean that security can receive tangible rewards for successfully raiding a cult base, or defeating a wave of cult's ghost slaves. Not to mention it would mean that manifested ghosts and constructs need to be used more wisely to avoid feeding security (similarly, holding a bag of 42 talismans across 6 boxes is a liability).

Residue could be redeemed at a machine for various quantities for things like

**Low End**
* Bottles of holywater
* Runic compass (One or limited uses. Rather than point in a direction, gives an idea of where the cult is setting up a base. "Very Hot" if there are runes on the less accessible Z-levels, "Hot" if there are runes on the mining asteroid or in a Space area on Z1 like in a room built in space outside the station, "Warm" if there are runes but none of the above, "Cold" if there are no runes)
* Rune decipherer (To read what a rune does before you smash it)
* Reality Measuring Stick (Warns you if the current cult objective is Summon Nar-Sie and someone has drawn a Summon Nar-Sie rune - probably too late to stop the ritual or even code red at this point, but any early warning at all could be a relief)
* Armor of God, Ephesians 6:13-18
* Null obelisk (in essence, a structure object that is cumbersome to move around and can't be used as a weapon, but disables runes and talismans in a wider area than a rod, perhaps requires setup like an emitter - wire knot and wrench/weld)
* An extra null rod
* A hypothetical paladin-based cyborg module conversion board
* A method to ordain a new chaplain (set their mind's job to chaplain, allowing them to bless)
* Some desperate-last-chance weapon capable of killing Narnar if he is summoned

**Arbitrarily High End**

And of course, like a vending machine, it would be trivial to limit how many of an item could be purchased. Since none of these things could be acquired before getting blood residue, there would be no way to metagame (like grabbing a runic compass every round just to scan for warmth).

**These are just rough ideas, but I think you get my point. Maybe you think security progression is a bad idea, let me know if so. Better ideas for loot? I want to hear that too.**

**Comment by Aurx** [comment]
There needs to be a good counter to "sit in a room in the middle of nowhere spamming manifested ghosts" or that needs to become infeasible.  Right now there's basically nothing you can do about it but evac or hope somebody stumbles across the ghostlair, and if it's on the other side of a teleporter you're plain fucked.  

Research really should stop being a thing.  It's makework that cripples the cult if nobody does it.  I think a week or two of tomes spawning with full words would be a good experiment to see what impact it would have on balance.  

>Some desperate-last-chance weapon capable of killing Narnar if he is summoned

Nar-tan should be the end, period, fullstop.  If he's summoned the cult's won.

**Comment by Kurfursten** [comment]
I understand your sentiments by saying if Narnar is summoned, the cult has won, but if that's the case, it would be nice if that would end the round instead of resetting the shuttle timer to 10 minutes so you now need to sit through 15 minutes of harvesters killing the last 3 people on the station. If the round is officially over from a gameplay standpoint, there's not really any reason to wait a quarter hour for the next round.

**Comment by Aurx** [comment]
Narsie sets it to 3 minutes ETA.  

I feel the 8 minutes of narsie serve to let the cultists revel in their victory while letting the non-cultists try for survivor bragging rights.  Would be easy enough to hold a server poll to see how people feel about the idea of just putting a banging donk on it 30 seconds after narsie.

**Comment by Kurfursten** [comment]
Ah, I see, Sprok changed that a couple months back, that was a good move. Before then, it was a staggering 15 minutes factoring in the docking and travel time.

If you want to let people try for survivor bragging rights (which I think is a legitimate reason to let the game continue, don't get me wrong), don't even call the shuttle. Send an announcement that the emergency pods will launch in 2 minutes (as though the shuttle had docked with the station). 120 seconds is about the limit of what you could be expected to hold out against the harvester swarm for without being overwhelmed.

**Comment by yclatious** [comment]
Why not make it so that in the presence of a cult, deconverting a cultist by direct or indirect means would give the chaplain favour with whatever deity he is worshipping currently and make it so that those items would be obtained by using his holy book and "purchasing" them. The chaplain could also do some sort of holy rituals to grant a sec officer immunity to runes like a rod does, or grant them protection from cult weaponry.

In case of the chaplain going down, just make it so the sight of runes inspires the sec officers to zealous hatred and make them able to also get gifts upon deconverting or killing a cultist.

**Comment by Kurfursten** [comment]
Sure, just a couple days ago telescience was decked out in some eight or so runes, complete with juggernaut factory

**Comment by Blithering** [comment]
A major problem with cult rounds is when one or two members get busted early, resulting in the whole thing never getting off the ground and cultstended happening. Giving sec officers more toys to deal with cults would only make this happen more often. That said, I still advocate making the chaplain's null rod into a single use immovable rod when narnar rises.

**Comment by Kurfursten** [comment]
Sure, but I think that's the beauty of having progression based on rune destruction and the like. In a failcult where they never get off the ground, security basically gets no toys at all. But if they bust up a ton of ghosts and runes because the cult is organized, they get a bunch.

**Comment by Blithering** [comment]
I find that if security is getting a lot of confiscated cult material and busting hideouts, it's seldom because the cult is doing well.

**Comment by Kurfursten** [comment]
The more runes, ghosts, and constructs a cult has, the less likely it is to be "busted early" and "never off the ground". One rune here or there, sure, but if they have a developed base with travel runes, talisman factory, construct factory -- that's off the ground whether they make use of it or not.

**Comment by Blithering** [comment]
The trouble is the sort of person that sets up that kinda base almost inevitably does it on a remote platform out in space that security never has a chance of discovering, the most common things that would get found and destroyed would be the basics: starting papers, tomes and convert runes.

**Comment by Blithering** [comment]
Maybe instead of a machine in sec that processes cult items, have the chaplain able to bless common detritus of a well set up cult into holy versions. Like ectoplasm could be blessed into some form of holy powder that heals, or can be thrown at a construct to stun it, or block it's abilities for a duration. Maybe also blessing cult swords into less spoopy versions to fight mano-a-mano.

**Comment by Kurfursten** [comment]
I agree that it's a problem - maybe you can help me iterate on the compass idea until we find something that feels fair to everyone and also encourages on-station cult activity

**Comment by Allspice** [comment]
Oh that was my base thank you for noticing me.

Anyway, the jugs were just to defend my hideout from any sillycons that were attempting to breach it, since I deaded most of security earlier on. But more relevant: Giving sec upgrades for confiscating tomes and talismans is another way to say you're punishing the cult even more when the skilled duders are caught, moreso than the brain drain already does. People already get frustrated and angry when they're converted and sent on their way without a tome, but if someone gets caught with a box of seven tomes to hand out to converts, well you'd be punishing an attempt to prevent that sort of impotent converted cultist. Which seems bad to me.

**Comment by Blithering** [comment]
One nasty idea for making the infinite manifested ghost factory counterable: Blessed weapons also deal a portion of the damage dealt to the summoner when attacking manifested ghosts.

**Comment by Kurfursten** [comment]
@Allspice I don't think that's a problem. You're not punishing the cult for making talismans, you're punishing the cult for making too many of them and then getting busted. They have to make a gamble if they're good enough to make tons and not get caught, or decide if they just want to make a few and be less risky. If you don't do it this way, you end up punishing all cultists, like Blithering said -- Sec doesn't need a buff against cultists who can't make talismans and bases.

**Comment by Blithering** [comment]
Veering slightly off topic, but the major gripe i have with cult at the moment is how make or break the tome is on the cult's activity. There's no guarantee you'll be able to contribute in any meaningful manner when you're converted, as you cannot say for certain whether you will receive a tome, either through negligence or just not having the words for summoning a new one yet. It also means people are loathe to ditch their tomes when the heats on, leading to a lot of avoidable captures. 
If cultists were given an innate tome summoning ability that had a reasonable health cost but required no rune, you could guarantee a new recruit would be able to contribute, and also losing your tome would not be nearly as much of a handicap, so people would be more likely to dispose of them for sec to recover and possibly smoosh into anti cult goodies.

**Comment by Kurfursten** [comment]
Sure, I'm not dead set on having tomes reward blood. Honestly, tomes aren't really a "high end cult" item anyway.

**Comment by Allspice** [comment]
Additionally, there's two other things off the top of my head. Keeping a good supply of talismans on hand is more a matter of time efficiency than being super buff. I COULD only keep 2-3 on hand at any given time then re-imbue more whenever I use a paper, but that'd slow shit down a load. And when I hear complaints of cult being noaction for the longest time, I don't think it's good to make it even slower.

Furthermore, punishing cultists for using their toys (or getting caught with them I GUESS) just means they'll opt towards using plain jane traitor techniques, making them less special. Instead of spooky constructs and "elaborate bases," you'll get silicunt subversion and cargo eguns. Subversion and eguns and chloral are definitely viable and strong but we should encourage cultists to use their unique strengths instead of goading them towards the typical shit.

**Comment by Kurfursten** [comment]
I think cultimov is standard practice no matter whether cult is using their toys or not.

Also, I think the opposite is true: if you're not sitting in the back waiting 30 minutes to fill your boxes with talismans and instead only making 2-3 before rolling out, that's more fluid.

**Comment by Allspice** [comment]
It takes five minutes or less to sit down and make twelve stunners if you're efficient and you know how to. As opposed to stun, convert, go-to-some-secluded-area, write imbue AND stun, imbue, erase Imbue, stun the next dude, repeat.

**Comment by Kurfursten** [comment]
Then the action starts sooner and is more segmented. When people say they don't want a slow round, they don't mean "I want to wait one hour of nothing, then get lightning blitzed by all the prep work in 5 minutes of speed action", they mean "I want things to start happening right away, and if there are a few minutes lull between them, that's okay" - C'mon, you know that. You, like me, have been on both sides of cult rounds.

It's in the same vein as what @Aurx is thinking. When I play cult, my first priority is
* Find somewhere secluded to complete all research and communicate it - this takes a lot of time
* Talisman factory so I have enough for myself and to share with new converts -- more time
* At this point I'll either start designing a base if no one else has -- more time
* Then, and only then, do we start converting

I think cult research is a really cool concept, but I can't argue with Aurx that it delays the action until later in the round.

**Comment by Blithering** [comment]
Maybe have convertees have a chance of hearing narnar whisper a word to them? Kinda a research/conversion double whammy.

**Comment by jakmak5** [comment]
In my opinion cult is a mode that depends entirely on several things.
1. the cultists. The cultists have to be smart enough to A do research, B not leave runes out in the open, and C not oust themselves at the first sight of a sec officer
2. Sec. While it is securities duty to fight the cult it is very easy for it to turn into a systematic force implant of the entire crew since with other game modes like traitor and changeling there isnt a tattoo under the antags shirt written on their chest  that says IM VALID. A traitor can hide in the crew easy with no way to detect or find them (provided they dont do anything antagy). Cult on the otherhand has a 100% surefire way of finding and de antaging cultists. Taze, cuff, drag to brig, 50u Holy water, implant, and out the door you have secured a crewmember not knowing if they are even antag or not. While not having deconversion against a antagonist like cult who converts non antags into antags unlike all other non rev gamemodes which are picked roundstart who cant have any more created (excluding adminbus and greytide implants) then it would turn into just executing cultists on sight. Problem is that it is far to easy to systematically decon and force implant the entire crew against cultists. Maybe for non-cultists if they consume holy water suffer mercury levels of brain damage in order to discourage mass deconings.
3. Silicons. While this does fit kinda into issue 2 silicons are in general a problem with this game mode. The AI eye makes it extremely easy to see anything and everything (as oppose to a camera console which is harder to work with) and under all lawsets (excluding memelawsets and subversions) cultists=valid and as we all know silicons love their valids. While the cult does have equipment designed for borg fighting (emp runes and stun tailsmens) these tools are subpar for fighting borgs (both of which are a short stun and essentially tell the borg THIS MAN IS VALID) and which in borg combat you need to win everytime while the borg only needs to win once. This is a larger issue but maybe instead of more anti borg stuff why not make the current anti borg stuff more functional. Not to mention a smaller issue of silicons trying to bypass subversion or outright ignoring it to collect their valids.
4. Shuttle. This game mode is ended quickly and efficiently with a shuttle call. The cultists are discouraged from waging full scale guerrilla warfare (excluding ghost rushes) due to the fact if sec begins loosing the battle they will call the shuttle. Maybe a new rune. Recall shuttle. needs 4 cultists to use. If used it will recall the shuttle if it is not currently docked with station (RP excuse is that narsies magic causes it to get lost in bluespace or there is a forged recall transmission) The reason this entire rune is balanced is that it requires 4 cultists to actually sit down and use a rune to prevent their defeat. As we all know we can barely get 3 cultists to sit still for 10 seconds for a cult sacrifice to progress their objectives..
5. GHOSTS. Good god these things are fucking broken. For the love of god remove their nostun and prevent them from being able to be used for runes (and maybe throw in a health nerf in there). That right there is all the balance you need for ghosts and all the other things I suggested regarding new runes.
6. Remove research. Kurf & aurx did bring about a lot of good points regarding research and segmentation of the game mode. Implantation of idea 5 and removing research would be able to allow cult to be able to immediately get to work instead of sitting around and praying one of them is willing to do research. While it may work on other servers where the games pace is different it just doesn't flat out fit here.
7. Rune drawing. Rune drawing in general is slow and annoying and has the issue of making tailsman manufacture a chore. If coupled with idea 6 go to the old tome system of instead of manually selecting words you instead select the rune itself (with teleport runes requiring the extra last word). Along with shortening the draw time of a rune. To balance this out and prevent ninja converts have conversion require the target to sit still on it for 3-5 seconds (this would also handle the minor issue of pushing people onto hidden runes or table converting)
8. Teleport other. Again minor issue but its just kinda an obscure rune. Its function is to be able to teleport objects and such on it (objects like non cultists, lockers, machinery ect). Problem is ive never seen it used since it needs 3 cultists. Maybe reduce this down to a single cultist for all non living things and 2 cultists to be able to teleport non-cultists. It would make base building a bit easier and bring an obscure rune into the game field again.

I admit many of these ideas may not be perfect but atleast they are a solution to some of the issues that plague this game mode.

**Comment by Kurfursten** [comment]
EMPs got buffed recently so I would want to see how that develops before even considering a buff to EMP runes/talismans

**Comment by Aurx** [comment]
@jakmak5 (How the hell did you need 5+ different usernames anyways?  There's limits to how godawful one person's ability to lose passwords should be.)

1: No way to fix stupid with code.  
2: Implant spam is an issue with the transition from cargo points to credits and how nobody every bothered to make it so you can't dump insane amounts of money through the system.  Hell, right now it's set up to basically let cargo order absurd amounts of anything.  If implants were something that were in short supply as they used to be, sec would at the very least have to make tough choices on who to implant.  
3. AIs can't see maint or runes or anywhere you cut cameras or anywhere off-station or even anywhere they don't think to look (unless they're the track-everyone-in-turn powergayman).  Hiding from the AI is easy.  Borgs are chumps if you have half a wit about you; EMP fucks borgs triplehard.  Also you're dangerously misinformed regarding validity and lawsets so you might want to brush up on that before playing silicon.  
4. Shuttle is trivial to deal with because the recall side wins a shuttle war.  Murder a head of staff, any head of staff, for their ID and the shuttle will never come if you're not a gibbering idiot.  Or convert them and hope they're competent.  That works too.  
7. Runes are powerful enough that they can't be fast to make, and the input is zippy if you know the words that constitute a rune.  
8. Teleport Other gets used occasionally, and it's absurdly OP when it's used smartly.  The three-man limitation also isn't that bad since it works best as part of a three-rune combo.  You can also use braindeads.
