### ISSUE TITLE
Player zombies made by the Staff of Necromancy aren't actually player-controlled

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13460]
The zombie just turns into an NPC, even though the player gets the message: `You have been risen from the dead by your new master, [Owner]. Do his bidding so long as he lives, for when he falls so do you.`

**Comment by Durgen** [comment]
related: when you get Cyberhorroed by a mednano overdose, you become a NPC cyberhorror.

**Comment by Zth--** [comment]
Are zombies as broken as 6 months ago? I've never ever played on something so bugged

**Comment by Exxion** [comment]
The cyberhorror one is intentional, and for good reason

**Comment by Probe1** [comment]
[NO FUN ALLOWED]

**Comment by 9600bauds** [comment]
Looking into the code it INTENDS to put you inside the zombie but for some reason fails

Also worth noting that I was gibbed by the staff as the zombie was formed, which left all my bodyparts on the floor - including head which was later reattached. But then how is zombie form????

**Comment by Kitfox88** [comment]
Your spiritual energy is used to create matter from nothing, as the spirit is the strongest force in the universe and I'm a huge gay

**Comment by Probe1** [comment]
>and I'm a huge gay

**Comment by ghost** [comment]
Right, here's where the staff of necromancy is a big pile of sticks bundled together.

When it shoots at a corpse, it makes a mob and transfers the personality into that mob, BUT it then gibs the old body, which in turn throws a head out.

This head then calls back to its old personality to transfer the mind from the now gibbed body into the brain mob inside the brain inside the head.

It is an extremely flawed system, because if you just go 'Oh, well gib the body and delete the head' this means that whoever just got necro'd can now no longer be even cloned, because there's no mind to reference.

**Comment by SkowronX** [comment]
@d3athrow look at what you diiiiiiiddd

**Comment by 9600bauds** [comment]
please do not shame the elder
