### ISSUE TITLE
The hydroponics department need to be made much bigger

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13478]
There's way too much shit that demands space in botany and way too little space supplied by the hydroponics rooms. 

- The dozen tools (hoe, clippers, axe, analyzer, plant bag**s**, wrench) that will inevitably make their way off your backpack and onto the floor because it's much faster and convenient to store them there since you can't keep your backpack open forever because you always need to open your plant bags too.
- The various bottles of robust, mutagen, radium, dieth, ammonia, left-4-zed, etc., that will also litter the floor because they either come in 10u bottles that you have to use a dozen of on all of your trays and can't be assed to collect all of them and throw into the disposals, or 30u bottles/50u beakers that never quite end up being fully used up and wait on the floor forever.
- The water tanks that are there solely for you to bump into and push onto a hydroponics tray just to be a pain in the ass that pulls attention from other things, and the water buckets that accompany them that will inevitably always be on the opposite corner of the room from where you are.
- Special snowflake growns like tower caps, grass, no-fruit, nettles, egg-plants, etc. that can't or shouldn't be put into a plant bag and end up littering the floor as a result.
- Solid final products you create like wood, plastic, uranium, etc., and while there's technically a table for these, we all know leaving that shit out in the open just results in the clown/greytiders stealing the entirety of your hard work and doing fuck all with it.
- Similarly, all the chemical pills, beakers, etc that are either being used to create the above intermediaries, haven't made their way to the fridge, or can't make their way to the fridge.
- Chickens laying their eggs all over the floor if you ever make the mistake of feeding them,
- Diona that don't take any ghosts in and die right next to your trays.
- Fellow botanists, arguably the worst offenders here, unless you have a good relationship with them they will only end up multiplying all of this other waste and will often cause conflicts. Though at least conflicts are fun.
- Fellow chefs, these are worse than botanists because if they ever poke their fucking nose into botany it's to destroy any semblance of organization you might've created by planting fucking white beets and cabbage and whatever shit into the trays that you'd reserved for something else, and harvesting all your other plants onto the floor like the filthy plant-bag-not-using animals that they are.
- The light pollution created by shitty bioluminescent plants that exist just to add a shitty filter to all of the above and strain your eyes. Okay, these don't take up space, but it definitely feels like they do if you ever make the mistake of planting them.

And all of the above is just regular ol', no-crates, no-nonsense hydroponics in the botanist position for the sole purpose of plant procreation. Just the above shit already needlessly strains your ability to be effective as a botanist. But, of course, you can order more shit that takes up space:

- Egg incubation machines, their crates, and their chickens and eggs that will block you from clicking on your trays and make your life hell if you if you're not always on help intent.
- Apiaries, their crates, and the bee accessories that have now doubled the amount of tools lying around on the floor.
- Chem dispensers brought by mechanics.
- Small farm animals and their crates.
- Large farm animals (crate gets disassembled).
- The half dozen exotic seeds crate you need to order to get any interesting results.
- Weed killer crates.
- Fambots; if you thought water tanks were bad, try giving them wheels.
- Kudzu.
- Vox seeds.
- Resupply packs if you accidentally used up all three seeds and their resultant growns.

As a reminder, here's what the box hydroponics looks like:

![boxponicseroo](https://cloud.githubusercontent.com/assets/22053715/21963094/1174d854-db02-11e6-94ce-0b31dbb331df.PNG)

Mappers clearly don't play botanist ever because they must think that all botanists ever do is plant three wheat, two tomatoes, a corn, and suicide succumb. Where the fuck are the farm animal pens, for example? There's clearly something wrong with the map if Cargonia ends up growing farm animals far more often than botany ever does.

Ideas to resolve this (for box):
- Remove the wall between botany and xenobotany
- Remove the wall between xenobotany and the chef's backroom
- Push out into maintenance and/or the library
- Decrease the amount of hydroponics trays
- Add a lot more tables to put shit on
- Add livestock pens

**Comment by Probe1** [comment]
Coming up on 3 years and I've never thought this before.

**Comment by jknpj** [comment]
Why remove trays? People usually end building MORE trays

**Comment by despotate** [comment]
Remove them to make space for everything that isn't a tray, like tables, farm animal pens, places for machines to be, etc

**Comment by Lokiamis** [comment]
>Where the fuck are the farm animal pens

Zoo when?

**Comment by Exxion** [comment]
There is a zoo.
It's on the bomb testing range

**Comment by Lokiamis** [comment]
The memezoo is a travesty and needs to removed so we can properly introduce the real zoo and the zookeeper role.

**Comment by despotate** [comment]
Okay, so to make the issue clearer, I decided to make an overlay of spaces that can be used for crates and solid objects:

Green = doesn't obstruct anything
Blue = only obstructs the sink
Yellow = obstructs your movement more the more of them you use

![botanyplease](https://cloud.githubusercontent.com/assets/22053715/21963996/98182276-db11-11e6-874f-18b2cf126be1.png)

There are 

- 6 scattered green spaces
- 2 blue spaces
- 20 yellow, of which you could probably use eight without severely hindering movement (the top middle two, middle four, bottom middle two)

This is clearly not enough for what botany should be able to do. The good spots are scattered all over the place and the bad spots are right in the middle where you need your important work to be done. There just isn't anywhere to add a farming pen, or to add multiple machines, or order more than 3 crates.

**Comment by Kurfursten** [comment]
I don't think botany needs more space personally, and I probably play more botanist than anyone who posts on github, and I also made the chicken incubator so I use it a lot too. I usually do one cow but don't bother with kudzu or bees. Neither is rewarding enough to me, the chef can play garnish lotto at cargo if he really wants flan.

I usually put the chicken incubator next to the disposal bin and move one of the sinks to the middle of the room, give my water tanks to the roboticist, and the biggest change to the department I usually make is smashing out the bottom left windows so I can move the chef's condimaster to the right of the food processor, which allows me to easily grind and bottle flour/soy/ketchup for him.

If you're really dying for space, I suggest you drag eight of the outer wall trays to the middle of the room, so you have a 4x4 area. This is the strategy I use when I want bees because of the way pollination works (you literally get no bonus unless a bee is actually idling above a tray), but it also has the added benefit of making your back wall entirely "Green".

You start with a wrench for a reason!

* Decreasing the number of trays is bad. I can use all of them when I'm botanist, and it gets worse with 3 botanists.
* Removing the back wall or the wall to cold storage is a bad idea. You can move the xenobot machines out, but botanists need a back room they can do tator things in, that's the point.

**Comment by kol1th** [comment]
I feel like all of service needs a re-design, tbh. Always thought something like this would be better: 
![image](https://cloud.githubusercontent.com/assets/16979948/21965151/d102a29e-db0e-11e6-915d-4122067f0ddf.png)

**Comment by Zth--** [comment]
I love that thing, what is it? I really really like it

**Comment by 9600bauds** [comment]
Mess is the essence of life

If you didn't make a mess, you didn't work

**Comment by Exxion** [comment]
That's pretty good other than the jukebox behind the bar, but what the fuck are those wall/floor/juke sprites?

**Comment by Kitfox88** [comment]
ugly, that's what

**Comment by Kurfursten** [comment]
The walls probably look better after being smoothed, but that rocky snow sprite looks so ugly

**Comment by Lokiamis** [comment]
![untitled](https://cloud.githubusercontent.com/assets/25004372/21967428/4875ca42-db5d-11e6-8da5-b4d942a4137b.png)

Admittedly I've only rarely played Botanist, but this would give you +4 trays to work with and two tiles to maneuver around the room instead of just one. Any respectable zo- animal pens would have to take a chunk out of maintenance, unless I'm overestimating the amount of space required to care for several animals comfortably. The windows to the back room are tinted for privacy when working on those autism machines I've never seen before.

...


And now that I'm testing this I realize that you can now walk on top of plant trays ok cool

![213](https://cloud.githubusercontent.com/assets/25004372/21967498/c50a307e-db5e-11e6-9b90-e34bdbd7be13.png)

![cc](https://cloud.githubusercontent.com/assets/25004372/21967547/a59bab2c-db5f-11e6-9154-832132c5d957.png)

**Comment by ghost** [comment]
Many did play botanist and gave in feedback the last time botany got mauled:

You keep your primary tools on hand and box or table the ones you infrequently use. This is how things are and it's fine

You throw them at one of the tiles that doesn't overlap a harvest zone and you can crate them into the nook by the disposal until you give a shit to disposal them or just ignore them cause you know it's your empties pile

You can just move them out when you're crampt. Like every other sane botanist already did.

Most of those can, more can if you just drop a grown on top to proc the pickup, and you can crate move what doesn't like you'd do when your biogenning 300 meat.

You can move a botanist locker into one of your some 18 or so free tiles like any sane botanist already did

If you're too messy, you can put in an order for a medical crate for a pill collector when you buy your exotics

Which isn't a problem because you have an entire back room to put a chicken to be fed

There's plenty of minerals, ways to salvage minerals, and you have enough windows to create a diona pen to contain their flailing. There's a public airlock circuit in aux tool for a windoor if you don't want to yank one out of the art storage door. Due to people not doing the same shit, pens get in the way

That's part of being a team. Wrench some stools and chairs then wall off if you're gonna be [TRIGGERED] by someone else existing near your safe space

If they get nerfed like you cry for there's even less reason for them. At least as-is in an extended/pseudo-extended high potency biolums can function as a neat replacement for station lights if you can get people to help swap

You have a free pen in your mulebot delivery, you can lay more glass, and you have ~18 tiles in the main lab and a good deal of additional tiles in the back
Seeds fit in the seed extractor


The back room wall was a valued separator that made your livestock pen and antagonist stuff, the cold room wall is necessary for antagonism, people need more trays if anything to deal with 3 botanists+1 chef's autism. And you can add more tables wherever you want from public chair metal without necessitating other botanists to have to move it every round cause it conflicts with their setup


The holy land of Botania always needs to expand more, just pointing out your holes.

![botany diona pen](https://cloud.githubusercontent.com/assets/5564796/22511645/c96c3504-e842-11e6-8afc-1422affc18a6.png)

**Comment by despotate** [comment]
This issue doesn't matter anymore. My current meta is to just unwrench all the trays and stack them on the tile next to the fridge and just alt-click farm, unwrench the vendors, chemistry machines, and xenobotany machines and move them near the fridge too. Everything you could possibly need is then available maximum two steps away with the added bonus of fucking over any fellow botanists who might've joined you on this wild ride because they have no idea where all the trays went. This is the only way to have enough space to make farm animal pens and expand in the rest of botany.

**Comment by Exxion** [comment]
@kol1th Please
What is that map you posted and why are some sprites ours but others awful

**Comment by DeityLink** [comment]
Especially now that the new bees require you to keep attention what plants your bees are pollinating.
