### ISSUE TITLE
Miners money should go to the station's account

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#13510]
IRL you don't own what you mine if you're a miner. This should apply to this game too, which fixes some nasty unbalanced things of our economy system and miners being ultra rich.
This money, as the title suggests, should go to the station's account.

**Comment by Probe1** [comment]
How about a tax

Half goes to the station (which is divided between the station acc and cargo)

**Comment by Probe1** [comment]
Also get ready for MINER FREAKOUT at the idea that we may curb the ridiculously broken mining monies but we won't rebalance the mining vends and lower the cost there too.

**Comment by Kurfursten** [comment]
Move the mining goodies to cargo crates with reasonable prices and mining access. The vendors just encourage you to tick the throw wire and collect free gear. That might also improve cooperation between QMs and their miners.

You could still use the old dwarven vendor as a free departmental vendor (like nanomed or securetech) for the toys like canaries and fake facehuggers, but also other mining gear like the GPS instead of placing it in lockers. This way, the GPS list wouldn't be as clogged at shift start, and the Vox outpost wouldn't have mining GPSes from their lockers, preventing them from hunting miners easily.

**Comment by Aurx** [comment]
Departmental balances could also stand to be cut dramatically.  Cargo can trivially order a shuttle full of guns at round start, and it's a bit silly.

**Comment by Probe1** [comment]
While true that also has to do with crates having been added ad hoc over years and years without any attempt to balance or rebalance them AND a conversion from a points system to a cash system.

**Comment by uazuaz** [comment]
nobody uses the secondary western mining station's unloading machine because doing so they couldn't collect their money;
removing mining money would fix this, but then you necessarily need a QM or a HOP to buy better gear, if vendors aren't changed.

**Comment by Probe1** [comment]
I mean I figure no one uses it because it's way the fuck over there and ore boxes can carry shitloads (infinite?) ore so what's the point of smelting, having a butt ton of sheets that need transport and won't fit in your crate, then going back to the station anyway since you've smelted your load and it needs delivery.

It's all and all just a rest stop, hide away, and dot on the map rather than a utilitarian addition.  Money plays only the smallest of roles.  Even if it granted you double reward points it'd be seldom used.

**Comment by ghost** [comment]
Yes. Put money into the stations account with minets getting about 30%.

Then have large scale things that can be ordered, like different emergency shuttles or large scale prebuilts to be attached by engineeting

**Comment by aceedex** [comment]
Mining dosh already goes to the cargo account after they buy shit

**Comment by Rattlederp** [comment]
The mining vendors are already a joke because you can hack it and put a monkey next to it to get everything

**Comment by Zth--** [comment]
Ok so we can break this in two parts:

- remove items from the vending machine and make proper crates for them, leaving a few useless items at low cost or even free (like the bird)
- rework how machines in the mining outpost handles money

I'll start investigating about the second one

**Comment by SonixApache** [comment]
Mining vending machines feed directly into the cargo account, it'd be a shame to take them away.

**Comment by Zth--** [comment]
What you should understand is the vending machine and its prices are based on miners having tons of money. It's based on some poorly designed mechanic.

That's why it needs to be reworked. Miners won't have 36k anymore, so there's no reason to keep them.

**Comment by SonixApache** [comment]
I honestly don't know what I can say about this since it boils down to "I don't care because I like it." I just like being able to get cigars, chili, soap and whiskey as non-miner. Great shit as QM.
Adding even more fucking crates seems like a waste too.

**Comment by Blithering** [comment]
How about dividing it up, so that when ore is smelted or deposited, miners get points to spend at mining vendors, and the station gets cash?

**Comment by Kurfursten** [comment]
Didn't have enough support to pass in its day, open it again if you still care
