### ISSUE TITLE
Re-add non-human heads

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#13545]
please god, I've seen too many rounds that're missing a cap or HoP or HoS (or have shitty players in those roles).

We already had issues with filling head roles, and banning non-humans 4noraisins only made it worse imo

**Comment by 9600bauds** [comment]
![toll-gate-new-jersey-winter-snowstorm-much-snow-night-52267030](https://cloud.githubusercontent.com/assets/6526157/22095741/026ddada-ddf6-11e6-94e5-26f284be31fb.jpg)
The Snowflake Toll

**Comment by Probe1** [comment]
👎 

Humans first.

**Comment by kilozombie** [comment]
![1478571453172](https://cloud.githubusercontent.com/assets/6062247/22096372/f80ddcdc-ddcf-11e6-8201-9374fb0ed8fa.png)
Look at these stupid birdbrain motherfuckers. All they're good for is being cute. They can't breathe oxygen or work with the AI, so why should they run a Nanotrasen vessel, which has an oxygen environment and an AI meant to work with the heads of staff?

Not to mention flame bones, which will die near-instantly if they get their suit torn off by an Assistant, or normal bones, who are pathetically slow and vulnerable to damage from all common weapons. Or Dionaea, who can be erased from the station with a simple flare gun or welding tool. Don't even get me started on Greys, who are mind-controlling aliens out to steal your fucking brain.

**Comment by yclatious** [comment]
We already have people bullshitting the restriction by selecting Captain and switching races, we don't need to make it official and allow snowflake space proof nigger birds who can't even speak properly, brittle imolating bones that get fucked if you remove the suit or tank, even more brittle bones that die to 4 toolbox hits and move slower than a grandma without her prune juice and a tree that dies to a welder to run a human station, run by a vox hating CEO, made for humans, by humans, with human interests in mind, frequented by racist human crew.

No.

**Comment by JustSumBody** [comment]
>We already have people bullshitting the restriction by selecting Captain and switching races

I have almost literally never seen this happen.

**Comment by kol1th** [comment]
@yclatious Yeah let's just make nonhumans completely valid, would make it much easier to kill people

**Comment by TheFriggenSawbones** [comment]
@kilozombie @yclatious 
I really don't like the argument that they shouldn't be allowed these roles because of some gameplay balance issue, because our boy, Slate Slabrock, dies faster than anything. Also yclat you're lying about the restriction avoiding thing

**Comment by yclatious** [comment]
How am I even lying, Im dang sure Ive seen it happen and even more sure I saw a issue here that said it was possible and was being done.

That aside, just because one human player dies extremely quickly doesn't excuse people from playing even more frail races to die even quicker than him, especially if they are worse than him. Captains have all access sawbones, a 40 burn rechargeable gun, the pinpointer, the disk, the comms console to, ironically, do the most antagonistic thing possible and endlessly recall the shuttle, its a lot of power that you can get relatively easily if its a dionae, just shoot it three times with a laser gun and its dead with you having it all, just be a no id greysuit with a mask and cap and stunglove the plasmaman captain, remove his suit and tank, toolbox him a few times and bam, all yours, skeletons are just toolbox fodder, and the main issue with all of these is that we would always be forced to have that great NT default lawset be standard every single time they play because the AI is a hit or miss with the non humans. Gameplay balance matters sawbones, its why things are nerfed and buffed and thinking massive weaknesses that can be exploited don't matter when you own the station is a excuse, a really bad one, and basing it on a player that might be bad is just finding a scapegoat.

Too much hassle, no good gameplay changes, just snowflakes with easily exploitable weaknesses being even more of a target than before and like always, being bad at being captains, like every single captain player. Doesn't fit the lore, doesn't fit gameplay wise, too weak/exploitable, not worth it.

**Comment by uazuaz** [comment]
having heads that are not listened by an asimov AI doesn't seem a good idea.
when people that usually play other races want to play as heads, they can just change their race to human for that round.

**Comment by Kitfox88** [comment]
just make nt default the default instead of asimov 🤔

**Comment by yclatious** [comment]
Its NT default because unless Im mistaken, goon has it as the default lawset, we have assimov because its much less shit to the general crew instead of just serving the captain and having a army of borgs kill you for a broken window.

**Comment by SonixApache** [comment]
remove non-humans altogether

problem solved

**Comment by Blithering** [comment]
I don't see what the problem with nonhuman heads are. It's perfectly possible to create a limbless, blind and deaf human and sign up as captain, so what's a couple of racial downsides gonna change?

**Comment by SonixApache** [comment]
@Blithering 
AI it's revs kill the heads

**Comment by Ephx1** [comment]
> Its NT default because unless Im mistaken, goon has it as the default lawset

We took "NT Default" when we went on Bay code, as that's the NanoTrasen standard lawset for their in-lore stations, it covers all of their alien species. It's also _not made for our lawset rulings as theirs do not flow in a number priority fashion_, meaning the Captain there can't just order everyone to be killed.

**Comment by ultraplen** [comment]
>snowflakes want to be in positions of power

naaaaaah

**Comment by Killette2** [comment]
Why not just get a promotion to head of staff? 9/10 times nobody will care, and if they do care they probably aren't roleplaying and they're just being a cunt because potent antags.

**Comment by ComicIronic** [comment]
I care because player Vox were a mistake. Oxygen station for oxygen breathers.

**Comment by Iamgoofball** [comment]
Slippery slope

**Comment by jakmak** [comment]
I remember only one single time a non human captain was not a condom ( and the captain in question was diethyl). The WORST captains are always non humans. The same retarded shitters that get in fights with sillicons constantly and leave the disk on the desk. Atleat with humans you have a good chance of them not having autism and down syndrome.

**Comment by Blithering** [comment]
@SonixApache AI open your upload turn off the turrets and don't tell anyone while I set you to onehuman okay now kill the heads.

**Comment by kol1th** [comment]
There are more snowflake humans than nonhumans

**Comment by SkowronX** [comment]
Equal opportunity or employment has no place in spess.

**Comment by Kitfox88** [comment]
ill be writing hr about this discrimination just u wait

for real though lol if you're playing a vox as anything other than janitor/paramed/librarian or T R A D E R

**Comment by Rattlederp** [comment]
Why would you even want to be a head? The only advantage is you get slightly better gear but the disadvantage is everyone expects you to do everything and cries when you don't single-handedly save the station (edit: they also cry if you DO save the station, you valid-hunting asshole). You'll be lucky to find subordinates that listen to you or even acknowledge the fact that you're a head. Try being non-human on top of that.

Heads were made with higher roleplay gameplay in mind, just like half the things in this game. There's no reason to try and fix something that was made with a heavy reliance on roleplay, especially not on light-rp, and even less reason to have non-human heads because the only roleplay revolving around that is "dude racism lmao" and "I'm sorry Dave, I'm afraid you're not human"

tl;dr even when you're human people rarely acknowledge your head position, it doesnt get any better if you're not even human

**Comment by Riekland** [comment]
antag only vox when
replace traders with plasmamen
make trader the only job blasmamen can take
remove roundstart skeletons
j o b d o n e

**Comment by Ephx1** [comment]
Skeletons already move slow as shit and are made out of twigs, it's punishment enough for anyone who wants to play a walking joke.

**Comment by kol1th** [comment]
@Rattlederp I agree, people only play heads to powergame. Let's remove heads.

**Comment by Kurfursten** [comment]
If we remove heads, we're going to have to relocate the brain and eye organs to the chest.

**Comment by Killette2** [comment]
![engraving-blemmye 1](https://cloud.githubusercontent.com/assets/5169310/22136129/9a87404a-dea0-11e6-82a4-b15141ca3a02.jpg)

Our ancestors long before us predicted how ss13 would play out after the removal of heads, and the other features the slippery slope allowed after.

**Comment by TheFriggenSawbones** [comment]
@uazuaz Yeah, that's probably the biggest problem with it.

@ultraplen idk how you can call the non-human players snowflakes when we have anime haired waifus running around stealing our Cap and HoP roles.

@ComicIronic Vox weren't really a mistake. There's quite a few good Vox players who add positively to the round, you don't know them because you don't play.

@Iamgoofball Hey goofball, you're on the wrong github again. https://github.com/tgstation/tgstation

@jakmak You're a special boy

@SkowronX why's that

@Rattlederp Good points but I've seen plenty of successful non-human heads. It can be done, and I think it normally adds to the round.

**Comment by kol1th** [comment]
So without posting a paragraph with no punctuation, what is the actual argument against non-humans? Lore? RP? Powergaming?

**Comment by yclatious** [comment]
All of those, yeah, alongside the server not actually needing the head slots filled most of the time, especially with how bad non human captains are, even worse than the regular human ones, to the point ill take a animu snowflake human over a alien generic man any time of the week.

**Comment by SonixApache** [comment]
@kol1th 
Furbait, first and foremost. Slippery slope.
Snowflakery. Not just code-wise, but also playerwise. See: you, sawbones, other non-human advocates.
Silicons hate them. This is annoying to everyone.

**Comment by Ephx1** [comment]
I don't hate non-humans, except when they desperately try to pull a law two seriously when arguing with an actual human. Which coincidentally was usually a non-human head screaming about rank.

**Comment by Blithering** [comment]
What about some, but not all races being re-added? Lore wise it makes sense, as plasmamen were human NT employees before being turned into album covers, makes sense that some of them held rank, and greys aren't hated nearly as much as other nonhumans. Gameplay wise not every captain has to have the pinnacle of validhunters, as that way lies madness and mikecari.

**Comment by SonixApache** [comment]
Depending on which lore you're talking about plasmen are either freakish living dead stuck in a flaming hellish purgatory or weird science rejects that are stuck in flaming hellish purgatory. Not really officer material.

Greys are weird mind-fucking aliums and the most stereotypical alien a huamn can think of. Wouldn't want to serve one except to the dogs.

**Comment by yclatious** [comment]
While lore and RP wise plasmamen and greys are semi reasonable, plasmamen still are fragile as shit zombie freaks in constant pain, that ignite with oxygen and will get dunked real hard just by you stealing a tank and suit, greys, despite don't have any major weaknesses to splashed water unless you drag them under a constant source of splashing water like a shower, are still some freaky psychic wierd looking race of grey skinned freaks that can shitpost into your mind, yes, better than niggerbirds and a tree, but not by much, gameplay wise, plasmemes have issues too.

Without any sort of damage outside of the loss of the tank and the natural burning they have, plasmamen have approximately 1 minute and 42 seconds till crit, that is without a single toobox hit if the traitor feels like humiliating the captain by stun cuffing and setting him in maint, in the chance the traitor will toolbox him, just 7 hits will make the plasmeme be put into crit, 3 will crack his skull, these can easily be done by the scrubglove or a stunning prod stun time, allowing you to, if you catch him off guard, dispose of him real dang quickly, and lets face it, with no real oposition by anyone but sec. We also don't need NT default be more any common, we already know command roles are mostly shitter jobs which now would have non humans which have been known to be worse than humans in said shitter jobs, and like said above, slippery slope with a bunch of snowflakes in command jobs is not what we want.

If you want more players to play command and high importance jobs, you should make these jobs worth playing but there is no reason for a player to be a HoS when you can just be a sec officer and go on as usual, no reason to be a HoP other than full access shittery and going HoPcurity, no reason to be a CE other than slightly better magboots, shinny suit and not having the AI toggle the button to get your suit, filling these spots with non humans won't actually do anything but at worst, make bad command players and at best, inflate command with non humans for about a week and then, like everyone knows it will happen, command roles will again be left mostly empty except the shitters or new players who have played ss13 for a total of 4 days and decide to be captide.

Again, its both lore, rp and gameplay that makes this a bad idea.

**Comment by SonixApache** [comment]
Greys actually punch like little girls, for the record.

**Comment by Blithering** [comment]
A captain that gets himself scrubgloved and cuffed in maints is dead no matter his race. trickypens, ling stings, vamp glares and cult talismans will fuck over anyone but the most shittertastic powergamer if caught alone. This is not a bad thing.

**Comment by yclatious** [comment]
Still fragile as fuck and can be downed even by a random guy with a toolbox with relative ease, doesn't fit lore, doesn't fit gameplay wise, nobody likes plasmemes and plasmemes don't fit captaincy anyways since, in lore, they are walking zombies in permanent pain that ignite in the station atmosphere. With non human captains like Mr Ufo being as bad as they are, what makes you think that the even less accepted non human captains would not get lynched if they didn't fall back on good old NT default and a army of borgs ready to suck their burnt dick?

Face it, they are needlessly weak, aren't good for captaincy and in general, aren't really good for anything, making them in charge of the station will do nobody any good but allow a bunch of snowflakes to be shitters in the premier shitter job of them all, no reason to allow that.

**Comment by Megamaw** [comment]
>humans aren't the snowflake race

>all the 'waifus' are human

i dont get it. i've never gotten this and i still don't. can someone please explain what a 'snowflake race' is if it's not the most popular race amongst 'special snowflake' players

**Comment by Blithering** [comment]
I'm not going to be able to convince you to like nonhuman heads, nonhumans in general or heads in general, I just ask that you consider that other people do like them. I've given my reasoning and personally enjoyed playing as a nonhuman head back when it was allowed, working with the downsides the race had added a challenge to the role that kept it fresh. I also really liked the suit designs, captains armour has too much green in it still.

**Comment by kilozombie** [comment]
If you want nonhuman HoP, Captain and HoS, introduce some way to prevent just anyone (i.e. players who will do it badly) from doing so, I suppose.

**Comment by Blithering** [comment]
Isn't that what ban requests are for?

**Comment by Megamaw** [comment]
this is literally what we have headbans for. if someone's a shitter as head, they don't magically get a free pass because they're a skeleton.

also i'm pretty sure you have to be on the server for a certain number of days for headroles anyways

**Comment by Durgen** [comment]
Maybe we can split the difference and allow non-humans to be heads, but always give preference to humans.

For example, a human with HOS set to low would get the job over a grey with HOS set to high.

That way, nonhuman heads are kept to a minimum, but can still fill slots as a last resort.

**Comment by Megamaw** [comment]
low vs high? that's a little excessive.

but again this change in the first place was pretty fucking dumb

if someone's a shitter captain, telling them they can only be the most powerful race in the game won't stop them from being an awful shitter captain

**Comment by yclatious** [comment]
The thing is, as of so far, we have had a overwhelming majority of nonhuman captains and the like be absolute trash, opening the floodgates so they are now absolute trash but in weaker and more unique forms doesn't change the fact that they still suck at it. You will allow them to pick the head spots and they will suck at it, and like I said above, at best, it will just make the head roles be inflated with non humans for a week or two and at worst, you will have bad non humans sticking to it.

If they want to be non human captains, with the whole shtick of being a underdog because of being a non human, they should prove to be good human captains first anyways. Wouldn't you agree?

**Comment by Blithering** [comment]
Not really, whitelists create an entirely worse brand of faggotry to the server.

**Comment by yclatious** [comment]
In my honest opinion, non human heads are themselves massively faggotry, whitelisting to allow them was a brainstorm moment and I admit its a bad idea in hindsight, but at the moment it was the only way I could even see that the players that want to be non humans are atleast competent enough to play with a racial disadvantage.

Either way, whitelist or not, still a god awfull idea.

**Comment by Megamaw** [comment]
ok so let me get this straight

the arguments are as follows

"we dont want nonhuman heads because most nonhuman head players are garbage"

shit head players are going to be shit whether they're playing human or nonhuman. this isn't real life, someone can just switch to human to be a head.

"nonhuman races more like SNOWFLAKES am i right"

literally all the 'waifu' characters (bar Rail) and most of the supposed 'metaclub' are human have been historically always human in the past. humans are the most powerful and easiest to play race in the game. 'snowflakey' behavior (self-important bullshit, ridiculous hair colors) is, again, something that is almost entirely exclusively human. unless somehow the word has miraculously changed over the last ten years, i think people screaming 'snowflake' are just looking for a buzzword to latch onto.

any other arguments I should be addressing?

**Comment by yclatious** [comment]
Yes, shit players will also play as shit humans in roles they are shit in, I don't see a single reason to play races meant to be underdogs as the top dogs of the station and I don't see why we should allow the people who are shit at playing human captain to now play non human captains, which are objectively worse and would make them even worse at playing that role, due to silicon behaviour, NT default being mandatory, likely abuse of power and like we know non human heads to be, comdomry is guaranteed. What player likes forced NT default every round so the captain isn't ignored at best and killed at worst by silicons, what player wants captains that leave disks in the desk unprotected, and what player wants to follow around a three laser hit and dead tree, a weak as shit zombie skeleton that ignites in the station atmosphere, a gypsie bipedal raptor bird who can't even speak the spess version of english properly and has a tendency to steal everything he can, a literal meme race or a stereotypical grey alien. I sure as hell don't and I sincerely believe nobody else does.

You act like anyone has excused human snowflakes when nobody likes them either. We can't stop whatever attention seeking bright neon hair retard decides to snowflake unless you start banning how a character looks like, and I don't even think that has ever happened. Look, not all non humans are snowflakes, but I believe that if you are a non human, you are wilingly playing as a underdog to enjoy being a underdog. I played a bit as a plasmaman because I liked how I didn't have the borgs need to obey me, how I was slower,  it was a nice handicap and made me appreciate everything, I understand that people enjoy playing non humans and I won't shit on them for that, but I will shit on them for thinking they can pick what is alien, what is meant to be in a hostile environment, what is meant to be discriminated against, even if lightly, and then suddenly try and integrate what is naturally meant to not be integrated and normalize it.

The fun, atleast for me, of non humans is how they are naturally different enough they are usualy treated worse but can make great player interaction, like a sec officer and a vox chatting peacefully because the vox behaved and was cordial, showed he meant no harm to anyone and so they began chatting and traded a bit, a plasmamen showing a picture of his ass to the HoP so that central command could verify that indeed, plasmamen still have their asses and its possible for a plasmamen to sit on a photocopier and print their burning hot buttocks to the physical form, I remember a skeleton in medbay, a great CMO, and how he taught me in my starter days as a paramedic, I remember the chill as hell skeletons who always relax by the bars, playing slots and the likes, I know that non humans can be fun, but they are meant to be treated as inferior and strange, they are too be treated as aliens, not to be normalized or integrated, its them being so strange and discriminated that makes them interesting to interact with, and now thinking you are worth more than you are, that you now are the authority, the big boss of the station when you never were meant to be more valuable than anyone else, I consider that snowflaking, yes. I will never say for non humans to be removed, because I know that there is a good component to them, occasional racial exploiting aside, but I still believe that the point of them is that they are meant to be played in lower class jobs, not command ones, both because its mostly shitters that play command and because it, in my honest opinion, doesn't fit them at all.

Also, I fondly remember my round of nookops where a non human, Mister UFO, in less than 5 minutes of planning done, already had a complete revolution happening by the crew, had the borgs hating him, and let the disk on his desk for us to locker ops effortlessly, only for our team to set it outside the station and fail, so maybe I just saw the worst of it all, but still dang bad and Id rather that doesn't happen again.

**Comment by kilozombie** [comment]
yclat, I don't always agree with you, but I appreciate when you put time into shit like this to get your point across. Heavily in agreement.

**Comment by yclatious** [comment]
Im a nerd with too much time, did you excpect me to do anything productive instead of ranting about the dang illegal aliens?

**Comment by Blithering** [comment]
You've brought up this mister UFO person multiple times, consider that that maybe they were a shit captain because they were a shit captain, not because they were a nonhuman. Your round wouldn't have gone any better if you'd had the termedclepe 'checked the manifest at round start and determined it was nuke ops so the disk is in a polyacid mousetrap box in a cake in a cheese wheel in the clowns arse' scenario. Choosing a human character does not automatically magnetise the nuke disk to the captain, and picking a nonhuman doesn't superglue it to the desk. Likewise, the AI's laws are probably not going to be changed all that more even if every nonhuman captain does set it to NT default, which I certainly didn't when i played. At present the laws change to full valids mode when wizards, nuke ops, cult, traitors or any other human antag gets suspected, or when the clown is sighted within ten feet of the upload door.

Other than vox being generally accepted as space gypsies there's no concrete way to play any nonhuman race, so stating that they are meant to be treated in certain ways and play in certain jobs is a bit off. It just seems to boil down to the idea that you feel that other races exist to have something to feel superior to, and allowing them head roles endangers that.

I've already gone over the racial weaknesses point, but I'll reiterate, anyone who can get a captain stunned or unconcious enough to strip internals and suit, or feed them a bucket of water or whatever nonhuman eradicating method, will have enough time to slip them a 30u chloral pill or stick a brick of c4 on them. The execution doesn't matter. a captain who gets stunned alone in a room by a guy who wants them dead is dead.

**Comment by yclatious** [comment]
I mention the worst example I can find to prove my point, the fact that non human or not, captains are usually shit and having him be a non human only helps to make him perform worse, even if by borgs not needing to obey him and just ignoring him. Im not asking for massive powergaming as a captain, Im asking for competence, and human or not, we do not have players that play competent heads anyways, why do you think that now opening it to people who miss the bleeding point of non humans will somehow solve any issue or that it would do anything but fill a role with too much access with shitty players who can't even play said roles decently? Why would you ever want players just fill up spots if they already suck at, and why would we then want them to fill up their spots as unfiting races meant to gimp you for interesting interactions?

Actually, yes, the round would have been a lot more different if the captain did his job and secured the disk right, except like we have said before, many non human captains have been absolute garbage and this example solidified it very well, there are very few players that could do a good captain, and opening it to players who I believe, miss the whole bloody point of being non human, will do nothing but, like I said two times already, inflate the playercount of heads for about a week or two at the best scenario and at worst, you now have some insistent little non human shits who suck ass at captain and can't even shove a disk in their person play all the time. Im sorry, if you aren't this kind of player, I am sincerely sorry, but I do not want someone who plays a skeleton/chronic pain fire zombie skeleton/tree/grey alien for the sake of playing as a different race and standing out to be anywhere near a job made to control/having any control over the station and oversee others.

If you are one of the few non human captains that doesn't suck massive nobs, then good on you mate, but don't make me laugh by saying that non humans will in any way shape or form be better captains than humans, and that non human captains would be better on human ships with human atmospheres, with human dialects, with a human CEO and human pride and racism. Non human captains don't fit, we do not need alien fodder for command jobs, they miss the whole bloody point of being non humans and playing as non humans for the sake of the side effects, instead just playing as some big shot birdo who thinks they can play captain, and surprise surprise, they can't, like 90% of the server population.

Again, we don't have even 10 people who can play captain in a good way or even 15 that can play HoS and HoP without pushing it, why do you think that enabling non humans with weaknesses will now make it so these jobs are done well? 
Especially when its been said several times now that non humans heads have been known to be awful, the pr to remove them went ahead for a reason, because they weren't needed and they never actually did anything in any way better than humans ever did, only creating hassles and NT Defaults. Again, if you used to be a non human captain and played in some different time zone from me so I never saw you be a good and interesting captain that used his non human status to bring something new to crew interaction, Im sorry, but right now, I see it how I've seen it be, bad captains that create nothing but trouble from their non human status, that are still bad captains from personal skill and never became better at captaincy or any high profile job by playing as non humans. 

Sorry if at this point Im doing nothing but ranting, but I don't see a single thing good coming from this, besides, who here wants Rat King Sawbones as their captain? The second that shit hits my screen, Im doing a clown and running off the airlock, no offence zealotron.

**Comment by Blithering** [comment]
I'm trying repeatedly to help you understand, a good captain and a bad captain are defined by the PLAYER, not the race. Restricting it arbitrarily to humans doesn't dissuade the shitters who want to grab all the fancy toys and play as all access assistant, if anything it makes it easier for them as there's a higher chance of the spot being free. Repeating that nonhuman heads are crap til you're blue in the face doesn't convince me when the only behaviours you describe have little or no connection to the fact that they're nonhuman.

**Comment by yclatious** [comment]
And I am trying to tell you that the players who play non human captains and the like suck, much like the players who are human and try to snowflake with bright neon hair.

And I am trying to tell you that captains aren't played that much and don't need to be played and those that do play are usually bad, and as such, allowing more people to play that job is bad, especially when the people who insist on playing that job as a non human have been extra bad, worse than usual, and its not like we have high standards for captaincy blithering.

And I have told you so many ways that they don't fit, gameplay wise, lore wise, rp wise, I have said in detail how it goes against it, how the PLAYERS themselves who play NON-HUMANS CAPTAINS have been known to be SHIT because they have NO SKILL to be CAPTAINS, because I do indeed know that it is the player who sucks, not necessarily that it is because of non human status, but I also know that the two go in hand too bloody often to be just a coincidence.

And I know that I will not convince you and that you won't convince me, Im discussing this because Im a nerd with too much time that is discussing racial job oportunities and how they fit in the context of lore, rp, how the playerbase responds, all in a game with a engine older than most pewdiepie viewers that was originaly a atmos autism game turned social deathtrap. 

You can keep repeating that non human captain players weren't shit, that this is a good idea, that player skill being low and playing a non human captain aren't connected till your face goes blue too mate, but you wouldn't be right in saying so.

**Comment by clusterfack** [comment]
Plasmamen should be allowed since they were canonically human employees, imho.

**Comment by Probe1** [comment]
Yeah I'm okay with plasmamen.

**Comment by Blithering** [comment]
Hooray for the spirit of compromise.

**Comment by yclatious** [comment]
Rat king sawbones is going to be a captain.

God save us all.

**Comment by Exxion** [comment]
He's been a captain many times before

Also I think nonhuman heads are dumb, but I also barely care so :woman_shrugging:

**Comment by Riekland** [comment]
How about this
Let plasmemes be heads, but headban sawbones

**Comment by SonixApache** [comment]
I'll take that deal

**Comment by Ephx1** [comment]
I'm down for that

**Comment by Blithering** [comment]
I read that as headmin sawbones first time around.

**Comment by yclatious** [comment]
Alright, plasmemes only and only if sawbones is perma headbanned.

**Comment by PJB3005** [comment]
@TheFriggenSawbones what do you say?

**Comment by ultraplen** [comment]
Its a slippery slope but its also a fair deal.

**Comment by Kurfursten** [comment]
Did not have enough support 2 years ago, make a new issue if you think you can get it to pass (doubt it)
