### ISSUE TITLE
make vox plants have snowflake chemicals

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13557]
i.e. Aloe doesn't have Kelotane, but rather [insert name] which behaves exactly like kelotane so there's effectively no difference

why?

so they stack with conventional medicines, thus, becoming useful to the main station

**Comment by Probe1** [comment]
Sure.

**Comment by Kurfursten** [comment]
Do you mean just aloe or other plants coming to mind? The only others that would make any sense are the pitcher plants (sulphuric acid) and garlic (holy water).

**Comment by 9600bauds** [comment]
I generally meant just the concept of alien plantz having things like Off-Brand Bicaridine
Kind of like how bees produce Off-Brand Doctor's Delight
There's no real difference to the botanist, but it's a moderately entertaining and moderately useful prospect for a chemist

**Comment by despotate** [comment]
Why not the same thing for botany?

Almost all of their plants make chemicals that could be made with a few button clicks twenty tiles away. The only plants worth getting are the deadly ones if you're an antag, or glowberries/golden apples, but usually by the time you mutate, splice, and robust any useful yields out of those, the miners will have brought much more than anything you can make. Plastellium's useful but usually you don't really grow that since mechanics prefer just taking a tray of it and scanning the seed extractor. People usually prefer ordering crates of wood. There isn't any service that botany _really_ provides other than making growns for use in food.

Hydroponics is just one big ghettochem, which I would be more fine with if it wasn't located 20 tiles away from the real chem.

**Comment by Probe1** [comment]
No reason not to except that I won't be the one doing it.

**Comment by Kurfursten** [comment]
>There isn't any service that botany really provides other than food

The biogenerator is crazy handy, pity not many people use it. Maybe if it was at the front of botany, kind of like the general fab for the mechanics.

**Comment by Probe1** [comment]
That'd be a super easy change on all maps.  One windoor and the machine.

**Comment by despotate** [comment]
Forgot about the biogenerator. I agree, it's pretty good, although it doesn't lend much creativity to the botanists other than planting pumpkins and robusting them to 120 potency for that maximum nutriment. +1 to adding them to the front, their products are pretty useful and diverse.
