### ISSUE TITLE
RSF for Librarian?

### ISSUE THREAD

**Issue by Yelier** [d3athrow/vgstation13#13589]
I feel like giving a rapid service fabricator to the Librarian would be a good thing to do. While it wouldn't really help a normal Librarian that much, it would work wonders for Reporter and Game Master, with the ability to make more cameras, film, playing cards, dice bags (this is a big one, librarian only starts with one of each kind of die that isn't d6 or d20), cardboard (folders), pens, or even candles for some gaming atmosphere.

I know that you can make an RSF from an autolathe or pester a service borg to make the shit you want, but I really think that it should just be something that they get at roundstart in their private study.

**Comment by Kurfursten** [comment]
On one hand, I don't really see the harm, but on the other the librarian has more time than anyone to go next door to get one from R&D, or visit cargo, or borrow the bartender's, or ask the neighborhood botanists for cardboard and candles. It's a pretty fluff heavy role so I'm not sure reducing interaction with the crew is right for this job. Also, putting matter cartridges in the librarian backroom is a pretty decent incentive to smash inside since they're rather expensive but also versatile.

With all that stated, I do think that there is a serious issue here in that the librarian doesn't start with enough dice. I certainly wouldn't object to the library having more bags of dice, or even for the game master to get some alt-title specific starting equipment. Plastic sheets should definitely be craftable into any size of dice - you could actually even, with some work, write it so that you can craft your own custom dice out of plastic, just in case you really want a d7 or something.
