### ISSUE TITLE
Remove roundstart command reports with probabilities of antags AND/OR add a report on a random round start modifier

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#13631]
Examples, probably shit ones, feel free to suggest your own:
 - Station is broke, no one has any money
 - Roach infestation in maint
 - Impending shipment of corgis ordered before the shift started

It'd be a hell of a lot more useful than the current report, anyway

**Comment by gbasood** [comment]
whoops

**Comment by Zth--** [comment]
I really like this

**Comment by Exxion** [comment]
The roundstart report actually has NOTHING to do with someone being an antag
If I'm not mistaken, the only thing that affects your likelihood to appear on it is your NT affiliation character pref

That said, if you do happen to appear on the report as a regular traitor, you get a bonus 4 TC

**Comment by Probe1** [comment]
It has a probability of being correct but I'm not going to share what I've empirically tested over a significant sample of rounds because it's just not a good idea for the serb.

Removing it is whatever.  I like it.  I think its useful for security to have people to be mindful of especially when they're bored.  

But at the same time it's almost never appreciated - either it gets totally ignored or a player ignores the "Acting on this without evidence will cost you your job(ban)" part and gets himself in a conversation with me.

I don't really want to see it go.  But I also don't think it'd hurt the game.

-----

I feel like its a totally separate issue to have random modifiers and that's both a pretty big project and a really cool one.  But it doesn't really seem related, except by proximity.

**Comment by Exxion** [comment]
Message me that evidence, because I remember looking at the code and specifically noting that it had nothing to do with antag status, as far as I could tell

**Comment by gbasood** [comment]
~~It may be that it statistically picks one antag as a threat over numerous rounds but it's not intended to do so reliably. In fact it's intended to be unreliable.~~
We could keep both, really, ~~but the report has historically caused more confusion to new players who think they have a valids report than good.~~
~~Not that I can think of anyone in the last 6 months who took the report seriously~~

~~Also statistics:~~ OVERSIMPLIFIED NOT ACTUALLY GAME CODE
Report picks 3 people out of 60 players - that's 5% of the population
Assuming all 60 players have an equal chance of antag where only one player is picked, it'd be 1/60 or 1.666..%
In a series of 3, i.e. command report, assuming that equal chance, you have a 1.666^3 chance of picking *one* antag out of the crowd, roughly 4.3%.
Your chances would be significantly better in a roundtype that picked many antags, like cult or autotraitor I think picks several at roundstart based on population? i.e. 6 cult players in a 60 player round means 1/10 players are antag, meaning your chance to get one in a series is (1/10)^3 if the report picks 3 people

It's been awhile since I've looked at the report so I'm just going off memory that it picks 3 people to be suspicious of, btw~~

**EDIT:**
Looking at code it isn't that simple, though
Lots of variables involved
The most notable being
```dm
		if(man.client.prefs.nanotrasen_relation == "Opposed" && prob(50) || \
		   man.client.prefs.nanotrasen_relation == "Skeptical" && prob(20))
			suspects += man
```

**Comment by Exxion** [comment]
That's the wrong measure for statistical significance, but turns out I was wrong anyway

**Comment by eplgr** [comment]
I like the feature, it adds more diversity to rounds. Actually it's something that we could start working on regardless of the current list. Different roundstart modifiers.

BUT, do keep in mind that if you appear on the current list AND you are actually a traitor, you get bonus TC, which is very significant in my opinion. 
(I also think the bonus TC amount got doubled recently?)

**Comment by gbasood** [comment]
@eplgr except you don't depending on your char prefs
which is something I'm going to fix today if my campus wifi ever lets me finish cloning the repo

**Comment by gbasood** [comment]
IDEAGUY WRITEDOWN TIME:
Random roundstart modifier: AI is not ASIMOV but instead NT Default/robocop/paladin

**Comment by Ephx1** [comment]
> Random roundstart modifier: AI is not ASIMOV but instead NT Default/robocop/paladin

Please no, not again

**Comment by Exxion** [comment]
I think we have code for that, but people flipped such a massive shit, the probabilities for everything except ASIMOV are set to 0

**Comment by Intigracy** [comment]
NT Default is the powergamer wet dream and is not fun.

**Comment by eplgr** [comment]
@Intigracy Powergamers will powergame. To talk about specific lawsets that provide slightly less tools for powergamers to powergame than others is a flawed discussion from its root.

In general, and now I'm not talking to just you, I believe we got a big issue where we limit too much certain gameplay aspects instead of dealing with the shitters.

But I guess all of this is offtopic, _honk_.

**Comment by gbasood** [comment]
@Ephx1 probably not going to add that one but it was the first thing that came to mind
