### ISSUE TITLE
The vox trader outpost and vox shuttle need to be bluespace-shielded

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13709]
monkey steal many vox ware when given friendship pie

edit: telescience can steal trader shit with no repercussions for those of you who need it spoonfed into your brain

**Comment by kilozombie** [comment]
But...
but why?

**Comment by ghost** [comment]
What?

**Comment by DamianX** [comment]
Is telescience stealing your toys? Is that what you're trying to say?
Also buildable bluespace shield generator when?

**Comment by despotate** [comment]
Because telescience can steal everything not wrenched down in the trader outpost and shuttle, yes. There's no IC repercussions because security will never side with traders and you don't have the manpower or tools to fuck with telesci, plus you don't know who did it so you'd get bwoinked if you even did do anything. The only "solution" to this is to have everything you're gonna sell on your backpack... which isn't a solution, especially now that bags of holding are gone.

There's no point to actually trying to trade if telesci will steal all of it, which is why tradertiding is so much more lucrative.

**Comment by kilozombie** [comment]
I
What
What???
what.
??????
I'm not gonna tick you for things that actually happened to you, but in dozens and dozens and dozens of my own rounds as Trader with both non-valuable and valuable goods, and this has _never_ happened to me.
Is this really a problem, or is this another case of you extrapolating one round to many rounds? Because that's what this feels like.

**Comment by despotate** [comment]
It's happened to me once plus I've heard of it happening to others in the discord. I'm not extrapolating this to many rounds:

> There's no point to actually trying to trade **_if_** telesci will steal all of it, which is why tradertiding is so much more lucrative.

They often, of course, won't steal all of it. But it's a repercussionless action they can take that's essentially just a random "fuck all of your hard work" to the Trader, as gassable as he may be. I'm fine with leaving IC things IC but what even IS the IC response to this? Telescience is a fortress, you don't know who actually did it, no one else will help you, and petty theft isn't ahelpable. Free shit for scientists at no risk.

**Comment by Kurfursten** [comment]
Actually I've seen this happen, a trader tried to sell bluespace crystals so the telescientist simply stole them. I mentioned the story previously in #13616

I wish moe still worked because the telescientist actually bragged about it in the thread after, I'd link you to the post, but it's too old for the 4chan archive.

**Comment by despotate** [comment]
Holy shit, they stole my telescience crystals too. It seems the only time they steal shit is when they want those crystals.

**Comment by ghost** [comment]
Is it time for a bluespace nullifier generator that runs off bluespace crystals?

The better the crystal, the larger the range

**Comment by Kurfursten** [comment]
Hey look, here's the logs!

[20:08:13]ADMIN: Emok/(<A HREF='?_src_=holder;adminplayeropts=[0x300037c]'>anglosphere</A>) teleported a the bluespace crystal to <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=285;Y=221;Z=1'>Telescience - 285,221,1</a> from <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=153;Y=225;Z=1'>Vox Trade Ship - 153,225,1</a>
[20:08:13]ADMIN: Emok/(<A HREF='?_src_=holder;adminplayeropts=[0x300037c]'>anglosphere</A>) teleported a the bluespace crystal to <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=285;Y=221;Z=1'>Telescience - 285,221,1</a> from <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=153;Y=225;Z=1'>Vox Trade Ship - 153,225,1</a>
[20:08:13]ADMIN: Emok/(<A HREF='?_src_=holder;adminplayeropts=[0x300037c]'>anglosphere</A>) teleported a the bluespace crystal to <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=285;Y=221;Z=1'>Telescience - 285,221,1</a> from <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=153;Y=225;Z=1'>Vox Trade Ship - 153,225,1</a>
[20:08:13]ADMIN: Emok/(<A HREF='?_src_=holder;adminplayeropts=[0x300037c]'>anglosphere</A>) teleported a the blue-space tomato to <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=285;Y=221;Z=1'>Telescience - 285,221,1</a> from <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=153;Y=225;Z=1'>Vox Trade Ship - 153,225,1</a>
[20:08:13]ADMIN: Emok/(<A HREF='?_src_=holder;adminplayeropts=[0x300037c]'>anglosphere</A>) teleported a the bluespace crystal to <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=285;Y=221;Z=1'>Telescience - 285,221,1</a> from <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=153;Y=225;Z=1'>Vox Trade Ship - 153,225,1</a>
[20:08:13]ADMIN: Emok/(<A HREF='?_src_=holder;adminplayeropts=[0x300037c]'>anglosphere</A>) teleported a the bluespace crystal to <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=285;Y=221;Z=1'>Telescience - 285,221,1</a> from <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=153;Y=225;Z=1'>Vox Trade Ship - 153,225,1</a>
[20:08:13]ADMIN: Emok/(<A HREF='?_src_=holder;adminplayeropts=[0x300037c]'>anglosphere</A>) teleported a the emergency defibrillator to <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=285;Y=221;Z=1'>Telescience - 285,221,1</a> from <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=153;Y=225;Z=1'>Vox Trade Ship - 153,225,1</a>
[20:08:14]GAME: trade shuttle (/datum/shuttle/trade) moved to hyperspace (trade shuttle)

Looks like **someone** owes someone else an apology.

**Comment by kilozombie** [comment]
Well, I'll be damned.
Still, is this really common enough to ban Telesci from? I don't think it encourages tradertiding.

**Comment by despotate** [comment]
You're a trader. No one has visited your trade shuttle. Suddenly, sparks appear in the place where your goodies crate just used to be.

Describe the IC actions you take as revenge.

**Comment by kilozombie** [comment]
Me, personally?
I retrieve my handheld radio and politely tell Security that Telescience is stealing shit from people. I announce on radio that, hey, man, that's fuckin' rude, you can come and buy it yourself.
In case that doesn't work...
Since my goods are always spread out, they'll only steal so much. I move all my shit onto one tile and stand on it always, so that if they teleport the crate they'll take me with it. I have a flash and butcher's cleaver, and threaten the dude that did it, and tell him to teleport me back.
If I get teleported into space or something, I ahelp it. If I get teleported back into my shuttle, I'm happy. If they don't teleport me, I start smashing shit and flash, handcuff, steal ID, disposals them if they try and attack me. If they return to try and get revenge at a further time even after all that, I behead them and throw their head out an airlock.

**Comment by despotate** [comment]
>  I retrieve my handheld radio and politely tell Security that Telescience is stealing shit from people. I announce on radio that, hey, man, that's fuckin' rude, you can come and buy it yourself.

Why aren't you wearing the botanists/miners' radio lad, also security's never gonna listen because their station just got free shit, never mind that there's no RP or server culture reason for them to side with vox traders instead of telescience.

> Since my goods are always spread out, they'll only steal so much.

Yeah, this is where it ends. They only steal "so much" (I'm assuming you don't ACTUALLY evenly spread all your shit out over every tile of the shuttle) and they just stop. At least that's what seems to have happened with the two confirmed cases of telestealing so far. With preliminary scouting they will have stolen everything on whatever tile contains your most valuable shit. But let's assume they keep going and teleport you in and refuse to teleport you back. You say that 

> If they don't teleport me, I start smashing shit and flash, handcuff, steal ID, disposals them if they try and attack me. 

You're on the main station, you're fucked now. If I was security, even if I knew telescience was 100% at fault for this (not gonna happen, it'll come down to flimsy evidence and he-said she-said), I'd slap this on you because you took matters into your own hands instead of calling security:

- Vandalism
- Possession of weaponry, contraband
- Assault
- Theft

Which should be enough for a stripping, deportation, and turning a blind eye to the crew looting your shuttle. Of course, if you actually did go the hilarious route and complain to security over the radio, I'd just ignore you because there's almost nothing that would make security ever side with a trader vox over a crewmember.

Now of course this is all **_theorycrafting_** but given space law and server culture towards vox, do you realistically expect any outcome other than "get fucked" here once telescience starts nabbing your shit?

**Comment by kilozombie** [comment]
>Why aren't you wearing the botanists/miners' radio lad

I can't get Security channels on my headset, which is why I also have the station-bounced.

>(I'm assuming you don't ACTUALLY evenly spread all your shit out over every tile of the shuttle)

![expensive fortification 51 2016-12-11 214302 1](https://cloud.githubusercontent.com/assets/6062247/22408540/5446bb74-e62f-11e6-9c9a-d09a4057aacd.png)
Chikiwek Bakery

>I'd slap this on you because you took matters into your own hands instead of calling security:

I already said I called Security, you doofus. I look for the most peaceful route first in every scenario. The only scenario in which I do anything to harm the station is one in which the telescience people have escalated to a ridiculous and frustrating level, which, even if it did happen, I would not say it warrants a P O W E R C R E E P bluespace shield.

>because there's almost nothing that would make security ever side with a trader vox over a crewmember.

Maybe you're just a bit too rude as trader, and maybe as Security you're just a little too shitty to people. If this really did happen, you better bet I'm gonna ahelp your shitcurity.

**Comment by AutismSpider** [comment]
beat the shit out of telesci and the bird.

most people who use telesci do it to be massive faggots and loot shit and not help fish out space bodys etc

**Comment by despotate** [comment]
Your pic is really comfy but there's almost nothing to steal in it given you're going for a voxponics-style trader. 

> If this really did happen, you better bet I'm gonna ahelp your shitcurity.

Is it even possible to ahelp the entire security department for "ignoring" someone? I mean I wouldn't _actually_ act like this if I had the time to listen to both sides and judge, but realistically security being the rushed, understaffed clusterfuck that it is, they'd deport first, ask questions later.

Anyway, I'd argue that it's not powercreep to bluespace shield something that 1. is its own self-contained ship 2. owned by jews who would of course bluespace shield it 3. can have shit effortlessly stolen from it with no drawbacks, as we've just discussed.

**Comment by AutismSpider** [comment]
like to make a note super matter room has no bluespace shield so people can teleport to start sparks in the room or pull the shard out.

**Comment by kilozombie** [comment]
If the standard is that anything with high-value things should be bluespace shielded (a reasonable one), then maybe this issue makes sense. But where should the line be drawn? Should you be able to port the lockers out of Security, or should all of Security be bluespace-shielded? Should you be able to port all of Engineering's equipment?

I don't know all the places that are currently shielded, could those be made clear?

**Comment by despotate** [comment]
> Should you be able to port the lockers out of Security

I'd go with yes because they're locked (EMPing them would depower the taser/batons inside) and because it's stealing from another department, especially the department with full power to ensure justice. The reason I'm opening this issue to shield the vox traders is because, as much as we want to pretend they don't, security and the chain of command will go much harder on the telescientists if they're stealing from other departments than the birds.

**Comment by despotate** [comment]
Also I believe that only the AI core, vault, and armory are currently shielded, along with a bunch of vaults.

**Comment by ghost** [comment]
Captains office, and bridge, and some other areas too

**Comment by Durgen** [comment]
\>calling security when you get robbed (or assaulted) as trader

Security will never help traders unless they smell antag valids. If you've been griffed and it wasn't a Ling, vamp, cultist, etc they won't care.

**Comment by Intigracy** [comment]
@Kurfursten https://boards.fireden.net/vg/

**Comment by jknpj** [comment]
Just make the bluespace crystal teleport-proof.

**Comment by Kitfox88** [comment]
Can't do it because uh, conflicting wave interference or some shit, technobabble whatever. Blam, can't telesteal the one thing traders have that telesci might want.

**Comment by Kurfursten** [comment]
Honestly it is a grim artifact of the past that the same department that makes bombs gets to be the department with the teleportation console.

Some day we'll give paramedics the telescience room.

**Comment by Probe1** [comment]
cough
https://a.pomf.cat/jdutmc.png

**Comment by despotate** [comment]
Cool, so they're gonna start stealing the bottles of peridaxon, rezadone, and nanobots instead of the telecircuits.

**Comment by kilozombie** [comment]
Telescience was a mistake

**Comment by kilozombie** [comment]
OK, but real question time: if a doctor visits the shuttle and knows where the bottle of rezadone or peridaxon or whatever is, what kind of dipshit goes and spends 5-10 minutes getting telesci to retrieve it instead of just, y'know, _buying it?_ Max it's going to cost is, what, 100 credits?

I don't disagree with you here, but these telescience terrorists are bigger jews than the actual birds are, and that's saying something.

**Comment by despotate** [comment]
Yeah, who would ever think of starting unnecessary conflicts in this game?

**Comment by Kurfursten** [comment]
I don't think giving tsci to medbay would stop stealing, but it would at least reduce telebombing and increase paramedic body recoveries.

**Comment by AutismSpider** [comment]
@kilozombie just buy it and pray we have a Service borg to drop the rezadone/peridaxon

**Comment by despotate** [comment]
Oh, that brings up something else.

Borg law 2 open the shuttle doors and stun the trader while I loot his shit.

Hasn't happened, but if it ever did, would any admins not treat it as an IC issue?

**Comment by Kurfursten** [comment]
Did we ever take AI access off the trader shuttle? I think we agreed it was dumb the NT AI can send the trader shuttle away, stranding the trader on the station.

**Comment by kilozombie** [comment]
I mean... you can't just remove crew bullying traders.
That's kind of a given. If you're being harassed or treated badly, either suck it up or be more robust. Borgs can't press buttons they can't see-- activate your shutters.

**Comment by despotate** [comment]
Crew can telesteal your shit and send your shuttle away every shift without any IC or admin consequence. There's no robusting your way out of this. There's no "sucking it up" other than accepting that NT will simultaneously bitch about tradertiding while refusing to cooperate with the job, because that's all that's left when """bullying""" (meaning powergaming the Trader to uselessness, I've had more than my fair share of getting disarmed or my crates stolen on the station and I'm 100% fine with that) is openly encouraged by the IC and OOC rules.

Vox shuttle AI access is hell, by the way. Once a comdom wanted to bring me to the brig for a retarded reason, I refused because I hadn't left the shuttle all shift. He sent a security borg after me. I hit the shutters button and the borg just opens them. I close the entrance door and it opens it. I block the entrance door with my farmbot and welder tank and it opens the sales window instead and lobs a few tasers through. I run to the cockpit and close the door behind me, but it reopens it and sends more tasers through. I try to run up to it with my flash and it uses the cockpit shuttle console to send the shuttle back to try to stun me with its departure. I manage to survive that hellhole for two entire minutes (it just kept spamming depart to make me buckle down to try to hit me with a taser through the window) with a combination of buckling, spamming doors, spamming buttons, and dodging tasers. I run up to the bot with flash in hand but get tased before I can flash it.

Kurfursten even made a mildly infuriating related comment on the previous issue about this https://github.com/d3athrow/vgstation13/issues/11752:

> Satisfied? I should point out that I only use the nook op shuttle as a specific example because other things are not as locked up tight.

>> Trader can still smash a window

Fucking WHY is it the expectation that Traders are the ones who should be smashing the windows out of THEIR OWN SHUTTLE to escape instead of the monkeys being the ones who should smash the windows to enter?

> Borgs can't press buttons they can't see-- activate your shutters.

They can open the door shutters no matter what and then open the window shutters through that. They can also open the window shutters by backing up into the station's double airlocks where they have vision of the button through the window. From there it's an easy path to fucking with the rest of the ship.

**Comment by ThePlapatin** [comment]
Despotate is the king of "this thing personally inconvenienced me one time so it should be completely removed"

**Comment by Anglosphere** [comment]
If I remember right. I was antag during that round when I stole from the birds. I even announced on the radio I was stealing from them. 

In all my rounds playing Science, I think that's the only time I've ever seen any one steal from the trade ship. I went to the ship, asked about the pricing on the crystals, the vox said he wanted guns, so I just made a quick coordinate calculation while I was there and swiped them when i got back to telesci. I then yelled about taking them on the radio. 

I'm sure it happens from time to time, but it seems to be extremely rare. 

Even so. An artificial blue-space crystal can be acquired fairly easily, and trading 1 artificial blue-space crystal for 5 or so natural blue-space crystals is still worthwhile.

Giving the vox shuttle, and vox outpost bluespace protection seems pretty snow-flakey when almost every department is susceptible to theft from telesci.

**Comment by ThePlapatin** [comment]
It makes absolutely no sense that the vox outpost of poor birbs would have shielding from nanotrasen's high end teleporter. It makes perfect sense that secure areas like the armory and places like centcomm is safe, nanotrasen would obviously block scientists from getting into those areas. The vox outpost is on nanotrasen's asteroid and they're too poor or weak to care about if they get annoyed. Why would nanotrasen extend the anti-telescience area to their outpost? It benefits the company in no way.

**Comment by kilozombie** [comment]
>the person who stole those crystals that one single time was a fucking antag

despotate, man... you've gotta stop doing this. I tried to sympathize, but I'm reading more, and... again, this is an extremely rare occurrence and not worth giving birds magical protection towards. You're not being reasonable.

I asked,
>Is this really a problem, or is this another case of you extrapolating one round to many rounds? Because that's what this feels like.

You replied,
>It's happened to me once

So I'm pretty sure that's what's happening here.

**Comment by TheFriggenSawbones** [comment]
@ThePlapatin you don't play on our server.

**Comment by ghost** [comment]
N.O. You shitty griefing fucks kidnap, trader tide, trader upload, and otherwise are such obnoxious cockroaches that getting teleshielded is unacceptable. Take it up with sec, when they don't care take it up with the admins, when they don't care go to to forums. It's a two-way street. If you want teleshielding then traders would have to be whitelist only with even stricter rules to keep it clean.

**Comment by despotate** [comment]
@Anglosphere 
I think you missed the point I alluded to around the tenth or so comment, which is that vox are not "other departments". Vox don't get protected by security like "other departments". Vox aren't allowed to be on the station unlike "other departments", nor do they have the clean opportunity for revenge - if anyone saw a Vox try to hack into telescience, regardless of their intent, they'd space or husk them as soon as possible. The Trader operates solely off a stockpile of goods and it just lies around on the floor of the shuttle waiting to be stolen, unlike "other departments" who might rely somewhat on physical items but for the most part rely on consoles, machinery, and access to do their job, as well as being mostly able to replace the items that get stolen anyway.
@ThePlapatin
Does anything indicate that bluespace shielding is an expensive or limited good? It's entirely possible that all bluespace shielding involves in-lore is adding tinfoil to the wall and floor insulation, and the reason why NT doesn't bluespace shield all the less-important parts is to allow telescience to retrieve bodies from those places in case of emergency. Traders faced with the choice of protecting their wares or allowing NT to save bodies from their shuttle would obviously start applying tin foil right there and then, probably the least expensive part of their shuttle.
And if I'm not mistaken, we've already bluespace various unrelated space vaults because of the propensity for telescientists to nab shit from there roundstart for easy loot, so it's not breaking precedent to give that ability to the vox Traders as well.
@kilozombie 
It's something that's happened multiple times as seen in the discord and Kurf's comment; antag status doesn't exactly matter here when the exact same thing is possible as a non-antag without reperecussion. But that's beyond the point. You wouldn't add a new vault and then decide whether or not to bluespace shield it based on how often it's done in the subsequent months of gameplay; you'd decide to bluespace shield it based on whether it inherently needs it.
@SarahJohnson489 
Teleshielding only helps legitimate Traders, why would you be against it because of Tradertiding? Do you really think that making it easy for people to steal legitimate Traders' shit isn't just going to encourage Tradertiding?

**Comment by kilozombie** [comment]
Giving birds some magic protection against something insanely rare and that shouldn't really be preventable sets a precedent. "It's okay to give birds anything that makes their lives remotely easier."

I mean... c'mon. We're talking about two or three instances of thievery on _one_ item, using a method which actually results in your shuttle being _less_ damaged than any alternative. Traders really don't need this, and they don't need somebody saying they can have superb protection against anything that happens to inconvenience them once or twice a year.

**Comment by Exxion** [comment]
Telesci can still steal nearly anyone's shit. Doesn't have to be traders. Why give specifically traders protection?
My favorite thing to do if I see sparks is move my valuables around and place strongly-worded letters where they were.
But getting your shit telestolen is an occupational hazard when trying to sell to sociopaths with a teleporter.

**Comment by despotate** [comment]
> Giving birds some magic protection against something insanely rare and that shouldn't really be preventable sets a precedent.

"Insanely rare" should apply to things like the immovable rod striking exactly the Trader ship, not something that in theory can be done every round with a 0% chance of failure or repercussions but isn't solely because the server's audience manages to be more mature than that.

I don't understand why I have to keep restating this but ALL a Trader owns are the possessions on his back and floor. If it gets stolen he has nothing else to do but grow chicken crops and Tradertide. Let's pretend telescience had the ability to steal anyone's ID out of their pocket and wouldn't receive and IC or admin punishment for it. Would you call this a "rare" and "unpreventable" event that you should just suck up?

> Why give specifically traders protection?

Did you read the first five times I stated why Traders are specifically different from other departments when their shit gets stolen?

- The only thing Traders have is their irreplaceable possessions and voxponics. All other jobs can get their shit stolen, sure, but usually the items they use are replaceable and unimportant because the real bulk of their work is done in consoles and machinery, etc., none of this applies to Traders, if your shit gets stolen, all you have left is to Tradertide or vox hydroponics.
- No one will cooperate with Traders to retrieve their items.
- Traders will get shot for stepping onto the station to try and retrieve their items. Basically, unlike every single other job, they can do nothing to prevent or take revenge on telestealing.
- Their ship would obviously be tinfoil-shielded. They clearly understand security which is why they have a securivend, why wouldn't they also wrap their shuttle in tin foil?
- In general, the practice has been to bluespace shield important non-NT areas such as space vaults. Same should apply to non-NT shuttles.

Fundamentally making it easy as pie to steal shit from the Traders without retribution has its future consequences. You can't balance an economy or a job that bases itself on trading around a situation where x% the time all of its possessions can be taken away with no consequence to the thief whatsoever.

**Comment by ghost** [comment]
Talk to the admins if security does nothing and at worst just keep logs of the teleporter, log dive, and make a ban request if it's a common occurrence as it's a violation of server rules at that point. Consdier that the reason people kick the shit out of traders aboard is because they're such unrepentant repulsive shitguzzlers that it's a public service to put them down.

The only teleshielded space vault is the gooncode chamber and that is only because it's an rp macguffin for starting adminbus. It does NOT protect the many other valuables. Only the gooncode core.

It blocks rescue teleports mid-fight/kidnapping before the suit is stripped or turned off. It prevents zapping past prox-trapped entrances to the trade outpost. Protection for when those fucking niggers first step over the line is not worth it. Take logs and you'll clear out all 1 big bad telescience boogemen.

Trader tiding and teleniggering is an issue to be handled at the admin and log collection issue level. Not the code level. Knock this the fuck off. They shouldn't get the same protection a head/AI core has over shit everybody else has to put up with and there's no excuse for people griefing legitimate traders which is why you have to keep repeating it. Cause you can't get it through your thick skull buried under all that sand.

**Comment by kilozombie** [comment]
Traders getting bullied is part of the job. It's stupid to arbitrarily remove ways to do this just because they're possible and don't fit with your views.

Again, as somebody who has actually traded often (not just voxponics, mind, I have received plenty of rare goods and guns while bartering and sold those, too) it is ridiculous to assume that traders need special protection. In the past, the only 'special' things they've needed are more things to trade, as well as special rules to prevent tradertiding.

C'mon, man. Don't assume that the crew isn't going to help you out-- most of the time they might not, but if you have something to barter with or you've made friends with people on the crew, you sure as shit will find cooperation.

But if you're _you,_ despotate, maybe it's a different story. You've admitted to tradertiding on _purpose_ with the AI upload shit. Maybe you just have a rude, unpleasant, stinky attitude and the crew doesn't like you.

Even if that were the case, even if you were being singled out by telescientists, it's fucking not! It's not. You got your shit stolen by a traitor utilizing a tool which has been in the game for ages.

I've managed being stolen from. I've managed borgs fucking with me. If you're really unable to handle one bad round once in a while, maybe you should play a different job.


edit:
>something that in theory can be done every round with a 0% chance of failure or repercussions but isn't solely because the server's audience manages to be more mature than that.

People have been banned for abusing telesci round after round before. Nobody besides absolute crazy people would visit the shuttle to see what they want and THEN steal it with telesci when they could just buy it. This issue is a code solution to an IC problem that almost never comes up. When it does come up, it pretty much just creates an interesting conflict anyway, and there's not a harm to that, in my mind.

**Comment by despotate** [comment]
Chill. I've already told you being bullied is the fun part of being a trader. Telestealing causes more trouble than it's worth because

> When it does come up, it pretty much just creates an interesting conflict anyway, and there's not a harm to that, in my mind.

it seems to me you've missed the most important point I keep making post after post here: **telestealing is not an interesting conflict**. You don't know who did it, you can't do anything about it, and no one will do anything about it for you. It's the same thing as if your items just straight up disappeared. So unless your definition of "interesting conflict" is encouraging Tradertiding in response to being unable to retaliate directly to theft, I don't see how leaving the vox shuttle unshielded encourages fun bullying.

**Comment by ghost** [comment]
You don't want to retaliate because that is exactly what has created the situation you so despise. That people wont help you? That people kill you for being aboard? That's all on you and people like you. They don't care how wronged you were, they only care that you hurt them in your quest to be an asshole which permeates the playerbase as traders retaliate which provokes more abuse which provokes more retaliation.

Talk to sec. Talk to admins. Take logs to the forums and if they're really the problem you so describe they're an easy ban. Teleshielding is not the answer and it will encourage more of the power creep that you and people like you use to justify for even more.

**Comment by despotate** [comment]
Why bother teleshielding anything if administrative bans are apparently the solution to any possible bluespace oversights?

**Comment by kilozombie** [comment]
Stealing all the guns from the armory = holy shit that's bad. We can't let telescientists do that.
Stealing some pretty much valueless or useless shit from the trade shuttle = That does not meet the standard that we've protected other areas for

Bluespace shielding is NOT done to make people less upset when stuff is stolen. It's to prevent stuff (which should be hard to steal) from being stolen ridiculously easily.

**Comment by kilozombie** [comment]
>Chill. I've already told you being bullied is the fun part of being a trader. 

ctrl+f "bully", the only mention of that is you insulting people who bully traders. Ha

**Comment by ghost** [comment]
The teleshielding is primarily:
Heads/AI - protect 0 effort obj zaps
Armory - To prevent needing the roundstart loose guns in an idlocked locker
Goon code - high rp adminbus macguffin

You know god fucking damn well that there's a difference between those, the reasons why they have them and a trader's pile of shit.
