### ISSUE TITLE
Garlic, upon scanning, contains no holy water

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13739]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: c9d75a99130d6f4f684a4665c60e30fde59d7636 

>General description of the issue
I was always under the impression that garlic contained holy water, even the wiki says that it does, but in reality it only contains nutriment. I used a plant scanner on garlic that I had gotten from no-fruit, and nutriment was the only reagent it contained

>Steps to reproduce if possible
no-fruit spam until you get garlic
examine with plant analyzer.

**Comment by Zth--** [comment]
How mucg potency did your plant have?

**Comment by RealestEstate** [comment]
enough to get 4 units of nutriment as opposed to the default 2 units of nutriment. I'll test it again, but I assumed there would be at least some units already present in the plant, even if under 1 unit. I'll try raising it to about 140 pot to see if that makes a difference.

**Comment by despotate** [comment]
`chems = list(HOLYWATER = list(1,25),NUTRIMENT = list(1,10))`

It's definitely in there. You probably accidentally purged something else's phytochem into it.

edit: oh, no, the issue is that you scanned the original grown you got directly from no-fruit instead of planting it. What happens when you roll for a grown with no-fruit is that the grown is created without it receiving any of the chemicals that its seeds contain, instead it gets whatever the no-fruit grown contained. So you likely purged nutriment phytochem into the no-fruit and that's what happened.
