### ISSUE TITLE
mouse is rogue blow the cheese

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13747]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
controlled mouse moves on its own near food  and it keeps moving after death

**Comment by ghost** [comment]
After death?

What the shit, I set that to only happen when not unconscious or worse

**Comment by ghost** [comment]
Seriously can't see where this would cause the mouse to move after death, it does a check to see if it's unconscious, dead, or faking death

**Comment by pvak** [comment]
not sure if moving after death was admin fuckery but the rats keep moving when they see food which makes them hard to play

**Comment by ghost** [comment]
Rats moving when they see food is a feature, making it easier to bait them

**Comment by Shadowmech88** [comment]
Could not reproduce either issue. If I possessed an existing mouse *while* it was walking toward food, my body would continue doing so, but I don't believe it's possible for that to happen in-game and can be easily fixed by walking away from the food and then returning. After doing so, my body did not continue trying to walk toward the food.
