### ISSUE TITLE
Horror form is shit

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#13893]
The game says you are inmune to stuns but that's bullshit.
They can stun you, they can flash you, attack damage is shit and ZAS fucks you in the ass

**Comment by Shadowmech88** [comment]
Horror forms are supposed to be permahulked.
So either something broke that's preventing them from getting hulk, or hulk itself is broken.

**Comment by mtpowell** [comment]
Looks like HULK is broken and has hardcoded cases into everything that would effect it. That's going to be a pain in the ass to fix.

Is hulk supposed to be immune to flashes/stuns as well?

**Comment by gbasood** [comment]
I kept saying horror form was shit and nobody believed me reeeeeee
Are you sure hulk is broken? It worked fine a month or two ago. I'd be surprised if it was that and not just horrorforms not getting hulk'd

**Comment by mtpowell** [comment]
Well Horrorform inherits from Hulk and doesn't apply any of its own anti-stun/anti-blind code, so I'm assuming Horrorform should have that or Hulk already has it and it's broken.

Someone correct me if I'm wrong, I'm still new to this codebase

**Comment by Shadowmech88** [comment]
Horrorform isn't a mutation, it's a species type.
As a species, it's always supposed to receive the hulk mutation, making it literally a hulk the same as if you have the genetics power, but with no limit.

So if horror forms are getting stunned, it's because either they're not receiving the hulk mutation like they're supposed to, or the hulk mutation itself is broken and now stunnable.
