### ISSUE TITLE
Assuming a sane movement speed system was implemented, how should things affect your speed?

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13903]
Immediate thoughts:

Should hardsuits slow you down again? (trick question they should)
Should galoshes/clown shoes slow you down as they were meant to?

Hyperzine: Junkie gofast drug, or muscle stimulant?
This one's tricky. Historically, hyperzine has always been used to bring you TO your "top speed", not INCREASE your top speed. Obviously, a higher top speed is a very strong thing because then you can outrun everyone else. Personally, I think hyperzine should continue to be "a thing you take when you have a hardsuit so you can move like you didn't have a hardsuit", and a chemical that increases your top speed should be added separately.

Hyperzine+magboots? I know Nuke opened an issue on this but it got bandwagoned pretty hard, I want to see honest opinions here

Should hardsuits slow you down to HALF YOUR FUCKING SPEED (as they were before) or be something like 30% slowdown?

Currently walking is 7 times slower than running. Should that be upped a little?

**Comment by aceedex** [comment]
On one hand hardsuit slowing you down means that hardsuit or no hardsuit has a significant value on combat, and that is great.
on the other hand mining will be a nightmare to play with ANY slowdown. if mining hardsuits were spared I'd say go for it considering they have no special properties

**Comment by 9600bauds** [comment]
Mining USED to have a slowdown.
They were hyperzine junkies.
They didn't complain, because all the hardsuits had a slowdown.


Also, goliath skin compatibility is a special property

**Comment by kilozombie** [comment]
I have only played with slowdown hardsuits on other servers, and they seemed like a decent thing-- but yeah, mining is misery with slowdown, so either they'll have to start doping on hyperzine again or mining hardsuits shouldn't be nerfed. But then you can make the argument for making atmos suits fast, and so on.

**Comment by Lokiamis** [comment]
I'm all for restoring old move speeds on items and speeding up walking. Fuck walking. Realize, though, that you'll forever be the guy who pissed off 100 people by making hardsuits slower.

**Comment by 9600bauds** [comment]
And the man who first nerfed toolboxes back when they were 20 force pissed off a hundred greyshits.
Nobody remembers who he was.

**Comment by Sprok0** [comment]
You could just make mining hardsuits have no slowdown on asteroid turfs, because they have the right boots or something for the terrain.

**Comment by Probe1** [comment]
Remember when wearing a hardsuit slowed you down?

Probe remembers.

Bring back balance/hyperzine addictions.

**Comment by nuklearcellphoneg** [comment]
My standpoint usually boils down to the following:

Does something give you an advantage?

Does it give you an at least equal disadvantage?

If no, then it's basically unbalanced- to focus on what I've already brought up, hyperzine + magboots: The only disadvantage someone pointed out was that you must eat hyperzine and continue doing so in order for it to continue working. 

That's not a disadvantage, that's a precursor for the advantage.

**Comment by kilozombie** [comment]
>Does something give you an advantage?
>Does it give you an at least equal disadvantage?

This is a really dumb method to test 'balance' on. For instance, jumpsuits have no downsides and give you tons of pocket space, belt space, and ID space.

**Comment by nuklearcellphoneg** [comment]
That's not an advantage, now is it?

**Comment by nuklearcellphoneg** [comment]
Jumpsuits, that is something everyone starts with, across the board... an MD has a slight advantage, for example, over a cargo tech, because they start with a coat, with two pockets and its own exosuit slot.

**Comment by kilozombie** [comment]
I'm losing track of what you're trying to say. My point is, that's a flawed metric to try and balance something on, especially in a game where so many people play. Many would disagree and say that hypermagboots is not unbalanced because ZAS is so harsh.

**Comment by nuklearcellphoneg** [comment]
If EVERYONE starts with a jumpsuit, its advantages/disadvantages are basically null(everyone has them, so it doesn't give any advantages).

People must obtain magboots, so then they give you advantages/disadvantages not available to people who have not obtained them.

I'm not sure at what point it became such a hassle to toggle the magboots on and off?

At any rate, it's a good thing to consider when adding any item or new facet of gameplay. Consider for example, cancer- many disadvantages, with an arguable lack of advantages. And anyway, you're not done once you consider Advantage vs Disadvantage; next is to multiply it by the assumed amount something it can be used.

Good example of that is mechanics, in its beginning(whoever implemented it did not initially consider 'okay, they can clone anything... what if I multiply this ability with emag x 50?')

And so, to go back to suits/exosuits, here is an issue we stand at:

1 What are the advantages of various armors
2 What are the disadvantages ' ' ' ' ' ' ' ' ' ' ' ' '

I'd argue we could use a slight rework of exosuits in general, to change how their preventing damage etc etc and other things work(which unfortunately I think covers a LOT of different items).

There is a chance iirc to completely negate damage, or not with armor. This is awful and just adds more rng to the game rather than thoughtful play style, which routes back to my initial point on Hyper+Mag:

Instead of keeping your magboots in your bag, for when you think, 'I will need them' or for when you've been alerted to a situation where 'I ought to go ahead and put these on' or thinking 'I better turn on my magboots before I open this firelock' or 'I need to make sure I have space in my bag for my shoes/magboots, as I will be switching back and forth' you just leave them on 4ever with no thought.

You equip the 'best' item and make sure to kill its disadvantage with its supplement item and thus ends your thoughts on it.

Specifically on Magboots and ZAS though, ZAS itself could use some work... and I'm not really sure why we don't have the ability to brace for the incoming ZAS, when you know it's coming, by grabbing bolted items down(tables, bolted chairs, etc) in order to prevent ZAS from sucking you away, and, if ZAS is too strong, to at least mitigate the damage caused by it, by bracing beforehand.

**Comment by kilozombie** [comment]
I think ZAS is currently Not That Bad. The only real part about it I dislike is the sudden and unexpected 'you are knocked over by wind for 10 seconds and this is never explained'.
A majority of the rest of the time you can predict it. I think people like hyperboots because they can focus on other things besides utmost caution with ZAS. I've certainly used and abused it as a Head of Staff during newcops, and without it I would have probably been too slow and died. Many firelocks, sudden explosions, etc.
Whether or not that was overpowered or powergaming or whatever, I don't think I'm a good judge.
Also as note-- why take off the boots and swap with your shoes if you can just toggle the magboots? Also, if you want some Real Pro ZAS Tips, just buckle into a chair to save yourself. And if no chair's nearby or you're on the move, drag an office chair behind you and buckle in (it won't move)

**Comment by uazuaz** [comment]
what if an higher slowdown is applied in a pressurized environment?
so, people will stop to use the hardsuit when unnecessary (inside station) but have a lesser penalty when a hardsuit is necessary (in space, on the roid).

**Comment by jakmak5** [comment]
uazuaz that actually does sound pretty good. No slowdown in low pressure enviroments/roid to make it not a total bitch to walk in with a hardsuit while in normal livable environments it gives you the slowdown

**Comment by Blithering** [comment]
Definitely in favour of uazuaz's suggestion, it can be explained away as being outside the gravity generator's (when) area of effect and therefore no longer encumbering to use. Also random suggestion: take hyperzine's current effect, slash it in half and give it to brawndo. Make hyperzine able to increase your max speed beyond the standard but add in side effects that would make it impossible or hugely undesirable to be on it the entire round. Crew aren't so reliant on chemistry to counteract magboot speed and brawndo really does have what plants crave.

**Comment by 9600bauds** [comment]
I'd probably get screamed at by somebody if I checked your turf's pressure level EVERY SINGLE TIME YOU ATTEMPT TO MOVE
Maybe keep it exclusive to the asteroid, even the pressurized parts, handwave it as saying "there's less gravity there lol"

**Comment by 9600bauds** [comment]
Also you already suffer no slowdown from literally anything when moving along space tiles, i.e. skirting the outer hull

**Comment by nuklearcellphoneg** [comment]
I think folks forget how much slowdown we used to have?

**Comment by 9600bauds** [comment]
noted so in the OP, the smallest amount of functioning slowdown made you twice as slow

**Comment by uazuaz** [comment]
@9600bauds 
how does the proto-kinetic accelerator check work? couldn't that be applied on the hardsuits?

**Comment by Yelier** [comment]
Would be a nice way to curb powergaming. Hyperzine would need some changing, though.

**Comment by 9600bauds** [comment]
OK

Very important questions

Should hyperzine prevent pain slowdown?
Should hyperzine prevent fatness slowdown?
Should hyperzine prevent hypothermia slowdown?

**Comment by Intigracy** [comment]
Yes
No
Remove
