### ISSUE TITLE
Infinite soulstones and shells

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13938]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)0bed6bce8085eeecf24c46f9b4fc089ca2b847c2 

>General description of the issue
You can constantly refresh artificer cooldowns by changing them back to artificer while on an armor rune.

>What you expected to happen
Cooldowns to be reset to zero

>What actually happened
infinite soulstones and shells

>Steps to reproduce if possible
put artificer with cooldowns on armor rune and change back to artificer

**Comment by N3X15** [comment]
Automatically applying controversial for exploitable balance thing

**Comment by kilozombie** [comment]
It's OK, this isn't controversial, this is objectively just a bug (tm)

**Comment by Shadowmech88** [comment]
It's more of an oversight than a bug.

**Comment by Aurx** [comment]
Would we agree that it's not controversial, but there is controversy as to if it's an oversight or a bug?

**Comment by Allspice** [comment]
Sounds about right.

**Comment by kilozombie** [comment]
Get the popcorn this is surely going to be an argument
(shadowmech's right it's an oversight)

**Comment by Allspice** [comment]
I guess I'll repeat what all was said in the coder discord (N.b I'm about the only person who ever used the trick that I'm aware of, alongside one or two people that I personally taught it to):

So far as I know, the cult armour thing works because it creates a new construct mob, places the player in it, then deletes the old one. Artificers like any other mob are created with not-depleted cooldown timers, so they can just immediately pop out a new stone and shell when they're type-changed. So it's like medical waterpotas in that the implementation produces an "interesting" consequence.

Anyway. The trick is consistent with other cultist mechanics like rune imbuing, where you turn the time required to write a rune into a consumable resource (talismans or construct parts). Additionally, I like the way it contrasts with wizardly constructing: Wizards can create shells, and therefore new constructs, in the field but are limited by their soulstone count, and if they run out of artificers and soulstones that's the end of the constructing; Cultists can crank out them soulstones for cheap if they dedicate the time to it, but it's largely impractical to crank the buggers out without returning to your cult base first.

Furthermore the only practical way I can tell to directly fix the cult armour thing, IF it is decided to need fixing or what ever, is to start artificer cooldowns at 0 for stone and shell. If that's not done, you can still daisy chain soulstones by first turning your victims into artificers, making them pop out a stone and shell, then armouring them into a jug or wraith to produce more victims to turn into artificers to make stones to jugwraith and so on.

But if the arti cooldowns started at 0 without any other changes I would be sad along with perhaps some others, since it takes three minutes to produce a shell and a full five damn minutes for a soulstone. That would be an annoying wait to kick off an artificer cult, and would also penalize wizard constructing too, especially considering how you especially need to hit the crew hard and fast with wizcult.




If it's a lot of words for a niggling thing, my B.

**Comment by AI-Is-Rogue** [comment]
Could the cooldown being reset to zero be tied to the rune alone?

**Comment by Allspice** [comment]
Then you'd just get daisychain artificers getting turned to the more violent forms.
