### ISSUE TITLE
Plasmamen don't cool down

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14035]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
610292f026f13396fe13bf0f105a4920a89695fc 

>General description of the issue
They don't naturally cool down anymore, meaning if they catch on fire once and don't put it out quick enough, they'll burn to death regardless of their suit being on and the fire being out.

>What you expected to happen
to, you know, go down in temperature

>What actually happened
it doesn't go down

>Steps to reproduce if possible
be plasmaman
set yourself on fire
watch as you never cool down

**Comment by gbasood** [comment]
I mean it's from sawbones who generally knows his shit but that's weird
I don't remember anything touching this code for awhile

**Comment by TheFriggenSawbones** [comment]
It's been happening for awhile.

I'll take my suit off for a second and remain in like orange/yellow heat for the rest of the round.

It also seems like showers aren't effective at cooling you down, it goes about one degree every 2 or 3 seconds. I remember it being a lot faster. Like, I'd die from Hypothermia pretty quickly if I got in a cold shower.

**Comment by Blithering** [comment]
Heating and cooling happen bizarrely slowly in general, you can run through a hot room, not feel anything and then begin uncontrollably combusting while in a room temperature area.

**Comment by ghost** [comment]
It's sweating. Plasmamen have no sweat glands so can't control their internal temperature.

Just give them leporazine or toss them in the mancrowave.

**Comment by despotate** [comment]
This makes it cancer to search plasmemes in the brig for contraband gloves / eyewear because if you take too long to do so they'll die irreversibly.

**Comment by SonixApache** [comment]
the obvious solution is to remove plasmemes

**Comment by TheFriggenSawbones** [comment]
WEIRD NEW MYSTERIOUS BUGS

**Comment by jknpj** [comment]
Can confirme, giving plasmaman the HAS_SWEAT_GLANDS anatomy flag solves this because <s>thanks celt</s> the only way natural thermo-regulation can happen is if you have sweat glands.

So we either give plasmaman some kind of coolant or give them sweat glands to fix this or we label it as a FEEEEEAAATTUUUURREEEEEEEEEEEE and leave them unable to bandaid themselves without dying.

**Comment by SonixApache** [comment]
Consume frost peppers / frost oil?

**Comment by PJB3005** [comment]
> only way to thermo regulate is with sweat glands.

That's not how temperature works. There's still passive heat loss from conducting to the environment...

CELT.

**Comment by Exxion** [comment]
I'd like hypothermia if it weren't just so poorly-coded and poorly-thought-out

**Comment by SonixApache** [comment]
The suits probably have perfect heat retention.

**Comment by Exxion** [comment]
I'm about 90% sure that's not even a thing our current heat system takes into account

**Comment by gbasood** [comment]
Heat retention afaik isn't a thing no
Just heat resistance

**Comment by SonixApache** [comment]
I'm talking about the `heat_conductivity` var. It's why you can go into space in a firesuit.
It determines how quickly your body adapts to your environment.

Plasmaman suits are just children of basic space suits, which have `heat_conductivity = SPACESUIT_HEAT_CONDUCTIVITY`
__DEFINES/setup.dm says
`#define SPACESUIT_HEAT_CONDUCTIVITY	0	// until a time where space is no longer cold`
Which is why they'll never cool or heat on their own.

**Comment by jknpj** [comment]
Even if you remove your suit and get under a cold shower your temperature won't go down, i've tried it before crawling to medbay with 89 burn damage thanks to a toy facehugger dropping my helmet.

**Comment by SonixApache** [comment]
@jknpj isn't that just because plasmemes are hardcoded to burn?

**Comment by jknpj** [comment]
No, being under a shower prevents you from burning
