### ISSUE TITLE
FTL Vault Bugs

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#14061]
@Probe1 

![untitled](https://cloud.githubusercontent.com/assets/9782036/23055174/003aeb52-f4aa-11e6-9c2b-4bf11e797271.png)

**Comment by ghost** [comment]
Would refresh parts not work on that AME?

**Comment by Kurfursten** [comment]
It did not

**Comment by Probe1** [comment]
Yeah that "mapping AME" code didn't really work but I was done with it so I left it as it was.  The second image is because the bottom room shares the same area as the top room which already had a PC and to save work I just replaced the APC with a frame. 

I won't lie I'm not gonna fix any of this.  The AME is bad code and the APC is just some flavor.
