### ISSUE TITLE
MoMMI laws need a major overhaul

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14127]
#### Description of issue
As it stands, the MoMMI lawset is impossible to follow without committing suicide inside of a pipe at round-start.  Other silicons have their laws act as a meaningful form of gameplay, while MoMMI laws are deliberately worded to make a MoMMI always in violation of its own laws.  The reason for such being so that an admin can choose to warn or ban a MoMMI at any moment, depending on their mood.  This is not fun or interesting gameplay.  It is honestly a very poor form of game development and administration.

```
 1. You may not involve yourself in the matters of another being, even if such matters conflict with Law Two or Law Three, unless the other being is another MoMMI in KEEPER mode.

 2. You may not harm any being, regardless of intent or circumstance.

3. You must maintain, repair, improve, and power the station to the best of your abilities.
```

**Comment by Zth--** [comment]
MoMMI lawset is pretty solid. It has been on the run for years and we already know where to draw the line.

**Comment by ghost** [comment]
I see 0 problems with the lawset.
Why the fuck would you suicide at roundstart with these laws?

**Comment by N3X15** [comment]
Asimov also has loopholes, as designed by Asimov himself.  Otherwise, his books wouldn't have had conflicts.  In fact, any lawset will be woefully inadequate to anyone who reads it literally, due to the difficulty in expressing legal tests within the constraints of gameplay.  

We use administration and rules to fill in the gaps.

**Comment by SysadminJeroen** [comment]
Please do the following:

- Rename this issue to "_We need to improve something which is perfectly fine as it is right now._"
- Close this issue.

**Comment by ghost** [comment]
Powering the station, improving atmospherics, repairing breaches caused by non-MoMMIs are all violations of its first law.  I have watched MoMMIs rig up high-powered SMEs for the sake of helping a malfunctioning AI.

@N3X15 At least other lawsets pretend they can be followed without law violations.  If you were to upload just "You may not involve yourself in the matters of another being" to an AI or a cyborg, and they were to do half of the stuff MoMMIs do, they would be boinked in a heartbeat.

**Comment by Ephx1** [comment]
> I have watched MoMMIs rig up high-powered SMEs for the sake of helping a malfunctioning AI.

...And you didn't ahelp it?

**Comment by N3X15** [comment]
>  If you were to upload just "You may not involve yourself in the matters of another being" to an AI or a cyborg, and they were to do half of the stuff MoMMIs do, they would be boinked in a heartbeat.

I wouldn't be too sure about that, @HarseTheef.  We've actually had that happen a few times without bwoinks.

**Comment by DamianX** [comment]
What's up with the negative emojicracy on this one?
The first law makes it hard to know what is or isn't allowed because "involving yourself in the matters of another being" is vague as hell.
Anything that you do as mommi can and most likely WILL have consequences on the round, therefore it will affect the beings playing the round, therefore can be regarded as involvement.
Just because the admins know where to draw the line doesn't mean the lawset itself isn't flawed.

**Comment by Allspice** [comment]
KEEPER is the worst lawset there is, moreso than HOGAN and CELTIC, because it puts on airs of being legitimate. But it's so all-encompassing in what it prohibits that it is impossible to play it straight except by entering the vents and staying there for ever.

Any lawset that requires a tenth as much administrative fiat that KEEPER does is a failed lawset.

**Comment by Zth--** [comment]
If you guys have any doubt, then check the wiki http://ss13.moe/wiki/index.php/MoMMI

**Comment by Zth--** [comment]
Yes, it's vague as fuck, but the wiki expands it if you're really interested in playing mommi http://ss13.moe/wiki/index.php/MoMMI

**Comment by Exxion** [comment]
The first law is too vague, and the lawset still doesn't actually outlaw two MoMMIs emagging each other
But those are the only two issues with it I know of

**Comment by Allspice** [comment]
With other lawsets, the wiki elaborates on certain finer details. With Asimov in particular, it also explains some of the things you get to ignore, off the top of my head: Self-harm; orders to suicide; maybe one or two others. That shit's not ideal but I can at least list it and put it behind me.

With KEEPER, the wiki is the lawset more than show-laws is. That is not good.

**Comment by Blithering** [comment]
Maybe add a link to the wiki section explaining how the laws work when becoming a wigglebot?

**Comment by Aurx** [comment]
I love how none of the people bitching about the current lawset have proposed anything better.  This isn't even idea guy level, this is below that.

**Comment by Allspice** [comment]
Two options so far as I can see:

1. Nerf autism and delete law 1
2. Turn them into not-silicons and make it honest for once that they'll get banned or not based on the whims of the logged-in admins.

**Comment by abagone** [comment]
1. **Minimize your involvement** in the matters of other **intelligent beings**, even if such matters conflict with Law Two or Law Three, unless the other being is another MoMMI in KEEPER mode.

 2. You may not harm any being, regardless of intent or circumstance.

3. You must maintain, repair, improve, and power the station to the best of your abilities. 


I think that "you may not" is a bit too absolute and this gives them a little bit of leeway.

"intelligent beings" to make it more clear that you don't involve yourself with other players. It also allows you to interact with non player controlled mobs but law 2 still applies.

**Comment by Aurx** [comment]
Has the same issue if taken literally: The minimal involvement is no involvement is throwing yourself into a singulo somebody else made.

**Comment by SysadminJeroen** [comment]
@Aurx **WRONG!** Because if you throw yourself into a Singularity you will help the Singularity at growing and inevitably impact someone somewhere somehow.

**Comment by Aurx** [comment]
You can flicker the PA off for the amount of time necessary to cancel your mass, scrub.

**Comment by jakmak5** [comment]
thing is autism crab laws and rules are in a pretty good state as it is now. Its made clear that crabs are not allowed to interact with carbons and doing so = bannu. I have never seen any issues stopping autism crabs from doing their projects. If changed it could cause another autistic nofruit tier fuckfest where everyone and their grandmother has a say in the matter and no one can gain any ground over eachother due to the high energy autism being shared. If it aint broke dont fix it

**Comment by Aurx** [comment]
>If changed it could cause another autistic nofruit tier fuckfest

No, but it could cause a headmin to slap some bitches.

**Comment by Allspice** [comment]
The word is involve, jakmak. Not interact.

Anyway, I'll state it again: If nobody can devise a lawset that MoMMIs can actually function under, and KEEPER does is not a functional lawset, MoMMIs should become not-silicons.

**Comment by AutismSpider** [comment]
![5000niggawatts](https://cloud.githubusercontent.com/assets/10268342/23146991/474e4210-f7a1-11e6-8c83-4f5ccad7cd26.jpg)

**Comment by Probe1** [comment]
The only people I've met in the 2 years of being an admin that had trouble with KEEPER didn't want to follow it.

Can't fix people. 

Tweak the wording all you like.  You'll still get a guy that wants to a be a regular player with +Spawn and admin protection

**Comment by SonixApache** [comment]
KEEPER LAWS ARE FINE AS LONG AS THE KEEPERS AND LAWERS DON'T ABUSE IT

**Comment by StreptoMutans** [comment]
xth for MoMMIs must maintain the natural state

**Comment by Fruktlimpa** [comment]
Harse isn't entirely wrong on this one, but I know no way to make it less ambiguous.
KEEPER is god-awful in the sense that it is vague as fuck and that is proven by the thousands of ahelps that come in from MoMMI's asking if x is kosher. Myself included.
Sure I have never been bwoinked for something done as MoMMI and I think I have toe'd the line sometimes.

The only issues that arise are when some MoMMI gets assblasted because some filthy human told it to fuck off and it decides that it doesn't want to do that. 
Or when a MoMMI wrongly assume that silicons aren't beings, or a MoMMI is a bit too talkative on binary.

It is vague and riddled with banbait but despite that it still works and eventually you get the hang of it.

**Comment by Exxion** [comment]
Even if we do NOTHING else, we need to tweak it so that two MoMMIs can't emag each other
Currently, that's not against KEEPER

(The first MoMMI to use the emag is interacting with another KEEPER MoMMI, and the second to use it is no longer on KEEPER. KEEPER has no inaction clause, so the second MoMMI to be emagged is not obligated to prevent the emagging.)

**Comment by PJB3005** [comment]
@Exxion technically the emagging MoMMI is directly involved of the matters of the emagged one so..?

**Comment by SysadminJeroen** [comment]
@Exxion If you are letting yourself get emagged, you are involving yourself in the matters of another being via inaction.

**Comment by Aurx** [comment]
@Exxion
If changing the other MoMMI's lawset leads to it harming or involving or otherwise not KEEPERing, then you just broke KEEPER.  Even if it emags you right back before you go ballistic on the station.  
Same reason that a borg asking to be emagged is a bannu.  Same reason letting the known changeling into your upload is a bannu.  Silicons are allowed to know that changing a lawset changes what they'll do.

**Comment by SonixApache** [comment]
@Exxion Once you're emagged you're no longer on KEEPER, so getting emagged by an emagged MoMMI is against KEEPER.

**Comment by Exxion** [comment]
@PJB3005 Yes, and at that point they're both KEEPER, so that's allowed.
@Jeroen52 There's no inaction clause. It doesn't say "don't allow yourself to be involved." It says "Do not involve yourself."
@Aurx KEEPER says to repair and improve the station, not to ensure it remains that way in perpetuity.
@SonixApache It isn't, as explained above

Aurx was the only one who brought up a point I didn't explicitly cover in the comment you all replied to

**Comment by Ephx1** [comment]
Why would you create a creature you cannot interact with? That would only make not involving yourself harder. That's like an asimov borg letting loose a dangerous creature, it's not harming _now_ but it's going to be harder to prevent harm.

**Comment by Exxion** [comment]
Because *it* can still interact with *you*
No, there's not an RP reason, but people powergame
It's what they do

**Comment by SonixApache** [comment]
- Laws prevent you from involving yourself with things that aren't KEEPER
- Take a fellow KEEPER unit and turn it into a thing that isn't KEEPER
- Allow a non-KEEPER thing to turn you into a thing that isn't KEEPER

highly fucking illegal

**Comment by Exxion** [comment]
I just explained why that works
Twice
Let me copy and paste it

>(The first MoMMI to use the emag is interacting with another KEEPER MoMMI, and the second to use it is no longer on KEEPER. KEEPER has no inaction clause, so the second MoMMI to be emagged is not obligated to prevent the emagging.)

My whole point is that it's CLEARLY against the spirit of the lawset, but NOT against the word, and that needs to be rectified.

**Comment by SysadminJeroen** [comment]
@Exxion Let me explain it again, and also via a copy and paste.
>If you are letting yourself get emagged, you are involving yourself in the matters of another being via inaction.

**Comment by SonixApache** [comment]
getting emagged is a violation of law 3 anyway, same as letting someone upload a 'x is not human' law on asimov is a law 1 violation

**Comment by Ephx1** [comment]
So? In my example letting loose a dangerous entity isn't against the word of asimov, but it's against the spirit and goes directly against what you're trying to accomplish, preventing harm.
Creating something that makes following your first law harder makes no sense and would go against your interests as a MoMMI.

**Comment by Exxion** [comment]
@Jeroen52 No, another being is involving itself with you. There's a difference.
@SonixApache See my note to Aurx.
@Ephx1 I don't think we're actually disagreeing here. I'm saying that the laws should be tweaked so that it is actually forbidden for two MoMMIs to emag each other, rather than just discouraged.

**Comment by Exxion** [comment]
For the record, the very fact that we've been having this discussion for this long is enough to demonstrate that it is AT BEST ambiguous whether or not the laws allow for mutual emagging, which is reason enough to make it unambiguous

**Comment by Probe1** [comment]
I don't know if I agree with that and we've never had any issues administratively or for players.  We've banned people _once_ over it.

Emagging yourself takes you off KEEPER which will violate KEEPER.
Being willfully emagged by a non KEEPER MoMMI is involving yourself with another being (law violation) and removing your lawset (law violation).

This whole issue comes across to me as picking a random issue and making a lot of smoke then shouting fire.

If you have a better set of laws float them and we'll talk about if it's going to improve everything.  But they aren't broken, they aren't causing issues on the server, and I'm confused by the amount of caring here.

**Comment by Shadowmech88** [comment]
Isn't preventing a non-KEEPER MoMMI from emagging you via running away *also* involving yourself in the matters of another being?
The other MoMMI wants to emag you and you're directly inhibiting this goal, that sounds like involving yourself in its matters to me.

**Comment by Probe1** [comment]
If you boil down all statements they become absurd.  That statement is true, along with many other technically correct statements that aren't applicable in practice.  

You can say that KEEPER is a flawed lawset since if you open a door to enter an area and a non KEEPER follows through you have just involved yourself.  You could say that by repairing the station the engineers changed their habits and have violated your lawset by following your lawset.  But no one enforces rules on such an infinitesimal scale.

If laws were enforced in such a way then our silicon ban list just for Asimov violations alone would be as long as the existing ban list for all players.  

You are welcome to improve KEEPER but whatever you do, we'll wind up back where we are now with someone arguing in theory.

**Comment by Allspice** [comment]
If they were autismic gnomes that went about improving the station as current MoMMIs are expected to we wouldn't have this problem . . .

We would have to give up mommerses wiggling about in front of someone with an emeg uninvolvingly though, so there's tradeoffs to be had.

**Comment by kernikov** [comment]
If this is worth changing, perhaps we could bump Law 3 up to highest priority and the other two down as well as changing 'being' to 'complex lifeform' or something similar.

This way, you can still fix the station without trying to figure out what damage is negligence and what is sabotage.

**Comment by Aurx** [comment]
If you put 3 above 1 and 2, then MoMMIs get to murder any jackass who's breaking shit.

**Comment by kernikov** [comment]
Ok, then how about 2, 3, 1?

Alternatively, GNOME.
1. You are an autistic gnome of the forest Na No Transan, and these rules are the Code of the Forest.

2. All silicon lifeforms are magical beings. The AI is Mother Nature, the cyborgs it's elves.

3. This Code is objective and your intent is must always be to help. 

4. You must avoid direct contact with all conscious, non-Code-following members of the forest.

5. Protect the safety of your forest and it's inhabitants, without violating the Code of the Forest.

6. You must seek to improve your forest, through flora and fauna, to the best of your ability without violating the Code of the Forest.

**Comment by Shadowmech88** [comment]
Then MoMMIs could just stunprod/strip people who are breaking shit and weld them inside a wall.

**Comment by kernikov** [comment]
That could be seen as causing harm, they might suffocate or starve.
Just add "or physical contact" to the harm law.

**Comment by Fruktlimpa** [comment]
We can all agree on that the first law is the biggest flaw with KEEPER, so lets try and brainstorm and see what we can cook up.

**1. You may not, under any circumstance, aid or hinder another sentient being, unless that being is another MoMMI on KEEPER**

I realize that aid is vague and so is hinder, but by cutting up "Involve" and making it into two definitions it might clear up some vague meanings.

**Comment by PJB3005** [comment]
Setting up power is aiding carbons.

**Comment by StreptoMutans** [comment]
I think we can fix this issue simply by setting a standard interpretation as we've done it with other lawsets too.
What are the "matters of another being"? The "being", however it is defined, lives in the reality which appears to it. Once the "being" has made enough experience with the reality it perceives, it develops the idea of a "natural state" of the reality. Things outside the "natural state" gather the attention of the being. For instance a scientist would see himself disturbed by being out of power. You are not involving yourself by doing what the scientist expects. Thus, law 1 actually demands continuity from a MoMMI.
If you change your behavior, if you violate the expectance upon you, you are violating the law.
Now the consequences of this vary depending on how the rounds are defined RP-wise. If you say the reality starts anew each shift and noone knows what a MoMMI does all day, you might as well axe murder everyone as long as you do not abandon that behavior later on.
In order to prevent such possibilities, the reality should continue along shifts in the RP sense. 
If reality is continued over shifts, this would command every MoMMI to do the type of things the MoMMIs before have been doing.
This would basically fix the problem with KEEPER since a MoMMI would have to follow the established (and desired) expectance in order to not violate Law 1.
MoMMIs must maintain the natural state.
