### ISSUE TITLE
"Suicidal Syndrome" is retardedly busted.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14145]
(WEB REPORT BY: kernikov REMOTE: 172.93.109.202:7777)
>Revision 70406da520eea6d365ed3740322ff484df9ec7c2 
>General description of the issue
'/datum/disease2/effect/suicide/activate(var/mob/living/carbon/mob)
	mob.suiciding = 1
	//instead of killing them instantly, just put them at -175 health and let 'em gasp for a while
	to_chat(viewers(mob), "<span class='danger'>[mob.name] is holding \his breath. It looks like \he's trying to commit suicide.</span>")
	mob.adjustOxyLoss(175 - mob.getToxLoss() - mob.getFireLoss() - mob.getBruteLoss() - mob.getOxyLoss())
	mob.updatehealth()
	spawn(200) //in case they get revived by cryo chamber or something stupid like that, let them suicide again in 20 seconds
		mob.suiciding = 0'

>What you expected to happen
A death that wouldn't permanently remove me from the game.

>What actually happened
Instantly unconcious in Crit after being hypersprayed with 5u of diseased blood and unable to be cloned.

>Steps to reproduce if possible
Become infected with a disease with the suicidal syndrome and observe that you've been effectively gibbed with the bonus of still being abled to get succ'd.

**Comment by kernikov** [comment]
I can't into posting code but DELET this.

**Comment by eplgr** [comment]
I think this is one of those cases where someone dies, feels bad, and makes an issue out of it.

It tooks AGES to reach stage4. And we knew waaaay before that it was a harmful virus. I screamed over the radio about that several times. No one cared.

What happened was expected and not imbalanced at all. You had ages to prepare for it, or at least confront medbay (who were all antags and the reason all of this happened in first place).
Also,  stage4 viruses are supposed to be strong, so "effectively gibbed" sounds fair.

**Comment by Kurfursten** [comment]
>effectively gibbed

One of the stage four viruses literally is to gib, and it's not even the worst, since maybe if a doctor survives they'll start putting brains in monkeymen.

Since Kingston's makes you valid, there's absolutely no expectation that someone should even _try_ to transplant your brain into a new body. Getting catbeasted is as round-ending as it gets.

**Comment by Shadowmech88** [comment]
Suicide Syndrome is a stage 4 symptom.
You should have ample time to make your way to Medbay and get some spaceacillin before it makes you kill yourself.

**Comment by kernikov** [comment]
Not if you're hyposprayed and instantly put into critical.

"Gibbing" is literally a better fate, because you can still debrain and clone.

**Comment by despotate** [comment]
It's badness=2, you can only get these stage fours with the hard work of mutating, can't get 'em from crates. Others in its class are monkeyization, catbeastization, literally gibbing, and this syndrome. 

It's a viruloose that I'm totally fine with. You could have countered it by scanning yourself beforehand, by impeding your ability to suicide, getting spaceacillin, chugging virus food and hoping for the best, etc.

It was likely something else in the hypo that critted you.

**Comment by kernikov** [comment]
[20:46:04]ATTACK: <font color='red'>Ronnie Salazhar (killette2) injected Jack Clark (kernikov) with hypospray Reagents: Blood</font>

🤔 🤔 🤔 🤔 🤔 
It was an instant critical.

**Comment by despotate** [comment]
Stage fours aren't supposed to take effect until the virus has gone through all 3 other stages. This is either a bug where the blood somehow infected you and moved you to stage 4 or you had the disease beforehand or got critted some other way.

**Comment by Shadowmech88** [comment]
Also you can render yourself immune to it with dex+, all the symptom does is hit you with oxyloss.

**Comment by kernikov** [comment]
[20:45:50]ATTACK: <font color='red'>Jack Clark (kernikov) was hit by Antibody Scanner thrown by Ronnie Salazhar (killette2)</font>
[20:45:55]SAY: Ronnie Salazhar/Killette2 (@292,233,1) As Galactic Common : Why don't you have antibodies?
[20:46:02]SAY: Ronnie Salazhar/Killette2 (@292,233,1) As Galactic Common : Here let me give you the cure, sheesh
[20:46:05]SAY: Jack Clark/Kernikov (@293,235,1) As Galactic Common : Because I don't give a shit ab0-
[20:46:05]SAY: Jack Clark/Kernikov (@293,235,1) As Galactic Common : No
[20:46:04]ATTACK: <font color='red'>Ronnie Salazhar (killette2) injected Jack Clark (kernikov) with hypospray Reagents: Blood</font>

Boom, -175 HP.

@Shadowmech88 
Suicides are "survivable", if you can even call it that, with a permanent Dexalin Plus drip.
Yeah, that's totally not far fetched at all and doesn't ignore the whole "you're dead forever" portion of this issue.

**Comment by AutismSpider** [comment]
How many people in the past touch the virus code? i bet some one fuck up and fail to test stuff.

**Comment by Killette2** [comment]
Hi. Let me explain. I have virod for years and I knew about this ever since the addition of kingstons syndrome, when I first discovered it. This is either not a bug, or a bug that has existed for a very long time, let me explain it this way.

1. get a monkey/monkeyman, infect with virus
2. wait until stage 1-4
3. spread virus
4. you will notice the virus will spread on the same stage. When I discovered this, people were getting catbeasted instantly when walking near an infected person with the kingston syndrome being active.

How I did it the last round was I took the blood of the severely infected or already dead and just injected it into others. I am not 100% sure why it works this way, I just know that it does and has for a very long time, but I can see why this could upset people.

When I first saw this issue on the github, I didn't read it because I thought it was someone else reporting another suicide syndrome bug for me since I mentioned it in ahelps that round. I have made that an issue as well.
https://github.com/d3athrow/vgstation13/issues/14149

**Comment by AutismSpider** [comment]
Wait i thought that was only for kingston syndrome only were it skip right to stage four and cat catbeasted you

**Comment by Probe1** [comment]
@despotate work your magic over here.

**Comment by Killette2** [comment]
It works for any virus AutismSpider. If you put a monkey in a pen, give it a virus, virus hits stage 3 and you decide to hug the money, you get the virus too at stage 3. This can happen with any virus, so if you cook a virus like cooking a grenade, the virus will grow until stage 4 and you can instantly transmit the whole payload. The only instant part about this, is the virus is as strong as it grew to be in another body, as there is not a way to jump from 1 to 4 without the virus growing in a host.

This isn't a bug at all, but it can be kind of shitty. A lot of other things in ss13 can be shitty too, but I think this is one of the few things virology even has going for it.

**Comment by Intigracy** [comment]
The entire point of there being differently staged symptoms is so that viruses get progressively worse if you don't get help, not that you can just instantly fuck someone.

**Comment by eplgr** [comment]
>Instantly fuck someone

You mean, fuck someone after the 60 minutes it took your virus to get to stage 4?

How long does it take to release the singularity? To delaminate the shard? To get slippery cyanide polyacid fruits? To just get a 15u chloral hydrate? To get 6dev ttv bombs? And so on.

There are many, many stronger things that do not need any set up at all or just require little time. How is this more of a problem than those things and as a result, needs to be nerfed/completely removed?

Just trying to put things in perspective. I really worry about the current trend we have: antags keep getting their tools nerfed, while the crew keeps getting new things to fight them.

**Comment by Killette2** [comment]
eplgr summed it up pretty well. A lot of things like cyanide slip fruits can be done in under 20 minutes with zero detection unless you are being watched on by a hawk. This is cherry picking off of one round, how often do we really see this happen?

Removing this feature is byond ridiculous because the virus can take over 40-60 minutes to manifest, not to mention the extensive time it takes to craft a virus.

**Comment by Kurfursten** [comment]
I think nothing is wrong with this symptom at all, but I also believe we should fix virus progression

Just for my immersions, if nothing else. If progression needs to be faster we can talk about that too though.

**Comment by Sprok0** [comment]
Personally I don't like suicide syndrome at all, the suicide verb is an ooc method of saying "I don't want to play anymore", and something that imitates that shouldn't exist ic

**Comment by Killette2** [comment]
You have a good point sprok0, but that point is unrelated to this subject. The issue at hand is the stage progression, since this being a stage 4 fun 2 syndrome there is zero problem with making it balanced on the level of other stage 4s like instagibbing, dying from instant DNA scrambling, and other major fuck yours like kingston.

With carried over progression viruses can be a little bit bullshit
With timed progression viruses take way way too long
Maybe there should be an in between where if a virus grew in another host, it grows faster in the new one?

@Kurfursten if it helps your immursions, think of it as a bug or strain that evolves before it infects

**Comment by despotate** [comment]
I'm fixing this.
> With timed progression viruses take way way too long

1u blood, 4u diluted milk (virus food) should get them to skip 4 * 5 * 10 = 200 stage ticks, that gets you to halfway through stage 2 after a minute. Hypo that man twice with that and they're almost halfway through stage 3. There's your method of accelerating manmade viruses, just get people to ingest virus food.

**Comment by Blithering** [comment]
Might want to change the title of this, since the problem is with all viruses, not just suicide syndrome.

**Comment by Killette2** [comment]
I do not enjoy the concept of having to ingest virus food. With this fix I doubt anyone would want to play virology at all unless the syndromes are also sped up on their own. I certainly won't be touching it.

**Comment by Intigracy** [comment]
I found another bug with viruses actually, regarding speed at which stage increases.

**Comment by kernikov** [comment]
If your body wasn't flagged as an actual suicide, I'd be fine with this.

**Comment by ghost** [comment]
"mob.suiciding = 1"

Here's your problem, remove it

Then, make it so the proc ACTUALLY FIRES SUICIDE_ACT. I thought it would be funny how special suicides would work with this, they don't because of shitty code, jesus christ
