### ISSUE TITLE
HoS Greatcoat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14195]
(WEB REPORT BY: generalveers25 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

3d70cc1a8639361e4e012dfd46719ce3de35ca53 

>General description of the issue
The new Head of Security greatcoat gives me eye cancer. It's edgy as fuck and just looks bad. The only benefit is that it immediately identifies Heads of Security who use it as "THAT GUY"

>What you expected to happen
To not have my eyes assaulted by this abomination.

>What actually happened
My eyes were raped by the shitty coat.

>Steps to reproduce if possible
It's literally in the HoS locker. Find it. Pick it up. Put it on. Go blind.

**Comment by Frutzl** [comment]
It fits, but it's a terrible sprite. No offense to the author, but it looks like fresh garbage.

**Comment by ghost** [comment]
The coat is ass.

**Comment by generalveers** [comment]
This is what it looks like: http://prnt.sc/edawax

This is what it's supposed to look like: http://vignette4.wikia.nocookie.net/metalgear/images/a/a3/Sundowner.jpg/revision/latest?cb=20121215205151

Good idea. Awful implementation.

**Comment by murnandreams** [comment]
Looks like trash, remove post haste.

**Comment by Ephx1** [comment]
Why was this merged?

pshh, nothin' head of personnel kid

**Comment by ghost** [comment]
I said right in the PR it's shit and noone cared

**Comment by Yelier** [comment]
Here's an idea:
Make it bulkier. It looks slimmer than the Hop coat.
Make the transition more subtle, and make it start closer to the waist.
And finally, make it a bus/vault item. It stands out WAY too much to be a default jacket. I know the idea is to use it with the new machetes to be Sundowner, but that is NOT something that happens often enough to justify having a jacket like that. I'd just slap a Sundowner corpse with some HF machetes in the closet into Centcomm with all the other character corpses, and maybe make a MGR vault or something. Otherwise, I see no place for it.

And to the spriter: don't let this feedback get you down. The sprite could use some improving and there's just no room for it in the HoS locker, that's all.

**Comment by Exxion** [comment]
Already changed lol
