### ISSUE TITLE
Body Scanners Delete the Human inside if deconstructed while in use

### ISSUE THREAD

**Issue by strawberrytan** [d3athrow/vgstation13#14191]
#### Description of issue
1. Open maintenance panel on functioning sleeper
2. Crowbar out circuit board
3. Other person climbs in while this is being done
4.They are now a ghost with no body

#### Difference between expected and actual behavior
Pop out unharmed, or not allow deconstruction while in use

#### Steps to reproduce 
As above

#### Length of time in which bug has been known to occur

25th Feb, 2017

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Riekland** [comment]
Would this work when drag dropping someone in while you crowbar'd it? That would be kind of powerful if so

**Comment by Killette2** [comment]
I'm sure this is intended behavior

**Comment by ghost** [comment]
I can not for the life of me reproduce this

**Comment by ghost** [comment]
Wait, yes I can

Problem with crowbar destroying something is that it has a do_after of 4 seconds and then rather than call destroy() it instead uses spillContents to remove whatever is located within it. The sleeper and body scanner check for occupants to shout at the user for trying to take apart the scanner before returning the parent proc, but not after
