### ISSUE TITLE
Grills can still shock you through full windows

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14213]
(WEB REPORT BY: cairo283 REMOTE: 172.93.109.202:7777)
>Revision 6177f6cf7422556077adb07d170993003f34bc92

>General description of the issue
A full window on an electrified grill can still shock you by running into it

>What you expected to happen
Not to be shocked since there was a window in the way.

>What actually happened
Got shocked even though there was a window in the way. 
http://puu.sh/ulwYE/6386b8759a.png
>Steps to reproduce if possible
Walk into an electrifed grill with a full window on top of it. See what happens.

**Comment by Exxion** [comment]
Maybe someday

**Comment by Killette2** [comment]
there has to be a directional window to stop you from touching the grille. One full window won't stop this

**Comment by Shadowmech88** [comment]
We moved to this terrible `Bump()` method full of collision bugs because we needed to do so in order for pixel movement to work, right?
Wasn't that *months* ago?
How's pixel movement coming along?

**Comment by Exxion** [comment]
Poorly because I'm busy
But that's not the only reason we moved
We moved because that was shitcode, which caused problems
Except turns out this also causes problems, which Lummox refuses to fix

There isn't really a proper way to fix these issues, because the proper way would be for Lummox to fix his shit, which he outright refuses to do

That said, I just had an idea for a possible way to do it. I mean I've had several, but none worked, because of various arcane BYOND bullshit, but this one *should*

**Comment by kol1th** [comment]
>pixel movement

**Comment by Exxion** [comment]
Yes, those are some words someone said

**Comment by Exxion** [comment]
This was fixed long ago
