### ISSUE TITLE
Changeling + monkeyed + cuffed + regenerated = can't ventcrawl

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14263]
(WEB REPORT BY: curver REMOTE: 172.93.109.202:7777)
As the name says. The cuffs vanish when transforming, but keep you from ventcrawling due to spaghetti.

**Comment by MasterofNothing** [comment]
I meant "cuffs vanish when regenerating". So:

1-You're a changeling.
2-You get cuffed.
3-You use lesser form.
4-You die.
5-You regenerate.
6-Cuffs magically vanish & you can do whatever with your hands.
7-You can do everything (as far as I know) but ventcrawl...

Once an admin removed the variable or changed it, the issue was resolved.

May be related to #7806

**Comment by Blithering** [comment]
Could it have something to do with borg cuffs? Since transform usually drops stuff and they're meant to vanish when dropped.

**Comment by MasterofNothing** [comment]
@Blithering : It was a borg who cuffed me, yes.

**Comment by jknpj** [comment]
Unable to reproduce
