### ISSUE TITLE
You Still Can't Paint on Blank Paintings

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#14422]
I mean, cmon

These things are made from wood and you can mount them on the wall, but they have no image. The code says it's "TODO"

**Comment by troots** [comment]
its realistic
no one knows how to paint on the serb

**Comment by SonixApache** [comment]
What would you even use for painting? A paintbrush? A box of crayons? A photocopier?

**Comment by Shadowmech88** [comment]
You could make it so that using a piece of paper on a blank canvas takes the first image on the paper, if any, downscales it to fit into the canvas, and creates a new painting object with that image as the painting.

Or make some kind of painting UI that functions like the BYOND sprite editor so that players could paint in-game. That'd probably be more challenging though.
And it'd necessitate creating some kind of bullshit paintbrush item to justify how it works.

**Comment by Kurfursten** [comment]
We have a bunch of random paintings already, just make a paintbrush item that works like the chisel but for paintings.

**Comment by Shadowmech88** [comment]
It'd kind of defeat the purpose of getting random paintings from the merch computer if you could just craft any one you wanted using the paintbrush, wouldn't it?

Personally I think it'd be better for blank canvases to be capable of holding paintings from players rather than just turning into one of the paintings we already have.

**Comment by yclatious** [comment]
>image to painting
>clowns do nothing but paint goatsee and other random shit, displaying it on the halls, cargo and security

Fund it

I demand it.

**Comment by Megamaw** [comment]
>expensive nanocanvases for obnoxious gifs

Fund it
