### ISSUE TITLE
xeno rework ideas

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14484]
Just a little place for people to throw around ideas on how to redo xenos and keep it easily recoverable somewhere

**Comment by ghost** [comment]
Can't pocket face huggers, why do xenos even have pockets?

**Comment by jknpj** [comment]
Space Slip. Using space around the station to avoid slowdown and abuse zas has to go. Maybe make a magboot-like spell for queens as they have no other way to go around the station but hunters are fags and have no reason to run around the station.

**Comment by eplgr** [comment]
Queen is too slow. Is that good balance? Isn't queen supposed to be the strongest xeno? Why is she the weakest?
Also, xenos are supposed to be beasts, super strong compared to humans. Especially 1vs1. Yet they are very similar. Chemicals (sleeptox, chloral) are better than lasers against xenos. None of these things feels right.

**Comment by jknpj** [comment]
Xenos are super strong agains everything, they have 100% disarm rate. I once destroyed two combat cyborgs in my hive by abusing walls and disarming + slashing the cyborgs. Chroral and Fire are the bane of xenos but i don't think it's unfair as they can throw huggers and split neurotoxin

**Comment by Hoshi-chan** [comment]
Currently, xenos are far too powerful. Facehuggers will home in on you across the room, tear off masks, helmets, hardsuits, whatever, all in one fell swoop that puts you into a long, unavoidable stun. Xenos can ventcrawl, force open doors in a matter of seconds, melt walls and doors, they can out-regen otherwise lethal damage so long as they're on weeds, they can facetank laser rifles, they're immune to stuns, they can carry up to 4 goddamn facehuggers at once, and failing all of that, they can keep you pinned to the floor forever with disarm spam.

I think the way to handle any sort of alien rebalance would be to rework them completely, dividing powers and abilities throughout the different castes so that they actually perform functions and are forced to work together as a hive, rather than each of them being, "they do everything but they can also do X thing."

For example, when the fuck do you ever see xenomorphs, in any Aliens media, carrying and throwing facehuggers? Restrict that ability to the queen. Make the hunter's ability to consume people actually useful, rather than an instagib death sentence, by causing them to take a fixed amount of damage over time, rather than allowing people to spam resist until they gib, so that the hunters actually have the job of going out and abducting people to the nest.

Restricting facehuggers to something that only the queen can use, or that pops out of eggs, means that aliums will have to slowly expand their nests outward, and makes attacking their nest a lot more dangerous. Restricting weeds to drones and the queen means that building, defending, expanding, and returning to the nest is a lot more important.

Those are just ideas. The general gist of what I'm saying is that the castes should be far more specialized so as to promote cooperation, rather than every fucking individual alium being a facehugger-throwing death machine.

**Comment by Jubisloviu** [comment]
make them able to slip on banana peels.
![915a750c41135dbc969d0b298fb687e954140aa1](https://cloud.githubusercontent.com/assets/20007336/24554043/9d68031e-1602-11e7-982b-121e551a30d5.jpg)

**Comment by ghost** [comment]
there was a xeno in AvP extinction called a carrier. Bit bulky, but could carry a number of facehuggers. This was necessary as facehuggers had an internal energy supply they would consume on moving so could not move under their own force for a while.

Remove xeno pockets, remove them being able to generally carry facehuggers, and have the carrier be a mutation of sentinel or drone

**Comment by Blithering** [comment]
Xenos have a head and chest slot, can they be equipped with anything? Always wondered.
Also xenos and constructs are supposedly immune to ZAS, but still get dragged about by it, meaning often they get stuck in place by constant airflow and lasered to death by the one guy with magboots or spaced altogether with no means of course correction.

**Comment by eplgr** [comment]
Stop naming things that happen 1 round in a million as examples of "how strong xenos are".
In reality, everyone in the station will grab lasers as soon as they find out there are xenos, and start hunting them in every single corner of the station, and xenos will die. This is what happens in most of the cases.

Maybe, *maybe* they do have a strong toolset. But it is nothing compared to how easy the crew can get armed to fight them and actually win the fight.

**Comment by ghost** [comment]
I've been watching you argue with jknpjr in the coder discord for the past half an hour. Most of your points are largely bullshit approached from a manner of somebody that hasn't played the game for a long time, instead working from theory or general ignorance ('Oh, I don't see it happen so it must not happen. Let them eat cake'). What we do have is a mob that can outrun anyone not on hyperzine, immune to ZAS, healed by plasma and potentially outhealing most damage outputs (standing on weeds heals 2.5 of brute, burn and oxy, so a xeno on weeds can not possibly bleed out), armed with multiple guaranteed stuns (80% on a disarm to stun through armor, neurotoxin spit that can weaken a person for 5 points of weaken (Roughly 5~ seconds of BYOND time), can carry 4 facehuggers which can remove protective clothing and sleep somebody potentially for good and doom them to a surgery process else they gib, that can also act on their own like landmines). It has special exceptions so it can't be knocked out with blunt weaponry but it can carry toolboxes just fine and has a potentially higher chance of knocking people out with it.

This isn't a mob that's fun to do the dance of death with, as it's a stun-centric and stun immune enemy in a game where stuns are death.

**Comment by eplgr** [comment]
@Skullyton Geez, you and the other guy should start reading what you write. And, like I said before, I probably play ss13 more than you and the average github user.
I actually pointed out *to you* what you are writing to me:
You are all saying: _I, one time, killed 3 officers alone! They are the best antags in-game!_

Also, what the fuck? I complained about how xenos are actually not "stun immune" and that sleeptoxin and chloral are the best (and also easy) way to deal with them. Even better than having 6 advanced eguns in your backpack.

But sure, whatever, go ahead and nerf another antag just because you bite the dust in your last round against xenos. This behaviour is super healthy for the game.

**Comment by Anton-Kr** [comment]
They are fine as is fuck off

**Comment by Exxion** [comment]
Xenos are very, very strong once well-established.
Which is why you don't let them get well-established.
They're fine right now, in my opinion.

**Comment by AI-Is-Rogue** [comment]
I just want to be able to pick up clothes and wear them as a xeno with the clothes slots they have.

**Comment by JustSumBody** [comment]
Meh
They're like most other antags in that you will just get fucked if you run into one on your own in a dark maintenance tunnel. That's just the way of things, greyshit mcgee shouldn't be able to easily 1v1 a xeno with a toolbox. They've got counters, if you're aware of their presence then you can usually roll them with those(chloral syringe guns, mechs, combat borgs, BLASMA FIRE, vent welding)
This of course depends on how quickly you find out about them and the difference between nosec/noheads and a fully staffed highpop station.

Idea of restructuring them so that they're a bit specialized is an idea, but then it might lead to first xeno having an unnecessarily difficult time kicking off if only one larva spawns or something. Especially if there's few to no willing ghosts for whatever reason. Would need to then rework xeno base to be a bit more defensible rather than just "lol borg saw'd through resin and laser u"

I've seen them completely obliterate stations to the point of admins needing to just force end the round due to lack of alternatives, but I've also seen them stomped out as larvas. It can swing either way depending on the crew.

**Comment by yclatious** [comment]
If you want to nerf them based on them being too strong in melee, most id say is reasonable is lower the disarm rate, even CM doesn't have 100% disarm rate and completely stunning borgs is kind of meh, removing hugger throwing would be nice for aliens that arent queens but not really needed and they are meant to be robust in maint and shit so any complaints you or any player say about wrecked in a tight hall are just to be ignored.

**Comment by Dizor** [comment]
First off, change how they disarm/stun. Their main method of stun should be a leap mutation like attack that leaps the xeno, has a decent cool down and stuns the first guy/Borg it hits. This way it's still effective and reliable means to stun but can't stun a whole room rapidly. make the leap also force drop anything being dragged or held so xenos don't try getting cheeky.

Possibly add a head bite attack. It channels for a bit but then does massive damage to the limb targeted, either severing limbs or blowing a hole in the target. wouldn't work against mobile targets but could be insanely deadly against isolated targets.

Improve stalking. It's kinda worthless.

Have them effected by zas, but give them the ability to cling, which prevents holding items, slows a little and acts like magboots.

Add additional perks to Hunters and Sentinels, as well as possibly adding Runners and variants based on other races.

**Comment by Aurx** [comment]
Fundamental underlying issues that should be addressed:

Xenos are stun dependent: They have to be able to reliably incapacitate a victim, remove their hugger-proof headgear if any, and keep them from running off to surgery/suicide so the hugger hatches.  Making non-queens unable to carry huggers will make them more stun dependent, since they'll have to be able to stunlock a victim long enough to drag them to the hive.  
Xenos are, if unable to carry huggers, unable to fully exploit their mobility:  If you have to take the victim back to the nest, being able to ventcrawl and spacewalk isn't as helpful as it seems since you're unable to do so with the victim in tow.  Making swallowing not suck would fix this.  
Xenos barely care about the queen once established: If you've got a good xeno with a hugger or a drone in some ass-end of maint, that's all it takes to restart the hive.  Killing the queen means jackshit when any drone can just immediately evolve to replace her.  
Xenos are too bipolar in their durability: A xeno caught off weeds when you've got a laser is basically dead already.  A xeno on weeds takes a ludicrous amount of damage to put down, and can seem immortal if the person fighting it is a 'tard.  
Xenos are too start-dependent: A queen who gets to pop all the viro monkeys is a hugely different scenario from the queen who has to get started off crewmembers.  It's fairly notable that every queen-guide starts with "Go to viro/xenobio and hugger the chimpers".  The viability of an alien infestation shouldn't be determined by if there's some bloke doing their job.

**Comment by Hoshi-chan** [comment]
We had xenos today, and as far as I could tell, nothing stopped facehuggers. They tore off masks, hardsuit helmets, combat helmets, welding masks, whatever and immediately latched on.

That's probably my biggest problem with them right now, is that there's no fucking counter to hunters ventcrawling in, throwing facehuggers, and one of them inevitably rips your headgear off and then you're fucked.

**Comment by Allspice** [comment]
Plus queens can produce let's call it an average of one facehugger every two to four seconds. Which before the change was whatever, but after facehuggers were made to be able to rip off helmets, ehhh

That's something I've been annoyed with since the facehugger buff, not because I got bopped pls nerf.

**Comment by Durgen** [comment]
being zas immune only while walking seems like a reasonable nerf

**Comment by Fruktlimpa** [comment]
I really don't understand why borgs are complaining about being chain-stunned to death. Why is a borg trying to melee a Xeno in the first place? Why is the borg alone with no backup? Lasers are effectively infinite for combat borgs and a million times more effective.
You are not supposed to fight Xenos in melee that is the entire point. Remove their reliable melee stun and Xenos are going to be awful to play because people are just going to kite you even harder than they already do.

Xenos lose extremely easily if the crew isn't braindead and rush in one on one into the hive like Rambo. Borgs fuck Xenos like no tomorrow if they keep their distance and play smart.
Removing pockets for the other castes severely limits the ability to actually make new aliens. Since the Queen cannot ventcrawl you have to settle in viro to get monkeys or you are just going to have to pray to Jesus that you can settle elsewhere and not get discovered before you get eggs. You then HAVE to jump a human to get your brood started and once they know there are Xenos you are going to get fucked.

How often do Xenos win even? I can assure you that Xenos probably loses more times than they win and that this is a non-issue and only comes to discussion because people rambo aliens thinking they can and should be able to melee a Xeno.
**Facehuggers being able to rip off hardsuit helmets and other more robust helmets is something that should be nerfed I agree(Flimsy masks can fuck off, huggers should be able to tear those).** 

Xenos require teamwork and support to beat. People who try to 1v1 Xenos deserve to get chain-stunned to death because you are simply not supposed to do that.

**Comment by Blithering** [comment]
On the subject of facehuggers, they have absurd health when crawling, I remember unloading an entire egun into one and it still managing to reach me to hug me.

**Comment by Exxion** [comment]
Facehuggers are items, not mobs, so it's very possible their health system is very buggy

**Comment by SonixApache** [comment]
They can't see their own health very well, and they don't really know when they're on fire. That's a pretty big issue.

**Comment by gbasood** [comment]
@Blithering they're *supposed* to take 5 projectile damage and then die
I dont know how eguns work with that though. It should work to some extent because I remember testing it when I first added that proc, but it might not work for eguns specifically? Dunno. Worth testing.

@Fruktlimpa On the subject on facehugger removal of rig stuff:
```dm
		if(mouth_protection && mouth_protection != H.wear_mask) //can't be protected with your own mask, has to be a hat
			stat_collection.xeno.proper_head_protection++
			var/rng = 50
			if(istype(mouth_protection, /obj/item/clothing/head/helmet/space/rig))
				rng = 15
			if(prob(rng)) // Temporary balance change, all mouth-covering hats will be more effective
				H.visible_message("<span class='danger'>\The [src] smashes against [H]'s \the [mouth_protection], and rips it off in the process!</span>")
				H.drop_from_inventory(mouth_protection)
				GoIdle(15)
				return
```
So they have a 15% chance to remove rig helmets right now. Anything that isn't a child of rig helmets gets a 50% chance, though. There's probably oversights there.

I will say that what @SonixApache said about health and fire is a huge problem I experienced while playing xenos.

The reason that they're even able to remove rig helmets at all is that a large portion of the crew will (or did before at any rate) end up wearing rig helmets as soon as they see an ayy, or coincidentally if their job requires it (engineer) or if they're jerks (bad HoS or captain at round start). Which meant ayys had a really hard time getting started.

@Commandersand Wait what? Since when? They're absolutely supposed to be able to do that. In fact that's what people did when these changes were first added is just carry as many facehuggers as possible and throw them at a person until they got on their head.

And on that note, maybe a good change to ayys/facehuggers would be to give the ayys themselves better capability of closing distances without immediately dying or some kind of ranged combat themselves, and then just preventing facehuggers from removing rig helmets to make them a good counter to facehuggers.

And yeah @Skullyton is right about stun-centricity. That's why people like to play xenos and hate fighting them.

I'm not going to argue the balance of the RNG involved in the removal anymore, but that's why it was added at all. I'm also going to try to stay removed from balancing xenos since I don't have time to yell at people about it.

**Comment by Allspice** [comment]
Sents already get neurotoxin to stun, which does work on people with hardsuit helmets.

Also "xenos caught off weeds when lased are basically dead" is a huge joke. 4 laser shots to crit drones, the weakest xeno after larva. Then it's 6 lasers to crit a sent, then 9 lasers to crit a hunter, nearly a full laser gun charge (don't miss).

**Comment by gbasood** [comment]
On the other hand a xeno queen requires about 3 people each with a laser gun to kill in half a second off or on weeds, if you want it done expediently.
With one person you just carry two lasers and don't get neurotoxin'd
I can't comment on whether or not that matters though, just like i can't comment on whether or not what you said matters.

**Comment by Blithering** [comment]
The bane of 95% of melee focused creatures is backpedalling with a laser.

**Comment by Allspice** [comment]
except they all get facehuggers, and sents get tasers while being approx. as resilient as cyborgs. Those things that are commonly considered a bitch to kill.

**Comment by Fruktlimpa** [comment]
@Allspice You are describing a situation where only one person is present and armed and trying to take down a xeno. Stop with this, you are not supposed to be able to solo a hive.
If you were just two people with lasers then any alien caught of weeds is dead pretty much before it can react.

**Comment by Allspice** [comment]
And you're pretending that teamwork is a thing wholly unknown to aliens, those other creatures that get instant and silent communications to their friends. So I find it informative to consider how one human stacks up to one xeno--it is very favourable to the xeno, perhaps a bit too much so, and I see no reason why the scales tip towards the humans with 2v2 3v3 et cetera.

**Comment by ComicIronic** [comment]
Because there are far more crew than xeno, and xeno are meant to be strong as single predators, like they were in the first Alien movie.

**Comment by Allspice** [comment]
I reckon the total crew count is less useful as a metric than the number of those crew that are fielded efficiently against the xenos, which is much closer to even.

One other thing: Xenos are stuncentric to a degree, but once a person is infected you're better off killing them than bothering to stick them in a nest, which still strikes me as odd. To this end you might as well vent the nest because the survival of the hosts does not matter, and slowing down invaders with magboots is pretty okay.

**Comment by Fruktlimpa** [comment]
> I reckon the total crew count is less useful as a metric than the number of those crew that are fielded efficiently against the xenos, which is much closer to even.

Yes, most people who attack Xenos do so alone and recklessly, usually ending up dead, but to nerf Xenos in a 1v1 situation wont fix that issue, all it will do is make xenos even more stompable should a few crew actually cooperate with each other.
The crew needs to cooperate loosely to squash a fresh hive and they need to cooperate effectively to squash a prepared hive, if they don't do that and instead try to play Rambo then yes, they should always lose.

**Comment by Allspice** [comment]
The main ways the crew has to purge a proper established hive is to: Burn it out; bomb it; send mechs (eh); send borgs (ehhhhhh). I dislike balancing features for the first two because it's playing a dangerous game with administrative action. Mechs can possibly do the job if the xenos aren't good enough to run circles around them. And borgs can theoretically do the job but they're preoccupied for minutes by those damn resilient walls, then shoved by beings as tanky as they are, if not more so, and that's all she wrote.

I exclude humans because the queen can fill the nest with hundreds of facehuggers in minutes, so that fifteen percent chance will eventually fuck you.
