### ISSUE TITLE
Riot Helmet doesn't blocks facehuggers

### ISSUE THREAD

**Issue by Jubisloviu** [d3athrow/vgstation13#14494]
#### Description of issue
Facehuggers just ignore them and you die like a bitch

#### Difference between expected and actual behavior
Expected: Block the Huggers as it should since it covers your face
Actual Behavior: Xeno throw a facehugger in your face and you get stunned them die like a bitch

#### Steps to reproduce 
1. Wear the Riot Helmet
2. Xenomorph throws a facehugger at you
3. Be amazed because it completely ignores the helmet and you are on the ground getting gangbanged by xenos.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by IAGFPRMF** [comment]
I believe it has a chance to tear off all helmets.

**Comment by Jubisloviu** [comment]
it doesn't even tear the helmet
it just ignores it like it was never there in the first place.

**Comment by yclatious** [comment]
Riot helmets being able to deflect facehuggers seems like a good adition instead of making sec nigger the hardsuit helmets just so they dont get memed. Stuff like wielding a riot shield to be able to delect or be imune to thrown facehuggers when facing the right way would also help against xeno hugger combat.
