### ISSUE TITLE
Discussion thread about transparency problems and muh attack animations drama.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#14573]

**Comment by ultraplen** [comment]
@Fruktlimpa @jakmak6 Please respond here if you feel inclined to do so.

**Comment by Iamgoofball** [comment]
lets dissect this post by the wonderful HONEST AND TRUE @jakmak6 BOYFRIEND-FREE VEEGEER

>It was a shitty idea that the community was so against they had to force merge it for april fools to mask it as a april fools joke along with all the other hilarity they had. Problem is they removed all the other meme stuff except this. Attack animations were barley tested and riddled with bugs and the community has expressed extreme disdain from them. I understand you want them in but with the autism surrounding it the only way to have it without being jewish is to hold a server poll to see if the want to keep or remove the attack animations. If it was so bad it had to be a april fools joke just to get it in then maybe it isnt such a bad idea to consider removing or atleast getting a vote in on it

>it was a shitty idea that the community was so against
>community was so against

whats this about a poll proving this to be wrong?
http://ss13.moe/index.php/poll/51

>Problem is they removed all the other meme stuff except this

Can you provide proof of this statement? Preferably some server logs of active merges and/or testmerges.

>Attack animations were barley tested

Farm memes aside, can you provide proof of this?

>riddled with bugs

Please provide cited issue reports that you or another community member has filed that follows the proper template including reproduction steps and evidence of your own reproduction of the issue.

>the community has expressed extreme disdain from them

Please provide statistical data proving this in the form of a multiple day poll lasting long enough to collect data from all timezones and all potential work schedules for our playerbase that may or may not be able to vote during working hours in their timezone.

>I understand you want them in but with the autism surrounding it the only way to have it without being jewish

what did he mean by this? scholars are confused to this day

>is to hold a server poll to see if the want to keep or remove the attack animations

Please make sure polls are also held for the following:

1. A poll for whether a new poll should be ran.
2. A poll for that poll.
3. A poll for each option on the new poll.
4. A poll for that poll.
5. Polls run for hardware demographics to figure out the reason players approve/disapprove based on statistical data on hardware and software differences that may factor into player disapproval.

Only then will democracy be complete, and a bald eagle will shed a single tear.

>If it was so bad it had to be a april fools joke just to get it in then maybe it isnt such a bad idea to consider removing or atleast getting a vote in on it

Can you prove this was an april fools joke and was not just merged around the time of april fools? Please provide photographical evidence and/or associated chat logs from the merging maintainer and coders.

**Comment by PJB3005** [comment]
Alright here's my fucking argument for why everybody who's complaining is stupid.

You're a 14 year old and for your birthday you asked your parents for a gift. IT JUST SO HAPPENS that your birthday is on the *second* of April. Your parents didn't ever say they were going to give you it on your birthday.

Your parents give you a box of candy and tell you not to open it until April's fools, and you do and the gift you wanted is inside. Wow!

Oh and then on the second of April, on your birthday, your parents take your gift away and give it back to you in new wrapping paper but it's extremely obvious... What?

That's basically what's happening here. Calm the fuck down Jesus H. Christ.

**Comment by ultraplen** [comment]
@Iamgoofball 
>Can you prove this was an april fools joke

#14503

**Comment by Iamgoofball** [comment]
There you go, but it's still a solid feature and it being originally an april fools joke doesn't mean it has to go immediately and doesn't discredit the actual feature itself.

**Comment by Iamgoofball** [comment]
yeah that basically covers it @PJB3005 

you forget the part where the 14 year old goes to an image board and posts about the "jewish parent conspiracy trying to ruin my birthday and make it for the normies"

**Comment by ghost** [comment]
I thought we were getting trains

**Comment by ghost** [comment]
Attack animations help show what the fuck is happening

**Comment by brnor** [comment]
I don't care about the feature but why are you making life hard on yourself by : 

- continuing to argue to no end about few minutes of work
- poorly documenting changes done to the code  and claiming that's fine

**Comment by PJB3005** [comment]
https://github.com/vgstation-coders/vgstation13/issues/14573#issuecomment-292280410

**Comment by Probe1** [comment]
I was bemused by everyone suddenly becoming outraged since I figured everyone had read the actual code, especially in such a odd sounding PR on April Fools.

Additionally I was annoyed and disappointed that many of you said "We can only have attack animations if they have a toggle to turn them off" then immediately on gaining a toggle, the same people said "Well we don't want them at all".

I'm a mix of surprised and disappointed in every person who flipped their shit, asked for something to be coded, then flipped their shit again when it was.

I also rate attack animations a 3/10 on the "Worth giving a shit about" scale.  But that's how it is here.  We freak the fuck out over little things then no one says boo when collaborators merge some huge reaching PR because no one has told them they should be upset about it.

**Comment by TheFriggenSawbones** [comment]
@Iamgoofball tbh when they were first merged there was a shit ton of issues with hitting yourself, no attack delay, ect ect. But cluster was quick to fix all the issues I, or anyone else, found.

Also you're on the wrong github again.

**Comment by Fruktlimpa** [comment]
@ultraplen 
> Your words are directed at some vague "coder" entity, not quite realising that "the coders" are a fairly large group holding varying opinions - I recommend atleast getting an overview good enough not to make such broad statements before posting. 

The very reason as to why I use the word "coder" as an entity in itself is because all the big shots are behind this merge even with how poorly it was handled, which is insane.
Why didn't any of the other collaborators say; "Hey, this is going to cause drama, why are we doing it like this?"

> I've already stated that the circumstances of the merge were shitty, but as Shadowmech said reverting would serve no purpose. Also, the animations would have been merged without any further vote anyways. A major component in the outrage seems to be that people don't realise/accept that the animations have already been discussed, emojied and voted on and that the against side lost.

You fail to understand yet again. The outrage sparked because it was shrouded as an april fools joke, which made people believe it was an actual joke. I'll say it again, if you had done it properly the first time there wouldn't have been such an outrage.
I cannot for the life of me understand why you would purposefully do it the worst way possible instead of the normal way.

> I don't understand how you can expect people who chat and collaborate daily to not have a bias for eachother. 

I expect our collaborators to not ignore blatant rule breaking actions just because their buddies did it. And instead call them out on it and force them to do it properly.
I do not believe that it is ok to break the rules "just once".

> Putting that aside, it is only rational to hold the opinion of someone who has put in countless hours of work into this server higher than that of someone who signed up for Github yesterday to shit on a PR. The "hardcore" guys who have put their blood, sweat and tears into this server and its code deserve respect for it and I can't honestly see who would be "hotter shit" than them on here. That being said, there have been alot of rude and unconstructive posters on both sides.

This is also a major issue, you assume that people who are against this PR are just "new" people who shits on it for the memes, which just adds to this hot shit issue.
Acting like hot shit is the action being stuck-up and having an irrational sense of superiority. You can contribute a lot and I don't consider myself better than coders, but act humble instead of being a cunt essentially.
The ivory tower stops being a meme and actually becomes reality because you surround yourself by yes men

I'll reiterate. If this was done in a proper manner then it would have passed with little drama. I am sure of that.

**Comment by Intigracy** [comment]
So we should open up two PRs, one to revert them and one that adds them right back in again, and then merge them both right after one another?

What do you expect to get out of this?

**Comment by Kurfursten** [comment]
@Fruktlimpa "Coder" doesn't really refer to "big shot" in any sense. Besides nobodies like me who literally just add content PRs (and rarely even look at the code discord/irc), you have really smalltime coders like Niggly or Fudge who have done just a few little changes (even Kammerjunk has added some logging). Coder also refers to Celt and Sarahjohnson and Pomf who were all against attack animations, and dead people like Wild Bill and Eswordthecat. Even if you only count meaningful contributors, there are tons more who haven't even weighed in on attack animations, probably because like me they don't care. You look at people whose code I admire like N3X, Deity, bauds, and Unid -- none of them have ever said anything about any of this.

It's not a useful category for anything but thread shitposting really. Coders are as varied as our playerbase (for the obvious reason that they were drawn from the playerbase).

**Comment by ultraplen** [comment]
@Fruktlimpa 
>If this was done in a proper manner then it would have passed with little drama. 

This we can both agree on.  The behaviour of the against side has been very poor however. Some have even gone so far as to make up their own realities about the situation (@jakmak6). The bulk of this shittery was in the 4chan thread though, so it is to be expected.

>The very reason as to why I use the word "coder" as an entity in itself is because all the big shots are >behind this merge even with how poorly it was handled, which is insane.

The merge was handled poorly, but it isn't even nearly as bad as you're trying to make it out to be. Many explanations (of varying qualities) have been posted and the refusal to accept them shows that this controversy is about the content itself, rather than its merger.

@Kammerjunk also posted a good response to your use of the word coder as a was typing this rant out.

>You fail to understand yet again.

"Yeah, the merge was shitty."
"Nah man you don't get it! It was really, _really_ shitty!"

>And instead call them out on it and force them to do it properly.

If the symbolic action of reverting and merging again would put an end to the arguments I'm all for it. I do think it's absurd though, and I understand the people that are against it.

>This is also a major issue, you assume that people who are against this PR are just "new" people who >shits on it for the memes, which just adds to this hot shit issue.

I intended for thing about "new" people to be interpreted as a slight hyperbole. Of course, most of the people involved in the discussion have a contributor tag. However, I dare claim that one side has more merges, and the other more bug reports.

I do stand by my opinion that the opinion of a collaborator, or an "actual"/active contributor, carries many times the weight of the opinion of others. People don't have nearly enough appriciation what these people do, and I've even seen some posts of people believing themselves to be "customers" of the "coders".

This text ended up being more rantlike than I wanted it to be - it's well past my bedtime.

**Comment by Exxion** [comment]
The merge was shitty and nearly everything about this was handled in the worst possible way.
That said, there's no reason to revert it, unless someone can show me a poll that has the playerbase substantially against it.
>But you just said the merge was shitty!

That I did. But what do you want us to do? Revert it and immediately re-add exactly the same thing with a better PR? That's just a waste of everyone's time.
The merge already happened. We can try to handle things better in the future, but there's not really anything we can do to make this one better. (Other than fix bugs and add a changelog entry, both of which are actively being done.)

**Comment by kilozombie** [comment]
>The merge was shitty and nearly everything about this was handled in the worst possible way.
That said, there's no reason to revert it, unless someone can show me a poll that has the playerbase substantially against it.

This is the objective truth. Attack anims are working and fine. I like them. Large majority of people like them. The only argument is about transparency. Don't fucking misunderstand me @Probe1 I'm not any more angry about this than it deserves-- I barely care at all, but it is worth fucking talking about.

**Comment by Lokiamis** [comment]
I like and use animations, but nothing should be exempt from revert attempts because it passed a poll with 55% of votes back in like fucking August. They alter gameplay. They give advantages to players who have them enabled. If the majority of players still like them, the revert will fail. Was your recent PR that would have set them on by default done because you want to make the game better or because you wanted to spite the thread/4chan community you openly despise? 

And fuck all of you faggots in the coder Discord circlejerking "haha it's just one guy in the thread spamming complaints" because I've been seeing this bullshit attitude more and more lately in response to more than just attack animations.

**Comment by kilozombie** [comment]
As much as I don't think anything should be exempt from revert attempts, especially not one that narrowly passed a poll half a year ago... that isn't getting through to any coders.
I don't think any collaborators care or realize what you're saying.
Let's just move on and have a more definitive poll soon enough.

**Comment by Exxion** [comment]
It's not immune to revert attempts.
But can people at least wait a few goddamn days for a poll?

**Comment by Lokiamis** [comment]
>It's not immune to revert attempts

![screenshot_20170406120433](https://cloud.githubusercontent.com/assets/25004372/24777471/ed0f2aca-1afb-11e7-815e-3858f1e6431b.jpg)

**Comment by Exxion** [comment]
He's not the only collab.
Also @PJB3005 What the fuck

**Comment by kilozombie** [comment]
I don't think pjb or probe know that the actual thing people are complaining about is the lack of transparency. By probe's view, people are being fucking morons and changing their opinions on attack anims. That's not correct at all, but from that PoV, I understand Probe's and PJB's actions.

**Comment by Kammerjunk** [comment]
Evidently not the only collab - even they don't get along!
![image](https://cloud.githubusercontent.com/assets/5942183/24777749/1af0151e-1b27-11e7-99c2-7068efedfd05.png)

**Comment by Exxion** [comment]
Cluster didn't say there that a revert wouldn't happen
He said that it wouldn't happen *unless someone brought up an actual reason for it*

**Comment by Kammerjunk** [comment]
I really should have highlighted the important bit
![image](https://cloud.githubusercontent.com/assets/5942183/24777864/d2d5c764-1b27-11e7-9929-035c56a19264.png)

**Comment by Fruktlimpa** [comment]
@Kurfursten 
You are right I'm sorry, I should replace coder with specific individuals that are making this whole process ten times more cancerous than it needs to be, and one of them is obvious. PJB is a pr-nightmare but I really don't think he gives two shits about this.

@intigracy 
No I do not want a revert and a new PR, at this point it really doesn't matter. What I want is repentance basically, and as faggy as it sounds I would appreciate an apology not this high-horse attitude that basically resorts to spitting down from the ivory tower at those who complain.

@ultraplen 
> The merge was handled poorly, but it isn't even nearly as bad as you're trying to make it out to be. Many explanations (of varying qualities) have been posted and the refusal to accept them shows that this controversy is about the content itself, rather than its merger.

Think about it this way. Do you honestly think that I would be able to create a PR that does something entirely different from what the actual code will do and not have the entire collaboration team at my throat? Of course not.
What I am annoyed about is how this was passed seemingly unhindered by other collabs, as if they were fine with the thing in question. And once the complaints started rolling in they double-downed on it and refused to apologize.

Don't get me wrong from this whole rant. I don't dislike any of the collaborators based on the work they do. I appreciate their work, what I don't appreciate is the attitude behind it all and the apparent lack of respect for the whole "Pride itself on transparency and integrity". Which is just a massive kick in the balls when you look at this whole ordeal.

@Exxion 
This is pretty much what I want to hear, admittance that this was a massive failure. Like I said, I don't want attack animations reverted, I don't really care. I simply only care about the way it was handled.

**Comment by Exxion** [comment]
@Kammerjunk Still not seeing what you're saying
Spoonfeed me

**Comment by Kammerjunk** [comment]
😮 🥄
![image](https://cloud.githubusercontent.com/assets/5942183/24777982/6ec19b30-1b28-11e7-8a89-f045cc84005b.png)

**Comment by SonixApache** [comment]
@Fruktlimpa 

>Do you honestly think that I would be able to create a PR that does something entirely different from what the actual code will do and not have the entire collaboration team at my throat? 

Depends, do you do it on april fools? Or are you somehow masking/obfuscating the code in the [CODE] tab so you've *actually* made a PR that does something entirely different from what the actual code will do?

A feature that had been in limbo for months finally got finished and merged. The description under which it got merged was a joke. Everyone's still screaming about a joke. I just want the screaming to end.

**Comment by Exxion** [comment]
Ah
*shrug
Personally, I've only locked issues
1. When Imagebard was posting porn in them
2. When they got excessively hostile and weren't going anywhere

I don't really see anywhere better to discuss managerial issues of the codebase, but I also get what Cluster was saying.
Note, though, that he only closed it. He didn't lock it.
Unless he did later in which case oops

**Comment by Ait1** [comment]
Since I'm almost forced to come here and give an opinion that's counted, I personally hate the animations.
It's buggy as fuck, plenty of times where it bugged out so bad the animation stuck on to my character and doing everything I could didn't change it. The problem even escalated to a point to where it interfered with the sprites of the game itself and a few people can stand behind that.
"Disable it in settings"
That doesn't work either, in fact that's by default it's disabled. Which annoys me even more.

**Comment by Fruktlimpa** [comment]
@SonixApache 
I really do not understand how you can argue that it is ok to write whatever in the description section of a PR as long as the code section is obvious.
The whole point of the description section of the PR is to EXPLAIN what your code is going to do. To write something else entirely is to purposefully hide what you are trying to do.

I should not have to dig into the code and read all the lines to understand what your PR is going to do. You are supposed to explain that to me in the PR, like any decent person. 

You call it a joke, I call it a breach of trust and transparency.

**Comment by Exxion** [comment]
Them getting stuck was allegedly fixed. (And for the record, never reported.)
Them being disabled by default is fucking stupid, but that was the compromise we were forced to make.
Maybe in a few months we can change the default without too much uproar.

**Comment by Kammerjunk** [comment]
No, but I'm pretty sure closed means "this is dead to me"
I have no stake in this anyway, I've been playing other games and with the amount of people yelling for and against this, there's nothing I can say that someone else hasn't or won't say ¯\\_(ツ)_/¯
But for real maybe merging something in this manner when the first PR about it got 151 comments and the second PR got 177 comments isn't very clever. I thought bigshot collab supercoders were clever ☹️

**Comment by SonixApache** [comment]
@Ait1 now that you've made an account you can easily post issues as well, good job! Should definitely make an issue for the bugs you've encountered.

@Fruktlimpa A prank was pulled on april fools. I'm arguing that it's fine to pull pranks on april fools.

I don't understand why you are actually complaining about *a breach of trust and transparency* about a thing that happened on april fools in a group filled with jokers. I'm not going to dig up every single PR that doesn't properly describe what it actually does, but I can assure you there are hundreds of them.

**Comment by kilozombie** [comment]
I think we should hug it out and move on, and never do anything like this ever again, for absolutely everyone's sake.

**Comment by Fruktlimpa** [comment]
@SonixApache 
Pranks that are pulled on April fools are also not permanent. It stops being a prank when it continues outside of april fools.
All the other april fools PRs were properly removed as they were pranks for that day. This """prank""" was never intended to be reverted. The intention was to keep it running even after the day, which doesn't make it a prank anymore.

The breach of trust and transparency comes from the fact that it was never intended to be a prank, it was always intended to be a full PR. But april fools was just used as a method to sneak it in. 
You know this, don't act stupid.

**Comment by Ait1** [comment]
I'm agreeing with Fruktlimpa, it _was_ supposed to be removed after april fools.

**Comment by SonixApache** [comment]
@Fruktlimpa the prank was the description and title, not the content.
Should the description and title have changed? Is that what the issue is? 
Because I agree, it should've. 
But I'm not going to throw a massive shitfit over it. Maybe because I'm okay with the changes?

It was intended as a full PR **months ago**. It was intended to be merged **months ago**.
It finally got fixed and merged and snuck in among the jokes to give everyone something positive to work with after the joke day was over. 

Some people refuse to see it all as anything but negative.

**Comment by Fruktlimpa** [comment]
@SonixApache 

> But I'm not going to throw a massive shitfit over it. Maybe because I'm okay with the changes?

So what you are saying is that you don't care standards when it comes to PRs as long as the content within them is to your personal taste? I really hope that isn't what you are saying.

Like I've said countless times, I know it was passed by votes and by discussion. I do not give a single fuck if it was intended to be merged months ago, you still do not make a meme PR and sneak it in. If you were so certain it was going to get merged why didn't you just make a proper PR?

I don't understand this; "Give everyone something positive to work with". The issue was controversial from day one and just barely passed a majority vote. Sneaking it in like this would never turn out positive and I don't believe for a second that anyone involved with merging it didn't know that.

This PR disaster is only negative. The content is not.

**Comment by SonixApache** [comment]
What I'm saying is that there is next to no standards when it comes to PRs here and that *you* are a joke for pretending that this is the case.  What the fuck, man.

Whenever I run into shitty paperwork while codediving to bring back old shit I do the civilized thing and complain about it to the people in question if I can, and otherwise to everyone in the discord / IRC / ingame / thread without throwing a massive fit. Because causing massive drama over such stupid shit is really just a waste of everyone's time.

Meme PR titles, descriptions, branch names and commit messages are a common occurrence and I really don't feel like trying to be super serious in fear of my boss firing me for jokes on fucking github.
I doubt anyone here feels otherwise.

**Comment by Huuuuuuuuuuugo** [comment]
Shit's bugged out so you get rid of it

If shit's bugged out and your responsible coders aren't reverting it then what the hell does that say about them?

**Comment by SonixApache** [comment]
@Huuuuuuuuuuugo
The whole purpose of the issue tracker on this very website is to help fix bugs. If you just revert everything that is even slightly buggy you won't ever get anywhere. Our past 5 years of history are a testament to that.

Cluster's already fixed a bunch of reported and unreported bugs regarding the thing. Report the bugs to help get the shit in the best condition, voice your complaints in the relevant channels (as you are right now) and vote when a vote comes up.

**Comment by Exxion** [comment]
You don't revert something for bugs unless they're gamebreaking.
You fix the bugs.
We could never get a new feature at all if everything with a bug got reverted.
Also, we aren't psychic. Report bugs.

**Comment by Fruktlimpa** [comment]
@SonixApache 
Point to me a single PR that has had a completely different title and body to what it was actually trying to add.
We have standards, by the mere act of having a guidelines on how to make a PR when you try to create a new PR, the fact that you don't think we do is irrelevant.
I consider following simple steps such as explaining what your PR is going to do and not being purposefully  neglectful of this matter is having standards, and from what I can see on 99% of the PRs currently open they are following this standard.

There it is again, you try to say that the drama was caused by everyone who reacted to this instead of the ones who literally set it up to become a drama shitfest.
The ones lashing out are not in the wrong here, the people responsible for the PR are the ones who fabricated this drama.
This is also one of those main gripes I have with this issue is that you are trying to push the blame onto others for this drama when it is the PR-creators fault that this even got to this point.

If you don't feel like making a proper PR that at the very least explains what you are going to do then maybe you should take a look at yourself and improve.
It is not being "super serious" to fucking correctly present your PR, what the fuck man.

**Comment by SonixApache** [comment]
@Fruktlimpa 
Alright, point taken and agreed with, apart from the holiday PRs I have to go back a few months to start getting shitty descriptions in PRs.
![image](https://cloud.githubusercontent.com/assets/8468269/24779273/943c8c6a-1b2f-11e7-8ad4-e0d2a653b501.png)

Still no reason to cause a week-long shitstorm over a joke. Proper PR explanations exist for peer review -- not needed if there isn't supposed to be peer-review.

I'm still agreeing that this whole situation was handled badly, I've yelled at cluster/PJB myself over it. 
I'm just saying that there's *way* too much drama.

Like, "This collab removed all other collabs and became supreme king"-tier drama. Or like that one time with the DMCA.

\*edit:*
I think I've reached the point where I'll just say "this is a clash of opinions and there ain't shit we can do about it" and ditch. I've said my part.

**Comment by FudgePucker** [comment]
Discord was a mistake.

**Comment by Kammerjunk** [comment]
Spess was a mistake.

**Comment by Intigracy** [comment]
Life was a mistake.

**Comment by SonixApache** [comment]
players were a mistake desu

**Comment by Kammerjunk** [comment]
(You) were a mistake 💢

**Comment by Huuuuuuuuuuugo** [comment]
"c*ders" were a mistake

**Comment by Fruktlimpa** [comment]
@SonixApache 
I agree that the amount of drama has been overblown but in my opinion it was inevitable. Poor management from both sides simply fan the flames. 
If anything that fact that there are PRs with very shit descriptions that haven't' gotten reprimanded is a mistake. I am not saying we should have professional level PRs, memes are fine, but the PR itself should at the very least say; "Hey, this is what this PR will do".
Then you can have whatever you want after that as long as it doesn't obfuscate your intention.

**Comment by carshalash** [comment]
Did you really put muh in the title?

**Comment by Kammerjunk** [comment]
Cow goes muuh

**Comment by FudgePucker** [comment]
My friend shit on my front porch on April fools day. I thought it was funny.
The next day when I confronted him about a second pile of shit on my porch he got really pissy and offended.

IT WAS AN APRIL FOOLS PRANK FOR A GOD DAMN GOOD REASON.

**Comment by clusterfack** [comment]
The poop was optional though, just toggle it off through your doorbell.

**Comment by carshalash** [comment]
Is this some jetsons shit where your doorbell makes shit disappear?

**Comment by invoid9** [comment]
@clusterfack But the shit will only be toggled off for him. Anyone else going to visit him, will HAVE to smell shit, and then who's going to visit him once word gets around that his doorway smells like shit? He will also attract flies and other shit eaters with no way to stop them. 

Also, unrelated, but can we get poo next April? (you could disguise it under the attack animations revert)

**Comment by PJB3005** [comment]
@invoid9 yes but the Shit is under the mat and you need to pick up the mat to actually be able to smell it first.

**Comment by clusterfack** [comment]
It was a really shitty analogy to start with

**Comment by PJB3005** [comment]
Get out

**Comment by Kitfox88** [comment]
i'm gay and like attack animations because i play in a rather small window because of REASONS and that makes dissecting exactly who's toolboxing what via chat panel irritating sometimes

**Comment by optimumtact** [comment]
goof why are you here

**Comment by PJB3005** [comment]
@optimumtact

He was unbanned by accident when we moved to an organization.

**Comment by cowboybuttsdrivemenuts** [comment]
@PJB3005 
So why haven't we rebanned him?

**Comment by PJB3005** [comment]
We have.

**Comment by PJB3005** [comment]
Well, pomf did.

**Comment by cowboybuttsdrivemenuts** [comment]
God bless that chicken.

**Comment by Hoshi-chan** [comment]
So long as attack animations have options and default to off, I don't see the problem, unless they're the cause of all the lag recently.

Personally, I like the sprite ones. The weird ghostly object ones look fucking _terrible_ though.

**Comment by Exxion** [comment]
It's been nearly a month since someone commented on this so I think it's served its purpose
