### ISSUE TITLE
Morphing Mask drops Soulstone shards

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14611]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
Title says all. Hide it wherever you want, backpack, bag, boxes. the soulstone shard WILL drop to the floor if you use a morphing mask

**Comment by BobdaBiscuit** [comment]
Intended.

**Comment by Gunosaguki** [comment]
Wow, really? thats a very unusual thing to have intended

**Comment by BobdaBiscuit** [comment]
Your dude gets sent to nullspace while morphed, if you keep an active soul shard on the null body (pAIs etc drop too) it could cause fuckery.

**Comment by Shadowmech88** [comment]
Once I have *time* I intend to do away with the nullspace stuff and just put your other body inside your new body when you transmogrify, the nullspacing is causing too much of a headache.
Don't know when that will be, though.

For now though, yes it is intended.

**Comment by PJB3005** [comment]
Putting stuff inside also causes tons of headaches though.

**Comment by Shadowmech88** [comment]
Like what?
I suppose there will be ventcrawling concerns, but I could work around that by making a special container atom and putting the mob into that and putting *it* into the new mob, and adding that atom to the ventcrawling exceptions list.

What else is there?

**Comment by PJB3005** [comment]
To correctly do a refactor like this you basically need to provide wrappers around the entire BYOND location system.

**Comment by Shadowmech88** [comment]
I don't know why it would.
I just need a place to store the player's old body while the client is inside the new mob. Storing it inside the new mob instead of in nullspace would prevent issues where pAIs/soulstones/posibrains/etc are stuck looking at a black screen due to being in the old body's contents.

**Comment by Exxion** [comment]
Storage atoms, etc.

Alternatively,
1. Make an `is_held_by()` or something proc which checks if something is held by another thing through an arbitrary number of layers. (I have a possible idea for how to implement this with magic and internal BYOND shit to make it efficient, but I'd have to test if it actually works.)
2. Add code to `/mob/Entered()` to check if the thing entering the mob came from a location that is held by the old body, and add it to a list to eject when the person transforms back if it is. Make sure all children of `/mob` call the parent in `Entered()`.

**Comment by Exxion** [comment]
Actually `is_holder_of()` already exists, though it doesn't use my magic idea

**Comment by Shadowmech88** [comment]
>Add code to /mob/Entered() to check if the thing entering the mob came from a location that is held by the old body

This sounds like you want to leave the old body in nullspace, but move all of the old body's contents into the new body.

**Comment by Exxion** [comment]
I meant to move the body into the creature without fucking up dropping things or using a storage atom

**Comment by Shadowmech88** [comment]
>without fucking up dropping things

What do you mean by "dropping things"?
The old body shouldn't ever drop things, it's timestopped while the mob is transmogrified.
The new body will empty its entire contents list onto its turf when it un-transmogrifies.

**Comment by Exxion** [comment]
Then why did you need the storage atom?

**Comment by Shadowmech88** [comment]
Because if we were going to store our old body inside our new body, it would be in the new body's contents list.
Ventcrawling loops through the contents list of the mob attempting to enter the vent, and disallows the mob if it has anything in its contents list which isn't in a specific list of exceptions (things like implants, borers, and facehuggers are in said exceptions list).
So rather than add *all* mobs to that exceptions list, we can make a storage atom for transmogrified mobs and add *that* to the exceptions list, then put the mob's old body into that atom and put that atom into the new body's contents.

This will allow mobs transmogrified into ventcrawling mobs such as xenos and monkeys to ventcrawl while their old body (and thus any mobs their old body was carrying) remains centered on them rather than moved to nullspace.

**Comment by Exxion** [comment]
Ah
It's pretty stupid that it checks all `contents` for absolutely anything except a certain list of items, but whatever
Carry on
