### ISSUE TITLE
Feature request: Chaplain Miracles system

### ISSUE THREAD

**Issue by Lancemaker** [d3athrow/vgstation13#14666]
#### Description of Feature
idea : add a favor system to the chaplain job. favor is a automatic increasing variable that get multipliers based on the number of people inside the chapel. with this the chaplain can manifest miracles he can buy from his bible. and also forces the chaplain to do stuff in the chapel.
#### Difference between expected and actual behavior
Right now the Chaplain is (unless vampires and cult) a pretty much RP only job. No real problem with that, RP is the central idea of this game, but adding some surplus to that should be nice.  My idea is about making the chapel a place where people can go to get heals and buffs based on belief and religion. Pretty much a space cleric. Also the Chaplain will get favor based on how many people stay hanging in the chapel, this way it would be an actual in game reason other than RP to people go in large numbers to hear a sermon. In no way the chapel should be a better option than the medbay, it should be used differently, and possible only in dire need since the favor is not easily achieved and miracles are expensive.

possible miracles : 
 - heal minor wounds.
cure a equal number of each of the 3 health attributes. 
 - heal light, medium and greater wounds. 
same as the above escalated.
 - cure disease: 
it would remove one disease from the person (i was thinking about viruses, broken bones but i really dont know how does that work on code yet. so we might rethink this.)
 - breathless : 
target does not need to breath for a time. 
 - silence:
target is unable to talk, this should be a counter to wizards, since they would be unable to cast spells without talking (again mabe i should have smaller ideas... this can or cannot be problematic)
 - resurrect : 
the priest becomes a one time defibrillator.
 - greater resurrection : 
priest heals the target completelly and makes him go alive. 
 - talk to spirits : 
priest becomes able to summon and talk to a spirit for a time. he need the spirit body to do so, and the spirit needs to want to talk (if the player is afk it should return a message or something).
 - zone of truth : 
Rp Spell, every one in the circle is compelled to answer the truth to the priest, this should be useful by the sec.  

it would be nice to add : 
healing spells have reverse effect on undead (vampires and zombies).
ressurection has a chance to kill undead, and greater ressurection has even a greater chance, case this chance fails the target takes the heal as damage. 

#### Steps to get to coding: 
first i will need to code the favor system:
a variable that will grant a fraction of point per second by a number of people on the chapel. 
Ex : 
0.1 if there is only the priest/s
0.1 X 2 if there are 5 people in the chapel/s
so on and so forth. 
i need to do some math and set the prices of the miracles accordingly 

thats it, please give me some insight and say if the idea worth my time coding.

**Comment by Bpage5** [comment]
This seems like it'd be massively susceptible to powercreep and either abuse or disuse, depending on how long it would take to gather up enough GodCoins™ to cast one.

 I feel like making miracles cost rare or valuable items (possibly chosen randomly at roundstart from a list, excluding hilariously common objects and things that can be tagged as traitor objectives) to cast would encourage Chaplains to get out and do things instead of just herding all the greyshirts into the Chapel for Loitering-With-Padre hour.

 In addition, the miracles seem like they'd be useful to the Chaplain _personally_, and maybe useful as a one-off thing for the few souls bold enough to ask them a favor, but there's not much the miracles could do for the crew at large. There's not much I can imagine would fit under the description of "Miracles" that isn't on your list or something Xenobiology can already do.

**Comment by Riekland** [comment]
even the examples you have here are stupid op
I know it requires herding the common rabble into the church for a bit, but it's not hard enough to justify something like ressufuckingrection
what you're talking about is an admin and player issue, chaplains dont do cool shit and ask for favours that are reasonable and fun enough, admins don't actually respond to the reasonable and fun ones often enough
`>>>/forums/`

**Comment by Shadowmech88** [comment]
The problem with trying to "automate" divine miracles (as in remove the need for admin intervention) is that you will either need to make the miracles small enough to be mundane, or risk someone being able to game the system for powerful shit.

The need for admins to play god isn't ideal, but we can't exactly write an AI with the same level of judgement.
Any particular offering/reward combo could make the round great or screw it all up depending on the circumstances of the round itself. We need human judgement for that decision.

**Comment by FudgePucker** [comment]
Ideas for powers.
Wind of protection: everybody in the chapel receives zas protection toxin resistance eye damage resistance and thermal damage resistance. This would act as a last ditch effort against plasma flood. The blessing only effects people inside the chapel, only lasts a few moments outside, enough to make it to the excape shuttle. Everybody could treat it as a bunker until the shuttle arrives when distro becomes plasma.

Thread of reality: a single target besides the Chaplin becomes a barrier of reality, narsie can't be brought over as long as the Chaplin and the thread are alive, one of them dies or leaves z level the blessing ends. Thread has an overlay displaying their status to cult members. Would have to have rules to prevent faggotness like holing up in a 1x1 room in maint until round end.

The feature sink argument isn't that great when the giant fucking cancerous tumors cargo and research are the only two feature sinks.

Chapel should provide devine intervention, not small powers. It should be light in the dark. When things look their worse you pray for a way out, sometimes the sea will part.

**Comment by ghost** [comment]
just be good enough at chaplain for admin bus dude

**Comment by Kurfursten** [comment]
I don't really want to see people select the chaplain slot because they want to be a budget wizard.

**Comment by icantthinkofanameritenow** [comment]
@FudgePucker 
Feature sinks they may be, but those two things alone have the potential to have a much more serious impact than Cargo and RnD combined. Seriously, do you want people to hate the Cult mode even more than they currently do? 

Chaplain is a RP job, first and foremost- it doesn't need the surplus and certainly shouldn't be used as a MMO-cleric wannabe. If you don't want to role-play and just want neat powers, you're better off hoping you get picked to be a wizard or something.

**Comment by FudgePucker** [comment]
If you have gone loud as cult, the chaplain should be dead.

Their has to be a group of people to do the blessing, so you could just intercept the meeting and toss in a polyacid smoke grenade or a one tank bomb to crash the party. So you can't just circle jerk in a secret base until objectives are far enough to summon.

The first one isn't broken at all. How the hell is single room protection from plasma flood radically game breaking? Plasma flood is the easiest way to fuck over the entire station, and being smart enough to use something other than the mix tank you can make it be unstoppable.

**Comment by icantthinkofanameritenow** [comment]
@FudgePucker 

First, why should an RP job get powers at all? Are we going to pass special abilities off to librarians too? They're a RP-centric job too, so by your logic they should have some kind of ridiculous power too. 

Second, I can already think of one exploit that runs like this.

- Find braindeads/catatonics/monkeymen. 
- Drag them to chapel.
- Free favor

Finally, if he has to gain powers they ought to be minor things that only do little things, like sound effects or graphical changes. There is no reason that a normal, non-magical chaplain should be capable of stepping on Medbay's toes, and even less reason to use feature bloat in one department as a justification for creating feature bloat in another. 

Fudge, how about just cutting all the bloat down to manageable levels instead of trying to make them all equally bloated?

**Comment by FudgePucker** [comment]
Chaplin is more than a RP job though.
Best source of holy water.
But every round other than cult they are a worthless role, so most of the time there won't be one when you need them.

If they truely are strictly a RP job that has zero impact on rounds then remove their ability to produce holy water.

**Comment by icantthinkofanameritenow** [comment]
@FudgePucker

Don't jump from one extreme to the other, especially since holy water is useless 95% of the time. Were it not for the existence of cult mode, it would be no more useful than the IAA's promotion and demotion chips that nobody ever uses. But if it is cult, then it becomes the only way to deconvert rapidly. 

I think that's not a problem with the chaplain so much as it is a problem with the cult mode itself. And that requires another issue entirely, though I doubt you can code something to address the stupidity of the average cult player not named Kavlax.

**Comment by Exxion** [comment]
It's an RP job... that DOES have an impact on the round (at least sometimes).
Revolutionary, I know.

Anyway this is a bad idea
Miracles should be left up to the admins, who can be much more unique and interesting than a coded system.
If all you have to do is get GodBux:tm: to automagically perform one of a list of predefined "miracles," it rather devalues the miracles.
Plus it would turn Chaplain into yet another powergamer job where you grind the same shit every round to get the same advantage every round.

**Comment by FudgePucker** [comment]
It is an extreme example I must admit.
But most of the server is allergic to RP, so I don't think anybody is going to be the job that is worthless 95% of the time and doesn't even have maint access. So balance of cult is based on someone picking a worthless job.

**Comment by Lancemaker** [comment]
hey guys.. i guess i dropped it. Seems like its a bad idea, and im a new coder. I asked for the older coders for some pointers and im trying to fix a very simple bug right now and im having alot of work. I would probably not be able to code this thing with my current knowledge of both DM and VG/bay code. Thanks for the feedback anyways. i will be trying to fix bugs for a while.
