### ISSUE TITLE
Drag damage logging is badly worded

### ISSUE THREAD

**Issue by BobdaBiscuit** [d3athrow/vgstation13#14676]
#### Description of issue
Wording on some of the logs are pretty shit, we had to investigate an asimov borg causing HUGHMAHN HARAM and were presented with

>[22:57:11] Has started dragging critically wounded Brett Johnson(tifora) . 

One would think this means they are in crit and haram occurred, but with further testing they were actually dead when the dragging started.

pls fix

**Comment by SonixApache** [comment]
it fires if they're past crit and drag damage applies
i suppose i could add a clause for being dead

\*edit:* 
oh hey turns out i commented out the logging as well as the message due to the broken pulling thing
both the crit damage logs have logs, though
`add_logs(src, HM, "caused drag damage to", admin = (M.ckey))`
`add_logs(src, HM, "caused drag damage bloodloss to", admin = (HM.ckey))`

**Comment by ComicIronic** [comment]
Add a clause for being dead. Crit is generally understood to mean alive.

**Comment by ShiftyRail** [comment]
Drag damage is ded
