### ISSUE TITLE
Subspace tuneller doesn't work.

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#14714]
Got confirmation from bobda, I tried taking out the bluespace crystal twice and put in new ones, tested out different super matter bins and nothing worked.

**Comment by Shadowmech88** [comment]
In what way did it not work?
Did it do absolutely nothing?
Did it display a message as though it worked but the object was not actually moved?

Please elaborate.

**Comment by carshalash** [comment]
Absolutely no message at all. I tried teleporting small objects, large ones and large anchored ones. All had nothing happen even with a bs crystal and bin

**Comment by Kurfursten** [comment]
Reproduced bug on test server

This is a recent bug, I tested the subspace tunneler and got it to work recently (I want to say in the last month?)

**Comment by Shadowmech88** [comment]
Any runtimes?

**Comment by Exxion** [comment]
Sure sounds like it

**Comment by Gunosaguki** [comment]
I forgot to bug report this after trying two rounds to get one to work

**Comment by Shadowmech88** [comment]
I found the problem.
`NO_TELEPORT` was defined as a flag for areas, and given to Spessmart and the hive vaults. The subspace tunneler was made to not work in areas with that flag.
Unfortunately that flag was given a value of 2, and from what I can tell, *literally every area has a value of 2 for its `flags` var*. This means that the subspace tunneler won't work anywhere, and neither will crushing a bluespace crystal, since it has the same check.

This means that there must be some other flag with a value of 2 somewhere else in the code, but for the life of me, I can't find any other area-specific defines nor even any places where the `flags` var of an area is altered.

**Comment by Shadowmech88** [comment]
It turns out `/area` is a child of `/atom` and was inheriting the `FPRINT` flag.
