### ISSUE TITLE
Update the Detective (to be more in line with how fast our server is)

### ISSUE THREAD

**Issue by SerWind** [d3athrow/vgstation13#14829]
Suggestions go here right? I have two I think relatively minor changes that would help out the detective role significantly. 

1) Update the scanner to be a tablet/scanner hybrid, it now has all the information right there. Things move way to fast especially on high pop for detective to be useful in MOST (not all) situations. 
2) Let the detective set a filter for certain things on the new scanner IE black gloves, security jumpsuit, etc.

Bonus but I seriously doubt it would get the green light: make autopsies quicker, perhaps involving the new scanner, perhaps no need for the knife and shit so the detective can do it himself.

**Comment by ghost** [comment]
I'm pretty sure Autopsies are either broken or don't work on our server. Any times I've tried it it has had zero results. Autopsies aren't that slow anyway, just a cut and a scan, detective has morgue access already

**Comment by SerWind** [comment]
I've never had a problem with them, though they are kind of woefully uninformative it feels like. Anyway that's why I put it as a bonus suggestion because I didn't want it to be tied to the overall changes and then it be ignored. I still think it could do with the det just be able to outright scan them though.

**Comment by ghost** [comment]
Maybe give them a laptop that fits in backpacks where they can search medical/sec records and also work as an advanced scanner

**Comment by Shadowmech88** [comment]
@SolariousGabriella 
Did you try them recently? A bug that broke autopsies was fixed a couple months ago.

**Comment by ghost** [comment]
I haven't tried them recently, I gave up doing them because I figured the bug would never be fixed. Glad to see it's working normally now. It's a pretty cool feature and pretty helpful for a detective

**Comment by Megamaw** [comment]
yeah, we should probably buff the detective

he's got a gun but that's about it. he doesn't actually have the tools to actually do his job r/n

**Comment by SerWind** [comment]
I feel like Detective must have been pulled from another server, kind of like medbay. I mean don't get me wrong but medbay only works on our server out of sheer, unadulterated autism. And it's a team of autists. And every autist has a get out of jail free card with cloning. If detective had a thing he could go back to and just like plug shit into and it would tell you right away who did it? And there was five detectives, all female with pink hair for some reason? Yeah it would work.

**Comment by PJB3005** [comment]
*well* we did fork from Bay absolutely ages ago.

**Comment by ghost** [comment]
>he doesn't actually have the tools to actually do his job r/n

That's not true, the scanner picks up everything you'd need to figure out who did a crime or at least give you a very good lead on where to look. It's not perfect, it doesn't tell you exactly who did something and that's a good thing. It requires a little thought

**Comment by SerWind** [comment]
Actually if the scanner doesn't give you explicit info on who did it you're pretty much fucked. 
>fibers from an assistants jumpsuit
>fibers from insulated gloves

vs

>finger prints of the literal person who dun it
or
>fibers from the HoP's jumpsuit

There's very few situations where it's inbetween, and I can't actually think of any. You could have hair color and things like that, or hell, foot prints.

**Comment by ghost** [comment]
Except you aren't at all, if you give up because you hit a hurdle the job probably is not for you.
>Insulated gloves

Scan the fitness area where the silver coin spawns, scan the vendor in the assistant spawn that gives out insulated gloves, check cargo and ask if electrical maint crates have been ordered and if they have the papers still you can check who ordered it, if they dont have the papers check disposals since they probably flushed them. Between all of this you should know a list of assistants with gloves you can then you can investigate those people.

All of this is fun and gives you chance to investigate areas, talk to people and talk to suspects. Detective works just fine as it currently exists, speeding it up by giving you all the information directly from the scanner is okay as it's just a speed increase and doesn't change the actual job. Making the scanner show even more would ruin the job because retards would be able to stumble their way into catching the antags.

**Comment by ihadtoregisterforthis** [comment]
Luminol was a good idea, maybe with a bad implementation

**Comment by SerWind** [comment]
Okay so you're not actually arguing against a speed increase you're arguing against more information on the scanner because retards might luck into catching bad guys and that would derive enjoyment from you, the one good detective on the serb. The "git gud" argument is pretty terrible to be honest.

Also I fail to see how adding hair strands to identify hair colors would help people luck into shit anymore than if they manage to get finger prints which LITERALLY IDENTIFIES THE PERSON 100 PERCENT. Detective is about taking clues, putting them together, and figuring it out right? Well right now what clues do we have. Blood, fibers from clothing items, finger prints. I mean scanner clues. Two of those identify victim or perpetrator immediately. The other one is the only "I need to put shit together to figure this out" clue. 

Edit: Also the lack of info ties into the speed thing, because your solution was to spend thirty minutes to find out that half the crew has insulated gloves.

**Comment by Kammerjunk** [comment]
>The "git gud" argument is pretty terrible to be honest.

Maybe you could just git gud though 😕 
Also wait are you arguing against the one saying "you're not fucked at all because you can do investigative work around the places you'd usually find the item those fibres are from" but then right after that, you say "detective is about investigating"
Am I getting it wrong? Also you can't just say "I'm only talking about scanner clues" because it seems to me the discussion is whether the job as a whole needs the scanner improvement and detective is more than the scanner

**Comment by ghost** [comment]
>because retards might luck into catching bad guys

This is a bad thing though, half the fun of detective is figuring something out when it's not simple. If you make detective stupidly easy it would remove the fun of the job and people that get caught will be mad because the job is very easy and they can't cover their tracks. I can't think of a crime that would go unsolvable without a lot of prep time for the criminal, and I think that is fine because it rewards the antag for their hard work with going uncaught.

**Comment by SerWind** [comment]
Who said anything about making it easier? Who made that argument. Who proposed something that would make it so people could luck into catching bad guys? Did you ignore my whole post about the finger prints thing and so on? 

Also sorry Kammer but you never seem to be able to understand me so I don't think I am going to bother. Git gud.

**Comment by ghost** [comment]
Letting the scanner detect more things would make the job inherently easier

**Comment by Kammerjunk** [comment]
But you did reply to a post that said:
>Scan the fitness area where the silver coin spawns, scan the vendor in the assistant spawn that gives out insulated gloves, check cargo and ask if electrical maint crates have been ordered and if they have the papers still you can check who ordered it, if they dont have the papers check disposals since they probably flushed them.

with:
>Okay so you're not actually arguing against a speed increase you're arguing against more information on the scanner because retards might luck into catching bad guys and that would derive enjoyment from you

Which is silly because it well addressed the post preceding all that, which said:
>Actually if the scanner doesn't give you explicit info on who did it you're pretty much fucked.

**Comment by SerWind** [comment]
Solarious can you just tell me if you think Detective is perfect as is and everyone is bad at Det but you so I know if I should waste my time or not having a back and forth with you.

**Comment by ghost** [comment]
Detective is mechanically perfect, I agreed with your idea about speeding up by giving you all the information directly from the scanner but I disagree with your later idea about giving the scanner additional information it can pick up as it would change the job too much.

I think a lot of people are awful at detective, I don't think the job should be changed because people refuse to learn how to play it, like any other job they should just GIT GUD and not try to make the game easier to make up for their lack of ability.

**Comment by BitterVanilla** [comment]
I also stand by the idea that the current detective scanner we have now is fine as it is. If that negates my suggestions, then fuck you too. 
 
Two job slots for detective. 
Having a partner who can cross reference fingerprint IDs or do autopsy whilst you seek evidence, as well as cover the station since crime scenes are woefully unreported would definitely help the time/high pop pressure. It would ease the burden with the number of potential traitorslings, and it gives experienced detective players a chance to teach others how things work - security officers are usually too busy collecting current law valids; and picking up an assistant, trying to convince them to help, trying to convince the HoP/Security that they're cool and need access, and the potential 'they're metafriending every round!' is even more difficulty ontop of a constrained job. 
Mechanics and Paramedics already show they bring benefit from two job slots, as a liaison to a main department. 
 
Make the universal recorder able to identify the voices in playback/transcripts. 
As they are now it's a pain to read and it's almost impossible to highlight the important parts of a transcript. They're almost useless and I've never been able to convince a HoS to read them, and thus never had any real opportunities for interrogation. From my experience, interrogation and shoving evidence in a perp's face and catching their lies is 90% of how to get an accurate verdict, and is more fun for those involved than being caught just because a scanner you didn't know about said so. 
I realise this probably messes with saycode and it might be a mess to change, but it'd be a huge QoL change for the role.

**Comment by ghost** [comment]
We've all been on Mr. Scanner's wild 65% of the station fits the category so you're better off just getting the alert elevated to blue and start hailer grabbing until nasty shit falls out ride. If they're truly interested in a clean run, who would though when the scanner is useless 90% of the time and auxiliary evidence is just as helpful, it's not hard to get a different outfit for whatever you need, grab the right gloves then switch out and space em after your scavenger hunt making random searches the only way to find the macguffin. God have mercy on you if they bother to make a hidden cache or use a compressed cause nobody else will.

Bitter, the pda cart just needs a search string function like the medical records so they can just pull it right up. Not that there's ever fingerprints when it matters.

**Comment by SerWind** [comment]
That's a pretty crazy statement to me but I guess if you find it perfect, you find it perfect. I think a lot of people are bad at all of the roles and yes it shouldn't be changed to fit them, but I think you're seriously overstating your experiences on the serb as Det.

Anyway it wasn't even my idea for additional scanner stuff, I still think it's a really good idea but I'm fine with a speed increase by having them have all the info right there. 

That does make it easier though so I'm not sure why you'd be good with it, lol. 

Edit: Getting more info from the scanner would change the job too much does not make a lick of sense to me, and would punish shitty antags who take less prep time, so shouldn't that even out?

**Comment by ghost** [comment]
Speeding up the detective is a quality of life improvement, think of quickswap. It doesn't really change the game much it just saves you a few seconds every round when you want to change jumpsuits.

Getting more info from the scanner means the antag has to do even more to prevent getting easily caught meaning the detective has an even high chance of just catching them by scanning one thing and seeing a detail they didn't cover up.

**Comment by BitterVanilla** [comment]
/vg/code should not be tailored to punishing antags, no matter how shit they are

**Comment by SerWind** [comment]
That's a cool opinion Bitter. 

An actual antag will take the necessary prep time to not get caught, but it helps out with the ten thousand myriad bullshit crimes, I'd say.

**Comment by BitterVanilla** [comment]
Punishing antags is what lead to TG ID locked weapon triggers and I can say confidently that most of the server are against changes like that. Look at how lockboxes went down, trying to punish antagonist behaviour because 'well shitty antags are shit'. 
 
Not to mention that /vg/ admins aren't the most patient when it comes to antags biding their time. I've been killed by an admin for being a solo vampire virologist, for taking too long to try and brew a virus. Maybe if admin bus was consistently fun for everyone, it wouldn't matter if antags got weeded out by crew/adminbus because they didn't git gud/took too long. But that's not the case, and would just put even more pressure on admins. We all know how prayermin went too.

**Comment by ghost** [comment]
Yes, because putting on your biker helmet before going out to hurt people is such a high bar meanwhile the gloves are blocking prints and your spare maint jumpsuit after someone opens one of them leaves some really fucking helpful clues if you're lucky enough to even get that. Which you usually don't. It's not about antags, it's about the detective being able to be more than another ED-209 stuncuff searchbot

**Comment by SerWind** [comment]
You guys have a different understanding of the game apparently, but if everyone is cool with the scan with all the info on it that's all I really care about lol.

**Comment by Durgen** [comment]
>Make the universal recorder able to identify the voices in playback/transcripts.

This would be very helpful. The universal recorder is a bit wonky at the moment. Also it picks up things from comms so when you record a conversation with someone half of the playback will be random things said over common.

**Comment by SerWind** [comment]
Yeah that universal recorder idea is pretty cool and would also open avenues for traitors with the voice mimic shit. I kind of always wanted a camera thing too like you could access a specific cameras logs but maybe that's too much.

**Comment by ghost** [comment]
The Residue/Smell idea was a good one in the thread. Shooting a bullet gun would have a high chance to leave some gunpowder residue on your jumpsuit or outer suit. Shooting an energy weapon would have a high chance to slightly burn a corner of your clothes. Hardsuits should be immune to this and clothes should be able to have the evidence removed with space cleaner, a sink or a washing machine.

**Comment by CptWad** [comment]
Tbh theres things that dont bit should leave prints. 
For example. When you tear off peoples clothes/headset no evidence is on the headset, not even the victims.

**Comment by SerWind** [comment]
Quite a lot of things that would leave some sort of evidence but

GIT

GUD

**Comment by ghost** [comment]
One problem I've just thought of with speeding up the scanning by changing it to a tablet would be that if you die all your scanning is essentially lost. In the current system the HoS can check your computer and have all the evidence you gathered since you had to scan it into the computer, if it's just on the go you'd have to tell them all the important evidence yourself as it would be lost in the case of your death.

**Comment by icantthinkofanameritenow** [comment]
For what it's worth, I've found that autopsies fail to differentiate between damage taken before and after death so it's not all that reliable even when it is done.  Making the scanner more efficient would also be helpful, since the few times I've rolled detective I spent far more time trying to search through the fingerprint database than I did actually solving crimes. 

At the absolute minimum, there should at least be a "search" function in the security/medical records so you could plug in the fingerprint ID instead of having to look through the whole list manually every time.

**Comment by Shadowmech88** [comment]
>there should at least be a "search" function in the security/medical records so you could plug in the fingerprint ID instead of having to look through the whole list manually every time.

You can use Ctrl+F to search the security records window.
