### ISSUE TITLE
[BAGEL] A bunch of random wall intercomms have their microphones enabled at roundstart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14960]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

f45682708f6a19a77cf2b6473858a5501f49dc95 

>General description of the issue

there's just a bunch of wall intercomms that have their mics enabled at roundstart

**Comment by CptWad** [comment]
I need specific instances I cant find proofs

**Comment by SonixApache** [comment]
The one at the HoP's office is one of them, it's got the mic on and speaker off by default.
I'll look around for some specific ones in a bit.

**Comment by SonixApache** [comment]
@CptWad 
The one in the HoP office 
![image](https://cloud.githubusercontent.com/assets/8468269/26308171/62de0dbe-3ef8-11e7-903a-7012abdee3b2.png)
the one just south of the HoP office, central hallway 
![image](https://cloud.githubusercontent.com/assets/8468269/26308181/6e652f8c-3ef8-11e7-8274-aa9df0a3a28f.png)
The one just further south in the same hallway 
![image](https://cloud.githubusercontent.com/assets/8468269/26308204/82df3e94-3ef8-11e7-97fc-212dc243445a.png)
And the next one down the hallway clockwise from the last one... 
![image](https://cloud.githubusercontent.com/assets/8468269/26308240/a5602c9e-3ef8-11e7-9d3b-eccbf291ffb7.png)
And the one in the court room... 
![image](https://cloud.githubusercontent.com/assets/8468269/26308255/b23e044a-3ef8-11e7-904b-6c892db892c3.png)
In sec, at the shuttle entry point
![image](https://cloud.githubusercontent.com/assets/8468269/26308298/e82b7d3a-3ef8-11e7-965b-aa28c8e20bac.png)
This one in the armory **isn't** set wrong, but it's stuck behind shit. Move it across the room to the table with the gas masks. Or to the other side of the wall, since there's no intercomm in the secure armory.
![image](https://cloud.githubusercontent.com/assets/8468269/26308338/177b10be-3ef9-11e7-9030-6cc8a4d03ba4.png)
This one, outside genetics
![image](https://cloud.githubusercontent.com/assets/8468269/26308442/8854765e-3ef9-11e7-9c48-dd32d22256f1.png)
This one, at the dorms
![image](https://cloud.githubusercontent.com/assets/8468269/26308451/9752e938-3ef9-11e7-9d00-ba4b168df8e3.png)
This one, further clockwise from the last one. Funnily enough it's only the one on the left, not the one on top.
![image](https://cloud.githubusercontent.com/assets/8468269/26308480/b505252c-3ef9-11e7-97ad-ad84e6358de5.png)
This one, at virology access.
![image](https://cloud.githubusercontent.com/assets/8468269/26308566/166ce520-3efa-11e7-855d-744f473b19c0.png)
This one in cloning isn't wrong, but it's on the goddamn floor.
![image](https://cloud.githubusercontent.com/assets/8468269/26308618/41ea5944-3efa-11e7-83ca-4c628c982742.png)

You may want to just check it with notepad, there's a lot of them.
Not sure why would even ever need a mapped intercomm set to common with it's mic on and speaker off?
