### ISSUE TITLE
Toxins Suggestion

### ISSUE THREAD

**Issue by chaotichawk** [d3athrow/vgstation13#15085]
Since some people are rather upset with toxins I thought on a suggestion/balance to fix the problem but still make toxins a viable solution and maybe even the RD more useful (since rarely people play as RD).
So the current balance change suggestion is:
Make shutters to toxins like secure storage and the control button inside the RD room (need RD access to open),I know how bomb works and I know people will say oh the chamber is useless all you need is Heater/Freezers,but the question in point is, the TTV's are inside the toxins so being locked round start would make it hard for someone to go and grab it.I know science has thermite access in Outpost and would easily make a breach in the reinforced walls, but that would be a Science/RD problem to resolve and something to work along security/detective to find out (since that's a forced trespass)

**Comment by DrSnips** [comment]
Seeing as it's compared to the engi secure storage, it might just be broken into nearly never round. This also promotes people going RD just so they can make bombs, whcih isn't the best.
But what if, they were all in a lockbox round start? You would need RD or weapon permit access to open it (all 6 in one box) normally. This way, if you want to do them round start, you need to ask a real person, blow them open, or emag it open. If you hear a bang early in rounds, usually people look to science/toxins so if you force it open it's clear to others someone is trying to do stuff.
I do support a way to slow down toxins though.

**Comment by FudgePucker** [comment]
Just putting it in a locker or the storage area containing the canisters of plasma  might be enough.
One problem right now is that the transfer valves are on the table, hacking a single airlock in a not very often visited part of science from maintainance is all that seperates you from the keys to the destruction of research.

However fuck being unable to do toxins research because of power tripping RDs.

**Comment by FudgePucker** [comment]
Oops not research, keys to the destruction of the station.

**Comment by ghost** [comment]
Nerf plasma floods too tbh
Take five minutes to flood distro to plasma and n2o and only powergamers will notice
Both require little time to cause so much destruction

**Comment by DrSnips** [comment]
Easy fix, remove plasma. :^)

**Comment by FudgePucker** [comment]
If you make it any harder to do autmos I will murder someone REEEEEEEE

At most remove the mix tank so it takes actual effort.

**Comment by ghost** [comment]
>toxins have to manually make the mix chamber with a RPD every shift

Fuck yes, they can still make huge bombs but it'll take longer

**Comment by FudgePucker** [comment]
Wrong mix chamber.
That is kinda overboard as well considering that science doesn't get RCDs.
I was talking about the one in atmos, the one all the dumb people use to plasma flood.

**Comment by ghost** [comment]
RAPID pipe DISPENSER
Not the construction one
science can just build a mix chamber with regular walls and an RPD plus they can make it how they see fit

**Comment by ghost** [comment]
In my opinion the only problem with toxins is that the bombcap is too high as is, especially since it was increased from 6 to 7 for basically no reason.
Since the crater is so impossibly big nobody wants to repair it and if they try they can never repair it in time anyways.
Since the radius is so big all you need is to half-heartedly chuck the bomb in the general direction of where you want it and you're guaranteed to fuck up the department anyways.

Special shout-out to whoever made the current poll about the bombcap and worded it as "hey guys leave as is or lower it to 4 :^)" great job not adding more options asshole it just needs to be 6 again.
