### ISSUE TITLE
Unable to get hides from Aliens

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15169]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
From what I gathered, the only way to get an alien hide is from an empress, but I know a xenomorph mask is coded in. Is it a bug that I was not given a skin option from all types of xenomorphs?

**Comment by Sooose** [comment]
I've definitely gotten one from the drone on the metaclub asteroid before, can confirm this not to be the case in the past.

**Comment by MadmanMartian** [comment]
probably a difference between the simple_animal aliens and the carbon aliens

**Comment by ghost** [comment]
Spawned simple and carbon aliens, skinned em. All had skins. All skins made masks not that there should be a problem. Checked a mask from each not that there should have been a difference since they make the same skins. Worksonmymachine.mp3

![untitled](https://user-images.githubusercontent.com/5564796/47611501-cfcb9d00-da1b-11e8-9cec-1a420be23138.png)
