### ISSUE TITLE
Ordering Mech Circuits from Cargo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15177]
(WEB REPORT BY: smedley8 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

c1141f9ef54061ddb0cd70005e97e23523b90bc8 

>General description of the issue

Ordering Mech Circuits namly the "Ripley" and "Odesseus" do not work.

>What you expected to happen

The order to work.

>What actually happened

It didn't work.

>Steps to reproduce if possible

Order one from cargo.

**Comment by SonixApache** [comment]
"*It doesn't work*" the bane of all tech support.
Circuit crates were only added because there was no way to get the circuits otherwise, this might be a good time to kill them.

**Comment by Killette2** [comment]
I remember on pubby servers people ordered them because it was more reliable than getting RnD to make them. People also willingly used the limited cargo points to do this

**Comment by Blithering** [comment]
those were dark times, when acid was more valuable than money and noone knew how the destructive analyser worked

**Comment by jakmak** [comment]
Why not replace the circuits with a full set of mecha parts and add in more crates for mecha tools(but not mech weapons) and also buff mecha utility add-ons to be actually good

**Comment by yclatious** [comment]
Because that's massive fucking powercreep that both has no reason to be implemented since roboticists can just print parts fine and because it removes inter departmental interaction.

Do you do anything but try to powercreep jak, last time you tried and it got merged the coders made your creep take a minute to print,  coders will probably do the same with buffed up mecha utility add-ons and make it so they require shit like phazon if it ever got merged.

**Comment by jakmak3** [comment]
As it stands now ylcat outside of mining and murderboning mechas are worthless and even for mining they are roughly equal to a miner kitted out with full sci gear. Most of the utility modules are either so worthlessly useless that they dont get made since they are outclassed by the hand held versions of their gear and the other half are so expensive resource wise it is not worth it to bother trying to use them. In our code currently all mechs can be used for effectively are for combat and mining

Abd all the shit i try to power creep needs some form of buffing. Machine upgrades for the sleeper and fabricators were total trash before I changed them. Sleepers would vend 2 seldom used chems one of which im surprised is even still in the code (phalanxamine) and the upgrades for fabricators was almost completely negligible (t3 lasers would mean 1/1000th of the cost would be shaved off and pico manipulators removed a whole .5 seconds from production!). Not to mention trying to buff emp grenades because they were and still are total garbage and a borderline waste of TC if bought via traitor uplink.

**Comment by SonixApache** [comment]
A box of ripley parts wouldn't be a bad thing to add to cargo 

**IF**
it still required roboticists to assemble them AND
we had something more for roboticists to do.
Like IPC maintenance, or more bots.

**Comment by jakmak3** [comment]
wypi and wyci sonix

**Comment by Exxion** [comment]
Do you just login on a random one of your accounts every time you want to use GitHub?

**Comment by jakmak3** [comment]
no because my mobile is logged into my first git and this is my most recent and im to lazy to change it

**Comment by ghost** [comment]
My bad, looks like you use fixes #15177 in the desc for github to autoclose an issue? @gbasood

**Comment by SonixApache** [comment]
'fixes | closes | resolves #xxxxx'

**Comment by gbasood** [comment]
The important thing is you don't have words between the autoclose keyword and issues.
Lists are fine:
Fixes #x, #y, #z
This is not fine:
Fixes that bug that kills everyone #x
