### ISSUE TITLE
Locking departments/roles behind playtime? 

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#15215]
http://ss13.moe/index.php/poll/114

This looks ominous. 

So I guess if you want to talk about this we can. Do you think medbay should be locked behind a certain number of hours of playtime?  Do you think any other departments should be locked behind playtime? What amount of playtime do you think would be reasonable? Do you think locking it behind playtime is outrageous? What do you think about current locks? 

Should captain be locked behind 3 years of playtime? :^)

Silicons: Cyborgs locked equal to Security's lock
Mommi: Less than silicons/security(if at all)
AI: Equal to Captain's lock time
Some reasoning: These roles can't be joined into mid-game or transferred to without new units being built, making them an especially scarce 'resource'.

Engineering: Perhaps?
All head roles: One year????

**Comment by jknpj** [comment]
Medbay? Come on. Silicons need it, not medbay.

**Comment by PJB3005** [comment]
This is why polls don't fucking work.

Remove polls when.

**Comment by nuklearcellphoneg** [comment]
@jknpj Right so what kind of time do you think silicons should be locked behind? AIs? Mommis?

**Comment by Ephx1** [comment]
Isn't there a playtime lock for Security? I think standard cyborgs should be that long, then AI would be as long as it is for Captain. I think MoMMIs should be a little less than Cyborgs, because while they still require law following, they have less chance to screw things up as their laws will usually be their standard affair. 

Edit: To be clear, I'm only suggesting this for silicons because they have 5 slots total and to get more they have to be _built_. Unlike other roles where they're shit, you can just instantly replace them with someone not functionally retarded.

**Comment by SonixApache** [comment]
aptitude tests for every job

jokes aside, nah, there's new people and shit people in every job
dying's part of the game, cope with the situation in deadchat like everyone else

**Comment by Gringonius** [comment]
>WHY ISN'T THIS DOCTOR HEALING ME FAST ENOUGH I NEED TO COLLECT MY VALIDS FUCKING HIPPIES, BUNKER NOW

The only department I can see a playtime lock being somewhat justified would be engineering considering how screwing up there can ends rounds. But even then how much would a new player learn with 30 days of not going in there to begin with?

**Comment by Kuranon** [comment]
This won't fix anything

**Comment by DrSnips** [comment]
A small counter thing would be great that tracked how many times you've round started or joined as a department (silicon, command, engineering, medical, etc.). This would be helpful in locking head roles to only experienced players for certain fields like neededing 20 rounds in engineering to play CE. Assistant would not count as anything. Its also helpful to admins because they can find out if a person really knows whats up or not, if some engi looses the goose but has 20 rounds for engineering, its clear it was intentional if they claim it was an accident.

**Comment by FudgePucker** [comment]
You can still fuck up with having that much experience via time off rusting skills or sloppy work from going too fast

**Comment by DrSnips** [comment]
You could have it delete all recorded data if the account hasnt been active for a good amount of time, 6 months would be fair. If it was sloppy work, thats a ban no questions.

**Comment by nuklearcellphoneg** [comment]
@Gringonius Tons, I'd say. I learned a good deal about medbay outside of medbay, at the very least the basic damage types, how to stop bleeding, and how to fix burns- it was also where I learned to hack doors, and construct and deconstruct walls and stuff. It's a very everyman department. I would argue engineering would be the least necessary, but I wouldn't disagree with it being locked behind a week or something. Further, I don't think it's about fast healz. I think it's about people who can't play the game at all, who get dropped into a medbay round where they can't keep up, get overwhelmed, don't learn anything, get screamed at, and don't play medbay again.

And maybe fast healz. :^)

@kuranon 'This won't fix anything' won't fix anything.

@DrSnips Would be nice, but that seems a bit much to code(as well as we'd have no legacy data for older players, albeit something might could be coded to comb the logs for some of that). I think we have enough old enough players to lock Head positions behind a ton of time, which would imply some real respectable experience outside of just 'this guy is a head of staff, you should listen to him'.

@FudgePucker Yes, but the reason they fucked up isn't going to be that they bashed their dying patient's head in with a medkit.

**Comment by Theophrastus1** [comment]
Science + Medbay 10 days
Sec 15 days
Heads 20 days
AI and Silicon 30 days

This is a similar timeframe i remember from when i first started playing, but i added in science since you can get someone in toxins and fuck shit up if you dont know, or open the canisters on accident and fuck up the department and get bannu'd

Science is very debatable, but Engineering and Civ roles give you the best training in game sense and basic building/deconstructing so they shouldn't be locked.

**Comment by DrSnips** [comment]
@nuklearcellphoneg If it was implimented now, it wouldnt be an issue for people who want to play a certain role because  HoP (anyone who steals the spare) might be useful actually for the first few weeks people need to get the time required.
Or enable the time counter and then apply the time required lock after a month. People will have the required at that point to play all roles if they activelly played in that month.

**Comment by nuklearcellphoneg** [comment]
I think that the circumstances where they would need to steal the spare and act as the HoP would be special and a learning experience unto itself that would be helpful  with situations that HoPs must sometimes face- for example knowing ways people can break into his secure quarters.

Not having access to the role is very different from, say, someone who became the HoP who had been banned from the role.

**Comment by Theophrastus1** [comment]
@nuklearcellphoneg well isn't that technically a permaban offense if they end up in that position unless an admin says yeah sure it's fine just roll with it? Because that's technically working around a role ban

**Comment by nuklearcellphoneg** [comment]
Exactly, which is why I said there was a difference.

If you don't have access to the role round start because of inexperience, and wind up in the role via in-round circumstances, we wouldn't be looking to punish someone because of that, nor would we be extra critical in our notes and so on- of course they're going to be inexperienced or bad at it, there's obvious reasons for that.

If someone is HoP banned, goes assistant, goes to the Captain, and asks to become the HoP, specifically, that's where we'd go out of our way to punish someone.

I think putting a year cap of play time for all head roles would be very interesting in and of itself, or even a set number of connections, because then you'd have a legitimate reason for expecting some form of experience or seniority from a Head of Staff or Captain.

:^) That's just me though, I'd have no faith in others supporting this myself.

**Comment by Theophrastus1** [comment]
A year is far too long. Like I brought up, Heads are good after about 20 days, if you're not an ape and can learn it doesn't take much to fully learn one department, or at least be able to read the wiki for all the roles in your department. Silicon/AI definitely need to be the highest amount of time locked just due to the fact that a lot of people fail to interpret our laws correctly, and they need to get used to and understand how exactly they can use and abuse the laws before subjecting themselves to following them.
