### ISSUE TITLE
Disappearing photos when placed in envelopes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15220]
(WEB REPORT BY: domku REMOTE: 172.93.109.202:7777)
>Revision:fa91c37251625074933911b550a7bbla7d07bde0 

>General description of the issue:
Any photographic image placed in an envelope disappears entirely

>What you expected to happen:
The image to remain inside the envelope until being taken out, not disappearing from existance entirely

>What actually happened
The image disappeared as soon as the image was placed in the envelope and still missing when opened

>Steps to reproduce if possible
Place a photographic image in an envelope

**Comment by Shadowmech88** [comment]
So it turns out that the photo isn't actually disappearing, it's being attached to the envelope, since envelopes are a child of `/paper`.
I agree that it's not optimal to need to attach a photo to a piece of paper and then put the paper in the envelope just to mail a photo, but I'm not sure whether removing the ability to attach photos directly to envelopes is the best option.
