### ISSUE TITLE
meleeing yourself with a gun wastes the bullet but it doesn't shoot

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15277]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: d2b45f9c028a58ad5879a8939ba61ed2a8cc4229 

>General description of the issue
meleeing yourself with a mateba on an intent other than harm will spedn the bullet, but you won't shoot yourself

>What you expected to happen
not lose bullet or shoot yourself with bullet

>What actually happened
mateba drops a casing, and there's one less bullet in mateba

>Steps to reproduce if possible
I grabbed the pair of matebas from the deff goonesat, and melee'd myself with disarm intent at one point while trying to loot a body, and noticed the bullet casing as well as my gun missing a bullet. I tested it again and sure enough, I wasted another bullet.
I don't know if the other guns do this, I only tested the mateba

**Comment by Exxion** [comment]
magic

**Comment by SonixApache** [comment]
is the casing spent or not

**Comment by RealestEstate** [comment]
casing is spent yes tried reloading the gun with the casing that fell out, didn't work.

**Comment by SonixApache** [comment]
Been testing this, some findings:
- Melee works with all intents but HARM/red
- Melee works on yourself AND on others
- Casing gets dropped on all intents but HARM/red
- Only one casing gets dropped by meleeing - more melee does not mean more casings
- The first shot fired after meleeing *does not drop a casing*
- Seems to be an issue with every gun
- Meleeing places a bullet in the chamber. As example, meleeing with a C-20r creates a `/obj/item/projectile/bullet/midbullet` and sets the `in_chamber` var as a reference to that bullet. This bullet (and thus var) is not present at any time during normal firing.
- This means that meleeing causes the `process_chambered()` proc to fire.

I'm not 100% on what the actual cause is, but it's probably got to do with `Gun.dm#L335`
