### ISSUE TITLE
Deff auxiliary AI core slots have windoors on the same tile as the AI.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15406]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
So there's an invisible barrier (when the AI's in place) preventing carding et al.

**Comment by SonixApache** [comment]
Alt+click on AI to get tile?

**Comment by Exxion** [comment]
Oh this is hilarious
I'm guessing the AI layers over the windoor, because it's technically a mob
So you can't click the windoor to open it
But if it's closed, you can't Alt+click the tile because the windoor's in the way

That said, just walking into it *should* open the windoor unless yet another dense object is also on the tile, because objs are *always* earlier in `contents` than mobs

**Comment by ghost** [comment]
Yeah, if you then secure a full window as well, you basically cant get at them. It's pretty dope.

**Comment by ReindH** [comment]
Ballistics still kill, cultist shades (forgot their name) easily kill them, it denies people to quickly card them or wrench them out of place without throwing a toolbox 20 times, pretty stupid.

**Comment by Exxion** [comment]
Just kick a glass shard

The AI should probably reside on the structure plane rather than the mob one

**Comment by Duny-** [comment]
So what's the correct way to fix this, change the AI itself or the map?

**Comment by ReindH** [comment]
Just map the windoor so it's not on the same tile as the AIs.

**Comment by Duny-** [comment]
I asked for the best way not the obvious lazy way out

**Comment by Exxion** [comment]
Make Alt+clicking check range rather than adjacency
There's no good reason for it to check adjacency, since you still couldn't actually interact with anything you weren't adjacent to anyway, and there is no case in which it can give you any more information than right clicking on the tile does (as long as it's still restricted to a range of 1)

**Comment by ReindH** [comment]
If you can make it so people can see the windoor and open them in any other way than changing the position of windoor, do so. But just because something seems lazy doesn't mean it's a bad idea.
