### ISSUE TITLE
Internal Affairs Cargo access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15420]
(WEB REPORT BY: senaat1 REMOTE: 172.93.109.202:7777)
>Revision 

Revision: 897b81d32834d508ae3631cbe487f0be59a3406b 

>General description of the issue
Internal Affairs has access to the cargo bay area but not to the front office, so they have to enter through maintenance.

**Comment by Kurfursten** [comment]
This is to prevent IAAs from being able to confirm orders IIRC

**Comment by SonixApache** [comment]
How hard would it be to add a `cargo console` permission?

**Comment by ghost** [comment]
Afaik, add it to access.dm, update the jobs that should have it including adminbus role ID's, cyborg/mommi/AI, and make the consoles check for it instead. Then make sure nothing weird goes on with the id comp. Airlocks probably pull from access.dm so that should be fine. Anything missed would be easily and quickly hotfixed. Any of the mechanic addition pr's would probably help.
