### ISSUE TITLE
Trash Cubes are Sent to the Mass Driver by Default

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#15531]
The garbage sorter machine that looks a lot like some kind of crusher sends materials and recyclables to a conveyor belt, and miscellaneous items to another. The recyclable items go through a very inefficient recycling furnace, and then through a stacker before being returned collectively as one or two sheets of metal or glass. If something doesn't belong to the recyclable line the furnace and stacker pass it along untouched to the tile with the reclaimed material. Meanwhile the bloody labcoats and PDAs line up to be spaced via mass driver.
Trash cubes break into the items they once were when placed on the recycling furnace, and those items may or may not be recyclable. The cube itself however is sent to the spaceables pile where it won't break apart. This can be manually changed so the sorter sends misc. items (including trash cubes) to the furnace, but then all the trash that belongs to space would never reach the driver.
Since nobody recycles anything, and trash compactors are only on one map this is a very minor issue.

**Comment by Kurfursten** [comment]
That's WAD actually, the reasoning was that, as you pointed out, many items in cubes aren't recycleable and people could toggle RECYK_MISC on the sorter if they wanted to.

Now, if you think it should be different you could change its class to RECYK_METAL or something.

**Comment by FudgePucker** [comment]
What if the garbage sorter dismantled the trash cube first?
That seems like it would be designed to do that.

**Comment by Exxion** [comment]
The recycling system is old and bad
1. The sorter is superfluous, as unrecyclable items just pass right through the furnace
2. The furnace will recycle recyclable containers, but not their unrecyclable contents, so you have to manually go and put those on the mass driver belt after they come out the sheet chute
3. Really that's it but I wanted a third thing

Number 2 means that it's impossible to properly sort everything without either a sorter that comes after the recycler, or some sorting functionality built into the recycler. Since having two sorters is stupid, I propose removing the sorting machine entirely and just folding its functionality into the recycler.
