### ISSUE TITLE
Typo in Soy Late drink

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15658]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

a4f1b05f2a5f7f23b636edcc6a15115d10c1fc8c 

>General description of the issue

A nice and refrshing beverage while you are reading.

**Comment by Kurfursten** [comment]
The soy latte is a drink that boggles my mind, because it's the only bar drink to use soymilk and was therefore the justification for putting five hundred (500) units of soy milk in the boozeomat that never gets used. Same deal with bilk for normal milk, this stuff only gets used if the chef comes to steal it.

**Comment by Exxion** [comment]
In my nearly two years of playing almost exclusively bartender, I have been asked for either of those drinks by name maybe once each.

Bilk is my go-to choice anytime someone asks for something awful, though. Unless I have Amasec on hand.
This happens more often than you think.

**Comment by SonixApache** [comment]
can't believe i made a typo in an issue report about a typo
*again*
