### ISSUE TITLE
Player Controlled Slimes cannot attack certain things

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15686]
(WEB REPORT BY: ch0c0latem00se REMOTE: 172.93.109.202:7777)
>Revision dea69d34b455da695e91a2059a68e8c7340efb9f

>General description of the issue
Players turned into slimes have limited ability to attack things, cannot attack windoors, windows, grilles.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Killette2** [comment]
Grow into an adult to do that
it's so babbies can't break out of xenobio but adults can
Old shit from metroids

**Comment by SonixApache** [comment]
[not a bug]
metroids when

**Comment by Shadowmech88** [comment]
When someone thinks up mechanics for them that are still faithful to Metroid lore, but sufficiently different from slime mechanics so as to justify their existence alongside slimes. Which is difficult because slimes used to be metroids, and so already have pretty metroid-like mechanics.

Or are you suggesting we reskin slimes back into metroids?

**Comment by SonixApache** [comment]
the latter
I played slime rancher for a bit and concluded that our slimes are tame and lame as shit.

**Comment by jknpj** [comment]
we need to bring xenos to xenobiology
