### ISSUE TITLE
Supermatter monitoring sensor isn't available

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15771]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
c34f60199eb5ef8ce16ce1cff443957bdccca81d

# Description
On box, you can't use the supermatter sensor info in the AAC with the roundstart shard.
# Steps to Reproduce
Place box roundstart supermatter shard somewhere
Go to an AAC
Set a thing to check for supermatter sensor info
Note how you can't select a sensor
# What you Expected
to be able to select the sensor
# What Actually Happened
click ----, nothing happens

**Comment by SonixApache** [comment]
Okay, turns out you can multitool a supermatter shard without nuking yourself.

However! Cloning doesn't work, nor does resetting the frequency.
And shards never start out with any metadata set, which is a shame.

**Comment by DamianX** [comment]
Is this in any way specific to box as the OP suggests?

**Comment by SonixApache** [comment]
*nope*
Just tested in on box when I made the report, that's all.

**Comment by DamianX** [comment]
Well. You can't select a sensor because shards don't start with a frequency/id set.
Should this be changed?
If so, to what? All maps (except Dunystation, for some reason) have the SME's room AAC set to 1349. We could have shards default to that frequency, and assign them an ID on spawn like the gyrotrons do.
But having to multitool the insta-death shard manually sounds fun to me.
