### ISSUE TITLE
"ProtectStation" AI module should be moved to the high-risk or core module sections of the upload

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#15828]
This goes to all maps.

The ProtectStation module is reachable in the upload to anyone who runs in without being further locked away behind an airlock or windoor. This module, that lays next to NT Default, Freeform and Reset, is anything but a safe lawset to be uploaded to the AI.
While intended to free silicons from protecting antagonists such as nuclear operatives and wizards those are generally dealt with NT Default and the laws ProtectStation adds are in almost every situation instead used by valid-hungry silicon players to kill whoever they can with the reasoning that any laws that aren't from Asimov can be interpreted literally and without outside rules complementing them.
The most common things this module causes are summary executions for: crew putting cracks on windows, breaking lights and scientists blowing up the bomb test site (because that's still part of the station) and, more rarely, crew who are redecorating a part of the station by removing lots of tiles and deconstructing walls.

Come to think of it, I can't remember this particular law being used against antags ever since NT Default has been a thing. It really shouldn't be this easily reachable by whatever clown or assistant that manages to get into the upload.

Edit: To add, why not swap it with the Asimov board? It seems silly that the truly default lawset is locked away. Having NTD and Asimov as the two readily-accessible lawsets seems like a good setup.

**Comment by CptWad** [comment]
Cant really argue with that
though personally, the best lawset to have the sillycons on is some form of keeper
though ive always been a fan of goons AI lawset since it removes a very key word to everyones problems

1. You may not injure a human being or cause a human being to come to harm.
2. You must obey orders given to you by human beings based on the station's chain of command, except where such orders would conflict with the First Law.
3. You must protect your own existence as long as such does not conflict with the First or Second Law.

fixes security vs AI, crew vs AI and generally all the other problems that come with being an AI

**Comment by Exxion** [comment]
Inaction clause or riot

**Comment by Intigracy** [comment]
Basing it on chain of command is dumb.
