### ISSUE TITLE
Why is ZAS so shitty?

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#15913]
I can take that it stunlocks you
I can take that it will slam you into a potted plant and put you into crit
But why does it do both when a hull breach or gas leak is one of the easiest things anybody can accomplish?

I feel like this is a huge balance issue that everyone ignores for "realism" and not any other argument. It can be deadly but it's been too much for too long. It gets old because of how common it causes deaths compared to someone actively trying to kill you, and it's not fun to deal with due to how overwhelming it is to the average geared crewmate (not a powergamer).

**Comment by yclatious** [comment]
Because its fun to have it hardcore as it is.

Rest of your explanation about realism can go toss stones in the river, having meaningfull atmos that has consequences is fun and !FUN!, get good if you cant handle it.

**Comment by PJB3005** [comment]
TG player detected.

**Comment by Killette2** [comment]
Git gud just equates to powergaming. I can't be the only one who dislikes going from 100% to crit just from opening a door without magboots.

**Comment by clusterfack** [comment]
I'm not sure we should modify a system based on feedback from a player who is on permanent unending probation 🤔

**Comment by yclatious** [comment]
Git gud means get used to a harcore system and learn how to mitigate danger and risk, not powergame delight.

If you cant avoid ZAS or mitigate it in any way that isnt considered powergaming to you, I ask you sincerely, what are you doing here instead of places like Paradise or other rp servers where powergaming is minimal and atmos is for the most part baby tier instead of here where we do have some decent powergaming and a hardcore system. Cluster also has a point.

**Comment by PJB3005** [comment]
Real answer though:

Surviving ZAS isn't that hard. Opening airlock and instantly going into crit is extremely rare especially if you're wearing some armor. ZAS is still more useful as a stun for an entire room than actually being used directly as a way to kill people.

**Comment by Killette2** [comment]
Cluster does not have a point, it pertains to me not the issue and that's ass retarded. I also argued for this prior for 2 years.

@PJB3005 It can do that in cluttered rooms with lots of objects, where you can get slammed into multiple things at once or after each other. What about a cooldown on the damage you can take so it's more strategic instead of gamble how many things will ZAS decide to slam you into?

**Comment by PJB3005** [comment]
Things slamming into you barely does any damage as far as I can tell. Besides it's extremely difficult to actually ensure somebody gets slammed by things because then they already have to be close to the suction point.

If you want to kill somebody with ZAS, just throw the bomb at them and let it do the actual work.

**Comment by Killette2** [comment]
I've been slammed into up to 10 objects before, it really can add up

**Comment by yclatious** [comment]
No, cluster does have a point, why would we change the entire hardcore system over you? Never mind the fact that you might or might not be a shitter, why would we change a server wide and server accepted hardcore system just for you and you alone? Almost nobody else feels the same way, much less enough to make a issue like you have, but you don't even have a slight popular opinion, its a small not even loud minority.

Ironically enough, unless you pressurized a room to the point of it being more condensed than the core of jupiter and made the other one void, just taking someones air out is usualy more deadly due to bleed loss and lung damage. This is just "I ded, pls nerf" in a nutshell really, you overestimate the frequency of instakills or the effect of object slamming and you want it all nerfed because you want it, not because you have a community wide agreement on it. Tbh, git good

**Comment by ghost** [comment]
Can someone here explain me how the fuck do I get slammed into the same wall tile 6 times in a row after a single door opening, with no additional doors being opened or changes into the atmosphere

It really makes me think

**Comment by PJB3005** [comment]
See now that's a bug worth reporting.

**Comment by Killette2** [comment]
I thought it was a feature :smirk:

**Comment by Killette2** [comment]
@yclatious maybe I made this issue to see if other people also have an issue with it, like the person who just commented. I think you really jumped the gun on "if it's not my problem then it's not a problem".

**Comment by ghost** [comment]
It's also fucking retarded that maint doors have no firelocks. I've been literally 100-to-0 stunlocked with no warning, and you can depressurize ALL of Maint with one single hole or broken window. Isn't that great?

**Comment by yclatious** [comment]
His issue isn't it being hardcore, which is your point, its a bug that coders were unaware of, and when I play these days, I don't see anyone complaining at all, be it on the thread or ingame, ic or ooc, at most I sometimes get a bit annoyed at being slipped ten times in a row over atmos bollocks but really, nobody Ive seen these days shares the sentiment.

**Comment by N3X15** [comment]
hey
hey killette

git gud

**Comment by Killette2** [comment]
If it's a bug that's been causing this problem then maybe this isn't what I'm making it out to be and that could be my issue all along. I'm pretty disappointed that most of you went for the personal route instead of looking at the situation as a whole.

**Comment by yclatious** [comment]
Hard to take a dude that scams kids out of roblocks paid currency with shitty cosmetics seriously laddie, don't put the blame on me.

**Comment by ghost** [comment]
Will everyone shut the fuck up

**Comment by Killette2** [comment]
>heart emojis cry for peace
>after a personal attack

Even kolith had more mature moments when criticizing me

**Comment by N3X15** [comment]
But git gud

**Comment by Killette2** [comment]
-Infamous faggot makes an issue
-Coders meme and try to beat the OP's faggot score
-One min gives a decent analysis of it and his counterargument
-Another player chips in about the topic and provides information
-Coders continue to meme
-I call out their shit and go back to the issue while I get deflected with personal attacks
-Player who chipped in just wants us to STFU because this looks like a circus

I guess I really did get babies day out. We can't talk about ZAS without it devolving into this because I'm the OP

**Comment by SonixApache** [comment]
>I can't be the only one who dislikes going from 100% to crit just from opening a door without magboots.

the answer is not to open the door
you are presented with a choice:
press a button and die horribly
or don't press a button and don't die horribly

you are somehow inclined to make the wrong choice; that's a you problem

**Comment by gbasood** [comment]
no your complaint is dumb and literally just "why ZAS", it provides nothing to discuss other than "ZAS is bad stop making it bad"
space is deadly and you're asking for it to be made soft and cuddly, which last I checked isn't something that the majority of our playerbase wants.
@Unknown-as-Captain did happen to point out a bug which is good and he should probably make it its own issue so it isn't buried under you trying to complain about coders when the problem with this issue is you didn't think it through

**Comment by yclatious** [comment]
More of the lines of
-You complains about x
-Everyone else tells you x is accepted and that you are one of the few who think its bad and that its due to you being casual
-Random player chips in actual coding issues with it
-Coders keep the stance since you didn't actually argue anything towards how making it more casual would be best, you at best described
-Blame lack of response on people meming over you
-I joke about what you do
-Still no argument as to how casualized is better

I mean, really dude, If you tried to argue how casualized is better, im not seeing it.

**Comment by Killette2** [comment]
I clearly said damage and stun is too much. If the damage is more than what it should be at random times due to a bug then that would explain my complaint.

**Comment by yclatious** [comment]
Again, exaggerated version of the common story and that's not a argument as to how casual land is better, if you don't have a argument and the bug is indeed the only thing the complaint is about, id say itd be better to just close this since no discussion is actually being made but us telling you to stop being a scrub.

**Comment by Killette2** [comment]
Can't close it without the bug tag

**Comment by gbasood** [comment]
🤔 
the only bug is something your OP doesn't describe so actually yeah we can
