### ISSUE TITLE
Deff medbay

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15975]
(WEB REPORT BY: robosperg REMOTE: 172.93.109.202:7777)
# Revision
535535b12243268dd46612b745b07f961f0a56fb

# Description
There are no stretchers in medbay
# Steps to Reproduce
Load into deff
# What you Expected
Stretchers
# What Actually Happened
Fuk u duny

**Comment by SonixApache** [comment]
@Duny-

**Comment by nuklearcellphoneg** [comment]
Well, Duny's exes never referred to him as much of a stretcher.

**Comment by ShiftyRail** [comment]
There is no Mancrowave either, which is kind of annoying for processing plamsamen who lit themselves on fire.
I don't know if this is intentional or not. If it is intentional, please reconsider.

**Comment by Duny-** [comment]
The mancrowave is too ugly and bulky of a thing to add just for the scenario of plasmamen who have lit themselves on fire. If there is no other solution when that happens just think of a different one that doesn't pollute medbay with this abomination, or let plasmamen regret their life choices. Sounds like something that should be hard to treat anyway.

**Comment by ShiftyRail** [comment]
There are plenty of space for the mancrowave, as shown in this picture

![a modest proposal](https://user-images.githubusercontent.com/31417754/30431428-d3b8e19c-995e-11e7-8d21-7bce90f8b6d3.png)

>doesn't pollute medbay with this abomination

t. has painted Medbay black instead of the traditional blue-white scheme
Abomination is subjective and not a real reason for deletion

>let plasmamen regret their life choices

Are you encouraging me to be a shitter

>Sounds like something that should be hard to treat anyway.

Don't know if there is a typo or not, but it's not hard - you cryo them, wait a bit and then feed them tons of Kelotane via sleepers
It's just annoying and takes time from both you and the patient, and also makes it a consistency issue since it's a feature present in some maps and not in others.

**Comment by Duny-** [comment]
See https://github.com/vgstation-coders/vgstation13/issues/8047, the mancrowave isn't necessary in the slightest anymore and I'm not sure why this issue hasn't been closed already after fixing the maps.
I'm not re-adding the mancrowave just so you can treat plasmamen more quickly in a very specific situation.

**Comment by SonixApache** [comment]
@ShiftyRail just use a fucking sleeper, they have the same functionality. Throw them in cryo if they need cooling.

**Comment by ShiftyRail** [comment]
I already know how to do that
It simply takes unnecessary longer to wake people up with sleepers. In the middle of the wild ride the click delay (because that's a thing) can make the difference.
Same thing with cooling down Plasmamen and burned down people.

If Duny doesn't want it, fine, but I believe it wasn't as unnecessary as you think it is.

**Comment by SonixApache** [comment]
Should make a feature request for a hotkey (alt-click?) to sleeperwake people.

**Comment by Exxion** [comment]
>He doesn't know
