### ISSUE TITLE
Remove Mancrowave

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#15989]
#### Description of issue
Mancrowave exists.

#### Difference between expected and actual behavior
Mancrowave exists, yet should not.

#### Steps to reproduce 
Join a game on any map but deff and go to medbay: Behold, the mancrowave.

#### Specific information for locating
It's near cryo.

#### Length of time in which bug has been known to occur
Since around the time of hypothermia.

#### Server revision
Post hypothermia.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
What did he mean by this?

**Comment by ChugMonkey** [comment]
Remove mancrowave, bring back roundstart skelemen and xeno heads. Sounds like a win win to me

**Comment by Intigracy** [comment]
skelemen were removed due to the massive amount of buffs they'd recieved

blame megamaw

**Comment by nuklearcellphoneg** [comment]
Remove mancrowave.

**Comment by TheFriggenSawbones** [comment]
remove nuke

**Comment by Kurfursten** [comment]
I don't really understand what makes people dislike the Mancrowave so much. People always say "you can just use the sleeper", but people enjoy using the THR because it auto-wakes + has a satisfying animation and sound. Some game theory here, but finishing a patient's treatment with an easily identifiable sound that is culturally coded to mean "finished" probably produces a dopamine response in the reward center of the brain.

Since Duny has complained about the Mancrowave taking up 2x1 squares instead of 1x1, I toyed with designing a black-colored 1-tile "next generation" THR for Deff called a Dithermal Utility for Natural Youth. Perhaps this new technology could remove light bruising with exfoliation, for that natural youth look.

It's really hard to come up with a good Y word.

**Comment by ShiftyRail** [comment]
Equipment lives matters
Adopt a Mancrowave today

**Comment by Exxion** [comment]
There's an entire extra button press AND click to wake with the sleepers, too

I'm being completely serious by the way

**Comment by Kitfox88** [comment]
I think the mancrowave is fun and stuffing people into a glorified tanning bed to defrost them is enjoyable. Plus yeah, the ding.

**Comment by Kammerjunk** [comment]
Mancrowave wakes you up
Sleeper wakes you up
Mancrowave also regulates your temperature without leporazine
Mancrowave also actually wakes you up instead of needing a few more shakey wakeys
Both take up 2 tiles

**Comment by Exxion** [comment]
I feel like most of the hate it gets is just due to association

**Comment by Blithering** [comment]
Mancrowave also has a neat emag feature and makes diona heads pop

**Comment by Shadowmech88** [comment]
What about making the mancrowave a tall structure that only physically takes up one tile, like a cryo tube?

**Comment by Exxion** [comment]
Would involve completely rewriting it, but honestly it should be rewritten anyway

**Comment by Fruktlimpa** [comment]
The mancrowaves temperature regulation feature is actually good. People give it a lot of hate because it is associated with celtothermia, which is understandable, but please don't deny its features.

**Comment by SonixApache** [comment]
I dislike the mancrowave because it's Yet Another Machine™ and it takes up more precious space in medbay. That's all, really.

**Comment by Kitfox88** [comment]
>Mancrowave also has a neat emag feature and makes diona heads pop

What's the emagged gimmick? There's no wiki entry.

**Comment by nuklearcellphoneg** [comment]
I don't really care for or against the mancrowave, to be honest.

However, I noticed that Duny successfully did not add the mancrowave- it seems redundant. If it's redundant enough to be left out of one map, then I think it's reasonable enough that we should consider either removing it or modifying it in a way wherein it has some some more utility, because as noted above, it's redundant, albeit it saves a click or so.

Since Kammer noted it regulates your temperature, that's nice, because it would be reasonable to climb into a mancrowave and manually stopping the pop out so you could survive an extreme cold temp... but I'd also assume it'd help in the case of super hot temps like with a plasma fire, which is silly for it to do. It heats up cold people from cryo.

**Comment by Kurfursten** [comment]
It's very simple Nuke. A microwave heats things up by rotating the water molecules inside organic structures. A mancrowave can cool people off by rotating the water molecules in the other direction.

**Comment by nuklearcellphoneg** [comment]
I'm confused. Why do people with that one symptom that causes them to spin around and around not heat up or cool down when doing so??

**Comment by Kurfursten** [comment]
A better question is why we don't need to crack open a CO2 canister in botany to make the plants grow

**Comment by nuklearcellphoneg** [comment]
Because autists are mouth breathers and botanists are autists.

**Comment by ShiftyRail** [comment]
>If it's redundant enough to be left out of one map

The mancrowave strictly speaking isn't needed (anymore), but it helps a lot in the ride and the sound is just satisfying

**Comment by Kurfursten** [comment]
I mean, Nuke wanting the THR to be *more* useful isn't a bad feature request. There's no need for it to be 2-squares long since it doesn't really need a console, the sprite can be compressed to normal size. It could have other perks like clean off the contents.

**Comment by Kitfox88** [comment]
Having it be something like the exosuit sterilizers but for people could be neat. Burns anything on you off, heats you up to a little above normal temperatures, gives you a sweet tan.

**Comment by ghost** [comment]
@Kammerjunk I have never had a patient need more shaking after using the sleeper to wake them up.

Cryo also regulates temperature even better than the Mancrowave and oh gee guess which two machines are within 4 tiles of eachother

**Comment by Orangerush** [comment]
The plasmamen coalition is most displeased

**Comment by WhiteHusky** [comment]
The Mancrowave has very limited uses. So far it's being used to heat people back up from Cyro and wake them up without vigorously shaking them.

Personally I've found them useful to chuck people into from surgery to quickly wake them up while I head off to remove someone's appendix or remove their foot from their ass because they looked at someone wrong.

And situations where people are exposed to space, so they get frosty, don't ever need the treatment since the body will return back to normal temperature without intervention other than the burn and brute damage caused by the exposure to space.

If people had problems getting themselves into a human icicles then the Mancrowave would be useful for those situations. For now it's just to warm people from cyro and force-wake people from whatever kind of malpractice you happened to do on them.

**Comment by Blithering** [comment]
It also has a use when people have been in a hot area and are stuck combusting. I've seen people sitting in a 20 degree room go from 100% to husk because of it. The mancrowave fixes it in a jiffy.

**Comment by Exxion** [comment]
It served much more of a purpose before people decided to make it useless by giving its features to other things because they didn't like the fact it existed

**Comment by nuklearcellphoneg** [comment]
tfw you bait people in with the remove x and it always results in meaningful conversation about changes

**Comment by Orangerush** [comment]
banning you on the server nukclear

**Comment by nuklearcellphoneg** [comment]
> implying adminning for four years hasn't turned me into the ultimate ban evader

**Comment by nuklearcellphoneg** [comment]
I know a thing or two about ban evading. :^)

**Comment by clusterfack** [comment]
>It served much more of a purpose before people decided to make it useless by giving its features to other things because they didn't like the fact it existed


The purpose it had was artificial in the first place, cryo already was stabilizing your temperature before it was introduced

**Comment by Kurfursten** [comment]
Someone didn't play medbay back in the good old days where you'd put coffee in the cryo mix to make shakey wakey go faster

**Comment by nuklearcellphoneg** [comment]
But the coffee would mix with the milk and make latte. :(

**Comment by Kurfursten** [comment]
Latte actually is better than coffee, it instantly sets sleeping = 0 in addition to the normal coffee benefit of lowering sleepy by 2 per tick

**Comment by ghost** [comment]
>The purpose it had was artificial in the first place, cryo already was stabilizing your temperature before it was introduced

Objectively a fact

**Comment by nuklearcellphoneg** [comment]
But then there would be no milk in the mix

**Comment by Aurx** [comment]
So you add more milk than coffee.  
Learn2chem

**Comment by nuklearcellphoneg** [comment]
But then there would be no coffee :(

300u stasis beakers when?

**Comment by Intigracy** [comment]
But then they mix in their stomachs

**Comment by Kurfursten** [comment]
Latte has the same effects as coffee

If you want to stack -sleepy you can include several kinds of coffee like espresso, soy latte, cafe latte, etc.

**Comment by nuklearcellphoneg** [comment]
What if we replace the mancrowave with an espresso machine?

**Comment by strawberrytan** [comment]
Make the advanced 1 tile mancrowave tube you can upgrade to darken skin tone by 5 each use until you're a black void and call it a day

**Comment by ihadtoregisterforthis** [comment]
>cryo already was stabilizing your temperature before it was introduced

But it wasn't, it's just that body temperature didn't matter before hypothermia
![2014 12 11](https://user-images.githubusercontent.com/13305885/30522761-ea16a5e2-9bab-11e7-8449-712e47dcd536.png)

**Comment by ghost** [comment]
Let me ask you a question.

If I make the death threshold -25 HP instead of -100, and clones end up coming out dead from the cloner because they start out in crit.

Is it more accurate to say "The cloner was already spitting out dead people before", or "I fucked with the death threshold, maybe I should update this number too"?

**Comment by ghost** [comment]
By the way, that temperature of 12C isn't what the temperature was like inside cryo, it's way colder than that and it used to be set to 12C on ejection. I.e. it stabilized temperature to 12C, a number that was picked because it was safe before hypermemeia.

Just to be clear, this is a factual retelling of how the mancrowave's artificial purpose was created:
1) A long time ago, under the old temperature system, someone makes Cryo eject people at 12C, so that they don't take cold damage after ejection (there was even a comment explaining this)
2) Celt codes hypermemeia, notices hypermemeia fucking kills people after cryo
3) Instead of adjusting the 12C value to keep consistency with the previous behavior, he adds the memecrowave
4) He adjusts the 12C value to something higher anyways to make people not die from it, proving the number was completely arbitrary. He still chooses to keep the value low enough to force the memecromeme despite it being completely unnecessary.

**Comment by nuklearcellphoneg** [comment]
Ice Chili Pepper cryo working when thx

**Comment by Exxion** [comment]
Does it not?

**Comment by icantthinkofanameritenow** [comment]
And to think all this started over a much ballyhooed "snow map" that ultimately proved itself to be the SS13 equivalent of vaporware. 

This is all your fault, snowfaggots.

**Comment by Kurfursten** [comment]
I have something in the works that I believe you will all be very pleased with. Just working on a fresh NanoUI template and it'll be ready to show.
