### ISSUE TITLE
Clipboard Sprite Does Not Update Correctly For Certain Actions

### ISSUE THREAD

**Issue by WhiteHusky** [d3athrow/vgstation13#16011]
#### Description of issue

![](https://puu.sh/xBOwQ.gif)
Clipboard does not change when paper is removed.

#### Difference between expected and actual behavior

Expected the clipboard to be blank, instead it shows that paper still _exists_ in it.

#### Steps to reproduce 

Put paper into the clipboard, and remove.

#### Server revision

61e7b03a5fcf5b307561f48fd4df28c5a5a269e9

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by WhiteHusky** [comment]
![](https://puu.sh/xBOSD.gif)
The clipboard has a few bits of wonkiness.
Pen overlay works fine oddly enough.

**Comment by Kurfursten** [comment]
I actually know about these and have a branch that fixes the first reported bug (removing paper). The stamp bit might be a little more annoying to fix. The upcoming change will also let you easily dump clipboards into filing cabinets.

I'm working on a different cargo thing at the moment though, so that will go to PR first. They're all sort of connected in a general way, but not atomic enough for a single PR.
