### ISSUE TITLE
Cable duplication bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16015]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
61e7b03a5fcf5b307561f48fd4df28c5a5a269e9

# Description

Putting a cable coil and removing it from the microwave will produce a new full length of cable, despite the original cable only having lost one unit of it.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kurfursten** [comment]
Please test this with anything that can be inserted into a microwave and is stackable. Metal rods come to mind, for the kebab recipe.

Another thing to test is objects which can be partially used. For instance, if you take a bite out of an ice cream cone, insert it, then eject it, does it come out as a fresh ice cream cone with no bites missing?

**Comment by SGuivenne** [comment]
Update, I've done some science, the metal rods in the kebab recipe do NOT duplicate and if you put one in only one comes out.  They do register that stacks of rods have multiple rods in them as opposed to just one and only will take one at a time.  

This bug is only with the wires.  Checking ice cream cone thing later.

**Comment by Kurfursten** [comment]
I'm guessing this is related to item pooling

**Comment by nervere** [comment]
This was fixed by Toomy a little while back.
