### ISSUE TITLE
Juggernaut broke

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16019]
(WEB REPORT BY: blithering REMOTE: 172.93.109.202:7777)
# Revision
85c4c3c0dca87e4ebe5c9a7149504b0412361aee

# Description
Got soulstoned and put in a juggernaut, screen went black and never changed, was able to see some chat (announcements and cult chat) but unable to speak, relog did not fix, but on ghosting was able to observe normally, as also unable to locate my previous body, so unsure if it ever existed
# Steps to Reproduce
be turned into a construct during extreme lag maybe?
# What you Expected
jugg smash
# What Actually Happened
jugg have existential crisis

**Comment by Blithering** [comment]
Just confirmed with the person who made me into a jugg, no juggernaut spawned, but the soulstone disappeared. It may have nullspaced me

**Comment by DeityLink** [comment]
sounds like a runtime occured. if we had the exact hour it occured we could check the logs.

**Comment by DeityLink** [comment]
http://game.ss13.moe/logs/2017/09-September/18-Monday.log
[13:24:24]SAY: Shade of Lenny Webb/blithering (@239,231,1) : I detest slimes now
[13:25:11]ACCESS: Logout: *no key*/(Shade of Lenny Webb) (Mech Bay - 284,232,1)
[13:25:11]ACCESS: Login: blithering/(Juggernaut (620)) from [NOPE] || BYOND v511
[13:25:34]SAY: Juggernaut (620)/blithering (@0,0,0) As Cult : Am I meant to be blind?
so I got the time

http://game.ss13.moe/logs/Dev/runtime/2017-09-18-runtime.log
however the closest runtime was
[13:25:49] Runtime in screen_objects.dm,225: Cannot execute null.Click().
  proc name: Click (/obj/abstract/screen/clicker/Click)
  usr: The Juggernaut (620) (blithering) (/mob/living/simple_animal/construct/armoured)
  usr.loc: (nullspace)
  src:  (/obj/abstract/screen/clicker)
  src.loc: null
  call stack:
   (/obj/abstract/screen/clicker): Click(null, "mapwindow.map", "icon-x=24;icon-y=31;left=1;scr...")

which confirms you were in nullspace, however that wasn't caused by a runtime, which is worrying actually, since we can't pinpoint what caused the nullspace-ing.

**Comment by Blithering** [comment]
I think someone said they were able to replicate it by spamming hitting a soul shard on an empty shell with an autoclicker
