### ISSUE TITLE
Bee Loyalty Cascades Trigger Too Easily

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#16047]
If a bunch of undisturbed bees in a vault can end up genociding themselves, they're a waste of cycles.

![untitled](https://user-images.githubusercontent.com/9782036/30725220-aeb0ff56-9f08-11e7-88f0-a3e3588d8700.png)

Of course perhaps the best known case is "vending machine throw wire event, prepare to have all your bee hives ruined"

Hives need some kind of forgiveness mechanism, so if they fall below a certain bee count they surrender and focus on rebuilding instead of fighting until extinction.

**Comment by Hugh-G-Rection** [comment]
So long as we're making a buzz about this issue, I found another _bug_ last night.

Created about 30 amorphous masks with a syndicate mechanic scanner. The very first one I put on turned me into an angry swarm of bees.
"THE BEES SWARM THE BEES!"
I instantly died as my mob killed itself. The disappointment still stings.

Would be really sweet if we fixed self hating bees.

**Comment by Zth--** [comment]
We can either remove the feature of bees attacking other bees or improve the equation.
> 		//Bees will only attack other bees if they're crazy from high toxicity.
> 		if (istype(G,/mob/living/simple_animal/bee) && (((current_poison_damage - bees.len)/bees.len*100) > 51))
> 			var/mob/living/simple_animal/bee/B = G
> 			//even then, they won't attack bees from their own hives.
> 			if (B.home == home || (home && B.home && B.home.wild && home.wild))
> 				continue

**Comment by Shadowmech88** [comment]
>the feature of bees attacking other bees

Are they supposed to even attack bees that are a part of the same swarm?
I don't feel like a single swarm of bees should be capable of killing itself with stings.

**Comment by Hugh-G-Rection** [comment]
Just want to post an update in hope this issue gets some attention and tweaking.

The "Wont attack bees from their own hives" doesn't seem accurate. Been placing a single hive with a single queen, just to keep my plants happy and healthy, and the bees still wind up furious without provocation.

The bee minigun is also now much less useful, because instead of making a cloud of angry bees for someone to stumble upon, they just kill themselves. Same goes for the briefcase of bees, whoever opens it will be stung, but once they move off screen the bees will inevitably turn on themselves.


If I'm being honest I don't completely see the point of bees attacking bees. If it's to keep the population down, I've proven that you can overcome it with a little effort and get collect 7000+ for release.  The only thing that the "feature" is really doing is preventing more inventive uses of bees. I would love to leave a cloud or two of cyanide bees in maintenance as a trap like a vampire's bats, or just release them in the hall as a deadly flood, but as it stands both of these result in a pile of dead useless bees. At the very least, can we add the feature that a thrown bee-net will release the bees on impact, so we can throw angry clouds of bees at people?

Like the majority of botany they take so much time and effort that I rarely see anyone utilizing them for anything, so I really don't see the harm in making them a little stronger as a whole. I know Deity worked really hard on this, to the point of burnout, but I hope we can still find a perfect balance so they can be more functional.

**Comment by DeityLink** [comment]
Something's wrong, angry bees from wild hives shouldn't ever attack each others

**Comment by Kurfursten** [comment]
Pretty sure(?) Deity fixed this when he recently reworked bees again

**Comment by DeityLink** [comment]
It got fixed a while ago when someone completely commented out bees getting angry at other bees.
I have no plans to re-add it in the short term.
