### ISSUE TITLE
Construction datums emit an admin warning on completion

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#16196]
#### Description of issue
I'm trying to wrap my head around these, and I get admin warnings when I complete a construction process.

#### Steps to reproduce 
- Build APC frame
- Insert rods
- Insert wires
- Screwdriver
- Get admin warning

#### Specific information for locating
`[04:37:55]ADMINWARN: <span class="admin"><span class="prefix">ADMIN LOG:</span> <span class="message">Holy shit /datum/construction/reversible/crank_charger/(/datum/construction/reversible/crank_charger) is trying to set its new index to 0! how the fuck did this happen? I don't know, our direction is forward old index was 1. User is <A HREF='?_src_=holder;adminplayeropts=[0x3000056]'>damianq</A>, itemused the screwdriver, step /list</span></span>`

#### Length of time in which bug has been known to occur
No clue

#### Server revision

6bdd9c11b81fcf6e805ac9d08f573f8442300f93

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kammerjunk** [comment]
I've read over the reversible code a few days ago and I'm not sure this error is even supposed to exist. It appears when the length of steps left to construct it eventually reaches one, which is why it only happens when you finish constructing it. `diff` is FORWARD (-1) so `new_index` is set to `index - 1` and since index is the length of the steps list, that's going to be 1 - 1 = 0 at the last step.
I can't think of why this message should happen.

To dump what I saw without putting any actual effort into writing it again:
![image](https://user-images.githubusercontent.com/5942183/37584878-6a94475c-2b57-11e8-9a14-f22144d048a1.png)
![image](https://user-images.githubusercontent.com/5942183/37584890-722eaae8-2b57-11e8-8784-b0b314f64cde.png)
![image](https://user-images.githubusercontent.com/5942183/37584901-7b4b7912-2b57-11e8-879e-c6c64899833e.png)
![image](https://user-images.githubusercontent.com/5942183/37584916-87681b38-2b57-11e8-8972-ff77341658cd.png)
![image](https://user-images.githubusercontent.com/5942183/37584944-9815eb54-2b57-11e8-97af-d71a53843f4b.png)
![image](https://user-images.githubusercontent.com/5942183/37584953-a232ee16-2b57-11e8-88cd-0553a065e279.png)

**Comment by Kurfursten** [comment]
@Exxion This was fixed very recently

**Comment by Exxion** [comment]
#19623
