### ISSUE TITLE
shortening the launch while the escape shuttle is flying to centcom will make it arrive faster

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#16221]
#### Description of issue
If you use the shuttle console computer to shorten the launch (either with head Ids or an emag) after the shuttle has left, it will move sanic fast to centcom.

#### Difference between expected and actual behavior
shuttle ride takes 2 minutes
shuttle ride takes 10 seconds

#### Steps to reproduce 
emag or head ID shuttle computer after it departs from station

#### Length of time in which bug has been known to occur
it's probably been around for a while, funny that no one noticed this

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] It just happened last round and I assume it could happen again

**Comment by DrSnips** [comment]
Pretty sure it was an emag that did it and it was in the 10 seconds after the first shortening with head ids

**Comment by DrSnips** [comment]
shorten with head id, 10 seconds to launch, emag, super short shuttle

**Comment by Kitfox88** [comment]
emag obviously optimizing inferior nt tech for maximum efficiency

**Comment by Cyadox** [comment]
So this  *is* possible, I've seen it happen, but local testing has proven fruitless.

- Shortened the shuttle time to 10 seconds with 3 auths, then emagged during the 10 seconds. No change
- Shortened the shuttle time to 10 seconds with 3 auths, launched normally, then emagged. No change, though you can emag it indefinitely with no results
- Shortened shuttle time to 10 seconds with emag, then 3 auths during the 10 seconds. No change.
- Shortened shuttle time to 10 seconds with emag, waited for launch but you can't use auths after the shuttle launch.

The only way I can see this working is if you use the very small window between the timer hitting 0 and the shuttle launching to emag the shuttle. You *cannot* keep the emag prompt open if you use the 3 auths first, because it uses the same proc as the auths to confirm your action, ie you can only do one or the other at one time, not both.
However, you can keep the emag prompt open *after* the 3 auths, but again it does nothing after the shuttle launches.
