### ISSUE TITLE
Importing Assembly frame builds voice analyzers are wrong

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16260]
(WEB REPORT BY: spoonylove REMOTE: 172.93.109.202:7777)
# Revision
a50a28e8f054bda8755c8d2deeabdd0084515b14

# Description
importing plans from an assembly frame to a new one, the activation phrase or code word will be wrong on import. built a frame in a previous round imported it all the voice analyzers seem to be wrong. 
# Steps to Reproduce
https://pastebin.com/P12wusne

here is a paste of my shitty assembly frame for baby AI, I've listed the parts needed at bottom. 
# What you Expected
A simple copy and pasting the text SHOULD just remake the assembly frame. 

# What Actually Happened
all the voice analyzers are wrong and have to be redone every time you rebuild

**Comment by Exxion** [comment]
Looks like the entry in `accessible_values` for the activation message of voice analyzers is erroneously typed to `VT_NUMBER` rather than `VT_TEXT`
Non-fatal errors such as incorrect type just fail silently in assembly frame importing because `write_to_value()` doesn't return anything specifying whether it succeeded or not and apparently I decided not to change that at the time

**Comment by spoonylove** [comment]
it would be nice to be able to change the password/phrase within the assembly frame as well as be able to check what the word/phrase is. It looks like voice analyzers are the only thing that can't be modified in an assembly frame.

**Comment by Exxion** [comment]
For some reason, voice analyzers are coded specifically to not allow the message to be changed while they are part of another assembly
Also an easy "fix", but there might be a reason they're set up that way
