### ISSUE TITLE
Cannot hack with Clarke multitool.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16348]
(WEB REPORT BY: libertino REMOTE: 172.93.109.202:7777)
The clarkes multitool does not work.
# Revision
f36295aecd8ee8d77cb9f5aa13ab7822126614a9

# Description
I tried to hack doors using the multitool from an exosuit mounted engineering switchtool, it would not open the hacking window.
# Steps to Reproduce
Use screwdriver on a door using a clarke with an exosuit mounted engineering switchtool and then try to hack it using the multitool.
# What you Expected
I expected it to work as intended, like any normal switchtool attached multitool.
# What Actually Happened
It did not open the hacking window.

**Comment by PJB3005** [comment]
It should be noted this guy was a posibrain in a mech.

**Comment by Exxion** [comment]
It doesn't matter. It won't work no matter what.

**Comment by PJB3005** [comment]
Considering MMI mech code is horrible it wouldn't have surprised me if it was MMI-specific.

**Comment by Jubisloviu** [comment]
to add to that, i managed to open the hacking menu from doors with the clarke, but couldn't pulse or cut wires with it

**Comment by Exxion** [comment]
Yeah sorry I would have elaborated but I thought the cause was common knowledge
Since hacking is done through `Topic()` rather than attacking, it specifically checks for either a multitool/wirecutters in the user's active hand, or a switchtool with one of those selected
There's no contingency coded in for hacking through a mech

I bet you could hack with the Clarke if you're holding a multitool in your active hand when you try though
