### ISSUE TITLE
Bagelstation: solar panels SMES start with full charge

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#16357]
The result is that engineering doesn't need to setup power for a solid hour and a half.

**Comment by Probe1** [comment]
After investigating it pretty thoroughly here are the results.

1.  The solars are fine.
2.  There are 5 SMES in Engineering opposed to the 3 on other stations.
3.  Those 5 SMES are all set to have 1,000,000 charge instead of the 0 other stations have.

This results in power clinging on for 30~ minutes.  I haven't played Bagel so I can't really make the call here but the obvious answer is to remove that hefty 5 million charge that Bagel gets opposed to every other map that has 0 extra charge.
