### ISSUE TITLE
Zombie Powder paralysis lasts forever if forcibly removed.

### ISSUE THREAD

**Issue by Sooose** [d3athrow/vgstation13#16360]
If you remove zombie powder through water + potass or charcoal, the effects of zombie powder will never run out. This leads to a permanent paralysis unless you feed them more zombie powder and let it run its course naturally.

**Comment by SonixApache** [comment]
Defibbing / face-slapping / mancrowaving / sleeper-cycling doesn't work?

**Comment by Dacendeth** [comment]
As a victim of this months ago no normal medbay thing would wake me up. I had to be killcloned.

**Comment by ghost** [comment]
I hate to backseat moderate but this is kinda exploitable

**Comment by Exxion** [comment]
That it is

**Comment by Sooose** [comment]
Face-slapping/mancrowaving/sleeper-cycling doesn't work, didn't try defibbing.

**Comment by Aurx** [comment]
Defibbing wouldn't work.  
Cause of this is that zombie powder sets the fakedeath flag when applied, then removes it in its on_mob_life() or on_removal().  But water+potass just uses clear_reagents() which bypasses on_removal() and since there's no longer zombie powder in their system zombiepowder/on_mob_life() won't be called.  
So the fakedeath flag sticks until they get zombie powdered again and it leaves their system properly, which is likely to be never.

**Comment by DamianX** [comment]
Should `clear_reagents` make it so `on_removal` gets called?

**Comment by Aurx** [comment]
clear_reagents iterates over all reagents and calls del_reagent on them.  
Making del_reagent invoke on_removal would fix this.  

But there's only two reagents (in reagents.dm at least) that have special code for on_removal.  
Blood uses it to refuse to be removed under some circumstances.  Zombie powder uses it to unset the fakedeath flag.  

Anything that fixes the latter runs the risk of having trouble with the latter.

**Comment by Exxion** [comment]
Just make `del_reagent()` call `on_removal()` but ignore its return value

Also
>Anything that fixes the latter runs the risk of having trouble with the latter.

**Comment by Aurx** [comment]
Replace the latter of those latters with former.
