### ISSUE TITLE
Wizard Lightning spell does zero damage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16531]
(WEB REPORT BY: jameswbigmac REMOTE: 172.93.109.202:7777)
# Revision
ac89c6110cc221e214a54ded92ad5e2b0aa723d2

# Description
The Lightning spell does zero damage
# Steps to Reproduce
Select the lightning spell and use it
# What you Expected
The spell to do damage

# What Actually Happened
The spell did not do damage

**Comment by gbasood** [comment]
I'd be very surprised if this were actually the case

**Comment by DamianX** [comment]
#15914
There's quite a few issues about lightning in particular, there must be something wrong.

**Comment by Chazach** [comment]
I tried in the test serb, lightning did absolutely nothing to a naked monkeyman

**Comment by gbasood** [comment]
Weird, since the code hasn't changed to my knowledge
Someone's gonna have to throw some debug output in and find where it's failing
The issue @DamianX linked seems like it might be more nuanced than this one, though

**Comment by SonixApache** [comment]
Doesn't it cause heart damage?

**Comment by AutismSpider** [comment]
you mean burn damage and emp when upgraded

**Comment by EenKogNeeto** [comment]
I believe this could _maybe_ be something to do with the glow orbs? You can activate them with lightning and then they do things, but otherwise, lightning does nothing but sound cool and scuff the floors. This is repeatable, anyone can recreate this bug by taking lightning on test or live server and shooting anyone or anything bar said glow orbs which are the only thing it seems to interact with.
