### ISSUE TITLE
Bring back space holodeck sim

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16558]
-One of the simulations for holodeck used to be a space simulation (looked like space but wasn't actually space)
-Since the holodeck became larger, that one was removed
-Should be generally easy to bring back

**Comment by Killette2** [comment]
![image](https://user-images.githubusercontent.com/5169310/32698759-a5e77df8-c778-11e7-9764-5aebe2bd4bc4.png)
Picture containing it

**Comment by MadmanMartian** [comment]
Should be a doddle

**Comment by Exxion** [comment]
>looked like space

Barely
No parallax, obviously, and it only used two of the space tile sprites, so it was a pretty poor attempt even before

**Comment by Shadowmech88** [comment]
If it's brought back, the floor could just do what glass floors do to show space underneath them.

**Comment by Exxion** [comment]
It's not that simple
But it's also not *that* much less simple

**Comment by Lokiamis** [comment]
I was too dumb to get the parallax working. Looked terrible without it.

**Comment by Exxion** [comment]
You should give it the regular space sprites and put it on `PLANE_SPACE` or whatever it's called
The one that space is on
But to do it properly, you should *also* make a `turf/simulated/parallax` and re-type glass floors to be a child of it and make the parallax performance check check for that rather than just glass floors
Obviously the holo-space would also be a child of the parallax turf

**Comment by Killette2** [comment]
People use paralag?

**Comment by PJB3005** [comment]
Not everybody has a potato as computer.
