### ISSUE TITLE
pAI mulebot sprite doesn't stick

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16568]
#### Description of issue
The alternate mulebot icon for when they have a pAI plugged in will very easily revert to the normal mulebot sprite after doing pretty much anything: like opening and closing its maintenance panel or having it pick up and drop objects.

#### Difference between expected and actual behavior
Expected the alternate sprite to stay until the pAI was ejected.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by EenKogNeeto** [comment]
Since this is already here, The person riding it's sprite only updates if they get off and back on aswell. meaning they could have anything equipped (TTVs?) and nobody would know.
And even less important, if you put someone on a rollerbed the load the rollerbed all it shows is the 'extended' rollerbed sprite, not the person on top.

**Comment by Pathid** [comment]
I was planning on making another issue for that one, yeah. Rollerchairs make the rider invisible too.
Also related: #15712
