### ISSUE TITLE
Natural regeneration does not work at certain health levels.

### ISSUE THREAD

**Issue by Sooose** [d3athrow/vgstation13#16573]
#### Description of issue
Grab a toolbox or a lit welder and hit someone a few times, they will not regenerate. Now punch them once and watch as the regeneration kicks in. This is because regeneration only works if the damage is not divisible by 15.

#### Difference between expected and actual behavior
Expected your body to not decide its going to regenerate you to full health because you got poked once.

#### Steps to reproduce 
Modify a weapon's force to a multiple of 15, hit target and watch as they don't regenerate.

**Comment by Dacendeth** [comment]
To reiterate it's possible to regen from something like 89 burn damage, as long you regen past the 15.0, 30.0, 45.0, etc mark in some way. This happens sometimes as regen seems to make you go from an integer to a number with some extra decimals. ex 75.199 ticking past 75 to 74.999 and so on all the way back to 0.

**Comment by Blithering** [comment]
So 6 1u tricord pills should be fine to get you from 1 to 100 if taken at the appropriate thresholds? Assuming brute or burn damage only

**Comment by Dacendeth** [comment]
Yeah, it would take a while but that would work.

**Comment by EdXbtkOEwGw** [comment]
Natural regeneration works in a wound-by-wound basis, so you may have a 60 brute wound and a 10 brute wound at the same time, caused by different effects (60 brute by toolbox, 10 brute by punch). Wounds also have a limit to how big they can be before they don't autoregen. So the 10 brute wound will regen, but the 60 will not, which leaves you at a round 60.

I couldn't reproduce any way of re-enabling autoheal through punching. I tried a welder and toolbox. In both cases the punch regenerated, but the rest of the damage didn't, as expected.

**Comment by SonixApache** [comment]
mystery solved

**Comment by Sooose** [comment]
Proven wrong, issue closed.

@EdXbtkOEwGw  You're definitely right on the punch regen not working. However I noticed the thresholds still seems to be wonky, a toolbox of 15 brute won't regenerate unless the victim starts bleeding from it, however a syndi toolboxing will cause regeneration with or without the bleeding at 20 brute. Both of these should be single wounds, right?

**Comment by Exxion** [comment]
I still have flashbacks about last time I had to look at woundcode
It's very possible there's a bug *somewhere* in there
