### ISSUE TITLE
Cyborg stations make module slots lock up

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16735]
#### Description of issue
A very recent change made it so that if cyborgs have modules equipped when charging it prevents them from being clicked after leaving the charger. However, the swap-hand hotkey still works and is a workaround for the problem.

#### Length of time in which bug has been known to occur
Started happening today, Dec. 9th.

#### Server revision
Game: 23b20ae8ccf3e904f0535f2452c4e02685801757 
Patches: 6b998d358c4c884692233ecb12edde774b2f220c 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
@DamianX I think the mouse opacity thing might've caused this.

**Comment by DamianX** [comment]
fuck

**Comment by SGuivenne** [comment]
How the hell does that code bit even effect this bug, I'm not quite sure what interaction the two would even have?

**Comment by DamianX** [comment]
Basically `fix_modules()` sets mouse_opacity to 2 for all modules, this means that you can click the whole area around the object to select it, not just the object itself. This is good if the module is stored, but if it's equipped it ends up covering the slot's UI icon, which is what you HAVE TO click in order to select a slot.
I wanted to change that behavior in #16740, to allow clicking on the equipped object itself, but I hate it and can't be bothered to finish it.

**Comment by Exxion** [comment]
just make it set mouse_opacity to 0 when equipped lol

In seriousness, there's probably something you can do to make that easy, be it mouse_opaque overlays, or a `PLANE_MASTER`, or something
