### ISSUE TITLE
[Salt] Is dimensional push too strong ?

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#16813]
Related : #15325

This issue is to get feedback on dimensional push before making a PR ~nerfing~ adjusting it.

Dimensional push, is among with Doppelganger and ICASTFIST, probably one of the strongest assets in a wizard toolbox.

Here is a few issues I see with it : 

- It can literally bring all departments to an halt with no hopes of recovery in a few seconds. Dimensional push the door, steal the essential assets, and blink away.
- It requires no robes, which means you can do all of this in an atmospheric hardsuit, whilst holding guns.
- It can pushes gas miners.
- It is cheap enough that you can combine it with blink. Normally this wouldn't be an issue - no wizard should have to rely on only one spell - but this makes gas miners fuckery even easier.

Combine the four, you can push away all hardsuits, suit yourself with atmos/CE hardsuit, and then push in a gas miner to plasmaflood the station with very little effort, and unlike most other plasmaflood, very little tools to fight against it, since a gas miner is much harder to suppress than a classic flood.
Note that there is not only one gas miner, but 4, all of them equally deadly.

My suggestions to """fix""" it : 
- Have the cooldown based on the object teleported. The larger the object, the longer the cooldown.
- Make it require robes.
- Make it more expensive.

I think that the first is the best, as it still enable the playstyle some players here seems to like (to each their own), but make it less spamable and requires you to actually think your moves through. If you really want to disable sec, medbay, or steal that sweet gas miner, you'd need to prepare for it as if you failed, or got caught, you'd be vulnerable for a few seconds.

This rewards careful planing and execution, and punishes sloppiness or relying too much on your antag advantage. In my opinion, it fit relatively well in spessmen.
Tell me what you think via comments or emojis.

**Comment by AutismSpider** [comment]
Dimensional push not work on bolted down items/airlocks/gas miners unless you buy power upgrade.

Make icastfist  LOS base means they have to buy the orb for ghost fisting past walls etc.

Doppelganger needs to be taken out or hard cap on how many clones you can make or the wizard takes % of the damage the clones take.

**Comment by Pathid** [comment]
Problem with clones is when upgraded they get a super fast moving variant of magic missile that wizards themselves don't have access to.

**Comment by DamianX** [comment]
- Make Dimensional Push respect the same blacklist as Bound Object
- Remove doppelganger
- Remove fist

**Comment by Killette2** [comment]
Clones require a decent amount of points invested into to be bullshit. With the same amount of points you could do bullshit yourself to an even greater level with multiple other spell combos already.

Nerf clones firing rate of magic missile if you really want. That's the only issue they have since the cooldown is 30 - 10 per upgrade.

**Comment by SonixApache** [comment]
robes is a good idea

**Comment by Killette2** [comment]
I'd be fine with push requiring robes but bound object requiring robes would be too far

**Comment by Hugh-G-Rection** [comment]
You could also just leave it the way it is and deal with it like men instead of whining babies. Sometimes rounds are shit. It's a mixed bag, that's how it's supposed to be. Am I supporting plasmaflood? Of course not. Being a lazy, shit, boring flooding/murderboning antag should have your antag roll removed for a week. But removing things that non-shitters with an imagination can use for actually entertaining purposes is the wrong way to make a game better.

It's impossible to have a game that has limitless potential and possibilities for fun and excitement without also containing tools that can also be exploited by assholes and shitters. By it's nature SS13 is impossible to be balanced, and it's sad how many things get removed for the sake of attempting the impossible because people just get bootyblasted. People complain constantly about boring shitty antags using things to extremes for murder and grief, but we refuse to recognize the actual problem is the number of unchecked assholes doing what they want because our headmin says "Antags can do whatever they want."  Obviously they can't, because it's how :fun: features get removed, and removals and nerfs hurt the game dynamic as a whole.
But that's just like, my opinion man. And it's probably hypocritical to other things I've said, and I'm sure it's not popular or even intelligent, so :clown_face:

**Comment by FudgePucker** [comment]
Blacklist gas miners.
If you want to abuse the miners you should have to get it out of there by hand. The pressure is so high the atmos hardsuit doesn't even provide full protection.

**Comment by Blithering** [comment]
@killette2 the investment requirement of clones is not that great, considering the spell is half the cost of others. I think the clones need a significant health decrease, both for balance and to make the on death fake teleport believable.
