### ISSUE TITLE
Fedora tipping is too powerful

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16869]
1. Take fedora, wear it
2. set up your autoclicker to click every 0.01 second
3. use the fedora tip action on the top left to flood chat

**Comment by MadmanMartian** [comment]
We need a universal cooldown handler.

**Comment by DamianX** [comment]
`delayNextSpecial` is a thing, but one would have to use it

**Comment by PJB3005** [comment]
@MadmanMartian I recently *removed* a universal cooldown handler. Universal cooldowns are *not* the solution.

**Comment by Killette2** [comment]
Why aren't they?

**Comment by PJB3005** [comment]
Because a generic cooldown *always* affects too much things, 100% of the time, so now you're ignoring valid input for a lot of things. This makes the game feel like *shit* to play.

You know how if you were wrenching pipes and you accidentally click an already placed one, you have to wait a bit before you're able to continue wrenching pipes? I removed that with #16404 and it's probably one of the best QoL improvements ever.

IMO we should either handle specific cases, or just tell admins to bwoink obnoxious assholes. That or have people be allowed to apply a good toolbox if necessary.

**Comment by SGuivenne** [comment]
>IMO we should either handle specific cases, or just tell admins to bwoink obnoxious assholes. That or have people be allowed to apply a good toolbox if necessary.


What PJB said.  If people are exploiting autoclickers to spam (or using autoclickers period imo), they should be bwoinked for it.  This isn't a grey area, spamming shit for the purpose of spamming shit and/or causing latency is against the server rules.

**Comment by DamianX** [comment]
Admins generally don't care, I and others have ahelped this one guy that loved to spam flashing ID or shuffling cards, nothing ever came of it. I fixed that in #16621.

**Comment by Kurfursten** [comment]
@Exxion This basically is no longer an issue as of new chat prefs

**Comment by Killette2** [comment]
unless you alternate between tipping your fedora and flashing your ID
