### ISSUE TITLE
Something Needs To Change: Box Perma or Crawling

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#16925]
Found this in the thread. Tagging @hugh-g-rection and @MadmanMartian for obvious reasons.

![1514526638727](https://user-images.githubusercontent.com/9782036/34433353-5e44391e-ec44-11e7-9ce2-0a049dbf2f39.gif)

Now I personally don't have a dog in the fight of which one we change but this isn't acceptable.

**Comment by MadmanMartian** [comment]
Looking at previous map iterations, those plastic flaps used to be two-long doors, like in the salvage shuttle. They were replaced as it was tedious for pods to actually get out of the pod bay.

Regardless, I'm getting pretty tired of these damn plastic flaps. Should I change it so that if the plastic flap is 'airtight', you can't crawl under it?

**Comment by SkowronX** [comment]
Remove crawling

**Comment by Hugh-G-Rection** [comment]
Please do not change airtight flaps to not allow people through them. They're one of my favorite things for advanced gimmicks, such as lubing people into space or a mass driver ride into a banana peel under flaps into the shard.

Just change crawling. Alternatively, make crawling only an option for people who HAVE to use it, as in those missing legs. Because that IS why it was added in the first place, right? Surely it wasn't just added for the memes, right??

**Comment by DrSnips** [comment]
At what point do you just accept that crawling isn't a good feature and that it should just be removed rather than just continuously applying bandaids.

**Comment by jknpj** [comment]
How else am i supposed to use the research outpost without using its conveyors + flaps.

But yeah it might just be better to change crawling so you can't crawl under flaps because besides this issue greyshits are using it to break into everywhere (using the MULEbot docking area) and i find this whole situation worse than fucking tableclimbing.

**Comment by EdXbtkOEwGw** [comment]
Just make it so that you can't crawl under flaps
Lube and conveyors are a greater commitment

Alternatively, remove crawling
