### ISSUE TITLE
Spiky skin effect is now super lethal

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#17073]
Trying to pull somebody with the `spiky_skin` virus effect, known as Porokeratosis Acanthus in-game, crits you very fast now, even while wearing armor. Guessing this is related to #17044.

**Comment by DeityLink** [comment]
![spkiy](https://user-images.githubusercontent.com/7573912/62371231-94bf4280-b534-11e9-8738-77bdddfb83fa.gif)

Bumped into him 16 times in the span of 2 seconds with max strength. So that means it can be done in 4 seconds with regular strength.

It doesn't proc when pulling someone with the symptom however.

I could halve the default/max strengths so it's less deadly.
Or have it at least take armor into account because WHAT THE FUCK:
![spkiy2](https://user-images.githubusercontent.com/7573912/62371395-10b98a80-b535-11e9-8c19-0066df9b1566.gif)
