### ISSUE TITLE
In the future, more strictly follow the repo guidelines.

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#17169]
PJB and N3X purposefully stirred up as much shit as possible, self-merged several times, shut down discussion, and seemed to want nothing but to make things on here unpleasant.

The rules and guidelines are here for a reason. Flaunting your ability to step around them is annoying. You didn't allow for proper vetting or discussion of a _feature removal_, and proceeded to get Pomf to let you merge a _feature change_. None of this happened with input of other coders or players.

Discussion on Discord _should not count_. It's far from transparent and avoids the fact that people who actively play the game and play with the thing being changed should at least have _input_ and _knowledge_, even if ultimately a coder makes the decision. **A collab making the decision isn't the problem, it's the fact that there's no time to properly come to one on big changes.**

But I digress. I don't need to explain this. You already know.

You, @N3X15 and @PJB3005 already know it's wrong to do this, but you don't really care. You have no oversight and feel as if it's alright to just stir up shit and flaunt your power around, despite what negative effects it might have to the health of the codebase. You didn't even address complaints that the code in the original PR which "fixed the bug" was snowflakey and shit.

Your code was broken and flawed, which you would have known if you hadn't rushed it. But you did rush it, because you don't care about the players, codebase, or even how you're perceived.

Please. In the future. More strictly follow the repo guidelines. Else, honestly, there are much better people who could be collab.

![annoying](https://user-images.githubusercontent.com/6062247/35189989-dc341d48-fe0b-11e7-93ab-d489cdf7f9dd.jpg)

![truthfulyes](https://user-images.githubusercontent.com/6062247/35190016-69ef17f0-fe0c-11e7-8356-f0496109a988.png)

**Comment by kilozombie** [comment]
Also:

1. There is no discord conspiracy to tear you down, N3X. You're just being a retard and my similarly retarded brain cannot help but talk about it.
2. Stop retracting to your safe space when you're scared of criticism. Grow up. Both of you.

**Comment by ghost** [comment]
why the fuck would there be a discord to tear nexis down? you don't need one; he's gonna quit anyway

**Comment by kilozombie** [comment]
Related PRs in chronological order:
https://github.com/vgstation-coders/vgstation13/pull/17151
https://github.com/vgstation-coders/vgstation13/pull/17154
https://github.com/vgstation-coders/vgstation13/pull/17158
https://github.com/vgstation-coders/vgstation13/pull/17160

**Comment by PJB3005** [comment]
I find it amazing that you took the "this is more fun" bait so literally.

**Comment by kilozombie** [comment]
Provide a counter-argument. You don't seem to have a reason for doing all of this except to stir up controversy.

**Comment by TheFriggenSawbones** [comment]
@PJB3005 perhaps you shouldn't be doing shit to "bait" the community.

**Comment by ghost** [comment]
Yeah, you hit the nail on the head


Mirroring:
PJB's response to inital nex's pr - "Shitstorm in 3... 2... 1..."
PJB's statement when he deliberately pulled all this shit instead of following the rules he holds flags to enforce -"Yeah but this was more fun."

I ask him - "So @PJB3005 , how about this, instead of merging it in two hours, ya leave something that has gotten along fine for years and get some feedback on your proposed improvement. Ya find out, unbeknownst to you two who no longer play, your improvement creates an issue. Questions are asked to further identify what it is, why anyone should care, and what can be done about it. Debate is had, proposals forwarded and scrutinized, it's resolved and moves forward because gee willickers it's a trivial step down from explosion cheesing and all the problems that come from removing explosion clearing are dealt with. No drama spike from not following the rules for the xth time while @d3athrow is mia and not holding you accountable. No irritation over an underaged child who not only fails to grasp his attitude problem but values it. Y'know, the way things are supposed to be done, the path reached after countless generations of collaborative decision-making. The way you hold others to with your flags you hold partially for this purpose but apparently neither yourself nor nexis.

Wouldn't that just be crazy???"

PJB3005-"Hey if you want me to tell N3X to merge it that's fine too."
PJB3005-I find it amazing that you took the "this is more fun" bait so literally.

Github isn't the place for this and neither is a collaborator/member(?) PJB's behavior acceptable in light of their flags and responsibilities. It needs to stop, @d3athrow It's a clear pattern going back years, and it's just going to keep causing problems.

**Comment by groosbstrd** [comment]
@PJB3005 instead of fucking with a server you no longer care about, how about you work on your dying ss14 project eh?

**Comment by PJB3005** [comment]
How creative of you to say that.

**Comment by Chazach** [comment]
jealous of bauds genetics speedrun, #17160 was selfmerged in 1 minute and bauds reduced to contributor
bravo

**Comment by TheFriggenSawbones** [comment]
for prosperity 





![](https://cdn.discordapp.com/attachments/240891374277361664/404469157275500545/Discord_2018-01-20_18-54-38.png)

**Comment by Kurfursten** [comment]
If anyone should be above the rules it should be me

I wouldn't self merge anything but I would create a lot of one line ifs

**Comment by SysadminJeroen** [comment]
U AR JUS LAZY AND DUMB COLABORATORS!!!

**Comment by gbasood** [comment]
Alright
Fuck this drama
@d3athrow will figure out what he wants to do when he wants to
I'm gonna lock this until then because otherwise it will turn into shit flinging
I'm not trying to prevent discussion of all this but until people cool down a bit this issue isn't helpful.
