### ISSUE TITLE
Antags can be deconverted but still show up as antag on traitor panel [OH GOD IT'S LOOSE]

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#17338]
my apologies to the antag datum boys

occurred here:
http://ss13.moe/forum/viewtopic.php?f=34&t=3773&start=60

**Comment by Aurx** [comment]
Since Celt is clearly unable to write at a third grade level, I'll do it for him.  
@PublicEnemyMaiPai, please verify that this is correct, particularly that I have correctly identify the antag-checking methods you were using when you encountered the issue.  
@DrCelt, post what antag-checking methods you were using when you encountered the issue.  

#### Description of issue
Two cultists were deconverted, but still registered on administrative tools as antagonists.  
Behavior occurred with the quick-info (?) and in the player panel (Believed to be F6 menu version).  

#### Difference between expected and actual behavior
System reported subjects to be antagonists.  They were not antagonists.  System should not have reported they were antagonists.  

#### Steps to reproduce 
Note: Not tested, this is a second-hand report.  
Convert cultist.  Deconvert cultist.  Ahelp their name.  Click the (?).  Open the F6 menu.  Observe ANTAGONIST label.  

#### Specific information for locating
Occurred Feb 4th, round starting 08:00:05.  

#### Length of time in which bug has been known to occur
I am unaware of prior instances of this issue.  

#### Server revision
Whatever it was Feb 4th 08:00:05.  

#### Issue bingo
- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]

**Comment by PublicEnemyMaiPai** [comment]
Yes those are the methods I used to check if the suspected players were antagonists

**Comment by BroseidonMOO** [comment]
The issue was reproduced this morning in testing with BathosBathtime. Issue appears to stem from [cult.dm] /datum/game_mode/proc/remove_cultist which does not set .special_role to null, I have submitted a fix with PR 17342.
