### ISSUE TITLE
Ideas for Antitoxin Overdosing

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#17398]
This has got to be the least controversial thing ever. Especially since #16571

We just need to agree on something. Antitoxin as we have it has no particularly good real life analog, so we don't have much in the way of real life effects.

I suggest these overdose symptoms, using the same time-based overdose mechanic that Chloral uses:
* After 10u, blurred vision until the antitoxin expires
* After 25u, internal bleeding of the kidneys and liver with increasing damage to both

This has the added benefit of bothering to make antitoxin/pepto pills much more attractive, too, for the ambitious chemist.

**Comment by SonixApache** [comment]
Antitox in large quantities starts to neutralize your blood. Every unit that metabolizes past OD just takes a unit of blood along with it.

**Comment by Pathid** [comment]
First, I'm in favor of a antitox nerf. However, Internal bleeding and organ damage at 25u seems a bit aggressive. The pills in the green first aid kits are 25u, you know.
Some possible side-effects that don't necessarily make things a lot harder for medbay:
* blindness
* confusion
* passing out/stuns
* slowdown

That and there's a "WIP" side-effect for anti-tox already in the code. Somebody could stand to ramp that up quite a bit since it's virtually fluff right now.
https://github.com/vgstation-coders/vgstation13/blob/33330b24e396621e46d1ac0b6b96a374395a3650/code/WorkInProgress/Cib/MedicalSideEffects.dm#L34-L35
https://github.com/vgstation-coders/vgstation13/blob/33330b24e396621e46d1ac0b6b96a374395a3650/code/WorkInProgress/Cib/MedicalSideEffects.dm#L103-L125

The effect being incredibly weak aside, the idea of having it cured by inaprov is neat because you need all the antitox gone before inaprov stops turning into tricord.

**Comment by ghost** [comment]
whew every time I'd get that effect I'd take more antitoxin
so THAT'S why it never went away

**Comment by Ephx1** [comment]
> Blurred vision

Is there even an effect in the code for blurred vision? I know there's that wonky welding overlay that I think nearsightedness uses.

**Comment by Kurfursten** [comment]
Yeah, it's that one you're thinking of.

@Pathid I said *after* 25u, not at. For that exact purpose you mentioned!

**Comment by Shadowmech88** [comment]
We have Pepto-Bismol in the game, and it has the same effects as anti-toxin, right?
What if we use the overdose symptoms that Pepto-Bismol has IRL for the overdose symptoms of anti-toxin?

**Comment by Kurfursten** [comment]
A quick Google search suggests the effects of Pepto overdose are

* loss of hearing
* extreme drowsiness
* seizures

Gotta say all three of those are things that are strong incentives not to OD on antitox. Perhaps not as strong as 'literally kill your ass with internal bleeding' but respectable enough problems.

**Comment by Pathid** [comment]
@Kurfursten Okay but, there's a good percentage of players that will stuff somebody who has 60 toxloss with three of those pills thinking it will work better and it would be a rough transition.

@Shadowmech88 
There's quite a few differences, antitox removes a lot more reagents and effects:
https://github.com/vgstation-coders/vgstation13/blob/f6be733990f147806b795ab52e8714b5cddc9a66/code/modules/reagents/Chemistry-Reagents.dm#L563-L599

https://github.com/vgstation-coders/vgstation13/blob/f6be733990f147806b795ab52e8714b5cddc9a66/code/modules/reagents/Chemistry-Reagents.dm#L4207-L4225

And only antitox has the special properties of blocking liver damage from high toxloss and slowly healing lightly damaged livers. 
https://github.com/vgstation-coders/vgstation13/blob/c6569dd911fc515f820e84672d3e80e498da1f9c/code/modules/organs/internal/liver/liver.dm#L32-L45

**Comment by Shadowmech88** [comment]
Also interesting, apparently Pepto-Bismol is incredibly toxic to cats.

**Comment by DrSnips** [comment]
Possible OD effects.
Negates the function of antitox and maybe even causes you to take tox.
Cramps/stunning you in place like the stun you get after vomiting.
The blood loss one also sounds good.
Since the chem is required for basic medical treatment of toxin damage it's OD should be at the same amount as all others at 30.

**Comment by Blithering** [comment]
I would say drowsiness, dizziness and confusion (random viewpoint rotation) would render an overdose crippling enough to power gamers to discourage intentionally  overdosing

**Comment by Dacendeth** [comment]
what if overdosing on antitoxin just made you vomit sometimes? It would prevent you from overdosing for a long time because you'd just vomit it all up eventually.

**Comment by ghost** [comment]
This is a bad suggestion, and I will tell you why.  Don't just touch dylovene, touch all overdoses.  Instead of more snowflake overdoses that are just part of the chem's functionality code-wise, we should take a hard look at Rezadone and rework general overdoses to function as such.  This would prevent long term chem usage and require downtime between dosings.  Seizures, blurry vision, vomiting, heart damage: all of these things could be a part of an escalating overdose system and would greatly improve how garbage the current system is.  Something something cleaner, maintainable code.

An overhauled OD system is long overdue, that is for sure.  Just gotta make it cyro compatible.  I could see a fair solution being low body temperatures making you unable to OD.

**Comment by ghost** [comment]
It's too attractive to just shove a bunch of antitox in whatever you've just radium'd to cure and push them out the door after taking a sample, to stabilize a liver while you try to figure out what fuckface did to himself, to ride out your own bicard OD field treatment of an internal bleed, survive using stimulants, triaging a large amount of patients in a rush, etc. Where is the gain for the feature loss, accidental overdoses between patient ignorance/poor communication/meddling coworkers (ala spaceacillin/bicard), tedium of having to monitor, and transitional pains from this?

**Comment by Kurfursten** [comment]
@SarahJohnson489 It'd actually be a feature add not a feature loss to add antitox overdose. Complexity - not convenience - is what makes Baymed interesting. We don't do away with internal bleeding or broken bones because it's inconvenient to treat. Some servers are like that, in fact! I'm not saying there couldn't be some kind of relevant chemical to slow the progression of toxin damage though if that's your real concern. It might be interesting if the anti-drunk chemical ethylredoxrazine stopped liver damage from toxing you while it's in your system. The example of jamming yourself full of antitoxin to negate the OD of bicaridine is a good example of the behavior that we'd like to stop though - it was a good to bring that up. As #16571 points out -- there's a reason why nearly 150,000 units of antitox have been pumped out at the outpost dispenser by a few select ckeys!

@HarseTheef I don't disagree that an overarching system would be good, but varied sideeffects also help with treatment. In the same way you can know what's wrong with telecoms right away if the messages get slow or start to repeat, having different results can help a clever doctor know right off the top what's wrong. The reason I'm most interested in Antitoxin is, as Sarah rightfully points out, it's the chemical that snowballs the most by negating other OD effects. It multiplies the problems of overinjecting.

**Comment by ghost** [comment]
Varied side effects are nice and I encourage it.  It can be a part of the overdose system.  It is still shitcode if half of the overdose effects are hanging out in the intended effects of the drug.

**Comment by ghost** [comment]
My main concern is that unlike unintentional spaceacillin OD's which are rare and irrelevant enough that it's not going to have a real impact, obstructing Bicard OD's while you drop bolts and hide in a bin riding it out are an example of a good gameplay niche and causing potential headaches depending on further hamstringing of AT is going to cause a lot of headaches from its status as a supporting pillar of the round. AT is also unlike bicard in that toxin damage is often continuing which has created a rampant overconsumption culture further aggravated by a lack of knowledge about how much x amount cures versus bicard which is fairly static. Could it be partially mitigated on the medbay side by adding a reagent scanner to the md's pda cart? yeah. I also don't see the problem with people punishing themselves by "pudding farming" antitox for prick resistance, stim memes, hulk memes, as a call to arms against it when its worst abuses are dealt with by proper arrest procedure and lethal burger therapy respectively.  If it was to go ahead, I'd like to see the means to treat your internal bleeding in the field and a means to stall liver failure to sidestep the need for chloral/choke therapy otherwise migrated instead of dumped outright for this shoddy reason.

It's not adding complexity, it's just adding tedium and it's adding headaches from dipshits colliding

**Comment by SonixApache** [comment]
What the fuck is "lethal burger therapy" ?

**Comment by ghost** [comment]
Shoot it until it's dead confirmed by examine before getting anywhere close, cut its head off then acid/fuel tank/put in an mmi and destructive analyzer/cremate the head/scoop it out at the kitchen and bake it into a burger. Burgering is the easiest for anyone to do with the least headaches since you don't have to explain your acid.

Edit: I guess saying Lethal>Burger therapy would have been more clear.

**Comment by Exxion** [comment]
Discussion dead, reopen to continue
Or make a new issue
This is an important one but it's so fucking old nobody will see it even if you start discussing again
