### ISSUE TITLE
REMOVE HYPERZINE

### ISSUE THREAD

**Issue by Jubisloviu** [d3athrow/vgstation13#17395]
Hyperzine is a shitty ass chem that is only used for powergaming purposes and nothing else.
it's a dumb designed chem with nothing else going for it, removing it will allow spessmans to acquire robustitude because they'll learn when damage reduction is worth it the loss of mobility, it'll make it so you'll not be able to chug zine and walk around with magboots turned on 24/7 without worrying about zas ever again.
The only non powergaming use for hyperzine is to remove the slowdown from the xenoarch suit, but honestly does the xenoarch really needs a slowdown?, it has no armor and it's just a space suit with a radiation protection.
MAKE SPESS ROBUST AGAIN

**Comment by SonixApache** [comment]
>The only non powergaming use for hyperzine is to remove the slowdown from the xenoarch suit

this is powergaming

replace hyperzine with hypozine, problem solved

**Comment by Arthurdentist** [comment]
Anybody who wants to remove things like hyperzine to make the game more 'robust' is actually an atmos main who wants to make it easier to get their ZAS valids. This is 100% true undeniable fact so please don't @ me about this.

**Comment by Kurfursten** [comment]
I'm always really impressed how no matter what controversial topic we always manage to get such even numbers. I even check the names to make sure it's not people like Hugh being a meme by voting yes AND no.

**Comment by iFlashYou** [comment]
t.I want easy valids with my flamethrower

**Comment by Jubisloviu** [comment]
what hyperzine has to do with flamethrowers?

**Comment by DrSnips** [comment]
I don't want to parrot too many points but the main use for hyperzine is power game and makes any form of balance related to speed null. We say that hyperzine is then balanced by the fact that it has a reasonable OD and does the usual toxin damage but then you just drink antitoxin and it completely removes that balance point of hyperzine as well.
Overall hyperzine is a huge mistake because it has no downsides that matter and it nulls any point of speed balance. Removing the ability to create a chem (which is extremely easy to make) that completely removes a point of balance in a game is the only real solution.
I do think that the botany version is acceptable since it's intended to give access to chems that can have decent or very good effects.

**Comment by groosbstrd** [comment]
What if the recipe was changed to require something that is only available from xenobotany or xenobio or the likes? It's still in the game but it's not something you can ghetto chem or just spit out of a chem dispenser in 5 seconds.

**Comment by ghost** [comment]
just make it have  you go insanely fast but if you walk I into a wall you headbutt it

**Comment by DrSnips** [comment]
I don't think you should be able to manufacture it at all. While my stance on the botany version seems to be hypocritical to this I think that botany should be rewarding and that a chem that has the effect of hyperzine is a good reward for putting forth an ounce of skill or know-how. Technically it's already a xenobotany thing.

**Comment by Kurfursten** [comment]
I should point out that in spite of people all universally agreeing that pumping yourself full of 900u antitoxin SHOULD have a drawback, no one has ever bothered to FIX IT.

**Comment by DrSnips** [comment]
http://www.britishsoccermom.co.uk/wp-content/uploads/2016/10/goalposts.jpg

**Comment by DrSnips** [comment]
![goalposts](https://user-images.githubusercontent.com/28679186/36055154-6d96b2d4-0dc8-11e8-859b-532972c2bc95.jpg)

**Comment by Kurfursten** [comment]
Sorry, I didn't realize that everyone didn't include you. Everyone *rational* believes someone should fix Antitoxin overdosing, except Dr. Slimes

**Comment by Riekland** [comment]
I thought the xenoarch suit was changed to have zero slowdown like a five months ago

**Comment by DrSnips** [comment]
I'm not saying your statement isn't true. I'm saying that the topic and title is hyperzine nerf/removal.

**Comment by DrSnips** [comment]
See #16524

**Comment by Blithering** [comment]
I'll say to this what I said to the chloral issue, make it require chemical heating and it'll be much more of a hassle to make.

**Comment by Dacendeth** [comment]
Hyperzine shouldn't work if you're starving.

**Comment by Pathid** [comment]
There's an idea.
What if: hyperzine made you play in hardcore mode for a while? AKA starvation mode.

**Comment by SonixApache** [comment]
okay since nobody wants their heart to explode, how about this
Hyperzine doubles/triples/quadruples your metabolism, making you burn through your food way way faster. And once you hit full hunger, it stops working altogether.

**Comment by Jubisloviu** [comment]
that's way too forgiving for a chem that throws anything balanced around slowing you down out of the window.
if hyperzine were to stay i think it would be fair to make it risky just like synaptizine, a thing you would take when you really need that fucking speed right fucking now, instead of always chugging 14.9888888 everytime you feel slow and forgetting all your slowdown based problems.
and i know the nutriment thing will do jackshit to it, since you can always chug sugar/corn oil and forget about it too.

**Comment by Pathid** [comment]
That's true. It wouldn't do much of anything without changing sugar and corn oil too.

**Comment by ghost** [comment]
Maybe nutriment should be split into energy and fat? Fat is mostly negative but prevents you from starving, causes heart attacks and obviously makes you FAT. Energy covers the usual need of nutriment, but maybe used up twice as fast, therefore good food has a balance of both and you can't just chug corn oil or sugar and the chef can't just make junkfood all round. Maybe nutriment can add a slight buff too because vegetables.

**Comment by Blithering** [comment]
Maybe just change the hyperzine overdose to work a bit like chloral's does, so it goes off time in your system rather than amount at any one time

**Comment by Jubisloviu** [comment]
it's not like peoples don't already take a 14.888u pill once they get hit with the slow again anyway, that would change absolutely nothing.
Hyperzine was a mistake.

**Comment by Pathid** [comment]
What you could do is have a variable separate from the reagent itself that tracks how much hyperzine the mob has had lately and base the OD off of that.

**Comment by Blithering** [comment]
or have metabolising hyperzine cause a buildup of another chemical with its own overdose

**Comment by Pathid** [comment]
Then you can reset it with water and potassium or charcoal and that seems too easy.

**Comment by ghost** [comment]
Remove yourself and do your own experimental server where everyone works at a crawl and gets meme'd by papa binoc supported off-screen rcd/grenade/fuel tank/window shot crutch. Hyperzine is bad but it's a symptom of the focus of the game going in too many different directions with no consistency. The only thing worse than trying to do shit before someone fucks up the round is doing it at a crawl.

**Comment by Jubisloviu** [comment]
being slowed down by heavier armor suits and stuff is part of the reason why those heavier equipments are balanced around it.
hyperzine breaks the balancing, you can just don a advanced EOD suit, with your magboots turned on forever while hopped in hyperzine without a single drawback.
this proposal isn't to remove everything and slow the server down to a crawl if that's what you think, it's to remove the chem that has no use but enable you to be a juggernaut walking at sonic speeds
given a choice to a spaceman between a lighter armor to keep you light on your foot with some moderate resistances and a heavier armor that slows you down but offers higher resistances the spaceman will just chug hyperzine and ignore the drawbacks of the heavier armor.

**Comment by Killette2** [comment]
But if you make hyperzine give you hunger mode, what if they have gaben syndrome that produces 1000 nutriment so now everyone is a running fat guy to powergame?

**Comment by Pathid** [comment]
Then they won't be able to wear hardsuits. See? Balanced. 😉 

Also I'm pretty sure hyperzine doesn't affect fat slowdown.

**Comment by Killette2** [comment]
and they can chug leporazine too

**Comment by DrSnips** [comment]
Since I have the PR up and I said that I would keep discussion here I thought I would explain why Im removing it rather than nerfing it here. 
I personally feel that hyperzine is extremely broken and that it's od effect can and will always be dismissed with other chemicals you can make at the same place you make hyperzine.

**Comment by PJB3005** [comment]
Just code addictions dudes. Too much hyperzine and you become  non functional.

**Comment by DrSnips** [comment]
Wouldn't that mean you need a constant supply of hyperzine for it to be considered an addiction? I'm not sure if I like the idea of encouraging always having a certain reagent in you.

**Comment by PJB3005** [comment]
Addictions imply making the reagent less effective the more you're addicted too, so eventually you'd need so much hyperzine that you'd hit hard overdose

**Comment by PJB3005** [comment]
Also make overdose not easily abusable by taking 14.9999 units

**Comment by Reviire** [comment]
I think removing it is going too far. Consider nerfing hyperzine so it doesn't delete slowdowns, but instead mitigates them. Higher slowdowns would still slow you down for more, but you'd be able to reduce it somewhat. It'd keep some of the speed balance, you wouldn't just literally remove your slowdowns. A hungry guy with magboots on in a RIG is still gonna be slower than the guy in a hardsuit, if they're both using hyperzine.

**Comment by ghost** [comment]
@Jubisloviu What he was talking about with flamethrowers is if you aren't sanic you have a harder time juking flamethrowers cause you aren't almost immediately out of the plume(s). Much like getting shot clickspammed, slowdown racks up fast and makes you easy pickings for further. It's nothing worse than the usual laser/gun spammed in a choke but with flamers the speed gave you a chance to mitigate a lot of it.

**Comment by Pathid** [comment]
There's other ways to negate pain slowdown, like tramadol. Except tramadol sucks in comparison, and yet it takes more clicks to make. :thinking:

**Comment by ghost** [comment]
Unless you're gobbling it all day long just in case, you don't really have a choice in the moment because as you're grabbing the pill, he's about to dump a heavy blast all over you and this blast you will not quickly get out of.  Even flinging a cable bola or spritzing/splashing water that anyone can get backwards would be more productive and it's not about pain slowdown in the first place, it was about being able to have the mobility to mitigate the damage of a weapon that applies its damage every 0.1s you're in its plumes when it's generally used to hose a corner or a chokepoint to engulf you in a very floor-tiling-esque style of fight to slow you down then lay it on. Without a raw speed advantage, no amount of pain mitigation is going to bail you out. Tramadol wont suddenly fix that in the absence of hyperzine. You have flamershittered people right?  :thinking:

**Comment by Pathid** [comment]
Have to confess my ignorance about it. Anyway you could talk all day about how multiple uber-powerful tactics exist and we need hyperzine in it's current state to counter them. I guess this thing that negates several game mechanics and has practically no downsides is really holding the game together? Maybe we should just get rid of slowdown.

**Comment by ghost** [comment]
Its need for hyperzine is a consequence of the contrast between projectile speed in general from all firearms, general slowdown, and the slowdown from mags that people often need to not get fucked in an average round and often space suits they want to either have some degree of protection from the inevitable plasmafires, chasing a guy through space, or doing their job in hazardous conditions compounded by the chestpiece of the suit for many being too big to store for most and leaving it behind causing its own problems. Speed when under attack by a flamethrower just matters more since your speed can mitigate it somewhat than when someone pulls a taser, lasgun or ebow and hoses your slow ass as you're left unable to juke more than 2 or 3 shots even when fed.

Well the thing is we want slowdown because there needs to exist design headroom that creates a spectrum where in various conditions you will want to wear various clothing, armor, and space suits. The problem is that armor values are largely irrelevant from stun and done stripping, explosives, or simply overwhelming its protection which is worsened by poor slowdown granularity making no hyperzine turn you a sitting duck if they can hit the broadside of a barn. Further worsened by hyperzine/cocaine being the end all be all take it and no slowdown at all pain and magnitude of slow be damned.

It's difficult to hem in its combat uses while maintaining the design headroom in the environment we have and the quality of life for civilians who are otherwise plagued by slowdown. While I do feel we can increase the granularity of slowdown/magnitude of it and fiddle with it so that there's a comfortable medium where you can not be drugged up and still not be proj/zas bait it's not a lot of room to work with to make it matter but not cripple.

**Comment by KingofHONK** [comment]
Removing content should always be avoided in my opinion. Especially in the content starved job that is Chemist, which is already rendered useless at the 10 min "I did my job" mark.

I do agree it needs a nerf. Really all you need to do is make the OD 5u to encourage autoinjectors. which is long enough to survive one ZAS breach in a pinch. Make it become a useful paramedic tool.

Either that or you can remove it's ZAS immunity entirely which makes it a drug that keeps you from suffering slowdown from hunger.

If the perceived problem is powergaming here, then that is not a github issue, that is a ban request issue. You will find quickly that our resident powergamers will just adapt and create a new meta, and you will be having the same conversation again with a new flavor of the month line of code. In fact, isn't that wierd that we were all talking about chloral just a month ago? I don't think that's a coincidence.

Once again, not opposed to slapping a nerf on hyperzine, I think it would be interesting to have it turn into a more situational chem, but if you are concerned about powergaming I have some bad news for you, it's the players, not the game.

**Comment by LavosIG** [comment]
Removing hyperzine is for the good of most things, there are balancing concerns to be addressed but as of current, as someone who takes that shit most rounds, its just too strong. Its existence is a balancing issue in itself because what you've done, with hyperzine as its current state, is create a 3 click chem anyone can make that completely removes almost all slows (not just speeds you up.) This means that you've take slows, an intended balancing tool, and added an in game easy to obtain way to remove that intended balancing check. This is fundamentally bad game design for start and bad balancing for second. Removal allows for people to address the balancing over other items that are typically paired with hyperzine to see if people using hyperzine was to make them "viable" as opposed to "overpowered"

Powergaming is the players but hyperzine is flawed game design from ground 0, if you make a feature way too good to use of course people will use it, removing it just leaves room for proper rebalancing and addressing real issues.

**Comment by LavosIG** [comment]
That being said I agree removing content should always be avoided, I just feel hyperzine is a fundamental balancing issue

**Comment by DrSnips** [comment]
I think peole keep missing the content of the PR. 
Hyperzine is effectively being moved to the "harder to get" reagents like carpotoxin or zombie powder. It doesn't say completely remove hyperzine it says removes the method to make it.
I dont think its balanced at all but I felt that it could be left in as something that's a treat to use rather than something you have access to in bulk all the time.

**Comment by Reviire** [comment]
@luzzgawr For the record, I am a resident powergamer. Hello, I am for the Hyperzine removal PR. Just because I powergame doesn't mean I don't want proper balance. If something is incredibly easy to abuse and offers immense benefits, it's not good design. 

If you're just going to ban people for using these chemicals in the situations they're good in, hey, what if we just removed the chemical? Because 100% of Hyperzine uses are powergaming. Countering magboot slows, hardsuit slows, hunger slows, damage slows... other slows that exist for balance reasons...

It 100% is the game. This powergaming takes 3 ENTIRE clicks. It's not some intensive process of powergaming to raid some space vault with high risks. You click 3 times, you remove all slows in the game. It would be like if you gave security a pulse rifle sitting on the desk, and called them powergamers if they touched it. 

Hyperzine shouldn't be removed or made hard to get anyway, it should mitigate slows by 30-50%.

**Comment by luzzgawr** [comment]
The OP says that it should be removed because powergaming and that was my rebuttal (if you want powergaming fixed then talk to admins not coders).

**Comment by LavosIG** [comment]
If hyperzine mitigated instead of removing a balancing feature it would be within the realm of possibility to fix it, but as of current its still too simple to get even if it did just mitigate slows instead. It should require at least something more then 3 clicks to get it because it is so useful and easy to get even as a 30-50% mitigation.

**Comment by Spessgontran** [comment]
Hyperzine is fine as it is. Not everyone uses it on a daily basis, except tree people and xenoarch since their suit  suffer a slowdown on their speed. The speed it's provide isn't that great as well unless you want to use magboots, and even then anyone with a mind will just order some if ZAS gets fucked.

Also, whoever created https://pastebin.com/Wec8QGrF clearly forgot that it is part of the job of Chemists to create hyperzine for the crew and store it in the fridge. Not to forget it is years of data taken into account. Reminder that if you take more than 15 units, you will OD on it and die. Using more or less won't affect the speed, it will just take more time for your body to ingest it

As antagonist, i barely ever used hyperzine because it wasn't necessary. I had plenty of other tricks in my bag to get around security, and ZAS wasn't a problem unless i didn't prepare myself properly for it. 

Hyperzine itself had a nerf on itself a year ago or so, if you tase someone that took some, they'll take longer before they are able to get up. 

The real problem is newfags not understanding the possibilities they can have by using items, it's the very same thing as HoS/Captain bitching about AI locking them down when they harm humans when they could have just set NT Default. You have possibilities of using something but you don't because it's makes the game "easier" and chose to whine about it instead.

Spess is about fun, removing something that makes it fun is shit. This isn't bay or TG, if you want to change something that makes the game fun for people, just change server and they'll gladly accept you there. Just accept that you too you can have fun with hyperzine instead of trying to change it

**Comment by SonixApache** [comment]
make hyperzine increase your metabolism so it metabolizes itself faster

**Comment by Exxion** [comment]
No discussion for over two months
Reopen if you want more discussion, etc.

Also I believe someone *did* nerf hyperzine at some point after this anyway
