### ISSUE TITLE
Cigarette Reagent Distribution

### ISSUE THREAD

**Issue by imw-Oculus** [d3athrow/vgstation13#17418]
If it is an issue that I did not use the provided form, please alert me and lock this issue - I will make a new one that is formatted properly. 

Synopsis:
As it currently stands, cigarettes can contain up to 15u of reagents. This would ideally be a novel way to distribute reagents slowly into the body of the smoker. Unfortunately, the rate at which reagents are put into the body is not congruent with how the long cigarette can be smoked.

Suggested Fix:
code/game/objects/items/weapons/cigs_lighters.dm
Line 367
```
if (smoketime % 20 == 0)
        reagents.reaction(M, INGEST)
        reagents.trans_to(M, 1)
```

**Comment by Kurfursten** [comment]
Nobody is that anal about format, the template exists mostly to help with bug reporting because people will post vague reports like "cigarette chems suck" and nothing else.

This is kind of a nuanced issue though because some people like that the chems are delivered right away, for example, to make trap chloral cigs or healing poppy blunts that want to deliver bicaridine much more often than every 20 ticks. What you describe mostly benefits very low metabolism chems like oxycodone, synaptizine, hyperzine, and nanobots.

Perhaps it would be interesting to have varied max reagents and chemical rate based on type of smoking instrument though. Currently we have gum, cigarettes, cigars, pipes, and blunts. Could add vaporizers and hookah, too, if that's not enough variance.

**Comment by imw-Oculus** [comment]
I would favor a more modular approach - maybe a new pair of reagents that slightly increase/decrease the rate of metabolism in the holder. Maybe have it depend on how fast the particular reagent is being metabolized in the first place.

**Comment by nuklearcellphoneg** [comment]
The amount of reagents taken per tick from the cigarette and put into the person must be enough to metabolize. I'm not sure what the actual  numbers are, but I'd wager if 15u was stretched out across the life of the cigarette it wouldn't be enough to have an effect.

**Comment by SonixApache** [comment]
If it was just bursts of 1u(or whatever's enough to metabolize) throughout the lifetime of the smokable it'd work, right?
I thought about this myself, since my cigarettes usually run outta juice before they're done smoking.

**Comment by nuklearcellphoneg** [comment]
Yeah but I imagine it wouldn't be nearly as long as the cig but I could be wrong. I think they inject all at one time as it stands.

**Comment by Kurfursten** [comment]
Sonix is correct, the current function is that it injects 1u every tick. The body metabolizes 0.2u per tick by default unless the chem has a modified metabolism rate iirc.  Oculus proposes that it instead inject once every 20 ticks.

You certainly could time it to last the life of the cig but regardless unless the metabolism * ticks per injection >= 1

**Comment by FudgePucker** [comment]
Maybe make cigs inject 0.2 every tic and also, shorten the time cigs stay lit/ increase the amount they hold. Exceptions can be made for empty cigerites that burn longer for RP and plasma/welder fuel exploding ones.

**Comment by FudgePucker** [comment]
You could then actually add nicotine to ciggies without it being a lethal dose.

**Comment by imw-Oculus** [comment]
I was thinking along similar lines, Fudge. 
Thoughts on:
- Shortening cigarette burn time
- Adding nicotine to cigarettes
