### ISSUE TITLE
Glass Bottles (Groans Soda) And Booze Container, And Molotovs, No longer Break.  Groans Soda Can Now Block Projectiles.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17424]
(WEB REPORT BY: anglosphere REMOTE: 172.93.109.202:7777)
# Revision
ba8e532970cddfb7e75d397b4bab413ecbe9f095

# Description
Throw a glass container at the ground.
It doesnt break. 

Also Groans Sodas now block bullets, tasers, and lasers from crossing the tile they are on. 

# Steps to Reproduce
Acquire Groans Soda, or a container of booze and throw it at the grund, or some one. 

Shoot a laser at something behind a groans soda. 

# What you Expected
The Glass Containers to break 

Glass Bottles on the floor to not block bullets, lasers, and tasers. 

# What Actually Happened
See Above.

**Comment by ghost** [comment]
feature, nanotrasen manufactured containers made out of reinforced plasmatic glass

**Comment by ghost** [comment]
HELLO?

**Comment by carshalash** [comment]
![image](https://user-images.githubusercontent.com/16896032/36082051-dee7e61c-0ff1-11e8-92b7-d72623447750.png)
IM FUCKING INVINCIBLE

**Comment by ghost** [comment]
https://youtu.be/e0WqAmuSXEQ?t=40s

**Comment by Anglosphere** [comment]
![dafuq](https://user-images.githubusercontent.com/20270723/36189188-af770858-1105-11e8-90d9-b243db42b1b6.gif)

**Comment by ghost** [comment]
based on my testing it seems to just be a product of cluttered tiles of ANY items blocking shots if you accidentally target the items.  I mean I guess you are targeting the item, so it makes sense.  Interesting enough, if you target an item that a mob is standing on, it will always connect with the mob instead of the item.

A non-issue as long as hitting items is intended.

**Comment by DamianX** [comment]
Related to #16466 perhaps?

**Comment by ghost** [comment]
VERY likely @DamianX

**Comment by Exxion** [comment]
Yeah if you click on something, you shoot that thing
There's no bug here if the shots simply don't pass when you click *on* the thrown item
HOWEVER, this sounds like a runtime. Thrown items are dense for the duration of the throw, and if something runtimes before the bottle breaks, then that would explain both the bottle failing to break and shots hitting it.

**Comment by Exxion** [comment]
There is indeed a runtime, which is presumably the cause of the bottle failing to break
However, I cannot reproduce the projectile blocking part of the issue

EDIT: In addition, the runtime only happens when the bottle hits an object or wall. If you throw it at the floor (like the report says), it works fine (other than the log claiming it was an unlit molotov)
