### ISSUE TITLE
Dexalin/Dexalin+ balance

### ISSUE THREAD

**Issue by imw-Oculus** [d3athrow/vgstation13#17503]
Synopsis:
Currently, the only reason to produce Dexalin is as a precursor to Dexalin+. This balance suggestion does not change the effect of either reagent, but it does modify their metabolism rates. These changes would alter the utility of each reagent, and make them more distinct. Dexalin would find its niche as a longer-term solution to oxygen damage, where Dexalin+ would be better used for emergency stabilization. 
Keeping the above in mind, I've also suggested adding an overdose limit for Dexalin+. I believe that a reagent that completely nullifies a source of damage more than qualifies for an overdose limit. 

core/modules/reagents/Chemistry-Reagents.dm

Dexalin:
Line 2300
`custom_metabolism = 0.2`

Dexalin+:
Line 2318
```
custom_metabolism = 0.6
overdose_am = REAGENTS_OVERDOSE
```

**Comment by Pathid** [comment]
While we're on the subject of stabilizing chems, `custom_metabolism = 0.5` for inaprovaline seems a bit high for how little good it does a lot of the time.

**Comment by imw-Oculus** [comment]
The reagents module (like many others) needs love and attention, but one thing at a time. Maybe open up an issue for Inaprovaline? I'd have thoughts for you.

**Comment by Pathid** [comment]
I only mention it because the role it fills is pretty much dexalin-. It's not something you're likely to use if you have dexalin on hand. I mean technically it's also bicaridine- and tramadol- but that's more subtle.

**Comment by ShiftyRail** [comment]
I don't think there is any reason to "nerf" Dexalin Plus.

**Comment by imw-Oculus** [comment]
Fair points. Inaprovaline is supposed to be the "stabilizer" reagent, in my eyes. It's not really meant to heal anything. Dexalin, on the other hand, is a healing reagent. Reinforcing Inaprovaline's niche as the stabilizer should be possible. Maybe replace those Doctor's Delight injectors with Inaprovaline injectors.

**Comment by imw-Oculus** [comment]
What part of my reasoning do you disagree with, Shifty? I'd like your thoughts!

**Comment by Pathid** [comment]
Nothing wrong with having multiple stabilizers as long as they all have a niche. That's the thing with dexalin, it doesn't have its own niche if you have a chem dispenser to add iron and carbon to it.

**Comment by ghost** [comment]
Hell no. Any rube can use dex which is everywhere and civilized places run dex+. Like hyperzine, speeding it up and adding an OD does fucking nothing because you just keep reapplying it. The only thing you accomplish is adding tedium while failing to create your niche.

**Comment by Pathid** [comment]
Right, the niche is the availability of blue medkits. The chemist isn't going to care about that but non-medbay crew are.

**Comment by imw-Oculus** [comment]
Sarah, do you agree that there's a need to differentiate Dexalin from Dexalin+? Do you think Dexalin has enough utility to justify it as a reagent? I'm not attacking you, different opinions are good.

Sarah/Pathid - An interesting point regarding availability. I was looking at the issue purely from the point of comparing Dexalin to Dexalin+. However, I find the assertion that we should have chems around that are deliberately gimped interesting. Should we make more chems that are easier to produce, but less effective? That'd be interesting as a supplement to ghetto chemistry.

**Comment by ghost** [comment]
It's fine as it is. Dexalin is more widely available from lockers and cargo without risking triggering shitcurty/chloralbay if you're concerned about your day being turned upside down by a jerk with a stick up their ass. It'll still stabilize someone lased into crit while you locker them to med. 

Not really and they kind of already exist. Things are pretty solid where they are. 
Tier 1: tea/milk/nutriment/tomato juice/citrus juices/iron powder, field blood donations, donk pockets, kit dex, kit Doctor's delight, medbot, luckshitting or asking for healing seeds in a maint access or willing to hack role
Tier 2: Cargo kits, specialized medbots, cargo blood crates, cargo megaseed restock, buying a cargo cow, hacked antitox, hacked syndiecakes, hacked O- blood packs, botany handouts, mortar and filtered dex+ from kits and burnt messes, general ghetto chem produced meds
Tier 3: Chem/sci/mechanics dispensers because you've learned how to rotate windows and med's blood fridge
Tier 4: Disposaled into a pen with vines and bees injecting dex+, kelotane, dermalin, bicard, antitox, dexalin, sugar, tramadol

**Comment by imw-Oculus** [comment]
All of these are fair thoughts, this issue can be closed if desired.
