### ISSUE TITLE
Stubborn brain syndrome nullspaces the ghost of whoever dies with it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17604]
(WEB REPORT BY: blithering REMOTE: 172.93.109.202:7777)
# Revision
cdb9f184780a1b5d20a9aeb4d472c3c99af1e8fa

# Description
When infected with stubborn brain syndrome, the zombie spawned is not player controlled, and the player is booted into nullspace
# Steps to Reproduce
get stubborn brain syndrome, die
# What you Expected
come back as a zombie
# What Actually Happened
get nullspaced as zombie AI assumes direct control

**Comment by Pathid** [comment]
The mindlessness seems to be intentional on the part of the person who made the virus symptom. The nullspacing is a different story and that's most definitely an oversight. What `make_zombie()` tries to do is store your original body in nullspace so it can be retrieved if you're turned back to normal with a bible, but it doesn't call `ghostize()` or make any provisions for the ghost.
