### ISSUE TITLE
It'd be for the best to make advanced bartender machines work differently.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#17613]
It's basically free shit forever.  And by basically I mean that's what it is.  The recharge rate is negligible and even if it wasn't it's a recharge rate.  It'll come back with no effort.

This isn't an important issue but it is one of those little things that undermines other stuff.  Can anyone think of a better way these machines can work?  The only thing off the top of my head I have is make them require batteries that drain instead of being area powered machines.

**Comment by ghost** [comment]
I'm going to disagree: We're a server which encourages roleplay, but doesn't enforce it. - Bay, a server which enforces roleplay, has refill cartridges and such for their booze dispensers (at least if I recall correctly).

Drinking alcohol has no in game benefit. Why nerf something which is solely for roleplay?

**Comment by Probe1** [comment]
Because they produce more than just ETHANOL they make everything from cream to teas of various healing qualities, to doppio and so on.  It's not like they're useless ingredients or else they wouldn't get so much use.

Refill cartridges sound like the best solution.

Expanding on my thoughts a little bit more.  Stuff like this messes with other systems in a subtle but impactful way.  If I can just hop to cargo and get infinite of whatnot then why do I want to milk a cow or use the biogenerator?  Where does that leave the biogen?  I don't think everything in the game needs a specific use but I do hate having one accessible thing overwrite other things that still exist.

**Comment by imw-Oculus** [comment]
For clarity's sake - this discussion was initiated by the fact that you can electrolyze cream from Booze Dispensers for infinite milk.
I was the one who dropped this hot tip on the thread, and I'm regretting it now.

There are a staggering number of "exploits" like this that can be found with electrolysis. Changing how one machine works won't remove them. If you want to "solve" them all, you'd have to change how electrolysis works, or how reagent dispensers work. 

I am not opposed to the idea of refill cartridges, but it'd be unfair to apply them to just this one machine. Having something like Compressed Matter Cartridges would be interesting. "Compressed Reagent Cartridges". I doubt this would be a very popular or practical change, however.

**Comment by Probe1** [comment]
Obviously it's applicable to all three machines and don't worry.  This is something that came to mind when they were added two? years ago it just reminded me to care today.

**Comment by imw-Oculus** [comment]
Okey dokey, glad that it's been taken into consideration. I really need to hop back on the code discord - is it fairly active and friendly to stupid questions? I'm having difficulty getting my github up and working, and I've spotted a couple of obvious one-line bugs already.

**Comment by DamianX** [comment]
Yes.

**Comment by ghost** [comment]
Refill packs for the chem dispenser too while you're at it.

**Comment by Kuranon** [comment]
no it wouldn't

**Comment by Kammerjunk** [comment]
>Cream into milk

What's gonna be the difference between requiring refill cartridges from cargo and just refilling the Booze-O-Mat with a supply pack from cargo? I seriously doubt *bartenders* have any issue with bottles cluttering up their table, so what will the important difference between the machines be?
That aside, the Booze-O-Mat already has 4 cartons of cream and each of them contain 100u for a total of 400u or 80% of what a dispenser with tier 1 components can contain/40% of what a dispenser with tier 3 components can contain.

>Plain milk

How much biofuel can the botany machine that spews out toys and goodies give you per period of time if you're just filling it up casually? In that machine, 20u milk costs 10 biofuel (10u E-Z-Nutriment is 10, 1 slab of meat is 50, 1 monkeycube is 250, a box of crayons with the extraordinary balance-related uses of eating them and painting your glubbs is *400*).
I don't think that the ability to make lots of milk through electrolysis (which also requires metal, wires, another beaker, a power cell, and the actual booze dispenser from cargo) entirely nulls the idea that you can just plant some stuff in the room you already have access to and mass-produce milk. You could also loot the chef's fridge for 250u milk, a quarter of what the booze dispenser can contain with tier 3 parts and *half* of what the booze dispenser can contain with tier 1 parts. You could also do neither of those since the Booze-O-Mat already has 4 cartons of milk with 50u in each for a grand total of 200u milk.

>Other uses

Not like anyone ever gives medbay DD anyway. Not like medbay ever uses DD anyway.

**Comment by Kurfursten** [comment]
I don't really view it as an issue. A cow is also free milk forever.

The real chemistry dispenser is way more important anyway and it's also infinite.

**Comment by FudgePucker** [comment]
You can also use a device analyser to print vending machines with full stock.
Milk isn't some game breaking chem.

**Comment by imw-Oculus** [comment]
@morenaaa 
That was my thought as well. The question is: what defines a reasonable limit on starting resources for Chemistry that won't make people freak out. 

@Kurfursten 
Is it necessarily infinite in your opinion? Reference the above question I posed to morenaaa. 


A spitball to go along with this: adding a machine which takes a small amount of plasma, and a very large amount of power to create Reagent Cartridges

**Comment by FudgePucker** [comment]
Seriously, its a child of chemical dispenser. Doctors delight is only slightly better than tricord. If they go though all the effort of getting cargo to cooroparate and setting it all up and making everything, who are we to stop them?

**Comment by ghost** [comment]
My post was mostly sarcasm. I don't see an issue with them at all. I use them a lot of the time and there's nothing inherently wrong with them. They can be a completely pain to set up as anything but Cargo, and essentially all they are are a replacement of the Booze-O-Mat. It makes the whole bartender thing a lot easier as you don't have to faff around with all this clicking to change transfer amounts, picking up and dropping stuff. With a Chem Dispenser too, you can make Doctor's Delight. Big Whoop. No one really wants that. If you make it and give it to Medbay it'll probably just sit and go to waste. 
What do you think medbays do with the DD from their autoinjectors? They just trash it. 
You also mentioned Doppio. Which does nothing. If you had said about Tonio, you'd be wrong, because you need things for that the machine does not make. Plus, these are the only way to even get Red and Green tea in the first place, to make useful teas like Chifir, and even that all that is is charcoal, because it makes you vomit. 
It's pointless to change them. The few people who even bother getting them when a Bartender or otherwise are never going to do something insanely crazy and gamebreaking with them, because there isn't anything you can do.

And changing the Chem Dispenser will just mean that one cryomix and a few pills and poof, chemistry becomes useless.
Can we please focus on content instead of "balance" changes?

**Comment by Anglosphere** [comment]
Run them on biomass cartridges from the biogen.

**Comment by ghost** [comment]
Since when is milk so important anyways?

**Comment by Exxion** [comment]
Discussion dead
You know the drill

Also, why take issue with these but not the chem dispenser?
