### ISSUE TITLE
Bridge shuttlepod vaped me

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17738]
(WEB REPORT BY: spooooon REMOTE: 172.93.109.202:7777)
# Revision
882b9a9bd7ef8db051980b94431d1d7c948e253a

# Description
Got toasted on the escape pod near bridge on bagel when it took off, killed me instantly, despite 3 other people being jammed into the pod.  Rip.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kurfursten** [comment]
Followed up on this in the OOC: both people sitting in the second seat caught fire and burned over time. Door was closed. Probably improper fire placement.

**Comment by Probe1** [comment]
I see absolutely no indication that this issue is unique to bagel.  

**Bagel**
![image](https://user-images.githubusercontent.com/8550416/37309112-4935d09e-2616-11e8-86c5-1b2d263db599.png)

**Box**

![image](https://user-images.githubusercontent.com/8550416/37309122-53441e38-2616-11e8-9ad7-d3e6560f50fc.png)
