### ISSUE TITLE
Bible smashing zombies ghosts zombie

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17810]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)
# Revision
27c0f71f942d9cbb48bf29cbdb75e1f91e6aeee9

# Description
When a chaplain revives a zombie via bible smashing the ghost gets ejected and is unable to re-enter the body
# Steps to Reproduce
zombify someone and then bible smash until human
# What you Expected
To be in the body
# What Actually Happened
Had an out-of-body experience

**Comment by Kevak** [comment]
I'm pretty sure I participated in this round (as the zombie) so I'll add further details from my end and possible theories on what caused it.

Timeline:
B1/B2 for body 1/body2 and so on.

>B1 spawns as wizard.
>B1 goes and gets killed.
>B1 ghosts, becoming G1 while leaving a body (B1) behind.
>G1 spawns as wizard 2. Becoming B2(G1).
>G1 is still tied to B1. B1 gets Staff Of Necromancied and yanks G1 out of B2 body and shoves into simplemobbified B1. (ZB1)
>ZB1 dies. G1 ghosts but it turns out that G1 is actually G2, name and title of B2.
>ZB1 gets gibbed as mind is no longer present and simplemob is by default hostile.
>B2 gets rezzed into ZB2, pulling G2 into body.
>ZB2 dies a couple times and comes back due to undeath.
>ZB2 gets cured of undeath via chaplain and becomes B2. Full spells included. B2 does not contain G2. G2 turns into G1. G1 is orphaned from body.
>Admin shoves G1 into B2 after prayer.

I suspect that part of the problem is that the current way wizards spawn does not detach them from their original body. There's a similar issue with cloning being able to do stuff like yoink construct minds without warning or dionae minds without warning.

**Comment by AI-Is-Rogue** [comment]
I actually wrote the bug report off of my own experience being zombified that round. I was the detective revived by the captain with the staff. After some moaning and groaning he got the chaplain to fix me with a bible, where I then got ejected from my body after it became human again.
I was unable to re-enter my own body which was also catatonic

**Comment by Kevak** [comment]
Ah fair enough.
