### ISSUE TITLE
Infinite Power Issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17907]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
# Revision
4315dc729429be213ad2e4f04eb8f4bde0a7886f

# Description
cell chargers use less power than they're putting into the cell, since the APC uses power very weird and since the APC uses cells, the cells have very minimal charge drained whenever the cell charger charges a cell, meaning all you have to do to have infinite power in the APC is have charged cells. the hand crank is also very good at charging cells.
perhaps a replacement for this could be to make APCs only use a special cell that can only go in APCs and have very low amounts of charge, or to make the APC use more charge from the cell.

**Comment by Aurx** [comment]
If memory serves, the last time this was brought up it was mentioned that APC charge rate is simply too low to power a cell charger at 1:1.  You'd have to either cut cell charger charge rate (QoL impact) or increase APC charge rate (massive increase in draw on the grid).  
Special cells would just be a pain in the ass.

**Comment by MiniMeatwad** [comment]
oh okay

**Comment by Aurx** [comment]
Come to think of it, giving cell chargers their OWN internal cell (or cells) that charge from the APC at a slow rate with 1:1 power conversion but dump into the cell they're supposed to charge at a significantly faster rate could work.

**Comment by MiniMeatwad** [comment]
might want to check the cyborg recharger too because i don't know how it charges the cells in it

**Comment by ghost** [comment]
It auto-sets them to full. You can plonk an empty hyper in a borg recharger, smash that upgrade cell, and walk out 30,000 charge

**Comment by Reviire** [comment]
Maybe if APCs could charge at a decent rate, and had decent capacity they could charge cells 1:1, as it stands a default APC will be drained in one or two seconds charging, an APC with a hypercell would be drained in about 9 or 10.

**Comment by abagone** [comment]
I don't know from a gameplay perspective you still have to manually replace the power cell so it's not really infinite FREE power because someone has to do something. 
We already have the hand crank and the treadmills both of those easily produce power but you have to do something manually to get it. 
I'm just saying that being able to "_infinite power_" is not a bad thing as long they can't just leave it alone and work indefinitely by itself.
(Which is exactly what you can do with a material sympathizer as a mommi by putting plasma or uranium into a generator and then using that to generate more than enough power to make more fuel.)
And I do agree we should make power cell recharges 1:1 with APCs .

Aurx said
>Come to think of it, giving cell chargers their OWN internal cell (or cells) that charge from the APC at a slow rate with 1:1 power conversion but dump into the cell they're supposed to charge at a significantly faster rate could work.

Is a good idea.
My idea is to make cell chargers and other chargers slowly recharge from APCs at a 1:1 rate but allow them to be wired directly to the grid and prefer to draw from it but if there is no power in the grid they can still slowly draw from the APCs.

And SarahJohnson489 they used to not do that but it was changed for convenience because who wants who sit in the recharger and wait for their new power cell to fully charge.
