### ISSUE TITLE
Baguloose from putting mintature black hole into plastic bag.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18002]
(WEB REPORT BY: spoonylove REMOTE: 172.93.109.202:7777)
# Revision
1759f357e3820a61cb4fc846e3384fd2dacc3ae5

# Description
misclicked putting the mini black hole into plastic bag, killing me and someone else. 

# Steps to Reproduce
get the mini black hole on centcomm, put it in a plastic bag

# What you Expected
nothing

# What Actually Happened
baguloose

**Comment by Pathid** [comment]
All you did was put it in the plastic bag?

![plastic black](https://user-images.githubusercontent.com/31839805/38235869-6a3bc4d4-36d7-11e8-82cb-1a3380b5336e.PNG)

**Comment by spoonylove** [comment]
thats all I saw, next thing I know we are gibs. It wasnt instant tho.

**Comment by small-boss** [comment]
i was able to replicate it
1. put the black hole in the plastic bag
2. open the black hole's inventory
3. click on one of the slots with plastic bag in hand
what i guess is that the game sees that the plastic bag has a black hole in it, and it also thinks we are trying to put the plastic bag into the black hole. due to that the singularity gets spawned

**Comment by Pathid** [comment]
That would do it.

**Comment by MadmanMartian** [comment]
absolutely correct. It's checking for bags of holding before it has confirmed that it can be put in the bag.
