### ISSUE TITLE
please add vampire clans

### ISSUE THREAD

**Issue by Jubisloviu** [d3athrow/vgstation13#18015]
i mean, it's a idea peoples have been talking about for a while, imagine it being like the vampire clans from WoD, or Vampire: The Masquerade - Bloodline
the idea here is to give the vampire more options to decide their playstyle and how well they'll fare
imagine as soon as you start and roll as a vampire you get to pick one of the many Vampire Clans, each clan with different disciplines and playstyle

Clans like Tremere, Ventrue, Brujah, Nosferatu, Malkavian, Toreador, Gangrel with different powers and different playstyles

**Comment by Irradiation** [comment]
Please buff the Toreador, CHA builds are pretty shit in the current meta, they really need something to keep up with the rest, you know?

**Comment by Durgen** [comment]
\>It's another Deff Nosferatu episode.

**Comment by Waismuth** [comment]
That's actually a really good idea! This would allow vampires to be more combat oriented, or persuasion focused, adding more on different ways of making the round interesting. Maybe one clan would be able to make thralls for cheaper/faster cost, other would be able to shapeshift, others would have a battle form, so something like horror form for lings?

**Comment by Kurfursten** [comment]
The problem with suggestions like these is that they are vague enough to sound broadly appealing (you fill in with your imagination what each clan might do) but in practice would consist of some 20 PRs to add a lot of content. Like for example when people asked for Traders to have stuff actually worth trading and that took like a year and some twenty PRs.

It's a lot easier and more atomic to do, say, one ling/vamp/wiz spell or traitor uplink item than it is to do Deity-style revamps of an entire gamemode. But if you want to go that route you should do what he does and draw up a design document. Deobfuscate your plans ahead of time: what are the clans and their strengths, what needs to be added specifically? How will those things be executed? (e.g.: Do you pick your clan off a menu? Randomly assigned? Assigned dynamically based off how you carry out the round and the abilities you use?)

I'll give you an example based off VtM since that's what people are talking about. How *specifically* would you execute something like Brujah's affinity for unarmed violence? Give them hulk? Just make their unarmed punches deal more damage? Brujah's weakness is a penalty against frenzy checks, something that doesn't exist in our imagining of vampires. How will you differentiate Brujah from Gangrel without causing riots for getting too close to furry territory? How do you execute Malkavian madness in a meaningful way? Besides the annoyance of fake doorshocks, hallucinations do not hinder an experienced player much, and on the flipside, how do you convey a bonus to inspection? Do you end up limiting thermal vision to just the Malks? These are all questions that need to be answered just to start.

**Comment by NigglyWiggly** [comment]
![image](https://user-images.githubusercontent.com/9064611/38337989-a19101d8-3835-11e8-8b5d-e1ddde5edcae.png)
Pictured: Kurfursten

**Comment by Jubisloviu** [comment]
>How specifically would you execute something like Brujah's affinity for unarmed violence

Good question, just like dionae can slash peoples with their claws i was thinking on making it so  brujahs/gangrels would have a toggle spell that would enable them to increase their unarmed damage, giving it sharpness, increased knockdown chance and the fact that you can't drop it sounds pretty good.
also Celerity would give them a chance to deflect and dodge tasers/batons/bullets while increasing their movespeed considerably at the cost of some blood to activate it, of course the more blood the vampire got in the round, the better would become his disciplines, at the maximum blood level Brujah/Gangrels claws are just as good if not better than a e-sword that can't be disarmed and is really sharp.

Honestly you do have a good point in the frenzy thing, i can't really say there'd be a way to actually implement it that wouldn't be cancer as shit or flatout terrible, maybe scrap out frenzy and add another backdrawn, we are in the year 2525, centuries after gehenna and shit maybe vampires evolved enough to not have retarded drawbacks

i mean i'm just throwing ideas around see what sticks, we could have vampire clans but they wouldn't need to be 100% based around WoD i guess

i guess i'm just tired of how vampire doesn't get cool powers like changelings, there's no good shit like Fat Sting or changing the appearance of everyone

**Comment by Aurx** [comment]
Please add actual actionable item.

**Comment by jknpj** [comment]
a thing now
