### ISSUE TITLE
Action Button Screenfreeze Test

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#18064]
If you received a viewport screen freeze during the testing period of April 10th through April 11th please report it here.

**Comment by ghost** [comment]
!!Action buttons are being removed as part of a temporary test to figure out the cause of screen freezes - some items will now have to be used in your hand to be toggled until this test is complete!! - please immediately ahelp WITH A SCREENSHOT if your screen is frozen and NOT fixed by relogging and/or waiting 30 seconds."

**Comment by ghost** [comment]
Also, if you experience less screen freezes than usual, please comment here.

**Comment by ghost** [comment]
If you experience a screen freeze during this testing: please include these three things in your ahelp and accompanying screenshot: What were you doing when your screen froze, how often do you get screen freezes normally, and does relogging fix it?
