### ISSUE TITLE
Box Engineering Discussion

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#18322]
This is something I've been thinking about a lot since doing a modernization on Box Telecoms and ending up with a ton of leftover space. The old design was just super huge and fat. Our current engineering borrows heavily from the servers we originally stole Box from, and I wonder if we could do better. I've sketched out a rough sort of design incorporating some inspiration from a post @SarahJohnson489 made about this about a year ago.

Roughly  I imagine the key elements of a serious rebuild would *learn* from the good parts of a lot of our other maps and combine their best aspects:
* Frontal lobby room has a "thief catcher" design like Bagel's entry, double-airlocked to discourage tailgating
* Centerpiece of the department is a TEG with easy access to both Atmosia and the engines, allowing for comfortable flow throughout the department
* CE room positioned near secure storage to act like a "warden" over secure rooms; learns from Deff/Bagel design with shutters easily openable for distribution of gear. Can split up storage into sub areas (circuit boards, shield generators, spare canisters, etc) and partition them with glass/doors.
* Move eng hardsuits out of secure storage so that opening up right at roundstart isn't necessary (e.g.: metaclub)
* Modernized engine chamber built with passive h/e pipe fittings making it configurable to run as a hot chamber (TEG and/or RUST) or cold chamber (SME)

Here's a very rough "sketch" composite from moving some rooms around inside the available area. We have a lot of dead space to move things around and make it work. Right now I would like to gather opinions before even considering starting on something this huge. I think there are a lot of longtime engineers who could have good input. Some potential concerns I have already:
* AME/SME is pretty close to tcoms in this design, may suffer from the deff problem where a blown shard knocks out comms
* Singulo this close to SME seems to tempt fate, but then it's already really close on Box so that's not really changing much.
* It's possible people think that tech storage needs to remain its own room separate from secure storage

![sketched build](https://user-images.githubusercontent.com/9782036/40292493-408459c8-5c91-11e8-929f-e0c2ce6ec73d.png)

**Comment by Exxion** [comment]
Not related to layout, but worth mentioning here in case someone actually works on this:
A bunch of the tiles in the AME room are set to `blocks_air = 1` for some reason. Probably someone clicked the wrong instance in the mapper. So if you're moving stuff around, maybe fix those.
Unless someone finally fixed that while I was away

**Comment by SonixApache** [comment]
Perhaps we should ping some people that could provide good input outside of github?
I can't really say much about engineering, apart from the following.
- best aspects section is A-OK with me, those all sound like good ideas.
- Having an atmosia-type suit-up room for the normal engineers would be nice, rather than stuffing the suits (that they almost always wear 24/7) into secure storage. I'm a big fan of personal (department) lockers.
- Secure storage and Tech storage should definitely be seperate. 
- I don't think having the SME close to the singulo / TComms is a bad thing. I *do* think having no immediate access to space from the SME chamber is a bad thing.
- Add a construction site somewhere?
