### ISSUE TITLE
Weighted Voting is a pop killer

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#18537]
#### Description of issue
Weighted voting kills pop round by round basis faster than lack of overall content.

#### Difference between expected and actual behavior
I expected to play on a map which got most votes.

#### Steps to reproduce 
Vote for a map, then play on deff because >1 vote. 

I don't know if there is any other game out there that gives you the choice to vote for a map and then uses RNG to determine which map gets chosen out of a pool of all the maps which got a vote. It is a dumb system put in place so that other maps get played because people put time and effort into making them, it is a nice sentiment but that's all it is. 

It wouldn't be as big of a deal if all the other maps weren't objectively garbage. We don't have a lot of interesting shit that could be used in harmony with station layouts so the other maps simply don't have a point to them other than the fact that they have a different layout and that their layouts are inferior to box.

**Comment by vampirebat74** [comment]
m-m-muh deff

**Comment by ShiftyRail** [comment]
Hot take : make it weighted voted one round of two, normal voting the other.

>that their layouts are inferior to box.

Debatable

**Comment by Killette2** [comment]
What if we have a weighted vote to vote whether our map vote will be democracy or weighted? Memes aside, it would at least be an improvement.

**Comment by Durgen** [comment]
The weighted randomness should exclude options that get less than x% of votes.

And if a map wins n times in a row, it should be excluded from the next vote.

**Comment by Riekland** [comment]
remove box from the rotation

**Comment by Hoshi-chan** [comment]
Did Box just lose the vote, so you created this issue in the heat of the moment?

The only _real_ issue with the non-Box maps, aside from the way Boxbabbies cry every time they come up, is that their asteroids are kind of a fucking pain for shaft miners due to the lack of a western field equivalent where they can be guaranteed to find real diamonds.

**Comment by MusgardTiger** [comment]
"Did I vagblasted ur waifu now you are posting this is this whats happening?"

Nah, I started playing five years ago, been adminning four years of it and I can spot patterns when I see them. I spoke against weighted voting when it was first implemented because it was gonna be a pop killer and it was and still is, however nobody gave a shit back then because our peak numbers weren't between 20-30. Now on the regular we get 10-20 players and when >1% vote wins the poll it makes people just quit and come back later which wouldn't be an issue if we had even a medium sized playerbase but we don't.

@Hoshi-chan

**Comment by bathosbathtime** [comment]
15% seems like a good cut off for me if we are using a percentage threshold.  A hard number of three votes may also work, if we're only concerned about a solo vote for "bad map" and logout.  Though that will need a special case for deadpop that has <3 voters/votes.

**Comment by SonixApache** [comment]
>It wouldn't be as big of a deal if all the other maps weren't objectively garbage. We don't have a lot of interesting shit that could be used in harmony with station layouts so the other maps simply don't have a point to them other than the fact that they have a different layout and that their layouts are inferior to box.

muh

box

**Comment by Killette2** [comment]
This shit happens all the time. Posting "are you mad because it just happened to you?" doesn't nullify this having the status of an issue. Especially when population is an issue, because a social game sucks when there's not enough people to be social with.

**Comment by Hoshi-chan** [comment]
The other maps aren't going anywhere. Changing the way voting works isn't going to change anything. If people hate the maps, we need to talk about particular issues with those maps, and how to correct those issues, not, "BOX ISN'T WINNING AND THAT'S WHY THE SERVER IS DEAD."

Changing voting isn't addressing the real problem, it's just brushing it under the rug.

**Comment by Exxion** [comment]
You're right, Hoshi, but fixing the maps is far harder than changing how voting works. That they *can* be fixed is not enough; someone actually has to fix them.

Since I haven't played in months and also don't really care anymore anyway, I'm not weighing in on whether or not weighted voting should be changed
But I will weigh in on *how*
If it is decided that maps with too few votes shouldn't be counted, it should be based on percentage rather than absolute number of votes. 1 vote in 20 is a very different thing from 1 vote in 5.

**Comment by Killette2** [comment]
Map quality is also dependent on player count. Nobody wants to play deff or bagel because 1 person voted for it when there's 10 people online. They're too fucking big for situations, and that's why people prefer meta and box. Make better small maps that aren't cramped and they'll get voted like the others do.

**Comment by Mothblocks** [comment]
I agree with the notion that weighted voting isn't bad, every other map just sucks really bad, but they'll never get fixed. In the meantime, changing voting seems like a good idea.

**Comment by SonixApache** [comment]
muh

box

**Comment by ShiftyRail** [comment]
:b:ox:b:a:b:ies

**Comment by Killette2** [comment]
I can't believe people are still too stupid to realize why box is the best map. You could hit a random department generator and these mongols will still love it.

**Comment by Riekland** [comment]
Name one(1) thing that box does better than meta that isn't the meme lobbies for medical and science

**Comment by Killette2** [comment]
While I already said that meta is a good map like box, I will say that it doesn't have a security disposals

**Comment by Gringonius** [comment]
Remove deff

**Comment by vampirebat74** [comment]
MUH DEFF MUH 4 VOTES seriously though I love deff and maint loot. Just add random maint loot to box please and ty.

**Comment by icantthinkofanameritenow** [comment]
@vampirebat74 Quite frankly, there's no reason not to throw a random loot spawner or two into every map's maintenance. Right now the only real rewards for exploring in there are a couple of silly gimmick costumes nobody ever uses.
