### ISSUE TITLE
Horror Form Bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18544]
(WEB REPORT BY: heroinehero007 REMOTE: 172.93.109.202:7777)
# Description
Transforming into horror form with genetic powers gave me more powers, made me instant collapse, and let me get stunned and meme'd on.
# Steps to Reproduce
Step 1) Transform as horror form with genetic powers
Step 2) Get meme'd on by crew
# What you Expected
Me memeing on the crew.
# What Actually Happened
I got memed on.

**Comment by Irradiation** [comment]
Perhaps this is karma for boring the entire deadchat with stealthsuccs through memesting, all-access and genetic powers.

**Comment by jknpj** [comment]
could be something with your TOO SWOLE TO CONTROL gene

**Comment by DamianX** [comment]
feature? It's how genetics works

**Comment by ghost** [comment]
If I had a take a guess, it was due to how a gene changing/activating has a chance of enabling other power-blocks that are in the range to be active, but are RNG inactive.  Sounds like a by-product of poorly conducted genetics research that the hulking out is triggering.  Similar to how you can get hit by your range active but RNG inactive round-start genes if you don't clean your genome before genetics research.  Doesn't sounds like a bug, just you screwing yourself.

but I could be wrong, so who knows.
