### ISSUE TITLE
Merge Mechanics and Robotics, Move the flatpack crap to R&D

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#18565]
Make a Mechanics/Roboticist engineering/science hybrid job focused into BUILDING pods, mechs, cyborgs and assemblies.

Move the upgrade/dupe crap to R&D and make it into an actual job focused in R&D instead of adding a tetris minigame to the gun printing machine.

**Comment by aceedex** [comment]
I dont like it. Mechanic is perfectly fine as a low responsibility job that can both fill in for engi and research if it needs to while also having some light responsibly. 

Theres no need to merge mechanics to other jobs and clump responsibilities in order to make RnD a little better. Hell, jusy remerge tetris

**Comment by jknpj** [comment]
>Mechanics don't work in the Mech Bay
>Mechanics don't work on Mechas

No sir, i don't like it.

**Comment by AutismSpider** [comment]
@aceedex never see mechanics do any type of engi work or fucking research for that matter

this job was a fucking mistake and piss poor port of the goon one

**Comment by RealestEstate** [comment]
@AutismSpider I wonder if that has anything to do woth the fact that they lack all the access to do either in its entirety

**Comment by jknpj** [comment]
@RealestEstate but they can setup the Singulo(but why would you do that), TEG, Solars AND they have their own fucking R&D setup. Also:

>access issue
>has glubbs

come on.

**Comment by RealestEstate** [comment]
right, but Solars and RnD are more tedious when done by mechanics. You got me on the TEG part, I don’t really touch engineering

**Comment by DamianX** [comment]
remove mechanics

**Comment by Reviire** [comment]
>Has glubbs

then he gets chloraled/TTVd/Tasered/Cargonia'd for breaking in

What if instead we expanded on the mechanics job, or even just merged it with engineering? Why does Science need everything?

**Comment by RealestEstate** [comment]
so is the issue that mechanics is a low responsibility job with too much reward? 
do you honestly think science will take up the burden of upgrading and building machines for the crew? You can barely get a person to respond to the RnD bell, forget about them rebuilding the cloning machine that just got struck by an immovable rod.
in my personal experience, the vast majority of players pick mechanic to build a spacepod and get a free hardsuit and they leave never to be seen again.  Then maybe some to greytide. There is a sizable amount of players that play it to actually improve workplaces and even setup autism projects that require both engi and sci access. mechanics isn't just the bridge between science and engineering, it's the bridge between autism and crew. Feel free to @ me about this.

**Comment by SonixApache** [comment]
MECHANICS IS THE OPS DEPARTMENT OF SCIENCE

**Comment by RealestEstate** [comment]
what's OPS?

**Comment by SonixApache** [comment]
Operations. The in-the-field section. The mechanics are the guys that actually leave the Science wing to repair / replace / upgrade machines and implement what R&D / Robotics shits out.

**Comment by aceedex** [comment]
Um sweety mechanic is anyone who maintains machinery mmmkay?

Shitpost aside, "I dont see them doing the thing" is a stupid argument. Its as stupid as remove assistant because they dont assist. Reminder that they also have responsability over tcomms, not that anyone ever goes in there. 

Aside from that, its also good that their access is this half abortion of sci and eng. Gives you just enough access to do emergency power setup/research if needed but doesnt fall into the pit of chemist where it might as well just be a MD alt title
