### ISSUE TITLE
Invisible horror forms with no clickable sprites? Easier than you may think...

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#18583]
1. be a changeling or become one
2. become a slime man
3. purchase horror form
4. use horror form as slime man
5. congrats! You're now invisible! Extensively tested on test server

**Comment by DamianX** [comment]
But wait! There's more!
![image](https://user-images.githubusercontent.com/6307265/41750383-ded4273c-75bb-11e8-8a12-5c41f362bedc.png)

**Comment by DamianX** [comment]
Nevermind that, that was due to unrelated testing.
I managed to get a horror ling with the base slimeman sprite somehow.

![image](https://user-images.githubusercontent.com/6307265/41750770-f28d939c-75bd-11e8-8745-2131261d4716.png)

That's a horror ling right there.
I don't get it, what's special about that species? Diona seems to work fine.

**Comment by Pathid** [comment]
Something to do with MULTICOLOR.

**Comment by Killette2** [comment]
@DamianX wrong order, you're supposed to slime then horror form.
You did horror form then slime
