### ISSUE TITLE
Module List for borg slowly vanished

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18999]
(WEB REPORT BY: kitfox88 REMOTE: 172.93.109.202:7777)
# Revision
89f1047f40cd9adc550b67c6fcd0a98db4f648b4

# Description
Went to pick a module as borg, selected janitor, nothing happened. Go to look again, janitor's gone. Canceld out, go back in, and repeat till the list is empty and I can't even open it anymore. Not sure what's up.
# Steps to Reproduce
Go to pick a module, get fucked out of it and stuck in AI upload lobby because of the new rules that you can't run around as an un-module borg

# What you Expected
To be useful

# What Actually Happened
NOT USEFUL

**Comment by Kitfox88** [comment]
More detailed explanation. Started the round, tried to go Janiborg. Nothing happened, open list again, no janiborg option. At that point I got stuck going down because byond is garbage so I closed the game window and reconnected. Still no janiborg. Closed list, reopened it, and then repeated as I watched the remaining modules vanish one by one with each closing and opening. No idea what specifically triggered it, maybe just a weird one off because of the server troubles going on these last rounds?

**Comment by Kitfox88** [comment]
Persisted through having my MMI yanked and body rebuilt before being reinserted, I have no idea what the fuck.

**Comment by Pathid** [comment]
@jknpj

**Comment by Kitfox88** [comment]
Persisted through mustard doing some admin shit to me, and the borg made mid-round for a posibrain had no module list to select from either.
>coders
>not even once

**Comment by Pathid** [comment]
https://github.com/vgstation-coders/vgstation13/pull/18982#discussion_r205788628

**Comment by jknpj** [comment]
I can only blame myself
