### ISSUE TITLE
Traitor AI happens too often

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#19024]
It undermines the sense of the AI being a tool, (a powerful and dangerous tool, but a tool) when it's going completely rogue all on its own a good percentage of the time, and in a stealthier way than a malf. Seems like it should be at the same level of restriction as traitor captain and traitor HoS. Last time a similar thing got discussed was #15289. I want to see what people think of this now.

**Comment by boy2mantwicethefam** [comment]
tbh AI is already too strong as it is against valids, when coupled with a functioning security department they're almost omnipresent, besides most ais are bored out of their minds and really wanna fuck with the crew

**Comment by DamianX** [comment]
Same thing I said a year ago: I'm totally okay with AIs having the same chance of becoming traitors as security.

**Comment by GeneralVeers25** [comment]
This is a good step in the right direction. The AI and its borgs are already a pivot for regular Traitors, and in most other round types as well. The AI already has an entire gamemode that revolves around it as an antagonist, so I don't see a problem with making roundstart Traitor AIs less frequent.

**Comment by vampirebat74** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEMOVE TATOR AI (or at least give it better checks than >greyshit has to scream in comms before paincrit from doorshock)

**Comment by iFlashYou** [comment]
@DamianX I tought this was already the case

**Comment by Matidash** [comment]
The way I see it, traitorAI is far too similar to malfAI which is constantly complained about as an extremely repetitive gamemode. Allowing it to occur this frequently in rounds that already have other antagonists antagonizing makes for some ungood times for the crew. Our antagonists tend to subvert the AI often enough for it to have a jolly plasmaflood murderbone even without the game giving them a golden ticket at the start.

**Comment by ghost** [comment]
I mean does it? How much is it traitor ai and how much of it is just autotraitor and a small antag pool? Better anonymous statistics would be a good place to start. I don't get it all that much in medpop but I'll start getting it somewhat commonly in lowpop and 2-3hr+ rounds when there's only a couple of us being eligible. I feel it's fine as is and it'd be more productive to tackle the issues that make traitor AI shit.

For the most part when it is rogue there's often clear warning signs along with checks and immunities against much of what it and its borgs can do that easily let you put it in the cuck shed. It's not surprising cause you rarely see a new AI made when malf is suspected for example. You say traitor AI's powerful and dangerous like somehow the rest of the crew aren't and there aren't major checks on what it can do without outing itself and what it can do against powergamers who routinely have the AI'sHateThis greatest hits mixtape.

@Matidash That comes from the extreme metagaming against the AI's actions, higher skill/trivia barrier, and generally small pool of ways to interact. Like has been said in other discussions, traitor AI with an "uplink" that would give it non-murderbone options to interact with the crew and station itself to create things for people to do with more 1:1 counterparts with legitimate carbon actions to reduce metagay checks would help break the cycle of 0 to AyoRealAIHunterHoursWhoUp prompting instablasma which prompts  0 to AyoRealAIHunterHoursWhoUp and so on...

**Comment by Pathid** [comment]
@SarahJohnson489 It's not so much that a tator AI is hard to kill. But it does seem to suck the rounds down into a samey "here we go again" hole where it's more or less normal for the AI to not care about laws at all. I can't back this up with any statistics but from just looking at the code and just the general feel of things, an AI with traitor enabled has the same chance of being made a traitor as an assistant or any other "generic" job. And this on top of the chance of getting purged/antimov'd/one-human-murderbone'd in the same roundtype.

>traitor AI with an "uplink" that would give it non-murderbone options to interact with the crew 

What if Malf was fixed to have more flexibility instead? What I'm wondering is, is there a real reason to have both Malf and Malf [Arrange] in the rotation here?

**Comment by SonixApache** [comment]
Is there a real reason to have revs, vamp, ling AND traitor in the rotation for greyshirts? Greyshirts do enough damage as-is *without* having to be antagonists. Maybe assistants should get a HoS-level chance of rolling antag.

**Comment by ghost** [comment]
If anything, traitor AI is the better of the two in terms of non-'bone productivity. Arguably the second worst thing about malf right behind the samey metagame shuck'n'jive is that it's difficult to be the often sole antagonist of the round within your well-known limitations, prepare for the inevitable battle of the metapowergamers without tipping your hand and avoid pseudo-extended because you're basically the only one(s) capable of doing anything. Worsened if you're unlucky and don't have a borg so with basically no conflict there's no hope of a borg within 2 hours so everything is entirely mindgames and the crew's willingness to deliberately not make themselves physically immune to anything you can do to them. Randoms know they aren't antagonists so there's a pretty large disincentive and obstacle to trying to get mutinies and otherwise spark actually significant conflicts where the malf roleplay would actually go somewhere. Versus traitor and auto where the AI has the potential to become a third faction or join either/(both) side(s) and rile things up with misinformation, framing, sabotage, red herrings, etc. You can actually have someone with a vested interest in moving your core, ever turning on your card's wireless or putting you back in for one reason or the other too versus malf's bleaker outlook and checks.

Hostage RP's ded but that's more of a general issue


As for what to do,
Recently, we got upload's split into a same-z and long-range version. If you're tired of playing upload tag, you can gamble on the roid or spend 6 minutes purge re-uploading from maint or wherever like usual, jetpacking to a space platform with it carded and a core kit, purge re-uploading it to whatever as a precaustion and stop by like once an hour to recharge it. Far from perfect yes but it'll help if it trickles into the meta since it's more effective than a head/sec that cares getting/printing the purge, asimov/freeform then the upload as part of his gearing up routine.

More random events such as breaking vendors/machines/weaker consoles-frying air alarm/comm/apc/fire alarm/etc wall machinery circuits-scrambling some area's airlock/alarm settings within weighted categories so eng/assistants have something to do infrequently, centcomm supply requests, AI cpu/cooldown analogs of those along with malf's announcements etc, able to load the intellicard into bots/mechs help provide things for people to do and respond to, Wall rot gaining spread and eventually deconstructing the wall then the girder if ignored long enough, announcements, general area-wide controls for faster air alarm modification with updates to an alarm's vents/scrubbers affecting the area's, an area threshold tab feeding changes back to the sub-area alarms or just a lengthy firelock override hack. updating the mule destination ui to a scrolling dropdown/menu or something so that it's easier to drive them and they aren't breaking when multiple cargo pda carts are active or whatever causes them to spaz. More destination beacons in general. More modules for borgs that provide the potential for shenanigans. While people thirsty for corpses will never go away, providing more ways to engage with the crew for a back and forth is a step in the right direction to help provide alternatives so it's easier to be less of a shit that smashes dat motherfuckin' blasma

Don't have a road for the no-borg, unstoppable remote robo control/bangerbrazzer'd/ion/blinder-flash powder+flasher holocaust in this meta of heavily over-granted access, and how to punish the AI without effectively taking it out of the round when they catch it if it goes too hard and triggers people. The proposed and passed nerfs elsewhere that make AI proofing an area actually effective can help but like configging alarms to meme with co2/n2o/near-harmless knockdown nuisances, people'd rather just be done with it than spend 15 minutes wrestling with it.

**Comment by Pathid** [comment]
How easy Malf is to meta and the lack of other antagonists along with it are definitely issues worth addressing. Although, for all I know the meta issues with AI Malfunction not occurring with other antagonists are going to be fixed with the always-mixed antag datums stuff, whenever that is.

As for punishing bad AIs without taking them out of the round, I feel like just physically moving the core and putting it somewhere public like the bar is underrated. (While putting manual valves on atmos, what have you.)

**Comment by Chazach** [comment]
What if, like security, they couldn't get roundstart antag. Most people feel like the round is a write off if AI is ragu from the very start, although much less so than malf since there are other players in the game, so to speak.
Also @SarahJohnson489 >For the most part when it is rogue there's often clear warning signs along with checks
There is literally no checks on tatorAI, and which how nasty and verbal most AIs are it leads to situations where sec spaces the NT def AI rather then dealing with the still potential bullshit that it might pull. I agree though that being unable to punish the AI and gunking being the most easily convenient and safe form of action creates this whole stale mess.

**Comment by SonixApache** [comment]
Security *can* get roundstart antag, though, right? Just low-ass chance?

**Comment by ShiftyRail** [comment]
Since vampire sec is (sadly) a thing, Security can be a roundstart antagonist.
