### ISSUE TITLE
Revisiting Bee Anger Mechanics

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#19023]
As per #18819 getting merged several of us (I believe) agreed that we would like to talk about arranging a better way to get bees angry at people other than yourself. Some ideas thrown around:
* Put them into a bee grenade like a jar that makes them angry at anyone wherever it smashes
* Just make them come out angry at everyone when net dumped
* Make them get angry at anyone when sprayed with plant-b-gone (watered down toxin)

Tagging @DeityLink and @Hugh-G-Rection for visibility

**Comment by DeityLink** [comment]
>Just make them come out angry at everyone when net dumped

doesn't #18819 do just that? I remember specifically pointing which line to comment out to allow for that.

**Comment by Kurfursten** [comment]
No, although I was open to the idea and thought it was a pretty good one, I didn't want to make things even less atomic. Then Hugh brought up that dumping bees so that they swarm onto your own face is actually useful in some situations and he doesn't want it to go.

I'd be happy to comment the lines if people like that idea. I'd PR it myself.

**Comment by spoonylove** [comment]
I think everyone could get behind weaponized bees in grenades.  sort of like viscerators. Maybe 1 beaker honey 1 jar bees or something.

**Comment by flagzzzz** [comment]
There is a bee-nade already in game, it just doesn't have a recipe as far as I can tell. You can get it from an exotic space weapon spawner though.
https://github.com/vgstation-coders/vgstation13/blob/41b41426fd67845e0d9558619c41573d3a97a45a/code/game/objects/items/weapons/grenades/spawnergrenade.dm#L77-L82

**Comment by Hugh-G-Rection** [comment]
Opening a bee-net makes all the bees inside angry at you, which surrounds you with a protective bee barrier and you become The Pain and are immune to everything but grenades and flamethrowers. The cloud blocks all projectiles, and most attempts to harm you will only sick your bees on your attacker. _GoodLuckI'mBehind7000Bees.png_ has saved my life a few times and it's hilarious. 

That said, as one of like 6 people who dabble in extreme apiaristry, there are some changes that could make bees a better and more amusing time sink. Smacking someone with a bee net should have the same effect as the bee briefcase, dumps them with aggro on the person you smacked instead of you. Bee jar grenade would be amazing so long as you can dump a fair amount into it. Bees might also benefit from better aggro memory, so when your bee cloud kills an attacker they can re-converge on you without the need to piss them off all over again.
https://giant.gfycat.com/FantasticSnarlingLeafbird.webm

Please make the bee grenade work with a normal grenade assembly, as a proximity mine would be great since you can no longer leave massive angry bee clouds in maintenance as homeless bees now die out after a while. Would be different if you could get their toxicity so high that they survive on fury alone: **Local Bee too angry to die**

Other thoughts: 
Mousetrap beetrap in box labeled "For the Clown"
Stuffing crates with bees, wrapping and gifting them to people that rage on anyone who opens it. I want to mail the HoS angry bees.
Anyone sprayed/injected with royal jelly become permanent target for angry bees 
Ensuring permanent anger in bees so extinguisher doesn't shut you down so fast
Alternatively let me replace water in extinguishers with more angry bees
