### ISSUE TITLE
Roidstation gulag isn't radiation-shielded

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#19207]
a3ee0e3e79f7954bf39e607807eab2ee40dd541e 

What it says on the tin.

**Comment by SGuivenne** [comment]
I fail to see the problem.

**Comment by brndd** [comment]
Radstorm code needs to be upgraded so that everything under /area/mine and /area/prison are radproofed. This is the most elegant solution, as otherwise a dozen areas would have to be added to it. @DamianX suggested using ispath() to check for this, but I could not get it to work. It should have no effect on existing map, because as far as I can tell on all the existing maps those kinds of areas are not used on Z-1.

Here's what I tried:
```
    var/safe_paths = list(
        /area/prison,
        /area/mine, //for roidstation
    )
```

```
/datum/event/radiation_storm/proc/is_safe_zone(var/area/A)
    for(var/szt in safe_zones)
        if(istype(A, szt))
            return 1
    for(var/spt in safe_paths)
        if(ispath(A, spt))
            return 1
    return 0
```
