### ISSUE TITLE
Roidstation waste line bugs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19254]
(WEB REPORT BY: filterfish REMOTE: 172.93.109.202:7777)
# Revision
c1074beca77f91602ad6e3f03607b2d963d50c28

# Description
The waste line spontaneously produces N2 and O2.  I've deduced that this is the result of some sort of bug coming from the portable scrubbers and air pumps in atmospherics (the connectors are hooked up backwards).
# Steps to Reproduce
Sign in Roidstation, check the waste line pipe meter.  Try disconnecting the waste line to the portable scrubbers in atmospherics to confirm.
# What you Expected
A nearly empty waste line
# What Actually Happened
Magic Air coming from the portable pumps.

**Comment by brndd** [comment]
Looks like something about the pipes connects supply and waste together, which is... quite problematic. They're all layered, so it should never have happened. It appears it was caused by two layered manifolds on top of each other. I've moved the piping around and it should be fixed in the next update.
