### ISSUE TITLE
How do we adjust/remove kill&clone?

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#19369]
related: #12585

Here's the idea I had, copypasta'd from the discord ideaguys channel when I came up with it at 4 at night

![shittyhandwriting](https://user-images.githubusercontent.com/8468269/44221465-e33bcb80-a181-11e8-8fe9-cc20aa9ac100.png)

So my idea is that the biogen makes and stores pattern bodies automatically from meat
Up to 5 bodies
And each body takes like, 3/2/1 minute(s) to make, depending on upgrades
And these bodies are good, no need for ryetalin afterwards -- 
but you could use a genetics disk to pre-equip them with powers or disabilities

These bodies would also be the source of the 'activate braindead body for respawn' function
moving them to the gene modder takes a few secs
Players can be scanned with the DNA scanner + central computer, which takes a bit (9/6/3 seconds?)
it scans their genetic structure and memory seperately
so maybe allow for husks to be memscanned but not genescanned
Applying memory and/or genetics is done in the gene modder and takes 3/2/1 minute(s).
slight chance of bullshit happening with gene modding on basic parts, much like current cloner
Overworking /EMPing any of the machines results in glitches such as minor genetical defects (corrupted clone records!)
emagging unlocks hidden functions such as vox pox /body part selection
gene modder doubles as a brain transference machine -- throw in body, apply memory, boom bodyjacked
modular gene modders, just like with R&D machines, so you can clone in parallel with upgrades

need to converse with medbay core to see if it's fair and converse with mins / playerbase to see if straight-up human respawning isn't too arcadey/gay

**Comment by Caboozles** [comment]
If you want to make speedcloning not a thing, why not just target speedcloning itself?
The problem is that cloning takes at most a minute to get back to full health with decent cryo and a working medbay.

Just triple the time it takes to work, allow upgrades to speed the time up, and prevent removing a cloned body before it's ready, unless you want a goopy mess that's missing arms/legs.

**Comment by DamianX** [comment]
that means medical is the same snoozefest except it takes longer
:clap:

**Comment by Accipitermaris** [comment]
I am in favor of removing cloning in favor of gated respawns as generation 2 pod people crew. Not sure whether there is any inherent interest in that. That said it would require something like ZUHmed otherwise headswapping/monkey-un-monkey would be the new cloning, and I also don't want to indirectly get rid of fun frankenstein projects so were this done it would require someone who is knowledgeable in every aspect of medbay at the helm so that the ability to turn someone into a frankenstein among other things would be preserved.

**Comment by Exxion** [comment]
[spoiler]just remove cryo[/spoiler]

**Comment by Irradiation** [comment]
Before we dabble into the dark and arcane art of [Touching cloning and medbay], let's take a step back and examine why people (speed)(kill and)clone, shall we? Helps to put probems into perspective.

**Why would I clone a corpse instead of performing hardcore surgery?**
- The corpse is too damaged to perform hardcore surgery (Read: An enormous amount of damage that can't be solved by removing limbs and defibbing).
     -Seeing a corpse come in with almost all his blood drained and a ton of brute caused from 
     _harmdragging_ is a demoralizing.
- I don't have the time to concentrate on a single _dead_ patient.
     -I don't have upgraded surgery tools to turn a 2-10 minutes procedure into a 15 seconds - 2 minute 
      procedure.
     -I can't be arsed to do hardcore surgery or don't know how to perform hardcore surgery (Read: a big 
      portion of medbay people and bystanders).

**Why would I speedclone (or kill & clone)?**
- Speedcloning is faster than surgery in a majority of cases.
- I don't have the time.
   -The wild ride is going in full swing. Better hurry up the fuck up. I don't want to keep people out of the 
    game for too long (Meta reason, the player can't IC complain about cloning being too slow).
- I'm lazy. (General kill & clone idea)
    -I COULD fix those multiple broken bones and internal organs & bleeding. But I don't want to or 
     (speed)cloning would still end up being faster than doing surgery.

**If you have any extra reasons that I haven't mentioned, please post a comment about them.**

**Comment by jknpj** [comment]
Remove the cloning console and replace it with T.E.T.R.I.S., for every cleared line the clone gets an organ.

**Comment by kilozombie** [comment]
I am generally a fan of the idea in OP, in which you _can_ kill and clone some folks if you're too lazy, but you'll be fucking yourself down the line when the wild ride goes into full swing. If you clone everyone it'll take forever, but if you clone really fucked up patients while healing the rest with defib and surgery, you'll manage to get through it. I like the idea of having to juggle "can I get this done really quickly without cloning" and "will i get a patient that's even worse who needs cloning" together.

I think the timing should be weighted more towards creating bodies than actually transferring minds-- a small storage capacity and slow creation rate of bodies (3 max, 5 minutes per?) would really cut down on how much cloning you can do, even in a lowpop round.

There should probably be some way of making that scale as there are more crew, though maybe it should only be a roundstart variable so that late-round wild ride is always wild. _Nanotrasen has granted your small crew a low-speed body replicator, as few losses are expected._ or _Nanotrasen has granted your oversized crew a high-speed body replicator, as more losses are expected._ It shouldn't be a massive change, but it'd be a nice touch.

**Comment by Riekland** [comment]
There is one(1) single thing that would make cloning less attractive

Just make clones come out missing limbs

random amounts, maybe just a foot, maybe both arms, maybe nothing

**Comment by SonixApache** [comment]
@Caboozles I want to actually add mechanics rather than just removing parts that work already. In my scenario "Speedcloning" would be writing someone's memory to a template body without modding its UI. Shouldn't take very long, even without upgrades.
@Accipitermaris Well, this machine could do that as well, but I think cloning is a pretty okay mechanic as-is.
@Irradiation so tl;dr "i kill&clone because it is literally always faster than anything but giving people a single pill"
This tries to solve that by making cloning a slower process, and maybe even gives medbay some more to do in downtime.
@jknpj please code it
@kilozombie scalability is definitely something I would want for this. Being able to link multiple sets of biogenerators and gene modders to the central computer for parallel cloning would be a must.
@Riekland think i missed this;
- Biogen generates bodies starting from the brain, then the head, torso, heart, lungs, etc etc ending with the feet
- Biogen has to be adjacent to a Gene modder to supply bodies automatically

Killing speedcloning by just saying "ha ha random limb loss" would be annoying as fuck.

**Comment by kilozombie** [comment]
The question seems to be "how do we make reviving people tougher and give an incentive to do surgery and defib without making the end result radically different for the dead person" and I like the idea in the OP for that purpose.

**Comment by DrSnips** [comment]
One big issue I have right now is toxin damage. Currently there is no way to bring someone back from major tox because chems dont work on the dead. You can deal with burn and brute by chopping bad limbs off (if possible so if its all on the torso or similar it doesnt apply) or using adv med kits and oxy is solved on defib. Cloning or brain swapping is the only way to fix that issue. Brainswap is a super long time because surgery so it's not very desireable when the body has 200 tox.

**Comment by DrSnips** [comment]
The speedclone issue is to just remove the ID swipe feature to eject. Boom done plain and simple. If you try to flick the power or take apart the cloner to force eject it just gives the person 30 heart damage (killing them) and the usual declone.

**Comment by DrSnips** [comment]
As for my take on solving the issue of killclone make it more resource intensive. Similar to the idea in the OP the cloner is now just a fancy brainswapper. It takes a whole body to make a whole body this would make medbay have to consider if they want to use up their resources to clone someone rather than 20 clones from one person via synthmeat production. Medical can use monkeymen to feed to the cloner so some mapping might need to change to give them less monkeycube boxes in genetics if any. You could also consume dead bodies BUT they give you less "points" toward a clone so only people at 100 health are worth 100 points. A person at 0% is worth 50 points and a person at -100% is worth 0 the points can be played with later. So a body with even 1 brute isnt enough to make a full clone you need to 100 points to clone. This would require the least amount of change possible in terms of how the cloner works currently imo as it's just changing what you feed the cloner.

**Comment by Coxswain-Navigator** [comment]
You could "kill" speedcloning by making it require more steps to prepare, as it is right now the most you can do to upgrade a cloner or set it up is put some meat and maybe upgrade the machines. Perhaps this could be fixed by giving the geneticist an actual medbay-related job to do; setting up the cloner. Maybe make it so that it has to be loaded up with disks (supplied at roundstart), meat, chemicals that can speed it up (similar to cryo but different chems) so that when everything's said and done, speedcloning will only really be possible with a fully upgraded cloner. Maybe, as previously mentioned make the ID eject function kill the patient unless the cloner's been upgraded.

**Comment by Arthurdentist** [comment]
Novel idea but how about not nerfing cloning and instead offering other incentives for people to do non-revival surgery. Unique body mods, augmentations and the like.

As someone who observes a lot of rounds, I really don't think kill and clone is as common as people claim it is.

**Comment by spoonylove** [comment]
Making surgery simplified is the way to do this. Maybe something like having all the necessary tools present allows you to operate on someone in a fixed amount of time. Maybe have this time sped up if the person is actually medbay staff( maybe something like how CM does it, but lets no do things like restrict pill bottles). Increased time with fuck ups if ghetto surgery. Rather than fiddle with grabbing each tool its just one process that requires only the necessary tools. Have holo tools be able to cover all the tools as they already do and speed up the process. Of course the more upgraded tools the faster. Maybe have some new chems that speed up the process by giving you "focus" maybe this can be a replacement effect for hyperzine so as to remove the abuse it gets from people on station. Im talking the implementation of some new systems, but it would see people doing more doctoring than murdering then cloning to fix a broken hand. 

If I understand the The initial idea for cloning, it sounds like the paranoia rpg style cloning. Crew clone back ups that respawn in a fixed amount of time from the cloners after death. Adjustable with upgrades as mentioned. This kind of goes hand in hand with genetics and paranoia as clones would have mutant powers. Maybe genetics can get a rework to,through the shift, make better and better clones, eventually with genetic powers. Initial clones can start off shitty and require some fixing with cryo. But the idea is. Clones would take longer to spawn than fixing people with surgery.

**Comment by strawberrytan** [comment]
Here's my shitty ideaguys idea inspired by the concept of growing the body before inserting the player's mind you're working with

![deusex-2008-01-25-04-29-13-74](https://user-images.githubusercontent.com/21017309/44270062-ea89d480-a268-11e8-855f-89a26c9b13c7.png)

The cloner has an interface where you build-a-body with the pieces. Head, Torso, Arms, Legs and the associated organs
There's a quick clone option, like quick robot in the robotics exofab. Orders up all the limbs and prints it.

Manually selecting the pieces is also an option. The cloner can be loaded with biomass to print basic organic versions of everything. It can also be loaded with upgraded organs and robotic limbs, wooden limbs (and maybe organic ones if you have them lying around?) to use these in lieu of the cloner printing them and cut down on how long it takes to produce a full body.

**Comment by Inorien** [comment]
There was a post in the thread about the surgery computer being turned into some computer assisted surgery thing, while reading it I imagined an interface similar to the picture above
The left side would have targettable body regions (with perhaps local damage appearing on upgrade) and right side would have tool selection. Rather than hunting down the tool on the surgery table and flipping hands, you just do the whole operation from one handy dandy interface 
its the future bruh why wouldn't they have surgery machines, we have them here already today now on earth

**Comment by tayachiya** [comment]
Why not have both?
Make the table an R&D item or mechanics upgrade for the table/computer itself
That way you can keep early tools and have more advanced technology for doctor later on

**Comment by DrSnips** [comment]
>Throw it in as an RnD thing

You would be back at square one then. Since we already have the thing(s) to make surgery faster there but obviously that's not changing anything currently.

**Comment by Blithering** [comment]
I like ArthurDentist's idea, rather than directly nerfing cloning make more things that would make people want to keep their original bodies over a freshly cloned one
