### ISSUE TITLE
More bagel feedback

### ISSUE THREAD

**Issue by bathosbathtime** [d3athrow/vgstation13#19394]
Building off of https://github.com/vgstation-coders/vgstation13/issues/17884 please add more if you have any
- This chapel looks awful:
![chapel](https://cdn.discordapp.com/attachments/245868847926607873/480483521106935849/awfulchapel.PNG)
- This is bad but not as bad:
![dorms](https://cdn.discordapp.com/attachments/245868847926607873/480483615269060618/awfuldorms.PNG)
- Why is the paremedic area hiding away and not attached to the hallway (I'd switch around medbay storage, paramedic's office, and genetics myself):
![paramedic](https://cdn.discordapp.com/attachments/245868847926607873/480484642131279902/awfulparamedicoffice.PNG)
- podbay still behind mechanic's office (if this is a feature it is an awful one):
![podbay](https://cdn.discordapp.com/attachments/245868847926607873/480485738740318208/awfulpodbay.PNG)
- Vending machines are all empty (I am aware it is a feature, it is a bad one)
- SME and AME wired to protaSMESes and not the main SMESes (I am aware it is a feature, it is a bad one)
- Empty space is still everywhere
- hallways are so long it takes forever to navigate the station
- So much shit on the inside of the station hallway where the bagel hole should be that it doesn't even look like a bagel
- AI core is filled cold pure nitrogen (I am aware it is a feature, it is a bad one)
- Medbay and telecomms are right next to each other making a super easy bombing target

**Comment by bathosbathtime** [comment]
To elaborate:
Chapel:
Large waste of space, two lobbies, has three main rooms where most maps get by with one

Dorms:
Large waste of space, wood which is garish, rightmost room is redundant with the sitting area by the fireplace, doesn't feel like any design went into it just thrown down

Podbay:
Why does it only have three flaps just add one more tile to the room, why does fluff like the chapel and the dorms have too much room but some semi-used rooms like podbay and the paramedic's office feel so compacted.  Also being gated behind mechanic access is bad.

**Comment by Caboozles** [comment]
Even as someone who plays mechanics, the access is pretty unnecessary, and just invites break-ins.

The power flow of engineering is totally fucked, especially since power from the southern grid doesn't even reach the northern grid. If you don't both shard and singulo, you'll have virtually no power in the top, or atmos.
Furthermore, the way power is configured by default you have to go out of your way to wire it, or hook the SMES in a fairly illogical manner. Simply put, unless you're really experienced with bagel's grid, you're experiencing a nightmare of a power system. That's even putting aside how dramatically short the power lasts on Bagel.

**Comment by Kurfursten** [comment]
The real problem with Bagel is that its size calls for a lot more stuff than a station needs. That's why the chapel and dorms have bloated outwards like a blob. There are basically two solutions to this:

1. Reasonable Solution: Reduce size of bloat areas and find new stuff to put there, even if it's just maint or something.

2. Best But Impractical Solution: Reduce the size of the entire station and make better use of space. This would require basically an entire remap.

One key problem is that all the locations on the map are a reference to the original Donut station, for example the chapel in the top right, bridge below it, brig below that. In practice though it's probably not the best way to organize things so that the whole donut gets used. "Useful" rooms tend to be on bottom half and "places I only go when I need to escape or get cargo pizza" are on the top of the station.

I don't necessarily consider the travel time itself a big problem since we could add goon-like one-location teleporters. And I don't mind fixing some of this stuff myself - the basics, like fixing the chapel and wire grids.

**Comment by beesil** [comment]
More feedback.

- Warden can't watch cells and front desk at the same time.
- Bridge has two (2!) conference rooms, neither of which are ever used.
- Maint is choppy, unconnected, and unevenly placed (see: loads of maint under medbay/bar, but barely any on the top right of the map).
- Aforementioned podbay is inaccessible if you don't have maint access.
- Bar, kitchen and theatre could use some love.
- Medbay is REALLY long, easy fix would be trimming chemistry down, then swapping the morgue and breakroom so cryo, genetics, and the morgue are closer together (and also connecting the morgue to the central hall), but it could probably use a complete rework.

I'd be interested to take a shot at some of it, if no one else is.

**Comment by Kurfursten** [comment]
Supposedly someone in the thread is already working on a slim down. If it's someone here (Cpt Wad?) I'd like to know so we can review in the process. I do think 90% of the issues can be traced back to that poor spacing issue that I mentioned, whether it's choppy maint, extra conference rooms, etc.

I will say that I don't necessarily think the bar/kitchen/theater area is bad though. Why don't you elaborate?

**Comment by beesil** [comment]
Like you said, most of the issue that it's oddly shaped and spaced, which discourages bartenders to renovate and do gimmick bars. Theatre is out of the way, backroom is huge (and dark, iirc). Hydroponics hurts my eyes and doesn't have any privacy (unless you count the zoo, which is visible from maint). 

To fix it, I'd trim the left and top walls of the kitchen inwards, turn the bottom part of the bar into the theatre, and redo a smaller theatre backroom where the old theatre was. As well as give hydro a new paint job and a private backroom.

**Comment by Riekland** [comment]
I'll add some thoughts and complaints

I like the port area of botany, but the starboard area serves no real purpose given the amount of space we have around the trays and the big fuckoff garden dome. It also means that if you're trying to talk to a botanist, they need to come out and stop whatever they're doing, and it can be difficult to get someone's attention if they're busy working and you can't hail them or whatever
![screenshot_2018-08-19 maprender4-3 png png image 2048 x 2048 pixels](https://user-images.githubusercontent.com/9220789/44310758-95b69d00-a3d3-11e8-902e-bb9ae5374c67.png)

Why is there a connecting corridor here? What purpose do those three extra tiles serve? I would also move the surgery computer to the left of the table, so that people taking a patient to overflow have two tiles to shuffle through, instead of just one.
![screenshot_2018-08-19 maprender4-2 png png image 2048 x 2048 pixels - scaled 33](https://user-images.githubusercontent.com/9220789/44310771-e8905480-a3d3-11e8-963c-500249860ab6.png)

The mechanics office really needs a chunk cut off the top right. There's a massive amount of space in the office and it makes the main hall uncomfortably tight, especially with it being placed next to an outsized art and tool storage. I really do want to draw attention to the fact that the main hall(!) goes to an effective two tile width due to the vending machines, O2 locker, and the mechanics office.
![screenshot_2018-08-19 maprender4-3 png png image 2048 x 2048 pixels 1](https://user-images.githubusercontent.com/9220789/44310789-34db9480-a3d4-11e8-8900-1cc91f84d5de.png)

The same sort of problem is on the aft starboard corner, where the two storage rooms are just too wide and make what should feel like a curve into a right angled corridor.
![screenshot_2018-08-19 maprender4-4 png png image 2048 x 2048 pixels](https://user-images.githubusercontent.com/9220789/44310899-de6f5580-a3d5-11e8-9528-5ca3a5bbd521.png)


This is the theatre backroom, not the stage - it's huge and empty for no real reason. The little "bedroom" really just looks unfinished, and it's an extra 3x5 area poking out and making the maint excessively far away from the main hall.
![screenshot_2018-08-19 maprender4-3 png png image 2048 x 2048 pixels 3](https://user-images.githubusercontent.com/9220789/44310815-8f74f080-a3d4-11e8-83c2-6170c0cffb9b.png)

The brig is big, ugly, and has corridors that don't need to be there at all. Example, why is the medical room not just a few feet to port?
![screenshot_2018-08-19 maprender4-5 png png image 2048 x 2048 pixels](https://user-images.githubusercontent.com/9220789/44310879-92bcac00-a3d5-11e8-8f28-7b7af88d591f.png)
