### ISSUE TITLE
Chameleon Projector acting fucky

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19540]
(WEB REPORT BY: kharkov72 REMOTE: 172.93.109.202:7777)
# Revision
4a8bd3e7ae934b0fab2c1454c643ae426a9f8b0d

# Description
Turns out, if you scan someone with a chameleon projector, and their sprite/condition changes, your scanned sprite changes too. For example, I could see that Kaylie had c4 on them, even though when I scanned them they did not.

# Steps to Reproduce
-Scan some fuckboy with the projector
-Do something to them
-Use the projector
-Witness the weird shit

# What you Expected
Normal Kaylie
# What Actually Happened
Kaylie with c4, then nude Kaylie

**Comment by Exxion** [comment]
Apparently you can alias `overlays` despite the fact that it's a fake internal list, most of which are implicitly copied when you try to do so
If what I just said isn't wrong, then the fix is to add `.Copy()` to the end of this line:
https://github.com/vgstation-coders/vgstation13/blob/006ce38c3d023872c1c9594087ce8348b814184e/code/game/objects/items/devices/chameleonproj.dm#L54
