### ISSUE TITLE
Starscreen doesn't work as intended

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19558]
(WEB REPORT BY: reind REMOTE: 172.93.109.202:7777)
# Revision
c81d9c4895933ddaf0f457991246f18b572b203d

# Description
Starscreen radius when set above 70m straight up stops working, doesn't even try to charge, tested it with 3 capacitors and the SME wired to grid.

# Steps to Reproduce
Set up shield, set rad to 72m and above and watch it do absolutely nothing.

# What you Expected
I expected it to work.

# What Actually Happened
It didn't work.

**Comment by SonixApache** [comment]
starscreens can only take power from one capacitor, which takes power from the APC
capacitors are very limited in how much power they can provide
not to mention that the hull one doesn't actually protect against meaty whores since the explosions pass through the shield and damage whatever it is protecting
needs rework, etc
