### ISSUE TITLE
Can't remove power cells from Broken APCs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19597]
(WEB REPORT BY: subs455 REMOTE: 172.93.109.202:7777)
# Revision
90f2f90d2e60e2c58c789cd5d6307c6a4ce26012

# Description
I was trying to fix an broken APC, and the battery wouldnt come out, making it impossible to fix.

Me and Soose tried to troubleshoot it but he ended up just deleting it so i could make a new APC from scratch.
# Steps to Reproduce
Remove the broken APC cover with a Crowbar. The powercell cant be removed.
# What you Expected
The powercell to come out, allowing me access to the Circuit Board.
# What Actually Happened
The battery wouldn't come out.

**Comment by Lunstra** [comment]
Had this happen a few days ago too and the only solution found was indeed to delete the APC so a new one could be rebuilt.

**Comment by ProfanedBane** [comment]
I'll have a look today.

**Comment by ProfanedBane** [comment]
If I'm reading the ahelp exchange right, you managed to get the cell out but still couldn't fully remove the circuitry?
I'm having a feeling that this is a wiki error, because the ACTUAL deconstruction method is >remove cell>screwdriver electronics>crowbar plating in front of apc>wirecutters on the apc>crowbar circuitry out>weld the frame

I've been unable to reproduce being unable to remove a cell in several conditions, including the cell itself being deleted.

**Comment by Sooose** [comment]
If I remember correctly they didn't remove the cell, they swapped it with another one which you can do via clicking an APC with a cell in hand when there is already one inside.

**Comment by SonixApache** [comment]
I thought I caused this issue with #19040, but I couldn't reproduce it.
