### ISSUE TITLE
AI Announcments are Gunked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19636]
(WEB REPORT BY: jazzstringz REMOTE: 172.93.109.202:7777)
# Revision
fa3b0fdcd569387784672604e389a540cbe17c01

# Description
AI Announcement Voice Clips play out of order
# Steps to Reproduce
>be AI
>Type announcement [i.e. Wizards are Shit Lynch He]
>play
>listen [i.e. Shit He Lynch are Wizards]
# What you Expected
Word audio to be played in the order typed
# What Actually Happened
Word audio played in whatever the fuck order the serb wants

**Comment by SGuivenne** [comment]
We just got a weird ass one for level 7 biohazard, it said the entire thing except the 7, which randomly went to the end of the thing.  Someone fucked VOX up royally.

**Comment by strawberrytan** [comment]
I played AI recently and tried out announcements

However it is fucked up is at least consistent - if you have multiples of the same audio it'll do it in sequence (eg you have 3 doops in your message they will play consecutively not randomly throughout)

I don't think it's alphabetical but it might be, clown death at captain played as at captain clown death

**Comment by Exxion** [comment]
Oh god I think this is a BYOND change
The VOX system sends the words to be played in order, but with no delay, and I guess BYOND changed so that it plays sounds received at the same time in sorted order instead of order sent
This would be very similar to the visibility issues that recently cropped up due to a BYOND update

I *think* this could be fixed by just adding a `sleep(1)` into the loop that sends the sounds, but that's ugly

**Comment by Exxion** [comment]
I can't reproduce this locally, so I can't really verify the above statement right now

**Comment by SGuivenne** [comment]
Definitely heard it consistently with biohazard alerts.

**Comment by SonixApache** [comment]
I just ran into this issue.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Does this still happen? You'd think we would have heard of it again

**Comment by DamianX** [comment]
works on MY machine
