### ISSUE TITLE
Horrific 512 bug that seems to be byond side but also incomprehensibly ONLY occurs on this server.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19706]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
27033397535792b994d5877c9ada8bb6be3708a4

# Description

In the unstable byond version I've had an occasional (but when it occurs persistant) bug where left clicking on objects in the visible map completely shits itself and stops working.  This is absolutely gamebreaking and seems to persist between rounds, cache clearings, and downgrading and upgrading.

Previously I was able to fix it via downgrading back to 511 before SOMEONE made it so that is no longer possible.

The fucked thing with this is, when I have an item in my inventory I am fully capable of left click operations, its explicitly map tiles and mobs that don't allow it.  I can also shoot so long as the tile is a wall or not visible.  This bug does not persist when I then go to bagil or CM so its not just my client catching fire or my left mouse button dying.

Even more oddly, as a ghost I can then left click things again, I just cant use my haunt abilities from the screen or toggle light switches.
# Steps to Reproduce

Be on 512 and get incredibly unlucky
# What you Expected

To have an actual playable gaming experiene
# What Actually Happened

An unironical gamebreaking bug.

**Comment by SGuivenne** [comment]
of note, as a ghost I can use VERY specific consoles by left click, but not others.  

Right click functionality always works and the graphics continue to update.  This is not the graphics freeze bug people talk about.

**Comment by Exxion** [comment]
This is especially bizarre because it sounds like the circumstances in which it works are inconsistent.
You can click on inventory items and obscured/fully-dark tiles, which are screen objects
But you can't click on haunt, which is a screen object, but you *can* click on most map objects as a ghost
?????

EDIT: Also since when does 511 not work? We were trying to keep compatibility with it until the screenfreeze was fully fixed.

**Comment by SGuivenne** [comment]
@Exxion since about 2-3 weeks ago ish?  I assumed it was an intended thing, but 511 is definitely incompatible now.   All I know is the first time I tried troubleshooting it with an admin helping it may have literally driven them to drink.

Even fucking weirder, I just joined the server and am NOT having it now.  I gave up fixing it last night.

**Comment by Exxion** [comment]
If it ever happens again, ping me in either Discord (or get someone else to if you're not in them)
Sounds like a fascinating bug

**Comment by SGuivenne** [comment]
Sounds like a fascinating bug is one of those terms that scares me on some deep visceral level coming from a coder here.

**Comment by Chazach** [comment]
radial menus require 512 even though we havent implemented any of them yet

**Comment by SGuivenne** [comment]
@Chazach so youre saying we cant join with an earlier client because byond considers that there MIGHT be features newer clients can't use, regardless of whether or not they are actually present... That sounds just idiotic enough to be a byond feature.

**Comment by Chazach** [comment]
@SGuivenne we ported em in #19599

**Comment by Exxion** [comment]
Well I guess if Pomf himself did it, we can start using 512 features
Thank fuck

**Comment by nervere** [comment]
no longer an issue
