### ISSUE TITLE
Large scale crashing being reported

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19821]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
f7ecef48b833d3fcdd9476a79d067effcaa682ec

# Description

Crashes are being reported all over box station for reasons that aren't clear.  One of the big troublespots is the hallway northeast of the bridge, however. 
# Steps to Reproduce

Prematurely merge Role Datums, suffer.
# What you Expected

Functional gameplay

# What Actually Happened

OH GOD EVERYTHING IS FIRE PANIC

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I'm fairly confident the cause of this was a shooting practice target dummy that had a shitton of bulletmarks in it
Probably too many overlays for BYOND to handle
After admemes deleted it I stopped crashing entirely and OOC went quiet about it

**Comment by SGuivenne** [comment]
PROBABLY should arbitrarily make targets fall apart after a certain point.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Do the thing every shooter since the dawn of time has done and limit the bulletholes to 10 at a time, new ones delete the oldest one

**Comment by DeityLink** [comment]
>Steps to Reproduce
>"Prematurely merge Role Datums, suffer."
How about you at least tell us which station it's happening on you piece of shit!

t. QA tester is my dayjob and steps to reproduce are serious business

**Comment by DeityLink** [comment]
Funny how people assume this is caused by datums.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I mean it's not entirely unreasonable to think the biggest refactor of the year might be the cause

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Still getting some crashing even with no mass overlays, might not be the only cause

**Comment by SGuivenne** [comment]
Also, for the record, I didn't blame datums under the lol-remove-datums thing.  I blamed it because generally client crashing bugs that are not only consistent but consistently effect multiple users are some of the first bugs that get patched, and it'd be abnormal (but not impossible) for it to have been some older bug that'd been missed rather than a new gamebreaking bug that was related to a recent patch, with datums being the immediate patch to point fingers at.  

That said, the overlay thing is just dumb enough to make sense seeing how shite byond generally is at parsing excessive things like that.

**Comment by DamianX** [comment]
#20284 has more relevant information
