### ISSUE TITLE
Colorful reagent recipe doesn't work

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#20106]
1. mix all 3 chemicals required to make colorful reagent

/datum/chemical_reaction/colorful_reagent
	name = "Colorful Reagent"
	id = COLORFUL_REAGENT
	result = COLORFUL_REAGENT
	required_reagents = list(MESCALINE = 1, PSILOCYBIN = 1, AMATOXIN = 1)

2. end up with nothing, all chemicals consumed but no reagent. You hear a bubbling sound for every reagent unit that should have been made

**Comment by Exxion** [comment]
It doesn't define `result_amount`

**Comment by Exxion** [comment]
Huh. I just looked at the PR, and it originally defined it as 3
How did that get removed?

EDIT: Oh man
Another PR added several more recipes below it, and the last one also had a `result_amount` of 3
That PR accidentally removed `result_amount` from *this* recipe, but it didn't show up as a removed line because Git just decided that those recipes were added right *before* that line
