### ISSUE TITLE
Mednanobots don't heal the amount per unit they're "supposed" to

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#20263]
#### Description of issue
Mednanobots are supposed to heal 40 damage per unit, see comment in their on_mob_life() in [Chemistry-Reagents.dm line 3426](https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/reagents/Chemistry-Reagents.dm#L3426):
`//The number/40 means that every time it heals, it uses up number/40ths of a unit, meaning each unit heals 40 damage`
Also optionally see the [the commit that originally added them](https://github.com/vgstation-coders/vgstation13/pull/8466/files#diff-5da7182f398e1fd964dee9d74d475679R2279). As you can see, it removes 4/40 because it heals 4 oxy, it removes 5/40 because it heals 5 brute, etc.

In the way they currently work, however, they remove 0.25u whenever they heal any or *any combination* of the basic damages plus clone damage. That means they'll remove 0.25u whether they heal 5 damage or 25 damage spread evenly through the 5 types.

To clarify, I'm not sure this is a *bug* as such because the PR that introduced it was a rework of mednanobots, but I'm not sure making their healing per unit (which is one of the only two metrics you're interested in, and the only relevant one for this reagent) vary wildly makes them more consistent, which was the goal of the PR. I don't know, ask @Fruktlimpa 

#### Difference between expected and actual behavior
Mednanobots heal anywhere between 20 and 100 per unit instead of the 40 per unit they're supposed to.

#### Specific information for locating

See above, but
- [mednanobots/on_mob_life() in live Chemistry-Reagents.dm](https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/reagents/Chemistry-Reagents.dm#L3405)
- [mednanobots/on_mob_life() in the original implementation](https://github.com/vgstation-coders/vgstation13/pull/8466/files#diff-5da7182f398e1fd964dee9d74d475679R2275)

#### Length of time in which bug has been known to occur
Since #12987

#### Server revision
2c5901f0f5e9bf51df212bc3f9e1b7941e882094

#### Issue bingo
didn't log on to test
- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Fruktlimpa** [comment]
I should probably have edited or removed that comment in the line because it incorrectly reflects how it works now.
If we are pointing out inconsistency then I will have to say that the sole reason I did rework how they heal was because it was so inconsistent from the start.
The idea is good but from my testing when I changed this, it was bugged or at the very least very ineffectual.

Chest damage of brute or burn would heal instantaneously using up pretty much no Mednanos, meaning that if you were only taking chest damage you'd be invincible save for a Pulse rifle.
Another point against it was that it was near useless at healing tox and clone damage because it was a 50% shot for tox and 60% shot for clone and even if it worked it would remove a measly 2 from each.
It was also a chance to not heal brute or burn at 90%, so I felt that for such an expensive reagent it having a chance not to heal you was strange.

My goal was to make them heal a substantial amount guaranteed and across all damage types. The consequence would be that they would be used up faster.
But I don't get how that is more inconsistent than how they used to be.
