### ISSUE TITLE
Dynamic mode is currently regarded as 'too aggressive'

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#20296]
#### Description of issue

There's a lot of talk about the game being a little too aggressive. Lot of dying, lot of validhunting, generally less fun.
Too many antags, coupled with our kind of buggy/unappealing antags makes for a bad time.
I'm not sure how much stat collecting has already been done, but I figure some tweaking is in order before major antag additions / reworks are done.

#### Server revision
c949cbab8d5bc69c29ed3485e1acacf86c31d42d

**Comment by CptWad** [comment]
Honestly only one ruleset should be applied per game but when said antags get killed off there should be a grace period where the game can slow down before adding more antags
its why admins wait every hour for adding antags. Gives people time for complacency and for people to play the game instead of TTT for a while

**Comment by SonixApache** [comment]
Supposedly that's the case, with how the `threat` var system works, but I'm not sure if it's working as intended (or even coded as intended). Need @DeityLink to chime in on this, probably.

From what I could see, the `threat` var doesn't actually change.

**Comment by CptWad** [comment]
Its pretty quick on the ball actually it efficently decides to add more antags nearly right after they die.
Now that I can easily check the threat level I can probably verify this but since threat is decided at the beginning of the shift if its very high it is more likely to generate newer antags and lower means that it usually NEVER spawns new antags 
I honestly dont quite understand it myself

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
We probably need a descriptive explanation of how it works first so we can see how to best tweak it
I think for most people it's bit of a mystery @DeityLink

**Comment by DeityLink** [comment]
The game exports stats that are meant to help me balance the mode out but right now I'm learning how sood's stats thing works and also fixing it, as you may have noticed that pop graphs no longer appear for some reason: http://stats.ss13.moe/match/2866

That said I can still use the discord's #server-status as reference for now.

From what I can see, the increase in antags may be a side effect of the "dumb bug" fixed in [19845] so I'll update the proc that governs rule injections to take into account the fact that they happen more frequently now. I'll also reduce the weight of ragin' magus a bit.

lastly
![image](https://user-images.githubusercontent.com/7573912/47191144-d5532400-d345-11e8-8bd3-0731754aad8b.png)

This thread might be related to the case that those three games happened on a row. At high pop and high threat level, those frequent antag spawns are bound to happen, but keep in mind that for every high threat round there is a low threat round.

**Comment by DeityLink** [comment]
I made a quick poll on the server to get the opinion of the players there on the antag spawns:

I want many more antags = 5
I want a bit more antags = 3
there's just enough antags = 1
there's a bit too many antags = 4
there are way too many antags = 0

Looks like the consensus is that people REALLY hate wizard. They don't hate antags in general, just the amount of wizards that have appeared lately. This is definitely related to the bug mentionned above so I think I'll

* disable midround wizard (the ghost polling one)
* keep latejoin wizard but give it a slightly lower weight (so you're more likely to be a latejoin traitor

**Comment by DeityLink** [comment]
#20309
