### ISSUE TITLE
No Alt-Title Change in lobby once readied

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20444]
(WEB REPORT BY: shadownil REMOTE: 172.93.109.202:7777)
# Revision
020de726396c782b6237cfc85c7de938a41451d5

# Description
cannot change alt titles of jobs once you ready up 

# Steps to Reproduce
be in lobby
click Declare Ready
click Setup Character
click Set Occupation Preferences
click any job name with an alt title (ex. Clown)
pop-up window to change it to Jester does not appear
window only appears once you unready and then do it
having that job at any rank (NEVER, Low, Medium, or High) doesn't affect this

# What you Expected
ability to change job titles while readied, maybe?

# What Actually Happened
no such option when readied - feature?

**Comment by Kurfursten** [comment]
Isn't this WAD? I thought you had to unready to change prefs.

**Comment by Exxion** [comment]
Yeah, this is intentional as far as I know

**Comment by DamianX** [comment]
Still retarded, IMO. It doesn't even actually tell you that you need to un-ready, it just brings back focus on the window to do that. Also, as the issue says, only some preferences can't be changed.
I imagine this was done so that you couldn't change IC preferences in-game (changing flavor text mid-round could be bad) but it could definitely be made better

**Comment by Exxion** [comment]
Yeah, it should tell you to unready rather than failing silently

**Comment by west3436** [comment]
Feature request this
