### ISSUE TITLE
Mob Printers Use Cooldown By Default

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#20484]
This is @kilozombie 's fault

When he added his cooldown feature for mob printers he accidentally made it on by default so now you have to manually turn it off if you don't want to use it. The most common cooldown you would want to use is 0 for round end fun shenanigans and if you're going to do something like dorf you probably are gonna set a custom cooldown anyway.

**Comment by kilozombie** [comment]
This was intentional, not accidental, because I made the presumption people would use this for more reasonable busses, not roundend griff
Having no cooldown means ghosts can just spam the fuck out of everything. It could be a subtype of the mob printer that has no cooldown if you wanted to make it easier, but this was specifically so that people could, for instance, make some monster spawners around the station that wouldn't crowd things too quickly.

**Comment by Kurfursten** [comment]
I've never seen any admin do that, and I don't believe they will.

**Comment by kilozombie** [comment]
I mean, shit, it's not like it was a well-known tool to begin with
The only place I was using it and the reason for the PR was because I put a martian spawner on the Shoal that (should be) guaranteed
