### ISSUE TITLE
Packed engineering APC doesn't charge

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20541]
(WEB REPORT BY: ddolll REMOTE: 172.93.109.202:7777)
# Revision
c201d349f03d0193ec258f59427a12c945b1bbb1

# Description
The engineering APC and the bottom SME on packed don't seem to charge, leading to various cases of the big gay
# Steps to Reproduce
Play on packed, set up an engine in the singularity space which uses emitters (e.g. SME)
# What you Expected
The APC to charge once power was being generated and the SMES was on.
# What Actually Happened
No power was actually stored in the SMES. The SMES UI also broke for some reason and the APC never charged.

**Comment by Kurfursten** [comment]
This isn't a bug, this is another case of bad engineers

**Comment by SGuivenne** [comment]
Are you sure?  I had some REALLY fuckey shit with the APCs on roid yesterday too, as in producing adequate power yet some APCs were outright refusing to charge, including the fucking AMU APC when the AMU WAS FUCKING ON.    And yes I checked and verified it was running and had fuel.

**Comment by Kurfursten** [comment]
Yes, I looked into it myself. Your problem is probably the same problem, which is this:

If you set the SMES to max charge, they will try to use all the power they can before the APCs get a drop of power. Meaning if you are producing less than 600kw (say, 160kw from running just an AME for example...) and you've set the SMES to auto/max, your APCs inside engineering will not charge and will eventually turn off.

This is the #1 problem newbie engineers have, a lack of understanding how the SMES works.

**Comment by SonixApache** [comment]
It's also very annoying that both the internal engineering net and external power net are the same color of wire.

**Comment by ddolll** [comment]
Yeah I'm just a literal retard and nanoUI doesn't work
You can close this
