### ISSUE TITLE
Feature Request:Remove the special snowflake bottles from the botany vendor

### ISSUE THREAD

**Issue by jubisloviu1** [d3athrow/vgstation13#20576]
Title says it all, those bottles are stupid 10 unit beakers that you can't even toggle their transfer ammount

Proposed change: Change them to normal 30u bottles and cut their ammount in the vendor by 2/3
inb4:"but muh powercreep, now botany gets FREE 30u containers"
\>Cans are available everywhere and they hold 50u

**Comment by DrSnips** [comment]
I can take this. Would people like new colors or anything for the sprites as well?

**Comment by Killette2** [comment]
While I move to the biogen rather quickly dispensing 4 or more bottles roundstart is slow and annoying. This change would be great

**Comment by Lunstra** [comment]
Man I'd be happy with them just not being green bottles on a green vendor anymore.

**Comment by Killette2** [comment]
I hope you're not implying that you're dispensing ez nutrient over the dark green robust harvest

**Comment by Kurfursten** [comment]
Just putting this out there, why not make them one each in a big boy bucket. You get yourself a big bucketful of fertilizer to start with and after that you have to use the biogenerator like a true botany patriot. Plus, free buckets.

Ideally the same PR would clean up the biogenerator to bring it into this century, too. I'm thinking a UI more like the autolathe select-able categories instead of playing ctrl f hunt, no annoying "processing" screen, and queuing.

**Comment by ghost** [comment]
Don't want to rain on the parade here, but do we keep "Easy Fix" and stick to "make this into 30u bottles and cut the amount by two-thirds" ? If so, the rest of the stuff would move to another ticket, because that's getting closed with the fix

**Comment by Kurfursten** [comment]
dealer's choice, really, of whoever deals with it first
