### ISSUE TITLE
Discussion thread about the assistant cap

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#20604]
[discussion] [help]

This is a discussion thread about the assistant cap, a feature of /vegan/ station.
Essentially, the first two assistant slots in a round are free ; then, 2 assistant slots are open for each security member. At over 5 sec members, the cap is removed.

**Arguments _for_ the cap :** 

- It forces people to actually play a useful job.
- It limits excessive greytiding by ensuring there is an appropriate security force to deal with it.
- It avoids a station of 5 assistants, 1 medical doctor, 1 scientist and 1 chef in low pop.
- Given our spare-rushing culture, this prevents some greyshirt to beeline into the teleporter, the cap office, hide the spare in his backpack and fucking off to space to an extent, since his slot might be taken by a more reasonable person.

**Arguments _against_ the cap :** 

- People who wanted to play as assistants will ask for a demote or abandon their post which might cause the HoP to demote them... as assistants, negating the point of the feature
- These people can end up wasting a critical job slot such as chaplain, or chef, without the intention to do anything during the round.
- Sometimes people who don't get their assistant roll end up disconnecting, which can cause pop problems, and we do not have the luxury to afford that right now
- You don't actually need to be an assistant to spare rush, as a mechanic, engineer or any other role can do it just as well. Ill intent knows no role restriction.

Now it is your time to speak fellow spessmen ; what do (you) think of the assistant cap

**Comment by Reviire** [comment]
What do you mean it prevents some greyshirts being able to beeline into the teleporter? What the actual fuck did you mean by this? The greyshit just plays mechanic because that role is better at securing the spare and fucking off into space.

**Comment by Caboozles** [comment]
You’re not going to stop greytiding by having a cap. You also possibly have a chance of having comedic good rounds where there’s 8 greyshits and a sec officer giving up on life.

It could be good, could be bad. But spare rushing IS easier on mechanic.

**Comment by Dacendeth** [comment]
Shitty people are going to be shitty regardless of their job if you ask me and limiting assistant doesn't really do much. If anything the cap has just prevented me from joining the round because I don't want to play a real job and just want to do some autism maint project like building a ghetto bar.

**Comment by ddolll** [comment]
Let's get some things out of the way:
* Powergaming validhunters have no reason not to take chaplain or mechanic slots since they have better inherents or starting kits and no drawbacks.
* 'Greytide' does not exist on /vg/. The kind of population required for a greytide to appear just isn't there.
* Security can interact with assistants in only the worst possible way, generally speaking; any other department is likely to have less drama when dealing with a large number of assistants and realistically it's service jobs more than anything else that prevent maintcrawlers from getting rowdy. Having a high sec and assistant population is the worst scenario because instead of having tensions go down from one 'side' being suppressed, there's an unlimited potential for escalation since both groups have a large surface area to generate grievances from.

That said, to address your bullshit
>It forces people to actually play a useful job.

Doing your job isn't mandatory, and not doing your job doesn't get you jobbanned (if it did, you would literally be forcing people to work when they're trying to play a game, which is what it seems like you hope to do here and which is not a good thing). Anyone who feels obligated to be productive literally because they aren't an assistant is probably not causing much trouble.
>It limits excessive greytiding by ensuring there is an appropriate security force to deal with it.

I somewhat covered this above, but it's basically as untrue a claim as could be made. At greytide pops (>90) sec can't do jack shit to stop the wall of locusts, and at actual pops (~40) the more sec there are the more likely some shitter in sec antagonizes enough people to get security as a whole demonized. The only benefit to a large security force is that assistants are less likely to reach for lethals with larger groups of officers because they're more likely to find someone who isn't shitcurity, but that has nothing to do with the actual ability of security to assault other players.
Additionally, relatively few players play assistant often and getting cucked out of the third assistant slot because nobody joined as sec doesn't make you any less likely to take an anti-sec stance in your non-assistant maintcrawling job.
>It avoids a station of 5 assistants, 1 medical doctor, 1 scientist and 1 chef in low pop.

What is wrong with this? Realistically, at least two of the assistants will set up power since they're much more likely than other roles to be hardworking powergamers, and the role is loosely aligned with engineering because of the maintcrawling paradigm. There's a captain (assistant), and a sizeable maint/tooluser presence to fix things and hunt antags. Why is this supposed to be a problem? Why should those 5 assistants be forced to pick engineering jobs if they don't feel like being the one who sets up power that round? How are the assistants doing anything less productive than the chef?
>Given our spare-rushing culture, this prevents some greyshirt to beeline into the teleporter, the cap office, hide the spare in his backpack and fucking off to space to an extent, since his slot might be taken by a more reasonable person.

Did you have a stroke before you wrote this or something?
>since his slot might be taken by a more reasonable person.

Literally just means the guy who's sparerushing has a better starting kit and more access to sparerush with. woh


You're also missing the biggest argument, which is just that people should be allowed to fucking play ss13 without having mandatory duties.

**Comment by DamianX** [comment]
remove assistant

**Comment by ghost** [comment]
y'all dumb
if assistant is taken
you just play iaa
if iaa is taken
you just play any other service role because they don't actually matter to the round
these are never fully taken even on the busiest /vg/ rounds
even after that there's cargo, who no one actually cares about so you can just fuck off
also mechanic, another non-important job because it's not fleshed out enough to be a solid independent thing that is sort of mandatory to round health
and if your goal is to validhunt like a dickhead then just go play /tg/ because you are cancer

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Yeah the OP already mentioned something like that but I don't know I'm too stupid to read it either

**Comment by SGuivenne** [comment]
Please for the love of christ no.    Staff Assistants are good for casual shit as well as for new players, in addition, they serve as a way to identify potential shitters through metagaming in a way that is less likely to get you banned than merely discriminating by name or by bald shittery.  

I've had rounds where some staff assistant went full rogue and was identified by simply reporting the location and appearance of every other greyshit.

**Comment by Irradiation** [comment]
>Given our spare-rushing culture, this prevents some greyshirt to beeline into the teleporter, the cap office, hide the spare in his backpack and fucking off to space to an extent, since his slot might be taken by a more reasonable person.

As has already been mentioned earlier, don't need to be an assistant to do that kind of shit. See: Clowns, Mimes & Mechanics. Anybody who wishes to rush the spare can do it in the first two minutes of the round anyway, depending on the map and their proximity to multitools and what-not. Thus, I think this point is moot.

>Realistically, at least two of the assistants will set up power since they're much more likely than other roles to be hardworking powergamers,

Maybe on low/deadpop, but assistants that rush the spare have a tendancy to take the spare and not actually use the spare to set up things. It happens, but the recent **_(Read: past year during medpop)_**  overwhelming majority of spare rushers just want the golden ticket and do whatever that fancies them. I'm not saying that entreprising grayshits don't exist, ownership of the golden ticket or not, but that I believe that you're overly-exaggerating because grayshits won't touch power, cryo or science in said recent times.

All of this being said, the assistant cap can get dropped for all I care, because you can't really force anyone to do their job, expect them to be productive or whatever. Sparerushing mentality isn't exclusive to assistants regardless.

**Comment by ShiftyRail** [comment]
I like it when someone says we should remove the assistant cap, I make an issue about it, and get called a retard by said person

The views in the OP aren't my own (not entirely), I just didn't want it to be a blank issue so I came up (dialectically) with arguments for and against to spark discussion 

I personally do not have much of an opinion, I get why said cap exist, and I think it had a purpose at some point in time, but right now it is not as useful and its removal could lead to interesting thing.

I do not believe that greytide is tied to pop ; for me it is just one or several assistant(s) wrecking havoc for attention/the thrill of it/out of boredom ; this can happen at any pop

I want to explain further a point about how I believe this feature can reduce the tide by assigning a would-be assistant to MD, for instance.

While any job can theoratically do this assistants have an higher tendency to do this because they have nothing they are strictly supposed to do, and have higher IC/OOC leniency.

Think of it this way : if an assistant beaks into bridge and steals the flash then flashes people in the hallways, he's just a shit ; if a MD does the same thing, he's a shit AND is not tending to the pile of bodies in medbay.

As a result, the MD is, as I understand, more likely to be ahelped, or complained about oocly, and less likely to do it in general.

People won't know if the guy is an MD out of choice or bad rng, and will take action regardless.
Feel free to call me a retard for that explanation

**Comment by SGuivenne** [comment]
If I recall correctly, the solution to spare rushing is to simply give people the 15 minute brig dick immediately for doing it, or permabrig them for severe crimes immediately.  The admins are very lax about round ending punishments when it comes to behaving like a fucking prick in the first 5 minutes of the round.

**Comment by charmstruck** [comment]
The solution to spare rushing is that security needs to rush to the bridge and taze&arrest every non-command member gunning for the spare

**Comment by ShiftyRail** [comment]
This happens already, to the detail that sec usually keep it for themselves.
When I do that I do HoP duty though.

**Comment by Arthurdentist** [comment]
just make it so that assistants have a 50% chance of spawning into the round, in the brig pre-arrested

**Comment by SonixApache** [comment]
i'd rather have deadpop than greypop

**Comment by Dacendeth** [comment]
What if assistant cap was based around total pop, 1 assistant per X of any job? 
It's not like sec are the ones capable of dunking a greyshit.

**Comment by Riekland** [comment]
so what you're saying is the argument against the assistant cap is that people will waste another job slot, apparently ignoring that they're wasting their space on the station no matter what because their actions don't change
you're saying that people will just ask for demotions instead of doing their job
why not, stay with me, enforce the rurus and stop people from bypassing things like job caps every round or refusing to do their job without a gimmick that isn't lole i tide u

**Comment by SonixApache** [comment]
actually, i reconsidered, and i'd like to see how many players we'd have if the assistant cap was off
test it for a week or two or four maybe?
