### ISSUE TITLE
Teleporter doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20709]
(WEB REPORT BY: somepersonsalias REMOTE: 172.93.109.202:7777)
# Revision
4eefdcef89c9f2db5d85ee83eabb9241ba5f6b74

# Description
The teleporter doesn't work, no matter the destination, setting and entering does nothing.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ghost** [comment]
While the issue was about as descriptive as '6ft white male', Looks like roidstation's out of order. When attempted to use, the hub would start up but wouldn't actually teleport a mob or item when stepped on
![untitled](https://user-images.githubusercontent.com/5564796/48496750-318f5380-e7df-11e8-9995-c50c9c018b2f.png)


When deconstructed and reconstructed locally in order it worked fine teleporting to the telcommsat. Have it left to right teleporter, station, hub. 
![untitled](https://user-images.githubusercontent.com/5564796/48496711-16244880-e7df-11e8-828a-4cd7f5b5a147.png)

Can I get a mapping roidstation label and someone bugger whoever's got priority?

**Comment by SonixApache** [comment]
@GeneralVeers25 
i love that you followed my request
but shit dude you only got 1 int
