### ISSUE TITLE
Glass floors don't show gas overlays

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#20832]
#### Description of issue
The purple and white snow overlays don't show up.

#### Steps to reproduce
- Open plasma/n2o canister in a room with `/turf/simulated/floor/glass` subtypes for floors

#### Length of time in which bug has been known to occur
Probably since XGM. I remember changing their `update_icon` for a bugfix and the overlays worked back then.

#### Server revision
39b1371cb904bba238b5418fe22dc6d19dce9738

**Comment by Exxion** [comment]
Bet it layers under them or something similarly idiotic

**Comment by Exxion** [comment]
Glass tiles are on the `SPACE_BACKGROUND_LAYER` `plane` for parallax reasons, and the visible glass part is just an overlay
And gas overlays got stuck on whatever `plane` their `turf` was on because BYOND doesn't let you specify `plane` in `image()`
So they were becoming part of parallax
Because of how parallax works this made them functionally invisible
