### ISSUE TITLE
Obese+trash bag= free storage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20842]
(WEB REPORT BY: spoonylove REMOTE: 172.93.109.202:7777)
# Revision
1d45da69591f630f53c860dab4ed501db80bdd06

# Description
be obese, put on trash bag, game tells you you burst out, still have the bag equipped in body slot, proceed to put things in the bag, on self inspection the bag does not appear on your description. This could lead to people having a stash of items undetectable by sprites or inspection
# Steps to Reproduce
be fat, get trash bag, see how you can now store things in your fat folds.

# What you Expected
to be able to wear trash bags while obese since its just a big bag.

# What Actually Happened
free storage

**Comment by RealestEstate** [comment]
oops

**Comment by DamianX** [comment]
I briefly looked into this and simply got frustrated. The bag is correctly dropped if worn while becoming fat, but then you're able to just re-equip it. When that happens, the bag is dropped again, but rather than being placed onto the floor it gets placed inside the human. The `wear_suit` var gets set to null, though, so that's why it can't be seen in the strip menu or examine().
