### ISSUE TITLE
Space Lube persists extreme amounts of time. How to do it will blow your mind.

### ISSUE THREAD

**Issue by SilentN** [d3athrow/vgstation13#20905]
#### Description of issue
If you use space lube for cleaning (with bucket/janicart/janibucket) with mop it will stay on a tile for extreme amounts of time. Including one time where I saw it stay on a tile for a whole round duration which was about 2h long.

#### Difference between expected and actual behavior
You'd expect cleaning with lube to have similar effect or just a bit better than spraying tiles or splashing solution with lube on the tile. Not 30minute active unavoidable slip trap.

#### Steps to reproduce
Put space lube in a bucket, clean the floor with the mop.

**Comment by Kurfursten** [comment]
@Exxion cannot reproduce on live

**Comment by Exxion** [comment]
And I also can't see a way it would happen
The duration is hardcoded

**Comment by SilentN** [comment]
Will test further on live once able to.

**Comment by Exxion** [comment]
Cause found
https://github.com/vgstation-coders/vgstation13/blob/f249199a287699ee30cdcd38e1d524c39d119df7/code/game/turfs/simulated/floor.dm#L674
`lifespan` is the time at which it will delete itself, *not* the time *until* it deletes itself
So when you put lube down on top of water, it adds the length of time the server has been running to the thing's lifespan

This bug is like perfectly designed to not come up in testing because it only happens when the server has been running for a long time
