### ISSUE TITLE
you can make altars actually on actually shuttles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20930]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
4999258d9e19330200c8dd7fd3137522fb7ab4ac

# Description
fuck you deity

**Comment by DeityLink** [comment]
that's not a bug in itself. The bug is that bloodstones shouldn't ever spawn on shuttles. Therefore I'll make sure it can't happen from an altar either.

**Comment by Chazach** [comment]
I think from a balance standpoint altars should not be able to be created on shuttles, regardless of bloodstone fuckery

**Comment by DeityLink** [comment]
For what reason?

edit: no really, I don't get it, is a feature of the altar causing issues on a shuttle?

**Comment by Chazach** [comment]
-they are functionally unassailable unless you corner all docking points, and even then they can keep jumping between them and get a free stun on everyone when they do so, which doesnt affect constructs
-they can wall it/natural shuttle walls make just lasering it difficult to unavailable
-the small area means that swords and AOE stun talismans and such are much much more effective
-have to funnel through designated 1 tile rape spots since shuttle walls are indestructible

now all of that is just inherent to cultists and shuttles but
-being able to stick altars on them makes them a fully functioning cult base that can spawn swords
is the kicker.
Nearly  every round I have seen has had the outpost culted (and sacced the target there half the time) since its just the easiest thing to do. I don't think this meta is healthy or fun for anyone. Preventing fancy structures from being raised on shuttles wont solve the issue but it wont contribute to it either.
