### ISSUE TITLE
Vampire Rejuvinate does not remove Clown PDA slip

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20960]
(WEB REPORT BY: shadownil REMOTE: 206.221.180.138:7777)
# Revision
c4145c9af771d8406cf5797ca107fbf924e7ad95

# Description
Title

**Comment by Kurfursten** [comment]
This isn't a bug, exactly. The way rejuvinate works is by removing your stun, but you need to wait until the next life tick to actually stand up, so it's not instant. If you're being chain stunned more frequently than life ticks, rejuv won't free you because you have to wait until the next life tick to stand.

**Comment by DamianX** [comment]
That's kind of lame for a spell on a 3-minutes cooldown.

**Comment by Killette2** [comment]
All the vampire spells have needlessly long cooldowns, it's their gimmick.
