### ISSUE TITLE
Dead borers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21046]
(WEB REPORT BY: lnachochaosl REMOTE: 206.221.180.138:7777)
# Description
Dead borers can talk on hivechat.
# Steps to Reproduce
Die as a borer, try to speak on hivechat.
# What you Expected
Dead borers being unable to speak on hivechat.
# What Actually Happened
A dead borer started speaking on hivechat.

**Comment by SGuivenne** [comment]
This needs an exploitable tab.

**Comment by ddolll** [comment]
Only using the actual verb you get when in a host allows you to talk while dead, whereas just using say "; ock in ick" will just speak into deadchat (so you can't do it while not in a host).

You can still talk into the cortical hivemind while not in a host and not dead, and I don't know if that was intended or not since you don't actually have the verb.
