### ISSUE TITLE
Clowncarts Are Powerful Spacepods

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21135]
Perfect space handling with no drift
Full speed without anything to drive on
Requires no recharging

Find clown planet easy every shift, and ride back, 5 minutes just need a suit.

**Comment by MadmanMartian** [comment]
It's almost as if people add clown stuff for funnies, disregarding balance

Looking at you, honk mech

**Comment by ddolll** [comment]
HONK was designed to be the top tier combat mech, since it was added in the transition period between spacecrawling being slowroll antag (i.e. autowin anyway tbh) or extended exclusive and hardsuit era. It's literally the old phazon, except rounds where it was made were assumed to be gunked beyond recovery anyway.


Clowncarts aren't substantially better than jetpacks except for not needing a slot, but it's true that there's not any reason for them to be as good as they are anyhow

**Comment by Kurfursten** [comment]
When you think really think about it, the "clown planet" is two times over an artifact of a bygone age. Even if you believe the HONK is the clown's "endgame", it doesn't make logical sense for clowns to get themselves. Consider situations A and B.

Situation A (Departmental Interaction): Clowns aren't expected to get bananium themselves (like banana peels from botanists) they are supposed to reply on miners/scientists/spacepod mechanics to bring it back and roboticist to build it (exosuit fab requires access anyway). This increases interaction. Therefore, clown doesn't need his own space pod.

Situation B (Part of the Clown Gameplan): If Clowns are expected to get the HONK themselves without relying on others, why gate it behind things they don't have access to (hardsuit, exosuit fab, mining pick, mining satchel) and put it so far from their ostensible role as entertainer (exploring space is the opposite of entertaining and interacting). It's illogical if one expects the clown to make a HONK himself that the task of getting parts is so far removed from actual clowning.

Though I confess, besides just the ludonarrative dissonance, part of it is just muh immershuns. Carting through space when really it should drift like a borg.

**Comment by Exxion** [comment]
Pretty sure this is a bug since the clowncart doesn't override `can_spacemove` and thus it inherits 0 from the parent
`can_spacemove` is completely unimplemented though so it's not exactly shocking

EDIT: Yeah the clowncart overrides `relaymove()` but doesn't include the gravity check that the parent does

**Comment by spoonylove** [comment]
Bury this PR. Clowncart is sacred.

**Comment by Exxion** [comment]
It's not a PR

**Comment by ghost** [comment]
Clown roid wouldn't be an issue if we didn't decide to load it up with adminium a few years back, aka Phazon

It's not even difficult to get to once you hit the Derelict, anyone who's not retarded knows how to align themselves to shuttle from the bottom of the Derelict to it

**Comment by Exxion** [comment]
Phazon has exactly three uses and only one of them is even moderately good
Also that isn't a reason to not fix this
