### ISSUE TITLE
AI hand warming

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21287]
(WEB REPORT BY: kitfox88 REMOTE: 206.221.180.138:7777)
# Revision
0e50b00c6c00b3f683b4b76885e5073d2b636989

# Description
Clicked on a lit stove, comfortably warmed my not-existing AI hands around it.
# Steps to Reproduce
Click lit stove while being disembodied brain living in eternal servitude hell.
# What you Expected
Nothing
# What Actually Happened
Immersion destroying interaction that ruined my round.

**Comment by Kurfursten** [comment]
dupe of #15826

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
This is so specific and innocuous I can't believe it was reported twice

**Comment by Kitfox88** [comment]
If it's a bug it's worth reporting, yeah? Otherwise given the way spaghetticode works fixing it down the line'll require changing 5 other things and also break goonchat or some shit. 🚯

**Comment by Kurfursten** [comment]
In this case it's not spaghetticode, it's the result of behavior inheritance. AIs can interact with machines at a distance. The campfire and stove are a type of space heater. Although, honestly, with how different they are it may have been better to just make campfires/stoves/fireplaces their own thing instead of making them space heaters with weird cell behavior. Because you have issues like this.

**Comment by ShiftyRail** [comment]
Duplicate
