### ISSUE TITLE
Cult sacrifice target takes too long.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21460]
(WEB REPORT BY: kavlax REMOTE: 206.221.180.138:7777)
30 minutes or whatever is excessive.

**Comment by Kurfursten** [comment]
This wouldn't have mattered anyway since there was only 1 valid sacrifice target, so even if it was checking on regular intervals at the end it would've kept picking Sorrel Peters. Everyone else was cult or a subverted silicon.

Also noticed that since it wants to check the z of a target, people inside mechs are not valid sacrifice targets.

**Comment by ghost** [comment]
Seems like the cult really cucked themselves by super rushing to convert everyone. They didn't even let new players do anything, just instantly converted them.

**Comment by Allspice** [comment]
Hypothetically, they could have killed a cultist (roundstart preferred), grew a diona, then sacced that when reroll comes around. But 30 minutes is still obnoxiously long.
