### ISSUE TITLE
Roid unsimulated turfs 2: electric boogaloo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21586]
(WEB REPORT BY: lunstra REMOTE: 206.221.180.138:7777)
# Revision
7558a114da28b47f8efc5fdce2151552e68b9c37

# Description
Like every single roid turf around where the gateway used to be at sec is unsimulated, including all the ones directly next to maint that look like prime area for random building projects in the rock
# Steps to Reproduce
Play on roid and mine any of those turfs
# What you Expected
For us to be done with this song and dance
# What Actually Happened
Mappers made mustard gas, again.

**Comment by Lunstra** [comment]
I should note that this is only really an issue because its both surrounded by maint cubbys with loot, has a hole inside it that looks like it could have loot (even through its only a pickaxe) and there's a pickaxe inside maint like 2 doors north of it. The are is is a giant zas trap waiting to happen.
