### ISSUE TITLE
Play-Global-Sound does not work on latest byond versions.

### ISSUE THREAD

**Issue by Sooose** [d3athrow/vgstation13#21677]
#### Description of issue
Play Global sound does not work on versions of byond higher than 512.1458, Play Local Sound still works even on the latest builds.

#### Difference between expected and actual behavior
Expected to be able to upset players with midis that no one asked for.

#### Server revision

Game: dd38146979e1438f0353f55a76b6e7581a7ee526 
Patches: aa87a68464622df7f246af3fb98aec6bf23b0196 
<byond><sound>

**Comment by Exxion** [comment]
Well, that explains why some people said it didn't and others said it did

**Comment by Exxion** [comment]
Turns out that it was a BYOND bug that it worked at all
https://github.com/vgstation-coders/vgstation13/blob/0297ea1c978453ac76f89d6959a1e5c1c230c0e5/code/modules/admin/verbs/playsound.dm#L8
I don't actually know why `SOUND_UPDATE` is there, but it should be removed since it doesn't work that way anymore
