### ISSUE TITLE
Something needs to be done about culted borgs.

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#21890]
#### Description of issue

Right now this is what happens, code wise, when you put a cultist into a mmi and then a borg shell

## Code wise

1) they get unlinked from the role, and will fail cultist checks (cannot use an altar to locate the stones, for instance)
2) they are STILL cultists for the purpose of keeping a ref ; if deborged, they will gain their knoweldge back (supposedly)
3) they still show up in cult HuD

(3) is clearly an error and should be addressed

## Gameplay wise

More important however is what happens as far as player interactions are considered.

Cultists borgs are in the limbo in which they still obey the cult BUT have to follow their laws.
This is in theory what Deity wanted. I think.
Smarter admins than me have pointed out why it's a dumb idea. Essentially 

1) From the player consideration : it forces you to put the player on a useful lawset, and still have the Damocles sword of the borg losing that lawset. A purged cultist borg will be able to get his human body back, while an asimov cult borg will be able to convert non-humans, for instance.

2) Other silicons might be thrown under the bus by the actions of a lone cultist borg. And unlike a regular rogue cyborg, it is something that happens immediatly when the borg is made. The borg is "born" evil. 

3) Admins will have a hard time resolving an issue involving something involving this conflicts of roles.

## How to solve this

The proposed idea was to mute the role - completly - and to remove his HuD icons.

For the second point, it was suggested that borgs should simply speaking be only beholden to their laws, erasing the current contradiction.

This issue is here to gather feedback and infos on the subject.

**Comment by RealestEstate** [comment]
what about a cult lawset?

**Comment by ShiftyRail** [comment]
This would make it even harder to get reinforcements as crew members.

**Comment by Sooose** [comment]
I don't want the precedent being set that borgs are allowed to wiggle through technicalities in their lawset so they can achieve their original antagonist role's valids. Mute the role, just like we do with any other antagonist.

**Comment by mtpowell** [comment]
If a borg is an antag, they shouldn't have to follow their laws, right? If this is the case, than all those arguments don't matter. Antags don't have rules.

1. they get unlinked from the role, and will fail cultist checks (cannot use an altar to locate the stones, for instance)

This is the only error that should be fixed, imo

**Comment by Coxswain-Navigator** [comment]
The best answer might just be to prevent cultists from becoming cyborgs entirely- or allowing them to become a shade to detatch from the shell and join their fellow cultists. They would still be beholden to their laws, but should their actions be a detriment to the cult they would have a way to abandon their cyborg body.

**Comment by ShiftyRail** [comment]
Cultists already have plenty of ways to avoid being caught and, if caught, will be brought back as a sword 

A crewmember dying or being converted is a permanent loss because the only way you can get reinforcements is through borgs (unreliable, requires a useful lawset...) or ERTs

**Comment by Kammerjunk** [comment]
To clear up some apparent confusion, borged antags aren't normally antags. If you borg a traitor, he can't keep going around killing people (barring extraordinary circumstances). In other words, "if a borg is an antag, they shouldn't have to follow their laws" is not the case

Beyond that, cultist borgs are retarded in several ways I mentioned in #metaclub and most of which Shifty has mentioned in the OP
They also don't fix one problem they're supposed to address (people making borgs of cultists because then they can snitch on the entire cult) because of the "laws > cult stuff" bit

**Comment by DeityLink** [comment]
`2\. if deborged, they will gain their knoweldge back (supposedly)`

Nope, nothing in the code permits that, hence why I've told you to do a recult() proc in the last PR that added the decult() proc. But that @Kurfursten  merged before either that or my compromise got added because ???

**Comment by DeityLink** [comment]
Also gameplay wise, the most important is to tell the player what his IC memory is. This is the very issue that started this whole mess:

`Help: SpacedGod/(oh): So from an IC perspective, do I have cult memory or not? I've always been unclear`

Because even assuming that the role is muted/removed, they could still:

1. Remember everything about the cult
2. Remember stuff only up to when they became cultist (so they remember who converted them)
3. Forget everything about the cult
