### ISSUE TITLE
TTVs beyond dev ~2 are now physically impossible

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#21975]
Due to https://github.com/vgstation-coders/vgstation13/pull/21782

Problem is that author of said PR doesn't realize that a 1650kpa pressure COLD tank is not a thing that can exist without var editing.

`G.multiply(1650 / G.pressure) //Sets each tank's pressure to 1650kPa. This was determined experimentally to result in a 7 dev explosion with this mix.`

**Comment by boy2mantwicethefam** [comment]
Works on my machine bro

**Comment by ghost** [comment]
For the record, I wrote ~2 because even 2 is an exaggeration of current potential. Dev 1 is what a single tank assembly produces at ideal conditions. A TTV assembly having near equal potential to a single tank is absurd.

**Comment by Exxion** [comment]
I know that a 1650 kPa cold tank isn't achievable. That mix isn't meant to be achievable. That's just an easy maxcap mix to write in the code. And for the record, the old mix in those pre-spawned bombs wasn't properly achievable either, since it actually caused the tanks to leak.
Also, it's a settings issue. Whoever merged it didn't update the setting on the secret repo.

Also also, you spent the whole thread arguing that you can always make a mix better than a speedmix, so the fact that you consider the speedmix I was given (which came out to just under 2 dev with the unupdated setting) to be the max possible is odd.

**Comment by ghost** [comment]
What I said in the PR you've made, is that if a max cap mix is possible, it will always be possible to make it fast. When a max cap mix is not possible, it will logically not be possible to make it at all. I'm not sure I understand what you find odd.

**Comment by Exxion** [comment]
OK, after reading back over what you said, your argument is confusing, but yeah, not really related.
I am curious how you came to the conclusion that it's *impossible* to surpass 2 dev with the wrong setting/4 dev with the changed one though. I mean, you may be right, but how do you know this?

**Comment by ghost** [comment]
Through game mechanics you can only get about 20 mols of plasma into a plasma tank that can still ignite in a TTV, but realistically you'll be playing with 15-17 mols at decent temperature (~400C) due to leftover CO2 from internal tank burn. After you have this ideal plasma tank, your only other limiting factor is mols in oxygen tank.

After having assembled such a TTV, you can quite accurately determine the maximum dev achievable through legitimate means. Prior to your changes it was dev ~10.

It should be trivial to make a TTV simulator that would just bruteforce through all possible valid tank combinations. I'd wager there wouldn't be more than a few hundred sufficiently distinct cases to make nice graphs from dev 0 to max theoretical.

**Comment by Exxion** [comment]
Calculus would be easier than the brute force method honestly, provided some approximations are used
Haven't gotten around to it though
(Or rather I did but was lazy and cut out some dimensions with assumptions that turned out to be wrong, so the results were meaningless)
Busy tomorrow. Might do it Saturday. It would mostly be for shits and giggles though since I now strongly suspect the theoretical maximum isn't much better than the ones achieved, considering the distribution of explosion sizes found in the toxins test area since the changes
(Every single one of them was exactly the same size, other than the first two)

**Comment by agentofzog2** [comment]
I got 3devs with a mix I used to use.  Those 20+ (theoretical) dev bomb Mitchell Owen used to make would probably still hit the cap but I remember he used to do stuff in atmos to get the higher end ones and I don't think properbombs need to take THAT much effort.

**Comment by Exxion** [comment]
The 3 devs were probably after I updated the setting on the secret repo
The records as far as I could see were one power short of 2 dev before and one power short of 4 dev after.

**Comment by ghost** [comment]
I've done some math and this should be a simplified dev range equation. I've made some assumptions for this:
-using pure plasma/oxygen
-all gases in tanks fully reacting upon mixing in a TTV (this doesn't happen afaik)
-always having at least twice as much oxygen mols than plasma mols

I've probably made a mistake somewhere too.

```
pressure = (((plasma_temperature*10 + fire_fuel_energy_release/20)*plasma_mols + oxygen_temperature*oxygen_mols) * R_IDEAL_GAS_EQUATION) / volume
range = (pressure-TANK_FRAGMENT_PRESSURE)/TANK_FRAGMENT_SCALE

range_dev = range*0.25
range_high = range*0.5
range_low = range
```

```
#define ONE_ATMOSPHERE 101.325
#define TANK_FRAGMENT_PRESSURE	(50.*ONE_ATMOSPHERE)
#define TANK_FRAGMENT_SCALE	(10.*ONE_ATMOSPHERE)
#define R_IDEAL_GAS_EQUATION 8.314
```

**Comment by ghost** [comment]
Issue seems to be now resolved.
