### ISSUE TITLE
Malf Procs Roundend Even With Other Antags

### ISSUE THREAD

**Issue by Kevak** [d3athrow/vgstation13#21996]
What the title says. Killing a malf AI ends the round preemptively. Even with minimal station damage and whilst other antags are active and doing shit.

#### Difference between expected and actual behavior
Expected: Dead Malf>Round continues with other active Antags.

What Actually Happeneed: Dead Malf>Round ends>multiple antags get cucked.

#### Steps to reproduce
Have a Malf AI>Kill Malf

**Comment by DeityLink** [comment]
Malf should NEVER end the round following its defeat. No matter how many APCs are blue, it should still be up to the crew to call the shuttle.

Cult auto-calls the shuttle because of the bloodstone spawning, and the likely bloodbath that occured, but last round a malf went delta, then got curbstomped, that should never end the round.

I'm a bit at a loss at why malf got ported to datums if it could just end the round when more antags can just spawn now?

**Comment by ShiftyRail** [comment]
Why do I feel this was because there was a cult during that round ? ;^^^)

I feel like if Malf gets it to delta, it should shuttle call it like Cult does.
Either make the auto-shuttle docking that cult has recallable (with the heavy dose of salt it could produce) or accept that Malf ends the round in a similar fashion.

**Comment by DeityLink** [comment]
I wasn't even watching that round, I'm mad because Kurfurst thinks it's fine as it is.

If malf auto-calls the shuttle, it should be a regular shuttle call so the crew can recall it.

Keep in mind that the shuttle auto-docking when cult lose was requested by players. Here players are requesting malf loss to NOT end the round.

**Comment by Kurfursten** [comment]
Uhh since I have a PR up current to *change* Malf roundending behavior I by definition am not fine as is

Are you pretending to be retarded?

(Clicked close and comment by mistake)

**Comment by bathosbathtime** [comment]
Cultlets seething lmao
