### ISSUE TITLE
Please revert "Cult actually requires enemies to fight"

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#22052]
[featurerequest]

Please revert #21946

The combination of #21989 and #22000 already drastically reduced the frequency of cult. I haven't seen it at all since the three of them were merged (although obviously it has probably happened at least a couple of times when I wasn't present), and while it was perhaps a bit too common before, it seems to have been eliminated from the game entirely at this point. 

I also think the idea of "[X] numbers of [Y] department are required for this mode to even fire" is silly, akin to when malf rounds used to fail to start and reset the lobby timer if an AI wasn't ready. Rounds without sec of some kind are fairly uncommon, especially at the populations required for cult to fire to begin with, and by the time a cult is becoming a legitimate threat that isn't quietly autisming off in space or a maint tunnel (late act 1, early act 2), a few members of security have usually latejoined. What's more, the ability to specifically request security roles can quickly make up for a lack of roundstart sec.

The idea of security being the cult's only "enemy" is also foolish. Tell that to the bloodstones that die within moments of act 3 starting because they spawned in the middle of a department with no cult, or the cultists that go loud only to be met by an army of validhunters abandoning their departments for the chance at some action.

**Comment by SonixApache** [comment]
alternate solution;
implement midround cult

**Comment by Caboozles** [comment]
Cult 3 has ridiculous tools entirely given to fight security. With no security, it’s a pure stomp unless the cultists are fucking stupid.

**Comment by Hoshi-chan** [comment]
> Cult 3 has ridiculous tools entirely given to fight security. With no security, it’s a pure stomp unless the cultists are fucking stupid.

That same logic applies to all antags. All antags are given powerful tools, and are primarily opposed to security. Why is cult discriminated against in this particular way?

> alternate solution;
> implement midround cult

This is equally acceptable.

**Comment by SonixApache** [comment]
>Why is cult discriminated against in this particular way?

Vampires require security (and only security) to fire. Same for Wizards and Ninjas.
Blob, revs and ops don't, for some reason, which is really fucking stupid in it's own right.

**Comment by ShiftyRail** [comment]
I will post again what I said in the PR : 
"Victory without risk is triumph without glory." 

In less laconic words :

Roundstart conditions are extremely important for the cult. Absence of security during, say Act I (when you need to convert people and you do not have access to a lot of tools) negates the "pressure" you're supposed to feel at such a stage.
Additionally, what can a AI do to stop a cult, assuming Asimov ?
- Yell
That's all. It can't destroy stones on its own, it can only yell. It is then up to the non-cultist crew to actually take up arms and fight the cult ; if they're retarded and they go for lethals, then AI has to actively *hinder* them.
The same goes for the chaplain ; he does not have access to weapons.

As said in the previous PR by Accipitermaris, silicons *are* sold to the higher bider in terms of access. The fact that security knows the magic words better simply illustrates more practice with silicon wrangling on their parts.

Now. There is maybe a compromise to be found.
Instead of a single value (enemy/not), maybe a *weight* could be given to cult enemies. A security officer would be, say, 3, and an AI would be 1 or 2. With a requirement fixed at, say, 5, it would ensure at least one active opponent.

There is also the issue that (before the youtube population boom) highpop [30+] rounds, without officers, were relatively common. 30 people means a lot of playing room for the cult, the absence of security means that even if they're caught, the eventual response will be late, etc.

Shortly : 
- I do not believe this PR warrants reverting as of yet. It had plenty of popular support. AI are still a tool, a powerful one, but they're entirely dependant on who gets to their upload first.
- If other rulesets have to be modified, then so be it.
- And there's always a compromise of giving less weight to AIs as an enemy, compared to officers.
