### ISSUE TITLE
Trader Shouldn't get Vampire

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22055]
(WEB REPORT BY: gunosaguki REMOTE: 206.221.180.138:7777)
I feel a vampire is too high a role for a trader to get given their private access to a shuttle. I don't feel i need to detail much more than that.

**Comment by Sooose** [comment]
This hardly makes more sense than removing it from cargo and science. If the traders are being succy you can always close the port and storm them from the asteroid.

**Comment by Gunosaguki** [comment]
its a bit easier to reach mining and research outpost than the outpost, its a lot of extra work that most vampires dont get the protection of. an entire shuttle to travel with even if its just between z levels is pretty strong for a vampire to have for free since its rare for another trader to be with them. this is mostly a minor nitpick of course than a true complaint. Mostly putting my thoughts on it

**Comment by Kurfursten** [comment]
We discussed this a few times before and people didn't like traders having better "metatrust" than captains and sec. You can select Merchant as your title to reduce your Vamp chances to 20% like sec but not "fully trustable" during the Vamp game mode. Security and Medbay vamps are probably the true powerhouses though when it comes to vamp. Having a shuttle/mining level base like miners/science/traders just doesn't compare to "has an excuse to drag someone off somewhere secluded", "access to vulnerable people", and "stealthy means of disposal".

If you close the trader port on a tradervamp it might as well be roasted since they can't cross through space, meaning they're entombed with no escape in their base.

**Comment by agentofzog2** [comment]
> 
 You can select Merchant as your title to reduce your Vamp chances to 20% like sec but not "fully trustable" during the Vamp game mode. 

Wait, what?

**Comment by Kurfursten** [comment]
Wiki
