### ISSUE TITLE
Microwaves unexpectedly fail to cook

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#22118]
I'll put the right ingredients in, and it causes a burnt mess and even destroys the microwave.

I have been playing chef for 2 and 1/2 years at this point and I know when I fail to put the right ingredients in. After testing with rigor and making sure I'm absolutely sure of every recipe, the microwave is still fucking up recipes over and over and over.

**Comment by DamianX** [comment]
example pls

**Comment by kilozombie** [comment]
Today I put in 15 units of flour and cooked it, ensuring there was nothing else in the microwave, and it created a burnt mess and fucked my microwave

**Comment by SonixApache** [comment]
The microwave ruining the recipe and blowing up is RNG.
https://github.com/vgstation-coders/vgstation13/blob/98c788f358a75eaa345a6351f6aca9bf4782f9f4/code/game/machinery/kitchen/microwave.dm#L322-L333

~~Apparently you're supposed to maintain it...?~~
So turns out disposing stuff raises the chance of RNG breaking the thing, and as far as I can tell you can't do preventive maintenance; no way to clean the damn thing till it explodes.

**Comment by kilozombie** [comment]
I am shitty in code-fu, but it looks like that file hasn't been edited in a way that would edit that anytime recently. I'm saying that recipes that I know are correct were failing, is that what that code implies?

I know that failed recipes have a chance (maybe an increasing chance) of messing up the microwave, but successful recipes have never had a chance to fail.

**Comment by Kurfursten** [comment]
The codeblock Sonix is referencing only happens if a recipe is *not* found, meaning the chef got it wrong.

As for this report... Well, I will take it seriously if I see it in action

**Comment by SonixApache** [comment]
- there's a maximum 10% chance of the microwave blowing up when dirty
 - disposing of reagents in the microwave makes it dirtier
