### ISSUE TITLE
Boxstation's EVA has science suits, but scientists/RD don't have access to EVA.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22157]
(WEB REPORT BY: irradiation REMOTE: 206.221.180.138:7777)
# Revision
ced5d4a70e0cbc1f9de443cd82ef3b984bd4566d

# Description
See title.

# Steps to Reproduce
1 - Be a scinigger.
2 - Try to get into EVA to acquire the sweet gibsmedat science suit.
3 - Get cucked by lack of access to open the EVA door.
4 - Thanks, mappers.

# What you Expected
To get me gibsmedat suits.

# What Actually Happened
A scinigger had to nigger his way to get the gibsmedat.

**Comment by kernikov** [comment]
EVA is it's own access level, with the main door having that as the required access and the 'Scientist' assignment not having it.
The actual science airlock in EVA has the correct access required.

Whether EVA access alone should be removed or not is open for debate I suppose, since it was from the ye olde days of EVA being 4 soft suits that everyone had to fight over.

In either case, this isn't a mapping specific issue in my opinion.

**Comment by CptWad** [comment]
I agree. Technically the best way to fix this is to bring boxstation up to par with other stations by adding the medsuits and scisuits to their departments and returning the standard peasant suits
