### ISSUE TITLE
Vox Trader Supply connected to station database.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22169]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
97ea9e268f5625bbe2d31d86dfb42491be51dc24

# Description

This doesn't really make sense and theoretically allows a whole bunch of weird mechanics, especially if its connected to QM budget like I think it is.

**Comment by SonixApache** [comment]
the candy machine in the wizard den is also connected to the station

**Comment by Kurfursten** [comment]
This is on my radar as part of a major economy fix coming probably in the next week which is wide ranging in scope

**Comment by SonixApache** [comment]
@Kurfursten dunno if "slapping vending machines with credits" is part of that, but it'd be a good feature.

**Comment by Kurfursten** [comment]
That's already a feature

**Comment by Kurfursten** [comment]
I actually consciously thought about this one a lot with the economy PR and it's not a bug. When you upload credits onto your card you are making a deposit into a NT account. You can still pay with credits if you keep them out and in a wallet instead.

The other "weird mechanics" of being to change prices with the QM card are fixed by this.
