### ISSUE TITLE
Vox Syndicate lacking slot for N2 Tank

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22232]
(WEB REPORT BY: demagoguedimension REMOTE: 206.221.180.138:7777)
# Revision
961cdf075d62a1158f5fa66a174525254a1a255e

# Description
Vox Syndicate lacking slot for N2 Tank. Unable to store N2 tank in suit storage. Did not spawn in Vox suit for Syndicate. Instead had bullet proof vest.

# Steps to Reproduce
Spawn in as Vox Nuclear Operative.

# What you Expected
The tank to already be placed in suit storage and wearing a Vox suit equivalent for Syndicate.

# What Actually Happened
Spawned with Bulletproof Vest instead with tank in hand. Was unable to store tank in any slots. Did not notice any Vox suits or equivalent near spawning point. Got Oxygen poisoning attempting to find a place to put tank.

**Comment by kilozombie** [comment]
Then he suicide verbed, exploded, and put two of his operative buddies into crit

**Comment by kilozombie** [comment]
Anyway so. I haven't played nuke ops *ever* but I'm 99% sure you can just put on a blood-red hardsuit regardless of species. Moreover, you can turn on your internals even if your tank isn't in your suit slot or back slot or whatever-- just click on the button on the right side of your viewport.

Fairly certain the problem lies between the keyboard and chair on this one

**Comment by Exxion** [comment]
Bloodsuit does indeed fit vox (or *should*, though I notice that its `species_fit` is double-defined so maybe it's bugged), and does indeed hold any tank

**Comment by Sooose** [comment]
Blood red fits vox and holds a nitrogen tank, there is no issue here.
