### ISSUE TITLE
Round end blob jecties broken

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#22233]
>Blob major victory!
>The blob managed to take complete conrol of the station.

vs.

> blob conglomerate 
>Objective #1: We must grow and expand. Fill this station with our spores. Cover 2778 station tiles. Fail.
>The blob conglomerate has failed.

This is also my opportunity/excuse to say 3 roundstart blob overminds is dumb

**Comment by DamianX** [comment]
bring back #15560

**Comment by Kurfursten** [comment]
This is caused when the blob passes its victory flag while someone is shooting at the blob, causing it to win, but then display roundend data after its blobcount has dropped slightly. Since the difference of just 1 blob could potentially cause it to mark as "fail", you see this about half the time.

The objective itself should probably mark as successful if you have at least 95% of your goal.
