### ISSUE TITLE
Mech Drill Bloodstone interaction.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22318]
(WEB REPORT BY: poik12 REMOTE: 206.221.180.138:7777)
# Revision
f71c67f5b69c1fcaa76465c747c4e5c7d4054a69

# Description
The Mech dril, and Diamond Mech Drill can't damage or interact with endgame cult bloodstones.
# Steps to Reproduce
Spawn a mech, attach a drill or diamond drill
spawn a cult bloodstone
enter mech and use drill on bloodstone
# What you Expected
I expected to be able to damage and destroy the bloodstone like how I can drill through walls and doors with the diamond version of the drill
# What Actually Happened
Nothing, not even a text indicator.

**Comment by Kurfursten** [comment]
This appears to be by design. By default, you can only drill things that are acidable (that can be melted by xeno acid). All bloodcult structures are not acidable as per bloodcult_buildings.dm L71.

This means you cannot drill altars, spires, forges, pillars, or bloodstones.

@DeityLink can make a call though

**Comment by DeityLink** [comment]
It's an oversight that I keep forgetting to fix. I'll have it deal a moderate amount of damage after a do_after() instead of outright deleting the cult structure.
