### ISSUE TITLE
Wizards have a tendency to start with two books.

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#22614]
#### Description of issue

Weird. Raging Mages fired, one wizard spawned, but he spawned with two books.

#### Server revision
376bb54c65a0c216c115bbf97966852a79c60161

**Comment by SirSkeleto** [comment]
ICKY OCKY BAN HE

**Comment by SirSkeleto** [comment]
THIS IS YOUR SERVER ADMIN

**Comment by SonixApache** [comment]
autism speaks

**Comment by Kurfursten** [comment]
There was no evidence in the original report that it was from an ongoing round, and in fact this has been an ongoing issue.

It's because of the really annoying way Ragin Mages is coded as a factional midround game mode, we've alternated between 2 books and no books for months because the logic is slightly different if the faction is created (ragin mages fires as the first wizard to appear) or isn't created (there was already a wizard earlier) and fixes keep failing to factor in the arcane nature of this coding method. It's all because PostSetup is getting called twice in this case, probably once by the faction itself getting set up. Ack.

**Comment by Zth--** [comment]
Fixed here #23151
