### ISSUE TITLE
its a real bitch to add custom objectives to entire factions and announce objectives doesnt work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22708]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
a7fe90035c38e7f62b461cf4cd2f175b504e25b4

# Description
adding a custom faction objective via the check antags panel doesnt work and neither does announce objectives button

**Comment by DDihanov** [comment]
I tested this and it works fine. Any more info?

EDIT: The problem seems to be when adding a custom faction objective you don't get the prompt asking you what the objective should be and you just get the default "Just be yourself", but this seems to happen only from the first screen, if you click on the antag's role panel from Check Antags and set a custom objective from there it seems to work. It only allows one custom objective - don't know if this is intended or not.

EDIT2: Currently making a fix for this

**Comment by SonixApache** [comment]
The issue with custom objectives (`objective/custom`) is that you can only add *one*. 
After that you have to add a *freeform*, and after that you'll just have to pick from what's left
And beyond that, you have to VV the `gamemode -> factions -> faction with objective -> objective holder -> objective -> desc` to even be able to change their descriptions.

- adding a [VV] button to objectives (that leads to the objective holder) would be nice
- any kind of feedback for pressing the [announce objectives] button would also be nice, no idea if clicking it actually does anything

**Comment by DDihanov** [comment]
@SonixApache Check out my push, I think I fixed most of the stuff
