### ISSUE TITLE
Suggestion: Trim all unused comms/language keys

### ISSUE THREAD

**Issue by ValkyrieSkies** [d3athrow/vgstation13#22795]
It's pretty well known that assigning new comms/language keys is fucked at the moment because practically every single key is already assigned, so we could probably do with culling those that don't matter anymore seeing as we now have a new antag datum system that means we'll be adding new antags much quicker than before, and eventually some of these antags will require their own comm line or language. Also being able to add some more fluff languages in the vein of Sol Common would be nice too.

Shit that could do with being removed:
• :8 - Golem language (Pointless language, Golems would just speak the language of their creators)
• :z - Skeleton language (They're fucking skeletons why do they have their own language)
• :o - Unathi (Unused species)
• :j - Tajaran (Joke species)
• :k - Skrell (Unused species)
• :f - Slime (They're telepathic so why do they need a specific language)
• :k - Grey (Also telepathic, but probably the most defendable inclusion here)

Also it would be nice to see minds retain their previously known languages after transformation, though their ability to speak them could vary.

Stuff like cultspeak and binary obviously wouldn't transfer though.

[discussion]

**Comment by Blithering** [comment]
I would argue skeleton language should stay, as its the only one shared between two species at the moment. You could also combine slime and golem, make it one shared xenobiology language

**Comment by ValkyrieSkies** [comment]
Skeletons and Plasmamen are both just fucked up humans, why would they have an entirely independent language?

**Comment by DrSnips** [comment]
L and R seem to be some kind of hand language and I think that can be added to the remove list.
P isn't even a language really nor do any radio keys exist for it so I see no need for it.
Skeleton is shared by plasmamen and they are common enough to warrant it's existence unlike other races like skrell. Rattles are a language which is kind of funny.
Since slimes don't actually have the mental shitposting genetic power I think that one could stay. Rolling golem into it could happen but I don't think golems even need a special language like you said.

**Comment by kilozombie** [comment]
L and R are literally for speaking into radios in your left or right... pocket actually AFAIK, I don't think it's listed right in the code

**Comment by ValkyrieSkies** [comment]
When slimes speak it says they do so telepathically, it just comes out in a universally understandable language I think, so I don't think they need a unique racial one.

**Comment by DrSnips** [comment]
I'd like to pin the poor word choice on left over metr*id lore. As the local expert on the fictional biology of the species slimes don't have a reason to have telepathy.

**Comment by ValkyrieSkies** [comment]
Slimes don't really have a reason to have a language in general considering they're rabid little balls of slime made docile by water and slimepeople are just transformed people who would also just speak their own previous language.

**Comment by ValkyrieSkies** [comment]
Also sign language would be pretty cool now that I think about it, require free hands but not a free mouth, if you only have one hand it comes out garbled, and obviously can't be sent via radio. Add it to the possible roundstart languages for humans.

**Comment by kilozombie** [comment]
I'd actually be down for that.

**Comment by ValkyrieSkies** [comment]
It'd certainly add more flavour, and we could make deafness actually last until healed so it can be a serious disability with a roundstart option.

Because current deafness is really kinda just fucking nothing.

**Comment by brndd** [comment]
Why do the languages need to be global anyway? Couldn't they check if you can speak a language so that keys can be reused? This way eg. 1-5 could always be meme languages like Gutter, Tradeband, racial languages etc. and they could overlap because no one will ever know more than 5 of these.

Also sign language sounds dope and should totally be a thing.

**Comment by ValkyrieSkies** [comment]
AI know nearly every language, pAI have access to universal translation module.

**Comment by brndd** [comment]
> AI know nearly every language, pAI have access to universal translation module.

I thought AI only understood them all, but could only speak the various human languages like gutter and tradeband. For this kind of special cases it could be handled by the Set Default Language verb.

**Comment by Exxion** [comment]
The problem with having multiple languages use the same key is that no language precludes you from knowing another, so it would always be possible to get a conflict, even if you only knew two languages
If you make it so that conflicts move one of the languages to a different key, that means that the same language isn't always the same key

There's not really any reason I can think of that keys have to be only one character, though
I'm not sure whether or not you need a space after the key, since I always put one there, but even if you don't, you could just reserve some number of characters to never be single-character keys, and add the next character to the key if the first is one of those
This would multiply the number of available keys by just under (1 + number of characters reserved for this)
If somehow we ran out again, this could be repeated to three-character keys, and so on
The downside, of course, is that it would take a whole extra keystroke to speak in some languages

Another option is to just let the player set their own keys but then they'd *have* to do so if they got a language whose default key overlapped with a language they already had

**Comment by brndd** [comment]
>If you make it so that conflicts move one of the languages to a different key, that means that the same language isn't always the same key

What about having a single key for racial language? You will *almost never*\* have multiple of those, so the amount of keys freed by this would IMO be a good tradeoff compared to the minor inconvenience caused in the edge cases where you do have multiple racial languages.

\*only if you're a pAI, AFAIK, though I'm not sure if pAIs can actually *speak* every language either or if they just understand them

**Comment by SonixApache** [comment]
Could easily just avoid some of these by making the more rare ones double keys.
:kk or :gg or some shit.

I'd be against removing the keys altogether, though.

**Comment by ValkyrieSkies** [comment]
AI CAN speak all the languages they know, including the likes of Unathi, Skeleton and Golem.

**Comment by brndd** [comment]
You're not currently required to have a space after your radio key, so double keys are bound to ruin someone's \~workflow\~.

**Comment by Exxion** [comment]
The method I said above is explicitly designed to work without requiring a space

**Comment by ValkyrieSkies** [comment]
We could also adopt an open-close format for clearer key input, like :s: instead of :s so we can have longer keys, and maybe even alternative keys for newer players so they can use :service: because who the fuck knows what the service key is.

**Comment by SonixApache** [comment]
isn't it :d for :don't care?

**Comment by Killette2** [comment]
This is both a nerf for bable syndrome and a slap in the face for xenobiologist
