### ISSUE TITLE
Binary is too easy to miss

### ISSUE THREAD

**Issue by ValkyrieSkies** [d3athrow/vgstation13#22809]
As discussed in my closed issue talking about chat visibility, Binary chat is probably the easiest channel to overlook in gameplay due to its small font and lack of colour. Many newer Cyborg players fail to reply to a large amount of Binary at all because of this.

An increase in font size or bolding the text would really help fix this issue.

[goonchat]

**Comment by SonixApache** [comment]
many newfags also don't know how to use :b in the first place

What I think would be a big buff we could use as well as a solution for both your discussions would be to improve goonchat's highlight function.
More entries, case-sensitivity, per-slot saving... There's room for improvement for sure.

**Comment by Kitfox88** [comment]
Maybe some default highlighting applied at roundstart for stuff like your name, department channels, etc if it can be done? It'd be nice to indicate the proper department channel letter somewhere as well so that if you're on more than a few and don't have them all memorized you don't need to crack the wiki just to find out service is :d or the like
