### ISSUE TITLE
When a cyborgs battery is broken he can spacewalk

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22977]
(WEB REPORT BY: kharkov72 REMOTE: 206.221.180.138:7777)
# Revision
1ee89f95dfe4a866fae803311d3f423faaa26910

What in the goddamn

**Comment by Kitfox88** [comment]
stop revealing sillyclub secrets

**Comment by jknpj** [comment]
Christ

**Comment by MadmanMartian** [comment]
Now that the round's over, let me explain

I was an engiborg, deconstructing the gateway room because it was becoming hell, and a creature bit my cell off.

I floated downwards, where there was a window on a turf (Doesn't have to be touching you, just has to be on a turf) which let me move freely, rather than spacewalk.

This ain't a bug.

**Comment by jknpj** [comment]
Scared me for a second
