### ISSUE TITLE
Summon mannequins/statues spell for wizards

### ISSUE THREAD

**Issue by GoodG1448** [d3athrow/vgstation13#22981]
Just to have a spell that can have synergy with the staff of animation. It would create a random statue (marble or wood) or mannequin (cult or cyber), not sure if anchored or not but it doesn't matter since they will start walking on their own once animated. Maybe a cooldown of 15-20 seconds and a cost of 20 points?

[featurerequest]

**Comment by DrSnips** [comment]
I don't see why you would ever take it since you can literally animate a whole bin of paper for free and it would give you the same results.
I think it would work better as a feature to the staff animation like an inhand use to swap to 
a summon statue and it consumes a shot to summon one. Swap back and animate it.

**Comment by GoodG1448** [comment]
>  think it would work better as a feature to the staff animation like an inhand use to swap to
a summon statue and it consumes a shot to summon one. Swap back and animate it.

I guess that could work. The idea was suggested because I remember seeing animated statues (at least marble ones) do 30 brute per hit.

**Comment by DeityLink** [comment]
How 'bout dis den?

**Comment by robintime** [comment]
what the fuck
