### ISSUE TITLE
Eye Surgery

### ISSUE THREAD

**Issue by groosbstrd** [d3athrow/vgstation13#23027]
I was doing eye surgery the other round and I noticed a weird issue.
If you are using the advanced scalpel in the switch tool (dunno if this applies to it when not in a switchtool) it will always cauterize the incision even if you haven't used a scalpel.
Also, you can use surgery tools an infinite number of times at any point. It's kinda weird. Like: Scalpel->eyes 10000000x
Retractor->100000000x
>hemostat->100000000x
>cauterize->100000000x
When you do eye surgery
At first I thought it had to do with mechanical eyes but I had another patient with organic eyes and the same thing happened. I'm no coder so I don't know but I will try to recreate it on the test serb soon.

**Comment by groosbstrd** [comment]
[https://imgur.com/a/XMYR9jI](url)
Isn't the exact same as with the advanced tools but yeah. It's a little weird. I dunno the name of the advanced scalpel so I dunno how to spawn it. But eye surgery is kinda fucked.

**Comment by groosbstrd** [comment]
[https://imgur.com/a/Xqr0HzV](url)
got the advanced scalpel
You can see in the pic that either mode will always cauterize. This kinda fucks up the switch tool.

**Comment by groosbstrd** [comment]
I'm no good at github let's try this instead
https://imgur.com/a/udOMR0u
https://imgur.com/a/IBiYdVm

**Comment by groosbstrd** [comment]
https://imgur.com/a/qoYTJRy

**Comment by groosbstrd** [comment]
point of the last pic is to show that the advanced scalpel will always cauterize despite the mode it is in

**Comment by Kammerjunk** [comment]
probably fixed by making sure the can_use() procs of `cut_open` and `cauterize` in [eye.dm](https://github.com/vgstation-coders/vgstation13/blob/9019dd44ee57c8bd421fa0df8c8c5fd34d089023/code/modules/surgery/eye.dm) do literally _anything_
like checking for `target.op_stage.eyes`. look at how the different steps set it in end_step() and how `lift_eyes` and `mend_eyes` do it in can_use()
basically just rotate the value around so that can_use() checks for it being one less than in end_step() in each of the 4 steps

**Comment by Kammerjunk** [comment]
maybe someone mark it as "easy fix" because I'm like n→100% sure that's the fix

**Comment by Cyadox** [comment]
Not exclusive to the laser scalpel - as @Kammerjunk mentioned it is a bug because the original coder didn't put all the checks in place to confirm which stage of the surgery you're in, and it solely exists because eye surgery is unique and doesn't reference the surgery datum procs like it should.

However, the reason why I'm commenting is I'd like to add this bug has existed for _6 or more years_, and even when I played back in 2015-17, it was a well known issue that everyone seemingly ignored because meds were (and still are) faster than surgery.
