### ISSUE TITLE
Cult Act 3 needs a rework - Here's my suggestion

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#23031]
![Screenshot 2019-05-25 00 18 49](https://user-images.githubusercontent.com/32942106/58365120-50089280-7e85-11e9-9319-a84dfd4623f6.png)

Tell me. What do you see in this picture?

Suffering? Misery? The dying wishes of a hundred souls, torn in anguish yet heard by none?

I tell you what I see in this miserable depiction. I see a rework.

### THE REWORK FOR ACT 3 - THE BLOODBATH

Blood tiles are awful. Instead, let's replace it with a summoning ritual.
After doing the sac, the bloodstones shall spawn as normal. One of these bloodstones will serve as the anchor, the place where Nar'sie will rise. It has more HP than the others and should also glow or something. Nar'sie will be summoned in 10 minutes if this stone is not destroyed. It will also not be the original stone, to prevent space bases.
The 4 other bloodstones serve as tools to fasten the process, reducing the time by 1.5 minutes each, down to 4 with all of them active. Once it's fully charged, act 4 proceeds as normal.

Thoughts?

**Comment by Blithering** [comment]
While I think having to spread blood once the bloodstones are up and everyone is in fight mode is counter to the escalation of the round, I don't like this idea. It makes cults have to cross their fingers and hope that the one important bloodstone doesn't spawn in the middle of a department where some botanists with hatchets can destroy it before anyone else gets there. (Also the dancing phase is a laugh)

Might as well throw my ideasguy hat on and pitch my suggestion as well
Have the cult be able to see rifts at the points chosen for bloodstone locations, and have to spread blood (possibly in a pattern? make some happy little trees?) in those locations in order to raise them in the first place, meaning they have to either find an excuse for why they're painting a department red, convert the place to keep them quiet or go loud and hold the territory. This has a plus of forcing there to be at least one cultist in place to defend each stone when they pop. also something something, bring back harvesters, maybe have them only creatable by using a soul gem on the bloodstones, and able to harvest victims to teleport back to and heal bloodstones.

**Comment by ShiftyRail** [comment]
My own personal idea is simple.

- instead of spraying blood randomly on the station, have the mission to completly dip in blood a particular area. Bridge, medbay, etc, whatever.
- when that area is covered in enough blood and shit, a bloodstone raises and you need to sacrifice an implanted person or the chaplain.

Simple as that. Buff the bloodstone HP if needed.
It solves the annoying "search and destroy" aspect of act IV as well as the underwhelming spray blood jectie, while centering the fight in a single place rather than all over the station.

**Comment by ghost** [comment]
I personally think the blood spreading idea is completely arbitrary, since the best way to spread blood is through a grenade or spray bottle as opposed to actual killing, which does almost none in comparison. I feel like the idea should be reworked entirely to better suit the combat theme.

The stealth idea Blithering suggested doesn't really fit either, and my idea was also pulled out of my ass to bring up discussion. I guess my goal in my idea was to turn focus towards combat instead of blood, which fits thematically but gameplay-wise makes no sense.

**Comment by SonixApache** [comment]
just add more sacrifices while also spreading blood
have to sacrifice one non-cultist per bloodstone
maybe spread blood around the BLOODstones as well

**Comment by groosbstrd** [comment]
It'd be pretty easy to cuck cult if you could just look at and see which bloodstone will summon narnar
