### ISSUE TITLE
Should revs end when head revs die/leave?

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#23126]
I ask because it tends to turn into extended after a crew "victory" with a single rev left alive and people mindlessly roaming maintenance looking for valids

**Comment by boy2mantwicethefam** [comment]
Yes
It used to be this way and people thought it wouldn't lead to gunk because a big chunk of the crew is/used to be antags tasked to kill a select few people. But suddenly only a bunch of head of staff die and the round HAS TO end because the station is in an irreparable state due to the lack of a few players versus the lack of a lot of players
If you ask me it should either end or killing heads of staff should continue the round but everyone gets de-revved and turned into non-antags

**Comment by ShiftyRail** [comment]
We live in a dynamic society in which new antags can spawn

What we need is a clear announcement of when revs are all out of commission, combined with the faction being deleted so that even if they get revived again, they lose their antag status (we can RP it as the brainwashing stopping to have effect, or something.)

>If you ask me it should either end or killing heads of staff should continue the round but everyone gets de-revved and turned into non-antags

What an horrible opinion

**Comment by boy2mantwicethefam** [comment]
*a

**Comment by DamianX** [comment]
just bring back secret then

**Comment by SonixApache** [comment]
revs needs a rework to fit in better with dynamic, the way it works now is a definite relic of the age of bay
round definitely shouldn't end if all revs / heads of staff are dead
