### ISSUE TITLE
zombies are almost indistinguishable from regular humans

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23181]
(WEB REPORT BY: helpmepls REMOTE: 206.221.180.138:7777)
this is something that ends up happening almost every time zombies do
zombies with clothing on look and walk and talk almost identical to crew so people confuse them for crew and get zomb'd.com more often than not
zombies should have stink lines or some other visually recognizable difference thanks for reading

**Comment by jknpj** [comment]
just make them speak shit like horrors, this ain't a romero movie

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Giving them a different hitsound/attack animation might help too

**Comment by SonixApache** [comment]
catbeast-like word replacement, but with random capital letters and the occasional `BRAINSSS...`

**Comment by Blithering** [comment]
I think its intentional that they look human like, particularly if they're fresh, but having their speech sound like muttering for brains to non-zombies sounds good.

**Comment by Killette2** [comment]
I like a moving stink lines idea for the sprite myself and it's the first thing I thought of when reading the title so it should come natural to anyone who encounters it (unless they're charismatic enough to just convince a newbie that they need a shower). Makes them easy to visually spot, since you can only do so much when it comes to detail with what we're working with it. some occasional brains... line would be good in addition

**Comment by Blithering** [comment]
I don't like the stink line idea personally, it kinda feels too cartoony to me. Evolved zombies change to a more noticeable sprite already, so I'm thinking the biggest issue is equipment covering anything but the crimson head claw. Maybe have zombification randomly unequip and drop equipped things?

**Comment by west3436** [comment]
Essentially closed via #26123.
