### ISSUE TITLE
Eyedroppers don't work anymore

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#23237]
I used a dropper full of chloral on a fellow changeling. He had no eye protection, mask, or helmets. I aimed at eyes. 5 or so times (some after this chat selection)  it gave a fail message that made no sense, I thought I just needed more chloral but he said nothing happened at all (no drowsy).

![dreamseeker_2019-06-12_19-16-05](https://user-images.githubusercontent.com/5169310/59395026-ec6cd900-8d4f-11e9-856d-edd2ff395860.png)
![dreamseeker_2019-06-12_19-32-08](https://user-images.githubusercontent.com/5169310/59395028-ed9e0600-8d4f-11e9-8716-b0e655fd2511.png)

**Comment by Kurfursten** [comment]
dropper.dm L66-69 handles successful eye squirt, it does cause a touch reaction and remove reagents but doesn't actually transfer any because of the return at L70 (means that only non-mobs get dropper reagents transferred to them). The "closed" message is being sent by reagent_containers.dm L96 in /attack(), because you are attacking someone with a closed reagent container. (Being closed means that you can't pour things into it our feed it to people, like a syringe bloodbag or dropper) Since the squirt happens in afterattack it sends the closed message first.

This seems to be the result of #16855 about 18 months ago. Before that, droppers used trans_to to send reagents. Perhaps there was some overlap between the attack behavior of reagent containers at that time. I'd like to hear @MadmanMartian 's thoughts, as he might remember why he implemented it this way.

**Comment by MadmanMartian** [comment]
Firstly, discomuffin why you so rude to killette? Secondly, I'm looking into it now

**Comment by MadmanMartian** [comment]
![image](https://user-images.githubusercontent.com/30557196/59440774-66a06a80-8def-11e9-8aae-9c3d9c088d6c.png)
certainly looks to be working from testing on a naked tajaran. The "dropper is closed" seems to be something else.

Were they wearing glasses?

**Comment by Killette2** [comment]
No, they had a clearly visible red eye sprite with nothing in front of them. Later they put on welding goggles after they killed me, but it was easy to tell that they had no eye protection at first assault. Someone suggested bio-protection such as shoes but it's beyond me.

**Comment by agentofzog2** [comment]
Oh yeah this shit.
For some reason droppers are stopped by MASKS
tried it on a guy with a blunt, didn't work, had him take it off, it worked

that should probably be changed

**Comment by Killette2** [comment]
I don't believe he had a mask but maybe he did. If so fixing that would be a step if not the solution.

**Comment by ShiftyRail** [comment]
Was fixed in #27116
