### ISSUE TITLE
Black Market Overhaul - Need Feedback

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#23701]
Y'all cupcakes have some strong opinions on the black market, and after 1 week of implementation there are many changes I would like to make based on feedback and my own observations.
Tl;dr
>Remove advanced uplink from bridge. Now spawns on vox trader station, it gives 10% discount on everything. 

>Remove SPS alerts.

>Remove meme items like portal gun, make it fit more a "low quality illegal goods" type of thing.

>New buyable section: local transaction, any player can anonymously scan an item, set a price and description, then teleport it up. 20% transaction fee. Beware of scams.

>New roundstart "antag", Black Market Operative. One spawns every round if possible. Like Vox raiders, but has special responsibilities. Read.

The Black Market Operative will be a pseudo-antag, essentially serving as the station's anonymous overseer of sales. He gets a special uplink (or hidden PDA app) that shows all transactions and profits and allows him to manipulate market prices. His goal?

>Conceal Black Market activity whenever possible and make as much profit as possible.

There are three possible roundstart scenarios: no BMO, BMO but no Big Boss, BMO with big boss. Any person can choose to contact the "local BMO" if there is one through their uplink and request for special goods through an anonymous chat. The BMO can acquire it themselves or contact big boss, AKA admemes. If the buyer asks for some shit like a portal gun, the admin can inform the BMO that it will cost 6000 credits. If the buyer accepts, the portal gun is teleported to the BMO and he handles the transaction. If the amount or stipulation is not paid (be creative), then the BMO can send in the mafia to get payment from the guy one way or another. Wasting the Mafia's time will likely get the BMO killed as well, or a ban from the role if you abuse over and over.

For the most part you shouldn't be allowed to murderbone with this role. You can do a little fuckery but it always has to be in the interest of making money. I would like to add a roundend stat for the black market earnings as well and make it a competition similar to how Vox Raiders had it.

>New Vox Trader role, Shady Dealer. Has greater chance of being the BMO, but will be deported from station on sight.

Thoughts?

**Comment by Kammerjunk** [comment]
Discount Deity's On the Go Feature

**Comment by Kharkov72** [comment]
Actually sounds like good changes, especially people being able to sell things themselves.

**Comment by DrSnips** [comment]
I appreciate the moving of the special uplink it just felt kind of weird. Beyond that and the following issue I have no other gripes.
FLAVOR STUFF AUTISM WARNING IN EFFECT BEYOND HERE.
A black market is defined as illegal trade and when you say that the black market is NT approved and whatever it completely defeats the purpose of calling it a black market because at that point it's just a market. The easiest solution is to just replace all instances of NT hosting it to Discount Dan/vox traders hosting it. This would satisfy my autism.

**Comment by Kurfursten** [comment]
Better Dan than traders, don't want to encourage any more theft gimmicks

**Comment by kilozombie** [comment]
>Remove advanced uplink from bridge. Now spawns on vox trader station, it gives 10% discount on everything.

Yep, sounds good

>Remove SPS alerts.

Makes sense too. I recommended this early on and it doesn't seem very great especially with these new proposed changes

>Remove meme items like portal gun, make it fit more a "low quality illegal goods" type of thing.

This is good and will also help with making it stand out as unique instead of just another "you can get wild items but you probably won't but you *can* so we can pretend that those items are obtainable"

>New buyable section: local transaction, any player can anonymously scan an item, set a price and description, then teleport it up. 20% transaction fee. Beware of scams.

Fucking legendary. This is exactly what was needed and I might start playing spess again just to try this out.

>New roundstart "antag", Black Market Operative. One spawns every round if possible. Like Vox raiders, but has special responsibilities. Read.

HHhhHHHhHhHHHghhghghHH??????

Okay, so this along with the rest of the explanation: it's fucking weird. It could be positive, but it just strikes me as too flimsy at present. Who's going to play the mafia? Why is it structured in this odd way?

Take a page from good design and try slimming it out to be as compact and purpose-built as possible, IMO. The idea of somebody on the crew being a soft antag trying to get everyone selling stuff is fun, but the peripherals and admeme influence seem like they'll bog it down.

**Comment by ghost** [comment]
>Okay, so this along with the rest of the explanation: it's fucking weird. It could be positive, but it just strikes me as too flimsy at present. Who's going to play the mafia? Why is it structured in this odd way?

Perhaps, I just wanted a way for people to buy big-ticket items and make it interesting. Having a Black Market Operative on station adds a new depth to the game, and I think it could be interesting. I'll probably do baby steps though, add player market and do the other changes first.

**Comment by spoonylove** [comment]
Space craigslist? Nice

**Comment by kilozombie** [comment]
@GlassEclipse If you're going to give us Space Craigslist, go full fucking hog and give us an ingame anonymous message board named Starchan on a per-round basis
You'll win hearts and minds

**Comment by ghost** [comment]
You can just make spesschan on the newscaster, you know.

**Comment by SonixApache** [comment]
add a line to spesslaw about the legality of black market operations

**Comment by GeneralVeers25** [comment]
I agree with a lot of what Kilozombie said.

I like the concept of the black market, but I would rather see this type of content added to cargo, the merchant computers we already have, or Traders. Add content to existing jobs, rather than completely new ones.

If you're pushing for this to be a player-based underground economy, you may also want to consider some way to encourage the various departments with points-of-sale (primarily the Bar and Kitchen, but also R&D) to actually use them.

**Comment by tuypo1** [comment]
Giving traitors a way to move items between them with ease is absurd

**Comment by ShiftyRail** [comment]
Where we are going, we don't need no black market.
