### ISSUE TITLE
Sending plasma ore/sheets via cargo shuttle doesn't do shit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23735]
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
1fa0d99b954bbb69ba250a6ca46673289e383f98

# Description
I mined a shitload of plasma, tried to send it back to centcomm inside a crate but the crate never got removed from the shuttle when sent and called back.

# Steps to Reproduce
1- Get loads of plasma sheets
2- Put them inside a crate and close it
3- Call the cargo shuttle
4- Load the shuttle with the crate containing the plasma sheets
5- Send it to centcomm
6- Call it back
7- The crate is still in the shuttle

# What you Expected
Money for cargo

# What Actually Happened
No money

**Comment by Kurfursten** [comment]
This is being caused by a runtime where the GetMaterial on the plasma sheets returns 0. It's also a recent bug because a few weeks ago I had no trouble.

It only checks for plasma sheets, and that file (both materials.dm and supply_shuttle.dm) hasn't been changed since we were having no trouble, so it may be a problem with materials_list getting populated or GetMaterial.

Get a look at this warning + runtime:

```
## WARNING: getMaterial(): Unknown material plasma!
[12:06:52] Runtime in supply_shuttle.dm,155: Cannot read 0.value
  proc name: sell (/datum/subsystem/supply_shuttle/proc/sell)
  usr: Frank Bickerson (durgen) (/mob/living/carbon/human)
  usr.loc: The floor (201, 232, 1) (/turf/simulated/floor)
  src: Supply Shuttle (/datum/subsystem/supply_shuttle)
  call stack:
  Supply Shuttle (/datum/subsystem/supply_shuttle): sell()
  Supply shuttle console (/obj/machinery/computer/supplycomp): Topic("src=\[0x21129143];send=1", /list (/list))
  /datum/nanoui (/datum/nanoui): Topic("src=\[0x21129143];send=1", /list (/list))
  Durgen (/client): Topic("src=\[0x21129143];send=1", /list (/list), /datum/nanoui (/datum/nanoui))
  Durgen (/client): Topic("src=\[0x21129143];send=1", /list (/list), /datum/nanoui (/datum/nanoui))
```

That warning gets thrown here


```
/datum/materials/proc/getMaterial(var/mat_id)
	if(!(mat_id in material_list))
		warning("getMaterial(): Unknown material [mat_id]!")
		return 0

	return material_list[mat_id]
```


https://github.com/vgstation-coders/vgstation13/blob/0d4bd808ece587842f3fe07379bd0f8fadfa35fa/code/modules/mining/materials.dm#L103

**Comment by MadmanMartian** [comment]
Gonna work on this now
