### ISSUE TITLE
Quick Idea Poll: "Remove the ability to examine contents of a drinking glass (would still work in other containers such as beakers or shakers)"

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#23762]
Issue: Right now the only way to "poison" or trick people into ingesting suspicious reagents is with badly named pills. That's also why floor pills are a popular meme I guess. Anyway, I don't know how far back have we been able to just examine glasses to get their content, but I think it's kinda detrimental to the bartender experience (traitor and otherwise).

I mean sure there's the "black color" reagent you can hide to a glass to turn it into an "international drink of mystery" but that's kinda on the nose and not subtle at all.

So here I thought, hey maybe we could go back to only beakers and other chemistry containers having detailed readings. Paranoid people could still carry a beaker to get the exact contents out of a bar drink, but that'd still require to go an extra step beyond shift+click.

I know that'd be controversial but since it's just an idea for now I'd like your opinions on this.

**Comment by MadmanMartian** [comment]
Recently fixed it so that black colouring obscures the reagents in beakers and such

**Comment by MadmanMartian** [comment]
Maybe have a chem analyzer implant that the bartender starts with?

**Comment by Irradiation** [comment]
>Scientists
>Having PDA reagent scanners
>Scientists leaving science for other reasons than getting mech balids

**Comment by beesil** [comment]
Consider bringing back #19092

**Comment by DrSnips** [comment]
PDA scanners were removed a long time ago. Only chemist, cmo, and chef(?) have them now.
A side effect that might come from this change is bar drinks becoming less popular due to them being mystery juice now. 
The way I would do it is have bar glasses able to have 1 pill hidden in them where its only able to be seen by chance depending on the pill size(actual contained reagents of the pill). When you take a sip of the drink the chance to consume the pill held would be calculated by doing 1/(reagents left in glass/5), the less sips left the more likely you are to consume the pill, to simulate pills not always floating. The pill would attempt a reaction check first and if they do react the pill dissolves like things do now. This is to prevent glasses of water+potas pill becoming bombs.

**Comment by DeityLink** [comment]
That'd be really awkward.

**Comment by DrSnips** [comment]
I can kind of understand what you mean since bartenders lack access to pill making or was is from something else. I thought I would put a "realistic" solution out there.

**Comment by DeityLink** [comment]
Just assume that beakers have small electronic displays on them, and that drinking glass don't.

**Comment by Exxion** [comment]
Hard job restrictions like that are bad
You could do it by giving the bartender an item to do it but that would just be a reagent scanner

**Comment by Intigracy** [comment]
#19092 was a good PR

**Comment by Durgen** [comment]
Is the shaker a child of beaker?

**Comment by Killette2** [comment]
Bring back color PR

**Comment by ShiftyRail** [comment]
I'm torn about this.
On the one hand, this makes poisoning things a possibility rather than pure theorycrafting.

On the other hand, I don't believe restraining things to specific jobs is a good idea in the world of ss13.

>So here I thought, hey maybe we could go back to only beakers and other chemistry containers having detailed readings. Paranoid people could still carry a beaker to get the exact contents out of a bar drink, but that'd still require to go an extra step beyond shift+click.

Yes, please. Medbay will be so much of a pain without that, all medicine looks the same.

**Comment by DeityLink** [comment]
My intent is definitely not to remove it from all reagent containers, ONLY drinking glasses. And it's true that we'd rather keep the game free of job-specific perks, so I've updated the title to reflect that.

Bartender would still be able to get detailed contents from his shaker, which I guess removes the need for a reagent scanner like what @Exxion suggested.

**Comment by PaulRitter** [comment]
give this some sort of tag so you can search for it more easily

**Comment by beesil** [comment]
Could allow people with the alcoholic gene to examine reagents in drinking glasses, as well as give the bartender a pair of beer goggles that do the same.

**Comment by DeityLink** [comment]
>beer goggles

That's awfully specific. As for the alcoholic gene doing that, I think it'd only make sense if you had to take a 1u sip.

How many reagents are deadly even at 1u?

**Comment by AI-Is-Rogue** [comment]
Drinking glasses already obscure liquids if it has too many unique ones inside of it, what if instead it made you unable to see that there are other reagents aside from the reagent with the largest quantity?

**Comment by DeityLink** [comment]
That's a sensible suggestion. I like it.

You could read "the glass is filled with X units of what looks like [main reagent]"

**Comment by beesil** [comment]
I mean "eyewear that allows the user to identify reagents in drinking glasses" by beer goggles, the name is just silly flavor. AI-Is-Rogue's idea is better anyway though.
