### ISSUE TITLE
The splashscreen for lamprey is not limited to lamprey

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#23814]
so it just breaks if it gets picked
![image](https://user-images.githubusercontent.com/6307265/62819923-796bbd00-bb5c-11e9-87d4-d32b509355af.png)

**Comment by kilozombie** [comment]
Intended for it to show up, unintended for it to break.

It shouldn't break if it gets picked except on local copies which doesn't have lampreysplash.dmi
The solution would be to move lampreysplash.dmi to the actual repo instead of having it in the sekrit repo. But if that's not the problem, let me know
If having it randomly appear isn't desired, the solution snowmap takes it moving the splash image out of /splashworks, so I'll have to change a little bit of code too, but it's plenty doable.

**Comment by DamianX** [comment]
I don't know why we would want a splashscreen that reads **LAMPREYSTATION** on any station but lamprey.

**Comment by DamianX** [comment]
This is still happening after lamprey was merged in the main repo.
It seems to be because the icon_state in lampreystation.dmi is `"lamprey` instead of null

**Comment by kilozombie** [comment]
Oh, that makes sense.
