### ISSUE TITLE
Cyber horror cyber horror

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23874]
(WEB REPORT BY: kereanil REMOTE: 206.221.180.138:7777)
# Revision
207995e940f4ae739f9921adfa8084f0ad12623c

# Description
Multiple cyber horrors stacked inside one mob, giving it insane HP

# Steps to Reproduce
No bloody clue
Maybe something about how they reproduce?

# What you Expected
A cyber horror actually being killable

# What Actually Happened
monkey (817) cyber horror cyber horror cyber horror cyber horror cyber horror cyber horror groans, "G@#!$ H@!#%, H!@%%@ @!#"
Said monkey had 400k (400,000) health, according to an admin

**Comment by MadmanMartian** [comment]
unexpected consequences of me making it so all mobs process reagents. Seems somehow a cyberhorror ended up with enough medical nanobots to turn into a cyber horror, making a recursive horror.

**Comment by MadmanMartian** [comment]
Think I've narrowed down how this happened;

The person who made the cyber horrors used an antag belt, which contains simple animals whose faction is set to your reference.

Because of this, any cyber horror they would make would not be on the same faction as themselves, so they would both attack one another, creating recursive cyber horrors as their flailing injects one another with medical nanobots.
