### ISSUE TITLE
Forking a monkey cube makes you instantly eat it before eating it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23871]
(WEB REPORT BY: awadwduwu REMOTE: 206.221.180.138:7777)
# Revision
89d2b4533a61782b236c4ccedcdfb28919b3efee

# Description
Using a fork on a monkey cube makes you eat it without eating it, causing a malformed monkey to form in you, while the cube is still on the fork

# Steps to Reproduce
Fork monkey cube
Get monkey'd

# What you Expected
Fork monkey cube, get a bit of a monkey cube to eat or have it not let me fork it

# What Actually Happened
It had me eat it instantly while the cube was on the fork despite me never eating it

**Comment by boy2mantwicethefam** [comment]
King Crimson has erased the time in which you ate it

**Comment by veles2001** [comment]
It looks like `/obj/item/weapon/reagent_containers/food/snacks/proc/after_consume` is called in `/obj/item/weapon/kitchen/utensil/fork/proc/load_food` when you put the last bite of food on the fork instead of after you eat it. The monkey malformation happens in `/obj/item/weapon/reagent_containers/food/snacks/monkeycube/after_consume`, so the monkey cube thinks you ate it even though you just poked it with a fork. I think the `after_consume` call should be put somewhere in `/obj/item/weapon/kitchen/utensil/fork/proc/feed_to`.
