### ISSUE TITLE
Super fart power allows you to fart through walls

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#2387]
You can blast people in other rooms with your super fart. I think it is hilarious but still needs a fixing.

**Comment by d3athrow** [comment]
honestly dont know the best way of fixing this as other than a* theres nothing that lets you respect dense objects.

**Comment by Zuhayr** [comment]
Since it's a gas it should probably use a flood fill.

**Comment by clusterfack** [comment]
You could check mobs in regular view() without any vision flags, this would still allow passing through windows and space but not through any walls that are blocking your vision of an area.

Or you could use a zone I believe and check mobs within a certain range of the user within that zone, since zone's entire purpose should be to measure areas that gases can pass into and through.

**Comment by ComicIronic** [comment]
Looking at the code, it already uses view.

**Comment by clusterfack** [comment]
That's exactly the issue, if it uses view while a user has xray, he farts through walls.

We need to make some procs that give mobs in view() depending on what various combinations of flags could be activated, instead of the ones that currently are.

**Comment by clusterfack** [comment]
Basically toggle off all vision flags, get mobs in view, toggle them back on, return mobs in view.

**Comment by clusterfack** [comment]
It would have been nice if byond already had these

**Comment by d3athrow** [comment]
To have it ignore your vision flags just do like
```
var/turf/T = get_turf(src)
for(things in T.view(7))
     //do stuff
```
