### ISSUE TITLE
Virtual hearers are being dropped from mobs

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#24268]
Several players reported this:
- They CAN talk but
- Can't hear self
- Can't hear others
- The "You can almsot hear someone talking" message doesn't appear
- Speech bubbles might not appear?
- Can't *shake
- Can *wave
- They don't have the deaf mutation
- Rejuv doesn't fix it
- Restarting the client doesn't fix it
- Changing to a different mob fixes it

@accipitermaris experienced it, maybe he can say something else about it

**Comment by boy2mantwicethefam** [comment]
the do_delay change must be behind this....

**Comment by MadmanMartian** [comment]
Their virtual hearer had either disappeared, or been lost somewhere.

Adding a new virtual hearer to them fixed it.

**Comment by DamianX** [comment]
paging Dr. @Exxion - I think the GC changes could be behind this

**Comment by SonixApache** [comment]
I ran into this on a player and fixed it by monkey->demonkeying the affected.

**Comment by Exxion** [comment]
If it's happening right now then no, the GC changes could not be behind it because they haven't worked since Pomf commented out `/datum/Del()` several days ago
Though since they're pooled, the fact that it's impossible doesn't mean it isn't the case, considering how unpredictable pooling is

**Comment by Exxion** [comment]
`virtualhearer`s override `resetVariables()` with an empty proc, so none of their variables actually get reset. This includes `gcDestroyed`. So it's theoretically possible for this to happen:
1. Some mob gets `qdel()`ed and successfully gets cleaned up. Its ref stays in the queue forever because one of the ways it would be removed is commented out and the other is bugged.
2. A `virtualhearer` is created and takes over that ref.
3. The `virtualhearer` gets returned to the pool, causing its `gcDestroyed` to be set.
4. It gets removed from the pool and used before it gets hard deleted by the GC. Because of the `resetVariables()` issue mentioned above, its `gcDestroyed` was never unset.
5. The GC eventually gets to the ref, and sees that the object it points to has a true `gcDestroyed`, and thus hard deletes it.

If that's actually what's happening, the solution is to just reset `gcDestroyed` in `/mob/virtualhearer/resetVariables()`
Or remove that proc entirely so that it calls the parent instead, but there's probably a reason it's set up how it is

**Comment by DamianX** [comment]
I haven't seen this happen anymore so I assume it was fixed.

**Comment by Exxion** [comment]
It was *mostly* fixed by re-fixing the GC queue, but it can theoretically still happen. It's just extremely unlikely.
