### ISSUE TITLE
Local man antagonises nuke ops and admins with one simple trick

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#24271]
## Description of issue

If you have the disk on your person while crossing map boundaries, instead of transitioning to another z-level, you loop back to another edge of the station 

You c an (ab)use this to just evade nuclear operatives forever and dodge their shots.

Proposed solutions :
- disk just gets transported back to a random room on the station, the carrier still goes to another z-level
- carrier and captain are thrown back to the main station at light speed when this happens

**Comment by DrSnips** [comment]
Possible solution. The disk is dropped in space before you jump and you get put on the next z level.

**Comment by utilitas-** [comment]
Or just have it be the exact way it always was and prevent them from moving off z-level, period. No teleporting, no nothing. Z-level is just a solid wall to them as long as they have the nuke disk.

**Comment by Probe1** [comment]
I think we could find some exploits that way as well.  It would probably be cleaner to respawn the disk if the person carrying it changes z levels rather than it having a gameplay effect on the person carrying it.

**Comment by vampirebat74** [comment]
make it so that the barrier on the disk rips it out of your clothes/bags and breaks the container it's inside while also teleporting away, leaving the carrier on a different z. Fun for the whole family

**Comment by utilitas-** [comment]
No, it's foolproof. It's how many of the teleports and movements are already guarded. It already has a "gameplay effect" by blocking shuttle movement and teleportation if you have the disk, and it sure as shit will have a "gameplay effect" if it gets yanked out of your backpack for seemingly no reason. It's worked perfectly fine for six or seven odd years, and I have no idea which gibbering mung of """coder""" changed it again. Keep It Simple, Stupid, and stop fixing what is not broken.

**Comment by kilozombie** [comment]
>No, it's foolproof. It's how many of the teleports and movements are already guarded. It already has a "gameplay effect" by blocking shuttle movement and teleportation if you have the disk, and it sure as shit will have a "gameplay effect" if it gets yanked out of your backpack for seemingly no reason. It's worked perfectly fine for six or seven odd years, and I have no idea which gibbering mung of """coder""" changed it again. Keep It Simple, Stupid, and stop fixing what is not broken.

What the fuck are you on about, man?

There was a round where a guy abused the current behavior to make it virtually impossible for nukies to get the disk. That's what the issue is about. That's why it's being proposed for a change.

**Comment by kilozombie** [comment]
> No, it's foolproof. It's how many of the teleports and movements are already guarded. It already has a "gameplay effect" by blocking shuttle movement and teleportation if you have the disk, and it sure as shit will have a "gameplay effect" if it gets yanked out of your backpack for seemingly no reason. It's worked perfectly fine for six or seven odd years, and I have no idea which gibbering mung of """coder""" changed it again. Keep It Simple, Stupid, and stop fixing what is not broken.

You could hang around the edge of the z-level and jetpack around to juke bullets. Additionally, since people can't actually go to the edge without teleporting first, it would be nearly impossible to retrieve the disk if it was right on the edge. You might even be outside of normal view radius.

**Comment by ShiftyRail** [comment]
I think utiltas's suggestion keep a "tactic" that is fairly risky, but makes sense

**Comment by Probe1** [comment]
Sorry I think you misunderstood me @utilitas- .  Rather than continue to maintain an increasing pile of exceptions and catches to keep the nuke disk on the station I think we should just run a check and if it leaves z1 delete and respawn.  

That way no one has a clever advantage, no ones accidentally adding new ways to get it off station, et cetera.  One thing to maintain.  One goal.  Easy and done.

**Comment by jknpj** [comment]
Sounds like an administrative issue. Not saying it couldn't be improved code-wise, but as long we keep tweaking it code-wise people will find a way to abuse it since they know nothing will happen to them if they do.

**Comment by SonixApache** [comment]
Possible solution: Ban whoever does this for a month.

**Comment by utilitas-** [comment]
I mean, it'd simplify the code, but it wouldn't simplify it from the player's perspective because it already is fairly straightforward. If you have the disk, you can't even theoretically go off-station with it. Period. The only advantage it gives - which I've inadvertantly exploited - is that you also cannot be tele-whisked away, which is a double-edged sword if you get fucked with your disk on-person.

Which just make me think of a new exploit. Find the disk, then telesci it away. Current system, you can't. Straight up and simple. In the new system, if it's off z-level, it gets deleted and respawned at a random location. So now, with SPS and GPS, you'd be able to keep a watch on whoever's holding the disk and whisk them away if the SPS beeps or they scream hard enough. If it deletes and respawns at a random location, you've now complicated things a bit and can keep doing that forever and ever as long as you can find the disk in time and stand on it with a GPS. If it doesn't delete and respawn, then you've rescued the disk carrier and also can keep doing that as long as they have their SPS on them.

Blocking is just the simplest solution. I don't think it's particularly difficult to keep track of it: if you have the disk, you don't go anywhere.

Best course of action would be to keep people with the disk from being able to go past the imaginary "edge" of space where most everyone would go to a new z-level, but I'm pretty sure it already did that. I also don't think it should get deleted and respawned if you, say, launch it out the chapel mass driver. If you're stupid enough to let it bounce off the z-level's edge, you deserve to have it nabbed by a syndiecunt. Just add a fluff sticker to the nuke disk's description that reads "NOTE: DOES NOT LIKE BLUESPACE. DO NOT SPACE."

**Comment by Probe1** [comment]
We aren't banning people because they're clever and our code isn't.

**Comment by utilitas-** [comment]
Instead, we're dumbing our code down so even clever people can't use it.

**Comment by Probe1** [comment]
We're not doing anything yet.

The nuke disk was never meant to be a powergaming or strategy item to manipulate how your character travels through the world.  It was given some sanity so you can't cheese the fuck out of a game mode.

**Comment by kilozombie** [comment]
>Best course of action would be to keep people with the disk from being able to go past the imaginary "edge" of space where most everyone would go to a new z-level,

Let me reiterate: that is highly exploitable. Stand on the edge, out of view, and walk around the edge of the z-level. Nobody can approach you and bullets can't even get to you-- they will be teleported off before they get near.

>you've now complicated things a bit and can keep doing that forever and ever as long as you can find the disk in time and stand on it with a GPS

The nukies also have pinpointers and likely more manpower and weaponry than you. If it's a race to find it, they will find it first, and they will probably kill you too. This isn't an exploit.

>Instead, we're dumbing our code down so even clever people can't use it.

Nice, taking a chance to compliment yourself while showing your ignorance. A PR hasn't even been made yet-- solutions are only being proposed.

Exploits have been in spess since the beginning and when they're not harmful to the game but they're fun instead, they generally remain in. Keep in mind the reason this discussion is being had is because of all things in the game, being able to keep the nuke disk forever is *very* disruptive to an ops round.

Finding a solution to that is not going to be perfect either way. However, if the disk is teleported at random, it at least prevents someone holding onto it forever, which both the current method and 'previous method' allow. If it's deleted when it leaves the z-level, that means that even if you throw yourself out a window, neither you nor the ops will know where it will go. It evens the playing field in a way which prevents stupid cheese.

You seem like you're really invested in this, but maybe I'm projecting a little, because I've had stuff like this where I find something cool and it's removed by c*ders. But especially in this instance, it's important to examine it critically and think about the actual ramifications of each change. The edge of a z-level has a massive bounding box of teleporters, and if you could stand there, it wouldn't be possible to attack you. Stuff like that is usually kind of a faux pas.
