### ISSUE TITLE
You can't resist.

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#2428]
Maybe I'm missing something here, but there is no resist button or command.

**Comment by Arthurdentist** [comment]
I did some testing after this was pointed out to me ingame by someone. You can resist whilst standing up but it seems you can't resist if you are buckled into a bed or chair.

To replicate: Get cuffed, have someone try and buckle you to a bed or chair, attempt to resist

Its entirely broken or at least seems to be, you might as well be straight jacket because you can't do anything about it.
