### ISSUE TITLE
Toward a "Planet" Snaxi

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#24319]
I thought I'd post this as a concept based on feedback I'd heard from some players. I want to make sure people are actually interested before I do the antifun part (read: wires, lights, pipes, and testing) since up until now I've just done the fun design bit. This would be a significant overhaul of the EngCargo station - other stations would get this later, but this is what I have.
* New vehicle bay -- why not have MULEs? Now that they can trek across the snow, seems reasonable. Also has a warehouse for future snowmobiles.
* New 'frozen core' -- this is the key to allowing snaxi to eventually become a full 'surface' map because it is a bunch of ice that acts like space (with pressure). Engineering should be able to cool their engines without need for space exposure.
* Maintenance no more! -- maintenance is something for space stations. Snowmap already has plenty of places to hide. The claustrophobic tunnel has disappeared in favor of a wide, public hallway.

Worth developing further, or bin it?
![Untitled](https://user-images.githubusercontent.com/9782036/65847841-d25c0400-e308-11e9-8bca-6dba3245cbdd.png)

Note to self: vehicle storage would be a great place to put a classic cargo train. What better map for one as a roundstart perk?

**Comment by ghost** [comment]
The ghetto bar being iced in was the best part, though!

**Comment by Kurfursten** [comment]
I talked to plosky about it and we may return it to its icy tomb somewhere _further away_ from the real bar

**Comment by Kurfursten** [comment]
Note to self: vehicle storage would be a great place to put a classic cargo train. What better map for one as a roundstart perk?

**Comment by ComradeDispenser** [comment]
Can you make snowmobiles be able to have carts attached to them like a cargo tractor or otherwise have some kind of transport capacity, so cargo can carry crates to hand deliver them, paramedics can recover wounded, security can bring back arrested suspects, etc. via snowmobiles?
The extra mobility they provide would be a bit neutered if you needed to get off it and walk to move anything.

**Comment by Kurfursten** [comment]
Sure, but that wouldn't require any mapping to do.

**Comment by agentofzog2** [comment]
Feels like it could use a couple of closets to do shady shit in, you can always run outside instead of ducking into maint but it looks like it'll take longer and have a greater chance of getting spotted, especially if you're service.
The current state of snaxi maint is really bad though and it shouldn't be left as is.

Cargo lobby is way too small while the other parts are too big.

Haven't experienced the snaxi ghetto bar myself but I wish it was somewhere that's more easily accessible, like in the middle of the stations instead of a place only cultists will bother with.

**Comment by Kurfursten** [comment]
I don't think it can be in the middle of any station because people seem to really want it to be encased in ice.

Here are a couple of potential places, and you can react to this post if you want.
👍 for by the northwest ice caves (definitely the most thematic, but also very isolated)
🚀 for by the southern podbay (gives people more of a reason to go there, which is cool)
👀 for the middle of the north road between MedSci and EngCargo (very central but maybe too central for a 'ghetto' bar... is this fair to the real bar?)

**Comment by agentofzog2** [comment]
All of the above, ghetto library on top for cult, bar in the middle for normies and I dunno, ghetto botany for bannana growing in that other place.
