### ISSUE TITLE
Fixing emagged double airlock makes it disappear

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24425]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
b63bf45c2bba0fd8d66e74f3e336ae91853fce1d

# Description
If you try to crowbar electronics from double e-magged airlock it disappears in a puff of logic.
# Steps to Reproduce
find double airlock, e-mag it, apply crowbar
# What you Expected
to get circuit and fix it with my handy-dandy soldering iron!
# What Actually Happened
DOOR GONE

**Comment by ghost** [comment]
Reproduced on # 64c34b49082db854eebad33cddff8f07218e646c .
However, the bug is just with multi_tile airlocks in general, regardless of whether emagged. Whole airlock vanishes upon crowbarring in an attempt to get the circuit board. I'll look into it right now.
![image](https://user-images.githubusercontent.com/29109612/68221677-6c216b80-ffaf-11e9-8b2c-07d0779000c2.png)
