### ISSUE TITLE
Foam Fire Extinguisher

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#2459]
Fire fighting Foam as of right now 

mommi and borg one not sure if its the same for the human one

Foam does not put out fires or lowers the rooms temp.

**Comment by SarahJohnson489** [comment]
I can confirm the human one is shit now. Without being able to use them to chill below spread temp there's still no point in trying to extinguish with a foam and 2 regulars+water tank. It takes so long you're better served by breaching or bringing an air conditioner+scrubbing and remaining CO2+plasma+N2O. Fuck whoever nerfed it into the ground.

**Comment by AutismSpider** [comment]
It's just useless.

does not put out fires or cool off slag

**Comment by clusterfack** [comment]
The problem is it isn't properly assigning water to the foam as the foam's reagent. I haven't figured out why yet.

**Comment by clusterfack** [comment]
The usedelay flag had a secondary side effect of allowing aftereffects to occur on objects that were at a range from the user like a flamethrower and foam fire extinguisher apparently. This issue could affect other such long range objects

**Comment by ComicIronic** [comment]
The USEDELAY flag no longer exists.

**Comment by clusterfack** [comment]
Which is why this no longer works unfortunately. I'll try to replicate it's effects in the aftereffect proc itself if I can and see if that fixes it.

**Comment by ComicIronic** [comment]
>which is why this no longer works unfortunately

Untrue.
The USEDELAY flag was removed after this issue was made, and was never in use in code when this issue was made. As for afterattack, it's always called on ranged clicks unless the code is doing something ridiculously funky.

**Comment by clusterfack** [comment]
Yes but the EFFECTS of USEDELAY was commented out before this issue was made. As you yourself put in the commit nexis already made the flag useless.

Also a comment from the old flamethrower.dm
>// USEDELAY flag needed in order to use afterattack() for things that are not in reach. I.E: Shooting flames.

**Comment by ComicIronic** [comment]
The comment from the file is incorrect, and N3X15's changes did not affect how afterattack operated in the general code i.e. not needing USEDELAY to be called when clicking a ranged tile. In fact, I can trace the lack of need for a flag all the way back to the addition of Mechanics, since the analyzer in that used afterattack and initially had ranged capabilities.

**Comment by clusterfack** [comment]
So you are saying https://github.com/d3athrow/vgstation13/commit/f1cadf6ef1b15488ebcbfee6cd2baa6dcb893514
Authored 5 days before this issue was created, did nothing to the code?

There's a simple way to test this you know, I'll merely download the commit just before and that one and see if this issue suddenly appears.

**Comment by clusterfack** [comment]
Seems it was caused by a runtime fix pomf pushed instead. Realized then when I saw the runtime in my server panel being triggered every time and remember our recent commit history.
