### ISSUE TITLE
Discussion: Space Size & Vaults

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24629]
(WEB REPORT BY: rabbit2rabbit REMOTE: 206.221.180.138:7777)
I'm being cheeky and using the bug report button because i'm lazy and don't want to make an account to post an issue, please don't ban me.

The thread has recently taken issue with the size and emptiness of space and I sort of agree with some of the complaints.
It's been pointed out that here [https://github.com/vgstation-coders/vgstation13/pull/7653], in 2016, the size of space was increased massively over it's previous size, however it wasn't until months later in [ https://github.com/vgstation-coders/vgstation13/pull/12910] that the number of vaults that can spawn was increased, and even then only by a miniscule amount in comparison to the huge increase in space size.

For what I see there are two solutions to fixing the overly empty and quite frankly boring space adventure things.
One, shunt the number of vaults that spawn up and up until people report a good feel to it. I definitely think the minimum is far too low, and the maximum not quite high enough. 
Two, we decrease the map size to something less huge.
I dislike the idea of the second one a lot, as big map size means big play areas for everyone. 
But the stipulation on One is that there is enough vault variety that, once a good number is found, the same vaults aren't just always spawning and spawning and spawning and that becomes boring and derivative in itself.

I would like others opinions and I am actually unlikely to check this ever again but hopefully someone who knows byond voodoo magick has an interest in this thank you goodnight!

**Comment by N3X15** [comment]
> hay guys i want a discussion but i'm probably not gonna read this again bye!!!

please don't become another me

**Comment by PJB3005** [comment]
It's almost like a game made interesting by emergent player interactions gets boring when you go off on your own to explore an empty void! Wow!

Seriously though, just raising the amount of vaults won't do shit to solve the problem. There isn't enough variety to make it fun.

If you want space exploration to be an interesting mechanic I would do two things:

* significantly more procedural generation of structures (not just placement) so there is something like goon's debris field, but random. 

* encourage exploration with multiple people. Things like vaults in ships that need two switches to be activated at once.

It would be interesting to experiment with making this feature packed enough to the point where mining as a job can be replaced with a salvage crew in this debris field.

Yes, making this enjoyable is hard (then again it's no difficult to beat mining). SS13 is a game built on massively emergent behavior from player interactions. This kind of exploration is very monotonous by nature.

**Comment by boy2mantwicethefam** [comment]
Raising the amount of vaults in space would be neat NGL

**Comment by DrSnips** [comment]
Yeah we could increase the count but just recall that a handful of vaults are shit. The IOU vault comes to mind. Yeah I know the meta joke is that its a shit vault but when it eats the already slim vault population it feels really shit.
A "design-a-vault" competition could be held and we enslave mappers to do a few of them. Ive been sleeping on making a "Spesla Roidster" (tesla roadster) vault in honor of the shuttle launch that happened years ago.

**Comment by Dacendeth** [comment]
preexisting vaults also need more randomized loot so you don't come to one and go "oh this one just has a squirt gun in it lets not even bother."

**Comment by Kurfursten** [comment]
A few things to say here:

1. We have been discussing decreasing the size of Snaxi, because once it's a surface-map we don't want people wandering around in 500x500. It will be a good testing grounds for feeling how people like smaller maps.

2. The design philosophy regarding vaults is "They don't need to be balanced" (I wish I could remember who set the policy on this... probe?) - many of them are in fact worthless if you didn't bring a specific item (e.g.: the asteroids vault and clown base vaults that require a mining pick to enter), don't know the trick (sokoban, meteorlogical observation, etc.), or whatever. The TG lavaland philosophy is that everywhere you go there needs to be proportional dungeon loot to justify your RPG existence, but our design has been the opposite... you should explore because you want to explore. _That does mean more vaults would be good_ because eventually you have seen it all - but it doesn't mean they all need to have a secret gun or other item.

**Comment by vampirebat74** [comment]
> 1. We have been discussing decreasing the size of Snaxi, because once it's a surface-map we don't want people wandering around in 500x500. It will be a good testing grounds for feeling how people like smaller maps.

I don't really think that's necessary to be honest. It's probably easier to make the impassable regions just made from a new impassable tile that would take up all the extra space, while creating a special variable that would make the Z1 impossible to enter via space, while making a teleporter/shuttle the only means to the space layers. 

As for vault hunting, I think the main obstacle towards doing it in groups is the lack of a good transportation. Sure pods are nice and they work, but building one is often more trouble than it's worth. Bringing more than two people to space is extremely rare without the salvage shuttle.

**Comment by ghost** [comment]
In my defense, the reason we increased in to 500x500 is that, incredibly enough, Boxstation got so big that you could literally accidentally switch Z-level by going a screen length off the bombing range, which was pretty brutal for some antags

imo it's not a terrible thing, and I especially hope it's kept for snowstation because it gives more hazard to being lost in space

**Comment by west3436** [comment]
Inactive discussion
