### ISSUE TITLE
Another Consciousness Resists

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#24631]
While ghosting, if you doubleclick on a turf you move there, it's a good way to jump around.

If you accidentally click the turf you're already on (for instance, sprite hidden), you get an error message: "Another consciousness is in your body...It is resisting you."

**Comment by Shadowmech88** [comment]
Successfully reproduced on the main server, cannot reproduce on local. It looks like this is caused by code that is in the secret repo, or maybe some kind of config setting.

Curiously, unless that exact string is also added to the code somewhere else by the secret repo, the fact that the player sees it means `reenter_corpse()` must be getting called. However, even if that were the case, there is a `can_reenter_corpse` check above it which should stop that proc from ever getting to that point, since observers have no body. They probably don't even have a `current`, which makes it even more strange that the check for whether there's another `key` in their body succeeds.

**Comment by Exxion** [comment]
Observers do, in fact, have a `mind.current`
It points to themselves
I don't think that's supposed to happen for ghosts, but it's pretty simple to see with VV

Also, I can reproduce it on local just fine. Are you sure you're on the current version, @Shadowmech88?

**Comment by Shadowmech88** [comment]
I'm definitely not on the current BYOND version, though I wouldn't think that'd matter for something minor like this. As for repo version, I'm only a few days behind. Was it a recent change that caused this?

**Comment by DamianX** [comment]
It was caused by either the change that made ghosts have a mind, or by the fix to that PR, can't remember which, probably the latter.

**Comment by Dacendeth** [comment]
happens when you observe and hit reenter corpse too
