### ISSUE TITLE
Should we add flora diskette boxes to vox tradeposts?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#24783]
They have the xenobotany machines but not the disks.  I did not add them originally because people wanted to limit the amount of things traders could do on their own without interaction with the station crew.  

Should we finally give them disks?
Were the xenobotany machines the right thing to add?

**Comment by Pancakemines** [comment]
I think giving them disks would be a good change. It opens avenues for a trader to grow better vox plants to make them more appealing if he wanted to sell them for coin. A lot of trader has been stripped away recently with winter coats being added to cargo and black market having mushmen seeds. These used to be somewhat unique gimmicks for traders to sell and motivate people to actually show up now you rarely see anyone head to a trader shuttle for anything, likely also because it's so out of the way and no one knows they arrived. (There was supposed to be a PR that alerted people that a trader arrived and if you're in deadchat you can see it as a PDA message but it's not sent to anyone in the actual round). A lot of traders trying to play it as an RP role have been pushed away by these changes I think and it just leads to more shitbirds breaking in and stealing anything they can as a "trader". I don't think this would be a problem in terms of powercreep because honestly it would be barley ever used in the same way that xenobotany is objectively better than botany as a job for making stronger plants but no one plays it.

**Comment by utilitas-** [comment]
how bout we remove the vox outpost instead

**Comment by west3436** [comment]
Can be rewritten as a feature request if desired.
