### ISSUE TITLE
[Wheelstation] Vents Cause High Annoyance Among AutismBots

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24805]
(WEB REPORT BY: utilitas REMOTE: 198.245.63.50:1337)
# Revision
3b89a11cb244e3fde2e19fcd4f43a5d07b10fcc1

Put some kind of null interface between the separate circuits where they come close. Either a valve or two pumps facing eachother, just so MoMMIs can crawl through, and for the benefit of most everything else. Otherwise you can only enter and exit somewhere nearby, or hope to god that an atmostech isn't around to mess with shit in atmos (and even then you have to go all the way across the station if you just want to go from science to the bar).

**Comment by brndd** [comment]
it's a feature

**Comment by utilitas-** [comment]
yes but
Picture this: Maintenance atmospherics substations. Like Goon's, and the same that we've had since Goon, except more. Little filters and connectors both to the distro and the scrubber network where an atmos tech can empty a can without going all the way back to atmospherics, and where he can fill up a portable pump from the distro without crowbaring open the hallways and potentially having to empty the pipe with a socket wrench just to get some fresh air. I'm going to do just that with Uterus: adding points where atmos techs can get to the distro/scrubbers away from atmospherics.
Those could potentially deal with air inbetween the departmental networks. They could even be used to balance the distro/scrubbers load, and it'd give you a reason to add something to maintenance that is _actually useful_ and isn't just another fucking tumour.

**Comment by brndd** [comment]
I've got substations, but right now they're just simple pressure tanks for refilling the loop in the case of a breach. Adding in connector ports for emptying and refilling stuff with air seems like a good fit, especially since these rooms already have high pressure gas in them to expedite this. I'll keep that in mind when I start making structural changes again.

I'm not sure about connecting the different sections' loops together in these substations, though. I have a hard time envisioning how to do it without making it look like it's done just because. Also on a principal level I like the way ventcrawlers don't have an easy time moving from one section to another, though I must admit it does feel confusing, at least at first, crawling in the vents on this map compared to other maps.
