### ISSUE TITLE
Eye damage from welder despite hardsuit helmet

### ISSUE THREAD

**Issue by Enwek** [d3athrow/vgstation13#2484]
Just noticed that I went blind twice while wearing an engineering hardsuit helmet while welding.

**Comment by ComicIronic** [comment]
Were you getting the eye damage messages?

**Comment by Probe1** [comment]
I had this come up yesterday.  "My eyes water"  "My eyes sting". I was wearing an engineering hardsuit and helmet with mesons underneath welding some glass shards while repairing a breach.  The bug is definitely there but occurs rarely.  I've only seen it happen once (yesterday) and I'm not even sure it caused any damage.  But the messages did come up.

**Comment by ComicIronic** [comment]
This was fixed, wasn't it?
Or was it called deliberate because mesons cancel out the helmet?

**Comment by Probe1** [comment]
I believe it was fixed very recently.
