### ISSUE TITLE
Borer died while inside of me from pressure

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#24872]
#### Description of issue
My borer died while inside of me while I was in a low pressure area taking damage.

#### Difference between expected and actual behavior
Borer to be safe in a body no matter what like they've always been
Borer died from pressure.

#### Steps to reproduce
Have a borer inside you while you're in a low pressure area suitless

#### Length of time in which bug has been known to occur

this is pretty new.

#### Server revision

Revision: ecaf4fec264939ccc8b2a0a34a5100e6b5254703

**Comment by Shadowmech88** [comment]
I can only imagine it is due to #24594, but I had the code check the `return_air()` of the borer's `loc`, which in this case was a mob..
Do mobs just return their turf's air when `return_air()` is called on them? Is there any reason they wouldn't just return `null`, seeing as mobs don't contain air?

**Comment by N3X15** [comment]
Eat fewer burritos you fucking monster

**Comment by DamianX** [comment]
```
/atom/proc/return_air()
	if(loc)
		return loc.return_air()
	else
		return null
```

**Comment by Exxion** [comment]
Mobs don't generally have an internal gas reservoir that `return_air()` *could* return
