### ISSUE TITLE
burgers don't have the names of the meat anymore

### ISSUE THREAD

**Issue by DaxterBrown** [d3athrow/vgstation13#2530]
burgers made of named meat don't have a name

**Comment by gbasood** [comment]
The problem here is that the recipe for a plain burger calls for 
```dm
/obj/item/weapon/reagent_containers/food/snacks/meat
```
Which means that the recipe picker picks it before it picks the human meat recipe, which inherits from that meat. One quick fix could be that the gibber creates something else that inherits from meat, such as:
```dm
/obj/item/weapon/reagent_containers/food/snacks/meat/plain
```

Recipes with human meat variants (currently just human meat and kebabs) would need to be changed so as not to select human meat for a standard burger.
