### ISSUE TITLE
Poppy Pretzel Failure

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25415]
(WEB REPORT BY: aerywyn REMOTE: 206.221.180.138:7777)
# Revision
4cac1f2dc1df0dcf694adefd35610306bb64b48c

# Description
Recipe needs poppy seeds. Microwave cannot accept poppy seeds.
# Steps to Reproduce
Attempt to put poppy seeds in microwave.
# What you Expected
Them to go in.
# What Actually Happened
They don't.

**Comment by RaccoonBro** [comment]
Should just need to add seeds to var/global/list/acceptable_items in microwave.dm

**Comment by ghost** [comment]
If I remember right, because of how finicky the microwave recipe system is they'll only accept stock seeds and since basically everyone modifies their shit it's almost immediately rendered unusable for cooking due to how botany3 affects the seed packet being incompatible with the clunky microwave recipe system without it just taking any kind of seed packet.

It's ugly but probably best to just have cooking a poppy in the microwave give you a couple toasted poppyseeds and rename the pretzel recipe to reflect it. I would have said food processor but that opens mapping issues and aggravates people needing yet another machine when they just want to open a pretzel stand somewhere.

**Comment by RaccoonBro** [comment]
May just be worth it to change the recipe entirely instead of making it more complicated. A generic jumbo pretzel would be alright tbh
