### ISSUE TITLE
How snowtaxi stole player interaction

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#25438]
#### Description of issue

Related to #24263 but with a slightly different message.
Snow taxi is bad for player interaction in its current form.

The walks in the snow are tedious and don't really encourage people to go to other departments.
As a result, every department is an almost closed system with little input from the outside world. This isn't really good for player interaction.

I think the map has potential, but the bunkers need to be made closer, interconnected to each other, or something needs to be done to encourage players to explore beyond their assigned bunker.

Additionally, the fact that snowmap has one comms console in each bunker seem to encourage the most extreme and depraved form of recall spam, which results in a prolonged experience on the map. This, I think, is also a consequence of the spread out bunkers.

**Comment by Allspice** [comment]
could use teleporters that have no failure

**Comment by plosky1** [comment]
I tried making them closer and people threw a massive shitfit so good luck. I agree though from a game design perspective.

**Comment by Kurfursten** [comment]
1. All of them are interconnected by taxis now, which are functionally similar to teleporters or narrow hallways or whatever your idea is.
2. The arrangement of departments is designed so that no station works as a closed system. Patients have to go to northwest, cargo deliveries/engineers flow to all stations from northeast. Sec patrols between all stations from south. Miners also deliver to northwest from south. Bored/hungry crew all flow to kitchen/bar in northeast. Orders or access changes require a visit to northeast. The only station without a major pull is south - it has the library and chapel but those don't get people going. It does have centrality and escape though, which helps. Scientists do have to hike between south and northwest to R&D/get back to their slime autism.
3. Only 2 stations have a comms console, not all three. One is by the HOP, one is by the Captain. There is no bridge on northwest station.

In seriousness, I don't know how short people are imagining when they say 'just put them closer together'. Much closer together and they're just going to be attached in a weird bagel and then what's the point?

**Comment by plosky1** [comment]
I think something that may help is something I tried doing before, which is there's a var for making tiles not have slowdown, and treating them as heated tiles. The biggest pain in the ass is that the tiles have slowdown even if there's no blizzard in snow. Or maybe it's after a blizzard happens.

Regardless, there's no way to remove it and makes trekking a pain in the ass.

**Comment by Kurfursten** [comment]
I believe what you're referring to is the turf_speed_multiplier. Two things affect that on snow turfs:
1. How hard it is currently snowing
2. How high the snow level has built up on that tile (counted in snowballs)

This is why after a blizzard most of the snow is much slower to move through, and why asphalt paths allow you to move much faster (they do not accumulate snowballs).

**Comment by plosky1** [comment]
Right, that's what I'm attempting (and failed) to refer to.

I may be wrong, but I don't think you can re-increase the speed. I think the following would help travel:

A. Add the ability to "plow or shovel", which would remove the snowballs from regular tiles to increase the speed back to it's regular non-snowball level. Currently after a blizzard walking tiles are permanently slowed with no way to increase the speed, though not as slow as regular snow tiles.

B. Add an overlay on regular tiles indicating the level of snowbuildup equivalent to snowball count so people can visibly see why they're being slowed.

**Comment by ShiftyRail** [comment]
I think that just giving asphalt tiles the same amount of slowdown than floor tiles would already go a long way.

**Comment by Kurfursten** [comment]
Asphalt tiles do have the same amount of slowdown as normal floor tiles (in lowest snow conditions) - assuming you aren't being slowed by cold or gear you're wearing

@plosky1 you can do that already, by pulling up snowballs by shoveling or hand - this calls update environment which recalculates slowdown based on number of remaining snowballs, but you are correct there is no overlay

**Comment by plosky1** [comment]
Ahh I didnt know that. A really cool option would be a snowplow attachment for snowmobiles, making it fun and easy, along with a nice overlay animation of it being cleared.

**Comment by Kurfursten** [comment]
sure, that sounds great if someone wants to code it, could even use the new vehicle actions

**Comment by ShiftyRail** [comment]
As an aside I really encourage people to report what "else" they feel is wrong with Snaxi.

I won't be long before we get the "Bagel effect", a sad sociological tale where a map is seen as bad, which causes people to play badly on it (it's a bad map so I want to skip it), which make the map look bad as a result, and so on in this vicious cycle.

I don't really want that to happen.

**Comment by Kurfursten** [comment]
1. I am still not satisfied with south station. I want to use the space from the removed arrivals shuttle to rearrange some things so some rooms can grow. The poor IAA/library/chapel need more space. I am also considering moving xenobot to the south station and toxins out to the outpost but this is uncertain.

2. I am not satisfied with northeast station. Botany/kitchen still doesn't feel right and I would gladly get input from veteran service players on how to make it work better. Maybe even an outside garden? Open to ideas here. Engineering could be shuffled and atmos expanded, too.

3. I want more geography out in the snow. I want to bring back the surface mine with a unique feel. I want a concentrated field of geysers and sandy region where all the snow has melted away, with cliffs. I want more unique snow surface creatures like birds. I want the frozen lake to be more than just a sticker on the ground: sliding effects, ability to break the ice and fall in or fish, etc.

It's all too much for one guy to do, but I am slowly chipping away at my complaints one by one.

**Comment by boy2mantwicethefam** [comment]
shifty how can you consistently have bad opinions

**Comment by nuklearcellphoneg** [comment]
But the massive snow fields between buildings is the only reason I like the map. It's what roid should have been.

Just put more station maps outside so folks don't get lost.

**Comment by ShiftyRail** [comment]
@nuklearcellphoneg there can be incentives to explore snow fields without necessarily making walking from a point A to a point B a long haul with little people to meet while doing so.

The problem really isn't that people it get lost, it's rather than the distances between places dilute the population and as a result make player interactions less likely to happen.

**Comment by nuklearcellphoneg** [comment]
Well, then focus on making an in-game economy work. Then folks will run into each other, otherwise people only go to medbay for treatment, kitchen for food, and cargo for 'stuff'- other than those three, there's no real reason for anyone to go anywhere, so of course you'd not run into someone.

**Comment by jknpj** [comment]
Maybe we should just drop the whole "3 mini stations" design and make each department its own building then make the buildings closer to each each other.

**Comment by Kurfursten** [comment]
For the monumental amount of work that would be, I don't get why that would solve anything. People keep saying it and I think they aren't really thinking through what that experience would be like. Separate all departments into separate buildings? So that means even less interaction because there's no common space between departments. There is no reason for someone to ever even step foot into the engineering building unless they're showing up to sabotage it. I don't get all of the calls to move things closer together. We have the taxis now if you don't want to ever be outside, the walks aren't that long.

I believe the biggest problem with Snaxi isn't any pithy statement like "just shove them closer together/farther apart", but rather that a lot of departments need more redesign from their taxi days. Too many cramped rooms that don't need to be.

**Comment by jknpj** [comment]
>There is no reason for someone to ever even step foot into the engineering building unless they're showing up to sabotage it.

You can say the same about every single map.

**Comment by Kurfursten** [comment]
On several stations there's a reason to be near engineering because you're passing through maint or behind a different department (e.g.: walked out the back of service on metaclub)

If it was its own building, people would wonder why you're anywhere near engineering. As it is now, people go by engineering because tool storage, mechanics, and cargo are right by it.

**Comment by nuklearcellphoneg** [comment]
I agree with making each department its own building. 

People ain't interacting with the folks in engineering when they pass by it on Box

**Comment by Kurfursten** [comment]
Since this issue was made the stations were made closer, the taxis were added, and the snowmobiles were added at each substation
