### ISSUE TITLE
Roulette Revolver frequency Too high

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25726]
(WEB REPORT BY: gunosaguki REMOTE: 206.221.180.138:7777)
I've been autism xenoarching again for the past week, and I've noticed the roulette revolver, for a recharging weapon. has an insane frequency. I can almost guarantee I'll get 1-2 per shift at this point, and given the destruction capability of it, seems a bit high. Not sure if working as intended or if I'm just having unnatural luck with them.

**Comment by nervere** [comment]
It now has a 1.3% chance of being present in any "War" digsite, per the code listed below.
It was 5x higher when this issue was made. See this PR: https://github.com/vgstation-coders/vgstation13/pull/29181
https://github.com/vgstation-coders/vgstation13/blob/223bf37a7386249ecf1fe425ca8cef25821ca9d7/code/modules/research/xenoarchaeology/finds/digsites.dm#L103-L122
