### ISSUE TITLE
[Feature Request] What the hell is the point of Requests consoles?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2609]
![image](https://cloud.githubusercontent.com/assets/8550416/5883929/0c9082dc-a325-11e4-8a2c-0117225f73b3.png)

I've been here for going on six months now and the only time I've ever seen these used were by myself, once, to see what it did.  Does anyone use these?  Do they have a purpose that isn't better served by PDA messaging and using the radio?  

They look like dead weight.  Let's revamp them into something awesome.  How about we throw out the entire supply requests part and replace it with a slice of the Supply ordering console?  A Requests Console in Engineering can use the request supplys button to order anything from the categories Supplies and Engineering.  Research can order anything from the request console from Supplies and Science.  And so on.  

That'd be great.  People would make use of cargo more often.  This clunky shit that no one uses would get used.  You'd still have to message a cargo tech and let them know you placed an order, but you can still place it without walking your pudgy ass all the way to cargo.  

Too bad I don't know how to code it.

**Comment by Duny-** [comment]
What they need is better sprites to show that they got a request and a sound associated with it. The only reason they don't get use is because nobody ever notices there's a request.

**Comment by eswordthecat** [comment]
I use it when playing roboticist.

**Comment by Probe1** [comment]
I disagree @Duny- , people are just going to ignore it because PDAs and radios are faster and more efficient.  

Not only that, the supply request and request assistance do the exact same thing, it just has a different name.

**Comment by Duny-** [comment]
>because PDAs and radios are faster and more efficient. 

PDAs aren't faster and can be lost or stolen. They also message one person who may or may not be willing or available to fulfill your request, while request consoles tell the entire department what you want. 
Every single time I've used the radio to ask for something, I never got it. And those are subject to telecomms shenanigans and the order will only stay on people's screen for a few seconds/not even a second

The only reason they don't get used is because nobody ever notices there's a request. Nobody bothers sending a request because they know nobody will notice, when someone does make a request nobody notices or someone notices but 20 minutes later when the guy who ordered something is dead in a dark maintenance tunnel. I've been on the two sides of this and I know I'd start using them again if they weren't invisible.

**Comment by Probe1** [comment]
Okay we can easily try that out by making it beep.   You're going to have cargo techs saying "come here and place the order yourself I don't have the money". but it's a step.  Make it continuously beep until the message is read.  Seems easy to code.

**Comment by Riukanojutsu** [comment]
Pretty sure making the screen flash or change color will be less annoying and just as efficient

**Comment by Probe1** [comment]
The screen does flash.  Nobody uses it anyway.

**Comment by ComicIronic** [comment]
Likely because nobody ever watches the screen.
Having them beep like PDAs would work.

**Comment by Probe1** [comment]
@comicironic can you code that and we can see how it works out?

**Comment by Probe1** [comment]
I'll re-open at a later time but #2754 was a good improvement
