### ISSUE TITLE
there is a large chance you will accidentally nullspace a slimeperson's brain

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26433]
(WEB REPORT BY: chaklet REMOTE: 206.221.180.138:7777)
# Revision
844a05c6ea77914f3ed04a5df5ecd1aa3229fe6f

# Description
if you die as a slimeperson, you will turn into a puddle of slime and normally be cloneable. if you fuck with the brain a little bit the puddle will no longer be scannable with the message "No signs of intelligence found." or some shit. the brain will not be able to be pulled out again and you will be stuck in hell - this has happened twice now and I'm assuming is easy to reproduce

# Steps to Reproduce
slip brain out of puddle
play with brain a little bit
slip brain into puddle
brain should be gone(i think)

# What you Expected
brain puddle
# What Actually Happened
no brain in puddle

**Comment by chaklett** [comment]
actually now looking through it ([18:41:53]ADMINWARN: <span class="admin"><span class="prefix">ADMIN LOG:</span> <span class="message">Madelynn Edelfelt () removed a vital organ (the crystallized slime core) from Madelynn Edelfelt () (INTENT: HELP) (<A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=0;Y=0;Z=0'>JMP</a>)</span></span>) it's possible it happens when the person in the slime puddle ghosts which i think is a lot more likely.

**Comment by chaklett** [comment]
okay after that round it literally is that easy as putting the brain back into the puddle just instantly vaporizes it

**Comment by Cisrox** [comment]
can confirm this bug, i was trying to clone/revive chaklet, after i took him out of the cloner his brain was deleted from his goo and we needed admin intervention to bring it back
