### ISSUE TITLE
Permanent School Glue

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#26440]
small_bossToday at 7:25 AM
get school glue from autodrobe, stand next to a sink, glue a item and instantly wash it off
it will keep the glue permanent

**Comment by ghost** [comment]
feature

**Comment by Kammerjunk** [comment]
important to note that this conversation arose because the antag ones straight up don't work with clothes
intended: clothes stick to you when you wear them (canremove = 0)
actual: clothes stick to your hand (cant_drop = 1)

potential fix: remove [this line](https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/game/objects/items/weapons/clown_items.dm#L333) because it makes glue_act() on /obj/item/clothing (which makes it not unequipable) also do glue_act() on /obj/item (which makes it stick to your hand)

**Comment by BomberBro** [comment]
oh no, I've been using this to stick items on people ever since superglue broke
