### ISSUE TITLE
What if Mushmen Weren't Terrible?

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#26611]
I want to preface by saying that I appreciate that Mushmen are actually trying to be a different experience. They feel like a significantly different way to play instead of cosmetic like playing a grey.

Unfortunately, the major ways they are different are pretty much the worst ways they could be different.
* Needing to be in the dark makes sense for an antag like a ninja or grue. The crew wants an intact station, they want to destroy it. The darkness is a visual metaphor for this. But for nonantags, it means either "I move like a snail" or "I will now ruin lighting for other people".
* This is a social game. I've had several mushmen players flat out say they'd rather mime (visible to everyone) than fuck with telepathy to each person individually. This COULD work but only if telepathy was made a LOT more convenient to use.
* At the end of the day, they are just reverse-diona: heal in dark, slow in light, which I already don't think have a great gimmick (this also causes people to get confused when they constantly starve in light, unintuitive)

Do people mostly agree with me that mushmen need a significant overhaul, or are you happy with how they are now?

**Comment by Exxion** [comment]
The miming thing sounds like an interesting drawback to me, though drawbacks do need to be countered by positives. I'd rather see them get more positives than see that drawback removed though.
A channeled spell for the telepathy would be a pretty simple way to make that less painful if they want to speak to someone they can see. (I'm assuming they don't already have one and just have to use the list like everyone else but I haven't actually checked)

**Comment by Kurfursten** [comment]
If we keep the telepathy no-mouth gimmick, I'd like to see it expanded. Don't do anything mouth related: no drinking chems or eating food or smoking. Get rid of the "nutrients come from darkness" which is dumb an unintuitive. Make it so they have to stand on food to absorb it (laying absorbs faster).

**Comment by Buchse** [comment]
I think having to lay/stand on food to absorb it would be pretty neat tbh, If if were up to me i'd give them a bit of a visual overhaul too so they appear a bit squishier/paler, more like the stereotypical mushroom tissue stuff

**Comment by beesil** [comment]
I agree that they could use an overhaul.

>I've had several mushmen players flat out say they'd rather mime (visible to everyone) than fuck with telepathy to each person individually. This COULD work but only if telepathy was made a LOT more convenient to use.

Could the telepathy menu be made more intuitive, or an option added to broadcast to everyone within a certain tile range/sight vision? The menu right now is painfully slow to use. 

Additionally it's buggy if a person on the list changes identity, and you can't talk to people on the station from the outpost since it only works within your z-level.

**Comment by Kurfursten** [comment]
Another idea I had to make them feel different is to give them an exoskeleton (roaches could get this too), since fungus has chitin. Basically, the exoskeleton reduces external damage, but breaks more easily than bone because it's exposed. So this has some obvious drawbacks, everyone knows how much it sucks to have a broken hand or foot.

Possibly at the cost of hunger they could regenerate limbs - so you might see mushmen ripping off limbs instead of getting their chitin fixed then budding on a new limb, Piccolo style.

**Comment by GreatBigFailure** [comment]
I've been a mushman twice and hated it both times. The dark vision doesn't work and is blinding for the player. Telepathy, like you said, is really annoying to use. The first time I was mushman I ended up AFKing in maint because I was tired of slow walking and starving, the second I smashed half the lights on the station. 
There's interesting and different but there's also fun. The goal should be both.

**Comment by SonixApache** [comment]
I've played them once or twice now and my findings are as follows;
 - Going at the speed of slow forever or having to deal with weldervision forever is gay for gameplay unless you plan on being sedentary (like diona but worse)
- Not being able to talk to people nearby is annoying - sure, it makes sense, but having to print a speaker just to be able to talk to people with some semblance of speed is ridiculous.

Possible solutions for the vision / nutrition thing:
 - Reduced color vision in inverse mode so it doesn't give everyone eyecancer
 - Remove inverse mode alltogether and just make shrooms see at 50/50 perfect grey in all lighting conditions - but make them unable to use camera consoles or something
- Give them special eyewear (or eyes) that work like blue NVGs but don't give them the nutrition debuff

Possible solutions for the talking thing:
 - Gay telepathic chirping like slimes do
 - "Select mind" spell that lets you talk normally, but only to one specific person. Would allow for actual conversations.
 - Maybe expand the above and add some sort of mental stamina system so you can talk to multiple people at once, but can't shitpost at the entire crew forever.

**Comment by Dacendeth** [comment]
Mindspeak really needs another button, where you click it and then click a target to send a message to the target you clicked on.

**Comment by GreatBigFailure** [comment]
To make the compost pile more unique mechanically you could have them suck up chemicals on the ground similar to the vacuum. Blood on the floor? Little bit of nutriment maybe, bleach on the floor? Oh no. 
>Possibly at the cost of hunger they could regenerate limbs - so you might see mushmen ripping off limbs instead of getting their chitin fixed then budding on a new limb, Piccolo style.

Since the goal here seems to be maintaining mushmen's uniqueness I think you should go harder on the sporing angle. Slimes already do what you described. The chitin idea is really solid, especially if you make the pros and cons consistently relevant (unlike slime's amputation thing). Instead of regrowing limbs why not have them bud-off a walking mushroom and compost pile their old body to grow big again? Something along those lines. Just a top of the head idea but if they're breaking limbs constantly it would make them feel very unique.

**Comment by SonixApache** [comment]
Mushmen blood should be Mescaline or some third variant of space drugs, and their brains should contain amanita toxin or something.
Y'know, as a natural defense system.
\>slap mushman
\>the colors, maaaaan
