### ISSUE TITLE
[Feature Request] PDA enhancement purchase - Station Alert Computer for Engi PDAs

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2663]
Welcome back Deity Link, here's something I think would go over well.  Other stations have portable laptops that function as station alert computers.  Instead of introducing a slew of items to give us a neat toy, give engis, atmos techs, and CEs a PDA purchase that lets them see station alerts from their PDA!

**Comment by Angelite191** [comment]
Fuck I wanted this so bad. Please do this!

**Comment by DeityLink** [comment]
My policy is that profession-specific PDA apps should instead be by default on their cartridge.

And that said, I see that engineer PDAs cartridges (called "Power-ON Cartridge") come with a Power monitor app that connects to all Power Monitoring Computers in the world. So why not a Station Alert Monitor app indeed.

However I'll probably tweak both apps so that they can only connect to Computer on their Z-level. That seems fair to me.

**Comment by Angelite191** [comment]
agweed.

**Comment by Probe1** [comment]
@DeityLink  is da best
