### ISSUE TITLE
I don't like cult

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#26811]

**Comment by d3athrow** [comment]
i don't really like cult either

**Comment by BomberBro** [comment]
Cult has a tendency to make absolutely abhorrent rounds and has a very janky execution, I strongly dislike it

**Comment by Dacendeth** [comment]
recall shuttle simulator 2020.

**Comment by d3athrow** [comment]
long time ago some of my most cherished rounds were cult 1 rounds. everything is so different now and honestly feels like it would have been better as its own gamemode instead of cult.

**Comment by Kammerjunk** [comment]
maybe cinematic game design doesn't translate that well into a game like SS13

**Comment by Caboozles** [comment]
The most fun cult rounds are where you and most of the station utterly disregard the cult and they flounder around doing nothing as the shuttle arrives.

The quality of the round is directly inverse to the quality of the cult players.

**Comment by SonixApache** [comment]
Some of the aspects are super cool, like secretly colluding with others in the dark and how the confusion rune works and when shit hits then fan and it's just you and your weapon and everyone could be out for your blood, literally.

Personally, I've fought cult more often than I've been cult, but I don't really dislike it.

**Comment by DamianX** [comment]
What was cult 1 like?

**Comment by ghost** [comment]
I like cult but i don't like how the round is super gunked if the cult fails, as a lot of people will be removed from the round forever and security will have to keep being nazisec forever. Furthermore you cannot arrest any of the cultists, as they will simply shade away or be teleported away by their buddies. Even if they do not do anything of the sort, permaing or jailing cultists is not viable anyways and they cannot be deconverted by any means, which means that braining cultists with field executions becomes the only realistic solution, which is anti-fun.

Honestly one of the main problems with the cult-conundrum is that i cannot even think of minor changes that would actually make people enjoy the mode more. At the same time i feel like removal of cult would be a major loss for the round variety as a whole. Furthermore some of the cult spells are fantastic for a team antag mode and i wish people utilized them more, instead of the usual stun-emp-convert in maint routine.

Finally i think a lot of people who have cult turned off are simply afraid of playing as a cultist. Cult mode is easily the most complex antag mode we have on the server. Even going through the spells list would make a new player feel lost. Perhaps a future incarnation of cult, if anyone is willing to write the code for one, could have certain sections of the cult mode compartmentalized as specific specs/roles/classes cultists could choose from, similar to how the Ops classes work.

**Comment by SonixApache** [comment]
Cultists should be deconvertable / get auto-deconverted post-cult, I guess. Would solve some issues.

**Comment by tuypo1** [comment]
With regards to people having cult turned off because it's overwhelming perhaps have an option where less experienced cultists can set themselves to be converted as initiates or something that have less power or responsibility or something

**Comment by Kurfursten** [comment]
I was thinking about this for a while. What if Cult was summoning Nar-Sie because this is like an eclipse or something therefore they have 1 hour (+- random amount of time so it can't be gamed) to get their shit together or the ritual time passes and it's a flat cult failure, all members deconvert/die and an announcement happens.

Solves
>cult that refuses to advance stage and keeps converting until OCCULT ENERGIES warning
>paranoia that there could still be more cultists if bloodstone stage never happens

**Comment by ShiftyRail** [comment]
The problem isn't IMO that it's hard to understand, more than people aren't motivated to play the round-long careful silent shuffle with the pre-traced steps. 

Any deviations from the maint cubby => stun/EMP => blood grenades => summon routine is harshly punished and one man's failures ruin the fun of the entire cult team. 

So it is less than it's overwhelming, but more than there's actually one "valid" play scheme which might not be what people want to play for the rest of the round (which is why you get boxes or "jobbie" cultists).

Some people do not enjoy playing cult in the same way that some people do not enjoy playing security, or assistant, or engineer. 
A good antagonist should offer multiple playstyles so that any job and any player can have some fun at it if they want.

**Comment by tuypo1** [comment]
I like that time limit idea
plus it could give traitors something to do during a cult by hiding bodies so when the cult runs out of time and people go to clone all the cultists the bodies are gone

**Comment by ghost** [comment]
IMO the fundamental problem with cult is that restrictive objectives aren't fun in a game that is otherwise open ended. Realistically there's only one way to approach each act, and players' distaste for cult means one fuckup and the cult is ded unlike other team antags where you sometimes see non-antags play along with fuckups. 

An idea I've mulled over is giving cult a list of tasks that contribute towards a point tally for advancing the act, with each act unlocking new tasks, but I don't think just giving cult more freedom will fix the issue at this point.

**Comment by 49bluesun** [comment]
I want to like cult but I can't. 
Current cult is a NoRP game mode that encourages bitter players to speed run and power game to end the round as soon as possible, because security WILL be at their most vicious and ruthless, civilians will freak and conscript themselves to end you, other antags may purposefully singuloose just to deny the cult, and new and confused cultists make a mistake and expose the team too early.

I like converting people, either through kidnapping or a bit of RP to convince others to be willing. I like building spooky lairs other people can see. I like using runes and papers despite still only really bothering to remember and tried a few. I like ranting in incomprehensible cult speak over open comms to tell fellow believers to rejoice.

I am discouraged from doing all of that. Any converts have to be quick and involve no interaction, or else be caught. Bases need to be simple and hidden, otherwise the shuttle is called once one is found. Any blood magic seen by crew who aren't instantly silenced send the crew into a panic. Doing ANYTHING or letting ANYTHING slip, even saying simple words, can instantly ruin a round. Cult becomes the bogeyman that can justify any war crime to pull us out. I want to be a loud, dumb antagonist over half the time but that doesn't mix with cult since that can screw the team over, AND I'm locked to very specific objectives that leave no wiggle room to RP or fluff it up, otherwise you fail and you're not a team player. 

I have a different idea of the ideal cult round than others, and I can accept that. But I feel like we're here because cult 3 forces you into the SAME tempo for a round, that ends in abjact failure due to early exposure or a complete bloodbath. I do not WANT to see cult gone. It has a lot of bits and features I still like and I've got nothing against Deity, but, what can we change then? Is this open for actual ideas, or for bitching and grievances. I've said stuff in discord and the thread before, so I'll do it here too. I don't have the answers, just thoughts.

1) Loosen up these goddamn specific  dumbass objectives. This may be the thing I hate the most. The end goal can still totally be to bring collapse reality to bring your elder god here, which can be achieved through stuff like getting X number of converts, hell twister, dancing around a bloodstone, whatever. The evolving power/tier of the cult as goals are met I DO like, but I just hate how it's always the same goddamn thing. Leaves little room for gimmicks due to security knowing letting you live means they risk being forced into TDM. It might be tough to plan a choose your own objectives or freeform, but there can still be a simple goal, such as get the disk, or exile/kill the heads

2) Ops and Revs as team antags have leaders. Why not cult? This is a role that I think could benefit from it a lot. You often have that one guy who REALLY is giving it his all to get shit done for the cult, powergamer or no, or a man with a plan in the form of a crazy gimmick others could agree with. This could be decided at roundstart, or as soon as people meet up, and could come with benefits such as the :x cult comms earlier to help rally and organize. Give the guy who's putting extra effort extra tools to help the group. This could be limited to one, or potentially grow and you could promote others. I dunno. Just having a dude with that 'leader' weight to give orders and have an easier means to talk could mean we have less fuckups.

3) Blood Magic is cool, and it may never be acceptable to finger paint runes in the halls, but the idiot RPer in me likes the idea of tempting people with powers still. Maybe if the uses of runes grew, but this just feels too HRP an idea, but something I'd still like to try with a gimmick that I'd be okay getting killed over if it went wrong. Imparting knowledge without getting converted or getting a full antag pass? Maybe. Give people power at a price.

I dunno there's more, this is just what's on my mind right now when I noticed this

**Comment by ghost** [comment]
Nar-sie needs to get cut for cult to be fixed. Nothing cult does is that scary until they summon Nar-sie and the round ends. All cultists get validhunted because their end goal is to end the round, so they just go into hiding and the round is boring because all the antags are walled off somewhere speedrunning the Nar-sie summon. People don't want to get converted because they don't want to be dragged into the brig and beat to death by shitcurity, or they don't want to get converted because they'll add nothing to the round since them going out of their workplace could raise suspicion.
The stakes for the cult are too high which leads to a lot of objective speedrunning, validhunting, metagaming and people getting bwoiked because they expose the cult and ruin the fun for the rest of the cultists.

If the stakes were lower and ignoring the cult didn't lead to ending the round, you could start giving them more freedom, removing powergaming tools so there's more roleplay and less gunning down cultists and forcefully implanting them. Also ghosts shouldn't be able to see runes or hear people speaking cult gibberish.

**Comment by TGFH** [comment]
Cult requires a shuttle call most of the time because we don't have deconversions and that means all cultists get beheaded. When it doesn't require a shuttle call (cult got caught and stomped early) it still results in sec going full gestapo and implanting everyone because there's no way to know if you really got them all.

**Comment by gurfan** [comment]
I have fun in cult and enjoy playing it but it is easy to see why people do not enjoy playing it.

Cult seems to be one of the most complex and also the one with the highest stakes. If people let themselves get converted and they don't know EXACTLY how to play cult they can easily fuck it over for everyone on their team. At it's core cult isn't that complex, but there's so many tricks and procedures that you should be pulling off in order to "play cult properly". Like 49bluesun said, giving cult a leader/someone to organize things and dish out orders might be a simple, if not perfect, fix in this regard. 

Part of the reason why cult so inclined to powergame and use every scummy, silent shuffle technique available is because the moment they get revealed security starts field executing cultists without mercy. This isn't a problem with security, theres just so many bullshit aspects with cult that I think create this mindset in security:

-Cult, if left unchecked, ends the round
-Cultists can't be imprisoned without keeping them buckled 24/7, as they can be teleported away by other cultists 
-Cultists can't be imprisoned even without the teleport abilities, as the ability to write runes anywhere and everywhere makes them dangerous all the time.
-Cultists can shade at any time, destroying all of their belongings and giving them the potential to escape. The only solution is to de-brain them ASAP.
-The cult gets more powerful as they progress. If you don't stop the as soon as possible they can (and will) become unstoppable
-The cult is trying their hardest to win, why should sec even give them an inch if any leeway could backfire horribly?

There are a ton of cult problems more related to gameplay itself.

-The spread blood phase sucks, and sometimes it can be completely slipped with prepwork. Either you spread blood with grenades/spray bottles/extinguishers or you just run around killing people.
-Once the bloodstones rise the game really does become TDM. This wouldn't be necessarily horrible if:

1. Noncultists don't usually know who's a friend/foe
2. Cultists didn't have some many stupid unstoppable powers (see below)

-Cult has a lot of scummy and unengaging tricks that can make them instantly win some encounters:
1. Stun talismans are cheesy. They're a necessary evil for how silent and stealthy the cult has to be, but getting slapped with a stun talisman in maint is not very engaging for the person on the receiving end.
2. Concealed runes can essentially function as invisible landmines for noncultists, if the cult bothers to set them up.
3. Cultists with the pale form tattoo can use stun talismans in hand for an AOE stun that affects everyone without the tattoo. Using the talismans in this way is essentially an instant win for any fight if the noncultists don't maintain a 7-8 tile distance at all times. Combine this with confusion and emp talismans and you have a nearly unfightable cultist.

Theres a lot of things I like about cult. Building bases and making construct armies being some of my favorites. The game is so rigid however it's easy to see why people get tired of it.

**Comment by Buchse** [comment]
honestly nothing makes me want to just close the game more than being wordlessly papered and dragged onto the rune. Talismans are free 30s stun+mute tools with no way to block them and no in-hand sprites.

Conversion runes are even more egregious, they make you sit helplessly waiting for the ebin purple prose that tells you "join or stop playing ss13", which then gives you flowery text lionizing you for how strong your brain was, that nar-nar couldn't turn you, etc etc. It's even worse if you're implanted, since it takes so much longer to be given the choice to box or not. 

Being able to convert through implants is a terrible choice in my mind, it reduces implants to just a method of checking if someone was converted after, or checking for cultists. Making it impossible to convert through implants means that cultists either can't just wordlessly steal sec and heads, and they have to either kill and clone them or remove the implant themselves.

**Comment by SnakeEater14** [comment]
cult is pretty bad. i don't like it in its current state. thanks for reading.

**Comment by tuypo1** [comment]
>Noncultists don't usually know who's a friend/foe

somebody made a PR to fix this by giving them an aura, why did that never go through I forget

**Comment by Dacendeth** [comment]
God I love the time limit idea, the worst part of cult for me is the shuttle recall spam until they win because eventually they fumble into doing what they're supposed to be doing.

**Comment by DeityLink** [comment]
Oh boy, reading to catch upon

**Comment by DeityLink** [comment]
@Buchse _>and they have to either kill and clone them or remove the implant themselves._

Realistically they'd just get soulstone'd though.

I agree with quite a few people here, "cult 3.0" has its failings that I failed to properly address for a long time because I lost track of what I really like in spess, about how organic rounds are. I too really miss cultists doing funny gimmicks.

@Kurfursten _>What if Cult was summoning Nar-Sie because this is like an eclipse or something therefore they have 1 hour (+- random amount of time so it can't be gamed) to get their shit together or the ritual time passes and it's a flat cult failure, all members deconvert/die and an announcement happens._

That's kinda what Act 3 was meant to be originally, like @Panicchip the threat of Nar-Sie rising is what makes the cult so terrifying. If you ignore them they'll just make their way through the whole crew because summoning Nar-Sie is their ultimate objective, and while old cult let you summon Nar-Sie at roundstart and end the round after 5 instant conversions, it was more an option than a necessity. I wanted objectives to move the cult to do stuff but in this Dynamic day n age where even traitors have freeform objectives, such a mindset is not properly adapted.

-----

If I am to rework cult again (which I planned to do after I got used to spess again after my 1 year studies break), these would be my guidelines, I look forward to feedback just as I did when I posted the original Cult 3.0 doc (which is here by the way ( https://docs.google.com/document/d/1OLbhmL7uyTdVjXvpFIO6OJZMrbv7ISvFzzunA3FYX34/edit ) for those curious about some of my design choices at the time)



1. **Removing the ACT structure.** Like Kammer stated, spess is poorly suited to such a cinematic approach. Its main goal was to give cultists some way of powering up gradually so they wouldn't be at their full power right off the bat, and that's one of the good things it achieved, but at the cost of locking the cult on a one-way conveyor belt to Nar-Sie, which would inevitably cause a meta to emerge and every round feel more and more like the same.

As a replacement, cultists would have a bunch of rituals they could perform individually or in a group, that would earn them "points" that would serve the same purpose of weakening the veil. Those rituals would replace the current main objectives, and would be split by difficulty of execution (rewarding thus more or less points) but could be performed in any order, and potentially repeated with some restrictions.

This would free the cult of having to follow a routine and choose whatever the like the best.

Summoning Nar-Sie would still be a possible late game ritual, but back again as an option rather than a requirement for greentext. It would feature a revamped "Act 3-like" event with three main differences:
* Only one bloodstone, its location is known by everyone
* Every cultists have red eyes/particle effects visible through clothing, that hint at their allegiance, so the crew and non-cultists can immediately identify them as such.
* A time limit (I like Kurf's idea of an "eclipse", also I like Berserk), should the time limit expire, the cult loses their opportunity of ever summoning Nar-Sie again this round, but don't immediately die. They might or not however keep the effect branding them as cultists until they die, should the crew decide or not to purge them.

2. **Rework conversions again, remove box'ing, and add a deconversion ritual** with none of this backfire bullshit from when I first came up with it, however both conversion and deconversions will still require the spessman to accept or refuse them. There are two main aspects of conversion that I'd like to change:

First is adding a new functionality to the Seer rune, which would be to see invisible particle around spessmen hinting at their cult preferences, this would allow cultists to easily find players looking forward to join them, instead of slogging through failed conversion after failed conversion (which is neither fun for the cultist nor the guy getting box'ed). Should the target refuse the conversion, instead of getting box'ed, they will instead remain stun for about half the duration of a stun talisman, during this "stun" period, the cultist can use a soul gem to capture them as if they were in crit, or deal with them any other way. Loyalty implants would reduce the stun duration even further, letting players get out of this stun in seconds.

Second is adding a hard limit to conversions. Instead of letting the cult either spread endlessly or add a risk of getting outed should they convert/soulstone too much, the max amount of cultists will get cap'd depending on the max size of the crew (as in, the size the crew is/was when it had the most living players at the same time). It's not a "cult" if everyone and their mother is part of it. let's let rev be the endless conversion faction. It should also help reduce the anxiety of dealing with a cult infiltrated crew.



On top of the above there'd be many smaller tweaks to the existing runes and tattoos, but here I'd like first to get feedback on these guidelines I'd like to work on.

**Comment by DeityLink** [comment]
Also this opens the door to add all sorts of silly rituals down the line, and potentially more RP as well as said by some people on Discord.

**Comment by Accipitermaris** [comment]
1. cult leaders sound good; revs and ops has it. really just a great feature to any team antag so you can actually punish the guy that rushes the mauler without listening to his team

2. if the shuttle is called, the cult should receive a secondary minor victory objective to hijack the emergency shuttle so that they don't feel like they're supposed to just spam recall the shuttle, which i don't think anyone considers fun. while i'm on this point, revs should receive a similar objective when the shuttle is called because i see some rev rounds where the only head is flying around in space, the shuttle isn't called, and obviously the revs don't want to call the shuttle either. need a natural and healthy stalemate breaker, and this would work quite well.

i'm sure i will think of more, cult is a lot like communism

**Comment by ghost** [comment]
Generally sounds like good changes that would make cult rounds flow a lot more smoothly. However i would also suggest a couple further changes with the direction you are taking.

First, some kind of craftable cultist ranged weapon from the forge. Cultists going melee versus people armed with ranged weapons are generally bound to lose, so looting the armory or acquiring weapons some other way becomes necessary for survival in the bloodstones phase. I would suggest adding a "blood crossbow" into the forge that would do brute damage+slow down targets upon hit and work in a similar fashion to the normal crossbow(that traders get), however this one would be reloaded with blood instead of metal.

Secondly i would suggest making the soul-gems not remove people from the round permanently, as it seems like they will become a lot more common. This could be implemented with some kind of soul-gem-breaking mechanic, which would re-create the (heavily brutalized) body of the consumed victim.

**Comment by DeityLink** [comment]
@Baronzegit Those are some solid suggestions, that said I'm not eager to dive into cult weapons before I've redesigned the objectives/ritual structure first. (also are soul blades this bad as ranged weapons? or do people just don't know that they can fire projectiles?)

After some discussion on Discord, ideas regarding deconversion is that it would work like this, you would require a bible and a glass of holy water. Both holy water and bibles would be available from cargo as well, as part of an "inquisition" supply pack, that might also have incense or not, we'll see.

1. give the target a sip of holy water
2. touch them with the bible, which will give them a prompt to get deconverted, which they can accept or refuse
3. if they accept, a visible message and animation show the that they are no longer a cultist
4. if they refuse (or haven't made a choice in 10 seconds), the target vomits and gets weakened for a few seconds. it's then up to sec to decide whether to execute them.

implants could potentially block conversion again, in which case a 5th step would be to implant the target afterwards.

As this means that the station may again be filled with implanted non-convertible people, the cult's goals will revolve less around converting more crew members, and more about fun cult activities that may impede the other departments, and require their help to untangle potentially. Ideas include:

* break/disable lights in many areas of the station
* use a confusion/deafmute talisman/rune on a crowd of people
* poison food with cursed blood that make spessmen sick and mutates their body with eldritch limbs
* perform rituals in maint with candles and a corpse, gaining points as long as the setup is in place
* write runes in public places (I know right?)

stuff that would liven up the round and unlock higher tiers of runes for the cult to use. it would then be up to the cult to decide whether they want to lay low, just have fun harassing the crew.

Summoning Nar-Sie would have to take in a specific timeframe where to begin the ritual, which means that if the round has gone long enough, the cult won't be able to summon Nar-Sie at all, which removes the necessity to kill them to the last one to prevent the apocalypse.

**Comment by BomberBro** [comment]
illegal w objective
