### ISSUE TITLE
Pacify doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27092]
(WEB REPORT BY: rubylips REMOTE: 206.221.180.138:7777)
# Description
Pacified the cap as a wizard. He kept on shootin.

# Steps to Reproduce
Be wizard
Cap shoots gun
Pacify cap
Can cap still shoot gun? Myyystery

# What you Expected
Cap stops shooting gun

# What Actually Happened
You die

**Comment by DeityLink** [comment]
Pacified how?

**Comment by AutismSpider** [comment]
Wiz spell puts chill wax in people means chill wax is not doing its job of pacifying people

**Comment by GreatBigFailure** [comment]
Now that I am no longer extremely salty I realize that what probably happened was I got unlucky and cast it very early in a tick, so the chillwax didn't start effecting him until I was already dead.
I stand by this being an issue because chillwax is a silly workaround for pacify and causes things like this. Gonna request this one is removed though because it's misleading.

**Comment by ghost** [comment]
Chems are processed every 2 ticks in Life(), which is a pretty small interval. I had the spell use chillwax because adding a proper pacification "status effect" would be far more convoluted than you might think due to how pacification works and how you'd have to set and clear it on a timer.

**Comment by DeityLink** [comment]
Just because you won't fix it doesn't make it any less of an unintended behavior and a bug though.

A workaround if it's as @GreatBigFailure says would be to just call the reagent's reaction_mob() during the spell so it takes effect immediately.

Don't be lazy, be creative.
