### ISSUE TITLE
Horizon Nitrogen Scrubber Not Configured Correctly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27259]
(WEB REPORT BY: simonbeldruf REMOTE: 206.221.180.138:7777)
# Revision
bd134d3958150baf95ce22e3fb416947caeec2b4

# Description
 The scrubber for nitrogen in the gas miner room isn't configured correctly, which leaves the station with virtually no nitrogen supply.

# Steps to Reproduce
 Load horizon, vent some air, wait, look at gas meters in the atmos room

this can be fixed by reconfiguring the automations console to 144.1hz and setting up the scrubber n2_out with a script

**Comment by hbycyl** [comment]
after some digging, i apologize for this bug report's description -- the scrubber is fine. 
What fixed the problem was actually when I entered the gas miner's room I vented some gas into space. After some reading we have the following code for the gas miner:

`pressure_delta = min(pressure_delta, (max_external_pressure - environment_pressure))`
`var/transfer_moles = pressure_delta * CELL_VOLUME / (pumping.temperature * R_IDEAL_GAS_EQUATION)`

If we are only removing oxygen and nitrogen (and btw why `GAS_NITROGEN, 0.1*rand(2,3)*rate` and `GAS_OXYGEN, 0.1*rand(4,5)*rate,` ? We use four times as much nitrogen as oxygen! Shouldn't the rates on the miner roughly reflect that?), we're obviously gonna fill the gas room with the leftover stuff. That builds and builds until the pressure is around 9990kpa at which point you'll gonna be getting basically no new nitrogen.

easy fix, just give horizon a normal miner set-up

until this is resolved, interested atmos techs should set it up like the attached image. 
![horizon atmos](https://user-images.githubusercontent.com/36418376/88457475-5fd09c00-ceb9-11ea-931f-ae7daf901940.png)
If you don't feel comfortable using the AAC, just venting the bad gases into space should mostly solve the problem. However, if you just do this part, eventually the miner room will have too much oxygen , so you'll have to go vent it manually if it comes to that.

**Comment by Exxion** [comment]
Perhaps just add an overflow scrubber/vent that vents everything to space above a certain pressure threshold? You can just do that with the external pressure bound setting. You'd still get certain gases building up more than others, but you wouldn't clog the miner, so it shouldn't be a problem as long as the miner puts out more of the relevant gases than the station uses
