### ISSUE TITLE
cannot see meteors moving through space

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27307]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
ad88297da8d1505caef75d2d19c6ce2f6282ebeb

I cannot see meteors moving through space. Dorms told me to make a bugreport about it, I remember being able to in the past, and I'm not sure why this is happenning right now, something might have changed.

**Comment by gurfan** [comment]
it was a meteor round

**Comment by gurfan** [comment]
Other people were have the same problem

**Comment by Dacendeth** [comment]
I've definitely felt like i've been hit by an invisible meteor on a normal meteor storm before

**Comment by Kharkov72** [comment]
I wonder if there's something wrong with the super meteors from #26910

**Comment by Dacendeth** [comment]
I went and fired a bunch of meteors from the meteor gun and they were all invisible

**Comment by SonixApache** [comment]
on 1f256d195689efba7424d1310c383a72871e538f 
![meaty_whores](https://user-images.githubusercontent.com/8468269/88823205-1a67e380-d1c5-11ea-8265-8cf1354bbcbd.png)

Only blob meteors are invisible, which is probably caused by them only having _pixel icons.
Don't know what caused the issue in the OP, but it was probably not a code issue(?)

**Comment by Zth--** [comment]
> I went and fired a bunch of meteors from the meteor gun and they were all invisible

That's a meteor gun bug #23666

**Comment by DeityLink** [comment]
> 
> 
> on [1f256d1](https://github.com/vgstation-coders/vgstation13/commit/1f256d195689efba7424d1310c383a72871e538f)
> ![meaty_whores](https://user-images.githubusercontent.com/8468269/88823205-1a67e380-d1c5-11ea-8265-8cf1354bbcbd.png)
> 
> Only blob meteors are invisible, which is probably caused by them only having _pixel icons.
> Don't know what caused the issue in the OP, but it was probably not a code issue(?)

Spawning the projectile object themselves doesn't actually display their actual sprite since it gets set when they are fired. Except for beams, most projectiles (such as meteors) ONLY need the _pixel sprite. So if meteors are missing theirs they'll be invisible when fired, regardless of whether they're visible when spawned manually or not.
