### ISSUE TITLE
horizon has no holodeck

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27315]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
1f256d195689efba7424d1310c383a72871e538f

# Description
bruh
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by GeneralVeers25** [comment]
Horizon is already tight on space and the holodeck is huge (11x11 tiles). Packed doesn't have one either and neither station needs it. I'm not planning on adding one.

**Comment by Kurfursten** [comment]
The deck size can be altered; there might be some interesting gimmicks you could make from a tiny holodeck of say, 3x3 (you could even do just directional windows instead of the full tile window+grille stuff.

Maybe a little zen chamber, rage cage, tiny beach, etc. Think of it like Hakoniwa, box gardening.
