### ISSUE TITLE
Colourful Bugs: Election 2020

### ISSUE THREAD

**Issue by GreatBigFailure** [d3athrow/vgstation13#27585]
By request I've been working on different colour variations for bugs. Long story short is after tinkering and getting black and white sprites made to fix some issues we now need to decide how colourful bugs are allowed to be. The colour values are going to be limited to a maximum (and maybe minimum) range to prevent visual abominations. I would like to know which direction people prefer.
**These values are easy to change. These are not the only two options.** 

This is a range limited from 0-50, each bug has a maximum value of 1-2 colours and a minimum of the remaining, aside from the top which are 0/0/0 and 50/50/50. The bottom is 25/25/25
![bugs2electricskittaloo](https://user-images.githubusercontent.com/64218965/90710958-89d56e00-e26d-11ea-8782-51e532733916.png)

This is a limit of 0-90, same deal with max/min examples. This is better organized though; left side is black, red, blue, green. Right side white and mixes. Bottom is 45/45/45
![newbugz](https://user-images.githubusercontent.com/64218965/90711035-b38e9500-e26d-11ea-9dc0-66f29374b1d8.png)

As I said these ranges are easy to change. Vote and such. The current PR uses a non-greyscale'd range of 10-50 in its OP. 

[vote][sprites]

**Comment by SageOfLight** [comment]
After some personal testing, I think 80/35/35 helps alleviate a lot of issues with certain colors. It allows a range of darker colors and I think red should be the primarily overpowering choice due to the race inherently being envisioned in earthy tones.

![image](https://user-images.githubusercontent.com/10042344/90717419-2b13f280-e275-11ea-8114-62c2d40a002d.png)
