### ISSUE TITLE
Dropped Mat Synth as a Mommi

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27601]
(WEB REPORT BY: serwind REMOTE: 206.221.180.138:7777)
# Revision
fc59bc962308049faa24d3433acbe1c772478da1

# Description
I somehow dropped my material synthesizer as a mommi

# Steps to Reproduce
I do not know. I tried making glass but didn't have the charge, then clicked somewhere (I forget where exactly) then my material synth dropped. An admin saw it.

# What you Expected
Me not dropping the material synth

# What Actually Happened
I dropped it

**Comment by SECBATON-GRIFFON** [comment]
did some testing, to note:
- the item is still stored in your modules after dropping
- not just the mat synth but ANY module can be dropped
- not just with glass either

the root cause seems to be going below 100 charge of any kind, where the code refuses to put the module in your hand but instead drop it. only applies for MoMMIs, not borgs
