### ISSUE TITLE
Outfit datums' prescription glasses stop being prescription glasses when unequipped

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#27793]
Might not be outfit datum's fault this time: #26730 made it so `unequipped` resets `prescription` to its initial value. Outfit datums is setting `prescription = 1`, but the initial value obviously remains unchanged.
The obvious solution is to remove wearing glasses over glasses because what the fuck is this code

**Comment by ShiftyRail** [comment]
This is definitively not outfit datums

**Comment by DeityLink** [comment]
> This is definitively not outfit datums

ehhh it kinda was at least partially (outfit datums just set "prescription = 1" which not only was no longer sufficient to deal with nearsightedness after the nearsighted_modifier var was introduced, but also removing glasses reset their prescription var so just setting that var to 1 wasn't gonna cut it). Anyway it's fixed by #34490 now.
