### ISSUE TITLE
Summon snacks removes items from all three of your hands, does not put food in third hand.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27859]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
0806b26f8ca2b00addb6dd470e68986b68662d91

# Description
I feel gyped.

**Comment by Kurfursten** [comment]
also, summon snacks puts food in the hands of mushmen who can only eat by standing on food @Rubylips

**Comment by GreatBigFailure** [comment]
Mushmen can still feed people though, can't they? In that case it's something I didn't think of but now intended. Skeletons for example should be able to infinitely counter summon snacks as they don't receive the chems from it when eating, that one is intentional.

The three hands thing I should fix. Possibly via a rare and elusive third snack.

**Comment by DeityLink** [comment]
And he never did.
