### ISSUE TITLE
Mommis should be able to use a grinder.

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#2793]
Don't see why they shouldn't.

**Comment by AutismSpider** [comment]
Add in hydro-trays/dirt  then as of right now mommis can't harvest stuff off hydro or dirt trays 

only way for mommi to get plastic is to nigger it form the mechanics work shop

**Comment by Midaychi** [comment]
Well, TECHNICALLY, a mommi could use a kudzu seed pack and the botany machines to make plasticilium vines, which occasionally drop their fruit as they spread. I say technically, because you probably don't want to do that on the station major. Probably construct a pressurized window space room for it.

**Comment by AutismSpider** [comment]
Thing with that is it make both kudzu pods and plasticillum on top of that mommi needs find the Products gene 1st

chemicals stuff is fuck up for now so all they get is anti toxin off the plasticillum made form the vines.

**Comment by SarahJohnson489** [comment]
I'd like to add it'd be nice if they could use microwaves as well.

**Comment by Midaychi** [comment]
Vines actually do transfer over so all you have to do is apply it backwards. I'm pretty sure vines are on the vigour loci anyways, not the product.
Also the issue that complained about xenobotany being broken was closed because apparently d3athrow fixed it. If it's not fixed recently then you might want to re-open #2506

**Comment by 9600bauds** [comment]
Yes, xenobotany was fixed, you can have an all-plastellium producing Kudzu tray. But that'd still be a laughably convoluted way of making plastic.

**Comment by AutismSpider** [comment]
just grow the plastellium normally.

making wall of space vines just big no no for me.
