### ISSUE TITLE
Autoborger Not Giving Malf-Slaved Borg Role

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#27956]
Building a borg gives it the role though.

**Comment by toomykins** [comment]
an extra lawsync() in Robotize should fix this i think, since it does some fuckery with turning you into a borg and then making an MMI to put in the borg and then making you the MMI.

I've no idea why building a borg even makes it work, new() calls connect_AI() which calls lawsync() which checks for mind, but new() is called before there is a mind.. it boggles my mind.

**Comment by DeityLink** [comment]
Fixed by #30161
