### ISSUE TITLE
Lawyers (and IAAs and Bridge Officers) Do not have access to Command and Sec Freqs in their notes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27964]
(WEB REPORT BY: drawsstuff REMOTE: 206.221.180.138:7777)
# Revision
339ef2fd27f772ac2512543c4c66552105b7b19f

# Description
Lawyers (and IAAs and Bridge Officers) Do not have access to Command and Sec Freqs in their notes
# Steps to Reproduce
Ready up as a lawyer
Check notes
Keys will be missing
# What you Expected
3 Radio Keys
# What Actually Happened
Only Common

**Comment by BomberBro** [comment]
lawyers don't have security radios for a reason, briefcase boy

**Comment by TGFH** [comment]
Actual feature.

**Comment by toomykins** [comment]
IAA only get common and command on their headset afaik, i guess command should be added to their notes.

**Comment by toomykins** [comment]
https://github.com/vgstation-coders/vgstation13/blob/339ef2fd27f772ac2512543c4c66552105b7b19f/code/datums/outfit/civilian.dm#L561-L566
https://github.com/vgstation-coders/vgstation13/blob/339ef2fd27f772ac2512543c4c66552105b7b19f/code/datums/outfit/outfit.dm#L272

Only bridge officers get a special headset that gives them access to the Command channel. No civilian but the head of personnel has access to the Security channel.
If you want in on Command stuff, man the bridge.

**Comment by BurntDevil** [comment]
I fixed this. It was fixed. Who fucked my fix?

**Comment by BurntDevil** [comment]
#27747 deleted the code I did to give the notes, so thats the best I can think of as to why it stopped working.

@DamianX

**Comment by DamianX** [comment]
Yeah, I didn't realize the list of frequencies given to them was different from the one their headset supports...which makes me wonder why that was a thing. If all an IAA has to do in order to get access to command and security channels is change the frequency of one or two SBRs, why not skip the middleman and give them headsets with those channels anyway?

**Comment by BurntDevil** [comment]
well yes, thats on my list of things to do actually. i was working on a content push for bridge officer that would have done that itself but it got corrupted. I think IAA/BO/Lawyer having a command/sec headset across the board is a solid move at this point.

I even had sprited a new headset for that for them, Ill have to resprite that.

**Comment by drawsstuff** [comment]
Laywers and IAAs get normal headsets, however, they also get the comms keys for security and command. This is purposeful, because if their headset is say, stolen: they have no means to defend themselves, unlike command and security. They're so interwoven into these jobs however that lacking these keys makes their job several magnitudes harder, since it's entirely their nature to watch the watchmen, so to speak.

I'm not stating in this issue that they suddenly stopped getting special snowflake headsets, they never have. I'm stating a much lesser known feature, and that's that they have suddenly stopped having access to security and command keys in their notes.

**Comment by DeityLink** [comment]
Fixed by #27747
