### ISSUE TITLE
[Box] Mine APC lasts for minutes and won't recharge

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#2818]
The lights go out in minutes and the mech recharger outside the research outpost is always off as a result too

**Comment by Probe1** [comment]
The bug as been around for approximately a month

**Comment by dylanstrategie** [comment]
This "bug" is caused by the Mining Outpost using a real SMES. Since there isn't any way to generate power save for PACMANs, the power goes out on the asteroids rather quickly

The asteroid would benefit from "natural" lighting that doesn't need electricity, as all the lighting drains the area APC at sanic speed

**Comment by Probe1** [comment]
I referred to it as a bug because it previously was not an issue.  

Varedit the SMES to never run out, remove like the majority of the lighting on the asteroid because miners do not give a flying fuck we're literally made of light sources and were mesons to boot, or something.

It's not a priority.

**Comment by dylanstrategie** [comment]
It indeed isn't a priority, but I want to try and deploy an interesting fix instead of just delete everything

**Comment by Probe1** [comment]
Go for it.  Keep in mind miners will not care to involve themselves in any of the solution.
