### ISSUE TITLE
Masks/hardsuits no longer hide gender

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#28200]
They used to. They ABSOLUTELY used to for Vox, but now they don't for anyone.

![image](https://user-images.githubusercontent.com/6062247/99220662-e4f6fe00-2793-11eb-9476-dbab7cbf2144.png)

![image](https://user-images.githubusercontent.com/6062247/99341675-327c7500-283f-11eb-959f-8bee2c1a4661.png)

Please fix

**Comment by Exxion** [comment]
It was broken for many years, then was fixed several months-maybe a bit over a year ago, then broke again sometime in the last few months

**Comment by DamianX** [comment]
It was broken for many years, then was fixed by #18466, then something Deity did broke it again, but I can't find the PR. I just remember being passive-aggressive with him in some issue about this.

**Comment by Exxion** [comment]
Wow it was over *two* years ago? How time flies

**Comment by kilozombie** [comment]
I don't mind c*ders but I would really appreciate if this was re-fixed from being un-fixed

**Comment by Zth--** [comment]
#26727 is the one that added these lines

https://github.com/vgstation-coders/vgstation13/blob/c873c95f926331c9b7f74e32c5bce58e61569ca5/code/modules/mob/living/carbon/human/update_icons.dm#L1383-L1384

I think these lines are buggy too

https://github.com/vgstation-coders/vgstation13/blob/c873c95f926331c9b7f74e32c5bce58e61569ca5/code/modules/mob/living/carbon/human/update_icons.dm#L1385-L1388

Very shitty and hard to maintain.

To be clear the first one is a feature. The second one is a bug.

In this case you can determine someone's gender because the helmet has a glass visor. That's the feature Deity introduced and the first snippet of code I pasted.

After some testing I realized that masks (for example the plague doctor mask) should be covering the identity but it's failing to do so. That's the second snippet of code. Helmets could be buggy too, but I didn't test them.

**Comment by Zth--** [comment]
If we can agree on what helmets/masks should hinder the identity and what not then we can work on a fix.

**Comment by kilozombie** [comment]
@Zth-- I'm actually confused by this entire implementation. If you can tell somebody's identity, you should probably be able to determine their gender. If you can't determine their identity, why not just not let you identify their gender?
Just make it the same check.

**Comment by Zth--** [comment]
Yes, that's exactly the problem, we have two systems doing the same thing but with different results

The whole identity system is an entangled mess, not long ago we had a round of bugfixes about it. There's bitflags everywhere and many duplicated variables and methods. Someone touches one thing on one side and it breaks everything on the other side.

**Comment by kilozombie** [comment]
Horrifying
I can't speak for everyone but w/r/t 

>If we can agree on what helmets/masks should hinder the identity and what not then we can work on a fix.

I think the answer should be, one and the same with what hides identity. Not a perfect system, but would apply fine to most cases. I could also think that, like, a hardsuit should hide gender, and masks/helmets hide identity?

**Comment by jknpj** [comment]
@zth i just want to add say that the mask properly covers the indentity in #28213, so you're not wrong.

**Comment by jknpj** [comment]
oh wait this is *gender*

**Comment by DeityLink** [comment]
Alright so let me explain the problem with hardsuit helmets not properly covering gender.

The problem stems from the fact that the default spacesuit helmet (/obj/item/clothing/head/helmet/space) is in fact transparent, so it benefits from a visibility part override over its EYES. This means that all other helmets have that override by default, and because the eyes are visible, their FACE (which is just (EYES|MOUTH|BEARD) ) is also visible, and thus their gender/identity is exposed. The default helmet also has the entire FACE visible by default.

So the obvious fix is just to manually remove that bitflag from other helmets. by giving them `body_parts_visible_override = 0`

I'll do that now.
