### ISSUE TITLE
Lasers reflect off things they're not supposed to

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#28453]
I've seen other things randomly reflect too, like off a wizard one round and someone said a laser reflected off a chicken they shot once too.
Picture is a zombie getting shot and reflected
![image](https://user-images.githubusercontent.com/26881007/103157702-c9fcae00-4783-11eb-9697-13a16b4282c3.png)

**Comment by SonixApache** [comment]
oh, maybe that's why the cyberhorrors were reflecting lasers

**Comment by DeityLink** [comment]
@PaulRitter I haven't read your new laser code yet but any idea how that might occur?

**Comment by Exxion** [comment]
I *believe* this happens when the beam misses someone. Projectiles that physically hit someone have a chance to still miss depending on various circumstances. In this case `forcedodge` is set to `-1` and later this value makes the projectile attempt to pass through the object it physically hit. However, with beams, it instead reflects because `permutated` increases in length in this case and this is how the beam determines if it should reflect, for some reason

**Comment by PaulRitter** [comment]
@Exxion i was unaware missing was also counted towards the permutated list.

because me being unable to directly hook into the result of to_bump (since i needed to_bump to ONLY be called when hitting something, which i couldn't predict unless copy and pasting /proc/Cross) i had to check the permutated list to check if it reflected off of something. a workaround for this would be to set a `/obj/item/projectile/var/reflected`-bool in `/obj/item/projectile/proc/to_bump` if something reflects off of the target.

i remember me eating away at this for quite a while so there might be more reasons i did this, altough i don't remember them now :/
