### ISSUE TITLE
Telepathy symptom induces genetic damage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28469]
(WEB REPORT BY: doomergloomer REMOTE: 206.221.180.138:7777)
# Revision
ac51dd05376fea97d0df4b71585e84404dd7f55e

# Description
When a virus with the telepathy symptom activates, it has a chance like with all genetic changes to induce negative mutations as well as radiation damage.  If this is cured, the telepathy symptom never fires again.
# Steps to Reproduce
1.  Contract virus with telepathy
2.  Random chance to gain disabilities

# What you Expected
To gain telepathy
# What Actually Happened
Lost telepathy when I cured veganism swedishness, etc

**Comment by ghost** [comment]
This is literally a feature, ryetalyn is supposed to fix ALL genetic conditions including beneficial ones

**Comment by DoomerGloomer** [comment]
So the viral symptom inducing other genetic damage, and never procing again, is also a feature?

**Comment by Dacendeth** [comment]
toggling on a genetic block by any means toggles on your other bad genetic blocks, the virus only procs once so it never happens again after you rye it away. You could easily do some quick genetics to figure out which block is telekinesis and which is bad genes though thanks to the virus.

**Comment by DeityLink** [comment]
> When a virus with the telepathy symptom activates, it has a chance like with all genetic changes to induce negative mutations as well as radiation damage.

![image](https://user-images.githubusercontent.com/7573912/103414022-6ce66b00-4b7c-11eb-918e-cbf675dce309.png)

The symptom only tweaks that one block, but when calling domutcheck, there is a small chance that other blocks might trigger a power despite their value not changing (because blocks always have a "chance" to activate depending on their value, and the change to the telepathy block just guarantees that it'll activate.)

@ShiftyRail was that intended? You could use genemutcheck instead to guarantee that only telepathy is enabled without causing other mutations to potentially activate.

@ancientpower 

> This is literally a feature, ryetalyn is supposed to fix ALL genetic conditions including beneficial ones

That's not quite the issue here. like @DoomerGloomer said the way the symptom works is that it only ever activates once, and if I had to guess it's because they didn't think of rye being used. by either using genemutcheck or just checking if the block is still active, we can allow the symptom to re-proc again and re-induce the mutation periodically as long as the mob remains infected.

@Dacendeth 

> toggling on a genetic block by any means toggles on your other bad genetic blocks

"by any means available to geneticists", but not in the code, and it doesn't have to be the case here either. Counter-examples that don't cause other blocks to activate include:

* cursed dice (which gives a variety of potential mutations)
* the mutate and clown curse one-use spellbooks when they recoil
* the detective's noir bar drinks
* admins toggle-ing blocks

Personally I'm of the opinion that the mutation should come back until the virus is cured, and that genemutcheck should be used instead as to not cause other undesired mutations.

Now that you mention it though, we have the DNA Degradation symptom that gives clone damage but it doesn't cause any SE/UI change and I think that's a missed opportunity.

**Comment by Dacendeth** [comment]
Detectives noir and better liver actually trigger random genetics roundstart

**Comment by DeityLink** [comment]
@Dacendeth you are correct, and I'm pretty sure it's unintended as well.

**Comment by Exxion** [comment]
Same goes for bartender's sober
I've actually gotten telekinesis roundstart on two occasions due to that

**Comment by DeityLink** [comment]
@Exxion isn't that the better liver that he was mentioning?

But yeah I've been roundstart blind as bartender for similar reasons.

**Comment by Exxion** [comment]
It is indeed the better liver he was mentioning, but he said detective
There's no difference of course but I wanted to bring that up

**Comment by DeityLink** [comment]
Dormant gene awakening made explicit by #29901

**Comment by DeityLink** [comment]
Although this symptom could be modified to use genemutcheck() instead but I never got a reply from @ShiftyRail when I pinged in january 😔
