### ISSUE TITLE
Desk Bells not sending signal

### ISSUE THREAD

**Issue by frangi** [d3athrow/vgstation13#2853]
This was on the server right now

How to reproduce:
-Make a deskbell case
-insert wire
-insert radio to your prefered freq (I used 151.5 -  30)
-screw and wrench the bell
-buy ringer app
-set it to the same freq
-ring the bell

The bell sound play fine, but you receive no notice/sound on your PDA.

**Comment by ComicIronic** [comment]
@Deity_Link

**Comment by DeityLink** [comment]
Just ran a test, actually sound comes from the PDA, hard to notice if you hear it at the same time as the bell's sound, however there is no notice message indeed because I'm an idiot and had a visible message come out of the PDA itself instead of having it come out of the turf. Which means you only see the notice if the PDA is standing on the ground (not in your hand/on a belt/in a bag). Fixing that right now.
