### ISSUE TITLE
You move very slowly while the hecate is on your back.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28666]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
6365f8e36e35d034b364b1628f997d75ae238a2f

# Description
Place Hecate on backpack slot, move at a snails pace. Very odd.

**Comment by APCUnlocked** [comment]
It's a big gun so it weighs you down

**Comment by Dacendeth** [comment]
A lot of items slowdown only works while twohanding them or wearing them, who knows what is intentional.

**Comment by Exxion** [comment]
Long ago (not really even that long actually), slowdown worked on all held items
Some people said to make it not work on held items at all
I suggested a system where flags would specify what slots slowdown applied on
Nobody did that and instead someone just made it so that it only applies on held items when twohanded, and on worn items always (as had always been the case)

**Comment by DeityLink** [comment]
Hecate shouldn't slow you down when on your back, that's a bug.

**Comment by Exxion** [comment]
The simplest way to fix this is to just have its `slowdown` be 0 by default and only add it when it's wielded, but I still maintain that the flags system would be better
