### ISSUE TITLE
Feature Request: Ghosts can feed singulooses by *spin-ing on top of it.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#28711]
It'd make for some post death interaction, you could limit it to only singulos that have left the singulo containment or bagulooses.

[featurerequest]

**Comment by Kurfursten** [comment]
I dead, restart

**Comment by Eneocho** [comment]
1 energy per spin, enough to keep a singulo going but not enough to make it grow. Make it apply only to bagulooses. Boom.

**Comment by PrimeDSS13** [comment]
is it ethical to *close* a feature request

**Comment by Kurfursten** [comment]
Ghosts don't actually spin, because they aren't living. Instead, it sends this to deadchat

>Patrick McGrey moans, "*spin"

Since it's just a saychat message, it doesn't incur a cooldown, either. Meaning even at 1 energy per spin, you could just slam that macro button to do it a ten times a second.

Moreover, singulos don't really need just a bit to 'keep them going'. Either they're big enough to consume departments and grow or they're 1x1 and can't get any smaller (they won't die at 0 energy).

On top of all of that: if someone fucks up their baguloose, that's their fault for planning poorly. Does baguloose REALLY need to be babyproofed?

**Comment by ShiftyRail** [comment]
Haha, no

**Comment by Eneocho** [comment]
It was worth a try to suggest this.

**Comment by DamianX** [comment]
Perhaps the incentive structure that led to the creation of this issue should be changed, then.

**Comment by Eneocho** [comment]
> 
> 
> Perhaps the incentive structure that led to the creation of this issue should be changed, then.

Perhaps. Closing the PR.

**Comment by Eneocho** [comment]
> 
> 
> Perhaps the incentive structure that led to the creation of this issue should be changed, then.

Perhaps. Closing the FR.
