### ISSUE TITLE
Proposal: Clones Locked to Alert Level

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#28885]
Security, silicons (being able to go combat), and traders (ability to lock down port) are all affected by alert level. Why not medical? Some day we might even see different cargo crates based on alert levels.

The idea is this: cloning pods simply won't activate at lower than [negotiable alert level]. This is because cloning is a taboo last resort only to be used if the crew is in dire straits. Lorewise, clones might have issues proving their identity to banks/etc or have serious lack of legal rights back home or something. In other words, you gotta ride the wild ride unless the crew is in deep shit, at which time NT says fuck it, bring in the clones. This would encourage more classic doctorin' and less clonebay. Meanwhile it doesn't interfere much with the ability of doctors to to the clone scramble when shit gets real, especially since most antags automatically raise alert to red when it's time to go loud.

This would also incentivize the CMO to be more active in red swipes.

**Comment by bathosbathtime** [comment]
Cloning unlocks on code green, the station is now on code rainbow by default so we can let in clowns like you.

**Comment by TurboGay** [comment]
Clonebay isn't really as prevalent as some people think it is, most doctors I see or play with will do a lot of classic doctoring over clone and tube unless the situation is dire (10+ bodies backed up) so I guess I don't really see the purpose in locking it behind a code, namely because new medbay players will suffer even more when they don't even have it as an option when they're genuinely stumped with a patient. And that might just lead to even less people playing medbay, which is already a problem as is.

Then there's the matter of people getting fatally injured in ways that have to be fixed with either cloning or a headswap, which without cloning (in the event of getting handed someone's head) can't have their identities fixed without a clone job, since you'd need their body to do such otherwise through genetics. And raising the code to red merely to fix someone in that manner seems clunky at best. I'm not horribly attached to cloning in it's current state, but I think if you want to make a change to it, codes aren't it.

**Comment by Arthurdentistss13** [comment]
Cloning is fine as is

Simple 'as

**Comment by mentgah** [comment]
why are coders obsessed with cloning?

**Comment by ShiftyRail** [comment]
This is a really strange proposal. From the "lore" and immersion standpoint, why would NT willingly lock a life-saving (life-renewing, in fact) equipment to a particular code?

**Comment by GreatBigFailure** [comment]
I don't like the idea of a doctor asking command to raise alert level just to clone someone then drop it down again.

**Comment by DrSnips** [comment]
This does nothing but enable code blue at round start. There is no reason you wouldn't other then MUH ARE PEE. The more things you put behind code blue the more enticing it is for people to enable it round start. It doesn't negatively impact the crew so why would people object?
The CMO themselves can enable it too since they have bridge access. This is a dumb idea.

**Comment by Kurfursten** [comment]
@DrSnips Just theorycraft. No one does that now. There's nothing stopping you from red swiping immediately in fact.

@GreatBigFailure They shouldn't. In those cases they should do a head swap + UI syringe if there's really no other way to deal with the body. If you wanted to have a failsafe fallback though you could require something like IAA swipes on cloner to unlock it for the next 30 seconds if the lawyer approves of spot cloning.

@mentgah It's quite the opposite, the thread is always asking for some way to discourage cloning. You don't see many solutions proposed on github.

**Comment by ghost** [comment]
~~Only if the armory is also locked to code red.~~

We already put a limit on speedcloning with people's limbs flying off, I don't think we need more code-based limits on player gameplay choices that are largely a matter of preference. Why would we limit the ability of doctors to play the game in a way that some particularly vocal people don't like if it's not violating the rules or the spirit of the game in any way? If there's a benefit to gameplay argument, I'd like to see it made, but right now it just feels like an arbitrary restriction.

**Comment by gurfan** [comment]
lol

**Comment by ghost** [comment]
cloning is already cucked enough, leave it be

**Comment by Kurfursten** [comment]
I think it's pretty clear at this point that there isn't support for this (which is what I suspected, and why I didn't bother to just PR it), but I'm going to leave it open a bit longer in case someone comes up with any other ideas or insights.

"Do something about cloning" seems to be one of our most persistent community requests, but maybe that's just a vocal minority that keeps harping.

**Comment by GreatBigFailure** [comment]
>IAA swipes on cloner to unlock it for the next 30 seconds if the lawyer approves of spot cloning.

@Kurfursten Now that I like. I think I could get behind cloning requiring head/IAA access except on code red. 
With that said I'd like to see another, more costly and less cure-all, method of bringing dead players back added before we nerf cloning too much. Right now it's just defib and cloning. Defib has its limitations and we want people to play the video game. That's a taller request than this though.

**Comment by west3436** [comment]
>greyshit traitor welder bombs tool storage at 12:05
>i now have to operate on 5 assistants all with >600 damage before I've even made medbay starting chems

**Comment by Eneocho** [comment]
Clonebay is cringe as hell, but most medbay players (barring the newer ones) prefer to do surgery+chems. Besides, cloning was already nerfed horribly when the speedcloning removal (speedcloning removes limbs and shit) was merged.

**Comment by TGFH** [comment]
Alert levels are a joke and I don't see how this would make the game more fun for anyone.

**Comment by Blithering** [comment]
Maybe add a different kind of cloning that unlocks as an emergency measure on code red
Flash Clones!
Needs no original body, pings ghosts to get in. Spawns bald with a number instead of a name, and has a max health of 50, so essentially taking double damage from all sources. Can only be made with an upgraded cloner.

**Comment by Kurfursten** [comment]
I forgot I was going to close this

Kind of a funny idea though @Blithering , I gotta say. Maybe a little too wild but definitely amusing.

**Comment by SootyBear42** [comment]
Honestly, fuck right off with that idea.
