### ISSUE TITLE
Cult doesn't spawn any chaos emeralds and softlocks itself

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#28938]
What it says on the tin, you do the sacrifice but no bloodstones show up, though it lets you still spread blood (which then orders you to go to a nonexistent anchor stone).

**Comment by DeityLink** [comment]
There needs to be some kind of Discord bot that pings me whenever a cult bug gets added otherwise I would miss stuff like that.

What map did it happen on? When did it occur on as well? The Anchor objective should runtime altogether if there are no bloodstones.

**Comment by DeityLink** [comment]
looks like it did.
![image](https://user-images.githubusercontent.com/7573912/109404490-e1643d00-7966-11eb-98ba-ae39763f7634.png)

**Comment by DeityLink** [comment]
aha 
![image](https://user-images.githubusercontent.com/7573912/109404521-2daf7d00-7967-11eb-85a1-849093f51792.png)

**Comment by DeityLink** [comment]
Looks like one side of the map had no valid turf which caused the entire proc to explode mid-flight. I can prevent that from happening though. The bloodstone that spawns under the altar is supposed to guarrantee that at least one shows up but if the altar is too far from the station center AND the first corner checked for bloodstone has no valid turf we could have this scenario occur. By preventing the proc from runtiming we'll only have one less bloodstone at best. I'll add a failsafe so that if no stone for some mysterious reason a different message is displayed.

**Comment by DeityLink** [comment]
Which map was it though?

**Comment by Eneocho** [comment]
> 
> 
> Which map was it though?

It was Box.

**Comment by DeityLink** [comment]
Should be fixed by #29251
