### ISSUE TITLE
Polyacid kudzu is dumb.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#29019]
There's just no way to deal with this shit and it's so easy to make, something about it needs to be toned down.

**Comment by DamianX** [comment]
It's pretty dumb, even scrungularities have counterplay, polytrinic acid kudzu does not

**Comment by GreatBigFailure** [comment]
Just make plant b gone. Vines are easy to deal with.

**Comment by DamianX** [comment]
make a video of yourself containing a single polytrinic acid kudzu tray one minute after it was planted.

**Comment by Eneocho** [comment]
While dumb impossible, I wouldn't nerf it. Kudzu is dangerous in any shape, polyacid is just the most flagrant way. High Carnivore Kudzu is more fun, but the powerfellas that make kudzu don't realize that.

**Comment by thefatgoat** [comment]
GBF is correct, Plant-B-Gone spray (easily made in both medbay and the kitchen, the 2 places surrounding botany) and kudzu control crates (from Cargo) both counter any kind of kudzu hard. You can easily clean up an entire department of kudzu in a couple minutes with antiweed grenades and spray.

The problem is the same as Blob. Most of the players are literal NPCs who, instead of going to fetch the hard counters, would rather run at the green thing and click it with a welding tool. And then keep clicking it with a welding tool for 5 minutes. And then complain that it's still growing despite their heroic welding tool efforts.

You can nerf kudzu so that it grows slower if it has polyacid in it, that would be an acceptable balance change. But it wouldn't fix the crew's problem of trying to ungabunga it 1v1. And when it turns out you STILL can't ungabunga 1v1 polyacid kudzu even after it gets nerfed, the ungabungas will want it nerfed again.

**Comment by Dacendeth** [comment]
What if it was changed to Ironrot as the requirement to destroy floors/walls, it would still be as devastating but you could fight it as it wouldn't kill you unless you put more effort into it.

**Comment by gurfan** [comment]
i ded

**Comment by Killette3** [comment]
> make a video of yourself containing a single polytrinic acid kudzu tray one minute after it was planted.

If you realize all the solutions to this you could even extend it to 2 minutes under the best non-mutagen related scenarios. There are some very hard counters that polyacid kudzu has that are very reasonable to obtain when you're in a powergame needing situation

**Comment by GenericGoose** [comment]
no one wants to fight fucking kudzu just remove it from the game its fucking annoying thats all

**Comment by Eneocho** [comment]
> 
> 
> no one wants to fight fucking kudzu just remove it from the game its fucking annoying thats all

Then where will I get the allicin for the autismweed?
Also, even if we completely removed kudzu, there's other vines in the game. And many "kudzuloose" events aren't actually kudzu but rather other plants, most recently, towercaps.

**Comment by Blithering** [comment]
The main problem for the "miracle instawin" stuff is kudzu destroys walls but not the girders left behind, and smoke and spritz don't pass through girders, meaning there's always plenty left to grow back. Not that it matters all that much, the amount of breaches even a moderate poly acid kudzuloose causes is a guaranteed shuttle call even if you clear it all out.
