### ISSUE TITLE
Virus symptoms of the same type can be stacked

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#29266]
Most noticeably spiked virus can instantly kill people you bump into if you make 50 clones of the same virus.

**Comment by Eneocho** [comment]
feechur

**Comment by DeityLink** [comment]
viruses CAN be stacked, the issue is specifically with those that have "bump into people" effect (and I don't think there is any other than Porokeratosis Acanthus) (oh wait nevermind there is butterfly skin too, so that means you can currently create "poison blood" full of copies of Butterfly Skin viruses at stage 3+, inject it into people, and watch them insta-die? Amazing.)

I can rework it so that only one virus with on_touch() symptoms may proc on touch at a time
