### ISSUE TITLE
Bees don't gather nutriment

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#29275]
#### Description of issue
Present nice, filling, nutritious, optimized plants to the bees, be shocked as the bees rather starve than touch any of them.
It happened in two different rounds, with all kinds of different plants – GMOed and natural – being offered to the bees.

#### Difference between expected and actual behavior

I don't expect bees to be anorexic

#### Specific information for locating

![image](https://user-images.githubusercontent.com/22218882/115153843-31fb3b00-a078-11eb-9e66-77c30c20d708.png)
![image](https://user-images.githubusercontent.com/22218882/115153871-52c39080-a078-11eb-8d2d-a902bf910bd0.png)

[bugfix]

#### Server revision
cde8007bda07ac62e9dc992be30e6d715a82081a

**Comment by Kurfursten** [comment]
Bees harvest nectar from plants they don't eat picked fruits

**Comment by StreptoMutans** [comment]
They should, but they ignore all the plants growing around them

**Comment by Killette2** [comment]
I was having an issue with this another round too

**Comment by Kurfursten** [comment]
If you encounter this again ask the admin to VV your bee swarms and check the following values to report:
`state`, `target`, `home`.

Also just generally check `worker_bees_inside` and `nutrilevel` in the apiary

**Comment by DeityLink** [comment]
I've run some test locally and holy fuck everything is broken.

Bees cannot path over tables, apiaries, or other bees, which means they can never re-enter their apiary, thus leading it to starve. However if you pull a bee you CAN drag it over the apiary, or a table, or other bees, which means the issue is pathing-related. (They don't either move on top of mobs they're trying to attack like they used to)

I fail to see any recent changes that could have caused this behaviour, when did it start occurring?

**Comment by StreptoMutans** [comment]
I honestly don't know. Haven't seen anyone keep bees for a while. Botanist seems to be a job mostly occupied by newer players, maybe all who tried just thought they sucked at beekeeping.
Could've been months

**Comment by DeityLink** [comment]
@StreptoMutans nah we've investigated and found that #29078 was the cause, from 15 days ago.
