### ISSUE TITLE
dynamic spawns too many midround/latejoin roles too quickly

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#29351]
tone it down again thanks

**Comment by Eneocho** [comment]
Is this the unforeseen consequence we were warned about?

**Comment by DeityLink** [comment]
@ShiftyRail

**Comment by ShiftyRail** [comment]
The change happened on 14/04.

Here's a list of midround and latejoin antags by type since then.
I originally planned to do two weeks, but this was too painful so I did just one.

21/04 to 28/04, adminbuses excluded,  
- Syndicate traitors : 51
- Loose catbeasts : 12
- Wizards : 16
- Soul Ramblers : 4
- Revs : 5*
- Ninjas : 13
- Malf : 1
- Vox raiders : 2
- Plague mice invasion : 3
- Nukies : 0 (!!!)
- Prisoner transfer : 0

Do note that Provocateur cost was also significantly reduced, and that the only midround revs we have seen on this period were provocateurs.

For comparison, the week before this change was merged, from  06/04 to 13/04 : 
- Syndicate traitors : 45
- Loose catbeasts :13
- Wizards : 5
- Soul Ramblers : 2
- Revs : 2
- Ninjas : 7
- Malf : 0
- Vox raiders : 0
- Plague mice invasion : 2
- Nukies : 0 (still)
- Prisoner transfer : 1

Conclusions : 

Slightly more antags, a greater percentage of non-traitors antagonists
Unfortunately, too many wizards and ninjas

Suggestions : 

- Raise the price of ninjas, traitors, and especially revs
- Slightly lower the price/requirements of nukies, vox raiders, plague mice, prisoner transfer, and malf
- Make it so the budget contribution to a catbeast is given in batches, instead of slowly drip-feeding traitors to the station
- A catbeast cannot spawn if there's more than 3 antagonists alive

**Comment by DamianX** [comment]
I feel like the roles are also being injected too early in the round. On multiple occasions rounds have ended at 12:45 with 4 or more midround rulesets being called (in addition to the roundstart one(s)!). I'm not sure whether ANY injection should happen that fast, but certainly not this many.

**Comment by ShiftyRail** [comment]
Very true, another angle to consider.

**Comment by DeityLink** [comment]
There's been several changes since then, make another issue if it's still a problem.
