### ISSUE TITLE
Weird inventory glitch with backpacks and any storage method.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29408]
(WEB REPORT BY: kirbythewizard101 REMOTE: 206.221.180.138:7777)
# Revision
4c09a724bde4dbd895b9468a1c8aa18c4f65c984

# Description
If you fill something up to it's full "line" i.e a row of items, it'll display the next roll instead of staying where it was, this is with toolboxes, toolbelts, backpacks, plastic bags, briefcases, etc.
If this is a feature where can I vote to revert it? I dont want my toolbelts looking ugly.
# Steps to Reproduce
Fill something up to a full row.
# What you Expected
For my shit not to look ugly
# What Actually Happened
It looked ugly.

**Comment by Dacendeth** [comment]
#29208

**Comment by help-maint** [comment]
If you come up with a better solution I'm listening

**Comment by ShiftyRail** [comment]
A little screen button to collapse/expand the second row?

**Comment by help-maint** [comment]
![dreamseeker_30_04_2021_19_41_41_06](https://user-images.githubusercontent.com/81891904/116760710-0d924d80-a9ec-11eb-9832-b5433631fffe.png)
Turns out you can just add one more /obj/abstract/screen/storage to work as an even more useful button, which you can just click while holding an item to store it. This button would only show while your bar is full.
However, UI code is absolutely nightmarish and I can't really do anything better than this. It kinda sucks and it blocks the red X. If someone could help by spriting a better button, I'd be grateful. Maybe something like a small box with an ellipsis.

**Comment by BomberBro** [comment]
@help-maint that looks absolutely fine imo, would make the whole issue of medkits and belts having double the UI clutter suddenly a lot better

**Comment by Dacendeth** [comment]
That looks fantastic to me.
