### ISSUE TITLE
Trade Outfitter wires can't be pulsed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29420]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
8537952f7c19eb85e7ff2dc37d3ca3326b6c3112

# Description
Trade Outfitter's wires can't be pulsed with a multitool, only cut
# Steps to Reproduce
unscrew panel, try to pulse
# What you Expected
it to work
# What Actually Happened
pulsing wires does nothing

**Comment by Kurfursten** [comment]
Intended behavior is for neither cutting or pulsing to work, as per the description

**Comment by Eneocho** [comment]
Feature. Though it should have the hacking part removed or revamped. An idea would be to have it be hackable for access or shock, but it cant spit items, pulsing/cutting the item throwing cable giving you a "Shoal reinforced tradervends are impervious to free dispensal, nice try, now go get those credits."

**Comment by Kurfursten** [comment]
I looked into this more. It's due to the implementation of CutWireIndex() and when it calls UpdateCut() (after changing the indexed wire to cut).

Basically although you can cut the wires, it won't do anything if you cut wires on an unhackable machine. In truth, you shouldn't even be able to unscrew the maintenance panel because none of the unhackable machines even have a panelopen sprite state.

**Comment by west3436** [comment]
Likely not even applicable anymore with the new trader vend
