### ISSUE TITLE
If you shoot rtg/phazon cells enough, they go to 100% minus energy production, then stop causing rad damage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29511]
(WEB REPORT BY: awadwduwu REMOTE: 206.221.180.138:7777)
# Revision
87fa87bb2ba89c671b0abbab0b6b252295e3bc95

# Description
The description for this is that they are 'leaking power'. The damage should scale up, not down. Because they are leaking more, not less. They shouldn't magically stop being made of radioactive material.
# Steps to Reproduce
Shoot a cell many times
# What you Expected
Nothing in particular
# What Actually Happened
The cells are inert.

**Comment by Eneocho** [comment]
The logic is that they are leaking power meaning that the inner circuitry from the generator side gets damaged and it doesn't charge the battery side, not that the containment proper for the radcell gets damaged. Radcells are both a pocket generator AND a battery (unlike IRL RTGs which don't store power). There was a whole thing about radcells being radioactive making no sense since they'd be self containing by design.
