### ISSUE TITLE
Antag bans do literally nothing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29595]
(WEB REPORT BY: cyrix01 REMOTE: 206.221.180.138:7777)
Currently antag banned player rolls antag twice in one round. 

https://media.discordapp.net/attachments/245856976217702400/846596292599611442/durgen.png?width=1130&height=316

http://game.ss13.moe/logs/2021/05-May/24-Monday.log

SAY: John Armstrong Camryn Lincoln/Durgen/(John Armstrong Camryn Lincoln) <span title='nuclear operative leader'>(A)</span> (@181,218,1) Deadsay: spooks, "some codebase lol"

**Comment by ShiftyRail** [comment]
They do something. The player started the game as challenger, not traitor, and then as operative, but he's technically *not* banned from it, as the ban string says "Nuke Operative", but the game looks for "Operative" as a keyword.

The problem here is the ban tools, not the ban system itself.

**Comment by DeityLink** [comment]
After taking the time to carefully read the code, I found at least two bugs that each might explain why durgen spawned as Challenger, and could become a Nuke Op.

Mid-Round rulesets that send applications improperly check the role typepath instead of the role id, so Durgen could receive the Nuke Op application prompt.

Secondly the Challenger ruleset has `role_category_override = TRAITOR` which means that a traitor ban SHOULD prevent one from rolling traitor. I'm still trying to figure out how that one could happen.
