### ISSUE TITLE
Spritermins: Go-Kart does not stop animating when key pulled.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29737]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
The go-karts keep animating the little exhaust jiggle after you remove the key and (presumably) kill the ignition.

Source: dude trust me

**Comment by DeityLink** [comment]
Am I the only one still driving vehicles by still holding the key in my hand instead of plugging it in so people can't just click the vehicle to get it out?

Anyway, the kart shouldn't stop jiggling after you remove the key since you're still holding it and thus can still drive the kart around. It only stops jiggling when its occupant leaves it, regardless of whether they're holding the key or not.

I don't think it's worth adding a process() to fix it by checking every second if the driver is holding the key.
