### ISSUE TITLE
Remove gourmonger from CE lockers and perhaps cargo

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#29840]
I've never seen the gourmonger contained successfully, other than using teleporters, and the teleporter method is still prone to destroying the server with lag, as we learned last round.

In its current state the Gourmonger should be understood to be an antag gimmick. In light of this, it should be harder to obtain, perhaps only orderable from hacked cargo computers, or from a syndicate uplink.

**Comment by Kurfursten** [comment]
I don't think syndie uplink is a good idea because then people would just valid anyone trying to build it and it does take a decent amount of autism to build. I think putting in hacked cargo crates is a fine idea except that then you could just order 10 and gourmongloose straight off. You could put it in the trader Cloud IX crates, but I actually am leaning toward it being in the Biogenerator more than anything.

That would encourage the engineering staff to ALREADY be talking to service before starting up the engine.

**Comment by GreatBigFailure** [comment]
Gourmonger is also never attempted properly. While I love the teleporter array method for pure meme value it still plays into the idea of "feed it as much as possible and never stop". The gourmonger is designed around not doing this. Gourmonger is very, very similar to the singulo in that you're providing a fuel source over time and if the fuel to time ratio is too high it looses. The difference being that gourmonger is much more flexible in this concept and doesn't have a "Maintain, grow slowly, grow quickly, loose" UI to choose from.
What I'm saying is that any time gourmongers are attempted it's the equivalent of setting up 2 hacked PAs set to 3 to fire at a singulo surrounded by bags of holding then getting surprised when it looses anyway. 
The "setup" of gourmonger is entirely based on the assumption it will loose rather than the prevention of loosing. This always shocks me because no other engine is treated this way. The shard involves setting up cooling to prevent a delam, not EMP-proofing the station. The singulo involves hitting the "don't singuloose" button when the "Singuloose?" color happens, not surrounded it by BOH. The AME involves putting in the right don't explode number not reinforcing all the walls and floors around it. I could go on.
I've set up a gourmonger engine a few times on live and not had it loose. The one time it did loose was because I got arrested and couldn't give it a snack. It's AME tier easy if you just want the lights to stay on.

Engineers saw "No upper limit on power" and "It's literally uncontainable" and took both as a challenge. Can't blame them.
http://ss13.moe/wiki/index.php/Gourmonger

@Kurfursten 
>I actually am leaning toward it being in the Biogenerator more than anything.
>That would encourage the engineering staff to ALREADY be talking to service before starting up the engine.

I get the mindset and I like the idea but it also goes against the idea of being a low starting effort, high upkeep engine. Though it would make more sense than cargo both mechanically and thematically.

**Comment by Kurfursten** [comment]
Needs a monitoring computer maybe.

**Comment by Killette2** [comment]
It's in the CE's locker? Cool thanks for the info!

**Comment by Durgen** [comment]
> I think putting in hacked cargo crates is a fine idea except that then you could just order 10 and gourmongloose straight off.

It would be an improvement, because currently they are in standard engineering cargo crates. At least they would be contraband if they required hacking.

**Comment by Kurfursten** [comment]
Oh right, I forgot about that.

**Comment by Eneocho** [comment]
The problem with that approach, @GreatBigFailure, is that you can press the one button and be done with the scrungulo maintenance. The Gours need constant food and you can't automatize food production in a way that doesn't encourage gourloosing (You either keep coal shoveling the high nutriment foods forever, round removing you, or make a self harvest plant, which will by design overfeed the things). 
Also, since they can Kool-Aid Man their way through any wall, you need to contain the inevitable LOOSE situation since there isn't a blatantly obvious sign that you are near a gourloose unlike the other engines (Shard warns you with the console, scrungulo grows large and the grav field gets wacky, rust EMPs, pacmans overheat, AME control consoles change sprite when they're close to exploding) and even then, most people just don't wanna micromanage simplemobs so they just make the containment design and remove the loose from the equation. 
I know you have that design on purpose but the fact is that nobody wants to be the guy that loosed and cucked the station with the walking Kool Aid shard if they fuck the feeding rhythm while aiming for high power.

**Comment by DamianX** [comment]
Why is a low starting effort, high-maintenance engine desirable?

**Comment by Durgen** [comment]
seems like gours are sorted out
