### ISSUE TITLE
Loyalty implants shouldn't block cult conversion

### ISSUE THREAD

**Issue by GreatBigFailure** [d3athrow/vgstation13#29881]
I understand the reasoning but in practice it's just not fun. This screenshot sums up my experiences with the mechanic and why I want it gone. 

![novideogametimeoutchair](https://user-images.githubusercontent.com/64218965/123029240-cfdbf080-d3ae-11eb-9f42-444ce72f24ef.png)

Boxing was an issue, I don't think we need another form of mandatory boxing with a "Literally forced to round remove him" flavor.
[featurerequest]

**Comment by drawsstuff** [comment]
I hate to agree in some aspects. They should still slow conversion down to a complete crawl, but I've always thought job was more important in terms of "resisting willpower" than an implant. On the other hand, dying is a part of playing security and you should more or less get used to it. It's still sad to see cultists being more or less forced to kill people who don't convert because of a lack of fun things to do with potential captures / risk of escape and outing. That should be focused on more I'd say, kidnapping is a cult classic, but currently there's a sad lack of fun rituals they can preform on said victims.

**Comment by Dacendeth** [comment]
> not fun

2. You're playing a multiplayer game. Sometimes you're having fun with everybody. Sometimes other people will be having fun at your expense. Sometimes you'll be having fun at their expense. Not every round will be flowers and sunshine. Antagonists are there to ensure that. However, if you think you're being griefed, make sure to adminhelp it.

**Comment by GreatBigFailure** [comment]
@Dacendeth I don't think that's relevant here. The person already had me dead to rights, they could have killed me to begin with and the fact that they used an O2 tank to do it showed they weren't prepared for it. They were hoping for a conversion. No one got anything out of the scenario. I can't really think of a scenario where anyone would get much out of it.

**Comment by Eneocho** [comment]
The problem with the implants is that both sides have their logic and going to one side has the other feel fucked. When implants DIDN'T block conversions there was no point to implanting crew, so people didn't do it, there was no point, since the implant would just pop out. Now that implants block conversions again, the incentive to mass implant is so great that cult just becomes either a whimper or a silent depopulator, since most don't wanna go through/don't know the surgery steps.
I know Deity has some ideas for cult to be a glorious fight between NT and cult and whatnot, but he forgets that players will more often than not optimize the fun out of their game, causing people to fall into predefined metas that while useful, aren't that fun to play with.
The problem is with the implants themselves. It's the fact that they're a binary effect, you're either culted or implanted. A solution would be to allow cultification when implanted but have a chance to de-cultify when implanted (call it willpower against the eldritch magic). This would encourage surgery to remove the implants, but implanting itself wouldn't fall into "shoot if they don't have wacky green square".

Also, this needs the discussion tag.

**Comment by DeityLink** [comment]
> 
> 
> @Dacendeth I don't think that's relevant here. The person already had me dead to rights, they could have killed me to begin with and the fact that they used an O2 tank to do it showed they weren't prepared for it. They were hoping for a conversion. No one got anything out of the scenario. I can't really think of a scenario where anyone would get much out of it.

Honestly this is mostly on them for:

* not using a seer talisman to check if you had an implant
* not having a soul gem in your pocket to soulstone you
* or not just remove your headset during the conversion to try and negotiate with you and attempt another conversion after ghetto removing your implant

```
place on altar (as efficient as operating table)
aim head
shard/blood dagger -> talisman -> crowbar -> talisman -> lit cigarette
```

Clearly the issue is more that they were a newbie and probably not used to conversion, and panicked. That happens. What I need to do is improve the newbie cultist experience and that IS the next planned cult update (I just wanted to code other things than cult these past few weeks, but since more issues are cropping up on that topic I think I'll get back on it sooner, Mecha 2.0 can wait)

**Comment by DeityLink** [comment]
> I know Deity has some ideas for cult to be a glorious fight between NT and cult and whatnot,

I haven't had that perspective since Cult 3.0 honestly. Now I'm more inclined to have it be an asymetric struggle where cultists can get out of trouble a bit more easily. Like you said the issue is that people don't know the surgery steps, or don't know what to do in general when the unexpected occurs. I cannot cover all the possibilities with code alone (well I could given enough time but you know)

> A solution would be to allow cultification when implanted but have a chance to de-cultify when implanted (call it willpower against the eldritch magic).

I'm not sure I understand, you mean chance to de-cultify some random time after being converted?

>  This would encourage surgery to remove the implants, but implanting itself wouldn't fall into "shoot if they don't have wacky green square".

How can you say that when deconversion is already a thing though? Or are you actually saying that 2-step deconversion is too complicated and it should be just 1-step because players are braindead? In which case I disagree. I'm all for quality of life and making things clearer but deconversion already is pretty straightforward.

In fact I was a rev a few days ago and we eventually got wiped out by sec and the captain, they weren't trying to deconvert/implant us at all. They have no duty to either. If sec wants you dead as an antag, they're entirely entitled to kill you. Until people code "sec shooting antag deconverts them" there's no way to guarrantee that sec will try and deconvert antags.

**Comment by gurfan** [comment]
lel

**Comment by SonixApache** [comment]
round removal happens sometimes
sec is for putting in constructs
not an issue

**Comment by drawsstuff** [comment]
>When implants DIDN'T block conversions there was no point to implanting crew, so people didn't do it, there was no point, since the implant would just pop out. 

I'd like to point out just how wrong you are but it serves little to no point in this conversation.

**Comment by DeityLink** [comment]
Oh I can do it for you: Green Square on SecHUD = guarantee that spessman is not a cultist. When there's a cult on board and you need to make split second decisions while fighting enemies that look just like the common spessman, that alone made it highly desirable.

Oh and I'm not even talking about its use as a way to check if the spessman is a cultist.
