### ISSUE TITLE
Vaults can spawn at the edge of a Z-Level, preventing players from even entering it.

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#29953]
Seen on Packedstation, Z=4, Vault was Black Site Prism

Players would skip Z Level before even entering the vault.

![image](https://user-images.githubusercontent.com/7573912/124382748-4fc85b80-dcc9-11eb-9ad8-b622dd2de8b8.png)

![image](https://user-images.githubusercontent.com/7573912/124382813-8f8f4300-dcc9-11eb-9a04-9aed3c0b38b2.png)

**Comment by DeityLink** [comment]
how does that even work? I thought vaults were restrained to the actual /area/random_vault .

**Comment by SonixApache** [comment]
Bad area detection code could explain the mining surprise overlap issue that showed up recently.
I'm just throwing words out because I haven't looked at the code, but maybe It's just checking if any of its parts are in the correct area, rather than all of them / the center?
I vaguely remember map elements being loaded from the bottom left, so maybe that tip was in the correct area and the rest wasn't.

**Comment by Eneocho** [comment]
You CAN enter the edge-vaults if you build a tile path to it. As long as you're on top of a floortile, the z-level teleporting doesn't happen.
