### ISSUE TITLE
Clown idea

### ISSUE THREAD

**Issue by Beroya** [d3athrow/vgstation13#3009]
Make anybody wearing a clown mask speak in Comic Sans font.

**Comment by clusterfack** [comment]
Nobody cared about my text until I put on the mask

**Comment by CptWad** [comment]
Fuck that. Papyrus.

**Comment by Probe1** [comment]
nah i'm not for it.  having borgs have different font is a really nice touch that instantly lets people know they're silicons.  if the clown wants comic sans then tell him to bother the geneticist.  font isn't supposed to be a snowflake shit, it's being used to differentiate borgs and humans plus the genetic disability.  

giving the clown unique font cheapens it 4noraisen except a clown player wants to be a snowflake at all times.

**Comment by Beroya** [comment]
People hate comic sans and people hate the clown, it's not ''muh speshusl snowflakes'' it's making the game funnier.

**Comment by Arthurdentist** [comment]
Leave the poor clown alone. Doesn't need another reason for people to hate him.

**Comment by Probe1** [comment]
Alright I gave it some thought and I'll explain my opinion with three points.  All of them relate to devaluing chat.

1.  The borg/human font change is nice and separates carbons versus silicons, which is a very important divide.  Moreso than races and jobs.  Silicons abide by their laws and are very different jobs than normal ones.  That difference should be accentuated by changing their font.  On top of that, they're robots and whatnot.  It helps immerse the players and help them make that mental leap to suspend disbelief when they look different, sound different and act different.  Sound in this case is text, and font is the conveyer of it.  That gives font a very special purpose.

2.  Comic sans already exists as a genetic defect and by propagating it, would make people care about it even less.  Already people are willing to take an injection with comic sans if it means a few powers.  Adding the Clown to the list, but instead of on occasion it would be every round, does the opposite of annoying people.  It makes it common enough that people ignore it and there's no specialness to it at all.  

3.  If the Clown stands up we all stand up!  Vox get special font, yes?  Aliens talk different!  Give aliens special text!  Why not skeletons too?  Or plasmamen.  Or grays.  Instead of solely silicons having a unique font that separates them (the importance of which I discussed in point 1), every other fucker has their own font.  If the Clown got his own then there'd be no good argument against giving every other race their own too.  Why is that a bad thing?  Devaluation.  Instead of the uniform and easily readable text box we have now, it'd look more like an AOL chatroom.  Giving people fonts because they're different doesn't improve the differences.  It clutters things up and makes the server look shittier, not the clown.

I think it's a bad idea and I don't think I'll be swayed.  But I am one person.  This is a single opinion and you should take it as such.

**Comment by Beroya** [comment]
That's basically the ''slippery slope'' logical fallacy reworded. Considering Clown is more different from any other job than any other job is different from any other job, with the exception of mimes, I proposed this because it would make the Clown just that bit stupider. Comic sans being a genetic defect isn't a thing I really see pop up ever, in fact I saw it for the first time the other day and I've been playing since before it was a thing.

**Comment by Cisrox** [comment]
Doesn't exist anymore. Closeable.

**Comment by PJB3005** [comment]
Not closable, smartass.

**Comment by Intigracy** [comment]
:+1: except attach it to the clumsy disability.

**Comment by ihadtoregisterforthis** [comment]
What is this milestone?
Who decides what is a High Quality feature request?

**Comment by Arthurdentist** [comment]
Of low quality\* I think you mean.

This was and still is a garbage idea.

**Comment by Imagebard** [comment]
@gbasood Please go

**Comment by gbasood** [comment]
I have no idea why this was put in that milestone
