### ISSUE TITLE
"Robotics for the Robos" was bad and we should revert it

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#30143]
I don't have pictures on hand but every round I've played as scientist ever since #29907 I just see the window (or sometimes door) between Robotics and the rest of Science consistently broken apart, or at best dismantled.

Having sub-departmental rooms locked to the rest of the department is only acceptable if the whole department is populated, which isn't always guaranteed, and is really just an eyesore at lowpop (especially when there's no HoP either). It's acceptable for Paramedics only due to every machine present in their station being also available elsewhere in medbay (on most maps at least).

When people knock at Science, at least 30% of the time they need a robot arm or to be borged/some criminal to be borged. (40% of the time it's Miners with mats, the last 30% are misc items needed from the protolathe/circuit printer), and as scientist you need Robotics either to help doing R&D, or to just keep yourself busy AFTER doing R&D since other science jobs are far away from the desk and have been split to their own jobs for a reason.

At the very least, "Scientists" should have Robotics access back. I don't mind too much if Xenoarch/Xenobio don't get it back *yet* (because even if they need to break in at some point, by that time there's good chance someone with access came, while Scientists need robotics access much earlier).

Anyway, discuss.

**Comment by Apogee-dev** [comment]
Agreed, certainly as far as giving robotics access to the generic scientist job. I kind of suspected it would play out like this when i first put up those competing PRs (i had hoped it wouldn't, but your point about the paramedic not really having any unique equipment is a good one) and there's ultimately better ways to get people playing roboticist- by adding more content to the job. Roboticist needs his RnD access restored at the same time, though.

**Comment by DeityLink** [comment]
> Roboticist needs his RnD access restored at the same time, though.

For sure. Honestly everyone in science should have R&D access, it's like the core of Science. I mean except geneticists, why are those even science staff? Why are virologists not science staff despite doing the same kind of research?

**Comment by SonixApache** [comment]
> 
> 
> > Roboticist needs his RnD access restored at the same time, though.
> 
> For sure. Honestly everyone in science should have R&D access, it's like the core of Science. I mean except geneticists, why are those even science staff? Why are virologists not science staff despite doing the same kind of research?

ancient bay designs

**Comment by Armadingus** [comment]
I am a lowpop man and my stance is also pro PR reversion, I need to build Ripleys to fight endless waves of kudzu and biomass and it is very annoying to be a roboticist and not be able to research to get the scythe or a scientist and not be able to get in robotics without busting the place up.
Both of roboticist and scientist need research and robotics respectively to do their job. A roboticist needs research to get their modules and miscellaneous items such as nanopaste, meanwhile scientists need robotics to not only speedrun research, but also maximize research with phazon equipment.

I say let them do their job properly again and cry later when we see ablinos in Durands. Because one powergamer is also worth one jobbie unlocking your brain's MMI and that's a good deal to me.

**Comment by xeroxemnas** [comment]
I agree. I think robotics shouldn't have access restrictions either. Like in an emergency if someone needs to use robotics they shouldn't have to steal an ID just to use the fabricator

**Comment by ghost** [comment]
dynamic access based on roundstart jobs and population would be better imo
