### ISSUE TITLE
The roid station shuttle has a bone setter but no bone gel

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30150]
(WEB REPORT BY: wotisjanitor REMOTE: 206.221.180.138:7777)
# Revision
27c61b851146f75ef8e5437567891aa749b953be

# Description
The roid station shuttle has a bone setter but no bone gel
# Steps to Reproduce

# What you Expected
to be able to fix broken bones
# What Actually Happened
could not

**Comment by Eneocho** [comment]
Most of the shuttle medical bays are either lacking or non-existent. Box and Packed shuttle have no surgery anything, for example. In packed it can be forgiven because its a lowpop map, makes sense to have a smaller shuttle, but box is one of the main maps and the most played one, but it still has the barebones medical area. Roid having but not enough hurts in its own kinda way though. You can JUST barely do the fix, but you cant do final step.
