### ISSUE TITLE
Spawning in the deadly disease diskettes as a traitor crashes the server

### ISSUE THREAD

**Issue by xeroxemnas** [d3athrow/vgstation13#30181]
#### Description of issue
>buy deadly virus viro item 
>server gets infected and crashes isntead

DEITY YOU FOOL

**Comment by DeityLink** [comment]
![image](https://user-images.githubusercontent.com/7573912/129124888-f79cae98-9734-4cab-bce2-ed424142dc92.png)
unable to reproduce, need more info

**Comment by xeroxemnas** [comment]
I dunno chief it crashed every single time I tried opening the disk case. Something is fucked.

**Comment by DeityLink** [comment]
So wait is it crashing the server or just your client?

**Comment by DeityLink** [comment]
if it's just your client, I need you to go at Cargo lobby, on the Merch computer, and buy a diskette box, see if opening those makes you crash as well.

**Comment by xeroxemnas** [comment]
dude it was the whole fucking server

**Comment by DeityLink** [comment]
so to be sure, the crash occurs when you click on the PDA Uplink button that lets you purchase it?

**Comment by DeityLink** [comment]
I'm hunting for possible factors. The crash occurred on August 11th at 20h35 server time. No runtimes. The regular server logs end abruptly without other anomaly.

I see you were in Virology as a challenger and named Ag Smag. I'm adding "Challenger" to the list of possible factors, since I did my local tests last night as a Traitor. I see you re-logged a few minutes before the crash, did you have some other bug or was that unrelated?

**Comment by DeityLink** [comment]
Well I tried again as challenger but no luck either. spawning the box on the main server (without going through the uplink) also didn't lead to a crash.

**Comment by boy2mantwicethefam** [comment]
feature
