### ISSUE TITLE
catbeast saying /list randomchatter

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30192]
(WEB REPORT BY: heroinehero007 REMOTE: 206.221.180.138:7777)
# Revision
12b98a48057a90b8566af0d32bdf36604118cf9d

# Description
Catbeast random lines include one that literally starts with '/list'  It was something like, "/list MEOW CANT TAKE IT ANYMROE"
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DeityLink** [comment]
The exact sentence was `(Follow) Lurks-In-Shadows stammers, "/list, PLEASE meow CAN'T DO THIS ANYMORE"`

and "GOD, PLEASE" specifically is one of the random sentence replacements tajaran can use.

however "god" also is supposed to be replaced by gosh or golly when spoken by tajaran. The wrong proc was used so instead of picking one, it returned the list type.
