### ISSUE TITLE
Blob is mouse transparent so you can't melee it unless you alt+click

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#30212]
#### Description of issue
title
#### Difference between expected and actual behavior
expected to be able to melee normally
#### Steps to reproduce
go to the fertility clinic and get an invitro
#### Length of time in which bug has been known to occur
Probably since #30138 
[bugfix]

**Comment by Megadeadly** [comment]
Further information on this: This seems to be due to mouse_opacity being 0 instead of 1 from what I was told. This is also happening with: Webs, cocoons, and hand tele portals (stated in previous post.) From what I was told, may be due to something being changed with the children of object/effect, but I personally have no idea. A work around currently is to alt click the tile in question and interact via the side menu.

**Comment by Eneocho** [comment]
Related to #30214 and #30185
