### ISSUE TITLE
Wizard Teleport

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30224]
(WEB REPORT BY: personable REMOTE: 206.221.180.138:7777)
# Revision
7a87dfac976d06d7334c92737b8417d0f9f3a1df

# Description
Wizard teleport scroll is broken. This also applies to the spell Teleport.
# Steps to Reproduce
Using the item or spell.
# What you Expected
A list of places I could teleport to.
# What Actually Happened
Nothing happening save for smoke being spawned. No list appeared at all.

**Comment by DeityLink** [comment]
Ghost and Adminbus teleport are also broken, their list of location only has a fraction of the areas it should have.

**Comment by DeityLink** [comment]
I called process_adminbus_teleport_locs() again during a round and the adminbus' teleport panel went from having only 4 entries (Space, Mine, Holodeck and something else) to having all the areas as it should, ~~except sorted in reverse (Z at the top, A at the bottom).~~ ok so that's because of cmp_text_dsc apparently

Could it be that the procs are called too early during server initialization?
