### ISSUE TITLE
If you use the Time Agent's Timeline Eraser on anything, the tile you were stepping on while using it becomes solid, blocking movement but not items moving through nor item placement.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#30247]
#### Description of issue
What it says on the tin.
#### Difference between expected and actual behavior
Expected to NOT be cucked outta moving by timeline erasing.
Tile got all fucked up.
#### Steps to reproduce
Become time agent.
Use timeline eraser on anything.
Observe how the tile you were standing on got fucked.
[bugfix]

**Comment by Allspice** [comment]
Looks like an issue with the timestop proc. Bisecting indicates that it was introduced in https://github.com/vgstation-coders/vgstation13/pull/30069

I'll look into sorting it out.

**Comment by Allspice** [comment]
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/spells/aoe_turf/fall.dm#L73

It's probably acting up because it's expecting a mob/user argument but not getting one, so it's creating a blank mob like https://github.com/vgstation-coders/vgstation13/issues/30237 mentions. I didn't notice this happening with the timestop wizard spell, only the chronogrenades. Whether the timesuit also causes it, should be a matter of how it's implemented.
