### ISSUE TITLE
Runescape feedback

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30349]
(WEB REPORT BY: punishedpajeet REMOTE: 206.221.180.138:7777)
# Revision
25705ebd704a6888c329d12a7eb8adfd821e2c2e

# Description
Runescape event was pretty cool. Would like to be able to kick the deconstructer in science and medbay kept getting PK skulls over their head. Would like that not to happen when treating people
# Steps to Reproduce
Play medbay
# What you Expected
No skulls
# What Actually Happened
Got skulls because I think certain actions were interpreted as harm

**Comment by DeityLink** [comment]
Noting down for myself some design issues because despite two OOC messages and one Command Announcement this ended up being the only ticket being made:

**Problem:** No PvP means that players are free to rush spare, grief, etc.
**Solution?:** Have a small player faction (maybe just Security) still able to disarm and taze people outside of maint and tasked with maintaing order outside of maint? Basically like those City Guards in MMOs

**Problem:** Mechas appear to be exempt from the PvP restrictions.
**Solution?:** Maybe forbid mechas altogether? They wouldn't add much to maint battles anyway.

**Problem:** Someone opened an N2O canister in maint which eventually flooded the entire station
**Solution?:** Should maybe remove N2O Canisters and Miners. Plasma ones are necessary for engineering and we can ban those who abuse it. N2O is a bit less obvious.

**Would be nice to have:**
* More clothing and weapons themed after Runescape
* More Maint loot to encourage people to enter maintenance?
* Allowing players to enter guilds/groups, provide large groups with bonuses, access to spells/building materials?
* Some Raid boss? Maybe admin or ghost controlled?
*

**Comment by DriftingSkies** [comment]
Add the Grand Exchange or I riot, also good gimmick. Had fun.
Also, make a FEW persistent safe areas. It wasn't really fun at the end with people camping the shuttle and gunning down people that just want to leave.

**Comment by Eneocho** [comment]
buying gf

**Comment by KingofHONK** [comment]
I'm just going to spitball some ideas here

If we're going to have ranged weapons it consider limiting crossbows and shit, as people with guns are gunna BTFO someone who's trying to melee, also just remove stuns in general so things like rune armor and scimitars and shields become valueable. 

Spawn in some shitty basic thematic armors or weapons for latejoiners so that they feel like they can join the action right away. Also something to consider is maybe declare the first 15 minutes of the round a prep phase (not sure if you did this already) so the departments can all prepare for the gunkage, especially medbay. 

Speaking of medbay, i think we were pretty lucky to see some docs jobbying up pretty hard, including the HOP who was giving basic access. I don't know if that was pre arranged or not but the only reason the bus functioned at all is because of them, so make sure when people ready up that a lot of em roll up as docs. Uhhh capes if you want to do guild based stuff the guilds can just wear capes that match.

Another thing you could do with pvp zones as an idea is make the start of the round similar to dorf, declare a certain department to be lumbridge and everything outside of that department to be the wildy, and allow people to set up shop there. Atmospherics comes to mind since there's lots of space.

**Comment by west3436** [comment]
Useful information for the forum, not github

**Comment by Eneocho** [comment]
It kinda is github info since it can be seen as a feature request for the rarely used runescape mode
