### ISSUE TITLE
Magboots do not protect you from atmospherics when enabled

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#30353]
#### Description of issue
While having magboots enabled and walking out of external airlocks, I got messages such as "You are blown away by airflow!" and when in space I got messages saying "You slipped!". Both times my character was moved by the game and not myself.

#### Difference between expected and actual behavior
I expect magboots to make my steps firm and not have me slip or be blown away by air when turned on.

#### Steps to reproduce
This was happened with a vox softsuit, keep that in mind.
>put on space suit
>put on magboots
>turn on magboots
>walk out an external airlock repeatably until results or lack thereof

#### Specific information for locating

I would suggest looking into this #30018

#### Length of time in which bug has been known to occur

This was a very recent experience, I'd say this change happened today or yesterday.

#### Server revision

Game: 0f2dde04d40ec40038ea3c7bca92e15aff6a7961 
Patches: 4b2ca98f0136267a4a7bec26f9b4c36f24f68941

**Comment by DriftingSkies** [comment]
It's been known that walking just BREAKS magboots while you have them on

**Comment by Armadingus** [comment]
Also true, but I was not walking in space or in the external airlock. Run intent was on.

**Comment by DriftingSkies** [comment]
> Also true, but I was not walking in space or in the external airlock. Run intent was on.

This also just happens sometimes, Atmos code is..... something.

**Comment by SonixApache** [comment]
~~A quick investigation shows that even with magboots, you have a 1-2% chance to slip per item held in your hands.~~ i can't read

However since the related PR touched `CheckSlip()` which is used for both of your reported events, that's definitely the actual issue. I guess this means that by design magboots users now have to move at non-magboot walking speeds to not slip, which is bad.


All that said, I can't reproduce this issue, so next time it happens please do take a picture of your loadout and maybe jot down some extra information on the situation (air pressure / differential, location, etc)

**Comment by DriftingSkies** [comment]
This happened to me today as well, no idea why it did this. I very much had the magboots toggled and kept getting sucked by airflow but not being knocked over by it.

**Comment by Exxion** [comment]
I can reproduce the airflow moving someone with enabled magboots, but I can't reproduce the space slipping. At least not unless something caused them to be really slow. Regardless, the PR I'm about to open should fix both.
