### ISSUE TITLE
Blindfolds don't let you see the unseen

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30519]
(WEB REPORT BY: rubylips REMOTE: 206.221.180.138:7777)
# Description
Blindfolds have the line 
see_invisible = SEE_INVISIBLE_LIVING
which does literally nothing. I can only assume the person who made blindfolds intended them to let you see things like cloaked wizards, people who drank invisibility potions, etc. They don't.

# Steps to Reproduce
Put on a blindfold
Exist near an invisible thing

# What you Expected
Only the blind can truly see

# What Actually Happened
The blind truly can't see

**Comment by gurfan** [comment]
???????????

**Comment by GreatBigFailure** [comment]
I think whoever made blindfolds didn't look very hard at what that flag actually did and thought it would make you see invisible living creatures, so anything besides ghosts. In actuality all living creatures start with that flag. I didn't look any further into it. 
Basically I think they're intended to let you see invisibility, but be blind otherwise. They don't work though.

**Comment by Exxion** [comment]
No, `SEE_INVISIBLE_LIVING` is the default `see_invisible` value for living mobs. I'm not sure why blindfolds explicitly set yours to that though.
