### ISSUE TITLE
Sending plasma to centcomm does not give you cash

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3051]
It used to and was an amazing way to generate LODSEMONE when miners brought you plasma like they were meant to.

**Comment by d3athrow** [comment]
Probably dont want miners double dipping using the smelter and then sending in smelted plasmas.

**Comment by ComicIronic** [comment]
This functionality exists in plasma already.
It's abundant and highly rewarded on the smelter screen, so miners can make money for the QM and cargo account by mining plasma and letting the QM cash it in.
Notabug.

**Comment by nuklearcellphoneg** [comment]
It was changed in lieu of the mining update, but to be honest the Quartermaster and Cargo Techs do tend to have to go to the HoP for money more so than the miners. I've seen quite a few miners go, "No my money lol"

It would make more sense for Centcomm to take part of the money and send it straight to the Cargo account rather than making Miners super super rich all day every day.
