### ISSUE TITLE
You can crack a safe while deaf/wearing earmuffs

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#30550]
#### Description of issue
Using a stethoscope on a safe apparently does not require you to be able to hear the tumblers click and grind.

#### Difference between expected and actual behavior
I expect it to be a requirement to have ears in order to hear.

#### Length of time in which bug has been known to occur

Don't worry, Deity, this was a thing way before you reworked it.

#### Server revision

69bdef3a6a8981793aac786e7aabc4e2d06a242c

**Comment by DeityLink** [comment]
Yeah I'm sure it was since safe code never took deafness into account but that's a very valid oversight.

**Comment by Eneocho** [comment]
I tested this theory. You can hear the clicks without a stethoscope, but you don't hear the PLINK when you set the thing correctly. You still need the stethoscope to confirm which position is the correct one.
If nothing else, the real problem is people without the scope (namely sec) being able to hear you cracking the safe.
