### ISSUE TITLE
telescience telepad can appear in trader vendor circuit box

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30776]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
8f6df8e23ff5e9308f21e186c69633ef5ecdf1d5

# Description
claims to be one of a kind thing
# Steps to Reproduce
buy circuit box for 25$
# What you Expected
random circuit boards
# What Actually Happened
random circuit board gave me one of a kind, unable to replicate circuit board.

**Comment by Kurfursten** [comment]
~~Mostly a problem because AFAIK the game expects there to be exactly one of these due to oldcode. Someone could easily modernize it by just linking to a computer with multitools but then we might end up with telepads everywhere.~~ Someone did modernize it like this. Feature I guess?

@Rubylips can decide I suppose

**Comment by GreatBigFailure** [comment]
Intentional, in fact it's one of the few good things in the pack. The same is possible with the spessmart spawners.
