### ISSUE TITLE
[Bug/Sprite issue] Magboots display as bare feet when wearing a rad suit

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3077]
Check them pasty white toes.

![ss 2015-02-17 at 10 26 06](https://cloud.githubusercontent.com/assets/8550416/6242183/15b6aa8a-b6f8-11e4-9b45-afecda894cac.png)

**Comment by SkowronX** [comment]
The suit inherits a hide clothing flag it shouldn't have.

**Comment by ComicIronic** [comment]
Look man it's hardly my fault these items were using hideflags wrong with the bad system.
I'd appreciate testing with more clothing combinations, and push a fix for this.

**Comment by Probe1** [comment]
I'll do some testing.

**Comment by ComicIronic** [comment]
Alright, I've got to clarify what is actually going on here:
The radsuit DOES correctly show shoes when you equip it.
What's happening is that you quickswapped from equipment (likely a space suit) that normally hid the magboots, to equipment that didn't, and the overlays didn't update because the code isn't being called correctly for some reason. I'll look into it.

**Comment by Probe1** [comment]
An engineering hardsuit, you can see it off to the south.  Good luck.

**Comment by Probe1** [comment]
closed in 3086
