### ISSUE TITLE
Metal Solidification

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30800]
(WEB REPORT BY: higgsbonbon REMOTE: 206.221.180.138:7777)
# Revision
b575a71b92add50e00eb6a85ae1b02d0ac9ed2e4

# Description
Metal solidification reaction uses silicate (spray) instead of sodium silicate
# Steps to Reproduce
Add reagents (metal powder, frost oil, sodium silicate
# What you Expected
reaction
# What Actually Happened
no reaction, uses silicate spray instead

**Comment by Eneocho** [comment]
Sodium silicate is used for (((xenoarch))) if I'm not mistaken. Solidification uses regular old silicate, the same you use to reinforce windows with the silicate sprayer. You can get silicate from the tool storage silicate tanks.

**Comment by Exxion** [comment]
Sodium silicate is apparently used for plasteel solidification while regular silicate is used for all other metal solidification.
This is seemingly intentional, but not especially intuitive. Feel free to discuss changing it.

EDIT: Plasteel solidification is the only use of sodium silicate in the entire codebase, and other than that the recipe is similar to other solidification recipes. We could totally just get rid of sodium silicate and use silicate in that recipe as well. Not that anyone uses that recipe anyway. Alternatively we could switch all other metal solidification recipes to using sodium silicate. :shrug:
