### ISSUE TITLE
[Feature request] Medbay needs its own backup generator.

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3095]
Makes sense. Just a simple PACMAN with a bit of plasma maybe in one of the backrooms. Most medical buildings have their own backup generators. Why not a high tech space station super medbay?

**Comment by wwjnc** [comment]
Seconding, this is a great idea. Maybe they could have their own SMES (or a mini-SMES!) with its input connected to the external power, isolating Medbay from the main power grid, just like the AI.

**Comment by PJB3005** [comment]
I think bay has seperate substations with SMESses for every departement, this'd be cool to have indeed

**Comment by Probe1** [comment]
Alright I had it out in the thread but that's not constructive so I'll post my thoughts here.  I play engineer pretty frequently as Allen Baker and I think I have a good grasp on the subject.

1.  Add PACMANs
http://i.imgur.com/oNObxMf.gif

Adding a PACMAN would do nothing unless you also clipped the cables leaving medbay or else it'd evenly distribute over the entire powernet.  That introduces more problems than it fixes.  Now you need insulated gloves and wirecutters or an engineer to come by and do it for you.  Which isn't plausible since they should be trying to bring power online and not helping out a specific department.  

2.  Add SMES


There's an important reason why almost all the SMES draw power from engines then push them to the grid except for three notable exceptions.  The SMES in engineering, telecomms and the AI core.  In the thread someone said
>"This would literally only be a thing for Medbay, which makes sense because it's the one area of the station that uses the most power and that you want to keep running longest."
I disagree.  The AI Core and Telecomms SMES both protectsystems that will catastrophically fail if unpowered and are hardened against hacking attempts.  The final one in Engineering powers the most critical department when it comes to power.  If power fails in engineering then god help you.  Nobody can fix anything because the damn apcs are all powered off and there's no way to get them on without power that you don't have. All this important stuff is centrally located in Engineering, where players will (in a perfect world) understand SMES levels as well as the amount of power available being produced.  Medbay has none of these which makes it wholly unqualified for a SMES. 

Furthermore, having a SMES isn't going to save you from power loss in early game when it hasn't had any time to properly charge.  And late game it will have way too much of a charge and negate any power issues for a very extended period of time.  This is the kind of project an engineer should be asked to do, not the kind of thing a map requires at round start.  If you've played engineer you'll understand that maps are intentionally designed to be unoptimized and have gaps, flaws, and issues for players to fix or exploit.  

3.  Medbay is not incapable of rendering treatment if the lights go off.  The only aspect that absolutely requires power is the cloner.  Everything else can be reasonably duplicated through pills, surgery, and good old fashioned ointment.  You'll have a harder time and some people just won't be saved but not every round should be perfect.
