### ISSUE TITLE
Latex Gloves

### ISSUE THREAD

**Issue by Beroya** [d3athrow/vgstation13#3104]
Latex Gloves leave a fingerprint
This is a bug

**Comment by Lokiamis** [comment]
http://en.m.wikipedia.org/wiki/Glove_prints

**Comment by 9600bauds** [comment]
>http://en.m.wikipedia.org/wiki/Glove_prints
That article only says that gloves leave a unique type of print depending on the glove's seams or fabric, which would mean the detective would only know what kind of glove was used. The criminal's fingerprints do not go through the glove.

**Comment by Probe1** [comment]
it has a chance of leaving your prints and its intentional.

**Comment by 9600bauds** [comment]
That's ridiculous, your fingerprints can't magically go through the gloves. The wiki article only says that different gloves leave different types of prints due to material type and creases and such, but in no case does the glove's external surface somehow match your fingerprints. Look at the "Notable instances" section of the article.

**Comment by BestName** [comment]
Latex gloves have always had a chance of leaving a partial print or full print.
This is not a bug.

**Comment by Unfit** [comment]
What if latex gloves didn't leave any prints, but after wearing and using them for a while they'd have more and more chance of leaving prints?
I feel like the ability to leave fingerprints through gloves is necessary for now because you can simply strap on some gloves on the beginning of the round and then go around your business without ever needing to take them off or change them. If latex gloves wore off over time, you'd at least have a need to take the gloves off.
