### ISSUE TITLE
Cult 4 feedback

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31273]
(WEB REPORT BY: gallywix4 REMOTE: 206.221.180.138:7777)
The blood cost for drawing a word is too little (1u for a word and 3u for a full rune) and it allows someone to easily set up a cult base without the need of help from other cultists or other sources of blood

While the cult mentor system was implemented to allow anyone to take the role of cult leader the fact no one knows who the mentors are causes the cult to lack a leadership, honestly i would like if there was a way for a cultist to take an actual leader role above the mentors so you don't have infighting

Path runes are a pain to deal with since they allow cultists to teleport for free, adding a small blood cost of something like 10u would make it a little bit more annoying for the caster so we don't have cultists that teleport x times in a row without the need of getting more blood

**Comment by DeityLink** [comment]
> the fact no one knows who the mentors are causes the cult to lack a leadership

Which is a bug since they're supposed to have a bigger purple cult chat. Secondly mentors are not leaders, in the sense that they don't give orders to the cult like a captain would, they give objectives and it's up to the rest of the cult to decide how to follow them or not, and mostly they're here to train acolytes (who automatically get told who are their mentors already). Also cultists can check the list of all cultists and their roles at an altar. The "infighting" is part of the fun, convince the rest of the cult IC that your proposal is superior.

> The blood cost for drawing a word is too little (1u for a word and 3u for a full rune) and it allows someone to easily set up a cult base without the need of help from other cultists or other sources of blood

Cultists are meant to be able to operate individually, even more so now that their numbers are heavily restricted. Adding more restrictions will only handicap newbies while pros will easily circumvent them, and I think one of cult's greatest problems is how hard the antag already IS for newbies.

> Path runes are a pain to deal with since they allow cultists to teleport for free, adding a small blood cost of something like 10u would make it a little bit more annoying for the caster so we don't have cultists that teleport x times in a row without the need of getting more blood

Adding blood costs for those mean they can no longer be used by blood-less species or shades, this rune is too important to suddenly become unavailable (plasmamen players already complain to me all the time that most cult content is hard to access at all) Cultists in cult 4 are meant more than ever to be able to easily escape the crew, but they still have more restrictions than wizards as their path runes only target specific turfs, and can be destroyed.

**Comment by agentofzog2** [comment]
How do you path talisman again? I saw one dude use it at will but when I tried it it seemed to require a prepped path rune.

**Comment by DeityLink** [comment]
It does. You cannot escape by talisman unless there's already a Path Exit rune set up. To connect a blank talisman to it there are two ways:
1. Just slap an attuned Path Exit rune with your blank talisman. However this requires the exit rune to be revealed and easily accessible to you.
2. Slap your talisman on a Path Exit rune that ISN'T attuned to a word (that still looks like a rune), then use it in your hand and you'll be able to specify a word among the exits available (useful to also check which path exits exists in the world). Using the talisman a second time will teleport you.


ps: Using a talisman on a Path **Entrance** lets you instead remotely activate it.

**Comment by DeityLink** [comment]
Closing as feedback as been dully acknowledged, feel free to re-open or create another ticket to discuss further.
