### ISSUE TITLE
Asteroid Station Wormholes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31312]
(WEB REPORT BY: djkramer REMOTE: 206.221.180.138:7777)
# Revision
c077fc9ee7966568780ee0d720de11689b5f719e

# Description
Wormholes event on roid spawn all the wormholes at once versus a handful them at intervals

# Steps to Reproduce
Press funny wormhole button
A million wormholes spawn on every tile possible
Sparks grind the server to a halt
# What you Expected
Press Funny wormhole button
Waves of wormholes happen like every other map
I laugh, people cry
# What Actually Happened
I press funny wormhole button
A million wormholes happen at once
They cover almost every tile on the station
All wormholes close at once
Sparks hell
People cry
I cry

**Comment by Eneocho** [comment]
![Military Hive Charlie 2021-11-17 042222](https://user-images.githubusercontent.com/67024428/142279652-2c7199a3-2c53-4f84-8a8a-81ce1f322c00.png)
pic related

**Comment by nervere** [comment]
This happens when the number of valid tiles for wormholes exceeds 3000, due to this:
https://github.com/vgstation-coders/vgstation13/blob/ab73db104137216e99d51bc9e5398ed7957c5f33/code/game/gamemodes/events/wormholes.dm#L13-L15
The `sleep_duration` is then rounded down to 0, so all portals spawn at once.
The simple fix is for the sleep duration to not be rounded. I tested it before, it works as a decimal.

Every time I ask if people actually want this fixed, I get told it's too soulful and that people enjoy it.
I will be closing this on those grounds. If you disagree with this, by all means feel free to make a PR.
