### ISSUE TITLE
Potential Gourmonger Changes Feedback

### ISSUE THREAD

**Issue by GreatBigFailure** [d3athrow/vgstation13#31320]
I've been mulling around the idea of changing gourmongers from producing radiation based power to more directly producing electrical power. I haven't decided on the tiny details but something like just adding X watts to either wires under them or the area they're in's APC if there are no wires. 
Despite having made the engine I'm not very knowledgeable about how power works, my understanding of it is very shallow. So I'd like feedback from the big boy engineers and figured an issue was best for discussion.

**Why?**
Rads were originally used for simplicity (easier to code at the time and a more obvious threat vs benefit system) and thematic reasons. 
However, rads get in the way of:
- Setup time, needing to either steal the SME area or take ages setting up collectors/wires
- Freeform/non-engineering gours. Though these are possible you need to double-wall them to prevent radiating the crew. Having a gourmonger body cleanup janitor in the halls is also impossible because of the rads. Same with a rancher/chef gimmick gour.

Basically making the immediate area around gours not a death zone would be better for freedom in how you use them. I think freedom in builds is what most engines are missing so I want to lean into it.

**What would change**
Only half decided how this would even work. I'd definitely want some dangers still involved, something should get you zapped but it shouldn't be high risk enough that a hallway gourmonger would be an immediate security threat. Maybe they just taze in an area when they split. 
Their power output would get a surface level buff too since without cooled plasma to undecuple their output they'll need it. 
Probably something else I dunno.

I still have other projects to complete before I even properly brainstorm this but I'd like feedback regardless. I'll never be free of fixing these things.

**Comment by Eneocho** [comment]
I suggested this on #30688 but reposting it here because I like the Idea:

Connector plates on a room, gourmongers have hyper efficient bioelectric organs that produce high voltage electric discharges which get absorbed via the connector plates. 
This would make it a high level engine that is not dependent on blasmacooling.

A side idea to this could be the voltage depending on the quality of the nutrition chem and the amount currently inside the gour. So 10u of Corn Oil produces more power than 10u Nutriment but 20u nutriment produces 2.4 times the power that 10u does. If you want peak power you keep them on the verge of splitting, say, 90 outta 100 nutriment. You can keep them there for stable-ish max power or feed them some extra nutriment for them to go above 100, so they split.

The danger would be in that the discharges would work like the syndie tesla cannon, you get shitfucked if not insulated.

**Comment by Eneocho** [comment]
The danger would be in that the discharges would work the same as the syndie tesla cannon. You'd get shitfucked if not shielded properly.

**Comment by west3436** [comment]
Feedback received

**Comment by Eneocho** [comment]
@GreatBigFailure
