### ISSUE TITLE
cant take a photo of wasps

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31464]
(WEB REPORT BY: sacredatom REMOTE: 206.221.180.138:7777)
# Revision
145612a93ed040e9b81cc0d685ae48f36f0fd163

# Description
cant take photo of angry wasps
# Steps to Reproduce
take photo of angry wasps
# What you Expected
a photo of the wasps
# What Actually Happened
vampire wasps

**Comment by nervere** [comment]
Seems like bees don't show up either, which makes sense since wasps are just a child type of bees.
The descriptions when taking pictures:
> You can see the angry hornet on the photo - the angry hornet looks hurt...You can also see the angry hornet on the photo.

> You can see the swarm of angry bees on the photo - the swarm of angry bees looks hurt...You can also see the swarm of angry bees on the photo.

Probably something to do with how bees are always moving around on the tile they're on.

**Comment by DeityLink** [comment]
> Probably something to do with how bees are always moving around on the tile they're on.

Yes and No. Them sliding around and being offset every second is not a problem. However them being an animated sprite (featuring the individual bees moving around) means that my get_icon_dir_count can't quite tell how many directions their icons are and returns 0 (since it tries to guess by reading its base64 hash). And my other proc getFlatIconDeluxe only force the south-facing sprite for icons that have 1 direction. I'll fix it by also having it force the south sprite for icons that it cannot be sure of. This _might_ cause every other animated sprites to appear facing south but unfortunately that'll have to do until we have a more reliable way to get how many directions a given icon state has. Better have icons facing south on photos than not appearing at all.
