### ISSUE TITLE
McFucking remove blob cores from roulette revolvers

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#31472]
Way too easy to accidentally spawn a round-ending antag with these and to do so in places they typically can't spawn in a way that breaks the game due to the lockdown, like other z levels.

**Comment by Kurfursten** [comment]
Just make it so the cores it spawns can't be controlled by a ghost, like how the vault one works

**Comment by Kromkar** [comment]
feature

**Comment by SonixApache** [comment]
literally feature, roulette revolver is a gamble whenever someone fires it

**Comment by Eneocho** [comment]
Roulete revolvers are love, but the admin fears love.

**Comment by Shadowmech88** [comment]
Having looked into it, this does indeed seem to be a bug.
I believe the Roulette Revolver is coded to only block the explicit types in its blacklist, not subtypes. The meteor projectile is in its blacklist, and at the time the Roulette Revolver was made, the meteor projectile _had_ no subtypes.
As additional types of meteors, including blob meteors, were added, the Roulette Revolver's blacklist was not updated to compensate. In fact, it appears to have only ever been updated once, with `/obj/item/projectile/beam/procjectile`.

I think the solution to this would be to make a separate blacklist intended for restricting not only given types, but their subtypes as well, and putting the meteor projectile into that one in order to restrict _all_ meteors.

**Comment by west3436** [comment]
Closed via #35752.
