### ISSUE TITLE
Simple mobs attack in bursts of 2

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31533]
(WEB REPORT BY: sacredatom REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description
Stand still next to a hostile simple mob, the mob will usually attack twice, stop for 5 seconds, then attack again usually after moving another tile.

# Steps to Reproduce
Easiest way is spawn a carbon in dome, and a simple melee mob, and watch it happen real time.

# What you Expected
Mobs to constantly attack

# What Actually Happened
Mobs attack in bursts of two, which can be used to usually kill a mob in most cases head on much easier. Even more simple if a plantman.

**Comment by Optimism333** [comment]
This really should get looked at, as it severely nerfs hostile mobs that use melee attacks. I tested it myself and there's only really two ways it wouldn't be noticed: if you're running away from the mob they will still attack pretty consistently, if the mob is a ranged mob since those move around a lot they will also usually attack pretty consistently.

**Comment by gurfan** [comment]
~~I can't reproduce this issue on local server.~~
