### ISSUE TITLE
Plant clippers missing from Box / all maps

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3166]
/obj/item/weapon/wirecutters/clippers

Despite being in code, all botanists have to grab regular wirecutters to cut their plant for samples.

**Comment by TermedClepe** [comment]
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/hydroponics/hydro_tools.dm

**Comment by Killette2** [comment]
As someone who does botany almost every day (Rowan) I must ask what's wrong with wirecutters other than the fact that we are lacking this feature? Wirecutters may harm the plant, but more often than not you use them because you want to harvest the seed of the plant right then, whether you think the plant will survive or not. It is also good for killing off plants where you want the seed but you don't want it to live much longer, and for plants you do want to live if you have bees they will repair any damage the wire cutters commit. Even if we get the clippers, I think I will stay with wirecutters just because they are more useful in general, and don't really do anything problematic to the job.

**Comment by TermedClepe** [comment]
You misunderstand Killette2, I believe they are identical to wirecutters. This is just for immersion.

**Comment by Killette2** [comment]
Well I roleplay Rowan as an odd guy, but if it's the tool for the job I'm not sure what I'll use... Now these days I pick up an electrical toolbox which contains wirecutters anyways which I use to build more hydro trays with the wires and the screwdrivers and able to rechange APC's with a multitool without hogging a ton of tools. I just figured they would be better, like how there is improper ghetto surgical tools and proper surgery tools.

**Comment by TermedClepe** [comment]
I'm pretty sure you'll be able to use wirecutters just as you always had regardless of this change.

**Comment by Killette2** [comment]
I'm sure I would too, I was just wondering if the right tool would be better somehow or if it's just for ARRR PEE

**Comment by TermedClepe** [comment]
Would be cool if it improved the odds of getting a sample, without nerfing wirecutters.

**Comment by Duny-** [comment]
I added some to defficiency because why not https://github.com/d3athrow/vgstation13/pull/3180

**Comment by Killette2** [comment]
We still don't like your map Duny, but at least you tried and made one.

**Comment by Duny-** [comment]
I didn't make the map you mouthbreathing retard. Cordially.

**Comment by Killette2** [comment]
But I can still say you did.

**Comment by Duny-** [comment]
And the mouthbreathing retards in the thread will gladly believe you, doesn't mean you should take the shitposting to github.

**Comment by Intigracy** [comment]
Fixed by #3166
