### ISSUE TITLE
Feedback thread for grue-related things.

### ISSUE THREAD

**Issue by Hinaichigo** [d3athrow/vgstation13#31969]
The grue light-damage changes in #31968 were done based on feedback from [this thread](http://ss13.moe/forum/viewtopic.php?f=4&t=6167).
I'd like to ask for feedback and ideas on a few issues that may come up going forward, and also for feedback and ideas in general:

- Should grues be able to smash computer monitors, AI camera lights, wall-hanging mining lanterns and other light-emitting machines?
- Should they be able to bite exposed power cables?
- What should they be able to do about things like flashlights (which currently have infinite power as I understand) that can be dropped on the floor. Some things I was thinking of was adding chargeable internal batteries to them, or making grues able to break them (or just the bulbs) or bash them away.
- What should grues be able to to do, if anything, about bolted doors?
- Umbras (original humanoid grues) have the ability to channel a dark field or scream to shatter lights around them. I kept these out for mechanical reasons as well as wanting the grues to seem more organic and biological and less shadow-magiccy. But I'm curious what people think about stuff like this. 
 
Again a lot of this will be somewhat speculative until more rounds have been played with grues but any feedback would be appreciated. Thanks.

**Comment by coolguymcman** [comment]
Grues should be able to get rid of all light in areas that they control. Having computers or lanterns that sting them for massive damage, and they can't turn them off in their OWN territory is very dumb.
Maybe let them have some way to flicker lights by standing near them, eventually shutting them off? Something that lets them have a firmer grasp on rooms they have presence in, but not ridiculous to the point insta-shuttingoff any lights assistants drag into their domain, or destroying every single light source within 10 seconds of walking into a room. While larva simply have to hide and molt, juveniles have barely anything going for them. They're gonna be spending a lot of time in the dark anyways, why not give them something interesting to do by standing near lights to disrupt them?
AI should keep their camera lights, but it would make sense for grues to destroy cameras. AI has to defend their cameras by shining lights on aggressive, expansionist grues. It could be interesting!

**Comment by Hinaichigo** [comment]
I've been looking at making things like desk lamps and flashlights smashable, done by using harm intent and clicking on the item, with or without a weapon. Ideally I'd want to generalize it (enabled on a per-item basis) to as many types of items as possible but since this would conflict with any item-specific harm intent actions it might not work out with every item. Not only things like a grue smashing desk lamps, but also being able to walk into chemistry and smash up the beakers with a crowbar. Only grues being able to smash flashlights would seem a little too snowflakey. So it'd have to be it's own general thing.
And the same goes for computer monitors and such.  If a grue can smash them then maybe an assistant with a crowbar should be able to as well. Comms console could have reinforced plasma glass or something to make it harder to break.

The current idea I have is that any item could be set to being breakable, with a certain amount of structural integrity (health). Then if it's breakable and it gets an incoming attack with harm intent, it overwrites the default proc and smashes at it. Some things could have a basic smash resistance, like if you try to smash a flashlight with a rag it just glances off, but you could use a wrench and break it apart in a few hits. 

There are a lot of light emitting objects of varying types, so a darkness or light-destroying aura thing could work well. But I sort of want to avoid making them seem like shadow elementals if possible.

What you mentioned about juveniles too, I changed them up a bit in #31968 so hopefully that should address it. Now they're a bit stronger and can eat. And the shadowpower farming mechanic was removed and replaced by needing to eat someone in order to grow.

**Comment by Eneocho** [comment]
Some people suggested that grue should have some sort of ranged attack and/or some sort of thermal vision like the benos have.
Ranged darkness bolt or thermals to locate properly if limited to melee only.

**Comment by Hinaichigo** [comment]
Thermals is seeing people through walls right?
Also, I noticed most people seem to die pretty quickly as a grue. Maybe the thermal vision could help them avoid that; do you have any other ideas? One thing I was thinking was invisibility in full darkness.

If #32007 gets merged I'm planning to make a bunch of light producing items breakable, and also try to extend it to structures and machinery so computer monitors, cameras, morgue trays, and wall mounted mining lantern hooks can be broken as well.

**Comment by coolguymcman** [comment]
>One thing I was thinking was invisibility in full darkness.

Well, grues are already practically invisible in the darkness (excluding NVGs). Although, being genuinely invisible in the dark, or at least transparent, is a very entertaining idea for a scary antagonist's toolkit. Certainly not a bad idea, grues may want to take everything they can get. Perhaps this opens the possibility for more tools to reward a mature, robust grue who has eaten several times, beyond breaking reinforced walls?

> Some people suggested that grue should have some sort of ranged attack and/or some sort of thermal vision like the benos have. Ranged darkness bolt or thermals to locate properly if limited to melee only.

Thermal vision is a brilliant idea for this ambush playstyle, but ranged attacks just seem silly considering that OG grues have always been melee confrontational, monstrous but vulnerable, like "im gonna kill that grue, oh shit a grue, i got bit twice oh- You have been eaten by a grue." Having ranged attacks leans too heavily into running away, and it might make actually FIGHTING the grues a slog of getting pelted by ~whatever~ damage bolts until you're slow enough to be mauled and gibbed. Not fun! If anything, grues deserve surveillance tools, like invisible tripwires to alert the predator to some prey walking into their territory. It helps to prevent you getting ambushed and BTFO by some assistant with a lasergun and a locker full of flares, while also encouraging confrontation with (potentially) unwitting crewmen, giving them a glorious scare.

TL;DR Invisibility, why not? Thermals suit a stealthy-type antag like the grue, but ranged attacks may be unfun to fight against. More tools to "find", not to "fight" since biting is so strong already.

**Comment by Eneocho** [comment]
> Thermals is seeing people through walls right?

Yes. Only people/mobs though. You see their relative location related to you but not the walls nor anything else. Try the thermal glasses on localhost for an example.

>Also, I noticed most people seem to die pretty quickly as a grue. Maybe the thermal vision could help them avoid that; do you have any other ideas? 

Main point of thermals is to actually be able to locate a victim, you're currently just stuck doing nothing, maintcrawling until you LoS with your target, point at which the target notices you as well.

An idea could be light sucking "totems" that make a considerable area (7x7? 9x9?) intensely dark for as long as they are active, humanoids without light move fairly slower (something something, eldritch dark). Only the most extreme light sources can breach the totem darkness and not by much (A floodlight makes the same amount of light as a PDA?). A grue can only safely create one totem per eaten sentient. Making more than your current limit halves your speed and damage per totem. They're good for area denial, but are obvious and unmovable. The Eat Light skill on the other hand, only removes light in a small radius around you (3x3?) and lasts for only a handful of seconds, letting you attack safelyin a mad rush, since you won't burn from the area lights. 

Alternatively, you could give them a "darkness bolt" type of skill, letting them range attack when covered in darkness.

>One thing I was thinking was invisibility in full darkness.

Perhaps, sounds good and would compound with the "Eat Light" skill or my suggestion of light sucking totems for some emergent gameplay.

> If #32007 gets merged I'm planning to make a bunch of light producing items breakable, and also try to extend it to structures and machinery so computer monitors, cameras, morgue trays, and wall mounted mining lantern hooks can be broken as well.

Not sure how you plan to implement the lights breaking, but instead of making the light source items get wrecked and unusable, make it so "breaking" a light source item breaks the bulb inside and/or power source (engineering floodlights, they use powercells and if they run outta juice they shutdown), so you can replace it (replace a desk lamp's lightbulb with a High Efficiency one for EXTRA LIGHT). Maybe add a way to manually replace the lightbulb without breaking the thing first.
Would emergent gameplay as well for both sides, since players could actively replace their lightsource bulbs with higher potency ones, while grues would not only break them, but also steal them to stop the light from being fixed.
Make it so they can disable or smash light-tiles as well, you only need one powergamey player to cuck all the grues with le funny light tiles.

**Comment by Eneocho** [comment]
Not related to grues, but could you consider importing the red overlay grues have to the NOIR gene? The Noir aesthetic highlights red, like blood or red clothing, but nothing else. I'd do it myself but I don't understand the colour matrix stuff nor how to edit it.
It'd make for a cooler looking "disability".

**Comment by Blithering** [comment]
Maybe give grues a motion sensor like ability they can place around their area, so they know when something has entered and can start hunting them.

**Comment by Eneocho** [comment]
I like the "track people in darkness" idea a lot. With invisible to non-grue tracks. You could use the CDDA scent mechanic, you have a scent that the "zombies" and such can track. To save on computing, only enable the tracks and stuff when a grue role is called, then disable them once the last grue (or egg) are dead.

**Comment by DamianX** [comment]
Having played a few rounds featuring the new grues, I'm wondering why they exist.
They like darkness, break light sources, run really fast, and click you until they you're dead, then they lay eggs.
That description sounds a lot like xenomorphs to me, except grues can run faster and tend to snowball in a shorter amount of time, while lacking all the things that make xenomorphs cool, such as the hivemind, a leader, classes, nests, etcetera.

Am I missing something?

**Comment by Hinaichigo** [comment]
One main thing is that they allow for novel gameplay based on the lighting system. Xenos, while they have nightvision, can survive in light and the darkness only benefits them by serving to blind humans. With grues though, light is a weapon against them, and they heal in darkness so it leads to more of a focus on keeping the lights on, and staying in the light, for humans.
If they seem to snowball too quickly we could nerf their stats a bit.
I noticed they started winning a lot more after the drain light spell was added (by popular demand). That could also be nerfed to last for less time per creature eaten. Or maybe it's just players getting more used to playing as them. Because for the first few weeks they would either kill themselves in the light or get hunted down and slain rather quickly.
Once they can break more light sources like cameras, mining lanterns, etc. I think some nerfs could be warranted if others feel similar.
Perhaps the size of the herd should be the "buff" rather than direct stat buffs?
As someone said, it might be good to have xenos as the more "existential" threat to the station (they do usually end up snowballing and winning it seems to me) with grues as more of a lurking menace that still allow the round to go on. That's sort of what I intended originally but maybe they get too strong too fast? Recently they seem to either be killed off somewhat quickly, or one adult snowballs while the juveniles mostly stay hungry and are hunted down here and there.

One idea I had was reducing their movespeed and/or strength buffs but giving them the ability to "blink" into a random, sufficiently-dark tile some distance away in order to elude being hunted down and also to keep people from knowing where they might be, adding a bit more uncertainty. But I'm not sure if that would be fun.

I will say that originally, the egg laying and proliferating thing wasn't planned to be the main focus, and I was thinking more about solo grues fighting on their own. I was envisioning lowpop rounds with a solo grue always lurking in the shadows posing a threat but as long as the human stayed in the light or carried a flashlight with them they'd mostly be fine. Indeed by myself I couldn't really test out the emergent dynamics with a bunch of grues being active on the station at the same time, But it seems that that is actually a central facet of their gameplay, creating a herd and working together with other grues. So I could see how some changes such as stat nerfs could help account for this, or anything else anyone might have in mind. I'm open to new ideas and suggestions and curious to hear what people think about making things more fun.

Also one thing to keep in mind grue egglaying is a config option that can be disabled to shift things more towards the "solo lurking grue" experience if that's seen as desirable. Anyone could petition to turn it off. We could always experiment with that for a while.

**Comment by Eneocho** [comment]
I still think that grue should spawn in groups of 2.

**Comment by Hinaichigo** [comment]
> I still think that grue should spawn in groups of 2.

In the same area or in a random area per grue?

**Comment by Eneocho** [comment]
Same area so they can cooperate.

**Comment by Hinaichigo** [comment]
I could try implementing that for the midround version.
Also, in general I'd like to express that from what I can tell, it seems they're generally settled into a state that people seem okay with, aside from the floor lights and unbreakable mining lanterns/cameras, so I'm a bit hesitant to change things too drastically (things like stat tweaks and stuff like the 2 grue spawn aside) unless there's a strong overall sentiment that something needs to be changed. "No news is good news" & "If it ain't broke don't fix it" type of thing. That being said, I'll continue to consider what's said here and also keep track and make note of the overall sentiment towards the gamemode and any particular points of contention.

One thing that made me think this way was the overall reaction to the thermal vision proposal. People were defending the current setup versus the proposed rather strongly, indicating to me some level of satisfaction with the state of grues at that time.

**Comment by Eneocho** [comment]
I'd still like if you could rework the grue vision for the NOIR disability, black and white but highlighting all red.

**Comment by Hinaichigo** [comment]
I took a look at that a little while ago after you mentioned it but didn't end up finishing it. I can take another look I spose.

**Comment by Eneocho** [comment]
Much appreciated.

**Comment by Hinaichigo** [comment]
It's fairly puzzling because first to get it greyscale you need to have all input colors map to an even split of output colors. That's why the current noir matrix has all 0.33s. So in a sense you want all colors to become white. But then you want excess red to erase blue and green from that white. That leads to anything that was originally white (with equal RGB components) turning pink. So I'm still not sure how to do it with the client.color thing by itself yet.

**Comment by Eneocho** [comment]
@Hinaichigo I tried the following matrix and it made everything black and white except semi transparent blue items (beakers, latex gloves, windows, etc). It however also made those semi transparent items red. It does look kinda nice, but not what I wanted.
`(0.33,0.33,0.33,0,\
  0.33,0.33,0.33,0,\
  0.33,0.33,0.33,0,\
  0,0.33,0.33,1,\  
  0,-0.33,-0.33,0)`
Mind you I have no idea how does the colour matrix system works (aside from the values being R,G,B,Transparency horizontally).
![matrix magic](https://user-images.githubusercontent.com/67024428/161859931-c8781e6e-9de2-4764-9bfd-285e44d32ace.png)

**Comment by Hinaichigo** [comment]
@Eneocho
With your matrix you are turning alpha into red it seems like. I think it might be best to avoid changing  the 4th row or the 4th column for that reason... but I'm not completely sure.
[http://www.byond.com/forum/post/2209545](http://www.byond.com/forum/post/2209545)
This has some useful info about each of the rows/columns and what they do.

**Comment by Eneocho** [comment]
When I tweaked the 4th value on the 4th line (I tried -0.33 on the 3rd line's 4th value and 0.33 on the 4th line 4th value) I accidentally made everything transparent, including space, so it all slowly transitioned to pure black.

**Comment by Eneocho** [comment]
RIP grue NOIR.
