### ISSUE TITLE
Problems with "Round now ends if no players are alive after 15 minutes "

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#32010]
#### Description of issue
I've seen #31962 thrice now and I do not believe it's beneficial for low population rounds. I had initially thought that the round end would trigger 15 minutes after the last death, not 15 minutes after roundstart.
This triggers when players log out of the game. say if you were the sole player on the station, you're having problems with game performance and you reconnect to fix it. The game immediately ends with no way for you to stop it. This is a common occurrence.

I hate that players can't setup power and log out, having latejoiners not have to deal with setting up power.

I dislike that players can't join into uber gunked and depowered station, and be the hero who restores everything back to normal.
Or that ghost role who inherits the station.

It's just taking away a lot of experiences and leaves players going through roundstart too often.
And the ending cinematic does not even show.

#### Server revision

21d9fe7daa2a7f33e74ba54c5c1fb0f15c5bfe68

**Comment by Silkizuad** [comment]
I think I was the player mentioned, and yes. While it's usefu when you're alone andl if you just die, and instead of waiting 15 minutes for the round to restart it restarts almost instantly, however, when disconnecting due Byond, internet or other issues, it kills the round. I personally would go for 5 minutes after everyone is dead or disconnected to end the round instead of instantly how it is now.

**Comment by Theophrastus1** [comment]
kanef strikes again

**Comment by Eneocho** [comment]
I thought it was 15 min after last death, what the hell?

**Comment by robintime** [comment]
@kane-f
