### ISSUE TITLE
The RoidStation Trader experience is pain

### ISSUE THREAD

**Issue by Cartlord** [d3athrow/vgstation13#32207]
#### Description of issue
On [roid] Station, being a Trader sucks, as other Trader outposts on lowpop maps (Box and Synergy) have more than it does despite Roid being a midpop map.
For comparison: BoxStation's Trader outpost has twenty-three or twenty-four plant trays, xenobotany machines (no disks), two roundstart apiaries with two roundstart chill bug queens to fill them, two Botanist lockers with full stock (Service radio headset, botany belt, bug net, plant clippers, hatchet, etc.), three Miner lockers with full stock (Mining belt, pick, scanner, meson scanners, etc.), and everything needed to make an Autolathe.

Roid has eleven plant trays, one crate with basic Botany supplies (no service headset, no plant clippers, no Hydroponics jumpsuit), a powered crossbow with some rods, a full set of solars, _one_ rack of _extremely_ basic miner equipment (one set of mesons, one pickaxe, one hand pickaxe, one mining ore satchel), a smelter you can't get money from, no coin press to put the metals in, one set of insulated gauntlets, a roundstart Autolathe, and a chem dispenser.

I may be an idiot, but I think we should have a [discussion] about just what a Trader outpost should have; personally, I think it's not right that a highpop station has less stuff to do than a lowpop station.
#### Server revision
Game: 640def376fa86972a10781008b1229fbd59a5072 
Patches: 609a806a066b5859e732b12938343551efcc77f7 
Current Infomational Settings: 
Protect Authority Roles From Tratior: 1

**Comment by djkramer123** [comment]
Imagine thinking traders are entitled to anything

>I may be an idiot

Should've started with this

**Comment by Dacendeth** [comment]
Birds are not important

**Comment by Cartlord** [comment]
If Birds are not important, then why are there so many good things on the Box Station and Synergy Station Trader outposts?

**Comment by Eneocho** [comment]
You insist on doing botany as a trader, but trader is a trade focused role, you can't expect them to get many botany trays, vox botany is supposed to be a side hustle while you trade with the crew. Can't you do botany as a crewmember botanist?
If you DO want to go for the trader food experience, there's far better ways than staying in the trader outpost farming for nobody's gain (most of the times the trader crops will never see use in the round). I suggested to you once that you do a hot dog stand thing. Boxen cloner, condiment machine flatpack, painted tiles via tile painter from an autolathe, boom. Instant roleplay AND food based trader gimmick.
And the miner/botany lockers are intended for the rare occasion the station sells you a prisoner to work on the slave farm/mines (they will not).
Coin presses are very powerful machines, so giving one to the traders is iffy at best and retarded at worst. If you want extra use out of your roundstart coin, you can gamble by using some wire on it, which gives you a chance to recover the coin on use.
There's lots of goodies on box station trader outpost because it's the oldest map and most played map, thus has been refined furthest. Not sure if viciosaurus is a vox metaclubbie, but it would explain synergy's outpost goodies.
And Box is NOT a lowpop map. Box is the default map. That it gets voted and THEN the pop falls into lowpop territory is another thing.

**Comment by Eneocho** [comment]
Also, if you get sand from the asteroid, you can crush it in hand to make sandstone, you can then turn said sandstone into piles of dirt which work as extra hydro trays. Alternatively, you can use grass in hand (if you get some in the vox outpost, either seeds or random chance on the "weeds" roll) to make astroturf. Installing then using a shovel in said astroturf also makes sand.

**Comment by Cartlord** [comment]
I referred to Box Station as a "lowpop map" alongside Synergy because they can both be voted in at very low pop, compared to Roid which has a pop requirement high enough that you won't always see it in the vote.
This is likely to sound retarded, but honestly, I enjoy chill lowpop Trader because I feel like it's one of the few roles where I won't get fucked over; the low seed selection makes Hydroponics more approachable, and it gave me a safe environment to learn the systems and some of their weird quirks.
If I play Miner at lowpop, I'm likely to have to work either Research & Development, Engineering, or both - and I play Miner to _mine_, not to set power or to do research. If I play Trader at lowpop, I can mine all I want, or garden all I want, and not a goddamn soul will stop me or yell at me.
I also want to point out, since you brought it up, that Roid doesn't actually give you a shovel, It gives you a botany spade, which can be used to dig sand - but, with the sheer amount of retardation present in this game, I imagine a good few people just wouldn't even consider that.
I can understand not giving the Traders a coin press on every map, but it just seems odd to have a smelter without any real use for the ore (beyond making reinforced plasmaglass to upgrade your solars, or selling it to the station in the **very** unlikely event they have no miners).

**Comment by Eneocho** [comment]
I meant both a shovel or spade. Since they're both digging tools, they both work for the roid sand and the astroturf sand farming.

**Comment by Eneocho** [comment]
And while I get the feeling, that exact kind of behaviour is one of the main issues with trader. This is a social game. Removing the social aspect is a bad choice.
Hell, most players like teaching ingame mechanics, join as a botanist and the nearest grayshit/clown/chef/botanist will probably drop whatever they were doing to teach you the good stuff.
Nobody ever asks a miner to do Engineering nor RnD. You can stay perfectly happy with your subpar tools while doing no research if there were no science staff, but you can do some very minor research (there's even a special guide for miners on the RnD guide to speedrun the mining tools and nothing else). 
You're only expected to do a job you didn't sign for if there's some expectations or you're playing a related one (asking a xenobio to do RnD or asking a mechanic to set up power, for example, despite what players say, LOOKING AT YOU RUBYLIPS), and even then you can just refuse, this is a social game after all.
For the seed selection part, vox seeds are actually the wacky ones. Unless you're aiming for specific reagents or effects, all regular human crops are mostly the same (nutriment source). 
Telling you this as a botany player, you'll find way more fun doing botany stationside than on the outpost, the variety of seeds is slightly overwhelming, but you can make tons of fun stuff, like plants that literally shit out diamond, plants that release oxygen, plants that teleport you when thrown, bananas so powerful you slip into next week, toxins so strong they're only curable by cloning, plants that literally EMP when harvested, food that fills you with spiders when eaten, plants that make meat on harvest, vines that melt walls, organic lights so strong that station lights become redundant, etc.

**Comment by Cartlord** [comment]
I know about the wack shit that mutant plants can do from other servers, I just like the smaller selection.
When I'm playing a Botanist and nobody can be bothered to give me any requests, I pretty much lock up, because there are so many damn seeds that I can't keep all my opinions on them in order; as a Trader, however, nothing stops me from growing _all_ the seeds. In addition, since there _isn't_ a guide for Trader Xenobotany, I actually had to put in some damn effort and experiment - you know, the thing that people claim is the best part of the sandbox game; this was one of the only times I found experimenting to be legitimately practical, because there were under a dozen seeds to try and I knew I wouldn't fuck myself or anyone else over by not having assblastium or whatever they needed grown but never told me they wanted grown.
As for saying I should join and get advice... well, I tried that once, and the other player literally knew nothing more than the wiki guide. In addition, with the server's population averaging under 20, it's not even likely for there to _be_ another Botanist I can try to get help from.
I understand the basic ideas of Botany, but frankly, I'm an uncreative fuck who doesn't want to grow anything specific most rounds, and Vox Hydroponics let me deal with that more easily.
As for needing to break into other departments and do their damn jobs, I feel like I need to do it, because I have no reason to believe anyone else will set up power if I don't.
I do frankly rather like the game's social aspect, but it feels like few people on /vg/station actually want to engage with it, at least when I try; I directly ask when playing Shaft Miner if anyone needs alloys, and directly offer certain materials to Engineering, but almost nobody ever bites. The only reason I mine past the ten minute mark most rounds is in the hope that something interesting will happen on the 'roid, because my crewmates certainly aren't going to provide anything engaging.
I mostly play on shitpop rounds (12 pop or under), so it usually amounts to a single-player experience anyway, unless I need to beat the Mime or deliver something to Sci. Being a Trader just makes the single-player experience easier.

**Comment by djkramer123** [comment]
If the extent of your social interactions with other people is "Does anyone want [insert material]" and running away to the roid when nobody wants them it's not really that surprising that you end up with single player experiences.

It's a scary thought for many autists who play this game but if you want to have fun social interactions with other players you have to actually make the attempt to interact with them to some meaningful degree.

If you want something that caters to a single player experience, play on a local server.

**Comment by WindowsErrors** [comment]
The Cartlord Trader experience is pain

**Comment by Kurfursten** [comment]
I'm somewhat surprised because I generally think for the average trader, they would prefer the Roidstation setup. 11 trays is usually plenty to grow a little Vox home cooking and having a prebuilt autolathe and chem dispenser is really fantastic. Yes, you can (and I always do) build an autolathe on Box, but having one out of the gate is one less thing to get done in the early shift rush. I think what they have is plenty reasonable already.

**Comment by Eneocho** [comment]
>In addition, since there _isn't_ a guide for Trader Xenobotany

There is none because xenobotany works the same for all seeds, including trader ones except the non mutable ones (nofruit, diona pods, clown pods, etc). 

> I knew I wouldn't fuck myself or anyone else over by not having assblastium or whatever they needed grown but never told me they wanted grown.

That is their problem, not yours. If they wanted peepeepoopoo plants grown, they better tell the guy who grows those plants, else they just won't get those plants and they can't get mad, because they didn't ask for 'em.
If you want some ideas on what to do try the following ideas:
If there's a clown: Get them Bluespace Bananas, at high potency they slip and remove shoes.
If you want to fuck around: Splice Blue Tomatoes into Bluespace Tomatoes then raise the potency. This mix both teleports you (or a victim) around and lubes that singular tile for that lube fun when thrown.
If you want to be helpful: Make the strongest fucking ambrosia plant you can. With all the chems you can find. The basic ambrosia mix is vulgaris into deus, the tryhard one is vulgaris, rocknut (iron) and kudzu (antitox) into deus, the autismo mix is all that plus all the reagents you can splice from random seeds (pic related).
![image](https://user-images.githubusercontent.com/67024428/158061472-cb1661d7-8fba-4ef7-97ce-9ad5cbe5cdbc.png)
If there are no miners: Mutate the material plants, splice ice chilly and silicate citrus into them, then potency. Harvest for literal sheets of rare materials.

Nothing stops you from just asking on comms, "Hey, does anyone want any plants grown?" and growing the requested stuff or learning the intricacies of the system by experimenting. 
Botany is a secondary job, shifts can and will go on like normal without any botanist but you can do tons of shit to help others (or ruin them, if that's your thing).

> I directly ask when playing Shaft Miner if anyone needs alloys, and directly offer certain materials to Engineering, but almost nobody ever bites.

The one time people ask for alloys is if they're doing a project that needs them en masse and they can't get them reliably by themselves, since stuff like brick is hard to get stationside, while plasteel or plasma glass can be made in recycling. The point of going miner is less to make stuff for others and more to mine for mining's sake. You get the dough and buy whatever it is the QM wants because you can afford it tenfold. Or do like some miners do and get some hivelords lazarus capsules for portable instant healing then go on space exploring.

And regarding your trader play, you tend to get too hyperfocused on the single player aspect to the point of ignoring the crew, which goes directly against the spirit of trader (nothing stops you from getting wooden planks and barricading botany as crew botanist btw). I remember more than a few rounds I had to bug you more than twice for you to answer. For real, man. Try the social aspect of the game, that's the fun part. You ever read any fun greens about a round? Notice how they never go for the single player experience?

**Comment by Kromkar** [comment]
> 

Not reading your six paragraph post but pay me $50 and I'll map whatever you want into roid trader and PR it

**Comment by drawsstuff** [comment]
One of the top 3 trader players as of 2022, I feel qualified to peanut post here.

No.

Roid is one of the better trader maps, and I would go as far as saying it's probably one of the best. You are two feet from sand. Go dig some sand. Better yet, go steal some bitches and make them dig the sand for you and grow your plants for you. You don't need to be an antag to profit from sweet sweet slave labor, collaborate with your local security department, maybe offer a profit split from a "prisoner exchange program". Trader is all about making everything from nothing.

**Comment by Cartlord** [comment]
Actually, Eneocho, the reason I'm hard to contact is because I wasn't able to wear my glasses for a while (weird story, don't ask) so it was hard for me to pay attention to chat & the game at the same time.

**Comment by Cartlord** [comment]
I'm considering closing this issue, and making a seperate one about how _inconsistent_ the Trader experience is across maps.
If Box and Synergy, with their plentiful plant trays, xenobotany potential, roundstart chill bugs, and full lockers of stuff are the intended Trader experience - then something is clearly wrong with Roid and Way.
If Roid and Way, with their meager tools, are the intended Trader experience - then, clearly, something is wrong with Box and Synergy.

**Comment by Kurfursten** [comment]
> You are two feet from sand. Go dig some sand

In short: "Touch sand."

> how inconsistent the Trader experience is across maps

That's the intended design. Always been that way. You should've seen the original meta trader experience.

**Comment by Kromkar** [comment]
> I'm considering closing this issue, and making a seperate one about how _inconsistent_ the Trader experience is across maps. If Box and Synergy, with their plentiful plant trays, xenobotany potential, roundstart chill bugs, and full lockers of stuff are the intended Trader experience - then something is clearly wrong with Roid and Way. If Roid and Way, with their meager tools, are the intended Trader experience - then, clearly, something is wrong with Box and Synergy.

Perhaps something is wrong with you. Again, pay me $50 and I will map and submit whatever changes you want.
