### ISSUE TITLE
toggling darkness breaks ghost sprites

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32212]
(WEB REPORT BY: diegoxt48 REMOTE: 206.221.180.138:7777)
# Revision
7ecbd7099769e02c0e34ae266d1bb852d55183ea

# Description
toggle darkness disables all ghost sprites, also breaks regular sprites some times
# Steps to Reproduce
toggle darkness as ghost
# What you Expected
to see my dead brethren
# What Actually Happened
alone in a cold dark void, only hearing voices

**Comment by ghost** [comment]
probably something to do with planes, it breaks docking ports too

**Comment by Eneocho** [comment]
I always thought it was intended.

**Comment by Exxion** [comment]
This has always been the case, and before the hide ghosts button was added, was the way to hide ghosts. It's because the toggle darkness button was added *way* before planes existed, or any other reasonable way to selectively hide certain things from certain people. Instead, it just uses `invisibility`/`see_invisible`, which pretty clearly cannot be configured to make darkness invisible but ghosts visible.
Nowadays, it would be pretty easy to change it to use planes or something instead, but nobody has bothered.

**Comment by nervere** [comment]
Fixed by #33171
