### ISSUE TITLE
Re-implementing puddles

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#32254]
[featurerequest][discussion]
Leaving this issue open as a way to collect feedback on the now removed system so I can improve it some other time, if it ever decides to come back.

Notable issues:
 * How should puddle cleaning be handled?

**Comment by adacovsk** [comment]
I like the puddles, but you need to keep it so that water from extinguishers doesn't make puddles (but other reagents still do). Just make it so that all the PRs are combined into one big PR. I like the puddles tbh.

Also, if a wire knot is exposed, make it so electricity passes through the puddles for extra fun (or just sparks)
thermite needs to work

I think they're great

**Comment by Eneocho** [comment]
I'm ok with it as long as you don't nerf water/lube to the ground. That and code optimizations, too many puddles meant frozen serb.

**Comment by Hinaichigo** [comment]
I like puddles too, and I think it'll be good to have it as a foundation to expand into volumetric liquid mechanics down the line.
I think it's important to preserve the current game mechanics with lubing and slipping so it can get up and running more seamlessly. The main opposition to it I think came from the disruption to established mechanics, mainly slipping and cleaning. I'll copy-paste what I said in #32244.

> Maybe even a single unit could form a puddle, with a minimum apparent size for visibility, with anything below eg. 10u looking the same as 10u, and evaporation times could go to their pre-puddle values and not depend on volume. Because they're flat along the ground, we could say a puddle's surface area (and thus evap rate) is linearly proportional with volume, so a small puddle would last as long as a large puddle, or something.
> 
> Also agree that slip time shouldn't be impacted by puddle volume, just the highest slipperyness of the reagents it contains.
> 
> That way all the previous functionality of lubed and watered floors are preserved as they were, within the puddle framework.
> 
> Down the line you could branch evaporation into two different things:
> 
> drying up (like the previous system, the puddle disappears after a certain amount of time) Lube would simply dry up, not evaporate into lube vapor.
> true evaporation (the puddle loses volume via evaporation into the surrounding air, at a rate depending on the pressure and temperature of the surrounding air) That way you could get explosive fuel-air mixtures and stuff.

Also maybe you could consider having blood puddles under a certain volume retaining their original bloodstain-shaped sprite. Since small puddles don't need to be circular this could actually be something for all liquids, with various randomly selected dynamically-colored "spatter" sprites for small quantities of liquid. Then when they get big enough they turn into a pool of blood, and then merge with others, and things like that.

**Comment by WindowsErrors** [comment]
the halls will run brown with coffee

**Comment by godietxt80** [comment]
they're so fucking annoying to clean up, the way space cleaner (my favourite item/chem) in the game basically doesn't work on them made me FURIOUS

**Comment by Hinaichigo** [comment]
What's the next step of your master plan?
