### ISSUE TITLE
zam snax are too expensive

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32269]
(WEB REPORT BY: wotisjanitor REMOTE: 206.221.180.138:7777)
# Revision
93d2deb731e16ba6abcbf3a1ed330ebc0f2658c2

# Description
$20 for a single biscuit, while the merch computer sells 3 for $40
# Steps to Reproduce
buy a biscuit
# What you Expected
like, $11
# What Actually Happened
$20 for 1 biscuit

**Comment by Optimism333** [comment]
Appreciate the feedback. However, I will say that this is intended by design:

-The pack of biscuits was calculated based on the nutriment / price ratio of the food items on the merch computer
-The individual biscuit was calculated based on the nutriment / price ratio of the food items in comparable vending machines
-I also wanted the individual biscuit to be more expensive than buying the pack, since it's generally cheaper to buy goods in bulk. I thought it was a nice bit of spess realism. Zam is trying to encourage you to buy more biscuits.

Finally, consider what you get for 20 credits at the roundstart Getmore Chocolate Corp machine. A bag of chips with 3 nutriment, that's it. But if you pay for the Zam vending packs you can pay the same amount of credits and get a biscuit with 3 nutriment, 3 hyronalin, 2 coco, 2 sugar, and 4 sulphuric acid. I'd say that's a pretty generous comparison. The only obstacle is getting the order from cargo and assembling the machine.

Even if you disagree with everything I said, hopefully you can understand why I don't think they're overpriced.

**Comment by Kurfursten** [comment]
This is fine, it's the classic raisin situation all over again. Maybe we should come up with a way to make it more coherent to people what they get out of various foods, since just eating it isn't always obvious. Hm.
