### ISSUE TITLE
brushes gunk palettes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32325]
(WEB REPORT BY: jesture REMOTE: 206.221.180.138:7777)
# Revision
beba032c93536214b13e07621626e17cc70035c8

# Description
i was trying to paint but when i applied an empty brush to the palette it added a new color to it for some reason then i was no longer able to open up the palette ui
# Steps to Reproduce
have palette with all the colors of the crayons on it
have empty brush in one hand
apply empty brush to palette
You add a new color to the palette.
try to use palette in-hand to open palette ui
palette ui no open
# What you Expected
graphic design is my passion
# What Actually Happened
pony.dmi

**Comment by jellyveggie2** [comment]
Noting this down for later:

What's happening here is, painting utensils (brushes, crayons, etc.) are converted to a base color + list of colors (aka palette datum) when used on a painting to transfer the colors available, or in this case when used on a palette (the item) to check the utensil has colors to be added. If it does, the palette item stores the palette datum on a list of palette datums. 
Brushes are special in that, when converted to a palette datum it produces a list containing both both it's own color and those of any palette items the user may be holding.

So, if you're using an brush on some palette _while holding a palette that contains colors_, the palette you're adding to will be fooleed into thinking the brush does have a color, but then complains about the data it just stored having no actual base color because the brush was empty.

It'll get into a fix later today.
