### ISSUE TITLE
beer glass not shattering when thrown

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32538]
(WEB REPORT BY: angryturnip REMOTE: 206.221.180.138:7777)
# Revision
f8b7812ba8a5a54a2ca45bf82d4a5a90296b3d1c

# Description
Tossing a beer glass at an artifact gives the "The glass of Beer shatters!" text, but it doesn't shatter.
# Steps to Reproduce
Toss a glass of beer at a large artifact
# What you Expected
The beer glass would shatter
# What Actually Happened
Drinkable beer!

**Comment by Eneocho** [comment]
The breakable stuff framework made it so throwing at the floor leaves glass shit intact, but throwing at a wall breaks em. I guess the artifact got counted as the floor or something. Feature(TM).

**Comment by Hinaichigo** [comment]
I don't think the new framework would affect this because beer and other alcohol bottles don't use the new framework; they were breakable before using their own system. After testing there is some inconsistency. If you throw a beer or other alcohol bottle on the ground it breaks, but if you throw it at anything else, it becomes invincible to further breaking, even on the floor.

Also, it seems there are some inconsistencies about whether or not you smash someone in the head with a bottle or try to feed them from it.

**Comment by Hinaichigo** [comment]
Ah I think I got it it.

**Comment by Hinaichigo** [comment]
It's because of line 1805 in drinks.dm.
`reagents.reaction(hit_atom, TOUCH, zone_sels = list(user.zone_sel.selecting))`
It runtimes because `user` is null.
@kane-f maybe you could take a look at this.

**Comment by Exxion** [comment]
again...

**Comment by Hinaichigo** [comment]
It's due to the new reagent body-part reaction targeting (#32424). It's trying to splash the bottle's contents based on what zone `user` is targeting. But in this case it runtimes because there's no `user`.

The reason it caused the beer bottle not to break is because `throw_impact()` is called twice when a thrown item hits something other than a floor. After the first hit, its breakability (not something from the new system, but the variable `isGlass`)  is toggled off to avoid the bottle breaking again during the second `throw_impact()`, preventing two broken bottles from spawning. However, the runtime interrupts it midway through the first `throw_impact()` before the bottle can break, but after it's set to be not breakable. So the next time you try to smash it on something or someone, it doesn't work.

**Comment by Exxion** [comment]
Yeah, I know, I meant this exact bug has happened due to similar runtimes like four times before

**Comment by Eneocho** [comment]
I'm having flashbacks to the "no dude, for real, I fixed the safes being broken" PRs.
