### ISSUE TITLE
[Meta] Spare parts locker in kitchen backroom blocked by meat spikes

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3254]
![ss 2015-02-27 at 03 59 01](https://cloud.githubusercontent.com/assets/6526157/6419202/06499c70-be9a-11e4-8413-c766f53f5f42.png)
You have to break either a meat spike or the reinforced window to be able to reach it. Doubly silly since you can't drag any of those two.

**Comment by IratePirate** [comment]
This is fixed in the PR i've got opened up.

**Comment by 9600bauds** [comment]
Closing this then.

**Comment by ComicIronic** [comment]
1. You should always either ref issues in the PR, or ref the PR in the issue. Trying to track what you're referring to is incredibly annoying if neither of these things are done, and it makes history tracking and bug location WAY harder.
2. You shouldn't close an issue until the PR is merged. This is part of the reason you want a ref, so you see it merged or closed. If the PR is closed without merging, this issue will stay closed and you might forget about it. Then, people will see it and assume the issue is fixed, and it gets into a whole clusterfuck.

**Comment by 9600bauds** [comment]
You're right Comic, sorry.

**Comment by 9600bauds** [comment]
Was fixed by #3241
