### ISSUE TITLE
SMES construction: terminal party

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#3257]
when adding a terminal to an SMES, you can click on the SMES a LOT of times before the terminal actually gets placed, resulting in a lot of terminals, which is silly, not sure if they work or not

**Comment by Probe1** [comment]
not only is it silly, it's a serious issue.  it can result in the apc not charging in some situations.  

there needs to be a check to make sure a player can't add extra wires to a machine as this bug is ubiquitous.  you can add a whole cable coil to a computer while wiring it for example if you click enough before the first one completes.

**Comment by ComicIronic** [comment]
Alt title: why we need more construction datums.

**Comment by ComicIronic** [comment]
Fixed by #4045. Reopen if still an issue.
