### ISSUE TITLE
monkeys and muzzles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32659]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
c67e1f391b7c3612d50114b45778f60ec295d51d

# Description
putting a rag in your own mouth as a monkey puts an invisible rag in your mouth and keeps a ghost one in your hand, it still muffles you but it just looks like you didn't put it in your mouth
you can take off the muzzles as a monkey despite there being code to prevent it
also i'm not sure if the muffled speech persists across languages
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Hinaichigo** [comment]
> putting a rag in your own mouth as a monkey puts an invisible rag in your mouth and keeps a ghost one in your hand

After some testing, the invisible item thing seems to happen for any item that isn't a clothing item or a cigarette. So rags, lollipops, and lollipop sticks. Also, I'll see if I can make a monkey sprite.

> you can take off the muzzles as a monkey despite there being code to prevent it

Is this normal muzzles, rag-muzzles, or both? That code only prevents normal muzzles currently. Should a monkey be unable to pull a rag out of its mouth? It seems to me like it wouldn't have much trouble doing so. I've been thinking of the rag as simply stuffed into the mouth. If it was tied around the head I could see a monkey having difficulty. We could change it so that the rag is tied around the head, though it seems like most rags would be too small for most heads (for humanoids anyway, perhaps not monkeys). What do people think?

>i'm not sure if the muffled speech persists across languages

Right now you will only hear the muffling if you can normally understand the language. Otherwise the you'll hear the syllables of the language you don't know. I did it that way to preserve more of the structure of the muffled speech for listeners who can understand the language, ie. keep the spaces and punctuation in the same spots. Another option is converting muffled speech to a new "Muffled" language that nobody understands, which would solve this problem, but the spacing structure is lost that way, so I kinda think the former is nicer. There could be a way to have it both ways though. I'll think about it.

**Comment by Hinaichigo** [comment]
Should a monkey be unable to pull a rag out of its mouth? It seems to me like it wouldn't have much trouble doing so. I've been thinking of the rag as simply stuffed into the mouth. If it was tied around the head I could see a monkey having difficulty. What do people think?

**Comment by pedr69** [comment]
>normal muzzles, rag-muzzles, or both?
i wasn't sure which one the code was referring to, so i tried both the proppa muzzle and the rag and could remove both
was guessing the muzzle was supposed to be stuck without outside help but the rags were working as intended
