### ISSUE TITLE
Hydrophonics massively broken - order cargo pizza

### ISSUE THREAD

**Issue by Killette3** [d3athrow/vgstation13#32661]
Clover comes out as "snack"
All edible plants produce an apple sprite but have their intended name. Straight from the vendor no xenobotany
All plants produce no chemicals, and thus also disappear instantly when attempting to eat. Straight from the vendor
Exceptions are non-edible plants such as towercaps, I assume since they are not under /snack/

**Comment by Killette3** [comment]
You also cannot inject grown produce with syringes in an attempt to eat them.

**Comment by adacovsk** [comment]
@Hinaichigo #32519 is breaking snacks

**Comment by Hinaichigo** [comment]
Apologies. something must have broken at the last minute. I'll work on a fix.
It seems spawning a snack works fine, but harvesting it runtimes:
"Positional parameters must precede all named args"
File isn't specified, but I suspect it's in seed_datums.dm.

I think it's because I used:
`product = new product_type(T, custom_plantname = name, harvester)`
when it has to be 
`product = new product_type(T, custom_plantname = name, harvester = harvester)`
I didn't know but apparently once you use a named arg in a proc you have to specify the names of each subsequent arg.
