### ISSUE TITLE
Strange seeds that make "clovers" have broken icons.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#32686]
#### Description of issue
Got a strange seed, planted it, icon worked well until then. On harvest however, the plant made only "zero leaf clovers?" (didn't seem to affect luck though), and there was no icon. I had to alt click and find the invisible faux-clovers.
#### Difference between expected and actual behavior
Expected working icons. 
Got spooky fake clovers.
#### Steps to reproduce
Plant strange seeds until you get one that harvests into non-standard "clovers". 
#### Specific information for locating
Check the seed datums interaction with the clover leaves.
#### Length of time in which bug has been known to occur
Noticed this 2 days ago.
[bugfix][oversight][sprites]

**Comment by Eneocho** [comment]
@Hinaichigo

**Comment by Hinaichigo** [comment]
I'll look into it. I wonder if it's in the runtime logs. I don't know much about strange seeds.

**Comment by Eneocho** [comment]
As far as my understanding goes, they randomly select an iconset with a food item annexed to it. So a strange seed with a bluespace tomato icon will make "bluespace tomatoes" with the teleportation interaction. You can even find strange seeds with nofruit icons, which give actual nofruit. And since these seeds tend to have high yield, you get more than 1 nofruit.
I think the issue is that the system checks for the clover iconset, but does not know which icon it should select, since the plant is not a clover, so it defaults to null leaves, which breaks the icon.

**Comment by Hinaichigo** [comment]
After looking at it a bit, I think this is the issue:
When a random seed is generated, it expects an `icon_state` called `produce` to exist. Clovers lack this, however. One way to fix this would be to snowflake in a check at the end of produce generation.
I haven't grown a mysterious seed before. Does the sprite of the in-tray plant correspond to the harvested product? Or it's its own sprite for mysterious plants?
Mysterious plants with the clover sprite also don't have the potential to be lucky. That would be nice though. I think it would require the number of leaves to be held in the seed, as we discussed before. For now I think I'll think about getting the sprite visible, and then we can consider refactoring it a bit so that works for mysterious seeds as well.

And there's another bug where self-harvesting clovers runtime because the harvester is not a mob and therefore has no `luck()` proc. That's a bit easier to fix.

**Comment by Eneocho** [comment]
The in-tray sprite matches with the fruit. A strange seed with a banana tree plant will make "bananas", the fruit will for the most part behave like a banana (but won't work on banana recipes).

**Comment by Hinaichigo** [comment]
Thanks. And with the mystery seed clovers, did the in-tray sprite work properly?

**Comment by Eneocho** [comment]
Tray sprite was a regular clover bush. Harvested faux-clovers had no icon.

**Comment by Hinaichigo** [comment]
Do mystery seed bananas leave peels when eaten?

**Comment by Hinaichigo** [comment]
Someone else had invisible four-leaf clovers.
The fact that the name gets as far as being zero-leaf or four-leaf, indicates it's generating true clover produce with specific numbers of leaves, since the procs to handle the name selection occur on the produce level, after harvest, and are specific to clovers.
I *think* I fixed it... by forcing the icon file back to `clover.dmi`
I don't really know why it wasn't `clover.dmi` in the first place, but for some reason that seemed like the right solution and from my testing I think it worked... though some factors may be different in the actual round so we might have to see.
