### ISSUE TITLE
[Disscussion] Changeling tests

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3286]
We need some better way to test changelings.
Or not at all if that is what people want.
Heres a few ideas:
Classic movie way: Get blood sample then hit it with a lit welder
Another idea: Changelings will give a special message in a cloner when "dead"
this RP week shed some light on how hard it is to "prove" a changeling unless you can put them on a linged body (which can be easily hidden/removed) or if they get murdered then come back to life.

**Comment by TermedClepe** [comment]
If it's going to be anything blood based, taking a blood sample with a syringe needs a delay as currently it is instant.

**Comment by ComicIronic** [comment]
>antag testing

This is a bad idea, even if it were the most subtle and out-of-the-way shit imaginable.
Stealthling shouldn't be punished for the sake of validhunting.

**Comment by jewishneocon** [comment]
i remember in the olden days
a snack named syndi cakes healed an antag
and thus came ye valids

such was additionally welding a beaker o' lingscumth blood, for it would bubble and A ling lies ahay.

**Comment by CptWad** [comment]
@ComicIronic I understand the concern but its easy to tell a traitor or cultist apart because they tend to have shit they are not supposed to. Changelings are hard to find evidence of. Stealthling is fun and all but when lowpop hits or a ling is getting munchy there is no way to find out if they really are a ling since so many good places to remove corpses exist. I can think of at *least* one good spot to permanently remove a body from the game per job [Except for maybe the librarian but you can always eat someone with access to one]. Since the lings only give away is the bodies themselves I find that detective work is hard in that case and in a fully populated round if one body is found in maint its not like the captain or sec can realistically lingtest every person on the station as that would be ridiculous. However I do think what @TermedClepe said is also true as someone could just ling test everyone as they walk through the halls.
I kind of like the cloner idea as lings can already come back from the dead and that cloning a ling should in theory bring into the world two seperate lings. Making it so that lings can't just get cloned by an unknowing paramedic.

**Comment by Probe1** [comment]
cindi kates are why it doesn't work but vampire tests are why it does work.

you can still do an antag test on vampires with holy water and just taking them on a stroll in space to see if they burn.  

changelings are pretty shit in that the only way to catch a ling is to catch it in the act of using its powers.  if you put it in perma, it'll break out and regenerate when it dies from exposure.  if you put it in solitary, it'll monkey->ventcrawl as soon as you walk away (so you weld the vent).  changelings are a pain the the ass because they have all the advantages when it comes to facing sec.  if they get away, they can change their name and be done.  if someone didn't catch a ling with its probiscus out then it can be very tough to actually prove its a ling.  and the alternatives I mentioned aren't great.

i think vampire antag tests work fine and changeling blood tests would be okay.

**Comment by ComicIronic** [comment]
>changelings are pretty shit in that the only way to catch a ling is to catch it in the act of using its powers

Which I believe is rather the point.
You're meant to be constantly questioning who could be a ling, or who couldn't be. It's not meant to be easy to discover, and I'm certainly against including a hard yes/no test for it.

The difference between the gamemode and the movie is that the Arctic base wasn't full of people who were heavily armed and knew what a ling was.

**Comment by Probe1** [comment]
the first paragraph is very fair to say @ComicIronic 

the second half I disagree with the reasoning and attribute the difference being in The Thing everyone knows each other well enough, and in SS13 it would be easy to impersonate anyone since who really knows anyone that well.

**Comment by CptWad** [comment]
Okay its not really wanted yet. Closing for now.
