### ISSUE TITLE
Challenger shouldn't fire on lowpop

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32872]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
cf5883bc634318dffd4d0729179e7b48b633842f

# Description
Challenger, if played by its intent, is a murderbone gamemode that typically ends in depopulation of an already depopulated station. Why is this a lowpop gamemode? This would make more sense as a highpop mode while standard traitor is lowpop.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by pedr69** [comment]
code it

**Comment by WindowsErrors** [comment]
no, it shouldn't, but you know why it still does?

it's not because it keeps things fresh, or because it makes people remember why security exists, but instead because nobody else has bothered to get rid of it

although I think it did kind of get fixed with that change that makes it require three candidates so that it doesn't just become a two player 1v1
