### ISSUE TITLE
[Feature Request] Single purpose light mechs

### ISSUE THREAD

**Issue by wiredhuman** [d3athrow/vgstation13#3289]
Nobody cares on IRC but whatever, here it goes.

The idea: Single purpose light mech

Its cheaper than a Ripley
Its faster than a ripley
Its specialized in that it only carries one equipment piece.
No internal air source, so mainly on-station use
Very limited storage

Why would you do such a thing:

Fast cable layer mech
Fast RCD mech
Fast but fragile xeno remover
Its like a segway but is actually useful
Has the potential to become VERY useful when dorf mode is finished

**Comment by 9600bauds** [comment]
So a janicart with a drill

**Comment by wiredhuman** [comment]
>Its like a segway but is actually useful
thats pretty much exactly what I said

also a drill would be the least useful thing on one of these

**Comment by 9600bauds** [comment]
You don't understand
I want janicart drill jousting now

**Comment by ComicIronic** [comment]
>No internal air source, so mainly on-station use

And so it's pretty useless.
What would be the niche of one of these things?
Moving in and out of mechs is a hassle. Moving around with a mech is a hassle. Having just one equip slot on a mech makes it totally not worth the hassle.

Hell, our current mechs are already never used because they're a lot of investment for a whole load of hoopla. And you want to add to that pile with more high-cost low-use mechs, but nerfed?

**Comment by wiredhuman** [comment]
Im talking low cost, fast mechs, that can be refitted but only have one equipment slot
and anyone who would use them in spess would have a hardsuit 24/7 on anyway, see engineering and mining

the niche of those things would be actually being affordable in counts more that 2 and providing functionality that an entire mech is simply not worth, like cable laying and transporting large volume machines like consoles

**Comment by ComicIronic** [comment]
But consoles can already be moved by simply unwrenching them.
Cable laying is also faster done simply by hand than by making a mech, equipping the mech, getting in the mech, walking the mech over to where you want to lay cable, laying cable in the mech, getting out of the mech, and never using the mech again.

**Comment by Killette2** [comment]
I'd like an exosuit which doesn't completely cover your body, but works as a robotic arms and legs. It deflects tasers like a janicart but if tased you fall out of it. It jogs at the speed of an odysseus and is commonly for civilian use. When you punch with it it will deal 10 damage instead of 5 and in exosuit fights you can either punch the exosuit, or it's user as the sprite does not protect them. It will need a unique set of attachments if any as it doesn't quite fit the mech catagory. Maybe a set of surgical tools installed for a doctor or a fire extinguisher for general usefulness. To do this you would have to print a surgical module attachment, fill the attachment with surgical tools, then attach it to the exosuit. For the fire extinguisher you can install a firefighter module which can be loaded with a firesuit to give you minor fire protection and an extinguisher, and a water tank. This type of mini-mech would be something good roboticist could provide for the station, and the user would be identifiable rather than hidden in the mech. There could even be things like chef modules with cooking tools and applications and hydroponic modules to install.
