### ISSUE TITLE
Disassembling the meat fridge does not remove it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32919]
(WEB REPORT BY: vampirebat74 REMOTE: 206.221.180.138:7777)
# Revision
169f18f49865b0efdfc15eeda1dc310b8e34f4db

# Description
Exactly what it says on the tin; the machine frame and components are removed but the meat fridge remains intact. This can be repeated infinitely.
# Steps to Reproduce
>Order a meat fridge from cargo, apply to venomat.
>screwdriver
>crowbar
# What you Expected
The meat fridge to be disassembled
# What Actually Happened
The meat fridge had babies

**Comment by jwhitak** [comment]
I'm at work right now, I'll have to see if I can reproduce it when I get home. To note, when testing, I made lines of these things and ripped them apart as described (in order to test mouse drop chance). How did you create the vendor, a new machine from scratch or did you put it on top of an existing vending machine?

**Comment by jwhitak** [comment]
![image](https://user-images.githubusercontent.com/69739118/179312244-c73d5bac-fde2-4643-8f3a-4308c4c4e238.png)
Can't reproduce.
