### ISSUE TITLE
Spacepod weapons give bad scary runtimes

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3293]
Neither tasers nor lasers work for spacepods. They can be installed properly, but clicking the "Fire Laser System" action gives the following runtime:

proc name: Fire Laser System (/obj/item/device/spacepod_equipment/weaponry/laser/proc/fire_weapon_system)
  source file: equipment.dm,113
runtime error: undefined proc or verb /obj/spacepod/civilian/fire weapons().

**Comment by Exxion** [comment]
OK I think I see the problem
Spacepods apparently remove their fire_weapons verb if they don't have weapons equipped. However, when you equip a weapon, rather than re-adding that proc, it adds fire_weapon_system, which relies on fire_weapons, which it removed earlier. (These issues are in spacepods/equipment.dm near the beginning and spacepods.dm around line 146.)

That's what it looks like, at least. I don't know that much about BYOND coding and I could be wrong, though.

**Comment by 9600bauds** [comment]
I think it's because it calls /obj/spacepod/civilian/fire weapons() rather than /obj/item/device/spacepod_equipment/weaponry/proc/fire_weapons() or something.

**Comment by Exxion** [comment]
I'm working on it. I've fixed the runtime error, but the pod still won't actually fire or play a firing sound. The fire_weapons proc must be getting called as it's now complaining if I click fire too quickly, but nothing else happens. I'll keep working on it tomorrow.
The problem with the runtime, by the way, was that fire_weapon_system called src.fire_weapons, but the way it was called, src was the pod itself.
I'll make a pull request if I can actually get the weapons to fire, but fixing a problem in favor of another one roughly equally-bad would be kind of useless.

**Comment by 9600bauds** [comment]
![ss 2015-03-04 at 08 49 09](https://cloud.githubusercontent.com/assets/6526157/6483052/6346b836-c24b-11e4-8979-b67eedb01879.png)
poooooooomf

**Comment by Exxion** [comment]
Don't worry, they were broken on so many more levels than that
SOMEONE moved the fire_weapons proc from the pod itself to the weapon system, which caused
1. Calling of a proc that didn't exist.
2. Once that was fixed, projectiles from the weapons were summoned into the nether world of the pod's own equipment_system. Sound was there, too.
3. Once THAT was fixed, projectiles would shoot in the direction of the weapon system rather than the pod itself. This was exclusively south.
