### ISSUE TITLE
Crate Forwarding disease creation kills the serb

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#32956]
#### Description of issue
[bugfix]

1. Enable crate forwarding
2. Centcomm decides to send some bacteria
3. It keeps being generated until the serb force-restarts

#### Specific information for locating

game.ss13.moe/logs/2022/07-July/22-Friday.log
[09:56:20]GAME: supply shuttle (/datum/shuttle/supply) moved to centcom loading bay
[09:56:21]DEBUG: CARGO FORWARDING: 1 crates forwarded.
[09:56:21]DEBUG: Creating and Randomizing Bacteria #8512-9290.
[09:56:21]DEBUG: Creating and Randomizing Bacteria #423-5815.
... [1787 more lines of Bacteria generation until Serb started restarting]

#### Length of time in which bug has been known to occur
This is the first time I've seen it

#### Server revision
f6218eb1e6bc6707bdbab261c2bbb6cfaf0a166a

**Comment by Kurfursten** [comment]
This is actually the makerandom proc for viruses. It's being called from the medical orders at L153 in orders_medical.dm -- you see, crate forwarding can send just random orders centcom requests. The loop is caused by the while loop one line ahead, it's randomizing until it can get a total badness of less than 13 with these args:
![image](https://user-images.githubusercontent.com/9782036/180584406-26c0e12e-f654-47b3-8fc0-b8fa6d07020e.png)

I am guessing that these args have a tough time creating a low badness virus? That does make sense given how hard it leans into negative effects
