### ISSUE TITLE
ED-209 Not Patrolling

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32995]
(WEB REPORT BY: knife28 REMOTE: 206.221.180.138:7777)
# Revision
f839452895187cdf64c2996df53002bbcb35f050

# Description
When setting autopatrol to on it toggles off after a second 
# Steps to Reproduce
Unlock ed-209, set autopatrol to on
# What you Expected
Autopatrol to stay on and ED-209 to patrol like beepsky
# What Actually Happened
Autopatrol toggles off automatically

**Comment by WindowsErrors** [comment]
i think all securitrons do that when they're aggrod

**Comment by ValkyrieSkies** [comment]
Fairly sure ALL bots are currently broken like this other than Beepsky.

**Comment by pedr69** [comment]
when beepsky/cheapsky see a criminal their patrol gets turned off, might be similar with ED

**Comment by WindowsErrors** [comment]
it's especially annoying when they see somebody, chase after them (without telling me, since beepsky only notifies people on arrest), the person they're chasing runs away, and then like 20 minutes later when there's somebody else going on a shooting spree or just emagged into atmospherics or something and I check my PDA so that I can see where they aren't at (if beepsky is in starboard hall then i know the person I'm looking for isn't there because beepsky would have attacked them if they were there) and then I see that beepsky is Idle in Port Forward Maintenance
