### ISSUE TITLE
Flashbangs sometimes pierce HoS hat protection

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#33055]
I've never seen this bug before, but I was stunned for about 5-10 seconds after throwing a flashbang 4-5 tiles away. Wearing the sunglasses and the standard hat. No flash or anything, but I was completely deafened. 
![bangerbros](https://user-images.githubusercontent.com/51391726/184771740-7aff9bf4-d5be-4598-96e5-c6e4ce6f8844.PNG)
Even checked to make sure I didn't get it thrown back at me, no clue how it happened.

**Comment by nervere** [comment]
I was able to replicate this locally, ~~but subsequent flashbangs didn't trigger the stun again.~~ I'm dumb, that's because I was deaf!
The HoS hat doesn't protect you because flashbangs check for NoiseDampening(), which is a proc that returns true for helmets. The HoS hat's path is `/obj/item/clothing/head/HoS`, so I'm not sure if it ever protected against flashbangs? I don't know if this is actually a bug unless I'm misunderstanding which hat you're talking about.

**Comment by BomberBro** [comment]
I was under the impression the HoS hat had flashbang protection, I'm gonna ask couple secmains if this was the case in the past or if I'm just retarded and I'll close it if it's the latter.

**Comment by Theophrastus1** [comment]
> I was under the impression the HoS hat had flashbang protection, I'm gonna ask couple secmains if this was the case in the past or if I'm just retarded and I'll close it if it's the latter.

fairly certain the only one that ever did was dermal patch. the Warden hat has flashbang protection to my knowledge but i am not as certain now

**Comment by pedr69** [comment]
why are there 3 different files with helmets anyway

**Comment by nervere** [comment]
@BomberBro I found the issue. Believe it or not, Cult 4 is partly to blame.

The issue is twofold. Firstly, this PR changed a lot of security gear to not be helmets two years ago (but it didn't matter because if the clothing covered ears it'd protect against flashbangs).
See this commit: https://github.com/vgstation-coders/vgstation13/commit/263c221db771e4516d81b6554b597c7dabf23c0d

Secondly, and more importantly, Cult 4 changed how flashbang protection works, and it didn't account for what it'd break: https://github.com/vgstation-coders/vgstation13/pull/30672

I'll switch the tags on this issue because you're right that they used to have flashbang protection and removal was never intended.

**Comment by BomberBro** [comment]
\>diety gives cult hoods flashbang immunity
\>removes it from the HoS and presumably Warden gear
can't make this shit up
