### ISSUE TITLE
Rad bug on box

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33098]
(WEB REPORT BY: dangitmaster REMOTE: 206.221.180.138:7777)
# Revision
56dcf439d0a85c6a1804faf0797a7e57d0fc27eb

# Description
When the radstorm kicks in on box, the rad storm is not shown in the bridge proper, and you will still die to radiation
# Steps to Reproduce
Radstorm
Try to survive on bridge being shown as safe
Die
# What you Expected
To not die
# What Actually Happened
Demon Core

**Comment by adacovsk** [comment]
I am not sure if I caused this, but whenever there's no power to an area, the emergency lights nor the rad lights flash. While not intentional, I don't think it's a bug if this is something new

I tested it, and the bridge definitely has rad lights

**Comment by nervere** [comment]
I tested Adacovsk's theory, the rad lights don't show up when an area has no power. This should probably be changed since the highlighted areas are meant to depicted what's being blasted with radiation, not necessarily warning lights from a room, but it's not a bug. This has been a thing for a while.

**Comment by Exxion** [comment]
Rad lights not appearing in unpowered areas is extremely old and was one of the big complaints with Deff back in the day

**Comment by nervere** [comment]
The people have spoken, this is a Feature™.
