### ISSUE TITLE
Chems don't mix on the test serb

### ISSUE THREAD

**Issue by DrLeprikon** [d3athrow/vgstation13#3315]
![image](https://cloud.githubusercontent.com/assets/10002997/6508563/a2f8776a-c36a-11e4-9c83-5817939064d0.png)

**Comment by Midaychi** [comment]
Chemicals combine, and you might need to heat chemicals to combine them now.
There's a bunch of legacy recipes that don't work anymore. Some because they use plasma instead of stable_plasma. Others are just bork. Most goonechem recipies require a specific temperature.
And for some reason putting a bluespace beaker into the chem heater causes the ui to bug out and be unusable.
Bunsen burners heat at an incredible slow rate if at all (left a beaker on one for ten minutes and it turned out to 185.925025609276 kelvin.. Reagent scanners don't tell you the temp.

**Comment by Midaychi** [comment]
Some of the above has been fixed on tg already, too.

**Comment by Iamgoofball** [comment]
I haven't touched legacy recipes though?

Mixing is working fine for me

**Comment by DrLeprikon** [comment]
Mixing works at first. It let me have 90u of a-tox, when I came back for the second helping it wouldn't mix anymore.

**Comment by ComicIronic** [comment]
What
test
serb

**Comment by DrLeprikon** [comment]
2soon
