### ISSUE TITLE
item stuck in cult construct's "hand"

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33258]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
37726685cc5aceb733efbeef1a9c4275bd5d53cc

was an artificer, and i helped click on a "resurrect" rune to revive a dead gultie
this caused a blood tesseract to appear in my "hand" slot, despite me not having hands, what with being a construct
couldn't use runes, altars, forges, click constructs to heal, etc because the thing was in my hand
admin had to delete the thing out of me before i could repair again

yvvel/(flash) has deleted the value the blood tesseract in the list /list, belonging to the datum Casey Nehling the Artificer of type /mob/living/simple_animal/construct/builder.

**Comment by nervere** [comment]
This is super weird. I happened to be the AI that round and was on the holopad. Whenever you talked, you had no name.
`Holopad received, chants, "Pasnar val'keriam usinar. Savrae ines amutan. Yam'toth remium il'tarat!"`

**Comment by nervere** [comment]
You had two runtime logs that round, but I'm not sure if either are related.
http://game.ss13.moe/logs/2022/runtime/2022-09-10-runtime.log

@pedr69 Do you recall the name of the cultist you were trying to revive?

**Comment by pedr69** [comment]
no, but the logs suggest it was lando

[21:11:17]SAY: Gallywix4/(Lando Watson) <span title='cultist'>(A)</span> (@303,234,1) Cult channel: artificer return to the rune
[21:11:24]SAY: Gallywix4/(Lando Watson) <span title='cultist'>(A)</span> (@304,234,1) Cult channel: i need you to bring me back to life

now that i think about it, it may not have been the ressurect that put the box in my hand
the resurrect revives the guy and equips him with some leather robes
i think it was me activating the "summon robes" rune while the newly resurrected guy was standing on it, since it equipped him with cult robes, and put the coffer with this old shit into my hand

**Comment by pedr69** [comment]
probably fixed by adding an ishuman() check here
https://github.com/vgstation-coders/vgstation13/blob/53931b6ea5c87275a858454b36f9fc3aaeccc6bd/code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm#L2054
else dropping the tesseract

**Comment by pedr69** [comment]
had similar happen to me as a zombie, and a way to fix it IC is by clicking on a table
