### ISSUE TITLE
Assistant sent back to lobby due to filled roles could immediately latejoin as one

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33266]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
eca36063df0c9af04779fc53c6e4861be01d4880

# Description
Someone readied up as an assistant was sent back to the lobby due to the roles being filled. Despite this, they could immediately latejoin as an assistant.

# What you Expected
Not to get sent back to the lobby when there was still an open slot.

**Comment by boy2mantwicethefam** [comment]
It likely means Dynamic bumped them off back into the lobby because something something antags. It's a potent meta-check against malf AIs too

**Comment by Theophrastus1** [comment]
NOOOOOO MY SECRET LATEJOIN STRAT

**Comment by nervere** [comment]
I'm not sure if there's any good way to fix this that won't in some way reveal meta information. Regardless of that, it's probably best that this gets changed so that people lifted from the station for one antag role or another don't take up that job slot.
Fixing this will end up touching roundstart procs though, so it's gonna suck no matter how you go about it.
