### ISSUE TITLE
AIs can delete charging defribrilators

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33388]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
22941ee7814aaeeae4ceddd348ed47c52fbf9966

# Description
Curious if I could eject defibs after they fully charged, doing this put said Defib into the ghost zone
# Steps to Reproduce
click defib in a charger as an AI
# What you Expected
just for the thing to pop out, nothing more
# What Actually Happened
it erased and I felt bad now there was one less Defib

**Comment by Eneocho** [comment]
Perhaps it was teleported to the AI core.

**Comment by Kurfursten** [comment]
It was not, it stays inside the charger but the sprite changes to empty and you can't get the defib out anymore. No runtime.

This is most likely because put_in_hands does nothing for an AI, and then it just sets charging to null so you can't get the defib anymore. Just needs a sanity check to prevent AIs from clicking.
