### ISSUE TITLE
[Discussion ] Accessibility of players blood types.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3346]
### Blood types

Currently, to find out what blood type a player is you must log in to a medical records computer, find their name and find their blood type within their record.  In my opinion, this is the only case a medical doctor will find themselves checking the record of a patient pre-treatment.  Using the players specific blood type when replenishing blood loss saves the limited supply of O- blood, which can be used to treat any patients blood issues.  

But this isn't often the case.  Instead, some medbay players like myself opt to use O- immediately instead of investing time to find the players blood type.  O- can be procured by bleeding medical staff with the blood type during lulls in the action and having a patient with severe blood loss is more common than minor blood loss, which leads to time sensitive action that favors O- instead of going to the medical computer and through the steps I wrote.  Time we just don't have that makes the difference between saying "Fuck this, he's getting cloned" and "WE HEAL".  

There is currently one other machine that can give you a blood type.  The surgical computer, which requires you to drag the patient over to surgery, lay them down and find out their blood type.  Again, this is quite out of the way when someone is bleeding to death in the lobby.  

### The meat and potatoes

Do we add blood type to health scanners information readout, or better yet, the body scanners?  Or do we keep it buried in medical records and surgery that encourages players to use O- instead of the blood type that fits the patient?  I think we should add blood type to the body scanners but I'm one player and lots of people approach medbay from different ways.

![capture](https://cloud.githubusercontent.com/assets/8550416/6543232/dfba5618-c4e2-11e4-98fd-782e3675b99f.JPG)

**Comment by xevonix** [comment]
I think you should be able to see bloodtype on the advanced scanners.
I play medbay pretty regularly and it does take a lot more time to hunt their name through your PDA than it would to slam them in the scanner and have a peep at it.
The time difference would definatly save someone from having to go straight to the cloners.

**Comment by ComicIronic** [comment]
You could just pull up their medical record using your MediHUD, though. The real issue is finding bloodtypes for people with no record at all, which is a bigger issue.

But yes, there definitely should be some way to do it with speed.

**Comment by Probe1** [comment]
man I knew I was going to forget some way, that doubt made me think to make a discussion instead of a flatout request.

I'm more set on body scanners having blood types now than before after considering unknowns without crew records.

**Comment by Midaychi** [comment]
What if: Players couldn't choose their blood type (it's randomized when you do certain things and doesn't show up on the char creation menu), and blood was species-specific (each species has its own range of types)? 

On top of that, different alien species have their own blood physics (example: Vox might have the ability to combine two blood types to get a third, because artificial species, and is super poisonous to other species because of its cyanide base)

Suddenly, Knowing blood types and having an established bank become super ultra important, and having it show up on medical scanners would be super handy.

**Comment by Probe1** [comment]
I've been saying Vox blood should contain hemocyanins instead of hemoglobins, which give horseshoe crabs in real life their distinctive blue colored blood.  It also is why said blood is worth $15,000 per liter.  I think that sells itself since Vox are genetically engineered food and it'd be a logical continuation to make their blue blood an extremely valuable pharmaceutical reagent.  

You could go the extra mile for Vox and make not iron, but copper the key to replenishing blood faster.  It would be a very slick touch of depth for medbay.

However that's all beyond what I had envisioned for this discussion and @Midaychi I still want to know what you think of adding the blood type to body scanners (the green sleepers)

http://en.wikipedia.org/wiki/Horseshoe_crab#Blood

**Comment by Midaychi** [comment]
Huh? I'd forgotten about vgs rediculous take on vox, and I was referring to zuhyrs original canon for them. (Though in that canon they don't have blood at all because vox primalis are basicallylly post singularity test tube babies with handy dandy blues pace connected electronic memory devices)

I don't see why scanners shouldn't show the blood type. Seems more like an oversight.

**Comment by Probe1** [comment]
Do me a solid and link the original canon, what I've learned is a mix of everyotherserver plus ours.  Our 'backstory' is kinda muddy.

**Comment by Probe1** [comment]
spring cleaning
