### ISSUE TITLE
[Balance] Add Wizard to any pop and consider other game modes

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3364]
Earlier with 8 people it was Traitor, Double Agent, or Extended.  Having the same mode twice (one with a twist) or extended isn't exactly Secret.  It's traitor or it's extended.  

The amount of murderboning a wizard could do to ruin lowpop is equal to the amount of murderboning a traitor would do in the same lowpop scenario.  Adding wizard to it would be an improvement for variety and making secret actually secret.  

I can't think of any other round types that would fit - Changeling and Vampire certainly not since it's just round approved killing everyone there and not really conducive to fun lowpop play.  There wouldn't be a reasonable force to fight lings and vamps anyways. 

The same thing could be said about the crew being unable to beat a wizard but it gives a good player the chance to run a fun gimmick as wizard that might be otherwise inaccessible because of legions of hungry validhunters, or not so good player a chance to play wizard in a situation without as much pressure.

If any other game modes seem suitable toss them in as well but I can't think of any.

**Comment by ComicIronic** [comment]
Issue is that you have to balance wizard for lowpop and highpop, which is impossible. Traitor increases the number of antags, but unless we get Ragin for highpop Wiz will either be over or under powered

**Comment by Hoshi-chan** [comment]
I second this.

You don't have to fudge with wizard to make it work for lowpop, because a wizzyman is just as good at slaughtering 40 people with ei nath, magic missile, and a car, as he is at slaughtering 10.

All this would do is speed up lowpop rounds on the chance you get a shitty wizard, or make them interesting when you get a fun one, same as traitor, same as any antag.

**Comment by ComicIronic** [comment]
Except that's untrue.  On lowpop, you're likely to have two sec officers, if that, and only one person capable of accessing the Armory normally, if there are any heads at all. All forms of weaponry against the Wiz are less accessible due to departments being understaffed,  along with murderboning and silicon subversion being easier due to lax security. 

On high pop, you have three heads with Armory access, people free to make EMPs and guns in chemistry and research, several borgs to protect the AI upload and loads more sec officers or armed staff. It's not comparable for balance.

And that's considering the cheapest option possible. Fun builds would be harder hit by balancing, since they would be unviable on highpop (bad) or impossible to fight on lowpop (not currently an issue).

Also, the car got nerfed.

**Comment by Probe1** [comment]
I'm doing some hand waving and ignoring your valid point, Comic.  It's based on the belief that during low pop (15 players or less) a syndicate uplink can be as deadly as a wizard built for murder.  The chance of an antag just killing EVERYONE in an unstoppable killing spree is the same.  

The justification for adding another mode is it keeps secret more realistic.  When the possible game types are traitor or extended, it isn't strictly secret at all.

I considered other solo antag types like ling and vamp but adding antags whos primary powersource is removing players from the round seems even worse than one that could be too much for the players to handle.

**Comment by Hoshi-chan** [comment]
Correction: on lowpop, you're likely to have NO sec officers. When's the last time you played? The server pop has decreased DRASTICALLY. Even in the afternoon on a weekend, I think I've seen maybe 40 players, tops.

Lowpop is most of the time now. Non-stop autotraitor is NOT fun. Tatorling is even less fun. Double agents shouldn't even be a game mode.

A wizard can be taken down by slipping or a syringe gun loaded with chloral, or a miner with pokemon, or a proto-kinetic accelerator, or a secborg, or R&D mass-producing guns.

You don't need security for jackshit. Lowpop protocol has always been, "Whoever gets to the captain's spare first is the captain," and most of the time either everyone learns all the wires for doors or whoever got the spare gives everyone all access. Stop underestimating lowpop.
