### ISSUE TITLE
Hot reagents don't scald people

### ISSUE THREAD

**Issue by Hinaichigo** [d3athrow/vgstation13#33668]
#### Description of issue
There's seemingly no mechanism for extremely hot liquids to scald people when splashed. One option is to just do an on-contact reaction thing that burns people based on temperature upon mob-reaction, similar to polyacid. Another is to have a "reagent coating/spatter" system like Dwarf Fortress has, and every Life() tick there could be thermal (and also chemical) interactions with the coated mob. Then you could also get wet people dripping onto the floor and stuff, which could be nice with puddles if they get implemented. A mob could have a single "covering" reagent datum, similar to how the blood/stomach reagents currently work, or they could have one per bodypart in the case of carbons. I'm curious to hear people's thoughts on this.

#### Steps to reproduce
Edit the temperature of the reagents in a container to thousands of degrees, then splash yourself with it.

**Comment by Kromkar** [comment]
splash code was fucked

**Comment by Eneocho** [comment]
And cryogenic liquids don't freeze you either. We don't have relevant temperature interactions with chems. Only for chem reactions, and even then it is very weakly used.
I'd definitely like to have more chem temperature interactions, chems that need cold to be made, a decent way to quickly cool down chemicals, effects for consuming chems at cryo or plasma temperatures, etc.

**Comment by pedr69** [comment]
if we were to add this, chem heating would probably need to be reworked too, so you couldn't get 1e40 kelvin temperatures with a single tap of the laserscalpel

**Comment by Eneocho** [comment]
For reference, you only get 4500K from using a laser scalpel. It doesn't go beyond that point by itself.

**Comment by Hinaichigo** [comment]
I've been considering how to implement this.
For now I think we can skip the reagent coating/spattering stuff as that's a system unto itself and anyway could be nicely compatible with this (by doing a touch reaction every Life() tick or something).
But there are several situations in which heat should transfer from reagents to a mob:

- Touch reaction.
- Ingest reaction.
- Whenever reagents are added to the mob eg. syringe, drinking, eating (It seems like currently, reagents added to a mob are set to the mob's body temperature).

And it probably *shouldn't* happen on metabolism, which I think we should keep to its strict meaning.

I'm also thinking that there's a few effects it could have. One is altering the body temperature of the mob itself. This should maybe scale negatively with mob size, and possibly be related to how thermally conductive the reagent mix is (but I don't think this is implemented for reagents). Another effect is causing immediate burn (or frostbite) damage.

**Comment by Eneocho** [comment]
You drink the -50°C or 200°C whatever, you get (frost) burnt to high hell on drinking, you get a heating/cooling tick (like with capsaicin/frostoil), afterwards the liquid is at the same temperature as your body, since you absorbed the heat.
One big thing you'll need to take into account is for heated medicines to NOT burn, or the pilling process cooling them down. Last you want is the chemist making some synthocarisol then killing the user with 4500K burns.
And code/map a way to quickly cool down chemicals roundstart. Sure, the chemfridge slowly cools down chems, but that's the issue. It is too slow.
The cryobeam RnD machine is a thing, but that's an advanced fuel-less cooling system. We need a weaker cooling system for roundstart, maybe a cooling bath that uses frost oil as fuel and starts with 100u?
Thermal conductivity is somewhat implemented with the specific heat mechanic, you need more or less energy to heat up your reagents. Try heating up some degen calcium or some water via bunsen. Degencalcium takes ages to heat while water heats real fast. You can just scale how much you burn by comparing the thermal conductivity to water's specific heat (4.184) or sacid (1.38, for ayys), such that > burns more, < burns less and = has no modifier.

**Comment by Hinaichigo** [comment]
> Last you want is the chemist making some synthocarisol then killing the user with 4500K burns.

For some reason I find that hilarious but good catch.

>cooling bath

I may not do that in the same PR, but that could be cool. Maybe there should be like a stockpile of ice somewhere like in the blood fridge or something (though the bar does have some available).

With the thermal conductivity thing I was thinking like, if someone put a 150 C sphere of gold in their mouth for 2 seconds, they might get worse burns than putting a 150 C sphere of rubber for 2 seconds. We could use the specific heat but I'm not sure it exactly corresponds (for ingesting, it definitely would correspond to a decent extent, but for skin contact/splashing), since the contact is limited in time and then the reagents drip to the floor or whatnot, maybe we could use like the siemens coefficient of the clothing covering the given body part?

**Comment by Eneocho** [comment]
I honestly forgot about the the siemens coefficient. I'd use it in tandem with heat capacity. Something like 
```
if(temperature > safe human temperature)
      damage = 0.01 * ((chem heatcap : water/sacid heat cap)*(0.3*siemenscoefficient))
```

Or some formula like that, such that low overheat causes minor damage but 4500K mixes fuck your shit up.
It would need tons of tweaking cause the siemens coef is exclusively balanced around electrical fuckery (as it should).
Alternatively, you could implement a secondary coefficient instead of the siemens, exclusively for thermal transfer calculations, such that you could have electrically isolating but thermally conductive clothing or vicecersa, this would require a LOT MORE tweaking, but would have tons of potential. There are materials that have high electric but low thermal conductivity, such as vanadium oxide and materials with low electric conductivity but high thermal one, like diamond.
It would fit ingame with composite clothing. An armor piece might have metalic plates on the outside but thermal padding on the inside such that it blocks bullets/lasers respectively, with the side effects of being electrically conductive and thermally isolated.

**Comment by Hinaichigo** [comment]
I might end up piggybacking the mob-body-heating onto metabolism, since it seems that's currently where the temperature equalization occurs, and maybe it's better (and/or simpler) to have it occur in one location rather than add it to every place where reagents get added to a mob. There could be some edge cases with that one reagent that blocks others from metabolizing, blockizine I think, but maybe that's not necessarily a bad thing.

**Comment by Eneocho** [comment]
Blockizine blocks other reagents from metabolizing by filling the user with 1000u of itself, which itself doesn't metabolize. This "stops" reagents from metabolizing in the sense that you don't have any space to get any more inside, it doesn't put other reagents on stasis. After 3000 worldtime ticks, blockizine qdels itself.

**Comment by Hinaichigo** [comment]
Oh, I see.
I'm thinking for the splashing, it should 'partly equalize' temperatures in the sense that only some of the energy should transfer, say like 20% of the difference, and that amount of energy should be related to the intensity of the burn.
