### ISSUE TITLE
Deep fryer oil is room temperature

### ISSUE THREAD

**Issue by Hinaichigo** [d3athrow/vgstation13#33667]
Deep fryer oil is room temperature. Ideally it would be scalding hot.

|oversight|

**Comment by Eneocho** [comment]
It's more an immersion deal than an oversight.
It would definitely have some uses to have it spawn scalding hot, even if it has no real effect on deep frying (in game). I could see chemists asking the chef for a beakerful of scalding hot corn oil to use as heat medium for fast autismo mixes instead of having to mess with the bunsen or ask ((science)) for a scalpel.

**Comment by Eneocho** [comment]
If you do plan on adding heated corn oil, consider giving it a specific heat value of 2.402 (average specific heat of corn oil between 40°C and 180°C) and a density of 0.9185.
