### ISSUE TITLE
box TEG chamber is vacuum roundstart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33799]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
bb3ecf3ac4f1fb2b3faa091acaac9099b0e0a547
you need to cycle some air into the chamber(or manually inject some fuel) before the script actually starts working
since it's a vacuum at a constant 20C until you add some gas to be cooled via the hot loop HE pipes

**Comment by nervere** [comment]
I'm looking at the TEG chambers on other maps, and all are a vacuum roundstart. It would seem it's part of the design.
If anything, this is an issue (?) with the scripting computer.

**Comment by kacurasuo** [comment]
easiest fix is to set the default script in the computer to begin injection at 250 instead of the current 300
alt fix would be to map in oxy floors for the teg chamber but I think that kinda sucks
you could also add a button that begins injection without fudging with the computer but I think that's the worst solution

or just git gud and remember that you have to begin the manual injection
