### ISSUE TITLE
[Feature Request] For removed implants to work when surgically reimplanted into someone.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#33829]
Imagine. It's revs, cargo was sabotaged so no extra implants. The seccie was brained so he's not coming back. You got a volunteer greyshirt to get implanted but you have none. 
In a hurry, you ask the brig medic to slice the dead seccie up, take the implant and surgically implant it on the greyshirt. 
It works. The volunteer is now loyalty implanted. You give him a gun and wish him best of luck. 
Eventually the revs catch up to you and in a bloody shootout you fall. Not dead, but close. You can hear some faint laser blasts, but you're too weak to open your eyes.
Dead silent. You feel someone shuffle you around. You wake up only to see the greyshirt bandaging your wounds.
Alive and recovering, you hand your ID to the greyshirt turned officer and tell him to call the shuttle.
He complies, the shuttle gets called. Feeling better, you give the greyshirt officer a medal and the highest commendations. 
Shuttle arrives, you leave with your trusted crew, in pain, but safe.
All because you could reimplant extracted implants.
[featurerequest]

**Comment by pedr69** [comment]
but they do.....
that is if you roll the 15%chance to not break the implant when removing it

**Comment by dinnerwoerror** [comment]
I think there's a pretty good reason why you can't reuse implants here and I can imagine why from back in the good old days when I was a sec main

For context on TG/bee and its derivatives there is a bag of surgery tools and an MMI in the execution room to expedite force borging (when the round is 45 minutes long tops you can't be dilly dallying by going all the way to the roboticist, you have to do it yourself); now me personally I never really liked force borging (and I still don't) so what I instead used the tools for was to [implant check the traitors for implant goodies](https://wiki.beestation13.com/w/index.php?title=Syndicate_Items&oldid=17147#Implants), if one was found it was a sure shot traitor detector and if I had an implant pad (easily available by just using a tracking implant on myself) I could even take the implant and use it for myself, my implant removal surgery record is still 14.41 seconds (Civil War surgeon tier) and my favorite one was the stealth implant because it allowed me to gangstalk people and I could get away with it because I was the head of security

Now I'm sure I ruined many people's rounds in the past like this but I did also reuse mindshield implants like this whole request is about, just remember that implants being reusable works both ways

**Comment by SonixApache** [comment]
#28708 ?

**Comment by Eneocho** [comment]
Well fuck, I've never seen 'em come out non-broken so I assumed it just wasn't a thing.
