### ISSUE TITLE
Pai unable to pick up people while in a mule

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33855]
(WEB REPORT BY: silent3 REMOTE: 206.221.180.138:7777)
# Revision
47f3f79da37e614437b1d77e133aa21348bcaa67

# Description
not able to pick up people while in a pai in a mule that has been hacked to accept unusual cargo
# Steps to Reproduce
be a pai in a hacked mule
# What you Expected
to pick up people
# What Actually Happened
nothing

**Comment by dinnerwoerror** [comment]
i think this is one of those ancient years-old limits that are unique to pAI mulebots in order to prevent people from just making their own tanks, although nowadays you can just control mulebots manually with the laser pointer so these limitations have been kind of obsoleted and powercrept

there's still other things you can attach to the pAI mulebot without problem (mainly because these things were added after the pAI mulebot limitations), such as a siege cannon, a rolly chair which a person can then sit on, or [a recharger with a pAI laser gun attached (please don't do this)](https://youtu.be/DHKxoARmjLU?t=67)

![image](https://user-images.githubusercontent.com/120611442/208330276-45676de7-91af-4557-9363-0b69f4e2a51c.png)
