### ISSUE TITLE
Security cameras completely messed up, lots of offsets, etc.

### ISSUE THREAD

**Issue by nervere** [d3athrow/vgstation13#33875]
#### Description of issue
Everything is offset on cameras. Many things are missing. All screenshots from Deff.
![image](https://user-images.githubusercontent.com/26285377/208799251-67bce4ef-ab93-4ef3-b328-25695b96c880.png)
![image](https://user-images.githubusercontent.com/26285377/208799286-725347ed-2901-4af9-8d1b-2f039c2318ec.png)
![image](https://user-images.githubusercontent.com/26285377/208799344-2aedaee1-c8c9-4069-bd44-a2b25be091ea.png)
![image](https://user-images.githubusercontent.com/26285377/208799394-25ae95e3-4fc0-40b4-b108-d891b3240979.png)

#### Length of time in which bug has been known to occur

Today. Possibly related: #33824 

#### Server revision

fe6613cf5950317a7085907a2c84e456a7ea13a5
<!-- SELF LABEL YOUR ISSUE TODAY!

**Comment by Exxion** [comment]
#33874 also mentioned lighting, but lighting looks normal here to me.
As for the cause, I suspect it's because the objects end up on plane 0 due to the camera using `PLATING_PLANE` as its base plane and `OBJECT_PLANE` plus that ends up on 0, but the camera console doesn't work on my machine, so I'll need someone to help test the fix.

**Comment by dinnerwoerror** [comment]
oh yea its been like that for a while, i've just autistically memorized the layout of everything on the station so that i can determine what does and doesn't belong there as the warden
