### ISSUE TITLE
Deep fryer removes all reagents from food

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3397]
![ss 2015-03-12 at 06 06 41](https://cloud.githubusercontent.com/assets/6526157/6628238/9f3ee08c-c8e2-11e4-817a-5714c05e1c93.png)
Pretty big deal, as it removes even the nutriment the food once contained.
Also deletes any items that you put inside the food, such as slipping a beaker inside a loaf of bread, and removes that food's ability to hold anything inside. Actually ANY unique food functionality like monkeycubes and popcorn is lost since it replaces the item with a generic "fried item" placeholder, this thing reeks of badcode.

Another smaller issue is that it replaces the description with "yummy" which, c'mon, you can do better. The grill leaves the original description intact, for reference.

**Comment by Cutelilduck** [comment]
Deep fryers used to be able to accept *any* item, hence the weird shitty code differing from the grill with the placeholders since it was converting non-food items. They were probably designed to "create funny times", but all it did was lead to Chefs griffing important items and afk Captains deep frying their ID and nuke disc and going braindead. Hence the hasty valid food item check in response, and a bunch of shitty item-destroying code.

Imo all that shit, cereal to grill to oven to deep fryer, should be removed. Cereal and Ovens to the exact same thing, destroying items and replacing them with static crap.

**Comment by 9600bauds** [comment]
>I don't like it so it should be removed!
No. The grill works almost perfectly fine. In the case of the oven and cerealmaker it makes perfect sense to replace the item with static stuff, just could use some sanitychecking.
