### ISSUE TITLE
waystation TEG issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34000]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
[waystation][way]
# Revision
8714a7d7e7fd0284d7867e46e00db69922f3fb46
the cold loop has the circulator pipe on the output side, instead of the input - as a result the power production is SHIT
the AAC script doesn't work right - it never disables the air injector, making the whole purpose of running the script to save fuel useless

there also aren't enough plasma cans to fill both the TEG pipes and the fuel mix, unless you use the secure storage but that might be intentional

**Comment by nervere** [comment]
@pedr69 What do I change here, I don't do engineering. Also, I'm not touching the AAC script.
![image](https://github.com/vgstation-coders/vgstation13/assets/26285377/fa796e16-54fd-4a3c-989d-d2b6b90107c7)

**Comment by pedr69** [comment]
cold side facing in
hot side doesn't really matter that much but from my testing facing out has slightly better power

![image](https://github.com/vgstation-coders/vgstation13/assets/18052467/6bdc8a51-1057-46ab-894a-e68463a54e6b)

it's not a dealbreaker, just subobtimal

**Comment by pedr69** [comment]
you may look at the TEG and see that it's still making power
but it actually isn't - the number on the TEG is the last produced powertick, which happens once every 20 seconds because the cold side almost never circulates
the actual power production is ZERO since you need consistent powerticks for machinery to accept power
![image](https://github.com/vgstation-coders/vgstation13/assets/18052467/ff5190f4-09ab-4d41-be5e-6665a26a1951)
