### ISSUE TITLE
Putting Mesons on top of your prescription glasses doesn't transfer the prescription effect to the mesons like it used to.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34119]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
d776b3a2fd4a8a847a9f52c9630af610d21c5635

# Description
Title.
# Steps to Reproduce
Start with nearsightedness.
Put mesons on top of your glasses.
# What you Expected
To see well and through walls.
# What Actually Happened
Got blindness overlay. @pedr69 [bugfix]

**Comment by pedr69** [comment]
i think it would be better if you could craft prescriptions and mesons together to make prescription mesons instead of the current "press E to do magic" which was very fucky even before the blindness PR

**Comment by Eneocho** [comment]
It's not magic though, it's a perfectly logical "slip the wall sight goggles on top of your tiny ass prescription glasses" kinda deal, like this picture I found in google:
![image](https://user-images.githubusercontent.com/67024428/220783142-6c492256-edc7-41b0-8821-6bc1dde18100.png)

**Comment by pedr69** [comment]
no i was thinking codewise
if you manage to code 2 items working in the same slot make a pr

**Comment by Eneocho** [comment]
We can reimplement the (bug) 10 cigarettes on the mouth slot thing, but with glasses.

**Comment by Exxion** [comment]
I think it mostly works for magboots, but that's because the properties of the shoes under them don't matter
The code to support overlaying mesons specifically is terrible, and will probably always be spaghetti even if it's fixed just because the codebase as a whole was not written with proper support for multiple items per slot in mind

I do think it can be made significantly less bad, but I bet there will always be some bugs with it

**Comment by Eneocho** [comment]
Best option would be to implement an attackby or similar on the prescriptions such that trying to wear mesons + glasses will make the mesons into prescription mesons, and an inhand to separate the prescription mesons into prescription glasses and regular mesons.

**Comment by pedr69** [comment]
that is exactly what i was thinking of
