### ISSUE TITLE
the deff QM office has a light switch but no lights

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34163]
(WEB REPORT BY: windowserrors REMOTE: 206.221.180.138:7777)
# Revision
c19080349e9fa02cd6cce1a6412013dd1e590c06

kinda funny tho so its not really an issue

**Comment by pedr69** [comment]
you ever wonder why the QM locker gets the fax key?
he doesnt have fax access

**Comment by ErrorsWindows** [comment]
> you ever wonder why the QM locker gets the fax key? he doesnt have fax access

Fax machines are originally a product of Baystation, the Quartermaster was responsible for the transit of all mail and cargo on the station and this wasn't just the typical "dumping your cargo crates in the tube", it was _all_ the mail and cargo, if someone got promoted/demoted and your subordinate's old office was getting cleaned out, the cargo workers were the one who cleaned out the office for you, so you had to show the cargo workers a list or a picture of what you didn't want them to steal, thus the need to send a telefax image to cargo...
About 2 months before /vg/ station was made, the Head Miner and the Quartermaster got merged together meaning that the new Quartermaster was responsible for the stuff the Head Miner was once responsible for, including all off-station expeditions, thus making them quite an important person and giving even more of a reason for them to have access to a fax machine, albeit only one instead of two considering how they're the same person now... I'm thinking the QM locker fax key is just a vestigial thing back when they actually had a fax machine and nobody bothered to take it out since locker space isn't really a big issue for the QM, unlike other heads like the HoS or CE... ever since /vg/ became a distinct branch, the Quartermaster never really had much to do, especially ever since Science started growing in power in 2014 and 2015, and nowadays they're pretty much (rather rightfully) made subordinate to the HoP who already has a fax machine so it wouldn't really make sense for the QM to have one now, that'd be like giving the Warden one...
To be fair if the QM got the fax machine back the only useful thing I could think of doing with it is faxing plasmeme porn to the head of security

sorry, I go on about history a lot

**Comment by Kurfursten** [comment]
Fax keys were actually added to head lockers much much later as IAA demotion keys weren't being used much. I'd tell you when, but our repo is DELISTED.

**Comment by pedr69** [comment]
>delisted

you mean the code search doesn't work anymore?

**Comment by Kurfursten** [comment]
Yes, we're deindexed meaning can't search keywords

**Comment by Exxion** [comment]
No we aren't. Go try it.
Search didn't work for a while, but I think that was actually a bug, not us being deindexed on purpose. For example, nixpkgs was also unsearchable.

EDIT: You may have to enable new code search in feature preview

**Comment by pedr69** [comment]
yeah, after i indexed my fork, i can search this one too
if it's still broken for you then probably one of the collabs should have vgstation be indexed so it works for everyone

when you're editing a file, press the "beta" button somewhere and the enable indexing is somewhere in there

**Comment by Kurfursten** [comment]
You were right. And here's the PR that gave QM (and real heads) the key -- just 2 years ago!

https://github.com/vgstation-coders/vgstation13/pull/28515

**Comment by ErrorsWindows** [comment]
> You were right. And here's the PR that gave QM (and real heads) the key -- just 2 years ago!
> 
> #28515

people pretending that the QM actually manages their department in a bureaucratic fashion instead of beating dissenters down to half health with an emergency toolbox and telling them that they're allowed back into cargo if they bring you the decapitated head of a security officer

**Comment by ErrorsWindows** [comment]
bro why am i being such a parrot todday im just talking out my ass
