### ISSUE TITLE
D20s no longer roll when thrown, kicked, exploded, etc

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34175]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
c19080349e9fa02cd6cce1a6412013dd1e590c06

# Description
haven't tested this on other die but the D20 can only be rolled now by using it in hand. my immulsions have been destroyed

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by jwhitak** [comment]
Issue is caused by #33830 adding in a new return to ``throw_impact`` and forgetting a !.

![image](https://user-images.githubusercontent.com/69739118/227690018-b42d667d-9faa-4c13-8090-42ea5e27a895.png)

Specifically here. The ``..()`` call returns 0 if there's no explosion. Therefore, the diceroll is only called if the dice explodes via the earlier type of explosion.

**Comment by jwhitak** [comment]
Calling @SECBATON-GRIFFON - come forth and claim your bugfix valids
