### ISSUE TITLE
Adding supermatter shard to derelict - discussion

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#3420]
A supermatter shard on derelict would allow mommies to learn how to setup supermatter without destroying up the main station, it would also provide more fun for players removed from the round.

Currently shards can be obtained from cargo for 200 a piece, for comparison a cheap lighter from a vendor costs 60. They can be spammed to hell and back, there's one available roundstart in storage.

This is to illustrate that it would in fact not increase the likelyhood of shard abuse for antagonistic activities and as such would not alter balance to any notable degree. The only thing it would do is provide more fun for derelict mommies.

I will most likely add this myself unless someone has some reasoning as to why it is a bad idea.

**Comment by AutismSpider** [comment]
Add TEG parts too.

Derelict has all the stuff for a burn room.

**Comment by Ephx1** [comment]
Just a question, doesn't a supermatter explosion affect all z-levels, as in, a nice dose of toxins and hallucinations?

**Comment by Probe1** [comment]
yes it will affect everyone.

also I think it's a stupid idea but i've already told you the reasons.

**Comment by Ephx1** [comment]
Yeah, unless a specific fix for Supermatter changes that, I don't think it would turn out too well.
Same goes for a singularity, it should really only be Solars/AME/TEG.

**Comment by TermedClepe** [comment]
I thought only the big shard variant affects everyone? I guess that's an issue in itself. Never experienced an off z level shard explosion so had no idea it affects all z levels.

TEG is fun too, I'll rather add that then.

**Comment by AnonymouxRex** [comment]
I imagine supermatter wouldn't be viable for the derelict (unless bussed in and monitored) until the radiation simulation is revised significantly.

**Comment by AutismSpider** [comment]
They affect all Z levels.

TEG and more solar parts is better.

**Comment by Probe1** [comment]
it would be hilarious though to be a miner and suddenly a fucking loose singularity eats you and half the roid.

**Comment by PJB3005** [comment]
I'm for this idea, I play derelict MoMMI a lot, but without making it not effect all Z levels, no.

if a derelict MoMMI fucks up and causes it to deliminate, the crew will probably not be able to stop it in time, getting to the derelict in the first place is hard, expecting it's a derelict MoMMI that's causing the issue is even harder.

TeG would be very fun however.

**Comment by dylanstrategie** [comment]
Economy will need a thorough rework at some point, so the cargo prices are a non-issue currently. We all know that anyone with access to the station account (which includes MoMMI) can fill the station with supplies in no time if they have the patience to pull all the supplies out of the shuttle

As for spawning a shard on the Derelict, meh. Usually station MoMMIs purchase one and teleport it to the Derelict, but the problem is that the Derelict MoMMI nest is almost exclusively a gimmick

**Comment by Intigracy** [comment]
Close please.

**Comment by clusterfack** [comment]
Why? Only 2/4 maps have one last I checked

**Comment by PJB3005** [comment]
2/4? Are you sure?

Deff has one but which is the other one?

**Comment by clusterfack** [comment]
I think Taxi copied Deff's derelict so it has one as well

**Comment by AutismSpider** [comment]
Deff and taxi have a shard box and meta do not

**Comment by PJB3005** [comment]
meta still doesn't have it.
