### ISSUE TITLE
Summon Server Crash Spell

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#34279]
**Step 1.**

Take arcane golem and pain mirror.

**Step 2.**

Invoke both, then smash yourself with a toolbox.

**Step 3.**

![wizardbreak](https://github.com/vgstation-coders/vgstation13/assets/51391726/092fcc06-9ddc-4200-a2af-bfbe421e958f)

**Comment by Eneocho** [comment]
I've done that specific combo before and it didn't crash.

**Comment by adacovsk** [comment]
Definitely seems like something that should be looked at since that could be an infinite feedback loop. I would look into it and maybe set a max reflection health at like 2000 damage and stop looping, but I don't have a computer right now

**Comment by Eneocho** [comment]
it ain't a loop as far as I can remember, it stops after like 10 cycles or something (or after the mirror spell stops).

**Comment by Exxion** [comment]
I can't reproduce a server crash. However, it can lag quite a lot if there are a lot of mobs around for pain mirror to damage. With three golems and myself standing in the middle of about 30 humans, the game froze for several seconds as all the nearby humans were converted to paste.
It's also just a ludicrously powerful combo, instantly gibbing everyone within range in a single hit.

**Comment by Exxion** [comment]
Oh man. It's not bouncing between the wizard and the golem. It's bouncing between the golem and *itself*.
There are two bugs causing this. First, `ignore_events` does not work on non-humans. Pain mirror passes this argument to `apply_damage()` to prevent exactly this from happening if two wizards both have the power active. Non-humans, such as arcane golems, ignore this argument and invoke their on damage events anyway.
Second, when pain mirror loops through `view()` to find targets to hit, it of course wants to skip the caster. It does this by skipping the spell's holder. However, arcane golems cast the owning wizard's own spells. When a golem with pain mirror active gets hit, it skips its *owner* as a valid target instead of skipping *itself*, so it can reflect the damage it just took to itself. Because of the first bug, this can continue indefinitely. In fact, I have no idea why it *doesn't* crash the server in my testing.

**Comment by DorainGrey** [comment]
Also See #29366
