### ISSUE TITLE
Unwrenchable Bridge Console

### ISSUE THREAD

**Issue by CorinJace** [d3athrow/vgstation13#34499]
#### Description of issue
Atmos console on bridge, northeast corner near the couch cannot be unwrenched. Literally the only console on bridge with this issue.

#### Difference between expected and actual behavior
Expected behavior: Should be able to unwrench
Actual behavor: Cannot unwrench

#### Steps to reproduce
Wrench in hand, click console, nanoUI screen appears instead of console being unwrenched.

#### Specific information for locating

Bridge, far right console near couch.

#### Server revision

Game: 0593a00132f3333fb530cdc471a43b237fe2eceb 
Patches: 45084ae38cc9f68891184351e906b395e62066f4

**Comment by pedr69** [comment]
not bridge specific, the central atmospherics console in atmos does this too
pretty sure because someone didnt put screwtoggle|crowdestroy|wrenchmove in here
https://github.com/vgstation-coders/vgstation13/blob/0593a00132f3333fb530cdc471a43b237fe2eceb/code/game/machinery/computer/atmos_control.dm#L21

**Comment by CorinJace** [comment]
Thanks for pointing that out. Hopefully we'll get someone on this. Minor issue really. No rush on it.
