### ISSUE TITLE
Runtime transformed into espeon before methylin was fully injected.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34505]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
0593a00132f3333fb530cdc471a43b237fe2eceb

# Description
Title.
# Steps to Reproduce
Get Runtime.
Get syringe with methylin (5u methylin and 5u fluorine in this case).
Inject Runtime with syringe.
# What you Expected
For the chems to be actually injected and THEN she transforms.
# What Actually Happened
She just smelled the methylin and became espeon.

**Comment by nervere** [comment]
It's actually intentional that the transformation is instant as dealing with a simple animal patrolling and trying to inject them is annoying. However, I didn't anticipate syringes trying to inject other reagents at the same time as the methylin injection happening, which is what happened here. Methylin thing happened, the methylin was instantly removed, and then the fluorine had its own action timer. I'll make a fix.
