### ISSUE TITLE
Railings dont hold simple mobs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34600]
(WEB REPORT BY: calzilla1 REMOTE: 206.221.180.138:7777)
# Revision
35673e3083f35c5db7d06548612a5dfbb776c9ab

# Description
Made some railings to hold cows and chickens but they just phazed through it
# Steps to Reproduce
>Build railings
>Put cow in fenced off area
>They walk right past it
# What you Expected
For a nice petting zoo
# What Actually Happened
Animal escape

**Comment by Exxion** [comment]
Did you specifically see a cow pass through the railings, or just chickens? I can't reproduce it with cows.
In the case of chickens, this seems to be... intentional? I mean, it probably isn't for animals in particular, but it's explicitly coded to allow anything that can move through a table to move through railings.
