### ISSUE TITLE
[suggestion] No spiders on the derelict.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#3462]
Know what sucks more than a carbon violating your station as a derelict MoMMI?

A spider smashing everything from the atmos tanks to the tables apart, BECAUSE YOU CAN'T DO JACK SHIT ABOUT IT.

I've had this happen, and I sometimes play derelict MoMMI from round start, this can REALLY fuck up your round.

**Comment by 9600bauds** [comment]
This happens when the spiders from the salvage ship get lured off rather than killed (since they are still the only non-asteroid space mobs). I don't know if a practical solution could be made other than coding the spiders there to not enter the Derelict's z-level a la nukedisk.

**Comment by Killette2** [comment]
That's the price you pay for being a non-human ;)

**Comment by ComicIronic** [comment]
I believe spiders can also happen as a random event.

**Comment by Rei1226** [comment]
Would be nice if spiders and carps were auto-deleted on this Z-Level, or something was coded in to prevent them from ever spawning on the Z-level. Technically MoMMi's (even derelict ones) are not allowed to kill the spiders or carps in accordance to their laws. I always let this slide though since it's kind of bullshit that they're not supposed to do anything except run away and let the spiders/carps destroy their creations.

Or we could just edit derelict MoMMi's laws to allow them to kill spiders and carps under their ion law. Could be a much simpler fix.

**Comment by Exxion** [comment]
Spiders start on the abandoned telecomms satellite on Meta, too, don't they? Not Box, just Meta.

**Comment by clusterfack** [comment]
I already made them unable to escape from the pirate ship itself, what more can you ask for

**Comment by gbasood** [comment]
I think this is over with, closing for now
