### ISSUE TITLE
Keycard Vault Entrance does not spawn.

### ISSUE THREAD

**Issue by DorainGrey** [d3athrow/vgstation13#34872]
#### Description of issue
The keycard vault introduced in #34292 does not work.
The three individual keycard locations spawn but when you go looking for the entrance it does not exist as it's never loaded.
See the following logs for evidence, god knows how many people have wasted time on this.

[02:22:20]ADMINWARN: <span class="admin"><span class="prefix">ADMIN LOG:</span> <span class="message"><span class='danger'>Can't find maps/randomvaults/keycard_entrance.dmm!</span></span></span>

This is an extremely annoying bug, as it's likely most people just assume they can't find the entrance after they gather the keycards.

#### Difference between expected and actual behavior
The keycard entrance to be there, so you can get your reward.

#### Steps to reproduce
N/A

#### Specific information for locating
Check logs for any  time keycard vault spawns.

#### Length of time in which bug has been known to occur
Since the features introduction, sceptical this was fully tested.

**Comment by pedr69** [comment]
good

**Comment by nervere** [comment]
Not sure why this vault isn't loading (haven't looked into it), but I can say the map file is actually in the game.
The error message:
`[02:22:20]ADMINWARN: ADMIN LOG: Can't find maps/randomvaults/keycard_entrance.dmm!`
... is extremely misleading, because it says that whenever it fails to load the map, whatever the reason may be.
