### ISSUE TITLE
Vox are no longer alerted to toxin damage from oxygen

### ISSUE THREAD

**Issue by falcon2346** [d3athrow/vgstation13#35078]
#### Description of issue
Vox are no longer alerted to when they're being poisoned by oxygen, aside from their health ticking down.

#### Difference between expected and actual behavior
Previously a little flashing green symbol would appear at the top right when breathing a toxin gas, this no longer appears to be the case.

#### Steps to reproduce
Be vox, try to take a deep breath of some oxygen.

#### Length of time in which bug has been known to occur
Since the recent changes to vox lungs that made plasma toxic to them.

**Comment by ghost** [comment]
What's happening is two calls to the [/datum/lung_gas/toxic/handle_inhale](https://github.com/vgstation-coders/vgstation13/blob/7e1d1d7d4f83545f664e08bfbe36462bb6c39b29/code/modules/organs/internal/lungs/lung_gasses.dm#L145C1-L167C21) proc are made nearly simultaneously with each breath, the first for oxygen, the second for plasma.

The first properly sets the `H.toxins_alert` property to 1. However, since the air does not contain plasma, due to the
```dm
else
     H.toxins_alert = 0
```
line in the whole proc:
```dm
/datum/lung_gas/toxic/handle_inhale()
	..()
	var/pp = get_pp()
	var/mob/living/carbon/human/H=lungs.owner
	if(pp > max_pp && !(H.species.flags & PLASMA_IMMUNE)) // Too much toxins
		//testing("TOXIC: gasid=[id];pp=[pp]")
		var/ratio = (pp/max_pp) * reagent_mult // WAS: (moles/max_moles) * 10
		//adjustToxLoss(clamp(ratio, MIN_PLASMA_DAMAGE, MAX_PLASMA_DAMAGE))	//Limit amount of damage toxin exposure can do per second
		if(max_pp_mask)
			if(H.wear_mask)
				if(H.wear_mask.clothing_flags & BLOCK_GAS_SMOKE_EFFECT)
					if(pp > max_pp_mask)
						ratio = (pp/max_pp_mask) * reagent_mult
					else
						ratio = 0
		if(ratio)
			if(H.reagents)
				// H.reagents.add_reagent(PLASMA, clamp(ratio, MIN_PLASMA_DAMAGE, MAX_PLASMA_DAMAGE))
				// no this is bad n3x pls no
				H.adjustToxLoss(clamp(ratio, MIN_PLASMA_DAMAGE, MAX_PLASMA_DAMAGE))
			H.toxins_alert = max(H.toxins_alert, 1)
	else
		H.toxins_alert = 0
```
the second immediately disables the alert.

The code here is sort of written with the expectation of one toxic gas, so we'll have to think of a good new way to set the `H.toxins_alert` property.
