### ISSUE TITLE
Brain installation surgery doesn't need to be completed to work

### ISSUE THREAD

**Issue by Inorien** [d3athrow/vgstation13#35091]
#### Description of issue

I just watched a man plop a brain he found in an MMI into a monkey man's skull and sealed him up without fixovein and the guy was alive

#### Difference between expected and actual behavior

The guy should not have been alive

#### Steps to reproduce

>have roundstart borg (probably not required, this is what I saw in round)
>obtain monkeyman, debrained, fresh
>rip the brain out of the borg's MMI and just drop it in the guy's skull without fixoveining the brain in
>glue his skull back together
>defib
>he lives

![image](https://github.com/vgstation-coders/vgstation13/assets/16082007/b4e4d0f1-2296-4101-bf6a-a4aeef3ea3d6)

#### Specific information for locating

Brain surgery

#### Length of time in which bug has been known to occur

No idea, probably forever

#### Server revision
f40bd5f75074f0e6b9d2631a138a9d7ba6fc1884 

[oversight]

**Comment by pedr69** [comment]
doesn't this also give the spaceman complete pain resist?

**Comment by ghost** [comment]
I think it should cause brain damage and ultimately fatal blood loss.

**Comment by Inorien** [comment]
> I think it should cause brain damage and ultimately fatal blood loss.

it just shouldn't allow the defib to proceed, if the brain is severed then the show is over

**Comment by Eneocho** [comment]
Intended as per #29435. The issue was that you felt pain when getting your brain surgerized (it has no pain receptors so you shouldn't feel any pain), but the "fix" was to make it so incomplete brain installs just make you immune to pain.

**Comment by Inorien** [comment]
weird, thanks for linking that

i have never ever seen someone powergame this to become pain-immune, really think we need a better solution but christ I don't wanna touch it

@jwhitak you like med code right

**Comment by Eneocho** [comment]
In the end nobody powergamed it, mainly cause it's really obscure and you wouldn't really know about it, even if lurking the wiki/code. Even long-standing medical players seem to be unaware of this mechanic, despite several of them being incredibly autistic about medical.
Another reason it isn't powergamed is that it is one of the rare powergaming features that would require someone else to do (cause you can't do self surgery), so it is never done. It definitely would pay off in long-standing fights and the like. You'd be the eternal champion in holodeck fights, as you'd be immune to holodamage pain.
As a sidenote, my original issue was that your character screamed when getting their brain sliced/diced, which shouldn't happen, cause the brain itself doesn't have pain receptors, but the "fix" somehow warped into making it so incomplete brain transplants make you painless, rather than skipping the no-painkillers surgery scream when slicing the brain.
