### ISSUE TITLE
creating a caramel pill causes a temperature increase in the room to 100 degrees celsius and causes like 60 damage upon eating

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35107]
(WEB REPORT BY: wotisjanitor REMOTE: 206.221.180.138:7777)
# Revision
f40bd5f75074f0e6b9d2631a138a9d7ba6fc1884

# Description
creating a caramel pill causes a temperature increase in the room to 100 degrees celsius and causes like 60 damage upon eating 
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by falcon2346** [comment]
This only happens if you use the create single pill function. If you use the create multiple pills function the resultant pill will always be at 20 C, although the room will still heat up.

**Comment by Hinaichigo** [comment]
Fixed in #34855 as it makes the pill-temperature equalization stuff not affect the air by default. And that should also help with the caramel being so hot as it will cool down gradually (rapidly if it's an extreme temperature) once you take it off the heat source.
Was it a pill made by laser scalpel?
And it doesn't actually cause 60 damage for a single hot pill swallow; pain causes hallucinated damage so you look more damaged than you physically are.

**Comment by Dacendeth** [comment]
>code shitty bugged pill thing
>merge fix into pr half the server doesnt want.

Cool hina, very cool.

**Comment by Hinaichigo** [comment]
My impression is that a lot of the downvotes there are holdovers from when it affected the air temperature and people were concerned about laser scalpels nuking the air, which's been addressed.
I added the 'fix' to that because it also introduces the toggle switch admin panel stuff for reagents heating up the air, so it's natural to have the pill stuff be toggled along with that.
The pill stuff itself was added to avoid people burning their lips on hot pills.
There's a lot of moving parts that, taken together I think will add positively to the game. However they have to be teased apart and done in a semi-atomic way that wont break anything or lead to massive backlash when a bug gets through that causes people to align themselves against these new sandbox features carte blanche.
And at the risk of encouraging people to do it more for fun, I must say that spite-downvoting the final key to the puzzle is... not an optimistic position on the potential to expand the sandbox.

**Comment by Eneocho** [comment]
A solution would be closing and remaking the PR. You'd get rid of the holdovers that haven't checked anymore, and those that genuinely do not want it to be a thing would notice and downvote again.

**Comment by wotisjanitor** [comment]
> And it doesn't actually cause 60 damage for a single hot pill swallow; pain causes hallucinated damage so you look more damaged than you physically are.

My face literally melted off

**Comment by wotisjanitor** [comment]
[00:35:58]SAY: Unknown (as Magicland Tokyo)/Wotisjanitor (@303,229,1) As Galactic Common :  My face melted off

**Comment by Eneocho** [comment]
the c*der menace...
