### ISSUE TITLE
Wheelstation Engineering Issues

### ISSUE THREAD

**Issue by DorainGrey** [d3athrow/vgstation13#35347]
- Two Pacmans in Secure Storage, no plasma for them.
- All the rad collectors in secure storage are duplicated, so there's like 8 on a tile
- Technical storage contains like 5 security camera boards for some reason
- CE office contains regular RCD not advanced RCD
- Engineering bathroom door, has no access set on it.
- Singularity only has one entrance to space, not sure how you are supposed to check on the emitters when the field is on.
- AME is probably too small for a station it's size, especially considering the Supermatter takes a lot longer to setup on this station.
- There's a shard ejection button, put on the same table as the shutters & door buttons and it's very hard to tell which is which & easy to misclick
- Bridge shutters don't cover captains window in bathroom.

**Comment by brndd** [comment]
> Two Pacmans in Secure Storage, no plasma for them.

The plasma's on top of the PACMAN in the SMES room, but I'm moving it to a table in the main engineering control room.

> All the rad collectors in secure storage are duplicated, so there's like 8 on a tile

There should only be 4 per tile, which was the number you get in a rad collector crate from cargo at the time. Looks like you only get 3 now, so I'm deleting one from each tile. AND removing two of the crates because 18 is probably more than anyone could ever need.

> Technical storage contains like 5 security camera boards for some reason

There were 3 (to replace missing advanced security camera boards), but I've pared that down to 2.

> There's a shard ejection button, put on the same table as the shutters & door buttons and it's very hard to tell which is which & easy to misclick

This is deliberate, because lol janky NanoTrasen design with no concern for anyone's safety. But let me know if you think it's genuinely so annoying that I should find a different place for the emergency vent.

> Bridge shutters don't cover captains window in bathroom.

This one is definitely deliberate. The captain's room has its own privacy shutter for that window.

**Comment by DorainGrey** [comment]
> This is deliberate, because lol janky NanoTrasen design with no concern for anyone's safety. But let me know if you think it's genuinely so annoying that I should find a different place for the emergency vent.
Really? 

Just fix it so people don't vent the Engine every two minutes.

Why did you ignore half the issues in this issue? The ones that actually matter and impact gameplay quite a lot.

- CE office contains regular RCD not advanced RCD
- Engineering bathroom door, has no access set on it.
- Singularity only has one entrance to space, not sure how you are supposed to check on the emitters when the field is on.
- AME is small compared to station power & engine setup requirements

**Comment by DorainGrey** [comment]
> There were 3 (to replace missing advanced security camera boards), but I've pared that down to 2.

Also not a big deal but why?
Tech storage really should just be 1:1 with every map, so people can know what's in there and what's missing.

**Comment by Kurfursten** [comment]
I'll reopen this since you raise a good point, although I should say engie bathroom doors might normally not have a requirement? I think Roid Eng Baths might not...

And it's okay for the AME to be lackluster in size, that's its thing.

**Comment by DorainGrey** [comment]
It's more about the AME being the only viable Engine for quick setup. 
Since the shard takes a decent bit longer & there's no TEG.
So it's that or the SInglo which really suffers from the lack of doors & just being the singlo.

I think it's worth having another layer like the ROID AME, though I'm not attached to the idea. Didn't really get a full look at the station average draw due to early nukies yesterday.

**Comment by brndd** [comment]
I added the RCD in, just forgot to mention it. I was unconvinced about the bathroom door initially, but you made a fair point about it on Discord so I'll change it in the next set of changes. Ditto for the camera boards.

The default shard setup takes less than 5 minutes with the steps in the brown guidebook. Of course if you want big numbers there's more prep time involved. I don't love the idea of making the roundstart AME bigger.

As for the singularity, you can just use the singularity monitoring console. I did it this way because the layout of the AME room and its surroundings was nicer without having to fit in a second singularity airlock, but on second look it doesn't change much to fit another singulo airlock. I didn't do it because I didn't think it's necessary, but I guess there's no reason not to.

**Comment by brndd** [comment]
#35349 should fix all the remaining ones except giving more AME parts. I forgot to update the changelog again but whatever.

**Comment by pedr69** [comment]
i think the bathrooms wouldnt be a problem if they didnt also have a maint entrance

**Comment by Kurfursten** [comment]
Seems fine to have an undersized AME

**Comment by DorainGrey** [comment]
Thanks for fixing these.
