### ISSUE TITLE
NRV Horizon TEG hot loop Void

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35501]
(WEB REPORT BY: superflybox REMOTE: 209.222.101.3:7777)
# Revision
cd3fa45fc8c586d26c5c67fb409bd2b07e9d3e36

# Description
The hot loop on horizon is non-functional.
Attempting to add gas to it is unsuccessful without directly attaching an existing gas pipe network directly, which also did not fix the issue of the hot loop behavior (gas does not flow inside the loop when pumped meaning zero flow in the TEG itself on the one side.)  Attempts to use the default gas pump and later a volume pump to fill the loop were unsuccessful.
# What you Expected
functioning gas circulation in the TEG loops
# What Actually Happened
one side is terminally stuck making the engine by default broken.

**Comment by content-to-remain-anonymous** [comment]
here are the issues i've found
![image](https://github.com/vgstation-coders/vgstation13/assets/151869497/f8faf153-5d13-45fa-b6e6-b77bad8191ce)
1- pipe-HEpipe transitions without a junction(technically halal, see #32019)
2- pipe endcap instead of T-junction
3- airlock doesn't cycle due to pipe layering being wrong - just put the vent on layer 2 without adapters
![image](https://github.com/vgstation-coders/vgstation13/assets/151869497/00a1be2b-df6b-4f06-ab4d-4c601053ea18)
4- cold loop has garbage pressure - the pump needs to be before the input, not after the output(also see #34000, it still makes power despite not circulating due to the TEG bug)
5- no gas sensor inside chamber
6- HE pipes and normal pipes sharing layer and direction(this makes nerve gas and runtimes when you try to pump gas into the hot loop, then also supercools it somehow)
7- pipes under walls bad - if you absolutely have to do this, use the visible variants instead of underfloor

also consider adding floor markings
