### ISSUE TITLE
NRV Horizon Map Issues

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#35543]
I was told to make a post about this, so here.

The virology airlock controls are mounted on the wall of the adjacent room with their icon offset down to look as though they're actually in virology. You cannot open the airlocks from within virology because of this, and it's something you wouldn't realize from an observer view.

Multiple maintenance doors are open to anyone with maintenance access, the ones I saw were the chapel morgue and the IAA office, you can get into the departments through the maint access door as long as you have maint access, without needing the access associated with the department itself.

The library is fucking ugly as sin.
There's 2 research database things and 1 book binder and the scanner is across the room from the computer itself. There's a table in the south wall of the library with stamps and folders on it, but it's completely inaccessible because of the arcade cabinet on the south side and the vending machine on the north, this also means that the library itself isn't airtight.

![image](https://github.com/vgstation-coders/vgstation13/assets/9064611/ad642e91-ba26-43ce-accb-cba46a5cbf2c)

I didn't get a good picture of the viro airlock control, and I can't go grab one from the map on ss13.moe, because that one is super out of date.

**Comment by DorainGrey** [comment]
The morgue maint door is deliberate, to allow pass through.

The library though, I don't know what you want me to do about that, people keep stuffing in separate machines into the library with their PR's and this is the natural result. 
This is more a reflection of the fact, Horizon is the only map with all the machines, most of the maps have a mix because they haven't been updated yet. 
I'm open to suggestions but there's limited space and it being "Ugly" doesn't give me much to go on here.

Fixed in PR:
The table was a veerism though gonna remove that now.

IAA airlock, I couldn't find any others that require only maint, certainly none without department access. Can you elaborate?

Fix for Viro Airlocks that somehow got lost in git.

**Comment by NigglyWiggly** [comment]
The library doesn't need two of the same machines, though!
Also in terms of 'ugly' I'd get rid of the pulpit, or at least replace the metal chairs with wood ones. Maybe replace the research thing at the bottom right with a normal book binder, and put the scanner where the book binder was.

If the IAA airlock is the only one with that maint access that's fine, I saw that one and the morgue and was unsure if there would be more.
