### ISSUE TITLE
Reagent innate affect on mob temperature is broken

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#35586]
chemistry-reagents.dm
L6230-6233

Stops heating or cooling when you reach healthy temperature, so for example cool drinks like sodas won't cool you past healthy body temperature, blisterol won't warm you up past healthy temperature (which it is supposed to)
Some of this might be irrelevant now that we have reagent heating - just make sodas come out of the machine cold?

worse, because the reagent *sets* your temperature to healthy body temp, if you are colder than healthy body temp and drink a cold drink, it will set your heat back to healthy warmth, meaning you can spacewalk with a cold drink!

**Comment by DeityLink** [comment]
This is an old issue, and incidentally the Thermal Entropy Update (the feature one specifically) actually fixes it by reworking the way adj_temp affects the bodytemperature changes (and carefully adjusting all the values so you can't get hypothermia from sodas or heatstrokes from coffee, while still allowing drinks with extreme adj_temp values to harm you)

It also makes it so that heating or cooling reagents that don't have a preset adj_temp will heat/cool you, although while keeping you in healthy temperatures unless you drink very cold liquids.

It's less a bug fix and more of a rework+balancing hence why I didn't shave it off the PR.

**Comment by GreatBigFailure** [comment]
It sounds specific to drinks, I know hell ramen works as intended for example. Same with Frost oil.

**Comment by Kurfursten** [comment]
This turned out to be a fucking myth!

**Comment by DeityLink** [comment]
Hell Ramen work fine because they don't rely on adj_temp, and instead directly increase body temperature on mob life.

**Comment by Kurfursten** [comment]
All of these work fine, I just tested it on live. It was a total myth.
