### ISSUE TITLE
Discussion: Should we remove Trader "flight in" on latejoin?

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#35596]
I had a couple people say this was preventing them from playing the role. I always thought it was charming, but maybe it's too hard for most players? In my personal experience I had no trouble getting there.

Maybe a compromise to give players a personal airbag + pinpointer to outpost? Or better to just be rid of it entirely?

**Comment by Dacendeth** [comment]
An airbag and some sort of holomap or pinpointer would solve everything, maybe a jetpack? It sucks to join as a mushroom trader because hitting a rock can break a bone from the brute multi they have.

**Comment by jwhitak** [comment]
I died as a latejoin mush trader from that impact the first time I tried out trader. Skill issue, but it stopped me from playing the role for a while. So, yes. Remove throwing people in.

**Comment by GreatBigFailure** [comment]
What is gained from having it? It's just silly. Like what if secoffs spawned in perma and had to break out to play their role. Have them spawn on the outpost.

**Comment by falcon2346** [comment]
I think the airbag/pinpointer option is perfect, honestly. The biggest problem is that if you don't know the layout of the roid you get fucked if it's a map that puts you far from the outpost. Having more direction would help a lot.

**Comment by west3436** [comment]
Spawning them on the trader shuttle is most in-line with the way the crew is spawned in.

**Comment by GreatBigFailure** [comment]
> Spawning them on the trader shuttle is most in-line with the way the crew is spawned in.

This, I just don't understand the need to compromise something between what currently happens, and just sort of being able to play normally. Like why is Trader different in this sense?

**Comment by DeityLink** [comment]
+1 for Airbag because I suggested it

**Comment by kilozombie** [comment]
I like the airbag and pinpointer idea, but I still prefer the idea of just porting them onto the trader outpost (*not* the trade shuttle, because that one might be in use or depressurized, and it's an O2 environment anyway). Put them in the bedroom where the spawns normally are, it won't break immersion too much.

Trader is a role that already has a million disadvantages if you latejoin--you're late to the party, you're late to setting up your goods, your outpost is probably vented and looted, the round is going to end sooner than usual, et cetera. No need to add literally any extra complications.

**Comment by west3436** [comment]
> I like the airbag and pinpointer idea, but I still prefer the idea of just porting them onto the trader outpost (_not_ the trade shuttle, because that one might be in use or depressurized, and it's an O2 environment anyway). Put them in the bedroom where the spawns normally are, it won't break immersion too much.
> 
> Trader is a role that already has a million disadvantages if you latejoin--you're late to the party, you're late to setting up your goods, your outpost is probably vented and looted, the round is going to end sooner than usual, et cetera. No need to add literally any extra complications.

There's zero reason to spawn them in a bedroom rather than their own shuttle. The arrivals shuttle can also be breached. With this logic you may as well spawn all jobs right in their departments because the arrivals shuttle could be damaged.

**Comment by Kurfursten** [comment]
The reason we don't spawn people in departments is because
1) It's bad for immersion to see someone pop into existence. We want them to spawn somewhere low traffic (the arrivals shuttle is this).
2) Having people spawn on the arrivals shuttle makes spawncamping much more policeable. Antags have zero reason to focus their efforts on the arrivals shuttle, but they could have a good reason to attack chemistry or genetics or the brig. If a chemist appears out of thin air right when you are knocking out a victim in chemistry, that's bad for both the new chemist and the antag trying to be quiet.

The Vox dorm is also very low traffic so it would be "okay" to spawn them there, although migrating in from space is not super different from the walk a new secoff makes from arrivals to the brig for example.

**Comment by kilozombie** [comment]
> There's zero reason to spawn them in a bedroom rather than their own shuttle. The arrivals shuttle can also be breached. With this logic you may as well spawn all jobs right in their departments because the arrivals shuttle could be damaged.

This is a really bad argument. The arrivals shuttle doesn't move and is one of the least-trafficked areas on the station; the trader shuttle might be in one of two places, might have people in it actively doing business, might be breached by bad actors or by a gunfight since it's a highly-trafficked spaceship. The types of shuttles aren't even close. The trade shuttle is used for trade, the arrivals shuttle is used for arriving.

**Comment by DeityLink** [comment]
I think the fly-in is both funny and soulful. Add to that an air airbag in their hand, and a pinpointer in their pocket that tracks a remote beacon set at the vox outpost to help with asteroids that don't have a straight line of sight from the outpost to the map border, and the problem's solved.

**Comment by Optimism333** [comment]
The fly-in is an odd choice, design-wise. Not least of which, because it doesn't always work. I've seen on at least one or two occasions, a trader not get flung towards the outpost properly, and just get stuck in deep space. It just seems simpler and more convenient to have late traders spawn in their dorm.

**Comment by Kurfursten** [comment]
It never happens that a trader won't get flung toward the outpost. As one of the top traders by rounds played and a frequent latejoiner, I definitely would have seen it. There are a couple situations that can confuse someone though:
* If you have bad directional sense and DON'T continue the way you were flying after hitting asteroid, you can end up wandering into space
* If you randomly flew into a vault you could feel you aren't on the asteroid Z level

I do think these are solved with the pinpointer
