### ISSUE TITLE
Can examine reagents inside open containers from any distance

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3569]
By examining open containers (beakers, spray bottles, bottles etc) you can see precisely what's in them, even from 10 tiles away.
Besides being a bit silly, apparently this hasn't always been the case, so I'm opening an issue on it.
![ss 2015-03-25 at 12 50 15](https://cloud.githubusercontent.com/assets/6526157/6818137/3e7807a0-d289-11e4-8c35-9da35a104090.png)

**Comment by dylanstrategie** [comment]
Pretty sure this is due to the way Examine() works. If you can see it, you can examine it

**Comment by 9600bauds** [comment]
Yeah, it's directly part of Examine(). Most people seemed to think you shouldn't be able to do this though, which is why I'm bringing it up.
Maybe adding an Adjacent() check?

**Comment by ComicIronic** [comment]
I'm not so happy it exists at all. What kind of person can see chemicals in a mixture?

**Comment by clusterfack** [comment]
It was centralized during the massive examine overhaul because reasons. I have an idea about how to fix it up, here it is:

Allow greater usage of is_open_container as a function of determining what you can see/do to an open container. I suggest a scale such as described below but this is for discussion

null - Cannot have reagents added to it
Any integer value can have reagents added to it
1 - Advanced mass spectrometer can identify chems within. Label it with something like ADVSCAN
2 - Space left open for future additions.
3 - Mass spectrometer can identify chems within, SCAN
4 - Space left open for future additions.
5 - Reagent scanner pda app can identify chems within, examine doesn't display, OPAQUE
6 - Space left open for future additions.
7 - Can be recognized by the naked eye using examine, while adjacent only, TRANSLUCENT
8 - Space left open for future additions.
9 - Visible to the naked eye using examine, from any distance, TRANSPARENT

So for example, janicart's contents would be 7. 
Food contents would be 3. 
Blood contents would be 1 or 3
Beaker would be 7 or 9

That way the basic functionality of is_open_container is maintained through if statements, and it has greater functionality for examine and potentially other purposes

**Comment by ComicIronic** [comment]
>left open for future additions

This wouldn't be necessary with a define system, but that might be a good idea.

**Comment by clusterfack** [comment]
Also fixes a bug where you can just hit a person with a chemistry reagent scanner and see what is inside of them instead of needing a mass spectrometer. And perhaps in the future we could add some kind of reagent identifier levels so that they can only be identified under one of these circumstances.

**Comment by d3athrow** [comment]
>I'm not so happy it exists at all. What kind of person can see chemicals in a mixture? 

@ComicIronic Bay tried to remove the ability but due to the playerbase and playstyle I reverted that specific change in favor of gameplay rather than realism. I'll add a distance limit though.

**Comment by Probe1** [comment]
it somewhat exists with beakers, if a lid is on you cannot see the mix.
