### ISSUE TITLE
Open containers splash onto SmartFridges, yet get loaded anyways

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3581]
When you try to stuff that Dexalin Plus bottle into the SmartFridge but forget to put the lid on, two things happen:
+ You splash the bottle all over the fridge like a dumbass.
+ The bottle is loaded into the fridge anyways.

The end result is a now-empty bottle, labeled Dexalin Plus bottle, inside the fridge.
It should either load the bottle without splashing, or splash the bottle but keep it in your hand.

**Comment by ComicIronic** [comment]
Caused by not returning 1.

**Comment by Probe1** [comment]
Did you try putting a lid on the bottle? Alternatively load it with a smartpill collector assuming there's also a pill on the same tile it will scoop up the bottles too.

**Comment by dylanstrategie** [comment]
Long date problem, slapping something on SmartFridges returns their afterattack procs. If the beaker doesn't have a lid on, it splashes shit all over the fridge

Temporary fix, always put a lid on beakers, vials and bottles you shove in the SmartFridge. This should be a quick fix in and out of itself otherwise

**Comment by d3athrow** [comment]
Working on a fix.
