### ISSUE TITLE
Ghouls still blind

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36150]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
190628293482bf30079650e1f6f04a5d39c812fe

# Description
nervere broke it, and still didn't fix it
# Steps to Reproduce
make a ghoul using mutagen and sticking it into a cryotube
# What you Expected
not blind ghouls
# What Actually Happened
blind ghouls
nervere only fixed an semi-related bug where blindness can't be cured

**Comment by nervere** [comment]
Loving the aggression in this "bug report."
Ghouls become blind because the radiation poisoning makes them blind. This is not something I, at any point, caused.
https://github.com/vgstation-coders/vgstation13/blob/190628293482bf30079650e1f6f04a5d39c812fe/code/modules/mob/living/carbon/human/life/handle_mutations_and_radiation.dm#L191-L200

In any case, I tested both ghouls and humans in my fix PR, both worked.
To be extra sure, I tested it again just now and successfully cured the blindness using imidazoline in a dropper.
![image](https://github.com/vgstation-coders/vgstation13/assets/26285377/241195eb-e5cb-4d86-9337-67e52d88cb2d)
This bug report can be closed.

**Comment by west3436** [comment]
Not a bug
If you want ghouls to be immune to radiation blindness make a feature request
