### ISSUE TITLE
I couldn't do a gender change surgery.

### ISSUE THREAD

**Issue by F-OS** [d3athrow/vgstation13#36188]
#### Description of issue
Trying to do the gender change surgery sometimes gets locked into tail mode. Either this is bugged or the wiki needs an update.
#### Steps to reproduce
Unsure as I haven't tested it. Attack logs attached.
[logs](https://pastebin.com/gCjZaste)

[bugfix]

**Comment by F-OS** [comment]
Pinging you because your PR #36146 was the last to touch this code, @13spacemen is this just me being retarded?

**Comment by Dacendeth** [comment]
No this is definitely shitty coded, in order to bypass the tail surgery code you need to click again with the retractor to get it to understand to do it which is definitely not ideal. perhaps a fix should be that tail surgery should be ignored if the groin is open from a scalpel.
![image](https://github.com/vgstation-coders/vgstation13/assets/26881007/2e628a86-8a12-462b-a955-cb3314c5ea0e)
it should be noted that this also gets in the way of kidney/appendix related surgery as well for the same reason.

**Comment by F-OS** [comment]
I clicked again, which is the weird part. Didn't go into the gender surgery code.

**Comment by Dacendeth** [comment]
You have to click again before the tail surgery step progress bar actually finishes.

**Comment by F-OS** [comment]
that's retarded.

**Comment by Dacendeth** [comment]
Yes it should be fixed but that is a temporary work around until someone does fix it.
