### ISSUE TITLE
Remove the Roundstart Syringe Gun from Medbay 

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#3619]
I wanted to start a discussion about this to see how people would feel about it. I think it would be a positive change to remove the syringe gun from medbay roundstart, but I would like to hear what others have to say about it. Its been discussed in the past but I don't think its ever been discussed as an issue on here. 

I think it would put an extra barrier between Medical Doctors / Chemists being able to chloral people early into the round. I don't think its a massive issue, it certainly doesn't happen too often as far as I can see but it is something that happens particularly in wizard rounds. Its not uncommon to see the chemist or CMO whip out that chloral the moment a wizard is announced and I think this simple change would help to avoid that without being too obnoxious or over the top.

Please share your thoughts.

**Comment by ComicIronic** [comment]
You do move the Ret syringe to counter hulk tactic, though.

**Comment by d3athrow** [comment]
:-1:

**Comment by Arthurdentist** [comment]
Torpedoed by Pomf, though id still like to hear more thoughts on this.

**Comment by Probe1** [comment]
I've played a fair amount of chemist, and CMO in my time.  I'd go as far to say I'm an expert in medical.  But my experience is narrow as I only play a certain way and rarely is it griff or validhunting oriented.  

I often grab the syringe gun out of protection for it rather than myself or gain.  I know that if I leave it there it will quickly disappear into the hands of an assistant or doctor that wants a weapon.  I have never, in the 8 months I've played ss13 on this server and 6 months I've had a thorough understanding of medbay, seen the syringe gun used as a helpful tool to apply medicine to patients.  I've experimented with it myself but the loss of a syringe and setup time does not make any sense.  It's far more efficient to fill a syringe or a medical belt with emergency pills rather than a syringe gun.  

In my mind this establishes the syringe guns use is not for treatment but for protection or aggression.  It is there to be obnoxious and over the top in your words.  

The question is does medbay deserve an object that has potential for good even if it's seldom used for any purpose except defense or aggression?  That same question could be asked of any department.  Do engineers truly need black gloves on their table except as a supply of stungloves waiting to be made when times go to shit?  Do Researchers need SO MANY THINGS THAT ARE POTENT WEAPONS?  Does the chef need a butchers knife when a regular one has almost same functionality, or a bartender a shotgun or so on?  How often are these items used for good compared to other intents?  

I think that the syringe gun is not there to help medbay treat patients directly.  It's there to help medbay deal with early game riots and break ins.  It shares a complimentary role and same purpose as the straitjacket.  These items are, combined with chemistry, the sword and shield of medbay while security (if it exists) is en route to do the serious pacification.  

I'd say keep it and instead focus on the problem as a whole instead of removing singular items - curb abject validhunting that crosses well beyond self defense.

**Comment by Kurfursten** [comment]
:-1: 

Medbay has very little defense in general, and is painfully easy to infiltrate, rob, and wipe out (look at how quickly it gets completely converted in Rev). The cloner is also probably tied for the brig as the most bombed place on the station. Doctors don't need to be even easier to kill.

**Comment by ComicIronic** [comment]
To be fair, a single Syringe Gun does very little to help Medbay avoid being overrun. It's only useful in a few niche situations.

**Comment by Boxe** [comment]
side note but what if we had a tator chemist/doctor syringe gun goon-style where you dump in chems and it shoots syringes w/o you having to load them

obv the syringes wouldnt be possible to re-use and maybe have it fire at 5 units per pop

**Comment by Probe1** [comment]
you can get close to that @Boxe by filling a medbot with "insidious chem xyz"

**Comment by CptWad** [comment]
:-1: 
imo its shit and only helps in cult/rev
The only advantage is that its a long range harm syringe. 
Really the best weapon for chloraling people is the hypo.
Also removing !!FUN!! is not a good step. It may mean someone gets upset once a round every three hundred but whatever its !!FUN!! without !!FUN!! ss13 is not as unique. Having stupidly over powered items is part of the entity. By having lots of stupid overpowered shit mixed together there is no one true way to 'win' the game. Rather, many different ways to achieve one goal. The Syringe gun is not even that good. Even in a good chemists hands they have a 15 unit maximum and are not nearly as powerful as a good chemist with a single  pill, or even spraybottle filled with god knows what.
If you dont like it replace it with something better. It's better to buff or replace something than to remove it completely.

**Comment by Probe1** [comment]
There exists a rapid fire syringe gun @CptWad that serves that purpose.  The advantage a syringe gun has over the ubiquitous spray bottles is its ranged.  I agree its equally powerful to just dump polyacid (to remove any masks) and your chem of choice into a spray bottle.  But there already exists a buffed version of it that RnD can hand out.

**Comment by SarahJohnson489** [comment]
I'd like to chip in that people are often extremely resistant and hostile to getting vaccines from virology over >viro always antag meta concerns. Especially when you're handing out a 3-6 out of 13 antibody vaccine from your starter dishes. The syringegun is a great tool for inoculating the resistant against 1/4-1/2 of the random viral disease events so you're ahead of the curve. Doubly so once an outbreak starts and double niggers are running around sneezing, viral sputum, bleeding all over the place with their aids but still wont come get treated.

**Comment by dylanstrategie** [comment]
I don't know where my fucking comment went, but in substance : 

>I would be fine with moving it the CMO's office so that he decides who's its deployed to, like the RCD for the Chief Engineer

**Comment by Arthurdentist** [comment]
I've thought about it some more and I don't think this would be a good idea anymore. I guess my problem is with incredibly short non-rounds caused by validhunting twats as opposed to the syringe gun itself. I'll keep this issue open however incase more people want to share their views.
