### ISSUE TITLE
Pulse demon balance suggestions

### ISSUE THREAD

**Issue by SECBATON-GRIFFON** [d3athrow/vgstation13#36585]
[balance]

some ideas glimpsed from complaints in #36576
-ion ing them blocks abilities and possession as well as healing, it currently just blocks healing
-add security or AI to enemy jobs
-making the grid check random event fire if too much power gets sucked in an SMES, warn the pulse demon about it first

any more are welcome

**Comment by angryturnip** [comment]
additionally letting you target floors with ions to make aiming at pulse demons easier

**Comment by SECBATON-GRIFFON** [comment]
> additionally letting you target floors with ions to make aiming at pulse demons easier

i wish guns could target floors in general honestly, if there was a sane way to do that

**Comment by kilozombie** [comment]
>-add security or AI to enemy jobs

Absolutely. If ions are the best most active counter, it makes sense to require (or at least heavily incentivize) a guy that might actually be able to get ions.

**Comment by Pancakemines** [comment]
Some way to check to know if the demon is dead would be really useful too since a lot of the time fighting them involves turning off power it's very annoying to leave it off for an extra 5 minutes or so becuase you're not sure if it's gone. (My personal suggestion would probably be running a scan using the power monitor that takes a good 20-30 seconds of inaction to complete to prevent you just pushing it as you walk by just to metacheck)

Another issue that I've commonly run into is that I like to use the Solars SMES for non central back up power on box and when a demon spawns it just adds four more areas for it to charge from that I have to run around in a panic and disconnect. I don't like the idea that I'm being punished for doing my job better. A way to equally prevent that would be nice, some kind of upgrade to SMES that make demons charge slower or throw an alert to the pager that isn't there by default but if you're going the extra mile to set up the backup power you could also upgrade them to have.

**Comment by Dacendeth** [comment]
I think using a multitool on a wire should tell if the pulse demon exists on that network, a message about a weird electrical disturbance being detected.

I think ions should collide with them when they're under floor tiles since the lack of being able to shoot at the floor directly is frustrating.

They also feel like the penalty for getting hit with a single ion is too small, you just zip away quickly and wait 10-15 seconds and you start regenerating back to full. and considering how it takes 4 ion hits in a row to kill an upgraded pulse demon this is in practice not a viable way to combat it.

**Comment by Killette2** [comment]
Does a demon have any counterplay to the grid getting shut off? They should get a low power mode which works like the sleep verb for demons that shields them in scenarios where there's 0 ways to get power. With everything being on 1 grid the majority of the time a demon is fucked every time a shard blows or the grid goes down.

**Comment by SECBATON-GRIFFON** [comment]
> Does a demon have any counterplay to the grid getting shut off? They should get a low power mode which works like the sleep verb for demons that shields them in scenarios where there's 0 ways to get power. With everything being on 1 grid the majority of the time a demon is fucked every time a shard blows or the grid goes down.

usually simply going onto another grid, if that happens

**Comment by hacker-on-steroids** [comment]
>any counterplay to the grid getting shut off

going into the SMES at telecomms/AIcore/solars(if they're set up)
with enough autism i bet he could even manually rotate the solars and phasewalk out into the space-cable, where the solars power him directly
