### ISSUE TITLE
Forever fire burning while breached to space with no oxygen

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36721]
(WEB REPORT BY: pancakemines REMOTE: 172.93.101.77:7777)
Just watched a fire that im pretty sure should not still be burning continue to burn but the sitauation is very unique reporting now to add pictures post round.

**Comment by Pancakemines** [comment]
Alright it me round over you waited patiently enough west heres your reward.
![dreamseeker_K26verqaMR](https://github.com/vgstation-coders/vgstation13/assets/57334601/27252c18-f2aa-4e62-a1c1-0a74868ed669)

So a breakdown of what's going on is we have the plasma gas miner inside of the TEG burn chamber room, a blob storm fires breaches right past the "shielding" and breaks mcgees impregnable single inflatable shelter seperating the miner from the rest of the station. Blob node expands and spreads into TEG burn chamber(which was empty and not burning) and somehow this causes the fire to start with the igniter inside despite the fact that at this point the room had been entirely exposed to space from the blob and nothing was left but the plasma constantly pumping from the miner + tiny amounts of oxygen/n2 from distro deperately trying to fill the voids all over the station.

Worth mentioning although you can see it with the temps going up this absolutely was real fire as it was constantly killing the blob spawned from the node (this might need fixing as well I remember this becoming a lag machine with the sing once) the fire didn't damage the node however not sure if that's intentional or not.
