### ISSUE TITLE
Cyber horrors don't inject their cyber juices

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36772]
(WEB REPORT BY: spacedgod REMOTE: 172.93.101.77:7777)
# Revision
7585f72d32547d11e59037aa430672678593df68

# Description
If this ins't a bug, I can't find the relevant PR. Cyber horrors still whale on non-horror mobs, but won't infect them with nanites. 
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Dacendeth** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/26881007/c862ff92-bd0a-4e0f-80d3-00527479620a)
confirmed

**Comment by wotisjanitor** [comment]
horrors in general need a buff. i think they should inject way more at a time

**Comment by Killette2** [comment]
The juice is generally low because it's been balanced around that. If you want the transformation to happen you wanna use multiple horrors or hope you get lucky with just one. If you wanna spam horrors without killing your subject, use monkey horrors, as horror is a racial damage multiplier and monkeys deal 0. If you wanna roll heads make a goliath horror

**Comment by boy2mantwicethefam** [comment]
I broke it sorry.
