### ISSUE TITLE
Air Alarms Can't be Placed in New Rooms Created Via Blueprints

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3696]
I built a room out into space from Escape, mapped it with the blueprints, installed an APC, installed a vent and scrubber, and then tried to install an air alarm so I could control the vent and scrubber. When I used the air alarm frame on a wall in the room, it said something along the lines of "The air alarm frame can't be placed in this area." It was already mapped with blueprints and I had already installed an APC, so I know it was a legitimate room.

Also, in response to this, an admin spawned a completed air alarm in the room. While I could see my vent and scrubber in the air alarm's menu, I couldn't alter any of their settings, and the air alarm itself seemed to be reporting incorrect pressure/temperature data about the room.

**Comment by ComicIronic** [comment]
Is it possible the places where you were trying to place the air alarm frame weren't defined as the same area?

Because APC frames and air alarm frames have the same requirements, so the fact that you were able to build an APC says to me you managed the area properly, but you weren't placing the air alarm in a good spot.

**Comment by clusterfack** [comment]
Yeah if you got that you built your room into the emergency shuttle station which doesn't actually work
