### ISSUE TITLE
Exosuit Fabricators improving resource/time efficiency from just having better research synced

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3719]
Exosuit Fabricators have (unique?) functionality that automatically improves them so that they use less resources and build faster, just from syncing them with better research.
Machine upgrades are usually handled by part upgrades, which already need research (and in the case of higher tiers, sometimes rare materials). This really breaks intuition, and I often see players upgrading their fabricator without knowing the effect research has on them.
That's not really the issue so much as the benefits from research being much, much bigger than the benefits part upgrades give: Fully upgrading your fab cuts the cost of a robot endoskeleton from 75000 to 69000, whereas maxing Materials research brings it from 75000 to 48000.
In the end, the upgrades just work really weird and disassembling your fab to upgrade the parts is simply not worth it. The upgrades should ideally be handled completely by the parts.

**Comment by Probe1** [comment]
I was the one posting the results in the thread yesterday and boy oh boy does that chafe my fucking testicles.  So just doing research and syncing to the server nets a 40% reduction in cost, but printing out new parts and adding them only make it 8% cheaper?

Sprinkles on top of the turd - manipulators and matter bins do nothing.  they build at the same speed and exofabs can hold for all intents infinite metal anyway (because whos going to insert 700+ sheets of metal to begin with without using any up first)

:-1: 

some brave soul needs to sit down and unify the logic behind part upgrades.  like weeds, machine upgrades have grown wild and tangled by many different hands all changing the code how they see it should be.  in this singular case of machines, it's a god awful mess.

**Comment by 9600bauds** [comment]
I'm guessing this was a thing before part upgrades, since the code seems pretty oldcode. This is more of a relic of times past rather than some coder's weird twisted vision.

**Comment by Kurfursten** [comment]
:+1: I want to do component-based upgrades for a lot of machines, but maybe I could do this in the next two days before the feature freeze. I wanted to edit fabs already because I have a really great (I think) tweak in the works that I won't get into here (I don't want to distract anyone).

**Comment by 9600bauds** [comment]
@kurfursten Did you ever touch this up while I was dead? Or is it still an issue,?

**Comment by Kurfursten** [comment]
No, I had PR to improve machine efficiency based on lubing them up with space lube, but in testing I determined it was too clunky to feel rewarding. Go ahead and tackle it if you like.

**Comment by Probe1** [comment]
This was fulfilled actually.
