### ISSUE TITLE
Grass phytochemistry genes purged/spliced onto edible plants makes them inedible

### ISSUE THREAD

**Issue by Kazuhirax3** [d3athrow/vgstation13#37204]
#### Description of issue
As the title says, phytochemistry genes extracted from grass and subsequently spliced or purged onto the seed of an edible plant renders the fruit harvested from said plant inedible (the plant in question will still be "consumed", but it yields no nutrition and says "There is nothing left of the _X._") Additionally, it also sets the biomass produced by each individual fruit to 1 (e.g. if you have 17 affected watermelons, add them to the biogenerator, and activate it, you'll only have 17 extra biomass). _If this is an intended feature, then I highly suggest editing the [relevant wiki page](http://ss13.moe/wiki/index.php?title=Guide_to_Xenobotany#Generally_Accepted_Roundstart_Method) to change the roundstart method of using grass for phytochemistry to something else._

#### Difference between expected and actual behavior
Expected:
Plants spliced/purged with a grass phytochemistry gene should still be edible and produce however much biomass a given plant with _x_ potency would.

Actual:
Attempting to eat a plant yields the message "There is nothing left of the _y_.", no nutrition is gained, and biomass generated by affected plants only yields 1 per plant. There's probably more to it than just these two quirks, such as grinding/juicing, but I have not tested that.

#### Steps to reproduce
>process grass seed genome in centrifuge
>extract phytochemistry gene
>splice or purge gene onto another plant
>attempt to eat fruit of affected plant/add affected plant to biogenerator and activate

#### Specific information for locating

There's nothing left of the watermelon.

#### Length of time in which bug has been known to occur

I'm not sure. I noticed it for the first time during the late night September 30th round that started ~6PM.

#### Server revision

Server BYOND version: 515.1620
01d78a7e709fa532a844b2cc48339850d3671e07 Current

[bugfix]

**Comment by RealestEstate** [comment]
An empty plant (no chems inside) will be empty on consumption therefore it is acting as expected (no biomass, no nutriment.). Purging from grass will give you the grass potency, but removes the "chems". Splicing higher potencies grass should fraction the chems, but also increase total by fact of simply having higher pot.
A grass spliced plant will always have less chems than one naturally brought to high pot, but it shouldn't be empty in either case.
Did you splice from grass with a high potency value(greater than 30)?

**Comment by Kazuhirax3** [comment]
Yes. I followed the Generally Accepted Roundstart Method verbatim and waited until potency was at or above 100.

**Comment by SECBATON-GRIFFON** [comment]
> Yes. I followed the Generally Accepted Roundstart Method verbatim and waited until potency was at or above 100.

for the record i took that from a pastebin from the days of yore and modified it for the wiki if that helps. then i think eneocho spruced it up

**Comment by hacker-on-steroids** [comment]
>A grass spliced plant will always have less chems than one naturally brought to high pot

wtf, really?
i thought i knew at least a little bit of botany but damn

**Comment by Eneocho** [comment]
>A grass spliced plant will always have less chems than one naturally brought to high pot

This is categorically false. The checks call specifically for the potency and add the reagents according to the formula.
If you have a watermelon you manually raised to 200 potency and one you spliced to 200 potency, you'd get the same amount of nutriment inside it.

**Comment by Eneocho** [comment]
For the purging itself, it's working as intended:
Grass has no reagents inside of it, and mutating it with mutagen (PHYTOCHEMISTRY) VERY RARELY (i've only had it happen once ever) adds chems to it, so you can just pump that potency all the way to 200 and extract the gene.
The data disk has PHYTOCHEMISTRY = NO REAGENTS, 200 POTENCY as the data (not how it's actually formatted in-code). 
If you SPLICE this, the machine adds "NO REAGENTS" and averages the seed potency with that of the disk's (a 0 potency seed and a 200 potency disk average out to 100 potency on the seed after 1 splice, for example). This means that, for example, a banana will now have around 108 potency after 1 splice (I think they start at potency 15) and will keep producing banana juice and potassium carbonate, scaled with potency.
If you PURGE instead, the machine **REPLACES** the data in the seed with the one in the disk, meaning that the seed now ONLY makes "NO REAGENTS" and has exactly 200 potency.
Fruit with no reagents inside it, regardless of how you made it, is inedible. If you get a regular roundstart apple then remove the chems with admin powers or chemistry fuckery, the apple will say "there's nothing left of the apple".
As for the biomass, it scales up with nutriment, so a plant with high nutriment (and an upgraded biogenerator) will make more biomass. If your plant has no nutriment (either empty or spliced/mutated out), it makes a token 1 nutriment.
@Kazuhirax3, you very likely purged phytochemistry instead of splicing, it's a common mistake, one everyone makes once or twice.
I can confirm botany as a whole still works as intended and described, yesterday I spliced hyper bananas and they worked properly (making extra reagents).
