### ISSUE TITLE
[Bug] Can't be shot when on a wall tile

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3810]
Walls stop attacks from hitting anyone standing on a wall tile but still allow the player standing on the wall tile to attack others.  This was obnoxiously abused by wizards in the past week to be invulnerable.  Figure out a way to allow attacks to reach players standing on a wall tile or prevent players from using it.

This also applies to any melee attacks I believe.

**Comment by MercuryDoll** [comment]
Instant brute damage when spawning inside a walltile, suffocation while staying inside. BAM.

**Comment by AutismSpider** [comment]
Melee attacks can hit can't hit them with range base weapons

**Comment by clusterfack** [comment]
Huh, I had no idea it also affected scrubgloves. I believe for projectile weapons we could fix it at this point in the code
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/projectiles/projectile.dm#L173
By first doing the check for the mobs in the turf, THEN the objects. Though I could be wrong (Comic should be able to tell us as he's dealt more heavily with projectile code)

For the gloves I am really not too sure at all if they even have a place where they are all compiled into one, so that could be a case by case basis.

**Comment by Probe1** [comment]
I was firing a handgun at the wizard in the wall and it didn't hit.  Lasers, etc.

**Comment by clusterfack** [comment]
If a malf engiborg builds walls under the turrets it can shoot from over the wall but not be shot at. No?

**Comment by Probe1** [comment]
resolved I think.
