### ISSUE TITLE
Flipping welding masks flip masks too

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3817]
Be clown
Don your glorious welding helmet
Flip your welding hemlet to see the world around you
Oh god your face is visible too!
Flip mask back down and just take it off your head in shame

**Comment by ComicIronic** [comment]
What I think is actually happening here is that the welding helmet is hiding the mask render, so flipping it up doesn't show the mask.

Haven't tested it, though.

**Comment by CptWad** [comment]
If thats the issue I miss having the clown mask show through anything you had on your head. Made walking around in eva suits just more fun

**Comment by PJB3005** [comment]
yeah, can confirm, if you put on a welding mask and then flip it up, your mask will be invisible, but, your mask stays invisible even after you take the welding helmet off

**Comment by ComicIronic** [comment]
If you were interested in learning why this was happening (because god knows I was) the hiding flags for the welding helmet were updating whenever it was flipped up or down. This was meant to make it so that flipping the helmet up would cause it to stop hiding the mask, so that would render.

However, the proc to re-render the mask was never called, and if the helmet was taken off while flipped up, the fact that it no longer was flagged to hide the mask meant that the mask was not redrawn (since only potentially covered items get redrawn).

This would leave you with no apparent mask, since the layer wasn't drawn properly after being hidden.
