### ISSUE TITLE
AME doesn't destabilise up when the containment jar goes empty

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#3819]

**Comment by Probe1** [comment]
when did it ever?  it's not done that for over a year.

**Comment by clusterfack** [comment]
I always thought it should, but I'm not sure if it ever has

**Comment by Probe1** [comment]
dunno if my car runs out of gas it usually just turns off instead of exploding.

**Comment by PJB3005** [comment]
the wiki even says it's supposed to destabilise when the fuel goes dry http://ss13.pomf.se/wiki/index.php/AME

**Comment by Probe1** [comment]
Yes, that's what it is.  Making it a station grade bomb does not improve it.  Our wiki contains many factual errors from when it was copied verbatim from other wikis.  Only a few months ago I removed erroneous engineering information that had people honestly believe that the CE starts with the door wires because that is how it was on tg at the time the wiki page was copied over.

**Comment by MercuryDoll** [comment]
I think it's fine the way it is now. It's low yield in the small version you start with and barely feeds enough energy for the lights not to go out, probably even need to wire the solars as well. 
You can cheaply order more parts and more fuel to create a massive reactor that charges significantly more effective, but turns it into a bomb. Just recently we had a 51-core AME and someone overcharged it, it blew atmos to pieces. It's a engieboy's first engine but adapative enough if you're willing to put effort into it.

**Comment by Kurfursten** [comment]
@clusterfack @PJB3005 Can we agree to close this? Seems like we're settled on status quo.

**Comment by PJB3005** [comment]
Eh whatever I guess.
