### ISSUE TITLE
You can put closets into the recycler and the closet including all its contents will be eaten by it

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3820]
Good googly god nerf now

**Comment by Probe1** [comment]
I saw this happen earlier today.  Engineering crate with anti matter jars went to disposals instead of where it was tagged to go.  It moved to the recycling part of the incinerator then the crate disappeared and the jars were shunted to the side.  Really fucking efficient if you want to open and covertly dispose of 100 weapon crates.

**Comment by CptWad** [comment]
So thats where all the improper destinations go, they get eaten by the smelter.
Weapon crates are cool and all but I am worried about corpses. You can shove dead bodies in a locker and have them dissapear. Oh man I gotta see if you can get a closet with a LIVE person in it and see if it eats them too
Okay maybe keep this but only when the smelter is emagged.
