### ISSUE TITLE
The Economy's Fucked. Let's figure out why.

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#3856]
## Why the economy is fucked.

* If we take the balance of payments, it's atrocious; due to two things
   * Lots of expenditure, (in numerous avenues), but mostly cargo.
   * Barely any income, only via mining, which does not get distributed.
* Culture. - It's not within the culture of the station to pay for things other than as a gimmick.
   * Is it because the system is obnoxious as fuck to use?
   * this'll probably be the hardest one to change 
* Currency has literally no value.
   * Not backed by anything (fiat)
   * Possible to print unlimited money 

## How can we fix it?
* Make shit easier to use
* Make departments compete as to who has the most money?
* Add money systems to player-stocked vending machines?
* Remove the way to print unlimited money please
* Make cargo change on points again so as to reduce the outflow of station cash out of the economy?
* Make vending machines money go to cargo's account?

## How can we not fix it?
* Don't import the system goon has where they pay every X minutes or whatever, this'll just lead to inflation and doesn't fix the problem at all

Please comment as to your opinion on this issue as to what the problems are, how we can fix it and ways not to fix it.

**Comment by d3athrow** [comment]
Thanks obama

**Comment by SangriaMonkey** [comment]
I know we all *just love* our bay lore but the whole money is evil spiel is a little trite at this point, or at least I would think. Plus it only serves to prop up chefs in practical terms.

Cargo points and Islamic Gommunism when

**Comment by MercuryDoll** [comment]
If you want to keep the money system, you'd need a complete overhaul. 

Currently we have a playerdriven economy, where heads pay their employees. What we'd need is departmental funds.
Example: The geneticists ran out of monkeys because the chef stole them, they need to order monkeycubes. Surgeons complain about the clown who's stolen the surgery tools. Both make a ordering request directly from the medbay ordering console. The CMO sees the requests and can approve them, this will use Medbay's departmental funds. At his console he can also pay the doctors their salary.
The drawback is that this is very roleplay heavy, which /vg/ just can't get along with, see paperwork.

Another option would be to give each job tasks that give them pay, see roboticists. Problem is that this is very inconsistent and not every job has a clearly defined task. Eg. what is security's tasks that can be mechanically paid?

What we'd also should consider is if how /vg/ plays spessmen is: Do we even need an economy? I think SangriaMonkey hinted at it already and it might not be all too braindead to remove money as a whole and give cargo "points" that fill up over time so ordering stuff isn't abused.

**Comment by DrCelt** [comment]
>Currently we have a playerdriven economy

>where heads pay their employees.

Except we don't.

**Comment by MercuryDoll** [comment]
that's what i said
> The drawback is that this is very roleplay heavy, which /vg/ just can't get along with, see paperwork.

It's never done, just like when roboticists want you to sign a borgification contract or HoPs want some stamped papers for access transfers.
/vg/ is a very gamey server that doesn't roleplay very much, which is why the roleplay-based currency system never worked.

**Comment by DrCelt** [comment]
> /vg/ is a very gamey server that doesn't roleplay very much, which is why the roleplay-based currency system never worked.

Yeah but currency systems do not inherently require roleplay; what's happened is that bay's roleplay-currency system has not been changed to an actual flowing currency which is independent of roleplay and used as a means of exchange for the reasons above and numerous others I'm probably too stupid to realise.

**Comment by CptWad** [comment]
Probably just make it extremely basic.
Give all crewmebers 1000 dollars + 500 if a head.
Now we seperate into two categories
Service machines and Wide machines
Service machines can be filled with seperate items and sold to the crew. 
The crew will come up to the desk with the machine on it and pick what they want and pay the price. Then anyone with appropriate access can place their ID inside and claim the cash
Some examples where this will work are RnD, Chef, Bartender ( Or a machine where patrons can just slap their ID on a item and it pays the bartender 5 dollars) 
Wide machines are items that load with many items and pay players based on what they bring it but other players will not have to pay for it, at least all the time
A player will bring their work to the machine, the machine processes it, then pays the player responsible
Examples include the CURRENT mining machine, a hydro machine (its the fridge but pays people who put stuff in it), a xenobio machine (Pays per slime core) and a viro machine that uses anitbodies and gives 1000 dollars fore each new antibody unit (More than one unit results in no extra money)

Now for cargo
The mining machines now will work differently
Miners gain a flat rate per ore they bring, regardless of quality

The cargo account is highly important, it should work like goons cargo where the stations success is measured by how much money cargo makes. 
Cargo can make money by selling: Artifacts, crates, Stacks of metals/plasma/diamond/etc, Mechs, and anything else you can think of.

Other unique examples
Robotcists can now earn money when they debrain, meaning they make money every time they borg/mommi. It only works when they make a connected player into a borg/mommi. A flat rate of 1000 a pop
Xeno arch simply gets a pda message whenever they unearth an artifact for a nice 5000 dollars
IAAs earn 2500 every demotion. This encourages them to actually demote tyrants. (They cant exploit this as an admin has to ordain demotions IIRC
Janitor gets 500 - # of messes on station per 30 minutes
Captain earns 100 dollars every twenty minutes
Sec officers, the detective, warden, IAA, heads of staff, the clown and mime earn 50 dollars every twenty minutes
Medical (all), Science (all), Engineering (all) and Quartermasters earn 30 dollars every twenty minutes
Service, cargo techs, miners and janitors earn 20 dollars every twenty minutes
Assistants earn 10 dollars every twenty minutes

WHAT DO WE SPEND MONEY ON?
All vendors are about 10 dollars per food. Thats what we have now
chef food sells at rates from 10 dollars for simple items (IE burgers) to 50 dollars for complex items (IE a turkey). The cost of an item is based on the nutriment value. This can be cordoned off by use of ranges.
RnD toys all have specific prices. The machine WILL NOT load weapons out of their lockboxes (unless hacked of course) Items range from 10 dollars for a PAI to 1,500 for a bag of holding. (Placeholders, can change of course)
Barmans tip is a solid 5 bucks. Drunk patrons can see their money dissapear before their eyes!

Thats all out of my mind for now

**Comment by NigglyWiggly** [comment]
>The mining machines now will work differently
Miners gain a flat rate per ore they bring, regardless of quality

How about no

**Comment by Probe1** [comment]
I have a lot to say on this matter and disagree with a few points that @DrCelt made in the opening post.  I'll be making a few replies, namely after I have tea and wake up properly.

>If we take the balance of payments, it's atrocious; due to two things
Lots of expenditure, (in numerous avenues), but mostly cargo.
Barely any income, only via mining, which does not get distributed.

We have **VERY FEW** real places to spend money.  1.  Cargo  2.  Vending machines 3.  PDA apps

Note that what ties them together is it is Player-Station transactions.  The money disappears into the  either and no one has to charge anyone else or lag the other players immediate short term goals by setting a price or preparing an object.  

The only economy that exists on vgstation is Player-Station (which I'll refer to as P-S).  Player-Player economy (P-P hee hee, when two players interact each other and trade currency for items) does not exist in any form except as a new player trying out those weird cash registers or EPTOS scanners no one ever seems to use.

I'm going to make a few posts in the coming hour but the main theme I want everyone to understand is that P-P interactions will not work.  Automating income and balancing costs for P-S interactions is how you're going to make economy work.

**Comment by DrCelt** [comment]
>I want everyone to understand is that P-P interactions will not work.

Why do you think that?

>Automating income and balancing costs for P-S interactions is how you're going to make economy work. 

But that's like having no economy at all; it's artificial and is why the USSR collapsed.

**Comment by Probe1** [comment]
It's an interesting reference to bring up.  @CptWad mentions having payment vending machines where viro cures or other items can be added for money.  One of the severe issues that crippled the soviet economy was this incentivization.  Production targets were set and quality control was mostly disregarded so that workers would meet their quota, which resulted in the available goods being poorly made rubbish.  However the comparison falls apart because of Soviet economy had a multitude of problems and hardly any of them will be simulated in a simple spessmen game.  I'll answer why I feel PtP interactions do not work as a **primary** mode of economy soon.

**Comment by DrCelt** [comment]
I'm alright with a PtS fiscal policy approach if we ensure that it runs neither a surplus or deficit as to the ratio money leaving/coming into the station, or we'll have inflation/deflation.
PtP needs to be improved severely though, (You can use a vending machine with a PDA and not even have to take out the card vs ATMs where you must enter your card your pin and account number and christ almighty is that not worth it - which we need to fix even if we focus on PtS.)

**Comment by Probe1** [comment]
Alrighty.  I'm on my second cup and I'm ready to talk about something I've given a great deal of thought and energy towards improving through the means I have had available to me.  The in game economy.  Over the last few months that I've been active in reporting bugs and making suggestions I've encouraged coders to add things that cost money (notably Deity Links PDA apps) and remove things that make transactions irrelevant (The RSF producing free cigarettes).  

I strongly believe that the economy cannot and will not be fixed with any big PR.  It has to be systematically improved through many approaches and I will discuss them here.

##Whats wrong

The economy is broadly speaking, a failure.  This stems from a few primary sources and a multitude of lesser ones.  The primary sources that undermine the economy are:  The ease of creating free money and goods, the difficulty in distributing money, and the lack of sources to earn and spend money.  The lesser reasons are the ease of getting free goods and lack of essential goods that cost money.

The ease of money is something we can knock out today.  Patch out the ability to make infinite money and drop the station account from the absurd  75000 credits to 5000-10000.  There is no reason to have that much money and it's a huge oversight that minimizes the importance of an economy entirely by itself.  Also tied into this is the asstons of money that miners will make.  On a good day I can mine upwards of 40,000 credits worth of money.  That's enough to give every single player during average pop 1000 credits, and that in itself is enough to last a player a several hour shift.  So not only does the station account need rebalanced and the infinite money removed, but mining needs to either return to a voucher and cargo points system or the income needs to be dropped by a factor (and the mining vending machine prices rebalanced to reflect that!).  

The second primary issue is that we do not have an automated payment system and we need it.  Either goons approach, or what @CptWad suggested, or a novel idea that isn't listed needs to be applied.  Relying on Heads who may not be there and likely won't be interested in acting as a Head of a Department even if they are there is an empirical failure.  We have all the data we can ask for from months and months of playing under this system and rarely seeing a Head ever release department funds or players ask their Head to do so.  I cannot accept disagreement on this point because we have the proof we need through experience - it just does not work.  

There needs to be ways for players to earn money without relying on other players or else the system falls apart.  Our playerbase (and for that matter, other playerbases) are interested in playing spessmen.  They didn't come here to play Recettear: An Item Shop's Tale IN SPESS.  It'd be a cool game but it isn't our game.  Having Player to Player (PtP) interactions be the primary economy will not work.  So we need more Player to Station (PtS) interactions.  Again, @CptWad brought up one idea and goon has another.  These both will work.  Assuming this point is settled and we now have ways to earn income, what do we spend it on?  Food?  I can hack a vending machine to spit free food out at me.  Materials?  Miners, botanists, and other methods can get them to me for free.  There are lots of things that only cargo can deliver but the cost values are a hodge podge of what the coder that wrote them felt like at the time and lack any central planning or guide.  So even the lowliest account balance can afford what they need that couldn't be acquired elsewhere.  


 On player to player economy, I have a simple example to illustrate my disdain for the idea.  How do engineers make money?  How does security make money?  Are they supposed to ignore crime until someone pays up?  Shut off the power until your payment comes through?  Not only does the idea of PtP economy leave half of the players flapping in the wind, it pisses them off that they're working for free and RnD wants a fat stack of shekels they don't have for something to improve their efficiency at their job.  If someone is charging money I will go around them.  Every single time.  A chef that wants what may be a reasonable cost for his time but an exorbitant price compared to pizzas from cargo,  A scientist who wants to charge for items but finds his costumers would rather ask a mechanic or break into the MoMMI nest and make it themselves.  PtP economy can exist but it will always be a minor aspect when 90% of the things players really want are through the cargo console which is a PtS interaction.

**Comment by Probe1** [comment]
>have to take out the card vs ATMs where you must enter your card your pin and account number and christ almighty is that not worth it - which we need to fix even if we focus on PtS.)

Or more bizarrely, somehow there is a way that you can just log in by opening the ATM somehow.  I've done it a few times and I'm never sure how I did it.  ATM code is wonky to an extreme.  It should be reworked.

**Comment by Probe1** [comment]
What I didn't touch on but is the most important aspect to consider is:  

Do we actually want an economy?

**Comment by DrCelt** [comment]
@Probe1 
>Do we actually want an economy? 

A good question, and I suppose that relates back to my original "cultural" points, but I'd argue that the economy being fucked this badly means that we basically have no economy right now anyway.

**Comment by Probe1** [comment]
I think what we want are ways to get rare or important goods and ways to limit the amount of rare and important goods that we can get at any one time.  The current economy has grown from this but it's gone woody on us and we have multiple hotspots that make it completely irrelevant.  We can fix one of them today by removing ways to effortlessly generate money and tone down the amount the station starts with.

**Comment by DrCelt** [comment]
Yeah, we must focus on the basic principles before we work on the sophisticated stuff.

**Comment by DrCelt** [comment]
@Probe1
>The ease of money is something we can knock out today. 

I concur, We must focus on the basic principles before we work on the sophisticated stuff.

>The second primary issue is that we do not have an automated payment system 

I disagree, unless you can ensure that this payment system (StP) is equal to the money spent on PtS or there will be inflation as the shift drags on.

>There needs to be ways for players to earn money without relying on other players or else the system falls apart. 

This needs to be backed up on things actually worth value, though, or the system falls apart, or again, StP > PtS and we'll have inflation.

>On player to player economy, I have a simple example to illustrate my disdain for the idea. How do engineers make money? How does security make money? Are they supposed to ignore crime until someone pays up? Shut off the power until your payment comes through? 

Yeah, that's an issue I've encountered myself too on theorycrafting. I'm not sure how to resolve this one. Security could issue fines or confiscate revenue, but otherwise I'm unsure.

**Comment by Probe1** [comment]
The key to beginning to solve the problems are focusing on things that are actionable.  A big PR isn't going to do much except give us one coders vision on how everything should work and be incomplete (but still change things dramatically and probably upset people that hate change).  

The key is to make small, actionable changes.  We can solve the station having infinite money TODAY.  Changing the amount of money the station account starts with is a 30 second edit and removing the means for infinite money could only take an hour at most.  

Start small.  Do what I've done but more concerted.  Patch out ways to get around spending money for things that cost money (cigarettes) and patch in ways to spend money that players enjoy (PDA apps - which if you remember were a hit because they brought back the original PDA light at a cost).

Start small, start actionable.  Do things that can help instead of bug ideas that won't happen but sound good.

**Comment by DrCelt** [comment]
Well the point of this issue request is to identify what needs fixed and discuss what we believe should be done about them.

**Comment by Probe1** [comment]
**Short term:**

Remove infinite money methods
Reduce the amount the station account has to be even with department funds
Halve the value miners get for ores (yes, and I am a damn good miner and have vigorously defended the ore redemption machine in the past)

**Medium term:**

Implement cargo-metrics to study and track cargo purchases for price evaluation
Reprice cargo items 

**Long Term:**

Implement payroll systems that work, regardless of what they are.

**Comment by DrCelt** [comment]
@Probe1 
Yeah, I think that's definitely a good guideline to work with right now.
Perhaps we should add "Add player-stocked vending machines which players can add prices to"
and, although it's unlikely to be well recieved, "Remove the ability to hack vending machines to spit out items they hold" may be necessary in order to make a working economy.

**Comment by jcronin1995** [comment]
http://puu.sh/h8C8J/adc41c58ba.jpg

Compiling some info and creating a model to think about. It's pretty forceful thus far and basically disregards 'culture'. It'll be done soon and I'll start sharing it around.

**Comment by SangriaMonkey** [comment]
#fuckmoney

**Comment by Probe1** [comment]
@DrCelt Yes I think its a good idea and a feasible mid term goal.  Start small and achievable.

**Comment by Probe1** [comment]
- patch out or rework the mining vending machines exploit
- increase general fab costs for matter carts

**Comment by DrCelt** [comment]
>patch out or rework the mining vending machines exploit

In a discussion with probe we came to an agreement on this potential solution: 
"First round of the Vending machines cost the amounts that are set right now; this money doesn't go to cargo but instead is just lost in the ether. (it was free to get so why should cargo take the profits?) The second round has the cargo techs stocking it up with the vendor stocks at the wholesale price, which cargo pays for; and any profits go to cargo's account?"

**Comment by DrCelt** [comment]
Furthermore I believe the ability of the mechanics to create tangible goods (such as cigarettes, food, security vends (?) etc.) out of plastic steel and glass is probably a problem, although some may disagree. Medium-long term goal for later review?

**Comment by SangriaMonkey** [comment]
Honestly I don't see the point.

Before we switched over to the whole money thing cargo was relatively straightforward and balanced. You started out with a set number of points that would replenish over time, or increase with crates/plasma/filled out forms sent back. Crates were priced accordingly and if you wanted to pimp out your cargo bay it took a little thought and planning. Fast forward to now and every QM has more money than they can use on crates which have maintained their point system prices. They're capable of doing pretty much anything with a little effort. The only thing really limiting them is "how many fucking boxes of shit do I want to deal with today". Call me crazy, but I don't think this was a positive change.

Mining is just as bad. The game is geared to be all *dramatic* and dystopian because baycode but these guys just shit all over that (which I think is great but that's beside the point). All the prices and ore values are arbitrary. Plasma is pretty much worthless, and so is most of the gear in the vending machines if you're not interested in the stupid pokemon shit or need to revive Ian. Any miner worth their hardsuit and airtank can go to the high-yield portion of the roid and get enough material to last at least two hours of powergamed RnD. There's pretty much no point to TG's monster bullshit or the money thing and never was, it only serves to impede players needlessly.

Vending machine prices are over the top and make zero sense, especially the Dan's machines. I don't care how inflated the economy was in bay's lore, I shouldn't have to shell out twenty dollars for a box of fucking dried fruit or tainted food. Chefs aren't that important. 

So overall I just don't get it. Do you really think any of this adds to the game? It feels like such tacked on pointless garbage and hasn't changed much since it was introduced. If you can't come up with realistic and comprehensive solutions to these things while finding a way to empower the players instead of needlessly impeding them and making the game less enjoyable, I would say your energy would be better spent on finding a way to dismantle everything and reintroduced the older systems.

Just my two cents.

**Comment by DrCelt** [comment]
@SangriaMonkey 
I agree with you that cargo being straightforward and balanced is what the cargo points system had.
If you look in the OP, I actually advocate cargo points as they'll reduce the station balance of payments deficit.
Yes, money is tacked on. This is the problem with a non free market economy; we have no price mechanism to make everything reasonably priced.
I'd rather dismantle the current abomination of a fiscal system we have though, it's clear nexis had no understanding of the repercussions when he implemented the money system in cargo.

**Comment by Manaony** [comment]
@DrCelt 
Then I suggest not touching anything until we find a way to get people to spend in a hypothetical future economy, right now there's no reason to bother for anyone to gain money and we'd want a price normalization AKA what is a credit worth

**Comment by Probe1** [comment]
I'm really not keen on the idea of doing nothing until someone does everything.  If anyone here is interested in fixing the economy all at once then I want to see the PR.  

None of these problems, which was my point of discussion, are getting solved by one person in one PR.  Saying that nothing should be done until they're all solved at once is a really poor solution and one that we've tried over the last year to no positive effect.

**Comment by Manaony** [comment]
I'm saying nothing should be done until we determine the value we want credits to have and how to normalize prices along with it so as to not aggravate the playerbase.

**Comment by Probe1** [comment]
Based on 8 months of that not happening I don't see that happening in the next eight so I prefer doing something over doing nothing.

**Comment by Manaony** [comment]
Then let's work the value of credit and normalize the prices all at once. What should 100 credit, an assistant starting money, be able to buy you and work around that.

**Comment by SarahJohnson489** [comment]
I disagree about cargo going to cash being a bad thing. As it was as QM you had to camp the console and ride every order as you needed a lot of supply points in an emergency. God forbid you need to order 2 crates of implants in rev/cult or guns in its cases.. At least with cash you can give the botanist his bees and seeds. Medbay its piles of virus crates. The eng his 10 AME shielding. And so on.

**Comment by AutismSpider** [comment]
Prices need to be normalize

CARGO PRICE ARE TOO FUCKING LOW!!!!

Its cheaper to refill the cig machine then it is to buy a pack of cigarettes stack of pizzas are cheaper then 4norasisin at the cost of a cheap lighter i can get crate with yellow gloves a welider and 3 fuel tanks.

For about 350 credits or so I can build a Super matter shard engine, for the same price as two whiskey bottle or 5 cigarette packs.

 Cargo can almost buy 100 crate of guns at round start with the 5K the QM starts with

**Comment by Probe1** [comment]
It might be that cigarette packs are just absurdly high and not the other way around.

**Comment by DrCelt** [comment]
@AutismSpider You're god damn right prices need to normalize. The best way to normalize prices is keep the prices out of the game's hands (Stop prices being set too high on vending machines etc) and let players decide the prices. Now, doing so on vending machines is actually relatively easy, and that's 
what I've outlined as the next step, some of which builds upon what already exists.

I'll get to work on coding this, but it's a rather long term project as a part of the overreaching goal of making money have a value. Of course these are unlikely to be used until we introduce cargo points or currency, but it's good to have this groundwork.

## Step 2: Vending Machines reform
 * Vending Machines Can be Linked to Station Accounts
 * Vending Machines Can be stocked by players with any good, which can have the prices set by them too.
 * Vending Machines can 
 * Vending Machines Can be ID-locked, much like a mech, Allowing only one person to edit the settings.
 * Vending Machines Can also be Linked to a Vending Machine Automation Computer (hereinafter VMAC) if the person has the ID it is locked to.
     * VMAC PDA support (?)
 * VMACs can be set to a certain account or simply to central command.
 * Vending Machines which are Linked to a VMAC can have their settings be edited remotely.
 * The stock of goods in vending machines can be monitored by this VMAC station wide and each vending machine
 * A VMAC linked to a VM which has no stock of a particular good will give an alert, much like an atmos alarm computer.
 * Vending Machines in the hallways now, by default are linked to a VMAC in Cargo.

I am willing to amend things, take criticism on it etc. I don't see anything controversial here though.

**Comment by MercuryDoll** [comment]
Sounds a bit much but i really like the idea of vendors being linked to player/department accounts. That together with prices being equalized sounds like it would already fix a lot of economic problems.
Cargo will take care of refilling general vendors, R&D will probably make a vendor selling tech/guns, the fridge is gonna be a vendor for botanists, chefs buying produce from the fridge and selling their food as well. I can even see assistants selling shit they stole.
 Engineers could be paid by power produced (MoMMIs can link the engine's power to station account if engis are too lazy).
We just need to find a way how to pay jobs that aren't directly tied to the economy, such as security. Perhaps managing security and co's funds could be the HoP's job, which would certainly distract them from playing Hopcurity.

**Comment by DrCelt** [comment]
@MercuryDoll 
Eh, better a bit much than too few. These vending machines are unlikely to get used until we fix the problem with inflation coming from mining, but it's a start, eh?

**Comment by Uqualm** [comment]
There are quite a few problems that need to be dealt with. I haven't thought this through TOO much so one problem that I think is a big deal may not be as big as something I considered minor. It's hard to predict, and that's why if you want to "fix it" you're going to have to keep trying until everything seems natural.

1. What do players spend their money on? Let's try to envision what each job could potentially spend money on. I'm just looking at this from a generic job perspective, not an individual perspective. So this won't account for the doctor who for some reason wants to buy insulated gloves, a full toolbelt, and a taser gun.

>Captain

He's the Captain. Realistically speaking because the Captain can do anything on station, his potential wants are going to be higher then the rest of the station. It shouldn't be too much of an issue for the Captain to find things that may be of interest for him to buy, because he has more freedom then the rest of the station.

>HoP

Same thing as the Captain really.

>Head of Security

His role is to protect the station, and he shouldn't have a desire to buy things typically. I can see him buying an advanced E-gun if they are able to be made. I view him as most of the time a non participator.

>Security Officer, Warden, Detective

More or less the same thing as the Head of Security.

>Chief Engineer, Station Engineer, Atmospheric Technician

I have no idea. Engine crates from cargo?

>Science Department

Materials from mining.

>Medical Department

I really have no idea. Medical supplies? How many medical supplies really need to be acquired from outside the department? Should the doctor have to buy supplies from within the department? Bicardinine from the chemist for example?

>Cargo

Well, they can spend the money on crates, but this leads us to another problem that I'll have to talk about later.

>Janitor

I have no idea.

>Bartender

I don't know, chemicals from chemistry?

>Chef

The chef is an important player in this economy. I will have to dedicate a section to him later. He could spend money on materials from botany.

>Botany

I have no idea.

>Assistant, Clown, Mime, the other "useless" jobs

Potentially anything I suppose. Shouldn't be too much of an issue.

>AI and Cyborg's

Well, they don't spend money.

**Comment by DrCelt** [comment]
@Uqualm 
>There are quite a few problems that need to be dealt with. I haven't thought this through TOO much so one problem that I think is a big deal may not be as big as something I considered minor. It's hard to predict, and that's why if you want to "fix it" you're going to have to keep trying until everything seems natural.

Yup, that's the goal.

**Comment by DrCelt** [comment]
Alright, brainstorming here for ways to monetise engineering, held a vote in game: "what do you think of a err, "Anti-Antimatter Engine", which takes power out of the power grid and fills antimatter cores which can be sold to central command?"
15 Yes - 3 No.
It's with these kind of uncontroversial ideas I hope we can revitalise this economy.

**Comment by Uqualm** [comment]
2. How does each job earn money? For some it may seem a bit obvious as to how they earn their cash, but for others you'll see it is very hard to come up with things. 

>Captain
I have no idea. You could perhaps say that his base salary is high enough for him to be able to spend as much as money as he wants with no issue.

>Head of Security

See the Captain, honestly apply this argument to all heads. 

>The rest of security

I have no idea. Do you want Security to charge criminals they catch fines as well as a brig sentence? Perhaps you could be payed to arrest someone?

>Engineers

I have no idea. If there are power problems do you charge people to fix them?

>Science Department

Sell your finished goods to the crew. If there are multiple scientists, any one of them can very easily print something from the protolathe so who gets the money? The person who prints the requested item? Do the scientists split the income? How do you fairly distribute that?

>Medbay

Do you charge people for medical care? What if they can't afford it? What if they will die without it? How do you make them pay if they just leave? Do you detain them if they can't pay? Are they a criminal who needs to be put in the brig if they don't?

>Cargo
Sell crates and raw materials to the crew.

>Janitor
I have no idea. Do you charge people to clean a department?

>Bartender and Chef
Sell your finished products to the crew.

>Botanist
Sell your raw materials to the chef.

>Assistant, Clown, Mime, etc
I have no idea.

**Comment by Uqualm** [comment]
The third issue that needs to be addressed. There is a fixed amount of money on the station, you cannot generate more. Because the station is so small, this may turn out to be an issue, but I honestly have no clue. I am strongly against the idea of money being generated from "nothing" and money being sent off to "nowhere". That means no sending things off to "Centcom" and no "Centcom" providing money for some arbitrary service like selling power or shipping items away or something. This is money that is either permanently removed from the game (making it that much harder to buy things) or something that has the potential to be farmed for easy cash. I am guessing (I am probably right) that inflation will not occur in the 2 hour time span a round lasts, so this farmed money will just be used to buy anything you ever want, as if it is free, thus making the whole system useless. 

The biggest issue though is that there is no motivation for anyone to do any of this as it takes away TIME which in the world of SS13 is going to be more valuable then money. I can think of ways to motivate people to do it, but they would get mad and complain and so would I. You could think of something that people NEED desperately and make it cost money to use. Pay for EVA suits, pay for oxygen, pay for tools, pay for taser guns, pay for cuffs, pay for valves, pay for clothes, pay for this that and that, pay for everything. This money would be sent off "nowhere" but would make people take money more seriously. They would seriously start to think about how to earn and spend money. Remove the nickel and diming after it has become a habit in the player base to spend money in the fashion you want them too (buying things from the chef, science, etc) I estimate it would take 6 months.

**Comment by DrCelt** [comment]
@Uqualm You're right in that with some jobs it is very hard to see how they could make money on the station.
The obvious solution is salaries, of course, but here's the problem, how do we make sure salaries (Station to Player Income)  does not create inflation? The way I've hypothesized is ensuring that Station to Player Income is the same as Player-To-Station Income. (We can introduce an acceptable amount of inflation, say 10% by the end of the shift and assume the average shift lasts around 90 minutes and with a payrate every 10 minutes means we can work out the inflation we can introduce per pay to produce a rate of inflation a simple logarithm equation.)

This falls flat in two ways; A) How do we ensure this?
B) How would we set salaries?
Personally I'm in favour of as little hand on the prices as possible; so it'd need to be decentralised to the captain or the heads as to how they get their money.

HOWEVER: My attempt at another solution is more simple - Transactional fees or a sort of 'taxation' set by the captain on all payments via PDA/etc which go to the general station account. In this way, we can actually fund security in the traditional way instead of a free-market approach, by the 'taxation' produced from these transactions.


>The third issue that needs to be addressed. There is a fixed amount of money on the station, you cannot generate more. Because the station is so small, this may turn out to be an issue, but I honestly have no clue. I am strongly against the idea of money being generated from "nothing" and money being sent off to "nowhere". That means no sending things off to "Centcom" and no "Centcom" providing money for some arbitrary service like selling power or shipping items away or something. This is money that is either permanently removed from the game (making it that much harder to buy things) or something that has the potential to be farmed for easy cash. I am guessing (I am probably right) that inflation will not occur in the 2 hour time span a round lasts, so this farmed money will just be used to buy anything you ever want, as if it is free, thus making the whole system useless. 

THANK YOU. This is what I have actually highlighted very often in what I said earlier. What I described in the OP re: "Balance of Payments" & "Currency has literally no value." is what you've just described in better terms than I could. - That's why I wanted to resurrect cargo points, but there are some alternatives. Honestly though I think cargo points are the best for a PtP (player to player) economy, and would be worse in a PtS (Player to Station Economy)

**Comment by Probe1** [comment]
I believe that player to player economy will not have enthusiastic participation and that players enjoy using the player to station economy more.  

I don't think the vending machines will work out but I hope that they do and encourage you to try.

**Comment by Manaony** [comment]
Here are the problem I see that need to be dealt before the implementation of those machine
1. Miner and miner vendor as one issue
2. Cargo and vendor prices Right now cargo prices are far too low and vendor are far too high
3. Infinite material from the material synth

**Comment by DrCelt** [comment]
https://github.com/d3athrow/vgstation13/pull/3953

step one of the vending machine reform complete.

**Comment by Kurfursten** [comment]
@clusterfack There is a more modern issue for this, let's close this issue

**Comment by ghost** [comment]
(бля бля бля лишь бы никто не заметил этого)

**Comment by PJB3005** [comment]
Russians invading our repo! 😨
