### ISSUE TITLE
Mousetraps don't trigger for bombs

### ISSUE THREAD

**Issue by MercuryDoll** [d3athrow/vgstation13#3877]
Revision: 1e25ea379feeacf85d8903a17371346ac2df8ed5 

Apparently if you attach a mousetrap as trigger for bombs, they refuse to work. Neither the classic backpack trap nor walking over it activates it.
Odd behaviour with grenades as well though that could be intentional.

**Comment by IratePirate** [comment]
Been like this for at least the two and a bit years i've been playing.

**Comment by ComicIronic** [comment]
>they refuse to work

This is really a feature request more than anything else. Mousetrap assemblies trigger when walked over, but since you don't "walk over" the assembly when it's attached to a bomb, you don't activate it.

It's a mild oversight of the code, but you can mitigate it by using a combined mousetrap/signaller signaller/igniter system.
Or you should be able to use infrared emitters or prox sensors.

**Comment by MercuryDoll** [comment]
yeah, trick was to boobytrap backpacks and such. seems extra effort and material with the two signalers needed, but it's not like science can't print them i guess. So i leave the "feature request" open to debate.

**Comment by 9600bauds** [comment]
If you can't step anywhere but directly on top of a soap in a 1x1 square then I'd say it's more than fair to allow mousetrap assemblies to trigger when walked over. It's just expected behavior.

**Comment by ComicIronic** [comment]
>it's more than fair to allow mousetrap assemblies to trigger when walked over

Mousetrap assemblies do trigger when walked over.
It's bombs with the assemblies that are the potential issue.

**Comment by 9600bauds** [comment]
That's what I meant, yeah.
If you're making a serious bomb, you probably have access to a proximity detector, so why not allow the ghetto option too?
