### ISSUE TITLE
The "I got an idea for wizard spells" depot

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3890]
Wizards are fun
but they are not fun enough
Here lets put up any and all wizard spell ideas.
Here are just some ideas
None HAVE to be added.
But putting ideas out there can lead to fun ideas for other things besides wizard maybe

**Ersuc:** Causes victim to move the opposite direction they intend to.

**Reverse Blink:** Like blink but for everyone but the wizard.

**Fist of the North Star:** Costs three spell points. Wizard can punch as fast as he can click.

**Release experiment:** teleports a buffed version of the experiment monster beside you who is loyal to only you.

**Freeze time:** Everyone and thing within your field of vision including stuff you cant see is frozen in time, including you for six seconds. Anyone who enters this field is subsequently frozen till the timer ends. This also includes objects or projectiles as they will simply stop in mid air

**Pomfdoras box:** An artifact like a box. Clicking it shows the user terrible visions. wacking someone with it will lead to instead you forcing the visions to someone else. Symptoms include: [Out of fifty chance] **20/50:** chance:10 second stun with 20u of mindbreaker **10/50:** 5 second stun 20u mindbreaker and player will start to spout screams asking to kill him **5/50:** 2 second stun 20u mindbreaker and have their eyeballs removed **5/50:** 5 second stun 20u mindbreaker, 100 braindamage **5/50:**They become a chicken **2/50:** 5 second stun 20u mindbreaker and if they try to talk they only scream **2/50:** Their eyeballs are removed and get an objective to jump into the singularity **1/50:** 5 second stun. Eyeballs removed. They become a cultist

What ideas you dudes got

**Comment by Exxion** [comment]
I assume ersuc is supposed to be curse backwards, but it isn't
And Fist of the North Star would be *very* bad if someone has a rapid clicker
I already know BYOND can fully support at least a dozen clicks per second as I sometimes rotate a chair at frightening speed out of boredom using my autoclicker
Otherwise pretty cool, though

**Comment by CptWad** [comment]
>I already know BYOND can fully support at least a couple dozen clicks per second as I sometimes rotate a chair at frightening speed out of boredom using my autoclicker

Well thats the fun of it. Watching a wizard gib someone just by punching them rapidly is hilarious but then again it is punching so the wizard gotta get up close and you cant punch borgs

**Comment by Arthurdentist** [comment]
An idea I have had for a while but haven't been able to even begin working on.

The Magic Cabinet (Or the Real Transported Man)

A cabinet that the wizard can create on the station, like the firebird he can only create it once. The cabinet comes with a spell which allows the Wizard to return to the Cabinet on a 60 second cooldown. Anybody on the same tile as the Wizard when he casts the spell will also be returned to the cabinet. The Cabinet is like any other closet on the station and can be welded shut or destroyed. 

The utility comes from being able to escape a situation much faster then the standard teleport spell, as you don't need to select your destination from a huge list, its a one way trip. You just have to ensure that nobody discovers where you hid the cabinet because it would be awful if you teleported home only to find it welded shut or shunted into the middle of space.

**Comment by SarahJohnson489** [comment]
For tele and tele scrolls you just have it prepped pre-fight. All you need to do is mash ok

**Comment by AutismSpider** [comment]
We have Subjugate for the direction stuff

This is a medium distance spell that makes your target stutter and not being able to move normally, like if they were drunk.
