### ISSUE TITLE
hardware for running /vg/station

### ISSUE THREAD

**Issue by abcdicks** [d3athrow/vgstation13#3892]
I want to run a small server [20 ~ 30 people] with your code. I plan on renting a Linux VPS to do so.

How good must be it? Not an issue, but whatever.

**Comment by CptWad** [comment]
@rizon #vgstation
Talk to deathrow
Or talk to pomf123 on byond
Both are same person

**Comment by BestName** [comment]
Nigga you just mentioned some random person, they're going to be confused once the email hits their inbox.
Also rizon isn't an IRC client it's a network, IRC client is what you use to connect to said network.

**Comment by abcdicks** [comment]
@CptWad 
Can't do. I have fear of talking to people directly, even on the Internet.

**Comment by CptWad** [comment]
@d3athrow get in here

**Comment by clusterfack** [comment]
It's run with like a 3.4 gHz cpu right now. (CPU is the only actual statistic that matters because byond).

We use about 25% of the CPU processing power each tick at a ticklag of .55 during standard play. The only real time when anything can or should lag is during certain endgame scenarios. 

So yeah even a relatively midrange computer should be able to run our code, the issue is just during periods of especially high stress. If you ever encounter lag during some high stress period use byond's profiling tool in dream daemon and post it here and I'll try to optimize it away.

**Comment by abcdicks** [comment]
@clusterfack 
Great. What about RAM?

**Comment by clusterfack** [comment]
I should have mentioned that due to the way byond works (doing all work client side on a single core), the only real bottleneck you should ever encounter is the CPU itself. Mid or low range hardware should suffice for any other component, getting a stronger CPU with fewer cores and setting all other programs to not use that core should give you the best performance.

**Comment by abcdicks** [comment]
Then would 1GB RAM work fine? :3

**Comment by clusterfack** [comment]
1gb ram, doesn't windows 7 use that much just to survive? 

Also I cant really speak to any cross platform capabilities or not.
