### ISSUE TITLE
Friendly Wizard Animate Staff

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3919]
I think the staff of animation should have an alternate setting, where the object's AI is friendly instead of hostile, and the spell never wears off of the object.

This way friendly wizards could use the staff to make pets for the crew out of any objects they wished.

**Comment by CptWad** [comment]
Or friendly wizards could not use the staff of animation.
If you have ideas for spells try #3890. 
IMO friendly wizards should just be wizards that don't "Hurt" anyone and just use spells that cause chaos. Not mingle with the crew and turn the round into a slightly magical extended. Shit is boring because very few people, usually including wizard, can into roleplaying
