### ISSUE TITLE
[Bug] List of issues with component_exchanger

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3927]
- It can't actually be made via the protolathe.

*data research may be too high*

- It only holds 10 items which is something of a bad joke.

*15 would be a bare below the red line minimum, 20 or 30 would be reasonable.*
- It has a menu that takes more time to use than it would to just click the damn items and go without.

*most of this could just be solved with examine*

- it's item id = "deviceanalyzer" from when it was copy pasted from the device analyzer code.
- It can't scoop parts itself and has to be fed with a gadget bag or by hand which is all sorts of convoluted.

*at this point the solution is worse than the problem.  I have to 1) print the exact items I need or make them into a neat little pile on the ground which involves checking the wiki or memorizing every machines components 2) scoop those exact components up in a bag and also hope the machine doesn't need more than 10 parts 3) fill the machine with better parts, hooray 4) repeat for every machine*

There isn't enough space to hold enough items to upgrade more than 1 or 2 machines at a time and you'll invariably end up with more than of one part than you need after a few uses, requiring you to go through the UI, dump the shit out, sort through the pile, scoop the stuff you want back and then put the stuff via a gadget bag back into the component exchanger then add the parts you wanted to begin with.

It needs a higher capacity like 30 to justify its material cost alone and it needs to be able to load items with the same functionality of a gadget bag without requiring a gadget bag.  This is more complicated than just disassembling the damn machines and doing it by hand and takes almost as much time as well.

@dylanstrategie

**Comment by dylanstrategie** [comment]
I'll forward fixes asap, most of these shouldn't be a problem to fix

**Comment by dylanstrategie** [comment]
Alright, from what I see I forgot to give the component exchanger design a new ID, so that prevented research. Data is on par with the device analyzer so that's not a problem

I'll up the container size to 20

The menu delay can't be improved that much. The fact you don't have to take the machine apart is a huge improvement

Actually having the component exchanger use bag behavior would be a pain in the ass. Right now you can scoop all components with a gadget bag, straight from the Protolathe, and then dump them in the component exchanger, and it works
