### ISSUE TITLE
Remove stungloves

### ISSUE THREAD

**Issue by ComicIronic** [d3athrow/vgstation13#3972]
They can be easily made using equipment available to pretty much anyone.
You can't disarm someone wearing them.
And a stun is already too powerful without needing to have to strip it off your opponent.

If we don't remove them, I suggest at least making it so that you have to hold the contact (like an igniter) in your hand, so that it's possible to drop the gloves and their stun effectiveness.

**Comment by Probe1** [comment]
was this precipitated by shadowmech88 getting scrubgloved while wearing an american pscyho syndie bundle?  

scrubgloves really suck sometimes but so does getting your head lopped off by an axeman.  i'd rather you didn't remove engineerings most viable way of stopping someone when their alternatives are pretty grim.  

as an alternative to removal, you could add a **small** chance for the stun to fail, or increase the drain to 1000 per use or something.

**Comment by ComicIronic** [comment]
This was mainly caused by the realisation that TG has already removed them for a damn good reason.

>RNG stuns

I find that minute RNG is rarely a good balance, especially in the case of stuns where getting the stun off or not is so crucial.

**Comment by Probe1** [comment]
It was an offhand thought I'm not married to it. 

If we're talking about whats good for balance though this could (and honestly) should lead into the entire long ass discussion we just had about stuns.  Lets say scrub gloves get nixed on account of being too stealthy for a stun weapon.  But then there's you know, parapens silencestings disintegrate which is like a stun glove except they fucking GIB, and a myriad of other ways you're going to get instantly taken out of a round with very little recourse or prevention if done stealthily.  So the balance/meta is still there, it's just being taken out of the hands of engineers and assistants (get it? hands comic HANDS).

Really though in my heart of hearts I don't like it because every time someone brings up something in relation to engineering, it's a nerf.  There's been like two things in 2015 that improved engineering.  The PDA Alert Monitor app and being able to add rcd_ammo to an rcd by point and clicking with the device.  Can't we have something nice for a change instead of watching coders ignore bugs or nerf the department?

**Comment by ComicIronic** [comment]
>parapens

Antag weapon. Also droppable. Also cannot be made (easily, anyways.)
>silencestings

Antag weapon. Also not available to pretty much any crewmember.

>disintegrate

Antag weapon.

The issue I have with stungloves is that they're available to everybody, and for being available to everybody they are too useful. If you really need a ghetto stun, make a stunprod.

**Comment by Probe1** [comment]
Add steps to the process so that they aren't available to just anybody?  Make it require engineering tape so it has some use other than watching people rip it down.

**Comment by ComicIronic** [comment]
I don't think that would solve the fundamental issue, which is that the stungloves themselves are invisible and cannot be disarmed from your opponent. In this way, they outclass most other melee stuns in the game.

**Comment by Probe1** [comment]
Give it a unique set of sprites that are noticeable?  

Unrelated thought:  make it drain battery charge at all times instead of just when in use, facilitating the need to keep incomplete until the moment you need it or recharge it fairly often.

**Comment by Manaony** [comment]
They already have (had?) a unique set of sprite and god help you if you touch a live wire with them on.

**Comment by ComicIronic** [comment]
God help you if you touch a live wire in most rounds anyways with the FRY SHITTERS tactic engies seem to take.

>unique set of sprite

Admittedly so, but they can be hidden under any suit which covers the gloves slot.

**Comment by CptWad** [comment]
I think scrubgloves used to only work on insulated gloves. That way they were an engineer only defense and only the few thrifty greyshirts could make them at the cost of not hacking shit without electrocution.
I think the most simple fix is just to reinstate the insulated only rule, or just make it so that if you use any other gloves it shocks yourself too, stunning both people comically.
I think TG removed restrictions because muh greytide bullshit

**Comment by Probe1** [comment]
Yeah that's really the problem with a simple solution, sprites no matter how well done will be hidden by hardsuits unless that is also changed and we're looking at a bigger and bigger job.

@CptWad I thought about that and from a balance standpoint it works perfectly fine for me.  It destroys the insulated gloves value as an insulator but its a weapon.  Non-insulated gloves stun the wearer the same amount as the person they stun.  But I held off on saying it because why would the live ends of the wires be making contact with the users skin?  It would work and it is a potential solution but it seemed strange when I thought about it.

**Comment by dylanstrategie** [comment]
Scrubgloves are extremely bad balance-wise. They are discreet (it's VERY hard to see if someone has scrub gloves, and impossible if they wear a hardsuit, compared to tasers or stun batons which are extremely blatant). They stun for a solid time compared to a push, are 100 % reliable, and put your opponent out of the fight for long enough to secure any weapons they might be using AND get a few jabs in, only to repeat immediately

Scrubgloves should obviously be removed, or seriously nerfed. If you want a ghetto stun, you should be making a stun prod, if you want a ghetto down, pushing or water exists

**Comment by Arthurdentist** [comment]
Perhaps you could make it so that you can't wear stun gloves whilst wearing a hardsuit / exosuit? I mean you got a honking big battery on your gloves and you are able to hide it under a firesuit? It would make the sprite more noticeable and harder to hide.

**Comment by Probe1** [comment]
I like the idea Arthur.

**Comment by MercuryDoll** [comment]
Why not give them spark effects?

**Comment by ComicIronic** [comment]
Sparks wouldn't help with gloves hidden before use, which is the most important point since stuns are one-hit.

**Comment by MercuryDoll** [comment]
i don't mean emitter-like sparks, i mean overlay spark animations, similar to genetic powers.

**Comment by Probe1** [comment]
@ComicIronic if you still want to move on this I'm fine with any and all of the ideas listed short of removing them entirely.

**Comment by AutismSpider** [comment]
reinstate the insulated only rule.

take a risk of getting shock/taking massive burn damage when using non insulated gloves for them

**Comment by SarahJohnson489** [comment]
I think it's alright as is. They're a potent equalizer when someone's being a griefing faggot, but not enough that the admins can do jack shit about, that lets you end the problem without killing the shit out of them to do so which gets you in trouble despite the faggot griefer grriefing. Especially when they have a better armament than you can easily get. I think anyone who's had the misfortune to be TJ's grief victim of the round can attest to, it's a no-win scenario. 

They have an obvious sprite to anyone who's used or been hit by them. You're already watching people you have beef with for such things and for those you don't have beef with it's fair game.

**Comment by clusterfack** [comment]
Except they are also hidden by hardsuits

**Comment by SarahJohnson489** [comment]
Well that's cocks

**Comment by Kurfursten** [comment]
@clusterfack Probably safe to close, since Comic was the only one pushing for this and he's mostly inactive now. He can reopen it himself if he still wants to provoke discussion on the matter.
