### ISSUE TITLE
(WEB REPORT BY: somhuan REMOTE: 198.245.63.50:7777) Medical cyborgs cannot fill beakers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4017]
>Revision (Should be above if you're viewing this from ingame!)
a3da7b07bffbdbadf47ea8fb130e892fc4537ba7 

>General description of the issue
Medical cyborgs cannot recover their beaker from machines

>What you expected to happen
To put the beaker into a chemdispenser, make chems, then store the beaker in my cyber body.

>What actually happened
The beaker popped out of the machine as it should, but I cannot store it, as "you cannot store something you are not holding". Now my 3rd slot is stuck and I cannot use it for anything or turn it off.

>Steps to reproduce if possible
Place a beaker into a machine as a cyborg.

**Comment by MercuryDoll** [comment]
Title is a bit misleading. The beaker module works as intended on the chemdispenser and chemmaster, even in combination with other beakers. The problem is that the physical beaker cannot be stored in the module slot again. Hence you're stuck with the beaker module using up one module slot since you cannot store the module again.

What the possibility of leaving the mediborg beaker lying around for other players to use is exceeds my imagination.

**Comment by Zth--** [comment]
This was fixed long ago
