### ISSUE TITLE
ERT/Deathsquad shuttle doesn't deploy

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#4028]
If you try to send an ERT to the station, you'll get the message "The strike team has not yet deployed" even though you did already prep an ERT for deployment and all that. Admins have been getting around it using the centcomm ferry.

**Comment by wwjnc** [comment]
This is not really a bug. You need to use the 'Send a strike team' (secrets menu) or 'Dispatch Emergency Response Team' (Special Verbs tab) for it to be enabled. Which is a terrible idea, because it forces you to jump through many hoops for just a simple thing.

IMO this stuff should be controlled through a computer at Centcomm, where an admin could handle everything IC (check vitals of the ERT/DS members, force move the shuttle, etc.)

**Comment by clusterfack** [comment]
I believe it is happening when admins DONT use the buttons, particularly for station requested ERTs

**Comment by Skullyton** [comment]
Considering the shuttle rework killed the "send shuttle" button, this can be closed.
