### ISSUE TITLE
Increase gibber meat returns & cloner biomass cost

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4032]
This is a two-part problem with a simple solution.
The gibber gives you three measly meat pieces per each whole live human you dump inside. That's pretty much next to nothing, which is part of the reason why most chefs get their meat from dionas or clonex.
Cloning is very cheap. This is in part because each clone only needs 150 biomass, which is 3 synthmeat or 15 blood + 3u clonex. You can even upgrade the cloner to reduce that amount to 50 biomass.
The solution? Put more meat on people's bones! Increase both numbers to something like 10 meat each.

**Comment by CptWad** [comment]
Ooo could we do it by portion?
Chest is three meat
Head is one
Groin is one
legs/arms are two
feet/hands are two
Also spits out a brain if there is a brain in there and a random select organ?
Glorious deep fried hearts

**Comment by Probe1** [comment]
You can get all the deep fried hearts you want from the organ fabricator (I think? I've never tried to deep fry one)

I'm totally okay with the gibber giving more meat.  That's a side issue to what I want to say.

Okay here's what I think on it.  Couple threads ago when  I said you don't want to think about the balance of a big bite burger costing 5 meat and a real human bean costing only 3.  Adding a higher biomass requirement per cloning would rectify that but it would do it in the least interesting way.  It's just adding a few more clicks for doctors and would only really affect the people that are too lazy or bad to use clonex for synthmeat.

What I think it needs is additional reagents.  A beaker of clonex or some novel chem, or item, that is required and expended when you clone someone.  Something that adds more depth to the cloning process and encourages players to treat rather than clone.  Adding more biomass is just going to mean we actually use up the 3000 biomass we add at round start instead of only using half of it.  

So that's what I think.  Increase the biomass sure, but also add some ingredient.  A beaker of clonex and it using 10-30 clonex for each clone would be something to consider.

**Comment by CptWad** [comment]
Using clonex over meat is much more better IMO since it removes a step and requires you to refill beakers.
To add to my comment I meant more for gibber produce not general use

**Comment by Probe1** [comment]
That would be nice to get a random organ which saves you the trouble.

**Comment by MercuryDoll** [comment]
I agree on both though. double the meat requirement and add the necessity of clonexadone. I still think the possibility of a missing limb or a damaged organ from cloning would add on it, but this will do.
Also always more meat from gibber.

**Comment by Probe1** [comment]
There needs to be a limit and reattaching limbs and fixing organs is going to eat up a lot of time that doctors won't have.  Then people will complain and it'll get reverted for being too much.

**Comment by Scottzar** [comment]
The base issue (unless gibber code was changed when I wasn't looking) here is that gibber meat is 'balanced' around returning high nutriment meat, while the synthmeat is always 3 nutriment.
Indeed, a related problem is that gibber meat can easily hit over 50 nutriment, and you lose reagents to the aether because the meat can only store 50 units.

**Comment by Probe1** [comment]
@Scottzar check this out https://github.com/d3athrow/vgstation13/pull/3513

the nutriment cap was increased to 100 and the nutriment values of raw ingredients are carried over now so that issue is mitigated somewhat.  At least to the point where it doesn't really matter if you're losing a little nutriment.  You're can still make a meal that can make three people fat.

**Comment by MercuryDoll** [comment]
perhaps we can base biomass on nutriment points of the meat?
