### ISSUE TITLE
Suit Storage Units don't decontaminate their contents now

### ISSUE THREAD

**Issue by wwjnc** [d3athrow/vgstation13#4034]
UVing the contents only cleans the blood on them.

**Comment by Probe1** [comment]
I don't think they have ever removed plasma contamination.  You have to use a washing machine.  What it was meant to do and actually does is unknown to me.

It would be awfully convenient if they did remove plasma contamination since engineers have to walk all the way over to arrivals for the washing machines.

**Comment by PJB3005** [comment]
You can't put hardsuits inside washing machines @probe1

this goes for a lot of stuff like magboots to jackboots

**Comment by wwjnc** [comment]
Yep, hardsuit stuff doesn't fit into washing machines. You never had to clean the contamination from engineering hardsuits since they used to be plasma-proof.

**Comment by Probe1** [comment]
Okay so there's two bugs.  The old one - UV decontamination in a hardsuit storage unit does not clean plasma contamination and hardsuits can now be contaminated by plasma.  As pointed out there is no way to clean plasma off a hardsuit so this is a big problem.
