### ISSUE TITLE
(WEB REPORT BY: uqualm REMOTE: 198.245.63.50:7777) There aren't enough antags

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4063]
This is a feature request.

There's a trend where a round starts with 20 or so people ready and in an hour there are 50 people in the round. At this point there is 1 or 2 antags when there should be more with the active amount of players. Most of the time the active traitors have left the game, gone braindead, or have been caught. This quickly turns the round into Extended and the round goes on for a long time. This happens a lot in Vampire mode especially. After the long round ends, nobody joins again because they just played a 4 hour round with nothing happening. It's 20 people declaring ready again, and people slowly come back again, and the cycle repeats. 

I'm suggesting you re-add the tensioner. Either in its old state or a modified state. Also make some functional crew transfer vote.

**Comment by Kurfursten** [comment]
The functional problem with the Tensioner is that as time goes on, three security members will probably dwindle to 1 or even 0. Braindeads, kill/stripping officers, or even rarely job changes. It's very rare to see a sec team prepared to deal with more antagonists later rather than sooner in a shift.

**Comment by d3athrow** [comment]
we've been ignoring adminhelps about security outside of excessive brig times or executions for a month nearly, how people are still getting bored with the job with the 'sheer amount of greytiding' i dont know

**Comment by Uqualm** [comment]
You can adjust the tensioner formula with amount of active security or something. Also you're not accounting for people late joining as security either. 

Playing as sec is like getting antag in reverse. It's no fun if there are no antags as there is nothing to do. Nobody wants to be security in a 3 hour long extended round. As more antags come more people will see the need for security.

Also literally just happened now. 
53 players. Vampire round. 2 vampires. Both failed. Round lasted 3 hours. New round starts and there are 20 people in the lobby.

**Comment by Uqualm** [comment]
Or at the very least make every game mode asides from cult and revolution auto.
AutoVampire, AutoChangeling, etc.

**Comment by IratePirate** [comment]
In my opinion every 15 minutes in traitor mode a new person should be auto-traitored (without access to uplink), in Nuke Ops, Blob and Heist there should be at least one traitor on board, and changelings and vampires should never be the only antags in a round. SS13 should be a lot more threatening than it is with all these 3 hour rounds. Security should be overhauled in some manner to encourage their use. Even if Security numbers don't increase more antags should be a thing anyway because our server's validhunting culture pretty much accounts for them in most cases anyway.

**Comment by Probe1** [comment]
@d3athrow 
>we've been ignoring adminhelps about security outside of excessive brig times or executions for a month nearly, how people are still getting bored with the job with the 'sheer amount of greytiding' i dont know

Punishments are pretty pointless for the most part.  No ones scared of 5-10 minutes in the brig.

**Comment by Probe1** [comment]
I'm closing this because it's old and but also because sarca made it.
