### ISSUE TITLE
(WEB REPORT BY: icycharm REMOTE: 198.245.63.50:7777) Disappearing Diona Plants

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4127]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Diona replica pods diappear before maturing. To clarify, they do not die, they do not result in a dead diona nymph, they just straight-up disappear.

>What you expected to happen
I expected some diona nymphs and so were the ghosts flickering my lights

>What actually happened
Wasted seeds

>Steps to reproduce if possible
Plant some diona seeds, get nothing

**Comment by Probe1** [comment]
Were bees involved?  I'm not sure if the issue is still open but there was a link between bees over fertilizing diona pods, causing them to never grow to the big green roundish stage and eventually disappear.  They were getting like 11/10 fertilizer level, bugging out and disappearing I think.

https://github.com/d3athrow/vgstation13/issues/3328

https://github.com/d3athrow/vgstation13/issues/3182
