### ISSUE TITLE
(WEB REPORT BY: fudgepucker REMOTE: 198.245.63.50:7777) Cable coils can not be added together.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4156]
>Revision (Should be above if you're viewing this from ingame!)
e540c

>General description of the issue
Cable coils can not be clicked on with cable coil in hand to merge them together

>What you expected to happen
25 length cable coil

>What actually happened
one 10 length cable coil and one 15 length cable coil

>Steps to reproduce if possible
Click on a cable coil with a cable coil.

**Comment by ComicIronic** [comment]
Figured out what this is likely to be: ever since we moved to strict pathing for stacks (why, lord, why) you can't stack different coloured cables. You also can't stack the same colour cables if one came from, say, a cut floor cable, because it won't be of the original type.

Segregation nation is ruining the game.
