### ISSUE TITLE
Deep fryers spawn empty, but only roundstart ones

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4160]
I can't for the life of me figure this one out. The deepfryers that spawn at roundstart will be completely empty, but if you spawn in a new deepfryer from the debug menu, they will have 300u corn oil as intended.

**Comment by wwjnc** [comment]
Deep fryer's `New()` only initializes its contents if `ticker` is not null. Seems like 4d8c8b37bdf3c1a0f5737482637455e56462c9d6 introduced this.

**Comment by 9600bauds** [comment]
So how do I fix it

**Comment by 9600bauds** [comment]
Pls to respond, I want to fix this but I have no clue what this ticker business is

**Comment by clusterfack** [comment]
Okay so here's the issue. The ticker initialization is what happens when the round starts or some shit like that, so that all the objects being placed on the map don't cause the original startup to be super slow which is why esword made the ticker make reagents.

However thanks to inheritance he made the initialize recreate the roundstart reagents thereby destroying the corn oil that was added. So just remove new entirely in this instance, and have
>initialize
..()
add_reagent(cornoil)
