### ISSUE TITLE
Balance issue: Emag

### ISSUE THREAD

**Issue by Manaony** [d3athrow/vgstation13#4176]
After playing several months I feel like the emag is too good. Infinite use, both in charges/recharge rate and different utilizations, it's also extremely cheap as far as traitor gear go. I feel like they could be balanced better.

**Comment by Probe1** [comment]
It needs to have its recharge rate adjusted.  It's effectively infinite uses because it recharges faster than you could possibly use it.  This was not always the case.  

It has since become the go to purchase because it works on everything and has few downsides.

**Comment by Exxion** [comment]
I thought it was set to *be* infinite use. I remember looking at the code and seeing an infinite-use variant, at least, which I had assumed was the one that's in-game.

**Comment by clusterfack** [comment]
It actually just has a preposterously high recharge rate set by one of pomf's config files

**Comment by Kurfursten** [comment]
It actually has a warning system built in to show you when you're getting low, but few have ever seen it due to high recharge rate.

As a matter of general thought, I feel the emag has become a bit bloating with uses. It would be nice, for instance, to be able to hack a juke without an emag.

**Comment by TermedClepe** [comment]
Strap a literal battery onto emag, it now needs 3k charge per use and doesn't autorecharge, you can replace the battery with a better one or stick the emag into a regular weapon charger to recharge it.

**Comment by Uqualm** [comment]
>This shit again.
Wow. How many times do we have to have this argument? This has been discussed a billion something times and the whiny dylan tier nerfers always lose out in the end. 

Also

>I feel like they could be balanced better. 

You say this as the cult game mode exists in its current state. L O L.

**Comment by Uqualm** [comment]
>I thought it was set to be infinite use. I remember looking at the code and seeing an infinite-use variant, at least, which I had assumed was the one that's in-game.

It has been since 2007. Nexis got mad because a traitor ruined his round and added charges to it. This upset Pomf so 

>it has a preposterously high recharge rate set by one of pomf's config files

**Comment by ComicIronic** [comment]
Ideally, the emag should simply perform convenient hacking on a machine,  rather than having special functionality for machines like the jukebox.

**Comment by CptWad** [comment]
Most people find issue with doors. How about only fix the door issue then have infinite use for everything else?
If you want to emag every arcade machine in your arcade of death thats cool but emagging every door is hated mostly because its so hard to fix the damn things that people resort to walling off doors rather than repairing them.
I see two ways
>Nerf emag to reduce the amount of doors it can open rapidly

or

>Make two seperate items. One fun one that emags everything IE jukebox fire alarms shuttle console but no doors and then make a new door jacking item that jacks doors exclusively. Door jacker is two crystals and new emag is two as well

**Comment by Uqualm** [comment]
WAHHH WAHH WAHHH BAD TRAITOR OPEN DOOR
MAKE ME SAD
MAKE IT SO DOOR NO MORE OPEN

TATOR GRIEFING ME!!!

**Comment by PJB3005** [comment]
Emags kinda need a nerf, seriously.

**Comment by 9600bauds** [comment]
When people complain about emags having infinite uses, it's usually because of emagging airlocks. We oughta try fixing that first. Why does it fry the circuit anyways?

**Comment by PJB3005** [comment]
You're essentially rubbing sparks against a circuit board, maybe it wouldn't be as badly burned as the emagged sprite for the airlock electronics, but it would be basically unrecoverable.

**Comment by clusterfack** [comment]
It fries the circuits because the emag was originally balanced around causing troubles for engineers and NOT having infinite uses.

**Comment by Uqualm** [comment]
The emag has had infinite uses since I have been playing in 2011.

**Comment by Uqualm** [comment]
>Someone so butthurt they needed to censor all of my comments
Top kek. I wonder who it could be.

**Comment by VelardAmakar** [comment]
"oh god i'm being censored gamergate please help me :cry:"

**Comment by MercuryDoll** [comment]
I can see two ways: 
* reducing the amount of doors you can rapidly hack, whether by adding a snowflake code for airlocks or actually making recharge vital again.
* increasing the TC cost of the emag drastically.

And i'd like the idea of making the results of emagged machines like the jukebox and deepfryer available via regular means of hacking.

**Comment by ComicIronic** [comment]
One way would be to simply make airlocks take more emag charges every use.

**Comment by Probe1** [comment]
It's not just about doors that was just an off comment based on everyone understanding what I'm thinking.  Emags as Kurfursten said are literally used on EVERYTHING.  They're the nutella of syndie items.  

I like the idea of having a effective charge.  I liked @TermedClepe  's idea of having a literal battery.  dylanstrategie would appreciate that.  desire to get batteries would increase a lot.  

I wouldn't focus on how to improve emagging airlocks.  That's small time.  The problem is the emag itself not a single situation its used in.

**Comment by IratePirate** [comment]
It's always been far too good, and what makes it worse is that people keep adding functionality to it when they add new shit to the game. With a 3 TC emag you can fuck up the station single handedly by opening every single door.

Nexis added a system that limits to an automatically recharging battery so that should be in the code somewhere to be used.

**Comment by SangriaMonkey** [comment]
Just bump the price up.

**Comment by 9600bauds** [comment]
That fixes nothing.

**Comment by Kurfursten** [comment]
@IratePirate I'm halfway done with a new tool that will help that particular situation significantly, so at least the door situation won't be so bad anymore.

**Comment by mrpain666** [comment]
I feel the cost is fine, I do think the recharge time should be significantly increased though, that or lower the "charge cap".

**Comment by SangriaMonkey** [comment]
It should be a powerful *investment*. Most of our traitor items are never used because they're too situational and people would rather go for lower risk alternatives they can make themselves on-station. *Making everything equally bad isn't balance*. I can't stress that enough. Up the cost, make the other items more viable, and this would be less of a problem.

**Comment by 9600bauds** [comment]
There'd still be emag abuse, the item is broken in certain ways and upping the cost doesn't do much except putting the abuse behind a tiny investment. The ways that the item is broken in need to be addressed first.

**Comment by Kurfursten** [comment]
My new soldering iron tool #4205 should offer relief to our engineers over emagged doors

**Comment by Probe1** [comment]
It's important for me to reiterate a second time that repairing the doors is half of the equation.  Being able to get through every single door on the station, instantly without any concern, is the second half.  There's no need to be careful or tactful with an emag, which was fine a long time ago when it wasn't an omni tool but now that it is, that should be addressed.

**Comment by Probe1** [comment]
@Kurfursten it's only been two months but it feels like the soldering iron has always been a part of the game.  Well done on that.  Really well done.
