### ISSUE TITLE
Engineering airlocks won't open for engineering access, only atmos

### ISSUE THREAD

**Issue by Morriak** [d3athrow/vgstation13#4206]
This airlock labeled as engineering that leads to engineering, only opens for Atmos access. Engineering access doesn't open it.

http://i.imgur.com/e1OFxUI.png

**Comment by Morriak** [comment]
I just checked and it seems like NONE of the engineering doors actually open for engineering access

**Comment by Probe1** [comment]
I had a look on a local server.  They require power equipment access, not engineering access.  My last repo was from 

I was running a local server off a 7 day old repo so assume this bug was introduced a while ago and no one caught it.

![image](https://cloud.githubusercontent.com/assets/8550416/7410351/0a5a3274-eefc-11e4-94b6-e7069c24bf7d.png)

**Comment by Morriak** [comment]
weird, I made a card with literally just atmos on it and that worked too

**Comment by Probe1** [comment]
Yea when the access board has green letters it means you can have ONE (any of the access requirements), when it has red letters it means ALL (you must have all the access requirements, in this case Atmos + Power equipment)

Anyway someone fucked up.  Probably a long time ago I vaguely remember giving someone engineering access as Hop and they said it didn't work ages ago.

**Comment by Intigracy** [comment]
Fixed at some point, please close.
