### ISSUE TITLE
Cloning is Too Easy

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#4307]
There's no fear of death in the game, because as long as a person's body gets found, they can be brought back to life with a few clicks. Cloning is certainly necessary at some point because of the rare cases of people who get 500 burn damage or something like that, but the existence of defibrillators means that most patients are revivable with meds+bloodbacks+surgery. But hardly anyone ever does this because the cloner is easier with no penalty.
I think at the very least, the cloner shouldn't be there at round start, and should be a max-research machine that the mechanic has to build for Medbay. That's not much since Science has research+minerals 20 minutes into most rounds, but it's a start. Mainly I just think cloning should be changed so that it's a LAST resort, rather than a first one. Make bringing people back to life a little harder than operating a microwave.

Maybe people would be more afraid of dying if it'd send them on Medbay's wild ride instead of them just having to be popped into the cloner and then into cryo.

**Comment by PJB3005** [comment]
Yes, this please

**Comment by clusterfack** [comment]
Apparently some people don't remember the time Dylan changed cloning to be 10 minutes long.

**Comment by Praecordia** [comment]
why do we always get people saying cloning's too easy
we have biomass and it takes like 10 minutes now or whatever
it really doesn't need to be changed

**Comment by 9600bauds** [comment]
One of the problems with cloning is that it's supposed to have side effects, namely: Brain damage, genetic defects, and messes up your appearance slightly. The latter of the two were supposed to actually require Genetics to get you a clean S.E. and restore the appearance from your old body.
However, 1u Rye cures all your defects, Alkysine heals your brain damage extremely easily, and most people don't even notice their appearance was changed.
Making cloning slower just promotes speedcloning, making cloning require more biomass/whatever just makes it more tedious. I think if cloning is to be nerfed, it should be by making these side effects harder to fix.

**Comment by Kurfursten** [comment]
I'm not sure that cloning should be nerfed, but if it were to be, an easy way to nerf it would be to add fracture chance / organ damage chance.

I sure wouldn't want to clone someone if there was a chance they'd pop out with 5 separate surgeries required.

**Comment by 9600bauds** [comment]
Maybe just make heavy brain damage require surgery to fix, to give an extra step to cloning. I don't really like that Alkysine is a magic one-pill cure, and I can't remember the last time someone used Impedrezene.
Even if noone can give you surgery you'd still be back in the round, just retarded.

**Comment by Probe1** [comment]
@Praecordia 
>why do we always get people saying cloning's too easy
we have biomass and it takes like 10 minutes now or whatever
it really doesn't need to be changed

That's what I was getting at, it doesn't take ten minutes.  It doesn't take any minutes.  Swipe your medical access ID on the cloner, eject them immediately and stick em in cryo.  

And as far as biomass goes.. well it's either 30 units of clonex and a monkey to draw blood from or 60.  Biomass is a dead end that doesn't make it harder and can only make it more annoying for everyone involved.

**Comment by Probe1** [comment]
After thinking about it, I like the organ and bone damage route.  It adds a step, *greatly* encourages players to leave people in the cloner for the full duration to reduce the chance of surgery required side effects instead of popping them out immediately, and makes cloning less of a go to choice without entirely reworking the concept.

**Comment by FudgePucker** [comment]
It depends on the chance.
If you have the chance for bone failure and organ failure too low, then they will just kill them again to put them back into the cloner.

If you have it too low, then it still wouldn't be worth fixing damage, just fucking kill and clone again until it comes out right.

**Comment by TermedClepe** [comment]
Why would you want people to stay effectively removed from round for a longer period of time?

Playing is fun, watching a black screen for 10 minutes as newbies try to fix you is not.

**Comment by 9600bauds** [comment]
Because:
>There's no fear of death in the game
And because it's really shitty to have basically any advanced part of your job invalidated by the easier option. Why even bother with surgery or blood transfusions then the good ol' circsaw+clone can fix anything in 2 minutes?

**Comment by TermedClepe** [comment]
How about buffing surgery and blood transfusions instead of nerfing cloning?

Surgery steps take way too long, blood transfusions give way too little and way too slow.

I think the core of the problem is that cloning takes too long, and even if you wait out the whole time you're still left with the same result - clone damage, that's why it's better to just skip the waiting time and get to fixing the unavoidable cloning damage.

Solution to this could be removing the ability to interrupt a cloning process, any interruption would result in the clone dying.

**Comment by IratePirate** [comment]
I would just make it so there are more ways to more easily sabotage cloning for antagonists. It shouldn't be in quite as secure an area where geneticists can see it and you should be able to poison it like cryo.

**Comment by Probe1** [comment]
I don't know what you're talking about Clepe surgery is fast as fuck.

**Comment by PJB3005** [comment]
^

Seriously surgery isn't hard/slow at all

**Comment by FudgePucker** [comment]
>Why would you want people to stay effectively removed from round for a longer period of time?

The problem is that death has no downsides.
You don't have to worry about dying, all hostage situations are pointless.
Antag got a gun pointed at someones head telling you to not get closer?
Charge at him with scrubgloves, you can just clone the guy.
Antag shooting at you with a laser gun and you are just a lowly scientist?
Just fucking charge at him and spam disarm, they can just fucking clone you.

The games atmosphere of fear and paranoia is pointless when there is no fear of death.

**Comment by TermedClepe** [comment]
>Seriously surgery isn't hard/slow at all

I played purely surgeon for a very long time, I know that surgery is really easy but slow and should be made faster by making the steps take at least half the time, perhaps even less with the preparation steps.

>The problem is that death has no downsides.

Dying to an antag will always put you out of the round for a very long time, he will hide your body or head most of the time so you don't snitch, your corpse will also get looted.

Dying is not the issue here, the issue is that cloning can be interrupted for the same result as finishing it and that fixing organ damage takes too long.

**Comment by Kurfursten** [comment]
@TermedClepe Given that Sterilizine currently does nothing, I've been considering having it improve surgery times when tools are doused in it

**Comment by PJB3005** [comment]
>improve surgery time

Logic = 10/10

**Comment by 9600bauds** [comment]
@Kurfursten Sterilizine was made to do nothing because infections from dirty surgery were removed, the current way to speed up surgery is through R&D advanced surgery tools

**Comment by FudgePucker** [comment]
Maybe add better meds requiring materials not avaliable at round start.
Peridaxon could have a complex formula, also requiring diamonds, it would make medbay able to fix multible people with fucked organs when the ride goes over drive instead of just killing and cloning.
Maybe have a better method to regenrate blood other than iron, requiring you to use silver to make a better drug for it.

This would be even better for traitor chemist because they have more drugs to "accedently" OD someone in cyro and pills. Also gives them an excuse to get mats for more fun stuff. Lexorin uses up plasma instead of just using it as a cyatalist, meaning that you have to use your small supply of plasma up, you can't really ask for more because the only useful drug that uses plasma is Oxycodone, and its use is not that great.

Adding more fun things for the chemists to make would be intresting.

Fuck goof chem we should have /vg/chem. Imagine all the fun toxins that you could make with diamonds and silver.

**Comment by Kurfursten** [comment]
@PJB3005 You know this is the game where you make an EMP in a beaker with ground uranium right?

**Comment by FudgePucker** [comment]
Oh how about a chemical that fixes internal and external bleeding that also causing burn brute and toxin damage involving uranium?
Thats another material that chemists can't get but scientists can.

**Comment by TermedClepe** [comment]
@9600bauds

People never get given blood packs because blood transfusion is extremely lack cluster. You have very little blood available, it takes ages to transfuse it, you can't see the blood type on med scanner and have to check records or use surgery table, you can't attach an IV drip to bed so they both move together, your patient keeps getting bumped into or dragged etc.

I would say lack of blood is vast majority of "lets just clone him" cases.

Buff blood and surgery, remove cloning interrupting.

**Comment by 9600bauds** [comment]
We're beating way around the bush here. Cloning invalidates the doc's job, so we're suggesting to kill the ride so that there's nothing left to invalidate.
I get that "don't nerf stuff, buff other things" is a good policy but I'm annoyed that the supposed downsides of cloning (brain damage, genetic defects) are so easy to fix they're practically negligible. I don't think it's unjustified to tweak those downsides to make them actually matter, then, if cloning is still too good after that, sure, we can buff other things to level it out.
The issue was also "cloning is too easy", making other stuff even easier doesn't fix that.

**Comment by FudgePucker** [comment]
The question is that should we buff medbay where a pill can heal everything faster than cloning and cyro.
The problem with super chemicals is that they can be used in any situation. Where as a cloner is a clunky 3 part machine.
I say fuck it, let the chemist have some super hard to make drugs that out paces cloning 10 fold.

**Comment by Probe1** [comment]
I don't understand where you're coming from at all @FudgePucker .  Chemistry is STRONK.  Surgery is easy and pretty fast.  Blood recently got a huge buff with orderable blood packs, making it feasible to have more than one IV line running into a 'lost cause' case instead of cloning.  

But cloning is still the go to "He has a broken hand but cloning a new person is faster and easier".  I don't understand what chemistry has to do with that at all.  "Super hard to make drugs" already exist thanks to the nature of stacking healing chems.  When you give a guy beaten to crit a tricord-DD-bicard-dex+ pill he perks right up.  I believe that qualifies as super hard to make as far as an open source station goes.

**Comment by FudgePucker** [comment]
Organ damage can only be healed by a chemical that is unobtainable outside of xenoboatany.

Being a traitor chemist sucks. It just sucks.

Oh hey you have to do all your work in the middle of one of the most busy areas in the game and have no elbow room or access to fun things that let you do crazy things. Oh? Over a few airlocks? Oh that's just the scientists with their bluespace beakers, plasma and uranium, and EX grenades.

Having super chemicals that requires materials would give a traitor chemist an excuse to make better toxins.
If you are a chemist and you ask for uranium, the miner will most likely put his pick ax though your face for his valids, OH BUT THE SCIENTISTS GET 1000000000000000 SHEETS OF IT.

**Comment by Probe1** [comment]
I have no idea where you're coming from with that and my year of experience says everything contrary to it.  

You have an excuse to make fuckhuge grenades and no one is going to check on you or the contents of them.  As long as you can VAGUELY look like you're working you're free to make stockpiles of lethal chemicals like you're Doctor Thrax from C&C Generals.  You can fit these in pill bottles, and pill bottles in a belt as well as beakers so you have effectively unlimited space for poisons on you.  As well as long as you don't get caught, you can name them 10u tricordrazine or whatever you please to pass a glance.

I have no idea where the mining stuff is coming from, I've never had a miner (or RnD for that matter since it's usually faster to ask for a few sheets) refuse me a polite request for uranium or plasma.

**Comment by FudgePucker** [comment]
Science has FUCKER HUGEST grenades, and better beakers, and rapid fire syringe guns.
All a chemist has is medbay access to put fake pills into the fridge and the cyro.

Having more meds to "accidentally" put into cyro that "accidentally" OD people and kill their livers would make it more even with science.

**Comment by 9600bauds** [comment]
guys

cloning

**Comment by clusterfack** [comment]
You know what some of you guys posting here may be antags so I'm just going to kill you all and clone you if I can prove you are innocent.

**Comment by Probe1** [comment]
too much work, just stick them in cryo, eject them once they're knocked out and strip em then leave them in there while you loot their stuff.

**Comment by 9600bauds** [comment]
Sounds good, I like the brain damage thing too, though.
Maybe nerf Rye a bit, so Genetics actually has to give clean S.E. to clones?

**Comment by FudgePucker** [comment]
Hey, hey bauds.
Why do you think everyone in medbay has cloning access?
I mean, its the genesists job.
Its not like before that change, genetics didn't spend all round ignoring bodys.
We should have something that requires genetics to do something other than look for hulk power.
Awesome idea, I think our player base is ready for this change.

**Comment by TermedClepe** [comment]
@9600bauds
>The issue was also "cloning is too easy", making other stuff even easier doesn't fix that.

Most of everything in this game is too easy, you can have max research and be shitting out phazons in 20 minutes, you can power the entire station several times over in 15, you complete your entire fucking job as a miner in the first 10 and get paid thousands of credits on top.

Compare this to the time it takes to fix up a patient that has the most common injuries: major bloodloss, a broken bone or ruptured lungs.

How long will it take to treat that? Bloodloss alone is a death sentence in most cases since it's so tedious to fix, doing surgery on more than one body part results in patient going braindead out of boredom. Whenever I get a broken hand I rather bandage it and ignore it than go to medbay because I know how fucking long it takes to get fixed.

It's comedic that the issue report itself states how fucking easy science is in comparison.

**Comment by Arthurdentist** [comment]
I don't understand people's obsession with making medbay more tedious then it already is and I am not about to understand it. 

So to bring this back to Cloning instead of Science: I vote don't touch.

**Comment by 9600bauds** [comment]
@Arthurdentist It's less about Medbay being tedious and more about cloning being a much, much easier and cheaper alternative to everything else.
Imagine if the AME was 100% safe, produced enough energy to power the station at roundstart, and only needed to be fueled once. Nobody would use anything else, right?

**Comment by Arthurdentist** [comment]
To remove or nerf cloning in the ways you are suggesting is to make medbay more tedious, that is all it does, create busy work. I don't believe Medical needs anymore busy work then it already has. Its not uncommon to see Medbay swamped with people and Doctors having a hard time dealing with it because they either don't have the skills or because of the sheer number of people there. 

I couldn't point to specific changes because it has been a long time now, but when I first started playing Medbay was one of the areas I spent a lot of time in, specifically surgery. If surgery is tedious now then the problem is with changes made to surgery and the way blood loss is dealt with. Having a punctured lung didn't used to be the death sentence it is now, these things didn't used to take as long to fix either. I think it would be more constructive to look at surgery and consider how to improve that instead of removing or nerfing the cloner because 'nobody uses anything else'.
