### ISSUE TITLE
Chameleon Gene Doesn't Work For Vampires

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#4314]
Be vampire, get chameleon, nothing happens. They remain completely visible even when not moving. Possibly related to the fact that vampires can get shadowstep which alters their transparency, but I didn't have it at the time and I'm not a coder so I don't really know.

**Comment by CptWad** [comment]
Genetics used to have the shadow walking as a gene
However it never played nice with the chameleon gene
So it was removed
Chameleon + shadow walk = bad things

**Comment by d3athrow** [comment]
most likely a conflict with shadow walk

**Comment by Shadowmech88** [comment]
Moved to Gitlab.

**Comment by Shadowmech88** [comment]
Moved back to Github.

**Comment by FudgePucker** [comment]
My theory on it is that when a vampire has not enough blood to have shadowstep it goes 'welp not enough blood for cloak no invis for you.'

So when you have chameleon 'not enough blood for cloak, chameleon? Fuck that noise'

What are the interactions between chameleon and shadowstep? Isn't shadowstep a toggleable ability and chameleon permanent as long as you have the gene.

**Comment by dylanstrategie** [comment]
Both Vampire Cloak and Chameleon were coded by morons who thought they could just hard reset a mob's alpha without checking if something else is affecting it first

So it's going to need a bit of work to fix properly

**Comment by DeityLink** [comment]
The issue is due to vampire powers being handled after mutations. The opposite would cause chameleon to override vampire cloak.

**Comment by FudgePucker** [comment]
Crazy talk right now, what if you just added the transparency of both? So cloak of darkness is like -x based on light level and chameleon is -x alpha based on how long they have been standing in one spot, why not stack them both on top of each other with a limit on how low it can get so it doesn't over flow?

That way chameleon and vampire cloak stack on top of each other instead of canceling each other out.

Please note that I have no fucking clue on how you would do this or if it is possible.
