### ISSUE TITLE
Allow AI to use vending machines

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#4328]
This is super silly and I think it's dumb. Especially letting someone in somewhere and being unable to help them because the vending machine they wanted to get to refuses to let me use it.
Maybe it's there for a reason, I don't know.

**Comment by 9600bauds** [comment]
AI LAW 2 BUY ME 4NORAISINS

**Comment by MercuryDoll** [comment]
It also makes sense because why should a simple item vendor be wifi-connected to an AI?

**Comment by Ephx1** [comment]
It's connected to the powernet via magic and to the accounts database , it's not a stretch to think that the AI can use it somehow.

**Comment by MercuryDoll** [comment]
Ah, true. So vendors do come with WiFi.

**Comment by FudgePucker** [comment]
But then we would come into issues of people using the AI to get dem yellow powergaming gloves.
"AI open up into engineering and then get the yellow gloves for me after I put the coin in."
It adds a bit of human drama to it when they crawl to a medivend only to have it flash that big red screen in their dying face.

Also AI and cyborgs shouldn't be able to buy items from venders that charge.
"AI law 2 sit here and get me carpotoxin polyacid and sleeptoxin plox"

**Comment by Ephx1** [comment]
I'm pretty sure engivends and toolvends are already all-access use considering their placements in primary tool storage. I was leaning on the medical side of vending machines.

**Comment by FudgePucker** [comment]
Not the engivend.
The two things in primary tool storage are vendomat with timers and such and the toolvend.
Although I now realise that it is the toolvend that has the coin gloves. Boy aren't I an idiot.

I still think that AI and cyborgs shouldn't be able to buy from vending machines that charge cash.

**Comment by DeityLink** [comment]
>The vending machine refuses to interface with you, as you are not in its target demographic!

I think we can take into account the possibility that vending machines (lore-wise) were hard-coded with AI/borg deny behaviours, since goods take money to produce and their manufacturers want to make sure that the crew isn't going to try and get their products for free.

So I'm going to code a middle ground: Silicons can now "purchase" free items on vending machines, so that means every items on engivends and most other vending machines, howether they cannot purchase items that cost money (most foods). With one snowflake: MoMMI can purchase coffee.

**Comment by Ephx1** [comment]
Sounds cool, thank you
