### ISSUE TITLE
Plastic flaps are ridiculous

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4332]
Most objects (including fucking spacepods, apparently) can pass right through them, but they are still somehow airtight. It doesn't make too much sense that they are airtight to begin with, but it's been that way for so long, it can't really be changed.
What if, though, they allowed gases through when an object is actively passing through them (basically, when an unanchored object is on the same tile)? Even if it's at a decreased rate. But plastic flaps make no sense and are way OP as they are.

This is more for discussion than anything, as I'm sure many people will disagree.

**Comment by PJB3005** [comment]
I don't think a 'decreased' rate for gasses passing through is possible with ZAS, can't speak for LINDA/FEA.

Yeah though seriously, plastic flaps are dumb, they should only really be used in stuff like mining where  people can't be bothered to go inside and unload their crate there

**Comment by Exxion** [comment]
I'll admit to being part of the problem
My first PR was fixing the trading post so that simply using it didn't gas the vox
This involved the use of flaps

**Comment by PJB3005** [comment]
Yeah, you can't really do a whole lot in those kinds of situations, sadly

**Comment by 9600bauds** [comment]
It's not realistic, sure, but I don't see how they are a problem

**Comment by FudgePucker** [comment]
Its not realistic, but plastic is very rare.
10 plastic in mechanics can make 100 diamonds.
Plastic is such a pain in the ass to make that it is ballanced that for 10 whole sheets of it you get magical plastic flaps.

Shit plastic flaps can fix issues like #4195
It would allow us to fix painful issues.
What if we put plastic flaps in mech bay so that if you give, lets say, sec a mech, they won't need to go get robotisist access to go charge it, they can just go though the plastic flaps.

I say that plastic flaps are okay considering how hard it is to get more plastic. If it really was that broken then people would be abusing it more.

They abused the infinte mats from the protolathe, they would abuse this as well if it really was that over powered.

**Comment by d3athrow** [comment]
airtight plastic flaps is a game design decision rather than a realistic one. If you want it to be space flavored assume its some field that allows large objects to pass through but prevents small particles from passing.

**Comment by PJB3005** [comment]
@d3athrow that makes no sense on the molecular level
