### ISSUE TITLE
[Feature request] Make Mr Valids record everyone who has moved past them

### ISSUE THREAD

**Issue by IratePirate** [d3athrow/vgstation13#4397]
Mr VALIDs 'metal detectors' should be able to record who has activated them. Someone with the requisite access could then check it and it would list who has touched it and at what station time. Perhaps hacking them with a multitool could wipe their memory?

**Comment by CptWad** [comment]
>Multitool wipes
Better to have it id locked then have anyone with access print a paper with the names

**Comment by dylanstrategie** [comment]
I doubt it'd be useful, I'd rather try and extend security measures a little. As it stands, Mr Valid is a LITTLE bit too gimmicky, and no-one has any idea as to what it's supposed to do (expect for the part where it supposedly sniffs out antags). The following would be neato in the long run :

- Metal Detector
- Better infrared gear. Muh laser security
- Personnel Detector

**Comment by Exxion** [comment]
It scans for guns, energy melee weapons, and the Chain of Command. It's probably supposed to be all melee weapons, but it checks for /obj/item/weapon/melee and those are the only objects within that type. It also checks whether or not you have an ID and, if you do, if you're set to arrest. Finally, it checks if you have a mutantrace.
It should probably not do that last thing because mutantrace is very inconsistent in the code.
Really, it should probably be rebuilt from scratch. Maybe have its functions replaced by a few different tools, as Dylan said.
