### ISSUE TITLE
We're still using the shitty, bugged "medical side effects" 

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4404]
Refer to: https://github.com/Baystation12/Baystation12/commit/c872099e11ad5edf47eda19cd78f059378b3ca83
"Medical side effects" were supposed to be (I assume) a replacement for or early version of chemical overdosing. However they barely work, and are in basis, completely worthless.
You can inject yourself with 500 tricord and 500 dermaline. In theory, you should be getting nasty "side effects", right?
No, you'll ocassionally get some messages about your head hurting or your tummy feeling light. That's about it. You'll still be healing constantly from the 1000 units worth of healing chemicals in your bloodstream. Even if they actually worked as intended they can be completely countered by using more gigantic doses of OTHER chemicals, which does absolutely nothing to fix the problem.
Commonly when playing MD I see doctors just stuff a patient full of antitox or repeatedly slam the "INJECT 10U DERMALINE" button on the sleeper because hey, it doesn't do anything bad. And they're almost right.
Let's please just move on to overdoses.

**Comment by CptWad** [comment]
Have the human body be a massive beaker. Already filled with blood. As more chemicals are put in the blood percentage becomes lower and having too low a blood percentage cause same effects as lacking blood. This can be extended to alcohol as well

**Comment by Shadowmech88** [comment]
I remember hearing that blood was separated from the main human reagent container for some reason.
Anyway, many chems already have overdose thresholds, such as synaptizine, hyperzine, and bicaridine. I don't think it would necessarily be a bad thing to give every chem an overdose threshold, but personally being able to give people a 50u anti-tox pill and send them out instead of having to use cryo or constantly give them periodic 5u pills so that they don't overdose is pretty handy. On the other hand, anti-tox in particular is problematic for no overdosing since, to my knowledge, overdosing only causes toxin damage. Which means that since anti-toxin doesn't have an overdose threshold, you can take any amount of any chem you want and pop a 50u anti-tox pill and you won't incur any toxin damage.

It's a tricky issue.

**Comment by 9600bauds** [comment]
>50u anti-toxin
Holy fuck why? 20u by itself heals 100 toxin and removes most common poisons.

**Comment by Shadowmech88** [comment]
I've never run the numbers, but 50u was just easiest for guesswork since it was the largest you can make and you can make 6 at once with a large bluespace beaker.
Plus, another issue to consider is time. 50u anti-tox will be in your system longer than 20u, and will be removing/negating toxin damage that whole time. I always include five or six 50u anti-tox pills when I make my creatine kits, not because the toxin damage from creatine is severe, but because it's constant. If you're on creatine and you run out of anti-toxin in your system, you incur toxin damage steadily until you take more, at which point it halts again. So it's more efficient to take 50u pills less often than 20u pills more often if your goal is to have anti-toxin in your system at all times.

**Comment by 9600bauds** [comment]
There's the issue. You can just take monster doses of chemicals to constantly be hopped up on them, and since chemicals are pretty much unlimited, there's no downside to doing so. You now have a guy that will be regenerating health for the next half hour.
That's not very good design. Worse still is that you can overdose on SOME chemicals, but not on some others.

**Comment by Shadowmech88** [comment]
It might not be realistic, but to be honest, how often do you see people running around with 100u anti-tox, tricord, kelotane, dermaline, DD, bicard, dexalin plus, and inaprovaline in their system?
If not many people exploit it, it could be seen as a feature.

**Comment by 9600bauds** [comment]
Hell, I could be exploiting it myself, I don't out of principle because of how broken it is.
What you're telling me is that constant health regen, chloral immunity and halved stun times for half an hour are features. But then why can't I do the same with Hyperzine or Peridaxon?

**Comment by Shadowmech88** [comment]
You should be able to. If you load up on hyperzine, taking an equivalent dose of tricord and anti-tox should be more than enough to counteract the toxin damage.
Or does hyperzine stop boosting your speed if you overdose on it?

**Comment by 9600bauds** [comment]
It should, in all honesty. It's unbalanced, exploitable, unrealistic, and as far as I know the other major codebases have already moved away from this side effects system.

**Comment by FudgePucker** [comment]
Having blood inside you and humans acting like beakers would be a bad idea.
It would cause conflicts with internal reactions.
Clonxdone would be worthless as a cryo chem because people would just bleed out and produce 10000 meat, but you can't remove internal reactions because then fun things like potassium and water pills would be gone.

You would have to snowflake the shit out of the code to prevent blood from reacting inside the body but outside the body it does.

**Comment by Iamgoofball** [comment]
you guys should just port my overdose stuff, it's ten times less snowflake then bay's hardcoded version

i can make a quick PR for it if needed

**Comment by clusterfack** [comment]
Of all goofchem overdose stuff is what I really wanted

**Comment by 9600bauds** [comment]
How do overdoses work in goofchem? Never actually tried it myself

**Comment by Iamgoofball** [comment]
@9600bauds instead of the predefined 1 tox per cycle when overdosing, each chemical that has an overdose has a unique effect associated with it

**Comment by dylanstrategie** [comment]
Goofchem is the keyword here. Bay overdose was most likely fairly robust, but we nerfed it when we still were in our /tg/-ish years

We need some extremely robust overdose, and I'd advocate for a more robust health system in general. But that's for another day. In the meantime most chems should cause massive TOX damage in the event of an overdose, like really medicines do (if you drink tons of medicine, even weak stuff like cough syrup, you'll end up vomiting all over the place and even dying)

**Comment by d3athrow** [comment]
Only reason we even got overdoses was from ririchiyo porting organ changes.

**Comment by dylanstrategie** [comment]
Didn't we have overdoses like, years ago ?

I was pretty sure overdoses were a pivotal system of both /tg/med and Baymed

**Comment by FudgePucker** [comment]
There are very few drugs that don't cause overdose I thought. Mainly tricord and antitox, the main reason being that they treat toxin damage.
Inject 30+ units of spacecillin in someone and tell me how good of shape they are afterwards.

Having an overdose for anti toxin will make medbay lives harder and will make just cloning seem like a better choice than fixing organ damage causing continual toxin damage.

Shit only downside to not having an od for anti toxin is people might take 10000 units of it in case they are chloraled or sleeptoxined.

**Comment by 9600bauds** [comment]
You know there's bottles of activated charcoal in literally every vending machine? They quickly treat overdoses and heal a ton of toxin damage to go with it
If you clone someone over them being overdosed I will personally seek you out and slap you

**Comment by FudgePucker** [comment]
|>put chems in cyro that cause overdose that aren't removed by antitoxin
|>laugh as people go from cloner to cyro back into cloning in an external wild ride.
THE RIDE NEVER ENDS.

**Comment by 9600bauds** [comment]
but that's precisely what activated charcoal is for

**Comment by FudgePucker** [comment]
Not if you space medbays only 4 bottles of it :^)

**Comment by 9600bauds** [comment]
8, and botany can make more, and if you know what you're doing you can clear overdoses in other ways

**Comment by CptWad** [comment]
yes but people are stupid or new.

**Comment by FudgePucker** [comment]
Yea what @CptWad said, you think they are going to check the cyro mix or check regents in blood before circular sawing cloning after seeing liver damage?

**Comment by 9600bauds** [comment]
Cloning is a whole different problem altogether. But in all honesty? If a patient starts getting toxin damage after going into Cryo and the doctor can't even think of shift+clicking the tube to check the cryomix, they're too dumb to function, why should we balance the game around them?

**Comment by FudgePucker** [comment]
Don't you have to eject the beaker first?
Also most players don't understand how magical cyro tubes are. A cyromix of 40 u clonxdone 50 u cyroxdone and 10 u spacecillin might look perfectly fine and okay, but after 5 seconds they are super overdosed and already doomed.

**Comment by 9600bauds** [comment]
Absolutely not, it doesn't work that way. You need a ratio of more than 1:1 spaceacillin to clonex to cause any sort of build-up, and unless you only leave 1u clonex in the beaker or put more than 60u spaceacillin, the overdose will take minutes.

**Comment by FudgePucker** [comment]
Also the point of spaceacillin is that A: anti toxins don't remove it. B: it lasts a super long time in blood steam. And C: it is not a giant red flag, nanites will be caught as soon as someone starts screaming about killing them and easily treated with iron. Any toxins and polyacid will be stopped if even the dumbest doctor looks at the beaker, and polyacid smoke requires a stasis beaker, only normally available from research and they will point fingers at you if you ask for one and medbay turns into polyacid.

**Comment by 9600bauds** [comment]
So then the situation is somebody overdosing another person on a healing chemical.
It's easy to recognize the symptoms, doesn't take a genius to figure it out (over 30u of most things -> bad), is easily treatable, and is a completely legitimate strategy for trying to kill someone (plus there'd be more effective ways)
Then, what's the issue?

**Comment by FudgePucker** [comment]
There really isn't one, its a valid antag method. I was just pointing out that over doseing is already in the game and I am bored and on my phone.

**Comment by 9600bauds** [comment]
I somehow forgot to mention here that the five or so "side efects" are SO BUGGED that they get WORSE over time after the offending chemical is removed, and NEVER GO AWAY
Give someone 20 tricord and their head will hurt FOREVER

**Comment by Iamgoofball** [comment]
yeah i'll put some shit in my schedule to port goofchem overdose functionality

just remember that I'll be making overdoses more deadly because alongside that one of the "bugs" brought up here is that currently overdoses are toothless and can't do shit

something I figured out that works well at /tg/ is "chemical reverses the effects when ODing/overdoes the normal effects if that would be worse"

for example, meth at tg makes you fucking go out of control and flail your arms and in general turn into a drooling hyperactive mess because you went 2fast

the trekchem ODs at tg do damage instead of healing it, and it's the respective damage type

shit like that makes ODs actually fuckin matter, and calomel/charcoal become very fuckin useful when handling ODs.

"it does 1 toxin damage every once in awhile and makes some bad sad messages pop up" isn't good enough for ODs because 1 toxin damage is Literally Nothing 

and when paired with "most codebases make anti-toxin not have an OD" means there's no fuckin point to worrying about ODs, go ahead and pump those guys full of 200u of each healing chem + tricord, he'll be fine, maybe a bit of toxin damage but the anti-tox and tricord/DD take care of that

**Comment by Iamgoofball** [comment]
ps. oh and organ damage on OD is shit-tier, nobody likes surgery and doing it for ODs is excessive

**Comment by 9600bauds** [comment]
An explanation of how "side effects" work.

If you, ever, at ANY point, have an overdose of a certain select chems (i.e. more than 15 tricord), you get a "side effect". It doesn't matter how many units of said chemical you have, only that it's over the overdose threshold. 400 tricord and 16 both will have the same effect.

All humans have a constant cycle where SIDE EFFECTS DO NOTHING FOR ~15 MINUTES, THEN THEY SUDDENLY DO SOMETHING FOR 9 MINUTES, THEN IT REPEATS. That means that even if you overdose on something, the side effect will probably not even do anything until 15 minutes later. I have no fucking idea who came up with this shit or why would they deliberately code something this awful.

So what do the side effects do? First and foremost, their "strength" is always growing. Even if you're not overdosing on the chemical anymore. If you take 16u tricord at any time, your side effect will still be getting worse 40 minutes later. The actual effects they have? One message like "your head hurts" once every minute and half while the cycle is active. Plus extremely negligible effects such as 1-3 toxin damage, once every minute and half.

So if they're always getting stronger, how do you cure them? Either use one of their defined cures (such as alkysine, inaprov etc.) but ONLY while the cycle is active... Or wait until they cure themselves. That's right, once the side effect grows strong enough (which takes like one hour), at which point you get messages like "It feels like your head is about to split open!", it just cures itself. Done.

This is so incredibly shit.

**Comment by Shadowmech88** [comment]
I was under the impression that going over a chem's defined overdose threshold would cause constant toxin damage.

**Comment by 9600bauds** [comment]
That's the case for MOST chemicals, yes, there are a few snowflakes that do the thing described above

**Comment by ihadtoregisterforthis** [comment]
I would assume that those overdose times are because rounds were expected to go on for long times, maybe hours
