### ISSUE TITLE
Tech Storage needs a console screen

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4434]
If you need a console screen to build an Autolathe, and you need an Autolathe to make a console screen, how was the first Autolathe made??????

**Comment by Exxion** [comment]
There are things more complex than a console screen that can be made by hand out of sheets. Is there a reason the console screen can't be made by hand?

**Comment by 9600bauds** [comment]
Probably control conflicts
How would the welder know what kind of item you want to make when you torch that glass? It'd need a menu, and that's clunky

**Comment by Exxion** [comment]
Metal has a menu, though
Metal is malleable, so it would be slightly easier to form by hand, I guess
But you could have the same kind of thing
Like "Prepare console screen" gives an item that makes a console screen when welded

**Comment by Probe1** [comment]
Kurfurst said he was going to add one to the mechanics workshop at some point.

That aside, there's a microwave you can pry open in the ghetto bar which supplies a console screen.  There's also two autolathes, one in cargo and one in RnD.  Both departments are favorable towards mechanics.  "Needs" is a bit of a stretch I think.  It's as simple as walking over and asking for a console screen.  Anyhow I think it's gonna get changed.

**Comment by dylanstrategie** [comment]
Tech Storage should have spare console screens somewhere, because those things are buggers. Also I would like actual consoles to use them, because they're console screens

As for producing console screens, the Protolathe should be able to at Glass Materials levels if it can't already. And you should be able to order a spare parts emergency crate at Cargo that contains everything needed for basic machinery like Autolathes (or even an Autolathe crate)

**Comment by Probe1** [comment]
why would anyone order a crate of console screens when they could ask for a console screen from the autolathe

also making consoles require console screens would finally ensure no one ever builds those pesky consoles ever again, good idea.

**Comment by dylanstrategie** [comment]
If the Autolathe is offline, there should be a way to build another one in a hurry

Also making consoles require console screens wouldn't be too much of a problem per se, I'll have to look at adding more ways to obtain console screens if this happens, but that would make building consoles require SOME sort of Engi/RD/Cargo access or authorization

**Comment by Probe1** [comment]
if both autolathes are destroyed don't you have bigger problems than building an autolathe?  if the autolathe is offline aka power is off then why wouldn't you just unwrench the fucker and drag it to a room with power?  but wait, if it didn't have power then how are you using the cargo ordering console in the same room anyways?  

doesn't add up man.

**Comment by 9600bauds** [comment]
It's a convenience factor more than anything, the console screen is needlessly tricky to acquire and requires you to make or visit an autolathe you normally wouldn't even care about just to build some machines. If anything, why can't the Protolathe make it?

**Comment by Probe1** [comment]
tbh i'm not getting this trickiness, neediness or difficulty at all.  you ask the quartermaster or cargo tech for a console screen.  if there isn't you ask the AI or a borg to open the door.  If none of this is possible you stoll over to research on the opposite side and ask them.  if somehow everything isn't possible, AND THE CONSOLE SCREEN FROM THE GHETTO BAR IS ALSO GONE, you're a mechanic for christsake hack the door.

**Comment by dylanstrategie** [comment]
See #4446 for a fix I attempted. I did make it so computers need console screens, but this also addresses part of this by adding console screens to the Protolathe, as it should have been since the Protolathe's inception

I still think adding spare console screens is nice in case of a catastrophe, but I fear that this will cause merge conflicts due to current use of the map
