### ISSUE TITLE
Security should have general access to all departments

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#4435]
Currently they have the same access as an assistant with the exception of brig/eva.

Even a fucking paramedic has access to the brig, while an officer can't enter medbay.

**Comment by dylanstrategie** [comment]
Security Officers should have basic access to all non-Command departments. General Medbay, general R&D, general Cargo, general Engineering and all Service departments

We might need to actually review how the airlock accesses are set up, last I checked you can get dangerously far into the Engine without Engine access, for instance

**Comment by SerWind** [comment]
Not exactly sure why this wasn't the case but just might be an oversight? Sec is hard enough. Not being able to access basic areas like this not only hurts patrols but also any response to an issue.

;AI DOOR PLZ DOOR AI DOOR

**Comment by Manaony** [comment]
Pro tip: That's one of the reason the battering ram was added. Now just get your warden/HoS to make it available to you.

**Comment by Probe1** [comment]
I'm honestly not sure how this will turn out and I think it might encourage some shitcurity.  But it should be done so we can see.  On paper it's an improvement and should be done, after all they're not getting RnD access or access to the singularity or anything.  But maybe a breed of sec players come along and steal anything not bolted to the ground?  I don't know, I can see positives and negatives.  

Do it, see how it turns out.

**Comment by Kurfursten** [comment]
Unintended consequences?
* Giving security access to access_engine_equip would give them access to unlock APCs and Air Alarms, and program airlock electronics with access
* Giving security access to cargo gives them the ability to control cargo bots (this is actually probably a bug because cargobots have their own defined separate access but it is unused) and order their own crates (Might be easily resolved by moving supply shuttle and MULEs to access_cargo_bot)
* Giving security access to bar and research each grants them the ability to take stuff out of the ore redemption machine
* Giving security access to research allows them to open the R&D crate to make their own autolathe; access to hydroponics lets them open hydroponics crates (engine_equip is separate from engine, though, so those are safe)
* Research access also allows sec to use telescience as they please

Also, because we're discussing this in terms of "general access", it needs to be clearly defined what that means. For instance, access_cargo does not include access_mail_sort; access_medical does not include morgue, chemistry, genetics, virology, surgery, etc.; access_research DOES include the outpost but not R&D, toxins, tox storage, xenobio; access_engine_equip handles the main engineering foyer and SMES but not the engines themselves (access_engine used for these + crates)

--

Please note that this is neither an endorsement NOR an admonishment; I am neutral toward this subject. These are merely considerations you must take into account and if it is implemented, I would like to see it implemented with full cognizance of what is being done (and handled accordingly).

**Comment by TermedClepe** [comment]
@Kurfursten
That highlights a few shortcoming with current access levels, mainly that door access is tied to crates and machines.

**Comment by CptWad** [comment]
imo accesses need to be redefined. I had it in my mind that each head of staff could define who and what access can open what doors. IE the CMO could control weather medical doctors could enter chemistry/genetics. RD could control scientists in robotics and robotics in RnD. We could take my idea further and allow sec officers inside should the head of that particular department allow it. All at the press of a few buttons on some type of interface. Like a department access controller that also doubles as a way that heads could constrict parts of their departments and actually have power over their department.

**Comment by Probe1** [comment]
While I don't agree with you CptWad (because I don't trust heads that much) I do think that the ID card readers in heads office can use some love.  I mean all they can do is declare code red and revoke maint access.  There's a lot of room for potential in those.  You could tie some cool functions to them.

**Comment by SerWind** [comment]
How deep can these interfaces go? I think they could use some tune ups in terms of power/usability.

**Comment by Probe1** [comment]
If you mean the keycard authentication device then this is the whole deal.  Code red which is used sparingly and maint access which is used **never**.

![image](https://cloud.githubusercontent.com/assets/8550416/7624370/69815228-f9b5-11e4-9c42-ffce8b0501e5.png)

**Comment by FudgePucker** [comment]
I wish emergency maint access was used more.
Main hallways depressurized and you need people to stop opening fire locks?
Grant emergency maintenance access.
Shit going down in main hallways?
Grant emergency maintenance access.

**Comment by dylanstrategie** [comment]
Red Alert is really hard to obtain because it needs two heads to care, last I checked some head offices lacked card readers and you need to sync your card swipes perfectly, which is pretty painful because the window to hit both cards is low. Whole thing should be redesigned

**Comment by Probe1** [comment]
@dylanstrategie all the head offices have card readers, I just checked.

**Comment by gbasood** [comment]
A potential feature for keycard authentication devices (which have a very silly and useless name) would be allowing, for instance, the CMO to quarantine medbay. Simple implementation would be just activating every medical area's fire alarms, complex would be 'You can't open these doors unless you have medical access, otherwise you have to do some incredibly simple hacking first.'
