### ISSUE TITLE
Light tiles are weird

### ISSUE THREAD

**Issue by Unfit** [d3athrow/vgstation13#4436]
individual light tiles have a chance to be "flashing" or "broken" when created
flashing light floors shine more, broken light floors don't shine at all

a problem arises when you create a stack using a flashing/broken tile as a base for the stack
every light tile added to that stack will become flashing/broken as well
this is bad when you create a stack with a broken light tile, because then every floor you make with it will be broken.

**Comment by d3athrow** [comment]
Interesting

**Comment by dylanstrategie** [comment]
Being able to have "broken" light tiles is dumb, especially since stacks REALLY don't like independent variables

You shouldn't be able to create or rip off broken light tiles, and broken light tiles should be a byproduct of physical damage (for instances bombs, or any item hit that isn't the proper tools) and be destroyed into shards and cut wire when ripped off (similar to broken plating, although with some byproducts to allow some level of recycling, because you can't break floor tiles by hitting them)

**Comment by Unfit** [comment]
One more thing

making light tiles is a huge pain in the ass
not only you can get only 6 tile assemblies from one cable coil (although it may be understandable), but it takes roughly a second to finish each of those tile assemblies (due to the click delay on the metal). 60 light tiles need 10 cable coils, 60 glass, 60 metal and above all that, 60 seconds of your time (to click on the assemblies with the metal)

**Comment by Exxion** [comment]
Flashing and broken need to be subtypes of light tile rather than the same type with a different value for a variable
Who thought it was a good idea to do it that way? Someone who didn't know how stacks work, I guess.

**Comment by clusterfack** [comment]
I don't see why you couldn't just give a variable to light tile stacks of the number of broken tiles and flashing tiles, and then slightly modify a few of their procs so that they keep track of those broken/flashing tiles.

**Comment by Exxion** [comment]
Or just make them not stack together
Or, better yet, remove the randomization and give them separate recipes

**Comment by clusterfack** [comment]
Why would you want to build a broken tile?

**Comment by Exxion** [comment]
OK I guess I should have been more specific
Give the standard and flashing ones different recipes and make the broken one occur when one breaks
