### ISSUE TITLE
Double shotgun is magic.

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#4499]
When considering how you use a double shotgun in real life, you shoot it, pop it open, and then put in new shells.
With this magical double shotgun, you can shoot it, and just load it.
The funny part is that the shells don't magically disappear into the air.
When you finally break open the double shotgun, all the shells that you did fire pop out.
That means you can have 10000000000000000 shotgun shells pop out of those two barrels.
I think it might be missing a check to see if there are spent shells in the gun.
The question is if we should fix this.
It is a balance issue because popping it open produces evidence, and having to pop it open before reloading increases the time you have to spend on reloading a gun that already only holds two shots.

**Comment by Shadowmech88** [comment]
My first inclination would be to say that you have to pop the shells out, because it's more realistic. But the double-barrel shotgun, by nature of being double-barreled, is already worse than the average shotgun. Sure, you have to pump the average shotgun, but it's a quick action and you get two more shots because of the trade off. I wouldn't want to further handicap a weapon which is already the worst in its class.

What if you didn't have to break the shotgun open, but inserting new shells simply caused the spent shells inside the gun to eject themselves? The production of evidence isn't a big issue in my opinion, you are firing a shotgun after all. They aren't known for stealth.
