### ISSUE TITLE
The round shouldn't end when the wizard is killed

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#4512]
This feature makes doing a lot of things (like R&D or cargo or autismforting) pointless, because even if the wizard runs a peaceful gimmick, there's a chance every second that a random grayshirt will fill him up with chloral and end the round for everybody

**Comment by ComicIronic** [comment]
But then you'd have 3-hour extended boogaloo where nothing happens.

**Comment by Shadowmech88** [comment]
What if killing the wizard caused a new wizard to spawn, or caused someone on the crew to become a wizard?
Of course, we'd need a new win condition for wizard rounds, but it would make them last longer.

**Comment by PJB3005** [comment]
Isn't that ragin' mages?

**Comment by TermedClepe** [comment]
@ComicIronic

Exact same thing happens when all tators die, round goes on. Should round end when antags die? Are you really just playing to see antags?

**Comment by Iamgoofball** [comment]
@TermedClepe Yes, but the thing about all traitors dying is that the player doesn't know if there is more traitors. The paranoia is still there. They still need to fear their fellow crewmembers. They don't get an antag counter that tells them how many are alive still. They don't know if there are changelings. They don't know if one of the guys they killed turns out to be a traitor changeling and could be regenning this very moment.

If you kill the wizard, though, you know it's over, the paranoia and fear is gone. There no buts, or what ifs, the antag is dead, and there are no more.

**Comment by ririchiyo** [comment]
This is already a feature in the game at the moment. It just needs to be enabled by an admin who knows what the setting for it is.

**Comment by 9600bauds** [comment]
Wizards really, really shouldn't be their own gamemode. Mix them with autotator like Changeling did.

**Comment by TermedClepe** [comment]
@Iamgoofball

That circular logic, only reason they know the antags are dead in the first place is because the round ends. It can be raging mages, it can be adminbus, it can be tator trading his TC for few spells.

Having the round end is the reason why nobody takes wizard round seriously, everyone knows the round will end any moment and nobody will continue with their stuff until next round.

**Comment by dylanstrategie** [comment]
I don't like the idea of automatic Extended after a Wizard is killed, for one because EVERYONE will understand it's full Extended once they demolish the Wizard, and then because the Wizard literally WAS the threat of the round

It's kinda like Nuke Ops, except Nuke Ops lead to a near-automatic shuttle call

**Comment by Iamgoofball** [comment]
Why don't you just port Mulligan so it goes to a different round type instead of extended?

**Comment by TermedClepe** [comment]
@Iamgoofball

That is the proper solution to "antags dead extended".

**Comment by ComicIronic** [comment]
We'll port Mulligan when it werks.

**Comment by d3athrow** [comment]
if only my mixed mode worked

**Comment by Iamgoofball** [comment]
It's pretty functional. Check with incoming if he's got any final changes he wants to make though.

**Comment by Probe1** [comment]
I'm for removing the round end condition when the wizard dies.  Admins are thankfully plentiful currently and can handle the situation if the station gets boring.

**Comment by Shadowmech88** [comment]
If I'm not mistaken, the goal of this is to make people less likely to just stop what they're doing and either slack off or hunt the wizard due to the fact that the round would be likely to end in 15 minutes and their work would be for nothing. However, there's also the issue that if this is implemented and the wizard is killed, people know there aren't any more antags and the round's become extended, which means you'll have fighting between the people who are working on autism projects and the people who want to just call the shuttle because they know for a fact nothing interesting will happen in the rest of the round due to the only antag being dead.
So what if instead of becoming extended, it was made common practice for the death of the wizard to mean the admins can now press whatever buttons they want to keep the round from stagnating?

**Comment by Arthurdentist** [comment]
In my experience having the round end on wizard death leads to people being more likely to hunt down the wizard in order to get the next round going so they can re-roll their shit and hope for something better. I think it would be preferable to not have the round end on wizard death, perhaps the wizard's death could trigger the creation of a couple antagonists. 

This is semi-related but I also think the objective for survivors from the summon guns spell ought to be changed. Many people don't actually do traitorous things when they get made survivors because they are too busy hunting the wizzy or they simply don't know they can. Giving them an actual objective, random assassination or whatever, would make it clearer that they are and can do whatever traitorous and devious things they have in mind.

**Comment by Iamgoofball** [comment]
@Arthurdentist 
>would trigger the creation of a couple antags

yes this is mulligan port mulligan 2day

**Comment by 9600bauds** [comment]
Just today, I spawned as MD and went to ask the Chemist if he needed help making chems or a cryomix. There were rumors of a wizard over the radio (there wasn't, it was the clown clowning around).

The Chemist said something the lines of "we won't need cryomix if there's a wizard".
The wizard sudden roundend syndrome is real.

**Comment by Probe1** [comment]
That's a crappy chemist since there will be a ton of casualties during a wiz round. That's a hugely crappy chemist.  But it's also a point in the favor of removing the round end condition.

**Comment by 9600bauds** [comment]
His justification was "erryone gets ei nathd anyways lol"

**Comment by Probe1** [comment]
Yeah I'm sure no one is going to need cloned or given dex+ when their heads or brains are attached to monkeymen.  

banbanbanbanban

**Comment by Shadowmech88** [comment]
I don't think I've ever seen Medbay bother reattaching heads left by an El Nath wizard.
They're usually too busy making chloral syringes.

**Comment by clusterfack** [comment]
The SS13's doctor oath: "Do only harm"

**Comment by Probe1** [comment]
We've wholly departed the topic of the issue but not only do I do it as a doc, I insist they do it when my coworker gets splatted.  Last night for example.  The wizard didn't bother taking the other mechanics head and clowned me instead of finishing us both off.  So I got a mediborg to do brain swapping surgery with minimal coercion.  

This is the minority of the cases though, I ended up leaving 3 more heads in medbay and none of them returned to the round.

**Comment by FudgePucker** [comment]
Wizard rounds are stupid in every way.
They have a spell that removes players from the round instantly, leaving just a head.
You can't make them into cyborgs because the wizzy man can phase shift into walls to ignore turrets and upload one human.
Even better when its a friendly wizard, the round will last forever yet will end the second you start something.

Maybe have a button pushing not, where when wizard is killed it asks admins to pause it, if no admins are on to bus it ends the round by face rolling on the fun buttons.
Wizard dead and no admins?
Time for bomber man/highlander/meatywhores/blobs/super aids and embola/spider infestation everywhere/ or all of above at the same time.
Extended was removed from rotation, when the wizzy man dies then admins come up with a bus or the not crashing this station. WITH NO SURVIVORS.

**Comment by FudgePucker** [comment]
>not

I ment bot, fucking phone won't even let me edit posts

**Comment by Shadowmech88** [comment]
I like FudgePucker's idea. I mean, everything gets thrown out the window the second people know it's a wizard round anyway. Might as well make it more fun for the survivors who don't get the chance to fight the wizard in person.
