### ISSUE TITLE
Change unrealistic radiation and fire effects

### ISSUE THREAD

**Issue by smedbux** [d3athrow/vgstation13#4581]
Radiation takes hours even with massive lethal doses to have any impact on the body and therefore should not stun people down repeatedly after immediate exposure. Radiation should instead give toxin damage and genetic defects constantly over time depending on exposure levels. Arithrazine might be a little overpowered afterwards, but that can change.

Fire should not spread in space, and being in space should extinguish a fire.

**Comment by ComicIronic** [comment]
You have to consider the timescales of the game.
Also controlling radiation exposure in that way would be rather difficult.

**Comment by dylanstrategie** [comment]
Again, timescale. If everything took as long in real life as it did ingame, this game would be painful to play

As for the rest of your suggestions : 

- Radiation should likely not stun people, but instead give them toxin and clone damage proportionally to the dose (knowing that even 1 RAD is largely above the real life danger threshold, as it is given by handling raw uranium or being near the singularity/shard)
- Radiation shouldn't give mutations. Radiation demolishes the DNA, it doesn't mutate it. Odds of radiation giving some form of positive, or even non-destructive mutation are basically null
- Fire should obviously not go off in space and extinguish when all the oxygen is gone systematically, but fire is not very robust currently because ZAS fix PRs are few
