### ISSUE TITLE
Earmuffs + blind = still stunned by flashbang

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#4585]
How can a deaf man with no sight be stunned by a flashbang.

**Comment by 9600bauds** [comment]
shockwaves

**Comment by TermedClepe** [comment]
But that's not ho- please just stop.

**Comment by CptWad** [comment]
The shockwave of the flashbang can still hurt your brain or some shit

**Comment by TermedClepe** [comment]
There's no shockwave what are you even talking about, with a flashbang there's a sound wave that can't even permanently damage your ears, just deafens you temporarily.

**Comment by ComicIronic** [comment]
It's all shockwaves

**Comment by dylanstrategie** [comment]
Flashbangs have a shockwave, which is why you can't just sprint around firing blindly in real life if you get hit by a flashbang, but you would NOT get blinded OR deafened if you had eye and ear protection respectively

We should make sure the stun effect is properly scaled to the amount of protection worn. If you have full eye and ear protection, you'll just get kicked on your ass for a second, if you weren't on or right next to the flashbang, it'll barely stumble you

**Comment by 9600bauds** [comment]
Guys I was just making a shitty dark souls meem

**Comment by FudgePucker** [comment]
The problem with adding more protection is that security would use nothing but flashbangs.
They already carry around earmuffs for vampires, all they would have to do in an engagement is pop them on and throw a flashbang.

**Comment by ComicIronic** [comment]
Flashbangs are slow and limited, though.

**Comment by FudgePucker** [comment]
Flash bangs are somewhat slow, but they are also pretty much unlimited range.
Shoot a grenade launcher down the hallway off screen and you are still effected.
I don't want this change because I love flash bangs as they are now.

**Comment by TermedClepe** [comment]
>The problem with adding more protection is that security would use nothing but flashbangs.

What server are you playing on? It's rare for sec to even realize they have flashbangs, let alone use them.
And grenade launchers? Things that never happen: act II
