### ISSUE TITLE
(WEB REPORT BY: theeliminator16 REMOTE: 198.245.63.50:7777) simple_animals cannot use /me

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4587]
> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> After the saycode update, simple animals controlled by players no longer show any message after performing a custom emote.
> 
> What you expected to happen
> Emotes should happen.
> 
> What actually happened
> Emotes did not happen.
> 
> Steps to reproduce if possible
> Control a simple animal.
> Attempt to emote.

**Comment by eswordthecat** [comment]
Yes, it cannot use you.

**Comment by Probe1** [comment]
constructs for cult can't either but i assumed both of these were working as intended and haven't reported them before.

**Comment by ComicIronic** [comment]
This is intended, because people abuse emotes to get around language barriers.

**Comment by dylanstrategie** [comment]
Simple animals should be able to use Me, but there should be some form of regulation on what is done with Me, because currently you can just type Me "says, "Hey look, I'm not mute afterall !" with ANY mob and it will work

I would personally wager for a direct admin log for Me actions and a very clear and specific rule on what is and isn't okay with the Me action to avoid abuse, because it's also possible with aliens, monkeys, Mimes or even normal humans (notably making voice changers useless since you can "mimic local speech")

**Comment by nuklearcellphoneg** [comment]
I agree with dylan.

/me should just be logged, and abused be punished on a case by case basis(though it would be difficult to find such abuse).

The difficulty lies in that if you use a gas mask and utilize /me says, "Blah", the player it's used on really  won't be able to figure out /me is abused because this would require them to remove the gas mask, use it themselves, find out it's a voice changer, etc.

The largest thing we should do, really, sorry to hijack this issue, but players should be prevented from being able to use the characters =says, " Etc "= after using /me. 

There is, after all, no action requiring quotation marks or the words says for an action, I believe.

**Comment by 9600bauds** [comment]
I believe this was an issue with virtualhearers, what do you say @clusterfack ?

**Comment by clusterfack** [comment]
Pretty sure this was before virtualhearers

**Comment by clusterfack** [comment]
It came from a fix from the saycode rewrite where mice and such could emote words so they got disabled entirely

**Comment by gbasood** [comment]
Could prevent custom emotes and re-allow actual action emotes (i.e. *wave)
