### ISSUE TITLE
X-ray cameras not x-raying

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4592]
Unless I'm misunderstanding what these do, they don't seem to work any different from normal cameras. You can't see through walls, or see people through walls, or anything really.

**Comment by ComicIronic** [comment]
Can you see in the dark?

**Comment by 9600bauds** [comment]
Just checked, they can't see in the dark either.

**Comment by Exxion** [comment]
Cameras as viewed by the AI work perfectly, as far as I'm aware.
Cameras as viewed from consoles are exceptionally horrible because all that happens code-wise is that your eye is moved to the camera's location
So it uses *your* vision properties rather than the camera's
Which also sucks because I want to add harm-labeling to cameras, but this doesn't work because they are bullshit

I wonder if it would be possible to just swap the user's vision_flags with an equivalent on the camera while they are using the console.

**Comment by 9600bauds** [comment]
Okay that's pretty awful

**Comment by Exxion** [comment]
I think someone put a lot of work into the AI-camera code but, when presented with the security camera consoles, just said "Eh. Fuck it."
Or the consoles were coded before the AI's camera use. Not sure.

**Comment by Exxion** [comment]
Well I found out why x-ray cameras don't see in the dark even for the AI
I can't see anything in the code suggesting anyone even attempted to make that happen

**Comment by clusterfack** [comment]
Well we should see if one of the other codebases fixed it and port it then, considering how far back the issues goes someone probably caught it and fixed it already

**Comment by Exxion** [comment]
I'd rather that not be done right now, if possible
I'm working on unfucking cameras as viewed from the console

**Comment by 9600bauds** [comment]
I checked Bay and TG, neither unfucked their cameras.

**Comment by Exxion** [comment]
I just sort of did, but I'm not opening a PR yet because I did it in almost the shittiest way possible
