### ISSUE TITLE
Make the derelict available to taxi more easily

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4653]
Essentially, add it to the taxi consoles by 'fixing' the buttons on the derelict

**Comment by ComicIronic** [comment]
It might let people harass the poor Derelict MoMMIs too easily.

Also, compare it to how easy Box's derelict is to reach.
I'm not sure making a direct connection possible is wise.

**Comment by Exxion** [comment]
One of Taxi's two derelicts actually already has areas for the taxis to arrive in

**Comment by PJB3005** [comment]
I know, @Exxion, and those only work if the taxis are emagged, what I'm suggesting is a different way for the derelict to become accesible.

**Comment by Exxion** [comment]
Ah
Also, @ComicIronic, the derelict that has the taxi areas is not the one that the MoMMIs are on

**Comment by PJB3005** [comment]
Well, but it's basically ment to be what they fix, heck, they literally have an unfinished catwalk that, if completed, meets up PERFECTLY with a catwalk on the other derelict

**Comment by FudgePucker** [comment]
I think that the derelict on taxi station being reached easily if the buttons are powered and fixed would be a good idea.
The station with the taxi ports isn't that much of a derelict station, only one room has a hole to space, and its over in maintanance on the edge of the station, pipes are already placed, only a few are missing in a few areas.
Its more of a ghetto station, a small fixme up instead of having to fix a whole fuck ton of shit. I want people to visit my autsimfort.

Only problem might be derelict MoMMIs using the shuttles to get back to station.

**Comment by PJB3005** [comment]
Just don't allow them to use it, simple as that, derelict MoMMIs can't get to the main station with the salvage shuttle either (though it does behave kinda buggy)

**Comment by FudgePucker** [comment]
Also I think Taxi Derelict is my new favorite derelict.
You have an engineering part and a autism fort part.
It is practically designed for derelict MoMMIs and not based on a older station, there's even a god damn hat vending machine there.
