### ISSUE TITLE
Taxi Station Science Department Split

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#4667]
I know I'm not alone in this; I don't think Robotics and R&D should be split off from the rest of the Science department, entirely on another station. I get the surface logic of "trauma kits, beakers, and tools for Medbay" behind it, but that's just one batch of tools, it seems strange to put R&D on the Medical station just so that their trip for a one-time delivery is shorter. This affects Mining as well. Initially I thought it was neat that Mining was right next-door to Science, but the issue is that Mining is right next door to exactly all of the Science departments that don't need any minerals. The three Science departments that do need minerals are split between two other stations, making the miners' trip to the mechanic's, R&D, and Robotics take possibly even longer than it does on Box.

I'm not sure what the best way to rearrange it would be, but I definitely think every department within Science should be on the same station.

**Comment by CptWad** [comment]
I am OK with it

**Comment by ComicIronic** [comment]
RnD is next to Robotics because they have to be for Robotics to get anything done in a round, and because RnD has no better place to be - it services Medical and basically nowhere else.

Toxins and telesci are together because, like RnD and Robotics, they are cooperative departments, and they are next to Mining to encourage inter-departmental cooperation since Mining is likely to use them for asteroid bombs and corpse retrieving.

Xenobio is on it's own because bleh.

Everything cannot be next to everything else. Toxins and telesci, as the two most dangerous departments, are next to the security base, and this is doable because science is the least continuous department. Everything else has to stick together: Medical, for example, can't be separated from Parameds, Virology, Surgery, or Chemistry. The idea that Science should be a single department is largely just Box design philosophy, and so that the RD has an easier time trying to manage <s>as if they ever do</s>.

You have to use the Taxis to move stuff around. It's an inconvenience for miners, but look at it this way: if they were on the same station, Mechanics might get nothing.
