### ISSUE TITLE
Away missions: when and how

### ISSUE THREAD

**Issue by ComicIronic** [d3athrow/vgstation13#4673]
Having looked over the code, away missions are surprisingly close to being completed. The biggest obstacles are a lack of compatible maps and no clear implementation.

Here's hoping we can fix one of those.
# Questions
## When

Away missions have a good chance of emptying the station. This means that they'd ideally involve the whole crew, but that they'll also interfere massively with gamemodes, particularly those tied to the station like Nuke Ops or Malf. One solution to this is to limit missions to a certain set of modes - ling, traitor, extended, etc. - but that opens avenues for metagaming, and also fails to solve the underlying issue of how the missions are meant to interact with the regular round.

Admin intervention is also an issue. A human element would make handling when missions are allowed to happen a lot easier, but it would limit away missions to the times when an admin is online and cooperative, and I don't like tying game features to admin use generally because we'd like player action to be independent.
## How

Missions should also ideally come at the end of some progression. Charging up the gateway would be a good example, and a manual delay less so: it should be a rarer achievement to be able to go off-station using the gateway, and how this would be set up is important.

Where the mission goes is another matter. An admin could set a manual mission, but again, we don't want to have heavy-handing in the whole process. Randomness would potentially increase the fun, but remove the possibility of preparing for a specific mission, like colonising a planet. We could have a random selection of maps decided when the gateway is activated, and then have the user pick from those, but this would have to be discussed further.

**Comment by CptWad** [comment]
Why not make it its own gamemode?
Solves all the problems.
Away missions could then be solved for crewpoints.
It could allow for players to start on the other end of the away missions for more complex missions. 
And for those that leave for the away missions for the rest of the players they could have that extended round they always wanted.

**Comment by Probe1** [comment]
I'll read this thoroughly and put better formatted thoughts into it later but right now I want to say something that's come up in a few previous discussions.

hardcap on amount of players and additional hardcap on amount of heads that can be away on an away mission at any one time.  

oranges has talked about it with us a fair bit in irc and that is the primary issue TG had.  everyone fucked off to the away mission and instead of it spicing up a round, it became all the round was about and the regular station was a ghostserver.  you could add an admin verb or even a card authentication device function to repeal limits and let everyone and Ian go if you like, but I think the first thing is to limit how many people are on it.

**Comment by IratePirate** [comment]
I would make it its own gamemode with auto-traitoring every so often to keep things spiced up. Away missions are inherently problematic because 80% of the crew would leave to go on them, so why not make it so away missions have an end goal which ends the round fairly quickly? There's no point trying to segregate people into those able to go and those forced to do drudge work on the station, it'll just piss people off, if you're going to have away missions they would have to be the central focus of any round that they are in.

In about month or so i'll be free to make some away missions, perhaps we can get a mapping drive going? Maybe a competition with the prize being chicken.

**Comment by CptWad** [comment]
I will contribute 20 dollars towards the prize as long as its kfc

**Comment by ComicIronic** [comment]
> Solves all the problems.

Not really.
Is the gateway available from roundstart? If so, the station is going to go to pot pretty quickly, particularly if some of the jobs with hardsuits (sec, engineering) decide they're best for going through.
If the players know the gateway is going to open at some point, it creates the same problem, since people aren't going to do their station jobs if they know they can leave.

More importantly, a roundtype removes the idea of player choice in whether or not an Away Mission happens. I want it to be a reward for good power generating by Engineering, and also something that the crew can decide to do together, instead of requiring specifically that the game itself or admins say "ok, now you can have your away fun". Especially since that opens up avenues for introducing more content.

As for the station becoming deserted, who wants to be the people left behind on an away mission? I think you'd see a lot of suicde-to-observe cases whenever one happened.

**Comment by Exxion** [comment]
Maybe have each mission have a specific number of players of each of a few jobs, plus some unspecified job slots so assistants, the bartender, the clown, etc. can come too
Engineering and security come to mind for possible specified jobs
Engineering as technicians on the mission and sec to protect everyone
Also, that would encourage people to actually *play* those jobs so we might have fewer rounds with zero sec and/or engineers.
Then maybe have the away missions have set goals that don't take too long and only allow a given player to go on an away mission once per round to give everyone a chance

There's probably some glaring flaw with that plan, but I can't see it

**Comment by Unfit** [comment]
Giving away missions their own gamemode won't be good, because that would make most of the jobs useless (like all of service, xenobiology or xenoarchaeology) and those who picked them would simply suicide unless they're autistic
As for the gateway, it only should allow in 4-5 people per round. This will both make designing away missions easier and remove the problem of half of the station disappearing.

**Comment by clusterfack** [comment]
Ooh thanks for this comic

**Comment by PJB3005** [comment]
To revive this old thread:

I think it'd be very neat if admins could load map files as away missions manually at runtime.

I also believe away missions should have special scripted things happening in them (much like goon).

In general my dream would be admins being able to make huge scripted events, with background music for areas, custom mobs, items, machines. These wouldn't be able to be powergamed like R&D, as the general playerbase wouldn't be able to know them very well.

Also procedural away missions, that'd be the shit too.

Powergaming and them simply being boring after seeing them twice (not to mention being able to just go to GitHub to find where the loot is...) is the exact issue with away missions, there's no replayability value other than the loot.

**Comment by gbasood** [comment]
Bussed away missions are the only way I see away missions working well.

Maybe we could allow away missions to have preset SDQL calls to work around a lack of real scripting? It wouldn't allow for things like "Rescue a hostage stuck on an asteroid before time rounds out" very well but just an idea.

**Comment by PJB3005** [comment]
@gbasood SDQL isn't the tool for that, ideally we fix NTSL so it's more powerful (OOP) and then allow admins to add scripts to event hooks on atoms.

For example, event hooks for when a wall gets cut through, somebody walks in somewhere, somebody presses a button, something regains power...

**Comment by Probe1** [comment]
We redid away missions.  A while ago.,
