### ISSUE TITLE
Give Miners a Science headset, or Scientists a Supply headset

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4745]
More often than not there's no communication whatsoever between miners and scientists (and even less with mechanics), which is terrible for inter-departmental cooperation and leaves both ends to guess if the other is doing their job at all.

These last shifts when I played either role, I printed a station-bounced radio and abused the fact that you can listen and talk into any channel with them, purely to be able to talk to the people on the other end. It's improved the cooperation between jobs a LOT, and the quality of my job in general. Especially as Miner, because then I can check if anyone's doing R&D, make sure research is done and I'm not too early when coming back, check if the Mechanic exists and how many materials does he want, check if Robotics knows what they're doing and whether they will need phazon or not...

Maybe if Science could talk into Supply, with the rest of Cargo overhearing, they could even offer to mail the materials (I'd like to point out that there is even LESS communication between miners and Cargo than there is between miners and Science).

Ultimately, if radio privacy is a concern, maybe create a new "Mining" channel that only Miners and Scientists can hear into?

**Comment by Shadowmech88** [comment]
I'll vote for this, especially the new channel. I remember one round where I was using a station-bounced radio to talk with the miners, and I was able to use Telescience to send them weapons, retrieve xenoarch items too large for them to carry, and beam processed materials directly in from the asteroid. But that was only possible because we were communicating with each other and he was able to tell me when he had something and where it was in relation to him.

**Comment by dylanstrategie** [comment]
Miners should really have a special miner headset that allows them to listen to Cargo and Science. Most of their job revolves around supplying Science, they shouldn't have to ask on Common for Science's attention
