### ISSUE TITLE
Mechs: No remote lockdown, maintenance mode can be disabled in one click, detonating beacon does almost nothing, hijack/murderbone yes

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4792]
There is no way to boot someone out of a mech short of blowing it the fuck up. Which is a problem on itself, but twice as bad because the exosuit control console to blow them the fuck up does almost nothing.
Expanding on that: You can theoretically use your Science ID to enable maintenance protocols on a Mech, but there is an option to disable it from inside the cockpit (and combat mechs start with it disabled, as retarded as that is). Now there is nothing you can do about the guy in the mech short of responding lethally. Look at how people react to Hulks to see why this is a problem.

Now, you might say, if the guy is being a problem, use the Exosuit control console to remotely detonate the mech, right? For some reason, it does laughable damage. It left a Ripley at 60% integrity, and you can immediately repair it with a welder afterwards.
Compare to a rogue borg, for example, which you can lock down and blow up at any time. Except that, unlike a borg that requires an emag or subverting the AI, your mech can be hijacked at any time by anyone unless it's DNA locked to a single person. You can't leave an Odysseus in Medbay for all of Medbay to use, because then any chucklefuck can climb on it and become unstoppable short of the rare ocassion when Sec gets ion weaponry.

This is all without mentioning antag Science members, which have EXTREME murderboning potential through combat mechs.

IMO, disabling maintenance protocols should require removing your mech's tracking beacon, and the "detonate exosuit" safety protocol in the Exosuit control console should do what it claims (there is only one console and you can blow it up in any case)

**Comment by Ephx1** [comment]
What about a way to set Mechs to specific area access as an option, for like all of medbay?
Also a way to eject the pilot outside, especially MMI and posibrain.

**Comment by Shadowmech88** [comment]
The last time I used a beacon to detonate a mech, it didn't visibly affect the mech, but it was rendered immobile and inoperational.
Did you confirm that the mech still worked after detonating the beacon?

**Comment by 9600bauds** [comment]
Yes, I detonated the mech beacon within the minute of it getting hijacked, about ten minutes later it showed up to use the mech recharging station and I still couldn't do shit about it (other than realizing, in hindsight, that next time it happens I'll deconstruct the rechargers)

**Comment by FudgePucker** [comment]
You can't really argue about antag science.
They are the antag job role.
If you are an antagonist scientist who isn't a complete and total retard you automatically get green text.
It's a fucking choose your own adventure book, only instead of adventure its mass murder tools.
And that's where some of the difficulty of being a traitor scientist comes from, no one fucking trusts you.
Mechs are near the bottom of the 'Crashing this station, WITH NO SURVIVORS' list of tools science has.
Plus the fact they would just not put a tracking beacon in the mech in the first place to prevent lockdowns.

**Comment by 9600bauds** [comment]
The tracking beacon is automatically added (like the cell and the internal airtank).
An antag scientist should be able to remove the tracking beacon, but it'd be great to be able to do anything about hijackers or at least slightly hinder mech murderboning sprees (They are pretty damn strong, and the driver can still be fully armed and armored after they bail, I don't know why you say they are near the bottom of the list of stuff you can do)

**Comment by Ephx1** [comment]
This is more about preventing assholes getting snagging your mech before you can get it done rather than antag scientists being Unstoppable.

**Comment by 9600bauds** [comment]
That's absolutely terrible.

**Comment by 9600bauds** [comment]
Looking at this again, there's no way to remove any of the mech parts, and you can't add a tracking beacon to a mech if it doesn't have one.
This is even worse than I once thought.

**Comment by Probe1** [comment]
this is only tangentially related but mechs need a check to prevent multiple beacons from being attached.  I built a couple of gygax's one time for an arena fight in the bomb testing range and someone who wasn't in the loop got antsy and slapped 2 beacons on each on top of the one that was already there.  

the mech control console looked ridic.

**Comment by FudgePucker** [comment]
@9600bauds I know how over powered mechas can be, like I said, science is a choose your own adventure book, only instead of adventure its mass murder tools.
You can make 6 bombs that fuck the station sideways.
You can make grenades that spawn 12 monsters.
You can make a chem desp and rapid fire syringe guns.
There are so many fun things to do as a scientist antag, that murder boning with a mecha seems kinda on the bottom of the list.

**Comment by FudgePucker** [comment]
Double posting because I had an idea brewing for a while and might as well slip it in here for a reaction before making an entire new featrue request, but what if you could install PAI's into mechas?
Don't call me an idiot yet. They would basicly be smart tanks from GitS, only unable to use weapons.
You can call over radio for assistance, and then your PAI can turn on, head over to you, and then open up for you. It can close the hatch and walk around, and then open it to let people in (It gets a prompt to allow when someone trys to enter it.). Also it would let PAIs have a way to use a radio.

Plus you would basicly have a giant robot buddy.

**Comment by Shadowmech88** [comment]
You can already have posibrains and MMIs in mechs, but I like the concept of pAIs acting as a supplementary AI rather than a full pilot. I've seen similar things suggested by people where a pAI could be slotted into a hardsuit and made to walk around using it in the event that the wearer is knocked unconscious, so it could move its master out of harm's way.
But yeah, that'd be material for a new feature request.

**Comment by FudgePucker** [comment]
Alright then I will make it later tonight then.

**Comment by Ephx1** [comment]
@Shadowmech88
IIRC, Bay has a system for pAI insertion into hardsuits with their neat hardsuit system, although I'm uncertain if they can actually control a hardsuit.

Last I saw of that was an old attempted port by Riri, so I doubt we'll be getting it any time soon.

**Comment by 9600bauds** [comment]
Pls wait before trying to implement pAIs into mechs, I have a PR open mechs and another one on the way

**Comment by FudgePucker** [comment]
Implying I know enough to implement that.
All I know how to do is basic shit.
I don't want to touch things that require more than copy and pasting and changing some parts.

**Comment by BestName** [comment]
>use the Exosuit control console to remotely detonate the mech

It's not supposed to detonate the mech silly. It detonates the tracking beacon which hits the mech with an EMP.

**Comment by 9600bauds** [comment]
It's not actually an EMP, it's a full-scale explosion that deals damage to the mech according to the battery's charge.

The point is that it still doesn't really do shit.
