### ISSUE TITLE
Laser scalpels don't work as regular scalpels for surgery, which although intended, is bad&unintuitive

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4803]
Most new doctors expect a laser scalpel to work both as scalpel and hemostat/cautery all-in-one. In truth, it's actually only useful at the very start of a surgery, where it works as a scalpel and hemostat both-in-one-step, but then doesn't work for anything anymore: not as a scalpel, not as a hemostat, not as cautery.
Problems with this:
* It's extremely unintuitive (how on Earth are you supposed to figure that out by yourself, especially if there is only one non-descriptive error message for surgery and the item description doesn't tell you anything useful?)
* It generates unnecessary clutter (from 10 to 11 tools!)
* It undermines the usefulness of having Science actually give you stuff, because the tool in question is only ever useful for one single thing (saving you about 10 seconds total per surgery ~IF~ you know how to use it and have it at hand)
* It does nothing to help with people viewing surgery as something unlikely to be quick or even possible depending on THE RIDE this shift (some people are truly shocked that everything worked out after I do surgery on them)

Further problems with laser scalpels:
* There are three tiers of laser scalpels. They all work exactly the same, except tier 1 and 2 have a random chance to fail even if you did everything right. Why?

My suggestion would be to make laser scalpels actually work as a scalpel in all surgeries, so you can fully replace the ole metal one with something better. Then, have each tier of laser scalpel speed up the surgery step rather than... not fail it.
The same currently happens with the Incision Manager (scalpel+hemostat+retractor), which is the upgrade to the laser scalpel. Perhaps it could be made to work as a retractor as well? The sprite certainly looks the part.

**Comment by Probe1** [comment]
It hinders it more so that no one ever wrote a paragraph on the surgery wiki discussing them.  That's something we can fix right now at least.

The only thing I really have to say about it is the first two laser scalpels should be straight up commented out.   There is no need for the first two advanced lasers.  They are never printed.  The tool itself is only a marginal upgrade and does not completely replace the original scalpel for reasons listed above.  

Remove the first two advanced scalpels that no one ever prints or uses.  Expand the use of the precision laser scalpel to be applicable during any stage of surgery instead of just at the first.  A buff to its step time couldn't hurt either.  

From experience when you bring medbay these tools they don't get used half the time.  People are both unaware of what they do and unimpressed with the upgrade they bring.
