### ISSUE TITLE
Alternate Directions for Multi-Tile Sprites

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#4819]
For a new system I hope to implement in the near or far future multi-tile objects need to have some sprite to view them from the side (ie NSEW sprites). The back can likely be a simple reversed image for many of these.

The problem mainly comes from objects that have a somewhat isometric perspective like
- [ ] sleepers
- [ ] adv scanners
- [x] crematorium possibly
- [x] morgue trays

**Comment by Intigracy** [comment]
- [ ] sleepers
- [ ] adv scanners
- [x] crematorium
- [x] morgue trays

Gave morgue hubs directional sprites for N/S, E/W already existed.
The tray for the morgue already has directional sprites, didn't change anything on it, but still included it anyway. I used this to figure out how to position the crematorium tray sprite for directions.

Crematorium / Crematorium tray now have directional sprites.

| Crematorium: | Morgue: |
| ------------------------ | ------------------------ |
| ![](http://puu.sh/iC4wE/3312b9dd0d.png) | ![](http://puu.sh/iC4yK/6c29589dad.png) |
|  |  |
| ![](http://puu.sh/iC4sU/16731520fc.png) | ![](http://puu.sh/iC4zn/6b0e8b6300.png)
|  |  |
| ![](http://puu.sh/iC4wc/08fdd8288e.png) | ![](http://puu.sh/iC4zO/d208ea467c.png)
|  |  |
| ![](http://puu.sh/iC4xj/561a35c1fd.png) | ![](http://puu.sh/iC4Ae/5b25ebbf27.png)
|  |  |
| ![](http://puu.sh/iC4yk/79b71c29e0.png) | ![](http://puu.sh/iC4Ay/6f813efd47.png)
|  |  |
|  | ![](http://puu.sh/iC4AS/c651382e7d.png) |

I'll do sleepers and adv scanners tomorrow.

http://puu.sh/iC55y/a34cb18259.dmi

**Comment by clusterfack** [comment]
Thanks! This'll help speed up #5001

**Comment by Intigracy** [comment]
By adv scanner, do you mean the green looking sleeper?

**Comment by clusterfack** [comment]
In box medbay there's the sleepers, to the direct left of them are the adv scanners. I think they are red though.

**Comment by Intigracy** [comment]
Nope, they're green. The red sprites aren't used anywhere in the code as far as I can tell (from a quick ctrl f all files search.)

Anyway, tomorrow.

**Comment by Intigracy** [comment]
- [x] sleepers (I didn't make the controls yet, though.)
- [x] adv scanners (I didn't make the controls yet, though.)
- [x] crematorium
- [x] morgue trays

Sleeper directionals ~stolen~ borrowed from /tg/'s codebase. From there I worked magic to make the adv scanner directionals / animations since /tg/ doesn't have animations. They also removed the control sprite completely, and its function is on the sleeper itself.

I'll get to the controls soon, it'll take actual effort since I'm making it from scratch.

| Sleeper: | Adv Scanner: |
| ------------------------ | ------------------------ |
| ![](http://puu.sh/iCS1i/aa4bae5e05.png) | ![](http://puu.sh/iCS3k/305d84a29b.png) |
|  |  |
| ![](http://puu.sh/iCS40/c6709526e9.png) | ![](http://puu.sh/iCS69/b1bf319dc0.png)
|  |  |
| ![](http://puu.sh/iCSdO/3a27b61db7.gif) | ![](http://puu.sh/iCSdn/9ffa8b50fb.gif)

http://puu.sh/iCSr8/3ea4180bef.dmi

**Comment by ComicIronic** [comment]
We can finally get rid of ORIENT!
