### ISSUE TITLE
Different z-levels share the same drift

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#4838]
Unless I got REALLY lucky and each z-level ended up on the same drift calibration on telepad, it seems broken.

**Comment by Shadowmech88** [comment]
Elaborate, do you mean teleporter drift or Z-level drift? Since that Telescience change a while back, there are two drifts now. There's the teleporter drift which has been around forever and is local to the teleporter itself, meaning one calibration is good for use on any Z-level. Then there's the Z-level drift, which keeps the coordinates the same, but shifts the Z-level under it around so that the offsets between one place on Z-level 1 and another place on another Z-level aren't the same between rounds. When retrieving stuff from other Z-levels using coordinates, like with a GPS or suit sensors, you'll still only need the basic calibration since the coordinates on the other Z-levels aren't shifted, only the locations are.

**Comment by Ephx1** [comment]
Alright alright, I misread the pull then, I had assumed that each z-level required different calibrations for each so as to deter finding out the simple calibration then applying it to each other z-level. I didn't think every single coordinate was altered.
Excuse my stupidity.

**Comment by clusterfack** [comment]
No its only there to prevent you from making a telescience sheet of all object coordinates on all zlevels. It is not noticeable ingame in any way.
