### ISSUE TITLE
Vox raider dart gun doesn't accept beakers

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#4847]
Found this out today when someone delivered a gun to R&D.
Tried to replace some of the beakers in it with other stuff, but once you pop the beakers out nothing can go back in them; not even the ones you took out.

**Comment by 9600bauds** [comment]
It uses vials, not beakers.
Which is pretty stupid and should be standardized

**Comment by Shadowmech88** [comment]
It does come loaded with beakers, but can only use vials. Which is stupid because that means that even if you do refill it, it will never be able to hold as many chems as it did to start with. And it's terrible for the raiders themselves since now instead of stealing just a box of beakers, they've got to take a whole fucking autolathe or the vial box from Virology in order to refill the dart guns.

**Comment by 9600bauds** [comment]
Not exactly a bug, more like a chain of oversights that culminate into a heaping pile of what

**Comment by clusterfack** [comment]
What you just described to me is a 'bug'

**Comment by SonixApache** [comment]
I don't know what else vials are used for other than virology, but maybe bluespace vials is an idea.
