### ISSUE TITLE
Need more mols in telecomms cooling loop

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4944]
Why are there so few mols of gas in telecomms cooling loop?  Why aren't there more?  I've encountered a problem with telecomms getting slightly toasty recently and no one had touched it.  Is adding more mols something we can do to improve it?  The pressure tank that's responsible for keeping the control room warm has 1000.  The two below it responsible for keeping tcomms cold barely have 10 combined.

![ss 2015-06-12 at 07 04 30](https://cloud.githubusercontent.com/assets/8550416/8141505/e6f03fca-1135-11e5-805c-b4d2bc278917.png)

**Comment by clusterfack** [comment]
Hm, could be a bug where the pressure tank isn't reconciling the air with the pipe network its connected to.

**Comment by Kurfursten** [comment]
Yeah, I've noticed this in many rounds, especially those where any real cooling needs to be done in tcoms.

Needs map issue tag though

**Comment by dylanstrategie** [comment]
I did some work on the Telecommunications waste loop so that it drains into space instead of connecting to the general waste loop to avoid a perfect 8000°C Telecommunications half of the rounds. Now Tcomms no longer fries every time a fire is started somewhere, but maybe the cooling loop accidentally drains into waste. Needs to be checked
