### ISSUE TITLE
There Should be a Way to De-Traitor People Without Borging

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5008]
This is more of a discussion than a straightforward request. Currently when a confirmed traitor is captured by Security, their only viable options are to outright execute them, borg them, or put them in perma. The chances of being rescued from perma are slim, and even if you're able to attempt breaking out yourself, it has a high chance of failure due to warden/AI monitoring, especially due to the AI's connection with Atmos alerts. Execution straight-up removes the person from the round, causing them to lose much and the station to gain no more than it would have if you'd kept them alive locked in solitary. Releasing them is right out, even with a loyalty implant they still retain their traitor-ness so you can expect them to go right back to murdering as soon as you take your eyes off them. Which leaves borging as the most viable option. But from an IC standpoint it's a little unsavory to do so against the prisoner's will, even more so than execution would be. Not only that, but many people don't like playing borg, and some are banned from the role either by choice or otherwise. My point here is that there isn't a way to get rid of traitors if you (for whatever reason) also don't want to ruin their round. Cultists can be deconverted and implanted, revs can just be implanted.
Anyway, I was picturing something like a mind-wipe injector. Requestable from Centcomm via IAA fax (with adequate proof of the prisoner's traitorousness attached), and when injected, it will remove the player's antag status, randomize their name and appearance, and IC-ly prevent them from remembering anything before the injection, essentially making them a brand new crewmember.
Obviously ideas can be bounced around, but mainly I just think that there should be a way to remove a traitor's antag status (thereby making them not a liability to release) as well as allowing them to remain human, or at the very least something besides a silicon.

**Comment by FudgePucker** [comment]
This brings up many questions on gameplay.
How much proof is required to use this? 'We found a hacked ID card on him with some wires attached to it, plz send us a device that can erase someone.' Shit the mind wiper in a morality point of view would be more like murder than borging, borgs still have some of their ego left, they just have it somewhat locked away and have laws bounding them to not do bad things. The mind wiper would erase their ego. What if there aren't any admins on? Someone could still get back into a body with antag status if they manage to get themselves blown up, taken out of the MMI, and then monkey man cloned.
Why are we so worred about getting people back into the round anyways? If you turn on traitor you know what you signed up for, you get rule one immunity, but you don't get rule one protection. Everything you do is 'valid' but you are 'valid'. Don't want to get removed from the round for having some object on you? Turn off traitor. We have so many diffrent ways to get back to the round outside of cloning, defibing, and borging. You want to know how many goon has? ZERO. Goon isn't a good example to follow though, their player base is shitty. (I died in the middle of the hallway and wasn't cloned all round, everyone just walked over my body. Screamed out that CE was a traitor as he shot me twice with a deringer, everyone didn't even care or notice, funny fact is that I wasn't his objective, he had access to his objective, he managed to walk into AI upload without doing anything in there, and went braindead. Fuck goon.) The real question is, should we care so much if a traitor got caught? The fact that security or any player would care enough to fax centcom and wait on something, much less just borging you instead of murdering you and spacing you to 'GIT DEM VALIDS' is such a god damn rairity.
If you get caught by security, accept your faith and become a borg, go autismbuild as MoMMI on derelict, wait until you can become a part of the greentide, or just ghost.

**Comment by CptWad** [comment]
nah. If a traitor gets caught he gets caught. Giving people redeem cards just because they lost their antag role but still wanna play is not fair. Not to mention confusing for round end shit and admins.
If you select antag and get it you stay is so long as you live. The rule to live by. De-traitoring is not something that should be an option. Its silly and loyalty implants are sort of dumb now that rev no longer is in rotation.
