### ISSUE TITLE
Emag replacement - Hacktool

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#5035]
Wheee.

Idea: Remove emag, but in its place have an item that strongly resembles a multitool. Same price, or maybe a little cheaper idk that's game balance.

The device would function as a multi tool, but if you did special and James bond something to it like used it three times or threw a pen at it or something, using it on objects that have an emag functionality would open up a window with a selection of buttons.

You could select what you want to accomplish based on the object, say; for doors to open or bolt them or depower them or something. Or for vending machines you could hack it to vend a specific object, or change functionality, or whatever. Or FULL OVERRIDE, which would have the same effect as an emag normally.

Pushing your selection would then bring you to a quick minigame. Succeeding means you do what you set to do, failing knocks you back to the previous menu. If you fail multiple times in a row on the same machine in the span of a 30 second to a minute cooldown, something bad might happen. Ie, door shocks you, camera alarm goes off, etc.

As for the minigame itself, you could just make it a wire clamping minigame, or heck just steal the system shock 2 hacking 3 in a row thing. Whatever. Could just be a lights out. Or SNAKE. eat all the data without crashing.

Would make emags from instant to 'gotta stand there and look cool for a bit', and I guess would make hacking cyborgs hardmode idk how you'd handle that.

**Comment by ComicIronic** [comment]
Minigames are a cheap and bad way to have the user feel challenge in doing something.
They also go against the game's design ethos.

**Comment by Midaychi** [comment]
Well ok. What would be a better way to do it? A timer?
Just click the button and wait a few seconds and hope nobody gets curious?

**Comment by IratePirate** [comment]
All that really needs to happen is the emag's literal hundred uses divided up slightly. For 3 tcs you should not essentially become the god you are now with it. Either that or it is made much pricier a la Goon which would anger traditionalists who wish to buy it every single time they get tator religiously.

**Comment by Shadowmech88** [comment]
What about making the emag itself free, but useless on its own? Then the traitor has to buy modules for it like a computer interface module, airlock interface module, silicon interface module, and so forth.
They can spend all their TC and have an emag that does everything, or they can spend a bit of TC and have an emag that does just one thing.

**Comment by Midaychi** [comment]
Instead of an empty emag card you could just make each of the functions a pda app, and have them either well disguised or hidden unless unlocked with the syndicate code. That way you could swipe the pda instead of using an obvious looking card.

**Comment by Shadowmech88** [comment]
But it also means you couldn't stash it anywhere since your PDA is also your uplink, and it's kind of necessary to you.

**Comment by FudgePucker** [comment]
@IratePirate 
There really needs to be a way to ""emag"" things with out needing an emag.
Emag is like research, its a feature sink, have a nice idea for this object for a traitor to use, but don't want normal people to use it in that way? JUST FUKIN EMAG IT.
I have never bought the emag for the use of opening doors. But I might be missing some fun feature because its a feature sink.
Maybe add in new items that you can make for hacking.
Maybe using wire on sodering iron and then attaching a batery will let you fry electronics to do things, like open locked lockers or disable locks on emitters.
The only problem with this is our servers culture, where if someone has a very illegal hacking device like this and security arrests them, security is a apperntly shitcurity for arresting them, he ain't no antag, graytide station wide.
@Shadowmech88 @Midaychi 
Maybe a solution to that would be being able to lock it in someway to hide the app, security walks up to you, lel code green random search, just push a panic button on the PDA and it locks away the hacking tools.
