### ISSUE TITLE
Pepperspray needs a buff

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#5142]
Unprotected face and eye sprays need longer stuns as well as medium length lasting blindness. That's my personal opinion, but really, give it reason for use over other tools.

**Comment by Probe1** [comment]
sure but the issue isn't that its weak, its that no one that plans on committing any crimes goes without eye and face protection

**Comment by dylanstrategie** [comment]
To be honest, eye protection shouldn't protect fully against sprays, because you would have capsaicin all over your face and it would immediately jam up your respiration

Only full-face masks such as gas masks should protect fully, or a combination of eye coverage (to prevent temporary blindness) and mouth/nose coverage (to prevent respiratory shock and thus immediate pacification)

**Comment by FudgePucker** [comment]
Put a pepper spray recharger in wardens office that recharges it with polyacid.
There, solved the mask issue. :^)
