### ISSUE TITLE
A change to APCs, and ghetto battery racks

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#5187]
A feature request/change/refactor idea?

APCs as they are, work, and that's fine. This is an idea for an alternate way for them to work.

1- Remove batteries and battery handling from apcs. Apcs turn into glorified subnetwork power switches and feed directly off whatever power's in the power network to give it to its subsystems. Yes this means that engineering/solar SMES would be directly responsible for powering everything.

2- Take the atmospherics control computer and copy pasta it into engineering, then refactor it for using apcs instead of air alarms. Then engineers can then access and control npcs that have remote access turned on.  Sensitive areas and the Ai core would of course, have their remote turned off by default.

3- You can still have your own little power area though, without fussing with generators or power sources like solars.
  Make a ghetto battery rack with metal, wire it up, snip the wires and screw them to complete a little portable machine that accepts batteries. Load it and wrench it ontop of a knot to provide power to the area. The downside is that it can't also charge the contained batteries due to voltage fluctuations, and if emp'd, the ghetto battery rack will completely discharge into the power network and blow the lights.

The non-ghetto one doesn't discharge on EMP, and ALSO allows you to charge from that network like an smes, but requires use of a soldering iron to make a board and some capacitors to handle proper voltage regulation. Supports having a deployable terminal for connecting to external power, so you can use it as a buffer mini-smes.

**Comment by Probe1** [comment]
>power is interrupted

>entire stations power goes down instantly

**Comment by Midaychi** [comment]
^ feature

**Comment by Probe1** [comment]
that's a dumb feature.

**Comment by Midaychi** [comment]
It promotes engineering to either do their job or get lynched. Engineering not doing anything will lead to people breaking in and doing it themselves.

**Comment by Midaychi** [comment]
You can also pre-map a battery backup into secure areas, so they aren't meta bait.

**Comment by Midaychi** [comment]
Alternative suggestion, because the first one could lead to some assistance with insulated gloves snipping lines to LOL POWER OUT.

- Map each area with their own single backup power rack.  Basically, medbay and all its sub areas would feed off a single rack and that rack would feed off the station power. Same for the entirety of science, sec, etc.  Then instead of charging 50 apcs you just charge one rack per area, and each area has its own centralized power buffer.

**Comment by PJB3005** [comment]
Yeah, I recently finished alien: isolation and I have a LOT of inspiration to make SS13 ACTUALLY FEEL LIKE A FUCKING SPACE STATION!!!

one of those is what @Midaychi is suggesting here.

**Comment by FudgePucker** [comment]
:-1:
There are 10000000000000000 issues with this.
First up, do you even fucking play engineer?
If someone clips a single wire in maintenance as it is now, engineers have to go all the way around the station looking for clipped wires before they get lynched. WITH YOUR SUGGESTION, THEY DON'T GET A NICE PERIOD OF TIME TO LOOK FOR IT, NOPE ITS JUST LIKE A FUCKING FREE POWERSINK.
YEA, THIS WILL MAKE IT SO THAT WIRE CLIPPERS AND YELLOW GLOVES ARE 10000 TIMES BETTER THAN A POWER SINK.
>It promotes engineering to either do their job or get lynched.

Two words.
Fuck.
You.
Second up, have you ever seen the black out event on the server?
The powernet changing rapidly and all that updating causes it to lag really fucking hard.
NOW IMAGINE IF YOU CAN JUST CLIP WIRE PLACE WIRE CLIP WIRE PLACE WIRE TO MAKE THE SERVER UNPLAYABLE.
Third up, there would be little to no reason for making an engine when science can just print super power cells and any jackass with yellow gloves can make the backup rack.
Congratulations, you in the same update made engineers lives even more hell and removed more importance from the station.
:-1: :-1: :-1: :-1:

**Comment by PJB3005** [comment]
@FudgePucker, first of all, stop ranting, second, you're thinking of it like this: APCs have no cells anymore.

What about HV cables that needed more than a fucking set of wirecutters to clip?

**Comment by PJB3005** [comment]
The current station's power grid is a JOKE!

Seriously, backup generators in a lot of places, backup batteries, rerouting power, MORE REDUNDANT WIRES, you people are underthinking this, I am ALL for this.

**Comment by FudgePucker** [comment]
@PJB3005 
You would be able to clip the new fancy wires by just using IED then, just drink a soda, get some wires, find a fuel tank, and bam, power is off line.
Setting up power is already a pain in the ass, APCs having backup power buys you time for setting up engines.
Backup generators is over complecating the job that is already too complex for 95% of the player base.
The problem that prevents science from just printing super cells for the entire station is that you have to swap out the cells once they dry out, cutting off power for a moment and being a pain to do, this would let them just pop in and pop out cells with no interuptions.
And they would do it every round because you can only do it when you have power in research, not when you need it in an emergancy.

Shit, the fucking scale of the PR to do this would be, new items, changing a current system, new machines, new wires, and massive balance changes, just to over complicate the hardest, most understaffed, and complex job on the station.
Now as it is if a bomb goes off you have to seal up a giant fucking hole and repressure the area that takes a fuck ton of time to do, now if you don't get the wires fixed every FUCKING ASSHOLE POWER GAMING ASSISTANT WILL BE BARGING DOWN THE DOORS EVEN MORE?

THREE WORDS.
GO
FUCK
YOURSELF

**Comment by PJB3005** [comment]
@FudgePucker, thanks for the

![](http://puu.sh/iEYtZ/8b1704356b.png)

**Comment by dylanstrategie** [comment]
I'm fine with that rework. What I would consider is turning APCs into the area's power interface, like air alarms are an area's air machinery interface already

APCs should still be able to buffer some power, but nowhere as much as they do currently. I'd also like to use this to slowly phase out magic electricity-proof material and make using the main breaker to work on electrified wires the norm, in that case we could make it so that there are main power wires that feed the station and secondary power wires with a fusible and that can be cut of all power via the main breaker

**Comment by Midaychi** [comment]
Well, that happened. I do agree with some of the more coherent points Fudge is making though that the original post in this issue would make random assistant bumfuck with insulated gloves able to go "LOL WHAT POWER", which is why I added that addendum about having standard racks spawn on map per area so everyone would have a battery backup. Medbay would get a single rack in their storage room, science would get their own in the server room, Engineering already has smes so they don't need it, etc.

**Comment by PJB3005** [comment]
Yes, dylan gets it

**Comment by PJB3005** [comment]
@Midaychi, bay already has substations everywhere, like that

**Comment by Midaychi** [comment]
Bay substations are just on/off switches. They're not really much in the way of power handling.

The thing is that if you just turn apcs into dumb switches you can streamline them and possibly do some optimizations. Instead of each apc being a power storage you'd just have one big battery metering out to a number of apcs, which means less machines on the network have to process charging.

**Comment by dylanstrategie** [comment]
Then, the idea would be the following : 

- Engine produces a shitload of power, feeds the Engine SMES cells
- SMES cells are set to what the station needs and output into the main power grid which can survive something like 5 million W no problems (otherwise the primary fusibles break, and if the fusibles are bypassed the cables melt)
- Each department branches out in a special room with a SMES cell, which acts as a power regulator
- Going out of the department SMES goes a secondary network that runs through the entire department and can survive 250 000 W (since 200 000 W is supposed to be SMES max output)
- Each room with an APC has a secondary fusible and a power regulator that makes sure the power isn't overloaded
- Tertiary can produce terminals with APCs, which runs equipment and lights and resist about 50 000 W total
- APCs no longer store power (outside of a thirty seconds emergency charge) and now allow you to turn on and off all of the power consuming equipment in the room selectively
- The APC can also modify the power regulator. If it is turned off, you can safely operate the wires

Then, in general : 

- Insulated gloves no longer have 100 % but instead something like 90-95 %. If power is too high you'll get the shit shocked out of you
- Electrified grilles will use the room network, which means they no longer kill but instead pacify

**Comment by Midaychi** [comment]
Something like that, except using SMES buffers makes powersinks useless. It'd be like putting a powersink on a solar that goes through the smes; you'd just suck the solar power.  The department smes or token smes stand-in should be vulnerable to powersinks in a way that normal smes are not. Either that, or powersinks need a redesign too.

**Comment by dylanstrategie** [comment]
I think power sinks should actually buffer the energy they suck in, and be able to directly restitute it to the grid

This would have the effect of fucking up all primary fusibles on the map (so about six), and if someone bypassed the fusibles it could cause serious damage

**Comment by Midaychi** [comment]
Oh, so instead of powersinks being 'OM NOM NOM power, OH NOM NOM',
you'd make powersinks be power-trolls?  Like, They store power to a point, then suddenly discharge into the network to fuck up all the fuse boxes and subnetworks, shutting the power off and requiring maintenance and repair to put it back up?

**Comment by dylanstrategie** [comment]
Sure, that's the rework I'd propose. Being forced to change the fusibles would piss off the Engineers and can lead to totalling the power grid if the Engineers fucked around with the system

**Comment by FudgePucker** [comment]
@dylanstrategie 
Okay, I have set up hundreds of SMEs, and other engines.
I have fixed more breaches than I can remember.
I have weeks of ingame time spent as engineer.
I can barely understand what you want to do with that giant clusterfuck of recomendations.

What about the rest of the player base?
Engineering is already understaffed.
Very few players understand anything byond setting up singulo or AME.
What you want to do is add 10000 times more work for engineers?
Also
>Making insulated gloves have a chance to fail, making working in engineering impossible when working with hi output engines
Dylan having anything to do with balance at all

Please no.
Dylan real talk right now.
I love all the map updates, bug fixes, and other useful things you do. I respect your skill as a programer.

Don't touch balance issues with a 20 mile long pole please.

**Comment by PJB3005** [comment]
@FudgePucker, you don't seem to realise that this isn't that bad

**Comment by FudgePucker** [comment]
@PJB3005 
You don't seem to realise that engineering is already too difficult for most of the player base.
Lets take Dylans recomendations, on a local small scale just for engineering.
The APCs and local area can not take in that much power with out blowing up, okay remove wiring to grid as an option if SMESs are fucking up (LIKE EVERY OTHER ROUND). But wait theres more.
Just in engineering this becomes a nightmare. Any engine that is well set up is going to produce over MW... PER RAD COLLECTOR. 'well fudge, why not just use the SMESs.' Yea, but you forgot one little thing. What about the APCs in enginering itself? As it stands now the engines output goes directly into the engineering grid, then into the SMESs for the rest of the station and the back up SMES in engineering. With this change, the second you turn on the engine, engineering blows up. So the only way to solve this is to have the output from the engines go into a SMES set up that powers engineering. Sounds simple enough (if you are a good engineer and haven't just decided to take the yellow gloves and fuck off to gray tide as soon as I said SMES like 50% of engineers.), if you don't realise that the wires will have to cross at one point because the airlocks are only one tile wide in SME and AME rooms. Meaning that there will be a jumbled up mess of wires as the very large output wire can't cross with the APC wire, I am getting a headache how you would wire this shit to work, send painkillers.
OH, IM NOT DONE YET, THERE IS NOW A CHANCE OF TURNING INTO A WELL DONE STEAK EVERYTIME YOU TRY TO CHANGE THE POWER OUTPUT OF ENGINE, BECAUSE YOU KNOW, >Dylan and balance change

The workarounds for this to work is to add special wires only in engineering that can handle the load and special APCs that can handle any power. Considering one of dylans princibles is to remove snowflaking, this is fucking retarded. You would be adding a ton of stuff only used in one part of the station and make a job more difficult for what outcome?

**Comment by Midaychi** [comment]
1 - No don't generalize human beings like that. Bad. You're operating on huge assumptions and held opinions. I personally have seen many consecutive rounds in which individual engineers did great jobs, and I've also seen rounds in which individual engineers who did horrible jobs but were either backed up by mommi support or crew oversight. Also, even if the engineers suck isn't it the CE's job to oversee them? Oh hey engineering suddenly requiring actual organization.
2. Turn the breaker off before you mess with wires. Its what you do in real life when doing electrical work.
3 and beyond- Some rewiring and minor map refactoring would fix that overloading problem without requiring any fancy engineering-only stuff.

**Comment by Midaychi** [comment]
tl;dr: if engineers were as stupid and helpless as you claim, then the antimatter/singularity/supermatter would never get set up because engineers would be too busy smashing their heads into doors and trying to eat batteries.

**Comment by FudgePucker** [comment]
1. I know that engineering teams can be good sometimes, they can also have very new players who don't understand anything, and they can be nonexistant. The problem is that number two turns into number three because of complexitys and lack of guides that don't suck shit. Making it even more complex won't help. Also why would you add something that requires organization, no other department requires organization, engineering is one of the hardest jobs on the station, and all the hard work you do is erased and in the end is meaningless, making you ask yourself why you even bothered? BETTER MAKE IT EVEN HARDER.
2. So I should have to walk around shutting off the AME, turning off rad collectors, just to be able to place wires. Awesome. Gee wiz that just sounds like so much fun, I can't wait to have to do it every single round, why don't more people play engineer?
3. >Minor map refactoring > SME chamber is broken on a weekly basis > In the last week key wires were removed from maps causing power failure in diffrent areas >Time to make wiring and mapping even more confusing.

Great idea.

**Comment by ComicIronic** [comment]
Some rounds, that happens.

Glove nerfing is a terrible idea.
Shutting off the power to a whole area, just to rewire something, especially when it's likely to be in engineering, is a terrible idea.

Moving power storage from APCs to battery racks is both needless and more open to abuse.

Taking out power storage altogether is awful. Just awful.

**Comment by PJB3005** [comment]
1. if a big refactor like this happens, whoever does it should be forced to update the wiki.

2. You fail to realise that there'll be some sort of breaker box

3. Let's be honest, the wiring wouldn't be that bad.

**Comment by PJB3005** [comment]
How is having to shut off power in an area to rewire something terrible?

**Comment by FudgePucker** [comment]
@ComicIronic
Thanks for explaining what I meant without autistic spuging or all caps key.
@PJB3005
Define area.
'Oh hey, need to lay some wires in engineering? Just shut off the power, it doesn't require that much ef- OH GOD ITS LOOSE CALL THE SHUTTLE!'
Also engineering is hard enough with minimal pay out, you are adding another step to a job no one really wants to do.
Also the power changes nerf antag engineer. Shocking bolting and shutting off bolt lights is fun to do as engineer with leathal amounts of power in grid, don't even get me started on sith lord power gloves. Making it so that you can't have 10 delorians in the grid removes more options for antag engi, a bad idea when plasma flooding is right there, whispering in your ear 'guess you can't internally cook people huh, why not cook them externally?'

**Comment by Midaychi** [comment]
You keep referring to how it works now to describe problems with a complete refactor idea and it's getting kind of silly. Things would have to be changed but it would work properly and fluidly once PBJ got done with it.

**Comment by FudgePucker** [comment]
The emitters have an internal battery, but that just means you have a time limit to change wires.
Awesome, that's exactly what doing minor cable changes in engineering needed, a time limit before getting eaten by a giant black hole and banned.

**Comment by PJB3005** [comment]
I have no goddamn clue where people get the "emitters have an internal battery" myth from, however engineering's goddamn equipment network WOULDN'T BE DIRECTLY CONNECTED TO THE EMITTERS

**Comment by FudgePucker** [comment]
Because they do.
Last time I made a SME a blackout happened.
AAC was off, lights were off, and the environment atmos equipment was off, but that emitter was still going on.

**Comment by PJB3005** [comment]
You mean a power outage event?

Wanna know why?

Fucking power outage just forces all APCs to 0 charge and fucks up charging (engie and AI core are exceptions), then empties the SMES, power is still MORE than flowing in the wires going from the rad collectors and to the emitters

**Comment by Midaychi** [comment]
Rip I said emitters when I meant shield generators.

**Comment by PJB3005** [comment]
@Midaychi, @FudgePucker thought emitters have capacitors either way, which isn't true.

**Comment by FudgePucker** [comment]
@PJB3005 
Oh that makes sense my bad.
But still, that means that you can't cut power, for instance, if you wanted to put wires down to put in more radiation collectors on singularity.
Meaning that you have a 5% chance of death every wire you place.

Infact it just proves my point further, instead of having a time limit on how long you can cut power to place wires, you have no option.

**Comment by PJB3005** [comment]
What, I don't see how having to place extra collectors puts you at ANY RISK.

1. Place all disconnected wires except 1 cable piece
2. Place collector.
3. Shut off power.
4. Place last wire.
5. Turn power on again.
6. ...
7. Profit!

That takes about 30 seconds.

**Comment by d3athrow** [comment]
WOLOLO NEXIS WAS MAKING A NEW POWERGRID SYSTEM BUT IT NEVER HAPPENED WOLOLO
