### ISSUE TITLE
All Map NanoUIs Lag Like Hell

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#5260]
Every one of those nanouis that use maps and small coordinate dots to display information:

-Crew monitoring computer
-Central atmos computer
-Advanced sec computer

Use up about a fourth or greater of the servers cpu cycles when used continuously.

**Comment by Midaychi** [comment]
maybe @nullquery would know of a fix?

**Comment by nullquery** [comment]
The fix is to use my own system, which you should be able to port pretty easily.

I don't know what NanoUI does that makes it lag, and to be frank I'm not looking to investigate after developing a working alternative.

Porting the security camera computers will not be possible since there is an outstanding issue in tg to deal with that. Perhaps you could leave some feedback in that issue?

**Comment by clusterfack** [comment]
Hey that seems great, thanks. The issue of how to make one of these very specific uses of Nano not be exceedingly slow has been plaguing me for some time and I had no idea how to optimize for Json.

**Comment by Midaychi** [comment]
@nullquery I wish there were an easier way to ping you than github issues.

**Comment by clusterfack** [comment]
Not entirely insurmountable, I have a working version at the moment. All I need is to add an element to change zlevel at this point.
