### ISSUE TITLE
One-Directional Firelocks Incapable of Reporting Temperature on Far Side While Their Door is Closed

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5328]
The firelocks can always report the temperature on the tile they're closest to, but if they share space with an airlock, they can only report the temperature on the far side if the airlock is opened.
The old firelocks were able to report the temps on both sides of the door at all times.

**Comment by ComicIronic** [comment]
This is because border-only firelocks take the temperature from the tile they are on.
Really, they should not share tiles with doors.

**Comment by Shadowmech88** [comment]
Moved to Gitlab.

**Comment by Shadowmech88** [comment]
Moved back to Github.

**Comment by FudgePucker** [comment]
Crazy solution here, take the temature on the turf behind the fire lock. Fire locks on turfs with no airlock are not facing a wall, and fire locks on turfs with airlocks are clear one turf down. Will upload shitty mspaint pic describing it in detail

**Comment by FudgePucker** [comment]
![1000hoursinmspaint](https://cloud.githubusercontent.com/assets/12202731/10119498/9ddffe78-6465-11e5-86ff-5e7e42d69395.png)

In most (if not all) situations the turf behind the firelock isn't a wall and is connected to the same airzone as the turf, except that there is an airlock fucking it over. By moving over the turf that it picks up the atmospherics on from the turf it is on to the turf that is next to it on the opposing side of how it is facing, then it will properly display the correct air in the next room over instead of the air in the air lock. this shouldn't be too hard to implement, because firelocks already take the data from another turf, the turf that is right next to its facing side. Only problem with this is possibly firelocks being placed on turfs right next to walls, but I don't think there are any, and if there are, the number is sure as hell lower than the number of firelocks on airlocks.

Also I hope this wasn't too much of a clusterfuck to read, at some point I think I was typing but I had no idea what I was typing. So I drew an image.
