### ISSUE TITLE
Sleeper Suggestion

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#5360]
Sleepers are large and by used as Soporofic injectors. They also have infinite Bicaridine, etc injections. Cryo, when held next to the sleepers, makes them nigh useless.

Just a suggestion I just came up with after reading some complaints in the thread, please discuss, add ideas, etc:

Remove:

-Infinite chems
-Being unable to inject people who are past crit

Add:
-Starts with say 30u(limited amount) derma, inaprov, soporofic, etc, for just in case there are no competent chemists.
-The ability to add any chemical to the sleeper to be used to inject said chems directly into a patient(Can't synthesize like say an Oddy, you must refuel it)
-For the sake of balance, maybe make a grand total amount of say 300, 400, 500 units, however many, with more being available upon an upgrade. Or separate beaker slots where if you have a beaker with 25/25 derma and bicard, if you inject from that it will inject the mix. You would need to insert separate beakers with separate contents.
-The ability to inject crit people, duh

Make sure there's no lag to inject said chemicals, this way it gives it an advantage from syringes and/or pills. You could also then make the sleepers more specialized for later game, like one sleeper is for brute and blood loss, while the other focuses on antitoxins and burns, or whatevs.

![sanic_hedgehog_by_theiransonic-d79itrk dmi](https://cloud.githubusercontent.com/assets/6540760/8644517/aad04e50-290d-11e5-9869-30619449c19e.png)

**Comment by Probe1** [comment]
Copying what I said from the thread

>I really wish they were removed or had energy like chem dispensers. They originally only gave inaprov to keep someone in crit alive. Cryo made them irrelevant. Then freechems were added to it.

>I really don't like them.

I dislike how they can effectively negate chemistry for basic chems and think they need a downside.  I don't care what, even if it's a token downside that isn't really major.  But infinite free chems is a little too meh. 

Why bother with chemistry? 
Why get chemistry access if you don't have a chemist? 
Why go to cargo and order more supplies?
Why ask RnD for stuff?

Just hit them with a spurt of kelo from the sleeper and send them out.  It's a thoughtless decision.  I'd like a little more thought and value to be placed on sleepers.  A chemistry dispensers energy levels would be adequate, nuks ideas work as well, and there are probably more good ideas out there.

**Comment by SonixApache** [comment]
Well there's no antitox in there, that's a pretty big minus on it's usefulness at least.

**Comment by sonime** [comment]
I do have to wonder WHY they aren't used if it's just freechems. I think the ability to inject crit patients would help. Being the pessimist that I am, I think the reason they aren't used is that people are afraid they're gonna get sleeptoxed. I think removing the sleeptox from them would help people use them more often.

**Comment by nuklearcellphoneg** [comment]
They're good, as it stands, for treating noncritical patients. You can't make use of the benefits of overdosing on Bicaridine with it, but if they're hurt, you can just click most of the buttons and heal them quickly AND for the next ten-fifteen minutes.

I can see someone problems with my idea off the top of my head, mostly OP traitor related but it's nothing that can't already be done. My suggestions would basically turn it into a precisely injecting Cryo machine sans Clonex and Cryox. It really might be kind of overpowered to allow it to inject when they're not Crit'd, because then you could feasibly easily treat four critical patients at one time, in a sense.

-Well there's no antitox in there, that's a pretty big minus on it's usefulness at least.

That's by design. Toxins come from poison or overdose. If you had an infinitely injecting antitoxin machine, it would make treating any and all toxins cake for the most part. Antitoxin is easy to make anyway, but it takes a moment and can use up a lot of energy if you make big pills(which you should).

-I do have to wonder WHY they aren't used if it's just freechems. I think the ability to inject crit patients would help. Being the pessimist that I am, I think the reason they aren't used is that people are afraid they're gonna get sleeptoxed. I think removing the sleeptox from them would help people use them more often.

I think folks use them more than you think. Allowing them to inject crit patients AND having infinite chems is a bad idea. Here you go, 30u inaprov, bicard, and kelo, toss him unconscious out in the hall. Have a nice day, bye.  I think the sleep toxin thing is something that scares someone who's just past being a newbie. You can scream for help before the soporific knocks you out, as it takes a few moments to work. Chloral on the other hand is instant.

Also, it's a funny thing. If everyone was scared of being sleep tox'd, you could only treat them while in crit and unconscious- in which case the sleeper doesn't work. The sleep toxin can also help surgeons, and it's a decent last resort self defense thing for doctors.

**Comment by FudgePucker** [comment]
Sleepers being able to treat people in critical condition would be very useful, theres no point for there being defibs in secs and science outposts medbays if the sleeper can't help them get stablized fast enough.
Sleepers are to help people in very bad conditions, but most of the time in medbay you have dex+ that can do the same 10 times better, and bloodbags, and bandages, and cyro, and surgury, and a cloner, in science outpost and security all you get is a medbox, a defib, and a sleeper.

One solution would be to make sleepers have a small storage of chems and have it recharge very slowly, that way it will always have what you need when shit hits the fan, but you can't rely on it to solve every issue instead of good old chemists.

Also sleepers aren't good enough to replace chemists, a doctor spending 2 mins of the early shift where nothing happens making dex+ antitox clonex and tricord is 100 times more useful than the sleepers are. Sleepers aren't as great as you make them out to be when dex+ isn't in them and dex+ being a magical drug that sets O2 damage to 0 instantly as long as it is in the blood stream.

There really isn't an excuse not to make dex+, just take the blue medkit, take out two of the pills, pop them in a beaker, put it into the chem desp, press two buttons, and you now have enough dex+ for the entire shift.

Just make sleepers have limited chemical storage and production, let them treat people in crit, and it will be perfect. In fact, it will make science upgrading medbay even better, as the sleepers will get faster chemical production and better storage and maybe even better chem options like antitox, that you can burn up your limited supply of with your limited suply of inprov to make tricord, but that isn't really worth it when it heals up slower and, well to be honest, a chemist would still be able to outproduce it. (If science brings the chemist a large bluespace beaker, they can make a fuck ton of tricord, hell tricord is so fucking easy to make, because antitox and inprov are so easy to make, the three buttons are in a row for both, so you just clickclickclick move to the other, clickclickclick, bamn shitton of tricord.)

**Comment by Exxion** [comment]
Could give them srejuvenate, AKA stoxin2, which exists in the code but is not obtainable as far as I'm aware
Puts people to sleep, but also heals them
Sort of
I don't think it actually heals damage, but it removes most alments

**Comment by FudgePucker** [comment]
@Exxion 
Define ailments
Because having rejuvenate in the name might mean it is way too over powered.

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/8664840/af4da7b4-29aa-11e5-94da-39d3e0fa60a0.png)
Please excuse the horrifyingly ugly color scheme. I don't know what I was thinking when I picked it and I can't be assed to change it.

Put simply, it is basically a slightly stronger version of inaprovaline that also puts you to sleep, removes suffocation damage (I think; I'm not very clear on mob life code), unstuns/weakens/paralyzes you, and makes you no longer dizzy, drowsy, stuttering, confused, or jittery.
Technically, it only puts you to sleep in high doses, but all of those effects except the inaprov part only take effect at or above that dosage, as well.

**Comment by FudgePucker** [comment]
Make it so that it heals brute and burn damage at <25, replace all chems with it in sleepers, and make it so that sleepers can be used on people in critical, there we go, sleepers balanced.

**Comment by Exxion** [comment]
The data variable that the switch there is based on increases with each tick, not decreases

**Comment by FudgePucker** [comment]
Ohhhhh
I see now.
Okay I am retarded sorry about that.
