### ISSUE TITLE
Solars are broken again!!!

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5387]
They track the star's orientation correctly, however the solar panels don't update accordingly, only when the tracking mode gets changed

**Comment by Probe1** [comment]
just fuck me up

**Comment by FudgePucker** [comment]
My theory on why solars keep fucking up is that there is a sekret group of higher ups sabatoge it so that singulo has to be made every single round so that it can end the round at will.
Why do the solars keep fucking up?
Why does the SME keep leaking everyother map PR?
This is the only reason I can think of.

**Comment by Ephx1** [comment]
This is terrible. How will I go 100% green? Solars are love, solars are life.

**Comment by clusterfack** [comment]
I've seen them work as well, so if there is an issue I don't know what it is exactly

**Comment by d3athrow** [comment]
its working for me, could be a powernet node issue though

**Comment by PJB3005** [comment]
@d3athrow, though the console will still have the relative angle of the star tracked in the UI nontheless, which makes no sense.

**Comment by clusterfack** [comment]
I can just make the solar tracker not require power. I think it didn't anyway before we started playing with its inheritance.

**Comment by FudgePucker** [comment]
@clusterfack 
I came up with the most over the top, confusing, most unnecessary way to fix the issue.
A new item called the sun chart, where (using nanoui or some shit) it brings up a chart of the suns positions based on the time and side of the ship, letting you figure out how much power is going to be produced at what time and the suns position to the station.

Also add in being able to manually change solar panels positions with a wrench so that you can get power to the tracker.

You would have to use a chart to figure out what degree to set it to then go out there and change the position manually with a wrench.

**Comment by d3athrow** [comment]
idunnowhy

**Comment by d3athrow** [comment]
@clusterfack 
https://github.com/d3athrow/vgstation13/commit/e14ff2c0473d25ad7624140289a0aa467be496ba#diff-93cb213beec8ba6241f18ecfaa66192eL70
