### ISSUE TITLE
Summoning Narsie resets shuttle

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5396]
Terrible balance, and horde mode is shit.  It's too laggy for any non cultists to accomplish anything thanks to the hordes and just to add insult to injury, the shuttle timer is reset to 10:00 for no reason.

PM to-Admins: >shuttle reset
PM to-Admins: thanks coders
[07:36:45] Codermin PM from-Deity Link: working as intended
PM to-Admins: oversight 
You force Firelock East open with the crowbar!
[07:37:10] Codermin PM from-Deity Link: cultists are meant to have 10 entire minutes on the station once narsie has risen

Cultists do not need 10 minutes to celebrate that they have already won.  Anyone that gets on the shuttle gets shitfucked anyways by lag and juggarnauts meleeing them to death.  It just drags out the round and screws over non cultists that try to survive.

**Comment by DeityLink** [comment]
>Cultists do not need 10 minutes to celebrate that they have already won.
That's the real issue, the 4th objective beeing too easy. Rather than making post-narsie shorter, it should actually give non-cultists a few ways to survive.

Also as said earlier the only potential issue I see is Nar-Sie being summonned AFTER the shuttle leaves, the escapes would be stuck in transit for 10 minutes, in fact I'm not even sure how would the game handle that situation. I think the solution would be to have Nar-Sie not being summon-able once the shuttle has left.

**Comment by ComicIronic** [comment]
>That's the real issue, the 4th objective beeing too easy.

But if the cultists have already won after the third objective, why does the fourth one exist?
Most people want to get back into a new round after the old one is over. What purpose does the endgame serve, except to kill off anyone lucky enough to survive and piss people off while doing so?

**Comment by DeityLink** [comment]
That's the thing, cultist have not achieved total victory until the 4th objective is complete. The round is not "over" when Nar-Sie rises. Well, it feels like it's over because players can hardly do shit against mobs, and that's what I intend to fix there.

>What purpose does the endgame serve
You'd be surprised but being an harvester in the endgame, travelling through the ruined station is really fun, new players can use it to experiment with the runes, and there's always one or two harvesters kind enough to help ghost come back into the round has manifested ghosts, who then get converted into new harvesters by narsie.

The way I'd like to fix the issue would be by, firstly doubling the delay until mobs spawn from gateways, so that players don't get killed by bats while the post-summon lag is still in effect, and then have aditional structure spawn that players can exploit to acquire the means to defend themselves and escape the station.

**Comment by FudgePucker** [comment]
Post summon lag is the worst part of narsie rising.
It just ruins everything.
I enjoy the post narsie rising, if it wasn't for the fact that walking 3 spaces is a nightmare.

**Comment by DeityLink** [comment]
The lag subsides significantly about 1 minute after nar-sie rises, the huge quantity of changes immediately following the summoning are the main cause of the lag, Nar-Sie itself doesn't cause much lag.

**Comment by FudgePucker** [comment]
What if instead of narsie having a chance to cultify everysingle turf on all zlevels, it just cultifyed turfs around him?
The randomized culting happens on all zlevels, and I think that having everysingle turf rolling a chance to be cultifyed would lag the game a bit.

**Comment by DeityLink** [comment]
@FudgePucker All turfs are processing things:
/turf/proc/process()
	universe.OnTurfTick(src)
Rolling for a chance of being converted shouldn't take any CPU, and as you can read in floor.dm, cultifying a floor doesn't actually call the ressource expensive ChangeTurf, it only changes its icon_state and spawns a small animation on it. 

Lastly as I said a moment ago the lag subsides a minute after the summoning.

**Comment by PJB3005** [comment]
Er, actually, @DeityLink, `/turf/proc/process()` isn't used, it was my attempt of implementing `OnTurfTick()` when porting lighting because DAL used to call it, I made a turf process but it sorta killed servers so I stuck with doing it via lighting, but forgot to remove that.

**Comment by DeityLink** [comment]
uh....wait so...Is OnTurfTick() called only by update_overlay() from lighting_overlay.dm?
wait, how often is that proc called? does that mean that a turf with many atom/movable on it is more likely to decay while a turf without a single atom/movable on it will never decay? What is this nonsense?

**Comment by PJB3005** [comment]
Lighting overlays get updated whenever their color changes, AKA, they change visually, DAL did it like this too.

**Comment by DeityLink** [comment]
Then OnTurfTick() can only be called by process(), there isn't a single other proc in the code that calls it, right?

**Comment by FudgePucker** [comment]
@PJB3005 
SME Cascade seems like it is the perfect storm of lag.
Random walls being melted, including ones leading out into space, across all zlevels, meaning that the air in every single area will keep constantly updating as all the air gets vented out into space.

I don't think I have ever legitimately made it to the beach during a SME Cascade. The one time I made it we were just teleported there because it was still broken. Every other time it just lagged too hard for me to make it to science outpost or the server just crashed outright.

(Of course the cascade doesn't happen that often and usually also 50 other buttons are pressed along with it. I have prevented more SME cascades than have been in.)

**Comment by PJB3005** [comment]
Er, no, @DeityLink, it gets called from [this line](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/lighting/lighting_overlay.dm#L78)

**Comment by DeityLink** [comment]
@FudgePucker The cascade is usually only triggered when the map is already pretty fucked, so that doesn't help. 

@PJB3005 but that's what I said earlier! The update_overlay() from lighting_overlay.dm, and that makes no fucking sense, as you said it only gets called when it visually changes, but we both know it's not the case.

**Comment by PJB3005** [comment]
@DeityLink, this is how it used to be, this is how it is now, when I implemented a turf process it killed a local server every time the process fired.

**Comment by DeityLink** [comment]
I believe you, I just don't understand how it actually works.

**Comment by DeityLink** [comment]
Welp, now I do, though I still can't fully believe that's how it actually works, even though it's 100% the case, but part of me refuses to believe that it actually works like that: https://dl.dropboxusercontent.com/u/33846352/HOLY_SHIT.webm

So either way @FudgePucker that kinda proves that turf decay can't generate much lag post narsie summoning.

**Comment by Probe1** [comment]
i just want the shuttle timer to not be overridden by summoning narsie

**Comment by PJB3005** [comment]
ye

**Comment by DeityLink** [comment]
You want that because post-narsie is not very fun for non antags, am I right?

**Comment by clusterfack** [comment]
I think there are two main factors
1. The timer is just too long, 9 harvesters can explore every part of the station, get to every escape pod AND bring narsie onto the shuttle in 10 minutes
2. The harvesters are too strong and the cult mobs are too numerous, you can barely go one screen without being attacked by a cult mob and a harvester will just FUCK YOUR SHIT UP with the insane stats they have

**Comment by DeityLink** [comment]
I'm taking all this feedback into account, As I've said on IRC I have plans for at least one more large cult update (before moving my efforts to an entirely new game mode)

**Comment by FudgePucker** [comment]
@DeityLink 
Please tell me the new game mode is gokart racing.

**Comment by DeityLink** [comment]
not even close

**Comment by Probe1** [comment]
SO YOU'RE SAYING THERE'S A CHANCE?
