### ISSUE TITLE
Setup Character/Load slot failing to work

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5410]
This is a bit difficult to reproduce.  It always happens for me after the following:

Join, a round ends, the server restarts, you're not disconnected and don't have to re-open ss13.
Wait until the round starts and declare ready.  It will change to view manifest and join game..
Hit Setup Character and Load Slot.  

Load slot will never open and you have to close your client and open it again.

**Comment by PJB3005** [comment]
I know what causes this, functions like load are blocked if you're readied up, thing is, if you wait for round start without reading up, the ready up button still stays there until you click it, which will set your status to "readied up" while that shouldn't happen during the round, as such you can't use those actions because the game thinks you're readied up which *should* be impossible.

**Comment by Probe1** [comment]
smart job recognizing it.
