### ISSUE TITLE
(WEB REPORT BY: apeh REMOTE: 198.245.63.50:7777) Add an intercom Boxstation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5438]
>Revision (Should be above if you're viewing this from ingame!)
2867574f4774b4cf95b8dcf74b695a63c0cc42b3 (what a fucking compicated revision name)

>General description of the issue
Telecomms satellite room with two turrets has no Intercom. Why is that an issue? 
Because you can dump someone in there without a headset and they will be forever tormented and never found by anyone. 
It's a fate worse than death.

>What you expected to happen
Intercom to holla for help

>What actually happened
Trapped in there all round realistically but my suffering ended due to dying from chloral overdose.

>Steps to reproduce if possible
Go to telecomms satellite
Go north two doors where the room with two turrets are in
Someone strips you of your headset (and ID)
You are now there forever if there is no AI on board GG

**Comment by Intigracy** [comment]
Telecomms satellite as in that thing off the z level?

**Comment by Exxion** [comment]
Plus there's a teleporter two doors south

**Comment by Probe1** [comment]
eh

![image](https://cloud.githubusercontent.com/assets/8550416/10629037/766f4668-7799-11e5-8258-dc834857501c.png)

There's a teleporter then an intercom then a room with death lasers, and more rooms with death lasers.

Doesn't seem like its needed.

**Comment by Exxion** [comment]
Not to mention you couldn't actually use the intercom while chain-stunned

**Comment by Probe1** [comment]
tbqh with all respect to apeh, this isn't happening.
1.  Telecomms don't extend to the station on the telecomm sat level (ironic, I know.  The name is a relic from when it housed telecomms)
2.  Even if you DID have an intercomm to yell for help with, the turrets would be stuffing your sweet ass with stuns or death anyway.
3.  There's an intercomm in the room directly below it.  You could make the argument for any room except the one that has one.  And none would work since there's no relay.
   @N3X15
