### ISSUE TITLE
Box and Taxi need more maintenance/places for bases.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5470]
So I'm working on clockcult, and I realised this, meta and deff both have more than enough maintenance for things like clockcult bases.

Box or taxi however, don't.

Box definetly just needs a ton of extra sealed of things, hidden doors in maint, junk... like deff or meta, if you try to setup something like a cult base 1 assistant running through maint and you're comprimised.

Taxi it's even worse due to being VERY cramped. Seriously there NEED to be places for people to make cult bases and stuff, currently the best you've got is... like, atmos on the sec/science post.

I'm not even joking this will SEVERELY impact balance for clockcult.

**Comment by Probe1** [comment]
dunno if I agree with your assessment of Box and since we all know antags have no problems setting up bases on Box..  I'll list out the good spots anyways

Engineering Access:  Vacant Office, Aux Engineering
Research Access:  THE ENTIRE OUTPOST, Xenobio, anywhere telesci will take you including the satellite and any other location listed here
Cargo Access:  Mining Outpost, crate storage in cargo bay, mining storage south of mining office
Medbay Access:  Virology, Aux Surgery
General Civilian/Maint access:  Every single one of those goddamn rooms, aux cyborg charging, ghetto toxin mixing room, ghetto bar, ghetto bathrooms

There's just an absolute shit ton of places to hide out on Box and I'd rather see Clockcult actually finished before we start balancing the map around a mode that afaik is still in planning stages.

**Comment by Shadowmech88** [comment]
Just by nature of Taxi's design, it changes how most gamemodes are played. Nukeops for example can take out nearly a whole station with one or two bombs. It's just the way Taxi is.
As for Box, I wouldn't be against adding more maintenance, but either the departments will need to be spread out to make room for the maint between them (a major design change for a map so many people are already comfortable with) or the extra maint will need to simply be tacked onto the outside of the station, which is fine from a gameplay perspective, but is a little strange from an IC perspective, since the extra maintenance would serve no official purpose.
I wouldn't be against expanding Box's maintenance, but I agree with Probe1 in that I think we should wait and see if there's actually a problem before attempting to fix it.

**Comment by IratePirate** [comment]
Expand maint.

**Comment by Exxion** [comment]
Honestly, beside Deff's, any maint looks pretty sorely lacking
Box has enough areas for bases, but not enough *good* areas
Box's maint should be improved, but I'm not sure specifically how

Taxi's maint is so ridiculous and convoluted that it has hiding places even though there's not much space
Taxi only has like two good maint bases, but one of them is *really* good, provided the janitor is in the cult or whatever needs a base

**Comment by Probe1** [comment]
Do you feel like this has been fulfilled for Box since the recent addition?

**Comment by ihadtoregisterforthis** [comment]
Box has new rooms, taxi is no more, and the clockcult has been stolen anyways.

**Comment by Probe1** [comment]
this was addressed and as @ihadtoregisterforthis succinctly put it, the underlying issues are no longer present.
