### ISSUE TITLE
EMPTY ATMOS AT ROUNDSTART

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#5473]
http://i.imgur.com/TMRdg4n.png

VIVA DEMOCRACY

**Comment by Exxion** [comment]
Remember that one time Meta won the mapvote even though the Great Tile Switcheroonie fix had yet to be merged and the entire station filled with plasma almost immediately?
Prepare for that to happen every third round

**Comment by AutismSpider** [comment]
get ready for the station to flood with gas 75% of the time if this happens.

**Comment by Boxe** [comment]
terrible idea

**Comment by utilitas-** [comment]
great idea

**Comment by ihadtoregisterforthis** [comment]
okay idea, I guess

**Comment by SkowronX** [comment]
No way this can go wrong.

**Comment by Probe1** [comment]
The Good:  People will have to learn atmos.

The Bad:  People won't bother learning atmos.

The Ugly:  We won't have atmos.

**Comment by AutismSpider** [comment]
the lack of atmos is good and bad.

stops the ebin emag/hack into atmos for plasma flooding by antags and rouge/malf ais form doing it.

**Comment by IratePirate** [comment]
I think plasmafloods need to go anyway, they ruin rounds with rogue AIs, give atmos literate antags an incredible amount of power and generally fuck up any round they occur in with shitter shattering lag. Atmos is mostly just a headache that takes players away from Engineering and rewards them for pure autism instead of actually helping the station out.

**Comment by Exxion** [comment]
Occasional plasmafloods are fun, but they get old very, very quickly

**Comment by Cyadox** [comment]
I see this being more grief than good. Yes, Atmos takes like 2 seconds on Box to optimise, yes there's literally dick all for you to do aside from normal engineering stuff and occasionally running over to a breach with a can of air, but building an atmos from scratch? No way. Besides, people will just build it how it is, aside from the pipes being below grilles/windows.

If there somehow was a huge reservoir of air at round start so people don't suffocate 10 minutes into the round, I could see this being good. If atmos was literally empty, the vents would have nothing to pump, and if there's no atmos techs? Bye bye station. Maybe dial it back by making just the waste/waste filter and custom mix lines not set up at round start?

**Comment by Exxion** [comment]
Plus it wouldn't make any sense
It would imply that Atmos had been demolished at the end of the last shift for some reason

**Comment by Cyadox** [comment]
Exactly. IC it just sounds retarded - a space station with no air supply? OR waste management? Doomed to start.

I can understand the players wanting more incentive to play and experiment with Atmos, considering there's a lot of stigma around just how complicated the job is, even though it's pretty simple as it is. Maybe a more straightforward guide is needed? Or something half-finished to give something to play with, even if you're not good at atmos?

**Comment by Exxion** [comment]
[Honk] tag when

**Comment by Probe1** [comment]
>I think plasmafloods need to go anyway, they ruin rounds with rogue AIs, give atmos literate antags an incredible amount of power and generally fuck up any round they occur in with shitter shattering lag. Atmos is mostly just a headache that takes players away from Engineering and rewards them for pure autism instead of actually helping the station out.

I'm available to teach people atmos any time I'm on.  I can teach you how to shut down a plasma flood then get cockblocked by the server lagging itself to bits because a doctor was smoking and ignited haf the station.

**Comment by AlphaBuffalo** [comment]
Celt please
Baisc atmos should be set up, but entirely emptying it out is dumb. Like if the o2/n2 mixer is already setup then it could work that way we have an atmosphere when people are tkk dumb to set it up.

**Comment by Kurfursten** [comment]
@clusterfack I don't want to press, but shouldn't this have Map Issue (General)?

**Comment by clusterfack** [comment]
It's not an issue though

**Comment by Kurfursten** [comment]
It's a github issue

**Comment by FudgePucker** [comment]
@Probe1 
Fixing simple mix tank plasma floods is easy.
If you know atmos more than what three switches are the 'flood plasma' buttons, you can destroy everything with no real chance at fixing it.
Scrubbers in the plas tank linked to a cooler (no red flags, you make a plasma cold loop every round, other engineers will think you are just going a little over board... Until there's plasma everywhere.) Then once you have a big enough one link it to distro go back space the socket wrenches, sit in atmos monitoring and set air alarms to the 'correct settings' and enjoy.

On topic, atmospherics itself is where someone has mastered it enough to just quickly rebuild it no problems, its just yet ANOTHER early round, boring, chore. Then there's the idiots who will fuck it up hard and there will be too much N2 and everyone suffocates, or forgets N2 and the station goes up in flames when some one even walks into toxins or smokes a cig. Having it blank will make what few competent engineers leave because of the same reason why the rest of them left, the groundhog day situation of having to set up the engine over and over and over and over and over and over again, just to have the shuttle be called an hour in because the captain stubbed his toe or an assistant didn't get antag and wants another roll. Why spend half the round doing the same exact bullshit again instead of going assistant or some shit and enjoy the entire round.

Disconnecting mix tank from distro would be nice. You can still plasma flood with out laying pipes by putting plasma into waste then filtering plasma into a tank from recycling, or even set plasma to not filter so that it loops back into the pump that leads to distro. (Why the fuck is that pump there anyways? 'Unknown gas that we don't have a filter for? BETTER PUT IT IN DISTRO)
