### ISSUE TITLE
make cargo its own independent department

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#5514]
devolved power best power
you don't want the cargonians to be getting all uppity do you

**Comment by Boxe** [comment]
it's dumb idea day apparently

**Comment by DrCelt** [comment]
!(http://cdn3.gurl.com/wp-content/uploads/2013/04/mean-girls-do-you-even-go-to-this-school.gif)

**Comment by Ephx1** [comment]
I'm pretty sure they secede into their own station, complete with AMR, Dosh, and botany every round.
Really all they need to do now is make a vacuum between the main hall and cargo.

**Comment by SangriaMonkey** [comment]
Might as well. Maybe if you treat QM like an actual head role they'll be a little more responsible.

**Comment by Probe1** [comment]
HA

**Comment by SangriaMonkey** [comment]
It ought to be. Between mining and the roles it can fill if the need is there cargo is definitely important enough.

**Comment by Probe1** [comment]
I don't agree, jokes aside.  Miners are pretty distant from Cargo and are only associated because that's how it's been and how it's mapped.  Miners have larger facilities than the rest of Cargo, and spend most of their time on the asteroid, hanging with Research or lost in space on an adventure.  

Cargo techs and a Quartermaster aren't enough to make a department.  Even if we add miners back into the calculation (despite their aloofness compared to members of other departments) they are still just two jobs and a Head.  

The Quartermaster is already seen as a mini-head.  Irresponsible as a rule and the perfect place for new players to start transitioning from another faceless cargo tech or assistant to someone that has some modicum of responsibility.  I think that the status of Cargo is really good and it does not need changed into a full department.  

Something I would not mind seeing is Civilian and Supply be separated on the manifest.  I don't think it should be its own department due to the weakness in comparison to other departments I wrote about above.  But as a nod and a boon to organization, it would be nice to see cargo techs and miners sifted out of the big fucking list of Civilians.

**Comment by SangriaMonkey** [comment]
Fair enough.
Space Truckers when

**Comment by Intigracy** [comment]
Bad idea.

>Something I would not mind seeing is Civilian and Supply be separated on the manifest.

Good idea. 

Also, the best analogy I can give for the QM is the warden. They're essentially the same thing, a middleman between the head and the rest of the workers.

**Comment by ComicIronic** [comment]
What do you mean, its own department?
It is its own department.

**Comment by Probe1** [comment]
A major department on par with Engineering, Medbay Research of Security.

**Comment by Arthurdentist** [comment]
Cargonians are subservient to the glorious head of personnel, and they should learn their place in the world and be happy with it.

**Comment by FudgePucker** [comment]
Merge cargo with science.
It would make the most powerful department on the entire station.
Cargo needs an emitter to open up crates of eguns.
Science needs an egun to open up the lockboxes, and all they have is an emitter in xenoarch lab.
Its the perfect team.

**Comment by ComicIronic** [comment]
>cargoscience

I too would enjoy everything going to shit every round forever thanks to griff: the superstore.

**Comment by FudgePucker** [comment]
>I too would enjoy everything going to shit every round forever thanks to griff: the superstore.

That's the problem with it, its too perfect, in every way.
Science has all the tools it needs to bring the station to its knees every round, it just doesn't have the motivation.
Cargonia has the pride and the inspiration to crash the station every round, but its tools are limited to what it can order.

If Cargonia had access to toxins, research, robotics, xenobio, and telescience, they would separate themselves from the station by removing the rest of the station.

**Comment by DrCelt** [comment]
CARGO SCIENCE IS NOW CANON
VIVA GRAND CARGONIA (and in its later days it shall become the Cargo-Sciencia Empire in order to appease those rebellious nerds)

**Comment by gbasood** [comment]
> A major department on par with Engineering, Medbay Research of Security.

IT ALREADY IS
Cargo is right up there with R&D in terms of antag potential, since they can get literally anything they want with an emag.

QM could use something that makes him important though

**Comment by Intigracy** [comment]
Cargo already is its own department.

Cargo contains: HoP  > quartermaster > the cargo technicians = the miners.
Think of the quartermaster as the President Pro Tempore of the senate of the united states, and the HoP as the Vice President of the united states: The QM is in charge unless the HoP decides he wants to butt in.

This feature request is still stupid almost a year later. The only good idea in here is the one to split up cargo out of civilians on the manifest and into a cargo header.

**Comment by Probe1** [comment]
Moving cargo personnel out of the big ass list  of civs definitely has merit
