### ISSUE TITLE
Uses for Enriched Uranium and Mythril

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#5528]
Currently, there are two materials added by xenoarchaeology that can only be gotten via xenoarchaeology digs. Enuranium and Mythril. Enuranium doesn't have a sprite (though Deity_link apparently is fixing that).

Consider, that these are materials of which you'll probably ever only see 20-30 units of during a round, if you're lucky. 

Here's a list of idea's I've come up with, and I'm looking for more:
- Coins.
- Some way to alloy smelt them together with plasma to create a third new material, adamantine. (Make it a grey reskin of silver)
- Add them to material datums so you can make themed walls/stuff out of them, and make adamantine a sufficient pain in the ass to take down and highly resistant to bombs. Mythril could make spellcasting of wizards and cults more difficult when used as a floor tile or a wall. Enuranium could just be like normal uranium but more radioactive.
- Use enuranium to irradiate the station, or make weapons grade nuclear dirty bombs, or enhance the rust reactor.
- Use mithril or adamantine to make beastly melee resistance armour for your torso/head/hands/feet, mithril being not as protective as adamantite but being lightweight, and adamantite amazing but slows you down a lot, and neither are space worthy gear.
- Use mithril or adamantine in place of the plasteel when constructing a firefighting ripley to construct a Mithril or Adamantine "Urist" instead. It's a Firefighting ripley but recoloured silver/grey. The mithril Urist is a little more resistant to melee and can move faster than a normal ripley, and the adamantine Urist is a beast against melee damage but moves as fast as a normal ripley.
- Drinks/foods involving the liquid/solid version of these metals?
- Enhance excavation suits. Replacing the anti xenoradiation liner with mithril makes them as fast as if they were wearing a mining rig with no other benefit or downside, while replacing the liner with adamantine instead causes the excavation suit to count as full protection like the anomaly suit with no other benefit or downside.  Can't use both at once because reasons.
- Wizard/Cult/Clockcult being able to steal mithril and use it for enhancing their traitorous methods and means.

-etc.

**Comment by clusterfack** [comment]
It is so specific and situation, it would be useful for incorporation into any gamemode, it would probably be best as for some neat little things you want players to be able to make but only very rarely so they stay original.

**Comment by PJB3005** [comment]
>enhance the rust reactor.

You use uranium for nuclear fission, not fusion :<

**Comment by FudgePucker** [comment]
>You use uranium for nuclear fission, not fusion :<

Is there any lore on the exact physical nature of plasma?
Shit seems like the most crazy carbon compound ever. (Plasma fires produce CO2, plasma is carbon based.)
It can be a liquid gas or solid at room temperature, all with very different attributes.
It is used as a super magical medical drug, but is also explosive.
It also has radioactive properties because R-UST and the very random chance of mutation (if that wasn't cut out.)
It even causes rapid changes in alien lifeforms. (slimes)

What is its textile strength?
Considering it is very easy to change shapes under manipulation (protolathe), would it be possible to make carbon nanotubes out of it to make super strong structures?

**Comment by clusterfack** [comment]
I think plasma is supposed to be some kind of molecule that undergoes fusion through combustion. Pretty sure 3 parts plasma and two parts oxygen burn together to make CO2, so 3 plasma -> 1 carbon

**Comment by PJB3005** [comment]
Also plasma makes like, unrealistic amounts of CO2, which means plasma has enough pure energy to CREATE atoms.

**Comment by ComicIronic** [comment]
Plasma is !HIENG!

**Comment by PJB3005** [comment]
HIENG PARTICLES

**Comment by FudgePucker** [comment]
I mean wouldn't it make sense for it to be some super concentrated yet light form of carbon that only exists inside specific stars made by super conditions?
Basically diamond only lighter and more violate.

Because that would mean plasma would be able to be made into the strongest shit ever, and under the right conditions be tougher than diamonds.

A lore bit could be that the death squad armor is made from carbon nanotubes or some shit.

**Comment by Midaychi** [comment]
If plasma were anything, it'd be a magic hydrocarbon

**Comment by FudgePucker** [comment]
Rare hydrogen gas that science only gets a canister of and engineering only gets two canisters of when?
Its rare because no space sation wants to be Hindenburg 2.0

**Comment by Midaychi** [comment]
If we had xgm we could randomize newgasses with special properties, then start toxins mixing with two cans of each. Call them plasma derivatives and give them a number suffix. Toxins mixing tasked with studying and utilizing the plasma derivatives.

**Comment by FudgePucker** [comment]
Hydrogen gas would make the R-UST more interesting, considering the fusion and everything.
