### ISSUE TITLE
Change/Make it easier - Xenoarcheology

### ISSUE THREAD

**Issue by Venseer** [d3athrow/vgstation13#5564]
This is a request to make Xenoarcheology more fun or less complicated.
This role is almost always neglected, whenever there is a full round with five scientists, there are almost always no scientists doing XenoArch.

I think finding minor artifacts is fine, it takes the share of work and you can always end up with unique and useful objects. But even rounds where people will take the job, with one or two Xenoarcheologists, there is almost never a Large Artifact.

I've tackled the job a couple of times trying to find a Large Artifact and I was never succesful. Maybe I just need to get better at it but I would really like to see maybe one Large Artifact once in a while every round. Make it so that pinpointing the artifact position is more easier instead of radius triangulating, maybe after doing all the research on the stone, you get a code that you can put on a pinpointer like the nuke disc that guides you towards it with +5/-5 titles margin of error.

**Comment by Midaychi** [comment]
Ynkow? The real reason that there aren't many large artifacts found is because they're not interesting/relevant enough to warrent finding. 8/10 times you'll end up with something nasty and you're not an natag.

A secondary reason is that it's very tedious. You find some rock walls, sample them, run them through chemical process and put them through the machines with the right carrier fluid to get an inaccurate range. 

Then you have to mentally lay out all the points you took and figure out where the site could be through triangulation, then go over and get more samples closer to the spot to refine your search.

Repeat ad.infinitum until you get something.

By then, most of the antags have already made a move. If you're unlucky, the round's already ending due to fluke ops or malf or wizard dying in a fire or whatever, and you'll have to start from scratch the next round.

**Comment by Venseer** [comment]
This is a problem on the design of the job, related to it's pacing related to other jobs. Other jobs even in science you can get them going really easily, even Xenobiology, that I think it's one of the slowest jobs can get useful slimes going after the ten or fifteen minute mark.

Maybe you should take less time finding them and more time figuring it out, how to activate or what exactly are it's functionalities.

**Comment by Probe1** [comment]
An issue with making it easier is the large artifacts are balanced around the difficulty of the job.  If you made it easier, you'd have to make the already rare beneficial items rarer.  Xenoarch is *very* potent. Large artifacts will change how a round goes.

**Comment by ComicIronic** [comment]
I see no reason to make the job easier.
It is not crucial to the game in any way, and some large artefacts can actually disrupt round balance in a massive way. It being underpopulated is not an issue.
Xenoarch is considered the endgame of science, and there's no point in changing that. Leave at least one job which is more challenging than clicking I-WIN.

**Comment by Probe1** [comment]
I'd like to reiterate again that I have seen *extremely* successful teams of players that worked together to play xenoarch and made the job how you imagine it to be.  Working alone, it will always be difficult.

There is no rule against messaging other players before a round and organizing a team for xenoarch.  As long as you do not meta-communicate during a round or use meta-cooperation to gain unfair advantages over other players, it is perfectly okay to assemble a team and has been done in the past for amazing results in xenoarcheology.

It's a team effort job that is possible on your own but challenging, mostly due to time.
