### ISSUE TITLE
Kill the stolen spacepod sprites.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5566]
And the goonheist sprites in general.

```
<Haine> you know the pod sprites are one of the reasons our coders are so pissy about working with open source distros at times, right?
```

**Comment by clusterfack** [comment]
From what I'm aware though it was called the 'goonheist' those were not stolen but given freely

**Comment by EclectusInfectus** [comment]
I've asked around, (this being Haine), none of our coders are aware of anyone giving permission to use those pod sprites.  I know replacing them isn't an easy task, but it would calm things a lot on our end.

**Comment by Shaska-** [comment]
If I recall correctly, Pomf got permission to use them from the guy who originally drew them, or something along those lines.
Try asking him when he wakes up.

**Comment by EclectusInfectus** [comment]
Asking around again, now I'm hearing you guys may have had permission for the pods, but no one is totally sure.  Cogwerks is apparently the person who made the sprites, so I'm gunna try and talk to him about it when he's around next time.  If it turns out people were grumping over something that wasn't even true, I'm gunna have some loud, angry opinions for said people.

**Comment by d3athrow** [comment]
when the DMI sheet was posted for the sprites in our lonely autist thread of space i asked around on goons irc for permission to use them

**Comment by EclectusInfectus** [comment]
It seems this was a bunch of miscommunication on our end, so my apologies on kicking a fuss about it!  We're gunna go over what people have given to others to use so we can avoid confusing poor idiots like me over these things in the future.  Sorry again, guys.

**Comment by PJB3005** [comment]
Alright i'll close this then.
