### ISSUE TITLE
(WEB REPORT BY: cisrox REMOTE: 198.245.63.50:7777) MoMMI's can't alt click

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5584]
>Revision (Should be above if you're viewing this from ingame!)
09f185b68a28bf49031a7bb23176e62d01c1ea7b

>General description of the issue
An MoMMI can't alt click anything. The status page goes white.

>What you expected to happen
Being able to alt click properly.

>What actually happened
Status page went blank, nothing else happened.

>Steps to reproduce if possible
Be MoMMI, alt click the floor.

**Comment by AutismSpider** [comment]
So mommis not sure if its same thing with cyborgs can alt click objects for the status page but doing it to floor/plating gets you nothing

**Comment by Shadowmech88** [comment]
Similar problem happening with silicons, however alt+click does work as a silicon if you click on an object, rather than the floor.
This is an inversion of the previous problem where silicons could only access the alt+click menu by clicking on the floor.

Seems like Kurfurst messed up when he fixed it in #5332.

**Comment by ihadtoregisterforthis** [comment]
This works as of now

**Comment by clusterfack** [comment]
Still has a bug where you can alt click objects but not turfs, but that may be in another bug report

**Comment by clusterfack** [comment]
Yeah I fixed this

**Comment by ihadtoregisterforthis** [comment]
Ah, yes the I JUST MASH ON THE KEYBOARD AND IT WERKS

You can actually find the PR in Google with that sentence.
