### ISSUE TITLE
Syndicates winning even though they kept the disk in the nuke and planted the nuke on the solars

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#5591]
> Revision (Should be above if you're viewing this from ingame!)
> 09f185b68a28bf49031a7bb23176e62d01c1ea7b
> 
> General description of the issue
> Syndies won even though they did everything in their power to try and lose
> such as: Keeping the disk in the nuke
> and planting the nuke on the solars
> 
> What you expected to happen
> the station to not blow up
> 
> What actually happened
> the station to blow up
> syndicate major victory (even though they didn't have the disk?)
> 
> Steps to reproduce if possible
> keep the disk in the nuke
> plant nuke on solars
> SYNDICATE MAJOR VICTORY

**Comment by FudgePucker** [comment]
What is expose to happen if the nuke is planted on the solars?
It is a bad location anyways because that would be the first place anybody would check, viro maint would be better if you smash a window into medbay.

**Comment by Intigracy** [comment]
Syndicate major victory happens on the nuke blowing up regardless of if they have the disk or not.

They just fucking blew up the station for crying out loud.

I do think that the nuke isn't supposed to blow up the station when planted on the solars, but I'm not sure.

**Comment by ComicIronic** [comment]
Hardly an issue.

**Comment by PJB3005** [comment]
It's not supposed to happen, they're supposed to lose.

Not sure about the disk being in the nuke though.

**Comment by ComicIronic** [comment]
Why would they lose?
They blow up the station. It's the only newcop objective.

**Comment by Intigracy** [comment]
What he means is that the solars are, or at least were at one point, considered as off the station for the nuke explosion cinematic. This meant ops actually had to put the nuke somewhere on station to win.

**Comment by PJB3005** [comment]
Okay, what we REALLY need to check is if it works if the nuke's off station (in space) or on another Z, if it does, yes then it needs fixing.

**Comment by Probe1** [comment]
the others are trying to say this used to not be a viable strategy and resulted in a loss.  it changed without them being aware of it and they believe it is a bug.

I don't really give a fuck because every time a newcop team plants on solars it makes it very easy for me to murder them all like Brock fucking Samson.

**Comment by IratePirate** [comment]
Honestly we should consider doing what Goon currently does for their Nuke Ops rounds. The Nuke Ops have to set the nuke in a designated target area instead of just anywhere on the station which leads to people putting them on solars or in random quiet maintenance rooms leading to dull rounds ending within 10 minutes.

**Comment by PJB3005** [comment]
Yeah but, it should be randomized if we do that
