### ISSUE TITLE
Should AME bring back the feature where it explodes on having an empty injecting fuel can?

### ISSUE THREAD

**Issue by Intigracy** [d3athrow/vgstation13#5637]
Ingame poll soon hopefully, this issue is for discussion as to why/why not.

Three options as I see it:
Yes, as it was before (always max cap)
Yes, but based on number of cores (up to bomb cap)
No

Also, if it's added as having the explosion size based off cores, if it's any consolation my plan would be that with 1-2 cores it exploding wouldn't even affect much of anything besides the room it's set up in.

**Comment by Intigracy** [comment]
This resulting in a discussion in IRC about how engines should each have drawbacks that you have to learn to avoid (sans the solars)

I honestly didn't even know this feature was removed until today, as 2-3 weeks ago I was discussing the AME with people in engineering chat and they told me to make sure it didn't explode.

**Comment by PJB3005** [comment]
#3819

**Comment by Probe1** [comment]
The AME hasn't exploded when it ran out of fuel for over a year.

**Comment by PJB3005** [comment]
It pretty much SHOULD

**Comment by Ephx1** [comment]
Not explode immediately, but a nice tick down in integrity until explosion would be good.
Definitely only up to the cores it has.
As of now, the AME can power the whole station on its standard two cores, usually it's expanded on too, and then you never have to look at it again until refueling, which sometimes never happens.
Too little risk over so much reward.

**Comment by clusterfack** [comment]
The AME's *only* chance of impacting a round these days is if papa singuloth gets freed.

**Comment by Probe1** [comment]
Here's my opinion.

The heart of this discussion came from both being beginner engines and community members dislike of beginners engines having enough power to run the station.

Neither the Singularity or the AME can power the station by themselves without modification.  Both are simple to set up and a good entry engine for new players to learn engineering and become familiar with building, maintaining and optimizing engines.

Changing it so they produce even less power and have more drawbacks does not improve Engineering as a department or rounds.  We do not have an existing problem of engineering being too easy or rounds going on too long so there's no underlying issue that necessitates the change.

The singularity engine is complicated enough for a new player and even if set up properly in its most basic way, will not power the station.  If you were active at the time, you will remember how angry the playerbase was at dylanstrategie for nerfing radiation collectors when no one wanted it.  That anger went away because people are here to play spess, not hold onto bitterness.  It was not a change people liked in the end.  It was a change people dealt with.  The singularity already requires you to fill each plasma tank to max with room temperature plasma or it won't cover the stations draw (which moves it past simply doing a simple setup - one of the points of the argument for more complicated beginner engines that produce too much power).  Even then, the engine will only produce just over the stations draw and not enough to max out the SMES and leave.  Over the next hour, the radiation collectors will drain enough plasma to necessitate refilling them if alternative and superior engines or modifications to the Singlo have not been made.

The Antimatter Engine I can concede some ground on but not on the most basic setup.  With just two cores and an injection rate of four, you get a measly 160kW.  Still under station draw, and in combination with a singularity engine that has 1013kPa plasma tanks it can produce 520-550kW of power.  It has a role.  It's easy to set up and beginner friendly.  The only way you can fuck up is if you set the injection rate wrong.  Despite this, at least once a week someone *does* @clusterfack .  Moreso when an antagonist carbon or silicon sabotages it.

Where can we cut down on the power of the AME?  Well injecting 8 units on a 4 core is enough to max out each SMES.  It gets super strong if you're willing to babysit it every 15 minutes with only one crate from cargo.  

Fucking up beginner engines because you don't like beginners having something simple will just create a problem for another coder to fix later on.  If you want exploding AMEs, why not add super jars that people have been asking for?  Comes with double the amount of fuel as a regular jar but running the engine on empty results in damage to the engine?  

Address problems we have, not problems we don't.  We have  750 open issues and improving the AME is one of them.  Devaluing it for beginners is not helpful.

**Comment by FudgePucker** [comment]
As some one who sets up the SME, if the AME blows up because some idiot forgot to refill it and a mommi had the SME set up, it should emag the mommi with law 0, murder everyone.

Only idiots set up the AME, if some jackass fucks over all the work I spent thirty minutes on, then I better be able to murder absolutely everyone in hopes of getting them as well.

**Comment by SangriaMonkey** [comment]
If the AME is even on any antagonist can set the input higher than it should be, forget about it, and sabotage the whole department. Especially if a singularity was set up. If you think it's too childproofed for whatever reason, it should just melt down rather than fucking explode as if it were overloaded. And maybe burn holes in the floor for added whatever.

Regardless, there should be safe options for pussies and new people. You might be against banning them but you're probably alone on that.

**Comment by Intigracy** [comment]
I honestly have no issue with the power output of any of the engines and think it's fine where it's at, with requiring you to set up at least two to have the best effect you're looking for.

I do however think each engine should have a drawback if you aren't careful with it. The singulo gets loose and eats the station, the SME spawns Mr Clean and ends the round, fucking up with the turbine releases plasma/hot gas into the air.

Having ways to screw up with the engines / sabotage them just adds interesting elements to rounds. As I said, I disagree wholeheartedly with jobbanning someone for making a genuine mistake in engineering as some have proposed. Just because the engine is new player friendly doesn't mean it has to be 100% safe. I also thought from the day I started playing here again a few months ago that the AME explodes at maxcap with an empty fuel tank in it, and so did the engineering players/cyborg on the engineering radio that I was asking about setting it up.

I don't have some dedicated grudge against new engineers or anything, I just like things going wrong in rounds that people learn from to get better at the game.

**Comment by PJB3005** [comment]
How about, the AME gives an alert ON THE RADIO about instability (can be fucked with for antag usage)

**Comment by FudgePucker** [comment]
@Intigracy 
![basedontrueevents](https://cloud.githubusercontent.com/assets/12202731/9028806/e62f0266-3952-11e5-916b-06801a502d5a.png)

Fuck AME babies.
I don't feel like having my hard work and effort going to fucking waste because someone decided to set up the baby engine instead of a real one. (Context for image, he fucked up the fuel injection. 'x*2=y' was way too hard for a carbon lifeform to figure out.)

**Comment by Intigracy** [comment]
Looks like fun.
