### ISSUE TITLE
(WEB REPORT BY: conker327 REMOTE: 198.245.63.50:7777) MoMMIs cant use crowbar after long

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5797]
>Revision (Should be above if you're viewing this from ingame!)
8ab9672a79089acba08fe858d79f96781c554d96

>General description of the issue
after logging out for a long time (getting discharged) and relogging (and charging again, It wasnt possible to pick up the crowbar from the module visual menu. It was possible, though, to do so through the text menu, which solved the problem.

**Comment by FudgePucker** [comment]
Has this been tested?
There are very few details on it, just logging out for a long time. How long? 3 seconds? 10 seconds? 10 mins? 30 mins? an hour?

**Comment by ConkerDev** [comment]
an hour, I went for dinner. It is literally all info I have. I would test by letting a MoMMI run out of power, then recharging, then trying what I said. Perhaps try having tools toggled.

**Comment by Unfit** [comment]
can't quite reproduce

MoMMIs can't equip anything while they're critically low on power. Once they recharge, they can equip stuff again. Are you sure that's not what happened @ConkerDev ?

**Comment by FudgePucker** [comment]
You know what, FUCK IT.
A solution to nearly every problem with MoMMI tools could be solved if you gave them a button to reset their module.
>tool broke? Reset.
Mat stack broke? Reset.

Its balanced because MoMMIs only have one module, unlike cyborgs who have like 6 or 7 of them I don't know.

Bamn, hey someone make me the fucking head codemin, I'm a god damn genius.
