### ISSUE TITLE
Discussion: Blob

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#5800]
This gamemode is shit and we MUST do something about it. Let's discuss a bit, what if we turn blob into a rare random event?

**Comment by Arans** [comment]
Blob starts when a person bursts though right? Perhaps you could change blob to being a virus symptom for a late stage so people actually have to get infected.

**Comment by Shadowmech88** [comment]
I like blob as a concept. What I don't like is that blobs happen very early in blob rounds, and then everyone drops everything and it becomes a crew vs blob deathmatch.
Wizard has this problem, but at least wizards have the option of going stealthy and hiding their existence somewhat. Blobs are announced to the whole crew via the biohazard announcement and they can't hide or disguise themselves. Even xenomorphs are lower-profile than a blob.
This means that 99% of the time, the blob round ends in five minutes because the crew drilled to its core with lasers and killed it before it was big, or the blob round lasts for 20 minutes of waiting for the blob to become large enough to win because it gained a foothold and became too powerful to kill. These are not good ways for gamemodes to turn out.

I think blob should be restricted to a random event, and one that can only trigger after an hour or two of any given round in order to give the antagonists a chance to do their thing.
Not only that, but I don't think blob should be able to "win" in a proper sense. Either the crew kills it, or they call the emergency shuttle, or evacuate to the asteroid. But the blob taking over 60%/80% of the station shouldn't end the round, though maybe it should force a shuttle call.

**Comment by Probe1** [comment]
Blob is always going to be TDM Crew Versus BLOB.  It's too great of a threat, and unifying, for it to be anything else.

Blob is somewhat balanced towards an early game encounter where the players have to act fast and intelligently or else risk ruin.  Late game blobs tend to face combat kitted phazons and departments that are already prepared.  On the other hand, shit happens and who knows what might go down in a round prior to a blob showing up.

People have been asking for blob to be moved from a game mode to a random event.  Players consistently rate wizard and blob to be bad because they are the entire round and it ends when its over.  Even something similar, nuclear emergency, is not the same.  You can kill the nuke ops or put them in perma until they suicide.  The round will not end when they die.  

So I have to say, yes.  Absolutely move blob away from a round type and towards a random event.  It's what the playerbase wants.  We may have to rebalance it due to the different conditions a blob will face but there's no way to tell on average whether a late game crew will be more or less effective against a blob.  While they might be more geared up and prepared, they also will have had many players disconnect through death, boredom, or they had to leave for whatever reason.  Plus all the normal hijinks that happen every round.

**Comment by Shadowmech88** [comment]
If we ever implement the "Wizard rounds turn into some other kind of round if the wizard is killed instead of ending immediately" strategy, I'd be fine with blob being turned back into a game mode and having the same thing applied to it.

**Comment by Ephx1** [comment]
Random event, it gives some meaning to the biohazard alert other than just viruses.
Not only that but it shares another problem with wizards in the fact that (other than raging mages) you will absolutely never play it, if you do you have barely any time to get into the swing of things even with wiki on hand, so a majority of the time you'll get poor blobs that have barely a clue how to work out what to do in time before a rampant crew wants to get the round over with.

**Comment by Zth--** [comment]
Well I guess we all agree that we have to move it to a random event. So let's work on that, and then test for some rebalance (most probably will have to nerf it a bit)

**Comment by Probe1** [comment]
![aegis_relay_nine_2015-09-25_01-03-32](https://cloud.githubusercontent.com/assets/8550416/10093512/6f4c5362-6321-11e5-8ae5-f5dac738d9f1.png)

**Comment by Angelite191** [comment]
WHY NOT BOTH THOUGH!?

**Comment by Probe1** [comment]
both is fine too

**Comment by clusterfack** [comment]
1. It already is a random event but it is bugged somehow ever since dylan touched events (or longer)
2. It's balanced around being a gamemode that happens within the first few minutes of the round before the station can print 10,000 aeguns

**Comment by Shadowmech88** [comment]
Is blob not still terrible?
