### ISSUE TITLE
(WEB REPORT BY: talux00 REMOTE: 198.245.63.50:7777) Bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5851]
Revision: 8863d47208e80bec8cb19bc09ea9936e673823e2 

>General description of the issue: When you use an evidence bag on a fire extinguisher it "get stuck in the muzzle" but when you use the fire extinguisher you fire the evidence bag with a fire extinguisher inside.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by PJB3005** [comment]
DESCRIPTIVE ISSUE NAMES PLEASE.

**Comment by Probe1** [comment]
>When you use the fire extinguisher you fire the evidence bag with the fire extinguisher inside

holy shit.

Also add an exception for evidence bags to fire extinguishers so you can't cram them in.

**Comment by FudgePucker** [comment]
Wait wait wait.
Does it shoot a bag with a fire extinguisher inside it?
Or does it shoot a bag with the fire extinguisher inside it?
Because if it is duping a fire extinguisher than it should  be patched.
If it is turning inside out the fire extenguisher leaving the holder empty handed and launches a body bag out then that is the best feature in the game ever and should never be fixed.

**Comment by clusterfack** [comment]
Okay if this continues I'm going to start deleting comments that contain that phrase 'shouldn't be fixed' and variants of such

**Comment by Unfit** [comment]
it used to shoot a bag with a fire extinguisher inside, the effect was purely visual however
