### ISSUE TITLE
A lot of vents / scrubbers are disabled / have incorrect config.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5869]
THIS IS WHY SUBTYPES > INSTANCES OLDMAPPERS.

**Comment by dylanstrategie** [comment]
The trick is to Make Active Object existing vents, and not use the Object window

It's when you pick instances in the Object window that problems arise

**Comment by PJB3005** [comment]
No, the trick is to not use instances and use subtypes instead.

**Comment by Probe1** [comment]
I don't even know what map you're referring to and box has over 500 scrubbers alone.

**Comment by PJB3005** [comment]
@Probe1 EVERY MAP.

**Comment by Probe1** [comment]
Can you be more specific than any of the 1000+ vents & scrubbers?

**Comment by PJB3005** [comment]
@Probe1 there is no being specific, it's a TON of scrubbers and vents that are fucked

**Comment by N3X15** [comment]
Please point out some specific ones.  I may be able to make a dmmfix rule for them

**Comment by PJB3005** [comment]
Metaclub SME room's ones, for example (in the room between engineering and the SME room)

scrubbers are off in telescience, the anomaly lab.

**Comment by Rei1226** [comment]
The problem is that when mapping, there is literally no way to tell if you're putting down a vent that's enabled or disabled, as they look the same, and there's about 5 of them for each direction. In fact, I don't know why the option to even put one that's disabled is listed. I'd imagine a quick fix would just be to replace all existing instances of the disabled version with the enabled one.

**Comment by PJB3005** [comment]
@Rei1226 the issue is that then there's spot where they SHOULD be disabled and you catch those too
