### ISSUE TITLE
(WEB REPORT BY: kinggrimlock REMOTE: 198.245.63.50:7777) Spray Cleaners not Spraying

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5885]
>Revision 6b2664a8b956b0775228e77db843afa08532e72e 

>Spray Bottles use up chemicals inside, but fail to produce a cloud and clean anything.

>I expected the spray cleaner to actually clean shit.

>Shit did not get cleaned.

>Take a spray bottle, find a mess (such as a bloodstain on the floor), and spray the spray cleaner at it. It will not be cleaned.

**Comment by Shadowmech88** [comment]
Tested on a local server.
A spray bottle worked correctly exactly once for me, after which I could no longer make puffs with it, and as a result it no longer cleaned anything.
Strangely, this persisted across all spray bottles on the map, and even after entering a different body.
It would appear that after the first time a spray bottle makes a spray, then ALL the remaining spray bottles on the map become incapable of doing so for the remainder of the round.

I think someone broke something larger than just spray bottles.

**Comment by Cyadox** [comment]
@Shadowmech88 
You'd be correct on that one. See: http://boards.4chan.org/vg/thread/117563189/spess-men-on-a-spess-station-ss13g#p117586524 

Wires, tables, wall girders, RPD pipes, chairs, grilles; the list goes on.
From what I can deduce, there's something wrong with how the game spawns objects in the world, but the weird thing is that it doesn't happen consistently.

For example, if you spam the RPD enough, a pipe WILL spawn eventually, and usually for a couple times afterwards, or if you spam a tile enough, you will be able to place a wire (snipping has the same affect, too). And it happens any time you construct and deconstruct anything - I imagine since the spray's cloud lasts for X tiles, that it uses the same code to 'create' and 'destroy' itself too.

**Comment by PJB3005** [comment]
@Cyadox, is it still happening, because #5889 should've fixed it.

**Comment by Cyadox** [comment]
I haven't played since last night, but I'll be sure to try it when I get the chance. Word in the thread is that it was fixed though, so I think you're good.
