### ISSUE TITLE
(WEB REPORT BY: angeliteentyshak REMOTE: 198.245.63.50:7777) Operating table bug.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5917]
Being dead and placed on an operating table then removed will fix your view on the operating table... why?

**Comment by dylanstrategie** [comment]
It never ends with the mob eye bugs

I've noticed some dodgy behavior with mob.eye myself, notably being shoved into your core instead of above it when you Return to Core as AI, which means you have to move to get rid of the walls and all

Needs a case per case check to get rid of problematic camera instructions
