### ISSUE TITLE
Show Player Notes by Ckey(Feature request)

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#5975]
I previously asked for the Player Notes to be arranged alphanumerically rather than by page number(0-1.,A,B,C...Z vs. 1,2,3,4,5...etc) but no one acted on it.

However, MrPain mentioned something that would be much much more efficient.

Can we please have a Show Player Notes by Ckey button?

It's somewhat difficult and time consuming to dredge through the pages upon pages of player names to find a player, and doubly, triply, sometimes even quadruply so when they have 3-4 alternate ckeys.

**Comment by Probe1** [comment]
Rei wanted something similar on gitlab and I responded with the show player info verb.  

![image](https://cloud.githubusercontent.com/assets/8550416/10292117/73db2b26-6b7b-11e5-8f01-b5e2449aec44.png)

It gives you a prompt that you can enter a players ckey into.  This is very useful rather than going through the big list of everyone that has a note.

**Comment by mrpain666** [comment]
OH GOD PLEASE
