### ISSUE TITLE
Can't use the foyer turret control on Metastation as silicon

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#5981]
Just why? My only guess is because telecomms is beyond there, but I don't understand why telecomms has it in the first place, unless it's some balance for people walking in there.

**Comment by Probe1** [comment]
it was probably copy pasted from box or something.

silicons aren't allowed to touch the telecomms turrets because "reasons".  Since its the entrance to both the AI Core and Telecomms, I'm willing to bet someone copied and pasted it.

**Comment by Ephx1** [comment]
If it is intentionally for tcomms, I suggest moving the control panel to the telecomms doorway, then moving I dunno, one turret into the tcomm control room.

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/10292642/5dcf80ea-6b7e-11e5-8116-d9eafd2f78d4.png)

Yeah, it has ailock = 1 which is the firewall thing you run into.  

What do we do though?  We'd need to move telecomms, or the Cyborg Upload+AI Core.  Or the silicons would have to accept that the emitters that are there are their turrets.

**Comment by Ephx1** [comment]
This is what I was thinking, one turret should be good coverage for the whole room
![untitled](https://cloud.githubusercontent.com/assets/6224074/10316257/664001e2-6c2c-11e5-8578-851205149a61.png)

**Comment by FudgePucker** [comment]
AI should have control over tcom turrets, if someone sets it to lethal then you can't turn it off with out taking laser damage

**Comment by Ephx1** [comment]
I really don't know why Telecomms turret control was ever removed from AI control. It's just sort of a nuisance if you want to help someone, the only practical reason I can conjure up in my mind is that if the AI made a malicious tcomms script, it would be hard to undo with turret control. Makes sense on the abandoned satellite, because then the AI could just help you get the goone code (which you can help them get anyways with APCs).

**Comment by FudgePucker** [comment]
@Ephx1 
I guess its so that AI can't shut off Tcoms durring malf and then set it to leathal/kill when someone enters to fix it.

The problem with this and everything you do to try to balance malf is that the AI can just pump plasma in there to prevent it.

**Comment by Ephx1** [comment]
Best part about that is the AI has controls to the doors directly, so when they go through the cycling airlocks you can just disable the power and trap them within.
This is very interesting, I'll have to ask someone why tcomms is like that if you can do pretty much anything to stop people in there.

**Comment by Probe1** [comment]
The things you learn.  I'll put up a PR tonight removing  the AI firewall on metaclub and if you think we should break from tradition completely, I'll remove it from all maps.

**Comment by Ephx1** [comment]
I'm fine with it right now at the moment, having to let someone into tcomms being a problem hasn't been too frequent (Surprisingly). But thank you, letting the AI control the Metaclub turrets would be wonderful, mostly because that's the only way to the AI directly.

**Comment by IratePirate** [comment]
The Tcomms turret console on Box was made AI locked about a year and a half ago for some reason and since then it just seems to have become accepted. I used to mess with tcomms and slaughter the  heads when they went to check it out, so in many ways it somewhat nerfs rogue silicons. I only made the AI sat turret console on Meta AI locked for the sake of consistency, and also because at the moment the satellite is quite powerful for a rogue AI. It seems unfair for the crew not to be able to at least have a chance of rectifying comms if something bad happens or the AI sat gets bombed. It wasn't just a copypasta of Box, many of the design decisions I made when editing the map were based on "people like Box so keep it consistent with Box".

I'd allow AI access on all the maps, as it should be.

**Comment by Probe1** [comment]
I held a vote and most of the server wants it to remain as is, so I'll only touch meta.

**Comment by Hoshi-chan** [comment]
Yeah, tcomms on Box is fine as it is... maybe. I find it annoying when I have to keep explaining to dense heads that no, I can't control the turrets in that room, and then wind up carded because they think I'm trying to kill them.

Okay, so maybe the tcomms turret firewall on Box isn't great, and like people have said, there are a zillion other ways you can kill people in that room without using turrets, so really all it does is inconvenience non-malf AIs trying to get someone inside to fix a tcomms script on a console whose monitor has been disconnected. Here's the thing though: as a malf AI, I don't think I've ever seen tcomms go down and someone investigate it, because when I take tcomms down, it's because I'm going loud. Usually they'll INSTANTLY assume the AI is malfunctioning if the comms are down long enough, and start brewing thermite without so much as a peek. On top of that, I've always thought that tcomms on Box is FAR too close to the core to be strategically viable for a distraction/trap. Also, anyone going in to fix it will likely have found a handheld radio, and will just scream over that when you try to turret them.

But still, the problem here is the AI satellite on meatclub. It stinks because it blocks your AI core access. Maybe whoever designed the satellite shouldn't have put telecomms there if they didn't want the AI to have an extra set of turrets. Try not to look rogue when people are trying to get past a set of turrets that you (apparently) won't turn off.
