### ISSUE TITLE
METACLUB MEDBAY SUGGESTION

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6002]
(WEB REPORT BY: gringonius REMOTE: 158.69.55.2:7777)

>f9ea79b5de6e347ab4de7f75d324eb02341b04af 

>MAKE THOSE PLASTIC FLAPS IN FRONT OF THE SURGERY ROOM THE AIR-TIGHT VARIETY, HOLY FUCK
>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Probe1** [comment]
eh.  the flaps on Box that allow mules to deposit crates in medbay aren't air tight.  the flaps anywhere aren't air tight.  except for pod bays and you know what?

those are gay as fuck.  I don't think there's a good reason for the ones leading to departments to block air and tbh I'm afraid you had a challenging, wild ride of a round that I witnessed but I don't think we should dick around with magic vars because of it.

**Comment by FudgePucker** [comment]
@Probe1 The pod bay flaps are okay. It is 100000000000000 times better than the system before with those stupid airlocks only used in that one specific area in the entirety of space that were a nightmare to open, you had to get out of your pod to press the button, get back in your pod, wait, wait, go off into space, also hope no one is moving though maint, because then maintenance is gonna get depressurized. The flaps seem silly at first until you realize that they are construable, destructible, and most importantly, they fucking work.

Only other solution would be to add fancy force shields that block air but allow things to move though it that are construable and deconstructable, but even then, if there is a black out the room gets depressurized. The flaps just work.

**Comment by IratePirate** [comment]
Air blocking force fields would actually be a pretty neat idea. Like the hangar shields from Star Wars ships.

**Comment by FudgePucker** [comment]
@IratePirate Yea that was the thing I was thinking about.
Only problem is like I said, if someone opens the maintenance airlock while power is down good bye air.

**Comment by Probe1** [comment]
Does anyone disagree with this featreq?  If everyone wants it I'm gonna do it.
