### ISSUE TITLE
Economy, again.

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#6020]
Ok since Deity started the discussion, again, http://pastebin.com/Y1wd4bCb why don't we get our shit together and make it work?
- I suggest making a simple shop somewhere in the station where you can actually spend your fucking money on (and maybe add a shopkeeper job as a subtype of assistant?)
- Also someone suggested vendors where you can put your stuff and add a price to it, which it's a really good idea (imagine the chem nanofridge but with prices). I think I can make this one. #3198

**Comment by AlphaBuffalo** [comment]
I was going through the code and saw someone noted that maybe add an economy based on what you did your job from previous rounds. Like scientist who do research earn 100 bucks into their bank account for next round, and if you don't do anything you don't make money. It would give incentive for players to do their jobs, no?

**Comment by Cyadox** [comment]
@AlphaBuffalo This issue with that is that there's currently no system in place to carry over data from one round to the next. What's being proposed here is to make an economy that's relevant every round, and honestly 100 credits is barely any incentive at all at the moment, nor would it be in the future.

I feel a timed system is ideal since it promotes prolonging the round instead of calling the shuttle over trivial issues, but obviously we're going to need to figure out a way to enforce spending on basic needs. The ETPOS and POS systems were a miserable first step, but the idea is solid and just needs to be better implemented. I remember someone suggesting having 'blank' vending machines that players could fill and have it pay into their account - that seems like a great idea, especially with a lot of departments not having the time or willingness to man their counter.

**Comment by AutismSpider** [comment]
What happen to  that black jack mini game some one was working on for gambling?

>(engineer)orders of a portable SMES filled with to least X% with energy.

Take that shit out most of the time they don't even set up when they do its done wrong

**Comment by ihadtoregisterforthis** [comment]
Always keep in mind: Hacking, destroying and >implying everyone gives a heck about paying for stuff

For the hacking part, many players don't care for belongings or private property, and entering by force to take whatever is a custom. If you put your stuff in a machine, it will probably get stolen and wired to spew everything until what the assailant find what they were looking for. Live example are the costume drawer and booze-o-mats

The station being bombed is also a regular thing. If you spin your earnings around a public machine and it gets destroyed, AND the shuttle isn't called, you lost the money game. 

>implying anyone gives as much as a fuck for money

Everything is free and this can't be stopped. Only things that actually require money to get are crates. You are trying to put capitalist earnings in a station of hyenas

Also something something inflation.

**_imo_**

Make a completely radical change, put prices on everything and then start reverting stuff away at discretion. Otherwise it will never leave the drawing table.

**Comment by Cyadox** [comment]
@ihadtoregisterforthis 
You're going to get theft no matter what you do - if anything, adding monetary value to everything will probably make it more prevalent if this update rolls out, whether it's vending machines or pricing things by hand.

The problem we have, as I understand it, is that while it's easy to say just put a price on everything, it's a pain in the ass, and would be rife with balance issues for weeks. What I propose is letting the players decide that for themselves, because then it becomes an IC issue if something is too low or high, instead of DEADMIN HE CODERBUS A SHIT.

I don't know how it'd be accomplished, I'll admit. The scanner/POS is realistically how that should be handled, but I think the players need more guidance and tools to make it easier. We need to incentivize the crap outta this to make people WANT to pay for things, and we need to make it as simple as slapping your ID on something.

**Comment by DeityLink** [comment]
I didn't plan to start such a discussion when I posted my plans.

I know that many people are convinced that it won't work, so I'll do it my way for now.

**Comment by DeityLink** [comment]
How about you guys post suggestions of things that could be bought with money?

I'll repost the 4 guidelines of my Economy update:

1-"Economy" in SS13 must NOT be mandatory for the players to use. We're not forcing them to use it.

2-"Economy" in SS13 must be easy to use and intuitive. As N3X15 said, players always take the path of least resistance, which is why this PR is a huge step up from the current state of money in the game (since money is really easy to transfer from player to player now, doesn't require EFTPOS bullshit, and bills can be printed/absorbed without the need of an ATM)

3-Goods that can be bought with money (in the merch computer for example) should NOT be overly convenient tools, weapons, etc, but rather luxuries, toys, good examples include clothing (we have tons of unused clothing sprites in the game which don't fit with the Autodrobe's clown theme. We could allow players to purchase them here instead) or toys like Cyadox's upcoming Poker suitcase, paintings...

4-Admins will have a certain degree of control over this economy, the next parts will add salaries, bonuses, orders, and admins will be able to regulate it in real time (as nanotrasen), which gives the IAA a much more important job, he can now report which crew members are doing a good/bad job and salaries can be adjusted in consequences. Or adminbus events featuring crisis, global strikes, recession, etc.

**Comment by Zth--** [comment]
Think of this. An assistant can buy a vending machine pack from an ATM (or ask cargo) and set up his own vending machine with his own items and prices. 
Imagine a science vending machine stacked with bag of holdings, armors and stuff. Or chemists selling creatine

**Comment by ihadtoregisterforthis** [comment]
Things that could be used for pricing? 
Hats and clothes, like many games do for IRL money. But not a fixated stock like the costumes one, add some degree of RNG so people won't bumrush to get the fanciest hat.

Make the arcades have a little enough price too

Now for >vendors, 
What if you put your hard earned stuff on your machine and someone steals it?
Or what if someone steals your hard earned stuff and puts in their machine?

**Comment by Zth--** [comment]
Make them unhackable then

**Comment by ghost** [comment]
(oh shit you saw nothing)

**Comment by PJB3005** [comment]
Yes we did!

_uses google translate to steal the Russian ideas_

**Comment by ComicIronic** [comment]
Russians: "Shit, how do we do economy?"
