### ISSUE TITLE
Editing Someone's Alpha in VV Automatically Reverts After A Second

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6092]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
91fa1f4ed136d2766e78852edae912cbe9560fd7 

>General description of the issue
If you try changing someone's alpha, it automatically reverts back to 255 almost immediately.

**Comment by PJB3005** [comment]
Definetly caused by `Life()`

**Comment by clusterfack** [comment]
You can set alpha to whatever you want if you actually know how it works

There is a list of alphas, and it picks the lowest, varedit the list and add a new entry with a lower alpha to set it to that alpha.

Of course you wont get this message because you're an idiot who didn't make a simple github account to get his question fulfilled.

**Comment by PJB3005** [comment]
Actually @clusterfack that's @Rei1226
