### ISSUE TITLE
Vines do not emit/absorb gasses

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6095]
(WEB REPORT BY: killette2 REMOTE: 158.69.55.2:7777)
On trait plants can have is the ability to absorb or release multiple gasses. However this trait does not carry over to vines, like bioluminecense does. The amount of gas it releases may or may not be linked to the potency, but it is nowhere near the hell of a gas miner. Please let this feature be included into vines.

**Comment by FudgePucker** [comment]
Sooooo you want to release plasma flooding cyanide apple death berry super bright kudzu?
Hell someone needs to fix this problem STAT.

**Comment by Killette2** [comment]
As good as that sounds on paper, I don't think you understand how underwhelming kudzu is as an antag weapon. Go on, try it yourself and see how many kills you get.

**Comment by FudgePucker** [comment]
I know how underwhelming it is, I was just being sarcastic.

Still, a better idea might be to just buff kudzu or vines instead of HOLY SHIT YOU WANT PLASMA FLOODING VINES?

**Comment by Killette2** [comment]
Well whatever's stunting the vines, whether it be a vine cap or something else needs to not exist, since the crew knows how to handle vines more properly than blobs even. In that one round where I planted 7 vines with potency 114 at once, nobody got killed and they even halted their growing progress and refused to grow, despite meeting the light and atmospheric conditions they needed. Even after other vines were culled, the existing ones still refused to grow and people ended up leaving them alone.

For the buff vines, they should grow endlessly but their growth speed remain related to what makes them grow fast, and they could be a bit more grabby than they are instead of just walking through a jungle. Also for plasma or buff vines, why not both? But if they emit or absorb a gas, they will be less potent and less grabby, so you can pick your poison whether you want to crew to be constricted or suddenly chocking to death due to no oxygen.

**Comment by FudgePucker** [comment]
I think one of the main problems is how bullshitty boatany is with RNG. I guess making it easier to improve the traits and buffing how well the traits effect how fucked the station is, then it should be fine.

But trust me. Plasma is VERY VERY VERY overpowered. Opening a canister of room temp plasma fucks over more than the vines will. Only 5 rig suits on the station protect against plasma, add in the source of it producing it spreads and you got an exelent depopulation tool.

Although it would be interesting to have it rapidly suck up all the O2

**Comment by clusterfack** [comment]
Now I didn't read it too carefully but last time I looked at vines a few months ago I think there's a cap at which their growth is extremely slowed at very high numbers of vines, and a lower cap that once you've eliminated the majority of the vines their growth slows as well.

**Comment by FudgePucker** [comment]
I think that buffing vines by removing the growth limits would be fine.

Vines are simple enough to remove if cargo isn't stupid, botanists paint a giant target on their backs, and if they fuck up and let loose vines on accident it isn't that bad, people normally get one free singuloose as non antag on accident, and lord singularity does way more damage than some vines, as long as the botanist let's the crew know they fucked up and doesn't spread it outside of hydroponics or sabatoge efforts to fix it (like that one faggot who got banned) it would be fine.

Botany doesn't have that many antag options to create mayhem (I always wanted to try poisoning the chefs food with that one 'medical' chemical in glowy weed that reduces stuns but causes high toxins just to make medbay kill itself from people with failing livers), vines should give them the power with enough knowledge to cause massive death, hell medbay has viruses, science has bombs and research, and engineering has our lord and saviour singularity

**Comment by Killette2** [comment]
I would also like to add that in addition to his, another trait plants can have is raise or cooling the temperature of gas around it by up to +4 or -4 degrees, but this trait also is not included into vines. It would be interesting to have vines that make the place insanely hot or insanely cold, as a freezing station is not something that often happens.

**Comment by 9600bauds** [comment]
This is not feature loss, as it was never a feature

**Comment by Killette2** [comment]
Botany3 will reign supreme!
