### ISSUE TITLE
Defficiency starting APC power seems low

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6134]
By 13 minutes into the round, the Atmospherics APC was already drained to 14%, disabling both equipment and lighting. I was just beginning to cool plasma for the collectors when this happened. At first I thought that it was a powersink, but then it turned out to be Ragin Mages. 

Most Defficiency rounds end because no one sets up power, or sets it up fast enough to prevent a shuttle call 30 minutes in because the entire station has lost all power. You should have at least 20-30 minutes of equipment power before things begin to fail, especially considering that the only easily set up engine on the map is the SME, and most people are going to want to modify the cooling before firing it up.

**Comment by dylanstrategie** [comment]
This is most likely an issue on all maps

A simple solution would be to massively increase the starting charge on the Engineering SMES and putting output on maximum. This gives the crew a lot more time to set up the power

**Comment by Hoshi-chan** [comment]
Yeah, now that you mention it, it sort of is. Was something changed that put a huge drain on the powernet?

**Comment by dylanstrategie** [comment]
The stations in general got much bigger. This is the same reason for solars no longer being able to hold the powernet (the output was never actually decreased)

Factually, I think the station load on Box doubled or even tripled, and the new stations are all equally power-intensive outside of Taxi, which is special

**Comment by Hoshi-chan** [comment]
Singularity engine got a hard nerf, too, for that matter. Setting it up like you used to doesn't produce nearly enough power, not without supercooled plasma in the tanks, and few engineers bother.

**Comment by Kurfursten** [comment]
If you aren't supercooling plasma for rad collectors you're playing engineer wrong.

Powernets have been a little weird lately, notably high strain on Box a few rounds. Deff's early failure of atmospherics is not new, though: it happens frequently because it never charges at all off of the starting SMES settings. Deff has tons of lights, some of which are in maint, eat up much more power than Box.

It's not too hard to solo a 'good enough' SME engine on deff if you start right away. Use normal plasma tanks or filled warm tanks to hold over the station's power while you work on supercooling, or delegate tasks and get it all done fast.

**Comment by Hoshi-chan** [comment]
Kurf, I'm not sure when you last played, but NOBODY plays engineer, and those that do usually focus on some huge project like the R-UST or a rage cage that takes 2 hours to build while power fails all over the station.

Literally the only engine anyone bothers with anymore is the TEG, because it's easy to set up, can't explode, and can be piped into atmos to be self-sustaining forever.

**Comment by Kurfursten** [comment]
I played this morning in the same round you were messing with the engine. I got killed by one of the ragin mages. And yes, I was on the engineering staff.

**Comment by Hoshi-chan** [comment]
I'm just saying that power used to be stupidly easy to set up, which was bad, but at least it didn't slow the round down.

Now it requires a dedicated team of engineers working together, as well as either atmos technicians or atmos knowledge, and sometimes multiple sources of power. The entire point of alternative engines were supposed to be to provide alternatives, not for ALL of them to be required to be set up for everything to run properly.

But maybe something's just plain wrong with power in general, because, like I said, I've seen THREE engines running simultaneously and power continuing to fail, with no power sinks or cut wires.

**Comment by Kurfursten** [comment]
What were your SMES settings? How much was in the main grid? Was it on Deff? Because Deff has only 2 engines by default unless you count the singulo parts which aren't set up.

**Comment by Hoshi-chan** [comment]
The three-engine fiasco was on box, and there were a number of engineers and MoMMIs. I was AI, and they were actively working, so I didn't futz around with their settings. They had the TEG, AME, and SME all running at once. I'm not sure WHAT their setup was, but I know that the power output on the SMES were on, and that the power monitoring console in the engineering lobby said that the power supplied was sufficient.

**Comment by Hoshi-chan** [comment]
You know what, can we just schedule that aforementioned test server date? I want to measure a few things, like time until complete power failure on each station without intervention, the power required, and what the output is like on each engine without atmos intervention (meaning no cooling, no RPD, no pipe dispensers), which CANNOT be expected from the average engineer.

**Comment by Kurfursten** [comment]
You can test those things without me as they don't require particular engineering knowledge. The appointment was for advice on setting up a Radio Transmitter which you were having trouble with. That being said, you can reach me on Byond messaging, I'm free tomorrow. Atmos cooling should be expected from the average engineer, and is the reason the Singulo was nerfed ages ago.

I'll admit to partial culpability in creating the current TEG meta because I'm the one that made the easy guide. It does need a certain level of nerfing, though not as drastic as some have suggested, I think.

**Comment by Hoshi-chan** [comment]
I dunno, bub. I always nag engineers to just hook a darn plasma tank to the freezer in atmos for a couple of minutes before they do the radiation collectors on the SME/Singulo, but they NEVER listen. N E V E R.

**Comment by Kurfursten** [comment]
Deff's failure speed isn't because of a lack of power in the SMES, it's because the SMES aren't configured by default to output enough to charge atmos -- at all -- from roundstart. You have to configure the SMES first.

**Comment by Duny-** [comment]
I'll make power failure happen less fast on deff since people like to use their special snowflake setup for the SME and there is no baby engine able to produce enough power to power the station in 5 minutes like on the other maps.
I never noticed the problem during my various testing rounds since the longest time I spend on the map before closing the server is when I try to beat my own goonecode facility, which never takes long and isn't on station.

**Comment by Hoshi-chan** [comment]
Again, thank you Duny.
