### ISSUE TITLE
Tier 3 parts plastic cost should be reduced.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6162]
I like the change.  Uranium for weapons.  Diamonds for the best stuff.  Silver for COOL TECH.  and so on.  Plastic is now the "machine component" material and it's very neat.

But 300 per part doesn't sit well with me for a few reasons.

- It doesn't divide evenly into 2000 (1 sheet of plastic in cm3).  You'll only be able to print 9.66666666r parts per sheet of plastic.
- When a mechanic is around they print A LOT of parts.  Upgrading botany alone costs something like 106 parts!  That's all of the trays, all of the machines and doesn't include anything new like a chem dispenser.  There's all the roundstart plastic GONE and we've just hooked up a single room.  Granted its one of the bigger rooms but its by no means the only and we can look at medbay,another place that requires a lotta parts.  It'll take 63 parts to upgrade all the machines in genetics, in chemistry, and in medbay in general.  That's 18900 cm3 of plastic, or just under 10 sheets of plastic (1 plastic flap, 20 plasticide [ground plastecillum]).
- Botanists do not just serve Research like miners basically just serve research.  They get chems for medbay, they get food for the chef, plastic for the mechanics AND research, and fun items for the crew.  From what I've observed since this has changed, mechanics are far, far more likely to rely on deconstructing every plastic flap than to get plastic from botanists.  Even when I personally have supplied botanists with as close to a round start chem dispenser and begged, it hasn't happened.  This makes it more of a pursuit of fort building than interdepartmental cooperation.  It's far more likely to see a mechanic do well if he gets his own seed and builds his own tray than depend on someone.
- Research now has to deconstruct their plastic flaps to get their timely upgrades and follow the established path for RnD.  Reducing the cost won't remove the need but it will help stretch it out.

All these reasons come together.  It would fit much better if parts cost 200 plastic instead of 300.  

Most of all though, holy SHIT do uneven divisions bug me.  

@Kurfursten you changed it, what do you think?

**Comment by clusterfack** [comment]
This is why we need economy

**Comment by Wizardcrying** [comment]
Specifically how so?

**Comment by Kurfursten** [comment]
I wouldn't be opposed to a decrease to 250 just to get it to an even divisor. That means each harvest of botany, they will be producing 30 sheets = 240 parts. Which by your math is enough to upgrade every machine in botany (a ridiculous prospect), every machine in medbay (a reasonable prospect), upgrade every machine in R&D (which you claim they'll already have done using their own sheets), every machine in your own layer, and still have some to spare for new machines. Per harvest. Since you'll be floating around 60 extra parts, you might consider upgrading all of the vending machines on the station and also all the machines in cargo and engineering. You'll still have parts to spare.

(Probe, if you're actually upgrading every single botany tray each shift as mechanic and you can't get them to plant three plastelium spores ONCE, I have lost an incredible amount of faith in your ability to bargain. And yes, 30 sheets was including one mushroom set aside to make new spores.)

**Comment by 9600bauds** [comment]
Well I guess this is dead
