### ISSUE TITLE
Wizard's Apprentices Kinda Suck

### ISSUE THREAD

**Issue by Rei1226** [d3athrow/vgstation13#6181]
So yeah, the apprentice ability kinda blows. Apprentices spawn with fireball and magic missile. If they're locked down somewhere in a room they're fucked. And their magic missiles can hit the wizard and vice versa.

Seems like this ability has more potential to fuck over the wizard then it does to actually aid him

**Comment by Shadowmech88** [comment]
I believe the intent was to make them into mini-wizards that would go off and wreak havoc, not fight alongside the wizard.
However, I do think it would be better if the apprentices could choose a particular spell to take instead of being automatically forced to have just fireball and magic missile.

**Comment by Duny-** [comment]
The wizard can choose between multiple types of apprentices. If my memory serves, only one doesn't make the apprentice want to suicide succumb immediately and is actually pretty good (jaunt/blink). The worst is the one aimed towards destruction (so fireball/magic missile) and obviously wizards love to pick the one supposed to wreck shit rather than the elusive one. The last one is NEVER played, so I don't even remember the spells. I think it has knock but I'm not sure.

**Comment by AutismSpider** [comment]
Last one was Robeless and Mind Swap

**Comment by dylanstrategie** [comment]
Once, a very long time ago, I had plans for Wizard stuff

But then that kinda dropped off

**Comment by DeityLink** [comment]
My only complaint is that apprentices are considered by the game like syndicate agents instead of wizards. They should have their own list and role, like thralls do.

**Comment by Kurfursten** [comment]
I don't have an issue with destruction school being the most limited, but I would like to see more schools added. Also maybe an option to spawn a non-school apprentice and let them choose their own school.

**Comment by gbasood** [comment]
w e w
Closing this because old balance discussion issue that as far as I know doesn't really apply anymore
Plus looks like a PR changed it at one point so

**Comment by DeityLink** [comment]
I'm currently working on making apprentices their own role, like thralls are, as part of my special roles overhaul. Did someone also do it recently?

**Comment by AutismSpider** [comment]
Not yet Deity
