### ISSUE TITLE
Make SQDL Its Own Flag, Give It Only To Codermins

### ISSUE THREAD

**Issue by Rei1226** [d3athrow/vgstation13#6197]
Ever since some admins started learning about all of the funny and odd things you can apparently do with SQDL, most have gone overboard with it once they find out about it, to the point of massively making the entire server do immersion and sometimes round breaking shit, or even crashing the server (with no survivors, i might add).

I think codermins should be the only one with this ability, and that we could probably trust them to use it responsibly instead of some admin picking this stuff up for the first time after learning about it and having a hayday with it.

**Comment by SkowronX** [comment]
:+1: Celt once again proves we can't have nice things.

**Comment by dylanstrategie** [comment]
SQDL should most likely be a VERY restricted access flag, only for headmins or trustedmins with enough coding knowledge to know what they shouldn't and shouldn't put in the box

**Comment by PJB3005** [comment]
But we admins have been having SO MUCH FUN.

C'mon deadmin the badmins don't ruin it for everybody.

**Comment by Rei1226** [comment]
but you're a codermin PJB, you'd still have access to it

**Comment by PJB3005** [comment]
But admins like skowron won't.

**Comment by AlphaBuffalo** [comment]
Let the players use it

**Comment by Arthurdentist** [comment]
I agree it should be its own flag. If an admin desperately needs it they can explain to a headmin why.

**Comment by nuklearcellphoneg** [comment]
If its access can be locked, it most certainly should be.

I'm not a coder and I don't rightly understand it in detail: I wouldn't even know how to fiddle with it personally. If it's just under debug, I can just remove the debug flag from admins. If it's an extension of variable editing, I'm not really sure how to restrict access to that.

We do use varedit for some things- but mostly bussing, which most of the admins are not very good at. Subtlety doesn't come easily it would seem. Sometimes we use it to attempt to troubleshoot a problem, but it typically doesn't work, because we're not coders.

I can think of two instances where I actually managed to alleviate a bug midgame: One time a deadminned admin would see a check for bodyparts literally every tick because one of their preferences for seeing debug messages was left on, and I was able to somehow set the preference to DO NOT WANT(I have no idea how and it took about ten or fifteen minutes).

The other was someone being buckled to a chair, which they were still buckled to, as I used the Get verb- that was my own fault, and the problem is just as easily fixed by simply unbuckling them from said chair.

**Comment by PJB3005** [comment]
At the moment, SDQL (Not SQDL) does no allow editing one's permissions as admin, this is due to a bug with UPDATE, #6193 would allow it (as it fixes said bug), though for that reason I've set DNM on it.

Here's a TL;DR of what SDQL allows you to do:

* Call procs on atoms, with argument, though arguments have less choices than proc calls through VV/verbs.
* Change the variables of any atom.
* Delete any atom.
* Show admins a list of every atom.

All of the above can be done through certain criteria, such as variables and typepaths, you can for example delete every meteor of which the x coordinate is greater than 70.

SDQL currently requires +DEBUG.

**Comment by ghost** [comment]
@gbasood not a bug

**Comment by Probe1** [comment]
We can and will deadmin admins that abuse their buttons.  

You can code it though!

**Comment by PJB3005** [comment]
The admins that are shitposty enough to abuse it don't have the brain cells to so whatever.

**Comment by ghost** [comment]
This is true there has never been a shitposting admin that abused this system don't worry lads
