### ISSUE TITLE
Radiation Too Stronk

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#6200]
I was on the DJ station, wearing the CE hardsuit, and when I passed by the Radio Transmitter, I collapsed within 10 seconds of standing in front of it. Either up the rad protection on the CE's suit, or lower the Rad damage from the transmitter

**Comment by ihadtoregisterforthis** [comment]
There's a read suit besides the transmitter entrance just for that.

I seriously hope you weren't the CE that round and just stole the hardsuit.

**Comment by AlphaBuffalo** [comment]
I was the CE that round, I just dont understand why it doesnt have more rad protection than the normal engineering suit

**Comment by ihadtoregisterforthis** [comment]
It does have more read resistance than a normal engineering suit, but still less than the proper rad suit. You know, the dull yellow one that doesn't cover hands or legs.

You deserved it for leaving the station as a head and chief of the engineers

**Comment by AlphaBuffalo** [comment]
If its an advance hardsuit, then how does plastic stop more radiation than it?

**Comment by Kurfursten** [comment]
The CE hardsuit is general purpose: it combines the powerful temperature/pressure resistance of an atmos hardsuit with the moderate rad resistance of the engineering hardsuit. It also combines both of those things with space-worthiness and a large suit storage slot. The radsuit is a very specialized item that does not protect from space, cold, heat, or pressure. It does not have suit storage. In return, it has extreme rad resistance. It's more than just a plastic raincoat.

If you want a sciencey answer, the advanced hardsuit is made of mostly fiberglass reinforced with alloy struts, which does not make highly extensive use of multiple electron-level gradient shielding. By comparison, the radsuit is made of eight different atomic layers each with a different valence level to prevent electron penetration.

**Comment by dylanstrategie** [comment]
This is an issue with how damage resistance works

Instead of "dampening" the impact of radiation, all armor has a RNG change to block radiation (100 being, of course, 100 % chance, hence full protection)

Anything lower than 100 % means you'll eat up radiation eventually. Any Engineer who spend a few minutes on the Engine site will quickly realize this also applies to the Singularity and Engineering Hardsuits, although the radiation is infinitely lower

**Comment by FudgePucker** [comment]
I think the main issue with the radio transmitters radiation is the fact that you black out instantly and then its gee gee no ree.

If you took burn and toxin damage from walking in there with an engineering rig suit or the elite rig suit instead of blacking out, it would be better.

If you walk in there in there with out realising that you don't have enough radiation protection you can walk out in time, as it stands now, as soon as you walk in there you black out and are dead because you can't get away.

Funny story is that one time I tried to make a radio station in the vacant office and thought that glass would block the radiation, the captian walked in there after seeing me die on the crew monitor and died as well.

The main problem is blacking out not damage. It is very frustrating when it happens because you are powerless to stop your death.

**Comment by AlphaBuffalo** [comment]
I think it may just be a damage resistance issue like Dylan said but I still think the CE should get fu 100% rad resistance just because he is the CE.

**Comment by FudgePucker** [comment]
Eh, removing all radiation damage might be a little too much, it would make dealing with super matter too easy. Just remove blacking out from rig suits, you would have enough time to see that you are baking alive in your suit to run the fuck away.

**Comment by AlphaBuffalo** [comment]
Well it would be just for the CE and its not like the SMR isnt easy, everyone who makes it (at least properly) don't put it in while they build, its the last thing. The only difference with the CE having full rad resistance is he can pull the shard out if need be and not die. Or do as you said and remove blacking out. Which imo is next best

**Comment by Kurfursten** [comment]
Your proposal of just buffing the CE suit doesn't really make sense from a game design perspective. If you just want one specific suit that can resist rads, we already have that: the radsuit. There are fourish in engineering and one on the sat, plenty to choose from.

Incidentally, the radio transmitter used to be even 50% stronger! I nerfed it down from a staggering 450 rads to a mere 300 rads. You can also reduce this to 150 rads by cutting one rad wire, which I recommend if you're doing a DJ setup.

**Comment by AlphaBuffalo** [comment]
I was just walking past it to get to the tcomms machine next to it, and thats where I died, trying to turn on comms over at the derelict.

**Comment by FudgePucker** [comment]
@Kurfursten Damage doesn't matter in this case.

Especially on the DJ satellite.

Once you black out you aren't getting back up, halving its damage just means that it takes longer for you to die in that helpless state.

**Comment by ihadtoregisterforthis** [comment]
Again, the DJ station has a suit of his own and again, as CE you should stay on station.

Ideally you could ask a borg to do the totally rad job for you.

Could engie robes have a speshul code Geiger counter? Maybe eyewear for detecting radiation sources?

**Comment by Skullyton** [comment]
Lot of people seem to die to radiation sources, is there any flavour text or warning (Besides the radiation symbols in most areas) that say you're getting irradiated? What's the threshold that causes collapse?

**Comment by FudgePucker** [comment]
@Skullyton
Nope. You black out and die.
There was a reason why dragging around the radio transmitter was so op. You can't pop some antitox and robust the guy, you just black out and die.

**Comment by AlphaBuffalo** [comment]
I kinda hope this hasn't become irrelevant, otherwise I may just close this
