### ISSUE TITLE
Request: Let MMIs and Posibrains see emotes.

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#6205]
They have eyes or optical sensors, or whatever those thingies are.
Personal problems were caused by the lack of this feature.

**Comment by Hoshi-chan** [comment]
Yes, please.

**Comment by Shadowmech88** [comment]
>holopads
Shouldn't the AI eye be able to see emotes in general? It's a camera, and emotes are strictly visual phenomena.

**Comment by Ephx1** [comment]
I always assumed that the cameras were just garbage, so they'd need to zoom to see people's gestures.
Like with reading papers, it's just too far away to get a good look.

Although I'm suspecting the real reason is to curb down Big Brother and general AI Nerf.

**Comment by Hoshi-chan** [comment]
Yup. AI doesn't need to see emotes via the cameras. It'd be nice, but unnecessary, and probably tough to code. It could also affect balance, not that AI needs it, since its only real power comes from atmos and doors, both of which can easily be bypassed.

However, holopads would be nice, since it's a much more solid, focused presence that the AI is projecting, and only into select locations.

**Comment by clusterfack** [comment]
This is not a balance issue in any way. It's an issue of mobs (brainmobs) inside devices (mmi, posibrain, pai). Systems like emotes are not recursive (finding mobs withing things), a long time ago the same used to be true of regular saycode as well, and once we implemented TG's recursivity it actually took a lot of processing power to keep up searching through objects. Emotes were never given this for performance reasons or laziness, one of those two.

Anyway getting back to the topic, I rewrote the way saycode works to be an order of magnitude faster so this should be feasible now. All it requires is someone changing the hearing method for emotes to use actual saycode.
