### ISSUE TITLE
Xenomorph issues

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6223]
There's been a lot of gripes lately about playing xenos and from what I've observed, they aren't unfounded.  I have a pretty good view of things.  I'm reading deadchat, ahelps, and modchat.  I'm spawning them in and watching them play.  

There's a few key areas I can identify and a lot more that are either already issues on github or I think someone else who is playing them can say better.

- Chloral and chems work against all xenos all the time except simple mobs.  
- Lasers wreck their shit six ways to Sunday and being seen by someone with a laser or proto kinetic accelerator is frequently an expedient death sentence.  You'll be fucked before you can run away.
- Ventcrawling issues covered here https://github.com/d3athrow/vgstation13/issues/6191
- Firelocks and mobility issues when already exposed and in the open which is as previously mentioned a death sentence https://github.com/d3athrow/vgstation13/issues/6196
- Eggs take too long to grow and larva gestate.  Evolution also takes too long at the start.  A curved evolution speed would be pretty damn slick so aliens gain plasma faster when there are fewer.

**Comment by Probe1** [comment]
In addition: https://github.com/d3athrow/vgstation13/issues/5074  Queens are up shit creek in combat which isn't really supported in the lore (movies) or from a gameplay standpoint since xeno queens are easily solo-ed.

https://github.com/d3athrow/vgstation13/issues/4269

General facehugger buggery.  They will gladly hop at the same monkey repeatedly that has a larva already gestated inside it if the original facehugger has fallen off, wasting additional facehuggers.

**Comment by Victorems** [comment]
Free the xenos

![image](https://24.media.tumblr.com/tumblr_m8lrb7ZiPc1rue4a1o1_500.jpg)

**Comment by Ephx1** [comment]
* Chloral and chems work against all xenos all the time except simple mobs.

This is very dumb and should be changed.

* Lasers wreck their shit six ways to Sunday and being seen by someone with a laser or proto kinetic accelerator is frequently an expedient death sentence. You'll be fucked before you can run away.

See, I think this should be at least kept in. As a Xeno I feel you should move stealthily through the vents and spread darkness when no one is around, really only one kind of Xeno I feel should be away from the Nest, the Hunter, which conveniently has a sneak mode which in the darkness is basically invisibility. Not to mention that if you disarm someone as a Xeno, they are beyond fucked, you get a tackle down a majority of the time, all the while you can strip them and if you're a drone or queen, slap them into a nest while doing so, or a babymaker if you're a Hunter.

* Eggs take too long to grow and larva gestate. Evolution also takes too long at the start. A curved evolution speed would be pretty damn slick so aliens gain plasma faster when there are fewer.

Not sure about the first part, but a curved evolution speed would be great as a boost to get the nest going before the AI glances at Xenobiology/Virology and calls the shuttle.

Actually expanding on the nest thing, I think the problem with Xenos is there's very few places on the main map of Box, it's either Xenobiology or Virology where you get placed, with good reason, they're secluded and have monkeys in them. Defficiency suits them perfectly, and I've never seen Xenos on Metaclub, Taxi must be a death sentence for them.

I think for Queens, they should just be tanks, I wouldn't mind either a speed buff or a resistance to lasers, because really, unless you're one person in a small room you'll easily kill the Queen before she can move towards you.
We could incorporate the Ovipositor, while attached she can make eggs, but moves incredibly slowly, while off she could then move a bit quicker, but I somehow feel that's going a bit too far.

**Comment by dylanstrategie** [comment]
- Chloral and chems work against all xenos all the time except simple mobs.

Snowflake code

- Lasers wreck their shit six ways to Sunday and being seen by someone with a laser or proto kinetic accelerator is frequently an expedient death sentence. You'll be fucked before you can run away.

For some reason, someone decided it was a good idea to double Xeno burn damage. While Xenomorphs don't like flamethrowers and what have you, this also makes them ridiculously vulnerable to laser weaponry and welding tools. Either remove the modifier or double Xenomorph non-crit health

- Ventcrawling issues covered here

Ventcrawling just directly checks for contents, which is dumb. The restriction was added to prevent Dionae from emptying all secure rooms on station by using the vents and a backpack, but it can most likely be handled another way

- Firelocks and mobility issues when already exposed and in the open which is as previously mentioned a death sentence

Firelocks were re-coded VERY aggressively. If you don't have a crowbar or all-access, you're basically stuck in here, wherever you are naked, armed to the teeth or a demi-god. Blame the virulent and hopefully short-lived atmosia autism burst of half a year ago

- Eggs take too long to grow and larva gestate. Evolution also takes too long at the start. A curved evolution speed would be pretty damn slick so aliens gain plasma faster when there are fewer.

Eggs should take less time and should auto-pop and be cleanable by everyone. Evolution should be sped up massively by weeds, but otherwise the waiting time is somewhat justified (it's the warning that isn't, it often blares way too early)

- Queens are up shit creek in combat which isn't really supported in the lore (movies) or from a gameplay standpoint since xeno queens are easily solo-ed.

Fix Neurotoxin by making it either a taser or an auto-aimed single MM-like ability. Also massively increase the Queen's health. It's already slow as dick, so it sure as hell doesn't need to move so slow it can barely outrun a limping crewman

- General facehugger buggery. They will gladly hop at the same monkey repeatedly that has a larva already gestated inside it if the original facehugger has fallen off, wasting additional facehuggers.

Facehuggers need more checks so that they aren't wasted. It might even be interesting to have them scamper and use vents on their own, although that would need strange coding since they currently are coded in as masks (and thus objects)

**Comment by Hoshi-chan** [comment]
Yes to everything.

**Comment by Duny-** [comment]
People used to call the shuttle upon seeing xenos. Now they just gets lasers and melt them even more easily since burn damage to them as been doubled, or call the shuttle if they were left unchecked for a while. The day xenos aren't pushovers they'll call the shuttle immediately again. I used to do xeno rounds but either I was the queen and the shuttle was called once I had a nest going (or I died pathetically) or I wasn't and they died pathetically (there was also the problem of xeno signups which has been fixed); it's just not worth doing anything.

For starters, the fucking warning needs to go. I have a lot more to say but I gotta leave. :^)

**Comment by ihadtoregisterforthis** [comment]
Last fun xeno rounds I remember were when admins shut the power when the shuttle was called, and when a clown made a mass driver ride with a gygax inside.

Another problem with the xenos is the small numbers they usually have. Either because there are very few ghosts or because those who could play don't want to be a xeno for a few minutes until the whole crew storms in lasers ablazin.
Could simple mobs when no candidates accept be a possibility? Would increase the secrecy needed for facehugging since you don't know if the larvae will be setient.

**Comment by Probe1** [comment]
> AlanDemarest
>As a mechanic I killed an alien queen and drone, single handedly using chloral/sleep toxin and a kitchen knife..

>Please buff aliens.
crossposted from forums

**Comment by Ephx1** [comment]
One other thing Rei mentioned was the fact that resin structures can be Kenshiro'd into fuck because there's no delay on click attack for them.

**Comment by ihadtoregisterforthis** [comment]
Stuff that could change are the slow as fuck acid and the weakness to the easiest obtainable weapon.

Could the neurotoxin have a hotkey like ALT+click?
