### ISSUE TITLE
Make bank account security a per-character setup option

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6244]
So that miners don't have to go risk getting mugged in the hallway to change their account security to zero to use the machines like they used to every round.

I guess having money deposited from the smelter into your virtual wallet rather than your bank account would be fine too.

**Comment by Probe1** [comment]
Christ, I meant to make this exact issue the day it was implemented and something always came up.

THIS
THIS
THIS

I HAVE TO CHANGE MY ACCOUNT SETTINGS EVERY ROUND!

**Comment by dylanstrategie** [comment]
I'm fine with that. The only problem is that there's literally no reason to not just set your account security to Zero and forget about it permanently

Actually having to find an ATM to transfer money to your virtual wallet is extremely annoying, especially since people barge down the hallways where they are located

**Comment by Hoshi-chan** [comment]
Yeah. I really don't understand why this was implemented at all, as it just made working with money frustrating again, but I'm not looking to rock the boat, I'd just like the ability to disable it completely and pretend it never happened.

**Comment by DeityLink** [comment]
Well if you can set your account to 0 by default anyone who steals your ID can still  take all your bank account's money but sure I'll add that. I haven't tried coding anything that affects a player's preferences in a long time though so it won't be out soon.
