### ISSUE TITLE
Borer host-related upgrades

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#6260]
Not being able to check for myself completely. Based on the fact that the specific evolve option dissapears, I'm guessing that this is how this happens:

When as a borer you evolve the telephoto vision, the host properly sees further. That option is then consumed. If you enter another host, the former retains the special eyes, but is not possible to improve the new host.
Since I never heard of a home-head complain about losing vision I discard them losing the changes on borer exit. Same for the better livers

This is rather uncomfortable because you can only make a single supersoldier. It could be adressed by either allowing multiple uses of said evolve options or moving the upgrades to the borer, so any host would reap the benefits, but this makes less sense.

Borers also seeing further when the host can would be nice too.

**Comment by Shadowmech88** [comment]
>moving the upgrades to the borer

I like this option better since it means a single borer couldn't run around the station handing out supersight to the entire crew.
It could be rationalized in that the borer is acting as an auxiliary source of body cells, filtering alcohol that passes through it using its connection to the bloodstream and connecting directly with the host's visual cortex to act as a vision enhancer, both of which would logically be lost if the borer was no longer physically present in the host.

**Comment by N3X15** [comment]
Most host-related things are supposed to be removed when the borer leaves.

**Comment by ihadtoregisterforthis** [comment]
Then why not allow the repeated use of them? If the borer has to leave the host, at least let it evolve again.
*This wasn't really a bug report ~~tbh~~ desu*
