### ISSUE TITLE
Option to disable mining message spam

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6290]
> You start drilling.
> You finish drilling the rock.
> You start drilling.
> You finish drilling the rock.
> You start drilling.
> You finish drilling the rock.
> You start drilling.
> You finish drilling the rock.
> You start drilling.
> You finish drilling the rock.
> You start drilling.
> You finish drilling the rock.
> You start drilling the rocky debris.
> You finish drilling the rocky debris.
> The rocky debris suddenly crumbles away.

**Comment by Cyadox** [comment]
I've been meaning to bring up a feature request that disables 'system messages'. Maybe a preference that disables certain text styles.

**Comment by Hoshi-chan** [comment]
Well, it's just that now we have a visual cue for mining in the form of progress bars, as well as the audio cue when you press against a wall, so I don't see why the spam is necessary at this point. Before progress bars, that was your notification that, "Yes, you are digging."

**Comment by clusterfack** [comment]
Not everyone plays with progress bars

**Comment by uazuaz** [comment]
then those messages could be active only for people that disable progress bar.

**Comment by Hoshi-chan** [comment]
Well, I said "option", not "remove them entirely", didn't I?

**Comment by Cyadox** [comment]
I have to agree with @Hoshi-chan on this one, but I don't think there's an easy way to turn off notifications without turning them ALL off, which would be very bad since that notification style is used practically everywhere. 

I suggest we make a player-toggleable flag for the 'mining proc' that disables that specific notification only, and maybe further enhance it to block other spammable notifications or warnings.
