### ISSUE TITLE
[Feature Request] Give paramedics more medbay access

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6321]
Even geneticists have access to surgery, chemistry, and virology, on top of science access, and paramedics don't? What the fuck is this shit?

Everyone in medbay EXCEPT paramedics can go everywhere in medbay (save for the CMO's office). Paramedics have more of a reason to be in chemistry than even doctors, seeing as they can improve their own personal cryo tube's mix or create pill bottles of cure-all pills to revive the dead in the field, or at least keep them alive long enough to get them into medbay for real treatment.

**Comment by FudgePucker** [comment]
paramedics also have full maintenance and external airlock access.

**Comment by PJB3005** [comment]
@FudgePucker to add to this, other medbay staff do NOT have paramedic access.

**Comment by Probe1** [comment]
:-1: 

Play doctor if you want to shove virologists and chemists out of the way and do their job instead of yours.

**Comment by Rei1226** [comment]
I'm pretty sure paramedic's have surgery access. That's pretty much all they need

**Comment by Hoshi-chan** [comment]
I'm pretty sure paramedics do NOT have surgery access, as I've played medbay pretty much all week and have had to keep opening surgery/chemistry for paramedics because they're the only other medbay staff.

**Comment by Probe1** [comment]
You are correct, paramedics do not have surgical access on Box.

As I said, giving everyone access to everywhere for Science and Medbay has not improved things.  There exists multiple mechanisms for paramedics to gain access.  The HOP/Captain, any engineer that is willing to give you a second, any silicon which if it's close to roundstart is all but guaranteed to open and bolt the door for you, or you could be proactive and do it yourself by removing a window or getting gloves/the door wire and tools to open it.

Paramedics job is not to make chems or cure viruses or perform surgery.  It is to retrieve the wounded.  They already have access that the rest of medbay does not (Maint) to perform their job.  Giving them complete medbay access would give a minor Quality of Life improvement for some and a huge Powergamer QoL improvement.  Why bother taking a Medical Doctor job when they have all the access + maint as a paramedic?  Why bother taking CMO when you get full medbay access but no head responsibility?

The status quo of having to get additional access to fit the specific needs of the round works and giving paramedics more access works against the purpose of the job.  If paramedics want to be chemists then they have different job options for that.

**Comment by Hoshi-chan** [comment]
Most chemists abuse their position or fail to do their job, most departments tend to take care of their own corpses as far as returning them to medbay for cloning, and the medbay lobby now has a crew monitoring computer accessible by all other medbay staff. What then, is the point of a paramedic?

Most often I see them trying to fill in for a lack of doctors because, whoops, they chose paramedic instead of doctor and realized that they have access to nothing.

Yes, there are ways to circumvent the lack of access, but grabbing tools and dismantling medbay is a shitty solution, as is asking the silicons to bolt open doors to rooms containing the circular saw and chem dispenser, which will almost certainly be looted by assistants or the clown.

Right now, with the way that medbay access is, everyone but paramedics can go everywhere, and therefore medbay works by being communicative, cooperating, and respecting the boundaries of other people working there. You don't run to viro and shove the virologist around if a virologist is actively working, just as you don't do the same to chemists in chemistry, or surgeons performing surgery. You have the access, IF YOU NEED IT, which is exactly the point. No, a paramedic shouldn't be doing chemistry or surgery, but oftentimes, they need to do it themselves, and breaking windows and welding walls is an awful way to go about doing it, especially if someone is dying of internal bleeding.

**Comment by Hoshi-chan** [comment]
@Probe1 Right, and the thread just reminded me, doctors can al

**Comment by Hoshi-chan** [comment]
Whoops, fuck.

**Comment by FudgePucker** [comment]
If parameds had more access then they would be super doctors.

A chemist at round start can't chloral someone and drag them out of an external airlock through maint. Parameds have limited access for a reason.

If they had full access no one would play medical doctor or chemist over paramed

**Comment by aceedex** [comment]
At the very very least paramedics should have surgical access. Ideally they'd have surgery and chem. But for the sake of balance Id take just surgery since they already have maint. 

At the very very least I should be able to reliably stop internal bleeding without having to break in through surgery observation. 

And no, having to bolt open/break in to sensitive areas just to do a very basic part of medbay is not a good solution. Specially if youre the only doctor worth a damn/only doctor altogether that shift.

And speaking of paramedics. When are you going to put magboots in their EVA closet?

**Comment by Hoshi-chan** [comment]
Yeah, that is kind of a problem.

They should at LEAST have surgery though.

**Comment by ihadtoregisterforthis** [comment]
Plasmamen parameds are subpar, they can't do CPR. Probably for another request.

The thing is that parameds are pretty independent from medbay. They aren't really expected to do surgery and fill a patient on all kinds of medicine. They are the first ones to assist on a breach. They smoke by default. They have their own office with cryo and Med console. They have an arcade machine. They aren't frowned upon if they leave medbay. They have a hat.

Sure you can do all the work or be like the asshole surgeon that does nothing because "lol i only surgery". Parameds are not blue medical doctors.

**Comment by Probe1** [comment]
eh, we're right back to the beginning.  If you wanted to do surgeries then why did you pick paramedic?  If you wanted to do chemistry, " ".  

If the specific round necessitates someone filling in for another position then go get the access, break the window, get a silicon or engineer to leave open the door/change the access.

If you want to trade maint and brig access for chem and surgery then that's fine by me.  Just pick doctor.  Otherwise your job isn't to stop internal bleeding, it's to bring the wounded to medbay and proactively treat crew before they reach the department.

@ihadtoregisterforthis snowflake toll.  if you want to give CPR then you have to give up the free spacesuit.

**Comment by PJB3005** [comment]
Personally I'm against this.

**Comment by Probe1** [comment]
I think a good comparison to show why this isn't something I support can be made with RnD.

The protolathe has tons of goodies for medbay.  Any shift that I play medical and we don't have access to trauma kits and bluespace beakers I'm tinged with annoyance until they're delivered.  Does that mean Medical staff should get RnD access?  Or have a personal protolathe?  How about engineers, they'd benefit as well, as would security and service and conceivably every department.  But they must depend on research players helping them, like research players depend on miners and botanists, or indirectly engineers to supply power.  

The game is based around having restrictions and ways around the restrictions.  If medbay doesn't have a chemist then there's a window you can break, a player you can ask for access from, ways to get around it.  Removing the restriction does not improve the game.

**Comment by aceedex** [comment]
Probe, its not necessarily that I want to do surgery but rather sometimes the extra hands are needed. Might as well take geneticist and chem acess from MD. If you wanted to do chemistry you should have picked chemist.

And take surgery and genetics from chemists too. 
See? Its silly when you put it in the scope of any other medbay role. Specially since the only thing stopping MDs from being superior paramedics in every possible way is maint access, which isnt hard to get. Certainly much easier to get than chem and surgery

**Comment by Probe1** [comment]
I stated in an earlier post that I had no problem with your suggestions.

**Comment by aceedex** [comment]
True. You dont need chem or surgery to be a good paramedic. Does that mean we can give parameds telesci access then? Because that really helps with rescues.

But your post is something that sounds good on paper. Sure, good parameds just bring people to medbay. But if you just bring people to medbay and let them die of whatever because you can't make the chems/enter surgery, is that really a good paramedic or doctor in general?

Sometimes you need to do things yourself in many situations. Thats why at least I'd like them to get surgery

**Comment by Rei1226** [comment]
That's odd. I could have sworn one round yelling for a doctor to help me and open surgery so I can do surgery on a dying patient, then I bumped into the door and it opened, and I was like Oh...huh, guess paramed's have surgery access now.

Now that I think about it i'm actually pretty sure I was chemist, and medbay was so terrible that round that I was doing their job as a chemist.

Why the fuck does a chemist have surgery access but a paramedic does not? Seems a little bit silly. I think that should be at least be changed and parameds should have surgery access. Nothing more than that though.

Although the way the morgue doors works makes zero sense. I'm almost positive I made it so parameds had access to both the doors from their office leading to the morgue and the general door near genetics leading to the morgue, but I'm pretty sure Duny changed it so they only have access to the door from their office. They also don't have access to use the door that goes out of the morgue to the hallway. What sense does any of that make? You can use one door to get in, but not the door two tiles over to get in? They both lead to the same room.
