### ISSUE TITLE
wrong destinations when sending parcels

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6326]
(WEB REPORT BY: hurr REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
96874c752ecc178602a4043dc993fa92ad6cafb0

>General description of the issue
on Box Station, some of the destinations are bugged when sending parcels using disposal unit + destination tagger

>What you expected to happen
that every parcel reachs its destination

>What actually happened
BAR
if you send a parcel to bar, the parcel simply comes back to delivery office, coming out of disposal outlet after about 30-60  seconds.

THEATRE
if you send a parcel to theatre it arrives at the bar

CARGO BAY
A) if you send a parcel to cargo bay from the delivery office, it arrives at mechanics workshop instead;
B) if you send a parcel to cargo bay from the delivery chute (west side of cargo, near supply shuttle dock), it arrives at cargo's disposal unit

NOTE: i noticed that there is no label for mechanics workshop, so maybe the destination is right but the label is wrong; if this is the case you still need to fix point B anyway.

OTHER DESTINATIONS
all other destinations seem to work fine but i'm not 100% sure because i just tested them once.

>Steps to reproduce if possible
send stuff to all the destinations.

**Comment by Exxion** [comment]
It used to be worse. I guess some were fixed. I remember trying to use a destination tagger to sneak into several rooms and the only one that actually worked was the library, as I recall. That was months ago, though.

**Comment by Shadowmech88** [comment]
Were you sending all of these one at a time?
If you send multiple packages at once, ALL of them get sent to the destination of the first package, because the package sorter is not a smart machine.

**Comment by uazuaz** [comment]
(i'm Hurr on BYOND)
i tried 1 single parcel each time.
by the way, i know that you can send multiple items at the same destination wrapping and tagging just 1 item, as i can see it's intended to work that way.

**Comment by Kurfursten** [comment]
Reproduced successfully on local. This is a map issue. The only way to solve it is to make anyone who edits the map swear they understand how disposal pipes work, because only a few people do. The result is a lot of broken sorting junctions as people just throw any sorter on and assume that will work.

I look at the map file and it appears someone has blanked all of the sort_tags on every sorter, and added a useless sorter to the mechanic workshop which isn't even a destination. We're using the depreciated sorttype variable now and it's not working. Anyone who worked on the map recently could be to blame.

@dylanstrategie @probe1

**Comment by PJB3005** [comment]
Also if anybody's going to fix this, subtypes AND use the `sort_tag` var so we can remove `sortType`.

**Comment by Probe1** [comment]
I don't even know how it works and didn't go near anything related so I couldn't tell you if I did it.  I doubt it did though.  However I did encounter this yesterday and assumed it was an error on my part.  

Hydroponics and Security worked just fine.  Bar did not and sent the package to disposals.

**Comment by ihadtoregisterforthis** [comment]
Research also went to disposals. Personally rode the ride to ensure this. 
What caught my eye is how the crate so carefully packed got unwrapped by the time it hit destination.

**Comment by uazuaz** [comment]
for further information, i saw this bug about 2 months ago so is not so recent. i opened a report on gitlab at the time.

**Comment by Faptastic** [comment]
The bar one is localised to this single piece of pipe, the theatre is working fine it just never gets a chance.
!Bar Destination Bug](http://s16.postimg.org/g97bct8px/bar_bug.jpg)
The mechanics workshop is labeled as cargo bay, so basically, check the labels and in the meantime, use the d.tagger to correct them mid-round.

This bug is still there in the bleeding edge, but easily fixed.
