### ISSUE TITLE
Bees are pussies and weaker/more useless than slimes.

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#6333]
Using bees as an antag seems to be intended but is impossible. For example you CAN make killer bees by feeding them poison or shooting them with a floral somatoray for bigger stingers, which modify their toxin and brute damage dealt.

But what is the point?

-Bees hardly survive long away from a hive due to beecode
-You can net bees, but releasing them from a net makes them attack only YOU
-They move slower than walking speed so anyone can just move away from a swarm
-They somehow get stuck in windows/grilles when calmed
-It only takes ONE well aimed spray from a fire extinguisher to calm them down, three if you suck making them way too easy to pacify
-If you attempt to use rogue bees, everyone will know it was you (the botanist)
-If you want them to attack anyone, you have to convince them to hit the hive or the bees, which they will not do
-There are no special items to make bees more dangerous besides buffing the bees strength, for example there should be a traitor item that makes bees impossible to calm or a suit that lets you control bees

Feel free to add on to why bees are disappointing

**Comment by 9600bauds** [comment]
I might look into this later, for now, I don't think the "everyone will know it was you" bit can be addressed. 
That said, something that also needs mentioning is the fact that anyone in a spacesuit is completely invulnerable to bees. That's something that would be hard to balance around.

**Comment by Killette2** [comment]
Floral somatoray makes their stingers do more brute damage by making them bigger/sharper/whatever. Maybe at a certain strength they can pierce all suits?

**Comment by FudgePucker** [comment]
>suit that lets you control bees

THE PAIN.

Bee machine guns when?

**Comment by PJB3005** [comment]
@FudgePucker is this Terraria?

**Comment by DeityLink** [comment]
Working as intended.

Xenobiology is protected behind reinforced walls for a reason. If you want to toy with dangerous critters get a job change.

Now I'm not saying we cannot improve bees so I'll answer each of your points:

>-Bees hardly survive long away from a hive due to beecode

blame N3X15? I think this change was unnecessary, bees outbreaks just like vine outbreaks are part of what makes playing botanist dangerous and !FUN! that being said, I've had plans for Beekeeper 3.0 where bees would have a more complexe path, (and do trips back to their hive to store the acquired nutrients and progress the honey production)

>You can net bees, but releasing them from a net makes them attack only YOU

I've got plans to improve antag-bee-netting in Beekeeper 3.0 since the main issue with bees in nets is that they completely forget their attributes (mutation/toxic/origin apiary)

>They move slower than walking speed so anyone can just move away from a swarm

They always have, people still hate them though. I think I could have swarms split into faster/smaller swarms mid-battle.

>-It only takes ONE well aimed spray from a fire extinguisher to calm them down, three if you suck making them way too easy to pacify

Oh you're kidding right, it's the exact same with rabid slimes.

>-If you attempt to use rogue bees, everyone will know it was you (the botanist)

well DUH!

>-If you want them to attack anyone, you have to convince them to hit the hive or the bees, which they will not do

as I said they aren't reliable to antags right now, Beekeeping 3.0 will fix it (for the record 2.0 was https://gitlab.com/vgstation/vgstation/merge_requests/100 )

>-There are no special items to make bees more dangerous besides buffing the bees strength, for example there should be a traitor item that makes bees impossible to calm or a suit that lets you control bees

I like the traitor suit idea. Will think about it later.

**Comment by Killette2** [comment]
Make it a bee antennae hat like on venture brothers if you want bee mind control to be obvious, but if stealth make it look like a bee suit.

**Comment by Hoshi-chan** [comment]
Or you could add bee pheromones that make bees friendly to you.
