### ISSUE TITLE
Health analyzers no longer give low blood counts in big red letters

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6375]
Can we go a week without fucking things up by "fixing" them?

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/10831270/1906c7d0-7e5b-11e5-8e4a-cc8d69c16433.png)

This bit should be huge.

**Comment by PJB3005** [comment]
> Can we go a week without fucking things up by "fixing" them?

Well, not accepting things from @dylanstrategie isn't that hard.

**Comment by dylanstrategie** [comment]
This is intended. The blood display is only bold if blood levels are so low you'd start choking on toxins. Otherwise there's no points since everything would be bold

**Comment by PJB3005** [comment]
@dylanstrategie hey nerd, in the picture **the blood level is at 55 %**, if that isn't deadly then I don't know what is.

Also, you don't die from toxins if you lose blood, you die from oxyloss.

**Comment by 9600bauds** [comment]
ANY blood loss is a MASSIVE problem. I know for quite a few doctors, 55% is below the "fuck spending all my bloodbags in this guy, just clone him" threshold.

**Comment by Cyadox** [comment]
@9600bauds I'd put it at the 60-65% mark but agreed. Should be a quickfix too.

**Comment by Probe1** [comment]
If the paramedic hadn't given me a dex pill and given me the time to stuff my face with 20u of dex and hook myself up to a blood bag I would have died.

Anything below 75 is a serious fucking problem and there was no reason to fuck with it.  Doctors need to know when something is a serious problem.

**Comment by PJB3005** [comment]
Also I'm gonna mention that this was NOT mentioned in the PR description...

**Comment by Exxion** [comment]
Hell, an actual person missing 45% of their blood would already be dead

**Comment by Cyadox** [comment]
So from a bit of research I was able to determine, yes, this was @dylanstrategie 's doing, but it was only because he was using old values still present in the code to give more feedback with the scanner.

Previously, any volume under 336 was considering Critical - anything between 337 to 560 was Low. The new code puts these thresholds at SAFE (500+ - 337), OKAY (336 - 225), BAD (224 - 123) and SURVIVE (122 or less), and only warns between the BAD and SURVIVE thresholds.

Fortunately these defines are only used in iv_drip.dm (to beep(what) or stop giving blood) and scanners.dm (duh), so I think we should either tweak them to better reflect what would realistically be the threshold between 'Give them bloodpacks' and 'Clone the fucker'.

**Comment by dylanstrategie** [comment]
The problem is that those defines are in theory used in blood.dm itself

If you want to tweak them, look at https://en.wikipedia.org/wiki/Hypovolemia for how they were obtained in the first place

**Comment by clusterfack** [comment]
That evidence only servers to make those values look fucking WRONG.

From that webpage
Stage 4 (blood loss)
Loss greater than 40% (>2000 mL)
Survival is extremely unlikely

336cl is where the 40% value occurs. So yes, 'survival is extremely unlikely' is fucking CRITICAL.

**Comment by Probe1** [comment]
please don't try to bring real life data points into autism station 13 medical system.

also please revert this whole health analyzer thing thats caused nothing but trabble.

**Comment by clusterfack** [comment]
@probe1 The real life values match up pretty well with how it works in-game. The real problem is that the code he wrote doesn't match up with the real life values!

**Comment by dylanstrategie** [comment]
@Probe1, the health analyzer works, stop trying to get things reverted left and right

The only problem is that a single Chemist killed himself with an IV by accidentally draining half of his blood, because apparently he's not used to actually reading the blood percentage, instead of waiting for the thing to turn bold

I give it one week before everyone gets used to the new display and this never happens again. Warning means you're getting hurt, Danger means you're basically dead unless you're being transfused gallons of chemicals (which is useful to rate defib patients)
