### ISSUE TITLE
Cloning might be a bit broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6404]
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7777)
Having an extreme increase in clones coming out of cloning, and they're still considered 'asleep' (Not being able to interact with anything, instead saying "I can't quite see it") while still being able to see everything and move around. They stop taking damage from external sources (Vox wasn't taking oxy and toxin damage from breathing oxygen, and was shot with a chloral syringe and went over a banana peel while naked and didn't even go down)

As for the "Skeleton day" bus, any humans that had become skelefied and then cloned would gib into a skeleton while inside the cloning pod, so they wouldn't regenerate any clone damage and couldn't get out regardless of if the cloning pod was turned off.

**Comment by Skullyton** [comment]
On top of this, the new clones are just called "unknown", and can't succumb after suiciding.

Gonna be adding more details as I see them.

**Comment by PJB3005** [comment]
Related to #6403 maybe?

**Comment by Rei1226** [comment]
Cloning is incredibly broken right now. People are popping out as completely immortal humans simply named "unknown" and are unable to interact or do anything aside from walk around. Attempting to admin rejuv them gave me an error message saying I wasn't rejuvenating a valid mob. Pretty much only thing I can do at this point is put their ckey in their old body and admin revive that.

**Comment by Hoshi-chan** [comment]
Some testing I did with the failed clones yielded these results
* They can be unfucked by having an admin gib them and a player transplant the brain
* Chemicals do not affect them
* Explosions do not affect them
* You cannot perform surgery on them
* They cannot be slipped, stunned, or otherwise disabled in any way

**Comment by FudgePucker** [comment]
What the hell happened to cloning?
What was the last change?

**Comment by Probe1** [comment]
``` runtime error: Cannot execute null.get reagent amount().
20:47:36 Runtime detected
Cannot execute null.get reagent amount(). at cloning.dm:304 ```

**Comment by mrpain666** [comment]
ITS ALL TUMBLING DOWN

**Comment by Probe1** [comment]
It may be fixed as of now, but I noticed strange behavior regarding a Captain being unable to be cloned because his implant was missing??  Leave the issue open for a bit longer and I'll stay on it.  Cloning **is working** right now, but there may be a kink.  

![2015-11-03_02-53-18](https://cloud.githubusercontent.com/assets/8550416/10906932/a5507f9c-81f3-11e5-88be-5518fa5c7807.png)

**Comment by PJB3005** [comment]
Er, doesn't the cloning scanner inject health implants into people, so you can track their health (not location though) from the cloning computer?

I think that implant just got missing.

**Comment by Faptastic** [comment]
Local tests have produced a fully working clone of myself, implant and all. Looks like it's fixed, yay.
