### ISSUE TITLE
silicate sprayers for Mommis and Engi borgs

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#6438]
As a upgrade or round start thing.

**Comment by Probe1** [comment]
:+1: silicate sprayer roundstart for mommis.  They've missed a lot of recent upgrades to engineering and they deserve some love.  I'm one of the people that said they should miss some of the recent additions so I feel like this is their time.

**Comment by AutismSpider** [comment]
Like for both of them to get and a upgrade board to make it a Adv sprayer

**Comment by Probe1** [comment]
I completely agree.  Partially because MoMMIs have missed a lot of upgrades.  This is one they should get.

**Comment by Ephx1** [comment]
Eh, I'd agree it for an engineering borg upgrade, but MoMMI has graspers. It's like the soldering iron, it's on the station and you can go nab one yourself.

**Comment by AutismSpider** [comment]
they have graspers but no real way to bag it for later use. 
using a plastic bag as a hat bugs the UI out some times and the items poof into nothing some times

**Comment by PJB3005** [comment]
Engi borgs already have them, but I decided to not give MoMMIs them because muh MoMMI powercreep.

**Comment by Probe1** [comment]
When was the last thing MoMMIs got?  It's been a while.

**Comment by clusterfack** [comment]
Their sight button back

**Comment by PJB3005** [comment]
I'd add it but now it's feature freeze so...

**Comment by PJB3005** [comment]
Just for clarification, I did want to give MoMMIs silicate sprayers, I just didn't want to get shot for le MoMMI powercreep.

**Comment by FudgePucker** [comment]
MoMMIs not getting silicate sprayers is retarded.

Seriously, what is the harm in MoMMIs getting normal and not upgraded silicate sprayers?

Oh man, they aren't going to have to spend 5 mins deconstructing windows then reconstructing them when they are damaged, OH GOD MUH BALANCE.

The people who complain about le MoMMI powercreep are just shitposters, MoMMIs haven't gotten much recently, after the ventcrawling nerf that turned a very fast way to teleport across the entire station into a much slower way of travel that might be useful if you were malf or some shit, I don't think that giving them a god damn silicate sprayer would shatter the balance.

Science can print rapid fire syringe guns that aren't in a lock box, BUT GOD FORBID IF MOMMIS CAN GET A SILICATE SPRAYER MODULE.

**Comment by AutismSpider** [comment]
If you want to see powercreep old mommi was it.

Now not so much only thing they got going is the power grab shit most of it they cant use and the half ass thing we now call ventcrawling only helps xenos and rouge mommis the most

**Comment by FudgePucker** [comment]
@AutismSpider 
Yea seriously, MoMMIs have been nerfed to nothing after the vent crawling fixes.

Engineering borgs get a mat synth that can copy any mat, a RCD that is almost limitless and can even decon rwalls, and if you don't feel like being an engineer that round you can also be a mediborg secborg servborg janiborg or miningborg. MoMMIs are just MoMMIs, only benefit you have over engiborgs is being able to put plasma tanks into rad collectors.

Also playing as a borg over MoMMI is a lot less tedious and repeditive. You can get rounds were you are a traitor, the AI is malf, get ordered to 'shut off your radio and stand still while I emag you', or someone uploads onehuman kill all non humans. MoMMIs can only be emag'd and you are to run away from emag'ers because letting yourself be emag'd is involvement.

If MoMMIs still had the same teleporting vent crawling I would understand why you would not want to give them a silicate sprayer module, they could just vent crawl to nest and print one out and then vent crawl back, but after the changes, vent crawling to nest could involve going though a station sized maze.
