### ISSUE TITLE
6 (Six) Cyborg rechargers on Deff, as little as two threes

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#6468]
~~*Actually five, but couldn't write a prime number as a product without fractions.*~~

Two near the AI core, two well hidden in engineering and one in the MoMMI nest, that barely sees any use.
For comparison, Taxi has seven, and Box has ten. These are much more clumped stations and the rechargers have easy access.

While yes, rechargers can be built with ease, you never notice the lack of them until you have a blinking red light in the battery and have to make a run to the ones in science, the most obvious ones.

PS: Make that six, there's another one near the AI core besides the red phone.

**Comment by 9600bauds** [comment]
so it's as little as two threes

**Comment by Kurfursten** [comment]
Deff is actually more clumped than Box, as the departments are small and close together paradoxically without much maint. The "maint" area is mostly off to the side and not intertwined like on Box and Meta.

That being said, I don't think one charger near sec or escape would hurt, since that's the only real remaining blindspot.

**Comment by Exxion** [comment]
>Can't write prime number as a product
>"As few as one five"

**Comment by ihadtoregisterforthis** [comment]
pls no
