### ISSUE TITLE
Deff shuttle console at research station can't call shuttle

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6514]
![ss 2015-11-10 at 02 13 58](https://cloud.githubusercontent.com/assets/8556111/11056770/29bf17a2-8753-11e5-80d1-31d778f7b567.png)

**Comment by Probe1** [comment]
>speciied

**Comment by Hoshi-chan** [comment]
No clue. It was just like that when I tried taking the shuttle back via the research station on deff.

**Comment by Duny-** [comment]
The computer on the research station seen here 
![ss 2015-11-10 at 06 36 21](https://cloud.githubusercontent.com/assets/5224390/11070102/060d194e-87da-11e5-81fd-4dd73afad479.png)

needs to be replaced with /obj/machinery/computer/shuttle_control/mining

It doesn't find docking ports because it's still trying to use the research shuttle, which doesn't exist.
