### ISSUE TITLE
Spiderbots can't pick up anything

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#6561]
*again*
Except now it doesn't give you a message that you already have something in your hand, it just straight up reads you can't pick up anything.
I also found that they can flip tables sometimes, but not other times, which is odd.
I know you can't flip reinforced tables, but the one in aux storage isn't reinforced, I couldn't flip that one, but could flip the one in robotics.

**Comment by Probe1** [comment]
The hand thing I don't know about.  Spiderbots *don't have hands*.

The table thing I've been able to reproduce and I'm looking for the cause.  You are blocked from flipping tables on one side of them but not the other.  I initially suspect its because an apc was mapped there (but shifted on compile 30 pixels north)

**Comment by Probe1** [comment]
oh WOW.  Spiderbots have verbs under the spiderbot tab to pick up and drop items.  But they don't have click attackby kinda pick up stuff.

That.  Is.  Ghetto.  As.  Fuck.

**Comment by Probe1** [comment]
![2](https://cloud.githubusercontent.com/assets/8550416/11112382/7321debe-88e0-11e5-8b76-8b94281791fe.gif)

**Comment by clusterfack** [comment]
Kek, the pick up item verb and pick up verb are separate.

**Comment by clusterfack** [comment]
The table shit looks fine to me so if you guys find something actually WRONG with that make another bug report with steps to reproduce or some pattern or something
