### ISSUE TITLE
Give rev a check to make sure there's actually security

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6651]
Rev is terrible.  This would make it marginally less terrible.

**Comment by 9600bauds** [comment]
Yup

**Comment by PJB3005** [comment]
:+1:

**Comment by FudgePucker** [comment]
I mean shit, rev has way too many issues.
Issue one: Communication. Cult has communication runes, allowing them to communicate across the entire cult with relative ease. There is little to no communication in rev, even between head revs.
Issue two: GRAY TIDE WORLD WIDE. Here is how most rev rounds go. Head revs get caught early on and everyone gets implanted. Or there are enough converts to just fucking decimate the entire security team and the rest of the crew.
Issue three: People are fucking stupid. Seriously, cultists have a disadvantage of having to convert instead of flash, this works for them because they can be more selective with who to convert, not so much with just flashing all of the assistants to go attack the armed HoS with nothing but floor tiles and a tool box, this is only made worse by issue one.

The obvious solution would be to just remake rev entirely.

The only revs are the head revs and they can not convert, however, they get 5 TCs that they can also share with the other head revs who also have 5 TCs, they also get an implant that doesn't show up on scanners that lets them communicate with the other head revs using telekinesis, if they are injected with a loyalty implant, or if the implant is removed, it blows up with a dev 1 force (or greater, this is to make sure that they just don't metagame and implant everyone to look for revs, the implanter isn't going to survive it.), meaning that you can't just remove the implant to get the names of the other head revs, also no cloning, blood line termination if you fuck up this mission agent.

The five tele-crystals means that they have to work together and communicate to get the most out of them. If you don't really need your tele-crystals you can give them to a teammate, or if there is a mechanic you can print out multiple copies of the gear if you give him some to get his scanner.

The communication implant would allow for more coordination with the revs. If one is arrested, he can just tell his teammates that their cover is blown and go loud, with out being over heard.

This would turn rev from the heads fearing everyone because everyone is a rev into the heads fearing everyone because anyone could be a rev.

Four people working together perfectly would be much more horrific than a mob of 20 with no clear leadership.

Yes I know this just sounds like 'traitor round 2: team edition', but it would be more fun that 'team deathmatch, only this time one team doesn't know what the other team looks like'

**Comment by Probe1** [comment]
We can start today.  Well not today but after FF.  And it's something that can be done quickly.  Add one check to make sure that at least 2 people are playing security.  If not, then repick.

**Comment by AutismSpider** [comment]
only way to make rev less shit is take it out as game mode.

It was made   as RP game mode RP as half a fucking joke here so why do we have this game mode?\

If we want TDM we have cult for that.

**Comment by Ephx1** [comment]
I wouldn't say Cult is TDM. It's more "Sanic everything and summon Noosie" the only way you'll get caught is if you're mentally challenged, or are being validhunted to the maximum by an AI. Otherwise it's one of the simplest gamemodes, like extended except a demon pops out at the end.

**Comment by dylanstrategie** [comment]
"Check for Security" should really be a thing for all gamemodes

Force Extended if there's literally zero Security personnel. Basic gamemodes like Trators, Lings, Single Wizard and Vamp for 1-2. "Team" antags at 3 and more (because they are bound to actually overwhelm a small Security force very quickly, unlike lone antags that will approach Security by themselves)

**Comment by Probe1** [comment]
I think rev is the sole problem with no security.  Cult can be for the same reasons, but rev stands alone in its pure carnage.  

In every other game mode, it's "Us versus them".  In Rev and Cult, it's fighting to get people on your team.  Revs major problem is it is piss easy to convert and it quickly becomes a reverse nuke ops where command and security are the operatives, alone on a hostile station.  Unlike nuke ops, their hands are tied by being non antags and all the access locked doors and low starter gear that is standard to a round.  Cult would seemingly have the same problem but it takes longer to convert people and words must be researched.  It is by design slower and has speed bumps.

I want one thing for rev right now and it will improve it.  Make sure at least two security players are aboard.  2 sec and Heads++, versus 4 starter revs.

In other game modes, the number of security doesn't matter as much as the random skill levels of the antags, security players, and non security players willing to defend the station.

  Personally in one afternoon only a couple months ago I played three nuke rounds back to back to back.  In the first round, I wiped an entire nuclear operative team *by myself* as the only security officer there.  I did it with my taser.  The next round, I was an engineer and got shot in the face with an RPG which was amazing because those things never work out.  Security got rolled.  The third round I played security again and what do you know, it was nuke ops again.  This time I fell short of my mark.  I arrested 4 out of 5 nuclear operatives and convinced the last one to kill himself with the operatives nuke.  Those two feats were done with nothing more than a taser, a hardsuit, and a lot of spare cuffs.

What matters isn't how many, or anything else.  What matters is having someone there.  
If there's no security then no one is going to be able to stop the revolution.

**Comment by Hoshi-chan** [comment]
What if you didn't start rev heads with flashes, so that they had to do some prep work before flashing everyone and turning it into TDM?

Or you required them to use a sort of implant or something instead of just rushing up to people and insta-converting?

**Comment by AutismSpider** [comment]
We had some try the implant root people got mad all you got do is slip/disarm rng push some one get a implant in.

Better off taking it out as game mode or reworking.

**Comment by mrpain666** [comment]
I think this could potentially work itself out if the minimum player threshold for the mode was raised a bit. Seems too low now. And with more players, chances are you'd get more security and heads.

**Comment by nuklearcellphoneg** [comment]
When you start out as a Rev,

Why not inform the head Revs as to who the other head Revs are, so they can work on an actual plan...?

Cult has this via Communication talismans.

**Comment by FudgePucker** [comment]
Seriously, only round where I was head rev ended with me plasma flooding because I was in the mob that failed to murder the captain and had a suicide virus, told another head rev that I would plasma flood if shit got any worse earlier (Fun fact, he was banned for opening a canister of plasma and killing no heads of staff and killing revs, I flooded the entire station).
Still got my green text.

Rev really blows.
I still like my idea of nuke ops with less telecrystals that can stealth it because they start on the manifest with jobs, only they get less TCs, no super gear for free, and have to kill all heads and send a message to centcom from a communications computer instead of setting up the bomb.

**Comment by nuklearcellphoneg** [comment]
SOP is, if you win the round doing something you might get banned for as a non antagonist, then good job, but you run that risk. Rev rounds are one of the worst on which to do this due to its hectic nature, but not so much as a Rev, more so with a Captain. On a Wizard round, because the only way you can tell how many antags there are is if:

1) Wizard casts Summon Guns, which means there's only one wizard. However, this causes Survivors to be created, so the round won't end if they are dead, not to mention you don't know who the survivors are.

2) If it's Ragin', and you've killed all but one Wizard, and go to bomb the last... but he had mind swapped into another someone else.

**Comment by Probe1** [comment]
I gave a dude an award a week ago for managing to bomb the only vampire and save someone just outside the blast range from certain death.  The shuttle launched moments later and everyone survived thanks to him.

It's pretty fuckin rare.

Anyway 

@mrpain666 

> I think this could potentially work itself out if the minimum player threshold for the mode was raised a bit. Seems too low now. And with more players, chances are you'd get more security and heads.

This works too.

**Comment by Probe1** [comment]
this will not pass

**Comment by FudgePucker** [comment]
Oh yea another problem with rev rounds is that there isn't a real metagamey tell.

You arrest a someone and he has a tomb, call code red and implant everyone.
You arrest someone being a shitter and he has a flash, time to impla- BWANK, WHAT THE FUCK ARE YOU DOING YOU POWERGAMING SHIT? You have been banned. Reason: Fucking dumbass loyalty implanted someone for having a flash.

Someguy running around with a cult blade is a clear 'this is cult' tell, someguy running around with a flash, the fireaxe, and the entire armory is just every single round.

**Comment by AutismSpider** [comment]
why rev is shit and was taken out with vox riders make sure to put bullet in pomfs head for adding both back in

**Comment by mrpain666** [comment]
rev its glorious on highpop, I've played both sides on TG. Dont give up on it. Just change the thresholds.
