### ISSUE TITLE
You can't name your GMO strains in botany

### ISSUE THREAD

**Issue by Cisrox** [d3athrow/vgstation13#6761]
This is a feature request.

I think we should be able to name our GMO strains in botany to differentiate them, because I usually use the same base for some of my strains, and sometimes the other botanist grows the default plants. It'd also add a coolness factor.

**Comment by 9600bauds** [comment]
This is partially in my PR in the form of being able to label botany trays.
As for naming the WHOLE strain... I don't know, you're kind of naming your peridaxon chanterelle "banana" and everyone magically sees "banana" when they see it. It's a little weird.

**Comment by Cisrox** [comment]
How about just naming the seed packets? Like, strange plant spores [PERIDAXON], so it carries on with all plants?

**Comment by 9600bauds** [comment]
That's doable, but then again, it wouldn't really fix the problem you describe in the OP.

**Comment by ghost** [comment]
What's the problem with naming your apples bananas?

You can already splice any combination of plants with bananas, and one of the produce will be called banana containing all the chems of other plants. It's no less silly and even more deceptive than a mushroom being called banana.

Deathnettle bananas are still called bananas when harvested. It is stupid that we cannot distinguish between plant breeds because their seeds and produce are always named based on their base plant and product sprite respectively.

It becomes a nightmare once you add the produce to a fridge as they will all stack regardless of where the produce came from.
