### ISSUE TITLE
Add a little bit more info on how to type stuff into the web reporter

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#6802]
As you can see if you look at any web reports, people often fuck it up in some way that makes it a bit harder to read. Other times, people totally ignore the structure, which can't really be prevented, but being a bit more specific about where to type each part of the report might make reports from people who are actually trying a bit easier to read.

**Comment by FudgePucker** [comment]
Have a dialog box pop up telling them that it is laid out for a reason and it is double important to fill it out correctly due to the lack of an edit and reply feature with the web reporter, have it also list the revision build so that they just have to copy it right from it instead of looking it up.

Also remind them that it is only for bugs and not feature requests, if its not good enough for them to log into github then it isn't good enough for a coder to implement.
