### ISSUE TITLE
Mann's Drink not a child of soda_can, can't make IED with it

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#6826]
title

**Comment by Kurfursten** [comment]
Soda can IEDs are kinda snowflakey. Wouldn't it be nice if you could strap an igniter and wiring to any sort of container, and it explodes if it has suitable reagents, relative to quantity?

**Comment by FudgePucker** [comment]
Someone really needs to look at some of the ghetto bombs, @Kurfursten, rags in beer bottles filled with welding fuel still don't work as Molotov cocktails.

I want to be able to over throw shitcurity by throwing firebombs at brig windows.

**Comment by 9600bauds** [comment]
Where do you even get rags, I've only seen one, once

**Comment by FudgePucker** [comment]
I think there is one in the bar and one in bartending supply crates.

Like I said, someone really needs to work on ghetto bombs.
Someone was going to make cloth material datums that would have been able to make rags from ripped up jumpsuits.

**Comment by FudgePucker** [comment]
Maybe for IEDs, instead of using soda cans steal ideas from goon and be able to make pipe bombs from metal sheets. That way it would be a lot easer to understand and a lot more flexible, because as it stands, IEDs are pretty fucking shitty with how they are. You would make the pipe, fill it up with what ever chemical you have on hand, then wire it shut to throw it at whatever. Bonus points if you also include being able to put other chemicals in there, plasma makes it somewhat higher yield and causes a small fire, putting acid in there makes it shoot acid in the blast radius in exchange for loosing yield due to less amount of propellant, have some snow flake bullshit to make it no react so that you can have a pipebomb that produces a single slab of synth meat for you to throw at security, or polyacid grenades with 50% less effort but 75% less potency it would knock them into crit and remove all of their stuff instead of killing them beyond defibing and losing all their stuff, hell if polyacid smoke is too scary you can just add some snow flake that causes polyacid to just melt though the thin low quality pipe, seems kind of silly how polyacid can melt containers that can hold them, how does that work? I pour polyacid on a beaker it dissolves, but I pour polyacid into a beaker it is fine?

**Comment by Kurfursten** [comment]
@9600bauds Anything sharp on a bedsheet
