### ISSUE TITLE
Taxi2 Discussion

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6869]
Taxi is extremely cramped and difficult to work with.  It was designed for low pop in mind but players don't vote logically.  They vote on what they want to play.

Current Taxi will be very challenging to improve and meet players criticism due to its constructiveness.  I feel that at this point, the best option might be a complete re-write, using Taxi as a building block but ultimately making a completely new station.

Please discuss the idea.

![](http://i.4cdn.org/vg/1449279302762.png)

**Comment by Probe1** [comment]
Vote: Taxi should be..

Vote Result: Kept more or less the same but improved. with 16 votes
     Removed had 6 votes
     Remade had 0 votes

**Comment by PJB3005** [comment]
I agree the BELT HELL was very duct-taped on because I couldn't find a proper place to move certain things to.

**Comment by SonixApache** [comment]
Worth a shot, can't be worse than current taxi.

**Comment by Kurfursten** [comment]
I definitely think a redesign would be good, but it would also be crazy to do a remapping on that scale if people don't want it.

**Comment by Probe1** [comment]
Yeah that's why I'm not leaping to this and made a discussion.  I'd rather not spend 12 or 20 hours doing something that isn't wanted.

People do want taxi to be improved.  The problem is.. there's just no goddamn space.  Each station needs to be about 20% bigger for even lowpoop and that would be such a pain in the ass to do that you might as well start from scratch.

**Comment by ihadtoregisterforthis** [comment]
Worth a try. If anyone comes up with a design that ends up being better, **without being Box**, the kingdom of horror might end.

On that design in the picture, there's quite a few things that could be made better. There's a lot of unused precious space.

As for the general idea, what could go on a fourth station?

**Comment by CyberTropic** [comment]
A fourth station made up of maintenance tunnels and abandoned ghetto bars would be neat, since one of the problems with taxi is not enough hidden areas

**Comment by PJB3005** [comment]
@TNepr that's the derelict station for you.

Did you know you don't even need an emag to ride the taxis there? I sure do.

**Comment by Kurfursten** [comment]
@Probe1 Here's what it would look like more realistically with some thought put into it.

![untitled](https://cloud.githubusercontent.com/assets/9782036/12136126/2ff66baa-b40a-11e5-9169-d39ca5e6fa4a.png)

**Comment by Probe1** [comment]
It looks like you already have a map?  Make a PR!

**Comment by Kurfursten** [comment]
It doesn't have complete coverage for scrubber waste lines, antagonist ship docking locations, cameras, newscasters, intercoms, extinguishers, and other quality of life little things yet - many of these things require a significant time investment to test (besides ensuring access on all doors, etc.). I put in a few minutes here and there over a month and I finally have a prototype. What it does have is:
- Dramatically enlarged maintenance with ghetto bar and other similar rooms - maintenance exists in complete "loops" - you can walk around the circumference of the station on Medical station and Civilian station in maint without using the main halls, much like Box and Meta. Security station does also have larger maintenance, but not as extravagant.
- Much larger rooms that were suffering from extreme small size (e.g.: Botany, Xenobiology, Brig, Head and QM offices, etc.)
- Included missing Teleporter, Dorms, and Holodeck
- Beepsky is back and he brought patrol Navbeacons
- More fire closets, cyborg chargers
- Travel through the space sorter is now somewhat safer due to shorter distances, and the sorter itself is now an enclosed "mini-station" with its own atmosphere
- Each station is now equipped with its own EVA with suits and space pods at shift start, allowing for transportation even if the Taxis at each ends of the station become sabotaged.
- R&D and RD re-united with the rest of science: makes oversight easier, and miners do not have to travel to a different station to make deliveries.
- All Civilian jobs (except Miner) have been reunited on Civilian/Engineering station
- So many subtle things: the bar has an entertainment telescreen for the thunderdome, there's a beepsky patrol route on sec station, the intercoms are now properly general intercoms instead of department-specific, telecoms is turret protected and has a gas sensor + computer, the stasis field projectors for xenoarch spawn on the roid instead of needing to clunkily take them on the shuttle and out the external doors, librarian gets his D&D table, engineering has a double-door to deter tail-gaters like every other map - a bunch of little quality of life things that might go unnoticed

**Comment by Probe1** [comment]
Now is as good of a time as any for a PR.  We can help and pull against it.

**Comment by ihadtoregisterforthis** [comment]
Remember to keep an eye on why is taxi like it is #1569. It surely changed a lot but there are some foundational reasons like

> Then I had to think about the individual rooms and where they should be placed, and I ran into the problem of "Why would anyone ever WANT to go to the sec station unless they enjoyed being beaten up?". 

Also since it's being made from the ground up you can avoid #5949 and other mapping issues

**Comment by Kurfursten** [comment]
Yes, one major change I want to make from any other map is that all scrubber pipes will be entirely on pipe layer 2, meaning they can stack with vents. In short, there is no need to pipe under walls at all. But this has been a slow crawl of design, I'll push it when it's a little closer to completion (in essence, when I don't know what else to fix), mainly because I'd rather avoid a bunch of server publicity until it's closer to done. As for the other thing, now that R&D is on security station, every department has an excuse to visit - but I take your point, and it is something to consider down the line. The dorms are on Sec Station: maybe they should be past the checkpoint instead of in the public sector?
- ~~Draw blueprints~~
- ~~Build rooms~~
- ~~Fill rooms with items and objects~~
- ~~Ensure all departments have proper lockers~~
- ~~Assign all areas and APCs~~
- ~~Fully working powernet~~
- ~~All rooms have lights~~
- ~~Working and fully tested disposals network~~
- ~~Total camera coverage giving preference to the less-snowflakey Autoname cameras~~
- ~~Complete distro loops~~
- ~~Complete scrubber loops~~
- ~~Working Taxis~~
- ~~Quality of life wall stuff~~ (~~Newscasters~~, ~~intercoms~~, ~~extinguishers~~, ~~requests consoles~~, ~~sound systems~~)
- ~~Firelocks~~ and ~~air alarms~~

I may need help with getting Taxis to work - the neo shuttle code remains enigmatic to me. I have one partially working but they have really been a bane for me. That can come after I finish atmos though. Here's a "real" image though: resolution is still bad and the whole bridge/cap office got cut off, but there will be a better image in the future. Already you can see the most important parts though.

I am pretty happy with where it is from a design standpoint - rooms and maintenance are generally larger and more habitable, plenty of stuff for assistants to get into when they get bored. The idea to put an EVA/Pod Bay on every station was not mine, it came from the thread, and I have to say it works really well, I am very happy with where that is at, although the map had to be designed with the common suits and pods in mind, so there are much less windows than other maps, especially to secure areas like perma.
![composite](https://cloud.githubusercontent.com/assets/9782036/12187056/0ed36ca6-b56e-11e5-8d3a-87a1ab5b959b.png)

**Comment by Kurfursten** [comment]
I've made a lot of progress over the week, as the many crossed-off items above indicate. I'm getting very close to a PR. What's left?
- Non-station shuttle docking positions (Vox raider ship, Nuke op ship, Pirate ship)
- ~~Every dir 2 (default) vent on the map is turned off. Need to replace all of those.~~
- While Taxis now move from station to station just fine, they seem to have weird atmos behaviors, sometimes failing to bring their air with them. Consult others on a fix?
- Take better screenshots and make a write-up of all the ways that this map (tentatively titled "Bus Station") is different than Taxi, the inspiration
- Test every door, the atmos loops, disposals/mail again, every single computer and machine that incorporates some sort of link up (I tested pretty extensively but there's only so much one person can do)

Most of these things could be helped with by other people after the PR goes up. When maps go live, they are traditionally unplayable trainwrecks (I am reminded of Taxi's debut), but I'd like to avoid that here. @Probe1 is the one who fixed a lot of Taxi's wires and pipes so I'd like him in particular to have a look over it, since I know he has a sharp eye (granted he used the render map).

**Comment by ihadtoregisterforthis** [comment]
Gee Bill, how come your mom let's you have **five** wide hallways?

**Comment by Kurfursten** [comment]
I think it works here (although it's really closer to two 2-wide hallways because of the placement of lockers, plants, and walls in the middle of the halls). Remember, the original Taxi boasts 4-wide halls, in a similar vein. The idea between two 2-wides was that people will be congregating in these halls a lot - more than box. The focus is on service windows that do not remove you from the main hallway - for instance, Cargo, Botany, Chemistry and R&D on Box have you move out of the flow of normal traffic to stand at the window, but Robotics and Mechanics have no such inlet - so you need to be able to get around people on both sides, 2-wide for each half of the hall.

I might trash it when it gets to the review step, really, because after playtesting the lockers get annoyingly shoved around and then they just get in the way. This seemed like the best solution for having lockers readily accessible everywhere, but that may not be worth the annoyance they cause. Here are two solutions I've considered:
- Add directional windows to the emergency O2 lockers so that they are not pushed around as easily, and keep the increased hall size for maneuvering
- Reduce hall size to 3 (similar to main halls on Box) but indent 1 in front of windows (like Botany on Box) so that people at windows are not in the way of passers by

Once I put up some better images (probably later today?) you'll be able to see a lot of things much more clearly (and I'm sure find some much more glaring issues that I glossed over)
