### ISSUE TITLE
Feature Request: Make the large artifact hover pod not worthless

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#6891]
Right now, if you get the hover pod as your large artifact, you feel pissed off at how totally worthless it is.

Its the slowest mecha in the game. Oh god a plantbro with magboots and a riot suit is faster than this thing.

It has no point.

For the effort in getting a large artifact, it should at least have some use over something made in a few mins in robotics.

SO WHY NOT MAKE IT BE BETTER?

Make it as fast as the Ody. and be able to move in space.
Now it is a space pod that can also move in the station, and only takes up 1x1 instead of 2x2.

Tada, I just fixed it. Now instead of having some lame pointless stupid piece of shit large artifact, you get a KICK ASS HOVER POD.

**Comment by PJB3005** [comment]
Gigadrill is definetly worse though, the hover pod has a LOT of health.

Oh and that crystal you can find LITERALLY has no code other than breaking into 1 glass shard.

**Comment by Exxion** [comment]
Yeah but people worship the crystal

**Comment by 9600bauds** [comment]
Does gigadrill even do anything?

**Comment by Probe1** [comment]
@9600bauds it's from pre-diamond drill times.  It's currently worse than the diamond drill.

**Comment by Probe1** [comment]
I can think of two nice options.

Easy option:  Make it the same speed as an oddy.  I used to do this when I bussed it in for people that prayed, except I made it phazon speed.  Since it has practically no attachments other than a clamp big whoop.

Harder option:  Copy and paste gygax code to make it faster and go really fast when toggled.

The core issue is its too fucking slow and does nothing that a spacepod doesn't, but even worse.

**Comment by clusterfack** [comment]
Someone make a better gigadrill sprite and an orange pulsating beam that can come out of it and we can make it an emitter that cuts through walls and asteroids. I think that is large artifact worthy.

**Comment by PJB3005** [comment]
@clusterfack actually, emitters were able to mine before @N3X15 moved emitters to constant BEAMS.

**Comment by clusterfack** [comment]
Also let it be unanchored and not requrie power for funsies

**Comment by FudgePucker** [comment]
A good way to make the crystals not worthless would perhaps make them into single primary effect large artifacts that are always activated by lasers (laser gun or emitter).
A simple easy to activate large artifact.

**Comment by FudgePucker** [comment]
Oh oh, and to separate it more from other artifacts maybe make it so that if shattered the glass shard has some interactions of the effects from the artifact itself, so that way you can stab people with the shard to heal them, throw the shard to charge a cyborg, or make an EMP spear to stab cyborgs with.

**Comment by FudgePucker** [comment]
Oh man artifact spears would be so cool, make death spears, make spears that cause your foes to go insane as they bleed to death, make spears that cause massive amounts of plasma and O2 to be produced as you murder everyone in an atmospheric rigsuit. It would be hard as fuck to implement but would be so fuckin rad.

**Comment by icantthinkofanameritenow** [comment]
Perhaps the hoverpod could also be customized with modules only it could use that could be dug up separately.

Maybe an infinite cell, or a mech plasma gun? (I know, plasma guns aren't that good but it was the first gun I could think of that might differentiate it from other mech guns. )

The idea of having crystal shards have the same effect of the full crystal doesn't sound too good since the exotic particle harvester already does something similar, but making them into single-effect artifacts with a consistent trigger could be helpful. Make them into baby's first artifact, if you will.

**Comment by Probe1** [comment]
Digging up a large artifact is already a big enough pain in the ass unless you're one of the few people who are great at it.  Having to dig up two seems like it adds insult to injury.

**Comment by icantthinkofanameritenow** [comment]
Alright, then how about it having those "artifact modules" already equipped on it then? If you have ideas for other doodads it might come with, list them.

**Comment by FudgePucker** [comment]
How about adding some modules that would benifit the xenoarch and make sense. A laser drill, that acts like human used diamond drill when moving into a astroid turf, but when clicking on one it acts like a containment field lets you set a precise dig distance, scans the material type, gives you the clearance of the next object, and laser precice measuring tape, the ultimate xenoarch tool. It makes sense because an alien civilisation was doing xenoarch there before you. A proto kinetic cannon that can shoot a spread shot of three normal kinetic shots side by side or one super one. It would make the hover pod into the ultimate mining mob killer due to goliaths resisting bullets.
An emergency teleporter that runs on a separate (alien recharging lower volume) battery that you can set a position then teleport back to. Set it to a mecha charger to ensure you don't get stranded.

That laser drill would allow you to dig out a site with out getting out of your mecha. It would turn the hover pod from a worthless large artifact into the best find you can get.

**Comment by icantthinkofanameritenow** [comment]
@FudgePacker

Something that would make it more useful for general purposes was more what I was thinking of- all that sounds good on paper, but outside of its specific niche it would still be mostly useless.

**Comment by FudgePucker** [comment]
@icantthinkofanameritenow 
Just the laser drill is job specific, the other two would be super useful and unobtainable otherwise. Also whats wrong with having an attachment that would let it be super useful to the job that has to dig it out?

The cannon would be able to blast away anything in space, if you also let the mecha fly in space like I said in OP, then it would let you just sit in comfort and blast away spacecarp and other critters, it would also let you ambush people in space and devastate the ever loving shit out of them.

The teleporter would give you a panic button, if your pod is at risk of being destroyed, it doesn't matter if you are low on energy or out of energy, you can just teleport away. How is a panic button a specific niche? Hard to kill someone in the pod if they can just teleport away across the station or to another zlevel and repair it.

'general purposes' is hard to describe. What would fill out 'general purposes'? Hell the emergency teleporter is more 'general purpose' than most of the other cyborg modules. Tell me one 'general purpose' module that isn't job specific or combat oriented.

What about a module that slowly recharges the battery no matter what? It is different from the telsa charger because it wouldn't need a powergrid to run off of.

Do you want more guns? What about a railgun, it would be able to shoot though walls like the sniper rifle, but would have more ammo and shoot faster.

**Comment by icantthinkofanameritenow** [comment]
@FudgePacker

By "general purposes", I meant something whose usefulness isn't limited to doing one thing that one job will appreciate but be useless everywhere else. The teleporter is a good example of that, but how would you set its location- with a tracking beacon? If so, what if there are no beacons it can lock in to? It would have to work like the station teleporter instead in being linked to predefined locations to warp to.

The railgun sounds good, if a bit low-tech for something with exotic and advanced technology otherwise. Would it be energy-based or bullet-based?

The proto-kinetic cannon's main flaw is that it's absolutely useless if you actually want to bring the mech onto the station, and the asteroid mobs can be slain with just about any laser weapon or even the drill easily enough. As you said, it'll be good in space- but only in space. That alone will cripple it, since how many enemies that genuinely need a mech to kill stay exclusively in space? It should be a module that a Ripley could take, perhaps- but that's a discussion for a different feature request. 

The auto charging battery is also good, though it's charge rate might need to be slightly worse than the Tesla's to compensate for the fact it can charge anywhere.

As for the laser drill, it just seems like it would totally trivialize xenoarchaeology. A module that automatically identifies, digs, and contains artifacts before you even know they're there just seems ridiculously unbalanced, and yet ironically it'll still break artifacts because the excavation mode doesn't toggle when it tries to move into a tile with an artifact in it.

**Comment by FudgePucker** [comment]
@icantthinkofanameritenow 
Maybe a button you press to set it then you can push it to go back there.
Simple and fast.
Rather than having to set it to an object (might cause nightmares and potential bugs with putting it in containers or destroying it.), you set it to a turf, and then it would be able to just jump back there at a push of the button.

The rail gun might be energy based, it is super advanced alien tech, so having it be just like our slug based railguns would be too low tech. Maybe it condenses some electrons into a super dense projectile using a partial accelerator and a fancy alien stasis field (or some shit) to hold them in place, then shoots it out of a magnetized barrel, the negative charge of the projectile increases how much force it goes against the positive charged magnetized barrel. The fact that the weapon would be able to make electrons into a solid projectile would possibly advance the technology of humanity at the time and you would get so many prizes and awards for discovering it, imagine batteries made out of PURE ENERGY, superior particle accelerators that are better than anything humanity has, in a much smaller size. Or you get it destroyed when you try to shoot the clown with it. Hot damn hire me to write all the lore for the technology. You will shit your pants when you see the ten pages I have on plasma.

EDIT: Here is a taste of some of my ideas on the potential of plasma. Due to the fact that plasma reacts with O2 to produce CO2, that means it is some type of super carbon compound that is unobtainable on earth, or producible with our level of technology. Imagine how easy it would be to mass produce carbon nanotubes with it? You would be able to make super lightweight and tough spaceship exteriors using them. Space elevators could become a reality and cheap with solid plasma. The diamonds on the asteroid aren't normal earth diamonds, they are plasma deposits that underwent extreme pressure for an extended period of time, meaning they have insane properties not fully understandable by science, maybe a reason why diamonds are needed for the bag of holding is because they are so dense it helps produce a miniature singularity to hold all the stuff.

Plasma is going to lead humanity to another level, and it is going to be leaded by nanotrasen, the syndicate is so hellbent on attacking nanotrasen for this reason, plasma is so valuable that who ever holds onto the location of it holds the location of the future of humanity. The reason why there are so many digsites of so many different alien cultures on the asteroid is because they too knew the endless potential of plasma, and set up mining locations there. They might have all gone extinct or moved to another part of the universe, who knows?

**Comment by icantthinkofanameritenow** [comment]
@Fudgepacker

I was asking about the railgun's damage type for more practical reasons- namely, that the strongest bullet-based mech gun is the Scattershot, which is mediocre at best. Adding a new bullet-based gun exclusively for its use would give the hoverpod something other combat mechs lack. Nice lore though, even if it'll be completely ignored by most people. 

As for the teleporter, I don't know code so I'm not sure how setting it to a turf would work- if that's even possible. And having it act as a "get out of robusting free" card might end up with it being OP; perhaps leave a portal briefly that someone could follow it through? Or a cooldown in between uses?

**Comment by FudgePucker** [comment]
@icantthinkofanameritenow 
Oh its projectile would just be a child of the sniper rifle, so bullet, but instead of having static ammo amounts have it use battery power. Unless you wanted to do something really fancy like have the field holding the electrons together hold together though inorganic material like walls and airlocks, but when hitting something living (mobs and players) the field disperses and the electrons scatter away from each other super fast fucking over everything in their path because they don't want to be by each other anymore, causing a miniature explosion in the target it hits.

Eh I don't know what the proper way to describe it, maybe just have it save a position to go back to? Just use the easiest and least fuckup way to have it save a position and be able to teleport to it. It is only for emergencies, not to keep setting every few seconds to backstep in a fire fight, so having a cool down between uses is what I had in mind (Low volume slow recharge but long life battery meant that it only had enough charge for one use before it had to recharge.). Who really cares about balance on one of the most luck based and complex job items? At least it isn't hulk.

**Comment by icantthinkofanameritenow** [comment]
@Fudgepacker
So the railgun would work like the Combine OICW then? That sounds about right to me. 

As for the teleporter, I was just trying to keep in mind how it might work in practice. I want this hoverpod to be badass, sure- but it shouldn't be able to just cheat death once every X minutes by warping to safety. I can imagine how that would be a gamebreaker- just think of any wizard who manages to save his bacon by teleporting out of reach. Giving that to a mech would be more than a little bit irritating if there wasn't a way to counter it.  Maybe this emergency teleporter needs to be made on a test server to see how potentially OP it really is instead of theorizing about it here.

**Comment by FudgePucker** [comment]
I mean isn't there a mecha teleport module right now? The single location was my way of balance instead of click anywhere to go there, the backup battery was to just make it unique.

Another really over powered idea I had that wouldn't work for balance outside of it being bus only. The sasis field on the railgun is one way, the electrons go in, but can't get out, even with magnetic power wanting it to be anywhere but in that field. What if we turned it inside out and surrounded the pod? It would reflect or bounce away bullets and lasers, totally nullifying damage to the pod. It would make the pod totally transparent due to no light reaching it, it however would give off a metallic sheen due to light not perfectly bending around the field. It would push out air around the pod creating a vacuum around it, meaning it could save you in extreme atmospheric situations. Their would be downsides to it however, you would be totally blind outside your bubble due to NOTHING getting though the shield, thermals, messons, everything, hell your radio even stops working and you are deaf to sound outside your safe bubble. You would still be able to fire out of it, so you aren't totally worthless. The pod would start to take damage with extended use due to the pull of the field trying to rip apart the outside wanting everything to get out.

**Comment by FudgePucker** [comment]
Also wizard phazing is a bad example because of the phazon, being able to do that. This pod requires xenoarch, a very complex job and you might not even find one due to the random nature of finding large artifacts. I can get phazon as a miner reliably every round by just finding the clownroid

**Comment by icantthinkofanameritenow** [comment]
@FudgePacker

I was referring more to the wizard's teleport spell rather than Ethereal Jaunt due to the whole "warp somewhere entirely different with no warning" thing. Being single location is fine, the catch is making sure it isn't set to somewhere that only the user will be able to find so a traitor who gets it can't just run the station ragged with hit and run attacks. 

For the stasis field, isn't that just a slightly tweaked Phazon phasing? The only real differences are the invisibility and being able to shoot at the expense of being blind and damaging itself. Again, you have to imagine how it works in practice, not just on paper. 

This is how I see it. 

Traitor digs up hoverpod, sets teleport location to the Derelict and builds a charging port there. As a scientist, he will have access to RnD and the circuit imprinters needed to do so. 

> Traitor flies off to the station, blowing shit up. After taking some damage, he warps back to his hidden base. Security has no way of tracing him. 
> 
> Traitor repairs the pod, returns to inflict more damage to the station. This repeats until they call the shuttle, he gets careless and had the hoverpod destroyed, or Security manages to find out where his hideout is. 

That's why I have misgivings about how this teleporter will work.

**Comment by FudgePucker** [comment]
Maybe limit it to zlevel then

**Comment by icantthinkofanameritenow** [comment]
Reasonable enough. That would ensure any such secret base would be found out eventually.

**Comment by FudgePucker** [comment]
Don't forget they would also need to make the base airtight and pressurized if they wanted to make repairs. It would also need an APC (Would show up so there is a way to check for their secret base) to have the exosuit charger if they wanted to recharge it, APCs being able to be checked.

Maybe also have the teleport make a unique loud sound, so that way if you try to have someplace hidden in maintenance, someone might overhear a very loud noise. Maybe also have it leave scorch marks on the ground of the teleport location, that way if you use it to keep running away, you might comeback one time to a pissed off mob armed with EMP grenades fire axes laser guns and ion rifles.

**Comment by Exxion** [comment]
#12288
