### ISSUE TITLE
New Species Idea: Nucleation (AKA Supermatter People)

### ISSUE THREAD

**Issue by icantthinkofanameritenow** [d3athrow/vgstation13#6937]
I got this from looking at another SS13 wiki. Given all the talk about race variety, I took a look at it and saw it might have potential for a race that plays genuinely differently. 

The lore (if anyone cares about it) is simple enough- they were humans exposed to supermatter radiation in a way that's causing them to start turning into supermatter themselves. 

Pros and cons from their origin server (feel free to modify)
+Can handle supermatter without being disintegrated, and also immune to hallucinations from supermatter.
+Do not breathe, feel pain, or catch viruses.
+Are healed by radiation.
-Chemicals of any type have no effect at all on them. Only radiation can heal them. 
-Cannot be cloned, use robotic limbs, or be put in MMIs.
-Increased vulnerability to all damage.
-Produces a small explosion on death, akin to a much weaker supermatter delamination. (Possibly modify it so it only produces radiation, as opposed to a breach?)

Posts >>124767531 and >124766426 have some potentially interesting mechanics that would make it into a form of "glass cannon", but I don't know how viable they might be. At the very least, I support the idea that suicides shouldn't trigger the death explosion for obvious reasons (read: shitters selecting nucleation, then blowing themselves up in arrivals or somewhere equally populated). Decapitation or using the gibber probably shouldn't do so either in my opinion. 

Anyway, if you guys have any further tweaks that could be done to make them playable I'm all ears. I also found a basic sprite for them, if that helps. (sprite is at http://wiki.apollo-community.org/index.php?title=File:Generic_nucleation.png)

**Comment by gbasood** [comment]
**no**

**Comment by 9600bauds** [comment]
c'mon now, I'm not one for the idea either but that type of comment doesn't help anyone

**Comment by FudgePucker** [comment]
I know it might be egotistical of me to take credit of anonymous comments, but I was the poster of those two comments. (It would be more egotistical of me to use a name. If I knew you were going to make a feature request I would have saved my ideas for it.)
I like the idea of a race that is very different than the other ones.
It would be a race that is very easy to kill, but also very hard to kill.

Maybe make the sprites more crystalline in nature rather than human sprites with chunks of shard sticking out of them.

I would play as this race instead of human if it was added. It would be another race of our own making (if implemented with the new ideas and sprites) instead of just ported from bay.

**Comment by gbasood** [comment]
@9600bauds Okay, well if you want me to give constructive criticism:
-  A mob that explodes on death is a bad idea in many ways. It punishes people trying to kill them (traitors) and rewards shitters (people who play this and kill themselves without the suicide verb, people want to suicide bomb, people who want to kill them to see them explode)
- The fact that they don't breathe means they would have a much easier time in space than any other race to the point of being ridiculous
- This is basically just a variation on the idea of plasmamen and that bothers me quite a bit. I'd rather see dumb organic or mechanical alien races than "dudes who are made of fire/plasma/unobtanium"

I will say I do like the idea of a fragile race who can't recieve the same medical treatment at all as other races, however. Maybe if it weren't attached to all these other variables.

**Comment by icantthinkofanameritenow** [comment]
Perhaps by reducing the death explosion to only a weak radiation release and disabling it entirely will curb the matter of the first issue, or as FudgePacker mentioned in his posts to make the explosion happen only under certain circumstances. (You might want to copypaste that here when the current thread dies, by the way.) As for the last one, perhaps we could tweak the sprite so it looks more like a vaguely humanoid supermatter crystal than anything else?

Breathing will be an issue, I'll give you that. Perhaps they can keep a weakness to pressure, which will still kill them.if they're spaced and leave them in a state of near-death if they can't find a source of radiation.

As I said, there's plenty of room for modification here.

**Comment by FudgePucker** [comment]
Eh make it so that they are super weak to high pressure (causes them to activate) and temperature. Space immunity is important for them because they need to be able to space themselves to cool down to regenerate.

No really, the concept of a player spacing themselves like they would a supermatter shard is just the most funny and great thought I have had all day.

**Comment by PJB3005** [comment]
For the record: this was made by @Zomgponies on paradise, IIRC.

And these were intended for events only.

**Comment by ZomgPonies** [comment]
Actually these were ported from....Atlas? Apollo? I forget.

**Comment by PJB3005** [comment]
Oh, whoops then.

**Comment by icantthinkofanameritenow** [comment]
Yes, it was Apollo I found it on. Although we do have room to tweak it, though.

**Comment by Ephx1** [comment]
Cousin of Plasmamen huh?

Not to say a crystalline race isn't cool. _cough_ Silicoids _cough_
But I stubbornly believe we need to work on our own races before we bother with new kinds.

Also I'm iffy about them being immune to supermatter, I suppose logically it makes sense, but we already have enough people dragging the supermatter through the halls with zero ways normal people can fend for themselves. Like silicons and their complete immunity to anything hot, or radioactive completely fucking over every living creature any chance they can. Even worse they're healed by the supermatter's main form of fuckery, radiation that mutates, knocks out, poisons, and in general kills at sanic speed.

If they are supermatter themselves, wouldn't they also destroy people/items on contact? They'd have to have a suit made out of whatever the supermatter shard sits atop. Unless they aren't fully supermatter, but it certainly looks like major parts of them are already crystalline. 

Lord almighty I can already see the absolute asspain coming from nuke ops shard men, not only would they explode, but give off radiation as well.

EDIT: Relating to radiation healing, as a way to stop them running about with the supermatter shard all willy-nilly, why not give them a short stun saying how their body stops to soak in the radiation? Logically radiation would only occur from either, Storms when everyone is inside, Uranium walls that are never made, Radio Transmitter, and Singulo/Supermatter. The only problem of which I could see, is a shardman falling sleepy as he's running away from the singularity.

**Comment by icantthinkofanameritenow** [comment]
Ephx1: The idea of a brief stun when exposed to radiation to trigger its healing effects on them makes sense to me, and radiation is the least of your worries if the singularity gets loose. That said, I always thought that dragging the supermatter without touching it should be impossible in the first place if you're not a silicon. 

The lore reason for why they don't disintegrate shit is because they have an organic covering over their supermatter deposits that keeps objects from being directly exposed to the supermatter on their bodies. Something about their flesh slowly changing into supermatter, or something like that.

**Comment by assdad211** [comment]
It would be very easy to powergayme with this race given radiation is beneficial for it and harmful for everyone else

Space immunity as well

If this is added, add it as a rare consequence of touching the supermatter crystal, or something from a xenoarchaeology large artifact, don't let it be a roundstart race

**Comment by icantthinkofanameritenow** [comment]
@assdad211

I'd be fine with that. Alternately, make it so they gain no benefits from eating given that they can't process chemicals- they'll be forced to use radiation in the place of food as well, which will further restrict what they can do.

**Comment by assdad211** [comment]
Its not hard to get irradiated, bolt a radio emitter down in your workplace and turn it on as needed

Or chug radium or something.

**Comment by icantthinkofanameritenow** [comment]
But where would you get the radium from? Chemistry barely remembers to give out shit not directly relating to medicine as it is.

**Comment by FudgePucker** [comment]
They would need an atmospheric rigsuit to drag around the shard to murder people. The shard producing heat would slowly kill them. 
If you are that worried make it so that when dragging the super matter they slowly activate to take damage. Meaning they can still work with super matter, just not drag it for extended periods of time.

Hell this race wouldn't be that over powered. There already is a race that has regeneration, toxin immunity, and radiation proof, all with just easily treated downsides.

**Comment by icantthinkofanameritenow** [comment]
@FudgePacker

Given that the posts I first linked to discussing the activation mechanic are gone now, can you remind us how the activation mechanic would function? Assuming it could be made to work in the code, I mean.

**Comment by FudgePucker** [comment]
@icantthinkofanameritenow 
No problem.
The whole gimmick behind it being a "glass cannon" is that as they take damage they get more energized.
As they take damage their heat increases, 'activating' them more, internal heat damages them, activating them more. They will slowly go supernova if they are not cooled down by fire extinguishers, space, or cyro. But as they activate, they gain powers. They get reduced stun time as they activate more, their punches deal more damage to other people because they stab them with shards this also damages and activates them some, as it activates that damage scales more both to themselves and the target, they are not slowed down by damage and will remain at full speed (Just like a dionia on hyperzine), and as they activate they glow brighter and brighter, a way to see that they are activated and you should turn on that fire extinguisher you were bashing it with before you get your shit kicked in. (also lets you know that a shitter is attacking itself with a glass shard in the middle of medbay to go boom)
The fact that they take continuous damage while they are activated is counter acted by them slowly regenerating when cooled down.
As they hit critical they have a chance to go super sayain if they are activated enough. A last wind for it before it goes boom.

They are very easy to kill, but dangerous when backed into a corner.

**Comment by Arthurdentist** [comment]
Nucleations were originally made by @Kwask , if people actually wanted them here in whatever form I am sure he wouldn't mind

**Comment by Kwask** [comment]
Not one bit, though if you skip out on [the cool burst they do when they die](https://drive.google.com/file/d/0B9LNmHO_PasjMnYxNWFDYWRBT00/view?usp=sharing), I'd be sad

Another mechanic that was important to this race's inclusion was that supermatter explosions sent out a massive wave [like this](https://drive.google.com/file/d/0B9LNmHO_PasjSmFnVkFTWFkyeE0/view?usp=sharing) which would have a chance to turn humans into nucleations.

**Comment by Ephx1** [comment]
Neat, are those green shards radioactive?

**Comment by FudgePucker** [comment]
@Kwaks
That looks fucking awesome. I think everyone is just mostly against the idea of players using it to grief. I don't think it would be that bad as long as it doesn't breach the hull. They would only do it once and then everyone just takes an antitoxin pill and a kermderm pill and move on.

If we are against the idea of there being another 'WHAT HAS SCIENCE DONE?' race alongside plasma man, maybe instead (LORE WARNING) they are a strange race born in stars with super matter cores. They are like sentient gas creatures that talk together telepathically across the star. They attempted to communicate with any other beings across the universe by using solar flairs, to see if they are alone. NT saw strange flares from a star containing plasma and decided to investigate.
Outside of the star they condence into a crystal bipedal humanoid, although if this form is too damaged they return to their original state. For this reason some other employees report that they seem fearless of death and rash, their death isn't the end for them, their conconsness will find its way home, or colonize a new star. They however respect the fact that other races are locked into their mushy weak bodys, and feel obligated to put themselves in danger most of the time because of this fact. Hot and high pressures still damage them because it causes the crystal nature of their bodies start adapting back to their original habitat, stars.

I will make a shitty ms paint artwork of what they look like.

**Comment by Kwask** [comment]
@Ephx1 Yup, and they also slowly spread through walls over time

@FudgePucker Yeah, on our server we whitelisted the race so people wouldn't griff with it, so I can understand the hesitation. Lorewise on our server, supermatter releases radiation that transforms normal matter into supermatter. Therefore, nucleations were usually veteran engineers or people who were unforuante enough to get caught up in a supermatter core explosion.

**Comment by FudgePucker** [comment]
@Kwask I know the lore from reading the wiki page. The main problem with that lore is that we already have a 'horribly mutated from working on a space station' race, plasma men, only with plasma(phoron or what other name bay uses instead of plasma) instead of super matter.

**Comment by Ephx1** [comment]
> If we are against the idea of there being another 'WHAT HAS SCIENCE DONE?' 

Nah I love those, I just think these have high griff potential.
And, well, like I said, I think we need to work on our own races before another one is implemented.

Right now we have only really one major played race aside from humans, Vox. Plasmamen and Greys are kind of left to wither, and Dionae are usually regulated to the kind grown in botany which isn't too bad.
