### ISSUE TITLE
Security Cell Timer Feature Request

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#6942]
Hello. I think this would make Security a lot more FUN. I hate not coding at all, but I am lazy and these ideas just float in. Anywho, keep Cell Timers as they are, being able to add time and etc however:

If we could add a Space Law Calculator, that would be most excellent. By this I mean

---

[Add time buttons] --- Label this as a Custom, however adding custom requires a reason, then you just type in the minutes and seconds into a box, to allow for a record of why they were imprisoned.

[Sparking a Manhunt button] --- does not mention the time added, just adds the time (five minutes)

[Sabotage] --- Same as above (eight minutes)

---

So say a criminal sabotaged something, got caught, and sparked a manhunt. You hit both those buttons and 13 minutes queues up in the timer. Impersonal, efficient, no need to memorize every single law, etc.

And so on with all the crimes. Now, with crimes such as Murder, the penalty is Perma, Cyborgization, or Execution. Add the buttons, but have an error asking them to consult space law, Head of Sec, Captain, etc etc, or just an explanation that only those options exist under Space Law.

---

Also there are modifiers which exist but are not utilized very often. 

 One of these is Recidivism, basically, repeating a crime for which you are a previous offender. Each time you return for said offense, 3 minutes is added on top of the crime: No one does this. As a function of the cell timer, would it be possible to have the Cell auto add a crime history for each crew member entered(Don't do it from the manifest, because that's bad for Nuke Ops)?

The other modifiers are all positive ones, you could have these as a second pop up screen after setting all the crimes. So going with the above scenario, someone has committed 13 minutes of crime, mainly Surrender and Cooperating(the rest are grounds for release).

All those modifiers do is cut the time down by a percentage.

Anyway, feel free to discuss, it's just an idea I had. If someone loves this idea so much they immediately want to work on it, try to hold off on it a bit. We're doing an admin review of Space Slaw for the moment.

**Comment by PJB3005** [comment]
Sounds like a good idea to me, it'd also be nice if there was an easier way for people whose time finished to leave security without needing the AI / a security member to open 2 doors for them.

**Comment by Shadowmech88** [comment]
Personally, I think it would be better for Security officers to just learn Space Law. They can even carry a book on them if they need to, at least four spawn in Security every shift.

**Comment by nuklearcellphoneg** [comment]
I think that having a list of the crimes available in the Cell Timer window would not only make things easier, it would also reinforce retaining knowledge of Space Law, as they would have to dive over the list time and time again, leading to a little event of, 'Oh right they're breaking that law I always see'

The problem is two fold. Someone might give excessive punishment to a player because of ignorance of Space Law, while the punished player doesn't notice because they themselves don't know Space Law.

I know a lot of stressed newbies that just put everyone in the cell for three minutes and move on. Further, someone may not like someone and give them more time 4 no raisin. Finally, the knowledge of space law is largely pedantic. While everyone can readily recognize a crime has been committed(stealing, assault, murder, etc), the punishment is more often the bit that's not paid attention to.

While memorizing chemistry is rewarding, and the same with constructing things, science, etc etc, it's not so much with Security.

Really, it would probably be more rewarding to feign ignorance to keep someone locked up whom, which is something quite easy to get away with to an extent.

**Comment by ghost** [comment]
Makes sense to me. I'd code it but I'm doing snow shite.

**Comment by Cyadox** [comment]
I think it's a great idea, having played Sec on and off myself. Half the time I just delegate to the warden or someone else because it'd take too long to look up the crime in question and deduce a suitable time - and usually by the time I'm done they could've already served the sentence.

 It'll also help when writing up the person's criminal log because then you can just use that list; and who's to say we shouldn't add that to the criminal record system too? We already have a pop-up for criminal status, why not both?

I don't feel that we should add superfluous buttons that notify the need of Captain/HOS/HOP intervention because it should be fairly obvious when they're not on the list of punishments, and you REALLY gotta fuck up to be executed, or a tator.

It'd also be handy if it automatically adds those crimes to their criminal record, though I imagine it'd be hard to pass that information along to the criminal database.

**Comment by Kurfursten** [comment]
All this and more are underway.

**Comment by nuklearcellphoneg** [comment]
As far as the review of Space Law goes, no one has really piped up about it so I'll likely not be removing any laws(With the exception of 'Suspicious Behavior' which has no punishment outside of the search).

Anyway, I might add a law or two, such as Manslaughter for when someone accidentally kills someone.

As a side note, I was thinking a feature or two might also be neat to tack on.

Adding a sentence to someone requiring them to be matched up with a name on the crew manifest, and from there

-add the crime to their history
-if set to arrest, set status to imprisoned
-upon release, set to release

I was also thinking that if it auto sent an alert via PDA to the relevant head for the criminal's department and the HoS, that would be neato.

**Comment by Kurfursten** [comment]
Yeah, that's how I have it set up. I'm not sure about doing the PDA thing because that might be annoying, but here's how I have it working right now:

> You can't even close the door without setting an inmate, which is selected from a list of humans set to arrest in a short range (meaning you can't imprison unless you first set them to arrest with your sunglasses or sec records)
> Switches their status from arrest to incarcerated + updates their records with a list of everything you added to their sentence (you can't add the same crime twice for the same sentence)
> If the timer expires and they are within range, it sets them to released automatically

Also you can set which windoor and flasher it is associated with by multitool. I'm about half done with this, plus testing after that.

**Comment by Kurfursten** [comment]
More to the point, writing up these sentences, are most of them even necessary? Do we need a separate pickpocketing law when it's either just a theft or they're valid because pickpocket gloves? Cleanup might be wise considering it eats up space on the UI. I don't play a lot of sec, but I know it's rare for sec officers to waste their time on "minor crimes", so here's my pitch for a cleanup:
- Keep: Suspicious Behavior, and anything that doesn't use the timer (murder, enemy of corp, escaping life sentence, grand sabotage)
- Petty Hooliganism (3 Minutes): This is a merger of misuse of radio, vandalism, petty theft, petty trespass, petty assault, petty B&E
- Sparking a Manhunt (5 Minutes): Combines the existing manhunt, resisting arrest, and escaping from brig
- Nonviolent Misdemeanor (5 Minutes w/ possible demotion): Poss. contraband, drugging others, theft, trespass, creation of workplace hazard, insubordination, sabotage, B&E restricted area, framing
- Violent Misdemeanor (8 Minutes): Poss. makeshift weapon, poss. weapon, poss. IED, assault
- Impeding Justice (10 Minutes): Assault on officer, interfering with arrest, freeing prisoners from brig, de-implanting
- Misc Felony (10 Minutes w/ Demotion): Unlawful AI upload, unlawful combat gear construction, abuse of power, major trespass, major B&E, grand theft, poss. non-IED explosive

Besides taking up less space and being easier to remember, I think this also helps alleviate the problem where previously someone who breaks into robotics and steals a flash is doing more time than a bartender who uses lethal rounds on a botanist but doesn't finish him off (because those minor offenses quickly add up to more than one major offense)

**Comment by Shadowmech88** [comment]
> because those minor offenses quickly add up to more than one major offense

So consecutive charges are not going to be applied under the new system? If a person commits vandalism, petty theft, petty trespass, petty assault, and petty B&E all in one go, they still only get three minutes?

**Comment by Kurfursten** [comment]
How often do you see someone arrested for petty theft? Do you carry out minor crimes charges? I've never seen you do it when you static name. Like for instance, I am pretty sure I have welded/wrenched (the table) into the kitchen and stolen food from the smart fridge right in front of you with no punishment at all.

That's petty trespass, petty B&E, petty theft, and vandalism all in one go arguably (although another problem with all these laws is the overlap between B&E and vandalism, trespass with B&E, etc.) So the question is, if someone does that - all those minor crimes for a non-secure area, even all at once, do they NEED more than 3 minutes? Should they get 12 minutes while the guy who attacks a sec officer only gets 10? Remember: petty B&E, trespass, and theft are all for inane non-secure areas and items. It's not like breaking into the armory.

> consecutive

You mean concurrent, right? Consecutive would be if they got arrested and then did it again - I'm all for increasing their timer over that, and I can build it into the calculation by pulling their records.

Also worth mentioning: There **will** be a custom time button. I would hate to take away that ability from sec officers.

**Comment by Shadowmech88** [comment]
I haven't played in a while.
But as far as I can remember, when I mained HoS, I arrested for all crimes that were in the book unless the crime was both harmless and had good reason (for example deconstructing a table to get food when there's no chef to make it). Outside of that, I've personally made arrests for every minor crime, except maybe forcefully drugging due to how uncommon it is.

I suppose it makes sense to group some crimes together, but it should be based on the crimes themselves rather than the level of severity of the crime. For example, someone who breaks a window to get into a restricted area wouldn't be charged with both vandalism and B&E, however someone who commits both B&E and assault should be charged for both crimes, since they're unrelated beyond being at the same level of severity.

I think that, yes, if someone breaks into Robotics, beats up the roboticist, and steals a flash, they should receive 11 minutes while someone who attacks an officer receives 10.

As far as trespass vs vandalism vs B&E, I feel that vandalism should be the basic crime covering destruction of station property such as machinery, walls, and windows. If vandalism is committed in order to gain access to an area, the charge should be B&E instead of vandalism. It seems best to reserve the trespassing charge for people who gain access to restricted areas without committing vandalism, IE tailgating, unscrewing/rotating windows, ordering a silicon to let them in, et cetera. Otherwise every B&E charge would result in a trespassing charge.

**Comment by Kurfursten** [comment]
Robotics isn't a petty trespass area though, nor is a flash a petty theft item. Also, you didn't count poss. weapon for stealing flash and it is specifically mentioned in that law. What you're describing is B&E of a Restricted Area (10 minutes) + Assault (6 minutes) + Theft (6 minutes) + Possession of a Weapon (7 Minutes) = 29 minutes (wew lad, that's not even adding extra by counting 'Trespassing' and 'Vandalism' as well like the first calculation)

**Comment by Shadowmech88** [comment]
When you put it like that, it is a lot.
However, using the groupings you posted earlier, the same crime would be two nonviolent misdemeanors (10 minutes) and two violent misdemeanors (16 minutes) which is still 26 minutes.

If you only charged them once per category, it'd just be a 13 minute sentence, which may seem a little better. The problem with the practice of charging once per category is that it means someone who breaks into the captain's office, steals the captain's ID, and uses it to bring the AI under their direct control, is still only sentenced to 10 minutes since they all fall under misc. felony.

I'm not quite sure which system would be the best, but they all have flaws.

**Comment by Kurfursten** [comment]
If they one-human the AI that's grand sabotage (the grand sabotage wording makes this explicit), sentence becomes death. I definitely think we should keep all the laws that don't relate to timers, as I said originally.

Now, a more realistic situation to your point would be if the clown breaks into the cap's office, steals the cap's ID and uses it to make the AI say honk at the end of every sentence - only ten minutes. Not as outrageous but I see where you're coming from.

**Comment by nuklearcellphoneg** [comment]
Oh boy, this is part of why I wanted to have a more open discussion about law in general among the players and the admins about Space Law.

Typically I think you see about three different ways officers tend to use the timers:

1) Criminal is 'not so bad' - 3 minutes ish
2) Criminal did 'a lot' - 10 minutes
3) Criminal did something worth Perma/Execution, OR keeps being brigged over and over(or just plain hassling security), OR the Officer hates the character in a Meta(round to round they've noticed they grey tide) way, upping their timer from time to time, torturing them, repeatedly interrogating them, etc etc

'I suppose it makes sense to group some crimes together, but it should be based on the crimes themselves rather than the level of severity of the crime.' I dunno much about Git, I dunno how to quote. :( Shadow said this

I agree with this above; grouping the laws is something I mentioned on http://ss13.pomf.se/forum/viewtopic.php?f=4&t=2232

---

'D) Finally, after all this, I'm going to categorize the laws by their type(not sure exactly how, but as a general idea: 

Thief stuff: Pickpocketing, Petty Theft, Grand Theft, Trespassing. 

Structure Damage: Breaking and Entering, Grand Sabotage, Sabotage. 

Violence: Assault, Murder, Drugging Others).'

---

You're right about pickpocketing... it's very rare that this gets applied- how often does one even successfully pickpocket(outside of the glove which don't notify with a message, but your item clearly disappears from the UI) someone to be able to apply that? Further, if someone successfully pickpockets another... then they likely wouldn't know it occurred.

I think we should find a decent way to categorize the crimes(Stealing, Property Damage, Violence...) and when you open the timer window, picking the category reveals the crimes listed from the lowest to highest in terms of time.

So I guess I still need to clean up Space Law a bit, but really simplify it in terms of, rather than having a separate law for pickpocketing, stealing, yadda yadda, have it go

Stealing:
   From a lowest crew: 1 minute
   From a Head: 3 minutes
   From a Captain: 6 minutes
      Value of Object
         Common:1 minute
         Rare: 3 minutes
         Very Rare/Extremely Complex: 6 minutes

So, if you steal  the Captain's Spare ID, which is one of a kind, 12 minutes

If you steal the Clown's horn, 7 minutes

If you steal Metal from the CE, 4 minutes.

Etc etc etc etc.

**Comment by Shadowmech88** [comment]
Sounds like a decent system.
However I'd recommend going VERY in-depth on which items fall under which categories at some point.
Vagueness is the worst thing to have in a law system.

**Comment by nuklearcellphoneg** [comment]
Right, I know. The same already goes for Grand Theft, which doesn't really include all the items which really count for it. It might be better to have a rigid system for what defines an item being in a category.

**Comment by Kurfursten** [comment]
I don't really care which system gets used as long as the number of actual crimes listed gets reduced significantly. It will make a big difference in UI clutter. Organizing by crime type might work, but the way you put it seems like it might... A) Produce even MORE charges (now we need NINE different types of stealing charges?) B) Unstandardize the law.

It was one thing to have petty theft and grand theft but introducing so much complexity in sentencing seems like it will make it unclear to people just how much time they 'deserve' and leave Space Law up to more interpretation. We need to be eliminating bloat, not adding it. Otherwise, just do away with Space Law and say "Give the criminal what you feel like is appropriate for their rank and what they did."

**Comment by nuklearcellphoneg** [comment]
AHHHHHHHHHHHHHHHHH

**Comment by Probe1** [comment]
reeeeeeeeeeeeeeeeeeeee
