### ISSUE TITLE
/emergency_oxygen tank stops working when filled to max capacity (1013kPa)

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6945]
Fill it up, put on your mask, die of suffocation.

**Comment by ghost** [comment]
Tested this, couldn't replicate. Did you have your mask toggled?

**Comment by Probe1** [comment]
yes.  the bugs been around for like 6 months.  I should have stipulated that I used the small blue tank from my internals box and emptied it first.

**Comment by clusterfack** [comment]
Did you VV the gas datum to see agar was up?

**Comment by Probe1** [comment]
agar?

**Comment by Zth--** [comment]
This has been like this since forever and I always thought it was on purpose. It has sense, emergency ox tanks shouldn't be refillable

**Comment by Probe1** [comment]
Then make them un-refillable.  If you set the oxygen canister to 1012kPa its fine.  It only fucks up hard when you set it to 1013kPa (max)

**Comment by clusterfack** [comment]
*What was up

**Comment by Probe1** [comment]
Oh no I was busy fighting a blob then rage posting an issue that i've ignored for six months after I died.  

Shouldn't be hard to reproduce just drain an internal tank and fill it to max.

**Comment by clusterfack** [comment]
That's assuming of course it does happen every time

**Comment by gbasood** [comment]
It happens reliably by filling any emergency tank from an air canister up to 1013 kPa.

**Comment by clusterfack** [comment]
Neither celt nor I can reproduce this

**Comment by SysadminJeroen** [comment]
I have also filled up my emergency oxygen tank multiple times and haven't encountered this bug even once.

**Comment by SysadminJeroen** [comment]
I think that I may know what the problem is, as far as I am aware about @gbasood's problem, this is not a bug.
Now I know why I have never encountered the bug.

As you have stated, you have refilled the emergency oxygen tank using the white air canister, there is your problem.
You should have refilled it using the blue oxygen canisters.
The blue oxygen canisters are 100% pure O2.
In the meanwhile, the white air canisters are 1/5 gasmix of O2 and N2.
You need 16 kPa oxygen to breathe, the normal 1/5 gasmix of O2 and N2 at 101.3 kPa is sufficient to breathe. The emergency oxygen tanks are set to 21 kPa and by default contain pure oxygen.

Protip: You can also set all oxygen tanks to 16 kPa to save your precious oxygen.

Additional data.

An emergency oxygen tank comes by default with 303 kPa O2 and the mask release pressure is 21 pKa.
If you fill up the emergency oxygen tank with the white air canister you'll get approximately these results:

```
Pressure: 1013.2 kPa
 Nitrogen: 0.5 mol, 55%
 Oxygen: 0.4 mol, 44%
 Temperature: 20°C
```

If you were to leave the mask release pressure of the emergency oxygen tank at the default 21 kPa, you wouldn't get enough oxygen, so if you were to fill it up using the white canisters you'd have to set the mask release pressure significantly higher to compensate for the N2.

**Comment by Intigracy** [comment]
haha probe refilled his oxygen with air hahahahahaha

but seriously to breathe air it's like way higher kpa than 16

**Comment by SysadminJeroen** [comment]
@Intigracy pretty much.
