### ISSUE TITLE
Telekinesis does not work on Air Alarms

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#6964]
Oversight, just no response when clicking them from a range.

Telekinesis lets you use other machines, APCs, computers, etc. from a distance

**Comment by FudgePucker** [comment]
I fucking hate telekinesis.
Last time I played chemist I had to wait for chemistry to be fixed because one of the machines blew up.
When I started making basic meds because the fridge was empty I saw 20u potassium pop up in the beaker then I went into crit.

Was it a malf AI trying to prevent me from making thermite?
Ha
HAHA
HAAHAHAHAHAHAHA

IT WAS SOME CHUCKLE FUCK OF A GENETICIST, WHO HAD DONE IT TWICE, IN THE SAME ROUND.
FUCKING BULLSHIT MOTHER FUCKER ONLY GOT A DAY BAN, FOR DOING THAT, TWICE, IN THE SAME FUCKING ROUND.
TRIED TO GET AROUND IT BECAUSE IT DIDN'T LEAVE A FINGER PRINT, ABUSING THE LOG SYSTEM.
TWICE.
IN THE SAME ROUND.

HOLY SHIT BOTH GENETICISTS GOT DAY BANS FOR BEING SHIT, IN THE SAME ROUND.

YOU KNOW WHAT, FUCK GENETICISTS, I KNOW THAT I AM BREAKING MY SHIFT BUTTON AND ONLY HAVE ANECDOTAL EVIDENCE, BUT HOLY SHIT, I CAN'T COUNT THE NUMBER OF BAD EXPERIENCES I HAVE HAD WITH SHITTY GENETICIST PLAYERS, I HAVE HAD ZERO GOOD ONES.

How to fix this bug.
Remove genetics.

**Comment by assdad211** [comment]
Make it so I can fart on people with telekinesis somehow

I urge the farts out of their ass with my mind, and direct it into their face.

**Comment by Kurfursten** [comment]
Thanks for those relevant replies

**Comment by FudgePucker** [comment]
Okay serious reply time.
When a silicon clicks on an air alarm from range it autologs in for them.
Maybe it has something to do with that.
Also NanoUI fuckery as well, this is all just one giant storm of shit.
the best solution would obviously be ~~REMOVE GENETICS~~ find out what is different with air alarms and other machines.

**Comment by PJB3005** [comment]
Wait, x-ray DOESN'T LEAVE HIDDENPRINTS?

HOW HAS THIS NOT BEEN NOTICED FOR THIS LONG.

Also, I think air alarms have stupid snowflake code to make sure the person is in range, same issue occurs for adminghosts.
