### ISSUE TITLE
Ghosts touching the lights on the DJ sat resets the song playing from the beginning

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6997]
(WEB REPORT BY: alone REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 2aa83849b5200ca84f5691a76ed625ee7db65cec
> 
> General description of the issue
> Song resets if the light switches on the DJ sat are turned off/on
> 
> What you expected to happen
> just the lights turning off/on the DJ Sat
> 
> What actually happened
> The song kept resetting itself to the beginning when the lights were touched by a ghost
> 
> Steps to reproduce if possible
> turn on jukebox on the DJ Sat
> turn the lights off/on
> song playing resets itself

**Comment by clusterfack** [comment]
That's a joke right, there's no way that would actually work

**Comment by PJB3005** [comment]
@clusterfack actually...

Because power / APC code is shit, toggling the light switch causes a `power_change()` on _all_ channels (same goes for disabling a channel in the APC, all others still get `power_change()` called for some retarded reason).

My guess is that the jukebox resets when it gets a `power_change()`.

**Comment by Ephx1** [comment]
This does happen, tested on the bar as a ghost with juke on.

**Comment by Zth--** [comment]
Is this still relevant? I don't think so

**Comment by Exxion** [comment]
I am 100% entirely certain that this doesn't happen anymore

Well... almost
