### ISSUE TITLE
Liberian traitor gets round start bombs

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#7014]
This is fucking stupid.
REALLY FUCKING STUPID.
LIKE HOLY SHIT TWO ROUNDS IN A ROW WE CAN'T GO TEN MINS WITHOUT EVERYTHING GETTING BOMBED STUPID.
ITS FUCKING IMBALANCED TO HELL AND BACK.

Remove D20.

**Comment by ghost** [comment]
Change d20 to 7 TCs.

**Comment by 9600bauds** [comment]
Idunno, they only get two bombs in exchange for most of their TCs and they aren't guaranteed to be big. You can get INFINITE bombs with just an Emag.

Also consider the fact that Librarians don't get roundstart access to pretty much anything.

**Comment by Kurfursten** [comment]
If your problem is with ten minutes, I hope you realize a good scientist can make three bombcap TTV bombs and telescience them to medbay, the brig, and the cap's office within 10 minutes. At the cost of 0TC.

I don't see a problem with the item itself. The librarian has one of the smallest kits available to them in terms of access, having a strong traitor item is GOOD game design. And remember, the same chance that they get to ignore bombcap (5%) is used for the chance that they will gib with no explosion (5%).

**Comment by Arthurdentist** [comment]
You are forgetting that (in theory) a scientist has to know what he is doing to get his three bomb cap bombs.

traitor librarian currently just has to get lucky.

**Comment by FudgePucker** [comment]
@Kurfursten 
I don't think you understand.
Round start EVERYTHING IS BLOWN THE FUCK UP.

ROUND
START
BOMBS

> B-but muh cuban pete

They can bomb primary hallway and brig before you can even beat cuban pete half way

> B-but muh toxins

You have to know toxins.

**Comment by Kurfursten** [comment]
Traitor scientist not only has bombs he can count on to not kill him / not be a tiny little 2dev, but also can teleport them where he wants with no risk to himself. And if you just want fast destruction, the engineer can simply set up a singulo without the upper containment and force the singulo on a destruction path toward the center of the station, 3 minutes in. The librarian is a difficult role to traitor for, with limited access or reason to be anywhere. We've had the e20 for a long time now, and this isn't the first time it has been used. This seems like a knee-jerk reaction to suddenly push for its removal because a traitor item killed people.

**Comment by 9600bauds** [comment]
/tg/ has a tag for these kind of issues, "i ded"

**Comment by FudgePucker** [comment]
Two rounds in a row it ended super fast, just because lamo unlock PDA and throw dice at brig and main hallway.

Its really silly.
For singloose you can't get caught by the rest of the engineering team.

I am not over exaggerating how fucking fast we went from round start to shuttle call, getting round start bombs is stupid outside of nukeops.

Liberian not having an easy time getting green text by using a broken traitor item is pretty irrelevant, when its ROUND START BOMBS.
Someone just welderbombing at the start of the round is enough to make you want to suicide succumb, this is shuttle call roundstart, no fuck you you aren't going to do anything this round this round is over.
Two rounds ended so fucking fast that the time waiting for the next round was longer than the round itself.

**Comment by ihadtoregisterforthis** [comment]
There's a certain bundle that comes with max cap bombs, also available at roundstart from a traitor PDA, if you are lucky.
Nuke Ops start with a bunch of bombs at roundstart, and easily the main reason why Nuke Ops rounds end really fast too. Also antags.

And in a way you are exaggerating, those rounds lasted half an hour at least, and not ten minutes.

**Comment by Intigracy** [comment]
Can we close this one?

I lost pls nerf.

**Comment by clusterfack** [comment]
Yeah to be honest I've seen people do the same thing with cuban pete bombs and these have a 5% chance to gib you each time you roll them anyway

**Comment by Intigracy** [comment]
RIP Liberian traitors.
