### ISSUE TITLE
If a ghost touches hyperspace, it will never again move upwards

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7017]
It is only forced downwards while in hyperspace, but it can only move sideways and downwards forever after touching it.

@clusterfack I think

**Comment by clusterfack** [comment]
Why ping me?

**Comment by Exxion** [comment]
This didn't happen last time I tried it
You are the only person I know changed hyperspace at all in the intervening time

**Comment by clusterfack** [comment]
Ha, I only modified changeturf so no.

**Comment by Exxion** [comment]
OK so now the question is
What the fuck?

**Comment by clusterfack** [comment]
Either way I can't reproduce this

**Comment by Exxion** [comment]
OK, I figured out the specific circumstances in which this happens
If a ghost is pulled downward by hyperspace but stopped by hitting a wall, it forever behaves as if it were touching hyperspace in all ways except being forcibly moved down. The same presumably happens for all other directions.

**Comment by ghost** [comment]
dang it this is my favourite bug I love messing around with it

**Comment by Exxion** [comment]
And now ghosts ARE forced in the movement direction even after leaving hyperspace unless they have something dense to hold onto

**Comment by Shadowmech88** [comment]
I tried entering hyperspace as a ghost just now, and was not moved at all until I manually crossed back into regular space, which teleported me to another Z-level.
Unless there's something special about entering hyperspace from a ship as a ghost instead of just jumping inside the hyperspace area, it seems this no longer exists.

**Comment by Exxion** [comment]
It does still exist, but it was kind of a shitty report.
But yes, there is a difference between moving into hyperspace from a ship and jumping into it, since hyperspace is shitcode
Also this only happens if you move out of the ship and back in. It doesn't apply if you hit the edge of hyperspace and get warped to another Z-level. That resets it.

**Comment by Shadowmech88** [comment]
What if hyperspace just didn't move ghosts at all? It teleports them when they leave it anyway, and making it ignore ghosts would probably be easier than messing with how it restricts their movement.

**Comment by Exxion** [comment]
Probably a good plan.

Before you go looking for where hyperspace moves things in the code: It doesn't. There are invisible thrower objects around the shuttles. That's why it doesn't happen when you jump in, and what I meant by shitcode. Should still be easy to fix if you look in the right place though.

**Comment by Shadowmech88** [comment]
Are you *sure* it still happens? Because in the process of riding the shuttle so I could see the turfs with the throwers to find their path, I decided to test hyperspace as a ghost again. As both an adminghost, and a regular ghost produced via the mask of the phantom, I simply walked from the ship into hyperspace, and it didn't move me at all. I was completely free to move from the ship into hyperspace and back as I pleased, and my movement was never changed or restricted.

**Comment by Exxion** [comment]
It certainly did fairly recently, but I haven't checked in the *very* recent past

**Comment by Shadowmech88** [comment]
In fact, the thrower object even seems to already specifically exclude observers.
![image](https://user-images.githubusercontent.com/3991927/46564428-cba0d980-c8cc-11e8-9c96-0bf0627ca2b8.png)

**Comment by Exxion** [comment]
Yeah then this was probably fixed sometime since I last saw it

**Comment by Exxion** [comment]
Yep
#17265
I thought I'd tried it more recently than that, but apparently not
