### ISSUE TITLE
PLEASE FOR THE LOVE OF ALL THAT IS OR COULD EVER BE CONSIDERED AT ALL HOLY, WHY, BAUDS, WHY???

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7020]
Plants can now contain advanced mutation toxin, previously only available from end-tier slimes and only one unit at a time.
The chef cooked with some plants the botanist grew from his _early round_ exotic seeds and ended up making several foods _each_ containing **_TEN FUCKING UNITS_** of advanced mutation toxin
Several people took bites and were slimed

@9600bauds 
IT TURNS PEOPLE INTO SLIMES
Not slime people
_SLIMES_
Maybe _don't_ include it in seeds you can just buy from cargo

Yes, the botanist should have checked before growing the plants, but still
This would be WAY too powerful for an antag botanist
_ONE UNIT_ will turn someone into a slime

**Comment by FudgePucker** [comment]
Oh god.
!PANIC!

**Comment by Exxion** [comment]
[Honk] [OH GOD IT'S LOOSE] [Balance]

**Comment by ghost** [comment]
This has nothing to do with new botany. They always had advanced mutation toxin as a possible chem in random seeds.

Not a bug or a change.

**Comment by Exxion** [comment]
Jesus fuck are you serious?
Well then sorry bauds

Still fucking absurd though

**Comment by ghost** [comment]
Yes I'm serious.

> cooking food from exotic plants

**Comment by ghost** [comment]
So I double checked, exotic seeds have always since before being ported from baystation had advanced mutation toxin. Even baystation still has it https://github.com/Baystation12/Baystation12/blob/master/code/modules/hydroponics/seed.dm

The only problem I see with sliming is that it's permanent, you should make a feature request for turning slimes into monkeys or humans.

**Comment by Imagebard** [comment]
Remember the "working as intended" label too.

**Comment by 9600bauds** [comment]
henk
AFAIK it was ALWAYS a thing, just that it used to not work at all until it was fixed a couple months ago
https://github.com/d3athrow/vgstation13/pull/6464

**Comment by Exxion** [comment]
Yeah, it wouldn't be as big of a problem if there were any way to turn back
Also I later realized that the chef almost certainly did it on purpose and lied because I asked him at gunpoint.

**Comment by 9600bauds** [comment]
What about the non-advanced slime mutation toxin, what does that one do?

**Comment by FudgePucker** [comment]
Makes you into a slime person

Also would poisoning the food like that be bannable?
I mean if I spike the chefs food with mutagen, sterilizine, or other nasty shit, it is arguably not as bad as adv slime toxin. They get to ride on the wild ride and are back to normal, once you go slime, you don't go back.

**Comment by 9600bauds** [comment]
Basically what I'm asking is, I have no idea who put slime mutation toxin in the exotic seeds chemicals list and I don't know what the logic behind that was.

I didn't realize it was a thing until a couple months ago and I've never experienced it in-game so I'm not aware of the implications of giving slime mutation toxin to a botanist.

SHOULD it even be there?

**Comment by Exxion** [comment]
Chef may have been antag. I forget.
There were no admins on at the time

And it probably shouldn't be in the list at least until someone makes it possible to de-slime people

**Comment by 9600bauds** [comment]
Neither of them? Can slimepeople be cured?

**Comment by Exxion** [comment]
I don't think they can, but they can still do people things
They just take damage from fire extinguishers and cold or something and are immune to clone damage

**Comment by FudgePucker** [comment]
Curing sliming would take some power away from xenobio traitors.

It might be best to remove it from exotic seeds, because getting adv slime toxin in xenobio is one of the higher tier slimes.

**Comment by Exxion** [comment]
Tied for highest tier, in fact, if I'm not mistaken

**Comment by ihadtoregisterforthis** [comment]
How about a crazy low chance of getting it in botany?

I'm not against removing it but there's always the potential fun.

**Comment by 9600bauds** [comment]
I'll see about that. The problem is that you're not rolling for a chance to get a little bit of it, you're rolling for a rare chance to get a quick way to get an unlimited amount of it.

**Comment by FudgePucker** [comment]
There are multiple highest tier slimes.
Now unless you mean 'what you are rushing for as xenobio' then yea it is up there with gold slime cores.
There are four slimes that require a mutation of a mutation, black slimes are one of them. Also those four are somewhat iffy on their uses. Oil slimes are pretty fucking dumb when TOXINS IS RIGHT ABOVE YOUR WORK PLACE. Pink slimes just make large pet slimes. Adimite slimes are okayish if you want to have GOLEM TIDE STATION WIDE, but they are the mutation of gold slime cores, soooo. So in general most of the tier one and two slime cores are more useful than them, like purple slimes that make slimes produce two cores instead of one.
