### ISSUE TITLE
Turn to Stone spell statues last too long

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7034]
Current duration is extremely long, might as well be instadeath. I would suggest halving the duration and adding a description like "maybe he'll come back to life in time" so people don't just whack them dead.

**Comment by CptWad** [comment]
+1

**Comment by Killette2** [comment]
Also on a balance issue, there's no cooldown on hitting the statue. I abused this when testing the spell with a telebaton and destroyed people in less than 5 seconds with no cooldown hits.

**Comment by PJB3005** [comment]
I agree this is needed :+1:

**Comment by Kurfursten** [comment]
@Killette2 That may not be the case anymore. I got wizard 2 days ago and picked Flesh-to-Stone just to showcase how overwhelmingly too good it is. I was not able to attack the statue with no delay (using a toolbox), needs more testing. "Halving the duration" is probably not going far enough, though. It really is an absurdly long period. Another possibility is to just reduce it by half but introduce a chemical for counterplay that safely dissolves the statue back into flesh, like Lithium Sodium Tungstate or something -- sort of like how Subjugate Wizard results in everyone carrying some Ethylredox pills.

While we're on the subject, I wish Subjugate was in View instead of in Range, like Flesh to Stone is. Subjugation through walls gets old very fast.

**Comment by Intigracy** [comment]
I'd be fine with duration staying the same, click cooldown being added, and bashing it breaking them loose instead of turning them/their gear into ash with no revive chance.
