### ISSUE TITLE
Desk bells can sometimes be picked up by bags???

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7071]
![](http://i.imgur.com/wopdN1Z.gif)

![](http://i.imgur.com/lxMmTE7.gif)

Both ring when clicked, but only one can be picked up by the bag.
#4666: The reopening

**Comment by 9600bauds** [comment]
I dig your gif

**Comment by Exxion** [comment]
Good job, me, for not asking an admin to VV them

**Comment by uazuaz** [comment]
desk bells can be bolted using a wrench. was the one on the floor bolted? otherwise it's normal that you can take it using the bag. besides, starting bells are bolted by default, so it's normal that you cannot take it using the bag; if you use a wrench on that bell on the desk you can pick it up like the other one.
usually the only way to pick up an unbolted bell is to drag the bell on yourself; clicking on it just rings it no matter what.

(unrelated note: you can bolt bells inside containers too, like backpacks or plastic bags; this should be fixed but is unimportant)
