### ISSUE TITLE
Medical Malpractice STILL overpowered after its nerf, remove it

### ISSUE THREAD

**Issue by icantthinkofanameritenow** [d3athrow/vgstation13#7085]
After seeing another round where half the station was murdered by one person in a Medical Malpractice, I'm convinced that it's simply too overpowered to be in the game in any way other than adminbus.

To elaborate:
-Its movement speed is still too fast to be avoided, and it knocks people down when it hits them so even if it did move more slowly its victims wouldn't be able to get away anyway.
-It blocks all forms of attack. 
-It takes no more than 5 seconds to incapacitate a person due to its move speed.

In addition, numerous people in both the thread and in the game itself have repeatedly requested the removal of the Medical Malpractice. Please, get rid of it at once.

**Comment by Exxion** [comment]
It does not block all forms of attack
I have shot someone off it with a beanbag round from the double barrel before

**Comment by ghost** [comment]
All it takes is one runover to knock someone down, then a backwards forwards motion about 5 times to kill, taking off limbs in the process

If it stopped when it hit somebody for a moment as they go over them, then that'd be alright

**Comment by Exxion** [comment]
Oh yeah it's still OP as fuck
But that is one thing it doesn't do

**Comment by icantthinkofanameritenow** [comment]
@Exxion 

Funny, just this past round I saw it soaking up shots from an energy gun like nothing. Maybe that was my eyes playing tricks on me. 

@Skullyton
Better yet, prevent it from actually knocking people down at all. That alone makes it a gamebreaker.

**Comment by ghost** [comment]
@icantthinkofanameritenow Aim for the head, rather than the body, vehicles protect their drivers unless you clonk them one in the head with as was mentioned a beanbag shot

**Comment by AutismSpider** [comment]
More or less a mule bot that faster not on a awful ai and does way more damage/faster.

@icantthinkofanameritenow its like the janicart/fire bird it can take damage some times aka block shots for the rider if a stun bolt hits it the rider gets knock off no matter what.

**Comment by Exxion** [comment]
I don't know what to tell you about the shot blocking
Unless it was for some unknowable reason _buffed_ since I last saw it, at least beanbags can knock people off it
I've done it twice, in fact; I forgot the second time

**Comment by AutismSpider** [comment]
@Exxion  Shot blocking is rng thing that's part of the firebird janicart and this thing for god knows what Stun bolt hitting it will knock them off no matter what.

**Comment by icantthinkofanameritenow** [comment]
@Skullyton
@Autism Spider

The problem with that is that the wheelchair still moves faster than the standard run speed, despite claims to the contrary. It has a good chance of just outrunning and outmaneuvering the stun bolt as a result. Besides, what kind of doctor zooms around in a wheelchair anyway? There's tons of much better stuff a medical doctor could get as a traitor item. Like an airborne virus that turns people into Cluwnes, or some kind of ultra-potent poison disguised in an autoinjector.

**Comment by AutismSpider** [comment]
Antag doctors have lot of cool stuff to use but why use it when you have this over power shit that turn you into god with how fast you move on it.

**Comment by 9600bauds** [comment]
Could it be that the tickrate has some effect in the supposed slowdown of the wheelchair?

**Comment by icantthinkofanameritenow** [comment]
Tickrate seemed normal, but it was still moving like a crack-addled cheetah.

**Comment by Kurfursten** [comment]
**Blocks all form of attack**: My testing results

LASER RIFLE: Of ten shots aimed at the chest, all of them did full damage.
TASER: Of ten shots aimed at the chest, all of them stunned.

These results do not seem consistent with your reports. There is a graphical error where if the person in the wheelchair doesn't try to move after being tased, they will still be "buckled in" and not toppled over, but they won't be able to take any action (such as firing a weapon) or moving (which causes them to topple over). There does remain the fact that wheelchairs can block shots if you AREN'T riding them (instead standing behind them), _although this could be changed by removing density from wheelchairs (like office chairs)._

**Too overpowered**
To test this, I went through the logs of every shift this week in which a wheelchair was used and compared it to successes with an esword, _an item traditionally used to murderbone that is 50% cheaper, reflects tasers, does not slow down its user, and does more damage_.
Successful traitors with a wheelchair: 0/1
Successful traitors with an esword: 6/9

How many people were able to kill at least 5 people ("murderbone") with their weapon?
Wheelchair: 1
Esword: 11 (Wednesday the 9th, Friday the 11th, Saturday the 12th, three times on Sunday the 13th, twice on Monday the 14th, three times on Tuesday the 15th, didn't even check today) -- How can this be? Less than 9 shifts had an esword? - The answer lies in Nook Ops rounds and rounds where an esword was stolen by another traitor (e.g.: Hunson the paramedic's murderbone).

This was extremely tedious. Interestingly I did notice a lot of overlap in who likes to use an esword, but that's not really relevant to this.

**It moves "faster" than a person**
To test this, I did laps around medbay from the APC back to the APC both in the wheelchair and out of the wheelchair. These are the averages of five tries:
Foot: 8.2 sec
Wheelchair: 8.8 sec

The methodology here is somewhat flawed because I had more practice when I switched to the wheelchair, but I still consider the difference negligible. For the purposes of this conclusion, I think they move at the same speed. This isn't consistent with your report, but I was surprised that the difference is as little as it is. I had thought the movement delay from the previous nerf would do more than this. Of course, a little difference can add up over great distances

**Psychology and Conclusions**
Logs show that people murder in great number far more with an esword, so one wonders why the wheelchair is so different. An esword is concealable, blocks shots, and you can take it with you if you have to disposal yourself to escape the AI. I was personally killed in a murderbone with an esword this week where one player killed literally every member of the crew and then himself, with zero survivors except the AI. If this is the case, why is there more of a reaction to the wheelchair than the esword? Is there? Maybe polling should be done as to how people feel about being killed by an esword vs being killed by a wheelchair. **One interesting note I found in the logs is that this report was made immediately after a shift in which the reporter was killed by the wheelchair.**

Regardless of what comes, I've concluded that there are two things the wheelchair does need:
- Logging of damage. This doesn't happen currently and it should.
- Removal of density. This should actually apply to all wheelchairs, and I'm not sure why it's not in currently. Also, as quality of life, I'd like to be able to buckle someone else into a wheelchair: this comes up more often than you'd think.

**Comment by ihadtoregisterforthis** [comment]
I cast vote against removing wheelchair.

**Comment by Exxion** [comment]
Don't remove it, no, it's too funny and also has good points
But it does need some balancing

The thing is, if you don't know how to use it, it's piss (I assume, because I've seen people both fail miserably and succeed hilariously with it)
I killed one person within five minutes of roundstart with just two beanbags and the esword they dropped
But Sawbones killed like half the fucking station with just (or at least primarily) the wheelchair
I have little idea what the difference was between the two runs, but one was ungodly effective and one was piss useless.

**Comment by Kurfursten** [comment]
@Exxion This may not surprise you but Sawbones is actually a robust murderboner based on my log adventure. He uses the esword a lot - one of the most common users of the weapon. Maybe his practice with other melee weapons is what makes him so good with it?

**Comment by Exxion** [comment]
I guess
Someone else mentioned that they saw another highly effective wheelchair murderbone, but I wasn't around and don't know who did it.

**Comment by Kurfursten** [comment]
It must have been more than a week ago, because I only found one wheelchair purchase in the last week.

**Comment by icantthinkofanameritenow** [comment]
@Kurfursten

The Esword doesn't knock people down on the VERY FIRSY HIT it does. Run over them.even once, and it's all over for them. You also forget that the esword only seems more.successful because more people have bought it over the server's history. Of course it'll look more succesful as a result when it's been around for a longer period of time.

Perhaps you should have a poll within the game itself, because a lot of people are thinking you're outright refusing to listen to what the people want.  And for the record, I wasn't one of the people killed by the wheelchair, I simply observed both its consistent lethality and the considerable hate many people harbor towards it.

**Comment by Iamgoofball** [comment]
you can't nerf bad doctors

**Comment by Kurfursten** [comment]
http://strawpoll.me/6288992/r

People seem to dislike murderbone with the esword more than the wheelchair (at the time of recording 5 to 1, with most people selecting other options entirely).

Also I don't know if I buy your other arguments.
- Ebow always knocks down first hit and it's ranged.
- I don't understand your longer period of time argument. How does an overpowered item garner success with less frequency than a fair item?

I'm not against balancing the wheelchair, although I do feel like a lot of the hatred toward it is because of people that spread incorrect information about it (such as yourself in the OP of this report). I feel as though the changes I've suggested in my above analysis will help a lot, though.

**Comment by icantthinkofanameritenow** [comment]
@Kurfursten

It's because the e-sword is an older item, and the wheelchair hasn't been around as long so fewer people have got a chance to actually use it. If it was a thing since the start of the server, its stats would be far more reflective of its lethality.

And the e-bow has a much bigger drawback due to its piss-poor ability to actually deal damage and the terrible speed at which it recharges. The wheelchair has neither of those flaws- roll over someone once, and you can finish them in seconds by backing up a few more times. 

By the way, there's a reason why i said to do the poll in the actual server. Half the people in the thread don't even play the game, they just come there to shitpost.

**Comment by Kurfursten** [comment]
So what you're saying is there's a sort of "illusory murder" -- the item needs to be removed because of kills that people might be able to make if they were better at the game? I'm not trying to be sarcastic here, I'm trying to understand what you're saying. It sounds like you're saying "people aren't killing enough or succeeding because they can't use it to its full effect... remove it now because these successes which are not taking place might happen in the future"

Icanthink, it was very painstaking to go through the logs and see the success rates of players with two different traitor items for a whole week. Incredibly tedious, you have no idea. Please don't disregard real stats for the phantom numbers.

**Comment by icantthinkofanameritenow** [comment]
Very well. I'm not fully convinced that it's not OP, but perhaps it simply needs to be rebalanced further. 

For a start, the knockdown on hit absolutely go. It's a wheelchair, not a driveable taser. Being knocked down even once shouldn't be a death sentence on its own.

**Comment by Kurfursten** [comment]
A motorized wheelchair is way more dangerous than a bottle of booze to the head. Really, you don't think this would knock you down? https://www.youtube.com/watch?v=EEtwxKS0A3M

To tell you the truth, based on the logs and the shifts I've seen it in, I am not convinced that it is even as useful as an esword. I do believe that removing density is a quality of life change that will help improve not only balance for the traitor chair, but also make use of legitimate wheelchairs more pleasant for everyone. It's a place to start.

**Comment by icantthinkofanameritenow** [comment]
It's not even the knocking down so much as how quickly it can be followed up with five or six bouts of backing up, which severs limbs too.

**Comment by Kurfursten** [comment]
Maybe moving on top of someone should anchor the chair for .5 seconds, since it's clunky to move over bodies. The more I think about it, that seems like it solves a lot of problems.

**Comment by Exxion** [comment]
That does seem like a good idea. It doesn't affect single combat much, but it definitely helps people nearby stop the rampage. And there will be little single combat in this thing because lots of single combat suggests stealth, which this device entirely lacks.
