### ISSUE TITLE
Whats the point of lock boxs?

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#7127]
When a fucking IED can pop them open like nothing.

Being real here whats the fucking point of the box if they cant take a IED blast.

**Comment by Ephx1** [comment]
B-BUT MUH SCIENCE GUNS I VALIDHUNT WITH!

**Comment by TermedClepe** [comment]
What's the point of airlock access?

When a few fucking tools can open them like nothing.

**Comment by Ephx1** [comment]
It's more the fact that something that's supposed to keep people out only needs an empty soda can, igniter, and a cable coil. At that point if the box contains a laser then you only need an IED once.
I would say that airlocks are on a completely different level, sure they can lead to some pretty dangerous stuff, but that's usually behind several of them.

**Comment by CptWad** [comment]
I always just brought the boxes to mining then used gibonite to open them
Though I think that them being locked is just to add an extra step to free guns. Mostly because the science department is outrageously overpowered.
You can also drill the boxes open with a mech drill 
If you really want to fuck science over just put a 80% chance that the contents of a lockbox are destroyed along with the lockbox. That way they have to ask someone who is supposed to have guns or the HoP to let them have guns.

**Comment by 9600bauds** [comment]
It's a deterrent.
It's not meant to be an impenetrable lock that no scientist will ever get through, because that's shit.
Instead, it's just something that makes you think twice before forcing the lockbox, and makes it so that anyone can give you shit for having done so.

**Comment by clusterfack** [comment]
2015 and people are still arguing about this?

**Comment by Probe1** [comment]
lol we changed lockboxes like 4 times since this issue
