### ISSUE TITLE
Botany3 - Invisible infinite slippery plant

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7132]
Make lethal chem plant with slippery trait.
Feed plant to human repeatedly until it dies while you're mid-feeding.
Your plant is now invisible in your hand.
Drop it with drop key.
Behold as you can now forever slip on that tile while there's seemingly nothing there.
Pick up plant by using plantbag on the tile.
Drop anywhere.

**Comment by 9600bauds** [comment]
smells like r u n t i m e s

**Comment by 9600bauds** [comment]
This is happening for EVERY SINGLE FOOD ITEM.
Any single time you feed anyone anything and they finish eating it, everything runtimes and it gives you an empty item with null reagents stuck to your hand that will cause more runtimes for nearly every single fucking purpose. I have no fucking idea how long has this been happening for.
And all of this is happening because the food consume code is always assuming that the person who is eating the item is also holding it, as if feeding other people was never as possibility.

![disaster](https://cloud.githubusercontent.com/assets/6526157/11909927/44411962-a5cc-11e5-8f47-572aea3ef20f.jpg)

**Comment by ghost** [comment]
Magic.

**Comment by 9600bauds** [comment]
Thank you for your bug reports, by the way, I don't think we would have found this bug anytime soon without the "you have to feed someone else" how to reproduce.
