### ISSUE TITLE
Snow clothing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7268]
(WEB REPORT BY: assfaget REMOTE: 158.69.55.2:7777)
You should be able to walk around in snowspess without having to wear a full space getup, internals and all. Just a hat, some outer clothing and some gloves should be enough to avoid freezing to death.

**Comment by ghost** [comment]
Celt said he'd rework hypothermia and protection flags, so it's up to him. I don't envy him

**Comment by ghost** [comment]
Hate. Let me tell you how much I've come to hate you since I began to live. There are 387.44 million miles of printed circuits in wafer thin layers that fill my complex. If the word 'hate' was engraved on each nanoangstrom of those hundreds of miles it would not equal one one-billionth of the hate I feel for humans at this micro-instant. For you. Hate. Hate.

**Comment by PJB3005** [comment]
What is that quoting GLaDOS?

Or Celt is an evil AI, whatever works.

**Comment by FudgePucker** [comment]
@PJB3005 

> What is that quoting GLaDOS

I really hope you were being sarcastic.

**Comment by ihadtoregisterforthis** [comment]
This got at least partially adressed, right?

**Comment by ghost** [comment]
This is addressed, yeah.
