### ISSUE TITLE
Remove Rev form Rotation

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7274]
Nobody likes it.
The rounds always end fast, revs can just beat up what little people are in sec and the heads of security and win, and then there's the whole nolly with revs not caring about the state of the station they're trying to save.

Why the fuck was this snucked back in again? Round after round just proves that people don't like revolutionaries at all.

**Comment by icantthinkofanameritenow** [comment]
Agreed. It ends in less than 5 minutes tops and takes zero strategy on the part of the rev heads to win. Even traitors who go full murderboner mode at least pretend to be subtle at first, but with revolution it immediately descends into GREYTIDE STATIONWIDE every single time.

**Comment by Jeroen52** [comment]
What about making it rare? Requiring at least 4 security, at most 1 head position unfilled.

**Comment by 9600bauds** [comment]
Have it require at least 3 heads and at least 3 sec members.
That would already make it hard enough.

**Comment by icantthinkofanameritenow** [comment]
@Jeroen52

No, even there they can be overwhelmed simply via sheer numbers. Unless you have the power to not be robusted while 5 or 6 people are all wailing on you at once or the rev heads do something so stupid it kills themselves, the heads lose every time without fail. 

@9600bauds
And make sure at least one of those is the HoS, because with no loyalty implants you're still going to be curbstomped.

**Comment by Imagebard** [comment]
@Jeroen52 
It already is rare, @N3X15  commented on it. It happens about once per day, if not less.
People still don't like it, and sneaking in gamemodes nobody like "with a low chance" is full on coderbus BS.

**Comment by Killette2** [comment]
I like it. I don't like raging mages however, but it's good in the sense it teaches people how to be less shitty of a wizard.

**Comment by PJB3005** [comment]
I'm pretty sure this is all the config on the main server, not something we can change on the repo without just killing the gamemode / editing it so it uses a different identifier.

**Comment by icantthinkofanameritenow** [comment]
@PJB3005 
Quite frankly that might be a good thing at this point.

**Comment by Imagebard** [comment]
@PJB3005 
Do you think we would object to that or something

**Comment by sonime** [comment]
The issue I've noticed is that conversion is waaaaaay too easy. The main way I've thought of and the feedback I've got is to have conversion to the rev take time rather than be an instant flash.

**Comment by FudgePucker** [comment]
I will repeate my idea.
The problem with rev side is lack of communication, the other sides problem is being stormed and over powered by sheer force.

Why not have it be just a group of crew members who have to take down the heads, with special implants that allow telepathic comm between them.

Turns rev from everyone's out to get you to anyone can get you

**Comment by AutismSpider** [comment]
@FudgePucker Some one try some thing like this people got mad over it

**Comment by icantthinkofanameritenow** [comment]
@FudgePucker

What Autism Spider said, plus even with communication they just go with the sheer force method anyway. If you take that away, all you have is a slightly modified team version of Traitor.

**Comment by sonime** [comment]
The issue with Rev (and what separates it from Cult, a roundtype known for being tough) is that you just flash people in the halls and riot your way to victory.

Making conversion more difficult would be a major step to rebalancing it. Limited converts was already discussed on the server and most people didn't like it. So making conversion take time is the next logical nerf I can think of.

**Comment by 9600bauds** [comment]
Before any of that shit you need to look at the very basis of the gamemode itself.
It just DOES NOT WORK without heads and without sec.

**Comment by AutismSpider** [comment]
Right now rev is jerk off with the flash and have 90% of the staff rev.

30+ people vs 2 sec guards at most+the hos+one other head or two if we are lucky

**Comment by Killette2** [comment]
OK WHAT IF GUYS

Heads were alerted it was a rev round from the start also?
How much of the gameplay would it change if heads were allowed this information from the start?

**Comment by AutismSpider** [comment]
@Killette2 that's not going do shit if any thing that just back fire with how awful the player base is one of the heads will yell out about the revs and the station turns into cluster fuck of people trying to join them or hunting them down to out right kill

**Comment by sonime** [comment]
@AutismSpider I think once revs are confirmed, that's kind of an inevitibility. The issue is that the mode is unbalanced because of a lack of heads/security, also that, like you daid, 90% of the crew becomes rev.

I think like @Jeroen52 and @9600bauds said, having the gametype require a certain amount is heads/sec would be a great way to make sure the "counter-revs" have a way to fight back effectively, especially of one of them is the HoS or at least having a Warden to secure implants.

**Comment by icantthinkofanameritenow** [comment]
@Killette2

I think that's what they do in Bay. Predictably,the heads must then act like assholes as part of the ARE PEE experience in a way that would make people want to join the revolution on their own.

**Comment by sonime** [comment]
@icantthinkofanameritenow They don't do Secret on Bay, every round the game mode is known. They vote on it.

But yeah, that's how the RP goes on there for Rev. Wouldn't work on /vg/ but it's a start.

**Comment by Imagebard** [comment]
Christ, are you people trying to remake Rev?
Leave it for another Issue, a Feature Request for your suggested game mode. Right now it seems most people want Rev commented out form the code.

**Comment by icantthinkofanameritenow** [comment]
@Imagebard 
My thoughts precisely. It shouldn't be remade so much as outright removed. Nobody wants it, no matter what form it comes in.

**Comment by Imagebard** [comment]
@icantthinkofanameritenow 
I'm actually requesting they take it elsewhere because it would take a few days or weeks to fix rev, but code can be commented out faster. I have no objections to playtesting the new "rev" they make as long as it does not become Meteor v2.0

**Comment by Ephx1** [comment]
@sonime 
They do vote on gamemodes, but one of the voting options is secret.
I believe they have two revolution gametypes, the purely roleplay one, the other being normal rev with a longer subversion time, and proper Revolutionaries.

**Comment by icantthinkofanameritenow** [comment]
@Ephx1
You're thinking of the now removed "mutiny" mode.
http://wiki.baystation12.net/Mutiny

Incidentally, Bay allows Rev heads to use the same uplink traitors do. They even still have the same flashing thing, but DENSE ARE PEE means that if they ever use it in a case where the "convert" verb isn't broken (as it seems to be rather frequently), they get jobbanned from revolutionary.So not only could they convert the whole crew in minutes, they'd also be armed with eswords and revolvers.

**Comment by Jeroen52** [comment]
@Imagebard
I agree, comment it out now and fix it, later we'll test ti.

Just add one more step to the conversion of a person and require both sides
to be balanced somewhat.

Not that there are 50+ players and 11 flash-able assistants, but only when
there are about 25 to 35 players and enough heads and security.

2015-12-25 1:23 GMT+01:00 Imagebard <notifications@github.com>:

**Comment by Ephx1** [comment]
@icantthinkofanameritenow 
Shame, that was such a neat idea that would actually work there.

**Comment by icantthinkofanameritenow** [comment]
It really wouldn't be. We'd just get people immediately asking the rev heads if they can join up.

**Comment by Ephx1** [comment]
I said __there__ not __here__.
Any gametype focused around roleplay fails miserably here.

**Comment by mrpain666** [comment]
Dont remove it. Just increase the minimum player threshold. Whenever I see it we have a lack of security and are almost always missing one or more heads. An increased threshold would reduce the likelihood and severity of that happening and would make the round more enjoyable.

Plus removing round types is totally a TG thing to do now. Leave it to them.

**Comment by TermedClepe** [comment]
I like rev.

Lets remove dying, nobody likes dying. It just removes people from the round.

**Comment by Incoming5643** [comment]
If your rev rounds are rolling too hard in favor of the revs I suggest https://github.com/tgstation/-tg-station/pull/12724

**Comment by Imagebard** [comment]
>Lets remove dying, nobody likes dying. It just removes people from the round.

Are you being intentionally obtuse

**Comment by Jeroen52** [comment]
@Imagebard He is being very sarcastic.
Why remove it completely while you can also fix it and make it fun?

**Comment by icantthinkofanameritenow** [comment]
Because in its current state, tbeirea nothing to fix save for forcibly drafting people into Security at round start.

**Comment by Imagebard** [comment]
@Jeroen52 
Yes I understood that, but its still a crapshoot argument.

>Why remove it completely while you can also fix it and make it fun?

We already got a answer to this question while Dylan was messing around with meteors. The code was kept in-game while normal players had to deal with the gamemode, which was **still being fixed** and nobody liked.
And that's not taking into account that TermedClepe meant that he liked the gamemode as is.

**Comment by Jeroen52** [comment]
@icantthinkofanameritenow Forcibly making people security or heads could give it away that there is a rev round and get every Security on Red Alert and the Heads hiding away.

@Imagebard 
Some people like any sort of change, even if it is somewhat unbalanced and cause the round to be over within 10 minutes.
I personally sometimes like a change from the regular autotrait and Revs is fun, although it would **SUCK DICK** if I were to be a head or sec that round since all revs are out to kill you then.

**Comment by icantthinkofanameritenow** [comment]
@Jeroen52

Well for now that's the only thing solving the core issue that the revs have essentially zero resistance in accomplishing their goals.

**Comment by FudgePucker** [comment]
Lets look more into the issues of rev.
What if I am HoS or captain and catch some assistant with a flash early on into the round.
Would I be able to win the revolution round if I forcefully implant all of cargo then science, medbay, and then the rest of the station?
Would I be banned for powergaming if I do this at first sign of someone going around flashing people?

Rev is really shitty because it is team death match, but only one team gets to know who the other team is.
Cult requires a special antag item to convert, rev requires a flash, a common item that when asked why they have it, you get replies of "I DIDNDONUTHIN" and trying to take action against them results in 'BWONK: WHAT THE FUCK ARE YOU FUCKING DOING TO THAT ASSISTANT SHITCURITY' and being clunwed.

Just remove rev and increase cult chance.

**Comment by Jeroen52** [comment]
@icantthinkofanameritenow Not the only thing, what about adding another step into converting a user into a rev? That should make things more interesting and challenging for head revs.

@FudgePucker You could arrest people for having a flash because it is contraband, and make sure that the item is spaced.
You could possibly win by implanting everyone, that would make it way more difficult for revs to do anything.
As I have said before, maybe a second step should be added before you can convert someone, a step which is more obvious and more prone to errors than flashing someone.

**Comment by icantthinkofanameritenow** [comment]
@Jeroen52 Such as what? Or perhaps alternately, the conversion process itself could be time delayed and actively resisted. The key difference between cult conversion and rev conversion is that the former needs to be performed on a specific spot 

But seriously, if you want to reform rev, make a new issue. This one's focusing on commenting it out until that time. In its current state, the sheer numbers the revs can muster means the skeleton crew that /vg/station security tends to be is always outmached barring extreme acts of robustness or good luck.

**Comment by Arthurdentist** [comment]
today I will remind them that rev needs to be removed

**Comment by Zth--** [comment]
I don't know if this has been requested (tl;dr) but what if rev rounds had an anouncement like blob? It would be muuuch more balanced since heads would have some time to make a bunker or whatever

**Comment by Imagebard** [comment]
I would quote ICTOANRN on

>This one's focusing on commenting it out until that time

But huh, looks like nobody wants to do this issue.
Should I just close this and start a new discussion so people don't get confused.

**Comment by viniciuspetch** [comment]
Fine by me

**Comment by Imagebard** [comment]
Well it clearly isn't happening.
