### ISSUE TITLE
Allow medical belt to hold a hypospray.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7357]
(WEB REPORT BY: pinkacolada REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Medical belt can't hold a hypospray
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by CptWad** [comment]
Nah. As much as the CMO would appreciate it, I think its supposed to stay out of the belt. Its a traitor objective and its not like the CMO, or whoever doctor steals it, use up their backpack space when they can fit near everything medically they need in their belt or a medkit.
Id be OK with boosting medical belts to holding two rows of items, like toolbelts, since 90% of everything that fits in medical belts is small as shit.

**Comment by clusterfack** [comment]
It already fine as it is it fits in your pocket last I checked also STOP USONG WEB REPORTS FOR THIS SHIT
