### ISSUE TITLE
No roundvote

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7370]
(WEB REPORT BY: somhuan REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> e5395183613fb01d6f88628e0bb9877ac4a37270 
> 
> General description of the issue
> The round vote is not appearing.
> 
> What you expected to happen
> A vote for rounds to appear
> 
> What actually happened
> No vote, a map is randomly selected
> 
> Steps to reproduce if possible
> Try to vote for a map

**Comment by ihadtoregisterforthis** [comment]
It's a feature

**Comment by Zth--** [comment]
[Not a bug]

**Comment by 9600bauds** [comment]
when did we decide to remove map voting?

**Comment by Zth--** [comment]
nexis the dictatorship did

**Comment by icantthinkofanameritenow** [comment]
Nexis did, because nobody here gave enough fucks to file the bug reports willingly. Now we have to pay for their laziness.

**Comment by ghost** [comment]
@icantthinkofanameritenow
I wasn't aware the bug report count was going down. It's been climbing steadily and we're at over 200 now.

https://github.com/d3athrow/vgstation13/labels/Bug

But I guess forcing random maps that nobody wants to play because they are inherently badly designed will make people report even more bugs (???).

**Comment by ihadtoregisterforthis** [comment]
This is not a problem now
