### ISSUE TITLE
Taxi station is awful for AIs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7372]
(WEB REPORT BY: somhuan REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> e5395183613fb01d6f88628e0bb9877ac4a37270 
> 
> General description of the issue
> AIs cannot scroll smoothly from station to station
> 
> What you expected to happen
> The camera to jump from one station to the next as you reached the edge of one
> 
> What actually happened
> The camera does not jump, forcing you to use the incredibly slow jump to camera verb if you want to see other stations.
> 
> Steps to reproduce if possible
> Be on taxi station as an AI

**Comment by Ephx1** [comment]
Switch to camera, memorize the two combinations each station has.
Switch to camera, I want to see the cargo station -> Press C a few times -> Hit enter.
You are now viewing another station, congrats.

**Comment by fitrandiddle** [comment]
That's specifically the problem, yes.
That you have to go through the switch to camera menu if you want to see someone.
This fucks with ALL your menus you already have up, which you'll need due to the spread of the useful computers on the station, and has a nasty habit of messing with nano-UI too.

Additionally, it's way, way, way slower than the normal scroll, and fucks up AI gameplay flow.
