### ISSUE TITLE
Feature Request- Make it harder for the crew to outgun Security

### ISSUE THREAD

**Issue by icantthinkofanameritenow** [d3athrow/vgstation13#7396]
As a fairly frequent Security player, I'm more than a little irked that all it takes for Science and Cargo to outgun Security is a simple IED or a shotgun borrowed from the Bartender, and any of those guns ends up in the hands of an antagonist or a shitter they can murderbone with minimal effort. I've heard arguments that the best way to prevent this is to give everyone guns and that a "2nd Amendment" station is actually a good thing, but I doubt I would be alone in questioning people's ability to not shoot each other over suspicions of being antagonists or as a result of improper escalation. When you give people guns in this game, you'd be an idiot to assume they won't try to find an excuse to use them.

While looking at how other servers handled this, I've come up with a couple solutions.  The first is to port over the firing pin system that TGstation came up with to get around the lockbox problem without completely suppressing the ability to make guns. The pull is below if you wish to look at the code. (Disregard the explosive implant removal for nuke ops, that was badly received even over there. )
https://github.com/tgstation/-tg-station/pull/6925

However, I feel it would take a lot of work to adapt it properly, which is why my second solution is to make lockboxes and crates more difficult to open without either the correct access or an e-mag. At the very least, opening locked crates/lockboxes with gunfire, explosives, or emitters should run a risk of destroying the contents as well as the box/crate itself. It would also minimize the risk of Cargo stealing shit from their crates for themselves and cut down on "Cargonia" antics. 

Lastly, it may just be easier to simply add an AEG or two to the armory in place of the laser rifle that spawns there, or to make the HoS spawn with an AEG instead of a standard energy gun. They could still end up outgunned later, but at least this way they would theoretically be able to hold their own long enough to stem the production of unauthorized weaponry. The Mysterious Armor in the armory should also be replaced with something better, I think; compared to literally all the other armor in there, it's terrible. 

Before anyone objects, I'm not against arming the crew in an emergency, but they shouldn't be able to outgun Sec in normal circumstances unless they use antagonist items/abilities or put in a shitload of work to do so. Security is meant to protect the station after all, and it's hard to do that when everyone is packing weapons that make the entirety of the armory's contents look like pea-shooters.

**Comment by FudgePucker** [comment]
I had a more unique and more robust idea.
I will make the feature request tonight once I get home.

**Comment by PJB3005** [comment]
I agree, guns are too easy to get.

**Comment by Imagebard** [comment]
@FudgePucker 
I really want to see it, but I think the firing pins idea might be the best one for now.

**Comment by icantthinkofanameritenow** [comment]
@FudgePucker 
I'd be fine if you posted it here, since it sounds like it would have a similar result in practice. And as I said, we'd still need to modify it quite a bit.

**Comment by Killette2** [comment]
The problem isn't this. The problem is that there is little to no security, so they can't communicate or do searches effectively if problems arise.

**Comment by icantthinkofanameritenow** [comment]
@Killette2

And this is part of the reason why- it's demoralizing to know that even if you do search you're likely to be shot up in seconds by half the station.

**Comment by Imagebard** [comment]
@Killette2 
>The problem is that there is little to no security

God wonders why you'd join security when you can replicate the whole armory as a validhunting scientist.

**Comment by icantthinkofanameritenow** [comment]
@Imagebard

And in the process, make security's job hellishly difficult by giving everyone who asks a gun even the HoS would be jealous of. It's not replicating the armory so much as surpassing it.

 The problems there should be self-evident, and it doesn't take a genius to figure out that an antag scientist would arm himself up in a heartbeat before bombing the station or what have you.

**Comment by Zth--** [comment]
Make weapons research more uniqe and complicated. For example, make it so the only way to get to level 3 is with an energy gun or an antag weapon (and then, remove eguns from cargo). This is a lazy example, but I hope you get it.
It should solve the problem of scientists printing 50 assault rifles and 100 advanced eguns per shift

**Comment by Intigracy** [comment]
Make cargo unable to order gun crates without sec access.

Lockboxes at least are already hard to get into, you actually have to explode something on them to do it.

**Comment by icantthinkofanameritenow** [comment]
@Intigracy

Between IEDs, Ripleys, and Toxins, lockboxes are little more than a speed bump to gun-happy scientists and the moment that first lockbox pops open, all bets are off.

**Comment by AutismSpider** [comment]
@Intigracy  lock boxes are bloody joke to open can drill them open with ripley/ied them open hell you can even emp them open but thats bit of rng all they have to do open one weapon to get more open.

**Comment by FudgePucker** [comment]
#7415
I did it.
Fuck research having guns.

**Comment by d3athrow** [comment]
SHALL NOT BE
INFRINGED
N
F
R
I
N
G
E
D

**Comment by icantthinkofanameritenow** [comment]
@d3athrow 
Fuck you, the second amendment doesn't apply to spehss.

**Comment by Imagebard** [comment]
@d3athrow 
Oh please. 
Shitters love to join science and grab guns to validhunt, specially if R&D is already done so they don't actually need to contribute anything to science.
If people want to validhunt they should join security already.

**Comment by AutismSpider** [comment]
@d3athrow We have sec for the job of muh valids but what it turns into is a job to baby sit player base of man children's who cry out dindu nuffin when do bad shit they should not do but do it any way on top of having the temperament of a bull!

**Comment by clusterfack** [comment]
@d3athrow Texas stands with you

**Comment by icantthinkofanameritenow** [comment]
@clusterfack
Hopefully in front of a bus. Seriously, science now is Validhunting: The Department no thanks to effortless AEGs.

**Comment by AutismSpider** [comment]
At one point of time AEG gave out RAD's (it has mini nuke core in it for its power etc) not a lot of rads but if you were smart ass and had like two or three this would kill you+organ damage people cry bitch tears and it was taken out.

**Comment by SangriaMonkey** [comment]
People don't play security because the funny I didn't do anything you're a raciss popo /pol/ joke gets really tiresome after the thousandth time. That and the fact that you're pretty much a designated loot piñata for lings and vampires since they'll faceroll you if you don't have some sort of lethal weapon or a lynchmob helping out. But that's beside the point. If you've played here for longer than three days you're probably aware that almost everybody in almost every position is going to invariably procure some sort of weapon or means of self defence at some point during the round. That's just the way it is. You can keep putting hurdles in front of people but they'll always find a way. And quite frankly I'd rather have a potentially armed crew that could potentially save my ass than an unarmed crew that couldn't if they wanted to, even if that means I might have to get into a couple more gun battles with retarded memetiders.

**Comment by d3athrow** [comment]
God bless Space America
'An energy gun behind every floor tile' - Shoe Snatchin' Willy
;-;7

**Comment by icantthinkofanameritenow** [comment]
@SangriaMonkey 
You're forgetting the flip side of the argument- it also makes it much simpler for the antagonists to be armed too. I can't trust RnD to keep their gun boner under control, so it has to be controlled for them. I figure that Security simply doesn't clamp down when they get the chance, and then pays the price for their complacency.

**Comment by d3athrow** [comment]
psh take guns away from people who follow space law and antags will still get them

**Comment by icantthinkofanameritenow** [comment]
Ah, but fewer guns means fewer chances for antagonists to get them. It'll make them appreciate the guns more.

**Comment by AutismSpider** [comment]
force the antags to buy that awful as fuck ebow or the strong and useful revolver.

**Comment by Uqualm** [comment]
This is a step forward in the right direction and I was the original Anonymous guy who suggested it. For that reason it will never be implemented. If it is though, you'll see more people play Security.

Look Pomf boy I'll keep it short and simple so your chicken brain can understand.

2nd Amendment works in real life where 99.99% of people don't want to kill you, there's police officers and a reliable justice system in place, and people don't randomly seceed from whatever territory they're in and start shooting at cops for no reason. It aint the case on SS13 where there's guaranteed to be at least one guy on a 50 something station who wants to kill you and people act like greytiding shits all the time. Just use your head. Security doesn't have shit and everyone else has the good stuff. Why would you play sec?

**Comment by ghost** [comment]
Since we have similar issues, everything I said in https://github.com/d3athrow/vgstation13/issues/7415

For specifics, they can't shoot you with lethals/bullets without risking bans. Your belt of tasers, flashbangs, slip strips, and the initiative is fine for sec since they can't take advantage of their shit

Nobody ever went gee, I can only print/order thirty guns instead of 25, not worth it after blowing them open gobbles them I guess. Even if you completely removed emp opening shit 4nogudraisins you can just make enough no matter how punishing the mulch rate and print cost is. They'll happily empty the lathes

You can already get your own lasers at cargo and if needed, you have four other places to print those "superior" guns if somehow your multiple flashbangs and tasers is insufficient. In which case they wouldn't help you cause you're hopeless anyway.

It's fine as is as an IC matter, especially as a light rp server, enforce space law or don't and enjoy having more armed people who don't want to get killed. Security can arm itself quite fine numerous ways in addition to the same ways as others in the same amount of time it takes sci to get the basics. So you're only "outgunned", flashbangs ahoy!, as much as you sit on your hands. Sec has the advantages of its flashbangs and shooting up sec with illegal cause they were trying arrest you nonharmfully with tasers and flashbangs round after round is a good way to get notes and free vacations. Never forget our brave cargonians ancestors who died for our freedoms ;_;7

If you do want to ram it though, you get permabanned thirty times for every fucking time I and anyone else have to put up with the bullshit of FUCKING WARDEN/HOS/HOP/CAP WE HAVE ENTIRE LOCKERS OF GUNS I'M SCREAMING IT ON COMMS, ALL OVER YOUR PDAS OH MY GOD WE CAN DO THIS IF YOU'D JUST ENABLE THESE GUNS IT'S BEEN FIFTEEN ACTUAL MINUTES AT THE BRIG DESK WHAT THE FUCK, in an emergency like blob or vamplingzard ability cheesed through sec and now all we have is mostly chem and ghetto proj.

Uqalm, most people here don't either. And if you do want to tryhard sec, open the door, chuck a flashbang in, and brig+demote them. If they resist or act up after, implant and perma them for being mutinous shit over guns they shouldn't have and sure as hell shouldn't be firing at sec. When they break out, pop their implants and go gibber the corpse then get on with life.

**Comment by Uqualm** [comment]
Alright, time for some walls of text if you're posting your own. Remember what the point of this is to nerf the crew because they are way too strong in relation to Security and to give some sort of incentive for people to play Security. 

It's not hard to fuck over Security and get away with it. You don't have to kill them. You just have to stun, cuff, detain in Science on a chair. Or not even detain. Just strip them naked and throw them in disposals. None of that shit is bannable, but it still completely fucks you over. I'm not going to talk about MUH ADMINS, but I will say that it's not hard to just claim escalation and an admin will just forget about it. You keep going on and on about these dumb power gaming strategies you would do as HoS or Security to stop it, but I'll be honest dude, I saw you as Crunch Buttsteak and you were a really inefficient HoS. That's beside the point though. I mentioned it in the thread where I was arguing with this guy who created the issue, evidently I convinced him of something so I'll just copy paste the relevant parts. Or you can just read the conversation here. https://4ch.be/vg/thread/126852604/#126856517

For all the counters you keep posting I can only say this,

Yes, there are counters for all of this, but even with these counters, there are counters that the crew can take for those counters and it's never as simple as, do this if they do that. You are always assuming a pristine condition in which everything is so simple to accomplish or even possible. It's not always the case that you have an AI who is going to be helpful. It's not the case that you are going to be free or have enough people to raid Cargo, Science, or whoever is acting up. You simply can't be in all places at all times. You have to prioritize. Some things are going to slip through the cracks, it's just that on /vg/, most things will slip through the cracks. The times I played Security on /vg/ (where I was the HoS as only Security aside from maybe the detective and a borg) I was forced to ignore all crimes and just get the antagonists. If I didn't I became swarmed with tasks that took way too much time and the traitors went around killing people and eventually blindsided me while I was brigging the guy who kidnapped the clown.

The point again, is that the situation for Security on /vg/ is abysmal. You are outgunned and outnumbered most of the time. Not many people can handle it, and so not many people play it. Especially new people.

Now back to the rest: If you're outnumbered 3 to 1 or even 5 to 2, it doesn't fucking matter that you can flash bang a guy (even though he could have flash bang protection) because you can't cuff 3 people at once and as soon as they get up you have to either chain stun them very accurately to cuff the rest (let's hope to god all people are in one room and nobody just wanders in to shoot you) and then cart them off one by one. 

About the lockbox thing, I completely disagree with this guy. Removing the lockboxes entirely is fine IF AND ONLY IF the firing pin system is implemented. 

I'll say again my solutions to the problems. I don't know why I'm bothering as nobody will take it seriously.

1. Firing pins. Traitors can emag the unpinned gun to make it work. Firing pins are only in the armory. If you want to spam guns fine, but you have to break into the armory first. 
2. Security cargo crates (GUNS) only able to be ordered with a Security ID in the console.

I should re-iterate I'm not some kind of crap Security player who whines and can't get shit done. I was literally stickybanned from /tg/ for apparently ruining the rounds as HoS by incinerating all the rounds traitors every single time, they called me "JLP but worse". It's an issue. Maybe not for YOU or for ME, the superman who has played the game for years, but for most people it is.

**Comment by ghost** [comment]
The biggest problem with pins/hard id checks and other shit is that you're making an assumption of med+ always moderately/fully staffed with actually competent staff which rapidly breaks down in blob, wiz, ling, vamp. What you're essentially asking for is applying the same level of tard wrangling it takes to get a code red to getting guns people desperately need in a crisis. Heck just think of all the times nobody could fix you as a borg or provide the ID so you could fix a broken borg. That's what your asking for. It's terrible, accomplishes little, and fucks over everyone.

**Comment by icantthinkofanameritenow** [comment]
@SarahJohnson489

And guess what? It very often is the case. Security on the other hand is lucky to get more than three fucking people in the department at once. And the borgs have it easy, they can always just unlock their own covers at will. But you wouldn't know that, because GIT GUD is the only argument you can make. 

I dare you, go and try one of your "raids" on the server now and see how well it works out for you. I'll be here to say I told you so when it fails.

**Comment by ghost** [comment]
When the precise problem is trying to tackle a hard problem like hamfisted cluwne no shit the answer is step up your game until it's legit. You're only outgunned if you can't hit for shit and refuse to use just about every tool and advantage at your disposal so no shit the medicine is gitgud. Not uncle coder plis fix muh booboo for me.

**Comment by icantthinkofanameritenow** [comment]
@SarahJohnson489

I have yet to find a tool that allows you to stuncuff 3-5 people within a few seconds of each other in short succession, and the fact that such a raid is even necessary proves that the intended purpose of lockboxes (to keep scientists from making guns that they can use for themselves) has failed. 

If you would simply prefer lockboxes to be indestructible without emags or correct access, that's fine and I'd be fine with it. I could be a perfect shot, but when three guys are all shooting you at once when you have no backup (which -surprise!- is almost always the case due to Sec being a skeleton crew of the worst kind), it only takes one lucky shot for you to be stripped and bucklecuffed.

Brag about your own personal robustness, but the security staff today that aren't immediately turned off by the fact they are the most hated job on the station need the crew to be put in their place. Lockboxes wouldn't exist if the crew was meant to be armed to the teeth at the smallest sign of trouble. 

Keep shouting "GIT GUD" and avoiding the real issue here as much as you like, but if that was really the solution then I would have never needed to make this issue in the first place!

**Comment by Imagebard** [comment]
>the intended purpose of lockboxes (to keep scientists from making guns that they can use for themselves) has failed. 

That was never the intent, it was to signal if scientists are just making guns for security or if they're letting them go loose.

**Comment by ghost** [comment]
You have all damn day with a stun baton or just baton em all once, move em into the locker and weld it then go gas them at sec to get your stripcuff on. Lockboxes were never meant to stop them, only to make it clear they're being naughty boys and to require a minor knowledge and supply check.

You can argue hypotheticals all day and I can shout gitgud all day

We had that and it broke the shit out of the quality of many rounds because guess what, sec is already chest deep in quicksand and don't get to them which is a chunk of how we ended up where we are. Sec still got fucked with by greytide anyway and always will because it's a problem with greytiders that need brigging rather than what they have.

Maybe what's clearly the issue is the garbage attitude of buying into the sec is hated and admins are hard on sec meme. Don't be a gigantic cunt and you're fine.

**Comment by AutismSpider** [comment]
@SarahJohnson489 >dont be huge cunt and you be fine >the player base thats FULL OF HUGE CUNTS AND CRY BABY'S!.

oh that slaps me on the knee

**Comment by icantthinkofanameritenow** [comment]
@SarahJohnson489 
Given that they treat me like that no matter what I do as Sec, perhaps becoming Space Hitler really IS the best approach. They need the discipline shoved down their throats, and fuck them if that means their greytiding isn't tolerated for even a second. If that makes me shitcurity, fine- it's what they always deserved.

**Comment by Uqualm** [comment]
Being a hard ass takes time, if you don't take the time you're not efficient enough to ensure that the people you are punishing have no way of reversing their punishments. You also don't have the time to follow up on leads, and ensure that the people you are punishing have actually truly done something worthy of punishment. There are innumerable amounts of things for you to deal with, and if you are to do Space Hitler properly you need other people who are as competent, level headed, and dauntless as you are. This will very rarely happen, especially on /vg/ under the current conditions. You are then forced to play as Space Hitler improperly through two ways.

1. You deal with tasks with the time required on a first come first serve basis. 
2. You deal with tasks required as quickly as possible on a first come first serve basis.

The third way is to prioritize and do only the most pressing of tasks, but this is in direct conflict with what Space Hitler actually is. When you prioritize you will be forced to ignore such a large portion of crimes that you cease being Space Hitler and let people get away with a lot of things.  

If you stick to the first way, you will as I said earlier, be bogged down with so much stuff and get killed off easily. If you stick to the second way, you won't be efficient enough to do your job and may possibly get banned for a mishandling of the situation. The third way is the only proper way of doing things, and that means you are forced to most of the time ignore the greytide and focus merely on the people you know will kill you. Lastly this third way takes someone of tremendous character to play properly.

I don't think that Sarah Johnson understands that to play Head of Security under these conditions you need to have a certain real life quality that you don't need for many other roles in video games and that most people just don't have. It is incredibly demanding and it is why nobody plays it, they are incapable. 

You will agree with me if you try it yourself, and so I ask that you do, and open up this discussion again once you have. For Sarah Johnson, I don't think they will change their mind so I only say to you, you have no clue what you are talking about. If you even tried to practice what you preach in those so called situations you would fall flat on your face.

This is the only solution to the problem.

**Comment by icantthinkofanameritenow** [comment]
Then I shall take that third way, or at least attempt to do so. But that doesn't mean I can't give a nice little "fuck you" to the greytiders whenever I get the chance. 

I'll just have to relish those moments more. Regardless, this discussion will remain open indefinitely as I know for a fact that the issue will not simply vanish no matter what it is that I do, and that a truly lasting solution will in fact require gun control, so to speak.
