### ISSUE TITLE
Defficiency - Large amount of maintenance isn't radproof

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7405]
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7777)
http://i.imgur.com/Pj1Ribp.png

A radstorm rolled in, and you would assume that these areas would be radiation resistant, considering they're A not glowing when the rad storm rolls through and B part of maintenance.

That isn't the case. These areas are considered "Port Derelict" and for whatever reason everyone inside got a nice dosage of radiation

**Comment by ghost** [comment]
[it's not maintenance]

**Comment by ghost** [comment]
Damn it Duny

**Comment by Exxion** [comment]
Considering they're old station rather than maint, it makes sense they aren't shielded. However, they should glow to indicate that.

**Comment by Intigracy** [comment]
What z level is this on?

**Comment by Exxion** [comment]
The station.

**Comment by ghost** [comment]
@Intigracy That's the main station, the picture itself is just off of the theatre.

Seems odd that you have to gamble whether or not you're in a rad resistant area or not in a map that on first glance is 60% maintenance and the area you are in is not glowing

**Comment by Duny-** [comment]
Exxion is right, I don't know why they don't glow. I'll take a look at it.

**Comment by Duny-** [comment]
They don't glow because they aren't powered. I'd make them glow anyway through pure magic so people can be safe from radiations without having to shift-click a door or check if there's a white line on the ground after dying once to rads but I have no clue how the fuck I could do that. Didn't find any mention of the alert needing power in the unreadable mess that is the code to begin with so I dunno.
