### ISSUE TITLE
Latejoin vox can't speak or understand Common on Heist rounds

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7412]
I don't know when this broke, but it was very recent
This applies to station vox, too

**Comment by Ephx1** [comment]
Isn't it that some can and some can't? If not it should be that way.

**Comment by Arthurdentist** [comment]
did you latejoin as vox or were you roundstart vox?

**Comment by Exxion** [comment]
Latejoin.

**Comment by Arthurdentist** [comment]
I think there was an issue about this before though I could be wrong. As far as I know Heist Vox cannot understand common and its latejoin Vox specifically who cannot also understand it. As far as I am aware all other roundstart vox are not affected. You can actually meta the roundtype through this because if you see a latejoining vox assistant skreeching at everyone in their foul disgusting parrot language, you know its very likely to be a heist round because of this bug.

**Comment by 9600bauds** [comment]
I wouldn't rule out the Vox assistant just being a dick, because that's what a Vox do

**Comment by Intigracy** [comment]
Was it you that this happened to or just some random guy who might have been being a dick?

**Comment by Arthurdentist** [comment]
it was someone who 'ahelp: I can't speak common for some reason!'

**Comment by Exxion** [comment]
@Intigracy Me and all the other latejoin vox

**Comment by 9600bauds** [comment]
[Exploitable] [OH GOD IT'S LOOSE]

**Comment by clusterfack** [comment]
Didn't we fix this before? I'm fairly sure we've had this exact same problem in the past.

**Comment by gbasood** [comment]
There's an entry in the changelog for this issue now. @d3athrow it's your changelog entry, can you confirm it's fixed?

**Comment by Exxion** [comment]
He specifically said it was, so I'll close this and reopen it (and yell at him) if it isn't actually fixed
