### ISSUE TITLE
Taxi Medbay

### ISSUE THREAD

**Issue by Allspice** [d3athrow/vgstation13#7413]
Minimum 24 tiles between cloner and cryo behind two airlocks, which is too much.

MDs do not get access to a crew monitor computer.

You have to go through a wide loop and past two airlocks to get from med primary to chemistry.

The lobby is nonexistent; patients have to wait directly in front of the med airlocks or just dawdle about in the middle of medsilicon until they're received.

Telescience is on another station, so it's never fucking used.

**Comment by invoid9** [comment]
Here's some more complaints (the overlapping ones are there for emphasize :^))
-Cloner is too far away from the cryotubes
-Light switch in patient room works for the main medbay
-Chem fridge is far away from main treatment area
-Chemlab cannot see the main treatment area, has a bitch of a time getting to help patients (which they have to do often)
-No surgery overflow
-No clear indicator of where surgery is (minor issue)
-Those wheelchairs are fucking annoying and always get pushed to block doors, please move the spawn to next to CMO's doors (can't get pushed there)
-Cloning lab is too cramped, I feel.
-not many firelocks

**Comment by xevonix** [comment]
The "Medbay Storage" room, which holds the chem fridge and the doorway to the cloners is only accessible by Medbay staff, causing unneccisary hassle to try and bring bodies to be cloned as a non-Medbay staff member or easily distribute/receive medicine to people within medbay without access. 
If the reason its locked to only Medbay to discourage stealing, then everything could easily be fixed by just putting the valuables behind ID locked windoors.

There is a lack of visibility within the front desk/Paramedic spawnpoint to the hallway outside of medbay which could be fixed by replacing the area circled in red here, http://puu.sh/mesZ5/ac2757759d.png , with reinforced glass windows with grills.
More problems with the Paramedics spawnpoint/front desk is that the desk with the bell on it, shown here: http://puu.sh/met5W/47ac3ba1ac.png , does not posses an airlock on it. Meaning if pressure or oxygenloss happens in the center taxi area of the Med-Sci Taxi Station, then the entire main part of Medbay is without air or pressure as well.

Another thing that could improve the quality of this map's Medbay is the addition of airlocks to prevent airloss/pressureloss near the Cryotube area. I propose, shown in this drawing: http://puu.sh/metbX/ca863f3943.png , that we place two airlocks in the tiles that I have the red box around and move the door to the Medbay Lounge to the right one tile.

**Comment by Kurfursten** [comment]
@Allspice I've been saying for a while we should experimentally give the paramedic the telescience console on one map to see how it goes. Wouldn't be too bad in my mind to let Taxi be the testing ground, it is kind of the gimmick map.

@xevonix Maybe just a firelock there, like the cryo tubes on Box.

**Comment by SarahJohnson489** [comment]
>Doesn't communicate with science to teleport corpses back

For shame powergamer... For shame.
