### ISSUE TITLE
Unending butchering popup spam when trying to fight mobs with sharp weapons

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7434]
1) Kill spider with fireaxe
2) Start killing more spiders on top of the tile where first spider died
3) Accidentally click on the first spider's corpse, get butchering popup asking if I want to butcher it, cut it's legs, or do nothing
4) Hastily close it and continue to kill more spiders
5) Accidentally click on corpse once again, popup appears
6) Repeat steps 4-5 a few times
7) Drag the butchering popup to a corner and ignore it
8) Try to close it during a moment of peace
9) There are so many queued windows
10) I have closed like 40 butchering popups and they show no signs of stopping
11) Help

Proposed solutions:
- Restrict butchering to help intent only
- Make it so that butchering popups don't queue endlessly (bad)
- Restrict butchering to kitchen knife only (worse)

**Comment by Exxion** [comment]
I used to get the salvage shuttle like every third round and even using a rapid clicker I never had this problem
Sure, once I one-hit myself with the fire axe by accident, but never accidentally butchered a spider
Still, popups are annoying
Maybe it could be changed so that what you do is based on the body part targeted rather than a popup
(Like remove legs if you target the legs, harvest teeth if you target the mouth, butcher if you target the chest, etc.)
We have that whole body part selector and it's only even used in actions performed on carbons and maybe silicons, as far as I know

**Comment by 9600bauds** [comment]
I never actually butchered a spider. I just got asked if I wanted to do it like 40 times.

**Comment by Exxion** [comment]
You know what I meant

**Comment by 9600bauds** [comment]
In the situation described in the OP all the spiders were in the same tile, which was pretty chaotic. Unrelated but I'd also appreciate if dead mobs were given a layer underneath live mobs, because most of the time I had to pixelhunt the hump of the not-dead spider out of the rest of the spindlylegs.
![2015-12-31_13-14-59](https://cloud.githubusercontent.com/assets/6526157/12069971/1ab737ec-b036-11e5-87ba-fd70775ce2fd.png)
