### ISSUE TITLE
[DEFFICENCY] Fuck what duny says and add the fucking crew monitor to the lobby

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7441]
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
Duny doesn't do jack shit anymore and adding a crew monitor to the lobby would improve the medbay a fucking thousand times.
Not only is the maint fuckhuge here, but even if someone dies with their suit sensors on no one can fucking find them because Duny refused to put a crew monitor avaliable for general medbay use because he loves eating paramedic dick all day.

**Comment by ghost** [comment]
:+1:

**Comment by AutismSpider** [comment]
or we could take this fucking map out of the list

**Comment by Cisrox** [comment]
deff is better than taxi

**Comment by Zth--** [comment]
Do eet

**Comment by Imagebard** [comment]
Well, fucking do it.

**Comment by MemeFury** [comment]
If we're going to have to do forced rotation, I'd like to have every other map's capabilities regardless of what is intended "design" for a map.

**Comment by mrpain666** [comment]
REMOVE DUNY
E
M
O
V
E

D
U
N
Y

**Comment by Duny-** [comment]
Just delete paramedics and I'll do it. They've already been made entirely redundant and inferior to the rest of medbay on Box and Meta.

Here's what I told Hoshi about it, and his answer https://github.com/d3athrow/vgstation13/issues/6459
And another here because I just love repeating myself against people whose sole argument is "all maps must be the same" https://github.com/d3athrow/vgstation13/issues/7380
Stop pissing yourself because you don't want to play paramedic/AI/borg/CMO/captain/CE/RD/HoS but still want to track the crew.

**Comment by ihadtoregisterforthis** [comment]
Masterly performance.
