### ISSUE TITLE
Head of Personnel privacy shutters

### ISSUE THREAD

**Issue by MemeFury** [d3athrow/vgstation13#7495]
Something I really enjoyed on Deff is the blast doors you can put up on the HoP's office. I think we should have it on Box.

**Comment by CptWad** [comment]
but how else are the greyshirts supposed to steal access from terrible HoP's?

**Comment by gbasood** [comment]
I don't see the need. It's pretty difficult to break into the HoP's office as it is, and if you want privacy there's the meeting room right next to it.

**Comment by CptWad** [comment]
Difficult? All you need is to break down the window, which is not hard

**Comment by gbasood** [comment]
HoP shouldn't be sticking around long enough for someone to break in.

If there's a use for these, I'm all for it. I'm not saying that they're useless for security, I just don't think they give anything worthwhile towards it.

**Comment by CptWad** [comment]
>HoP shouldn't be sticking around long enough for someone to break in.

Wait so
He should not be in his office long enough for someone to break in
Fuckin english
You are saying that HoP's are not shit
hell ive been the HoP that shoves himself in his office all shift. Its hard as hell, harder than most could imagine.
Though im impartial to the addition, adding it *would* make it harder to get in the office as the HoP could lock down the doors. Then it becomes whoever can
*A: Work with someone else to get over the table
*B: Have insulated gloves and/or knowledge of the power wire
*C: Welding protection
Usually any jerkoff can get in the HoP office using his windows since shards are shockproof

**Comment by Intigracy** [comment]
Maybe you shouldn't leave things out worth breaking in for.
