### ISSUE TITLE
Map Rotation Voting Compromise

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7508]
As it stands, we very rarely play other maps, and while I wasn't in favour of the forced map rotation when it was around, due to both the complete lack of accountability of n3x and the lack of democracy, I accept there's an element of truth to N3x's argument and hence I propose that instead of absolutely voting for the map, you rather vote for for the weighting of the random chance of the map. - Here's a practical, albeit drastically oversimplified example.

Assume 40% of the players want to play Box, 15% want to play Defficiency, 30% want to play Metaclub, 15% want to play Taxi. If there was a vote, assuming they only voted for the map they wanted to play, the maps played would be thus: 100% Box station.

With the weighted system, instead you would have 40% Box rounds, 15% Defficiency rounds, 30% Metaclub rounds, & 15% Taxi rounds.

That's far fairer, as both a compromise and an alternative.

**Comment by PJB3005** [comment]
:+1: :x: :100: :x: :100:

**Comment by gbasood** [comment]
We could also influence map voting based on the last X number of rounds. For instance, we could put votes against Box based on how many rounds in a row it's been voted on.

How we'd track that I have no idea, text file export on round start or map vote completion?

**Comment by Exxion** [comment]
Please
Playing exclusively Box since voting returned has been very boring

**Comment by ihadtoregisterforthis** [comment]
Some fag had this idea #4712, but it would still have the same issue.

N3X15's way was extreme for some but he wasn't lying. Now Box keeps winning most of the time, even if the other maps get slightly more votes than before.

**Comment by IratePirate** [comment]
People have been suggesting this ever since Meta and Deff were merged, but nobody ever listened despite it being the only sane choice. Everybody wins, Box gets played the most keeping the normies happy, and the other maps don't get outvoted each and every time on high pop by people obsessed with retaining the status quo so they can grab their gloves from the same spot round after round keeping them happy.

If there was a way to randomise the number and placement of items that would be the best change to the game possible.

**Comment by ghost** [comment]
Map chance depending purely on number of votes it got is a very good idea, that way all map fanbases will get their proportionate share of server time. Even if it's just one guy voting for taxi.

It makes no sense to force or increase a chance of a map to be played just because it was not played for x rounds. Votes directly represent what the current server population wants to play.

**Comment by gbasood** [comment]
We could also remove the map that the round just ended on from mapvote, but I feel like that's more obnoxious than weighted mapvoting

@IratePirate As much as predictable item placement is a problem, I don't think it's the problem we're actually trying to solve.

**Comment by PJB3005** [comment]
I'm working on this, but BYOND is bullshitting me hard (impossible error)

**Comment by Kurfursten** [comment]
It looks like there is already a firm majority of people behind this idea, but I just thought I'd add another :+1: to the stack. This seems like a really good middle ground for the voting system.

**Comment by uazuaz** [comment]
maybe you could do that when a map is played 3 times in a row (maybe 2?) it will not appear in the vote list.
taxi could appear in the vote list only if lowpop.

**Comment by 9600bauds** [comment]
I would also appreciate it if the voting window didn't pop up as soon as the round ends. This is for 3 reasons:

1) It gets in the way of post-shuttle griff and round-end info, which is a problem in and of itself, but also causes:
2) People voting immediately without much thought just to get the window off, and
3) People who normally would vote, not voting because they just close the window to get it off.

Essentially you're using a very intrusive pop-up to ask everyone at the worst possible time.

**Comment by ihadtoregisterforthis** [comment]
As a reminder or new information, here are polls from may last year about improving Deff and Meta respectively

http://ss13.pomf.se/index.php/poll/28
http://ss13.pomf.se/index.php/poll/29
