### ISSUE TITLE
Botany: Shitcode and other issues

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7542]
All other plants have 2 long lists, except for ambrosia plants which have 3 long lists like "kelotane" = list(1,8,1). I'm pretty sure this fucks with something.

Both kinds of nettles have "sacid" = list(0,1) / "pacid" = list(0,1) and hardcoded acid amounts somewhere else, this results in odd bugs with splicing the chems onto other plants. They also have ridiculous amounts of said acids making them quickly push out other chems at high potency due to reaching max chem capacity.

Egg-plants that produce eggs do not carry over plant chemicals into eggs, which are edible. Eggs also can't be put into a biogenerator / seed extractor even though this makes them plant products. It should have a tag indicating that the egg came from a plant to allow for seed extraction. Bonus points if chickens hatched from it poop more eggs like it.

**Comment by 9600bauds** [comment]
The long list should literally not fuck with anything from what I can appreciate. It's wrong, but the third number does literally nothing rather than something bad.

The hardcoded amount comes from the grinder code being a monumental piece of shit which I hate. Fun fact: You can get more corn oil out of corn by injecting it with nutriment beforehand. Don't even ask.

The egg-plants return a literal egg item. It's not a plant product. It's the same kind of egg you get from a chicken. I suppose you could have it inherit the chems from the plant, but then you'd essentially have a juicy 1 plant. To get egg-plant seeds, use clippers.

**Comment by ghost** [comment]
I remember there being issues splicing ambrosia plants pre botany3, could have been related to the long lists.

That corn trick sounds terrifying.

I already know about clipping seeds from egg-plants, problem is sometimes you clip a plant before it mutates, then you can't clip again. Perhaps make it reset when plant mutates species, everything else about it gets reset anyway.

**Comment by ghost** [comment]
Also another issue, plants mature on clipping, even as far as being instantly harvestable if you get lucky.

**Comment by 9600bauds** [comment]
Yeah, they actually tick process() after clipping, which means they'll probably skip 10-20 seconds. No pain no gain

**Comment by Killette2** [comment]
Funfact: The corn trick can also be done with wheat, since grinder turns wheat nutriment into flour.

**Comment by 9600bauds** [comment]
Putting this here to remind me to make plant species mutations reset clipping status
