### ISSUE TITLE
[Deff] Literally no firelocks on doors

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7545]
NICE MAP

**Comment by ihadtoregisterforthis** [comment]
Surely you don't mean this #6513

**Comment by ghost** [comment]
Let me describe the issue in more depth then.

There is absolutely no warning that opening an airlock will instantly smash your face through your ass, since a tile with a gas giant on it looks exactly the same as a tile with not even a fart. That's the entire point of the firelocks underneath every door on box.

The last round I played deff was a plasma flood, it burned out and everything looked 100% normal. Except you can't see pressure and air alarms are not in line of sight from every single door, so the pressure difference between my room and the one I opened was in the thousands.

This was true for every room on the station, meaning every airlock you opened was a diceroll on whether you will get your shit pushed it or not.

I can't believe the issue was closed last time, guess it exemplifies what's wrong with non box maps.

**Comment by Duny-** [comment]
>I can't believe the issue was closed last time, guess it exemplifies what's wrong with non box maps.

What's wrong is that a lot of people seem to prefer screaming and moaning (more or less ironically) over making valid points. Just like your first post here.
You're making a valid point now, and without your second post I would have dismissed this issue as a non-issue.
I always saw the firelocks on the same tile as doors as a nuisance preventing quick movement where and when it's needed, since airlocks themselves block atmos. I never thought about their use as a warning sign.
A non-dense type of firelock, for example some kind of holographic sign appearing on designated airlocks when there's a danger on the other side, would be a much better thing in my opinion.
As long as such a thing doesn't exist (hopefully not too long), I'll put annoying firelocks at every department exit/inside big departments to prevent the issue you described.

**Comment by ghost** [comment]
> You're making a valid point now, and without your second post I would have dismissed this issue as a non-issue.

It's your choice to plug your ears and go lalala.

How about you put them on every internal airlock like all the other maps?

There really need to be mapping guidelines to prevent things like this. I'm also pretty sure you're still using the full tile firelocks in places which are terrible to look at.

**Comment by Duny-** [comment]
Yes it's my choice to plug my ears and go lalala when I'm told "SHIT MAP", "NICE MAP", "OTHER MAPS HAVE X AND Y" and other types of constructive criticism. A choice I'm not ashamed of.

I'm not "still using the full tile firelocks", if there are still full tile firelocks it's because they weren't updated when firelocks were changed. There's only very few firelocks on deff right now anyway (the original layout was so terrible I just ended up deleting everything after complaints) so if it's the case it can't be a lot.

**Comment by ghost** [comment]
I said in places, as in there's a few. If you want to go against the flow of other maps in terms of gameplay, then at least have a rational reason for it.

The reason other maps have firelocks on every internal airlock is because opening airlocks/firelocks with even relatively small pressure differences between rooms can be fatal. It's very logical and makes sense to have on a space station. The only annoying part I can imagine is having them wrongly drawn under airlock sprites.
