### ISSUE TITLE
Robotic limbs and organs, in general

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7627]
Right now, Robotic limbs have a higher chance of failure than organic limbs, blow off on the nearest EMP, and the kicker here is is that any damage to that robotic limb counts towards (or in this case against) the users overall HP, so you can get stuck on the wild ride with 60 burn on a robotic limb, constantly being dripfed keloderma that's doing nothing for you, and there's no escape because nobody's thinking to just apply wires to your damaged robotic limb.

Made a vote on the server, and a lot of people think it's weird that an inorganic replacement somehow hurts the organic recipient when said inorganic limb is damaged.

So, how's about a rework of robotic limbs and organs?

Discussion time, what needs changing, what needs replacing, what needs fixing, and why

**Comment by Killette2** [comment]
But wires are easier to obtain than any chemicals or bandages/ointment.

**Comment by Exxion** [comment]
That's pretty irrelevant for robotic _organs_, though, as you still need surgery to fix them and surgery generally happens in medbay.

**Comment by ghost** [comment]
Robotic limbs / organs should be removed/limited to x parts from lobby character selection and buffed a lot.

**Comment by 9600bauds** [comment]
I'm pretty sure robolimbs are SPECIFICALLY intended to not count towards your overall health.

**Comment by ghost** [comment]
@9600bauds I had to physically drop in to a round earlier because somebody had 60 burn to their robotic limb, and were just stuck perpetually in the ride, so something might be a bit off.

**Comment by AutismSpider** [comment]
@9600bauds some off with the robo limbs then damage to them counting towards the overall heath now

so 60 burn on a robot leg or foot = passing out in pain form burns until its fix

**Comment by TheEliminator16** [comment]
We need a robo-limb overhaul in general. This should be part of it, but we need several things to make robo-limbs cool again
-make dismemberment easier so there's more demand for limb replacement on patients that you can save instead of just cloning
-add tier 2 and maybe even tier 3 researchable limbs that grant various boons, like giving the increased run and jump powers to cyber legs and maybe even built in magboots, for example
-emp resistance. not immunity, resistance, based on the tech level of the limb
-clearer indicators that a damaged limb is mechanical to help alleviate one of the issues in this report

**Comment by Kurfursten** [comment]
It's already extremely obvious when there are mechanical limbs present. You can't cure a shit doctor who doesn't use the health analyzer. There's nothing to be done about that. It says in big bold blue letters METAL DETECTED.

**Comment by gbasood** [comment]
Like I said in #7918 robo limbs themselves are fine, I think. What needs to be changed is robo organs, since they're currently ONLY organs that can be EMP'd.

#5669 for instance
