### ISSUE TITLE
[Feature Request] Detective Thermals

### ISSUE THREAD

**Issue by LordMyroc** [d3athrow/vgstation13#7636]
On Meta Club, the detective starts with a thermal imaging eyepatch in his locker. Could this be extended to the other maps?

**Comment by CptWad** [comment]
Im okay if it gets added to deff, but for box and taxi they would be too powerful due to the smaller maints.
Detective used to start with thermals but it was removed to nerf sec for cult rounds back in TG
That and TG's modified ling, back then, which is what we still have. Detective could walk down a maint tunnel and see scientist Mctoxins sucking off his RnD buddy.
It would work for deff as deffs fuckhuge maintenance shelters enough. Box however has the second worse maint tunnels.
Thermals are a game changer.

**Comment by Kurfursten** [comment]
I wouldn't like to see it on the other maps. It makes Meta different, and as CptWad points out, it is very powerful.

Plus I already see the HoS looting the detective's office for the eyepatch often enough.

**Comment by ghost** [comment]
Thermals royally fuck over any stealth antags. Lets not.

**Comment by 9600bauds** [comment]
>stealth antags getting a dick up their ass

I fail to see the issue

**Comment by ghost** [comment]
> I don't like it so lets ruin it

**Comment by 9600bauds** [comment]
Aren't you the guy that ruined as many rounds as he could because he didn't like the admins?

**Comment by ihadtoregisterforthis** [comment]
I suppose he doesn't mean stealthy antags like parapen and space the body, but stealth based antags like lings, vamps or raiders, maybe nuke ops on some situations.

I vote against thermals in every map for keeping map variations and allowing fun.

**Comment by Probe1** [comment]
Fuck no.  Its acceptable for one map because maps need unique features but its not a good idea to begin with.

**Comment by Kurfursten** [comment]
As much as I agree with your sentiment Probe, it probably wasn't worth reviving a 4 month old discussion

**Comment by Probe1** [comment]
Whenever you see me do this its because I'm looking at all the map issues and trying to find a way to close em.

**Comment by 9600bauds** [comment]
What's the problem in reviving an old discussion

**Comment by Probe1** [comment]
let the ded rest
