### ISSUE TITLE
I believe it's nigh time for something to be done about the AEG

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7680]
It's relatively easy to mass-produce it and most people agree it's the best gun in the game because it's a self-recharging taser (I believe most complaints about stuns center around THIS gun specifically) that has lethal capability as well.
Having used it a bunch myself, honestly it's a spray-and-pray just keep firing stuns down a chokepoint experience, then switch to lethals once they go down. I wouldn't miss it if it went away. It's also a bit obscene for Blob, too.

Things that could be done:
- Make the Protolathe spit out an "Advanced Energy Gun Mod-Kit" that requires an egun as a base item to be crafted, to make AEGs mostly a security or command only item
- Make it irradiate people like it used to :^)
- Separate the laser and stun ammo count, have stun ammo not self-recharge
- Make it irradiate people like it used to :^)
- Improve the lockbox system to make it harder to abuse than "just touch a protolathe"
- Make it irradiate people like it used to :^)

**Comment by Cisrox** [comment]
I agree with making irradiating people.

**Comment by 9600bauds** [comment]
It would make it kind of worthless for Sec, and would only put a "you need to powergame a pillbottle of arith" barrier for Science to abuse it

**Comment by Shadowmech88** [comment]
Recharging guns, of any kind, usually end up being the best in the game. Even if it had no stun, it'd still be the best energy weapon because of its recharging ability.

I think the problem with it is how easy it is to aquire. All the other self-recharging guns are relatively rare/important, such as the captain's laser gun and the spur. Contrast this with the aegun, which can be mass-produced within half an hour if Mining and Science take their time.

I think it just needs to be made harder to acquire, either by raising its protolathe cost or removing it from the protolathe altogether.

**Comment by CptWad** [comment]
I was thinking about unique protolathes that sync with the main server, in each department, that produce unique items for each department
Or just make it require access to print it in the first place (from the menu), removing the need for lockboxes too

**Comment by 9600bauds** [comment]
What about having lockboxes send a message in Sec channel when they get broken open?
"A secure lockbox containing Advanced Energy Gun was broken open in Toxins Storage (193,92)."
Then if Science IEDs a lockbox open they'll have to face Sec over it.

**Comment by CptWad** [comment]
>Nuke ops/xenos come
>sec gets chat spam whenever science prints guns and opens them
nah

**Comment by 9600bauds** [comment]
and the preferable alternative is science to not be able to get the guns at all during newcops/xenos?

**Comment by CptWad** [comment]
In xenos case by the time xenos are on station its just a bit of leg work on sciences end to ask security. Not to mention sec can just stockpile the disks and hand them over when the situation demands it.
Or just go to the HoP and get/buy a gun permit and armory access. Like they could/should now.

**Comment by 9600bauds** [comment]
That's a really, really, really big stretch.

Besides we're talking about maybe ten lines max worth of chat spam, and all of it is very relevant info that Sec definitely wants to hear.

**Comment by CptWad** [comment]
Will it fire when its emagged then? Or only blown up/shot? Will this be extended to cargo weapons crates?
Having sec be informed every time someone breaks a crate will only lead to science being the next cargonia

**Comment by 9600bauds** [comment]
Probably not when emagged, we don't want antags to be fucked over (then again, Science antags have it easy enough...)

> Having sec be informed every time someone breaks a crate will only lead to science being the next cargonia

That sounds excellent to me

**Comment by CptWad** [comment]
I'm fine with cargonia antics
but cargonia does not have rabid slimes, bombs and whatever horrors xenoarch finds
There will be at least one or two idiots who blow up all of sec (either the members or the department) because muh sciencia

**Comment by icantthinkofanameritenow** [comment]
Scientia is already Cargonia, they just rebel less due to being easily distracted by bombs. And I say this as someone who mains Science.

**Comment by ghost** [comment]
Radiation damage is very easy to ignore since you can just eat a pill with 30u of each anti rad chem and spam your gun like nothing. Considering science already rushes a chem dispenser this will achieve nothing and make it only more exclusive to science.

I very much like the first option of it being a mod kit for eguns, this will make science actually interact with outside world to get the op guns. They already mine their own ores half the time thanks to outpost.

I mean it's a bit silly I can play as a geneticist and reliably get an advanced egun few minutes into round.

**Comment by Kurfursten** [comment]
The mod kit idea is interesting because all the eguns are on heads and in the armory.

It does make EGs/AEGs a hell of a lot more precious in blob, too.

**Comment by LordMyroc** [comment]
Replace AEGs with a small self-charging power cell which can replace the cell in any energy-based weapon. Also increase the amount of tech required and make it cost more types of minerals.

This could also open up room for additional types of cell replacements for weapons. I'm sure sec officers would love to be able to extend the capacity of their shitty five-shot tasers.

**Comment by clusterfack** [comment]
Mass produceable rechargeable weapons was a mistake

**Comment by icantthinkofanameritenow** [comment]
Agreed. LordMyroc's idea would just change how the infinite charge weapons are made, and even if you made them require Phazon it would be nothing that a material synthesizer, a miner or two, and perhaps an Engiborg couldn't make irrelevant. In fact it would make things worse since they'd make all of their guns self-charging and thus make the captain's own laser worthless as anything other than a traitor objective. 

Instead, it should make an AEG modkit, but in a way like a vending machine inasmuch as only a specific number of them can be made in total. I imagine that 6 or 7 would be a good maximum- 5 or 6 for a fully staffed security department and the HoS,  and one for the HoP. (The Captain should just get a stun function added to his own laser, it's made to be deliberately OP anyway.) 

Without a hard cap on their numbers, they'll still be mass-produced- it'll just take slightly longer to do so since they'll have to mine more materials and ask Cargonia to order guns- and really, when do they not order guns at the first chance they get?

**Comment by 9600bauds** [comment]
I don't consider it likely that massive-scale departmental cooperation between Science and Cargo will happen with any consistency, I consider it a lot more likely that Science wil just make assault rifles instead

**Comment by icantthinkofanameritenow** [comment]
@9600bauds

That might be a problem farther down the line, but one thing at a time.

**Comment by LordMyroc** [comment]
@icantthinkofanameritenow How do you propose we put a limit to the amount of items that can be made through a machine that by its very design is made to mass-produce things?

The biggest issue with AEGs in my opinion is the fact that both their research requirements and their resource costs are very meager for how powerful they actually are. Its one of the first things unlocked when researching weapons tech (requires Combat 3 and Power 3, even the XCOM laser weapons require more research and are almost never used in place of AEGs), and only needs metal, glass, and a small amount of uranium if I remember correctly. So basically any half-competent scientist can get the prerequisite research done and then only need to wait for a single miner shipment that contains uranium in order to produce more AEGs than anyone will ever need.

Bumping its research requirement to at least Combat 6 (which requires a Combat Shotgun, meaning you'd have to interact with another department in order to get the sufficient tech), plus introducing more minerals to their costs and in larger amounts (so you'd require a steady supply of diamonds, gold, and silver, instead of being able to print at least 20+ of the things with just 10 uranium sheets), and then finally requiring a base gun to actually modify, sounds like a decent tradeoff for having a self-recharging energy weapon in my opinion.

AEGs are powerful, but they aren't adminbus-weapon-tier powerful. They're just way too easy to get for what they do. Keep them in the game in some function (whether as a stand-alone gun or as a modkit), but make them the end-game of weapons research instead of having it become available almost right off the bat.

**Comment by 9600bauds** [comment]
I'd just like to interject for a second and say that giving it a high research cost does NOTHING when R&D is routinely maxed 5 minutes into every shift, and giving it a high material cost does NOTHING when miners routinely wheel in more than will ever be used within the first 20 minutes.
Even if you somehow make research actually matter, and you make materials actually matter (miners will get a shitton of uranium in 3 minutes if it means getting their guns), then you're still making them mostly Science-exclusive.

**Comment by LordMyroc** [comment]
Combat 6 is, in my experience, almost NEVER achieved in most rounds in which RnD is staffed, simply because of the Combat Shotgun requirement. That, and it's still very easy to run out of diamond if you're printing too much of things that require the stuff, unless you got a borg playing matsynth slave - which, again, is a very rare occurence (and is in itself an issue of its own if you ask me).

**Comment by Shadowmech88** [comment]
It's possible to get combat 6 using nothing but mining minerals and items printed in R&D/Robotics. You can get to combat 5, then use a tesla relay to get illegal tech 1, then print additional illegal items until you reach illegal tech 5, at which point you can print a chemical mask to get to combat 6.

**Comment by FudgePucker** [comment]
Having a modkit would be fun.
Trade the emitter in xenoarch to cargo to have a trade relationship.
Separate cargo and sci are annoying, but together they can rule the station

**Comment by Imagebard** [comment]
Revive this discussion.

What if AEGs were a w_class higher, or needed both hands to operate? They're supposed to have a nuclear reactor inside, so it makes sense.

**Comment by CptWad** [comment]
in case the AEG runs out of juice
thats why people carry like 3 so they never run out of lasers

**Comment by PJB3005** [comment]
One idea is to lower the damage from the AEG, it'll make them less valuable over other, both more expensive and NOT RECHARGING options.

I also really like the idea of making taser shots NOT recharge.

**Comment by Imagebard** [comment]
>in case the AEG runs out of juice

You're taking the question too literally.
Less damage could work but as long as you have unlimited stun shots, you can stun someone.
And if you can stun someone, you can kill someone. You could even use a 5 damage weapon to kill that someone.

**Comment by icantthinkofanameritenow** [comment]
So how would the modkit be made exactly? Same material cost means that there would be a ton of them.anyway, cost should be made a real factor here given that plenty of much weaker weapons are more expensive to build and take longer for the protolathe to complete.

**Comment by 9600bauds** [comment]
The real cost would be the energy gun. Material costs mean basically fucking nothing. The greatest cost is the one that you can't just print in the protolathe.

**Comment by icantthinkofanameritenow** [comment]
@9600bauds

Cargonia is not exactly known for its restraint in ordering a shitload of guns under the flimsiest of pretenses. But it's the best we can do for now.

**Comment by icantthinkofanameritenow** [comment]
Welp, here's that PR you wanted. 

#8343

**Comment by 9600bauds** [comment]
Sweet
