### ISSUE TITLE
Ventcrawling controls like trying to catch a greased pig, too easy to accidentally pop out of a vent

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7685]
Combine no icon centered around the center of the screen to show where you are, going a little fast, features, an atmos piping system not designed around ventcrawling, and instant popping out of a vent: You end up accidentally coming out of vents constantly.

Ways to fix:
- Make coming out of a vent take a couple of seconds, giving you time to move away
- Make coming out of a vent require clicking the vent (bad, unintuitive)
- Change all of the atmos piping to better accommodate ventcrawling (nobody wants to do it, does not fix the underlying issue, will not happen)

**Comment by ihadtoregisterforthis** [comment]
Other alternative is mapping #5949

**Comment by 9600bauds** [comment]
Added alternative 3

**Comment by gbasood** [comment]
I agree it could be better, but:
- Clicking the vent to exit when something's on top of the vent can be painful.
- Mapping to fix it only solves PART of the problem and is a lot more work (fuck you box)
- Forcing things to take time to exit vents can be very problematic when something that has entered a vent needs to exit as soon as possible in order to live (~~borer~~ xeno/monkey/diona in an overpressurized line)

**Comment by Ephx1** [comment]
Last I checked atmospherics in pipes don't apply to borers.
But it would be an issue with xenos in a hot pipe.

**Comment by Kurfursten** [comment]
Amusingly xenos have the same heat tolerance as a human - both damage rate and heat levels.

**Comment by uazuaz** [comment]
adding an icon to show your actual position would help, something simple like a circle or a crosshair should work.

**Comment by ihadtoregisterforthis** [comment]
Borers too need to leave as soon as possible.
