### ISSUE TITLE
Rework or kill the bandolier

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7704]
In its current state, it is not only worthless, but broken. Putting anything in it always opens its inventory, over any other inventories you might have open.
Also, everything it can do the plastic bag can do better. You have to give up your exosuit slot to wear the bandolier and it only holds shells. The plastic bag fits on your belt and holds anything of w_class 2 or below, shells included.

**Comment by Shadowmech88** [comment]
The bandolier should really be able to be applied directly to a jumpsuit like the shoulder holster.

**Comment by Exxion** [comment]
I actually like that idea as long as there is a quick way to remove shells from it when it's like that

**Comment by Shadowmech88** [comment]
Perhaps clicking it with an empty hand removes a shell, and dragging it onto your sprite removes the bandolier from the jumpsuit.

**Comment by Exxion** [comment]
I think there's already a remove accessory verb that would take the bandolier off

**Comment by Kurfursten** [comment]
The bandolier doesn't compete with the plastic bag in the same way that the backpack doesn't. You can wear both at the same time for way more shells, which is actually pretty good for the traitor bartender.

**Comment by Shadowmech88** [comment]
The problem is that the fact that it takes up the exosuit slot means if you want to wear a bandolier you have to forego very important and useful items like armor and hardsuits.
There is no situation where someone would wear a bandolier instead of wearing armor/a hardsuit and just storing the shells in a box in their backpack instead. This makes the bandolier inherently inferior to backpacks/boxes/plastic bags in a combat scenario, which is a problem.

**Comment by Kurfursten** [comment]
Sure: the bandolier is competitive with the bartender's armor (they share a slot). If there was a **need** for more shells than fit in the plastic bag, bartenders would have to make a tough choice between the bandolier and the body armor, but as you point out - they don't because there's no need for more shells, ever.

But the bandolier isn't inferior to backpack/box/plastic bag, **it's inferior to body armor** (the item it shares a slot with). It's non-competitive with the storage items because they don't share a slot. Those items are better in most situations solely because they don't share a slot (as you point out). So you're left in this situation:
- Solution A: Make the bandolier hold more items to be competitive with other storage it doesn't actually compete with. This doesn't solve anything because as we have established **there is no need for additional shells beyond the plastic bag every bartender wears anyway**.
- Solution B. Make the bartender not fit in the exosuit slot. This doesn't solve anything because as we have established **there is no need for additional shells beyond the plastic bag every bartender wears anyway**. Remember: there's nothing competing for the bartender's belt slot: he'll always have that plastic bag (not like the engineer's old dilemma of plastic bag vs tool belt). So you're just giving him a bunch of extra storage space that it has been established he doesn't need for shells.

**Comment by Shadowmech88** [comment]
It would enable the bartender to store other things in his plastic bag instead of using it for shells, now that he would not have to choose between having extra shells and having armor.

In any case, this isn't just relevant to the bartender. Isn't it possible to acquire bandoliers for Security via Cargo?

**Comment by Kurfursten** [comment]
As you point out though he's never making the choice between extra shells and armor. If he was, he'd be occasionally picking the bandolier (which would be good, encouraging a tough strategic choice - but he's not making that presently).

On the note of security: if you want to make bandoliers not take up a slot at all, why not cut out the middle man and just make the shotgun hold 8 shells? If having a bandolier is just 7 free shells with no slot and there's no reason not to order one from Cargo every shift AND it comes in the same crate as a shotgun... why not just make the shotguns hold more shells?

**Comment by Shadowmech88** [comment]
The bartender isn't making the choice between extra shells and armor, he's instead making the choice between wearing armor and being able to store miscellaneous items in his plastic bag. Storing ammo in the bag means he can't, for example, store a set of tools in the bag.

Combat shotguns already hold 8 shells and are pretty much the only shotgun Security ever uses. It's true that making bandoliers attach to jumpsuits essentially gives seven free shells with no downside, but as it is Sec never ever uses the bandolier because it's never worth it for Sec to sacrifice armor for more ammo space.
Would there be any way to add a drawback to wearing a bandolier that isn't the sacrifice of the exosuit slot?

**Comment by Exxion** [comment]
1. The bartender does  not start with a plastic bag, though it's easy to find one
2. The bartender starts with six shells. A plastic bag can hold 21. Honestly the bandolier isn't a necessary item at all unless it is somehow made to be faster/easier/more convenient to remove shells from.

**Comment by Shadowmech88** [comment]
> the bartender does not start with a plastic bag

Is there any reason why? I thought everyone started with one.

**Comment by Kurfursten** [comment]
No service, engineering, or medical job starts with one.

**Comment by Shadowmech88** [comment]
Alright, but why not?
Was it considered too OP to let them have one?

**Comment by Exxion** [comment]
I understand engineering and medical because they get belts
But why not service?
