### ISSUE TITLE
Blob breaking a disposal chute while you are in it nullspaces you

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7751]
Can't fucking believe I forgot to report this yesterday when it happened

**Comment by ghost** [comment]
@exxion CONFIRMED for github antagonist 

Ban him for helping the feature freeze please

**Comment by invoid9** [comment]
Same thing happens if you're in disposals and Nar Nar comes over.

**Comment by Exxion** [comment]
Sounds like SOMETHING's missing a Destroy() proc, or at least a good one.

**Comment by uazuaz** [comment]
something similar happened to me as a MoMMI some days ago.
i was inside the disposal bin, used the welding tool on the bin from the inside and got nullspaced; i can assume that this happens when you're inside the disposal bin and the bin gets disconnected from the pipe. can't test it at the moment because the testing server is pretty fucked up right now, as you can see in the picture: this is what you see when you're in-game on the testing server.

![scrnshot1](https://cloud.githubusercontent.com/assets/6170726/12403496/75fd2f56-be34-11e5-968e-6d673f04bc55.png)

**Comment by Exxion** [comment]
Nice

Yeah, sounds like the disposal bin is missing an instruction to drop all contents in its Destroy()
Now who wants to nullspace the nukedisk?

**Comment by FudgePucker** [comment]
Holy shit is that the old goon splash screen and krampus?

I want what ever the test server is tripping balls on.

**Comment by Exxion** [comment]
Go ahead. You have a local copy. Update it, _don't_ recompile, and start a local server.

**Comment by PJB3005** [comment]
@Exxion not how any of this works.

What you're seeing in that screenshot is RSC corruption, it happens sometimes.

AFAIK it's just bad luck, and a clean recompile fixes it.

**Comment by Exxion** [comment]
Oh
Well it's quite similar to what happens if you don't recompile, if somewhat more extreme

**Comment by uazuaz** [comment]
about the broken test server:
i tried to enter it many times during these 3 days, but it was broken every time and it's still broken right now.
i know for sure that the server restarted at least 2 times.

**Comment by PJB3005** [comment]
@uazuaz yeah but did it actually recompile?

@N3X15 left /vg/ again and his watchdog IRC bot isn't in the channel anymore so I think he stopped automatically recompiling the test server.
