### ISSUE TITLE
Many levers are not unidirectionally locked at shift start

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#7777]
On metastation, both cargo bay and and the mail room levers

On box, cargo bay levers

Probably others as well, needs more testing to determine all of them so they can all be changed at once

**Comment by Exxion** [comment]
#7747

**Comment by uazuaz** [comment]
#6923

**Comment by Kurfursten** [comment]
Neither of those lists metastation issues, re-open

**Comment by PJB3005** [comment]
Pretty sure it's only map specific in the way that the map specific part is shitmapping.

@probe1 removed any and all specific code from oneways, which broke them, the ones that do work are just instances (that's my theory).

I'll reopen it anyways.

**Comment by 9600bauds** [comment]
That was me because I thought that the switches had their convdir hard-set in mapping, since all conveyor belts do have their individual directions hard-set in mapping AND their snowflake one-direction stuff set in mapping
will address now

EDIT: Turns out that some of these simply didn't even use the subtype, so yes, it's still fucked

**Comment by PJB3005** [comment]
@9600bauds I think exactly the ones that _didn't_ use the subtype stayed onedir (since the map instance remained with the variables edited).

**Comment by 9600bauds** [comment]
Basically I thought stuff was awful when it was only half-awful and only fucked up the not-awful part
