### ISSUE TITLE
Adminghosts can't pull fire alarms, including party alarms

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7810]
(WEB REPORT BY: dylanstrategie REMOTE: 158.69.55.2:7777)
This breaks literally everything everywhere ever, please fix it rapidly

**Comment by gbasood** [comment]
how dare someone break this essential feature

**Comment by TheEliminator16** [comment]
There are like a million machines that adminghosts can't use
Off the top of my head, I can think of the intercom and the APC, but I know there are more. Being able to use those as an adminghost would make bus much faster, because you wouldn't have to spawn a mob, hop in it, and then use the machine.

**Comment by gbasood** [comment]
Wait isnt this not a thing
