### ISSUE TITLE
Atmos is buggered

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7835]
Why has nobody reported this.

OOC: DragonBro: Temperature doesn't flow, air doesn't flow, telecomms dies about 2 minutes in
OOC: DragonBro: A feature freeze, and somebody manages to break the core thing ss13's built on during it

**Comment by SysadminJeroen** [comment]
@DrCelt Do you know when this happened? Where does temperature not flow because I think that it was still flowing a couple days ago.

**Comment by CptWad** [comment]
Ive been seeing air hang a bit when exposed to space (Usually when npc mobs break shit) causing an exposure but not sucking the air out. Usually a player touching stuff around the breach activates it and that will suck the air out of the hallway and anything connected. For tcomms dieing it must have happened overnight because it was working fine. The only thing I do know is a deff issue I never got around to reporting where theres an improper alarm in the tcomms room that wants it to be a normal room and not a coldroom

**Comment by Zth--** [comment]
#7700
