### ISSUE TITLE
Add furniture?

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#7946]
Do we even have furniture in the game? Or do we have to add some, because I want to build cozy home.

Here is an example of the best I could do with the current furniture options we have now.
![cozy house](https://cloud.githubusercontent.com/assets/5650556/12689413/ba4f3ca2-c6aa-11e5-9823-76d5f1375a77.png)

**Comment by Exxion** [comment]
Well what other furniture do you want? Be a bit more specific.

**Comment by AlphaBuffalo** [comment]
Idk, maybe more table ideas, only one off the top of my head I wanted when I was doing this was a coffee table, and a kitchen sink.

**Comment by AlphaBuffalo** [comment]
Also, a constructible stove, or fridge, as well as a way to pot plants, desk lamps that dont take up an entire table, and TVs and mirrors constructible

**Comment by ghost** [comment]
Code it!

**Comment by Exxion** [comment]
Honestly spriting it is the bigger difficulty for most or all of these

**Comment by AlphaBuffalo** [comment]
If I was a L33T spriter I would help, but since my computer skills only allow me to barely figure out how windows works, I have to ask people

**Comment by AlphaBuffalo** [comment]
Well, the only things we would need to sprite is the coffee table, kitchen sink, and smaller desk lamps, everything else already exist in game, just need a way to construct them

**Comment by Zth--** [comment]
If you sprite it (or get the sprites somehow) I'll code it. I'd like to see more furniture too

**Comment by ghost** [comment]
https://www.dropbox.com/s/8xj267ofepppq46/FO13%20-%20couch.dmi?dl=0
https://www.dropbox.com/s/fx0ll99f3ki1jc4/Pool.dmi?dl=0
I'll also sprite some furniture sometime tonight.

**Comment by ghost** [comment]
@Nienhaus at it again the absolute madman

**Comment by ghost** [comment]
I updated that couch dmi
https://www.dropbox.com/s/8jdzcbycyk5b3gs/Pool%20Table.dmi?dl=0 Better pool tables.
https://www.dropbox.com/s/11o7t5x92j1h2zt/fish%20tank.dmi?dl=0 Fish tank
https://www.dropbox.com/s/1vu9rrwb6ln88us/Fishtank.dmi?dl=0 Older fish tank
https://www.dropbox.com/s/71yk6dygdviwtil/Couches.dmi?dl=0 Couches
https://www.dropbox.com/s/rf5cez21e1lb8sh/Bar%20items.dmi?dl=0 This has a round table, different stool, and wooden table.
https://www.dropbox.com/s/c12ws18dwwiclja/Road%20thing%20%2B%20fence.dmi?dl=0 This is a road and fence (I'm include this for @DrCelt because I'm to lazy to link it to him)
https://www.dropbox.com/s/yb6rvmlvzj22zxt/Furni.dmi?dl=0 Some generic furniture.
https://www.dropbox.com/s/o5a9cnq7vbknetu/Astromech.dmi?dl=0 Astromechs are furniture right??
https://www.dropbox.com/s/c0iu36yfr5nmb82/Gun%20cases.dmi?dl=0 Some old gun cases.
https://www.dropbox.com/s/dcdy9n42ce8okso/Wood.dmi?dl=0 This is a bunch of stuff made of wood, not sure if useful or not.
https://www.dropbox.com/s/ljldcip4zpsat6h/Generators.dmi?dl=0 I think this one is a little off the ball but there they are.

**Comment by ghost** [comment]
I also want to include this on the account that more toys are always needed.
https://www.dropbox.com/s/9wcpypentioaawb/209%20toy.dmi?dl=0
Also make suggestions, with images and the such.

**Comment by Zth--** [comment]
Damn I love that fishtank. I'm gonna start working on this as soon as I can.

**Comment by Zth--** [comment]
Do you think you can sprite some cool mulebots? Those cargo trains from goon are cool.

**Comment by ghost** [comment]
Any thing you want them to look like in particular @Zth-- ?

**Comment by Zth--** [comment]
Not at all

**Comment by ghost** [comment]
That makes things a little trickier.
