### ISSUE TITLE
In combined antag modes (THAT ARE NOT MIXEDMODE), antag roles can be overriden by other antag assignments

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8000]
Example:
Traitor assigned
Traitor re-assigned to ling
Ling re-assigned to traitor

In that case the ling is probably still a traitor+ling but still what the fuck

**Comment by ghost** [comment]
@deitylink

**Comment by gbasood** [comment]
I don't know the state of antag code anymore, but any antag code should return 1 if successfully antag'd and 0 if antag target is already antag, and gamemode code should handle that appropriately.

Best fix 10/10

**Comment by clusterfack** [comment]
You waste #8000 on this

**Comment by gbasood** [comment]
you're right clearly I should've made an issue saying "FUCK YOU DUNY"

**Comment by DeityLink** [comment]
Mixed mode is a work in progress. That's why it currently isn't in secret and that when admins force it should be so we so we can get feedback. Alright? Good.

On that topic, I am completely overhauling the mind.special_role var, since it hadn't been created with the possibility in mind that an antag could have multiple roles at once. Which is taking time because there's like 1000 uses of it in the code. So there's that.

Beside that, something bothers me about that issue. You're talking about antag assignment at roundstart? Multi-role antags shouldn't happen at round start. A while ago we had a 16-roundstart antag round (thank you @DrCelt ) and none of them had more than one role.

**Comment by gbasood** [comment]
@DeityLink I explicitly said NOT mixed mode.
This specific instance occured in Traitor+ling.
![](http://i.imgur.com/19NzzkY.png)

**Comment by ihadtoregisterforthis** [comment]
Let's call that "combined"

**Comment by DeityLink** [comment]
> In combined antag modes (THAT ARE NOT MIXEDMODE)

er, what? you mean for example when you force a player to become vampire during a ling round?

Well that's pretty much the same issue.

**Comment by gbasood** [comment]
@DeityLink 
Traitor+ling mode. The literal mode called Traitor+ling.

**Comment by DeityLink** [comment]
As said on IRC I know why it's borked. I'm working on it.

**Comment by PJB3005** [comment]
ANTAG.

DATUMS.

WHEN.

**Comment by gbasood** [comment]
no but seriously the changes @DeityLink is talking about are about half of what it would take to transition to an event-based gamemode system as well I'm excited

**Comment by DeityLink** [comment]
Mixed mode in itself is a good framework for that event based game mode you're talking about.

**Comment by Exxion** [comment]
I rather doubt this is still an issue, but if it is, it's for a totally different reason, since the code has been completely rewritten
