### ISSUE TITLE
Telekinesis bugs

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8103]
Your worn ID access is used to open airlocks/press buttons far away from you, this seems harmless until you realize you can open AI shutters in its core with proper access.

Can't open/close firelocks from distance even though they are not on lockdown.

You can teleport IDs using the ID console. Pulling out IDs from it puts them into your hand regardless of distance to the console. You can steal the captains spare very easily.

**Comment by Ephx1** [comment]
What's wrong with the first one?

**Comment by ghost** [comment]
If first one is fine then by logical deduction the teleporting ID must be fine, since both take the ID to/from your hand and use it at a distance.

**Comment by Ephx1** [comment]
I think that's more just a balance. Airlocks also require you to have proper access with telekinesis, which I'm guessing it's possible for the door to detect you at a distance?
Teleporting ID can be done straight through walls and I'm fairly certain it's not intended, something to do with adjacent checks? Since you have telekinesis it probably just ignores that and pops the ID in your hand.

**Comment by Shadowmech88** [comment]
The first issue, though it may be unintended, honestly seems more like a feature.
The second issue no longer happens.
The third issue was apparently fixed by #12903.
