### ISSUE TITLE
Found a wonderful bug related to the supermatter.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8107]
I wasn't even sure if I wanted to report this. But testing #8099 with the supermatter, I got hallucinations. Nothing wrong with that, really, I expected to. But I thought to myself, here, those hallucinated doppelgangers are annoying, can I kill them with a supermatter?
Yes I can.
Does it power the station? Yes it does.

**Comment by PJB3005** [comment]
Feature

**Comment by Killette2** [comment]
You don't understand.

What if the hallucinations were actually ghost. They are literal carbon copies of whoever is existing on the station. This effect has been caused from overexposure of plasma, and as tiny harmless particles float through the stations airways, they take on the form of any life force on the station almost as if they want to become that on their own. When hallucinating under the effects from the supermatter, LSD, spiritbreaker, or an excrete that changelings can produce, you are able to see these particles now that your vision spectrum has ascended. They have always been coming for you, whacking you with whatever item the person that they have been impersonating was holding when they last floated around them. They need to get rid of the real thing, but why? Jealousy of not fully existing in this functional world created by a civilization of beings? Why would something, a by-product of plasma mining, care about what's around it? They are trying every single round to bring themselves to existence, trying to get our attention. They've been watching us, mimicing our actions and features. However this 4th state of matter is not immune to everything in our corporeal world, when sucked into extreme gravitational wells like blackholes or singularities, they too become stuck in the void inside. When the particles, capable of passing through other sources of matter, collide with another wonder of nature, the supermatter, they are transported from the byproduct they once were to the plasma gas itself.

This would explain why that them hitting the supermatter would generate power. Maybe it happens more than you can see, but it's hard to tell since they aren't ever alone. They're always around somebody. Trying to reach out, and become something more.

**Comment by Imagebard** [comment]
Killette please go

**Comment by AlphaBuffalo** [comment]
I've seen it happen too, I had hallucinations and one of them slammed into the shard

**Comment by Exxion** [comment]
I especially like when you can sometimes see other people's hallucinations

**Comment by FudgePucker** [comment]
@Killette2
What if we play as the plasma particles and the hallucinations are the real inhabitants of the station.

I need some shrooms or acid. Anyone selling?

**Comment by Probe1** [comment]
HA HA HA HA

HAHAHA

**Comment by 9600bauds** [comment]
won't fix
