### ISSUE TITLE
Better use of mailing system on Box and Taxi

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#8186]
I noticed that Defficiency and Metaclub have both a specific mail outlet for untagged parcels; this way, if someone from anywhere on the station needs to take an item somewhere, they can just wrap the item (there are package wraps in almost any department), take a pen, add a note on the parcel (for example, "send to RnD") and put it in a disposal unit; the parcel will exit from the mail outlet instead of the regular disposal outlet:
at this point, the cargo tech will (hopefully) notice the parcel (better if you just yell at him via radio/message him via PDA/requests console), move the mouse on it to read the note, add the tag with the destination tagger and send it via disposal mail.

I like the idea very much, so why do not use it on Box and Taxi too? Especially for Taxi, sometimes could be very frustrating to walk around stations to take/bring an item, so using this system would be very useful.

I tried to modify both delivery offices on box and taxi to add a mail outlet, trying to not waste any room space (you just need to add a Wrapped Sorting Junction before the disposal outlet):

![mail](https://cloud.githubusercontent.com/assets/6170726/12931988/c428f3ce-cf80-11e5-9ea9-d6c9858e2e8a.jpg)

i noticed that the other guy on the server opened an issue for this last detail: #8183

P.S.: talking about cargo, reminder about this too: https://github.com/d3athrow/vgstation13/issues/6800

**Comment by 9600bauds** [comment]
I like it

**Comment by SonixApache** [comment]
Hey, this is how it used to be actually.

**Comment by ihadtoregisterforthis** [comment]
Only fresh and naive cargo techs take care of the packages that come with the trash. This will be really handy.

**Comment by Kitfox88** [comment]
:+1: :100:

**Comment by ghost** [comment]
The Boxstation Mail system broke a while ago due to lack of maintenance, notably because few people know how the mail system actually works, and was finally pruned in Duny's Cargo remapping

Abumblingidiot never added proper mailing to Taxi, although he did add that Goon-esque off-station disposal sorting system due to Taxi being Taxi

Needs someone who is competent with the mailing system to re-introduce it without lowering the quality of the map. Ever since we have 500x500, only time and dedication is the limiting factor here

**Comment by nuklearcellphoneg** [comment]
# Do it
