### ISSUE TITLE
Rename Feature Request to When You Code it

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8219]
Saw this on gitlab a while back was reminded by #8206 - do this please or people will think their ideas will be coded when 95% of the time they are not

Inb4 tagged with feature request

**Comment by Shadowmech88** [comment]
I kind of like this idea.
Other coders will still be able to peruse feature requests using the new tag, and non-coders will not feel as entitled to have someone else code their thing.

However, it may also prevent people from making the feature requests at all due to the fear that they'll never get coded, which would be less than ideal.

**Comment by 9600bauds** [comment]
I just change the label's name, tag it, and change it back for spectacular issues that deserve their own tagging message.

That said though I don't think this is a good idea, it's a joke at someone's expense (hint: not always the guy that makes the request).

**Comment by ghost** [comment]
I think recent tagging is getting a bit silly, with tons of "it's loose" and similar.

Totally not pointing fingers @9600bauds

**Comment by 9600bauds** [comment]
IT'S LOOSE is our stand-in for "High Priority" "Important" "Oh Fuck" and similar

thankfully I haven't been abusing it ;^)

**Comment by Zth--** [comment]
Yeah, it's loose tag should be rarely used and with priority bugs...and it's currently being used as a joke tag
