### ISSUE TITLE
Proposed stun nerf that isn't easy to code but suprisingly uncontroversial.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8220]
Have people shot by a stun not necessarily (50%?) drop their weapon, but if they're already on the floor they will.

It's easy to code, but doesn't get to the root of the stun problem. Regardless, it's a step in the right direction .

**Comment by ghost** [comment]
> rng is a step in the right direction

**Comment by 9600bauds** [comment]
shhhhhh you'll summon sarca

**Comment by Exxion** [comment]
> extremely easily coded

Please
Tell me how
Because I'm pretty sure you auto-drop everything that you _can_ drop when you are lying down

**Comment by ghost** [comment]
I think he means people would retain the ability to use items while they have them in hand and are lying on ground. Which would be pretty awesome for ambushes.

**Comment by Zth--** [comment]
It's ok to drop stuff when you are pushed or weakened. But the problem here is that if you're lying down you can't use your hands to pick up or hold things. It would be cool to pretend being stunned and shoot from the floor

**Comment by Exxion** [comment]
Yes, but currently you _always_ drop your items when you lie down and changing that to only happen under certain circumstances would not be extremely easy
Not necessarily hard, though

**Comment by Duny-** [comment]
If you want rng to fuck you over during combat just play xcom fam

**Comment by ghost** [comment]
@Exxion 

> Yes, but currently you always drop your items when you lie down and changing that to only happen under certain circumstances would not be extremely easy

You know that Glue does this exact thing? Just change the part that checks for glue.

**Comment by ghost** [comment]
Custom vote started by DrCelt.
A proposed solution to fix stuns: If you are stunned while standing up, you do not necessarily drop what's in your hand, but if stunned again while on the floor, you do.

Vote Result: Yes, but only if it is not up to RNG whether or not you drop the item with 17 votes
     Yes, this is a good idea had 2 votes
     No had 2 votes

**Comment by Shadowmech88** [comment]
If not RNG, then what?

**Comment by Ephx1** [comment]
Admins will now have to work round the clock to decide who wins.

**Comment by ghost** [comment]
It could just be based on how much damage you have or how much pain you're in. Another preliminary vote says people are against RNG, and any attempts to introduce even a "weighted" RNG system would be highly controversial, so we should avoid that. Anyone any ideas?

**Comment by kilkun** [comment]
Idea, why not implement a system similar to goon?

Two states of being on the ground, "stunned" and "knocked down". While knocked down, the payer doesn't drop what's in their hands, and can still interact with objects, but is otherwise immobile. This occurring maybe x of the time a stungun like a taser or egun is used, where x is dependent on health, chems in the system, and a base of 50%, and given if the roll is failed the player is stunned as well. Making pushes knockdown adds another layer in hand to hand combat that a knocked down enemy with a weapon is still dangerous, and makes actual disarms useful.

Of course that's going to be "hard to implement" so much of the codebase is antiquated old-code, and it's within those depths that most of the issues revolving around balance lie. You have to get over that fact and accept that it's a necessary part of maintaining a codebase that not every improvement will be easy and sometimes it's necessary to dig in elbow deep into the nasty globs oldcode to make something better.

**Comment by icantthinkofanameritenow** [comment]
@kilkun

Wait, weren't you banned a while ago? Shouldn't you be working on that RPG of yours?

And why do you sound so reasonable?

**Comment by ghost** [comment]
@kilkun Is that goon's system? That seems to be what I was suggesting here. Though I don't think we should have RNG.

**Comment by ghost** [comment]
Oh yeah, how's that RPG of yours doing?

**Comment by kilkun** [comment]
@icantthinkofanameritenow
Yes but playing on /tg/ makes me pine for the good old boys back home, so I still lurk around and make sure shit doesn't catch on fire.

@DrCelt sort of. Goon's system is a bit different. It does have 2 states, the stun is initial, but after a while the player starts to crawl and can interact with the environment before standing up again. IIRC resting doesn't drop shit in your hands either.

yes I am working on my RPG and it's toodling along thanks for asking. almost ready for a demo release, chipping away at some stuff and trying to git gud at FL Studio. I gave Chug a pre-alpha to play a little while ago.

**Comment by kilkun** [comment]
Also forgot to add: RNG is inevitable. This is a GMUD and you have to realize that it's basically a real time pretty roguelike, which makes it an incarnation of an old school CRPG, which makes it a pen and paper RPG on a computer. You have to embrace that RNG is a mechanic and is basically the only strategic layer in the game (reducing dice rolls your adversaries get on you, etc) and you have to carefully design features around this.

Combat without RNG would be extremely wonky. It would have worked in the context of Railfists' idtech 1 port, due to the nature of FPS games, but it doesn't work that well in exadv1's meme combat.

**Comment by ghost** [comment]
Eh, it'll be FINE.

**Comment by kilkun** [comment]
Though you've got me thinking now, a good system instead of RNG would be to implement adrenaline.

Player gets hit when their intent is set on help it could make the mob start producing adrenaline which metabolizes into nothing, but if there's enough in it's system THEN the knockdown gets triggered when stunguns are used.

Or perhaps just have it reliant on intent in the first place? If grab, help or disarm are selected, stunguns cause stuns, but if harm is selected, they cause knockdowns.

The latter would be easier to implement, but the former opens up new gameplay mechanics revolving around a "combat aroused" state. Even introduces the idea of adrenal implants for Syndicate traits/ops, ERT and Deathsquad that automatically pump safe amounts of adrenaline into their system making stuns less useful against certain enemies.

Just a thought.

https://www.youtube.com/watch?v=be78uvNtAkY

**Comment by ghost** [comment]
Well we're getting into a complete stun refactor there, and I think it's better to take these things step by step, so why don't we start with this and consider adrenaline later?

**Comment by TheEliminator16** [comment]
Stun refactor when
Ling refactor when
Game refactor when

**Comment by ghost** [comment]
Should stun batons be exempt from this, ie, should they instantly cause the dropping of items?

**Comment by ghost** [comment]
That's a suggestion I read so I need some input on that

**Comment by ghost** [comment]
and err, should guns fired while stunned be less likely to hit?

**Comment by Exxion** [comment]
Fixing our code to actually work with step_x/step_y so we can have non-tile-locked movement and thus actual, physical bullet inaccuracy on a sub-tile scale when?

**Comment by TheEliminator16** [comment]
DEITY GUN REFACTOR WHEN

**Comment by SangriaMonkey** [comment]
[GONE SEXUAL] [2015] ✔
I'm not sure about this but it's not disabler beams either so I'll give you that

**Comment by NigglyWiggly** [comment]
@DrCelt Stop using ingame polls to try to prove that the server wants/does not want something.
If you really want a good ingame poll ask pomf to set up one of the server poll things for you

**Comment by ghost** [comment]
@NigglyWiggly I don't see what you mean by this at all. It's a snapshot of greater opinion; Sure it's a smaller sample and could have greater fluctuation but when dealing with supermajorities such as this I doubt it'll matter.

**Comment by Shadowmech88** [comment]
> It's a snapshot of greater opinion

You have no way of knowing this. Only 21 players voted in that poll. Highpop can get up into the 70s, and even then it's doubtful that the average highpop round includes literally everyone who currently plays on the server.

If you want to prove your point with a poll, then you'll need to make it a poll that can be answered by a greater percentage of the playerbase over the course of multiple days, not just whoever happens to be playing that particular round during which you made the poll.

**Comment by ghost** [comment]
@Shadowmech88 It is a snapshot, whether or not it is an accurate snapshot is what's up for debate. I would argue while obviously not entirely accurate, when you're dealing with a 19-2 majority it's going to be fairly indicative of popular opinion. In reality, there's no other quick method of gauging public opinion other than asking in the thread for feedback which you'll notice I have also done.

**Comment by Shadowmech88** [comment]
So go with a not-quick method, a server poll. The kind that you see in the lobby and stays up for multiple days.

**Comment by ghost** [comment]
@Shadowmech88 Well I don't have the power to set one of those up, but the poll was for finding out interest more than anything else; there's no use deliberately creating a highly unpopular thing just for the sake of it.

**Comment by Blithering** [comment]
How about instead of changing stuns flat out, make a chemical that gives a stun resist chance, opening up the opportunity for adrenaline implants, stimpacks and the like?

**Comment by TheEliminator16** [comment]
Combat stims for ERT like the wiki says when

**Comment by ghost** [comment]
I'll make a new issue.
