### ISSUE TITLE
MoMMIs can fire the rail gun

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#8273]
They can only fire it if its under a MW any thing higher and they get normal text how they cant fire the gun.

**Comment by 9600bauds** [comment]
Clowns too, since it's not a child of gun.

**Comment by AlphaBuffalo** [comment]
There's a rail gun?

**Comment by viniciuspetch** [comment]
@AlphaBuffalo https://github.com/d3athrow/vgstation13/pull/8010

**Comment by AlphaBuffalo** [comment]
Oh

**Comment by Shadowmech88** [comment]
They can fire it if it's under a MW because at that power level it doesn't actually call Fire(), it just throws the rod.

It also does completely abysmal damage at that level, the MoMMI would be better off smacking the person with the gun itself.

Does this really need fixing?

**Comment by gbasood** [comment]
Okay, maybe not. What about the clown part?

**Comment by Shadowmech88** [comment]
The clown is restricted by the same thing. The clumsy check is within Fire(), so the clown can only fire the railgun at power levels at which it doesn't call Fire(), i.e. under a MW.
The only gun the clown can fire which might pose an actual threat is the blunderbuss, since it doesn't call Fire() just like the pneumatic cannon doesn't.

**Comment by AutismSpider** [comment]
massive risk of the blunderbuss blowing up on you though

**Comment by gbasood** [comment]
well ALRIGHTY then
