### ISSUE TITLE
Triage spell for ghosts.

### ISSUE THREAD

**Issue by Myrios** [d3athrow/vgstation13#8376]
Having ghosts be able to use this spell to interact with living people in crit, allowing them to give a spectral form of CPR to targets in hard crit and shake living targets in soft crit once every thirty seconds to give them encouragement and an incremental amount of tramadol and/or DD (less than 5u total) in their blood to help them get back on their feet.

This would be a feature mostly for the benefit of deadchat and designed so that one ghost alone would not make much of a difference but when a whole group of ghosts converge they can (sometimes) get an injured crewman back on their feet just long enough to get out of harms way and get medical assistance.

Having this spell performed upon you would give messages along the lines of;
_"You faintly hear a familiar voice encouraging you."
"You swear you can hear someone calling your name."_

**Comment by Shadowmech88** [comment]
:+1: 

I'd make it 1u though, since I believe it's common to have upwards of 15 or 20 ghosts minimum close to the ends of rounds.

**Comment by Myrios** [comment]
My knowledge of precise dosages is limited so I'd defer balancing which chems and how much to someone who knows better than I; which is most people for that matter.

**Comment by ghost** [comment]
Even one unit is excessive unless there's a massive cool down, but otherwise what's the worst that can happen :+1:

**Comment by Shadowmech88** [comment]
Yeah, cooldown should be at least five or ten minutes so that a couple of ghosts can't just spam it to get someone out of crit.

**Comment by Myrios** [comment]
Which would encourage ghosts to work together to coordinate and all use it on the same target at the same time since they wouldn't want to waste their cooldown.

But what chems would you suggest? I thought tramadol would be good as it would allow a player to actually get up without healing but again, limited chemistry knowledge.

**Comment by SangriaMonkey** [comment]
:ok_hand:
I'd use DD over a pain med

**Comment by Shadowmech88** [comment]
Perhaps the coding of a new chem is in order, one that mimics the ability of a hulk to remain standing and conscious even while in crit.

**Comment by Blithering** [comment]
Perhaps have a ghost version of DD or whatever is needed that caps out at 5u in the bloodstream, so ghosts don't over fill their chosen champion.

**Comment by gbasood** [comment]
Interesting idea. Just going to outline some things this should NEVER enable:
- 10-20 ghosts should not be able to heal a person in crit out of crit under any circumstances.
- If this were to allow a ghost to heal any living person, it **must** be targetable only on people in crit to prevent healing some nerd hiding in maint asking the spirits to come to their aid

If you handled this via a reagent, you should check if the target already has that reagent before adding it, too. Just to prevent giving someone a huge amount of that reagent faster than they can metabolize it.

Maybe prevent ghosts from using this on things that aren't /mob/carbon/living/human, too. So that you don't have a bunch of ghosts trying to save xenos or something else silly.

**Comment by Intigracy** [comment]
Neat idea.
