### ISSUE TITLE
Give robotics more surgery tools

### ISSUE THREAD

**Issue by LordMyroc** [d3athrow/vgstation13#8395]
Now that science is capable of printing upgraded versions of internal organs, it would be awfully nice if roboticists had all the tools to required to install them without having to steal tools from medbay or order more from cargo every round.

More specifically, they require a FixOVein and Bone Gel.

**Comment by viniciuspetch** [comment]
As I whined in-game, you shouldn't, that kind of work is Medbay's. No Medbay, no augments. The only thing you can do is cry, or create a ghetto surgery place and cry more because you killed your patient.

That being said, Medbay is usually really undependable, and that means that rarely they'll be able to augment someone. With this, comes another problem: making surgeries in Science means we/they'll need to cramp a surgery room inside it, and that becomes a mapping issue (like the label!). Maybe a smaller version of the abandoned surgery room, being 3x3 with no computers, with only the tools and the surgery table? If you get the rest of the stuff for surgeries, it'll need to come with a proper room.

**Comment by LordMyroc** [comment]
How is this Medbay's job? Installing and repairing augments (robolimbs) has been part of robotics' duties for ages. How is this any different? Why should roboticists not be the ones responsible for performing this explicitly robotics-related thing?

Not to mention that medbay has enough problems managing the wild ride as it is, and there's absolutely no need to bog them down even further by everyone who wants a pair of cybereyes installed.

**Comment by Kitfox88** [comment]
Yeah, I don't think giving robotics a full set of surgery tools means they'll be replacing medbay when it comes to collapsed lungs and shit.

**Comment by viniciuspetch** [comment]
I know about repairing, but since when (and how) Robotics install robotlimbs?

Anyway, if the idea to put a small surgery room into Science is accepted, the biggest problem is a place to put said room. Simply throwing the surgery table (and the lacking tools) anywhere is kind of ridiculous.

**Comment by uazuaz** [comment]
in my opinion, installing augmented organs should be medbay job, repairing them should be robotics job, producing them should be science job.

**Comment by Kitfox88** [comment]
Why not just add them to the surgery suite already in robotics? It's just two items to plop onto the table, at least on box.

**Comment by LordMyroc** [comment]
@viniciuspetch You... you **are** aware that there is a surgery table in robotics, right? They have all the tools needed to replace limbs with robolimbs, and while there isn't much demand for roboticists to perform augmentations (they're not very good and most people that want them can just have them at roundstart) it does still happen. I've never seen people go to medbay for their robolimbs.

It's all there in robotics except for two tools.

**Comment by viniciuspetch** [comment]
@LordMyroc
No I wasn't. The only time I played with Robotics was in TGstation and they didn't have any of this, so I was really confused about that statement. Sorry for the misunderstanding. _You should have told me earlier hehe._

This clears out everything, I really didn't know you were lacking **only** those two tools. When you said "we have the tools" I understood you could make them at the protolathe. So scratch everything I said.
