### ISSUE TITLE
You can still attack while restrained in a resin nest

### ISSUE THREAD

**Issue by LordMyroc** [d3athrow/vgstation13#8399]
Although it is very satisfying to punch the fuck out of an alien queen that's trying to infect you, this is **probably** not intended behaviour.

**Comment by CptWad** [comment]
It really should be changed to resist out of nests
since its a fluff way to get out of nests (by clicking the nest) you can also resist out of a nest in mere microseconds by spamclicking the nest, getting out, put back in then you will immediately be forced back out because it counts clicks from before, which is frustrating

**Comment by gbasood** [comment]
Honestly why aren't nests just flavorful beds in terms of code
