### ISSUE TITLE
Overfilled moneybags change resolution when opened

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8423]
![help me](https://cloud.githubusercontent.com/assets/17381334/13202647/ef39cc08-d86f-11e5-8baf-216bc6ae8d51.jpg)
I don't know dick about coding but when a money bag is left at a coin press and fills over its limit it does this nonsense.

**Comment by Imagebard** [comment]
You're supposed to click the moneybag directly instead of opening it as a normal container.
Also, holy shit why is this thing so poorly fucking coded?

**Comment by PJB3005** [comment]
Nah I'm pretty sure this happens with any storage container as long as it's got enough things in it (the money bag just has so much fucking room that it manages this).

IIRC there's a var in storage item code to, instead of displaying each individual item, similar items gets represented as 1 with a number of how much there actually is.

**Comment by Zth--** [comment]
I reworked moneybags a while ago and they're simple bags now. I didn't know about that var, that would solve the problem easily

**Comment by ghost** [comment]
I tested it and there's a sanity issue with the coinpress, the moneybags can only hold 3 rows of coins when filled manually but get filled without limit when done by coinpress.
