### ISSUE TITLE
Selfharm with berries

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8484]
(WEB REPORT BY: brolaire REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 6c0b9d0d52fcf444885e0dc6cd6a0f6ec6bceefa 
> 
> General description of the issue
> You hit yourself in the chest with the berries instead of eating them when you're on harm intent
> 
> What you expected to happen
> Eating berries
> 
> What actually happened
> You have been attacked in the chest with the bunch of berries by Unknown (as Zane Straub)!
> 
> Steps to reproduce if possible
> Go to hotkey mode
> press 4
> hold berries in active hand
> press z

**Comment by Shadowmech88** [comment]
Is this true only for berries, or for all foods?

**Comment by 9600bauds** [comment]
Intended, some mutations of fruit have special effects when used to attack people. Just switch to any intent except harm you fucking neanderthal

**Comment by Exxion** [comment]
OK but this shouldn't be happening when called by `attack_self()`

**Comment by 9600bauds** [comment]
It's in case you need to bluespacetomato yourself (i.e. if you're in space or something).
Literally just get out of harm intent
This is what intents are for

**Comment by Exxion** [comment]
Then click yourself with it
If you use hotkeys or click it in your hand, you should eat it

**Comment by 9600bauds** [comment]
I believe clicking it in your hand and clicking yourself both call the same function, because I remember clicking on a fireaxe twice with altclick and somehow ending up whacking myself with it

**Comment by Exxion** [comment]
Clicking a fire axe in your hand wields it
Clicking yourself with it whacks you with it
This applies to basically everything except food

**Comment by ihadtoregisterforthis** [comment]
It is **attack** self after all

**Comment by Exxion** [comment]
Except `attack_self()` refers to attacking the _item_ with itself

**Comment by 9600bauds** [comment]
I don't remember the exact specifics because I don't have Atom or anything of the sort installed currently but when I was working on this, I believe attacking the item with itself AND attacking yourself with the item both did the same thing.

But really just like switch intent

**Comment by Exxion** [comment]
Attacking a beaker with itself: Puts a lid on the beaker
Attacking yourself with a beaker: Splash the beaker on you

Attacking a fire axe with itself: Wield the fire axe
Attacking yourself with a fire axe: Hit yourself, bleed out, and die

Attacking a bike horn/rubber duck with itself: Honk
Attacking yourself with one: I mean it's also technically honk but a different kind entirely

Food is _the only thing_ that currently behaves the same when you click it in your hand and when you click yourself with it

**Comment by 9600bauds** [comment]
Eh, I don't really recall what happened here but something odd was going on with this fruit self-attack business. Probably what you said about food self-attack being the same as attacking yourself. In any case this is a really low priority consistency issue, if I ever look at it it probably won't be for a while and certainly not now as I don't have Atom installed.

**Comment by Exxion** [comment]
But Bauds
Atom is slow, buggy shit

**Comment by 9600bauds** [comment]
Not in my experience and I can't go back to dreammaker

**Comment by Exxion** [comment]
Those are far from the only two options

**Comment by unid15** [comment]
attack_self() in food code just calls attack(usr, usr) because of lazycoding

**Comment by PJB3005** [comment]
@Exxion oh noes it's not as goddamn sanic and minimalistic as Notepad++ as such it's shit.

**Comment by Exxion** [comment]
Atom takes like half a minute to open, PJB
And unless you modify your copy, it has a... 2MB limit, if memory serves
Which is smaller than our .dmms
I use Sublime Text for DM because it actually has syntax highlighting for it if you download the package

Allegedly the package even lets you compile from within Sublime Text, but I can't get that to work

Atom's Git integration is better by far, though, as is to be expected
But it's just _so slow_

Also whose bright idea was it to write it in _CoffeeScript_? It's just a worse JavaScript

**Comment by PJB3005** [comment]
> Atom takes like half a minute to open, PJB

Took half a minute to open at first then took <5 seconds to open after that. I'm gonna have to test that on Linux because I blame windows.

Edit: just observed the same thing with Sublime but to a lesser extend, I blame Windows.

> And unless you modify your copy, it has a... 2MB limit, if memory serves
> Which is smaller than our .dmms

Not an issue for me.

> it actually has syntax highlighting for it if you download the package

https://github.com/stuicey/language-dm
Though I do agree Sublime Dreams has better highlighting. I should learn Atom's syntax highlighting at some point, but the documentation is REALLY FUCKING SPARSE.

> Allegedly the package even lets you compile from within Sublime Text, but I can't get that to work

https://www.reddit.com/r/SS13/comments/40xh7s/coder_stuff_updates_regarding_github_atom_for_dm/
"build" package in atom.

> Also whose bright idea was it to write it in CoffeeScript? It's just a worse JavaScript

I don't know either it's fucking horrendous.

Also let's just not derail this thread any further, shall we?

**Comment by Exxion** [comment]
This thread was barely on the rails when we started, but sure

**Comment by PJB3005** [comment]
True
