### ISSUE TITLE
R&D XCOM Assault Rifles stun people

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8628]
Their required R&D research is too low to give them the ability to stun people on shot. Make it higher or make it just deal damage.

**Comment by AutismSpider** [comment]
they never did that in the past

**Comment by 9600bauds** [comment]
They do deal damage, all bullets have a chance to make you fall down anyways. Kind of like melee weapons

**Comment by Imagebard** [comment]
Those seem to always make you fall down even tough they only deal 20 damage.

>They do deal damage

Oh fuck.

**Comment by 9600bauds** [comment]
Is this an XCOM joke?

**Comment by icantthinkofanameritenow** [comment]
@9600bauds 
No, inasmuch as the basic assault rifle was the default weapon and as such was objectively worse than laser and plasma guns. 

I believe what Imagebard meant was that they should only deal damage, not also cause knockdown like the C-20r does.

**Comment by AutismSpider** [comment]
@9600bauds never play xcom? not even ufo defense? all you got at the start was shit Pistol  and  Assault Rifles and the Auto Cannon  was to heavy for most rookies to use so you were force to use High Explosive and Grenade/Proximity Grenade+smokes

**Comment by 9600bauds** [comment]
I have played XCOM, that's why I was asking
This is not XCOM

**Comment by Imagebard** [comment]
I was just wondering how you came to the conclusion that I  was thinking Assault Rifles didn't deal damage.

**Comment by AutismSpider** [comment]
Assault rifles right now are cheaper C20r both the gun and the ammo can be made cheap like real cheap i think cheaper then making 357 ammo

**Comment by SonixApache** [comment]
More nerfs for gunsci? Could up the research level or material costs if that's the issue.

**Comment by Imagebard** [comment]
Its supposed to be the weakest gun of XCom, and increasing the research level would mean it would take more research than other, more advanced guns.

**Comment by icantthinkofanameritenow** [comment]
@SonixApache
Material cost hasn't been an issue for RnD in general, since a halfway competent miner can get enough materials to last an entire round within 15 minutes at most, and that's before you take into account the material synthesizer. 

I've been contemplating adding a modification to the way that lockboxes work so that gunfire and explosives have a fairly high chance of destroying the lockbox's contents instead of merely unlocking them, or perhaps make them indestructible by anything short of a Toxins bomb (as opposed to the IEDs that currently do the job just fine). I'm reluctant to actually code it though, as I'm sure that it would get a hostile reception.

**Comment by AutismSpider** [comment]
@icantthinkofanameritenow that happens with crates if you ied them open risk of some of the stuff being destroy

**Comment by 9600bauds** [comment]
Wrong issue to be discussing this but
>make them indestructible by anything short of a Toxins bomb (as opposed to the IEDs that currently do the job just fine). 

this is absolutely awful for reasons I don't need explain

**Comment by Zth--** [comment]
This is an awesome idea. Imagine lockboxes only openable with 4dev+ bombs, people would have to actually work on toxins and learn from it. And bombs are loud, it may create some suspects

**Comment by 9600bauds** [comment]
Do I really need to explain?
1) It's bad because it wouldn't allow for people to break open lockboxes in an emergency such as newcops unless there were conveniently bombs lying around.
2) It's bad because it would still only be an intermediate step to get yo guns. It's exactly the same shit as before, just that a Scientist now has to spend maybe 5 mins preparing.
3) It's bad because it's even more science exclusivity. Now nobody except a Scientist that can comfortably work toxins can break open lockboxes. That's not really a step in the right direction.
4) It's bad because it means MORE BOMBS (what was the supposed advantage of this change again)
5) It wouldn't even be a lot more high-profile than IEDs. You can even blow up the bomb on the asteroid to give the station no messages at all.
6) This is the wrong issue to be proposing it

**Comment by Blithering** [comment]
I agree with removing the knockdown from the assault rifle. 20 stunlock lethal shots + magazine based reloads is too good to be so widely available. CR-20 having the knockdown is fine, as it's restricted to nuke ops or the occasional wizard antic.

**Comment by icantthinkofanameritenow** [comment]
@9600bauds 
True on all counts. I'll make an issue later with the first idea I had in mind instead.
