### ISSUE TITLE
Vampires have more raw power than wizards

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8629]
Okay. Basically, vampires are part of the crew, and therefore trusted more than wizards and have better potential to sabotage things without having people chasing them. And multiple of them spawn. This means Wizards should be stronger in a open fight, right?

No. Okay, lets get off with basics...
Vampires can be inferior to the Wizard because...
1.They aren't human in the AI eyes. If command is smart, vampires are *even* on this issue, since they'll be considered non-human quickly.
2.They don't have a round start teleport to any area they want.
3.They are weak to holy weapons form the Chaplain.
4.They need blood form crewmembers to use their powers.

Vampires can be *on-par* with the Wizard because...
1.Being stunned does not matter to either of them, they can still attack or get out of the stun.
2.They have the same crowd control abilities that a wizard has

Vampires can be *SUPERIOR* to the Wizard because...
1.They can heal and come back form the dead, and still remain at full power.
2.*They can make minions*. This is enough to make a vampire better than the Wizard, make no mistake. And it doesn't even consume blood, as long as they have at least 300 they can use it.
3.They can put people to sleep instead of simply stunning like a wizard can, and being put to sleep makes people helpless and unable to scream
4.They can use powers whenever, no need to lose spell book points or use wizard robes.
5.Wizard stuns at least have some decency to be avoidable like making slow moving projectiles(Magic Missle) or needing people to be close(Butt Bot's revenge, Flesh to Stone)

If everyone is in agreement with me here, the Vampires need some nerfs. Maybe Enthralling should cost 100-150 blood.

**Comment by Ephx1** [comment]
Wizards can make minions as well, soul shard belt n' such.

**Comment by 9600bauds** [comment]
Soul shards are rather laughable.
There was a vampire murderboning today, he was doing it rather carelessly. Carelessly enough that I could just run up and harmbaton them twice within 20 seconds, but of course it didn't matter. Their abilities are strong enough that they can completely shrug it off (I assume the abilities that would have let them just fucking kill me AFTER I started harmbatoning them were on cooldown).

**Comment by Ephx1** [comment]
Oh I'm not saying they're better by any means, I'm just saying they can have minions.
Vampire thralling is the most obnoxious thing and I still think loyalty implants should protect against it.

**Comment by AutismSpider** [comment]
Vamp at half power is stronger then wiz even when stun vamp has three ways to stun you/fight back or to out right run.

a wiz at most would one one or two vamp can come back form the dead a wiz can not

**Comment by Imagebard** [comment]
>soul shard belt n' such.

Remember that they sacrifice their own power to make minions, whereas the Vampire loses nothing.

**Comment by ihadtoregisterforthis** [comment]
I agree with this, but wizards can make powerful apprentices and change crewmembers to break havok, either by staff of change or zombies.

Also to note wizards can come in waves, whereas vamps are few.

**Comment by CptWad** [comment]
Im fine with enthrall nerfs since those are some bullshit.
Though generally nerfing vampires are unessisary, we should probably be buffing wizard or just fixing the god awful magic missle

**Comment by Shadowmech88** [comment]
Why do the antags need to be balanced against each other?

**Comment by AutismSpider** [comment]
@Shadowmech88 they don't and its dumb to do so

**Comment by CptWad** [comment]
Antags should be powerful, especially when the spacestation 13 is easily the most hostile and dangerous setting, given that a crew full of lunatics with dangerous equipment they dont understand are all content on the metal deathtrap they call work it makes legitimate lunatics or evil-do-ers seem like small fry.
Vampire being overpowered is good, because that means that they can win (even though players still fuck it up often enough). Of course once @gbasood finishes the statistics we can point out which antags actually need major nerfs. Really vampire just needed stuff to go against the thralling, once that's squared away im good with it. 
IMO there's a few other antags that need attention because they lack.

**Comment by gbasood** [comment]
On statistics, it looks like I need to re-do a handful of collection methods for antag-related stuff. Double agent and blob specifically

**Comment by Killette2** [comment]
I'd still argue that wizard gets more variety and power than a vampire, bar the ability to come back from death. The thing about wizard is, it's often a scrub who has no idea what the fuck they're doing, but a smart wizard, despite being an obvious antag, is very mobile and can think of ways to easily outwit the crew.

However, I would agree that vampires are now a step up from changeling.

The reason why wizard, malf AI, nuke ops, and blob are powerful antags, is because they are SUPPOSED to be a solo threat to the crew (read raging mages is a meme, but worth keeping because it trains people to not be shitty wizards).

Vampires and changelings, while being powerful, come in groups, making them strong but should not be able to be more powerful than a wizard themselves.

**Comment by AutismSpider** [comment]
Thing is a solo ling is weak on his own all it takes mob of people or borg or two beat it to death.

Vs a vamp at half power or vamp he just keep running and rejuving out of stuns/chem ko's not even a fucking ling can do not only that a vamp can turn half that station into his slaves

**Comment by CptWad** [comment]
ling is due for a revamp

**Comment by 9600bauds** [comment]
ling is due for removal

**Comment by Imagebard** [comment]
>ShadowMech:Why do the antags need to be balanced against each other?
AutismSpider:they don't and its dumb to do so

Okay.

>

Thing is a solo ling is weak on his own all it takes mob of people or borg or two beat it to death.
Vs a vamp at half power or vamp he just keep running and rejuving out of stuns/chem ko's not even a fucking ling can do not only that a vamp can turn half that station into his slaves

Wait what?

**Comment by AutismSpider** [comment]
Tell me why its ok for a vamp to have the power to Enthrall  90% of the station and nothing you can do to stop it or fix it right now can derev and cult people cant un-enthrall people or block it in any way.

**Comment by Killette2** [comment]
Chaplain - or any of his friends with holy water, recently gained the ability to dethrall thralls, so that's something. Also the vampire must keep the victim still long enough to thrall him, so it's nowhere near rev flash stupidity.

**Comment by 9600bauds** [comment]
Service borgs are a myth

**Comment by AutismSpider** [comment]
@Killette2  Service borgs are bit to rare for that and all you need to do is disarm push/waterslip/clown pda for thralling

**Comment by ihadtoregisterforthis** [comment]
A medborg is fine too

**Comment by Killette2** [comment]
Can medborgs synthesize chemicals too now? I thought they could only carry them.

**Comment by Imagebard** [comment]
>it's nowhere near rev flash stupidity.

Revs can convert instantly.
Vampires are immortal converters with innate stun abilities to keep their target still while converting.

**Comment by Killette2** [comment]
At the cost of blood you mean, and yes they can get their thralls to sacrifice blood for them. A cost, no matter how simple it is to obtain, is more expensive than no cost, which is what wizards get.

**Comment by AutismSpider** [comment]
hypo and eye-flash cost no blood just has a cool down and to thrall people cost very little blood

**Comment by Imagebard** [comment]
@Killette2 You should know very well that 1.Wizards lose spell points to get apprentices and 2.Vampires can stun people at no cost
All the chronic lying, the inability to tell the truth you've been showing lately, on both this Issue and the Bluespace Bag issue, isn't healthy.

**Comment by Boxe** [comment]
thrall shouldn't be able to go through implants

also make it so the cap can't be thrall or culted like it used to beee

**Comment by Killette2** [comment]
I never mentioned ANYTHING about wizards getting apprentices or slaves, reread all that was said and realize you're just being a prick.

However OTHER PEOPLE (read: not me) have pointed out that soul stones and constructs exist. Please stop shitposting on the github, just because it is your issue doesn't give you the right.

**Comment by Imagebard** [comment]
>I never mentioned ANYTHING about wizards getting apprentices or slaves, reread all that was said and realize you're just being a prick.

I can't understand your message in any other way so please rewrite it. What "costs nothing to the wizard"?

>Please stop shitposting on the github

![00000](https://cloud.githubusercontent.com/assets/7571238/13555316/2ea167de-e39c-11e5-9da6-7c42a2d0391f.png)

**Comment by Killette2** [comment]
If you are unaware, thrall is free as long as you have 300 blood. The other vampire abilities have blood cost on a lot of them.

No wizard abilities have cost, that is what I was referring to.

**Comment by Imagebard** [comment]
>No wizard abilities have cost

It costs one spell point on the spell book to get an apprentice. *You're sacrificing 1 spell point that you can never get back.*
How is that "no cost"?

**Comment by Killette2** [comment]
There is a good reason wizards who know what they're doing don't get apprentices unless they're trying to give fun for more players or running a gimmick. With lasers flying at you, you need every spell you can get.

But if you are using the apprentice argument, which is poor since apprentices are pretty weak despite getting 2 spells of your choosing, then you're saying that wizards have a cost and vampires don't when it comes to amassing an army.

However I remember this change because it was hell getting 300 usable blood for every slave you wanted.

**Comment by Imagebard** [comment]
Vampires certainly have a 300 blood requirement to get slaves, but once they get it they can slave the whole station.
I don't know what you're aiming for, here. I don't think you understand the full power of having backup. Wizard apprentices ARE shitty, I don't deny it, but that's partially why Wizards are so underpowered compared to Vampires.

**Comment by Killette2** [comment]
So being a hulk that shoots lasers out of its eyes, mist form without taking blood, blink which also disguises you with smoke with a 2 second cooldown, turning people into statues, a staff that will break your bone and make you bleed out in one shot, AoE stun (again with no blood cost and less cooldown), the ability to pull EMPs out your ass are all underpowered?

A wizard can easily kill a whole station if he knows what he's doing. Face them against a vampire and a station full of thralls and see what happens.

**Comment by Imagebard** [comment]
>Face them against a vampire and a station full of thralls and see what happens.

The Wizard Loses.
Also, you picked 7 spells, wizards get 5.

**Comment by Killette2** [comment]
I was giving an example, if I was to face a few vampires and some thralls, I'd pick.

1. Jaunt
2. Blink
3. EMP
4. Mutate
5. Flesh to stone

Good luck humans and a few vampires, I ain't getting close enough for you to use any of your gay sleep spells on me

**Comment by FudgePucker** [comment]
Great (shitty) idea for a bus round.
Wizards vs vampires. Whoever wins the crew loses.

**Comment by CptWad** [comment]
You are kidding right? the crew could and probably would win.

**Comment by Killette2** [comment]
Depends on who's the wizard. The problem with wizard is this.

You have a lobby full of 30-50 people on mid or highpop.

gamemodes are weighted, with wizard being a bit rare

Players come and players go

How likely do you think an experienced player is going to roll the wizard role? It's slim to none, that's why people say wizards always die in 5 minutes. Same with blob, the player often doesn't know what they're doing and has played that role less than 5 times. Inexperience is more of the problem than the mode itself.

**Comment by FudgePucker** [comment]
I still have never gotten wizard, and only got vampire once.

**Comment by AutismSpider** [comment]
blob is so rare i forgot we have that as antag type we should re add the blob event and make it pool in a random ghost for the blob

**Comment by Killette2** [comment]
Blob should have a pop up that allows users to become the blob only if they want to, for example if you're in medbay and going to get cloned or you're busy doing other things and just using ghostchat to chat. It would work like xenos and be something like.

A blob will spawn in 60 seconds, click here to register to be the blob

**Comment by 9600bauds** [comment]
y is this close

**Comment by Imagebard** [comment]
Depends
Does thralling cost blood now? That was the main issue and I think they added a 150 blood cost to it.

**Comment by Imagebard** [comment]
If it doesn't, reopen.

**Comment by 9600bauds** [comment]
Well in the OP there's a lot of valid concerns that are not thralling

**Comment by Imagebard** [comment]
The truth is that I'm favoring issue 10301 because its a new issue and thus garners more attention.
