### ISSUE TITLE
EVA Rework

### ISSUE THREAD

**Issue by Myrios** [d3athrow/vgstation13#8655]
Just to toss an idea out there, since every department that needs hardsuits have them locally why not have EVA stocked with softsuits instead but as many as can be crammed into there?
Perhaps EVA could use being made a bit more mundane, the place where crew go for emergencies or if they need to go for a spacewalk and their job does not normally entail this? It would certainly make hardsuits more valuable and the crew a bit more survivable as a whole at the expense of the occasional individual where the difference between a soft and a hardsuit might save him.

**Comment by MusgardTiger** [comment]
I like the idea. Like those orange pressure suits from goon, gives you some time to get to safety or to help but gets ripped after a while but instead of making them department spesific we should make them one type.

**Comment by Kammerjunk** [comment]
Unless something has changed since the 28th of February, softsuits can't hold large O2 tanks, only emergency ones. As far as I can tell, there aren't any dispensers for emergency tanks. Either people will have to use the one in their internals box or a dispenser for emergency tanks will need to be added.
Other than that, I like it. A full emergency oxygen tank lasts for at least 30 minutes (maybe 40?) at a release pressure of 16 kPa, so that shouldn't be a problem for crew members whose job doesn't put them in space often.
