### ISSUE TITLE
Make it possible to extract UI + UE from a brain.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#8981]
Right now if you only have a bare brain (or head), you have to use a monkey body. Sadly this results in the old UI + UE being lost.

It'd be nice if we could get the UI + UE from a brain. It'd make it less of a fucking pain to revived from only being a head or brain.

**Comment by gbasood** [comment]
What if blood contained UI+UE, and you could take a blood sample from brains?
:question:

**Comment by Shadowmech88** [comment]
Why is a mob's identity attached to their torso instead of their brain, anyway?

**Comment by PJB3005** [comment]
@Shadowmech88 it's just DNA, it's everywhere in a mob.

The weird thing is being unable to get DNA except with a DNA scanner and a whole body.

What @gbasood suggested would be a good way to handle it too.

**Comment by Shadowmech88** [comment]
No, what I mean by "identity attached to their torso instead of their brain" is that if you attach Bob's head to Steve's torso, the new mob will be named Steve despite containing Bob's brain.
I feel like head transplants should cause the body to adopt the identity of the head, not the other way around.

**Comment by PJB3005** [comment]
Ah alright, I get it.
