### ISSUE TITLE
Cannot surgically implant asses into your body

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8988]
(WEB REPORT BY: zealotron REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 861a5c96dce31ffa41e9b3dd913fac4b6a7e352a 
> 
> General description of the issue
> you can't do surgery to place ASSES inside of yourself
> 
> What you expected to happen
> to be able to implant ASSES
> 
> What actually happened
> NOTHING
> 
> Steps to reproduce if possible
> do surgery

maybe it's because i'm a plasmaman because the surgeon was getting a It is as if I can't see any useful way to use the surgical drill on you message

**Comment by Shadowmech88** [comment]
If he couldn't use the drill on you, it sounds like the problem is with implanting items in general, not just asses.

**Comment by Killette2** [comment]
What size is an ass and where were you trying to implant it? A fun thing is you can do things that are pants on head retarded with implant surgery, such as hacking a kitchen vendor to provide a tiny/pocket sized chef knife, which can be implanted into the skull due to it's tiny size.

And for a detailed info on implant surgery. Chest fits normal size, groin fits small size, head fits tiny size.

**Comment by TheFriggenSawbones** [comment]
the asses were tiny and the surgeon tried my head and my chest

**Comment by gbasood** [comment]
This is more likely than not because there's something else asses are intended to do when you attack a person with them, and they're just not calling their parent proc.
