### ISSUE TITLE
N2O doesn't cause sleep

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#9048]
Revision: 537a8e757b2360f6f78e8e8335f30bd58beef948

> General description of the issue

This has been broken for a while, I think. N2O does not make mobs fall asleep when it should.

> What you expected to happen

In low amounts, expected messages of sleepyness/dizziness/whatever the message you're supposed to get says. In high amounts, expected people to fall unconscious.

> What actually happened

Absolutely no effect, even if breathing pure N2O. In case of tanks with N2O (either pure or mixed such as with anesthetic tanks), the pressure decreased, but it had no effect in the mob.

> Steps to reproduce if possible

Spawn an anesthetic tank, spawn a breath mask, wear both, enable internals. I'm not sure if the sleeping effect applies to test dummies, so possibly test it on a regular human.

**Comment by PJB3005** [comment]
Pretty sure this was a result of the deus ex update.

**Comment by gbasood** [comment]
yep
will test as soon as I can

**Comment by gbasood** [comment]
Alright here's what I got
An N2 tank, at default pressure setting, provides 0.0164232 moles.
N2O's minimum PP for paralysis is 1, and 5 for sleep.
Trace gasses's 'pp' is calculated via:

``` DM
return (gas.moles/breath.total_moles())*breath_pressure
```

So in this case, the first part of that is 0.0164232 / 0.0208232 = 0.788697222
The second part is:

``` DM
var/breath_pressure = (breath.total_moles()*R_IDEAL_GAS_EQUATION*breath.temperature)/lungs.inhale_volume
```

So 0.0208232 \* 8.314 \* 293.15 = ~50.75

So something's fucky with trace gasses, I think, because if that were actually the case, this would EASILY trigger the rest of hte sleeping gas shit.

I should mention that when using this with a mask and an N2O tank I got literally no giggles or paralysis.

**Comment by uazuaz** [comment]
#8598

**Comment by Intigracy** [comment]
quick sood rewrite all of atmos so that n2o isn't snowflake shit compared to every other gas being universally handled.

**Comment by PJB3005** [comment]
@Intigracy you do realise N<sub>2</sub>O is actually coded in a better way than the other gasses, it's just a snowflake because the other gasses are fucking retarded shits.

**Comment by Intigracy** [comment]
So fix the other gasses to be just like N2O. Whichever works better!

**Comment by SonixApache** [comment]
please fix this, i'm going to cry

**Comment by Probe1** [comment]
Fix it already it has been a MONTH

Stop merging shit that isn't tested goddamn.

And don't tell me it was n3x15 fault for code you revived and merged.

**Comment by Probe1** [comment]
wasn't this closed
