### ISSUE TITLE
Diona Nymphs freeze on ventcrawl

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#9104]
@DrCelt
@DrCelt
@DrCelt

Even when crawling into a 20C pipe filled with air, they freeze nearly instantly
This also affects monkeys and other vent crawling entities, such as xenos.

"According to Celt this is a feature because more air pressure = more heat transfer so you freeze to 20c ;)"

Last issue was locked and I cannot imagine why.

**Comment by Boxe** [comment]
@DrCelt

**Comment by SysadminJeroen** [comment]
@DrCelt

**Comment by PJB3005** [comment]
@DrCelt

**Comment by Killette2** [comment]
I think this happens because of a feature freeze, which would explain why ventcrawling would make you get colder

**Comment by gbasood** [comment]
> still pinging Celt when he clearly won't do shit

Hasn't been in IRC in forever
Hasn't done ANYTHING on Github except call people's PRs shit in at least a month
Fix it yourselves guys

Also just because a convo is locked doesn't mean you should open a new issue

p.s. if this turns into more mentioning drcelt every day I'm just going to lock this one too so cut that shit out

**Comment by Boxe** [comment]
ok let me start reverting hypothermia

**Comment by Intigracy** [comment]
Well close ONE of them, jeez.

**Comment by AutismSpider** [comment]
So revert all his fucking meme code it was only put in for a map he fucking stop working on

**Comment by gbasood** [comment]
No

**Comment by Intigracy** [comment]
Let's revert hypothermia and leave in the nice stuff like the campfires :^)

**Comment by ghost** [comment]
hello I am alive again

**Comment by SysadminJeroen** [comment]
@DrCelt FIX IT

2016-03-29 0:59 GMT+02:00 DrCelt notifications@github.com:

**Comment by Intigracy** [comment]
still happening what fun

**Comment by Killette2** [comment]
Something has always been fucked about pipes.

I syphoned a bunch of air in a pipe as a test to see how much it could hold (turns out the answer is infinite, however there's a flow depending on how many scrubbers are used), and when I pipewrenched it out, despite it being 20c it started giving me hypothermia stuff even though the room also remained the same temperature.

Also are you implying that atmos techs don't overstuff the pipes to begin with? Shit's annoying, I always make sure there's around 100kpa in the distro so there's enough in the case some place needs air, but at the same time nothing dies from over or under pressure from crawling through the vents. I like to let a little bit of fun happen.

**Comment by 9600bauds** [comment]
@DrCelt fix it you nerd

**Comment by Intigracy** [comment]
Revert hypothermia when, adding more half finished systems isn't cool bro

**Comment by NigglyWiggly** [comment]
Spess is practically made of half finished systems
If we just keep throwing more half-finished shit in, maybe some stuff will combine to form a full system!
