### ISSUE TITLE
hotkey wierdness shit

### ISSUE THREAD

**Issue by Boxe** [d3athrow/vgstation13#9112]
1. turn hotkeys off
2. click someone's name to bwoink them or something similar that opens a dialogue window, close the dialogue window however you want.
3. click the top bar where it say Space Station 13
4. hit either M or O, this opens the emote or OOC dialogue respectively despite the fact that hotkeys are off

fix it

**Comment by PJB3005** [comment]
It's because you're technically focused on the chat and the chat captures and activates hotkeymode hotkeys no matter what. Fixing that would be a MAJOR pain if not impossible UNLESS we bring back my hotkey mode rework which people hated to hell and back for some mind bogglingly dumb reason.

I can make it not focus if you click a link though.

**Comment by Konater** [comment]
This happens if you click follow on a name in deadchat and it's annoying as fug because when I want to type say "x" while following someone it moves me up a square

**Comment by clusterfack** [comment]
Didn't you fix this @PJB3005

**Comment by PJB3005** [comment]
I did not.

**Comment by PJB3005** [comment]
Now I did, fix PR coming up in a sec.
