### ISSUE TITLE
Cult deconversion text does not display

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9166]
(WEB REPORT BY: termedclepe2 REMOTE: 158.69.55.2:7777)
IE 8, win xp. After decoverting a cultist, no text displayed of decovnersion notification.

**Comment by gbasood** [comment]
> IE8

Are we actually trying to support IE this old
That said if everything else shows up in chat fine then cult text should have shown up as well

I'm not going to say people should try to reproduce this under IE8 and try to fix it for IE8 but it should be confirmed whether or not this issue is specific to IE8 at the very least

**Comment by gbasood** [comment]
For more info: How was the cultist deconverted? Bible, holy water, etc?

**Comment by Imagebard** [comment]
TermedClepe was banned form Github, you know. Or deleted his account?
Either way, he's "ghost" now.

**Comment by gbasood** [comment]
Yeah I know I was hoping @CptWad or dragon would chime in
Guess I'll have to bug them in game

**Comment by gbasood** [comment]
Apparently he did actually get them and he just overlooked them
