### ISSUE TITLE
Presets for wizard

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#9182]
Idea credit to SacredAtom who PM'd me on BYOND for this.

Presets for the wizard, a name and all the skill points used. Would probably help newbies who don't know which spells to pick.
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Killette2** [comment]
I thought raging mages was the point of newbie wizard training, also this would lead to some spells being considered OP together.

A better solution would be for us to all gather and discuss about wizard spells, and their difficulty to use in certain situations. An example would be magic missile and ethereal jaunt are better spells to pick for an inexperienced wizard than fireball or staff of change (if you're not robust, you'll just fireball yourself and lose your staff 5 minutes in due to a stun). While themed wizards isn't a bad idea, wizard's getting such a variety of spells is so you can be creative and entertaining, as antags are intended to be although not often followed.

**Comment by Intigracy** [comment]
> While themed wizards isn't a bad idea, wizard's getting such a variety of spells is so you can be creative and entertaining, as antags are intended to be although not often followed.

He's not saying that you HAVE to pick a preset, he's saying they should exist.

Tbh I think the presets _depending on the spell combinations_ could/should end up worth more than the starting spell points.

Like something that's purely gimmicky like the horsehead masking/clowning/miming would give you maybe 1 point more worth for picking it than picking one that's meant to kill everyone.

**Comment by AutismSpider** [comment]
Fire ball should never be pick its that bad to point were you can out run your own fire ball on top of that cast it then move to next tile were the ball would be and it crash into you

**Comment by Killette2** [comment]
I said presets are not a bad idea. They could exist if you really want them to, but presets won't ensure new wizards will know how to use them effectively, even if they are good presets. They may need to try easier spells while they may not be good in combination, it can teach them how to wizzyman better.

**Comment by Probe1** [comment]
can't wait to hear the bitching about 2stronk spells

**Comment by AutismSpider** [comment]
@Probe1 lighting or the old ass hulk out spell? most of the other spells are use to run or piss people off

**Comment by Probe1** [comment]
@AutismSpider What I'm thinking is a significant hurdle for new players is figuring out what spells are good.  They make poor choices and get shrekt.  

What if that was taken out of the equation and newer wizards had reasonable selections given to them?

Welp, time to have people bitch because what was the realm of t. powergamer is now at the fingertips of everyone.

It wasn't a serious post, I'm being flippant about it.  I'd love to see wizard get some work done to it.  It badly needs QoL.

Fuck mutation spell though, its downsides either don't work or are non existent and it's an infinite powered no cooldown egun that you can't drop

**Comment by Shadowmech88** [comment]
Not to mention the stun immunity.
Hulks aren't even supposed to be able to use guns, but the wizard gets a gun built into him in addition to his hulk.

**Comment by AutismSpider** [comment]
@Probe1 what fire ball should be the newbe wiz 1st combat spell what it really turns into fire ball killing them 2 mins in due to ZAS turning the rods/glass into walls or some one bum rushes the wiz so he/she dies to there own fire ball.

Mutation is just the hulk mut+ eye beams can jam them up with rye push them out of it or shot gun them two times and they die after the hulk part runs out

**Comment by Killette2** [comment]
You forgot the part where laser beams coming from your eyes drains your hunger really fucking fast, and wizards don't have money to buy food so they have to improvise.

**Comment by Shadowmech88** [comment]
They can easily break into areas where they can acquire boxes of donuts/donk pockets for free.

**Comment by AutismSpider** [comment]
food not that big of a deal for laser eye spam viro has box of donk pockets you can heat up for food and some cheap healing jack some one ID and get some food off the vend

**Comment by Probe1** [comment]
I didn't forget it.  I've never seen a wizard actually give a shit.  "I'm hungry" or "I move slowly" is moot when they can just teleport.

**Comment by Killette2** [comment]
First off, the teleportation spell is pretty shit compared to the jaunt, and I believe if you're slowed with regular movement, your jaunt is slow too.

Second, I believe this topic was about newbie wizards, so I doubt they would know the location of said donut boxes and donk pockets by heart.

**Comment by Shadowmech88** [comment]
Just because someone's a newbie to wizard doesn't mean they're a newbie to the game in general. Wizard's not a common role, second only to blob in rarity.

**Comment by Killette2** [comment]
Which makes me come to ask, why are newbie wizards a thing? Inexperienced ones I can understand, but people should in general know what not to do. It's a fucking meme knowing not to pick fireball, where we taunt any wizard who kills himself with it and call it a suicide spell. When a round ends, you can see the wizard's spells so if the wizard died, you can think to yourself "huh, that guy must not have picked a good spell combination, or some of those spells didn't go good with what he was doing" and when a wizard succeeds, they will notice that that wizard chose a good selection of spells that work together. Being a wizards is common sense, blob can be confusing if you don't know how important building placement is and learning ways to sabotage the crew as an expanding being such as targeting APCs, wires, and certain walls and doors. It just befuddles me how people can consistently be bad at wizard, especially when we have raging mages so we can see not only 1, but 5 people fuck it up and learn from their experience.

**Comment by Shadowmech88** [comment]
I don't believe there are playtime restrictions on any of the antags. Ideally, I think at least some of them should require the player to have been here for a small amount of time before letting them roll it, like what we currently have for command roles, so they can get a better grasp of the game mechanics before being given antag.
Nuke Ops is another one that might be confusing and difficult to accomplish for someone that hasn't at least played a couple nuke ops rounds before getting the role.

**Comment by AutismSpider** [comment]
Nah you move at full  speed with jaunt.TP is just god awful spell when you have jaunt and blink
