### ISSUE TITLE
Shit thats on fire stays on fire basically forever

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9218]
#### Description of issue

If you set a bunch of papers or whatever in the bar on fire they'll just keep their burning icon forever
#### Difference between expected and actual behavior

Have them turn into ash at some point
#### Steps to reproduce

Start a fire
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
Tested locally, still exists.
The paper I left in the burn chamber *did* eventually turn to ash, once the room reached 91% CO2 concentration and all the fires except the lighter went out.
The paper I took out of the burn chamber kept burning. I imagine there's no system for determining when the thing that's on fire is "burnt up," instead going solely by how much fuel is in the air.

**Comment by Exxion** [comment]
There is actually a system for determining when something is burnt up. A var called `fire_fuel` ticks down, and the thing turns to ash when it reaches 0.
*However*, this var only ticks down when the object is in a room with fire in it.
💯

**Comment by Probe1** [comment]
aged out

**Comment by Shadowmech88** [comment]
@Probe1 did you actually confirm that this no longer occurs? The bug was still present a year ago.

**Comment by Exxion** [comment]
Oh of course it still occurs

**Comment by Shadowmech88** [comment]
Looking a little deeper, the big problem is that `fire_fuel` is only consumed by `burnFireFuel()`, which is only called by ZAS fire code on objects that are on the fire's tile. In order to make items burn their own `fire_fuel`, they would need a `process()` to do so. *But*, using the regular `process()` and the regular `processing_objects` might interfere with object-specific processes or not work, depending on whether the objects even call `..()`.
Do I need to make a separate subsystem for processing objects that are on fire? How would I do that?

**Comment by Shadowmech88** [comment]
I'm just going to try using a loop.
