### ISSUE TITLE
assblast button

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#9229]
Now that there's a big ol' friendly [CANCER] button to smite all those who dare try and pray with something that's fairly buggy and evil, an admin came up with an idea for another button.

A button that automatically blows the arse off of whoever is inflicted with it.

**Comment by ghost** [comment]
Blows the arse off as in blows the arse of or blows the arse off as in blows the hell out of them

**Comment by clusterfack** [comment]
We should create a joint [PUNISH] menu, that gives options such as cancer, smite, BSA, assblast USA million butt minefield

**Comment by ghost** [comment]
@DrCelt As in their Gluteus Maximus is severed from their body with force

Like the wizard spell

**Comment by NigglyWiggly** [comment]
Can we just not clutter everything with more unnecessary [CANCER] Tier buttons

Like can we fucking move Cancer to Secrets if we're gonna keep it, instead of having it shoved right in with other, more commonly used responses to players? 

Also why in the fuck would you ever put something like this in VV, that's the worst thing you could do

**Comment by Manaony** [comment]
Can't we remove cancer altogether? It's awful.

**Comment by Kitfox88** [comment]
celt and duny still contribute code so no the cancer's metastasized and is uncurable :^)

jk i like u duny and celt

**Comment by Probe1** [comment]
Fulfilled but no one closed the issue
