### ISSUE TITLE
Stungloves are obscured by hardsuits, yet can be used while wearing one anyways

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9238]
Not only do hardsuits hide the stunglove's sprite, they also hide them from examination and from the stripping menu. This is fairly shitty considering that they still work anyways, even with a hardsuit on.

Proposed solutions:
- Easy: Stungloves don't work while obscured
- Probably Impossible: Make the stungloves display over the hardsuit on icon and on examination
- Best: Your hardsuit conducts the stungloves' electricity and shocks you instead

Also, stungloves need a sound

**Comment by SysadminJeroen** [comment]
Insulating gloves are also obscured by hardsuits, while fully usable.

**Comment by 9600bauds** [comment]
That too, but that's considerably less exploitable and probably necessary for Engineering's proper functioning

**Comment by Killette2** [comment]
So since hardsuits need to protect you from space, it wouldn't be a stretch to say that they come with gloves instead of just sleeves for your arms. If this is the case, how would you even be insulated from shocks by them? Sure your hand is covered with rubber, but unless you're putting the rubber glove over the hardsuit, then the electricity is conducting through the suit and around your gloves shocking the shit out of you anyways

I'm also thinking of how silly you'd look stretching another glove over your already worn hardsuit glove

**Comment by Shadowmech88** [comment]
The hands of a hardsuit probably aren't covered entirely with metal; it would make them too difficult to articulate.

**Comment by Probe1** [comment]
not an exploit 

go bother assistants with their infinite ghetto weapons

**Comment by Shadowmech88** [comment]
None of the ghetto weapons allow an instant stun without any form of visual cue that they're holding a stun weapon. Stungloves are just a step below a parapen, especially when you can't visually inspect a person to determine whether they're wearing any.

**Comment by Probe1** [comment]
ok go bother changelings and traitors undetectable instant kill buttons.

If you can't tell how I feel about this, the time for complaining about engineers having a weapon has long since past.  We have given everyone else extremely potent and common weapons.

There's no logical inconsistency with stun gloves being obscured by a hardsuit and I knew bauds had self tagged that shit before opening it

**Comment by Shadowmech88** [comment]
The difference is that the changeling and traitor undetectable instant kill buttons are _designed_ to be undetectable. This is an oversight because hardsuits obscure all hand-worn items, stungloves were never intended to be able to be obscured by any means.

**Comment by Killette2** [comment]
First I didn't imply the hardsuit built in gloves are metal, they could be any space resistant fabric as long as they cover your skin with no holes.

Second probe, I gotta say your logic is retarded here. How do you stun someone with your zappy gloves, when the gloves are covered completely by the hardsuit? Your stun wires don't go through your hardsuit like magic, they actually have to make contact. Therefore the gloves should be on the outside of the suit to even work, and if they are on the outside of the suit, why do they not appear visually as outside of the suit? Next you're going to try to tell me hardsuits have no palms/magically detachable gloves that appear again when someone needs them to be protected from space.

**Comment by Probe1** [comment]
It's always been that way, I'm having a hard time accepting it isn't intended when it's been that way for all time and hardsuits obscure all under layers. You don't like stun gloves being obscured but it's absolutely working as intended.

How about we make stun gloves periodically spark?

**Comment by ihadtoregisterforthis** [comment]
Visually as an effect or spawning sparks?

**Comment by Probe1** [comment]
Spawning sparks.  Have them spark at random intervals.  

Everyone wins.  It even adds risk that you could start a fire.

**Comment by Killette2** [comment]
You've gone from a visual balance to being a madman. Time for greyshirt mcghettoweapons to accidentally cause fires every time plasma is released resulting in more or faster deaths than normal

And explain how your gloves, not just stungloves but any gloves, work through the fabric your hardsuit covers your hands with? Hardsuits alone aren't insulated, so wouldn't the electricity be conducted through the suit itself as usual instead of being blocked by the rubber the gloves provide? It only makes sense for gloves to appear on the outside of a hardsuit because that's the only place where they actually would function.

**Comment by Shadowmech88** [comment]
Fabric isn't a particularly good conductor of electricity. When you touch something that's electrified while wearing cloth gloves, the current makes a fraction-of-a-millimeter jump between the surface and your skin, it doesn't get conducted through the cloth.
Even in real life, if you were to wear insulated gloves and then longer cloth gloves over them, you wouldn't get shocked when touching an electrified surface, despite the fact that the outer cloth gloves are in contact with both the surface and your arms.
The distance electricity can jump is dependent on the current, but given the fact that stungloves don't even cause burn damage, they're probably not high-current electricity. Which would mean that insulated gloves would work inside a hardsuit, but stungloves would only work on the outside.

**Comment by Probe1** [comment]
@Killette2 sounds like SS13 to me

**Comment by ihadtoregisterforthis** [comment]
Hardsuits are likely made with rubber, they need to keep the user's pressure in space

**Comment by 9600bauds** [comment]
Jesus, I go to sleep and when I wake up, Probe is equaling stungloves to ling stings.
I have no words here but "shame on you".

To expand on this: Since when are stungloves an engineer-only weapon? What is this misplaced and ill-intentioned tribalism out of nowhere when that's not even within a stretch of what actually happens in-game?
What's up with this "it's been that way for a while, thus it's clearly intended" mentality? That's a very dangerous precedent to set, especially when you could say the same thing for, say, the packaging wrap exploit.
To make a bold statement here: I AM NOT SAYING INSULATED GLOVES SHOULDN'T WORK THROUGH HARDSUITS BECAUSE THAT'S JUST DUMB
And to return to my original point because after thinking about it, it does deserve some more words: Even a parapen, a weapon specifically designed for antags, has a visual tell before it can stun you. Only ling stings and glares don't, and that's because those are exclusive to arguably stealth-oriented antags. When you look at stungloves, you need to be comparing them to other ghetto weapons, because that's what they are. They are not an antag weapon.
And when you compare them to other ghetto weapons? They're a little wonky in having no visual tell and not being disarm-able, I think.

**Comment by 9600bauds** [comment]
There's also the fun fun fact that you literally cannot search plasmamen for stungloves unless you're 1000% sure, but that's more of an issue with fucking plasmamen

**Comment by Killette2** [comment]
> Mention hardsuits don't provide any shock resistance at all (that I know of)
> Everyone rushes to say that hardsuits are made with fabric now, just to make sense of insulated gloves when calling them metal was done earlier, although a pure metal hardsuit is not likely either due to the handiwork required while using them

This still has nothing to do with insulated gloves, go try and be an engineer without insulated gloves and just the hardsuit, and I will tell you it will do jack shit against shocked doors or machinery. The suit is not built specifically for resisting electricity. Even if it nullifies some of the damage which would honestly surprise me, it still gets you shocked hard enough to stun you.

Point being, you need to wear insulated gloves on the outside of hardsuits for them to protect you, there is no magical explanation needed. Next do you want me to say that the surgeons hands were sterile because he was wearing latex gloves under his hardsuit (it can be any hardsuit, medical hardsuit isn't the point) glove rather than over? Do boxing gloves fit under hardsuits also? I'm not even sure if the boxing glove sprite appears outside of hardsuits since they're so bulky, depends on if hardsuits hide glove sprites or not, but it just makes more sense for any gloves to appear on the outside of hardsuits than inside.

Gloves protect your hands directly from things such a shocks, when you coat your hands with something that doesn't protect from shocks (IE a hardsuit, go walk into a shocked grille with one before you put on insulated gloves), then how are you safe? In real life you can't wear electric proof gloves as an electrician, then wear something else on top of that. They will tell you that it's not shock resistant and a safety hazard, and if you MUST wear that, then at least wear the gloves on the outside.

**Comment by NigglyWiggly** [comment]
@9600bauds >Since when are stungloves an engineer-only weapon?

He might be thinking of the Engineer traitor item gloves

**Comment by Probe1** [comment]
No I'm definitely thinking of regular stungloves and not power gloves.

If you're talking about stun gloves alone sure, but stun gloves + hardsuits?  Of course engineers are going to be the ones that feel the pinch.

Anyway I've offered what I think is an acceptable idea for it https://github.com/d3athrow/vgstation13/issues/9238#issuecomment-205237100 .  It adds risk to using them and is a tell.

**Comment by Shadowmech88** [comment]
@Killette2 
Just because the suit doesn't insulate against electricity doesn't mean it conducts electricity across its surface. Wearing insulated gloves inside a hardsuit would logically work because the current can't jump from the surface to your skin due to the gloves, and it's not going to be conducted through the hardsuit gloves' material up to your arms.

**Comment by Killette2** [comment]
Well Shadow, I believe the suit does conduct electricity else it wouldn't shock you when you meet electricity. It doesn't need to go straight to your hand and check for a glove for electricity to find an exposed area of skin on your body. Hardsuits shock you if you don't wear any gloves and you will get hurt. Who's to say having a glove under that will stop that shock when since it conducts through hardsuits to begin with, it will just go straight up your arm to your jumpsuit? Protection needs to be on the outside, especially electrical protection.

**Comment by 9600bauds** [comment]
Boxing gloves under hardsuits is not an issue because it has never proven to be an issue
Insulated gloves under hardsuits is not an issue because it has never proven to be an issue and would be terrible if it didn't work like that
The problem is specifically stungloves because they're a ghetto weapon and they don't give a tell.

I'm not sure about the sparks, because they would either have to spark practically every second or it could happen that the gloves just didn't spark in the three-four seconds that the guy in the hardsuit was in your screen, so you still didn't get any tell. The most ideal solution would be to have the glove sprites on your character, because they're subtle and always visible.
Also, the spark's risk here is not really a risk for the person wearing them so much as a risk for the entire crew

**Comment by Killette2** [comment]
I'm not complaining it's an issue gameplay wise, except for stungloves since it's a visible weapon. The thing I'm trying to push is that it makes no logical sense for gloves to protect you under the suit. They are gloves, not bullet proof vest. They protect your hands from electricity in this example, not because someone is shooting an electric bolt at your chest (which is what I'd say an abliative is for if you count stun shots as anything), but because your hands are your tools for dealing with electrical equipment whether it be doors or machines. If you touch an machine that will shock you, the electricity will go through your body in any way it can to ground itself, not crawl through your fingers specifically like it must go through your veins as soon as possible. That is what the insulated gloves represent, something that directly separates the electricity from your body using something electricity doesn't conduct through as a BARRIER. However, if you put something it does conduct through, like a hardsuit on top of the gloves, it nullifies the point of the gloves completely.

**Comment by Shadowmech88** [comment]
@Killette2 
Like I said, just because something's not a complete insulator doesn't automatically make it a perfect conductor. When you get shocked while wearing a hardsuit, it's more likely the current jumped directly from the surface to your skin, through the hardsuit material. This doesn't mean, however, that the hardsuit material is a good enough conductor to carry current farther than the fraction of a millimeter that is the thickness of the hardsuit's glove, especially not up the length of your hand and into your arm.

**Comment by 9600bauds** [comment]
The other alternatives are:
- gloves do not protect you under a hardsuit (terrible and makes many engineering things impossible)
- engineering hardsuits always have insulation (bad)
- all hardsuits always have insulation (terrible)

**Comment by Killette2** [comment]
@Shadowmech88 

Electricity is a powerful thing, and will try to go around the glove in any way it can, and if something is leading a bridge over your glove to your skin, it definitely will take it.

@9600bauds 

Yes all those ideas are terrible, which is why I suggested none of them. Gloves need to be and appear on the outside of hardsuits.

**Comment by 9600bauds** [comment]
The captain's hardsuit doesn't cover gloves, does that count?

**Comment by Killette2** [comment]
If by a logical perspective, you think having your hands exposed to space for any period even a prolonged amount of time, despite it not being as lethal as it should be in ss13 for fair gameplay reasons, sure.

**Comment by Shadowmech88** [comment]
> and if something is leading a bridge over your glove to your skin, it definitely will take it.

Air is leading a bridge over the glove to the skin. It doesn't take that path.
The ability of electricity to travel through a poor conductor is affected by how much it has to travel through. If you bring your hand within a few millimeters of a surface with a high current running through it, it will arc through the air to your skin. Static electricity, for example. But does this mean that the same amount of current will be able to arc six inches to your skin? No, because traveling through that much air would require much more energy.

In a similar way, an electrical current is capable of jumping a millimeter or two through the hardsuit material to a person's hand when they touch an electrified surface, but that doesn't necessarily mean that the same current would be capable of traveling six inches across the hardsuit material past their hand in order to get to their arm.

**Comment by Killette2** [comment]
If by a logical perspective, you think having your hands exposed to space for any period even a prolonged amount of time, despite it not being as lethal as it should be in ss13 for fair gameplay reasons, sure.

*No gloves in the game are specifically designed for space protection, your hands in a real life scenario, would be fucked. You might as well go into space in a morphsuit and call it protection because your body is covered

![morphsuit](https://cloud.githubusercontent.com/assets/5169310/14255612/d39a0ca0-fa62-11e5-8cbd-5d887c1dadbb.jpg)

**Comment by Killette2** [comment]
@Shadowmech88 
Air is a gas, not a solid object. Either we give hardsuits shock resistance, or it's dumb to say they may be not the best conduits despite conducting electricity still and all that matters is you have something is on your hands because in no situation with no amount of voltage, will the electricity ever conduct past your hands.

**Comment by 9600bauds** [comment]
The Captain's gloves are specifically space-proof
Only the captain's gloves AFAIK
It's weird

**Comment by Killette2** [comment]
Well I guess it'd be ok if the captain went in space then with his suit, as long as he wears his gloves. This of course gameplay wise would be a silly requirement, I'm just mentioning realistically you can't go into space in the captains hardsuit alone with nothing on your hands. I still stand by that if you wear a hardsuit over insulated gloves, it will not prevent you from being shocked no matter the voltage.

**Comment by Shadowmech88** [comment]
@Killette2 
I'm simply trying to explain to you that just because a material doesn't completely insulate from electricity, doesn't mean that the material perfectly conducts it over all distances equally.
If you put on some regular old cotton gloves and touch something high-voltage, you're going to get shocked through the gloves. But if you tie a rope of cotton around the high-voltage thing and then grab the end of the rope, the current's not going to travel through all that cotton to get to you because cotton's a poor conductor.

Poor conductivity != complete insulation.

**Comment by Killette2** [comment]
What if the electric thing is wired to the grid for a very powerful shock, wouldn't some of the electricity pass through the cotton rope since there's so much of it? Sure you'd lose a lot of it due to poor conduction, but with that much electricity you're bound to get shocked at certain wattages/watts, whatever is the more correct term.

**Comment by Senaat1** [comment]
Why are you arguing realism in this game.

**Comment by Shadowmech88** [comment]
If there's that much electricity, the rope would probably catch fire before actually shocking you.
Poor conductors tend to heat up when subjected to high current.

Truthfully, once you get into megawatt territory you'd be likely to see arcs through even the air.

**Comment by Killette2** [comment]
Because with current standards, gloves do not go over hardsuits allowing this issue to be made of hardsuits stealthing a stun weapon that is otherwise visible. I'm mentioning that this problem would be fixed, and it would make more sense in general, if gloves sprites were just on top of the suits to begin with.

**Comment by Shadowmech88** [comment]
For the record, I'm not opposed to having glove sprites over the hardsuit layer.

**Comment by Killette2** [comment]
The only thing is, it would probably look ugly in some instances, but we still have a ton of ugly shit like the clownsuit going through everything. It would just take some spritework to work things out, if not just making all hardsuits gloveless like the captains and say fuck it, space doesn't affect hands.

**Comment by Killette2** [comment]
On a side note, I'm kind of liking my picture. When will we get morphsuits from cargo?

**Comment by Shadowmech88** [comment]
When You Code It

**Comment by 9600bauds** [comment]
guys how 'bout them hardsuits hiding stungloves

**Comment by Kitfox88** [comment]
i support showing the gloves over the hardsuit

or just removing them entirely, fuck stungloves :^)
