### ISSUE TITLE
feature request: emergency atmosphic shelters

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#9251]
The problem with plasma flooding and other atmospheric sabotage is that everyone who isn't in a suit and geared up is dead before it can be fixed. People run though firelocks trying to get to safety only to spread the plasma.

What if we could buy more time for people to survive while the air is fixed and the giant scrubbers are set up?

One idea I had was to add fuctionability to the o2 lockers to allow people to close themselves into it to be provided; clean filtered air, a chemical agent that helps slow down damage from plasma contamination, and a mix of chemicals that helps slow down damage and stabalizes people while the plasma is cleaned up.

The benifit to using o2 lockers is that 
A: its already a different color and has a giant o2 on it.
B: its movable
C: you don't have to do any map editing, they are everywhere

**Comment by Shadowmech88** [comment]
Instead of giving the functionality to lockers themselves, put one of these rolled up inside the emergency toolboxes inside O2 lockers: https://en.wikipedia.org/wiki/Gamow_bag

Take it out, use it, it unfolds and puts you inside an airtight tent with clean air inside.
Would obviously not be resistant to plasmafires, and you couldn't move or do anything while inside the tent, similar to being inside a locker.

**Comment by FudgePucker** [comment]
Eh, surviving plasma fires temoararly without having to power game for a hardsuit or cocktail of pills is the point.

**Comment by Shadowmech88** [comment]
I thought the point was surviving plasma floods, not necessarily plasma fires.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
This was fulfilled
