### ISSUE TITLE
The great "how do we rework R&D" brainstorming issue.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#9278]
Let's be honest, R&D is a shit system. It's always the same, there's nothing fun about it.

So here's an issue to discuss how we want to make it not shit.

**Comment by ghost** [comment]
Make the goggles do something, let them tell you what an object is worth regarding research points?

**Comment by SysadminJeroen** [comment]
@Skullyton I agree, the science goggles are somewhat useless right now as you should replace them with a NVG or improved welding goggle right away.

**Comment by ghost** [comment]
Coould redo research altogether, make it into like a research tree that you have to invest points into

Each object broken down yields a certain amount of points, second time you break one down it yields half, third time a quarter, fourth time nothing

Then, you invest said points into progressing along certain branches to progress towards certain things, but let's not overdo it pic related

![Jesus christ it's like a sycamore](https://cloud.githubusercontent.com/assets/9110500/14315540/dc41dbb4-fbf5-11e5-9996-ed9e33182eb1.png)

**Comment by pvak** [comment]
make science goggles give some stats about the object examinated like meele damage, trow force, protection, etc

**Comment by Killette2** [comment]
Science goggles currently do something

They protect you from the flash made by gold and silver slime extracts

yeah... that's about all.

**Comment by clusterfack** [comment]
Make research levels just time-gated button pressing rather than effort intensive.

**Comment by Killette2** [comment]
You mean like borers? That still sounds like shit honestly. And I was thinking of suggesting that instead of synthesizing specific chemicals that borers get a more interesting chemistry tree, such as the ability to synthesize certain elements and putting them together. Preferably while still being more interesting than having a chem dispenser menu.

**Comment by clusterfack** [comment]
Killete are you responding to me or skully

**Comment by Killette2** [comment]
Ok hear out this concept.

Instead of deconstructing objects, you now research tech instead. What do I mean by this? You get a bunch of materials, put them in the protolathe and then put an item, say a crowbar in the protolathe with them. You infuse materials as parts onto the crowbar and see what it does better. This will also come with a tool similar to a device analyzer, but more of a health/plant analyzer for items. You scan your new enhanced crowbar and your machine has no idea what it does. You then test out your crowbar, whack someone with it. Once you THINK you've figured out what it does, you attach your device scanner to it and input what the tech did to improve the crowbar, if you're correct then the scanner will store this information which you can then enhance. If you're incorrect, then you'll be storing incorrect data into research and getting your entire research tree wrong. Let's say you think you discovered tech that makes the crowbar deal more brute damage, that's combat tech. You can then try new tech on your crowbar and it has a chance to make people shift a tile randomly around you, which is obvious to you bluespace. The lower the tech, the lower a chance of it's effect happening would be, so this would require a lot of field testing, meaning you actually do something in the RnD job. You could then try to fuse your combat and bluespace tech to have both parts on a weapon or object. Thoughts on this form of RnD? It would be more sciencey like genetics or xenobotany when you do something and see what happens, then work with your results.

@clusterfack 

A time lock is boring, experimenting/activity is fun, and would actually be able to be labeled 'research'

**Comment by clusterfack** [comment]
@Killette2 
I believe you are wholly wrong, the only thing you can say is really 'experimenting' is some minigame if its not some variation of a minigame the whole thing is just a repetitive chore done at roundstart every game.

And unless that minigame is actually fun the whole system is shit and better suited to simply being time gated content like it's meant to be (I saw this on goon's code a long time ago and it was much more fun to play than simply playing fetch with components like we have now).

**Comment by Killette2** [comment]
While I will say time gate is better than fetch item, I also won't argue that things like genetics and xenobotany aren't repetitive.

However I like the idea of being able to attach parts and upgrade items instead of solely "research levels, get this specific item"

**Comment by Killette2** [comment]
And if we don't intend to make it a minigame what do we make it? A recipe guide where we put certain numbers in to unlock items and they're all posted on the wiki? Most things are minigames like virology, xenobiology, xenoarch, xenobotany, genetics, mining, wires involved in hacking. Hell SPESS is a repetitive minigame

**Comment by gbasood** [comment]
I think having research be time-gated makes it easier to 'balance' tech progression because, as is the nature with time-gated research, they can only hit 'endgame' when enough time has passed.

But I also think that removing item deconstruction makes R&D completely uninteresting, because it goes from 'go out and find shit to salvage for those sweet tech levels' to 'babysit the research computer and do nothing interesting all round'. Same goes for R&D minigames.

Maybe some sort of combination of all three?

**Comment by clusterfack** [comment]
I only see three ways that a progression system can be based upon without being boring as shit
1. Simple time gating
2. Minigame based
3. Dependent upon another department for progression

I think 99% of the progression systems in game fail by almost any metric you could apply to them

**Comment by gbasood** [comment]
> 1. Simple time gating

Boring as shit

> 1. Minigame based

Boring as shit

> 1. Dependent upon another department for progression

Already exists, mining.

The problem isn't that other game systems fail when it comes to research. Research in their games aren't the focus. You do other things while you wait for research. But SS13's research guys have literally nothign to do but research when it comes to doing their job, and making them sit and stare at their timegated R&D is just plain bad.

**Comment by clusterfack** [comment]
I don't think time gating is boring at all, while it has nothing 'interesting' to it there doesn't NEED to be anything interesting to it. Something like genetics or current R&D is boring, which is actively repeating the same task every single round.

**Comment by gbasood** [comment]
@clusterfack Okay but what do you think R&D staff will be doing if we just timegate research as a solution

Because as it is, they're basically just glorified greytiders who help the station while simultaneously acting like huge shits.

**Comment by clusterfack** [comment]
I hardly think R&D's 5-10 minute time waster is really making a difference in that regard.

**Comment by gbasood** [comment]
Here's what I predict would happen if we just throw timegates in:

Instead of R&D doing their shittery AFTER research is done, they'll do it before. Because making research less rewarding by, for instance, timegating it, makes them want to actually do their job less.

**Comment by clusterfack** [comment]
Well that's a really negative and odd way of looking at things, but if you insist of thinking of it as scientists just being 'general shitters' at least they'll be doing it without a bag full of printed guns because they haven't finished researching them yet.

(Also you cant honestly tell me that scientists would want to do their job less if it was easier, come on)

**Comment by gbasood** [comment]
There's a difference between it being easy and it being completely unengaging I think
Asking them to babysit a machine to get research levels is the least interesting gameplay mechanic I could think of

The reason timegating works in, for instance, Subnautica, Civ, etc. is because research isn't the actual focus of their tech trees and such, it's just a means of progression which is left alone while the player heads off and continues playing

In SS13, we have an entire department whose job is to do research. If their job became 'babysit the minigame/countdown machine' it'd literally be less fun than xenoarch

**Comment by clusterfack** [comment]
It rewards them for being **IN** science at least periodically. The current R&D system only really supports you being in there for the first 5 minutes and then for about 3 minutes after you get materials so you can print shit once then fuck off.

**Comment by gbasood** [comment]
Well like I said, I like that aspect of timegating R&D. But if we replace the current system with a system that is ONLY timegating then it's just a computer babysitting simulator, which I think is a step in the opposite direction

**Comment by clusterfack** [comment]
Personally I think the biggest draw of SS13 is more likely the interaction between players not its minigames. And that gameplay mechanics should be based around interactions instead.

**Comment by PJB3005** [comment]
I would like to expand on @Skullyton's idea.

#### Progression

I think we should make it so R&D starts out really fucking slow and inefficient. As in, manipulators-take-multiple-seconds-to-make-slow and take an entire sheet of metal.

Over the course of the round R&D will be able to improve and if the crew isn't too terrible / distracted they should be up to speed (where we're at now) after about ~1.5 hours.

It should also be made that without help from mining you literally _cannot_ get up to the best parts, unless the RNG loves you with vaults / xenoarch.

#### So, that's general progression, but how would it work in practice?

So, as @Skullyton said, I believe a general research points system would be a good idea, but it wouldn't be so straightforward as simple unlocking it and there you go.

In addition to a cost of research points, my idea is to have a "CPU speed" system. You could use 10% of the **R&D server**'s CPU on say, improving the design for nano manipulators (more on improving later), while spending 90% to do something else.
Doing something would take a certain amount of time, and the more CPU you give it the faster it would go. _I think CPU should play a major role._  to unlock high-capacity power cells might be 100 CPU cycles, but to unlock pico manipulators would be 1,000,000 CPU cycles.

You can't just rush to the best stuff, you'll have to gradually improve your machinery (and get help from other departements, especially mining) to be able to get up there.

Also xenoarch should be able to provide quite big boosts to the research progression.

Then there'll also be a limit of the machinery in R&D being physically unable to make the more advanced stuff, but still being really inefficient, so you'll be using 5 sheets of uranium to print out a couple basic parts to get your machines able to progress.

#### Improving

Instead of "you now have this unlocked have fun", I think there should be a form of "progression" when researching a design (with your **precious** CPU cycles).
Early in the researching of a design you can't build it, period. As the research goes on you'll quickly be able to build and use it, but it'll be poor at it's job (even worse than previous tiers, say poor nano manip vs good micro manip), very inefficient, power consuming, **_and flat out unstable**_ and able to damage for example even the APC with power surges. The more time you spend the more efficient it'll be, and eventually you'll reach a point where the design is "done" (but can still be improved on)

This would add interesting dynamics where you can risk to print out an unstable design to get ahead, but if luck isn't on your side you'll end up blowing up the R&D lab's APC.

After a design is "done" improving it would improve everything (cost, speed, efficiency...) but you'll hit diminishing returns the more CPU time you spend.
