### ISSUE TITLE
Mysterious Magic Inventory Mirroring

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#9340]
Now THIS is a weird bug.

@Gringonius and I were retrieving my shotgun from someone who stole it
He clickdragged the satchel containing the shotgun to open it, but didn't actually take the gun out
I picked it up, opened it, took the gun out, and stuck it on my belt
He then commented that he could see the gun on his belt, but not interact with it
I took it off my belt to show that I actually did have it, and he commented that it appeared in his hand for a second
So I switched it between my hands for a while, and sure enough, he saw that, too
Wherever the gun was in my inventory, it appeared in his, too
This applied to only the gun, no other items

I did ahelp it, but nobody replied, so I don't have any VV info for you. Sorry.

**Comment by Probe1** [comment]
hold up.  what kind of bag and shotgun?

**Comment by Exxion** [comment]
Regular bag, sawn-off

**Comment by gbasood** [comment]
Pretty sure that the actual shotgun was only in one inventory
I've seen this bug happen before in really weird places (facehuggers)

**Comment by Exxion** [comment]
Yes, it was only physically in my inventory, it just appeared in both

**Comment by Gringonius** [comment]
I could see whenever he wore it in his back, belt or hands but I don't think he ever dropped it on the floor for me to check if that would fix it.

**Comment by Exxion** [comment]
It was never on my back because the sawn-off doesn't fit in the back slot
But yeah, I forgot to try dropping it

**Comment by Shadowmech88** [comment]
After further testing:
The mirrored inventory only happens if the bag is picked up and then the item is taken out, not if the item is taken out while the bag is on the ground.

If person B stands adjacent to person A and picks up the bag, the inventory window disappears for person A, preventing the shared inventory. If person B stands adjacent to the bag, but not adjacent to person A, the inventory window persists for person A. Dropping the bag adjacent to person A and then picking it up again while adjacent to person A will still cause the inventory window to disappear, though dropping it and picking it up again from anywhere else will not.

Person A seems unable to know anything about the state of the bag. Items placed into it from person B's inventory will not appear. After being separated from the bag, the only mirroring is in the apparent position of whatever items were removed from the bag before person A closed the inventory window.
If person A closes the inventory window, the mirrored item will still appear where the inventory window would be if person B places the item inside a bag.

If person B drops the item, it will cause it to disappear from both players' inventories. *However*, if person B picks up that same item, it will reappear in the same place inside person A's inventory. The same goes for if someone else picks the item up. In effect, it seems to act as a way to always know where a specific item is in any person's inventory, regardless of being dropped, moved, given to another person and then taken back, et cetera.

If person A ghosts and re-enters their body, or picks the offending item up themselves, the effect will stop. Otherwise, nothing in testing seemed to get rid of the effect.

**Comment by Shadowmech88** [comment]
I believe this qualifies as exploitable, since with two people cooperating one of them can become able to know when any given item is in any person's inventory. A captain could for example both hide the nuke disk and be capable of instantly knowing if anyone picks it up.

**Comment by Shadowmech88** [comment]
It seems this bug no longer exists. A bag being picked up causes the bag's inventory window to close for anyone who currently has it open, even the person picking up the bag.
I'm guessing some change to inventory code in the past year inadvertently fixed it.
