### ISSUE TITLE
WE NEED TO BUILD A WALL AND WE NEED TO BUILD IT QUICKLY

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#9346]
Return the ability for admins without +permissions to put the bunker on for a round for round basis.

No, we're not trying to force our secret illuminati agenda to make the server a white list only. Jesus tap dancing fucking christ.

We just want the day 0 griffin rapefugees out.

**Comment by BestName** [comment]
Make /vg/ great again!

**Comment by Probe1** [comment]
please no.  it was misused in the past and resulted in the playerbase stagnating.  we need a solution but the panic bunker is using the wrong tool for the job.

we're not getting raided and when we are then it should be used.

**Comment by ghost** [comment]
I'm not sure what you mean here. If you don't have +PERMISSIONS, you can still toggle the bunker for a single round (if not, needs a bug report up). But you can no longer permanently toggle it (it's been a while) and perma toggle works again (fixed recently due to bunker being up for way too long)

If two hours of panic bunker isn't enough, contact any of the three headmins and get them to perma-toggle, but the best defense stays observing newly joined players to make sure they don't do anything dulb

**Comment by Imagebard** [comment]
>it was misused in the past

Okay let me see if I got this right.

>THE BADMINS ARE ACTING _WRONG_
NERF THE GOODMINS

**Comment by Duny-** [comment]
>THE BADMINS ARE ACTING WRONG
>LETS FUCK OVER THE GOODMINS

Isn't that how life works?

**Comment by clusterfack** [comment]
The admins showed time and time again they couldn't be trusted to use it responsibility so it required a higher permission level so only more trusted admins could use it. This is LITERALLY how the system should work people.

**Comment by AutismSpider** [comment]
>trusted

>any of the headmins

oh wait you're serious 

let me laugh even harder

**Comment by mrpain666** [comment]
Well this clearly isnt getting changed anytime soon so I'll just close it.

I'm going to have an "I TOLD YOU SO" moment next time we get raided and both people with +Permissions arent around to do anything. Nothing personal, just business.

**Comment by Probe1** [comment]
look we haven't been 'raided' on the level that inspired the panic bunker since it happened that fateful month.  I think we've only had any sort of raid whatsoever 4 times since the bunker was made, and they were over in 24h.  

one guy popping in on a new ckey to ebin plasmaflood isn't a raid.  it's day to day lol fuck that guy permaban business.  if it happened more often than once a week/few times a month I'd be inclined to agree with you but it is very uncommon and actual raids are very rare.

what we need are better tools to prevent ban evasion and everyone knows it.  however using the panic bunker to stop 1 guy and block all new players is not the solution and we said that so often but were not heard.  so saving the panic bunkers settings was moved to permissions, leaving admins able to turn it on every round but not leave it on.
