### ISSUE TITLE
Balance Request: Surgeon's Switchtool

### ISSUE THREAD

**Issue by Brolaire** [d3athrow/vgstation13#9352]
#### Description of issue

Surgeon's Switchtool is absolutely useless. There's no reason to make these since handling the menu is bad enough and most of the time slower than just dropping the other tools and picking a new one up.

I would personally like it if the surgeon's switchtool is no longer considered a normal item. This is just a small change, but it allows us to cram it into medibelts, pockets, labcoats etc. and allows for on-the-go surgery. Give it more purpose besides "all-in-one surgeon kit that takes up just as much space as all the regular tools. This shouldn't be a game-breaking balancing request.

**Comment by 9600bauds** [comment]
Balance request: Remove the surgeon's switchtool so R&D will stop making it and thinking it's a replacement for the proper advanced surgery tools

**Comment by Intigracy** [comment]
It doesn't fit in pockets?

I know it fits in medibelts.

**Comment by Probe1** [comment]
its like 5 tools in one so saying it takes up just as much space is misleading.

its not supposed to be an end all replacement like an incision manager I think.

**Comment by Brolaire** [comment]
It does not fit in pockets or medibelts.
Tested: Three rounds ago, today.

**Comment by Intigracy** [comment]
Was it set to a tool?

**Comment by Brolaire** [comment]
no

**Comment by AutismSpider** [comment]
its useless no matter what you do to it laser scap and  incision manager out class it but crap ton

**Comment by uazuaz** [comment]
at the moment it works this way: let's say you're using the switchtool and you need to change the tool you're currently using, you must

> click on switchtool to close it
> click to open the options window
> click to choose the new tool
> click ok

so you need 4 clicks to change a tool.

if you can, you should change the option window this way

![st](https://cloud.githubusercontent.com/assets/6170726/14411427/1178b9f6-ff48-11e5-8349-b529f8d6046b.jpg)

so the new cycle will be

> click on switchtool to open the options window
> click the tool you need or close it with the "no tool" button

so, the cycle to change tools will be 2 clicks only.

---

if you can't change the option menu, you could modify it this way:
-add a "no tool" option to the tools list
-let the option window open everytime you click the switchtool
this way you will get rid of the "close switchtool" click and the new cycle will be:

> click to open the options menu
> click to choose either a tool or the "no tool" option
> click ok

so, the new cycle will be 3 clicks instead of 4

i know it's just a small improvement, but it's still better than the way it's now.

**Comment by ihadtoregisterforthis** [comment]
If the window could stay open, that would be great. Like with the RPD, where you need to change quickly between modes.

**Comment by uazuaz** [comment]
that's good too, just 1 click to change tools

**Comment by Probe1** [comment]
damn son that's some fine win98 UI.

**Comment by PJB3005** [comment]
@Probe1 you mean win XP

**Comment by Probe1** [comment]
i ruined it.

**Comment by uazuaz** [comment]
that's the power of an online error message generator + gimp.
