### ISSUE TITLE
Deff - Derelict incinerator won't glow green in a rad storm

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#9382]
#### Description of issue

As described by the title: the incinerator won't glow green but at the same time it's not shielded from radiation at all, turning it into a death trap if you're in the middle of the derelict tunnels. 
I really haven't really had the time to check if other rooms but I ask Duny to be through about this. The derelict parts of the station are fucking gigantic and there's no safe spot from a rad storm at all in there.
#### Server revision

b8d64d416bb66b6cdd9013a80cc439218f44bc25

**Comment by Probe1** [comment]
Those big radiation signs are warnings that x area isn't protected.

**Comment by Exxion** [comment]
This applies to the _entirety_ of Deff Derelict because the way radiation warning lights work came to bite us in the ass

**Comment by PJB3005** [comment]
Isn't it that they don't work if there's a lack of power?

**Comment by Exxion** [comment]
I'm pretty sure they work in the main station even if the power is out, but I'm not sure
If not, then fuck

**Comment by Probe1** [comment]
I'm pretty sure that it's entirely different part of the code that doesn't even involve power.  If I remember right and I'm not at home to check this it just does a check to see if the area is protected from radiation and flashes a green overlay if it's not.

**Comment by Exxion** [comment]
That's clearly not it, because then this wouldn't be an issue, unless somebody fucked up on that check
Which I guess is not out of the question

**Comment by Probe1** [comment]
What I'm saying here is parts of maintenance is not protected they are marked by the radiation signs

**Comment by Exxion** [comment]
Yeah, and that's better than nothing, but not as good as if the radiation overlay actually worked

**Comment by Gringonius** [comment]
As far as I'm used to see the only warning of whether a part is shielded or not should be the lack of green glow.

**Comment by ghost** [comment]
There's a list of areas that become highlighted if a radstorm is in effect, problem is adding the 'derelict' areas in deff to the list would mean that the actual derelict would probably start glowing too, as it uses similar areas

That and duny a shit

**Comment by Duny-** [comment]
The list you're talking about is of areas which are safe and therefore not highlighted, not of the ones who are. Every area not in the list glows (except space of course).
The derelict areas of deff are named "/derelictparts" and not "/derelict", I'm not retarded.
They don't glow because they're not powered. Which makes sense since I don't see how green lights would be blinking with no power source. On top of requiring me to actually code instead of just map I'm not sure if I should be "fixing" unpowered lights being unpowered to begin with. Which is in part why I made the huge warning signs instead back then.

**Comment by Shadowmech88** [comment]
Apparently not a bug.
