### ISSUE TITLE
Why don't we have a gravity generator?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9400]
Discuss.  

I was looking at a tg derivative and I can't help but think "Why the fuck not"?  Is this something people _don't want_ ? Or is it just something we've been unwilling to port?

**Comment by ihadtoregisterforthis** [comment]
There's one on the code.
I'd rather not drift helpless everytime someone touched it.

**Comment by 9600bauds** [comment]
I played with it once and it didn't seem terribly interesting

**Comment by Killette2** [comment]
Is there anything remotely interesting about it or is it just an on and off switch? If you could do something like intensify the gravity on the station, that would warrant having it.

**Comment by liltiptop** [comment]
Because there's really no reason to have it. If you wanted to buff gravity like @Killette2 said, then you're good. But I personally think that a gravity generator is not needed. If you WANTED to do something similar to that, why not place a singularity under the station, that provides artificial gravity? But again, gravity is fine as it is, IMO.

**Comment by Brolaire** [comment]
okay so, i played a lot of rounds with gravgens. When I played on /tg/, the GravGen was where the AI core/upload is now, and the AI had its own satellite southwest of the station. EVERY TRAITOR/DOUBLE ROUND WAS THE SAME in the sense that people would spawn c4 or a minibomb and destroy the gravgen, resulting in stupid rounds where people would figuratively murder each other over magboots and plenty of people were left in awkward situation for most of the round because they somehow got stuck in the center of the hallway without anything to throw besides their ID. Unless this was heavily changed or you plan on changing this heavily, the Gravity Generator is a 3x3 machine which needs constant power to function and becomes an unrepairable piece of scrap metal as soon as one part of it breaks, leaving the station crew floating in the most peculiar way.
Add a gravity gen to some other space constructs, but not the main station.

**Comment by FudgePucker** [comment]
Yea grav gens are a bad idea gameplay wise.

They will get sabotaged easily by pretty much every single antag.
They will shut off every other round due to no power.

You know how annoying it is when no one sets up power? Imagine that but with no gravity.

**Comment by Intigracy** [comment]
Because they suck.

**Comment by 9600bauds** [comment]
yes that's what gravity does

**Comment by Intigracy** [comment]
Making station act the same way as space / getting stuck in the middle of the hallway when the generator is destroyed may be fun the first few times, but it gets old fast.

**Comment by ghost** [comment]
What if you were able to swim through the air if there was no gravity but there was enough pressure?

**Comment by Probe1** [comment]
Well if no one else likes my engineering autism then I won't insist on it.

Also what is wrong with people?  Why would you _destroy_ it when you can _increase the gravity and crush everyone_?  smhtbhfam

**Comment by Brolaire** [comment]
see this would be interesting as a random event: gravity shifts. station floats too close to a very large star? everyone either walks super slow or is forced to crawl. or some other bullshit explanation as to why you suddenly float through the air or similar.

**Comment by Probe1** [comment]
We already have an admin button that does exactly that, and we often push it to spice up a round.

**Comment by ihadtoregisterforthis** [comment]
Shifting the gravity direction when? Anything not anchored to the ground gets slamsed into a wall and the icon direction changes accordingly. Space Station 13: platformer

**Comment by Killette2** [comment]
The fact that ss13 is already a topdown, the gravity direction would fuck with my head. The people with magboots would be walking on the walls per say due to the gravity shifting, but would still appear topdown...

**Comment by Probe1** [comment]
Thanks for the discussion guys.  I hoped we'd want the thing because I love engineering stuff but its clearly not as fun as it seems in practice.

**Comment by Killette2** [comment]
Engineering needs more toys that have to do with grid power, so we can do things more with numbers. Atmos finally has decent toys, but how come we don't have more electric related things in the grid? Tesla coils and random shit, something more deadly than emitters, mirrors, and prisms (deadly translates into fun).

**Comment by ghost** [comment]
More machines that require not only a direct connection to the power grid, but also a minimum amount of power to remain functional such as the gateway could be neat.

Always thought some form of asteroid defense system would be a useful application, either as a solid state shield that would be steadily ablated and reconstruct itself when hit by something explosive, or maybe some turret system to attempt to disrupt and destroy incoming objects, either as static turret systems, or re-purposed combat drones that are deployed at the push of a button to patrol a certain area.

**Comment by Killette2** [comment]
Being able to make pretty much a static fly net around the space station sounds horrifying. Space a changeling and if he ever tries to float back through space he gets zapped.

**Comment by Brolaire** [comment]
I like the idea of new engines, maybe something not collector array related. What about something more primitive, like a windmill or watermill, or maybe a coal engine. give the bar a real great depression vibe by serving nothing but hooch and burning your tables and chairs to not freeze to death

**Comment by Killette2** [comment]
We have a coal engine, except it's called PACMAN

**Comment by ghost** [comment]
Bio generator that runs off botany crops when?
