### ISSUE TITLE
Movement delay in space is really wacky

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#9415]
First of all, your glide speed gets lower the longer it has been since you tried to change your sprite's direction (Ctrl+Arrow key) (up to a point; it stops when it gets to about a third of your actual movement speed, which takes about five tiles of movement). When you change your sprite's direction, your glide speed jumps back up to maximum then gradually drops again. This is purely cosmetic; it changes how quickly you glide between tiles, but doesn't change the actual speed at which you drift.

Second, and more importantly, if you change your sprite's direction at exactly the same time you move, you stop moving. This is not purely cosmetic; you actually stop moving.

**Comment by Probe1** [comment]
Noticed this weirdness while observing this morning, and it applies to observers.

**Comment by Exxion** [comment]
I noticed the first part long ago and just never got around to reporting it, but I just noticed the second part right before I made the report

**Comment by clusterfack** [comment]
Is that why people get stuck a few times out into space? It could explain an old mystery.

**Comment by Probe1** [comment]
Maybe.  I'd love that particular mystery to get solved.

**Comment by SangriaMonkey** [comment]
I thought it was just me but I guess it really was fucked up after all.

**Comment by ghost** [comment]
Our inertia code is awful code attached to the awful code that is Move() code

Good luck fixing it, especially if you want something descent like proper inertia, aka conservation of movement and addition of further propellants to movement speed

**Comment by Exxion** [comment]
That would require things to have mass anyway
Which would require adding a variable to every single movable atom

**Comment by ghost** [comment]
On the short term, you can likely abstract mass based on w_class for objects, mob size for mobs (defines were added recently), and turfs and areas never move

**Comment by Intigracy** [comment]
:+1:

**Comment by ghost** [comment]
I'm most likely going to make actual learned people cry, but movement can be abstracted as such : 
- No variable shit, movement variables aren't complicated (speed is the derivative of displacement, and acceleration is the derivative of speed) but we can do without
- Ec = 1/2mv². Ec being, of course, kinetic energy. If we abstract kinetic energy, this means that when you change the mass by a factor a, the speed changes by a factor sqrt(a)
- Law of inverse reaction. In a vacuum (in atmospheres, can be abstracted as knockback), throwing an item means you are thrown back with a force inversely equal to the item's force (aka F(a>b) = -F(b>a)). Aka if you throw a small pen of a tiny mass very fast, it knocks your significant mass slightly back with equal force
- The momentum p is such that p = mv. The force is also such as F = ma
- Acceleration is pretty simple, an acceleration of x means your speed is x*t, where t is the time since observation started. So if your jetpack, via inverse reaction, pushes you with a force F, you accelerate by F/m. This means you will quickly accelerate. In that case, we just need to define an abstract "propellant force" for the jetpack
- All movements that aren't vehicles or propelled can likely be abstracted as constant linear movement, whereas a = 0 and the speed is constant

**Comment by Exxion** [comment]
Honestly, I don't think totally proper Newtonian physics would work well for us. This game is based more on tropes than realism, after all. And considering a backpack can hold several tons of iron but only a few grams of paper, balancing actual conservation of momentum with gameplay would be difficult.
That said, our inertia code is pretty ass. I'm not sure if a total rework would be worth it without pixel movement, though.

**Comment by ghost** [comment]
Pixel movement sounds fun and I'm pretty sure it's been suggested for ever now, but it's likely harder than it sounds

**Comment by Exxion** [comment]
I know it's hard
But it's also cool

**Comment by Shadowmech88** [comment]
Tested locally, could not reproduce. I believe we've made changes to space movement since this.
