### ISSUE TITLE
Robotic Chat and Instances of "Borg" 

### ISSUE THREAD

**Issue by SerWind** [d3athrow/vgstation13#9434]
While I'm here I might as well bring this up as I've always wanted to. Can we get some other colour for robotic chat besides black that's simply put in italics? It's easily lost under a swarm of chat and actions, at least I find (maybe I'm just bad), and I miss the AI kindly informing me about important things.

Also would be neat if sentences with borg in them were some how highlighted for a borg player, but I'm not sure how possibly this is.

**Comment by kol1th** [comment]
I've never had a problem with it. The italics make it identifiable, for me.

**Comment by nuklearcellphoneg** [comment]
Since :B is so unique it wouldn't be bad to(I know our chat capabilities have been expanded) to bold or or be larger. Wouldn't be a bad idea to have it this way for, say, ling chat, cult, etc(though cult is pretty noticeable already).

Honestly, being able to set certain chats to pop up in the Special tab could be cool too.

**Comment by Allspice** [comment]
Goonchat bolds things for no apparent reason, so that might not be so good. Larger font for binary sounds okay.

**Comment by PJB3005** [comment]
@allspice if there's anything being incorrectly bolded report it, it's trivial fixes.

**Comment by unid15** [comment]
@SerWind you can already highlight certain strings that appear in the chat
![](http://puu.sh/ohUqS/c43828ecc2.png)

**Comment by SerWind** [comment]
Sheeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeit. That's amazing. Thanks!
