### ISSUE TITLE
Request: Icon for Unconvertable/Team antag Opt-out

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#9457]
Since being unable to convert someone is basically a huge hassle for the cultist/rev who attempted the conversion(oh i have to dispose of this guy before he wakes up), to ensure that things are not to the disadvantage of the antagonists of their respective mode, can we just get icons, like the cultist green blob or the R or whatever, which indicates that someone is PRO NANOTRASEN ALL THE WAY, or basically not able to be converted(job ban, so on and so forth).

---
## HOWEVER, DO NOT APPLY  THIS TO PEOPLE WHO HAVE AN IMPLANT, AS THIS SHOULD ONLY BE INDICATED VIA THE SEC HUD.

If the above is put through, could we expand the function of the Role Selection bit of character creation, so that if someone does NOT tick Rev/Cult, then they also can't be converted, or perhaps tie it in with the Pro/Anti Nanotrasen thing?

This way, it's very clear who you can and cannot convert, whether it be due to being banned, hating the game mode, being unready for antag modes, etc etc etc and further removes admins from having to moderate who can or can't play cultist/rev. It's not a big hassle but it's kind of annoying.

**Comment by Intigracy** [comment]
Just because you don't want to be a roundstart rev/cultist doesn't mean you don't want to be converted to one.

**Comment by nuklearcellphoneg** [comment]
Are you sure? I think they go kind of hand in hand. Again that was the bit I wasn't sure about.

**Comment by nuklearcellphoneg** [comment]
Separate it into Head Rev/Head Cult and then convert Cult and Rev roles???

**Comment by ihadtoregisterforthis** [comment]
I personally don't tick cultist to avoid being a head cultist, but if I happen to be converted I'll do what I must. Do you think many people would tick to be able to be converted if it was their choice?

Also _muh e-mansions_

**Comment by PJB3005** [comment]
:+1: on the icon for antags to see whether somebody can be converted or not.

:-1: on the ability to disable being convertable to rev/cult.

**Comment by Probe1** [comment]
I like my idea of cult/rev bans making people go catatonic on conversion.  It's simple.

**Comment by Intigracy** [comment]
coverttarget.drop_everything() (or whatever the proc is)
qdel(converttarget)

**Comment by ihadtoregisterforthis** [comment]
Catatonic on conversion sounds fair. If you don't want to, or proved to be unable to play these modes, just observe where you can't be a bother.

**Comment by Imagebard** [comment]
That leaves the cult a body to deal with.
We've been over this before.

**Comment by SysadminJeroen** [comment]
@Imagebard Catatonic is not that suspicious.
It is worse to have a body gibbed or alive and kickin' with a headset on the head.

**Comment by Blithering** [comment]
Catatonic on convert seems the best way.

**Comment by nuklearcellphoneg** [comment]
Problem with catatonic on convert is like of you want Medbay as a conversion center and you spend twenty minutes stealthily kidnapping and converting the CMO or spend forever removing an implant from a sec officer, then just end up with a catatonic body. No reward for the efforts of the cultist.

**Comment by nuklearcellphoneg** [comment]
IIRC everyone except jobbanned people, chaplain, and captain can be converted

**Comment by Shadowmech88** [comment]
Does the captain have some special protection? I'd assume it's just because of his loyalty implant.

**Comment by nuklearcellphoneg** [comment]
Nah he's completely NT loyal(iirc). I've removed the implant before and gotten no dice.

**Comment by nuklearcellphoneg** [comment]
After all he's cap for a reason.

**Comment by Killette2** [comment]
![1453299238082](https://cloud.githubusercontent.com/assets/5169310/14594695/dac7c572-0506-11e6-854d-2adac96c4290.jpg)
Hold up
_smokes a blunt_
You be sayin
_robs a gas station_
that we
_hits a bong_
are havin
_sucks a chicken leg clean off the bone from KFC_
problems with
_steals a watermelon from walmart_
cult and shiet?

Here's a solution

If some one is shitter enough to ask for/deserve a cult ban and you try to use a convert rune, delete the body or leave the stuff they were wearing behind. In their place, an empty soul stone will appear. Cultist receiving a soul stone for an impossible conversion is much better than having to dispose of a body, and people may think twice before requesting a ban from a mode that requires 9 people just because they're too lazy to read the wiki. This is better than forcing people to go catatonic, and gives the cultist something for their effort.

This should not apply to implanted people however, implants are a good prevention from getting culted.

**Comment by DeityLink** [comment]
...Fixed?
