### ISSUE TITLE
Rejuvenate doesn't fix husking

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9526]
husk a dude, rejuv, he is still a freaky walking husk

**Comment by Shadowmech88** [comment]
I would expect this is also a problem for lings that are husked and then revive themselves.

**Comment by icantthinkofanameritenow** [comment]
I noticed that a while ago last time I was a ling, but I was never really sure if it was a bug. And yeah, it's a huge "I'M A CHANGELING" sign to anyone who sees the husked guy walking around normally.

**Comment by nuklearcellphoneg** [comment]
I always considered it a feature; One time as a ling I got thrown out of an airlock without a hardsuit, landed on that giant derelict medical ship thing, couldn't find a way in. I found the front of the ship and banged on the front window, because a guy was inside: He freaked out and ran away.

Maybe consider allowing Lings to shed their skin for a new one upon rising or something.
