### ISSUE TITLE
Should Metal Foam Be a Turf?

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#9546]
Metal foam's intended purpose is for the quick sealing of breaches. However because it is dense, you can't easily repair the sealed breaches because you have to break the foam first, re-opening the breach. Not to mention that passage through the breached area is impossible due to the foam.

Should metal foam be made into non-dense turfs instead of dense obstructions, so that you can walk over/build on top of holes that are sealed by metal foam?

If people would like to keep the current obstructing metal foam as well, it could easily be made into a different recipe under a name like "dense metal foam."

**Comment by Kitfox88** [comment]
I'd dig it. It's still super fragile so you want to repair it ASAP but it'd at least stop ZAS from striking again constantly.

**Comment by Exxion** [comment]
I'd say have the usual metal foam reaction create both. Have it do what it does now, but also place a metal foam turf under any dense foam placed over a space tile.

**Comment by 9600bauds** [comment]
I'm like 80% sure it only makes a wall if there is flooring under it. It does create just a floor if it's done over a breach.

**Comment by Exxion** [comment]
Nope. Just tested it. Only walls under any circumstances.

**Comment by 9600bauds** [comment]
Wow, yeah
that's stupid

**Comment by Blithering** [comment]
I'd prefer porting the inflatable barriers when it comes to patching a breach, the metal foam is good for sealing areas that are being abandoned for various reasons.

**Comment by Shadowmech88** [comment]
What reason would you have to abandon an area, and seal that area with metal foam?
Monsters? They could just bludgeon through it. Metal foam is incredibly weak.

**Comment by nuklearcellphoneg** [comment]
Thumbs up to wall and floor.

Thumbs up to, if floor is created over a breach, it has a life time of X, similar for floors.

**Comment by Probe1** [comment]
@Shadowmech88 The other week badmins crashed the clown roid into securities west side on Box.  I knew I was looking at a long and probably impossible job so I just sealed off everything north and west of the left cells and interrogation.  Focusing on the damage in the central areas of security allowed me to complete repairs in under 30 minutes and let security continue to function as a departmental location in a limited capacity.

It's not often, but it does come up.  I did not use metal foam in this case however because the effort in getting metal foam almost always outweighs the time otherwise spent fixing the mess.  It's a "plan ahead" kind of tool and not a reactionary one.

**Comment by nuklearcellphoneg** [comment]
There should be an analog chemist role for Science which relies on them making metal foam, mutagen, etc

If a Medical chemist does his job, he hasn't a lot of time to make some Metal Foam grenades.

As it stands, Science is in a good position and CAN do this, but it's a hassle.

**Comment by 9600bauds** [comment]
Solved by #9753
