### ISSUE TITLE
Meatspiking monkeys is not logged

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9550]
might be important if someone meatspikes a monkeyfied human 4noraisins

**Comment by Shadowmech88** [comment]
Aren't monkeyfied humans valid due to monkeys in general being valid?

**Comment by 9600bauds** [comment]
I don't really support that notion, and I generally don't see people immediately jumping at the chance to valid a monkey in any case

**Comment by Shadowmech88** [comment]
Well yeah most people don't kill monkeys for no reason because it's kind of dickish, but last time I asked an admin about it they said if a monkey was being a nuisance there's no penalty for killing it, same as with diona nymphs.

As far as this request goes, wouldn't it make more sense to log only the spiking of monkeys that have minds? No need to clutter the log with the spiking of monkeys that have never had a player inside them.

**Comment by nuklearcellphoneg** [comment]
> As far as this request goes, wouldn't it make more sense to log only the spiking of monkeys that have minds? No need to clutter the log with the spiking of monkeys that have never had a player inside them.

SPIDER DESTROYED WINDOW AT X

SPIDER DESTROYED GRILL AT X

**Comment by 9600bauds** [comment]
Rowan Leaf has added 10u water to the hydroponics tray at hydroponics (245, 312, 1)
Rowan Leaf has added 10u water to the hydroponics tray at hydroponics (245, 312, 1)
Rowan Leaf has added 10u water to the hydroponics tray at hydroponics (245, 312, 1)
Rowan Leaf has added 10u water to the hydroponics tray at hydroponics (245, 312, 1)
Rowan Leaf has added 10u water to the hydroponics tray at hydroponics (245, 312, 1)
Rowan Leaf has added 10u water to the hydroponics tray at hydroponics (245, 312, 1)

But yes it's totally doable to only log monkeys with a mind

**Comment by PJB3005** [comment]
PJB3005 (ROBOT-THINGY) has closed the opened and alarming firelock
