### ISSUE TITLE
Revert default telecomms due to balance

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9552]
What I mean by this, is how telecomms by default now states your job title beside your name.

You can easily see where this makes being an imposter over comms very difficult if not impossible as a changeling using the mimic voice ability.

**Comment by ihadtoregisterforthis** [comment]
At which point was this changed to what it is now?

**Comment by Exxion** [comment]
Many months ago.

**Comment by PJB3005** [comment]
When N3X15 rewrote saycode.

**Comment by Killette2** [comment]
Yes this is a pretty old change, and being a changeling or having someone else's ID is pretty much the only two, but still, issues regarding this.

**Comment by Exxion** [comment]
Honestly, most people don't even pay attention to the job on the radio message
I almost got brigged once for something someone said over radio as me using a voice changer

**Comment by Killette2** [comment]
Not in my experience. I was a clown changeling, mimiced the captains name and read WGW over the radio only to fuck up and realize the title Clown was beside my name. I then hid my PDA in my pocket and continued for a blank name, but the Captain then spoke over the radio and with captain beside their name and nothing beside mine, it was clear what was going on.

It was such a blunder that the captain let me off with a warning, not even bothering to check me for contraband or any antag related things.

You can also meta off of headset image sprites, like telling the difference between a standard and an engineering one by the color, and minings have the antenna making them very distinguishable.

**Comment by nuklearcellphoneg** [comment]
If it CAN be an issue, then it IS an issue, because it's a bummer when things go wrong because of something that should work but is out of your control and you weren't aware of the problem.

After all, your average player is only going to find out once they attempt these two scenarios, and at that point it's too late.

**Comment by Killette2** [comment]
So we blame the baldman!

**Comment by MercuryDoll** [comment]
The icon doesn't make much sense, since this is supposed to be "radio" chat, not IRC. I doubt you could hear the difference between a cargo headset and the captain's headset. The only way these icons would be useful is identifying where the radiochatter comes from, which device emits it. So you'd probably always have your own headset icon displayed unless you can hear radio from the station comms or an emergency radio.

Likewise the job of the speaker displayed is unnecessary and unrealistic. It also only perpetuates people calling others "the scientist" etc instead of paying attention to names. It's QOL but at the moment they're just meta-knowledge It should look up the name on the station's personnel database and match the title if possible, instead of taking the one registered in the PDA/ID, that way OP's problem wouldn't have happened.

**Comment by 9600bauds** [comment]
I'm absolutely terrible with names so calling people "the scientist" is a blessing to me

**Comment by Killette2** [comment]
remove metagay

**Comment by PJB3005** [comment]
I guarantee you that a PR to remove it will have tons of controversy about
removing QoL.

**Comment by Killette2** [comment]
Yeah it is totally awesome to be able to call someone "cook" or "scientist". We got so used to it we're fucked if we want to remove it, but there did exist a time when we were fine without it too.

**Comment by PJB3005** [comment]
You just summed up all QoL features that are unbalanced but can't be
removed anymore due to drama.

Welcome to /vg/station enjoy your stay.

**Comment by Intigracy** [comment]
I do think the complaint about being able to tell which device they're speaking into is valid.

It should show what device is EMITTING the sound that is in earshot, not the device they're speaking into.

Basically all of them would be your headset.

**Comment by Killette2** [comment]
I like that idea too. The major thing is that this would still be a controversy due to how convenient it is vs how fair it is.

**Comment by DamianX** [comment]
the people have spoken
