### ISSUE TITLE
Fulltile windows don't prevent you from bumping into stuff, notably, shocked grilles

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9635]
To reproduce: Build shocked grille, then build fulltile window on top, marvel as you're shocked when you bump into that square.
Alternatively: Go to any of the many windows in the station that have shocked grilles under border windows under fulltile windows, break the border windows first (i.e. by throwing shit at it), walk into that square, be shocked.

**Comment by Probe1** [comment]
but thats my favorite trap card

**Comment by Intigracy** [comment]
Good luck fixing it.

**Comment by ghost** [comment]
Might be a problem with CanPass

You can't move onto the tile since it's dense, but the problem is that the grille is set to shock you before it checks if you can physically move on the tile, since you can't pass over a grille

Not sure if this can be handled at the window level with an override, or if grille code needs a check

You could also check window panes, which check it properly afaik
