### ISSUE TITLE
Your temperature rises extremely fast from hot environments, stabilizes itself at an extremely slow rate, thus guaranteed death from even one tiny whiff

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9649]
Open door to any kind of fire, any mild fire
You get ZAS'd, catch 5 seconds of the fire, and your temperature goes up to 150ºC
Now even if you run to a room temperature room, your temperature stabilizes itself so slowly that you have already died five times over from HAVING YOUR BLOOD OVER THE BOILING POINT
@DrCelt

**Comment by SkowronX** [comment]
That explains why I died so fast from 300ºC showers.

**Comment by ghost** [comment]
The best way to fix this is killing people whose body temperature reaches a certain point, but I doubt that'll be popular.

**Comment by 9600bauds** [comment]
We have different interpretations of "best", I think the best way here would be to make your temperature not go from normal to 150c in five seconds

**Comment by ghost** [comment]
Depends what the temperature of the room is, to be honest.

**Comment by MercuryDoll** [comment]
I wish my oven could grill a whole chicken in 5 seconds. Even if i set it to 250°C it'll take about 10 minutes before the inside is hot as well.

**Comment by Killette2** [comment]
Well if you want to play that game Mercury, you have to consider how long your brain cells are alive due to the heat. You can't survive a fire just as long as you're not medium rare, if your body temperature stays too high too long (IE when you're sick in real life) your brain cells aren't able to survive those temperatures.

On the other hand, we shouldn't retain heat for so damn long. It makes no sense.

**Comment by MercuryDoll** [comment]
My point was that bodytemperature changes way too fast. Flesh doesn't transfer heat (or cold) that fast, even if your skin is turning into a tan crust from 300°C blowing at you.
