### ISSUE TITLE
Blindness from welding without protecting is persisting through eye surgery/eye chems

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9702]
Toggling the BLIND block via player panel of someone who is still blind after eye surgery AND eye pills on and then off fixes this.

Possibly eye surgery and eye reagent just isn't handling this, probably a Deus Ex thing?

**Comment by aceedex** [comment]
Try ryetalin. I think that fixes it

**Comment by gbasood** [comment]
@aceedex literally says in the desc that it doesn't

**Comment by Shadowmech88** [comment]
Can confirm this still happens. Even after imidazoline took my eye damage down to 0 and the white/foggy overlay disappeared, the black blindness overlay stayed until I rejuvenated myself.
It's probably due to `Life()` code checking for whether your eyes are damaged enough to blind you, but not checking for whether your eyes are healthy enough to not be blind.

**Comment by Shadowmech88** [comment]
In further testing, ryetalyn instantly cured the black blindness overlay, though it did not cure the foggy eye damage overlay.
It seems the cure for welding-induced blindness is a cocktail of imidazoline and ryetalyn.
