### ISSUE TITLE
Should SCP-173 be cageable?

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9720]
Possible solution: have SCP-173 check if its loc is a cage and have it break the cage apart if so

**Comment by Exxion** [comment]
Our 173 is already much more powerful than it is in the source material so I guess we might as well go all the way

**Comment by Shadowmech88** [comment]
I think it should be.
It's adminbus-only, and I quite like it when players are able to use game mechanics to outfox an admin's god powers. Like when that one guy managed to decapitate the four horsemen despite them all being invulnerable test dummies.

**Comment by Exxion** [comment]
Also, the loc wouldn't be the cage if the cage's cover is open

**Comment by Probe1** [comment]
given that its a fuckin scp, yes, scp stands for SECURE CONTAIN PROTECT

**Comment by kol1th** [comment]
it should be yeah since it's literally impossible to get rid of

**Comment by mrpain666** [comment]
If I really wanted it out of the cage I'd just teleport it out anyways. Which I already do.

**Comment by gbasood** [comment]
> Also, the loc wouldn't be the cage if the cage's cover is open

For some reason even though it can move when the cover is open, it still gets moved back to the cage if the cage moves I think

Not sure on that though

**Comment by Exxion** [comment]
It's just locked to the cage when the cover is open
The loc is still the turf

**Comment by ghost** [comment]
It should be cageable, yes. Although I did have to draw the line for closets and crema/morgue trays because those allow you to instantly get rid of him

What matters more to me is that his sight code is fixed (still fucky with darkness) and that all manners of magically deleting him (shuttle, crematorium, supermatter) are patched out so that you actually have to CONTAIN him (it's impossible to destroy from the lore used here)

**Comment by Exxion** [comment]
muh source material

**Comment by ghost** [comment]
SCP-173 in general is fucky

Was testing with it on the thunderdome, it jumped into the vent and reappeared in the stations gateway room

**Comment by gbasood** [comment]
@skullyton Probably doesn't check for atmos connections, just unwelded vents on station
@dylanstrategie Sounds like SCP-173 shouldn't move if it's locked to an atom, might want to prevent that for chairs though

**Comment by mrpain666** [comment]
@dylanstrategie during an SCP bus round I did yesterday the crew ended up sharding one, it respawned a few minutes later, someone might have had to tweak something though.

**Comment by gbasood** [comment]
@mrpain666 Considering that the SCP still respawns on Del() probably not really

**Comment by NigglyWiggly** [comment]
@dylanstrategie 

> all manners of magically deleting him (shuttle, crematorium, supermatter) are patched out so that you actually have to CONTAIN him (it's impossible to destroy from the lore used here)

Are you saying that destroying it using supermatter is cheating or something because that's retarded and you know it.

And the SCP lore says nothing about it being indestructable, IIRC. It's just powerful enough to be potentially be useful for something and it's studyable, so they want to keep it contained instead of just destroyed

**Comment by ihadtoregisterforthis** [comment]
If you go full lore remember the blood and poop on the cell it stays contained.
And headcanon doesn't apply here.

**Comment by Exxion** [comment]
SCP lore says it's mundane cement and rebar, yes

**Comment by mrpain666** [comment]
Apparently borgs can butcher it, but it doesnt drop anything.

**Comment by ghost** [comment]
Shouldn't be butcherable at all, that was supposedly fixed a while ago

**Comment by clusterfack** [comment]
INVULNERABLE flag should prevent these kinds of things
