### ISSUE TITLE
AI Cores should be deconstructible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9742]
(WEB REPORT BY: swaggaboy112 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> eb018257ab73f7f02285c069899710cc1a2780d6 
> 
> General description of the issue

AI Cores are not deconstructible, both starting AI Cores and built ones. Transferring AIs does not make is possible either.

> What you expected to happen
> Used a screwdriver to start deconstructing an AI and take the MMI/posibrain
> 
> What actually happened
> Stabbed the AI
> 
> Steps to reproduce if possible
> Try to deconstruct an AI using steps in the wiki. Even transferring the starting AI to another built core does not make this possible. Admin tells me this is not possible. Please add this feature, I think it would make for some interesting things such as placing the AI in a human/IPC

**Comment by kol1th** [comment]
was it the roundstart AI, or a constructed AI?

> IPC

wrong server buddy

**Comment by ghost** [comment]
> was it the roundstart AI, or a constructed AI?

Roundstart AI, I tried deconstructing it, didn't work, made an empty AI Core (the black >_ screen), transferred the roundstart AI with an intellicard to the constructed Core, still couldn't deconstruct it
I haven't tried this with a 100% constructed AI (with an MMI/posi mid-round) yet, don't think it will work though (will try if I get the chance).

> wrong server buddy

Sorry got it mixed up lmao, since there are no IPCs I think that if roundstart AIs are made deconstructible they should yield an MMI.

**Comment by kol1th** [comment]
you can deconstruct AIs that you make post-roundstart. i don't really think deconstructing the original AI is a good idea because >malf

**Comment by gbasood** [comment]
> malf
> not shunting when someone fucks with your core to that extent

**Comment by Shadowmech88** [comment]
Whoever handles this issue should however make it so that a malf AI loses if its MMI is removed.

**Comment by ihadtoregisterforthis** [comment]
> hey AI let me in for a "routine reassembling", LAW 2

**Comment by Allspice** [comment]
Can already do this for milf if you're enough of a cocksucker, carding it will fail.
