### ISSUE TITLE
Cuban Pete bombs just aren't working out.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9766]
We've tried to make the machines harder to cheat but they have the fundamental issue of being based on arcade games and exploitable by experience.

Sorry Pete but free max cap bombs just aren't improving the game, except for the players that can reliably beat it.  Toxins and max dev is supposed to require some planning, understanding, restricted access, and experience.

Cuba Pete short circuits that and the station is inundated with easy to attain, extremely powerful bombs for the low cost of a one time emag purchase and an arcade.

What was meant to be a fun gag has turned into ProBmbFarm420.  Pull the bombs.

**Comment by 9600bauds** [comment]
I'm going to throw my two cents in here: I think it'd be a shame to get rid of Cuban Pete arcades because it's genuinely hilarious when an innocent clueless player gets gibbed by losing to them. THAT's the most redeeming feature about these.

But the bombs are just a shitty concept to begin with. They could easily be nerfed, but let's stop and think first: Should it be extremely hard to get them? Should it be risky? Should the bombs just be weak?
Being extremely hard would only serve as some sort of barrier, but it wouldn't stop anyone that already has learned how to get past it.
Being risky is iffy because if an antag gets gibbed trying to get muh bombs, well that didn't work out in favor of the round's interest, did it
And them being weak bombs is, at the same time, a shame because c'mon, it's Cuban Pete. Maybe if it gave TTVs and it's up to you to outbomb him?

**Comment by Probe1** [comment]
If you changed it from bombs to TTVs it'd be a panacea and cover us for another few months yeah.

**Comment by Intigracy** [comment]
Nah just give them a water/potass grenade that's max explosion size.

It's extremely small compared to a bomb.

**Comment by Shadowmech88** [comment]
I like the TTV idea.

**Comment by Iamgoofball** [comment]
hasn't it always been a TTV bomb mix? or do you mean making it just a 1v1 me ttv only, final destination, no tanks

**Comment by Shadowmech88** [comment]
No tanks, just the valve.

**Comment by ghost** [comment]
What if it gave bits of the bomb?

Could get a hot plasma tank, could get a cold oxygen tank, could get a TTV, could get a timer/signaller/prox sensor

> I've been farming Pete for 50 minutes now and all I've gotten is timers, signallers, and this worthless cold plasma tank

**Comment by Blithering** [comment]
How about grenades instead? Or have the arcade cabinet become a bomb on winning so they aren't farmable.

**Comment by 9600bauds** [comment]
Probably just one-tank bombs if we're nerfing the bomb to something tiny, but that's lame

**Comment by Intigracy** [comment]
Oh, deleting the arcade when you win sounds nice.

The bombs are still fuckhuge though and there's a way to reliably beat pete.

**Comment by 9600bauds** [comment]
???
How does that fix anything

**Comment by Probe1** [comment]
freebombs just don't work.  trading one bomb for another isn't gonna resolve it.

a TTV instead is an ok solution.  then you have to go to ghetto toxins and mix a bomb yourself.  that calls the intended method of getting a bomb.

**Comment by 9600bauds** [comment]
we can do more than an OK solution
we need an excellent solution

**Comment by gbasood** [comment]
I mean maybe we just
don't need Cuban Pete machines anymore?

Giving people access to bombs without being involved in the process of preparing hte bomb itself isn't the best idea
Honestly the biggest lost in my mind is that we lose the reference to Cuban Pete.

**Comment by Blithering** [comment]
Maybe have it as a spectacular exit scenario, winning the game causes the arcade itself to explode, with the time delay being some relation to your remaining health.

**Comment by Intigracy** [comment]
You could change it so it still spawns the hat (does it spawn maracas? it should), but gives a random traitor item instead of a bomb.

You still get a prize for winning, just not a station exploding monstrosity.

**Comment by Probe1** [comment]
we're just looping right back to the start.

arcade machines are not meant for high reward items.  they are meant to be high risk high reward but instead are high risk (if you're new) but normally low risk high reward.

**Comment by Blithering** [comment]
Maybe the hat and maracas are enough of a reward, the maracas are already emaggable to make some boom. Is it possible to have those spawn pre-emagged?

**Comment by 9600bauds** [comment]
>assistant finds emagged arcade
>plays it to win the maracas
>throws them at people
"I DIDN'T KNOW"

**Comment by ihadtoregisterforthis** [comment]
Change the game to something hard instead.

**Comment by 9600bauds** [comment]
I have my doubts about that, because then people that have practice in beating the game can still lolebincubanpete bomb roundstart

**Comment by ghost** [comment]
As I have already said, get rid of the bombs from Cuban Pete arcades and change it into RARE PEPE ITEMS like commemorative toxin clocks

If you want to change how the arcade works, disguise it as a normal arcade and have it gib the player if they try to play it but either fail or walk away

**Comment by gbasood** [comment]
I think keeping Cuban Pete as a game that gives bombs isn't something we should consider as an option anymore.
Any system we design will be too easy to win to keep around or too hard to make usable. Our players are really good at finding the easiest ways to blow shit up.

**Comment by 9600bauds** [comment]
Let's not get rid of the arcade gibbing people that lose, though. That's the one redeemable feature of this whole thing.

**Comment by MercuryDoll** [comment]
If you win, you get a box containing: 

> A valve
> a signaller, proxy sensor etc
> harmless maraccas and hat
> Cuban Pete's secret recipe for the perfect bombs (as in a paper with a guide on how to make max cap bombs)

This way it's not a free bomb, just the tools and guide to make one. Still a reward, in some way (especially for inexperienced bombmaker and greytiders), but not an instant shuttlecaller.

> I've been farming Pete for 50 minutes now and all I've gotten is timers, signallers, and this worthless cold plasma tank

Sounds like Warframe droptables.

**Comment by 9600bauds** [comment]
A paper that literally brings up the wiki guide for toxins when read

Brilliant

**Comment by 9600bauds** [comment]
Here's a fun idea: Make maracas work as an igniter that plays a short midi of Cuban Pete before activating
Make Cuban Pete arcade machines only give assemblies using maracas
Make the commemorative Toxins clock have a countdown timer that plays that midi at the end, for maximum false bomb scare

**Comment by clusterfack** [comment]
You guys should have taken my nerf for them while you had the chance

**Comment by 9600bauds** [comment]
Which one?

**Comment by Boxe** [comment]
the solution is to remove the bombcap so toxins is worthwhile :ok_hand:

**Comment by 9600bauds** [comment]
maybe if toxins was hard

**Comment by Boxe** [comment]
no bro who cares about that just remove bombcap

**Comment by Killette2** [comment]
How's these 2 cents

Winning a cuban pete gives you randomized rewards with better rewards with increased rarity, for example

50% the time, just hat and rackas
30% of the time C4
19% of the time a maxcap bomb
1% rumba beat virus culture (it's old, look it up if you don't know)

Also another fun thing, is if someone gets a bomb from the cuban pete arcade, it will emit a loud laughing noise or beat and chat message across the Z-level to alert people that it's habbening and to PANIC

**Comment by mrpain666** [comment]
Im just sick of the 5 minute bombings.

**Comment by Intigracy** [comment]
oh hey why not just give c4s those are explosive but not round enders

**Comment by mrpain666** [comment]
that could work, still a decent reward too

**Comment by 9600bauds** [comment]
then you're still giving away high-end items as a reward for buying emags which everyone does anyways
except they are very un-cuban

**Comment by clusterfack** [comment]
You guys should antag ban the people who make 5 minute bombs

**Comment by Shadowmech88** [comment]
5 minute bombing is a shitty thing to do, but dictating how our antags are allowed to antag is a slippery slope.

**Comment by clusterfack** [comment]
They are already disallowed from spawn camping or extending the round needlessly, ending the round immediately does not seem far from that in terms of dickishness.

**Comment by 9600bauds** [comment]
Didn't someone get shit for plasmaflooding roundstart every round they got antag, too?

**Comment by Shadowmech88** [comment]
Kaname Chidori, yes.
However I believe their antag ban was more because they'd go braindead/suicide every time they _weren't_ antag, not because they plasmaflooded every time they were.

**Comment by Shadowmech88** [comment]
@clusterfack 
Could always make a server vote. If the majority is in favor of making it a new rule, there'd be no reason not to.

**Comment by clusterfack** [comment]
I would support a vote on it, I have no privileges for such a thing however

**Comment by SangriaMonkey** [comment]
How often do you actually see bombs as opposed to faggoty minmaxing shit that makes the round drag on for fucking three hours longer than it should?

**Comment by 9600bauds** [comment]
every time Nevill gets antag

**Comment by AutismSpider** [comment]
He pete bombs or makes them in toxins

**Comment by Probe1** [comment]
@Shadowmech88 is correct.  Kaname had an issue where he would plasmaflood every single time he got antag regardless of objectives (which is fine).  Eventually, he'd just go braindead or suicide when he did not get antag.  That's really poor behavior and lowers the quality of the server as a whole

@SangriaMonkey like three nights ago I confiscated eight pete bombs from golems. Eight.  That's nearly twice as many as are intended to ever be in the round.

It's not limited to one player. Its an uncommon thing to observe an antag dragging an arcade to a pod for some private one on one time with Pete at the start of the shift.

**Comment by Killette2** [comment]
If my C4 suggestion isn't nice enough, how about this.

What if you could only globally get ONE bomb from the arcade per round?

First come first serve, but you can still make the arcade to trick greedy lootgrabbers into potential death.

This suggestion would solve every problem mentioned from the power creep of the emag to the amount of bombs in the round, while still keeping the sanctuary of cuban pete.

**Comment by mrpain666** [comment]
That's still one potential round ending bomb five minutes into the round.

**Comment by AutismSpider** [comment]
one is better then having 20

**Comment by Intigracy** [comment]
0 is better than having 1

**Comment by Probe1** [comment]
unless its a `return`

**Comment by Shadowmech88** [comment]
One max-cap bomb isn't even a round-ender anymore.
Especially considering the entire hole can now be patched with a single large metal foam grenade.

**Comment by ghost** [comment]
You're implying people can be bothered with hard work rather than resetting it all, like how it always goes down

Even then, if the only person who can call it is the CE and they insist on rebuilding, they'll get lynched by one angsty greytide who can't hang out in the bar because it's a crater now.

**Comment by AutismSpider** [comment]
@Shadowmech88 it is for most people here they have hard time fixing shit or god forbid setting up power

**Comment by Probe1** [comment]
There is a difference between hard, and futile.  We both know that difference DragonBro.

**Comment by 9600bauds** [comment]
Bombcap is too high for bombs to be feasibly fixable right now.
One step at a time, though.

**Comment by Intigracy** [comment]
Bombs can be feasibly fixed pretty easy, I'll show you later

**Comment by 9600bauds** [comment]
Not in practice, every bombing I've been in it was a roundender, even with MoMMIs and borgs and engineers actively fixing the screen-wide crater.

**Comment by AutismSpider** [comment]
@9600bauds are you joking? in the past me and engi borg have fix mass bombing as the engineers fuck off to space can be done people don't want do it soft as  babby butt or want reroll of antag

**Comment by 9600bauds** [comment]
I don't blame the players, and I don't blame the engineers, because the current bombcap is not feasibly fixable in the context of a round. Sure you can fix it if it's just you and the bomb, but it takes a significant amount of time to fix the plating, to fix Atmos, to fix the powernet, to re-build all the machinery. And during all that time the station just doesn't hold together, especially since the cloner is certainly gone and there's a whole chunk of people gibbed. And there are still antagonists going around.

It WOULD be feasible if bombcap was smaller, and I don't think bombs would miss out on anything from so, but one step at a time.

**Comment by Probe1** [comment]
It relies on team work.  Which is a toss up.

I have had beautiful "WE BUILD" rounds where the CE shows up at the site to find engineers and atmos techs already patching the breach and replacing the pipes respectively, the mechanic listens and starts churning out flatpacks and new machines, the MoMMIs and Engiborgs are working as fast as they can, the janitor is there picking up the debris so everyone can see the floor and work faster..

But it's very rare.  It's beautiful when it happens.

One of the things that make it rare is that when there are bombs, there is never just one bomb.  There are half a dozen.  

I can rebuild a department.  But I can't rebuild half a station in the time given (an ambiguous variable  that depends on the other players willingness to stay while you fix things.)

**Comment by ghost** [comment]
Can we special case a mega TTV that bypasses the cap and only one can generate per round rather than pete maxcaps? That would keep the theme and still require them to have the knowledge and put in the work either before or after where the AI and sec can catch on.

For the earlier talk about the one-tank bomb, I don't think the in-code item works until it gets a proper prefab like the syndiebomb but when you make one IC, they're a 1,2,4 IIRC. They're great for when you want to be a little shit and snipe the HoP at his desk, the brig desk guy, pop randoms that open containers, or in prox traps around the station while not being as obvious as a welderbomb. Plenty while not being round ending.

Maybe we could do along the lines of killette's and do a base drop of maraccas and hat with a chance of one - c4, nitroglycerin grenade, napalm EXgrenade in Lbeaker, bluespace, or Lbluespace size,LBuespace+Lstasis EMP ExGrenade, one-tank bomb, empty flamer and a plasma tank from a drop table of strenghts, empty TTV, rhumba beat culture.

We could also go about indirectly nerfing it by providing different hacked arcades. A medical one that would drop from a pool of unlabled pills consisting of various misc chems ala trail mix but more weighted to be useful if not just a new trail mix list, vials of blood which may have a random antibody, have infected blood, or clean. Rare chance of a proper disease culture vial. If people actually fucking listen for once it's not hard to nip diseases in the bud with a hit of manly dorf and so on until it goes into remission. It'll need an in-thread education infographic campaign most likely but it wont be that bad. 

Could do a monster jungle themed one where it has a warning that it spawns a hostile on victory. gimmick being kill some random mob then if you go get some laz injectors you can revive and ball it. Probably want to include slimes since they're durable little shits. Could also include a low chance of the NPC blob, carp/baby carp pack just to fuck shit up. 

For pure dilution sake you could probably include a ghetto weapon one, if you bring back the planting kudzu from seed packet action you can make it part of a botany themed dropping a small grab bag of potentially useful crops with weighted stats. Maybe a tray+bees in a box and a bee agitator item. Could make a mecha arcade where you can win a couple random parts and boards for an unauthorized mech only good for punching/clamping unless you can knick some guns while everyone is busy.

Bauds, repairs are entirely practical if you can get roughly 5 decent people to help instead of jacking off in their stolen hardsuits. It goes even faster if one of them is an eng borg or a mommi. You don't need all the wasted space on the station. Call out to rally your nerds and id the damage. You only need 1 guy to get all the machinery fixed up in 10 min then start cloning if rnd wasn't hit. another 5 if he needs to yank the mommi nest to do it. Send 1 guy off to glass off and airlock useless shit like a bombed brig, 3/4 of medbay and other crap. 2 guys work on getting shit airtight and slapping highcaps/supes in new apcs in the new dept-in-a-room camp. You can go from a 6-bombed station to a pressurized and cloning medbay in 20 minutes or less but you need people to step up or at least minimize the work instead of well time to reroll for antag. And while you shouldn't have to bust your own balls to do it, once everything settles down you or another superman can get the posi's, golems, and nymphs flowing to get the gibbed back into the show if nobody else can claim it.

Now that aluminum and metal foams adding a metal floor turf was merged so it's even faster to superman and with faster supermans we'll have an easier time roping fence sitters into the WEBUILD. Every guy that helps makes it go faster.

**Comment by Probe1** [comment]
@SarahJohnson489 all those ideas are good and feasible but it'd take some work.  Making multiple DANGER MODE arcades, all bundled under an ambiguous name like "Strange Arcade" may mitigate the effects somewhat.  

On the other hand, there's nothing stopping a player from disassembling non Pete ones.  Emags are unlimited in use and rebuild time on an arcade is minimal.

**Comment by ghost** [comment]
Think it's something people'd be interested in?

Edit: Eh, that's why I figure Kilette's got a good approach with making a drop table though intigracy making it hat and -1-1,5 maraccas is pretty good too. Could probably just split them and idea farm more danger mode arcades with their own theme reason against disassembly. Not that people can't just do the ol' locker of boards in the mining dock back room but who knows, maybe with some ideaguys and a more open mind people'd give it a whirl all presuming that whatever happens this is all ending with no more syndiebombs one way or another.

**Comment by Probe1** [comment]
Oh yeah it sounds terrific but I'm not coding all that shit.

**Comment by 9600bauds** [comment]
We need to stop rewarding emags

**Comment by ghost** [comment]
Honestly, we need more antagonistic things that aren't outright murderbone

**Comment by Killette2** [comment]
Emags are a good thing, because they aren't directly a weapon and allow more creativity for antagonizing.

As for the bomb issue, you don't really have to repair things like airflow pipes or disposals 100% of the time, those are a luxury since air can come in by doors opening or canisters. The only major thing that usually needs to be rebuilt besides the floor and some machines, is the wiring, and we have holomaps and t-ray scanners for that. There is nothing wrong with half-assing repairs as long as it's stable, but if you really believe bombs are still a problem (besides cuban pete bombs currently being unlimited), you can make a different formula for explosion calculation which requires more work for more destructive bombs, more equal to the damage they will be estimated to do.

You can't take bombing away from antags, but it is their decision on if they want to use bombs as bombs are part of ss13 and sometimes you need a reason to call the shuttle other than boredom. But again, that's all up to the antag on how they want to be creative for that round. I still think a 1 time global use bomb from the arcade (further completions do not reward a bomb, first win gets the only bomb) or a drop table with better rewards having increased rarity.

**Comment by SysadminJeroen** [comment]
@Killette2 I'm siding with your idea of only being able to get a bomb from the arcade once.
This requires those who can cheese it to gather the arcades from potentially dangerous places.
And having thee arcades in the same room might bring some heat from Sec.

**Comment by Shadowmech88** [comment]
I believe Killette's idea is that only one bomb can be won from all Cuban Pete arcades in the world _combined_. Such that even if you have three Cuban Pete machines, you can still only win one bomb that round.

**Comment by SysadminJeroen** [comment]
@Shadowmech88 To get one of the three arcades you need to enter the Captain's office. Which is very suspicious to haul an arcade out of or to try to cheese it.

Edit: Aren't there four arcades on Box (including Captain's)?

**Comment by SangriaMonkey** [comment]
I don't see why you should childproof the game over one dickhead's new gimmick.

**Comment by Shadowmech88** [comment]
@Jeroen52
You do know it's possible to _construct_ arcades from scratch using a circuit imprinter or even a soldering iron, right?

**Comment by SysadminJeroen** [comment]
@Shadowmech88 If that is so, maybe add a check if the circuitboard from the arcade exists since roundstart.

**Comment by Blithering** [comment]
Perhaps instead of directly nerfing the bomb reward, make successive wins from the Cuban Pete machine incrementally more difficult for each win? Have some kind of ticker counting the number of times Pete's been outbombed during the round and adding that number to his attack rolls or something would keep the reward as being worth the risk but at the same time discouraging farming.

**Comment by SangriaMonkey** [comment]
I think a system of diminishing returns would be better. As in you have a lower chance to win a bomb for each bomb won globally, to the point where it just isn't worth the hassle for another one.

**Comment by 9600bauds** [comment]
The problem is that the first bomb is already bad enough

**Comment by Killette2** [comment]
But bombs have always been a part of ss13, that's like saying the singulo does too much damage to the station.

**Comment by Shadowmech88** [comment]
A single bombcap bomb really is fixable.

**Comment by Probe1** [comment]
The problem is they're never singular, and cuban pete machines make acquisition easier than is enjoyable for everyone (except the bomber).

**Comment by Shadowmech88** [comment]
They _would_ be singular if we were to implement the proposed "one bomb from the arcade machines globally per round" solution.

**Comment by Killette2** [comment]
Or... what if cuban pete gave a bomb steroid item, used on transfer tank valves? Still 6 bombs a round, but maybe the bombs ignore bomb cap? This also means you need to beat it 6 times and not die to abuse it to it's full potential, WHILE having an amazing bomb mix.

**Comment by nuklearcellphoneg** [comment]
HEY GUYS

SINCE IT TAKES X AMOUNT OF TIME IN ORDER TO DEFEAT CUBAN PETE AND GET A REWARD(THE BOMB) WHY NOT MULTIPLY THE H.P. BY 2x or 5x or 10x??

WOULDN'T THAT INCREASE THE AMOUNT OF TIME IT TAKES TO PRODUCE A BOMB VIA CUBAN PETER BY 2x or 5x or 10x

**Comment by Killette2** [comment]
It would, but that's probably the laziest and unthoughtful solution there is aside from removing the bomb reward.

**Comment by nuklearcellphoneg** [comment]
There are three valves on-station: The reward for beating Pete should be the fact you got access to a fourth bomb, and also that you got a bomb without having to break in or otherwise steal one from toxins, and the fact that this wouldn't leave evidence that someone got a bomb from toxins. 

Also, I believe Sarah Johnson has the right idea about the just git gud suggestion, as well as adding in some metal foam grenades to maps.

**Comment by Shadowmech88** [comment]
> three valves on-station

When's the last time you actually played a round, Nuke?
There are six tank transfer valves in Toxins at round start.

**Comment by Probe1** [comment]
He gets up believe it or not.  But all admins have gaps in their knowledge.

I don't know a fucking thing about xenobio.  I've never played chaplain.

**Comment by Boxe** [comment]
>he doesn't know how to do every single job

**Comment by AutismSpider** [comment]
6 on meta and box

7 to 8 on deff due to random spawns on that map

**Comment by nuklearcellphoneg** [comment]
Six
Fucking
Valves
Why? Here, just switch it to where, upon beating Cuban Pete, the arcade itself explodes like a max cap bomb

**Comment by AutismSpider** [comment]
@nuklearcellphoneg Not like you need all six. Three is all it takes to do real damage to box and meta

**Comment by Boxe** [comment]
>Why? Here, just switch it to where, upon beating Cuban Pete, the arcade itself explodes like a max cap bomb

non antag fuckery famalam

:eggplant:
