### ISSUE TITLE
There is no way to obtain a destination tagger if/when the original is destroyed or lost

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9816]
Makes it super impossible to do mailing if things get blown up

**Comment by uazuaz** [comment]
this issue it's been fixed by https://github.com/d3athrow/vgstation13/issues/12177 but i'd like to discuss about it.
now that the tagger can be printed on the autolathe and everyone has access to it, it could happen that science prints a tagger, use the package wrap that they already have inside RnD and send stuff anywhere bypassing cargo.
i don't really like this and i think that mailing stuff should be leaved to cargo, so in my opinion it could be done this way:
- remove the tagger from the autolathe
- make the tagger buyable on cargo and let it cost little, for example 10 credits
- put 2 destination taggers inside delivery office + 1 another tagger inside QM's closet on every maps
- (maybe you could also add this https://github.com/d3athrow/vgstation13/issues/8186 )

 this way every cargo member will have his tagger and easily buy other taggers if needed.

(side note: few people know how disposal mailing system actually works, i made this guide time ago and i think it could be useful if added ingame https://github.com/d3athrow/vgstation13/issues/6800 )

**Comment by 9600bauds** [comment]
The conveyor belt inside Cargo needs to be left on to let Science mail shit anyways

**Comment by Zth--** [comment]
@Uazuaz that wouldn't fix anything because science can still print the cargo teleporters/telepads. Actually I don't see it as a problem since science don't have crates to deliver. They have printable things to deliver, yes, but even then science will deliver them themselves
