### ISSUE TITLE
Changeling Death Sting is Too Powerful

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#9891]
I just personally feel that a weapon that is an instant knockout, guaranteed one-shot-kill, that is completely undetectable until use, and can't be stripped or disarmed is a bit too strong. Especially since changelings can already paralyze and silence people in the same manner.
Previously when the sting was lexorin it was still a fast death, but at least you could fight back or call for help or do literally anything before it killed you.

I don't think I'm alone in this.

**Comment by ghost** [comment]
Somebody changed it from lexorin (Slow but guaranteed death, as the recipient can't breath) to CYANIDE (Brain damage, instant knockout, toxin damage will kill you before you even have a chance to oxyloss, best hope you had buddies with you to recover your corpse, as it's guaranteed death)

#8356

**Comment by Probe1** [comment]
Changeling is by far the shittiest game mode and that has fierce competition.

**Comment by Killette2** [comment]
I dunno mate. Death sting can be directly countered by antitoxin, as it will metabolize the antitoxin along with the cyanide to prevent it from happening (means a bit of powergaming, but dex+ meant you could not be affected by the lexorin)

On the other hand, it also has a high chem cost and high genome cost where a changeling could better spend their chemicals, and doesn't really work too well in group situations as it outs you instantly when captured by multiple people (where people should be in multiples of at least 3 in changeling rounds once it's confirmed).

Think about it this way, if your victim can shout "X IS A CHANGELING HELP ME!" before use, then it's not too great of an ability on it's own for 10 genomes is it? Yes it can be combined with silence sting, but that also requires silence sting, possibly over 50 chems? Not sure on that one, but the point being is that combos cost extra. Just like parapen c4, it's complete bullshit, but it's a combination of things.

The reason it's hard to counter, is because it's a stealth attack weapon, like most non-loud traitor items. Will it be fair? No, of course not. Someone is trying to stealthily kill you, if you can counter and survive it, then their cover is completely blown.

**Comment by 9600bauds** [comment]
The way I understand it, the guy that changed it from lexorin to cyanide didn't know cyanide put you to sleep like chloral and the idea was to prevent dexalin powergaming
I think the best solution here would be to just use another poison that doesn't get countered by chemicals and doesn't instantly put you to sleep

**Comment by Killette2** [comment]
alpha amanitoxin finally has a use!

Or make a new chem, whatever floats your boat.

**Comment by ComicIronic** [comment]
Do not make a new chem

**Comment by Killette2** [comment]
What chem currently would fit the purpose of death sting, without having an anti-metabolizing reagent?

**Comment by 9600bauds** [comment]
What's the problem with a new chem
We're not redoing the entire chemistry system anytime soon or ever

**Comment by Killette2** [comment]
Also, let me mention this.

It's DEATH sting. I don't think surviving it is intentional, and maybe it should be who knows, but also remember this.

Vampires get fucking DEATH HUG.
You can't say HE HUGGED ME 1 MINUTE AGO HE'S A VAMPIRE, that's a bannu.

Vampires also get this death hug way earlier on than any changeling could ever get death sting.

**Comment by Hoshi-chan** [comment]
Changing death sting is treating the symptom, not the cause.

**Comment by Killette2** [comment]
What if we tried non-antag changelings as an experiment to fix this? They still retain all of their abilities, and this worked for vox.

**Comment by Imagebard** [comment]
@Killette2 But Vampires aren't balanced, why are you bringing them up as a example?

**Comment by Killette2** [comment]
@Imagebard Because both death sting and death hug/touch are certain doom abilities that are very hard to counter in a similar fashion.

**Comment by Imagebard** [comment]
Well, two wrongs don't make a right.

**Comment by Killette2** [comment]
I think the real question is as mentioned before. How do we change changeling to not be either thousands dead or nothing happens - the round. Them being non-human really should be setting them apart, but really the only 'cool' ability they get is HULK FORM and turn into monkey to escape. That's all, rest is weird inject chemical X, and be stronger buff. Where's the head crab? Where's more interesting alien shit? Changeling was blandly thought of, where if you're outed, due to silicon's presence you're not likely to survive. With vampire, they at least have the mercy of jaunting to go with their name changes to avoid lockdowns, but with the ventcrawl changes monkey mode doesn't hold up well for lings and are less likely to escape a locked down area due to their cover being blown.

**Comment by icantthinkofanameritenow** [comment]
As the guy who made the change to death sting in the first place, I did it because Lexorin was anything but lethal; when the "death" sting can be countered by one of the dozens of oxygen deprivation medkits present in the station at any given time, it's little more than a waste of evolution points. That said, I'd be fine if it was replaced with another poison that was just as lethal as cyanide but didn't make people sleep. It's "DEATH" sting. It's supposed to be lethal. (Or just make cyanide not put you to sleep, it's lethal enough without ripping off chloral hydrate's thing.)

While I did try to port over arm blades from TG, I gave up after realizing that I had no clue how to port things. I suggest someone else try it, though. Lings need something to go loud with that isn't Horror Form. And while you're at it, sucking off monkeymen for genomes REALLY needs to stop being a thing. Like, fucking now. That alone would fix a ton of issues with changelings, and with vampires as well.

**Comment by 9600bauds** [comment]
I feel like it's about time to revisit this. All that needs to be done is make death sting not Instantly Sleep™

**Comment by icantthinkofanameritenow** [comment]
My suggestion is to remove the ability of cyanide to put people to sleep. It'll retain its lethality, but it'll still give the victim a chance to get help.

**Comment by 9600bauds** [comment]
That shits on botany and newcops though

**Comment by Killette2** [comment]
More changeling abilities? We have blade arms, now we need retractable wings. Fly over tables to evade sec, be the insectoid monster you were born to be!

**Comment by Sprok0** [comment]
Another problem is that you can get death sting after only two succs at roundstart, at which point any further number of genomes becomes trivial. Even the vampire's disease touch actually spends some of their blood resource, the changeling version just recharges

**Comment by Shadowmech88** [comment]
Just give changelings a new chemical that's a special version of cyanide that functions identically aside from making the victim sleep.

**Comment by Allspice** [comment]
we have that chem with cheesy gloop now for what it's worth

**Comment by Shadowmech88** [comment]
@Probe1 
Has the death sting been changed since this was made?

**Comment by Probe1** [comment]
Cyanide and chloral got reworked.  I was closing issues based on usefulness.  No ones reading discussions from 2016 and if they want to it still exists.
