### ISSUE TITLE
10 min wiz rounds

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9918]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue

wizard fireballs himself 75% of the time or dies in 10 mins

> What you expected to happen
> when wizard dies the round continues (autotraitor or stuff)
> 
> What actually happened
> 10 min rounds
> 
> Steps to reproduce if possible
> roll wizard
> buy fireball
> get toolboxed to death

**Comment by kol1th** [comment]
FRIENDLY WIZARDS!

**Comment by Hoshi-chan** [comment]
Why not just treat Wizard like a more tame Ragin Mages? Only one wizard at a time, with a new wizard spawning from 1 to 15 minutes after the previous wizard's death. If no one is available to be a wizzyman, turn it into extended or autotraitor or something.

Just... no more "round ends on wizzyman death". It encourages people to validhunt in order to bring an end to the round, as well as sloppy wizman play since there's zero reason to value your own life since the round is going to end once you die.

**Comment by Probe1** [comment]
I agree.  In fact I agree so much that I will cha..
oh wait antag datums are being refactored and are off limits.

REEEEEEEEEEEEEEEEEE

**Comment by Shadowmech88** [comment]
ANTAG DATUMS DONE

W
H
E
N

**Comment by mrpain666** [comment]
Git fucking gud

**Comment by Exxion** [comment]
Wizard rounds no longer end on wizard death.
