### ISSUE TITLE
Ambrosia C potency issue

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9947]
Amborosia C is a plant who's potency you do NOT want to raise!

Why is this? Because it was shittily coded, and if you don't know, it is the traitor botanist item that produces spirit breaker.

Why do you not want to raise the potency of this item? Because no matter how high the potency, both the nutriment and the spiritbreaker stay at 1 and 10 respectively while every other chemical raises in the amounts. The fix for this bug would to at minimum, allow more spiritbreaker for higher potency ambrosia C.

**Comment by Hoshi-chan** [comment]
But then you could extract the high potency of an exotic seed via xenobotany, get your traitor seeds, splice it in, and grind one branch of it for 100u of spiritbreaker.

I'm no botany expert, but that seems just a bit imbalanced, since the only way to counteract spiritbreaker is to clone the person.

**Comment by Killette2** [comment]
> Needing to splice xenobotany potency

I don't think you've touched robust harvest in a while friend... leave the botany knowledge to me. Getting 100 potency without mutagen in 5 minutes is easy.

The issue though, with the capped spiritbreaker, is eventually the other chemicals will lower the spiritbreaker due to the average so it's best to leave the spiritbreaker plant alone rather than do further work on it, aside from splice it into everything in existence.
