### ISSUE TITLE
small vox outpost qol addition

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9951]
(WEB REPORT BY: durgen REMOTE: 172.93.109.202:7777)
it would nice to have a multitool at the vox outpost. 
this would allow for easier hacing of the vending machines (traders have no access to them)

**Comment by uazuaz** [comment]
you can build an autolathe and print a multitool.
to make the autolathe you can disassemble the smartfridge and borrow his components.

**Comment by PJB3005** [comment]
Better idea: Remove the access restriction.

**Comment by Probe1** [comment]
Best idea: Subtype it with different butt similar inventory and no access restriction.

**Comment by Durgen** [comment]
> Best idea: Subtype it with different butt similar inventory and no access restriction.

I believe that is what was done on the deff outpost

**Comment by Durgen** [comment]
also, metaclub could use this addition to the genetic testing lab vending machines as well.

edit: 
while we are on the subject of qol additions to the metaclub outpost, the genetics station could use some plasma and a grinder.
Last round a cultist accidentally chickened himself in front of me, and I was unable to clone and torture him effectively due to a lack of these items.

**Comment by beesil** [comment]
Fixed in #10502
