### ISSUE TITLE
Genetics.  Why is it fucked and how can we fix it?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9992]
Genetics is boring af and hugely dependent on RNG.  The wiki is so out of date that it does more harm than good.  There are a few rare players that are very good at it but even then I don't often hear people praise the job.  

First thing that comes to mind is to double the effectiveness of upgrades.  So injectors can be made every 3 seconds.  Second thing is to increase an injectors chance of working.  That causes a ton of confusion for players.

But really, the core issue here is the RNG related to the job.  RNG is ok if you have ways to get around it.  If you're skillful at the job you can mitigate some or most of it.  But with genetics, except for these rare few, players get dicked by RNG a lot.  

Anyone have any ideas?  
(Yes, porting goon genetics would be great but thats a huge ask and I don't see anyone willing)

**Comment by PJB3005** [comment]
Here's what we need to do.

Merge science and medbay into medsci.

Merge viro, genetics and xenobio.

**Comment by Killette2** [comment]
> Merge RNG, RNG, and RNG

ok but why?

**Comment by Probe1** [comment]
Here's a straightforward one.  For upgraded machines, injectors have 1, 2, or 3 uses depending on their upgrade level instead of just a flat 1.

**Comment by PJB3005** [comment]
@Killette2 I ment completely rework them all into 1, different, job.

**Comment by Killette2** [comment]
That sounds like hell PJB, they're all major jobs on their own.

**Comment by Kurfursten** [comment]
I toyed with an idea a few months back. Do away with the DNA modifier - you instead have a DNA bank and a DNA sampler tool. You gain research points for
- Submitting a DNA sample from a new person you haven't sampled before
- Extra research points for each power or disability the person has
- Extra research points if the person was a changeling

Additionally, _cloning causes much more SE scrambling, so there are more powers and disabilities for people who are cloned_.

This has a few benefits
- Incentivizes geneticists to do their job rather than ignore the cloner
- Increases the importance of genetics during changeling
- Encourages interaction with the crew, going around to check up on people for basic DNA samples

Once you have research points, you can spend those on unlocking powers, disabilities, primitive, etc.. After a power is researched you can create a syringe for that - plasmid style - with some production cost. Maybe biomass or plasma or something.

Ryetalyn also becomes slightly more important because no DNA modifier to remove defects.

**Comment by Probe1** [comment]
That _sounds_ great but we don't have people lining up to rebuild genetics from the ground up and implement Genetics3.  I'm thinking more short term bandaid fix what we have ideas.  

Like take injectors for example.  A 30% chance for a power to manifest?  After you spent over an hour just finding these powers?  It's RNG on top of RNG and neither case is compelling or interesting.  We could swap the chance of failure with the chance of success and deliver a less frustrating, grindy job.  

There's little chance to interact with the crew when you have to spam injectors all day and getting a box full takes minutes.  None of which are guaranteed to proc all their powers.  

A fancier way would be to retain the (not really good but) system and change block injectors to work 100% of the time so you can guarantee a power or maybe get a bunch of powers.

All and all I know the problem with genetics.  It's the foundation in RNG.  And I know the solution.  Replace or erase the RNG with gameplay.  Studying the crews genetics and having a genetic bank with researchy type stuff sounds terrific (as long as you account for monkey-men so it isn't cheesed) but I don't see anyone saying they'll code it.

**Comment by ComicIronic** [comment]
What's goon genetics like?

**Comment by Probe1** [comment]
Much better than ours.

You get genetic trait A (bad gas)
You mix it with genetic trait B. (appetite)
It becomes genetic power C. (Superfart)

I can't really say in depth

**Comment by PJB3005** [comment]
Alright let me explain goon genetics properly.

The way goon genetics works is that every person has a list of deactivated powers they have. You can't know what a power is until you've researched it.

To activate a power, you need to do a very simple puzzle.

I mentioned research earlier. Your DNA machinery starts out really crappily. You upgrade it with time and materials. Materials generate over time and can be bought, among some other methods to get them. 

You can splice and merge powers to create new powers (for better or worse), and there's a TON of powers.

The dormant genes inside a person can be activated if genetics cares about you, without penalty and extra tech requirement. However, to give somebody new powers requires injectors, which are slow to make and costly. But that's not the worst because non-native powers destabilize your genes, and if you have too much powers your skin literally oozes off and you slowly fall apart.

**Comment by Brolaire** [comment]
The issue is that irradiating blocks randomly scrambles the DNA way too often, meaning the more you do, the higher are your chances of losing everything including your will to continue your job and your will to live.
Remove the random scrambling and you get an okay job, a bit on the boring side but atleast newbies dont wanna kill themselves ten minutes into research and chill

**Comment by Probe1** [comment]
It's a 20% chance but it's a 20% chance every time you press dat button.  Which is a lot.

There's ways to mitigate it though.  Blocks 1-26 it will scramble the block above it.  Blocks 26-55 it will scramble the block below it.  So just work upwards till you get half way and then work downwards.

Either way I kinda just test for powers on myself and ignore how fucked the monkey is, I just use my own genes as the SE for powers.

**Comment by Brolaire** [comment]
See? That's what I meant, I didn't even know it's specifically like that, to me it looked completely random.

What if there's a small pool of powers you can get each round, like three positives, five negatives and two neutrals, but they're way harder to unlock? Replace pressing buttons with a simple puzzle like Mastermind (guess the five-digit number/color combination in X tries) or maybe require splicing of different species DNA (Splice Grey and Goliath for telekinesis or basilisk and human for Cryokinesis?) ? This would mean that Genetics actually need to run around the station and asteroid for gene samples PLUS if they get a puzzle it's more mind over bruteforcing numbered blocks.

Anyways WYCI
