### ISSUE TITLE
Borgs are able to run around and fuck with people even after removing their power cells

### ISSUE THREAD

**Issue by mikecari** [d3athrow/vgstation13#9994]
Especially on modes where borgs get commonly subverted and are extremely dangerous, this is a major issue as it gets rid of yet again another borg weakness, making them even more of an unbalanced role that people resent and despise. 

I realize this isn't a bug and was implemented so butthurt borgs without cells could move around, but it is extremely detrimental when you flash a borg, remove its cell, and it gets up and starts fucking with you even in death.

**Comment by Killette2** [comment]
We are a pro-chicken server, and chickens can run around without heads explaining the reasoning behind this.

**Comment by mikecari** [comment]
My aunt is a chicken, you damn dirty racist.

**Comment by 9600bauds** [comment]
I'm fine with borgs being able to move to a charging station if they run out of power but goddamn, not at full speed
Maybe not if their cell is GONE rather than empty

**Comment by Ephx1** [comment]
How about this:
If no battery/power but intact they can speak via MMI/Posibrain, that at least alleviates some of the absolute pain being without power is. Then you can remove their movement.

**Comment by mikecari** [comment]
@Ephx1 
Yeah that sounds like a good compromise.

**Comment by Killette2** [comment]
As long as the speech is local unless the MMI is radio enabled, then it's fair.

**Comment by ComicIronic** [comment]
No that's terrible.
Having spent an hour-long round as a MMI after bats got me in the MoMMI cave, being both unable to move and unable to radio-chat is the worst possible experience. Battery-busted borgs get one or the other.

**Comment by Killette2** [comment]
I can see it as a special hell for MoMMI's since they can't ask to be put in a better MMI holder in case of emergencies, what do you suggest, MoMMIs start out with radio enabled MMIs?

**Comment by Kitfox88** [comment]
All MMI should be radio MMI because if you ghost you can't go back when recovered

**Comment by Killette2** [comment]
Why is ghosting relevant to it at all? Just don't ghost, or enable re-entering as a MMI.

**Comment by Kitfox88** [comment]
Because if you're dead at least you can fucking deadchat while waiting for someone to clone you. MMIs just sit there, and if you ghost blam game over man, you can't go back in. At least that's how it was last time this sort of issue came up :open_hands:

**Comment by 9600bauds** [comment]
In most cases I personally consider deadchat to be a negative

**Comment by Killette2** [comment]
deadchat is OOC+, where you have the ability to be extra creepy because you affect less people.

**Comment by mikecari** [comment]
I think I remember once having a "last stand" moment on the research station as a traitor. I was actually succeeding in driving back the sec guys raiding the place, and carefully making sure to retreat as to divide them up for easy pickings. I even disabled the sec borg that was helping them and removed its cell. It ended up fucking me when it blocked my only escape route and the sec guys quickly got into a shootout with me with a 5:1 numbers advantage.

**Comment by Hoshi-chan** [comment]
Radio-enabled MMIs by default would enable all sorts of shittery. pAIs having radios is already bad enough since it makes their master murder-proof (who gave that back to them again?).

Maybe allow for re-entering your corpse as a ghost while inside of an MMI, to alleviate the suffering of being inside the cyborg recharging station off the AI core when somebody blows you. Or what if occupied MMIs showed up on the crew monitoring computer the way that posibrains do?

In any case, allowing a borg's MMI to speak, ostensibly free of the influence of its laws, when the battery has been removed, is a TERRIBLE idea. Imagine the malf round where someone flashes a borg, removes its cell, and asks the MMI inside if the AI is malf or not. Also, borgs can't "fuck you over" with their cell removed. They can move. If you've already flashed or disabled the borg, removing the cell doesn't suddenly restore their ability to move, which is what you're making it sound like, and if it does, then THAT'S a bug. You have as long as the flash lasts to remove their brain, lock them down, blow them, or beat them to death with a fire extinguisher. Two flashes is enough time to beat a borg until it shuts down with whatever's at hand.

Killing or disabling borgs isn't hard. I've died PLENTY of times as a borg, for all sorts of reasons, and unlike humans, you can't jam them into cryo or a cloner to fix them, you have to depend upon someone else understanding the finicky and arcane repair procedures. If Robot Man, Yred, or myself aren't working robotics, you're basically fucked. Oh, and hey, if you were malf or subverted, or just pissed somebody off, then nobody's gonna bother, even if they do know how.

Also, if borgs blocking the path are a problem, just change it so that they're always on "help" intent with their battery removed, so they can't obstruct your path. That seems reasonable. Lowering their movespeed with their cell removed seems equally reasonable. Making them unable to move, see, or utilize their radio, but retaining their ability to speak MIGHT be okay, but it introduces balance issues.

In any case, considering all of that, if removing the power cell is to COMPLETELY disable borgs, the go-to means of countering borgs is going to become flash, swipe, crowbar, remove cell, and the borg is dead. At least the way it is now, you have to actually put the time and effort in to KILL the borg once it's immobilized by a flash (or, pretty soon, flashbangs).

**Comment by Ephx1** [comment]
> Or what if occupied MMIs showed up on the crew monitoring computer the way that posibrains do?

Already a thing

> Imagine the malf round where someone flashes a borg, removes its cell, and asks the MMI inside if the AI is malf or not

Imagine the round where they do that but the AI isn't malf. Or they could just do what you said was so easy, and remove their MMI, it seems like you don't even need this feature to do that already.
Oh and silicons aren't going to pass up murdering people, so even then their MMI isn't going to say shit.

> you have to depend upon someone else understanding the finicky and arcane repair procedures. If Robot Man, Yred, or myself aren't working robotics, you're basically fucked

Nearly every roboticist now knows how to do this, you and your buttbuddies aren't special.

And last I checked, Borgs become invincible once their battery popped out, oh and guess what? Your battery is probably going to pop out before you die!

**Comment by AlphaBuffalo** [comment]
How about if the cell is removed from any Borg and mommi they can't move, but they can talk in binary after a short delay so the emergency backup battery can kick in (just a fake device to keep continuity) so if the person who removed the battery from the Borg gets caught, and no one saves the Borg, he can at least yell on binary. But if the cell is in the Borg and the cell is dead, it can move but can't talk.

**Comment by MercuryDoll** [comment]
> finicky and arcane repair procedures

You mean prying out the MMI, salvaging the robot parts and making a new cyborg chassis? Gee, that sure sounds a lot harder than cloning. Oh wait, the MMI popped free, might as well ask it if the AI is malf while waiting on the fabricator because lolnolaws.

> flash, swipe, crowbar, remove cell, and the borg is dead
> you have to actually put the time and effort in to KILL the borg once it's immobilized by a flash

Surely there's no way to disable and kill a carbon just as quickly. Oh wait, we have chloral-hydrate.

Real talk:
I'd say if the battery of a borg is dead or completely gone, make them unable to move because yes, an electronic device without power is a dead brick, but it's not "dead"-dead, because you can simply recharge/replace the battery and they'll be "at full health" again like nothing happened because it didn't actually damage them.

We need to overhaul the whole system anyway. 
- Roundstart borgs should spawn with a posibrain, not an MMI. 
- Posibrains and MMIs should come with a way to have their laws persist post-cyborg, eg. an MMI that's been removed from a malf/subverted cyborg will still retain their laws until they are purged. 
- Freshly created borgs should come unlinked from the AI per standart, Cyborg bodies need a way to have their laws picked/modified either before or immediately after putting in the brain. If you want a failsafe, let it auto-pick Asimov when no choice has been made after x seconds.

If you want to remove the ability of MMIs and Posibrains to talk, give them some sort of distress-beacon that makes them pulse glow, make a distinct noise and/or alarm the Roboticist/Scientists' PDA so they can potentially be found when they got blown in maint or eaten by carps at arrivals.

**Comment by aceedex** [comment]
Maybe borgs are fine as is. Maybe borgs without cells should simply lose vision. Maybe if you get dicked by a blind thing you suck

**Comment by Hoshi-chan** [comment]
By finicky and arcane repair procedures, I was referring to replacing damaged parts and then needing to repair the damage that still remains on the new parts which persists from the old broken ones. Like replacing armor plating, then having to weld the damage on it, because installing new parts and then needing to repair the new parts sure does make a lot of sense.

Don't act like everyone knows how to do it now. Some people know how to remove MMIs, but many still don't know how to deal with the shitty repair system. It's bad. Replacing a part should repair all damage to the replaced part, because it's a new goddamn part.

As for cells, I still think restricting vision and slowing them down, but leaving their de-powered state as-is would be fine.

What @MercuryDoll is suggesting for a general overhaul of cyborg bodies and roundstart borgs also sounds neat.

**Comment by Allspice** [comment]
> And last I checked, Borgs become invincible once their battery popped out
Oh right, minor tangent: I think borgs become invincible when every component is removed from them, not when their cell alone is removed. Nothing to do damage to or some such.

**Comment by MercuryDoll** [comment]
Yeah, the repair system was broken since i remember starting playing in 2013, which is probably why rarely people bothered to replace parts and just salvaged the chassis and build a new one for the borg.
